### ISSUE TITLE
Storage: occasional StatusCode=403

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-sdk-for-go#1005]
We are seeing these errors occasionally:

```
Error reading blob [blob_name] 
StatusCode=403, 
ErrorCode=AuthenticationFailed, 
ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

We only see this when:

- we use channels to run things in parallel;
- we see this randomly sometimes.

We never seen this when things are completely serial.

I am wondering if there is some kind of race in storage SDK?  I know we had issues with SDK when we used pointeres (e.g. `*storage.Blob`) -- there definitely seems to be some shared state in the SDK.

Or is it a general Azure Storage known issue?

PS: we are using storage keys, not SAS, if that matters.

**Comment by jhendrixMSFT** [comment]
It is likely a race condition in the SDK.  What API(s) are you using in parallel?  I would also like to point out that we're deprecating the blob storage functionality in this package, it will be replaced with the azblob package here https://github.com/azure/azure-storage-blob-go.

**Comment by ppanyukov** [comment]
I think in this case we use these calls in parallel.

```
// Simplified code
blobRef := w.container.GetBlobReference(blobPath)
blobRef.Get(nil)
ioutil.ReadAll(reader)
```

To be fair, we see these failures so rarely that we can live with them.

Don't know if it's worth fixing in this package since you are moving to new implementation?

@jhendrixMSFT I saw previous attempts at splitting out storage part into separate repo, how real is the deprecation this time?  Also haven't seen anything mentioned in the docs about this -- is the new repo production. Some pointers around this would be nice!

**Comment by jhendrixMSFT** [comment]
@ppanyukov Sorry for the delay.  I've been over these APIs and I haven't been able to see what could be causing the race.  Are there any other blob/container APIs in play here?  Sounds like it isn't a blocking issue for you so we can leave it be for now.
Regarding your question, the splitting out was a different effort; the new azblob package is owned by the Azure storage team.  We did update our doc with some info about it for our v14 release in February. 
 CC @seguler who works on the storage team.

**Comment by ppanyukov** [comment]
thanks @jhendrixMSFT , just one API for us. So it's a bit weird.  I must say it's *really* rare when it happens. I probably saw this maybe three times in total.  Could be bug in our code too :) 

Feel free to close.

We will look to using new API for new projects.
