### ISSUE TITLE
azure blob etag unqouted

### ISSUE THREAD

**Issue by meirf** [Azure/azure-sdk-for-go#1007]
Using `curl` against http://MY_ACCOUNT.blob.core.cloudapi.de/MY_CONTAINER/MY_PATH gives  header:

> ETag: 0x8C564F739B6442A

I thought [Etags need to be quoted][1].

  [1]: https://stackoverflow.com/questions/6719214/syntax-for-etag

**Comment by jhendrixMSFT** [comment]
@seguler any ideas?

**Comment by meirf** [comment]
any chance this is a bug and not just a question?
looks like other folks are getting theirs quoted - https://stackoverflow.com/a/48515021/1168364

**Comment by jhendrixMSFT** [comment]
If it is a bug it's not with the SDK but with the service itself (i.e. the service will need to be fixed).

**Comment by meirf** [comment]
That's fair. (Sorry, forgot which context this question was in.)

**Comment by jhendrixMSFT** [comment]
Ping @seguler

**Comment by seguler** [comment]
What is the REST API version where you see this behavior ? I am unable to repro the issue.

**Comment by marstr** [comment]
Closing as stale. Feel free to re-open.
