### ISSUE TITLE
Client avoidance of duplicate names produces duplicate files

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1023]
After this PR : https://github.com/Azure/autorest.go/commit/3458098afd88db38c357921cbd964aa72685a61d  

there is an unexpected behavior in the generation for example: ` azure-rest-api-specs\specification\automation `

It results in creating duplicate files with the same content the only difference is that one has the extra `Group` suffix.  ( **runbookdraft.go**, **runbookdraftgroup.go** )
 
As a side effect the build failures because teh future names are getting updated to include the `Group` part although they are referenced in the **runbookdraft** files .

```
.\runbookdraft.go:49:158: undefined: RunbookDraftCreateOrUpdateFuture
.\runbookdraft.go:96:82: undefined: RunbookDraftCreateOrUpdateFuture
.\runbookdraft.go:270:121: undefined: RunbookDraftPublishFuture
.\runbookdraft.go:316:75: undefined: RunbookDraftPublishFuture
```

**Comment by jhendrixMSFT** [comment]
Hmm it appears this is actually due to the following commit.
https://github.com/Azure/azure-rest-api-specs/commit/635c47960acb6787ebf2c4e1be6f8adc1a8d4256#diff-2849af3f8c6c51873d5b7924822a5074
When I remove the batch section the bug goes away.
