### ISSUE TITLE
Storage container doesn't include access

### ISSUE THREAD

**Issue by petitout** [Azure/azure-sdk-for-go#1040]
Hi,
the API to get storage container properties returns the container access (private, blob, container) : https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-properties

However the sdk doesn't return this information : https://github.com/Azure/azure-sdk-for-go/blob/a75e7321dcb5045edbbdba24b594d8f3f1b31352/storage/container.go#L97

Is it possible to add the access in the ContainerProperties struct ?

Thanks

**Comment by jhendrixMSFT** [comment]
I will add this functionality.  Also note that we're in the process of deprecating the blob storage functionality in the /storage package; it's being replaced by the new [azblob](https://github.com/azure/azure-storage-blob-go) package.

**Comment by petitout** [comment]
ok thanks !
Any particular reason for switching to azblob ?

**Comment by jhendrixMSFT** [comment]
If the /storage package is working for you as-is then there's no real urgency to switch.  That said all new SDK support for storage APIs is happening in the new package and will not be back-ported to /storage.

**Comment by petitout** [comment]
ok got it, thanks

**Comment by jhendrixMSFT** [comment]
Fixed in v14.2.0
https://github.com/Azure/azure-sdk-for-go/releases/tag/v14.2.0.

**Comment by petitout** [comment]
Awesome, thank you
