### ISSUE TITLE
Make the profile builder easier to use and document how to use it

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1044]
We need a push-button solution for the profile builder, perhaps a script, that makes it super easy to use.  Also document the different ways we invoke it (e.g. example command lines).

**Comment by marstr** [comment]
Last week I was reading an [old blog post about the `generate` command](https://blog.golang.org/generate). How would you feel, @jhendrixMSFT, about me adding files into the `profiles` directory so that keeping the profiles up-to-date is as easy as running `go generate`?

**Comment by jhendrixMSFT** [comment]
I like it.  Presumably we can add something top-level so we only have to invoke it once and it spews out all the profiles?

**Comment by marstr** [comment]
Exactly :)
