### ISSUE TITLE
storage API: Account struct needs to contain the resource group name

### ISSUE THREAD

**Issue by vadmeste** [Azure/azure-sdk-for-go#1049]
`AccountsClient.List()` is able to list all storage accounts under a given subscription. However, it is not possible to retrieve the resource group associated to a storage account. The resource group name is needed to call other APIs such as `AccountsClient.ListKeys(resourceGroupName string, accountName string)`

or am I missing something ?

**Comment by jhendrixMSFT** [comment]
@JasonYang-MSFT I dug up your name from swagger history, do you own this spec or know who does?

**Comment by jhendrixMSFT** [comment]
@JasonYang-MSFT ping

**Comment by vladbarosan** [comment]
@vadmeste right now there is no very convenient way of obtaining the resource group from a storage account. We reached out to the storage team for this.

Meanwhile you can try to use `ParseResourceID` on the resource id of the storage account to obtain the resource group https://github.com/Azure/go-autorest/blob/ed4b7f5bf1ec0c9ede1fda2681d96771282f2862/autorest/azure/azure.go#L163

Let us know if that helps.

**Comment by vladbarosan** [comment]
Let us know if the workaround works for you, otherwise SQL team was made aware of the request and they will decide on how to proceed.
