### ISSUE TITLE
Generate sdk for latest branch with latest changes from azure rest-specs-api

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1053]
stable branch of  autorest.go and stable branch of specs

**Comment by vladbarosan** [comment]
to decide 
 - PR for each spec change or nightly
 - automatic merge into nightly branch or not ( to begin with )  (correlates with the first point)

**Comment by jhendrixMSFT** [comment]
For latest branch let's start with a 24 hour cadence.  Set up a cron job to sync latest specs, generate SDK and profiles, validate, and commit.  Note that as part of this automation we must include the commit hash of the specs repo and the generator version.

**Comment by jhendrixMSFT** [comment]
This has been superseded by the swagger->sdk work.
