### ISSUE TITLE
Ability to use Org hierarchy APIs

### ISSUE THREAD

**Issue by nauxliu** [Azure/azure-sdk-for-go#10566]
### Feature Request

How can I call the [Org hierarchy](https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http) APIs using this SDK? Can this be supported?

**Comment by ArcturusZhang** [comment]
Unfortunately these APIs belong to `msgraph` and will not be supported in this SDK.

You can find a valid msgraph go SDK [here](https://github.com/yaegashi/msgraph.go)
