### ISSUE TITLE
deprecate legacy '/management' package

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1058]
The Azure Service Management API client (at `/management`) should be deprecated. Users should instead use one of the clients under `/services`. Thanks!

Related: #976

**Comment by jhendrixMSFT** [comment]
While I agree with the sentiment we did this [before](https://github.com/Azure/azure-sdk-for-go/commit/e1858f239d05a88aa4e1a6981c8f040c238ec6e8#diff-57d4c2c33fbc5543ebc2e6876898266a) and received some flames for it so we ended up reverting it.

**Comment by marstr** [comment]
Done.
