### ISSUE TITLE
Does azure go sdk provide a boolean value indicating whether a DNS zone is private or public

### ISSUE THREAD

**Issue by kirankumarbv** [Azure/azure-sdk-for-go#1059]
Hi,

I am trying to mimic some functionality in our application that currently uses aws route 53 feature. In particular I am interested to know if there is anything similar in azure go sdk to the below aws struct.

https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#HostedZoneConfig

In the HostedZoneConfig struct above there is a boolean called PrivateZone which indicates whether the given zone is private or public.  
Do we have something similar in azure that I can use in my application?

**Comment by kirankumarbv** [comment]
It would be great if I could get any update on this? This is kind of a blocker for us.

**Comment by joshgav** [comment]
It looks like the [Zone](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/dns/resource-manager/Microsoft.Network/stable/2017-09-01/dns.json#L1183) and [ZoneProperties](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/dns/resource-manager/Microsoft.Network/stable/2017-09-01/dns.json#L1158) specs don't provide such an attribute, nor do I see it in the [DNS API docs](https://docs.microsoft.com/en-us/rest/api/dns/zones/createorupdate). I'll raise this request with the DNS service team.

Thanks @kirankumarbv!

**Comment by joshgav** [comment]
Followed up with @kirankumarbv offline, this feature is in private preview so please reach out if you need it, thanks!
