### ISSUE TITLE
Daily updates to SDK in master excluding packages with breaking changes

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1062]
Create a task that will update the SDK in master on a daily cadence.  Any packages that include breaking changes will be excluded.

**Comment by marstr** [comment]
For this and the [monthly cadence of the same issue](#1063), we've agreed to use the PRs that are being automatically generated by the Swagger -> SDK bot. Each of the PRs is targeting the `latest` branch, and should be merged in as a soon as the original PR in the Specs repository has been merged into `master`. Anything that hasn't caused a breaking change should get cherry-picked and merged into this repository's `master` branch. At some cadence that we decide (monthly?), we will merge the `latest` and `master` branches.

The new `vgo` work that @rsc announced is game changing for us, and could help us navigate these waters more easily in the future. Once we decide to start shipping using [the newly introduced concept of modules](https://research.swtch.com/vgo-module), we could always release to `master`, and give each service their own version number.
