### ISSUE TITLE
Document Go SDK's Swagger -> SDK story

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1064]
Right now there are a bunch of discrete steps that are performed manually.

- Sync latest specs repo
- Run generation script
- Run profile builder once per profile

We need some kind of wrapper that handles the process end-to-end in one easy command.

**Comment by marstr** [comment]
This has been open for a while, and the answer is sorta: @lmazuel and I have been working for sometime on a tool called [Swagger -> SDK](https://github.com/lmazuel/swagge-to-sdk) that does the three steps @jhendrixMSFT mentioned. This issue should stay open until there is documentation, and our dev team understands how to use it.
