### ISSUE TITLE
coverage of web apps Kudu operations

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1065]
@tombuildsstuff informed us yesterday that some operations needed for setting up a web app come from [Kudu](https://github.com/projectkudu/kudu), specifically configuring source repos for automated deployments.

Let's figure out how to include Kudu operations in our SDK.

refs:
* https://docs.microsoft.com/en-us/rest/api/appservice/webapps
* https://github.com/projectkudu/kudu/wiki/REST-API

**Comment by joshgav** [comment]
Following conversations with @davidebbo we will not include Kudu operations in a public SDK and will instead seek equivalent Azure RM operations. Please open issues here or in [the samples repo](https://github.com/Azure-Samples/azure-sdk-for-go-samples) if you need help figuring out how to do something. Thanks.

**Comment by tombuildsstuff** [comment]
@joshgav are there any updated plans here? As it stands we're blocked from implementing https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104

**Comment by tombuildsstuff** [comment]
@joshgav unfortunately [I've just discovered another requirement for Kudu support](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2254) - are there any updated plans here, or should we look to write a Kudu client? :)

Thanks!

**Comment by joshgav** [comment]
Checking into this again @tombuildsstuff, sorry for the frustration.

cc @stefsch

Related: https://github.com/Azure/azure-sdk-for-go/issues/2397

**Comment by tombuildsstuff** [comment]
no worries - thanks @joshgav :)

**Comment by tomasaschan** [comment]
*bump* 😃 

I, too, came here from https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104, which I found because Kudu keeps changing the SCM type of my App Service to `VSTSRM`, which is currently not supported by the Terraform provider, so after each deployment of my app, my infrastructure config detects drift...
