### ISSUE TITLE
Provide a way to test API's locally

### ISSUE THREAD

**Issue by cdelacruzpinto** [Azure/azure-sdk-for-go#10682]
### Feature Request

In order to better test my code which uses the Azure SDK without needing to provision actual cloud resources, I would like to have a way to mock some of the APIs. 

In the case of Amazon, there is this beautiful project: https://github.com/localstack/localstack which allows to mock the most used ones.

**Comment by ArcturusZhang** [comment]
Hi @cdelacruzpinto thanks for this issue!

You can always make some mock test for the SDK using the interface such like [this](https://github.com/Azure/azure-sdk-for-go/blob/master/services/aad/mgmt/2017-04-01/aad/aadapi/interfaces.go).
