### ISSUE TITLE
package should be named "avs", not "vmware"

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-go#10683]
The package should be named "avs", not "vmware". #10454 was merged before I had a chance to review. Please rename the package. See also https://github.com/Azure/sdk-release-request/issues/496.

Current location:
https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/vmware/mgmt/2019-08-09-preview/vmware

Should be:
https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/avs/mgmt/2019-08-09-preview/avs

**Comment by ArcturusZhang** [comment]
Hi @ctaggart sorry for that... I will change it, release it and remove the wrong-named package in the next major version release (at the end of this month)

**Comment by ArcturusZhang** [comment]
Should be resolved in v44.0.0

**Comment by ctaggart** [comment]
thank you @ArcturusZhang ! ❤️
