### ISSUE TITLE
loadbalancers下的ListComplete接口异常

### ISSUE THREAD

**Issue by jinxue-w** [Azure/azure-sdk-for-go#10681]
### Bug Report
/Azure/azure-sdk-for-go/services/network/mgmt/2017-10-01/network/loadbalancers.go

最近调用的时候发现ListComplete接口在查询美东的负载均衡器的时候只返回55个（实际上有59个），nextlink非空，应该是分页了，但是查询西欧的时候就是全部63个个全部查到，没分页；之前使用一只是正常的，这个接口本来就应该可以查到所有的

- [ 美东] 
![image](https://user-images.githubusercontent.com/57025085/85134757-963e4a00-b26f-11ea-8313-61f90c27fd34.png)

- [西欧]
![image](https://user-images.githubusercontent.com/57025085/85134786-a0604880-b26f-11ea-9670-2c9024341261.png)

**Comment by jinxue-w** [comment]
我已经定位到这里了，只加了账户认证，而已，要代码的话就是下面，config后面是我调用自己的账户信息。
if err := readConfig(); err != nil {
		t.Fatal(err)
	}
	_ = os.Setenv("AZURE_TENANT_ID", config.Conf.AzureTenantId)
	_ = os.Setenv("AZURE_CLIENT_ID", config.Conf.AzureClientId)
	_ = os.Setenv("AZURE_CLIENT_SECRET", config.Conf.AzureClientSecret)
	authorizer, err := auth.NewAuthorizerFromEnvironment()
	if err != nil {
		logs.Error("Failed to get OAuth config: %v", err)
		os.Exit(0)
	}
	niclient := network.NewLoadBalancersClientWithBaseURI("https://management.azure.com",config.Conf.AzureSubscriptionID)
	niclient.Authorizer = authorizer
	resp, err := niclient.ListComplete(context.Background(), config.Conf.AzureResourceGroupName[0])


另外加一点，你们官方对外该接口的调试接口也是一样的错误，链接如下：
https://docs.microsoft.com/en-us/rest/api/load-balancer/loadbalancers/list

**Comment by ArcturusZhang** [comment]
Hi @jinxue-w thanks for this issue.

The difference between `List` and `ListComplete` is that the `ListComplete` function hides the details of the pagination from the user, while the `List` function would require you to do the paging yourself.

The `resp` in the return values of `ListComplete` is an `iterator` (you can take [this wiki page](https://en.wikipedia.org/wiki/Iterator_pattern) for reference). To list all of them in the iterator, usually we just do a for loop over the iterator:
```
iterator, err := niclient.ListComplete(context.Background(), config.Conf.AzureResourceGroupName[0])
if err != nil {
panic(err)
}
for iterator.NotDone() {
v := iterator.Value()
fmt.Println(v) // output your lb, or add it into a slice
if err := iterator.NextWithContext(ctx); err != nil {
panic(err)
}
}
```

**Comment by jinxue-w** [comment]
Thanks for your reply, this method is ok. However, the description of your interface is to directly query all of them, which is actually not in line with expectations. This has been normal not long ago, but only recently.

And this URL：https://docs.microsoft.com/en-us/rest/api/load-balancer/loadbalancers/list,
It also falls short of expectations.

**Comment by ArcturusZhang** [comment]
Hi @jinxue-w the `ListComplete` function is a method introduced by go SDK to simplify the usage of the vanilla `List` API in the REST API definition which requires manual paging.
If you like the paging approach, you could always use the `List` function like this:
```
resp, err := client.List(...)
if err != nil {
  panic(err)
}
for {
  for _, v := range resp.Values() {
    // iterates all the results in this page
  }
  if !resp.NotDone() {
    break
  }
  if err := resp.NextWithContext(ctx); err != nil { // go to next page
    panic(err)
  }
}
```
If you want to do anything else with the list results, you could always make a slice of results, first iterate the list result to collect all resources, and then do whatever you want with it.

Hope this could answer your questions and if you do not mind, I will close this issue. Please feel free to ping me if you have more questions. Thanks!
