### ISSUE TITLE
Track2: Additional model tags to keep some Swagger definitions

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#10732]
### Feature Request

It would be helpful to add some additional tags in the generated model, to keep as more info as possible from Swagger.

Take the [`OutboundRulePropertiesFormat`](https://raw.githubusercontent.com/Azure/azure-sdk-for-go/track2/services/network/mgmt/2019-12-01/network/models.go) as an example:

```go
// original
type OutboundRulePropertiesFormat struct {
	AllocatedOutboundPorts   *int32                           `json:"allocatedOutboundPorts,omitempty"`
	FrontendIPConfigurations *[]SubResource                   `json:"frontendIPConfigurations,omitempty"`
	BackendAddressPool       *SubResource                     `json:"backendAddressPool,omitempty"`
	ProvisioningState        ProvisioningState                `json:"provisioningState,omitempty"`
	Protocol                 LoadBalancerOutboundRuleProtocol `json:"protocol,omitempty"`
	EnableTCPReset           *bool                            `json:"enableTcpReset,omitempty"`
	IdleTimeoutInMinutes     *int32                           `json:"idleTimeoutInMinutes,omitempty"`
}
```

```go
// proposed
type OutboundRulePropertiesFormat struct {
	AllocatedOutboundPorts   *int32                           `json:"allocatedOutboundPorts,omitempty"`
	FrontendIPConfigurations *[]SubResource                   `json:"frontendIPConfigurations,omitempty" swagger:"required"` // *
	BackendAddressPool       *SubResource                     `json:"backendAddressPool,omitempty" swagger:"required"`       // *
	ProvisioningState        ProvisioningState                `json:"provisioningState,omitempty"`
	Protocol                 LoadBalancerOutboundRuleProtocol `json:"protocol,omitempty" swagger:"required,readonly"` // *
	EnableTCPReset           *bool                            `json:"enableTcpReset,omitempty"`
	IdleTimeoutInMinutes     *int32                           `json:"idleTimeoutInMinutes,omitempty"`
}
```

### Benefit

Rather than keep this information in other forms (e.g. comment), bake them into the struct tag could potentially be leveraged by code generation tools to generate code based on Go SDK (instead of Swagger/Modeler). For example, currently, it is not possible to build an Azure CLI in Go based on Go SDK because it lacks those constraints, that are required to define CLI args/options.

### Reference

https://godoc.org/gopkg.in/go-playground/validator.v9

**Comment by jhendrixMSFT** [comment]
I like this idea although I wouldn't use the term `swagger` in the tag (we will work on a better term).  This would also be useful for expressing things like read-only properties so we can omit them when sending over-the-wire.

**Comment by jhendrixMSFT** [comment]
Current proposal is to use `attr` for the key in the tag.
