### ISSUE TITLE
document how to migrate from `arm/` to `services/`

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1076]
In a wiki doc:

* history of the `arm/` path and how it abstracted versions
* how to find the last version represented by the `arm/` path
* exceptions and what to do
* perhaps mention profiles but don't use them for now

**Comment by kirankumarbv** [comment]
Hi,

It would be helpful if there is some pointers on where the examples went? We were referencing **DNS** examples under arm/ till yesterday and now unable to find it.

**Comment by joshgav** [comment]
Hi @kirankumarbv - Samples are now at https://github.com/Azure-Samples/azure-sdk-for-go-samples, and in fact I'm responsible for porting the DNS sample :) in https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/87.

In the meantime you can go back to the last commit which included the `arm/` folder: https://github.com/Azure/azure-sdk-for-go/tree/21b68149ccf7c16b3f028bb4c7fd0ab458fe308f/arm/examples/dns

**Comment by kirankumarbv** [comment]
Thanks a lot. 

As soon as I commented here, I realized I could do that and have been using the example from the older version. Thanks.

**Comment by marstr** [comment]
Closing as stale. If someone has questions, reach out.
