### ISSUE TITLE
Support non-root discriminators

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1077]
Discriminators might not start at the root of the composition tree ( see https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/preview/2017-02-28-preview/timeseriesinsights.json )

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.0.0
