### ISSUE TITLE
How to tell if a table has successfully been deleted

### ISSUE THREAD

**Issue by pabowers** [Azure/azure-sdk-for-go#10813]
Deleting a table is asynchronous so even though the REST endpoint returns as success the table might not actually be deleted at that point.

**Comment by jhendrixMSFT** [comment]
According to the [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-table), if the table is in process of being deleted, any future operations on that table will return a 409 (status conflict) with additional info that the table is being deleted.

**Comment by jhendrixMSFT** [comment]
Apparently there is some corner-case where GET will return a 404 (not a 409 as doc'ed) however when you subsequently try to recreate the table it fails with a 409 as the delete is still in progress.

**Comment by jhendrixMSFT** [comment]
@seankane-msft do you know if this has been fixed in `aztables`?

**Comment by seankane-msft** [comment]
I'm not sure what the solution to this issue is. There is a slight delay by the service to delete a table, and you cannot create a table with the same name immediately afterwards. However, you can loop on a `CreateTable` call when the response is a 409, but there is not built in method in the SDK for retrying this operation.

**Comment by jhendrixMSFT** [comment]
Would it make sense to model Delete as an LRO?  What do the other languages do?

**Comment by seankane-msft** [comment]
Other languages do not model delete as an LRO, we have the same implementation as other languages. I don't believe other languages have a built in way to do any polling for this method.

**Comment by jhendrixMSFT** [comment]
I've updated the docs for `CreateTable` and `Delete` to explain the nuance here.
