### ISSUE TITLE
Azure SDK's Go SDK documentation should provide guidance for asynchronous usage for SQL API scenarios

### ISSUE THREAD

**Issue by scgbear** [Azure/azure-sdk-for-go#10829]
### Feature Request

Problem Statement: Azure SDK's Go SDK documentation does not provide guidance for asynchronous usage for SQL API scenarios. 

Desired Experience: Update documentation to provide clear guidance for asynchronous usage across different services. Ability for asynchronous usage to work across different services as expected.

Azure SQL server APIs were difficult to use in an asynchronous fashion and had bugs that we had to work around. All samples showed only synchronous usage.
 
In our controller, we had to call the CreateOrUpdate() API in an async fashion and on the next reconcile loop we might end up calling the API again if the SQL server wasn’t provisioned yet (took 10-15 mins). This API isn’t designed to work in this scenario.

Note: We used the same model for Keyvault first and it worked fine.

It would be good to provide some async usage samples and ensure there is consistency across the different services

The project where we used and faced this issue is here - http://github.com/Azure/azure-service-operator

**Comment by ArcturusZhang** [comment]
Hi @scgbear thanks for this issue.

We have a [separated repo](https://github.com/Azure-Samples/azure-sdk-for-go-samples) which stores some samples of some of the RPs in the go SDK. And there are some samples related with SQL server [here](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/sql/sql.go).

Go SDK is using the async framework from [go-autorest](https://github.com/Azure/go-autorest/blob/master/autorest/azure/async.go), whose usage should be unified across different RPs.

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
CSEF365082
</details>

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). Also, for your concern, I wonder if this We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). I could solve your problem with our new version.
