### ISSUE TITLE
graphrbac: support the replyUrlsWithType property for Applications

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#10830]
### Feature Request

Looking at the Azure Portal when configuring reply/redirect URLs for applications, it makes use of the `replyUrlsWithType` property of the application resource, available with v2.0 of the API. This property is [undocumented](https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#application-entity).

How can we get support for this property, as it's seemingly the only way to create different types of reply/redirect URLs and will fill a large gap in support for different types of applications?

Implementing this would be a _huge_ enabler, as it is currently the canonical way to set the new redirect URIs for applications, given that MS Graph support is currently lagging behind here.

## Relevant portal blade
![Screenshot 2020-06-26 02 29 43](https://user-images.githubusercontent.com/251987/85811071-e710df80-b754-11ea-92e9-750c81b698f6.png)

## Add a platform
![Screenshot 2020-06-26 02 30 25](https://user-images.githubusercontent.com/251987/85811100-03ad1780-b755-11ea-8e61-27af5817d4ab.png)

## Add an SPA redirect
![Screenshot 2020-06-26 02 31 17](https://user-images.githubusercontent.com/251987/85811146-27705d80-b755-11ea-8f29-eab95a02e51b.png)

## Resulting API query
![Screenshot 2020-06-26 02 32 39](https://user-images.githubusercontent.com/251987/85811201-5686cf00-b755-11ea-9a6b-e800f1259772.png)
![Screenshot 2020-06-26 02 33 31](https://user-images.githubusercontent.com/251987/85811233-71f1da00-b755-11ea-9796-c47861d8b4de.png)

## Payload
```http
PATCH /myorganization/applications/0ee8ac26-20f5-4da4-abd8-4b504785782b?api-version=2.0

{"id":"0ee8ac26-20f5-4da4-abd8-4b504785782b","replyUrlsWithType":[{"type":"Web","url":"http://unittest.hashicorptest.com"},{"type":"Spa","url":"https://blah-spa"},{"type":"InstalledClient","url":"https://blahnative"}],"logoutUrl":null,"oauth2AllowImplicitFlow":false,"oauth2AllowIdTokenImplicitFlow":false}
```

**Comment by autom8ter** [comment]
Highly interested in this since its preventing anyone from using terraform to automate the creation & management of single paged AD applications that use the PKCE oauth2 flow.

**Comment by lilyjma** [comment]
@armleads-azure any updates?

**Comment by autom8ter** [comment]
Bump

**Comment by CaptainStealthy** [comment]
@armleads-azure @ArcturusZhang Any updates on this?

**Comment by FreFre** [comment]
#bump

Our Azure Fabric Explorer is secured using AD. As described in the following page : https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-setup-aad

We got the whole setup in terraform, but miss out on one thing: replyUrlsWithType as we need it to define

`$nativeApp = @{
    publicClient = "true"
    displayName = $NativeClientApplicationName
    replyUrls = @("urn:ietf:wg:oauth:2.0:oob")
    requiredResourceAccess = $nativeAppResourceAccess
}`

Currently Terraform **azuread_application** doesn't allow non 'https' url's in the replyUrls property.
Not even sure the type "Mobile and desktop applications" is supported **azuread_application**

![image](https://user-images.githubusercontent.com/1104727/141079764-c2eceac1-1bf3-48c6-a9dd-764e06872a36.png)
