### ISSUE TITLE
Some management APIs lack ability to check server name availability

### ISSUE THREAD

**Issue by krancour** [Azure/azure-sdk-for-go#1089]
The management APIs for some services (for instance, Postgres and MySQL) expose functions for checking the availability of server names (which must be globally unique).

Other management APIs (for instance, SQL or Redis) do _not_ expose this.

I'm pretty sure this is probably a function of the swagger specs for those services, but maybe this is a good place to start the conversation? I assume this functionality is already built somewhere because portal always checks server name availability for all services. Hopefully this is only just a matter of getting that functionality exposed via spec and, in-turn, in the SDK.

**Comment by jhendrixMSFT** [comment]
@joshgav could you please route this to the correct service owners?

**Comment by joshgav** [comment]
Thanks for raising this @krancour, the services which you said don't provide early name checks don't offer an API for it, I'll check into how portal is achieving the early checking for them and see if we can implement that here too. Thanks!

**Comment by joshgav** [comment]
Hi @krancour! So I did some digging and it seems only Redis is lacking an early name check, and I'll look into that.

For SQL, the spec is [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/checkNameAvailability.json), can you use [github.com/Azure/azure-sdk-for-go/services/sql/mgmt/2014-04-01/sql#ServersClient.CheckNameAvailability](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/sql/mgmt/2014-04-01/sql#ServersClient.CheckNameAvailability)?

Are there other services for which you need an early name check and can't find one?

I put together this list for future reference: https://gist.github.com/joshgav/e9580b7010ef56e1e09c751d3de5d430

**Comment by joshgav** [comment]
Good news, Redis has added an early name check to their [latest spec](https://github.com/Azure/azure-rest-api-specs/blob/69bc74ce8deed4b47b08825c7f1dc1557daa228c/specification/redis/resource-manager/Microsoft.Cache/stable/2017-10-01/redis.json#L62-L95)! Bad news, this doesn't seem to have come through in the Go SDK: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/redis/mgmt/2017-10-01/redis

@jhendrixMSFT can you look into why a CheckNameAvailability function for Redis wasn't generated? Thanks!

**Comment by jhendrixMSFT** [comment]
@joshgav We're still working on the automation to flow recent changes into master.  The change is in the latest branch.

**Comment by jhendrixMSFT** [comment]
This will hit master in our v15 release due at the end of this month.

**Comment by krancour** [comment]
Thanks for being so on top of this, guys!!

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.0.0
