### ISSUE TITLE
IntegrationServiceEnvironmentClient, Delete wait for delete completion

### ISSUE THREAD

**Issue by jbinko** [Azure/azure-sdk-for-go#10941]
### Feature Request

Currently the SDK has only non blocking Delete operation in IntegrationServiceEnvironmentClient.
The call Delete correctly deletes ISE in async mode but next get operation for status returns immediately NotFound so not possible to check for delete completion.

Please provide the workaround/example how to wait for delete completion of ISE with existing SDK or provide 
IntegrationServiceEnvironmentDeleteFuture structure so we can call WaitForCompletionRef to wait for delete completion.

**Comment by ArcturusZhang** [comment]
Hi @jbinko thanks for the issue!

Actually the implementation of the deletion of ISE is sync - which should be blocking. But based on your description, this deletion should be async. To resolve this, we will have to first modify the corresponding swagger to mark this operation as `long-running-operation` and usually this should be done by the service team.

In the meantime, could you please provide the response of the delete request (including the status code and the headers)? I have tried to create one first but it seems to take forever to complete... Typically, if the request is truly a long-running-operation, it should first give you the status code `201` or `202` and there should be a URL for polling the async result in the header (could be `Location` or `AsyncOperation` depending on the implementation of the service).

**Comment by jbinko** [comment]
Basically this call:
resp, err := client.Delete(ctx, id.ResourceGroup, id.Name)
initiates deletion process and returns quickly like in 5 seconds (it is OK) but real deletion of ISE can take 1-2 hours and is in progress in the background. I need to have mechanism to be blocked somehow until the real deletion really finishes. Reason is ISE is occupying my VNET resource and VNET cannot be deleted until real unprovisioning of ISE finishes. It is Azure Terraform related blocker.

**Comment by ArcturusZhang** [comment]
@jbinko based on what I am seeing in the response and the status code, this request is not a long-running-operation. Therefore we cannot introduce a Future struct for this function.

It interested me that if after the delete call returns, a immediate get request returns 404, does this mean the delete has been completed? This behaviour sounds very reasonable to me. Or is there any other context?

**Comment by jbinko** [comment]
Correct and this is the challenge I'm referring to. You call delete, it takes 5 seconds to successfully finish with status code 200. The ISE resource disappears from Azure (even from Portal) and you cannot control it/polling it. However the delete operation is still in progress for like next 60 minutes and is still effectively occupying your VNET and you cannot delete VNET until the ISE is truly deleted. How can I detect ISE is truly deleted so we can unblock TF workflow and continue with deletion of VNET which is not containing ISE anymore? E.g. Can we initiate change and ask for Long running Operations?

**Comment by lilyjma** [comment]
@ArcturusZhang any updates?
