### ISSUE TITLE
Azure go sdk import path changes

### ISSUE THREAD

**Issue by jiany88** [Azure/azure-sdk-for-go#1094]
I noticed that Azure go sdk has been replacing the import path from "arm" to "services" recently, since our existing codes are not ready to switch to "services" yet. Is there any alternative for getting the old SDK with arm in the import path? 

GO_DEPENDENCY_LIST      :=     github.com/Azure/azure-sdk-for-go/arm/compute \
                                github.com/Azure/azure-sdk-for-go/arm/network \
                                github.com/Azure/azure-sdk-for-go/arm/storage

**Comment by marstr** [comment]
If you use [dep](https://github.com/golang/dep), or another package management tool, you can lock yourself to any version of the Azure-SDK-for-Go `v12` or before. That should allow you to use the `arm` folder until you're ready to adopt the new multi-api version paradigm.
