### ISSUE TITLE
Latest SDK version tracking is confusing and cumbersome

### ISSUE THREAD

**Issue by kirankumarbv** [Azure/azure-sdk-for-go#1096]
Hi,

Earlier, I used to import compute, network etc in my files in a simplistic manner like show below

github.com/Azure/azure-sdk-for-go/arm/network
github.com/Azure/azure-sdk-for-go/arm/dns

Now with the latest move from arm/ to services/, Everytime there is a versioning change, I have to change all my files which import those services as the version number is not same for different services. As shown below.

github.com/Azure/azure-sdk-for-go/services/network/mgmt/2017-09-01/network
github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-12-01/compute

This will create a lot of problems for us as we have to change "2017-12-01" part of import everytime there is a version change. 
Is there a way where we do not have to change imports but only update our sdk version like we used to have when it was under arm/ ??

**Comment by marstr** [comment]
### Short Answer

The old behavior can be achieved by taking a dependency on the `latest` profile. Your imports would become:

``` Go
import (
    "github.com/Azure/azure-sdk-for-go/profiles/latest/network/mgmt/network"
    "github.com/Azure/azure-sdk-for-go/profiles/latest/compute/mgmt/compute"
)
```

### Long Answer

**We do not recommend development without tying yourself to an API Version**. Between API Versions, services teams have no restrictions on the changes they make. Further more, **we make no guarantee that the `latest` profile will not have breaking changes** inside of a major SemVer in this repository.

However, that doesn't mean this has to be inconvenient! If you want to, [you can run the profileBuilder yourself](https://github.com/Azure/azure-sdk-for-go/tree/8678d90a0680dc45d4b5257d09b2d5f3f40db0c8/tools/profileBuilder) and check in the virtualized packages in your repository. That will let you change the API Version you target across your entire application in a single line.

**Comment by joshgav** [comment]
@kirankumarbv thank you for the feedback. I'm sorry for the additional step now required; we're working to make this easier in the future, stay tuned. Our previous behavior of only supporting the latest API versions failed to meet the needs of users who needed to use a specific version. In the meantime, you can move to the `latest` profile as @marstr recommended and gradually select a specific version for each resource.

**Comment by kirankumarbv** [comment]
@joshgav Thanks for this update.
 Is there a recommended version for each resource listed somewhere? One that is most stable or something along those lines?
