### ISSUE TITLE
Use of ptr embedding in KeyBundle (and possibly other types) causes hard to debug nil dereference

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-go#10975]
### Bug Report
Go SDK version: v38.0.0
Import Path: "github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault/client.go"

I think that this issue could happen on any version and possibly with any SDK though, so it may be generic to AutoRest and not specific to this particular SDK.

AutoRest defines:
```
type Response struct {
	*http.Response `json:"-"`
}
```

The KeyVault SDK then defines:
```
// BaseClient is the base client for Keyvault.
type BaseClient struct {
	autorest.Client
}

// KeyBundle a KeyBundle consisting of a WebKey plus its attributes.
type KeyBundle struct {
	autorest.Response `json:"-"`
	// Key - The Json web key.
	Key *JSONWebKey `json:"key,omitempty"`
	// Attributes - The key management attributes.
	Attributes *KeyAttributes `json:"attributes,omitempty"`
	// Tags - Application specific metadata in the form of key-value pairs.
	Tags map[string]*string `json:"tags"`
	// Managed - READ-ONLY; True if the key's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true.
	Managed *bool `json:"managed,omitempty"`
}
```

`CreateKey` has the following signature:
`func (client BaseClient) CreateKey(ctx context.Context, vaultBaseURL string, keyName string, parameters KeyCreateParameters) (result KeyBundle, err error)`

I naively wrote the following code:
```
bundle, err := kvopsclient.CreateKey(ctx, vaultBaseURL, instance.Name, params)
if err != nil {
		if bundle.Response.StatusCode == http.StatusForbidden {
                    ...
                }
```

I hit a nil dereference panic on the `bundle.Response.StatusCode` line but:
1. `bundle` cannot be `nil` since it's a value type return.
2. `bundle.Response` cannot be `nil` because this is accessing the value-typed embedding

It's _really_ confusing that code where there are no visible ptr types can hit a `nil` deference panic.

In my opinion:
1. `KeyBundle` (and other types like it) should not embed `autorest.Response` - the test for embedding is (IMO) `is-a`. `KeyBundle` is not a `Response`. At best it _has_ a `Response`, so it should just be a property, not embedded.
2. Since `autorest.Response` may not be filled out (because we never sent the request, etc), the `autorest.Response` property should be a pointer (`*autorest.Response`).

Tangentially related, it's _possibly_ the case that the `KeyBundle` result should _also_ be a `ptr` because returning a default struct in the case the call was never made seems sorta strange - this is mitigated somewhat by the `err` return though and isn't the primary cause of the issues I faced but figured I would mention it.

**Comment by ArcturusZhang** [comment]
Hi @matthchr thanks for this issue!

You suggestion is very reasonable. In the current implementation, if the request has some problem and never been sent, the `bundle.Response.Response` would be `nil`, but `bundle.Response` would never be `nil` since it is a struct not a pointer. In your code, there is an implicit property prompt - `bundle.Response.Response` -> `bundle.Response`, which is quite dangerous on behalf of the nil checking.

But I am afraid that the current track 1 SDK may not change this, since this could cause a massive change in the whole SDK...
Hi @jhendrixMSFT do you have any insight on this? How would the track 2 SDK handle this?

**Comment by jhendrixMSFT** [comment]
Hello!  Agreed that this current pattern is non-intuitive.  However, as @ArcturusZhang points out, changing it would be a significant breaking change so unfortunately we are stuck with it in our track 1 SDK.  For track 2, `KeyBundle` will be returned by pointer, and in the case of an error will be `nil` (e.g. return value would be `(nil, <some error>)`).

However you can still access the underlying `*http.Response` via the error.  The returned error should be of type [DetailedError](https://github.com/Azure/go-autorest/blob/master/autorest/error.go#L29) so you can type-assert the returned error to this type then access the `Response` field to get the `*http.Response`.
