### ISSUE TITLE
Make profileBuilder work in swagger->sdk environment

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#1101]
At the moment the following function assumes that Azure SDK for Go is located relative to the GOPATH environment:

https://github.com/Azure/azure-sdk-for-go/blob/1e334c402ea1460704b0263e5d188f28ad946ce1/tools/profileBuilder/model/defaults.go#L26

There are a few problems with doing it that way.
1. It will be increasingly common to use Go with an implicit value of GOPATH. If it is not set we should probably figure out where Go itself is defaulting it to; I believe it is `~/go`.
1. The machine in which `profileBuilder` is executing should ideally be tolerant of Go not really being setup on the machine. For instance, @lmazuel is looking to have `profileBuilder` running across user machines, where we have little to no control of whether or not we can place output in the traditional location.

**Comment by marstr** [comment]
Further problematic locations:
https://github.com/Azure/azure-sdk-for-go/blob/1e334c402ea1460704b0263e5d188f28ad946ce1/tools/profileBuilder/model/list.go#L48

**Comment by jhendrixMSFT** [comment]
After discussion with @lmazuel the POR is to have the swagger->sdk environment for Go be a well-defined Go build environment that defines GOPATH.

**Comment by jhendrixMSFT** [comment]
This is working now.
