### ISSUE TITLE
Failed to create an Azure firewall when adding a network rule with a destinationFqdn

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-go#11094]
### Bug Report

- import path of package in question, `services/network/mgmt/2019-09-01/network/azurefirewalls.go`
- SDK version `2019-09-01`
- output of `go version`
 `go version go1.13.8 linux/amd64`

- What happened?
We want to build a firewall with below network rule. 
```
            {
              "name": "kms",
              "protocols": [
                "TCP"
              ],
              "sourceAddresses": [
                "*"
              ],
              "destinationAddresses": [],
              "sourceIpGroups": [],
              "destinationIpGroups": [],
              "destinationFqdns": [
                "kms.core.windows.net"
              ],
              "destinationPorts": [
                "1688"
              ]
            },
```
Below response is returned
```
In order to use DestinationFqdns in Network Rules,
 DNS Proxy must be enabled, or RequireProxyForNetworkRules must be set to 'false'. See rule kms in network rule collection DefaultNetRules
```

We tried to set `RequireProxyForNetworkRules`, `requireProxyForNetworkRules`, `DNSRequireProxyForNetworkRules` or `dnsRequireProxyForNetworkRules` to `false` in `AdditionalProperties`, it always return below error. The error is still same even if we use the API version `2020-05-01`.

Request:
```
    "additionalProperties": {
      "requireProxyForNetworkRules": "false"
    },
```
Response: 
```
{
  "status": "Failed",
  "error": {
    "code": "AzureFirewallInvalidAdditionalPropertyName",
    "message": "'requireProxyForNetworkRules' is not a valid property name for Azure Firewall.",
    "details": []
  }
}
```

- What did you expect or want to happen?
We expect to create the firewall with the network rule successfully.
- How can we reproduce it?
Build a network rule with a destinationFqdn as above.
- Anything we should know about your environment.
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by AbelHu** [comment]
ping

**Comment by ArcturusZhang** [comment]
Hi @AbelHu thanks for this issue!
Unfortunately I do not have much knowledge about this resource, therefore I have tagged this issue so that the service team could have a look at this and answer your question.

**Comment by AbelHu** [comment]
Could anyone from network firewall team help this?

**Comment by timMSFT** [comment]
The proper way to set DNS proxy is as below. 

    "resources": [
        {
            "type": "Microsoft.Network/firewallPolicies",
            "apiVersion": "2020-05-01",
            "name": "[parameters('firewallPolicies_DatabasePolicy_name')]",
            "location": "eastus",
            "properties": {
                "threatIntelMode": "Deny",
                "threatIntelWhitelist": {
                    "ipAddresses": []
                },
                "dnsSettings": {
                    "servers": [],
                    "enableProxy": true
                },
                "basePolicy": {
                    "id": "[parameters('firewallPolicies_BaseSecurityPolicy_externalid')]"
                }
            }
        },

**Comment by AbelHu** [comment]
> The proper way to set DNS proxy is as below.
> 
> ```
> "resources": [
>     {
>         "type": "Microsoft.Network/firewallPolicies",
>         "apiVersion": "2020-05-01",
>         "name": "[parameters('firewallPolicies_DatabasePolicy_name')]",
>         "location": "eastus",
>         "properties": {
>             "threatIntelMode": "Deny",
>             "threatIntelWhitelist": {
>                 "ipAddresses": []
>             },
>             "dnsSettings": {
>                 "servers": [],
>                 "enableProxy": true
>             },
>             "basePolicy": {
>                 "id": "[parameters('firewallPolicies_BaseSecurityPolicy_externalid')]"
>             }
>         }
>     },
> ```

I will give a try. Thanks @timMSFT

**Comment by AbelHu** [comment]
@timMSFT If I use firewallpolicy, I cannot use traditional network rules and application rules. How can I use custom dns proxy settings with traditional rules?

https://docs.microsoft.com/en-us/azure/firewall-manager/policy-overview#traditional-rules-and-policies
Subject | Policy | Rules
-- | -- | --
Contains | NAT, Network, Application rules, custom DNS and DNS proxy settings, IP Groups, and Threat Intelligence settings (including allow list) | NAT, Network, and Application rules, custom DNS and DNS proxy settings, IP Groups, and Threat Intelligence settings (including allow list)

Error logs:

        error=Code="AzureFirewallPolicyAndRuleCollectionsConflict" Message="Request parameter Firewall Policy FirewallPolicy and Rule Collection NetworkRuleCollections cannot coexist for the Azure Firewall /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/azureFirewalls/xxx." Details=[]

**Comment by AbelHu** [comment]
Finally I found the solution. I really wish that there was a good document for it.
```
    "additionalProperties": {
      "Network.DNS.EnableProxy": "true"
    },
```
