### ISSUE TITLE
Sending bad credentials returns new Client instead of nil

### ISSUE THREAD

**Issue by kirankumarbv** [Azure/azure-sdk-for-go#1131]
Hi,

I have negative tests that tries to get a Client using bad credential ( bad subscription id, bad tenant id etc). All of these calls return a nil Client because the credentials are bad/invalid.
However when I call the below methods, I do not get a nil client. 

DNSRrsClient = dns.NewRecordSetsClient(creds.SubscriptionId)
DNSRrsClient.Authorizer = autorest.NewBearerAuthorizer(spToken)

The value of DNSRrsClient should have been nil but it instead has the value :=

&{{{0xc42027f860 0xc42017ac00 <nil> <nil> 1m0s 15m0s 3 30s Go/go1.9.3 (amd64-linux) go-autorest/v10.1.1 Azure-SDK-For-Go/v14.1.0 dns/2017-09-01 <nil> false} https://management.azure.com myBadSubscriptionID}}

This behavior is also seen with SubnetClient. Is this the expected behavior? If so why do I not see this with other clients?

**Comment by jhendrixMSFT** [comment]
In which packages do you get a nil client?  AFAIK all of our generated code returns the client by value so it can never be nil.

**Comment by kirankumarbv** [comment]
I apologize. We were using return by pointer. I got it confused with the sdk's behaviour.
 In all other cases, we were validating the client using the list method. If list fails, we would return nil. However in case of DNS list requires lot of arguments, so we were not validating it. Hence since there was no validation, there was no error within our method and therefore returning the client as is.

**Comment by jhendrixMSFT** [comment]
No worries!  I think there might be an easier way to verify the credentials.  After you create the service principal token you can call Refresh() on it and check for a non-nil error.  Something like this.
```go
	tenantID := os.Getenv("AZURE_TENANT_ID")
	oauthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantID)
	if err != nil {
		panic(err)
	}
	clientID := os.Getenv("AZURE_CLIENT_ID")
	clientSecret := os.Getenv("AZURE_CLIENT_SECRET")
	spToken, err = adal.NewServicePrincipalToken(*oauthConfig, clientID, clientSecret, azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		panic(err)
	}
	err = spToken.Refresh()
	if err != nil {
		panic(err)
	}
```
This used to hang and eventually fail however it should work now (you should get an adal.TokenRefreshError type back).  If you find bugs using this approach please open an issue in the [go-autorest repo](https://github.com/azure/go-autorest).

**Comment by kirankumarbv** [comment]
Thanks a lot. I will try that and open any issue if I find any.
