### ISSUE TITLE
SDK for Go v38.0.0 KV decryption latency

### ISSUE THREAD

**Issue by TonySh127-ms** [Azure/azure-sdk-for-go#11351]
### Bug Report
- import path of package in question https://github.com/Azure/azure-sdk-for-go 
- SDK version V38.0.0
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
keyValutAlgorithm = keyvault.RSA15
 
//Client is one interface to define Decrypt function
typeClientinterface {
Decrypt(ctx context.Context, vaultBaseURL string, keyName string, keyVersion string, parameters keyvault.KeyOperationsParameters) (result keyvault.KeyOperationResult, err error)
//Sign(ctx context.Context, vaultBaseURL string, keyName string, keyVersion string, parameters keyvault.KeySignParameters) (result keyvault.KeyOperationResult, err error)
}

agent: Go/go1.12.7 (amd64-linux) go-autorest/v13.3.0 Azure-SDK-For-Go/v38.0.0 keyvault

- output of `go version`
- What happened? Key Vault latency at May 27th 4:00 am -7:00 am UTC and June 21th 2:00 pm - 4:00 pm utc. The highest latency is 18 sec. It caused the client side not response
- What did you expect or want to happen? the decryption normally only need to take lower than 1 sec. 
- How can we reproduce it? 
it intermittent occurred. 
- Anything we should know about your environment. 
the issue occurred at multiple subscription at same time. 

I am from support side. If SDK PG can help to check the problem, I can ping you internally. The KV PG has suggest to upgrade the version of SDK. But they seem to have difficulty to upgrade their SDK version. So we would like to double check this version whether have any way to low the possibility for this latency problem

**Comment by ArcturusZhang** [comment]
Hi @TonySh127-ms thanks for this issue!

This looks like some behaviour on the service side rather than the SDK side.
Could you please provide more information about this issue? For instance, some code snippet that could reproduce this issue, and if you can provide some log it would be the best. To get the logs, you can export an environment variable `AZURE_GO_SDK_LOG_LEVEL=DEBUG`

**Comment by TonySh127-ms** [comment]
thanks @ArcturusZhang, we will explain with customer side to collect the debug log if it is possible from their end. I will also consult PG side to have further investigation at service side. Based on comment from PG, they still recommend to upgrade the SDK version.
