### ISSUE TITLE
Handle preview specs properly

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1136]
Right now in the https://github.com/Azure/azure-rest-api-specs specs go in 2 folders:
 - **stable** - spec is ready to be consumed and it is not expecting breaking changes.
 - **preview** - spec is ready to be consumed but breaking changes are acceptable and expected.

To handle this, for API version which are in the preview folder ( regardless if the api version is preview or not) we will put them in a `services/preview` folder.  NOTE:
  - everything here is expected to have breaking changes. We will mark this explicitly that semantic versioning does not apply here.
  - api versions that currently exist and need to be in preview folder will exist in 2 places (in the preview folder and outside). The path outside of the preview folder will be marked as deprecated and wont receive any updates.  At one point it will be removed.

**Comment by vladbarosan** [comment]
@jhendrixMSFT , @joshgav here is the issue for handling previews.

**Comment by jhendrixMSFT** [comment]
Scrub is done and merged into latest.
