### ISSUE TITLE
Add Azure Resource Manager support

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-sdk-for-go#114]
Need to include support for Azure Resource Manager

**Comment by ahmetalpbalkan** [comment]
@anweiss This is currently in progress. Most likely it will be auto-generated code and will go under `resourcemanager/` pkg.

**Comment by prabirshrestha** [comment]
looking forward to this. is it being worked on somewhere?

**Comment by ahmetalpbalkan** [comment]
@prabirshrestha currently internally. Hit me up on IM.

**Comment by mnbbrown** [comment]
@ahmetalpbalkan any update on this feature request?

**Comment by brendandixon** [comment]
We have a pre-alpha client with ARM Storage and Network support. However, it will be changing substantially.

**Comment by ahmetalpbalkan** [comment]
@anweiss @prabirshrestha @mnbbrown We have first bits of ARM generated code over at pull request #185. Please feel free to join in reviewing the looks of the generated code and provide input.

**Comment by ahmetalpbalkan** [comment]
@anweiss @prabirshrestha @mnbbrown first bits are now in master branch `arm` directory. Please take a look and give feedback as it is still alpha.

**Comment by ahmetalpbalkan** [comment]
This mostly happened. We now have a comprehensive set of Azure Resource Manager packages in `arm/` directory that are actively used by some projects already. Closing.
