### ISSUE TITLE
OSimage get operation fails.

### ISSUE THREAD

**Issue by aznashwan** [Azure/azure-sdk-for-go#115]
The osimage.Client.GetImageList() operation consistently fails with:

```
Get https://management.core.windows.net/<my-subscription-id>/services/images: local error: internal error
```

**Comment by aznashwan** [comment]
Update:
I get that for

**Comment by paulmey** [comment]
Thanks @aznashwan 
"local error" point to a transport level error (HTTPS/TLS)...
Is it just this method or all methods?
Are you using a proxy?

**Comment by aznashwan** [comment]
Hello @paulmey, and thanks for the response.

Yes, everything was returning the same 'internal server error' for me up to now.

Upon looking further into the matter, it seems the problem was on my end with the format and encoding of my certificates. Weirdly enough; it granted me access just fine but afterwards it kept yielding the above error.
It works fine with a .publishsettings file, unfortunately my application would not have much access for getting such a file too easily.

I do very much apologize for raising an issue prematurely.
Everything works fine now, and thanks a bunch for providing this sdk for us.

PS: if I could go as far as ask you specifically what certificate encoding Azure works best with?

**Comment by paulmey** [comment]
No problem. For certificate handling, we use the 'standard' go pem/tls crypto packages, so anything that those support should work. The reason for vendoring the tls and http packages is to support a renegotiation feature that Azure needs, but is not in the upstream go libraries yet.
See https://github.com/golang/go/issues/5742 for more info...

**Comment by aznashwan** [comment]
Thank you very much, and my apologies again for all the bother.
