### ISSUE TITLE
Error json parsing of RunCommandResultProperties.output

### ISSUE THREAD

**Issue by pussinboots** [Azure/azure-sdk-for-go#1150]
Hi,

i perform the RunCommand function with the following RunCommandInput

```go
	commandId := "RunShellScript"
	script := []string{"sudo su", "apt-get update", "apt-get -y upgrade",  "apt-get -y autoremove"}
	cmdInput := compute.RunCommandInput {
		CommandID: &commandId,
		Script : &script,
	}
```

And i get the following parsing error.
Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal array into Go struct field RunCommandResultProperties.output of type map[string]interface {}' JSON = '{
  "startTime": "2018-02-23T23:37:09.9890716+00:00",
  "endTime": "2018-02-23T23:37:49.2150194+00:00",
  "status": "Succeeded",
  "properties": {
    "output": [{"code":"ProvisioningState/succeeded","level":"Info","displayStatus":"Provisioning succeeded","message":"Enable succeeded: \n[stdout]\nHit:1 http://azure.archive.ubuntu.com/ubuntu xenial InRelease\nGet:2 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]\nGet:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]\nGet:4 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]\nHit:5 https://aptdocker.azureedge.net/repo ubuntu-xenial InRelease\nFetched 306 kB in 1s (247 kB/s)\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following packages have been kept back:\n  libdrm2\n0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.\nReading package lists...\nBuilding dependency tree...\nReading state information...\n0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.\n\n[stderr]\n"}]
  },
  "name": "2a474be7-b1f3-4fea-8182-c6765287d285"
}'

**Comment by jhendrixMSFT** [comment]
What version of the SDK are you using?  I believe this has been fixed in v14+, can you please try it?

**Comment by jhendrixMSFT** [comment]
Closing as this has gone stale.  If you upgrade to v14 and this still happens please reopen and we'll investigate.
