### ISSUE TITLE
Azure Batch: "Consumes" ignored when generating go code. Service calls fail

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-sdk-for-go#1159]
I'm currently working with the azure batch provider. The API requires a `content-type` of `application/json; odata=minimalmetadata` as defined [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/batch/data-plane/Microsoft.Batch/stable/2017-09-01.6.0/BatchService.json#L16) via `consumes` but the generated go code [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/batch/2017-09-01.6.0/batch/job.go#L159) doesn't take this into account and instead uses the `AsJson` perparer which sets `application/json`. 

I was going to add this as an issue on autorest but the readme directed me here as issues are turned off.

Currently I've worked around this by adding a `RequestInspector` which overwrites the `content-type` so not urgent on my part:

```go
	jobClient := batch.NewJobClientWithBaseURI(getBatchBaseUrl(batchConfig))
	jobClient.RequestInspector = LogRequest()

....

func LogRequest() autorest.PrepareDecorator {
	return func(p autorest.Preparer) autorest.Preparer {
		return autorest.PreparerFunc(func(r *http.Request) (*http.Request, error) {
			r.Header.Set("Content-Type", "application/json; odata=minimalmetadata")
			dump, _ := httputil.DumpRequestOut(r, true)
			log.Println(string(dump))
			return r, nil
		})
	}
}
```

**Comment by lawrencegripper** [comment]
Awesome, thanks. Should I download the latest generator and regenerate the service files then submit as a PR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jhendrixMSFT** [comment]
You certainly can however we'll have a refresh of the SDK later this month that will include this fix.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.0.0
