### ISSUE TITLE
Support custom headers for AKS

### ISSUE THREAD

**Issue by jmcshane** [Azure/azure-sdk-for-go#11692]
### Feature Request

Provide a way to specify aks-custom-headers during the creation of a cluster. This is required for setting OS level configuration as described [here](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration).

**Comment by kingli-crypto** [comment]
Any ETA?

**Comment by ArcturusZhang** [comment]
Hey @jmcshane and @kingli-crypto sorry for the delay of response.
Actually we have a way to send the request with customized headers like this (I am using a virtual machine client for demonstration here, but all clients are the same):
```
func main() {
	authorizer, err := auth.NewAuthorizerFromCLI()
	if err != nil {
		panic(err)
	}
	ctx := context.Background()
	client := compute.NewVirtualMachinesClient(subscriptionId)
	client.Authorizer = authorizer
	client.RequestInspector = autorest.WithHeader("header-key", "header-value")
	request := compute.VirtualMachine{}
	future, err := client.CreateOrUpdate(ctx, "group1", "vm1", request)
	if err != nil {
		panic(err)
	}
	if err := future.WaitForCompletionRef(ctx, client.Client); err != nil {
		panic(err)
	}
}
```

**Comment by tombuildsstuff** [comment]
@ArcturusZhang these aren't HTTP headers, but a Key-Value field in the request/response called "custom headers" iirc

**Comment by njuCZ** [comment]
@tombuildsstuff after refer to the azure cli and aks team, unfortunately it's actually HTTP headers...So may I ask your opinion about issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/6793? I am preparing a PR for it.

**Comment by njuCZ** [comment]
@tombuildsstuff after refer to the azure cli and aks team, unfortunately it's actually HTTP headers...So may I ask your opinion about issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/6793? I am preparing a PR for it.
