### ISSUE TITLE
Upload files to adls using go code

### ISSUE THREAD

**Issue by vasundhara785** [Azure/azure-sdk-for-go#11691]
### Service Package Request

Hi,

I want a sample go application to upload files from on premises to ADLS gen1 .

Thanks in advance.

**Comment by ArcturusZhang** [comment]
Hi @vasundhara785 thanks for this issue!

Unfortunately regarding on this topic I could only find [this documentation](https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-offline-bulk-data-upload), and by searching some of the key words, I do not find anything related in the current go SDK. This functionality should be supported by some data plane SDK of the datalake.

Hi @jhendrixMSFT do you know anything about the data plane SDK of datalake?

**Comment by jhendrixMSFT** [comment]
Hello!  We do have a package for datalake, you can find it here.

https://github.com/Azure/azure-sdk-for-go/tree/master/services/storage/datalake/2019-10-31/storagedatalake

Unfortunately we don't have a sample detailing how to use this package to upload/download content (the majority of the SDK is automatically generated from swagger files).

**Comment by vasundhara785** [comment]
Hello!!!

So yeah i have written my application using  https://github.com/Azure/azure-sdk-for-go/tree/master/services/datalake/store/2016-11-01/filesystem.Its working fine.!

Much thanks!!!

**Comment by ArcturusZhang** [comment]
Hi @vasundhara785 glad it works and if you do not mind I will then close this issue. Thanks!
