### ISSUE TITLE
Delete virtualnetworks.

### ISSUE THREAD

**Issue by aznashwan** [Azure/azure-sdk-for-go#117]
Not sure whether Set simply nuke-and-paves the current configuration and applies the new one, thus semi-providing this functionality.
If so, the docstrings could use an upgrade, if not, a Delete function would be awesome.

https://github.com/Azure/azure-sdk-for-go/blob/master/management/virtualnetwork/client.go

**Comment by ahmetalpbalkan** [comment]
@aznashwan there's no delete virtual network operation in the Azure REST APIs: https://msdn.microsoft.com/en-us/library/azure/jj157182.aspx

> ![image](https://cloud.githubusercontent.com/assets/159209/7582684/05cdff86-f845-11e4-9aa4-775043311637.png)

That's a known limitation of the API unfortunately. User is supposed to get the configuration, modify it and send it back. I have an outgoing feedback thread about this. Feel free to +1 here: http://feedback.azure.com/forums/217313-networking-dns-traffic-manager-vpn-vnet/suggestions/5954992-make-virtual-network-operations-atomic-on-portal-a

**Comment by aznashwan** [comment]
@ahmetalpbalkan thanks for the answer. Seems decent enough.
