### ISSUE TITLE
API for Deprecated versions

### ISSUE THREAD

**Issue by ncole** [Azure/azure-sdk-for-go#11764]
### Feature Request

Use case (version numbers are aribitrary, but recent):
* Deploy a Kubernetes cluster using 1.15.10
* After some time, 1.15.10 is deprecated because of a bug that is fixed in favor of 1.15.11.
* Clusters can only be made with versions 1.15.11, 1.15.12.

I would like to understand when my deployed 1.15.10 cluster is deprecated.  Either via `ManagedClusterProperties` or using the `UpgradeProfile`.

Thanks,
Nate

**Comment by lirenhe** [comment]
@ncole, from https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli, you could only get the supported Kubernets versions, I didn't see that info is included in ManagedClusterProperties or UpgradeProfile.
Please confirm the details in https://docs.microsoft.com/en-us/answers/topics/azure-kubernetes-service.html
Close this item as this is not related to SDK. Let me know if you have furthur questions.
