### ISSUE TITLE
Port discriminated types fixes in v2 generator to v3 generator

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1177]
The storage team needs support for discriminated types in the v3 generator.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT 👋 purely out of interest, what's the difference between the v2 and the v3 generators?

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff Hello!  In the v3 generator we've tried to make the underlying sending/receiving of the REST operation more configurable.  It dumps go-autorest in favor of a "pipeline" model and provides a lot more flexibility in how a request is sent/received over the wire (e.g. you can easily drop in your own retry policy handler).  Best bet would be to take a look at the new [azblob](https://github.com/azure/azure-storage-blob-go) package which is replacing the blob storage functionality in our current /storage package.  Specifically, take a look at [this](https://godoc.org/github.com/Azure/azure-storage-blob-go/2016-05-31/azblob#hdr-HTTP_Request_Policy_Factories) part of the docs for some info on the pipeline.  The pipeline package can be found [here](https://github.com/azure/azure-pipeline-go).

**Comment by jhendrixMSFT** [comment]
This has been fixed in the v3 generator.
