### ISSUE TITLE
[BUG][NEED HELP] Costmanagement Query wrong payload format (404 Bad request)

### ISSUE THREAD

**Issue by rayanebel** [Azure/azure-sdk-for-go#11869]
Hello,

I'm trying to make a query on Azure Cost Management service by using the API and the Golang SDK. When I tried to execute it I have a `Bad Request` error and I don't understand what's going on.

Here you can find my code:

```go
	costQueryClient := costmanagement.NewQueryClient(subscriptionID)
	costQueryClient.Authorizer = authorizer
	queryAggregation := make(map[string]*costmanagement.QueryAggregation)
	queryAggregation["totalCost"] = &costmanagement.QueryAggregation{
		Name:     to.StringPtr("PreTaxCost"),
		Function: to.StringPtr("Sum"),
	}
	queryAggregation["totalCostUSD"] = &costmanagement.QueryAggregation{
		Name:     to.StringPtr("PreTaxCostUSD"),
		Function: to.StringPtr("Sum"),
	}

	queryDefinition := costmanagement.QueryDefinition{
		Type:       to.StringPtr("ActualCost"),
		Timeframe: costmanagement.MonthToDate,
		Dataset: &costmanagement.QueryDataset{
			Granularity: costmanagement.Daily,
			Aggregation: queryAggregation,
			Filter: &costmanagement.QueryFilter{
				And: &[]costmanagement.QueryFilter{
					{
						Dimension: &costmanagement.QueryComparisonExpression{
							Name:     to.StringPtr("ResourceType"),
							Operator: to.StringPtr("In"),
							Values:   to.StringSlicePtr([]string{"microsoft.compute/virtualmachinescalesets"}),
						},
					},
					{
						Dimension: &costmanagement.QueryComparisonExpression{
							Name:     to.StringPtr("ResourceId"),
							Operator: to.StringPtr("In"),
							Values:   to.StringSlicePtr(vmssList),
						},
					},
				},
			},
		},
	}

        result, err := costQueryClient.Usage(context.Background(), scope, queryDefinition)
```

Here you can find the error:

```
costmanagement.QueryClient#Usage: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadRequest\" Message=\"Invalid query definition: Invalid dataset filter; on a QueryFilter one and only one of and/or/not/dimension/tag can be set.\\r\\nInvalid dataset filter; on a QueryFilter one and only one of and/or/not/dimension/tag can be set.\\r\\n\\r\\n (Request ID: 50bd37a4-d480-4f24-ac3d-22adfe1a63d8)
```

I don't understand where is my error because, when I tried to make my query from the Azure Portal and retrieve the `http requests` from the developer console I have the same payload format _(only a difference on dimension key which is in plural)_.

**EDIT**: When I print the payload of my query in JSON format I have the following data:

```json
{
  "type": "ActualCost",
  "timeframe": "MonthToDate",
  "dataset": {
    "aggregation": {
      "totalCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      },
      "totalCostUSD": {
        "name": "PreTaxCostUSD",
        "function": "Sum"
      }
    },
    "filter": {
      "and": [
        {
          "dimension": {
            "name": "ResourceType",
            "operator": "In",
            "values": [
              "microsoft.compute/virtualmachinescalesets"
            ]
          }
        },
        {
          "dimension": {
            "name": "ResourceId",
            "operator": "In",
            "values": [
              "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/MC_xxxxxx-devweu-blue_bluedevweu-blue_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-linux-12345678-vmss"
            ]
          }
        }
      ]
    },
    "granularity": "Daily"
  }
}
```

And when I try to compare with the payload in the browser I don't have the same keys structure. For example, I have the key `dimensions` in the And filter and not `dimension` in my payload. And when I checked the `costmanagement.QueryFilter` I see for the dimension property a json tag `dimension`.

Here you can find the payload retrieve from my web browser with the query made with Azure portal

```json
{
  "type": "ActualCost",
  "dataSet": {
    "granularity": "Daily",
    "aggregation": {
      "totalCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      },
      "totalCostUSD": {
        "name": "PreTaxCostUSD",
        "function": "Sum"
      }
    },
    "filter": {
      "And": [
        {
          "Dimensions": {
            "Name": "ResourceType",
            "Operator": "In",
            "Values": [
              "microsoft.compute/virtualmachinescalesets"
            ]
          }
        },
        {
          "Dimensions": {
            "Name": "ResourceId",
            "Operator": "In",
            "Values": [
              "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/MC_xxxxxx-devweu-blue_bluedevweu-blue_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-linux-12345678-vmss"
            ]
          }
        }
      ]
    }
  },
  "timeframe": "MonthToDate"
}
```

Can you help me ?

`go version: go 1.14`
`costmanagement api version: 2019-10-01`

Thanks.

**Comment by rayanebel** [comment]
Ping!
Anyone have any idea about my problem ?

**Comment by AdityaIIITB** [comment]
Im seeing the exact issue with python sdk too.

**Comment by ramaganesan-rg** [comment]
Team is investigating the issue. Will get back to you.  thank you for your feedback.

**Comment by jochav** [comment]
Try using dimensions instead of dimension:

`{
  "type": "ActualCost",
  "timeframe": "MonthToDate",
  "dataset": {
    "aggregation": {
      "totalCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      },
      "totalCostUSD": {
        "name": "PreTaxCostUSD",
        "function": "Sum"
      }
    },
    "filter": {
      "and": [
        {
          "**dimensions**": {
            "name": "ResourceType",
            "operator": "In",
            "values": [
              "microsoft.compute/virtualmachinescalesets"
            ]
          }
        },
        {
          "**dimensions**": {
            "name": "ResourceId",
            "operator": "In",
            "values": [
              "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/MC_xxxxxx-devweu-blue_bluedevweu-blue_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-linux-12345678-vmss"
            ]
          }
        }
      ]
    },
    "granularity": "Daily"
  }
}
`

**Comment by ramaganesan-rg** [comment]
Hi Aditya, thank you for the feedback. May I go ahead to archive the request, if there are no further questions? please let us know.
