### ISSUE TITLE
Provide example for listing subscriptions in a tenant

### ISSUE THREAD

**Issue by lukibahr** [Azure/azure-sdk-for-go#11868]
### Feature Request

Could you provide a sample for listing subscriptions in a tenant? made it work by using manual api calls, but not using the azure-sdk.

Thanks in advance

**Comment by ArcturusZhang** [comment]
Hi @lukibahr thanks for this issue!

You could find an example using this SDK in #11574 . To get a program calling pure REST API, you could just run that example by exporting environment variable `AZURE_GO_SDK_LOG_LEVEL=DEBUG`, and the REST API URL as well as its payload would be displayed to stdout, then you could use those information to write your own program using your own http client (you will have to get your credential header).

Hope this would help.

**Comment by lukibahr** [comment]
Thank you @ArcturusZhang ! 

Got a list of subscriptions, where a service principal is mapped on with the following go function:

`func listSubscriptions(authorizer autorest.Authorizer, ctx context.Context) {
	client := subscriptions.NewClient()
	client.Authorizer = authorizer
	resp, err := client.List(ctx)
	if err != nil {
		fmt.Print(err)
	}
	for _, r := range resp.Values() {
		subscriptionId := *r.SubscriptionID
		subscriptionName := *r.DisplayName
		log.Printf("found subscription %s with id %s ", subscriptionId, subscriptionName)

	}
}
`

**Comment by lukibahr** [comment]
issue closed as the thread above solved the problem.
