### ISSUE TITLE
Azure Identity Extensions Support for using Go Azure.Identity with Track-1 SDKs

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#11870]
Filing a tracking issue to investigate adding Go support for Azure Identity Extensions, and to see if there is any general feedback on the tracking issue from the community (e.g., is there a need)

https://github.com/jongio/azidext#azure-identity-extensions

> Azure Identity Extensions
> This repo is a place for us to share ideas and extensions to the Azure Identity libraries.
> 
> DISCLAIMER: The code in this repo is not officially supported or intended for production use. The intention of this repo it to unblock customers who would like to use the Azure.Identity capabilities in the Fluent, Resource Management, and Service Bus SDKs before they have been migrated to the new SDK Azure.Core and officially support TokenCredential. We have included minimal tests in this repo, so please take it upon yourself to fully test this code to ensure it works in your environment.
> 
> Languages
> We currently have included examples for .NET, Java, JavaScript/TypeScript, and Python. Please file an issue if you would like examples for other languages as well.
> 
> Usage
> The classes contained in this repo are only meant to be a temporary stopgap between now and when the Resource Management, Fluent, and Service Bus SDKs support Azure.Core. Since those efforts are currently underway, we think it would be best for you to copy the classes in this project to your class instead of releasing them via a package manager.
> 
> Clone the repo git clone https://github.com/jongio/azidext
> Either reference the project or copy the classes you need into your solution.

**Comment by jhendrixMSFT** [comment]
Done.  Released as module github.com/jongio/azidext/go/azidext
