### ISSUE TITLE
Support for Tags CreateOrUpdateAtScope (resources API Version: 2019-10-01)

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/azure-sdk-for-go#11879]
### Feature Request

I don't see the 2019-10-01 API version for resources in https://github.com/Azure/azure-sdk-for-go/tree/master/services/resources/mgmt. I need it for CreateOrUpdate for tags (https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdateatscope). I am missing something or has support not been added yet?

**Comment by ArcturusZhang** [comment]
Hi @CecileRobertMichon thanks for this issue!

The package will soon be released after [this PR](https://github.com/Azure/azure-rest-api-specs/pull/10249) is merged

**Comment by CecileRobertMichon** [comment]
Perfect thank you @ArcturusZhang !

**Comment by CecileRobertMichon** [comment]
/close

this is fixed in the latest release
