### ISSUE TITLE
hdinsight.AutoscaleConfigurationUpdateParameter omits empty Autoscale

### ISSUE THREAD

**Issue by kosinsky** [Azure/azure-sdk-for-go#11967]
### Bug Report

- import path of package in question, e.g. `...services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight`
- SDK version `latest`
  - new type was introduced in https://github.com/Azure/azure-sdk-for-go/pull/11841/
- output of `go version` `go version go1.14 darwin/amd64`

Autoscale field defined with `omitempty`
```go
type AutoscaleConfigurationUpdateParameter struct {
	// Autoscale - The autoscale configuration.
	Autoscale *Autoscale `json:"autoscale,omitempty"`
}
```
As a result when setting it to `nil` it will be serialized to `{}` instead of `{autoscale: null}` which is required by autoscale REST API to disable the autoscale:
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-autoscale-clusters#using-the-rest-api

**Comment by aim-for-better** [comment]
I am checking.

**Comment by aim-for-better** [comment]
@kosinsky  Yes the null property was emitted in json. But both `{}` and `{"autoscale": null}` can disable autoscale successfully.

Thanks for this issue. We will update the doc as soon as possible.

**Comment by aim-for-better** [comment]
@kosinsky  Could you please confirm that `{}` can work or not from you side?

**Comment by kosinsky** [comment]
@aim-for-better `{}` worked for me too. Could documentation at https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-autoscale-clusters#using-the-rest-api be updated to avoid confusion for next person?

**Comment by deshriva** [comment]
@kosinsky Thanks for the feedback. We usually document a way that is easily understood by all our customers (beginners and/or advanced). The document is listing one of the ways to disable autoscale, there can be other ways, like in this case {}. I would like to understand why was it confusing as both would have worked?

**Comment by ArcturusZhang** [comment]
Hi @kosinsky for your information, the current implementation of the go SDK generator has a shortage that we cannot support `null` in update. Please refer [this issue](https://github.com/Azure/autorest.go/issues/432) for further details.

**Comment by aim-for-better** [comment]
Hi @kosinsky , Thanks for your feedback .Although the go sdk can work well for disabling autoscale , so I just close it.
Let's use [this issue](https://github.com/Azure/autorest.go/issues/432)  to address emitting null property issue.
