### ISSUE TITLE
resources: pin API version

### ISSUE THREAD

**Issue by Segflow** [Azure/azure-sdk-for-go#12077]
### Feature Request

Unlike other clients, the `resources.Client` [methods](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources) all expect an APIVersion parameter, which can be pinned like in the other clients.

**Comment by ArcturusZhang** [comment]
Hi @Segflow thanks for this issue!

Unfortunately those api-versions are by-designed and we will not fix them to a constant value.

I am going to take `CreateOrUpdateByID` as an example. The signature is 
```
func (client Client) CreateOrUpdateByID(ctx context.Context, resourceID string, APIVersion string, parameters GenericResource) (result CreateOrUpdateByIDFuture, err error)
```
This function consumes a `resourceID`, an `APIVersion` and a resource parameter.

This method is used to create **any resource from any RP** by using the given ID and APIVersion. Internally, it will call the actual API from another RP, therefore an api-version is needed and the SDK has no knowledge to infer it.

Taking a concrete example, for instance you want to use resources API to create a VM, you will need to first know the resource ID  of the desired VM, 
```
resourceID = "/subscriptions/0000000-0000-0000-0000-0000000000/resourceGroups/group1/providers/Microsoft.Compute/virtualMachines/vm1"
```
and then you will need to know the api-version of the compute package you want to invoke via the resources API, for instance `2020-06-01`, and finally give it a struct of the VM definition. This API call is equivalent to call the compute API
```
PUT /subscriptions/0000000-0000-0000-0000-0000000000/resourceGroups/group1/providers/Microsoft.Compute/virtualMachines/vm1?api-version=2020-06-01
```

As a reference, you could see the internal processing [here](https://github.com/Azure/azure-sdk-for-go/blob/a8a32631dae031e89decdb4a2a8e8c4e3df36f54/services/resources/mgmt/2019-05-01/resources/resources.go#L356): this function call is equivalent to calling a compute REST API in our example.

Hope this could answer your question, thanks!
