### ISSUE TITLE
Provide SDK for getting federation metadata XML file, please

### ISSUE THREAD

**Issue by artem-shcherbatyuk-sp** [Azure/azure-sdk-for-go#12180]
### Feature Request
In Azure Enterprise application we have XML metadata file which is used to configure SAML access to AWS Role.

For now Azure Golang SDK doesn't support getting this file, so we can get it only via GET request.
```
https://login.microsoftonline.com/<TenantDomainName>/FederationMetadata/2007-06/FederationMetadata.xml?appid=<AzureAppID>
```

Is there any chance that we will get it in SDK?

P.S. We need this file to map Azure App to AWS Identity Provider. 
Maybe the main question is **how to get known which AWS Identity Provider corresponds to Azure Enterprise Application?**

**Comment by ArcturusZhang** [comment]
Hi @artem-shcherbatyuk-sp thanks for this issue!

From the endpoint, this looks like an API related with authentication. @jhendrixMSFT could you please comment on this?

**Comment by chlowell** [comment]
> Is there any chance that we will get it in SDK?
> 

It's not in our current plans and to my knowledge no one else has asked for it. At first glance I don't see where it would fit in the Azure SDK or how a client would be better than a simple GET here. The endpoint is intended to provide this metadata to anyone who wants it, so it doesn't require authentication, its format is documented, and it doesn't--so far as I can tell, anyway--expose an API for managing or modifying the metadata.

I'm not familiar with your scenario though. Can you describe it in some more detail? How would you use a client that fetches this metadata? Would you expect the client to do anything more?
