### ISSUE TITLE
Add support for MSI resource ID

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-go#12184]
Similar to: https://github.com/Azure/go-autorest/pull/544

**Comment by catalinaperalta** [comment]
More info: https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet

**Comment by catalinaperalta** [comment]
Cross-language design pending

**Comment by jhendrixMSFT** [comment]
Required for AKS.
