### ISSUE TITLE
Permission denied with user managed identity

### ISSUE THREAD

**Issue by rishabhjaisw** [Azure/azure-sdk-for-go#12181]
**Describe the bug**
Azure go sdk code gives permission denied for VMSS scale out/in when user managed identity is attached to the VM, but same VMSS scale out/in works with Azure cli commands with same user managed identity.

Role assigned to user managed identity - virtual machine contributor role for resource sparkworkers-vmss

These azure cli commands are working without any issue,
az login --identity -u <user_identity_id>
az vmss scale --name sparkworkers-vmss --resource-group <rg_name> --new-capacity 4

No permission denied issue for above command.

we tried 2 ways with Azure go sdk code, both did not work.
1> Using NewAuthorizerFromEnvironment() in code for autorization and setting env variable AZURE_CLIENT_ID=<user_identity_id>
2> Using NewAuthorizerFromCLI() in go code for autorization. Logged in with az cli login (az login --identity -u <user_identity_id>) before running the go code.

Both are giving read permission denied for images, managed identity assigned action and subnet join action.

**Expected behavior**
Azure go sdk should not give any permission denied error as both az cli and go sdk are using same user managed identity.

**Environment:**
 - az version
{
  "azure-cli": "2.8.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.8.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
 - azure go sdk package
"github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute"
"github.com/Azure/azure-sdk-for-go/services/keyvault/auth"

**Comment by ArcturusZhang** [comment]
Hi @rishabhjaisw thanks for this issue!

Actually neither `NewAuthorizerFromEnvironment()` nor `NewAuthorizerFromCLI()` is designed for the MSI authentication and sorry that we did not include this authorization flow in the documentation. But you could refer to [this code snippet as an example](https://github.com/hashicorp/go-azure-helpers/blob/9d4c9e656897742c8dae85299b72c4ea973170b2/authentication/auth_method_msi.go#L44) that are using in terraform.

Hope this would help, thanks.

**Comment by thebenwaters** [comment]
It looks go-autorest

https://godoc.org/github.com/Azure/go-autorest/autorest/azure/auth#NewMSIConfig

Supports MSI
