### ISSUE TITLE
Cosmos db DatabaseAccountGetResults capability is not returning all types of capabilities

### ISSUE THREAD

**Issue by sburnwal** [Azure/azure-sdk-for-go#12229]
### Bug Report

- import path of package in question "github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2019-12-12/documentdb"
- SDK version 39.1
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`
go version go1.11 linux/amd64

- What happened?
Not able to get all the EnabledApiTypes that are returned by REST API when querying cosmos account DatabaseAccountGetResults

- What did you expect or want to happen?
Cosmos account can have multiple EnabledApiTypes. For example when I create Cosmos account of type Gremlin, it has EnabledApiTypes = Gremlin, Sql. But when use the GO SDK to query it, Capabilities returns only Gremlin. So is the case with Cosmos account of type Azure table 

- How can we reproduce it?
Create Cosmos account with type Gremlin.

- Anything we should know about your environment.
No

**Comment by MehaKaushik** [comment]
Hey @sburnwal Capabilities indicates the current account's capabilities. The account in picture is a Gremlin account, hence its capabilities would include EnableGremlin. EnabledApiTypes is not a supported param for REST API for CosmosDB ResourceProvider. (Please note Resource Provider operations are Control Plane operations.)
Our REST API are described here https://docs.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/databaseaccounts

Please let me know if this helps and if you have any more queries.

**Comment by sburnwal** [comment]
When I create Private Endpoint for a Gremlin Cosmos account, it is asking me to choose 'Gremlin' or 'Sql' as the sub resource. From the Go SDK I do get the 'EnableGremlin' as the capability. Which API will also give me the other sub resource type 'Sql' ?

**Comment by MehaKaushik** [comment]
Sql is the default API, so you dont need to set any capability for it.

**Comment by MehaKaushik** [comment]
Hey @sburnwal I hope your questions were answered. I am closing this issue, please re-open this if you have more queries.
