### ISSUE TITLE
oauth2AllowIdTokenImplicitFlow separate from oauth2AllowImplicitFlow

### ISSUE THREAD

**Issue by brondum** [Azure/azure-sdk-for-go#12249]
### Feature Request
**Azure AD Applications**
The ability to specify only ID tokens when using Implicit flow, as both the GUI and Manifest spec allows in Azure.

Would be extremely useful from the terraform-provider-azuread, as we could specify that we only want to enable implicit flow for the ID tokens.

The manifest spec: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#oauth2allowidtokenimplicitflow-attribute

Similar, but closed feature request: https://github.com/Azure/azure-sdk-for-go/issues/4478

A pending terraform-provider-azuread feature request: https://github.com/terraform-providers/terraform-provider-azuread/issues/163

**Comment by ArcturusZhang** [comment]
Hi @brondum thanks for this issue!

Unfortunately this feature should belong to MS-graph, which is not supported in this SDK. I have heard they have a plan, but I do not know any timeline of this.

There is a community contributed swagger PR for ms-graph [here](https://github.com/Azure/azure-rest-api-specs/pull/10275), you could also track this PR for any progress.

@jhendrixMSFT do you know if they have any more progress on the go SDK of ms-graph?

**Comment by lirenhe** [comment]
@brondum, Msgraph team has their repo https://github.com/microsoftgraph/msgraph-metadata for the api definition.
As the SDK of msgraph is not handled in this repo, please contact MSGraph team directly.
