### ISSUE TITLE
Support Querying metrics for multiple resources

### ISSUE THREAD

**Issue by vipinvkmenon** [Azure/azure-sdk-for-go#12252]
### Support Querying metrics for multiple resources

This may well already be possible, however, I was not able to find or understand.

Is it possible to get metrics of multiple resources in a single call/query?

For eg. metrics for a list of VMs.
or 
metrics for set of VMs of a given resource-group / subscription?

**Comment by ArcturusZhang** [comment]
Hi @vipinvkmenon thanks for this issue.

I am not quite sure what is metrics referring for, but as far as I know, Azure only supports get the instance view of one VM at a time.
You could LIST the VMs in a resource group or subscription, but it gives less information than instance view.

**Comment by vipinvkmenon** [comment]
Hi @ArcturusZhang .

Maybe I'll give you a context.

Coming from the AWS world.....
If I were to run the command
```
aws cloudwatch list-metrics --namespace AWS/EC2 --metric-name CPUUtilization
```

From Cloudwatch I would get the metric-value CPUUtilization for all the VMS present that particular region. 
And if run
```
aws cloudwatch list-metrics --namespace AWS/EC2 
```
Then all metrics related to VMs (at that time-instant)
(the cli is preconfigured with the region along with Credentials)

In their SDK the function is [GetMetricData](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.GetMetricData).

In the AZURE world, I would imagine something similar to this under Resource-Groups (if not subscriptions)?

For now, It looks like I would have to get the list of all resources and then Loop through each resource for the resource ID and then get the metrics, Which seems like a lot of API calls and a non-elegant idea... Hence the question.

Is there a better way to approach. (I may have failed to find the right APIs maybe?)

**Comment by Drewm3** [comment]
For general metrics the Azure Monitor team is the right team to answer these questions.

**Comment by yummydsky** [comment]
Hi @scottaddie any update for batch query metrics API?
We need this feature to resolve the performance issue when we heavily use the Metrics APIs.

**Comment by gracewilcox** [comment]
> Hi @scottaddie any update for batch query metrics API? We need this feature to resolve the performance issue when we heavily use the Metrics APIs.

Hi @yummydsky! We released the first beta for metrics batch query yesterday. You can use this feature with azquery [v1.2.0-beta.1](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery@v1.2.0-beta.1).

**Comment by yummydsky** [comment]
@gracewilcox Thank you!!! We will try this feature to see if it can enhance the performance. Thanks again!!
