### ISSUE TITLE
Can't create DataDisk with `compute.CachingTypesReadWrite` or `compute.StorageAccountTypesStandardSSDLRS`

### ISSUE THREAD

**Issue by nyetwurk** [Azure/azure-sdk-for-go#12309]
### Bug Report

`github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute`

`github.com/Azure/azure-sdk-for-go v40.6.0+incompatible`

go1.14.6

```golang
	vm.StorageProfile.DataDisks = &[]compute.DataDisk{{
		Lun:          to.Int32Ptr(0),
		Name:         to.StringPtr(diskName),
		CreateOption: compute.DiskCreateOptionTypesEmpty,
		DiskSizeGB:   to.Int32Ptr(sizeGB),
		Caching:      compute.CachingTypesReadWrite, // doesn't work
		ManagedDisk: &compute.ManagedDiskParameters{ // doesn't work
			StorageAccountType: compute.StorageAccountTypesStandardSSDLRS,
			ID:                 &id,
		},
	}}
```
I still end up with `CachingTypesNone` and `StandardHDD`

**Comment by nyetwurk** [comment]
I'm guessing those parameters are read only and have to create a storage account first with `storageAccountsClient.Create()`?

**Comment by jaylabell** [comment]
@Drewm3 Do you mind taking a look at this issue please?

**Comment by Drewm3** [comment]
Correct, you only need to set the storage account type in the VM create. No storageAccountClient.Create() is needed.
