### ISSUE TITLE
DefaultAzureCredentials availability 

### ISSUE THREAD

**Issue by toklive** [Azure/azure-sdk-for-go#12365]
Looking for capabilies mentioned in the following blog,  https://devblogs.microsoft.com/azure-sdk/authentication-and-the-azure-sdk/. It seems Go SDK is not mentioned there. Any update on it?

**Comment by ArcturusZhang** [comment]
Hi @toklive thanks for this issue!

Based on the documentation link in this blog, I assume this `DefaultAzureCredentials` should come from `Azure.Identity` namespace, which belongs to go SDK track 2. @jhendrixMSFT could you please share some comment about this?

**Comment by jhendrixMSFT** [comment]
You are correct, this will be released as a part of `azidentity`.  We have released an early alpha, you can find it [here](https://github.com/Azure/azure-sdk-for-go/tree/master/sdk/azidentity) if you're curious.  It's not ready for general consumption, and you need an adapter to make it work with our track 1 SDK.

**Comment by murarisumit** [comment]
@jhendrixMSFT is`DefaultAzureCredentials`  ready for general consumption ?

**Comment by jhendrixMSFT** [comment]
It's still in preview but should be stable, both in terms of public surface area and execution.

**Comment by RickWinter** [comment]
Available in preview
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity
