### ISSUE TITLE
Add support for the Microsoft Security Center API

### ISSUE THREAD

**Issue by russellds** [Azure/azure-sdk-for-go#1246]
Please add support for the Microsoft Security Center API to allow down level tools such as Terraform. 

API: https://management.azure.com/subscriptions/{Subscription_ID}/providers/microsoft.Security/policies/default?api-version=2015-06-01-preview

**Comment by joshgav** [comment]
Thanks @russellds, we'll look into how to support this API. It's documented at https://msdn.microsoft.com/library/mt704034(Azure.100).aspx but doesn't appear to be specified in the [Azure REST specs](https://github.com/Azure/azure-rest-api-specs) repo.

**Comment by joshgav** [comment]
Looks like we need to add a directive to the spec so the Go lib is generated: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/readme.md.

cc @vladbarosan

**Comment by vladbarosan** [comment]
Blocked on https://github.com/Azure/azure-sdk-for-go/issues/2293

**Comment by vladbarosan** [comment]
@russellds this is available now in the latest branch https://github.com/Azure/azure-sdk-for-go/tree/latest/services/preview/security/mgmt/2017-08-01-preview/security
In the next minor release it will be available.

**Comment by vladbarosan** [comment]
This has been released in [v19.10](https://github.com/Azure/azure-sdk-for-go/tree/v19.1.0/services/preview/security/mgmt/2017-08-01-preview/security)
