### ISSUE TITLE
Unused SubscriptionID1 field added in 43.0.0?

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-sdk-for-go#12534]
### Bug Report

In 43.0.0 (4f14e3d53f), it seems that a new unused SubscriptionID1 field was added in some clients, e.g. at https://github.com/Azure/azure-sdk-for-go/blame/master/services/cosmos-db/mgmt/2019-08-01/documentdb/client.go#L37

This seems to be entirely unused and is erroneous.  Do `grep -r SubscriptionID1` to see what I mean.

Can it be reverted in a future API version?

**Comment by MehaKaushik** [comment]
@jim-minter thanks for pointing this out. This was removed in our most recent api-version https://github.com/Azure/azure-sdk-for-go/blob/master/services/cosmos-db/mgmt/2020-04-01/documentdb/client.go

**Comment by ArcturusZhang** [comment]
Hi @jim-minter since this should have been resolved in the new version, I will then close this issue, please feel free to reopen or comment if you have other concerns

**Comment by jim-minter** [comment]
What I meant was, please could a future version of azure-sdk-for-go revert the change made such that *no* cosmosdb api-version client should erroneously have a SubscriptionID1 field in NewDatabaseAccountsClient?

**Comment by jim-minter** [comment]
@ArcturusZhang ^

**Comment by ArcturusZhang** [comment]
Hi

**Comment by MehaKaushik** [comment]
Thanks @ArcturusZhang  for the fix.

**Comment by ArcturusZhang** [comment]
Well, despite the PR in the swaggers would fix this in theory, it would not take effect until we regenerate the impacted packages. Therefore @MehaKaushik could you please open a release request after the fix is merged?
