### ISSUE TITLE
Add missing properties to BlobServicePropertiesProperties

### ISSUE THREAD

**Issue by sirlatrom** [Azure/azure-sdk-for-go#12547]
### Feature Request

https://github.com/Azure/azure-sdk-for-go/blob/master/storage/blobserviceclient.go implements the Blob Service Properties client including operations listed on [https://docs.microsoft.com/en-us/rest/api/storageservices/operations-on-the-account--blob-service-](https://docs.microsoft.com/en-us/rest/api/storageservices/operations-on-the-account--blob-service-).

However, the SDK does not currently implement fields such as `Logging`: https://github.com/Azure/azure-sdk-for-go/blob/e906ecd90d7cfeb084f91ede091657b1223cf068/services/storage/mgmt/2019-06-01/storage/models.go#L1061-L1079.

This prevents https://github.com/terraform-providers/terraform-provider-azurerm/issues/3581 from moving forward.

**Comment by ArcturusZhang** [comment]
Hi @sirlatrom thanks for this issue.

The go SDK in `services` directory is generated from `azure-rest-api-specs`, and I did not find any property that related with `logging` [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01). Therefore unfortunately we cannot help on this.

As for this client: https://github.com/Azure/azure-sdk-for-go/blob/master/storage/blobserviceclient.go, this is the data plane storage SDK (and this is in maintenance mode). CCing @jhendrixMSFT for more information about this data plane storage SDK.

Also as far as I know, terraform is not using the `storage` directory in `azure-sdk-for-go` but [this library](https://github.com/tombuildsstuff/giovanni) for storage data plane. Maybe you also need a feature request there.

**Comment by sirlatrom** [comment]
@ArcturusZhang Thank you for directing me to the right place, you are of course completely right that I should go to the https://github.com/tombuildsstuff/giovanni library instead.
