### ISSUE TITLE
Create Auto Release Notes Script

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-go#12552]
Take this .NET script that Pavel created and adapt it to Go

https://github.com/Azure/azure-sdk-for-net/blob/master/eng/scripts/Collect-Changelogs.ps1

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT could you please help on this?

**Comment by ArcturusZhang** [comment]
I am not sure whether exactly the same thing but we now also have changelogs per package, for instance: https://github.com/Azure/azure-sdk-for-go/blob/master/services/aad/mgmt/2017-04-01/aad/CHANGELOG.md

**Comment by tombuildsstuff** [comment]
@ArcturusZhang is there any plan to add behavioural differences to those changelogs?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang is there any plan to add behavioural differences to those changelogs?

If the behavioural differences mean the change of a service behaviour, I am afraid we currently do not have any approach to get this change unfortunately. From the perspective of the SDK, the only differences we could get is the differences on the interfaces/signatures

**Comment by weshaggard** [comment]
Tracking the general work with Azure/azure-sdk#1694
