### ISSUE TITLE
Add application.AddPassword

### ISSUE THREAD

**Issue by Segflow** [Azure/azure-sdk-for-go#12562]
### Feature Request

The API https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http is not implemented in the current SDK.

The current workflow is to use "UpdatePasswordCredentials" and provide a secret. Would be great if we can add that API to the sdk.

**Comment by ArcturusZhang** [comment]
Hi @Segflow thanks for this issue.

Unfortunately the whole ms-graph SDK will not be included in this repo (as far as I know). You could find some unofficial SDK of msgraph for go on github, for instance [this one](https://github.com/yaegashi/msgraph.go) or [this one](https://github.com/open-networks/go-msgraph).

The msgraph officially does not have golang planned as far as I know. CCing @jhendrixMSFT for some more information

**Comment by lirenhe** [comment]
Close it as ms-graph SDK will not be included in this repo.
