### ISSUE TITLE
How to add a VMSS to a backend pool of an Azure Loadbalancer using the SDK?

### ISSUE THREAD

**Issue by erstaples** [Azure/azure-sdk-for-go#12564]
I found [this issue](https://github.com/Azure/azure-sdk-for-go/issues/6504) regarding adding individual VMs to a backend pool, but the code examples do not seem applicable to scale sets. Can this be easily done?

**Comment by ArcturusZhang** [comment]
Hi @erstaples thanks for this issue!

To do this with go SDK, you will have to first use a GET function to get the definition of the VMSS, and append a new backendAddressPool Id to this slice [`vmss.VirtualMachineScaleSetProperties.VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations.IPConfigurations.VirtualMachineScaleSetIPConfigurationProperties.LoadBalancerBackendAddressPools`](https://github.com/Azure/azure-sdk-for-go/blob/8b1ae49e53332c534e4263b4d4160aeb81d9d497/services/compute/mgmt/2020-06-01/compute/models.go#L11575)
