### ISSUE TITLE
Authorization ClassicAdministrator Query Returns 404 Namespace Not Found

### ISSUE THREAD

**Issue by thinkjk** [Azure/azure-sdk-for-go#12580]
### Bug Report

- import path of package:  https://github.com/Azure/azure-sdk-for-go/tree/master/services/authorization/mgmt/2015-07-01/authorization
- SDK version: master

I'm trying to get the results from ListComplete from ClasicAdministrators. Currently the go SDK is returning a 404, though the CLI returns the list of classic administrators correctly. Upon further debugging both via CLI and https://docs.microsoft.com/en-us/rest/api/authorization/classicadministrators/list#code-try-0 I get a 404 return with the following error 

```json
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'classicAdministrators' could not be found in the namespace 'Microsoft.Authorization' for api version '2015-07-01'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01'."
  }
}
```
Looking through github I only see the 2015-07-01 path and not any of the supported ones listed as working in the error message. 

Thank you.

Edit. This works correctly using the preview package: https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/authorization/mgmt/2018-09-01-preview/authorization

**Comment by ArcturusZhang** [comment]
Hi @thinkjk thanks for this issue.

By checking the code, I did not see anything suspicious and BTW the preview package 2018-09-01-preview actually is using [2015-06-01](https://github.com/Azure/azure-sdk-for-go/blob/8b1ae49e53332c534e4263b4d4160aeb81d9d497/services/preview/authorization/mgmt/2018-09-01-preview/authorization/classicadministrators.go#L88).

Could you please provide some more information including some request logging? The logging could enable by setting the environment variable `AZURE_GO_SDK_LOG_LEVEL=DEBUG`?
