### ISSUE TITLE
Security Center Automations - fields required by the API are omitted

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-sdk-for-go#12634]
### Bug Report

- import path of package in question: `services/preview/security/mgmt/v1.0/security`
- SDK version`v46.4.0`
- Go version: `go1.15.1 linux/amd64`

### What happened?  
When trying to create or update an automation using the SDK and the `CreateOrUpdate` function, the following error is returned 
```
StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationRequired" Message="The location property is required for this definition."
```
I expect this package within the SDK has never worked due to this error

### What did you expect or want to happen?
The CreateOrUpdate operation to succeed and the resource is created in Azure

### Why this happened
The Automation struct has the READ-ONLY comment above the `Location` field
[Link to code in the SDK](https://github.com/Azure/azure-sdk-for-go/blob/8b1ae49e53332c534e4263b4d4160aeb81d9d497/services/preview/security/mgmt/v1.0/security/models.go#L2013)

The `MarshallJSON()` function does not include the `Location` field
[Link to code in the SDK](https://github.com/Azure/azure-sdk-for-go/blob/8b1ae49e53332c534e4263b4d4160aeb81d9d497/services/preview/security/mgmt/v1.0/security/models.go#L2034)

I suspect this is due to an error in the upstream API spec where that field has been marked read-only

### How can we reproduce it?
Sample code to easily reproduce the bug is here https://gist.github.com/benc-uk/c6114689e978c834b92b6fcd9656c020

### Anything we should know about your environment.
Nothing of note

**Comment by ArcturusZhang** [comment]
Hi @benc-uk thanks for this issue and sorry for the inconvenience. 

I have identified the root cause of this issue, and this will be resolved in the next major version

**Comment by benc-uk** [comment]
Thanks @ArcturusZhang this is great news. I spotted v47 in the PR section, will this fix make that release or the one after?

**Comment by ArcturusZhang** [comment]
> Thanks @ArcturusZhang this is great news. I spotted v47 in the PR section, will this fix make that release or the one after?

Should be included in this release, I am working on it

**Comment by ArcturusZhang** [comment]
Hi @benc-uk the v47.0.0 has been released and the issue should have been resolved, please have a try, thanks!

**Comment by benc-uk** [comment]
@ArcturusZhang I just checked an v47 fixes this
Thanks for the speedy turn around on this one! Great stuff
