### ISSUE TITLE
There is no api to create vhub virtual network connection individually.

### ISSUE THREAD

**Issue by sidheshdivekar29** [Azure/azure-sdk-for-go#12645]
### Feature Request

Currently there is no way to create incremental virtual network connection for a given vhub.
hubvirtualnetworkconnections.go does not have an api to create/delete virtualnetworkconnection for a given vhub.
The workaround is to get existing connections and use add/del new vnc & then call CreateOrUpdate vhub.
This might not work always if vhub client doesn't have permissions to update other vhub connections.

network.VirtualHubsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '' with object id 'd3bcb5b6-25f8-43f5-8fe5-8045a17fbefd' has permission to perform action 'Microsoft.Network/virtualHubs/write' on scope '/subscriptions/abc/resourceGroups/VWAN/providers/Microsoft.Network/virtualHubs/VWAN'; however, it does not have permission to perform action 'peer/action' on the linked scope(s) '/subscriptions/def/resourceGroups/def/providers/Microsoft.Network/virtualNetworks/def,/subscriptions/ghi/resourceGroups/ghi/providers/Microsoft.Network/virtualNetworks/ghi,/subscriptions/ghi/resourceGroups/vwan/providers/Microsoft.Network/virtualNetworks/vwan' or the linked scope(s) are invalid."

**Comment by lirenhe** [comment]
@sidheshdivekar29, it seems you are asking a feature request for Azure network service.
The SDK repo may not be the best way for that feature. 
So could you post your question in https://docs.microsoft.com/en-us/answers/products/azure?product=networking?
