### ISSUE TITLE
Support appRoleAssignedTo on ServicePrincipal objects

### ISSUE THREAD

**Issue by jasonoxley-cai** [Azure/azure-sdk-for-go#12642]
### Feature Request

I would like to view the app role assignments of a given service principal. This is supported by the Microsoft Graph as well as the Azure Graph with the [list app role assignments API](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0&tabs=http).
 E.g. `GET https://graph.windows.net/<tenant id>/servicePrincipals/<service principal id>/appRoleAssignedTo
`, which returns a list of AppRoleAssignment objects. 

I am not finding any references to this in the codebase, is it supported?

**Comment by ArcturusZhang** [comment]
Hi @jasonoxley-cai thanks for this issue!

And unfortunately the ms-graph API will not be included in this SDK. Now we do not have any official go SDK released for msgraph, but there are some community made SDK for msgraph for example [this](https://github.com/yaegashi/msgraph.go) and [this](https://github.com/open-networks/go-msgraph).
Given the above reason, I am closing this issue, hope you would not mind. Thanks
