### ISSUE TITLE
API to get default route table for every subnet 

### ISSUE THREAD

**Issue by manalivaltix** [Azure/azure-sdk-for-go#12656]
### Feature Request

I am trying to figure out how to get information on the Default Route Table that is associated to every subnet. List RouteTables only returns the UserDefined Route Tables.

**Comment by lirenhe** [comment]
@manalivaltix, as GO SDK is auto generated from Swagger which is defined by service team, and it seems you are asking a feataure request for the service behaviour, could you post your question in https://docs.microsoft.com/en-us/answers/products/azure?product=networking?
I will close this item as this is not related to SDK, let me know if you have any questions.
