### ISSUE TITLE
Add `Enabled` to ASC setting resource

### ISSUE THREAD

**Issue by beandrad** [Azure/azure-sdk-for-go#12687]
### Feature Request

The [response schema](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L103) of `GET /subscriptions/{subscriptionId}/providers/Microsoft.Security/settings/{settingName}` doesn't include the `Enabled` flag, which is used to determine whether the setting is enabled.

https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L175

Azure API specs version: 2019-01-01

**Comment by ArcturusZhang** [comment]
Hi @beandrad thanks for this issue!

I just checked the swagger for this API, this resource `Setting` has a [discriminator](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L227) with two possible values, which means this resource supports polymorphism. It should have two subtypes inheriting the base type [`SettingResource`](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L202) corresponding to the two values of the discriminators. But it clearly has some problems - I only find one subtype corresponded to discriminator value `DataExportSettings` [here](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L185). In this resource definition, you could find an `enable` option [here](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L241). 
Therefore, this resource actually has a property of `enabled`.
And if you do not mind, I will close this issue for now. Please let me know if you have further questions on this.

**Comment by beandrad** [comment]
Hi @ArcturusZhang, I'm not sure where the problem is exactly. It seems that the Get endpoint returns [`Setting`](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L264) in the response body, which in turns maps to [`SettingResource`](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L181). I don't understand why the schema definition requires so many levels of indirection.
