### ISSUE TITLE
Get of a Network Security Group doesn't return port-range.

### ISSUE THREAD

**Issue by manalivaltix** [Azure/azure-sdk-for-go#12707]
### Bug Report

import path of the package is:
"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-11-01/network"
SDK version: "v40.0.0"
go version go1.13.4 darwin/amd64

Get of a NetworkSecurityGroup that has a security group rule with  DestinationPortRange as 80,443 (seen in the UI)
is being returned with an empty string.
From my debugs:
SG rule DestinationPortRange  

- What happened?
Not getting the correct destinationPortRange

- What did you expect or want to happen?
Wanted the destinationPortRange string to have 80,443
- How can we reproduce it?
Please create a NetworkSecurityGroup, and have a securityGroupRule with destinationPort = 80,443.
Now try to get the NetworkSecurityGroup using golang SDK
Print the desitinationPortRange - you will notice that it is an empty string.

- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Hi @manalivaltix thanks for this issue!

Have you checked the `destinationPortRanges` property? The port range could also be stored in this property.

**Comment by manalivaltix** [comment]
Thanks, I never noticed destinationPortRanges. I see it there.
