### ISSUE TITLE
Security Center DataExportSettingProperties not unmarshalled properly

### ISSUE THREAD

**Issue by beandrad** [Azure/azure-sdk-for-go#12724]
### Bug Report

- import path of package in question: github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/v3.0/security
- SDK version: 46.4.0
  - Commit: https://github.com/Azure/azure-sdk-for-go/commit/e3b3fa36a8a194ac2914270c8f8ecc342d4a1ee5

- What happened?
[Setting](https://github.com/Azure/azure-sdk-for-go/blob/227ccd374f20c4f5f1b33b913c18132f1cb238c4/services/preview/security/mgmt/v3.0/security/models.go#L15499) is returned by the [Get function](https://github.com/Azure/azure-sdk-for-go/blob/227ccd374f20c4f5f1b33b913c18132f1cb238c4/services/preview/security/mgmt/v3.0/security/settings.go#L48) and it cannot be cast to [DataExportSettingProperties](https://github.com/Azure/azure-sdk-for-go/blob/227ccd374f20c4f5f1b33b913c18132f1cb238c4/services/preview/security/mgmt/v3.0/security/models.go#L6601) since this returns an error or by calling [AsDataExportSettings()](https://github.com/Azure/azure-sdk-for-go/blob/227ccd374f20c4f5f1b33b913c18132f1cb238c4/services/preview/security/mgmt/v3.0/security/models.go#L15569) since this returns nil. 

Regarding the Azure API specs, [Setting]()https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L175 is of type [SettingResource](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L202) has a field (`kind`) defined as discriminator, which makes `SettingResource` polymorphic.

- What did you expect or want to happen?
I'd expect to be able to Get to `DataExportSettings` when the kind field in the Get response is `DataExportSettings `.

- Related issue: https://github.com/Azure/azure-sdk-for-go/issues/12687

**Comment by ArcturusZhang** [comment]
HI @beandrad thanks for this issue!

Yeah, now I see this API is problematic, if the resource itself is polymorphic, the returned model should have a discriminator. But in this case, the returned model `Setting` does not have a discriminator, but it directly inherit from `SettingResource` which has a discriminator and does not introduce more fields. This makes `Settings` and `SettingResource` effectively equivalent, but in this way the code generator is not able to detect that discriminator and gives us the wrong code.

I will possibly have a look at this issue in detail. But I assume to actually fix this, we will have to fix the problematic swagger definition to remove that redundant inheritances.

**Comment by ArcturusZhang** [comment]
I just had a quick test, the returned JSON from the service is
```
{"id":"/subscriptions/REDACTED/providers/Microsoft.Security/settings/MCAS","name":"MCAS","type":"Microsoft.Security/settings","kind":"DataExportSettings","properties":{"enabled":true}}
```
As you can see, this is clearly a `DataExportSettings` struct, but due to the reasons I explained above, we cannot actually cast this struct (its type is `Settings`) to `DataExportSettings`.

And unfortunately we do not have any workaround within the framework of the SDK. I will try to fix this by fixing the swagger, please stay tuned.

**Comment by ArcturusZhang** [comment]
Hi @beandrad I made some experiments refining the inheritance structure in the swaggers and generating new SDK, the following test code:
```
	client := security.NewSettingsClient(subsID, "westus2")
	client.Authorizer = authorizer
	resp, err := client.Get(ctx, "MCAS")
	if err != nil {
		return err
	}
	fmt.Println(reflect.TypeOf(resp.Value))
```
And it gives you this as expected:
```
security.DataExportSettings
```

**Comment by ArcturusZhang** [comment]
Well, I decide to reopen this and close this from the new release PR.

**Comment by beandrad** [comment]
Thanks for looking into it @ArcturusZhang! :)
