### ISSUE TITLE
Missing support for domainservices 2020-01-01

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#12774]
### Service Package Request

The latest version of domainservices supported by the SDK is 2017-06-01. There is a newer version available 2020-01-01

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/domainservices/resource-manager/Microsoft.AAD/stable/2020-01-01

**Comment by ArcturusZhang** [comment]
Hi @manicminer thanks for this issue! 
We have received this and we are asking the corresponding service team to make a release request of this new package. Please stay tuned and we will let you know once this package is released. Thanks!

**Comment by manicminer** [comment]
@ArcturusZhang Looks like this has been added, thanks!
