### ISSUE TITLE
issue mocking `containerservice.ManagedClustersClient`

### ISSUE THREAD

**Issue by dnozay** [Azure/azure-sdk-for-go#12834]
### Bug Report

- import path of package in question, `"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-07-01/containerservice"`

- SDK version

```
+       github.com/Azure/azure-sdk-for-go v46.0.0+incompatible
+       github.com/Azure/go-autorest/autorest v0.11.5
+       github.com/Azure/go-autorest/autorest/adal v0.9.2
+       github.com/Azure/go-autorest/autorest/azure/auth v0.5.1
+       github.com/Azure/go-autorest/autorest/azure/cli v0.4.0
+       github.com/Azure/go-autorest/autorest/to v0.3.0
```

Ok I have a piece of code that looks like this.
```
	client := containerservice.NewManagedClustersClient(subscriptionID)
	iter, err := cluster.ManagedClusterClient.ListByResourceGroupComplete(ctx, cluster.ResourceGroup)
	// ...
	for iter.NotDone() {
		managedCluster := iter.Value()
		// do something with managedCluster
		err = iter.NextWithContext(ctx)
		// ...
        }
```

so then I want to add tests...
I poke around and find `containerserviceapi.ManagedClustersClientAPI` and now I'm happy
so I switch things around and use that so I can have my mock implement that interface.

```
type ManagedClustersClientAPI interface {
	// ...
	ListByResourceGroupComplete(ctx context.Context, resourceGroupName string) (result containerservice.ManagedClusterListResultIterator, err error)
	// ...
}
```

problem comes with the return type:

```
// ManagedClusterListResultIterator provides access to a complete listing of ManagedCluster values.
type ManagedClusterListResultIterator struct {
	i    int
	page ManagedClusterListResultPage
}
```
things are private so I look for constructor
```
func NewManagedClusterListResultIterator(page ManagedClusterListResultPage) ManagedClusterListResultIterator {
	return ManagedClusterListResultIterator{page: page}
}
```
ok, I can provide a page
```
// ManagedClusterListResultPage contains a page of ManagedCluster values.
type ManagedClusterListResultPage struct {
	fn   func(context.Context, ManagedClusterListResult) (ManagedClusterListResult, error)
	mclr ManagedClusterListResult
}
```
again, look for a constructor
```
// Creates a new instance of the ManagedClusterListResultPage type.
func NewManagedClusterListResultPage(getNextPage func(context.Context, ManagedClusterListResult) (ManagedClusterListResult, error)) ManagedClusterListResultPage {
	return ManagedClusterListResultPage{fn: getNextPage}
}
```

Problem:
- things are private so I have to use the constructor
- the constructor does not initialize all the fields where `mclr` is uninitialized
- I can't test the inside of the loop

**Comment by ArcturusZhang** [comment]
Hi @dnozay thanks for this issue!

This is truly a problem in mocking. We could provide a constructor with full parameters, but since `mclr` is not a pointer and also private, it may not help a lot. Also maybe we could consider make some of the fields public or introduce more methods to this Iterator or Page? I am not quite sure.
@jhendrixMSFT thoughts?

**Comment by jhendrixMSFT** [comment]
First I will say that the paging/iteration design here is sub-optimal for mocking.  For our "track 2" SDK we've improved this by returning a "Pager" interface which should make it super-easy to mock.  Please see the [Go SDK Design Guidelines](https://azure.github.io/azure-sdk/golang_design.html) for more info on this new design.

I dug into this a bit, you are correct that without being able to set the first page (`mclr` in this case) you can't fully test the loop.  We could fix this by adding a param to accept a first page to the constructor like so.

```go
func NewManagedClusterListResultPage(cur ManagedClusterListResult, getNextPage func(context.Context, ManagedClusterListResult) (ManagedClusterListResult, error)) ManagedClusterListResultPage {
	return ManagedClusterListResultPage{fn: getNextPage, mclr: cur}
}
```

It would be a breaking change though.  How would you feel about that?

**Comment by dnozay** [comment]
> For our "track 2" SDK we've improved this by returning a "Pager" interface

I'm not in tune with the release timeframe for this, but interfaces are great.

> It would be a breaking change though. How would you feel about that?

It's currently not useable outside of the sdk itself. So it's more of an un-breaking change.
Alternatives are to introduce an additional constructor or a setter.
If that's something I can use to fully test the loop then I should be happy with that.

**Comment by jhendrixMSFT** [comment]
I was thinking about the new constructor to avoid the breaking change, however it leaves the old, useless one which I think is confusing (we can add a deprecation notice I guess).

@ArcturusZhang can you please update the track 1 code generator to include this new param?

**Comment by ArcturusZhang** [comment]
Hi @dnozay despite that this issue should have been resolved, it will not take effect until we actually regenerate one of the packages that you want to mock.
Due to the releasing process we are following now, we only release those packages that are requested by the corresponding service team, in order to let them first ensure their swaggers are good to release since we get too many issues from a bad swagger.
Back to this issue itself, the fix will not take effect until the corresponding service team has requested a release on it. But to mock it, you could always generate the SDK by yourself, or modify it on your fork as a short term workaround. Sorry for the inconvenience.
