### ISSUE TITLE
API for getting roles assignments at management group level

### ISSUE THREAD

**Issue by manoj-guglani-sp** [Azure/azure-sdk-for-go#12892]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
.../services/resources/mgmt/managementgroups/managementgroups.go

- What happened?
Need to list role assignments at managements group level. I cannot find the right API. When I used the API for subscriptions  I got the following error:
```
"authorization.RoleAssignmentsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription <management group id> could not be found.\"
```
I could not find an API under management groups so decided to try the list API for RoleAssignmentsClient. 

- What did you expect or want to happen?
Expecting an API to get role assignments for management group level.

- How can we reproduce it?
Call List API with management group id.

**Comment by ArcturusZhang** [comment]
Hi @manoj-guglani-sp thanks for this issue!

I wonder if [this API](https://github.com/Azure/azure-sdk-for-go/blob/b28cbb47f61f9a5cb407c390dcf3e86dd3e1fea1/services/preview/authorization/mgmt/2018-09-01-preview/authorization/roleassignments.go#L883) could meet your requirement? Please use the full mgmt group ID for the scope parameter, e.g. `/providers/Microsoft.Management/managementGroups/mgmtGroupName`. Could you please have a try if this could work?

**Comment by manoj-guglani-sp** [comment]
@ArcturusZhang I did try that API with full mgmt group ID but got an empty list. When I checked the IAM roles at the root level in the portal there were two roles assigned at the root.

**Comment by mblaschke-daimlertruck** [comment]
this is still a valid point for the new SDK
