### ISSUE TITLE
storage/blobutil package to make it easy to upload blobs

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#129]
We recently removed helper methods from `storage/blob` pkg so that users won't be fooled by methods containing special client-side logic.

Now we must have a good client library for handling blob uploads (typically block blobs) from user's point of view easily.

Main areas for consideration for `PutBlob()` functionality (We must write logic to handle these cases):
1. Block ID generation strategy for multi-block blobs.
2. Uploading blocks (chunks) concurrently in `runtime.NumCPU` goroutines (io efficiency)
3. Support overwrites (to the entire blob)
4. If blob is small enough, we may as well rely on single PutBlob call rather than bunch of PutBlocks; then PutBlockList
5. Handle large blob uploads (limit data stored in-memory, accept `io.ReadCloser`)

cc: @paulmey wdyt?

**Comment by ahmetalpbalkan** [comment]
@paulmey ping again. I'll start after your input on this.

**Comment by paulmey** [comment]
Sounds good indeed, go for it!

**Comment by boonep** [comment]
Wanted to check on PutBlob() status, let me know if I can do anything to help.  Thanks!

**Comment by ahmetalpbalkan** [comment]
@boonep sorry I didn't have time to get back to this. There's pretty much a spec of what I wanted to build above and your help is greatly appreciated and welcomed. If you like to put out a `blobutil` package prototype, I'd be happy to proactively review and help iterate.

**Comment by jerbob92** [comment]
It would be great to have this in, it would make file uploads much easier.

**Comment by rdhakne** [comment]
I see that in C++ Azure SDK there are functions to 'upload from file' (void upload_from_file(const utility::string_t &path)). I dont see the same in golang SDK. 
Am I missing something or they will be coming soon? :)

**Comment by ahmetalpbalkan** [comment]
To anyone interested having this blobutil package: You can now use `AppendBlob` type which is super easy to just keep uploading chunks of data to a blob. It doesn't have the complexity of `BlockBlob`s or anything like that.

**Comment by mcardosos** [comment]
@jhendrixMSFT

**Comment by marstr** [comment]
This is something that should be considered as part of @jhendrixMSFT's refactor as seen in #470.

In an effort to consolidate issues, I'm going to close this one. If folks feel there is further independent conversation to have here, or if #470 doesn't encapsulate this, feel free to re-open.
