### ISSUE TITLE
Missing support for dns 2018-09-01

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/azure-sdk-for-go#12965]
### Feature Request

Latest dns API version is 2018-05-01 (https://github.com/Azure/azure-sdk-for-go/tree/master/services/dns/mgmt) but no 2018-09-01 which is the latest and has support for private zones and virtual network links: https://docs.microsoft.com/en-us/rest/api/dns/privatedns/virtualnetworklinks

**Comment by ArcturusZhang** [comment]
Hi @CecileRobertMichon thanks for this issue. 

The package requested is not DNS but privatedns. You could find the SDK package here: https://github.com/Azure/azure-sdk-for-go/tree/master/services/privatedns/mgmt/2018-09-01/privatedns
The corresponding swagger do not accept any update since 17 months ago, therefore I assume the SDK package is still update to date.

**Comment by CecileRobertMichon** [comment]
@ArcturusZhang using the 2018-0-01 I'm getting an error: `privatedns.PrivateZonesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=\u003cnil\u003e Code=\"MissingRegistrationForLocation\" Message=\"The subscription is not registered for the resource type 'privateDnsZones' in the location 'westus2'. Please re-register for this provider in order to have access to this location.`

The same subscription is able to create a private dns zone fine in the Azure portal. Is it possible the SDK isn't up to date? The feature went GA in 2019...

**Comment by CecileRobertMichon** [comment]
Nevermind, I think it's because I specified a `Location`, looks like that's not required for private dns zones.

**Comment by CecileRobertMichon** [comment]
hmm scratch that, when I remove Location I get `privatedns.PrivateZonesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"LocationRequired\" Message=\"The location property is required for this definition.`
