### ISSUE TITLE
appinsights: support API version "2020-02-02-preview"

### ISSUE THREAD

**Issue by khaliddermoumi** [Azure/azure-sdk-for-go#13012]
### Feature Request

Please support API version "2020-02-02-preview" for Application Insights. 
There's a major new feature supported in this version, the workspace-based Application Insights resource. It allows integrating AI into a Log Analytics workspace, meaning that the Log Analytics workspace is the data back end for Application Insights.
I noticed the lack of this feature as I started implementing support for this feature in Terraform.

Thanks and kind regards.

**Comment by ArcturusZhang** [comment]
Hi @azmonapplicationinsights could you please open a release request for the particular api-version of application insights?

**Comment by haflidif** [comment]
Hi @azmonapplicationinsights any updates ?

**Comment by tafs7** [comment]
Any updates?  @azmonapplicationinsights @ArcturusZhang 

It has been nearly a month since last comment, and no news.  Would be nice to know whether this is coming soon or further down the road, so others can plan accordingly.

**Comment by ArcturusZhang** [comment]
> Any updates? @azmonapplicationinsights @ArcturusZhang
> 
> It has been nearly a month since last comment, and no news. Would be nice to know whether this is coming soon or further down the road, so others can plan accordingly.

I just wrote some emails to the corresponding team, and we might get some updates soon! Sorry for the delay

**Comment by kibnelbachyr** [comment]
any updates on this ?

**Comment by rmaziarka** [comment]
I've come across this problem today - no option to create workspace-based AI. Is there any progress in this matter?

**Comment by sebader** [comment]
With the now announced deprecation of the non-workspace-attached AI, this should really be prioritized 
https://azure.microsoft.com/en-us/updates/we-re-retiring-classic-application-insights-on-29-february-2024/

**Comment by federicobarera** [comment]
Get we get an ETA on this feature please

**Comment by ArcturusZhang** [comment]
Hi @federicobarera @sebader we are discussing this with the service team currently, will let you know the process very soon

**Comment by sivetic** [comment]
@ArcturusZhang Any update on this task?  We are waiting on azurerm update to support the Workspace model, and it seems it keeps getting kicked down the line.

**Comment by ArcturusZhang** [comment]
Hi all, the service team is working on the swagger correctness issues now, once they finish their work, we could get a release on the new api-version.

**Comment by sivetic** [comment]
@ArcturusZhang Are there any further updates you could provide?

**Comment by pauska** [comment]
@ArcturusZhang Hi - are there any updates on this issue that you could share with us?

**Comment by ArcturusZhang** [comment]
Hi I am sorry it took this long, but the service team is trying to resolve the correctness and completeness issues in their swagger. We have to wait for them to complete these tasks to release the corresponding SDK. I will constantly ping them for updates.

**Comment by khaliddermoumi** [comment]
Hi!
Meanwhile [here is an implementation of the app insights ws-based resource](https://github.com/khaliddermoumi/terraform-modules-azurerm/tree/master/app_insights) as a terraform module (using "az rest"):
Usage:
```
source = "git::git@github.com:khaliddermoumi/terraform-modules-azurerm//app_insights?ref=v0.1.1"
```

**Comment by sivetic** [comment]
@ArcturusZhang Can you share any progress update?

**Comment by ArcturusZhang** [comment]
We have [a on-going PR](https://github.com/Azure/azure-rest-api-specs/pull/14870) for the new package for application insights. Once we resolve the issues in that PR, we will release a new package.

**Comment by dylan-asos** [comment]
https://github.com/Azure/azure-sdk-for-go/releases/tag/v55.5.0 looks like it includes these changes now

**Comment by ArcturusZhang** [comment]
This has been released in v55.5.0, therefore I will close this issue.

There is also a requirement that we want to make it stable, therefore in the next major version this preview will be removed and we will have a stable version of this by removing the preview APIs in it.

**Comment by dylanmorley** [comment]
@ArcturusZhang in this version of the API, the [RetentionInDays ](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2020-02-02-preview/components?tabs=json) property is no longer documented and has become read only in the Go SDK. 

For a bit of context on the problems this causes, [see this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7667) (see towards the end of the thread) We can no longer set the property when creating an app insights resource. 

Can you confirm the reasons for the removal of this property - is this a deliberate omission, due to workspace mode support and therefore the change in which resource controls data retention settings?

Before we can make any progress on the linked issue, it would be good to understand the breaking change to the API

**Comment by timja** [comment]
@dylanmorley best to raise an issue on the https://github.com/Azure/azure-rest-api-specs repo.

The service team will get notified, you may also want to escalate via your account manager if you have enterprise support.

**Comment by khaliddermoumi** [comment]
"Retention" is not needed anymore, as the retention is set and billed via the Log Analytics Workspace.
See: [Workspace-based Application Insights resources](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource):
"Data ingestion and retention for workspace-based Application Insights resources are billed through the Log Analytics workspace where the data is located."
That's why it doesn't make sense anymore to have the retentionInDays writable.

**Comment by dylanmorley** [comment]
@khaliddermoumi yes, but only if you set the workspace id. If you don't, then you're creating a 'classic' mode insights resource, which is in support for a few years yet - data Retention still applies for those types of resources. 

Thanks @timja, will raise an issue.

**Comment by khaliddermoumi** [comment]
The  "2020-02-02-preview" API version can only create workspace-based resources, at least according to [the docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2020-02-02-preview/components?tabs=json#applicationinsightscomponentproperties-object): 
"WorkspaceResourceId: Resource Id of the log analytics workspace which the data will be ingested to. This property is required to create an application with this API version. Applications from older versions will not have this property."
If this is correct, the TF resource implementation must use 2 different API versions to support creating both styles of AppInsights resource.

**Comment by dylanmorley** [comment]
Already reported here - https://github.com/Azure/azure-rest-api-specs/issues/14801
