### ISSUE TITLE
Address Client Certificate Credential Consistency Review feedback

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-go#13014]
Following changes need to be done, based on the review discussion:

- [x] Update Tenant ID Validation Message
- [ ] Add support for send certificate chain (SNI Auth) 
- [x]  Investigate credential behavior when scope is passed as nil (How does the credential handle it ? , what error does user see?). if its appropriately handled then no action is needed.
- [x] Investigate Credential Unavailable Exception scenarios (validate their use case and consistency across other credentials).
- [x] Rename clientCertificate param to certificate_path with the goal to add consistency with other languages.
- [x] Investigate possibility of flattenting/composing options bag.

**Comment by catalinaperalta** [comment]
If a nil scope is set we'll return the error from AAD saying that they need to set a scope. 

Leaving this closed since the last point left to address if a duplicate of #11874
