### ISSUE TITLE
Is there a key vault List Certificates API?

### ISSUE THREAD

**Issue by shaobovaltix** [Azure/azure-sdk-for-go#13038]
### Service Package Request

Hi, I'm using Azure Golang SDK to integrate Azure Key Vault certificates access. Is there any APIs I can use to implement something like ListCertificates() to get details of certificates stored in Key Vault?

From Azure CLI there is a command doing what I want:
az keyvault certificate list
https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az_keyvault_certificate_list

**Comment by ArcturusZhang** [comment]
Hi @shaobovaltix thanks for this issue.

Actually we have [this function](https://github.com/Azure/azure-sdk-for-go/blob/ba145441a3950c78926e1e1dbbd269a20f8bbde0/services/keyvault/2016-10-01/keyvault/client.go#L1753), could you please have a look if this could meet your requirement?
