### ISSUE TITLE
EventHub for 2018-01-01-preview is using wrong API reference

### ISSUE THREAD

**Issue by woehrl01** [Azure/azure-sdk-for-go#13032]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
services/preview/eventhub/mgmt/2018-01-01-preview/eventhub

- SDK version e.g. `master`, `latest`, `18.1.0`
  `master`

- What happened?

The API to use the 2018-01-01-preview is passing the wrong API Version:

https://github.com/Azure/azure-sdk-for-go/blob/b54cf2d8e4e1bdf621e7865562134c2f7aeb6585/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/eventhubs.go#L122

This results in missing values reading/writing e.g. `zoneRedundant`

- What did you expect or want to happen?

Being able to read and set  `zoneRedundant`

- How can we reproduce it?
- Anything we should know about your environment.

**Comment by woehrl01** [comment]
This current implementation results in https://github.com/terraform-providers/terraform-provider-azurerm/issues/4872 not working.

**Comment by ArcturusZhang** [comment]
Hi @woehrl01 thanks for this issue.

But unfortunately we do not have a api-version 2018-01-01-preview for creating the eventhub right now. Here is how this is defined in the specs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/readme.md#tag-package-2018-01-preview
The package you are using in go SDK is generated from [this tag](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/readme.md#tag-package-2018-01-preview) which is defined as a combination of some swagger files in the readme. As you may see, we do not have a swagger file 2018-01-01-preview/eventhubs.json available.

In [the issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4872) you posted in the description, the zoneRedundant should be a feature of the eventhubNamespace, and we have 2018-01-01-preview API version of creating the namespaces: https://github.com/Azure/azure-sdk-for-go/blob/b54cf2d8e4e1bdf621e7865562134c2f7aeb6585/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/namespaces.go#L188

Furthermore, the swagger operations-preview.json does not have any API related with creating eventhubs, it only has one API - listing of the available operations, which would not help in terraform (and our package `2018-01-01-preview/eventhub` supports this: https://github.com/Azure/azure-sdk-for-go/blob/b54cf2d8e4e1bdf621e7865562134c2f7aeb6585/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/operations.go#L45).

**Comment by ArcturusZhang** [comment]
Beside of the API version (which should not be the root cause of this issue), could you please provide some more details about in which ways https://github.com/terraform-providers/terraform-provider-azurerm/issues/4872 is not working as expected? I suppose someone from the service team may help.

**Comment by woehrl01** [comment]
Thanks @ArcturusZhang  it looks like it's a different issue. I'll investigate further.
