### ISSUE TITLE
forceDeletion query params when deleting resources

### ISSUE THREAD

**Issue by Segflow** [Azure/azure-sdk-for-go#13034]
### Feature Request

Some resources DELETE endpoints accept a `forceDeletion` query option (e.g: virtual machine delete) https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/delete

Currently it's not possible to use that query param in the Go SDK.

**Comment by ArcturusZhang** [comment]
Hi @Segflow thanks for this issue and we have it here now: https://github.com/Azure/azure-sdk-for-go/blob/ba145441a3950c78926e1e1dbbd269a20f8bbde0/services/compute/mgmt/2020-06-30/compute/virtualmachines.go#L463
