### ISSUE TITLE
Requesting SDK support for Azure Cache for Redis Api version 2020-06-01

### ISSUE THREAD

**Issue by sspeaks610** [Azure/azure-sdk-for-go#13283]
Hello,

We are getting customer asks for a new SDK version to support our newly released api version. What can I do to facilitate this going through?

Here's the azure-rest-api-spec for the new API version :
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/redis/resource-manager/Microsoft.Cache/stable/2020-06-01/redis.json

Thanks!

**Comment by ArcturusZhang** [comment]
Hi @sspeaks610 thanks for the issue!

@yegu-ms could you please create a release request if you find this swagger is good to release?

**Comment by curib** [comment]
Hi @ArcturusZhang, please see the following: https://github.com/Azure/sdk-release-request/issues/1054

**Comment by ArcturusZhang** [comment]
Hi @sspeaks610 this package has been released in v49.1.0, therefore I will close this issue now. Thanks
