### ISSUE TITLE
Operations Management client problems

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-sdk-for-go#1333]
Hi, 

### Context 

I recently worked with a team who are using Terraform to deploy AKS and wanted to enable Log Analytics Container Monitoring solution as well. As part of the work I created a [Terraform resource](https://github.com/terraform-providers/terraform-provider-azurerm/pull/952) for the RP but spotted a couple of odd things along that way which I had to work around. 

###  Issues

1. Create method parameters 

The client seems to take in an odd set of input into it's ["New Client" method](https://github.com/Azure/azure-sdk-for-go/blob/master/services/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/client.go) which I wouldn't expect to see. I was able to work around this by passing in some values [like this](https://github.com/terraform-providers/terraform-provider-azurerm/pull/952/files#diff-848235249455ee48aaf3ea5d431960aeR742) but I don't think this should be required. I wasn't able to tell from the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/preview/2015-11-01-preview/OperationsManagement.json) definition why this was happening so I assumed it was in the codegen but it's very likely I missed something. 

2. Successful creation returns an error

When calling the [CreateOrUpdate](https://github.com/terraform-providers/terraform-provider-azurerm/pull/952/files#diff-3f56658fd0e05b2b1bf784ed9794e9beR104) the `err` returned is non-nil even if the create request succeeds. 

This appears to be because the swagger doc it wrong. The service returns a "201 Created" and the docs [suggest it returns a 200](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/preview/2015-11-01-preview/OperationsManagement.json#L72)

Request Created
``` 
PUT /subscriptions/SUBHERE/resourcegroups/oms-acctestRG-101589505992913122/providers/Microsoft.OperationsManagement/solutions/Containers%28acctest-dep-101589505992913122%29?api-version=2015-11-01-preview HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.10 (amd64-darwin) go-autorest/8.0.0 Azure-SDK-For-Go/v12.5.0-beta services;HashiCorp-Terraform-v0.11.3
Content-Length: 436
Content-Type: application/json
Accept-Encoding: gzip

{"name":"Containers(acctest-dep-101589505992913122)","location":"westeurope","plan":{"name":"Containers(acctest-dep-101589505992913122)","publisher":"Microsoft","promotionCode":"","product":"OMSGallery/Containers"},"properties":{"workspaceResourceId":"/subscriptions/SUBHERE/resourcegroups/oms-acctestrg-101589505992913122/providers/microsoft.operationalinsights/workspaces/acctest-dep-101589505992913122"}}

```

Response Received
```
HTTP/1.1 201 Created
Content-Length: 1191
...
Content-Type: application/json; charset=utf-8
Date: Mon, 19 Mar 2018 17:35:48 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Ams-Apiversion: WebAPI1.0
X-Aspnet-Version: 4.0.30319
X-Content-Type-Options: nosniff
....
X-Powered-By: ASP.NET

{
  "plan": {
    "name": "Containers(acctest-dep-101589505992913122)",
    "publisher": "Microsoft",
    "promotionCode": "",
    "product": "OMSGallery/Containers"
  },
  "properties": {
    "workspaceResourceId": "/subscriptions/SUBHERE/resourcegroups/oms-acctestrg-101589505992913122/providers/microsoft.operationalinsights/workspaces/acctest-dep-101589505992913122",
    "provisioningState": "Succeeded",
    "creationTime": "Mon, 01 Jan 0001 00:00:00 GMT",
"lastModifiedTime": "Mon, 01 Jan 0001 00:00:00 GMT",
    "containedResources": [
      "/subscriptions/SUBHERE/resourcegroups/oms-acctestrg-101589505992913122/providers/Microsoft.OperationalInsights/workspaces/acctest-dep-101589505992913122/views/Containers(acctest-dep-101589505992913122)"
    ]
  },
  "id": "/subscriptions/SUBHERE/resourcegroups/oms-acctestrg-101589505992913122/providers/Microsoft.OperationsManagement/solutions/Containers(acctest-dep-101589505992913122)",
  "name": "Containers(acctest-dep-101589505992913122)",
  "type": "Microsoft.OperationsManagement/solutions",
  "location": "West Europe"
}


```

**Comment by vladbarosan** [comment]
@lawrencegripper we reached out to the OperationsManagement team and indeed the spec is out of date.   Adding  @dashimi16 who added the initial spec to provide an ETA of when the spec is expected to be updated.

**Comment by vladbarosan** [comment]
@lawrencegripper this has been fixed in v18 https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/solutions.go . Also please use the package listed ( under `services/preview` since the one under `services/` is deprecated.
