### ISSUE TITLE
Support for User Assigned Identity in MSI

### ISSUE THREAD

**Issue by thebenwaters** [Azure/azure-sdk-for-go#13339]
### Feature Request

When using 

`NewAuthorizerFromEnvironment()`

I'm receiving 

`No MSI found for specified ClientId/ResourceId`

**Comment by ArcturusZhang** [comment]
Hi @thebenwaters thanks for this issue!

I am not quite if this is the right solution, but you could have a try:
```
config := auth.NewMSIConfig()
config.ClientID = "your client id" // only specify this when you are using a user assigned identity
authorizer, err := config.Authorizer()
```
@jhendrixMSFT could you please have a look if the above code is the right way to use MSI authentication?

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang your example is correct.  @thebenwaters can you please let us know if it works for you?

**Comment by thebenwaters** [comment]
I was having issue with this using a specific resource (Key Vault), but will test and try again

btw) msft: bewaters

**Comment by thebenwaters** [comment]
Worked on VM, but need to test in Azure Functions (these was mainly where I had the issue)

**Comment by jhendrixMSFT** [comment]
There were a few bugs with user-assigned identity and azure functions that I recently fixed.  Please be sure to use the latest versions of `adal` and `auth` modules before testing.
