### ISSUE TITLE
Remove XMLName from returned response structs 

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#136]
I see quite many XMLName fields in response structs returned from client methods. These are not particularly useful to the user and they're confusing. Let's get rid of those –––assuming they're not needed for parsing those structs with `encoding/xml`. 

cc: @paulmey

**Comment by ahmetalpbalkan** [comment]
@paulmey looks like XMLName is mostly unnecessary  unless we're parsing an element that is deeper than the root object.

http://play.golang.org/p/u0MXkE0X0D

**Comment by paulmey** [comment]
yes, indeed it is. :+1:

**Comment by ahmetalpbalkan** [comment]
meh. we can live with this.
