### ISSUE TITLE
apimanagement: Broken/impossible validation rule for DiagnosticContract

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#13604]
### Bug Report

- github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-12-01/apimanagement
- v47.0.0+incompatible
- go1.14.5 darwin/amd64 (also go1.13.15 darwin/amd64)

- Trying to create an API Diagnostic using `APIDiagnosticClient.CreateOrUpdate()`
- The validation for `DiagnosticContract.DiagnosticContractProperties.Sampling.Percentage` is invalid
- This field is a float. Both values passed to the Validate func for the InclusiveMaximum and InclusiveMinimum constraints are int64s
- Validation fails with
    ```
    apimanagement.APIDiagnosticClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.DiagnosticContractProperties.Sampling.Percentage constraint=InclusiveMaximum value=10 details: rule must be float value for InclusiveMaximum constraint; got: 100
    ```

References:

- https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2019-12-01/apimanagement/apidiagnostic.go#L81-L82
- https://github.com/Azure/go-autorest/blob/master/autorest/validation/validation.go#L172-L175

**Comment by ArcturusZhang** [comment]
Hi @manicminer thanks for this issue!

After a quite brief checking, this should be a code generator issue. I will take a look very shortly. This should be resolved in the next version.

**Comment by ArcturusZhang** [comment]
Despite this issue was closed, this bug would not be actually resolved until a new SDK version was released.
We are planning to release a new SDK version with this change on this Thursday
