### ISSUE TITLE
web.CertificatesClient.CreateOrUpdate always returns error due to not supporting 202 Accepted Rest Response

### ISSUE THREAD

**Issue by AdamCoulterOz** [Azure/azure-sdk-for-go#13665]
### Bug Report

Paths:
`/services/web/mgmt/2019-08-01/web/certificates.go`
`/services/web/mgmt/2020-06-01/web/certificates.go`

Version: v48.1

**- What happened?**

When attempting to CreateOrUpdate a Certificate the AutoRest client always (at least for managed certificates) returns a `202 Accepted` asynchronous "future creation" response, which the client errors on in the following code, specifically Line 127:

https://github.com/Azure/azure-sdk-for-go/blob/48b0fcf4b1044723e27a96a411a3d96b5ad54c6a/services/web/mgmt/2020-06-01/web/certificates.go#L122-L132

```
AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/adamtesttf2/providers/Microsoft.Web/certificates/adamtest.xxxxxxx.com?api-version=2020-06-01:
 
    HTTP/2.0 202 Accepted
    Content-Length: 0
    Cache-Control: no-cache
    Date: Thu, 19 Nov 2020 03:21:57 GMT
    Expires: -1
    Location: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/adamtesttf2/providers/Microsoft.Web/certificates/adamtest.xxxxxxx.com/operationresults/00000000-0000-0000-0000-000000000000?api-version=2020-06-01
    Pragma: no-cache
    Retry-After: 15
    Server: Microsoft-IIS/10.0
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Aspnet-Version: 4.0.30319
    X-Content-Type-Options: nosniff
    X-Ms-Correlation-Request-Id: 00000000-0000-0000-0000-000000000000
    X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
    X-Ms-Request-Id: 00000000-0000-0000-0000-000000000000
    X-Ms-Routing-Request-Id: AUSTRALIAEAST:20201119T032158Z:00000000-0000-0000-0000-000000000000
    X-Powered-By: ASP.NET
```

**- What did you expect or want to happen?**

Return either the created certificate or a `CreateOrUpdateFuture` handle.

**- How can we reproduce it?**

Create a managed certificate against a Premium App Service Plan Web App, which already has a bound custom domain name. Example code below (this also includes my work around to capture the 202 error response):

```go
client := meta.(*clients.Client).Web.CertificatesClient

//...

certificate := web.Certificate{
    CertificateProperties: &web.CertificateProperties{
        CanonicalName: utils.String(name),
        ServerFarmID:  utils.String(appServicePlanID),
        Password:      new(string),
    },
    Location: utils.String(location),
    Tags:     tags.Expand(t),
}

if _, err := client.CreateOrUpdate(ctx, resourceGroup, name, certificate); err != nil {
    if !strings.Contains(err.Error(), "StatusCode=202") { // <--- this StatusCode=202 error always happens
        return fmt.Errorf("Error creating/updating App Service Managed Certificate %q (Resource Group %q): %s", name, resourceGroup, err)
    }
}

time.Sleep(30 * time.Second) // <- temporary workaround, but not reliable, as may be longer and could be well shorter

read, err := client.Get(ctx, resourceGroup, name)
```

I should be able to use the following pattern:

```go
createFuture, err := client.CreateOrUpdate(ctx, resourceGroup, name, certificate)
if err != nil { return err }

err = createFuture.WaitForCompletionRef(ctx, client.Client)
if err != nil { return err }
```

**Comment by jackofallops** [comment]
FWIW - I think this should be an LRO, meaning there's a `future` missing from the SDK that the `CreateOrUpdate` should return for us to poll for completion?

**Comment by AdamCoulterOz** [comment]
> FWIW - I think this should be an LRO, meaning there's a `future` missing from the SDK that the `CreateOrUpdate` should return for us to poll for completion?

Precisely what I was reporting as missing

**Comment by lirenhe** [comment]
@AdamCoulterOz, from Swagger, creating certificate is not defined as LRO. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/Certificates.json#L154
 As the SDK is generated from Swagger,  could you create an issue in https://github.com/Azure/azure-rest-api-specs/issues/new?
