### ISSUE TITLE
evaluate new Mongo driver with CosmosDB

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1369]
MongoDB Inc. is preparing a new driver for Mongo's API in https://github.com/mongodb/mongo-go-driver. Can we evaluate this lib and if/how it works with Cosmos' Mongo API?

Should we replace `mgo` with this library? Or something entirely different?

**Comment by RickWinter** [comment]
Closing this old issue.  If you feel this issue is relevant to the new track2 Go SDK please open a new issue.
