### ISSUE TITLE
update vscode-go to Delve API v2

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1370]
Some issues are fixed and support for Mozilla's [rr](https://github.com/mozilla/rr) has been added to Delve's v2 API. We should ensure [vscode-go](https://github.com/Microsoft/vscode-go) is updated, and test with rr as a backend.

Once this works we can work with the VS Code team to enable record, replay and rewind options with rr if there's user demand.

Related issues from vscode-go repo:
* https://github.com/Microsoft/vscode-go/issues/1555
* https://github.com/Microsoft/vscode-go/issues/1529

cc @ramya-rao-a

**Comment by vladbarosan** [comment]
with this release https://github.com/Microsoft/vscode-go/releases/tag/0.6.90 , the extension uses Delve API v2
