### ISSUE TITLE
Metrics List does not use context for HTTP request

### ISSUE THREAD

**Issue by akahn** [Azure/azure-sdk-for-go#13700]
### Feature Request

https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/monitor/mgmt/2019-06-01/insights/metrics.go#L85

The insights metrics package supports fetching metrics for Azure resources. The `List` method takes a context as a parameter. However, this context is not passed in to autorest's `ListSender`. This means that any deadline/timeout the user has set on the request is not respected. As a user I would expect the deadline I set on the context I pass to `List` to be respected, and the HTTP request therein to be canceled according to the context.

**Comment by ArcturusZhang** [comment]
Hi @akahn thanks for this issue.

Actually the context is passing in with the request, see the code here: https://github.com/Azure/azure-sdk-for-go/blob/e6a7ee8b264373c1f827ce8e95a1e12cc8f97f1c/services/preview/monitor/mgmt/2019-06-01/insights/metrics.go#L143

CCing @jhendrixMSFT for more context about this.

**Comment by akahn** [comment]
My mistake. Thank you for the clarification.
