### ISSUE TITLE
This SDK doesn't support the new version of billing api (specifically tags flag)

### ISSUE THREAD

**Issue by kyle-iot** [Azure/azure-sdk-for-go#13748]
The new version of Azure billing API has a flag that includes tags and needs to be supported by this SDK

**Comment by ArcturusZhang** [comment]
Hi @kyle-iot thanks for this issue.

The latest package for billing is here: https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/billing/mgmt/2020-05-01-preview/billing

**Comment by kyle-iot** [comment]
Hello,
Thank you @ArcturusZhang !
Please keep this issue open for a few days. I will check it out and get back to you shortly.

**Comment by ramaganesan-rg** [comment]
hello kyle-iot  - Its Jan and we have not heard back from you. We will go ahead to close this, please feel free to reopen on any further clarifications needed. thank you!
