### ISSUE TITLE
Configuration is lacking an environment variable for MySQL DNS Suffix

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-go#13749]
### Feature Request

Azure SQL has one: `config.Environment().SQLDatabaseDNSSuffix` (at least I think this is for Azure SQL).
MySQL's suffix is (based on their documentation): `mysql.database.azure.com`, but there is no such entry in `config.Environment` as far as I can tell.

**Comment by ArcturusZhang** [comment]
Hi @matthchr thanks for this issue!

Hi @jhendrixMSFT according to this, do we need to add something in `go-autorest`?

**Comment by jhendrixMSFT** [comment]
Correct, it would go [here](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L54).

@matthchr is the DNS suffix the same for sovereign clouds, or is MySQL not supported there?

**Comment by matthchr** [comment]
I'm actually not sure @jhendrixMSFT - I'm not a developer of MySQL just a user.

**Comment by matthchr** [comment]
For what it's worth, a customer of ours just confirmed that the DNS suffix for sovereign clouds is different. MySQL _is_ supported there.

What's required to add this?

**Comment by cdmurph32** [comment]
Fix submitted https://github.com/Azure/go-autorest/pull/631, but we can't test the China or Germany Clouds.

**Comment by matthchr** [comment]
@jhendrixMSFT - can probably close this given that the linked PR merged? Unsure if there is more to do to resolve this bug but I don't think there is.

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/v0.11.19`
