### ISSUE TITLE
Data Factory - Validation Error when trying to change `PublicNetworkAccess`

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#13821]
### Bug Report

- `azure-sdk-for-go/services/datafactory/mgmt/2018-06-01/datafactory`
- SDK Version `48.1.0`
- `go version go1.15 darwin/amd64`

I'm trying to adjust just the `PublicNetworkAccess` Data Factory attribute but I'm getting a validation error

```
validation failed: parameter=factory.FactoryProperties.RepoConfiguration constraint=Null value=<nil> details: unknown type invalid
```

I'm not specifying a `RepoConfiguration` and a `RepoConfiguration` isn't needed to change `PublicNetworkAccess`. Digging into the sdk shows exactly where the [validation error](https://github.com/Azure/azure-sdk-for-go/blob/master/services/datafactory/mgmt/2018-06-01/datafactory/factories.go#L164) is. 

The below is the payload I'd like to send

```
dataFactory := Factory{
		Location:          &location,
		FactoryProperties: &FactoryProperties{
                             PublicNetworkAccess: PublicNetworkAccessDisabled,
                 },
}
```

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for this issue!

I could tell that this should be a bug in the validation part of `go-autorest`. I will go through this and probably provide a valid fix for this.

**Comment by jhendrixMSFT** [comment]
This will require some changes in the code generator to fix.  In the meantime, I'm adding an escape-hatch to disable parameter validation https://github.com/Azure/go-autorest/pull/595

**Comment by jhendrixMSFT** [comment]
The flag to disable validation is in `autorest/validation/v0.3.1`

```go
validation.Disabled = true
```

**Comment by ArcturusZhang** [comment]
Reopen this issue since this is only resolved when a new package for data factory is released.
