### ISSUE TITLE
Error being swallowed when listing providers?

### ISSUE THREAD

**Issue by dimbleby** [Azure/azure-sdk-for-go#13882]
### Bug Report

(I'm a terraform user rather than developer, sorry if I've got these details wrong)

- `services/resources/mgmt/2016-02-01/resources`?  
- 48.1.0, I think

---

I'm using terraform, and seeing the azurerm provider hang at a point where it lists providers. I've raised https://github.com/terraform-providers/terraform-provider-azurerm/issues/9662, but they haven't got back to me yet, so I figured I'd see whether I could understand any of this myself.

I am a golang novice so may be way off base: is it possible that there's a missing `return` [here](https://github.com/Azure/azure-sdk-for-go/blob/fa7243bb9039435beef3417bf74602e8c2ceb153/services/resources/mgmt/2016-02-01/resources/providers.go#L154)?  Could that cause an error to be lost and, if so, might that result in these symptoms??

Even if this is completely wrong, any insight you can offer on what might be going wrong would be much appreciated!

**Comment by jhendrixMSFT** [comment]
The missing return does seem suspicious.  @ArcturusZhang can you please take a look?

**Comment by ArcturusZhang** [comment]
> The missing return does seem suspicious. @ArcturusZhang can you please take a look?

Yes it is the root cause. I will fix this for all the RPs in the next version of SDK
