### ISSUE TITLE
Question about azidentity

### ISSUE THREAD

**Issue by simongottschlag** [Azure/azure-sdk-for-go#13893]
Hi!

I've looked at azidentity and was wondering if it's something that's ready to be used?

I tried using it with resources but wasn't able to figure it out.

So the question is, should I wait to use azidentity? Or is it possible to use with the other parts of the SDK? 

Thank you!

**Comment by catalinaperalta** [comment]
Hi! `azidentity` is in beta but you can use it to authenticate with your code. 

If you're using the older version of the sdk that requires an `authorizer` you can use `azidentity` with the adapter found in the example [here](https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/samples/azidentity/SDKV1Adapter/example_SDKV1_test.go).

If you are using the new management modules which can be found under the `/sdk/arm` directory, then you can follow some of our examples for `armresources` in the *_test.go files, [here](https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/arm/resources/2020-06-01/armresources). 

Each of the new sdk modules (`armnetwork`, `armcompute`, `armresources`, `armkeyvault`, `armstorage`) have API examples in the example files in the same directory.

**Comment by simongottschlag** [comment]
@catalinaperalta thank you so much for the information! 😁
