### ISSUE TITLE
Redis 6 config support

### ISSUE THREAD

**Issue by anasokan** [Azure/azure-sdk-for-go#13946]
Hi Team,

I see that azure has started to support redis 6 in preview mode now.
To consume from script we need support for configuration of redis version from the API.
Can you check and provide the same

**Comment by lirenhe** [comment]
@anasokan, the latest version is  https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v60.2.0+incompatible/services/redis/mgmt/2020-12-01/redis

Does it meet your need?
