### ISSUE TITLE
Creating Azure Firewall from GO SDK is not getting Private IP generated.

### ISSUE THREAD

**Issue by escortnotice** [Azure/azure-sdk-for-go#13954]
### Bug Report

When we are trying to create an "Azure FIrewall" using SDK for GO ( "github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network" ) , the azure firewall get created but without a private IP address.
We would like Microsoft to investigate on this if the SDK has a bug or help us with a sample "GO" code for creating an azure firewall.
It also shows the same behaviour with the latest version and latest-1 version too. We tried with that too.

- What happened?
Try creating an azure firewall with GO SDK, the provisioning state is "updating", and the private IP does not get generated.

- What did you expect or want to happen?
It should create Firewall with private IP.

- How can we reproduce it?
Try to create the firewall with the GO SDK version mention above

- Anything we should know about your environment.
N/A

**Comment by ArcturusZhang** [comment]
Hi @escortnotice thanks for this issue!

Could you please also share the code of creating this Azure Firewall?
Please note the creation of azure fire wall is async, you will have to explicitly wait for its completion in your code.
One very brief sample:
```
future, err := client.CreateOrUpdate(ctx, resourceGroup, name, firewall)
if err != nil {
    panic(err)
}
if err := future.WaitForCompletionRef(ctx, client.Client); err != nil {
    panic(err)
}
```
And I assume you are referring the `privateIPAddress` in `IPConfigurations`, but please note you will not get one if you did not explicitly assign one `IPConfiguration` in the body parameter of the CreateOrUpdate function

**Comment by escortnotice** [comment]
Hi Arcturus, Thank You for your response. We will try to investigate and see if the async code update is the issue on our end or not.

Below is our code for your reference.

`func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	v, ok := mg.(*v1alpha3.AzureFirewall)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errNotAzureFirewall)
	}
	v.Status.SetConditions(runtimev1alpha1.Creating())

	af := azurefirewall.NewAzureFirewallParameters(v)

	if _, err := e.client.CreateOrUpdate(ctx, v.Spec.ResourceGroupName, meta.GetExternalName(v), af); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errCreateAzureFirewall)
	}

	return managed.ExternalCreation{}, nil
}`

**Comment by ArcturusZhang** [comment]
Hi @escortnotice thanks for the reply, and is it possible to print the variable `af` out before you send the request? Or could you confirm that you at least defined on IPConfiguration block in the request body.
Logging out the request body is another option - you could enable this by export a env var `AZURE_GO_SDK_LOG_LEVEL=DEBUG`
