### ISSUE TITLE
Functionality/code for Get/Set/Delete blob/container ACLs?

### ISSUE THREAD

**Issue by jf** [Azure/azure-sdk-for-go#14]
Is there any functionality or code for this, and if so, why not?

**Comment by ahmetalpbalkan** [comment]
Thanks for bringing this up. I assume you mean blob/container ACLs.

Currently, the blob storage client is written to be used in our other projects (like docker-registry azure driver, or packer-azure) and is not a full client (I should probably create a readme for the package). The mentioned projects do not require the ACL calls, therefore these are omitted.

Do you need them? I may look into those sometime or feel free to contribute.

**Comment by jf** [comment]
thanks, @ahmetalpbalkan for the quick reply. Yup, I do need them. I'm looking into using SAS at the moment. The ACLs will be for setting storage access policies.

**Comment by ahmetalpbalkan** [comment]
SAS is implemented for blobs if you like to use it. it might not be there for containers

**Comment by jf** [comment]
My understanding of SAS is that you'll need to use ACLs if you want to use stored access policies. Am I right?

**Comment by ahmetalpbalkan** [comment]
I don't think generating SAS URL for a container requires setting ACL on container. Read this: http://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-shared-access-signature-part-2/

**Comment by jf** [comment]
What if I want to use a stored access policy? I'll need to set ACLs, right? That's according to https://msdn.microsoft.com/en-us/library/azure/dn140257.aspx

**Comment by ahmetalpbalkan** [comment]
That's right. Implementing this sh

**Comment by jf** [comment]
ok. Should I define these as methods on BlobStorageClient?

**Comment by ahmetalpbalkan** [comment]
Sounds about right.

**Comment by jf** [comment]
Btw, I believe the "ISO 8061" mentioned at https://msdn.microsoft.com/en-us/library/azure/dn140255.aspx: that should be ISO 8601?

**Comment by ahmetalpbalkan** [comment]
Haha that's a nice catch.

**Comment by ahmetalpbalkan** [comment]
Haha that's a nice catch. :joy: I will forward this feedback. Yes it should be 8601.

**Comment by jf** [comment]
Thanks. I cried too about this. :}

**Comment by ahmetalpbalkan** [comment]
Hey @jf do you still need these methods around or are you planning to implement them?

**Comment by jf** [comment]
hi, sorry @ahmetalpbalkan, but I am no longer using Azure. Haven't for quite some time now, actually. I do need help with something else related to Microsoft, though. I'll email you, if that's ok with you.

**Comment by ahmetalpbalkan** [comment]
@jf I'm hardly the right person for all things microsoft but shoot me an email. :)

leaving the issue open if it grabs someone's interest.

**Comment by jf** [comment]
:) thanks, @ahmetalpbalkan ! You've got good timing - I just sent you the email... :)

**Comment by kpfaulkner** [comment]
Just to clarify, is this talking about public/private access to containers or talking about generating SAS Urls?

**Comment by ahmetalpbalkan** [comment]
@kpfaulkner this is about ACLs not SAS URIs. 

- https://msdn.microsoft.com/en-us/library/azure/dd179391.aspx
- https://msdn.microsoft.com/en-us/library/azure/dd179469.aspx

**Comment by kpfaulkner** [comment]
Added a PR for this covering Container ACLs. Hope it's some use.

**Comment by mcardosos** [comment]
Functionality added by @kpfaulkner PR. Thanks for your contribution!
