### ISSUE TITLE
appRoleAssignments for groups

### ISSUE THREAD

**Issue by AndriiOmelianenko** [Azure/azure-sdk-for-go#14032]
Hello, I have a need to develop code that is going to attach role to a group like below:

```bash
az rest --method POST --uri 'https://graph.microsoft.com/v1.0/groups/<object-id of the group>/appRoleAssignments' --headers 'Content-Type=application/json' --body '{"principalId": "principalId-value","resourceId": "resourceId-value","appRoleId": "appRoleId-value"}'
```

Could you please let me know if there is an SDK for such operations?

If no - I need to develop it as well, so how do I properly go through login? I've logged in to az-cli like so:
```bash
az login -u some-service-account --allow-no-subscriptions
```

**Comment by vijayrajah** [comment]
@AndriiOmelianenko .. Please check [here](https://github.com/yaegashi/msgraph.go) for a SDK for MS Graph. This SDK does not support MS Graph operations.

**Comment by AndriiOmelianenko** [comment]
hi @vijayrajah , isn't this https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/authorization/authorization.go#L42 example doing something similar? I'm kind of new to Azure/Graph stack, sorry for dumb questions :)

I need to attach application role to AD group, according to Azure manifests

**Comment by lirenhe** [comment]
Close this item as Go SDK does not support MS Graph operations.
