### ISSUE TITLE
Getting Groupid for private endpoint creation argument via golang SDK

### ISSUE THREAD

**Issue by gowrisankar22** [Azure/azure-sdk-for-go#14065]
Hi,

Creating a private endpoint, I have to pass the Groupid **[1]** via `PrivateLinkServiceConnectionProperties`. This groupid is different for each and every service. How to identify the GroupId for the PrivateLinkServiceConnectionProperties??

**Example:**
To get the groupid via az cli, I am passing the serviceid like below, in the response, I am getting a groupId. 

But I want to get that the same using golang sdk. Can you please point me to the right place for the same?

```
  ~ az network private-link-resource list --id 
"/subscriptions/xx/resourceGroups/rg_privatelink_poc/providers/Microsoft.DBforPostgreSQL/servers/myservergs"
[
  {
    "id": "/subscriptions/xxxxx/resourceGroups/rg_privatelink_poc/providers/Microsoft.DBforPostgreSQL/servers/myservergs/privateLinkResources/plr",
    "name": "plr",
    "properties": {
      "groupId": "postgresqlServer",
      "requiredMembers": [
        "postgresqlServer"
      ],
      "requiredZoneNames": [
        "privatelink.postgres.database.azure.com"
      ]
    },
    "resourceGroup": "rg_privatelink_poc",
    "type": "Microsoft.DBforPostgreSQL/servers/privateLinkResources"
  }
]
```

[1] https://github.com/Azure/azure-sdk-for-go/blob/v49.2.0/profiles/latest/network/mgmt/network/models.go#L2076

**Comment by ArcturusZhang** [comment]
Hi @gowrisankar22 thanks for opening this issue!

Would [this API](https://github.com/Azure/azure-sdk-for-go/blob/833259e221a0b7bdfc44dcf496be6a6fd75102e3/services/postgresql/mgmt/2020-01-01/postgresql/privatelinkresources.go#L140) or [this API](https://github.com/Azure/azure-sdk-for-go/blob/833259e221a0b7bdfc44dcf496be6a6fd75102e3/services/postgresql/mgmt/2020-01-01/postgresql/privatelinkresources.go#L53) work for you?
