### ISSUE TITLE
Support Microsoft.Insights/preview/2019-10-17

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/azure-sdk-for-go#14090]
### Feature Request

Support Azure Monitor Private Link Scope by supporting this api - [https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-10-17-preview](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-10-17-preview)

**Comment by ArcturusZhang** [comment]
Hi @ross-p-smith thanks for opening this issue!

I notice that you are a member of MS Azure, therefore could you go to https://aka.ms/openapihub to open a release request? Now we only release the packages when we receive a release request (or want to roll out some big changes from the code generator)

**Comment by tj-corrigan** [comment]
@ArcturusZhang I'm also a MS employee and interested in seeing this get implemented. I'm unfamiliar with the process to request a release. Can you provide any guidance?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang I'm also a MS employee and interested in seeing this get implemented. I'm unfamiliar with the process to request a release. Can you provide any guidance?

Please feel free to write an internal email about this, I could involve someone from the open api hub to explain the details of this.

**Comment by lirenhe** [comment]
@ross-p-smith, could you help to check the latest released GO sdk for insights? There are a couple of releases this year and the change should be already included. Let me know if you have any questions. Thanks
