### ISSUE TITLE
SSHPublicKeys client.ListBySubscriptionComplete() returns an empty list

### ISSUE THREAD

**Issue by shaobovaltix** [Azure/azure-sdk-for-go#14105]
### Bug Report

- import path of package in question
`github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
   v47.0.0
- output of `go version`
`go version go1.15.3 darwin/amd64`

- What happened?
The following code returns an empty list of ssh public keys, but actually I have a few keys stored in Azure.
        `client := compute.NewSSHPublicKeysClient(subscriptionID)`
	`authorizer, err := s.GetAuthorizer()`
	`if err != nil {
		log.Printf("Error while getting authorizer %v", err)
		return nil, err
	}`
	`client.Authorizer = authorizer`
`        for list, errL := client.ListBySubscriptionComplete(context.TODO()); list.NotDone(); errL = list.Next() {
        }
`

- What did you expect or want to happen?
The keys stored in Azure can be returned.

- How can we reproduce it?
N/A

- Anything we should know about your environment.
N/A

**Comment by ArcturusZhang** [comment]
Hi @shaobovaltix thanks for this issue!

Could you also provide some request log related with this request for us to better debug this issue? You can enable the request log by exporting an environment variable `AZURE_GO_SDK_LOG_FILE=DEBUG`
