### ISSUE TITLE
Device Provisioning Service

### ISSUE THREAD

**Issue by shaunco** [Azure/azure-sdk-for-go#14121]
### Service Package Request

Perhaps I'm just not finding it, but it appears there is no support for https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager in the azure-sdk-for-go.

**Comment by ArcturusZhang** [comment]
Here you go: 
https://github.com/Azure/azure-sdk-for-go/tree/master/services/provisioningservices/mgmt
and
https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/provisioningservices/mgmt/2017-08-21-preview/iothub

**Comment by shaunco** [comment]
Sorry @ArcturusZhang, but that only contains the DPS Certificate API and DPS Resource API. Where is:
- [Enrollment Groups](https://docs.microsoft.com/en-us/rest/api/iot-dps/getenrollmentgroup)
- [Individual Enrollments](https://docs.microsoft.com/en-us/rest/api/iot-dps/getindividualenrollment/getindividualenrollment)
- [Registrations](https://docs.microsoft.com/en-us/rest/api/iot-dps/querydeviceregistrationstates/querydeviceregistrationstates)

And all the other things added in the 2019-03-31, 2020-01-01, or [2020-03-01 release](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2020-03-01) of the DPS API? It would seem that only two of the DPS endpoints of the ~20 listed at https://docs.microsoft.com/en-us/rest/api/iot-dps/ are supported...

**Comment by ArcturusZhang** [comment]
Hey @shaunco I just reopen this issue. 
The newer api-versions are not released because the corresponding service team is not requesting them, we cannot release the SDK without the service team's request (it works as a confirmation of the swagger's productivity). 
Therefore I tagged this issue so that the corresponding service team could come and have a look.

**Comment by shaunco** [comment]
Thanks!

Weird that APIs that are fully documented on docs.microsoft.com don't make it in to the SDK until the team owning the service specifically asks for it...

**Comment by nberdy** [comment]
@ArcturusZhang could you please contact me about the process for getting included in the Azure SDK?

**Comment by nberdy** [comment]
Hi @shaunco, it sounds like you're looking to use data plane APIs in the Azure SDK. Unfortunately the Azure SDK only supports control plane APIs, so you will need to use the Azure IoT SDKs for data plane operations such as device enrollment. You can find the supported data plane SDKs here: [Azure IoT SDKs](https://github.com/Azure/azure-iot-sdks). Go is not one of the supported languages (sorry), but please feel free to open an issue in that repo requesting Go support.

**Comment by shaunco** [comment]
Bummer, but I appreciate the quick response! We'll cobble something together with go-resty or go-autorest from the docs.

It is really weird to me how much support there is for the control plane on all these services with so little for the data plane. Most everyone uses Teraform or Pulumi on the control plane side and doesn't really need libraries. On the data plane side it would be really nice to have official libraries.

**Comment by nberdy** [comment]
Please leave this feedback in the IoT SDK repo!

**Comment by shaunco** [comment]
@nberdy the https://github.com/Azure/azure-iot-sdks repo does not allow issues to be created in it.

**Comment by shaunco** [comment]
@nberdy Can we really not get a Swagger file for the DPS _(Individual & Group Enrollment)_ and IoT Hub _([Digital Twin Model Repository Service](https://docs.microsoft.com/en-us/rest/api/iothub/digitaltwinmodelrepositoryservice/arevalidmodels) and [Device](https://docs.microsoft.com/en-us/rest/api/iothub/device))_ APIs? I spent the the last 9 hours manually typing or copying + pasting type definitions, URLs, query parameters, status codes, API versions, and more from docs.microsoft.com in to my code ... and I'm not even 20% done. Really a shame to have to spend a week building copying+pasting for what would have taken all of 5 minutes with a Swagger file ... and chances are I will mess something up in the process.

**Comment by nberdy** [comment]
@shaunco This should be the swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2020-03-01/iotdps.json

**Comment by shaunco** [comment]
@nberdy that Swagger is missing all the data plane APIs (individual enrollments, group enrollments, device status)

**Comment by mccolljr** [comment]
This is still open in 2024 - I hate to bump an ancient thread, but is this issue resolved or do we still not have access to the data plane swagger definitions?

**Comment by shaunco** [comment]
This is not resolved. We just built our own client wrapper around the data plane APIs (individual enrollments, group enrollments, device status). IoT Hub and DPI seem like they were half implemented by Microsoft and then just kept on life support. SDKs are missing quite a bit and things like enrollment search are completely non-functional, despite the API docs claiming otherwise.

**Comment by mccolljr** [comment]
> This is not resolved. We just built our own client wrapper around the data plane APIs (individual enrollments, group enrollments, device status). IoT Hub and DPI seem like they were half implemented by Microsoft and then just kept on life support. SDKs are missing quite a bit and things like enrollment search are completely non-functional, despite the API docs claiming otherwise.

Thanks for the clarification - glad to know it isn't just me. We're in the middle of an implementation and we're finding the same issues on our end. Truly a disappointing scenario.
