### ISSUE TITLE
Undefined azure.FutureAPI

### ISSUE THREAD

**Issue by javierlga** [Azure/azure-sdk-for-go#14141]
### Bug Report

- import path of package(s):
  - `services/apimanagement/mgmt/2017-03-01/apimanagement`
  - `services/eventhub/mgmt/2017-04-01/eventhub`
  - `services/preview/eventhub/mgmt/2018-01-01-preview/eventhub`
  - `services/servicebus/mgmt/2017-04-01/servicebus`

- SDK version: `v50.0.0` 
- output of `go version`: `go version go1.15.3 darwin/amd64`

- What happened?
After creating a `go.mod` file and running `go test` the following error was received, in this case it was for api management but it's the same error for the other packages: 

```
../../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go@v50.0.0+incompatible/services/apimanagement/mgmt/2017-03-01/apimanagement/models.go:8379:2: undefined: azure.FutureAPI
../../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go@v50.0.0+incompatible/services/apimanagement/mgmt/2017-03-01/apimanagement/models.go:8388:2: undefined: azure.FutureAPI
../../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go@v50.0.0+incompatible/services/apimanagement/mgmt/2017-03-01/apimanagement/models.go:8479:2: undefined: azure.FutureAPI
../../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go@v50.0.0+incompatible/services/apimanagement/mgmt/2017-03-01/apimanagement/models.go:8906:2: undefined: azure.FutureAPI
../../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go@v50.0.0+incompatible/services/apimanagement/mgmt/2017-03-01/apimanagement/models.go:8923:2: undefined: azure.FutureAPI
```
- What did you expect or want to happen?
Use the package with no issues.

- How can we reproduce it?
Try to use one of the packages.

- Anything we should know about your environment.
No

**Comment by ArcturusZhang** [comment]
Hi @javierlga thanks for this issue!

As we stated in the [note of CHANGELOG](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md#v5000), you will have to use at least v0.11.15 of `github.com/go-autorest/autorest` module.
Please let me know if there are any further concerns.

**Comment by javierlga** [comment]
> Hi @javierlga thanks for this issue!
> 
> As we stated in the [note of CHANGELOG](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md#v5000), you will have to use at least v0.11.15 of `github.com/go-autorest/autorest` module.
> Please let me know if there are any further concerns.

Hello @ArcturusZhang, thanks for your answer but we don't use that package, we only use `github.com/Azure/go-autorest/autorest/azure/auth` version  0.5.5

**Comment by ArcturusZhang** [comment]
> > Hi @javierlga thanks for this issue!
> > As we stated in the [note of CHANGELOG](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md#v5000), you will have to use at least v0.11.15 of `github.com/go-autorest/autorest` module.
> > Please let me know if there are any further concerns.
> 
> Hello @ArcturusZhang, thanks for your answer but we don't use that package, we only use `github.com/Azure/go-autorest/autorest/azure/auth` version 0.5.5

**Go SDK cannot work without `go-autorest/autorest` module, even in previous versions.** 

One proof is that if you check one of the old version of Go SDK, you will find the `Future` types are using `azure.Future` - which is provided by `go-autorest/autorest`.

If you are not using this package directly (put it in `go.mod`), or you are not using any incompatible versions of `go-autorest` - it must be some of your dependencies are using `go-autorest`. 
To identify this, you could just go to your `go.sum` file and search `go-autorest/autorest` and see if any matches.

The solution is very simple, just add the module `github.com/Azure/go-autorest/autorest v0.11.16` to your `go.mod`.

**Comment by javierlga** [comment]
> > > Hi @javierlga thanks for this issue!
> 
> > > As we stated in the [note of CHANGELOG](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md#v5000), you will have to use at least v0.11.15 of `github.com/go-autorest/autorest` module.
> 
> > > Please let me know if there are any further concerns.
> 
> > 
> 
> > Hello @ArcturusZhang, thanks for your answer but we don't use that package, we only use `github.com/Azure/go-autorest/autorest/azure/auth` version 0.5.5
> 
> 
> 
> **Go SDK cannot work without `go-autorest/autorest` module, even in previous versions.** 
> 
> 
> 
> One proof is that if you check one of the old version of Go SDK, you will find the `Future` types are using `azure.Future` - which is provided by `go-autorest/autorest`.
> 
> 
> 
> If you are not using this package directly (put it in `go.mod`), or you are not using any incompatible versions of `go-autorest` - it must be some of your dependencies are using `go-autorest`. 
> 
> To identify this, you could just go to your `go.sum` file and search `go-autorest/autorest` and see if any matches.
> 
> 
> 
> The solution is very simple, just add the module `github.com/Azure/go-autorest/autorest v0.11.16` to your `go.mod`. 

Thanks, that fixed the issue.
