### ISSUE TITLE
Proposal: discontinue support for multiple API versions in the track 2 SDK

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#14163]
Please add a :+1: reaction if you support this proposal.  If you do not, please leave a comment describing why.

In track 1, we added support for side-by-side API versions as a means to insulate customers against breaking changes across API versions.  Now that we have a solid versioning story via Go modules, the side-by-side model is somewhat obsolete for this purpose.

Simply put, each RP (compute, network, redis, etc) would have its own module.  When an RP releases a new API version, a new major version of its module would be released, targeting the new API version.

For example, we release a v1 module for compute at its latest API version (2020-06-03).  When the next API version for compute is published (e.g. 2021-03-01) a v2 module would be released targeting that version.

This would consolidate the directory structure.  Today we have this.

```
/services/compute/mgmt/<api version>/compute
/services/compute/mgmt/<api version>/compute
/services/compute/mgmt/<api version>/compute
```

With the new proposal it would condense to this.

```
/sdk/armcompute
```

There is a question of what this means for Azure stack and the sovereign clouds and am researching further.

We also plan to update the track 2 codegen to include an optional API version parameter as an escape-hatch.  It would be used to specify an older API version to use with the current codegen in the event that a specific API version of a service is required but there is no module version available.

**Comment by tombuildsstuff** [comment]
(heads up I've not missed the request for feedback above, will post something early next week)

**Comment by jhendrixMSFT** [comment]
Current POR is to continue to support multiple API versions side-by-side.
