### ISSUE TITLE
Truncation on response

### ISSUE THREAD

**Issue by aronchick** [Azure/azure-sdk-for-go#14165]
### Bug Report

I'm using:
	"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-12-01/containerservice"

When I went to create a new agent pool, I was able to connect properly with no issues.

But I made a mistake and named my agent pool more than 12 characters.

In the CLI, it tells me correctly
```
$ # More than 12 long
$ az aks nodepool add -c 5 -n '0123456789012' -s "Standard_DS3_v2" --cluster-name "myclustername"
--nodepool-name can contain at most 12 characters
```

However, when I do the same using the Go SDK, I get the following:
![image](https://user-images.githubusercontent.com/51317/104667341-be1d5100-568a-11eb-8793-4e86243bb5c9.png)

As you can see, the error message stack is truncated which is non-ideal. Is there a way to pass through the full string?

**Comment by ArcturusZhang** [comment]
Hi @aronchick thanks for this issue!

By checking the code in `go-autorest`, I did not find any related logic to do the truncation. Could you please run your program again with the env var `AZURE_GO_SDK_LOG_LEVEL=DEBUG` to show the full response body?

**Comment by jhendrixMSFT** [comment]
The truncation is a debugger setting.  Please see https://github.com/golang/vscode-go/blob/master/docs/debugging.md#configuration for info on how to change the default max length.

**Comment by jhendrixMSFT** [comment]
Closing as this is answered.
