### ISSUE TITLE
How to Verify the peering is established ? 

### ISSUE THREAD

**Issue by gowrisankar22** [Azure/azure-sdk-for-go#14211]
I have a below scenario, to check peering is established. Can you help me with how easily we can do it?

1. I have a first vnet called Vnet-A
2. I have a second vnet called Vnet-B where my Kubernetes operator is running.
Using golang SDK from my Vnet-B I want to check to peer with Vnet-A is established so that I can implement the same in my k8s operator. I am not sure currently how can I do it?

BRs, Gowrisankar

**Comment by ArcturusZhang** [comment]
Hi @gowrisankar22 thanks for this issue!

I have tagged this issue so that someone from the corresponding service team might take a look at this issue and give you an API how to do it.

**Comment by miwithro** [comment]
This issue is best handled by NW team.

**Comment by gowrisankar22** [comment]
any update on this ?
