### ISSUE TITLE
Azure Go SDK for stopping an instance and restarting it

### ISSUE THREAD

**Issue by uditgaurav** [Azure/azure-sdk-for-go#14225]
### Description

I wanted to perform the following task using GO SDK for which I couldn't found any good example:

- Establishing Connection with Azure
- Stopping a VM instance
- Restarting the VM instance

1. The first part is establishing the connection for which I used:
```go
package main

import (
        "fmt"
        "github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
  authorizer, err := auth.NewAuthorizerFromEnvironment()
```
not sure it is the correct one. Anything else we need to set up here.

2. For stopping the VM couldn't get the exact function but in the Go SDK code I found one:

https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/ffcdafe9818d55dbc2134db1548e1ed10b4a6092/compute/vm.go#L168

3. Same for starting the VM:

https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/ffcdafe9818d55dbc2134db1548e1ed10b4a6092/compute/vm.go#L184

How to use it in GO SDK using the client?

**Comment by ArcturusZhang** [comment]
Hi @uditgaurav thanks for this issue!

The following functions on the VirtualMachineClient should help you:
1. Start: https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/compute/mgmt/2020-06-30/compute/virtualmachines.go#L2141
2. Restart: https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/compute/mgmt/2020-06-30/compute/virtualmachines.go#L1788
3. Stop: https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/compute/mgmt/2020-06-30/compute/virtualmachines.go#L1417

**Comment by uditgaurav** [comment]
Thanks, @ArcturusZhang it was helpful. One more thing I wanted to ask. If we want to get the current status of the VM the  is there any function for that let suppose I want to get the status of VM if it is in `Running`,`Stopped`, or any other state the n how can we access the status?

**Comment by uditgaurav** [comment]
I was able to do this using `InstanceView()`. Thanks for the sdk!
