### ISSUE TITLE
HDInsight Location Client Fails to Deserialize VersionSpec Model

### ISSUE THREAD

**Issue by jamisonhyatt** [Azure/azure-sdk-for-go#14238]
### Bug Report

- import path of package: `github.com/Azure/azure-sdk-for-go/profiles/latest/hdinsight/mgmt/hdinsight`
- SDK version e.g. `v50.0.2` ...but also all prior versions...I think it's been incorrect for 2+ years?
- go.mod:
```
go 1.15

require (
	github.com/Azure/azure-sdk-for-go v50.2.0+incompatible
	github.com/Azure/go-autorest/autorest/azure/auth v0.5.6
	github.com/Azure/go-autorest/autorest/to v0.4.0 // indirect
	github.com/Azure/go-autorest/autorest/validation v0.3.1 // indirect
)
```
- output of `go version` : `go version go1.15.7 darwin/amd64`

- Gist to reproduce: https://gist.github.com/jamisonhyatt/20e01c5837c15165fca566bf459516c7
- What happened: Successful (200) API calls with a valid response returns an error during deserialization within the `hdinsight.LocationsClient`

> hdinsight.LocationsClient#GetCapabilities: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal bool into Go struct field VersionSpec.versions.available.isDefault of type string'

- What did you expect or want to happen:  No deserialization error
- How can we reproduce it:  via this [gist](https://gist.github.com/jamisonhyatt/20e01c5837c15165fca566bf459516c7) or any call that attempts to deserialize the model `hdinsight.VersionSpec`: https://github.com/Azure/azure-sdk-for-go/blob/5aff21717612661044ca766fd0d3981c5010db57/services/hdinsight/mgmt/2018-06-01/hdinsight/models.go#L2173
- Anything we should know about your environment: nope

I verified locally that altering the type of IsDefault to *bool instead of *string in the above model does solve the problem.  Is a PR with the type change the right way to fix this, or is it more involved?

**Comment by ArcturusZhang** [comment]
Hi @jamisonhyatt thanks for this issue and sorry for the inconvenience!

We do know this issue, which comes from a swagger mistake. We just fixed this in the swagger 6 days ago (see [this PR](https://github.com/Azure/azure-rest-api-specs/pull/12612)) but this fix causes breaking changes in this package, we have to release it in the next major version (end of this month). In the new version, this issue will be resolved.

**Comment by aim-for-better** [comment]
Checking

**Comment by aim-for-better** [comment]
As Arcturus, this has been fixed from swagger spec side, we will update related sdk soon.

**Comment by ArcturusZhang** [comment]
> As Arcturus said, this has been fixed from swagger spec side, we will update related sdk soon.

I know that we have released a new version for hdinsight recently, but could you please make another release request to make sure that we would not miss this package in the next major version release?

**Comment by aim-for-better** [comment]
> > As Arcturus said, this has been fixed from swagger spec side, we will update related sdk soon.
> 
> I know that we have released a new version for hdinsight recently, but could you please make another release request to make sure that we would not miss this package in the next major version release?

Now we need to hold on the release request. there are still some ongoning changes.

**Comment by aim-for-better** [comment]
Still need to wait some days.

**Comment by aim-for-better** [comment]
still need to wait, we will release it soon.

**Comment by aim-for-better** [comment]
The Go SDK team is working on releasing. Hi @ArcturusZhang  could you please check the release request?

**Comment by ArcturusZhang** [comment]
> The Go SDK team is working on releasing. Hi @ArcturusZhang could you please check the release request?

This will be released in next week's major version.

**Comment by aim-for-better** [comment]
Hi @ArcturusZhang Is the Go SDK available now? Thanks~
