### ISSUE TITLE
Retrieve private link subresource and private dns zone via GO sdk

### ISSUE THREAD

**Issue by gowrisankar22** [Azure/azure-sdk-for-go#14248]
Hello,

Is there any possible way available to retrieve the **subresource** and **private DNS Zone**  via golang SDK for the private endpoint creation?

Let me explain in detail.

1.  I have a Postgres created in subscription 1. 

`/subscriptions/xxxx/resourceGroups/rg1/providers/Microsoft.DBforPostgreSQL/servers/demopostgresql`

2. Creating a private endpoint from subscription 2 using golang SDK. To do that I need to pass the **subresource** for private endpoint creation. I need to retrieve this subresource in an automated way by looking into the service provided from subscription 1.

3. Once the endpoint is created I need to know the right private DNS zone to create **A** record.  This information also I need to retrieve in an automated way using gosdk by looking into the service provided from subscription 1.

this is really possible now or are there any alternatives?

**For more info:** https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns 

BRs, Gowrisankar

**Comment by ArcturusZhang** [comment]
Hi @gowrisankar22 thanks for this issue.

These two functions might help you:
1. https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/postgresql/mgmt/2020-01-01/postgresql/privateendpointconnections.go#L52
2. https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/postgresql/mgmt/2020-01-01/postgresql/privatelinkresources.go#L53-L52
