### ISSUE TITLE
New network API has model object with a different property type.

### ISSUE THREAD

**Issue by MirzaSikander** [Azure/azure-sdk-for-go#14261]
### Bug Report

- import path of package in question:
`azure-sdk-for-go/services/network/mgmt/2020-08-01/network/models.go`

- SDK version:
`v50.1.0`
- output of `go version`
`go version go1.15.6 linux/amd64`

- What happened?
`InterfacePropertiesFormat` has a property called `ProvisioningState` which used to be a pointer type before API version `2020-08-01`

```
/ InterfacePropertiesFormat networkInterface properties.
type InterfacePropertiesFormat struct {
	// VirtualMachine - READ-ONLY; The reference to a virtual machine.
	VirtualMachine *SubResource `json:"virtualMachine,omitempty"`
	....
	// ResourceGUID - READ-ONLY; The resource GUID property of the network interface resource.
	ResourceGUID *string `json:"resourceGuid,omitempty"`
	// ProvisioningState - READ-ONLY; The provisioning state of the network interface resource. Possible values include: 'Succeeded', 'Updating', 'Deleting', 'Failed'
	ProvisioningState ProvisioningState `json:"provisioningState,omitempty"`
}
```
- What did you expect or want to happen?
This seems unexpected since all other properties are pointer types.

- How can we reproduce it?
Look at the file
https://raw.githubusercontent.com/Azure/azure-sdk-for-go/master/services/network/mgmt/2020-08-01/network/models.go

- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Hi @MirzaSikander thanks for this issue.

I checked the network package of 2020-08-01, [2020-07-01](https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/network/mgmt/2020-07-01/network/models.go#L18821) and [2020-06-01](https://github.com/Azure/azure-sdk-for-go/blob/e2799766f88d91bbf2b119e6fc9e7613aab4a4b7/services/network/mgmt/2020-06-01/network/models.go#L18437), the `provisioningState` in `InterfacePropertiesFormat` is all a const type (a pseudo-enum type in go), which comes from the corresponding swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-07-01/network.json#L251

**Comment by MirzaSikander** [comment]
You see this difference if u upgrade from 2019-06-01

**Comment by ArcturusZhang** [comment]
@MirzaSikander It is a string in 2019-06-01: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-06-01/networkInterface.json#L828
Therefore we cannot really change this.

**Comment by lirenhe** [comment]
@MirzaSikander, as the GO SDK is generated from Swagger, we are unable to adjust the behaviour defined in the Swagger spec.
I will close this issue and if you still have concern on this Swagger change, please create an issue in https://github.com/Azure/azure-rest-api-specs/issues
