### ISSUE TITLE
Get tls: no renegotiation error with interacting with ARM endpoint.

### ISSUE THREAD

**Issue by rapatchi** [Azure/azure-sdk-for-go#14264]
### Bug Report

- import path of package in question, e.g. `services/preview/hybridkubernetes/mgmt/2020-01-01-preview/hybridkubernetes/`
- SDK version e.g. `master`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

ARM calls are failing with below error when using Azure GO SDK. 

- What happened?
Failed to check Azure for existing resource err:Get https://api-dogfood.resources.windows-int.net/providers/Microsoft.Kubernetes/locations/WESTUS2/operationStatuses/579fa220-5396-436a-a13a-b50ccb6a800f?api-version=2020-01-01-preview: local error: tls: no renegotiation"

It was working fine before and suddenly we see this failure coming. So assuming some service side change. But would help if we you observed this kind of issue before.

- What did you expect or want to happen?
No error should come here.
- How can we reproduce it?
Try onboarding connected cluster in DF ARM. 
- Anything we should know about your environment.
Normal Kubernetes Environment.

**Comment by ArcturusZhang** [comment]
Hi @rapatchi thanks for this issue!

I am tagging this issue so that some one from the service side might know and take a look.

**Comment by rapatchi** [comment]
@ArcturusZhang  we are observing this issue not only with operations of Microsoft.Kubernetes. I am observing this issue with other api as well. Like getting the resource group etc. And FYI I am from Connected Kubernetes team itself.

**Comment by jhendrixMSFT** [comment]
The default it no TLS renegotiation.

https://github.com/Azure/go-autorest/blob/master/autorest/client.go#L193

If an endpoint requires TLS renegotiation they need to add a transform to their readme.go.md file.  Here's an example.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/AnomalyDetector/readme.go.md

**Comment by rapatchi** [comment]
We add the required fix.
