### ISSUE TITLE
Migrate from satori/go.uuid to gofrs/uuid

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-go#14283]
We are planning to replace the `github.com/satori/go.uuid` package with `github.com/gofrs/uuid` to resolve its [potential security issues](https://github.com/satori/go.uuid/issues/73) in a major version at the end of this month.
In major version release v53.0.0, you will have to replace all the import statements of the `uuid` in order to avoid compile errors.

Thank you!

**Comment by utkarsh-extc** [comment]
i would like to refactor code to use new module
