### ISSUE TITLE
Emulate the Storage endpoint with Azurite

### ISSUE THREAD

**Issue by mihaitodor** [Azure/azure-sdk-for-go#14295]
### Bug Report

- What happened?

The Storage client from this library does not obey the `BlobEndpoint` part of the connection strings. This makes things quite awkward when trying to test things in a containerised environment (i.e. Kubernetes), where [Azurite](https://github.com/Azure/Azurite) can't be run alongside the app which needs to be tested.

- What did you expect or want to happen?

Either
```
DefaultEndpointsProtocol=http;AccountName=account1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://account1.localhost:10000;EndpointSuffix=localhost:10000;
```
or
```
SharedAccessSignature=sv=2019-12-12&ss=btqf&srt=sco&st=2020-02-10T19%3A26%3A57Z&se=2050-02-11T19%3A26%3A00Z&sp=rwdxftlacup&sig=dT0xIFviqS3MzdT6ylixJbCVuy3CPsgcBdiobRKVkrI%3D;BlobEndpoint=http://account1.localhost:10000;
```
should be accepted and it should result in HTTP requests where the host header is set to `account1.localhost` instead of `account1.blob.localhost` (or failure in the case of the SAS token connection string). Azurite attempts to extract the account name from the host [here](https://github.com/Azure/Azurite/blob/456cbe74ca5c78b49e551b2659897ddf0d035b3c/src/blob/middlewares/blobStorageContext.middleware.ts#L142-L146) and ends up with `account1.blob`, which is not going to work. I could also use a hostname which doesn't end in `.localhost`, but then the account name is not set as the first part of the path [here](https://github.com/Azure/azure-sdk-for-go/blob/19fb1ff85758eb1a6fecc82f54ad681e03e6c548/storage/client.go#L518-L525) unless I use `devstoreaccount1` as the storage account, but that will force the Storage hostname to be [`localhost:10000`](https://github.com/Azure/azure-sdk-for-go/blob/19fb1ff85758eb1a6fecc82f54ad681e03e6c548/storage/client.go#L243-L245). 

- How can we reproduce it?

Call either `storage.NewClientFromConnectionString(tokenConnectionString)` or `storage.NewAccountSASClient(account1, sasTokenConnectionString, azure.PublicCloud)` (see [here](https://pkg.go.dev/github.com/Azure/go-autorest/autorest@v0.11.10/azure) for `azure.PublicCloud`) and then try to perform any blob operation.

- Anything we should know about your environment.

I assume this won't be fixed, given that this library is in legacy mode, but the new azure-storage-blob-go [does not have](https://github.com/Azure/azure-storage-blob-go/issues/244) connection string support yet.

In the meantime, I wanted to document a workaround, in case anyone is fighting with the same issue. I ended up placing Nginx as a reverse proxy in front of Azurite and I used the following config:

```
daemon off;

events {
}

http {
  server {
    listen 20000;
    server_name account1.blob.localhost;

    location / {
      proxy_pass http://127.0.0.1:10000;
      proxy_set_header Host account1.localhost;
    }
  }
}
```

Note that it requires setting `EndpointSuffix=localhost:20000` for the connection string or `BlobEndpoint=http://account1.blob.localhost:20000` for the SAS token connection string. Unfortunately, due to [this logic](https://github.com/Azure/azure-sdk-for-go/blob/19fb1ff85758eb1a6fecc82f54ad681e03e6c548/storage/client.go#L422-L431) we can't simply set the BlobEndpoint to `http://account1.localhost:20000` for the SAS token connection string as mentioned above. It also requires setting the `AZURITE_ACCOUNTS=account1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==` environment variable for the Azurite container.

Additional details:
- import path of package: `github.com/Azure/azure-sdk-for-go/storage`
- SDK version: `v51.1.0+incompatible`
- output of `go version`: `go version go1.15.6 darwin/amd64`

**Comment by ArcturusZhang** [comment]
Hi @mihaitodor thanks for opening this issue!

@jhendrixMSFT could you please take a look at this?

**Comment by jhendrixMSFT** [comment]
While you are correct that we aren't investing in this package any more, I'm happy to review and merge a PR to support this if you feel inclined.  If not then you'll have to wait for the updated blob storage package to support connection strings (I have a meeting with them soon and will bring this up).

**Comment by mihaitodor** [comment]
@jhendrixMSFT Thanks for the offer! I think I'm OK for now with the workaround. Would definitely consider sending a PR if this Azurite bug https://github.com/Azure/Azurite/issues/702 can also be solved somehow (any insight there?), because it would motivate me to revisit this integration to enable a few more tests in [benthos](https://github.com/Jeffail/benthos). Otherwise, I'd rather leave it as is for now, assuming the new blob storage package will get connection string support sometime this year.

**Comment by RickWinter** [comment]
The new blob package is available.
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob

**Comment by mihaitodor** [comment]
@RickWinter Thank you for the update, but I'm not sure I follow... I thought that github.com/Azure/azure-sdk-for-go/storage is getting deprecated in favour of https://github.com/Azure/azure-storage-blob-go. Can you please explain how this new `azblob` package relates to https://github.com/Azure/azure-storage-blob-go?
