### ISSUE TITLE
creating the private-endpoint fails for cross subscriptions

### ISSUE THREAD

**Issue by gowrisankar22** [Azure/azure-sdk-for-go#14306]
Hi,

I am creating a vnetprivate endpoint for a Postgres service which is running in a different subscription but it fails via golang SDK because it tries for auto-approval, ideally for cross subscriptions, it should be manual approval.

**Example:** 

**Subscription A:** Postgres service has been created.

**Subscription B:** Trying to create a private endpoint for the Postgres service which is created in the **Subscription A**

`version : github.com/Azure/azure-sdk-for-go v49.2.0+incompatible`

`2021-02-16T22:36:00.339+0530	ERROR	controllers.VnetPrivateEndpoint	Create event handler failed	{"vnetprivateendpoint": "pac/vnetprivateendpoint-example-foo", "error": "cannot create private endpoint: network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code=\"LinkedAuthorizationFailed\" Message=\"The client '447a4e3a-658c-4597-xxx' with object id '447a4e3a-658c-4597-xxxx' has permission to perform action 'Microsoft.Network/privateEndpoints/write' on scope '/subscriptions/8ab0fead-09eb-46dc-xxx/resourceGroups/rgtesitd/providers/Microsoft.Network/privateEndpoints/vnetprivateendpoint-example-foo'; however, it does not have permission to perform action 'PrivateEndpointConnectionsApproval/action' on the linked scope(s) '/subscriptions/6a08c93c-5ce0-4acb-xxxx/resourceGroups/dev2-customer-postgresql/providers/Microsoft.DBforPostgreSQL/servers/pacdemopostgresql1' or the linked scope(s) are invalid.\""}
github.com/go-logr/zapr.(*zapLogger).Error`

In addition to that golang SDK don't support adding approval note.

**PS:** if I do the same thing via azure console It works.

BRs, Gowrisankar

**Comment by MSSedusch** [comment]
@gowrisankar22 can you share a code sample in golang? 
The PrivateLinkServiceConnectionProperties type does have a request message. Is that what you mean by approval note?

**Comment by gowrisankar22** [comment]
@MSSedusch  Yes right for approval note. I will share the code via email to you.

**Comment by gowrisankar22** [comment]
after using `ManualPrivateLinkServiceConnections ` it worked but `approval note` is still not available

**Comment by gowrisankar22** [comment]
The approval note also worked.  the property name is: `Request Message`
