### ISSUE TITLE
An official Azure Monitor exporter for use by an opentelemetry-collector exporter

### ISSUE THREAD

**Issue by meastp** [Azure/azure-sdk-for-go#14305]
Today, you have some language-specific exporters for opentelemetry (in [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md), [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/monitor/monitor-opentelemetry-exporter/README.md) and you have an [exporter for .net in preview](https://github.com/Azure/azure-sdk-for-net/tree/Microsoft.OpenTelemetry.Exporter.AzureMonitor_1.0.0-beta.1/sdk/monitor/Microsoft.OpenTelemetry.Exporter.AzureMonitor)).

A similar exporter for go would not only benefit users of the go language, but could also be used in [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) which would benefit users of all the languages that opentelemetry supports.

**Comment by ArcturusZhang** [comment]
Hi @meastp thanks for opening this request!

I am not quite which exactly package you are requesting - but I have asked the corresponding service team's attention by tagging this issue. We would need them to initiate a release request anyway.

**Comment by meastp** [comment]
FYI It's @pcwiese who maintains the current (in opentelemetry/opentelemetry-collector-contrib repo) Azure Monitor Exporter. Perhaps he can give more context on what is needed? :)
