### ISSUE TITLE
Error while creating an subnet network.SubnetsCreateOrUpdateFuture: asynchronous operation has not completed

### ISSUE THREAD

**Issue by gowrisankar22** [Azure/azure-sdk-for-go#14334]
Hello,

I am creating a resource group,vnet, subnet, and nsg together using golang SDK but it is giving me the below error.

I took the examples from [1]

```
error": "network.SubnetsCreateOrUpdateFuture: asynchronous operation has not completed"}
```

[1] https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/network

can someone help to fix the issue?

**Comment by ArcturusZhang** [comment]
Hi @gowrisankar22 thanks for this issue!

@jhendrixMSFT does this look like a SDK issue, `go-autorest` polling issue or API issue to you? In the example code, we invoke `future.Result` after the `future.WaitForCompletionRef`, but we still get an result of "not done" in the `DoneWithContext` function (only this call throws this error message)

**Comment by jhendrixMSFT** [comment]
I can't repro this.

Can you please run your repro with [`DEBUG` logging enabled](https://github.com/Azure/azure-sdk-for-go#built-in-basic-requestresponse-logging) and share the trace please.

**Comment by gowrisankar22** [comment]
The issue is fixed as per @ArcturusZhang suggestion.

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang were you able to repro?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang were you able to repro?

Well.. no...weird

**Comment by jhendrixMSFT** [comment]
I'm going to close this given the lack of info.  @gowrisankar22 I know you have a workaround but if you can share more info to help us root-cause the issue that would be great.
