### ISSUE TITLE
How to assign a self-signed certificate for Azure Stack

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-go#1435]
Azure Stack development kit uses a self-signed certificate. How to assign it when using azure-sdk-for-go?
If not specified, I got the following error:
```
Get https://management.local.azurestack.external/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.Resources/deployments/xxx?api-version=2017-05-10: x509: certificate signed by unknown authority"
```

**Comment by vladbarosan** [comment]
@bingosummer can you please clarify what you mean ? (i.e. give a sample code of what you are trying to do ? ) Are you referring to using a self signed client certificate for auth  ?

**Comment by marstr** [comment]
Closing as stale, feel free to mention us and have it re-opened.

**Comment by bingosummer** [comment]
I figured it out. I need to put the self-signed certificate in `/etc/ssl/certs/ca-certificates.crt`.
