### ISSUE TITLE
Use a specific type for Azure resource IDs

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1437]
In https://github.com/Azure/go-autorest/commit/ed4b7f5bf1ec0c9ede1fda2681d96771282f2862 we added functionality for parsing Azure resource IDs.  We should investigate if our codegen can emit the azure.Resource type instead of a plain ol' string for resource IDs.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT so this'd be awesome to have 👍

We currently have an extended version of this behaviour within Terraform - where we parse all of the values out of the URI into [a dictionary/map[string]string](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resourceid.go#L18) which allows us to key into particular values; which it'd be great to add to this implementation if possible. We've noticed that certain Azure API's can return resources in different cases however, as such we've got a few resources which contain snippets to below:

```
config := id.Path["redis"]
if config != nil {
  config := id.Path["Redis"]
}
```

(Redis isn't affected by this particular issue, it's just to demonstrate the point)

Is the intention to extend this behaviour to return the extra properties as strongly typed fields? e.g. in the case of Redis:

> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cache/Redis/{cacheName}/firewallRules/{ruleName}

```
type RedisFirewallResource struct {
  Resource azure.Resource
  CacheName string
  RuleName string
}
```

On a related note - it'd be really handy to have the reverse, to be able to return the URI without having to make a Get request to Azure if possible (but I think there's a separate issue tracking that) :)

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff If we can get this reliably working for the base resource ID we can certainly look at extending it for provider-specific properties as you've outlined.  We can also add a method to reconstitute the URI.
CC @vladbarosan

**Comment by vladbarosan** [comment]
@tombuildsstuff thanks for the feedback. 

In the example you provided the ResourceId is for a `RedisFirewallRule` and our helper would should return the `{ruleName}` which is what the resource name is and what our helper would return. 

Would it be enough for your use case to have the Resource Name and the complete Resource Name returned ( i.e. when they are scoped under another resource like in this case ) ? That way we can keep it generic.

**Comment by vladbarosan** [comment]
@tombuildsstuff or maybe a wrapper type around the resource name which can either return the qualified name as a string or the actual resource name as a string or a map of the qualified resource name like in the terraform code

**Comment by tombuildsstuff** [comment]
@vladbarosan so I was thinking it might be possible to generate a type for each API Type as from the Swagger, rather than just returning the name; since the `Get` calls require multiple values (e.g. Express Route Circuit Peerings which require the Resource Group Name, the Circuit Name and the Peering name)?

**Comment by ArcturusZhang** [comment]
This issue should be resolved now, closing
