### ISSUE TITLE
Proposal: Convert this repo to a Go module

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#14387]
Please add a 👍 reaction if you support this proposal. If you do not, please leave a comment describing why.

Now that Go modules have solidified and are on by default in Go 1.16 we are considering how we migrate this repo to officially support them (this is for our track 1 content; track 2 already supports modules).

In keeping with our current release strategy and version, the natural option would be to place a `go.mod` file in the root of the repo.  However, given that we've already had dozens of major releases (`v52.3.0` at the time of this writing), it would mean that the next major version would introduce [semantic import versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning).

In `go.mod`:
```
module github.com/Azure/azure-sdk-for-go/v53
```

This would require consumers to update their import statements starting with `v53` and beyond.

```
import github.com/Azure/azure-sdk-for-go/v53/services/foo/bar
```

While this "plays by the rules" it introduces a burden on consumers and we'd like feedback on the impact.

**Comment by jhendrixMSFT** [comment]
Unfortunately this places a significant burden on consumers that use a large number of packages from this SDK.  This was mentioned [here](https://github.com/Azure/azure-sdk-for-go/pull/14626#discussion_r623995504) on the negative impact it would have on Terraform.

**Comment by marchesir** [comment]
well at some point go may force the change, so not easy on anybody. i for 1 have an issue azure-sdk-for-go is required by terratest but where i work we use artifactory and as there is no go.mod it makes downloading hard as artifactory assumes .mod.

**Comment by jhendrixMSFT** [comment]
I tend to agree.  It's a bitter pill but is likely inevitable.  In addition, I recall there was talk about tooling to simplify updating a major module version.

CC @tombuildsstuff

**Comment by bcmills** [comment]
Regarding upgrade automation, I am aware of at least https://github.com/golang/go/issues/32816 and https://github.com/golang/go/issues/32014, as well as a couple of existing tools (https://github.com/icholy/gomajor and https://github.com/marwan-at-work/mod, but others may exist too).

**Comment by bcmills** [comment]
I'm also planning to address module aliasing and renaming (golang/go#26904) for Go 1.18 (due out EoY this year), and it's possible that that will include a way for an existing module to leave a “fowarding address”.

(More design work is needed, but migrating from one module path to another — including from an unversioned path to a versioned one — is an important use-case that we're actively thinking about.)

**Comment by jhendrixMSFT** [comment]
Given that `/services` has moved to maintenance mode and is superseded by our new, module-based SDKs, I don't think it's worth making this change to the legacy SDK.
