### ISSUE TITLE
Support Gen2 for PowerBI Embedded 

### ISSUE THREAD

**Issue by kosinsky** [Azure/azure-sdk-for-go#14399]
### Feature Request

Current version of the SDK supports only Gen 1 for Power BI Embedded. Please, add support for Gen 2. ARM templates already support that: https://docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-create-capacity?tabs=ARM-template#embedded-gen2-preview

That will allow to add support for PBI Embedded Gen 2 to terraform azurerm provider https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/powerbi_embedded

**Comment by kosinsky** [comment]
@ArcturusZhang Looks like PowerBI Dedicated is the next step. They recently added version 2021-01-01 to the swagger:

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2021-01-01 and it does support Gen2 (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2021-01-01/powerbidedicated.json#L864)
Older 2017 version doesn't have that property and GO SDK supports only 2017 version: https://github.com/Azure/azure-sdk-for-go/tree/master/services/powerbidedicated/mgmt/2017-10-01/powerbidedicated

Could 2021-01-01 version be exposed to GO SDK?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang Looks like PowerBI Dedicated is the next step. They recently added version 2021-01-01 to the swagger:
> 
> https://github.com/Azure/azure-rest-api-specs/tree/master/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2021-01-01 and it does support Gen2 (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2021-01-01/powerbidedicated.json#L864)
> Older 2017 version doesn't have that property and GO SDK supports only 2017 version: https://github.com/Azure/azure-sdk-for-go/tree/master/services/powerbidedicated/mgmt/2017-10-01/powerbidedicated
> 
> Could 2021-01-01 version be exposed to GO SDK?

Unfortunately exposing a new package or updating an existing api-version should be initiated by the service team, so that we would know the corresponding swaggers are ready to ship SDKs. 
I will try let the service team know about this package request in our SDK.

**Comment by kosinsky** [comment]
@ArcturusZhang did you hear back form Power BI team? Python SDK was updated to use new version of the API ~2 month ago: https://github.com/Azure/azure-sdk-for-python/pull/17585

**Comment by ArcturusZhang** [comment]
Hi @kosinsky sorry for the delay but I just pinged the corresponding service team again using internal email.

**Comment by kosinsky** [comment]
We could close that. v55.1.0 added support for 2021-01-01 API for Power BI which includes Gen2 support: https://github.com/Azure/azure-sdk-for-go/pull/14727/files#diff-71e3b93c89042c183f656c256a4f0023bba0ac2987a70fa6db58504c916eed5e
