### ISSUE TITLE
Convert track 2 to one module per RP

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#14396]
Original plan was to release one module per RP/API version.  While this gives the greatest flexibility in terms of versioning, it creates an enormous amount of modules which is just too complex.

The new plan is to release one module per RP, so e.g. there will be separate modules for `compute`, `network` etc.  Each module will contain all API versions for its RP.

**Comment by jhendrixMSFT** [comment]
In addition, each RP will have a separate module for preview API versions.

**Comment by lirenhe** [comment]
@jhendrixMSFT, I think for track 2, we have decided to use single api version in one module. In general, we will release one module for one RP except for some special RP like resources. 
 Is there any additional action items still needed for this issue

**Comment by jhendrixMSFT** [comment]
Closing as this is POR for track 2.
