### ISSUE TITLE
[Storage] Getting error "StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format." while using batch operations on tables and sasToken client.

### ISSUE THREAD

**Issue by rafalrygas** [Azure/azure-sdk-for-go#14402]
### Bug Report

Paths:
` github.com/Azure/azure-sdk-for-go/storage`

Version: v52.3.1

**What happened?**

After creating storage client using `NewAccountSASClientFromEndpointToken` everything works correctly. 
When trying to create storage client using `NewAccountSASClientFromEndpointToken` there is always an error while using batch operations on tables (`storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.`). Standard operations work correctly.

**What did you expect or want to happen?**

Working with client created by `NewAccountSASClientFromEndpointToken` method.

**How can we reproduce it?**

1. Create storage account
2. Generate sasToken
3. Create table
4. Run below code

```
import (
	azstorage "github.com/Azure/azure-sdk-for-go/storage"
)

//...

client, _ := azstorage.NewAccountSASClientFromEndpointToken(host, sasToken)

tableService := client.GetTableService()

table := tableService.GetTableReference(tableName)

tableBatch := table.NewBatch()

entity := table.GetEntityReference("partkey1", "rowkey1")

tableBatch.InsertOrReplaceEntityByForce(entity)

err := tableBatch.ExecuteBatch()
println(err.Error())
```

Returns:
```
storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.
RequestId:628b8b14-3002-008e-4e17-143c18000000
Time:2021-03-08T12:35:27.9143308Z, RequestInitiated=Mon, 08 Mar 2021 12:35:27 GMT, RequestId=628b8b14-3002-008e-4e17-143c18000000, API Version=
```

**Comment by ArcturusZhang** [comment]
Hi @rafalrygas thanks for this issue!

Add @jhendrixMSFT for help since this is a legacy storage package issue

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

The tables functionality in the `/storage` package has been deprecated in favor of our new [`aztables`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables) module.  Can you please try it and see if it resolves your issue?
