### ISSUE TITLE
The future hangs when invoking `WaitForCompletionRef()`

### ISSUE THREAD

**Issue by xingtanzjr** [Azure/azure-sdk-for-go#14418]
Hi all,

I encounter an issue when set administrator for Azure PostgreSQL. My code is as follows:
```
	future, err := adminClient.CreateOrUpdate(ctx, config.ResourceGroup, config.ServerName, pgservers.ServerAdministratorResource{
		ServerAdministratorProperties: &pgservers.ServerAdministratorProperties{
			Login:             &config.ClientID,
			AdministratorType: &config.AdministratorType,
			TenantID:          config.TenantID,
			Sid:               config.SecureID,
		},
	})

	if err != nil {
		return err
	}
	log.Info(fmt.Sprintf("[%s] Wait for Administrator creating/updating to complete...", config.ServerName))
        // The codes stucks here
	if err := future.WaitForCompletionRef(ctx, adminClient.Client); err != nil {
		return fmt.Errorf("cannot get the Administrator create or update future response: %+v", err)
	}
```

When I invoking the method `future.WaitForCompletionRef()`, the thread hangs here. But actually the request is successfully and the admin is also set successfully.

**I checked the source code for WaitForCompletionRef(), and found that the `delay` is `600s` inside this function**
```
	// if the initial response has a Retry-After, sleep for the specified amount of time before starting to poll
	if delay, ok := f.GetPollingDelay(); ok {
		if delayElapsed := autorest.DelayForBackoff(delay, 0, cancelCtx.Done()); !delayElapsed {
			err = cancelCtx.Err()
			return
		}
	}
```

It seems that the delay is calculated from response's header `Retry-After`. 

Is this an issue or is there some way to make the future could returned quickly ?

Thanks!

**Comment by tombuildsstuff** [comment]
Sounds like the API itself is returning a long Retry-After header, which would root-cause this issue, I guess? https://github.com/Azure/azure-rest-api-specs/issues/13115

**Comment by ArcturusZhang** [comment]
Hi @xingtanzjr thanks for opening this issue

Since this is caused by a long Retry-After header, I marked this issue by Service Attention so that the corresponding service team could see this issue.
