### ISSUE TITLE
RedisEnterprise missing values

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-sdk-for-go#14420]
### Bug Report

- import path of package: `.../services/redisenterprise/mgmt/2021-03-01/redisenterprise`
- SDK version: `v52.3.0`
- output of `go version`: `go version go1.16.1 linux/amd64`

**Issue:**
The following attributes are not returned by the RP:
* `hostname`
* `version`

you are are also unable to set the `MinimumTLSVersion` value on the `ClusterProperties`

What happened?
* The values were never implemented.

What did you expect or want to happen?
* The values should be implemented and returned as expected per documentation.

How can we reproduce it?
* Use the API, it has never worked.

Anything we should know about your environment:
* No

**Comment by terrycain** [comment]
Not sure if this is the right issue to add this, but I couldn't find a way in the SDK to get the access keys either. Would be nice to add so it can be exposed via terraform.

**Comment by ArcturusZhang** [comment]
Hi @WodansSon thanks for this issue!

Sometimes this kind of issues happens, maybe the service team is keeping them reserved for the future, or simply mistakes in swaggers. I have tagged this issue as Service Attention so that the corresponding service team could take a look at this.

**Comment by greenms** [comment]
@WodansSon @ArcturusZhang The RP now returns the `hostName` and `minimumTlsVersion` cluster properties.  The RP also now allows the `minimumTlsVersion` cluster property to be set at create time (however, in contradiction to the REST API, the RP is currently blocking the update of `minimumTlsVersion` after create time).  https://github.com/terraform-providers/terraform-provider-azurerm/issues/11199
