### ISSUE TITLE
ARM template validation returns an error on bad template (change of behavior compared to past SDK versions)

### ISSUE THREAD

**Issue by Diastro** [Azure/azure-sdk-for-go#14423]
### Bug Report

 When using the latest version of the `SDK (v52.4.0)` the arm deployment client [Validate()](https://github.com/Azure/azure-sdk-for-go/blob/20a795df04f235f71d70edfb23b3d8e28bcfbb19/services/resources/mgmt/2020-06-01/resources/deployments.go#L3543) function will return an error on template validation failure. In previous SDK versions, the validate call wouldn't return an error for a template validation problem (an error would only be expected if a request error would have happened). Instead, the template validation error was present in the DeploymentValidateResult structure.

We have debugged the code and we believe the change in behavior is caused by the code change in [deployment.go:ValidateSender()](https://github.com/Azure/azure-sdk-for-go/blob/20a795df04f235f71d70edfb23b3d8e28bcfbb19/services/resources/mgmt/2020-06-01/resources/deployments.go#L3611). When a template validation fails (due to a bad template) the Resources RP returns 400 which is treated as a "failed" request by the autorest/the SDK causing an error value to be returned.

The way I see it, the Resources provider always returned 400 for this specific case (which [autorest will usually treat as an error due to this code](https://github.com/Azure/go-autorest/blob/c7f947c0610de1bc279f76e6d453353f95cd1bfa/autorest/azure/async.go#L414)). In the past, because ValidateSender wasn't using Future this wouldn't be an issue, but it seems like the lastest few major version of the SDK (where Future were added for the Validate call) is what introduced this problem. I'm not sure if the RP is the one which should change his response on bad template or some code has to be added to the SDK to handle this but the behavior as things stands in the latest release isn't correct IMO.

**Comment by ArcturusZhang** [comment]
Hi @Diastro thanks for this issue!

We did change the implementation of the future responder in past major versions - which might have unresolved issues.
CC @jhendrixMSFT for awareness.
Could you provide some more information on this so that we can investigate this more and perhaps provide a fix for this in the next major version?

**Comment by jhendrixMSFT** [comment]
The working version in the past was API version 2019-05-01 yes?  The `DeploymentsClient.Validate()` method for 2020-06-01 (the one linked) has always been a long-running operation thus it's always returned a future.

This is an interesting case.  The [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L1818) for the 2020-06-01 API version specifies an HTTP 400 as a success code which doesn't work with our future logic (I suspect other SDKs don't honor this either).

Can you use the older API version for now?  I don't anticipate a quick fix for this, assuming the swagger is correct.
