### ISSUE TITLE
FutureAPI Confusion

### ISSUE THREAD

**Issue by plombardi89** [Azure/azure-sdk-for-go#14433]
So I tried updating some older code to use the latest v52.4.0 release after reading through https://github.com/Azure/azure-sdk-for-go/issues/14010 and thinking the issue around the interface clients and future API requiring concrete types was resolved... but I think I am even more confused now than I was before.

Can we get an example of how one of these FutureAPI's is supposed to be used properly so that there isn't a dependency on the concrete client struct? I noticed there's now a `Result(<Client>)` func declared on the result Future, for example:

```golang
// GalleriesCreateOrUpdateFuture an abstraction for monitoring and retrieving the results of a long-running
// operation.
type GalleriesCreateOrUpdateFuture struct {
	azure.FutureAPI
	// Result returns the result of the asynchronous operation.
	// If the operation has not completed it will return an error.
	Result func(GalleriesClient) (Gallery, error)
}
```

The ClientAPI types return these Future's, for example:

```golang
type GalleriesClientAPI interface {
	CreateOrUpdate(ctx context.Context, resourceGroupName string, galleryName string, gallery compute.Gallery) (result compute.GalleriesCreateOrUpdateFuture, err error)
    [...]
}
```

How are you supposed to pass the ClientAPI interface type to `Result(<Client>)`? func that expects a concrete struct? I thought the whole point of GH-14010 was to make it so the interfaces could be used without requiring we somehow also get the concrete client. If I am missing something obvious then I would love an example.

EDIT:

Is this how this is supposed to be done? Feels kind of clunky:

```golang
               // assume "gc" is a GalleriesClientAPI

		fut, err := gc.CreateOrUpdate(ctx, p.ResourceGroup, p.ImageGalleryName, g)
		if err != nil {
			return err
		}
		
		if err := fut.WaitForCompletionRef(context.Background(), autorest.Client{}); err != nil {
			return err
		}
		
		fut.Result = func(_ compute.GalleriesClient) (compute.Gallery, error) {
			return gc.Get(context.Background(), p.ResourceGroup, p.ImageGalleryName) 
		}
```

**Comment by ArcturusZhang** [comment]
Hi @plombardi89 thanks for this issue!

The `Result` method is not in the interface, therefore if you want to write code with the interfaces, I recommend that we do not use the `Result` method. After the `WaitForCompletionRef` function successfully returns, we could just simply invoke `Get` function on the client to get the result.
CC @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
I agree this is clunky.  It was a trade-off made to keep the API compatible while providing a way to mock the `Result()` method.  Since the `Result()` method is type-specific we can't place it in the interface (this will be fixed once we have generics).

**Comment by jhendrixMSFT** [comment]
Here's an example I came up with for mocking this.

```go
type fakeGalleriesClient struct {
	computeapi.GalleriesClientAPI
}

func (f fakeGalleriesClient) CreateOrUpdate(ctx context.Context, resourceGroupName string, galleryName string, gallery compute.Gallery) (result compute.GalleriesCreateOrUpdateFuture, err error) {
	return compute.GalleriesCreateOrUpdateFuture{
		FutureAPI: fakeFuture{},
		Result: func(compute.GalleriesClient) (compute.Gallery, error) {
			return compute.Gallery{}, nil
		},
	}, nil
}

type fakeFuture struct {
	azure.FutureAPI
}

// add implementations for azure.FutureAPI to fakeFuture...
```
