### ISSUE TITLE
Update Identity README

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-go#14440]
Identity README Changes:
- [x] Update the DAC description to look like [this](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#defaultazurecredential).
- [x] Add Detailed Identity examples in the wiki for Identity Scenarios mentioned [here](https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Identity-Examples) and reference the link to the wiki in the README as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#examples).
- [x] Add Example for Default Azure Credential in README as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#examples).
- [x] Add Configuration, examples reference links to Credential classes tables as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#credential-classes).
- [x] Update the Next Steps to reference the libraries in azure-SDK repos as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#next-steps).
- [x] Add Managed Identity Support section as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#managed-identity-support).

MS Docs Change:
- [x] Update Azure SDK for GO Identity MS Docs to contain the content as [here](https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity).

**Comment by catalinaperalta** [comment]
Adding @elraikhm who can help with the MS Docs portion of this issue.
