### ISSUE TITLE
SDK Installation takes forever

### ISSUE THREAD

**Issue by siddjoshi** [Azure/azure-sdk-for-go#14459]
Hi,

I am trying to install the SDK with below command 
go get -u github.com/Azure/azure-sdk-for-go/...

It takes hours and still does not complete. I tried multiple times on different machines with same result. Is there something I am doing wrong or there is known issue with it ? How long it usually takes to "go get" it. 

Regards
Siddharth

**Comment by siddjoshi** [comment]
To reproduce the issue, please try building docker image with below dockerfile 

`FROM golang:latest
RUN apt-get update
RUN go get -u github.com/Azure/azure-sdk-for-go/...
`

I also noticed that during the process, it makes my machine extremely slow, and consume huge disk space (5 GB+ and ongoing). I have never tried this SDK before so not sure if it is expected to consume this much space.

**Comment by ArcturusZhang** [comment]
Hi @siddjoshi Thanks for this issue!

Hey @jhendrixMSFT could you please take a look?

**Comment by siddjoshi** [comment]
The installation never got completed , so didn't get chance to run it.

**Comment by lirenhe** [comment]
The issue should be related to the network issue which we are unable to control.  
Close it as there is no action that we could take
