### ISSUE TITLE
Support servicePublicIPAddress in PublicIPAddress properties.

### ISSUE THREAD

**Issue by TonyDou** [Azure/azure-sdk-for-go#14465]

**Comment by ArcturusZhang** [comment]
Hi @TonyDou thanks for this issue!

I assume the requested package should be `network`. The network team usually release a new SDK when they publish a new api-version.

**Comment by TonyDou** [comment]
Yes, the package should be network. This new property is released in version "2019-09-01", a relatively old version now. But it's not added to this sdk yet.

**Comment by ArcturusZhang** [comment]
> Yes, the package should be network. This new property is released in version "2019-09-01", a relatively old version now. But it's not added to this sdk yet.

Did you check the latest api-version? Usually we do not regenerate the old api-versions once we have newer api-versions.

**Comment by TonyDou** [comment]
I just checked it does not exist in the latest version 2020-11-01.

**Comment by ArcturusZhang** [comment]
It is interesting that this `servicePublicIPAddress` does not exist in 2020-11-01 or 2020-07-01, but it exists in 2020-08-01. This will need an explanation from the corresponding service team.
