### ISSUE TITLE
if all properties in a struct are readOnly, do not serialize this struct when sending request

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-sdk-for-go#14478]
### Feature Request

track1 go sdk
bug encountered: if a resource enable user assigned identity, it's common that we get the resource first, then modify the fields and fire the update api request.  The backend service will report error:
```
Invalid value for the identities '/subscriptions/sub-id/resourceGroups/resource-group-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."
```

this cause a lot of trouble for users

https://github.com/terraform-providers/terraform-provider-azurerm/issues/10406

**Comment by norshtein** [comment]
Hi @ArcturusZhang , any progress on this issue?

**Comment by ArcturusZhang** [comment]
We will enroll this change in this month's major version release.
