### ISSUE TITLE
NewVirtualMachineRunCommandsClient references retired RunCommandPreview

### ISSUE THREAD

**Issue by reciproke79** [Azure/azure-sdk-for-go#14493]
I experience a problem when utilising the **NewVirtualMachineRunCommandsClient** from the compute package, i.e. github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-01/compute 

When using the **CreateOrUpdate** method I'm getting the response:

```
compute.VirtualMachineRunCommandsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="The property 'runCommands' is not valid because the 'Microsoft.Compute/RunCommandPreview' feature is not enabled for this subscription."
{<nil> <nil>}
```

Microsoft confirmed, that the **Microsoft.Compute/RunCommandPreview** feature is no longer used/available. It seems that the RunCommandClient mentioned above still references that feature somehow?

**Comment by ArcturusZhang** [comment]
Hi @reciproke79 thanks for this issue.

Based on the error message here, the error is returned from the service and not related with the SDK itself. Therefore I tagged this issue so that the corresponding service team could take a look at this issue.

**Comment by avirishuv** [comment]
hi @axayjo could you take a look at this?

**Comment by axayjo** [comment]
@reciproke79 We're currently adding new features to the Run Command Extension and you're running into one of those features. Can you please use only the documented features of [Run Command Extension](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command)?

**Comment by axayjo** [comment]
Closing this issue. Please reopen the issue in case this warrants further discussion. We'll be announcing a preview of the new version of Run Command by end of the year.
