### ISSUE TITLE
Unable to create frontdoor service.

### ISSUE THREAD

**Issue by sidheshdivekar29** [Azure/azure-sdk-for-go#14511]
Hi,

I am trying to create new front door service.
The api I am using is as follows:-
```
i := f.FrontDoor{
		autorest.Response{&http.Response{}},
		&f.Properties{
			BackendPools: &[]f.BackendPool{
				{
					&f.BackendPoolProperties{
						Backends: &[]f.Backend{
							{
								Address:      to.StringPtr("papp.abc.com"),
								EnabledState: f.Enabled,
								HTTPPort:     to.Int32Ptr(HTTPPort),
								HTTPSPort:    to.Int32Ptr(HTTPSPort),
								Priority:     to.Int32Ptr(1),
								Weight:       to.Int32Ptr(100),
							},
						},
						HealthProbeSettings:   &f.SubResource{ID: to.StringPtr("")},
						 LoadBalancingSettings: &f.SubResource{ID: to.StringPtr("")},
					},
					// Name - Resource name.
					to.StringPtr("bep-1"),
					// Type - READ-ONLY; Resource type.
					nil,
					// ID - Resource ID.
					nil,
				},
			},
			FrontendEndpoints: &[]f.FrontendEndpoint{
				{
					autorest.Response{&http.Response{}},
					&f.FrontendEndpointProperties{
						HostName: to.StringPtr(appDmn),
					},
					// Name - Resource name.
					to.StringPtr(name),
					// Type - READ-ONLY; Resource type.
					nil,
					// ID - Resource ID.
					nil,
				},
			},
			HealthProbeSettings: &[]f.HealthProbeSettingsModel{
				{
					&f.HealthProbeSettingsProperties{
						Path:              to.StringPtr(AzureFDHCPath),
						Protocol:          f.HTTPS,
						IntervalInSeconds: to.Int32Ptr(30),
						HealthProbeMethod: f.GET,
						EnabledState:      f.HealthProbeEnabledEnabled,
					},
					// Name - Resource name.
					to.StringPtr("hps-1"),
					// Type - READ-ONLY; Resource type.
					nil,
					// ID - Resource ID.
					nil,
				},
			},
			LoadBalancingSettings: &[]f.LoadBalancingSettingsModel{
				{
					&f.LoadBalancingSettingsProperties{
						SampleSize: to.Int32Ptr(5),
						SuccessfulSamplesRequired: to.Int32Ptr(2),
						AdditionalLatencyMilliseconds: to.Int32Ptr(0),
					},
					to.StringPtr("lb-settings"),
					nil,
					nil,
				},
			},
			RoutingRules: &[]f.RoutingRule{
				{
					&f.RoutingRuleProperties{
						FrontendEndpoints: &[]f.SubResource{},
						AcceptedProtocols: &[]f.Protocol{f.HTTP, f.HTTPS},
						PatternsToMatch: &[]string{"/*"},
						RouteConfiguration: f.ForwardingConfiguration{
							ForwardingProtocol: f.MatchRequest,
							OdataType:          f.OdataTypeMicrosoftAzureFrontDoorModelsFrontdoorForwardingConfiguration,
						},
					},
					to.StringPtr("rr-1"),
					nil,
					nil,
				},
			},
		},
		nil,
		to.StringPtr(name),
		nil, 
		to.StringPtr(location),
	}

	r, err := fdClient.CreateOrUpdate(ctx.Background(), rg, name, i)
	if err != nil {
		o.log.Error(err.Error())
		return nil, err
	}
```

I am getting following error from azure. Am forced to pass following two field.

```
						HealthProbeSettings:   &f.SubResource{ID: to.StringPtr("")},
						 LoadBalancingSettings: &f.SubResource{ID: to.StringPtr("")},
```

 I thought there would be separate apis to create to create BackendPool, FrontendEndpoints, HealthProbeSettings & LoadBalancingSettings which I can use to create the resources and then pass their ids in above api. But am unable to find them. Can you let me know these apis are missing and what is the workaround for the same.

> Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Property 'FrontdoorEntityV2.BackendPools[0].Properties.LoadBalancingSettings' is required but it was not set; \nProperty 'FrontdoorEntityV2.BackendPools[0].Properties.HealthProbeSettings' is required but it was not set; \nProperty 'FrontdoorEntityV2.RoutingRules[0].Properties.FrontendEndpoints' is not within the minimum and maximum acceptable range for number of elements [1-2147483647].; \nProperty 'FrontdoorEntityV2.RoutingRules[0].Properties.RouteConfiguration.BackendPool' is required but it was not set"

All of these resources could be created from the file present in the following commit but I don't see these files anywhere in the git repository. 

Is this commit missing - https://github.com/Azure/azure-sdk-for-go/pull/2781/commits/b7f8341c0de94683f1bae6e2185c71256e35edce ?

**Comment by ArcturusZhang** [comment]
Hi @sidheshdivekar29 thanks for this issue!

The validation rules you encountered here come from the service side, therefore I have tagged this issue so that the corresponding service team could take a look at this issue.

**Comment by jbald-insight** [comment]
Was this resolved? I get the same error deploying Frontdoor from Bicep.
