### ISSUE TITLE
[Track2] Discriminator Unmarshalling Discriminator Value Compare Bug

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#14519]
### Bug Report

In Track2 generated code, e.g. https://github.com/ArcturusZhang/azure-sdk-for-go/blob/sdk/arm/network/v0.4.1/sdk/arm/network/2020-07-01/armnetwork/zz_generated_polymorphic_helpers.go#L22 (note that I'm using the fork from ArcturusZhang), the comparision between the `json.RawMessage` value and the enum const will never match, since their type are different. Therefore, the switch case will always hit the default branch.

Instead, the code shall cast them to the same type.

**Comment by catalinaperalta** [comment]
Closed in https://github.com/Azure/autorest.go/pull/603

**Comment by magodo** [comment]
@catalinaperalta Thank you for the fix! I've verified that it works after I adopt the track2 SDK to Terraform provider for the resource containing discriminator models.
