### ISSUE TITLE
Databricks Workspace does not call Update(e.g. PATCH) when CreateOrUpdate function is called 

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-sdk-for-go#14571]
### Bug Report

- import path of package: `.../services/databricks/mgmt/2018-04-01/databricks`
- SDK version: `53.3.0`
- go version: 1.16

**Description:**
Currently in the API when you call the `CreateOrUpdate` function with a change only to the `tags` of the resource it will only update the `tags` for the workspace resource only and not the connected resources to the workspace. Ultimately this should be handled by the service teams API and not the end user. As a workaround to unblock current customers we had to implement extra code in the Terraform provider to correctly fix the propagation of tags to the connected resources.

Terraform PR to fix issue: https://github.com/terraform-providers/terraform-provider-azurerm/pull/11405 

**Expected:**
When the end user updates a tag on the workspace the tag should flow to all of the connected resources that are associated with that workspace. This is facilitated by the `PATCH` call to the RP, which currently is an extra manual step that has to be done by the customer. The RP should handle this natively without the extra step of calling a separate `UPDATE` function.

**Repro:**
1) Using terraform use the below HCL configuration to provision a workspace resource.
```HCL
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "testrg"
  location = "eastus2"
}
resource "azurerm_databricks_workspace" "workspace" {
  name                = "testws"
  resource_group_name = "testrg"
  location            = "eastus2"
  sku                 = "standard"

  tags = {
    Environment = "terraformtest"
  }
}
```
2) Once the workspace is has been provisioned, update the configuration file like the below HCL example, to add a new tag to the resource.
```HCL
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "testrg"
  location = "eastus2"
}
resource "azurerm_databricks_workspace" "workspace" {
  name                = "testws"
  resource_group_name = "testrg"
  location            = "eastus2"
  sku                 = "standard"

  tags = {
    Environment    = "terraformtest"
    WorkspacePatch = "terraformtest"
  }
}
```  
3) Using the Azure Portal or Resource Explorer to view the workspace resource. You will notice that the updated `tag` has been added to the workspace resource as expected. Now navigate to the `Managed Resource Group` and observe the `tags` of the connected resource. It will not have the added `tag`.

**Comment by ArcturusZhang** [comment]
Hi @WodansSon thanks for this issue!

I have tagged this issue so that the corresponding service team could come and have this a look.
In the meantime, I suppose if this client supports `Update`, maybe we need to use `Update` function to handle the update procedure in terraform? What do you think?

**Comment by WodansSon** [comment]
@ArcturusZhang, yep, totally agree... that is exactly what I did as a temporary workaround for this issue to unblock our customers, but this scenario really should be handled by the RP as stated above in the issue. 🙂

**Comment by ArcturusZhang** [comment]
@WodansSon Agreed that this definitely needs to be fixed. Let us wait for the service team's response on this issue...

**Comment by msaranga** [comment]
@WodansSon : We are not notified about this issue previously. I just encountered when jeffrey cline pointed. we will be working on fix in upcoming sprints. NO concrete ETA yet. Please contact Bhanu Prakash on timeline.

**Comment by tombuildsstuff** [comment]
@msaranga https://github.com/hashicorp/terraform-provider-azurerm/issues/14606 highlights that these Tags also need to be propagated to the managed resource group too fwiw

**Comment by tombuildsstuff** [comment]
@ArcturusZhang any update on this one?

**Comment by RickWinter** [comment]
> @WodansSon : We are not notified about this issue previously. I just encountered when jeffrey cline pointed. we will be working on fix in upcoming sprints. NO concrete ETA yet. Please contact Bhanu Prakash on timeline.

@msaranga , @WodansSon Can you update this issue please
