### ISSUE TITLE
IoTHub Service package giving schema error

### ISSUE THREAD

**Issue by niksacdev** [Azure/azure-sdk-for-go#1458]
I am trying to create a sample for the IoT Hub Mgmt client, the Service folder currently has three versions and I am using the "github.com/Azure/azure-sdk-for-go/services/iothub/mgmt/2017-07-01/devices" version.

however when I make a call to:
```
.....
future, err := client.CreateOrUpdate(ctx, helpers.ResourceGroupName(), *hubSettings.Name, hubSettings, "")
....
```
I get the following error:
*cannot create iothub: devices.IotHubResourceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="**InvalidApiVersionParameter**" Message="The api-version '2017-07-01' is invalid. The supported versions are '2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."*

I can generate my own descriptions using autorest from the azure-rest-api-specs./specifications/iothub iothub.json file but I want to use the Go SDK path so I can import the right services package.

**Comment by jhendrixMSFT** [comment]
Hi @niksacdev, in what Azure region are you running this?
CC @kvish

**Comment by marstr** [comment]
Closing this as stale.

For folks who are reading this thread with the same problem:
Depending on the Azure Region you're targeting, the API Version of the Resource Provider you're using may or may not be available yet. Usually it sends back a message like above with a list of API Versions that should be easy to match-up in our SDK. However, if you target a region where that Resource Provider has not deployed any API Versions yet, Azure Resource Management gets confused and sends back a list of its own API Versions that are supported in that region. This can be kinda confusing, but is a known issue.
