### ISSUE TITLE
Azure Marketplace List and GetAgreement API returns errors

### ISSUE THREAD

**Issue by gargi** [Azure/azure-sdk-for-go#14628]
### Bug Report

- import path:  `services/marketplaceordering/mgmt/2015-06-01/marketplaceordering`
- SDK version  `v46.0.0`
- Go version: `go version go1.14.2 darwin/amd64`

- What happened?
  - `MarketplaceAgreementsClient.List` and  `MarketplaceAgreementsClient.GetAgreement` API return errors 
  - Here is my code 
  ```
	market "github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering"

	client := market.NewMarketplaceAgreementsClient(subscriptionID)
	client.Authorizer = authorizer

	agreements, err := client.List(ctx)
	if err != nil {
		log.Errorf("error being encountered is ", err.Error())
	}
	
	agreementTerms, err := client.GetAgreement(ctx, publisher, offer, sku)
	if err != nil {
		log.Errorf("error being encountered is ", err.Error())
	}

- Error with List API:    
```
marketplaceordering.MarketplaceAgreementsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal object into Go value of type []marketplaceordering.AgreementTerms  
```  

- Error with GetAgreement API: 
```
marketplaceordering.MarketplaceAgreementsClient#GetAgreement: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: \"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.\" error: invalid character 'T' looking for beginning of value
```
<!--
Thanks!
-->

**Comment by ArcturusZhang** [comment]
Hi @gargi thanks for this issue!

The root cause of this issue is that the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering/stable/2015-06-01/Agreements.json#L314) is defined differently from the actual JSON returned from the service. The JSON returned from the service looks like this:
```
{
   "value": []
}
```
which aligns with the convention on Azure, but the swagger does not match this.
To solve this, I have tagged this issue so that the corresponding service team could take this a look

**Comment by vivgoyal** [comment]
@ArcturusZhang can we prioritize this work?

**Comment by ArcturusZhang** [comment]
Hi @akning-ms do we include this kind of bugs in the S360 KPI?

**Comment by akning-ms** [comment]
Yes. it should be in our live validation report. but seems it is not shown due to no traffic. @leni-msft to help take a look

**Comment by leni-msft** [comment]
@ArcturusZhang This issue has already been detected in live validation report and created as S360 action item: https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=580A0264-1553-4CA9-910D-C4891AFA65E2

**Comment by RickWinter** [comment]
@ArcturusZhang @leni-msft , Is this issue still active?
