### ISSUE TITLE
Bot Service SDK incorrectly uses "preview" swagger

### ISSUE THREAD

**Issue by cleemullins** [Azure/azure-sdk-for-go#14627]
The SDK appears to be pulling an older (pre-GA) swagger file from 2018. This file is out-of-date and needs to be replaced. 
"github.com/Azure/azure-sdk-for-go/services/preview/botservice/mgmt/2018-07-12/botservice"

The SDK is currently pulling the swagger file from here:
* https://github.com/Azure/azure-rest-api-specs/tree/master/specification/botservice/resource-manager/Microsoft.BotService/preview/2018-07-12

The much more recent swagger (from this month) can be found here:
* https://github.com/Azure/azure-rest-api-specs/tree/master/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01

This is causing errors, as described in #14592 

Once this update is made, someone from the Azure Bot Service team needs to request a release based on the newer Swagger File: 
* http://aka.ms/openapiportal

**Comment by jhendrixMSFT** [comment]
@hailiu2586 can you please go to http://aka.ms/openapiportal and request a release of the Go SDK using the latest swagger?
