### ISSUE TITLE
Azure reservations are missing fields in the reservations.Response

### ISSUE THREAD

**Issue by ianeal** [Azure/azure-sdk-for-go#14632]
Import path of package in question:
	"github.com/Azure/azure-sdk-for-go/services/preview/reservations/mgmt/2020-10-25/reservations"

SDK version: 54.0.0
	go.mod file shows this information: github.com/Azure/azure-sdk-for-go v54.0.0+incompatible

Output of go version
	go version go1.16 linux/amd64

What happened?

We are converting from an existing implementation which uses straight HTTP requests to use the go SDK and observed that certain fields are missing from the reservations.Response properties when listing the reservations (ie we are using the List function)

The data is in the HTTP response body so it should be straight forward to add the new fields to the struct.

The missing fields are

archived (a boolean)
capabilties (a string)
swapProperties (a struct, which usually seems to have swapSource and swapDestination, uncertain about any other possible values)

**Comment by ianeal** [comment]
Hi, I was wondering if there are any updates on this one?  
Is any additional information required?

**Comment by ArcturusZhang** [comment]
Hi @ianeal sorry for the inconvenience but we are now waiting for the corresponding service team to response on this issue and they should either update the swagger accordingly so that we could regenerate our SDK, or they could provide some justification for not doing so.

**Comment by rkapso** [comment]
Thanks for bringing this up we are actively working on pushing the new swagger out

**Comment by ianeal** [comment]
Updated to the latest Azure SDK (ie v66.0.0) and changed my go dependencies

from "github.com/Azure/azure-sdk-for-go/services/preview/reservations/mgmt/2020-10-25/reservations"
to "github.com/Azure/azure-sdk-for-go/services/reservations/mgmt/2022-03-01/reservations

I compared the models and I agree that for archived and capabilities the properties are there.

However, I still do not see Properties.SwapProperties.SwapSource nor Properties.SwapProperties.SwapDestination?

I'd like to update to using the 2022-03-01/reservations but without this data, I need to keep using my autorest implementation to retrieve the raw JSON response using 2019-04-01 API endpoint

Any idea why swap properties was not added as well?

Has it been renamed to something else or made unsupported or deprecated?

**Comment by ianeal** [comment]
Swap source and swap destination are shown in the following microsoft documentation so I'd expect it to be reflected in the SDK

https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/reservation/list?tabs=HTTP

**Comment by ianeal** [comment]
@ArcturusZhang @rkapso Swap source and swap destination are shown in the following microsoft documentation so I'd expect it to be reflected in the SDK

https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/reservation/list?tabs=HTTP

**Comment by ianeal** [comment]
Any update on why swap properties was not included in the fix for this ticket?

**Comment by ianeal** [comment]
@ArcturusZhang With regard to the missing swap properties which I noted above.  I can see now that the swagger API for this was updated to include swap properties on Oct 10, 2022.

Is it known when the SDK will be regenerated?  

Also will the newer github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations API be updated as well?

**Comment by ianeal** [comment]
@ArcturusZhang I've converted from using the services/preview/... apis to using the newer sdk/resourcemanager/.. apis.

It appears the swapSource and swapDestination properties are now available in sdk/resourcemanager/reservations/armreservations/models.go.

Please confirm if I can now start using the latest armreservations API.

**Comment by ArcturusZhang** [comment]
This should be the latest version of go SDK for reservations, but I am not quite sure if the previous missing properties in swaggers has been resolved or not
cc @tadelesh to answer that since I am no longer actively working on this now

**Comment by tadelesh** [comment]
@ianeal yes, you could use the latest armreservation module. It is using latest stable version (2022-11) of reservation service.
