### ISSUE TITLE
ManagedIdentityCredential doesn't translate scopes to resource

### ISSUE THREAD

**Issue by kostrse** [Azure/azure-sdk-for-go#14644]
We are working on [support of managed identities in Grafana](https://github.com/grafana/grafana/pull/33807) and trying this library for token requests (both managed identity and client secret scenarios).

Looks like it's problematic to abstract over particular authentication mechanism using [TokenCredential](https://github.com/Azure/azure-sdk-for-go/blob/24b0cd86da44fcb99397bb8d83ac872ecfec5a79/sdk/azcore/credential.go#L37-L41) interface because of the known "scopes vs resource" problem.

If calling code provides a scope name, ClientSecretCredential works, ManagedIdentityCredential fails, if calling code provides a resource name then it's opposite ManagedIdentityCredential works but ClientSecretCredential fails.

Unfortunately, `strings.Join` here (and in other places) in **managed_identity_client.go** cannot work in principle:
https://github.com/Azure/azure-sdk-for-go/blob/24b0cd86da44fcb99397bb8d83ac872ecfec5a79/sdk/azidentity/managed_identity_client.go#L173

I saw mentions previously that AuthenticationPolicy supposedly has some trimming logic.

Maybe it makes sense to add this logic directly into `managedIdentityClient` since there's actual implementation of the protocol which is specifically doesn't support scopes?

**Comment by kostrse** [comment]
Here is code from Azure SDK for .NET:
https://github.com/Azure/azure-sdk-for-net/blob/7227b59d252f93851103d7f6526edad41a90fefb/sdk/identity/Azure.Identity/src/ImdsManagedIdentitySource.cs#L86-L87

It does have trimming logic built-in to the request client.

**Comment by jhendrixMSFT** [comment]
I think this ties in with https://github.com/Azure/azure-sdk-for-go/issues/12184

**Comment by kostrse** [comment]
When `TokenCredential` used only via `AuthenticationPolicy` then yes, policy takes care of the conversion.

The problem is that `AuthenticationPolicy` is very opinionated for the Azure SDK usage:
- it closely tied to its own transport pipeline.
- the way it handles token caching is useful for Azure SDK scenario when it's only single credential and cached token paired with the pipeline, but it's problematic for multi-user/multi-tenant scenario when we need to handle token requests for different credentials/scopes at the same time (e.g. resolve them from a map).

For example, in our project we have our own design of transport pipeline which makes the `AuthenticationPolicy` not usable for us, but we would be happy to reuse the credential client itself because ManagedIdentityCredential for example, has a lot of heuristics on how the MSI token should be obtained and it would be very complicated to reimplement and maintain it separately.

Generally speaking, It would be great if `azidentity` layer of the Azure SDK would be more versatile and useful for other applications, besides the Azure SDK.

I hope it's not a big breaking change to move scope trimming logic from the policy to client directly, since it wont affect policy but would make the client more useful by itself.

**Comment by kostrse** [comment]
@jhendrixMSFT can I send PR?

**Comment by catalinaperalta** [comment]
@kostrse we moved the scopes to resource conversion to GetToken() on ManagedIdentityCredential in v0.9.0 of azidentity. Please note since we are still in preview there are several changes included in this release.
