### ISSUE TITLE
func ListKeys() fails intermittently to list the keys for storage account 

### ISSUE THREAD

**Issue by akhilesh2410** [Azure/azure-sdk-for-go#14655]
### Bug Report

- import path of package in question:
 Facing issue due to :
 "github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage"

SDK version :
	github.com/Azure/azure-sdk-for-go v37.1.0+incompatible

Other package version:
	github.com/Azure/azure-sdk-for-go/sdk/to v0.1.4
	github.com/Azure/azure-storage-blob-go v0.10.0
	github.com/Azure/go-autorest/autorest v0.9.3
	github.com/Azure/go-autorest/autorest/azure/auth v0.4.2
	github.com/Azure/go-autorest/autorest/date v0.3.0

- output of `go version`
go version go1.15.1 linux/amd64

- What happened?
 "storage.AccountsClient#ListKeys:" API is failing intermittently with Azure AD App's credentials. Sometimes it works perfectly fine on the other time if fails with below error :
  `"storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '<App ID>' with object id '<ObjectID>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/<subscriptionID>/resourceGroups/rg-east2/providers/Microsoft.Storage/storageAccounts/zrmp6axzc3wimxvzvr' or the scope is invalid. If access was recently granted, please refresh your credentials.\""}`

- What did you expect or want to happen?
 It should work consistently.
- How can we reproduce it?
 Create an Azure AD app and assign role with **storageaccount** scope as **contributor** .
 After assigning this role, I am trying to list the storage account keys using below code : 
 
````
func GetStorageAccountKeys(log logr.Logger, resourceGroup, storageAccount, subscriptionID, clientID, clientSecret, tenantID string) (storage.AccountListKeysResult, error) {
	listKeyResult := storage.AccountListKeysResult{}
	accountsClient := storage.NewAccountsClient(subscriptionID)
	credConfig := auth.NewClientCredentialsConfig(clientID, clientSecret, tenantID)
	authorizer, err := credConfig.Authorizer()
	if err != nil {
		return listKeyResult, err
	}
	accountsClient.Authorizer = authorizer
	accountsClient.AddToUserAgent("test-agent")
```

	backoffAlg := &backoff.Backoff{
		MaxInterval:     120 * time.Second,
		ResetAfterNoErr: 10 * time.Minute,
	}
	err = backoffAlg.RetryOnError(log, []string{}, 8, func() error {
		listKeyResult, err = accountsClient.ListKeys(context.Background(), resourceGroup, storageAccount, storage.ListKeyExpand(storage.Kerb))
		return err
	})
	if err != nil {
		return listKeyResult, err
	}
	return listKeyResult, nil
}
`
 
I am calling this function on two places with same parameters value. on first place it always works fine but on second call this fails intermittently.
.
- Anything we should know about your environment.
-This code is running a container (base image : registry.access.redhat.com/ubi8/ubi:8.3-289 AS runtime)


<!--
Thanks!
-->

**Comment by ArcturusZhang** [comment]
Hi @akhilesh2410 thanks for this issue!

The error comes from the service instead of the SDK itself, therefore I have to defer to the corresponding service team's feedback here.

**Comment by amishra-dev** [comment]
@akhilesh2410 Akhilesh, could you kindly raise a service request since this will need someone from the service to take a look.

**Comment by lirenhe** [comment]
@amishra-dev, as this is a service issue, you could open a support ticket for it. https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
Close this item as this is not related to the SDK.
