### ISSUE TITLE
Incorrect codegen for types with embedded constants

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1466]
In test [PutReferencedConstant](https://github.com/Azure/autorest.go/blob/master/test/src/tests/generated/body-string/enum.go#L300) the codegen expects the caller to pass a value for RefColorConstant.ColorConstant even though it's defined as a constant in the swagger.  For comparison, see the C# [codegen](https://github.com/Azure/autorest.csharp/blob/master/test/vanilla/Expected/BodyString/Models/RefColorConstant.cs#L38) which properly defines ColorConstant as read-only and doesn't require it as a param to PutReferencedConstant.

**Comment by ArcturusZhang** [comment]
This issue should be staled, closing
