### ISSUE TITLE
Upgrade Machinelearningservices to 2021-04-01

### ISSUE THREAD

**Issue by gro1m** [Azure/azure-sdk-for-go#14666]
### Feature Request

The REST API is on version **2021**-04-01 for `machinelearningservices`: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01.
The GO SDK is one year behind (**2020**-04-01): https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/machinelearningservices/mgmt@v54.2.0+incompatible.

I want to do the terraform azure provider implementation for the Machine Learning Computing "Suite":
1) Machine Learning Compute Instance - this Compute type is unfortunately unavailable in the version 2020-04-01. (https://github.com/terraform-providers/terraform-provider-azurerm/issues/11255 / https://github.com/terraform-providers/terraform-provider-azurerm/issues/6827)

2) Machine Learning Compute Cluster - I cannot do the update operation. PR is here:  https://github.com/terraform-providers/terraform-provider-azurerm/pull/11675.  Looked into it with @favoretti from Terraform Azure Providers Team and this seems to be due to outdated versions: 
portal sends payload to PATCH request in form of:
```json
{"properties":
    {"properties":
        {"scaleSettings":
            {"minNodeCount":2,
              "maxNodeCount":3,
              "nodeIdleTimeBeforeScaleDown":"PT900S"
             }
         }
     }
}
```
, whereas Go SDK sends:
```json
{"properties":
    {"scaleSettings":
        {"maxNodeCount":2,
         "minNodeCount":1,
         "nodeIdleTimeBeforeScaleDown":"PT60S"
        }
     }
}
```
, but portal seems to use a newer API version.

3) Machine Learning Inference Cluster: not sure if that has an issue with the 2020-04-01 version. PR is here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/11550.

The following part in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json#L713 describes best the Get operation I need (of course also all other necessary operations for implementing the CRUD):
```
        "operationId": "MachineLearningCompute_Get",
        "description": "Gets compute definition by its name. Any secrets (storage keys, service credentials, etc) are not returned - use 'keys' nested resource to get them.",
        "x-ms-examples": {
          "Get a AKS Compute": {
            "$ref": "./examples/getAKSCompute.json"
          },
          "Get a AML Compute": {
            "$ref": "./examples/getAmlCompute.json"
          },
          "Get an ComputeInstance": {
            "$ref": "./examples/getComputeInstance.json"
          }
        },
```

Would look forward to a rather quick implementation (rough expectation: 1 week), but I am a bit irritated that the versions have not been pulled after consequently. So if there is a way I can contribute so that this moves quicker, I will be happy to do so :)

**Comment by favoretti** [comment]
@ArcturusZhang would this be a trivial fix or?..

**Comment by ArcturusZhang** [comment]
Hi @gro1m @favoretti thanks for opening this issue.

The SDK team cannot release an api-version without the release requests from the corresponding service team - therefore I tagged this issue so that the corresponding service team could get a notice of this.

**Comment by ArcturusZhang** [comment]
Hey @gro1m and @favoretti I just found that this issue comes from the swagger and the new api-version cannot solve this issue. More details can be found in this issue https://github.com/Azure/azure-sdk-for-go/issues/14669
