### ISSUE TITLE
netapp SecurityStyle constants differ in case from what the API returns

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#14684]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`"github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2020-09-01/netapp"`

- SDK version e.g. `master`, `latest`, `18.1.0`
`github.com/Azure/azure-sdk-for-go v54.2.0+incompatible`
- output of `go version`
16

- What happened?
the netapp.SecurityStyle constant casing in the SDK is different (`unix`) then what the API returns (`Unix`) - these should match

- What did you expect or want to happen?
the casing to match

- How can we reproduce it?
query the API

- Anything we should know about your environment.
no

**Comment by ArcturusZhang** [comment]
Hi @katbyte thanks for this issue!

This is an issue on the service side therefore I have tagged this issue so that the corresponding service team could have a look

**Comment by RickWinter** [comment]
@ArcturusZhang Can this issue be closed now that that new resource manager modules are released?
