### ISSUE TITLE
Missing CreateOrUpdateSwiftVirtualNetworkConnectionWithCheck in Microsoft.Web/stable/2020-12-01

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-go#14690]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`

azure-sdk-for-go/services/web/mgmt/2020-12-01

- SDK version e.g. `master`, `latest`, `18.1.0`

master - 4291d7a5ce235e5390ea9d08af11bd5792533a4e

  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

```
$ go version
go version go1.16 darwin/amd64
```

- What happened?
I'm trying to upgrade terraform (https://github.com/terraform-providers/terraform-provider-azurerm/pull/11809) to the latest web/mgmt API and I got compile errors on app service vnet integration related code: https://docs.microsoft.com/en-gb/azure/app-service/web-sites-integrate-with-vnet

I've searched and searched and it appears to be that only GET and DELETE are in the latest SDK

The API appears to be at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L5965

Best to open in a local editor as the file is huge

It was renamed from `WebApps_CreateOrUpdateSwiftVirtualNetworkConnectionSlot` to `WebApps_CreateOrUpdateSwiftVirtualNetworkConnectionWithCheck`

I assume there's something in the rest API spec that stopped it being published, but you would know better than me 

- What did you expect or want to happen?
I could create app service vnet integration
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Hi @timja thanks for this issue!

It has been a while until we regenerate the SDK for `web` because we have not received any release request from the service team.
I have tagged this issue so that the corresponding service team could see

**Comment by timja** [comment]
Sure but why is it missing in 2020-12-01 ? Which is released here?

**Comment by ArcturusZhang** [comment]
I am not sure, but if you check this `_meta.json` file [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2020-12-01/web/_meta.json) which stores the commit hash from which this package was generated - at that commit [the swagger](https://github.com/Azure/azure-rest-api-specs/blob/e0f8b9ab0f5fe5e71b7429ebfea8a33c19ec9d8d/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L5918) only has get and delete operation for this path.

I am not sure why the operation is missing in the first place, but now it is the case that the service team added it back and forgot to tell us to release a new SDK version for it.

**Comment by panchagnula** [comment]
@timja & @ArcturusZhang the AppService team fixed the missing API & other updates as reported during .NET SDK generation here https://github.com/Azure/azure-rest-api-specs/pull/14018 sorry if we missed notifying you of this. Does this help? Thanks!

**Comment by timja** [comment]
I believe a release request is required? https://github.com/Azure/sdk-release-request/

**Comment by ArcturusZhang** [comment]
> @timja & @ArcturusZhang the AppService team fixed the missing API & other updates as reported during .NET SDK generation here [Azure/azure-rest-api-specs#14018](https://github.com/Azure/azure-rest-api-specs/pull/14018) sorry if we missed notifying you of this. Does this help? Thanks!

Could you please submit an SDK release request via https://aka.ms/openapihub

**Comment by timja** [comment]
@panchagnula just checking if you've created the release request above ^^?

**Comment by panchagnula** [comment]
@timja no I haven't, I didn't do the original request either. I can speak to my team if they still need this SDK or have another request already in progress. Thanks!

**Comment by timja** [comment]
@panchagnula Just checking to see where this is at?

Thanks

**Comment by madsd** [comment]
@timja SDK is planned to be generated on Thursday.

**Comment by ArcturusZhang** [comment]
The fix for this has been released in v55.2.0
