### ISSUE TITLE
ActivityLogs client needs API version update

### ISSUE THREAD

**Issue by drewandersonnz** [Azure/azure-sdk-for-go#14704]
### Bug Report

Please update ActivityLogs client API version to `2017-03-01-preview` matching that used by https://portal.azure.com/ 

As per an error from the API: `The supported api-versions are '2014-04-01,2014-11-01,2015-04-01,2016-09-01-preview,2017-03-01-preview'.` 

This could be by adding a new implementation version of the ActivityLogs section which targets the newer API version, leaving all other implementations the same. Example: 

```
# example new implementation version
./preview/monitor/mgmt/2021-06-01-preview/insights/activitylogs.go:96:	const APIVersion = "2017-03-01-preview"
```

All current implementation versions of the ActivityLog client use an older 2015-04-01 API version, even though other API versions are available

```
$ grep -inr apiversion `find ./ | grep insights/activitylogs.go` | sort
./preview/monitor/mgmt/2017-05-01-preview/insights/activitylogs.go:96:	const APIVersion = "2015-04-01"
./preview/monitor/mgmt/2018-03-01/insights/activitylogs.go:96:	const APIVersion = "2015-04-01"
./preview/monitor/mgmt/2018-09-01/insights/activitylogs.go:96:	const APIVersion = "2015-04-01"
./preview/monitor/mgmt/2018-11-01-preview/insights/activitylogs.go:96:	const APIVersion = "2015-04-01"
./preview/monitor/mgmt/2019-03-01/insights/activitylogs.go:96:	const APIVersion = "2015-04-01"
./preview/monitor/mgmt/2019-06-01/insights/activitylogs.go:96:	const APIVersion = "2015-04-01"
./preview/monitor/mgmt/2019-11-01-preview/insights/activitylogs.go:103:	const APIVersion = "2015-04-01"
```

As the `activitylogs.go` is in `./preview` of the SDK, and there are `-preview` implementations in the SDK, there should be no problem providing a version which uses a `-preview` version of the API.

As per a recent ICM (242085637) there is a known issue where the 2015-04-01 API version is missing objects in the response which are present in the API version 2017-03-01-preview used by https://portal.azure.com. This is not a data format issue, instead the API is missing whole root level objects.

Full reproduction steps can be found in the above ICM.

The `az` cli tool also uses the 2015-04-01 API version and also exhibits this missing object problem.

It is possible to retrieve the ActivityLogs objects via a similar command line request as this:

```
# objects missing: 2015-04-01
az rest --method get --url ${AzureActivityLogsBaseUrl}?api-version=2015-04-01\&%24filter=xyzfilter

# objects found: 2017-03-01-preview
az rest --method get --url ${AzureActivityLogsBaseUrl}?api-version=2017-03-01-preview\&%24filter=xyzfilter

# fake API version to test failure, API version chosen from implementation version (./preview/monitor/mgmt/2019-11-01-preview/insights/activitylogs.go): 2019-11-01-preview 
az rest --method get --url ${AzureActivityLogsBaseUrl}?api-version=2019-11-01-preview\&%24filter=xyzfilter
# Not Found({"error":{"code":"InvalidResourceType","message":"The resource type 'eventtypes' could not be found in the namespace 'microsoft.insights' for api version '2019-11-01-preview'. The supported api-versions are '2014-04-01,2014-11-01,2015-04-01,2016-09-01-preview,2017-03-01-preview'."}})

# note the different API versions used
```

Required information requested by the github Bug Template: 

* Import path: "github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-11-01-preview/insights"
* SDK Version: v54.2.1 and master: https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/monitor/mgmt
* go version go1.16.3 linux/amd64

**Comment by ArcturusZhang** [comment]
Hi @drewandersonnz thanks for this issue!

This is how our SDK generator and swaggers work:
The SDK is generated from a thing what we called it a `readme tag`, you can find it [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/readme.md#tag-package-2019-11). A readme tag combines some swagger files together and the code generator generates the SDK code using those swaggers. This is why you see one SDK package can contain different "actual" api-versions. The date-like string in the package path of a Go SDK package is not the api-version in this case.

There is a new release of monitor in progress now, you can check it out here: https://github.com/Azure/azure-rest-api-specs/pull/14542#pullrequestreview-670907055
Please feel free to leave comments there about the desired api-version

**Comment by asheniam** [comment]
There are known set of issues with the backend system for the api-version = 2017-03-01-preview in Activity Logs REST API.  The team is working to resolve the backend issues first before publishing this api-version more broadly.  At this time, this engineering work is very significant and multiple months.  Currently, we are targeting releasing the new backend system in the Fall timeframe.

**Comment by dany74q** [comment]
@asheniam - Small bump - we could really use the more advanced filtering offered in 2017-03-01-preview (a-la filtering by operation type); 
I haven't seen a new api version published, do you happen to know if the problems you'd mentioned were fixed in the same API version, and / or if there's an updated ETA for the new version ?

Thanks a ton !
