### ISSUE TITLE
Long running operation in creating a VM does not return a final state URL

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-go#14730]
### Bug Report

- import path of package in question
  `github.com/Azure/azure-sdk-for-go/sdk/compute/armcompute`
- SDK version 
  `v0.1.0`
- output of `go version`
  `go version go1.16 windows/amd64`

- What happened?
  The response returned by `PollUntilDone` function is basically empty without any information of this resource.
- What did you expect or want to happen?
  We should get the full parameters in the response of `PollUntilDone` function
- How can we reproduce it?
  Sample code here: https://github.com/ArcturusZhang/azure-sdk-for-go-track2-sample/blob/dbd77ed6bf9cbf516dc31f7cb754f0a4626a3537/main.go#L338
- Anything we should know about your environment.

Related issue: https://github.com/Azure/azure-sdk-for-go/issues/14665

**Comment by jhendrixMSFT** [comment]
Fixed in `armcompute@v0.2.0`
