### ISSUE TITLE
Missing support for domainservices 2021-03-01 and 2021-05-01

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#14747]
### Service Package Request

The latest version of domainservices supported by the SDK is 2020-01-01. There are two newer versions available: 2021-03-01 and 2021-05-01

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/domainservices/resource-manager/Microsoft.AAD/stable/2021-03-01
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/domainservices/resource-manager/Microsoft.AAD/stable/2021-05-01

**Comment by manicminer** [comment]
Related: https://github.com/terraform-providers/terraform-provider-azurerm/pull/10782

**Comment by ArcturusZhang** [comment]
Hi @manicminer thanks for this issue!

We will work with the corresponding service team to release these new packages as soon as possible.
