### ISSUE TITLE
how to use azure repo api by this sdk

### ISSUE THREAD

**Issue by carrymec** [Azure/azure-sdk-for-go#14759]
i want to use azure api like this (https://docs.microsoft.com/en-us/rest/api/azure/devops/git/repositories/get%20repository?view=azure-devops-rest-6.0#security),how to use it by this sdk

**Comment by ArcturusZhang** [comment]
Hi @carrymec thanks for this issue!

The link of the REST APIs comes from the Azure DevOps. This repo is for Azure Management, therefore there is no way that you can use something in this repo to call the APIs in the link.

@xuzhang3 do you know if there is an official Azure DevOps SDK for Go?

**Comment by xuzhang3** [comment]
Hi @carrymec You can use Azure DevOps Go SDK: https://github.com/microsoft/azure-devops-go-api

**Comment by carrymec** [comment]
thank,this repo will support repo api later？

**Comment by carrymec** [comment]
> Hi @carrymec You can use Azure DevOps Go SDK: https://github.com/microsoft/azure-devops-go-api

i used it，but this  repo cannot support some api

**Comment by xuzhang3** [comment]
Current azure-devops-go-api SDK is based on v5.1,  some of the APIs are not available.

**Comment by ArcturusZhang** [comment]
Hi @carrymec since this repo is not designed to carry the APIs for DevOps, could you please open an issue there?

In the meantime, I am going to close this issue here.
