### ISSUE TITLE
Cannot unmarshal string into Go struct field for NetworkVirtualApplianceSKU and NetworkVirtualApplianceSKUListResult

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#14769]
SDK version: github.com/Azure/azure-sdk-for-go/sdk/network/armnetwork v0.1.0

- What happened?
It failed to call [VirtualApplianceSKUs.Get API](https://github.com/Azure/azure-sdk-for-go/blob/d279d9be648b29d3d6e23896b5410342b4ee3459/sdk/network/armnetwork/zz_generated_virtualapplianceskus_client.go#L35) and [VirtualApplianceSKUs.List](https://github.com/Azure/azure-sdk-for-go/blob/d279d9be648b29d3d6e23896b5410342b4ee3459/sdk/network/armnetwork/zz_generated_virtualapplianceskus_client.go#L97). 

Below is the error message:
```
failed to get virtual appliance sku: unmarshalling type **armnetwork.NetworkVirtualApplianceSKU: json: cannot unmarshal string into Go struct field NetworkVirtualApplianceSKUInstances.properties.availableScaleUnits.instanceCount of type int32

failed to list virtual appliance sku: unmarshalling type **armnetwork.NetworkVirtualApplianceSKUListResult: json: cannot unmarshal string into Go struct field NetworkVirtualApplianceSKUInstances.value.properties.availableScaleUnits.instanceCount of type int32
```

- What did you expect or want to happen?
These two API calls should pass.

- How can we reproduce it?
Invoke these APIs with go track2.

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei thanks for this issue!

This looks like a service-swagger inconsistency. Could you please provide the response body to help us debug this issue?

**Comment by sinbai** [comment]
Additional information from Elena：
After debugging, I found the InstanceCount type is *int in [https://github.com/Azure/azure-sdk-for-go/blob/10a9ef8c19ec235f65d45bc30ed96fbb041a4c5f/sdk/network/armnetwork/zz_generated_models.go#L11083](url), but the type of response data is *string from API. Seems it is a bug. Would you help to fix it?

reponse body from API:
{
  "properties": {
    "vendor": "ciscosdwan",
    "availableVersions": [
      "17.4.0928",
      "17.4.20201218"
    ],
    "availableScaleUnits": [
      {
        "scaleUnit": "10",
        "instanceCount": "2"
      },
      {
        "scaleUnit": "2",
        "instanceCount": "2"
      },
      {
        "scaleUnit": "4",
        "instanceCount": "2"
      }
    ],
    "marketPlaceLink": "https://aka.ms/ciscoMarketPlaceOffer",
    "provisioningState": "Succeeded"
  },
  "name": "ciscosdwan",
  "etag": "00000000-0000-0000-0000-000000000000"
}
