### ISSUE TITLE
Accepting terms for VM image

### ISSUE THREAD

**Issue by wilsonehusin** [Azure/azure-sdk-for-go#14768]
### Service Package Request

I would like to have a way to replicate the behavior of accepting terms for VM image from marketplace. This behavior exists in the CLI through:

```sh
az vm image terms accept [--urn <urn>|--publisher <publisher> --offer <offer> --plan <plan>]
```

I am aware of [`MarketplaceOrderingClient`](https://github.com/Azure/azure-sdk-for-go/tree/master/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering) where there is a method called `Sign`, but that seems to be a different behavior than the CLI args above.

From what I have observed, the CLI works fine and hitting the following endpoint:

```
https://management.azure.com
  /subscriptions/{id}
  /providers/Microsoft.MarketplaceOrdering
  /offerTypes/virtualmachine
  /publishers/{id}
  /offers/{id}
  /plans/{id}
  /agreements/current?api-version=2021-01-01
```

However, the `MarketplaceOrderingClient.Sign` is reaching the following endpoint:

```
https://management.azure.com
  /subscriptions/{id}
  /providers/Microsoft.MarketplaceOrdering
  /agreements/{id}
  /offers/{id}
  /plans/{id}
  /sign
```

which also returns error 400, with the message:

```
You must accept the legal terms through the Azure portal (http://go.microsoft.com/fwlink/?LinkId=534873).
```

Which client should I be using to replicate the behavior from CLI?

**Comment by ArcturusZhang** [comment]
Hi @wilsonehusin thanks for this issue!

The API in Azure CLI corresponds to this swagger: https://github.com/Azure/azure-rest-api-specs/blob/9b0e13aa57f7fe7fcfa7624b792ed699a40ad88d/specification/marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering/stable/2021-01-01/Agreements.json#L37
We will work with the corresponding service team and release a new package for this as soon as possible

**Comment by wilsonehusin** [comment]
Thanks for the clarification @ArcturusZhang! I thought I was missing something obvious -- looking forward to the resolution!

**Comment by drewmullen** [comment]
just to add to this, the cli command reports that it is working but it doesnt actually work:

return says accepted but is still marked "disabled" in the GUI:
```
 az vm image terms accept --offer tom-cat --publisher bitnami --plan hourly
{
  "accepted": true,
...
```
![image](https://user-images.githubusercontent.com/3812162/123425250-e2f9e680-d58f-11eb-909a-47f14ae0665f.png)

**Comment by ArcturusZhang** [comment]
Hi @drewmullen I am not quite sure about how azure cli works on this command, could you also open an issue for [Azure CLI](https://github.com/Azure/azure-cli/issues)?

**Comment by lirenhe** [comment]
Close it as this is not a GO SDK issue. Please create a new issue in https://github.com/Azure/azure-cli/issues

**Comment by wilsonehusin** [comment]
@lirenhe the original issue is a Go SDK issue, but the comment from someone else was on a CLI problem which was redirected by @ArcturusZhang. I believe this should still be an open issue, no?

**Comment by lirenhe** [comment]
@wilsonehusin, you are correct. I reopen this one and we will ask service team for a new release of MarketplaceOrdering.

**Comment by 804873052** [comment]
Hi @wilsonehusin  thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by specterz** [comment]
Any update on this team?

**Comment by Alancere** [comment]
Regarding track2 has been released on https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/marketplaceordering/armmarketplaceordering@v0.2.0, track1 has not been updated for the time being.

**Comment by Alancere** [comment]
latest track2 is version https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/marketplaceordering/armmarketplaceordering@v1.0.0
