### ISSUE TITLE
Add support for new Policy API so that custom error messages can be used

### ISSUE THREAD

**Issue by chris-p-martin** [Azure/azure-sdk-for-go#14760]
### Feature Request

Hello,

Is it possible to implement the latest version of the Azure Policy Assignment API (2020-09-01) so the custom non Compliance messages can be used on Policy Assignments.

Thanks,
Chris

**Comment by ArcturusZhang** [comment]
Hi @chris-p-martin thanks for this issue!

Actually the requested package has been released as a preview package because it contains some preview features: https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/resources/mgmt/2020-09-01-preview/policy
