### ISSUE TITLE
Request to add services/preview/securityinsight/mgmt/2021-03-01-preview/securityinsight 

### ISSUE THREAD

**Issue by kaovd** [Azure/azure-sdk-for-go#14800]
### Service Package Request

Please add the new Preview SecurityInsights API Specificaiton as a service package, 2021-03-01-preview into services/preview/securityinsight/mgmt/2021-03-01-preview/securityinsight 

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview

**Comment by ArcturusZhang** [comment]
Hi @kaovd thanks for this issue!

We will work with the corresponding service team and release the new package soon.

**Comment by ArcturusZhang** [comment]
Hi @amirkeren could you please confirm the status of securityinsight swagger and submit a release request via https://aka.ms/openapihub?

**Comment by dosegal** [comment]
@ArcturusZhang Currently we don’t have a package that combines all the RP capabilities including the new preview APIs. This is because we are in the process of splitting the old swagger file (SecurityInsights.json which we used in 2020-01-01 and 2019-01-01-preview) into smaller swagger files, usually one per resource type. 
Once all the APIs are extracted to separate swagger files, we can create a package that combines them all.

**Comment by kaovd** [comment]
> @ArcturusZhang Currently we don’t have a package that combines all the RP capabilities including the new preview APIs. This is because we are in the process of splitting the old swagger file (SecurityInsights.json which we used in 2020-01-01 and 2019-01-01-preview) into smaller swagger files, usually one per resource type. 
> Once all the APIs are extracted to separate swagger files, we can create a package that combines them all.

Right now its just alertrules package I need downstream so not sure if thats possible to get without a single combined spec?

**Comment by dosegal** [comment]
> > @ArcturusZhang Currently we don’t have a package that combines all the RP capabilities including the new preview APIs. This is because we are in the process of splitting the old swagger file (SecurityInsights.json which we used in 2020-01-01 and 2019-01-01-preview) into smaller swagger files, usually one per resource type.
> > Once all the APIs are extracted to separate swagger files, we can create a package that combines them all.
> 
> Right now its just alertrules package I need downstream so not sure if thats possible to get without a single combined spec?

@ArcturusZhang Is it ok to create a package that doesn't contain all the RP capabilities but only its subset? For example - "package-2021-03-preview-only" (which lacks the preview APIs of 2019-01-01).

**Comment by ArcturusZhang** [comment]
> > > @ArcturusZhang Currently we don’t have a package that combines all the RP capabilities including the new preview APIs. This is because we are in the process of splitting the old swagger file (SecurityInsights.json which we used in 2020-01-01 and 2019-01-01-preview) into smaller swagger files, usually one per resource type.
> > > Once all the APIs are extracted to separate swagger files, we can create a package that combines them all.
> > 
> > 
> > Right now its just alertrules package I need downstream so not sure if thats possible to get without a single combined spec?
> 
> @ArcturusZhang Is it ok to create a package that doesn't contain all the RP capabilities but only its subset? For example - "package-2021-03-preview-only" (which lacks the preview APIs of 2019-01-01).

That is acceptable here, but as far as I know terraform might not accept that, but we could have a try

**Comment by kaovd** [comment]
>That is acceptable here, but as far as I know terraform might not accept that, but we could have a try

Ideally please try, as this is needed to close https://github.com/terraform-providers/terraform-provider-azurerm/issues/11667

cc @magodo do you know if this would be acceptable downstream

**Comment by magodo** [comment]
@kaovd Normally we'd prefer using a single version for a certain RP in terraform. @dosegal May I ask if there is an ETA when the split up is expected to be done?

**Comment by dosegal** [comment]
@magodo The current ETA is August 20th

**Comment by kaovd** [comment]
@dosegal Any update on where the ETAs at?

**Comment by dosegal** [comment]
@kaovd A new preview version (2021-09-01-preview) is currently in development and is expected to be released by October. This version will contain all the RP capabilities from which we can create a proper SDK.

**Comment by lukiffer** [comment]
@dosegal @lirenhe @804873052 could we get a status on the 2021-09-01 preview spec and corresponding SDK updates? We're looking to make use of the the Terraform resource @kaovd mentioned and are trying to get an idea of timing to plan our own implementation work.

**Comment by kaovd** [comment]
@lukiffer as a hack you can currently use a combination of TF and Script Provisoners to make the neccesary PATCH calls to some of the stray APIs to achieve entities, custom details etc and the like but obviously its better if a RP.

As now october has rolled around a status update would be much appreciated

**Comment by kaovd** [comment]
Hi @dosegal 

I see NRT rules are also on the 2021-09-01-preview API, can i check these are also going to be in the spec as they have recently gone public preview?

**Comment by lukiffer** [comment]
@dosegal any update on the ETA for this? Thanks!

**Comment by lirenhe** [comment]
i found the Swagger for 2021-09-01-preview was already merged. @Alancere, could you help to follow up on the SDK release?
@dosegal, we will need your team to create the release request.

**Comment by Alancere** [comment]
Hi @dosegal could you please confirm the status of securityinsight swagger and submit a release request via https://aka.ms/openapihub?

**Comment by magodo** [comment]
@dosegal Unrelated, I'm wondering whether there is any progress of the all in one Swagger spec for the sentinel? Last time I heard that the preview one will be released around Dec.2021 or Jan.2022, and the stable one will be released after that?

**Comment by dosegal** [comment]
@lirenhe @Alancere - Thanks, we submitted a release request.
@magodo, the 2021-09-01-preview version already contains all the Sentinel RP capabilities, if that's what you mean by "all in one spec". A similar stable version is expected to be released during January.

**Comment by kaovd** [comment]
@dosegal  @magodo 
If I am correct this is released ? https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/securityinsight/mgmt/2021-09-01-preview/securityinsight

**Comment by magodo** [comment]
@kaovd Yes, I've submit a PR to upgrade the API version of sentinel for Terraform: https://github.com/hashicorp/terraform-provider-azurerm/pull/14983
