### ISSUE TITLE
Install Go SDK fails

### ISSUE THREAD

**Issue by seyadava** [Azure/azure-sdk-for-go#1487]
Running bellow command to install Go SDK fails with the following error.
> go get -u github.com/Azure/azure-sdk-for-go/...

ERROR:

# github.com/Azure/azure-sdk-for-go/profiles/preview/preview/iotspaces/mgmt/iotspaces
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\profiles\preview\preview\iotspaces\mgmt\iotspaces\models.go:34:21: cannot use subscriptionID (type "github.com/satori/uuid".UUID) as type "github.com/satori/go.uuid".UUID in argument to iotspaces.New
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\profiles\preview\preview\iotspaces\mgmt\iotspaces\models.go:37:32: cannot use subscriptionID (type "github.com/satori/uuid".UUID) as type "github.com/satori/go.uuid".UUID in argument to iotspaces.NewWithBaseURI
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\profiles\preview\preview\iotspaces\mgmt\iotspaces\models.go:43:27: cannot use subscriptionID (type "github.com/satori/uuid".UUID) as type "github.com/satori/go.uuid".UUID in argument to iotspaces.NewClient
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\profiles\preview\preview\iotspaces\mgmt\iotspaces\models.go:46:38: cannot use subscriptionID (type "github.com/satori/uuid".UUID) as type "github.com/satori/go.uuid".UUID in argument to iotspaces.NewClientWithBaseURI
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\profiles\preview\preview\iotspaces\mgmt\iotspaces\models.go:110:37: cannot use subscriptionID (type "github.com/satori/uuid".UUID) as type "github.com/satori/go.uuid".UUID in argument to iotspaces.NewOperationsClient
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\profiles\preview\preview\iotspaces\mgmt\iotspaces\models.go:113:48: cannot use subscriptionID (type "github.com/satori/uuid".UUID) as type "github.com/satori/go.uuid".UUID in argument to iotspaces.NewOperationsClientWithBaseURI
# github.com/Azure/azure-sdk-for-go/services/automation/mgmt/2015-10-31/automation
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2015-10-31\automation\dscconfiguration.go:456:23: client.ResourceGroupName undefined (type DscConfigurationClient has no field or method ResourceGroupName)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2015-10-31\automation\dscconfiguration.go:487:58: client.ResourceGroupName undefined (type DscConfigurationClient has no field or method ResourceGroupName)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2015-10-31\automation\keys.go:40:34: too many arguments in call to NewWithBaseURI
        have (string, string, string)
        want (string, string)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2015-10-31\automation\keys.go:48:23: client.ResourceGroupName undefined (type KeysClient has no field or method ResourceGroupName)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2015-10-31\automation\keys.go:78:58: client.ResourceGroupName undefined (type KeysClient has no field or method ResourceGroupName)
# github.com/Azure/azure-sdk-for-go/services/automation/mgmt/2017-05-15-preview/automation
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2017-05-15-preview\automation\dscconfiguration.go:456:23: client.ResourceGroupName undefined (type DscConfigurationClient has no field or method ResourceGroupName)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2017-05-15-preview\automation\dscconfiguration.go:487:58: client.ResourceGroupName undefined (type DscConfigurationClient has no field or method ResourceGroupName)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2017-05-15-preview\automation\keys.go:40:34: too many arguments in call to NewWithBaseURI
        have (string, string, string, string, string)
        want (string, string)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2017-05-15-preview\automation\keys.go:48:23: client.ResourceGroupName undefined (type KeysClient has no field or method ResourceGroupName)
DRIVE:\Users\USER\go\src\github.com\Azure\azure-sdk-for-go\services\automation\mgmt\2017-05-15-preview\automation\keys.go:78:58: client.ResourceGroupName undefined (type KeysClient has no field or method ResourceGroupName)

**Comment by marstr** [comment]
This should be fixed in v15.0.1

**Comment by marstr** [comment]
Feel free to scream at us if you're still running into this issue!
