### ISSUE TITLE
Release the monitor package of version 2018-04-16 to support `autoMitigate` on `LogSearchRule`

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#14892]
### Service Package Request

Per https://azure.microsoft.com/en-au/updates/public-preview-stateful-and-1minute-frequency-log-alerts-in-azure-monitor/, there is a new property called `autoMitigate` added for `LogSearchRule`.

From the swagger spec [history](https://github.com/Azure/azure-rest-api-specs/commits/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-04-16/scheduledQueryRule_API.json), it was introduced in Apr.19 (btw, why is it allowed to introduce new properties in a stable version). The affected Go SDK package is `github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights`.

This new property is needed for terraform-providers/terraform-provider-azurerm#12341

**Comment by tombuildsstuff** [comment]
> btw, why is it allowed to introduce new properties in a stable version

Adding new, optional fields to the response in a stable version isn't a breaking change (since the existing payload keeps working), so that's fine - if they were Required that would be, however?

**Comment by 804873052** [comment]
Hi @magodo thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by 804873052** [comment]
latest version https://github.com/Azure/azure-sdk-for-go/tree/ec2ed6d8450ad53978efa96822bf9c9431a63ab4/services/preview/monitor/mgmt/2021-07-01-preview
