### ISSUE TITLE
AMQP Support

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-go#14907]

**Comment by richardpark-msft** [comment]
Note, want to discuss adding in a 'add a fixed number of credits' to a link. It appears that go-amqp today only allows you to set a rolling window of credits, which makes some track 2 scenarios (like receiveMessages(5)) difficult to do properly.

**Comment by richardpark-msft** [comment]
> Note, want to discuss adding in a 'add a fixed number of credits' to a link. It appears that go-amqp today only allows you to set a rolling window of credits, which makes some track 2 scenarios (like receiveMessages(5)) difficult to do properly.
> 
> Created two issues to track parts of this:
> 
> * [Manual credit management: #15171](https://github.com/azure/azure-sdk-for-go/issues/15171)
> * [`drain` flag: #15172](https://github.com/azure/azure-sdk-for-go/issues/15172)

The 'manual credits' portion has been implemented now.

**Comment by richardpark-msft** [comment]
Drain also implemented.

**Comment by RickWinter** [comment]
@richardpark-msft @jhendrixMSFT Should this bug remain open?  I'd prefer to track the issues in the go-amqp repo and track schedule with those issues in the project.

**Comment by richardpark-msft** [comment]
We can close this, I think we've got our process down at this point, which is:

- If issues are go-amqp specific, file there (which @jhendrixMSFT has been doing)
- If issues cross repos file one in go-amqp for the feature, and one in azure-sdk-for-go for the actual implementation into azeventhubs or azservicebus.
