### ISSUE TITLE
ContainerServicesClient is missing as of containerservice/mgmt/2020-11-01/containerservice

### ISSUE THREAD

**Issue by Robert-Stam** [Azure/azure-sdk-for-go#14915]
### Service Package Request

As of github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-11-01/containerservice the ContainerServicesClient isn't available anymore.

In github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-09-01/containerservice and earlier this was available.

This client included ListOrchestrators, returning the list of supported K8s versions in AKS.

What functionality should I use to get the current versions of AKS supported in newer profiles (like github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-05-01/containerservice)?

**Comment by ArcturusZhang** [comment]
Hi @Robert-Stam thanks for this issue!

As far as I know, the AKS team is working on a new api-version, and we will release a new SDK package correpsonding to that new api-version. Please stay tuned.
Also I will contact the corresponding service team to see if they could update the swagger and refresh the SDK for the exisitng api-versions accordingly

**Comment by Robert-Stam** [comment]
> Hi @Robert-Stam thanks for this issue!
> 
> As far as I know, the AKS team is working on a new api-version, and we will release a new SDK package correpsonding to that new api-version. Please stay tuned.
> Also I will contact the corresponding service team to see if they could update the swagger and refresh the SDK for the exisitng api-versions accordingly

Hi @ArcturusZhang, thanks for the reaction.

Do you have any ETA for those 2 action points?

Regards,
Robert

**Comment by ArcturusZhang** [comment]
Hi @Robert-Stam I have sent some internal emails to draw their attention

**Comment by Robert-Stam** [comment]
H i @ArcturusZhang, 

Do you have any news?

Regards,
Robert

**Comment by lirenhe** [comment]
@Robert-Stam, the latest version of containerservice is 2021-10-01 but please note The ContainerServices RPv2 consists of two similar services: ContainerServices and ManagedClusters. Each service has its own swagger spec.
So if you want to use ContainerServices,  2020-09-01 is the targeting one to use.
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerservice/resource-manager#tag-package-2020-09

**Comment by mjudeikis** [comment]
This is still an issue if you want to keep your code consistent vendoring 
You can Cluster using `ManagedClusters` client but if you want to list available versions of AKS RP you need `ContainerServicesClient` and so vendoring different version of clients

Its just bit messy. Would be really nice if AKS RP team could iterate on clients in the same group on the same pace and not like

```
ClientAv1-> ClientAv2 ->clientAv3
clientBv2 -> --------------->clientBv3
```
As this point you release new API version and some clients are missing... In any other project it would be called regression, but this somehow becoming practice in Azure SDK where some clients "skips the release"

**Comment by Robert-Stam** [comment]
Imo the issue isn’t solved, please let me know which API I need to call to the supported K8s version as the latest ContainerServiceClient doesn’t support it anymore, and the ManagedClusterClient never supported this. I see this as regression.

**Comment by csandanov** [comment]
I have the same issue, used `ListOrchestrators` in v46.0, updated to v62.2.0 and now it's gone

**Comment by mjudeikis** [comment]
I like how for last ~4 month we speak with BOT with zero progress :D

**Comment by Robert-Stam** [comment]
> [ArcturusZhang](https://github.com/ArcturusZhang) commented [on Jun 30, 2021](https://github.com/Azure/azure-sdk-for-go/issues/14915#issuecomment-871174481)
> As far as I know, the AKS team is working on a new api-version, and we will release a new SDK package correpsonding to that new api-version. Please stay tuned. 

IMO this hasn't any prio or attention at all... really disappointing.

**Comment by mayankshah1607** [comment]
Hello,

Just wanted to follow-up on this issue. This functionality is missing in the [new SDK](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice) as well.
Are there any alternate APIs I can use?

Thanks

**Comment by FumingZhang** [comment]
Hey everyone, there's a new API ListKubernetesVersions available in managed cluster since 2023-03-01 (stable)/2023-03-02-preview (preview) to replace the old API ListOrchestrators in container service.

In latest azure go sdk, the corresponding method is [ListKubernetesVersions](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4#ManagedClustersClient.ListKubernetesVersions). The sample response of this new API is listed in [rest api doc](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?tabs=HTTP#list-kubernetes-versions).

@Robert-Stam, @ArcturusZhang, @lirenhe, @mjudeikis, @csandanov, @mayankshah1607

**Comment by Robert-Stam** [comment]
It's addressed, see: https://github.com/Azure/azure-sdk-for-go/issues/14915#issuecomment-1648846621
Closing this issue.
