### ISSUE TITLE
Add support for challenge based multi-tenant authentication scenario

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-go#14932]
Similar to: https://github.com/Azure/azure-sdk-for-net/pull/21378

**Comment by chlowell** [comment]
Waiting on https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/296. Public API for this was prematurely implemented in `azcore` and removed by #17640.

**Comment by chlowell** [comment]
Closing this because it's part of #17159 we don't need to track separately.
