### ISSUE TITLE
Add support for CAE 

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-go#14931]
Use Azure Identity crew's CAE onboarding page for guidance in the OneNote.

**Comment by chlowell** [comment]
Blocked on https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/263

**Comment by baywet** [comment]
related #14284

**Comment by baywet** [comment]
Additionally to passing the claim, azure identity should set the capabilities [in places like these](https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azidentity/client_certificate_credential.go#L72) (`WithClientCapabilities(new [] {"cp1"})`) [source](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-resilience-continuous-access-evaluation).

It seems that there's no way today for somebody using azure identity to set that capability.

**Comment by baywet** [comment]
see the equivalent for dotnet https://github.com/Azure/azure-sdk-for-net/blob/c7f68fb15a2dc8dace6e61f78b5b0f7425ec2d4c/sdk/identity/Azure.Identity/src/MsalPublicClient.cs#L46

**Comment by chlowell** [comment]
This support is available now: with azidentity v1.3.0-beta.3 and azcore v1.4.0-beta.1, credentials default to sending CP1 and ARM clients internally handle claims challenges.
