### ISSUE TITLE
Support for SQL `2021-02-01-preview`

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#14945]
Hello! 

I'm just looking to see if we can get the `2021-02-01-preview` version of the SQL service supported by the sdk.

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for this issue!

The SQL is shipped in a composite package way in this package: https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/sql/mgmt/v5.0/sql
You could search the api-version in this directory and there are some resources/APIs are using the api-version `2021-02-01-preview` now, including `servers`, `databases`. Could you please take a look at this package to see if it could meet your requirement?
