### ISSUE TITLE
Use existing NSG for VMSS while creation of AKS Cluster

### ISSUE THREAD

**Issue by rahul-da** [Azure/azure-sdk-for-go#14951]
Hello!

During the creation of AKS Cluster via GO SDK (using CreateOrUpdate in https://github.com/Azure/azure-sdk-for-go/blob/main/services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go), it creates a Virtual Machine Scale Set, which has a network security group created. Is it possible to avoid the creation of the NSG, and rather use a pre-existing NSG that could be attached to the VMSS.

**Comment by ArcturusZhang** [comment]
Hi @rahul-da thanks for opening this issue!

Sorry I did not find a way for us to specify the NSG during the creation of a managed cluster. It has a definition of `NetworkProfile` but it cannot specify the NSG.
I am deferring this question to the service team to answer.

**Comment by SnoWolfT** [comment]
Hi @ArcturusZhang ,

May I know whether you have any update from the service team? I encounter the same issue as rahul-da.

Thank you for your help!

**Comment by ArcturusZhang** [comment]
Hi @Azure/aks @Azure/aks-pm any updates?

**Comment by zhongyi-zhang** [comment]
As NSG can be associated with subnet, is it the same thing to use BYO subnet which applies your existing NSG? https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet

**Comment by SnoWolfT** [comment]
Hi @Azure/aks @Azure/aks-pm any updates +1?
