### ISSUE TITLE
API Management `SchemaContractProperties` `Document` is not to its swagger definition

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-sdk-for-go#14954]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
"github.com/Azure/azure-sdk-for-go/services/preview/apimanagement/mgmt/2021-01-01-preview/apimanagement"

- SDK version e.g. `master`, `latest`, `18.1.0`
"55.5.0"
 

 - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.

- output of `go version`

- What happened?
The go sdk data struct for `Document` is not according to its swagger definition

swagger link:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2021-01-01-preview/definitions.json#L4971 

SDK link: 
https://github.com/Azure/azure-sdk-for-go/blob/main/services/preview/apimanagement/mgmt/2021-01-01-preview/apimanagement/models.go#L12690

- What did you expect or want to happen?
The go sdk data struct for `Document` is according to its swagger definition
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Since the swagger has changed on the `master` branch, the generated code is aligned with the swagger. Therefore closing this issue.
Thank you!
