### ISSUE TITLE
Update the MarketPlaceOrdering package for 2015-06-01

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#14972]
### Bug Report

- import path of package in question: `.../services/marketplaceordering/mgmt/2015-06-01/marketplaceordering`
- SDK version: `master`

The Swagger has recently [changed its model for the Agreements related endpoints](https://github.com/Azure/azure-rest-api-specs/commit/24077a1b24f468dd86a5a224999e6e036c75e231#diff-14e78452177b8d700efcfc91fe4fca4ce660a932b5ce6fdd302a09d657d40af1), which is very different than before. This means currently, the code generated from the old Swagger should not functional at all. So please make a new release to catch up with the latest Swagger version.

**Comment by ArcturusZhang** [comment]
Hi @magodo thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md).
