### ISSUE TITLE
Review multi-tenant work 

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-go#14996]
Get architect approval for multi-tenant additions in azcore and armcore

**Comment by RickWinter** [comment]
@catalinaperalta, @JeffreyRichter What changes are left that need review?

**Comment by catalinaperalta** [comment]
I think this can be closed, I believe Jeff reviewed the multi-tenant PRs.

**Comment by JeffreyRichter** [comment]
Yes I reviewed this and we're good.
