### ISSUE TITLE
Unexpected quantity of TCP connections

### ISSUE THREAD

**Issue by meirf** [Azure/azure-sdk-for-go#1500]
I ran this code at https://github.com/Azure/azure-sdk-for-go/commit/56332fec5b308fbb6615fa1af6117394cdba186d

I'm seeing an unexpected number of TCP connections when copying files.

```
    package main
    
    import (
    	"net/http"
    	"sync"
    	"time"
    
    	"github.com/Azure/azure-sdk-for-go/storage"
    )
    
    func main() {
    	// create and initialize a client
    	client, _ := storage.NewBasicClient(ACCOUNT_NAME, ACCOUNT_KEY)
    
    	// use DefaultTransport with configs that limit conns
    	client.HTTPClient.Transport = http.DefaultTransport
    	transp, _ := client.HTTPClient.Transport.(*http.Transport)
    	client.HTTPClient.Transport = http.DefaultTransport
    	transp.MaxIdleConnsPerHost = 200
    	transp.MaxIdleConns = 200
    
    	rootClient := client.GetBlobService().GetContainerReference("foo")
    	numRoutines := 200
    	numRequestsPerRoutine := 100
    
    	var wg sync.WaitGroup
    	for i := 0; i < numRoutines; i++ {
    		wg.Add(1)
    		go func() {
    			for j := 0; j < numRequestsPerRoutine; j++ {
    				sourceBlob := rootClient.GetBlobReference("fileA")
    				destBlob := rootClient.GetBlobReference("dirX/fileA")
    				destBlob.Copy(sourceBlob.GetURL(), nil)
    				time.Sleep(250 * time.Millisecond)
    			}
    			wg.Done()
    		}()
    	}
    	wg.Wait()
    }
    time.Sleep(5 * time.Minute)
```

Because `MaxIdleConnsPerHost` is set to a high number we can reuse a lot more descriptors, but I still see more than what I expected. 

**Expected**
I expected there to be a maximum of 200 connections since I assume each goroutine is executing http requests in serial. 

**Observed**
Until the end of the execution, the number of TCP connections stays under 200. But towards the end that number consistently jumps to over 400 and sometimes 800 and I start getting `dial tcp: lookup `FOO.blob.core.cloudapi.de on 10.1.2.3:53: dial udp 10.1.2.3:53: socket: too many open files)`
 After the copying ends, the connections go from ESTABLISHED to CLOSE presumably because the 90 second idle connection timeout has elapsed. _But the file descriptor is still there even though the connection is closed which I think implies it's not properly being closed._

How could there be more than 200 open files if there are only 200 routines?

**Comment by meirf** [comment]
@jhendrixMSFT any ideas on this?

**Comment by meirf** [comment]
If I had some certainty around `azure-storage-blob-go` not having this same problem, I would probably switch, but it looks like there is a similar problem there. https://github.com/Azure/azure-storage-blob-go/issues/30

@jhendrixMSFT 
I would be happy with uploading a PR if you could help me narrow down where the problem is. I appreciate any suggestions on this.

Thank you!!

**Comment by meirf** [comment]
I'm not getting errors.

I've tried commenting out the wait (`return b.WaitForCopy(copyID)`) and
```
resp, err := b.Container.bsc.client.exec(http.MethodPut, uri, headers, nil, b.Container.bsc.auth)
if err != nil {
    if resp!=nil && resp.Body!=nil{
           readAndCloseBody(resp.Body)
    }
    return "", err
}
defer readAndCloseBody(resp.Body)
```

but I'm not seeing any benefits.

**Comment by jhendrixMSFT** [comment]
I found another potential issue, in [DefaultSender.Send()](https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L112) the response body isn't read/closed when a retry happens.  If you add a call to ```readAndcloseBody(resp.body)``` after line 122 does it fix the issue?

**Comment by meirf** [comment]
BINGO

@jhendrixMSFT, thanks for finding the problem!!

I've submitted https://github.com/Azure/azure-sdk-for-go/pull/1539 to the dev branch. If you think this warrants new release, I'd be happy if you created your own PR which does that. (I don't care if my PR makes it through - just happy the sooner this gets to the master branch.)

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.1.1, thanks for helping!
