### ISSUE TITLE
`AppServicePlansClient.GetResponder` does not error on 404.

### ISSUE THREAD

**Issue by jackofallops** [Azure/azure-sdk-for-go#15002]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

Import Path: github.com/Azure/azure-sdk-for-go/services/web/mgmt/2020-06-01/web
SDK Version: v55.3.0 (but all others in recent history)

Details:
`AppServicePlansClient.GetResponder` does not consider HTTP-404 an error.  This prevents the error return being correctly populated for checking and can lead to panic when accessing properties of the response that should be present in non-error states.

**Comment by lirenhe** [comment]
This seems to be a swagger issue, need the service team to update the swagger.

**Comment by lirenhe** [comment]
@jackofallops, as this is a Swagger issue for compute RP, i have created https://github.com/Azure/azure-rest-api-specs/issues/17160 and use it to track this issue.
I will close this item.
