### ISSUE TITLE
Instance location is empty in usage details

### ISSUE THREAD

**Issue by svaroop** [Azure/azure-sdk-for-go#1501]
Not getting information about instance location in usage details : github.com/Azure/azure-sdk-for-go/services/consumption/mgmt/2018-03-31/consumption package

**Comment by jhendrixMSFT** [comment]
Hi!  Can you please provide a bit more info about this issue, i.e. what API you're calling (I'm guessing it's UsageDetailsClient.List) and what you mean by "not getting information", is the field nil or empty string?

**Comment by svaroop** [comment]
Hi. yes. i'm using consumption.UsageDetailsClient. getting below json.

**Comment by jhendrixMSFT** [comment]
@asarkar84 do you know why the instanceLocation isn't included in the response?

**Comment by asarkar84** [comment]
InstanceLocation is currently not available for WebDirect subscriptions.

**Comment by jhendrixMSFT** [comment]
Closing as it looks like this has been answered, please re-open if you have further questions.
