### ISSUE TITLE
Include Azure Automation rest api version 2020-01-13-preview

### ISSUE THREAD

**Issue by OmnipotentOwl** [Azure/azure-sdk-for-go#15020]
### Service Package Request
Hello,

In investigating the ability to support Managed Identities on Azure Automation Accounts in Terraform it looks like the support which was last updated in the Azure Rest API specs repo with  Azure/azure-rest-api-specs/pull/12928 never made it into the Azure SDK for Go repo but the PR for it did get auto-created #14309 but was not moved forward for some reason.

Currently, this is blocking the ability to implement Managed Identities for Azure Automation Accounts via terraform-providers/terraform-provider-azurerm/issues/11503 and would further unblock this scenario for the Cloud Adoption Framework for Azure - Terraform landing zones module and solutions group via aztfmod/terraform-azurerm-caf/issues/474.

I would like to get be able to move forward with adding this support to Terraform so getting this new API version included would be greatly appreciated.

**Comment by doherty100** [comment]
Microsoft is recommending that customers stop using RunAs accounts for Azure Automation and move to managed identities so support for this is critical.

**Comment by ArcturusZhang** [comment]
Hey @OmnipotentOwl and @doherty100 thanks for this issue and sorry for the delay of response.

We have an internal email to confirm the readiness of their swagger, once we get that, we will release a new package for this api-version of this RP

**Comment by lirenhe** [comment]
We need to release a new version of the SDK for this.

**Comment by 804873052** [comment]
Hi @OmnipotentOwl thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by Alancere** [comment]
released in https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/automation/mgmt/2020-01-13-preview/automation
