### ISSUE TITLE
Storage Soft Delete Support

### ISSUE THREAD

**Issue by rohrerb** [Azure/azure-sdk-for-go#1504]
Hello,

Could we get support for Storage Soft Delete?

https://azure.microsoft.com/en-us/blog/soft-delete-for-azure-storage-blobs-now-in-public-preview/
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-soft-delete

Thank you.

**Comment by jhendrixMSFT** [comment]
The storage package in this repo is in maintenance mode, it's been replaced by the azblob package.  I've ported this issue to its repo, see https://github.com/Azure/azure-storage-blob-go/issues/37

**Comment by techiechap** [comment]
Can some pls share the configuration block for soft delete?

**Comment by jhendrixMSFT** [comment]
@techiechap please see https://github.com/Azure/azure-sdk-for-go/commit/cdf51db824e96eb7b402324f229fd7cb828ec087#diff-ddecebdea58b5f264d27f1f7909bab74 for where it was added, I believe it's the `DeleteRetentionPolicy` field.

**Comment by techiechap** [comment]
Thank you Jeol,

its kinda confusing, below is my snippet for existing storage account, now
i would like to refer to the storage account and enable (soft_delete,
https_traffic)
any help appreciated.

#Refer to RG
data "azurerm_resource_group" "resource_gp" {
  name      = "dev-storage-test"
}
#Refer to Storage Account
data "azurerm_storage_account" "st_ac1" {
  name                = "cvstaccountone"
  resource_group_name = "dev-storage-test"
}
#next step...

**Comment by jhendrixMSFT** [comment]
For management operations you'll want to use the the management APIs, see https://github.com/Azure/azure-sdk-for-go/tree/master/services/storage/mgmt/2019-04-01/storage.  [SetProperties](https://github.com/Azure/azure-sdk-for-go/blob/master/services/storage/mgmt/2019-04-01/storage/blobservices.go#L239) to enable soft delete and [Update](https://github.com/Azure/azure-sdk-for-go/blob/master/services/storage/mgmt/2019-04-01/storage/accounts.go#L1211) to configure HTTPS traffic.

**Comment by techiechap** [comment]
I appreciate Joel,
I would be grateful if that configuration is available as sample, would you
pls elaborate how could i get set properties on above configuration,

Thanks
Ashish

**Comment by tombuildsstuff** [comment]
@techiechap unfortunately Soft Delete support isn't available in Terraform yet - but [is being tracked in this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1329) - please subscribe to that issue for updates

**Comment by techiechap** [comment]
Awesome, thanks, many latest feature are not available, thats bit tedious,
hope they make terraform as first option.


 i was wondering whey some of the issue were closed?

https://github.com/terraform-providers/terraform-provider-azurerm/issues/1070
https://github.com/Azure/azure-storage-blob-go/issues/37

Thanks again
Ashish
