### ISSUE TITLE
Policy cleanup

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#15050]
### Feature Request

Move policies into a module

- [ ] TokenRequestOptions is “Options” the right thing to call this
- [ ] AuthenticationPolicyOptions
    - [ ] Field name may need to change
    - [ ] Possibly get rid of one of them
- [ ] Policies might be able to be in a modules
- [ ] Pipeline could perhaps be in SDK packages
- [ ] Check RetryOptions for name patterns

**Comment by seankane-msft** [comment]
Rename `Options` [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/credential.go#L18) to `TokenRequest`

**Comment by seankane-msft** [comment]
AuthenticationPolicyOptions -> AuthenticationOptions

**Comment by seankane-msft** [comment]
Change [this](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/credential.go#L24) to `NewAuthenticationPolicy`

**Comment by jhendrixMSFT** [comment]
Fixed in `v0.19.0`
