### ISSUE TITLE
CodeCoverage needs to be reported in CI

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#15062]
### Feature Request

- [ ] Add support to report codecoverage in CI
- [ ] Add minimum bars to prevent PRs from regressing

**Comment by RickWinter** [comment]
cc @seankane-msft

**Comment by seankane-msft** [comment]
* Code coverage is reported under the "Code Coverage" tab in CI, example for [azcore](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1038562&view=codecoverage-tab)
* Pipelines will fail if the code coverage reported by `go test` is lower than the values stored in [eng/config.json](https://github.com/Azure/azure-sdk-for-go/blob/main/eng/config.json)
