### ISSUE TITLE
[service-bus] Service Bus message

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15094]
Messages in Service Bus track 2 do not have settlement methods. Settlement is done on the Receiver instance. This avoids having an "active record" style pattern, which is non-idiomatic to the Azure SDK.

In addition field names have been standardized across the SDKs and will need to be here. Some examples:
- `Data` should now be `Body`
- `message` (private field) should be exposed as `RawAmqpMessage` (and its API surface should be reviewed as well to be consistent with the post-track-2 AMQP annotated message feature)
- `Label` should now be `Subject`
- `UserProperties` should be `ApplicationProperties`
- (and probably more)

There is a smaller Message/ReceivedMessage currently checked in. More than likely we'll just move those out of the way in favor of using the existing messages (with fields renamed).

There is a new interface (SendableMessage) that they'll need to conform to, but that's basically what `toMsg` is.

**Comment by devigned** [comment]
Standardizing field names to names that are different than the standard seem reasonable in the SB / EH code. Hopefully, the underlying protocol implementation will stay consistent with the AMQP spec.

**Comment by richardpark-msft** [comment]
@devigned: same goal here for sure. We made some changes for the "above ground" portions with the SB/EH messages so that's all this particular is.

There's been some work in the Service Bus and Event Hubs SDKs to allow more direct AMQP integration, which we'd want to do as well. I submitted an issue to cover that - it is part of the modern Service Bus SDKs: #15260

**Comment by richardpark-msft** [comment]
Message, as the simple azservicebus version, is done. Direct AMQP message access will come in https://github.com/Azure/azure-sdk-for-go/issues/15260
