### ISSUE TITLE
IOT DPS enrollment groups is missing from the SDK

### ISSUE THREAD

**Issue by ramondeklein** [Azure/azure-sdk-for-go#15098]
The administration of IOT hub's device provisioning service enrollment groups isn't in the Azure SDK for Go. This prevents the Terraform IOT DPS plug-in to allow the creation of enrollment groups. It seems that IOT DPS is low on the priority list, because the SDK also doesn't support the newer API (it's stuck on 2018-01-22).

**Comment by lirenhe** [comment]
Seems we need to refresh the SDK

**Comment by 804873052** [comment]
Hi @ramondeklein  thanks for this issue!

released https://github.com/Azure/azure-sdk-for-go/tree/main/services/iothub/mgmt/2020-03-01/devices.
