### ISSUE TITLE
appconfigurationapi Service wildcard search returning paged list

### ISSUE THREAD

**Issue by remhead** [Azure/azure-sdk-for-go#15188]
### Service Package Request

I am looking to build a Kubernetes Operator that builds ConfigMaps based on Azure App Configuration Key Value Pairs. In order to accomplish this I will need to use the Azure SDK for Go.

While inspecting the appconfigurationapi service in the SDK I have been unable to find a List command that will replicate the https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-key-value List key-values with a filter that would allow me to wildcard a request and return a paginated list of key values.

**Comment by RickWinter** [comment]
Thank you for using Azure and the Azure SDK for Go.  At this time we do not have support for App Config in the Go SDK.  We've added this request to the backlog and will look into adding support in the future.

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

We now have SDK `azappconfig` in beta and I believe [this method](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/azappconfig#Client.NewListSettingsPager) will provide the functionality you're looking for.
