### ISSUE TITLE
UUID is pseudo random

### ISSUE THREAD

**Issue by pascaldekloe** [Azure/azure-sdk-for-go#15180]
The UUIDs don't use a cryptographically randomised source. Not doing so breaks the specification.

**Comment by RickWinter** [comment]
Thank you for reporting this issue.  We will make a fix available soon.

**Comment by pascaldekloe** [comment]
The cryptographic random source can encounter errors, so you'd need to either change the name or use another UUID version.

**Comment by pascaldekloe** [comment]
Thank you @RickWinter. The changes look good.
