### ISSUE TITLE
Release Pipeline support for packages

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#15226]
Automation improvements for releasing packages

**Comment by benbp** [comment]
Adding some context here based on what we have in other languages:

Core release steps:
- Build
- Sign (doesn't seem relevant for go?)
- Verify changelog
- Verify no unreleased dependencies
- Create tags
- Release to feed (duplicate with tags?)
- github.io docs
- docs.ms docs
- update local package version references in the repo

Validation steps:

- Unit/CI testing
- Samples testing (live testing with samples code/projects)
- Testing for dependency issues with projects that include multiple SDKs with latest versions (run install with published package)

**Comment by RickWinter** [comment]
Split last two items into separate issues.

- https://github.com/Azure/azure-sdk-for-go/issues/15753
- https://github.com/Azure/azure-sdk-for-go/issues/15754
