### ISSUE TITLE
App service to allow accessing KeyVault with user assigned managed identity

### ISSUE THREAD

**Issue by tamirkamara** [Azure/azure-sdk-for-go#15227]
### Feature Request

App service allows referencing KeyVault secrets directly via its config. This is usually done with a system assigned managed identity. However, when the app service is defined with a user assigned one special configuration has to be applied as [described here](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#access-vaults-with-a-user-assigned-identity).

Having this setting would allow Terraform to include direct support for this too.

**Comment by tadelesh** [comment]
Thank you for your feedback. In 2021-02-01 web mgmt SDK, ManagedServiceIdentity can be updated by UpdateSlot API with siteEnvelope param (siteEnvelope -> Identity -> UserAssignedIdentities).
