### ISSUE TITLE
[Identity] Document the package can be used for more than the Azure SDKs

### ISSUE THREAD

**Issue by sadasant** [Azure/azure-sdk-for-go#15222]
Recently, the Azure SDK for TS/JS received requests from customers to improve our introductory paragraph in our Identity README to also mention that the Identity package could be used from applications not using the Azure SDK. We made the changes in our README here: https://github.com/Azure/azure-sdk-for-js/pull/16800. If you agree, we should do a similar change in the Identity README for Go.

**Comment by baywet** [comment]
FYI we have a Microsoft Graph Go SDK on the way that relies on Azure Identity https://github.com/microsoftgraph/msgraph-sdk-go (might give you a 404 right now as it's private)

**Comment by chlowell** [comment]
I would rather leave this implicit in the documentation. Applications can use `azidentity` independently from the SDK, if it has the necessary features, but I don't want to encourage that. `azidentity` has a narrow focus: authenticating Azure SDK clients. Developers looking for a general purpose authentication package should prefer [MSAL for Go](https://github.com/AzureAD/microsoft-authentication-library-for-go).
