### ISSUE TITLE
InvalidRequestFormat when create private link service

### ISSUE THREAD

**Issue by veezhang** [Azure/azure-sdk-for-go#15229]
### Bug Report

- import path `github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-02-01/network`
- SDK version `github.com/Azure/azure-sdk-for-go v55.0.0`
- output of `go version go1.16.2 darwin/amd64`

I create private link service with the following parameters:

```golang
	region := "eastus"
	serviceName := "pl-test"
	resourceGroupName := "rg-test"
	frontendIPConfigurationID := "/subscriptions/xxxx/resourceGroups/rg-test/providers/Microsoft.Network/loadBalancers/xxx/frontendIPConfigurations/xxx"
	subnetID := "/subscriptions/xxxx/resourceGroups/rg-test/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx"

	loadBalancerFrontendIPConfigurations := &[]network.FrontendIPConfiguration{network.FrontendIPConfiguration{
		ID: to.StringPtr(frontendIPConfigurationID),
	}}

	ipConfigurations := &[]network.PrivateLinkServiceIPConfiguration{{
		PrivateLinkServiceIPConfigurationProperties: &network.PrivateLinkServiceIPConfigurationProperties{
			PrivateIPAllocationMethod: network.IPAllocationMethodDynamic,
			Subnet: &network.Subnet{
				ID:                     &subnetID,
			},
			Primary:                 to.BoolPtr(true),
			PrivateIPAddressVersion: network.IPVersionIPv4,
		}}}

	parameters := network.PrivateLinkService{
		Name:             &serviceName,
		PrivateLinkServiceProperties: &network.PrivateLinkServiceProperties{
			LoadBalancerFrontendIPConfigurations: loadBalancerFrontendIPConfigurations,
			IPConfigurations:                     ipConfigurations,
			EnableProxyProtocol:                  to.BoolPtr(false),
		},
		Location: &region,
	}
```

I got an error `Failure sending request: StatusCode=0 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[]`.

Are there missing parameters? Or are there any samples?

The `Details` is empty, and I cannot get more useful information. If `Details` can explain why it is wrong, it might be more helpful to me.

**Comment by veezhang** [comment]
I had create a support 2108090050000055.  He suggested me to use `Portal`, `Powershell`, `Cloud CLI` or `ARM template` to create resources.

But I would rather use the SDK to **dynamically** create resources.

**Comment by veezhang** [comment]
I found that the `Name` of `network.PrivateLinkServiceIPConfiguration` is required.
And is it possible to prompt a more friendly error message in `Details`?

**Comment by ArcturusZhang** [comment]
> I found that the `Name` of `network.PrivateLinkServiceIPConfiguration` is required.
> And is it possible to prompt a more friendly error message in `Details`?

Hi @veezhang 😢unfortunately in your case, the error does not come from the validation in the SDK, it comes from the service, therefore we cannot do anything to improve the error message. I tagged this issue with service attention so that some one from the service team might take this a look

**Comment by lirenhe** [comment]
From Swagger, https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/privateLinkService.json#L874, name in PrivateLinkServiceIpConfiguration is not marked as required.   So for this swagger issue, could you create a issue in https://github.com/Azure/azure-rest-api-specs/issues/new?  

For the service to return a more meaningful message, could you leverage the support ticket for communication?
