### ISSUE TITLE
v0.18.0 broken

### ISSUE THREAD

**Issue by mjudeikis** [Azure/azure-sdk-for-go#15237]
### Bug Report

We are trying to migrate to AzCore Track2 for go. We tried new generator for autorest and found inconsistencies in the SDK being generated:

Generation:
```
sudo docker run \
    --rm \
    -v $PWD/pkg/client:/github.com/Azure/ARO-RP/pkg/client:z \
    -v $PWD/swagger:/swagger:z \
    "${AUTOREST_IMAGE}" \
    --go \
    --version=3.4.5 \
    --use=@autorest/go@4.0.0-preview.24 \
    --use=@autorest/modelerfour@~4.20.0 \
    --license-header=MICROSOFT_APACHE_NO_VERSION \
    --namespace=redhatopenshift \
    --verbose \
    --input-file=/swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/"$FOLDER"/"$API_VERSION"/redhatopenshift.json \
    --output-folder=/github.com/Azure/ARO-RP/pkg/client/services/redhatopenshift/mgmt/"$API_VERSION"/redhatopenshift
```

Issue itself is in the `azcore` where generated client expects external type for `Connection`:
```

type OperationsClient struct {
	con *Connection
}
```

But `connection` type is internal only. 
```
// connection - Rest API for Azure Red Hat OpenShift 4
type connection struct {
	u string
	p azcore.Pipeline
}
```

**Comment by jhendrixMSFT** [comment]
Hello!  By default, the generated client are not exported (I can go into details why if interested).  To export them, you specify `--export-clients:true`.  Note that this switch might get renamed to `--public-clients`, see https://github.com/Azure/autorest.go/pull/657 for more info.

**Comment by mjudeikis** [comment]
> Hello! By default, the generated client are not exported (I can go into details why if interested). To export them, you specify `--export-clients:true`. Note that this switch might get renamed to `--public-clients`, see [Azure/autorest.go#657](https://github.com/Azure/autorest.go/pull/657) for more info.

Thanks :) Overall would be good to make this more intuitive as basically with the settings generated above (we got them from SDK team for migration) client is unusable.
