### ISSUE TITLE
Add request id policy

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#15236]
Need to add the x-ms-client-request-id into headers.

Items

- Add new policy
- Add policy to clients
- Add tests for policy

**Comment by seankane-msft** [comment]
@RickWinter do you know of an example policy in other languages that takes care of this?

**Comment by seankane-msft** [comment]
I think the addition to clients will have to be done by autorest, @jhendrixMSFT is there another way to do this? I'm willing to learn enough autorest to make that change if you're willing to sit down with me for a bit.
