### ISSUE TITLE
[Azure-Batch] 2021-01-01 New User Assigned Managed Identity features for Batch Pool

### ISSUE THREAD

**Issue by haflidif** [Azure/azure-sdk-for-go#15274]
### Feature Request

Current version is **2020-09-01** there are new features regarding usage of User Assigned Managed Identity for Azure Batch Pool that are available in version **2021-01-01** https://docs.microsoft.com/en-us/azure/batch/managed-identity-pools is it possible to have it supported

**Comment by 804873052** [comment]
Hi @haflidif thanks for this issue!

released in https://github.com/Azure/azure-sdk-for-go/tree/main/services/batch/mgmt/2021-06-01/batch.
