### ISSUE TITLE
Import url cleanliness

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#15447]
Go supports Vanity urls for mod imports.  This would enable us to do something to the tune of:
```Go
import (
    github.com/Azure/GoSDK/core
    github.com/Azure/GoSDK/storage/blobs
    github.com/Azure/GoSDK/keyvault/keys
    ...
    )
```

Among other repo considerations, its worth considering a cleaner import story.

**Comment by jhendrixMSFT** [comment]
If we go this route I would also suggest that the URL be all lower-case characters as this has impact on systems with case-sensitive file systems (the capital 'A' in "Azure" is a real bummer).

**Comment by sadasant** [comment]
What about something like `go.azure.com/core` ?
