### ISSUE TITLE
merge and update succeeds even with mismatching etag ("") and force flag = false

### ISSUE THREAD

**Issue by sriarush** [Azure/azure-sdk-for-go#15476]
https://github.com/Azure/azure-sdk-for-go/blob/fbb66cedeb94af0a56ff6e8f31a44314af3ef114/storage/entity.go#L410

**Comment by sriarush** [comment]
it works fines with mismatching etag but correct format but not with etag=""

**Comment by jhendrixMSFT** [comment]
Hello!

The contents of the `/storage` package have been deprecated.

For tables, please check out our new [`aztables`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables) module which should have this fixed.
