### ISSUE TITLE
CDN 2020-09-01 is missing the `CustomHTTPSParameters` in model `CustomDomainProperties` (which exists in 2019-04-15)

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#15528]
In the Azure/azure-rest-api-specs, there is a commit: [Add missing customHttpsParameters field of CustomDomainProperties](https://github.com/Azure/azure-rest-api-specs/commit/162aac8f049496e8b4dd411c1a9dcc2a9e80da9c). The issue here is that in the currently used Go SDK, the model generated for 2019-04-15 has the [HTTPS parameters](https://github.com/Azure/azure-sdk-for-go/blob/51cec6163ccae3560113ea5142117f1332594181/services/cdn/mgmt/2019-04-15/cdn/models.go#L483) when getting the custom domain, while the model generated  (**at least**) for 2020-09-01 [doesn't](https://github.com/Azure/azure-sdk-for-go/blob/51cec6163ccae3560113ea5142117f1332594181/services/cdn/mgmt/2020-09-01/cdn/models.go#L2551).

Please update the CDN RPs to fix this.
(The latest Swagger also has another fix for the missing LRO for the enable/disable HTTPS for the custom domain)

This currently blocks: hashicorp/terraform-provider-azurerm#13283

**Comment by magodo** [comment]
@ArcturusZhang Would you please take a look at this and route it to the service team? Thanks!

**Comment by ArcturusZhang** [comment]
Hi @cdnfdsuppgithub can you please submit a release request to refresh this api-version in order to unblock our terraform work?

**Comment by t-bzhan** [comment]
Ack

**Comment by magodo** [comment]
@t-bzhan Any update for this? IIRC this should be a S360 issue.

**Comment by magodo** [comment]
This is now fixed in the v59 release.
