### ISSUE TITLE
[app-service] Support Listing Publishing Profile 

### ISSUE THREAD

**Issue by dmedeiros204** [Azure/azure-sdk-for-go#15581]
### Feature Request

Support the ability to use these endpoints to list the publishing profile of an web app or azure function

https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/list-publishing-profile-xml-with-secrets

With Slot support

https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/list-publishing-profile-xml-with-secrets-slot

**Comment by lirenhe** [comment]
@dmedeiros204, to clarify your ask, is it about you could listing Publishing profile by api documented but you are unable to use it in GO SDK or the rest API also does not have this ability?

**Comment by dmedeiros204** [comment]
> 
> 
> @dmedeiros204, to clarify your ask, is it about you could listing Publishing profile by api documented but you are unable to use it in GO SDK or the rest API also does not have this ability?

I'd like the go sdk to support this existing rest API functionality, unless I missed something it currently does not.

**Comment by ArcturusZhang** [comment]
Hi @dmedeiros204 I would like to clarify that would like a new-version SDK in the `sdk` directory, or an old-version SDK in the `services` directory? BTW we should already support this API in our new-version of SDKs. You can find it in this file: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/web/armweb/zz_generated_webapps_client.go (unfortunately it cannot be rendered on the github page @jhendrixMSFT would this be a problem for us in the future?)
