### ISSUE TITLE
GET VMSS expand parameter not required

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-sdk-for-go#15602]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
/services/compute/mgmt/2021-07-01/compute/virtualmachinescalesets.go#L553

- SDK version e.g. `master`, `latest`, `18.1.0`
latest 
Release v57.0.0 1630045276 (#15400)

  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
GET VMSS expand parameter looks like it is required. That is incorrect...it should be an optional parameter. See https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/get

- What did you expect or want to happen?
Customer should be able to GET VMSS without specifying expand parameter.
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by fitzgeraldsteele** [comment]
@RickWinter @lirenhe is there any way to get an RCA for this one? How is possible that an optional parameter in the API gets made as required in the SDK? Is there something we need to do differently in swagger?

**Comment by ArcturusZhang** [comment]
And BTW, in track 1 SDK, you will have to assign an empty string to it if you do not want to pass `expand` parameters.
