### ISSUE TITLE
Please provide documentation on how to use paginated response from armauthorization client

### ISSUE THREAD

**Issue by savaradh** [Azure/azure-sdk-for-go#15601]
### Feature Request

I am trying to use ListForResource from armauthorization client. It is returning a new type PermissionsListForResourcePager which has NextLink and PageResponse. Requesting clear documentation on how to navigate through this PermissionsListForResourcePager.
```
func (client *PermissionsClient) ListForResource(resourceGroupName string, resourceProviderNamespace string, parentResourcePath string, resourceType string, resourceName string, options *PermissionsListForResourceOptions) *PermissionsListForResourcePager
```

**Comment by ArcturusZhang** [comment]
Hi @804873052 could you help on this?

**Comment by 804873052** [comment]
@savaradh You can refer to https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/308/files#diff-fc361b82c4b795bb9dd57ffe0d1131ea0e36bafc44e7596488b0013305f6262bR121
