### ISSUE TITLE
Wiki Image link is broken in Set-up-Your-Environment-for-Authentication

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-sdk-for-go#15600]
### Bug Report

The link to the image is broken in the document below.

https://github.com/Azure/azure-sdk-for-go/wiki/Set-up-Your-Environment-for-Authentication#enable-applications-for-device-code-flow

![image](https://user-images.githubusercontent.com/73158/134086173-4edfc692-264c-4d6b-a375-54b67f488e2e.png)

Although it is described as a link like the one below. `/blob/master/` is a mistake in` /raw/main/ `.
```

![device code enable](https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/azidentity/img/devicecode-enable.png)
```

After correction.

```
![device code enable](https://github.com/Azure/azure-sdk-for-go/raw/main/sdk/azidentity/img/devicecode-enable.png)
```

**Comment by RickWinter** [comment]
Thank you for taking the time to report this issue.  I've updated the wiki links.
