### ISSUE TITLE
Add service package for cognitiveservices/v3.1/textanalytics

### ISSUE THREAD

**Issue by scottadamsmith** [Azure/azure-sdk-for-go#15616]
### Service Package Request

Service: CognitiveServices > TextAnalytics > v3.1
Language: Golang

I started using the golang package github.com/Azure/azure-sdk-for-go/services/cognitiveservices/v2.1/textanalytics to integrate with the DetectLanguage and Sentiment apis, but I overlooked the fact that it was using the older 2.1 api. I realized this once I tried to handle the output and saw that the package was returning an array of detected languages per document, whereas the newer 3.1 only returns a single detected language. 

Are there any plans for an updated golang package to interface with the 3.1 api? I dug around in the preview directory, but didn't see anything that led me to believe there is.

Thanks for your time.

**Comment by RickWinter** [comment]
Thank you for using the Go SDK and providing feedback.  We are working to provide support for all of Azure in Go.  I can't say specifically when this service will be available in the Go SDK.

**Comment by Avinodh** [comment]
Hi @RickWinter  - following up on this. I see that github.com/Azure/azure-sdk-for-go/services/cognitiveservices/v2.1/textanalytics no longer exists in the source tree either.

Is supporting this for Go on the roadmap in the short term? Thank you!

**Comment by Avinodh** [comment]
@RickWinter  - Following up on this
