### ISSUE TITLE
Auth Interop between sdk/ & /services sdks

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#15612]
Currently not all RP modules are available in the new SDK. So for some APIs we need to use the 'old' SDK. (EX: subscriptions client)

The new sdk use different auth mechanism compared to the old (authorizer )

Is there a doc on how can we use `azcore.TokenCredential` with old `autorest.Authorizer` ( or the other way)

Thanks
Vijay

**Comment by ArcturusZhang** [comment]
Hi @vijayrajah thank you for this issue!

We actually have a sample to convert a `azcore.TokenCredential` to `autorest.Authorizer` here: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/samples/azidentity/SDKV1Adapter

**Comment by vijayrajah** [comment]
@ArcturusZhang  -- Thanks for the reply. 

The example does not work anymore, as the azcore module has been refactored in multiple modules.

I tried to fix the issue, based on the example from [https://github.com/jongio/azidext/blob/master/go/azidext/azure_identity_credential_adapter.go](here)

The `azcore.Request` has been refactored into `pipeline.NewRequest` ( `github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pipeline` )

But, since  pipeline package is in internal, I cannot import it. So, I cannot use `pipeline.NewRequest`

Any suggestions ?

**Comment by chlowell** [comment]
We updated the adapter in https://github.com/jongio/azidext/pull/47, please try its [version 0.2.0](https://pkg.go.dev/github.com/jongio/azidext/go/azidext).
