### ISSUE TITLE
ACR model not align with Swagger: non-exist field `StorageAccount` defined in model `RegistryProperties`

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#15645]
### Bug Report

In side the ACR code in current main branch, there defined a non-exist field `StorageAccount` (in turns of [Swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/06a8e3f942ff066ea1eeed1d777c162d312114e2/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2020-11-01-preview/containerregistry.json#L3994)) defined in model [`RegistryProperties`](https://github.com/Azure/azure-sdk-for-go/blob/ec117138a3aa00cd412c313ddaafda3cf8e2bdaf/services/preview/containerregistry/mgmt/2020-11-01-preview/containerregistry/models.go#L5200-L5200). Precisely, that field existed before, but later got removed by https://github.com/Azure/azure-rest-api-specs/pull/13001.

This issue currently impacts our internal tooling which asks a high level of correctness of the Go SDK and the Swagger spec. Please help confirm and regenerate the ACR code for 2020-11-01-preview, and even any newer version.

**Comment by 804873052** [comment]
Hi @magodo thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.

**Comment by Alancere** [comment]
@magodo containerregistry latest preview version is https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/containerregistry/mgmt/2021-08-01-preview/containerregistry

**Comment by magodo** [comment]
Closing this since the 2020-11-01 version and its successors are fixed.
