### ISSUE TITLE
SDK documentation for consumers

### ISSUE THREAD

**Issue by adeturner** [Azure/azure-sdk-for-go#15656]
Apologies, I'm going to ask an almost certainly naïve question....

For the autogenerated SDKs like armcosmos and armservicebus, please can you point me to the client documentation?

E.g. https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/cosmos/armcosmos

Here there are zz_ files, but no instruction at all on how to use them other than limited methods for authentication.

Sleuthing around autorest... clearly there is a pattern for the sdk function naming, and probably a API swagger file available somewhere that autorest generated the zz_ files from. 

What I'm sorely after is the hook that provides me the entry point to the Go SDK functions.

Or as I've been doing to date, am I really expected to read the code and guess my way to the answers?

Cheers, Adrian

**Comment by tadelesh** [comment]
Thank you for your feedback. Since we are working on the preview of new go SDK version, examples for each RP as well as detailed API doc are on the way before GA. I've added our PM to this issue and will keep you in touch with the new update. Thanks.

**Comment by adeturner** [comment]
@lirenhe thanks for the info and the insight into the new-version, much appreciated. 
I've taken to wrapping az cli as a holding point/workaround and will circle back when available
Please let me know if I should leave this open or not

**Comment by lirenhe** [comment]
@adeturner, thanks for your update. We will close this item.
