### ISSUE TITLE
MQ: generate a simple "public API" file to make it simpler to see when we change or expose new symbols

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15661]
It's good to have a handle on what the public symbols are for a package.

Some ideas:
- Upload changes to apiview. It has a built-in diff as well as comment support, which can be useful for collaborating on changes after a PR.
- Auto-generate a readable text file and check that in, along with a CI step that validates that what's committed into the branch/PR matches what gets generated. This is nice because you can use this as part of your normal iterative development as well. 

  This is what JS does - the apiextractor tool outputs a file like this: [api-extractor output](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/servicebus/service-bus/review/service-bus.api.md). The tool also does some reasonable hygiene checks, like public symbols not having comments, etc...

There are possibly others.

**Comment by RickWinter** [comment]
@richardpark-msft The diff support in apiview gives us the ability to see what has changed.  I believe we have what we need here now.

**Comment by richardpark-msft** [comment]
It's not quite the same but it's probably good enough.
