### ISSUE TITLE
Migration guide moving from ARM track 1 to track 2

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15676]
It's useful for customers if they can get a good estimate of how much change is required in their code as well as something we can point to when customers ask.

It also gives us a chance of people finding it via search, organically, when they look for why an old symbol doesn't exist anymore.

As an example, for Service Bus, we wrote guides like this: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/servicebus/service-bus/migrationguide.md

**Comment by lirenhe** [comment]
@richardpark-msft, are you asking for this guide? https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

**Comment by richardpark-msft** [comment]
Yes, I think those are the guides we're thinking of. For any area where we're migrating from a previous package we supported to a new one we want people to adopt, basically.

(I believe at the time we talked about ARM was one of the areas we were talking about, so this sounds covered to me).

@RickWinter, are there any other packages you can think of where we might want a guide?
