### ISSUE TITLE
[service-bus] Tracing

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15678]
This issue tracks adding in distributed tracing using our `azcore/tracing` package, which has an adapter so it can report to OpenTelemetry.

Main issue: https://github.com/Azure/azure-sdk-for-go/issues/19280

There are some features missing to do linking and to generate diagnostic IDs, which are detailed in this comment: https://github.com/Azure/azure-sdk-for-go/issues/19280#issuecomment-1664902025

My plan is basically:

- [ ] Get link support into tracing
- [ ] Get SpanContext support into tracing
- [ ] Implement distributed tracing in Service Bus for send and receive

The actual spans we'll create are detailed in this spec from @lmolkova:
https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92

(previous text deleted now that we know we're going with our azcore/tracing package _and_ we have a solid spec for what we're doing with regards to spans and their data)

**Comment by devigned** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter is what we are using in Cluster API Provider Azure. You can see it used in [comparison with Jaeger and App Insights here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1575). There is some work to be done for metrics and log events, but it's not too far off. The comparison also shows traces including Azure SDK spans for HTTPS requests to Azure.

As for using `tab`, it might be better to have the SDKs own abstraction, one less dependency. It's relatively simple to implement a single provider. It would be more complex to provide a plugable solution where a user can bring their own. However, by standardizing on OpenTelemetry and exposing in that format, a user can use OpenTelemetry exporters to export in their format of choice.

**Comment by lmolkova** [comment]
Azure Monitor plans in Go do not include an in-process exporter, but they are going to have an official collector-based exporter (out-of-process agent) in the long term. As @devigned  just commented there is [unofficial](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter) one. 

I'm curious to learn what API we'd want to expose to users for tracing  - they'd have OpenTelemetry (or something else) either way if they want to trace and in other languages, we target zero to a few lines of configuration code needed to enable Azure SDK tracing. 

In the happy case, all users need to interact with lives in OpenTelemetry/Tab(Census/Tracing).

**Comment by devigned** [comment]
>  but they are going to have an official collector-based exporter (out-of-process agent) in the long term.

Any thoughts on why we wouldn't continue to build upon the "unofficial" exporter? Seems to work pretty well thus far. Also, how long is long term? Are we talking days, months, years?

**Comment by lmolkova** [comment]
I don't really know if it will be built on top of an unofficial one or will be rebuilt from scratch for some reason. There is no timeline, so unoffical exporter is as good as it gets in the near future.
Here's the source: https://techcommunity.microsoft.com/t5/azure-monitor/opentelemetry-azure-monitor/ba-p/2737823

**Comment by richardpark-msft** [comment]
Just to refresh this discussion a bit, we'll probably remove our direct dependency on 'tab' and just create a light pluggable abstraction, similar to what we provide in `github.com/Azure/azure-sdk-for-go/sdk/azcore/log`.

**Comment by JeffreyRichter** [comment]
Whatever happened to the tracing design we discussed?
Did this ever get prioritized and assigned to anyone?

**Comment by richardpark-msft** [comment]
Nothing's moved forward here, beyond the original sketch that you shared with @lmolkova and I.

**Comment by darrenparkinson** [comment]
With regards tracing, what is the appropriate way currently to achieve propagation between services using open telemetry and service bus?  From the [service bus docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2) it says:

> *Microsoft Azure Service Bus messaging has defined payload properties that producers and consumers should use to pass such trace context. The protocol is based on the [W3C Trace-Context](https://www.w3.org/TR/trace-context/).*

I'm assuming this only works with .Net at the moment? 

Thanks for any information you can provide.

**Comment by richardpark-msft** [comment]
> With regards tracing, what is the appropriate way currently to achieve propagation between services using open telemetry and service bus? From the [service bus docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2) it says:
> 
> > _Microsoft Azure Service Bus messaging has defined payload properties that producers and consumers should use to pass such trace context. The protocol is based on the [W3C Trace-Context](https://www.w3.org/TR/trace-context/)._
> 
> I'm assuming this only works with .Net at the moment?
> 
> Thanks for any information you can provide.

@lmolkova, can you answer this question? This particular issue is about Go and what we're considering but, assuming we fall in line with the rest of the SDKs, will this solve @darrenparkinson's requirement as well?

**Comment by lmolkova** [comment]
@darrenparkinson As @richardpark-msft mentioned, ServiceBus Go SDK does not yet support opentelemtery yet, but we're working on it. 

In the meantime, the best option would be to write your own instrumentation: 
1. Follow [Otel messaging semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md) to create spans with specific attributes.
2. Propagate context using [Message.ApplicationProperties](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/message.go#L35). Here's an example of how it's done in [HTTP instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/httptrace/otelhttptrace/httptrace.go#L63-L77). 
3. If you have ServiceBus producer and consumer both written in Go and you're going to instrument them both, you can use W3C Trace-Context propagator from OTel.
   - If you have one of them written in another language (.NET, Java, Python, JS) where you leverage existing SDK instrumentation, you'd have to implement your own propagator for `Diagnostic-Id`. You can use [W3C Trace-Context](https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go) as a starting point and rename `traceparent` to  `Diagnostic-Id`, `tracestate` is not supported, s you can remove any mentions of it.

**Comment by richardpark-msft** [comment]
Reviving the work here now that we have a tracing implementation in azcore in beta. Can't ship with it in that state quite yet, but I'll start prototyping so we make sure everything we need is in there.

This is the current spec for spans:
https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92

**Comment by richardpark-msft** [comment]
Some questions we want to make sure we can answer from this:
- What underlying pieces of the operation happened that might have made it take longer (ie: was this call the one that initialized the connection, are management$ links slow to start up, etc..)
- Retries occurring?
