### ISSUE TITLE
Queue Storage not usable when connecting with SAS token

### ISSUE THREAD

**Issue by nfoerster** [Azure/azure-sdk-for-go#15701]
We are trying to connect the queues of our storage account in Azure. For the connection we want to use a SAS token generated with the Azure UI. However, when we try to publish a test message, we get `http: read on closed response body`. After debugging we recognized that the internal HTTP response was not correctly returned to the application: `Status: "403 Server failed to authenticate the request. Make sure the val...+71 more"`

We had a look in the client implementation and struggled, why the GetQueueService, and also the other Getter for Table/Blob/File set the auth to sharedkey `f.auth = sharedKey`, although we use a SAS token.

Import path: "github.com/Azure/azure-sdk-for-go/storage"
SDK version: v58.0.0+incompatible
Go version: 1.17.1

Code to reproduce:
```
func TestAzqueueSAS(t *testing.T) {
	endpoint := "Your queue endpoint"
	sasToken := "Your SAS token"
	log.Printf("endpoint:%v", endpoint)
	log.Printf("sas:%v", sasToken)

	cli, err := storage.NewAccountSASClientFromEndpointToken(endpoint, sasToken)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	qsc := cli.GetQueueService()
	if err != nil {
		t.Error(err)
		t.FailNow()
	}

	queue := qsc.GetQueueReference("testqueue")

	eqx, err := queue.Exists()
	if err != nil {
		t.Error(err)
		t.FailNow()
	}

	if !eqx {
		err := queue.Create(&storage.QueueServiceOptions{
			Timeout: 30,
		})
		if err != nil {
			t.Error(err)
			t.FailNow()
		}
	}
	msg := queue.GetMessageReference("this is a message")
	err = msg.Put(&storage.PutMessageOptions{
		Timeout:           30,
		VisibilityTimeout: 5,
		MessageTTL:        -1,
	})
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
}
```

**Comment by jhendrixMSFT** [comment]
Hello!

Per our [README](https://github.com/Azure/azure-sdk-for-go/tree/main/storage), the storage package has been replaced with other packages.  For queues, please have a look the [`azqueue`](https://github.com/Azure/azure-storage-queue-go) module which has support for SAS authentication.

**Comment by nfoerster** [comment]
> Hello!
> 
> Per our [README](https://github.com/Azure/azure-sdk-for-go/tree/main/storage), the storage package has been replaced with other packages. For queues, please have a look the [`azqueue`](https://github.com/Azure/azure-storage-queue-go) module which has support for SAS authentication.

The package is outdated from 2019, I suggest to add full SAS support to this package.
