### ISSUE TITLE
API version '2021-01-25' for type 'guestConfigurationAssignments' does not support location 'eastus'

### ISSUE THREAD

**Issue by bigdatasourav** [Azure/azure-sdk-for-go#15702]
### Bug Report

- import path of package in question - `.github.com/Azure/azure-sdk-for-go/services/guestconfiguration/mgmt/2021-01-25/guestconfiguration`
- SDK version `latest` - 58.0.0
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- Error: guestconfiguration.AssignmentsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'eastus' and API version '2021-01-25' for type 'guestConfigurationAssignments'. The supported api-versions are '2018-01-20-preview, 2018-06-30-preview, 2018-11-20, 2020-06-25'. The supported locations are ''."

- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by lirenhe** [comment]
@bigdatasourav, could you use the api version of 2020-06-25 to workaround this issue?
