### ISSUE TITLE
[azservicebus] Processor design discussion

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15733]
# Design considerations/differences for the azservicebus Go SDK

There are some idioms and design decisions I'd like to discuss, to make sure we understand and agree that these differences are idiomatic and that they make sense overall.

### Background

The `Processor` type in our messaging SDKs is intended to be a simple "forever listener" consumer for messages. You register callbacks (one for receiving messages, one for receiving errors), start it, and then leave it running for the duration of your application.

This meshes well with the general nature of AMQP - requests for new messages (via credits) happen at any time, responses can happen at any time (up to the amount of active credits, which is constantly modified) and errors can also be reflected at any time. 

### Differences

In the .NET Processor, the `Start` method is asynchronous. 

In Go, similar APIs are not asynchronous by default (consider: `http.ListenAndServe`). This suggests two things:
- The `Start` function should block. Customers can "bring their own asynchrony" but just using a goroutine.
- The `Start` method might be better named to something more Go-ish:
  - `Subscribe`?
  - `Listen`?

For some context, the `Client`, which is basically the factory for all of these types, will eventually have an `AcceptSession` and `AcceptNextSession` function. They're not directly related to this type, however.

## Processor settlement method location

(Question for @JoshLove-msft, @jsquire, @conniey (Processor in Java))

Messages in Service Bus (when received in `PeekLock`, the default receive mode) need to be settled by the client. 

In .NET these settlement methods, for a `Processor`, are located on an argument passed into the user's callback:

```csharp
async Task MessageHandler(ProcessMessageEventArgs processMessageEventArgs)
{
 string body = processMessageEventArgs.Message.Body.ToString();
 Console.WriteLine(body);

 await processMessageEventArgs.CompleteMessageAsync(processMessageEventArgs.Message);
}

// start processing
processor.ProcessMessageAsync += MessageHandler;
await processor.StartProcessingAsync();
```

In Go I've put these settlement functions on the `Processor` itself:

```go
processor := client.NewProcessorForQueue()

handleMessage := func(message *azservicebus.ReceivedMessage) error {
  processor.CompleteMessage(ctx, message)
}

err = processor.Start(context.TODO(), handleMessage, handleError)
```

This follows the same rules as the `Receiver` type (both in Go _and_ .NET)

```csharp
ServiceBusReceivedMessage receivedMessage = await receiver.ReceiveMessageAsync();
await receiver.CompleteMessageAsync(receivedMessage);
```

```go
message, err = receiver.ReceiveMessage(context.TODO())
err = receiver.CompleteMessage(context.TODO(), message)
```

## Invert of autocomplete name

The `Processor` has a mode (`AutoComplete`) which makes it so messages can be automatically completed if the user's callback was successful (ie, no exceptions (C#), error is nil (Go)) or abandoned if errors occur.

In Go, I've changed the name of this flag from AutoComplete to ManualComplete, to make this pattern work:

```go
// ie, the 'zero' value of everything in there matches the defaults (or is obviously a zero value)
client.NewProcessorForQueue("queue", nil)

// and
client.NewProcessorForQueue("queue", &azservicebus.ProcessorOptions{
   ReceiveMode: azservicebus.PeekLock,
   // note I omitted the ManualComplete because I'm not interested in changing it.
})
```

Another option, to preserve the name, is to change the flag to be a pointer to bool instead, which is slightly annoying if you're changing it but we believe leaving it at a default is the common case:

```go
client.NewProcessorForQueue("queue", &azservicebus.ProcessorOptions{
   ReceiveMode: azservicebus.PeekLock,
   // enabled by default
   AutoComplete: nil
   // or to disable it
   AutoComplete: to.BoolPtr(false),   // `to` comes from `azcore/to`
})
```

**Comment by JeffreyRichter** [comment]
Set up a meeting to discuss this.

**Comment by richardpark-msft** [comment]
Closing this as we've arrived on a design that we like and are trying it out in the azeventhubs@v0.1.1.
