### ISSUE TITLE
[azservicebus] Automatic lock renewal in the processor

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15745]
The Processor should automatically renew locks for callers. This renewal happens in the background once a message has been received, and continues until the user settles the message.

As part of this there should also be a RenewLock call available on the Processor.

**Comment by richardpark-msft** [comment]
@marstr had a feature request in the original azure-service-bus-go repo covering this, but as a separate utility:

https://github.com/Azure/azure-service-bus-go/issues/68

We might want to consider breaking out that feature from the processor.

**Comment by googol** [comment]
Hi, how are your plans for implementing this looking at the moment? Is this on the roadmap?

This would be a really appreciated feature

**Comment by googol** [comment]
Gotcha. We've gone with our own renewal goroutine for now and it's not terribly difficult to do so. 

Of course a built-in solution would be preferrable, and in the meantime a documented example that covers some of the possible pitfalls would be nice so

**Comment by richardpark-msft** [comment]
@googol , filed an issue to write that example. Thanks for the feedback!
