### ISSUE TITLE
ServiceBus code coverage improvements

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#15756]

**Comment by richardpark-msft** [comment]
Hey @RickWinter, do you remember what we specifically wanted for this? Was it to meet a particular bar/percentage of coverage?

**Comment by RickWinter** [comment]
It was to ensure we reviewed coverage and pushed the block coverage over 90.

**Comment by RickWinter** [comment]
@richardpark-msft Lets time box this effort, drive the numbers up, and resolve the issue.
