### ISSUE TITLE
Azure AD Graph is being deprecated

### ISSUE THREAD

**Issue by jon-rosado-sp** [Azure/azure-sdk-for-go#15769]
It looks like the [Azure AD Graph is being deprecated](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview) in favor of Microsoft Graph. Since `"github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac"` references `graph.windows.net`, does the team currently have plans to migrate?

**Comment by lirenhe** [comment]
Azure AD Graph API is now deprecated. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
