### ISSUE TITLE
Release Request For KeyVault 2021-04-01-preview

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/azure-sdk-for-go#15776]
Since terraform-provider-azurerm is using KeyVault api version 2020-04-01-preview, and a new feature requests invoking api in [keys.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2021-06-01-preview/keys.json) and [managedHsm.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2021-06-01-preview/managedHsm.json), would you please add these two apis to go sdk, with both `2020-04-01-preview` and latest versions? Thanks a lot!

**Comment by 804873052** [comment]
Hi @lonegunmanb thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by Alancere** [comment]
released: https://github.com/Azure/azure-sdk-for-go/tree/legacy/services/preview/keyvault/mgmt/2021-11-01-preview

We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html)(see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)).Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md).If you could still repo this problem, please submit a support ticket in Azure directly.
