### ISSUE TITLE
Release request for `keyvault/data-plane/v7.2` 

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-sdk-for-go#15787]
### Service Package Request

I would like the [KeyVault Dataplan SDK v7.2](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.2) to be released, as it contains fixes for [this `azurerm` issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/13706) regarding Octet keys.

**Comment by jhendrixMSFT** [comment]
Hello!

We are in the process of releasing an updated SDK.  As such, we are not releasing any new data-plane packages that use the soon-to-be-legacy model (i.e. content under `/services`).

We have a new [`azsecrets`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets) for key vault available, and `azkeys` is in progress (https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets).

Please ping back if you have further questions.

**Comment by jhendrixMSFT** [comment]
We have new key-vault SDKs based on the 7.2 API set (soon to be updated to 7.3).  Can you please give them a try?

https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/keyvault
