### ISSUE TITLE
The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'

### ISSUE THREAD

**Issue by KuljitAthwal** [Azure/azure-sdk-for-go#15798]
### Bug Report

- Impacted Package : github.com/Azure/azure-sdk-for-go/services/costmanagement/mgmt/2020-06-01/costmanagement
- SDK version `master` 
- go version go1.16.3 windows/amd64

- What happened?

Hi there. I'm using the costmanagement library but when attempting to get Usage I get the following error back

> costmanagement.QueryClient#Usage: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="InvalidResourceType" Message="The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'. The supported api-versions are '2018-05-31,2018-08-31,2018-08-01-preview,2018-10-01-preview,2018-12-01-preview,2019-01-01,2019-03-01-preview,2019-04-01-preview,2019-05-01-preview,2019-10-01,2019-11-01,2021-10-01'."

I'd like to use the most recent recommended one, however when looking at the branch in github there appears to be no such 2021-10-01 version for that package

Is this a case of the SDK being behind the REST API? I see that 2021-10-01 is very recent.

Thank you.

**Comment by lirenhe** [comment]
@KuljitAthwal, as we provided the API version of https://github.com/Azure/azure-sdk-for-go/tree/main/services/costmanagement/mgmt/2019-11-01/costmanagement, could you try that to check whether it could solve your problem?
