### ISSUE TITLE
[design] Representing ISO8601 durations in Go

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15799]
## Conclusion

Durations are a bit tricky to represent properly and in a loss-less way if we use time.Duration. To avoid this potential loss we will leave the durations as strings for now (ISO formatted, as they are).

## Previous discussion

Some services (ex: Service Bus's ATOM API) specify durations using an ISO8601 duration (ex: PT10M). 

In .NET code this is typically deserialized using the built-in TimeSpan type, which has led to some leakage of details from TimeSpan in the API. In particular a few fields use the value of TimeSpan.Max as their "infinite" parameter. This value exceeds what we can store in Go's time.Duration type (which can "only" go up to 292 years).

Our other challenge is that we can make some decisions when we have a good idea of the domain (ie, this is just Service Bus and so only used a particular way with a particular max) but this can't be done so in an automated way for _every_ library. This could lead to a disjoint experience for customers when they transition between various auto-generated packages, like ARM, and back to our hand-crafted SDKs.

So here's some things we can consider:

## Let robots be robots, and humans be humans

We can make different decisions for automatically generated libraries vs hand-crafted libraries. This does let us provide a more natural representation of values to humans, who would probably prefer to work with time.Duration rather than having to format and parse ISO8601 duration strings.

Interop means there are some challenges here. If we need to represent TimeSpan.Max then we need to provide a convention to do so. 

Currently in Service Bus we're basically saying that:

For input:
< time.Duration max : use the actual value
== time.Duration max : treat as equivalent to TimeSpan.Max ISO8601 string

For output:
< time.Duration max: use the actual value
== time.Duration max : assume TimeSpan.Max ISO8601 string

This interops well enough in that reasonable values work properly and our 'max time duration' value still functions properly to represent the 'unbounded' value that Service Bus expects.

The downsides here are that this approach must be applied with complete knowledge of the domain, which we don't encode anywhere except in our heads.

## Use ISO8601 duration strings

This approach says we just stay out of the way. We use the value the service expects (ISO strings) and don't attempt to convert them. 

From a customer perspective this might be okay. If they ever do actually want to increment, compare or otherwise do something intelligent with the value it's not as useful and will require a 3rd party dependency. We could try to alleviate this by providing some helper functions, which would have to be written from scratch.

## Create our own custom "duration" type

This would essentially be "TimeSpan for Go". This would obviously be the most complete solution, but would deviate from our goal of trying to be idiomatic to the language. 

It might also have limited utility if nobody is actually using the values above time.Duration's max (ie, the "very large" values are just sentinel values).

**Comment by jhendrixMSFT** [comment]
I will point out that for generated code, we decided to _not_ parse the duration and simply return it as a string.  So, if we decided that's good enough for our generated SDKs, presumably it's good enough for SB too?

**Comment by richardpark-msft** [comment]
I could do that, it'd be good to be consistent. 

There is a special value in SB where the TimeSpan.Max value actually means something special to the portal so it might be that I need to define something there to indicate "NEVER", basically. I don't think I can use 'nil' since that would (in some contexts) mean "don't update/change this value".

**Comment by richardpark-msft** [comment]
@jhendrixMSFT, @JeffreyRichter - also, I've updated the issue description with our conclusion. Let me know if it's inaccurate.

**Comment by jhendrixMSFT** [comment]
To play devil's advocate, I get that there is value in being able to accept/receive the values in `time.Duration` format (one of the benefits of an SDK after all).  If we think we can reliably parse this across all our SDKs I think it's a net win for the customer.

**Comment by richardpark-msft** [comment]
> If we think we can reliably parse this across all our SDKs 

Parsing it is doable (to a time.Duration) but it's not lossless. Ie, PT1M (ie: 1 month) is not always equal to PT30D, depending on the month. Given our proximity to shipping at this point it's probably fine to leave it as a string and, if need be, add in some helpers at a later time to work with them.The lossy problem makes me think that doing this would require a custom type, not just "string <-> time.Duration".

**Comment by JeffreyRichter** [comment]
We should not parse this

**Comment by jhendrixMSFT** [comment]
We'll leave durations in string format.
