### ISSUE TITLE
Support Tags on App Service Environments (Reopen #15631)

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#15805]
As requested [in this comment](https://github.com/Azure/azure-sdk-for-go/issues/15631#issuecomment-942106445) since this is a feature request for the Service Team can this be reopened?

Thanks.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
