### ISSUE TITLE
New releases of v10.X

### ISSUE THREAD

**Issue by feiskyer** [Azure/azure-sdk-for-go#1586]
I'm trying to fix a issue in kubernetes v1.8 (refer https://github.com/kubernetes/kubernetes/pull/62249 and https://github.com/Azure/AKS/issues/199). It requires an update to Azure SDK. k8s 1.8 vendors Azure SDK v10.0, but all versions of v10.X don't include `SourceAddressPrefixes` in LoadBalancer model.

If we update the SDK to a later version (e.g. v11), many files would be updated, e.g. 18,687 lines of code add and −3,045 lines of code removes across 147 files in ttps://github.com/kubernetes/kubernetes/pull/62249.

Could we cut a new v10 release with `SourceAddressPrefixes` fixed?

**Comment by jhendrixMSFT** [comment]
Please note that v10 is a beta release.  Our first GA release is v14 so if you're to move to a new version it's highly recommended that you move to that one.

**Comment by feiskyer** [comment]
@jhendrixMSFT Kubernetes v1.8 has been using v10 for a long time. Could we release a new v10 release of kubernetes v1.8 only?

**Comment by feiskyer** [comment]
@jhendrixMSFT kubernetes v1.8 is using SDK v10 only v1.8.X is using this SDK version. Newer kubernetes releases have already upgraded in their vendors.

**Comment by feiskyer** [comment]
@jhendrixMSFT thanks

**Comment by feiskyer** [comment]
This is not required now, we will document this as a known issue for kubernetes v1.8.X.
