### ISSUE TITLE
Not able to get group members

### ISSUE THREAD

**Issue by giampierod** [Azure/azure-sdk-for-go#1587]
No matter what path I take, I cannot use the graphrbac to go from the current user logged in to the groups they are a member of. I have tried both of the following and the result is always nil. The user I am testing with is a member of 3 groups.

 ```golang
// Get the current users object ID
token, _ := getDeviceToken(cliID, tenantID)
objClient := graphrbac.NewObjectsClient(tenantID)
objClient.Authorizer = autorest.NewBearerAuthorizer(token)
usrobj, _ := objClient.GetCurrentUser(context.TODO())

// Approach 1: Use the GroupsClient.Get function to get the ADGroup object from the user
grpClient := graphrbac.NewGroupsClient(tenantID)
grpClient.Authorizer = autorest.NewBearerAuthorizer(token)
group, _ := grpClient.Get(context.TODO(), *usrobj.ObjectID)
fmt.Println(group)

// RESULT: {{0xc42039c2d0} <nil> <nil> <nil> map[] <nil> <nil> }

// Approach 2: Use the UsersClient.GetMemberGroups function to get the UserGetMemberGroupsResult object
usrClient := graphrbac.NewUsersClient(tenantID)
usrClient.Authorizer = autorest.NewBearerAuthorizer(token)
parm := graphrbac.UserGetMemberGroupsParameters{}
groups, _ := usrClient.GetMemberGroups(context.TODO(), *usrobj.ObjectID, parm)
fmt.Println(groups.Value)

// RESULT: <nil>
```

Given the lack of documentation around this particular thing, I assumed one of these would work.

**Comment by giampierod** [comment]
No dice

graphrbac.GroupsClient#IsMemberOf: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error"

**Comment by mcardosos** [comment]
That is an authentication issue. Verify the logged in user has enough permissions to do that operation.

**Comment by giampierod** [comment]
The user logging in is checking that they are a member of a group. What am I missing?

**Comment by mcardosos** [comment]
The application might not have enough permissions.
[Dcoumentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications)

**Comment by jhendrixMSFT** [comment]
@joshgav Is there somebody from the RBAC team we can loop in?

**Comment by jhendrixMSFT** [comment]
@jillcary I found your alias in the specs repo, is this something you can help with?

**Comment by jillcary** [comment]
Hello, are you referring to the PR for adding User Roles to the sdk [here](https://github.com/Azure/azure-rest-api-specs/pull/3165)? 
I am working on the [CLI for the Azure IoT Remote Monitoring Accelerator](https://github.com/Azure/pcs-cli) and we found that User Roles were missing from the current API.

**Comment by jhendrixMSFT** [comment]
@giampierod sorry for the delay, still trying to find an answer.  Regarding permissions have you seen [this](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_getmembergroups)?

**Comment by tariq1890** [comment]
Hi @jhendrixMSFT. On a similar note, can we get an error that conveys more information. Unknown service error is not that helpful :(.

**Comment by jhendrixMSFT** [comment]
@tariq1890 this should be somewhat fixed in v10.11.3 of go-autorest.  There is a larger work item here though, I've opened https://github.com/Azure/azure-sdk-for-go/issues/2201 to track it.

**Comment by tariq1890** [comment]
Thanks for your response, @jhendrixMSFT . I am assuming the Azure samples point to the latest version of go-autorest? 

https://github.com/azure-samples/azure-sdk-for-go-samples

I get the same unknown service error when I try out the graphrbac API calls.

**Comment by jhendrixMSFT** [comment]
The sample is using v10.11.2 which doesn't contain this fix.

**Comment by tariq1890** [comment]
My bad. Thanks for clarifying :).

**Comment by jhendrixMSFT** [comment]
I have not been able to find a solution to the original issue here.  :(  If this is still an issue please re-open.
