### ISSUE TITLE
Backlog?

### ISSUE THREAD

**Issue by rprakashg** [Azure/azure-sdk-for-go#159]
I was wondering if there is a prioritized backlog for this that I can take a look at to see what features are being worked on or planned?
I don't want to start something when someone else is already working on it

Thanks,
</Ram>

**Comment by paulmey** [comment]
All items that are worked on are supposed to be in issues. If they are really small, they might just be a pull request only, but usually, when we notice a gaping hole, we create an issue... :wink:

**Comment by ahmetalpbalkan** [comment]
@rprakashg thanks for asking, generally they are as Issues under the [`help-wanted`](https://github.com/Azure/azure-sdk-for-go/labels/help%20wanted) tag.
