### ISSUE TITLE
Release request for `FrontDoor/stable/2020-11-01`

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-sdk-for-go#15914]
### Service Package Request

Terraform provider for Azure `azurerm` needs a release of `FrontDoor/stable/2020-11-01` for [new sku's in the Azure FrontDoor Policy](https://github.com/hashicorp/terraform-provider-azurerm/issues/13836).

REST API docs: https://docs.microsoft.com/en-us/rest/api/frontdoorservice/webapplicationfirewall/policies/create-or-update#skuname
REST API specs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/frontdoor/resource-manager/Microsoft.Network/stable/2020-11-01

**Comment by t-bzhan** [comment]
Released: https://github.com/Azure/azure-sdk-for-go/releases/tag/v60.3.0
