### ISSUE TITLE
Ability to batch Rest API requests using the GO SDK

### ISSUE THREAD

**Issue by KuljitAthwal** [Azure/azure-sdk-for-go#15957]
### Feature Request

When using the Azure portal, it is possible to see many requests being sent inside a request array, normally a single request. Looking at C# and TypeScript SDKs it is possible to submit batch requests to the Azure REST API. Is this also possible in the Go SDK? I do not see any documentation around this there. Is this potentially a new feature request for the Go Azure SDK?

To be clear this isn't about the Azure Batch Service. Rather the ability to submit batched REST API requests to the Azure API

**Comment by RickWinter** [comment]
@KuljitAthwal Thank you for using the Go SDK.  Can you please provide links to the feature in C# and TS SDKs.

**Comment by djdongjin** [comment]
Hi @RickWinter ,

We are also investigating this feature. While checking the traffic in azure portal, we found that vmss uses some of the batch operations to complete some tasks (e.g., stop multiple vms, etc). The traffic and URL is shown as below:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/28295179/154368282-e49a25a2-d48f-4845-9906-1bda30508e8b.png">

The request body is a json that contains all requests within this batch.

Do you know where I can find any document about this API endpoint (`https://management.azure.com/batch?...`)

**Comment by djdongjin** [comment]
The same issue can also be found in the python sdk repo, which has more context.

https://github.com/Azure/azure-sdk-for-python/issues/9271
