### ISSUE TITLE
enable consumption of OpenCensus events in App Insights

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1596]

**Comment by joshgav** [comment]
in discussion with App Insights team about who will do this work

**Comment by funkeyfreak** [comment]
Hey @joshgav, what is the status of this task?

**Comment by joshgav** [comment]
Hi @funkeyfreak, we will be adding [Open Census](https://opencensus.io) support to App Insights in the future as announced [here](https://open.microsoft.com/2018/06/13/microsoft-joins-the-opencensus-project/), but we won't be adding OpenTracing. I'll update the title accordingly.

cc @nikmd23 in case you have further feedback or questions on these plans. Thanks!

**Comment by nikmd23** [comment]
You've got it covered @joshgav. Look for more support of OpenCensus coming soon.

**Comment by jhendrixMSFT** [comment]
resolved via github.com/microsoft/applicationinsights-localforwarder
