### ISSUE TITLE
Unmarshalling error on `Microsoft.DocumentDB/sqlRoleAssignments` (cosmos-db/mgmt/2021-06-15/documentdb)

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-sdk-for-go#15968]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2021-06-15/documentdb`
- SDK version: `v58.0.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- `go version`: `go version go1.16.6 darwin/amd64`

- What happened?
An error showed up when listing CosmosDB SQL Role Definitions:
```
        Error: loading Role Definition List: documentdb.SQLResourcesClient#ListSQLRoleDefinitions: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field SQLRoleDefinitionListResult.value of type documentdb.RoleDefinitionType' JSON = '
{
    "value": [
        {
            "id": "/subscriptions/<subscriptionId>/resourceGroups/acctestRG-cosmos-211028094631848319/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-211028094631848319/sqlRoleDefinitions/00000000-0000-0000-0000-000000000001",
            "name": "00000000-0000-0000-0000-000000000001",
            "properties": {
                "roleName": "Cosmos DB Built-in Data Reader",
                "type": 0,
                "assignableScopes": [
                    "/subscriptions/<subscriptionId>/resourceGroups/acctestRG-cosmos-211028094631848319/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-211028094631848319"
                ],
                "permissions": [
                    {
                        "dataActions": [
                            "Microsoft.DocumentDB/databaseAccounts/readMetadata",
                            "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery",
                            "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readChangeFeed",
                            "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/read"
                        ],
                        "notDataActions": []
                    }
                ]
            },
            "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions"
        },
        {
            "id": "/subscriptions/<subscriptionId>/resourceGroups/acctestRG-cosmos-211028094631848319/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-211028094631848319/sqlRoleDefinitions/00000000-0000-0000-0000-000000000002",
            "name": "00000000-0000-0000-0000-000000000002",
            "properties": {
                "roleName": "Cosmos DB Built-in Data Contributor",
                "type": 0,
                "assignableScopes": [
                    "/subscriptions/<subscriptionId>/resourceGroups/acctestRG-cosmos-211028094631848319/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-211028094631848319"
                ],
                "permissions": [
                    {
                        "dataActions": [
                            "Microsoft.DocumentDB/databaseAccounts/readMetadata",
                            "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/*",
                            "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/*"
                        ],
                        "notDataActions": []
                    }
                ]
            },
            "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions"
        }
    ]
}
'
```
- What did you expect or want to happen?
Unmarshalling to work fine. I'm not sure how to escalate this in the right way or if this is the right repository, but it makes implementation of [Role Assignments for CosmosDB in Terraform](https://github.com/hashicorp/terraform-provider-azurerm/issues/13907) impossible.
- How can we reproduce it?
Run `go install && make acctests SERVICE='cosmos' TESTARGS='-run=TestAccCosmosDBRoleAssignment_basic'` on forked branch of `azurerm`
https://github.com/aristosvo/terraform-provider-azurerm/tree/cosmosdb/rbac-role-assignment
- Anything we should know about your environment.
- Related to:
  - https://github.com/Azure/azure-rest-api-specs/issues/16560

**Comment by lirenhe** [comment]
@aristosvo, as I know, there are some API change in the latest API version, could you use 2021-10-15 to have a try?

**Comment by aristosvo** [comment]
Hi @lirenhe! Thanks for picking this up.

I tried it already, https://github.com/Azure/azure-rest-api-specs/issues/16560#issuecomment-953937851. Unfortunately this didn't solve the problem.

The problem is that the backend is returning numbers (which probably relate to enum values). This is therefore not solvable here tbh.

If you'd be able to promote [that issue](https://github.com/Azure/azure-rest-api-specs/issues/16560) internally it would be really appreciated 👌

**Comment by lirenhe** [comment]
thanks @aristosvo for the clarification. Yes, this seems to be a Swagger issue instead of GO SDK problem.  So let's use https://github.com/Azure/azure-rest-api-specs/issues/16560 to track the progress.   Close this one.
