### ISSUE TITLE
IoT Hub Device API

### ISSUE THREAD

**Issue by rojer** [Azure/azure-sdk-for-go#1603]
I would like to be able to manage IoT devices - add, remove them and invoke Device Methods.
Currently the SDK only contains IoT hub management APIs.
I found that for other languages there are separate SDKs for IoT, listed [here](https://github.com/Azure/azure-iot-sdks). Should we expect one for Go as well?

**Comment by jhendrixMSFT** [comment]
Hi @rojer, I don't know what our story is for this at present.  I'll work with @joshgav to get this figured out.

**Comment by joshgav** [comment]
@jseely @pierreca can you respond?

**Comment by pierreca** [comment]
@rojer thanks for chiming in. The IoT SDK is looking into Golang support right now (among other things) but we don't have anything ready as we're still figuring out how to balance resources to effectively support a new language. 

I understand you'd need CRUD operation on devices, and Invoke Device Methods - anything else? Also, if you can share this information, when would do you intend to go to production with these APIs?

**Comment by rojer** [comment]
@pierreca thanks for your response. in addition to invoking device methods i would like to be able to send and receive device messages.

as for going to production - well, i sort of already have :) except at the moment i shell out to the `az` utility for management and rolled my own implementation of of direct message client over HTTPS, SAS token and all. however, az is kinda slow and is also an additional external dependency for us which users have to install, so as soon as SDK becomes available i'd change to using that instead.

**Comment by pierreca** [comment]
Understood, thanks for the details! @joshgav not sure if/how you want to track this in your repository or close the issue. I can come back and comment here when we have something (it'll be a few weeks I guess)

@rojer if you want a good place to gather steam and maybe follow up on our progress, I would very much encourage you to post the idea for a Go SDK [on our user-voice page](https://feedback.azure.com/forums/321918-azure-iot)

**Comment by rojer** [comment]
https://feedback.azure.com/forums/321918-azure-iot/suggestions/32822650-go-sdk-for-azure-iot

upvoted.

ok, i'll close this issue then. hopefully we'll see Go SDK for IoT someday!
