### ISSUE TITLE
Using continuation token to retrieve records from Azure Storage Table fails with status 415 Unsupported Media Type and error.data.message contains AtomFormatNotSupported

### ISSUE THREAD

**Issue by alvaradojl** [Azure/azure-sdk-for-go#16041]
### Bug Report
 
- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
"github.com/Azure/azure-sdk-for-go/storage"

- SDK version 
github.com/Azure/azure-sdk-for-go v59.0.0
f92de54510280b0eba246b54113abcdbc65fc239

same behaviour with v52.5 as well.

- output of `go version`
go version go1.16 linux/amd64

 
- What happened?
Querying a table using the continuationToken provided in the first call fails.

- What did you expect or want to happen?
The table should return the records regardless if it's the first call (no continuationToken) or on subsequent calls (with continuationToken)

- How can we reproduce it?

```
func QueryTableByContinuationToken(azureStorageAccountName string, azureStorageAccountKey string, tableName string, continuationToken string) (*storage.EntityQueryResult, error) {

	table, err := getTableReference(azureStorageAccountName, azureStorageAccountKey, tableName)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get azure storage table reference")
	}

	result, err := table.QueryEntities(30, storage.FullMetadata, &storage.QueryOptions{Top: 0})
	if err != nil {
		return nil, errors.Wrap(err, "failed to query azure storage table")
	}

	result.QueryNextLink.NextLink = &continuationToken

	return result.NextResults(nil)
}
```

calling the previous method passing the continuationToken that looks like this:

`"https://<account>.table.core.windows.net/<table>?%24filter=PartitionKey+eq+%272021-11-01%27+and+Timestamp+le+datetime%272021-11-01T23%3A00%3A00Z%27&%24top=50&NextPartitionKey=1%2116%21MjAyMS0xMS0wMQ--&NextRowKey=1%2116%21MTY6MjI6NDEuMzk3&timeout=30"`

 returns a nil result with an error struct of type github.com/Azure/azure-sdk-for-go/storage.AzureStorageServiceError and the following content:

`{Code: "", Message: "Response body could no be unmarshaled: invalid character '<' looking for beginning of value. Body: <?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>AtomFormatNotSupported</code><message xml:lang=\"en-US\">Atom format is not supported.\nRequestId:8e2d22cb-e002-001b-3e54-cf3ce9000000\nTime:2021-11-01T19:16:39.5611825Z</message></error>.", AuthenticationErrorDetail: "", QueryParameterName: "", QueryParameterValue: "", Reason: "", Lang: "", StatusCode: 415, RequestID: "8e2d22cb-e002-001b-3e54-cf3ce9000000", Date: "Mon, 01 Nov 2021 19:16:39 GMT", APIVersion: "2018-03-28"}`

- Anything we should know about your environment.
Ubuntu 20.04

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

The tables functionality in the /storage package has been deprecated in favor of our new [`aztables`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables) module. Can you please try it and see if it resolves your issue?

**Comment by alvaradojl** [comment]
@jhendrixMSFT  thanks for the suggestion, 
I tried the new library but funny enough the question still remains, how to pass the continuation token?
below an example:

	```
table, err := getTableReference(azureStorageAccountName, azureStorageAccountKey, tableName)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get azure storage table reference")
	}

	untilString := until.Format("2006-01-02T15:04:05Z")

	var filter = fmt.Sprintf("PartitionKey eq '%s' and Modified le datetime'%s'", partitionKey, untilString)

	options := &aztables.ListEntitiesOptions{
		Filter: &filter,
		Top:    to.Int32Ptr(15),
	}

	//how to pass the continuation tokens before the call happens?
		// x.ContinuationNextPartitionKey = &continuationNextPartitionKey
	// 	x.ContinuationNextRowKey = &continuationNextRowKey

	result := table.List(options)

	return result, nil
```

I couldn't see any option in the code to pass the continuationtokens **before** the call happens, 
which means I can only either "query all entities" or query the first page.
I cannot use the continuationTokens returned

Do you have an example code how to do that?

**Comment by jhendrixMSFT** [comment]
@seankane-msft do you have an example of how to do this?

**Comment by seankane-msft** [comment]
Hi @alvaradojl, the current SDK does not have this functionality. I've added it in #16087 and after our team reviews will probably be able to release this on Tuesday. If this doesn't address your needs please let me know.

**Comment by alvaradojl** [comment]
@seankane-msft  thanks a lot, yes, those were the parameters I was looking for, thanks a lot!
May I also suggest to include documentation in the README ? It seems to me a pretty frequent use case.
Also I found the [Create the client documentation](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/data/aztables#create-the-client) is incorrect,
the documentation shows this:

```
cred, err := aztables.NewSharedKeyCredential("myAccountName", "myAccountKey")
handle(err)
serviceClient, err := aztables.NewServiceClient("https://<myAccountName>.table.core.windows.net/", cred, nil)
handle(err)
```

when it should be this:

```
cred, err := aztables.NewSharedKeyCredential("myAccountName", "myAccountKey") 
handle(err)
serviceClient, err := aztables.NewServiceClientWithSharedKey("https://<myAccountName>.table.core.windows.net/", cred, nil)
handle(err)

```

Thanks a lot again for the quick feedback to both!

**Comment by seankane-msft** [comment]
I updated our documentation in #16102

**Comment by alvaradojl** [comment]
@seankane-msft really sorry for coming at this after you close the issue, 
unfortunately I'm still having issues:
using the following code:

```
//initialize the query options
options := &aztables.ListEntitiesOptions{
		Filter: &filter,
		Top:    to.Int32Ptr(3),
	}
//use continuation tokens if you got one
if continuationNextPartitionKey != "" || continuationNextRowKey != "" {
		options.PartitionKey = &continuationNextPartitionKey
		options.RowKey = &continuationNextRowKey
}

pager := table.List(options) //returns empty when using continuation tokens in options
for pager.NextPage(ctx) {
	resp := pager.PageResponse()
	fmt.Printf("\nraw response:\n%s\n", resp.RawResponse.Body)

	fmt.Printf("Received: %v entities\n", len(resp.Entities))
       ... more code
```

Could it be something else missing?

thanks again and sorry again for not testing before

**Comment by seankane-msft** [comment]
@alvaradojl can you give a fully working snippet? I don't know where/how you pull `continuationNextPartitionKey` or `continuationNextRowKey` and that could be the issue. If you'd like to see a sample, I have a test for this situation [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/aztables/client_test.go#L389-L423) that you should be able to mostly copy paste into your code for trial.

**Comment by alvaradojl** [comment]
@seankane-msft  so this is my snippet:

```
        var rows = []DataRow{}

	table, err := getTableReference(account, key, tableName)
	if err != nil {
		return rows, "", "", errors.Wrap(err, "failed to get azure storage table reference")
	}

	untilString := untilTime.Format("2006-01-02T15:04:05Z")

	var filter = fmt.Sprintf("PartitionKey eq '%s' and Modified le datetime'%s'", partitionKey, untilString)

	var pageSize int = 1

	options := &aztables.ListEntitiesOptions{
		Filter: &filter,
		Top:    to.Int32Ptr(int32(pageSize)),
	}

	if continuationNextPartitionKey != "" || continuationNextRowKey != "" { //values obtained from 1st request (1st page)
		options.PartitionKey = &continuationNextPartitionKey
		options.RowKey = &continuationNextRowKey
	}

	pager := table.List(options)

	var count int = 0

	for pager.NextPage(ctx) {

		page := pager.PageResponse()
		count += len(page.Entities)

		for _, entity := range page.Entities {
			var myEntity aztables.EDMEntity
			err = json.Unmarshal(entity, &myEntity)
			if err != nil {
				return rows, "", "", errors.Wrap(err, "unable to unmarshal entity")
			}
			rows = append(rows, DataRow{
				ID:       myEntity.RowKey,
				Payload:  fmt.Sprintf("%v", myEntity.Properties["Payload"]),
				Modified: fmt.Sprintf("%v", myEntity.Properties["Modified"]),
			})
		}

		if count >= pageSize {

			if pager.NextPagePartitionKey() != (*string)(nil) {
				continuationNextPartitionKey = *pager.NextPagePartitionKey()
			} else {
				continuationNextPartitionKey = ""
			}

			if pager.NextPageRowKey() != (*string)(nil) {
				continuationNextRowKey = *pager.NextPageRowKey()
			} else {
				continuationNextRowKey = ""
			}

			break
		}

	}

	err = pager.Err()
	if err != nil {
		return rows, "", "", errors.Wrap(err, "there was a pager error")
	}

	return rows, continuationNextPartitionKey, continuationNextRowKey, nil
```

The continuationTokens I get them from the first request (or first page) then I when I pass the same values to the second request, I get empty rows.

The difference with your test is that I'm always passing a filter (you were passing nil options but that would bring more rows than a UI can digest)

**Comment by seankane-msft** [comment]
I am having trouble re-producing your issue. I wrote another test for using filters you can see in [this PR](https://github.com/Azure/azure-sdk-for-go/pull/16138). My best guess for you is to make sure that there are more entities in the first pager before you give the second pager the continuation tokens. Do both pagers use the same filters?

**Comment by alvaradojl** [comment]
@seankane-msft you were absolutely right, the code is working fine, it was my own testing parameters that produced the error.  This issue has been solved, many thanks!
