### ISSUE TITLE
publish azure identity 0.12.0 for azcore alignment

### ISSUE THREAD

**Issue by baywet** [Azure/azure-sdk-for-go#16042]
### Bug Report

At time of writing:
[azcore 0.20.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore?tab=versions)
[azidentity 0.11.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity?tab=versions) -> azcore 0.19.0

This becomes an issue if you have a transitive dependency on azcore 0.20.0 and an direct dependency on azidentity 0.11.0 as it seems that azcore 0.20.0 breaks a bunch of APIs (see #15886).

Releasing azidentity 0.12.0 since the alignment work in the code is already done would solve the problem.

**Comment by chlowell** [comment]
azidentity 0.12.0, which requires azcore 0.20.0, is available now. There are a number of API changes, detailed in the [changelog](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/CHANGELOG.md), so you may need to update your code, depending on which credentials you use. Please open another issue if you find something that doesn't work.

**Comment by baywet** [comment]
Thanks for the quick turnaround on this one!
