### ISSUE TITLE
Can not get application domains from azure ad 

### ISSUE THREAD

**Issue by devtrap** [Azure/azure-sdk-for-go#16050]
I'm trying to get list of applications and application domains from azure active directory using azure-sdk-for-go.
The library which I used is : github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac

here is the code which I used for getting the list :
```
func (rcv ADApplication) List(cred Credentials) ([]ADApplication, error) {
	var (
		res    []ADApplication
		filter string
		err    error
	)
	logger.Info("create client for connecting to the azure.")
	cli := graphrbac.NewApplicationsClient(cred.TenantID)

	if cli.Authorizer, err = azureAD.Authorizer(cred.TenantID, cred.ClientID, cred.ClientSecret); err != nil {
		logger.Error("can not get authorizer for resources, err : ", err.Error())
		return nil, err
	}

	resList, err := cli.List(context.Background(), filter)
	if err != nil {
		logger.Error("can not get resources list , error : ", err.Error())
		return nil, err
	}
	for _, singleRes := range resList.Values() {
		res = append(res, ADApplication{
			URL:        *singleRes.AppLogoURL,
			Service:    *singleRes.DisplayName,
			ResourceId: *singleRes.ObjectID,
		})

	}

	return res, nil
}
```
But I'm not able to get the list ,because each time I want to get the list I faced with below error:
```
graphrbac.ApplicationsClient#List: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."}}}]
```

I checked the credentials and clientId access before and all is correct.
Would you please help me to solve this issue? kindly let me know if I'm using dedicated library or not .

Thanks

**Comment by devtrap** [comment]
Is there any update for this issue ?

**Comment by tadelesh** [comment]
@devtrap Could you help to provide the implementation of azureAD.Authorizer.

**Comment by devtrap** [comment]
@tadelesh Here is my Authorizer func :

```
func Authorizer(TenantId, ClientID, ClientSecret string) (autorest.Authorizer, error) {
	return auth.NewClientCredentialsConfig(ClientID, ClientSecret, TenantId).Authorizer()	
}
```

**Comment by devtrap** [comment]
Is there any update for this issue ?

**Comment by tadelesh** [comment]
@devtrap , you may try another authorizer as following as a workaround. As the Azure AD Graph API will [deprecated](https://github.com/azure-deprecation/dashboard/issues/60) soon, you can try to migrate to use Microsoft Graph API instead.
`package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/adal"
	"github.com/Azure/go-autorest/autorest/azure"
)

var (
	clientID     string
	clientSecret string
	tenantID     string
	cloudName    string = "AzurePublicCloud"
)

func main() {
	var (
		filter string
		err    error
	)

	cli := graphrbac.NewApplicationsClient(tenantID)

	env, err := azure.EnvironmentFromName(cloudName)
	if err != nil {
		fmt.Sprintf("invalid cloud name '%s' specified, cannot continue\n", cloudName)
	}

	oauthConfig, err := adal.NewOAuthConfig(env.ActiveDirectoryEndpoint, tenantID)
	if err != nil {
		fmt.Printf("can not get oauth config, err : %s", err.Error())
		return
	}

	token, err := adal.NewServicePrincipalToken(*oauthConfig, clientID, clientSecret, env.GraphEndpoint)
	if err != nil {
		fmt.Printf("can not get oauth token, err : %s", err.Error())
		return
	}

	cli.Authorizer = autorest.NewBearerAuthorizer(token)

	// if cli.Authorizer, err = auth.NewClientCredentialsConfig(clientID, clientSecret, tenantID).Authorizer(); err != nil {
	// 	fmt.Printf("can not get authorizer for resources, err : %s", err.Error())
	// 	return
	// }

	resList, err := cli.List(context.Background(), filter)
	if err != nil {
		fmt.Printf("can not get resources list , error : %s", err.Error())
		return
	}
	for _, singleRes := range resList.Values() {
		fmt.Printf("%v", singleRes)
	}
}
`

**Comment by devtrap** [comment]
@tadelesh


still not resolve 
error:

error : graphrbac.ApplicationsClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-11-24T16:49:55","message":{"lang":"en","value":"Insufficient privileges to complete the operation."}

**Comment by tadelesh** [comment]
@devtrap From the error message, it seems that you don't have proper permission in your token. You may check your client api permissions for azure ad from: Azure Portal > Azure Active Directory > App Registration > All Applications > Client ID > Api Permissions > Add a permission > Microsoft Graph > Delegated permissions.
