### ISSUE TITLE
[azservicebus] Release pipeline warns that there are no test results 

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#16072]
Noticed when doing releases:

##[warning]No test result files matching /mnt/vss/_work/1/go/src/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/**/report.xml were found.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1176982&view=results

**Comment by benbp** [comment]
This should be resolved by https://github.com/Azure/azure-sdk-for-go/pull/15583 (see my [comment](https://github.com/Azure/azure-sdk-for-go/pull/15583#issuecomment-960091219)).
