### ISSUE TITLE
Input validation functions for specific parameter sets.

### ISSUE THREAD

**Issue by aznashwan** [Azure/azure-sdk-for-go#161]
The way strings are used for some options which have a finite set of possible inputs (ex: storage service types), makes it very inconvenient for people writing software that takes input directly from users.

I propose the implementation of functions which either take individual configuration options (ex: storageservice.ValidateAccountType), or for the whole structs used for passing parameters to the various CRUD functions already implemented (ex: storageservice.ValidateStorageServiceCreateParameters).

I'd be more than glad to do it myself (as I've already inlined most of it in my project before deciding people might need these and try and get them into the sdk).

Only points I'd like discussed more thoroughly is:
  * should validation be preffered per option, or per configuration set (see above storage service type example)?
  * should they be put in their own package (ex: azure-sdk-for-go/validation), or put in their respective packages?
  * should it be preferred to make API calls for getting the reference values (ex: location.ListLocations() and use that as the baseline), or have the values "hard-coded", as it were, in the functions themselves?

**Comment by ahmetalpbalkan** [comment]
@aznashwan thanks for the suggestion. My question is what do you mean for "validation"? (e.g. is it a check for required parameters, input format of certain fields etc?)

**Comment by aznashwan** [comment]
Most prevalent example are all the string configuration options scattered around the various resources.
By validation; I mean a way to be ensure that the inputs are valid (prefferably even without making API calls at all).
ex:
```go
func isValidProtocol(protocol string) bool {
     validProtocols := map[string]bool {
         "TCP": true,
         "UDP": true,
         "*": true,
     }
    return validProtocols[protocol] 
}
```

This can be applied further to a bunch of of other things (ex: given hosted service name contains disallowed characters, given disk size is preposterous etc...)

**Comment by ahmetalpbalkan** [comment]
@aznashwan unfortunately we consciously removed those checks from the client and we don't want to have those. Here are the reasons:

1. We think client library should be dumb enough and not be aware of the server's logic.
2. Adding validation to the client “duplicates” the functionality. (e.g. in both cases, we return an error anyway)
3. Having such logic at the client makes it possible to easily go “out of sync” (e.g. max chars for hosted service name can be increased on the API but client would require update to support it).

**Comment by aznashwan** [comment]
All very fair points indeed; some of them having crossed my mind as well.
