### ISSUE TITLE
Add an `ErrorCode()` method to azcore.HTTPResponse

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-for-go#16108]
### Feature Request

The [Azure API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#handling-errors) require that all error responses should contain an `error` object that contains a string `code` and string `message` fields.  The `code` field is what we want customers to use when checking for specific errors; the `message` field is just an English description of `code` but is not part of the "API contract".

To make it easier for users to find the error code, there should be a method on `azcore.HTTPResponse` extracts the code from the response body (or from the `x-ms-error-code` header if it is available). This logic will be a bit complicated and we don't want to force users to have to write it themselves (leading to 1000s of implementations).

When the response does not contain a `code` field (contrary to the guidelines, but certainly happens), the method should simply return an empty string.

This method will enable an error checking pattern like
```
	_, err := container.Create(ctx, nil)
	var responseErr azcore.HTTPResponse
	if errors.as(err, &responseErr) {
		if responseErr.ErrorCode() == "ContainerAlreadyExists") {
			// Ignore - the container exists so processing can continue
		} else {
			fmt.Printf("Error: %s", err.Error())
			panic("Cannot access the container")
		}
	} else {
		fmt.Printf("Error: %s", err.Error())
		panic("Cannot access the container")
	}
```

We should make sure there is good documentation for this pattern, since it is not something that users can find through intellisense.  In particular, the following docs should be updated to describe this new method:

- The example code shown in the [docs for `azcore.HTTPResponse`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#HTTPResponse)

- As another "Common Usage Pattern" in [this doc](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-core-concepts). Arguably it should be the first one since error handling is potentially applicable to every service method call, whereas the other methods only apply in specific circumstances.

**Comment by jhendrixMSFT** [comment]
Fixed in the pending v0.21.0 release.
