### ISSUE TITLE
Azure Storage Account Client returning Unmarshalling Error on call for List method

### ISSUE THREAD

**Issue by syedtahaaziz** [Azure/azure-sdk-for-go#16135]
### Bug Report

github.com/!azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage@v0.1.0/zz_generated_models.go

unmarshalling type *armstorage.StorageAccountListResult: parsing time “NULL” as “\”2006-01-02T15:04:05.999999999\“”: cannot parse “NULL” as “\”"

Throwing error in zz_generated_models for keyCreationTime.

unmarshalling type *armstorage.StorageAccountListResult: parsing time “NULL” as “\”2006-01-02T15:04:05.999999999\“”: cannot parse “NULL” as “\”" thrown when calling storage account list.

i expect to get the []*armstorage.StorageAccount result . instead I was getting this error.

Try creating armstorage.NewStorageAccountsClient call the function List.

**Comment by tadelesh** [comment]
@syedtahaaziz We've fixed this bus in the new version. Please try `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage v0.2.0` with `github.com/Azure/azure-sdk-for-go/sdk/azcore v0.20.0`.

**Comment by syedtahaaziz** [comment]
Yes it is working now! Thanks for the support.
