### ISSUE TITLE
Overriding HTTP transport

### ISSUE THREAD

**Issue by ior308** [Azure/azure-sdk-for-go#16159]
### Feature Request

How to override http transport to azblob.NewServiceClientWithSharedKey API.

Thank you
Best Regards

**Comment by ior308** [comment]
I need to set a custom http transport for socks proxy.

Best Regards

**Comment by chlowell** [comment]
In v0.2.0 you can set the `Transporter` field on [`azblob.ClientOptions`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#ClientOptions):
```go
opts := azblob.ClientOptions{Transporter: httpClient}
client, err := azblob.NewServiceClientWithSharedKey("URL", key, &opts)
```
`Transporter` can be a `net/http.Client` with your configuration or, if you need something more custom, anything that has a `Do` receiver with the same signature as `net/http.Client.Do`. For example, here's the SDK's default client: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/runtime/transport_default_http_client.go

**Comment by ior308** [comment]
sorry
