### ISSUE TITLE
Event grid maximal message size seems to be lower than documented

### ISSUE THREAD

**Issue by edoboker** [Azure/azure-sdk-for-go#16160]
### Bug Report

- Import path of the package: `github.com/Azure/azure-sdk-for-go/profiles/latest/eventgrid/eventgrid`
- SDK version: `v59.1.0+incompatible`
- Go version is `go1.16.4 linux/amd64`

- As documented [here](https://docs.microsoft.com/en-us/azure/event-grid/quotas-limits), the event size limit is 1MB. However, when I tried sending large events I received `Error 413 size too large` on much smaller sizes. The code I've run:

```
package main

import (
	"math/rand"

	"context"
	"fmt"

	eventgrid "github.com/Azure/azure-sdk-for-go/profiles/latest/eventgrid/eventgrid"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/date"
	uuid "github.com/google/uuid"
)

func main() {
	sas := autorest.NewEventGridKeyAuthorizer(MY_SAS_TOKEN)
	test := eventgrid.BaseClient{}
	test.Authorizer = sas
	topicHostName := MY_EGR_HOSTNAME

	okaySize := make([]byte, 786954)
	tooLarge := make([]byte, 786955)
	rand.Read(data)
	rand.Read(data2)

	str := "StressTest"
	id := uuid.New().String()
	events := []eventgrid.Event{
		{
			ID:          &id,
			Subject:     &str,
			EventType:   &str,
			EventTime:   &date.Time{},
			Data:        tooLarge,
			DataVersion: &str,
		},
	}

	req, err := test.PublishEventsPreparer(context.Background(), topicHostName, events)
	if err != nil {
		fmt.Println(err)
	}

	req, err = autorest.Prepare(req, test.WithAuthorization())
	if err != nil {
		fmt.Println("prepare error", err)
	}

	send, err := test.PublishEventsSender(req)
	if err != nil {
		fmt.Println("send error", err)
	}

	resp, err := test.PublishEventsResponder(send)
	if err != nil {
		fmt.Println("respond error", err)
	}

	fmt.Println(resp.StatusCode)
}
```

If you run this, an event with `tooLarge` returns error code 413 while an event with `okaySize` returns 200. Am I miscalculating the event size or misreading the docs? I was expecting the limit to be around 1,000,000 bytes (given that 1MB is 1,048,576 bytes and I'm adding here about 40 bytes in headers, fields etc.)...

**Comment by ljluestc** [comment]
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand"

	eventgrid "github.com/Azure/azure-sdk-for-go/profiles/latest/eventgrid/eventgrid"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/date"
	"github.com/google/uuid"
)

type MyEventData struct {
	// Define your event data structure here
	// Example:
	Message string `json:"message"`
}

func main() {
	sas := autorest.NewEventGridKeyAuthorizer(MY_SAS_TOKEN)
	test := eventgrid.New()
	test.Authorizer = sas
	topicHostName := MY_EGR_HOSTNAME

	okayData := MyEventData{
		Message: "This is an okay-sized event data message.",
	}

	tooLargeData := MyEventData{
		Message: generateLargeMessage(), // Generate a large message.
	}

	str := "StressTest"
	id := uuid.New().String()
	events := []eventgrid.Event{
		{
			ID:          &id,
			Subject:     &str,
			EventType:   &str,
			EventTime:   &date.Time{},
			Data:        tooLargeData, // Serialize the data to JSON.
			DataVersion: &str,
		},
	}

	req, err := test.PublishEventsPreparer(context.Background(), topicHostName, events)
	if err != nil {
		fmt.Println(err)
		return
	}

	req, err = autorest.Prepare(req, test.WithAuthorization())
	if err != nil {
		fmt.Println("prepare error", err)
		return
	}

	send, err := test.PublishEventsSender(req)
	if err != nil {
		fmt.Println("send error", err)
		return
	}

	resp, err := test.PublishEventsResponder(send)
	if err != nil {
		fmt.Println("respond error", err)
		return
	}

	fmt.Println(resp.StatusCode)
}

// Function to generate a large message.
func generateLargeMessage() string {
	// Generate a large message here.
	// Example: create a large JSON payload.
	largeData := make([]byte, 786955)
	rand.Read(largeData)
	return string(largeData)
}
