### ISSUE TITLE
Consider adding support for TCP RST in Azure Core retry policy

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-sdk-for-go#16199]
### Feature Request

The retry policy should retry if the server resets the connection. 
To see how to do this, see https://gosamples.dev/connection-reset-by-peer/

#### Details

When an unexpected TCP packet arrives at a host, that host usually responds by sending a reset packet back on the same connection. A reset packet is simply one with no payload and with the RST bit set in the TCP header flags.

**Comment by RickWinter** [comment]
@JeffreyRichter Would the desired behavior be to restart the request whent the Reset is received?

**Comment by JeffreyRichter** [comment]
Yes, just do a retry. This will be hard to test because services do this almost never but it does happen.
