### ISSUE TITLE
azblob.GetSASToken wrong singed resource

### ISSUE THREAD

**Issue by yvespp** [Azure/azure-sdk-for-go#16193]
### Bug Report
- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version: `azblob v0.2.0`
- output of `go version`: `go version go1.17 linux/amd64`

- What happened?
  [GetSASToken](https://github.com/Azure/azure-sdk-for-go/blob/697b41367d206549adbf8668d4a0a924851e9332/sdk/storage/azblob/zc_blob_client.go#L226) creates an invalid SAS token, error when opening the generated link: https://mytestsa.blob.core.windows.net/velero/test?se=2021-11-16T14%3A28%3A47Z&sig=%2FWci8y5MNPQWs%2BV3HE%2BGaan0m0U1v%2BCdfh9prQSchL8%3D&sp=r&sr=bv&st=2021-11-16T14%3A22%3A47Z&sv=2019-12-12
  ```
  <Error>
  <Code>AuthenticationFailed</Code>
  <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the 
  signature. RequestId:066a5247-a01e-0035-0df5-da6efe000000 Time:2021-11-16T14:23:28.2598269Z</Message>
  <AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail>
  </Error>
  ```
  The query parameter `sr` (singed resource) should be `b` (blob) but is `bv` (blob version). `bv` is set here: https://github.com/Azure/azure-sdk-for-go/blob/aa44a563f6264f521814d7479b2346d4ee2a8ca2/sdk/storage/azblob/zc_sas_service.go#L50-L52
  The version it checks is not the blob version but the version of the blob service `sv`, so this check is wrong. Doc: https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specifying-the-signed-version-field
- What did you expect or want to happen?
  The generated SAS URL should work
- How can we reproduce it?
  ```
  start := time.Now().Add(-1 * time.Minute)
  expiry := time.Now().Add(5 * time.Minute)
  credential, _:= azblob.NewSharedKeyCredential("mytestsa", "mySharedKey)
  blobClientWithSharedCred, _:= azblob.NewBlobClientWithSharedKey("https://mytestsa.blob.core.windows.net/velero/test", credential, nil)
  queryParam, _:= blobClientWithSharedCred.GetSASToken(azblob.BlobSASPermissions{Read: true}, start, expiry)
  url := fmt.Sprintf("%s?%s", blobClientWithSharedCred.URL(), queryParam.Encode())
  ```
  Then copy paste the url into a browser

**Comment by mohsha-msft** [comment]
Hey @yvespp ,

Thanks for reaching out and I sincerely apologize for the delay from my side. Let me check this once and get back to you. I'll include the fix in the `dev-azblob` branch once it is ready. Once we make next release of azblob, it'll be available to you.
