### ISSUE TITLE
Add a step in our pipeline template which ensures the auto-generated code not to have manual manipulations

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-go#16204]
### Feature Request

A large part of our SDK is auto-generated, and if they have some parts that are manually written, those will be lost in the next iteration of generation. Therefore I am asking here to add a new step in our pipeline template to ensure that the auto-generated code in a PR does not have manual modifications. This can be done by running the `go generate` (in mgmt plane which invokes the `build.ps1`) again and seeing the diff.

BTW we have this in DotNet SDK: https://github.com/Azure/azure-sdk-for-net/blob/bc940a54270ee823c5307120b28fbc76d68f83e6/eng/pipelines/templates/jobs/ci.yml#L165

**Comment by kurtzeborn** [comment]
The core implementation of language checking should be owned by the language team.  If you need help plugging it into the pipeline, please reach out to @benbp.

Also, a similar check has been implemented by @pakrym so there may be an opportunity to share ideas there (though his .NET implementation probably won't be reusable directly).
