### ISSUE TITLE
Cosmos needs a constructor taking TokenCrendentail

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#16219]
Add in a client constructor for AAD support

**Comment by ealsur** [comment]
Already tracked by https://github.com/Azure/azure-sdk-for-go/projects/4#card-64859516

**Comment by magnus-fors** [comment]
Any ETA for when TokenCredentials might be supported?

**Comment by ealsur** [comment]
It is currently a work item planned for this semester
