### ISSUE TITLE
[azblob] HttpRange does not expose its fields

### ISSUE THREAD

**Issue by pdsdjkdsfksdnf** [Azure/azure-sdk-for-go#16223]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version: main
- go version go1.16 darwin/amd64

- What happened:
  `PageBlobClient` methods accept range options in form of `HttpRange`, all fields of which are unexported and thus are unable to be set by the consumers of `azblob` package.
- What did you expect or want to happen:
  I expect to be able to set range options.

**Comment by JeffreyRichter** [comment]
Looks like a bug to me. The fields should be publicly exported

**Comment by zezha-msft** [comment]
Thanks @pdsdjkdsfksdnf @JeffreyRichter it indeed is a bug. I've logged an item to get it fixed.

**Comment by mohsha-msft** [comment]
Fixed in `sdk/storage/azblob/v0.3.0`
