### ISSUE TITLE
Azcosmos Core/SQL API Query support

### ISSUE THREAD

**Issue by dmyyy** [Azure/azure-sdk-for-go#16220]
### Service Package Request

Hello!

I am looking to use the [azcosmos Core/SQL API](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/data/azcosmos#crud-operation-on-items) and was wondering if/when querying with SQL will be supported. It seems to be implemented for [ReadThroughputIfExists()](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/cosmos_offers.go#L40) but not exported. I understand the package is still on v0.1.1 - looking for an approximate timeline.

**Comment by ealsur** [comment]
ReadThroughputIfExists does not use Query per-se, it just uses the REST API for Offers: https://docs.microsoft.com/en-us/rest/api/cosmos-db/offers

Support for queries will be down the road, there is no ETA atm. We have a tracking item in the Project: https://github.com/Azure/azure-sdk-for-go/projects/4#card-67521440 for single partition queries, which will be the first type we will implement.
