### ISSUE TITLE
[azservicebus] Review the Dapr components, see what we need to add

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#16228]
Dapr is a popular project, with several contrib components built on top of Service Bus. 

We should look at the code, see if there's anything interesting that we could add to make SDK/integrators authors lives easier.

Some things we appear to be missing:
- [x] Ability to set the user agent (this would just append, not entirely replace the agent)
(more to come)
- [ ] Prefetch
      NOTE: will need to think about this a bit. Prefetch can sometimes be tempting to use but it leads to complications as the customer doesn't necessarily have enough information to know how many messages are sitting in an internal buffer. 

     This [Service Bus page](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet) is is using C# as the example, but it applies universally. 
- [ ] Multiple messages for RenewLock()
       Need to go back and check why we didn't allow this. The underlying call does support it but it might have some unintended performance implications. However, there's a pretty neat little renewer implementation in the Dapr pub-sub component where it looks like it'd be useful if you didn't want to do a goroutine per message.

**Comment by richardpark-msft** [comment]
@kimprice , @mikekistler - just FYI, using this issue to collect any problems/issues/requests that come up as we look at Dapr.

**Comment by jjcollinge** [comment]
One issue that I spoke to @richardpark-msft about internally was the fact it's not currently possible for us to migrate [this Dapr test](https://github.com/dapr/components-contrib/blob/4bf0dcbfcfa38f668e3b014078e7758381c11321/pubsub/azure/servicebus/message_test.go#L128) as there is no way to construct the `ReceivedMessage` with a body as it's internal. We might be able to cover this scenario in the integration testing instead.

**Comment by richardpark-msft** [comment]
> One issue that I spoke to @richardpark-msft about internally was the fact it's not currently possible for us to migrate [this Dapr test](https://github.com/dapr/components-contrib/blob/4bf0dcbfcfa38f668e3b014078e7758381c11321/pubsub/azure/servicebus/message_test.go#L128) as there is no way to construct the `ReceivedMessage` with a body as it's internal. We might be able to cover this scenario in the integration testing instead.

This one is a bit tough because the reason it exists is to make sure users don't accidentally use the simplified contract when the body is potentially bogus (ie, the caller encoded multiple data bodies, or they used .Value or .Sequence instead). 

I don't have a good solution for this yet, but it'd be nice to provide one if possible.

**Comment by richardpark-msft** [comment]
(mostly I worry about accidentally "slicing" the message, where we lose subsequent encoded Data bodies or entirely lose the .Value and .Sequence bodies if the client resends the message).

**Comment by richardpark-msft** [comment]
Another item, that @halspang brought up, is that the SB library for track 2 does not have built-in support for prefetching. There was already code in dapr to do it's own style of prefetching, but it'd be nice to think about how we support that.

There are some optimizations that can be done at the AMQP level (not huge) but implementing it outside of the SB library is also possible.
