### ISSUE TITLE
Sentinel Automation Rule Creation

### ISSUE THREAD

**Issue by Coffee-007** [Azure/azure-sdk-for-go#16240]
### Bug Report

- import path of package in question: services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight
- SDK version: `latest`

In the Azure Sentinel interface there is the ability to define an "Analytic rule name" condition, but this does not appear to be an option in the conditions enum.

Can you please let me know if there is actually a way to restrict the Automation Rule to only apply to Analytic Rules based on the name, for example starting with "xxx"?

Currently I am having to work around this by placing a condition in place that restricts on the Incident Title.

Thanks.

**Comment by lirenhe** [comment]
@Coffee-007, could you help to provide some sample code for your question?

**Comment by Coffee-007** [comment]
Hi @lirenhe I was using this via the Terraform template (azurerm_sentinel_automation_rule), so not directly using the Azure SDK.

This is the resource that I was trying to create: 
```
resource "azurerm_sentinel_automation_rule" "example" {
  name = uuid()
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id
  display_name = "Example Automation Rule"
  action_playbook{
    logic_app_id = azurerm_logic_app_workflow.example.id
    order = 1
  }
  order = 100
  enabled = true
}
```
I reached out the the maintainers of the Terraform repo and they suggested there was no way in the API to achieve what I was trying to achieve. For your reference here is the question there: https://github.com/hashicorp/terraform-provider-azurerm/issues/14286

Hope this helps, but please let me know if you need more from me.

**Comment by lirenhe** [comment]
@Coffee-007, sorry for the late reply. It seems to be a feature request for the service instead of a bug in the SDK.
So could you post your questions in https://docs.microsoft.com/en-us/answers/topics/azure-sentinel.html directly?
