### ISSUE TITLE
Issue passing reader to upload BlockBlobClient

### ISSUE THREAD

**Issue by ior308** [Azure/azure-sdk-for-go#16254]
### Feature Request

Dears

if I pass a reader instead of a readseek descriptor to upload BlockBlobClient API as in case of streaming from network and not from local file (for instance ftp, sftp, http etc as sources) I get an error during compilation (descriptor is not seekable).

To work-around I define a reader with a fake seek interface that simulates the operation required by API, in particular from this code: 

count, err := validateSeekableStreamAt0AndGetCount(body)

The fake seek returns the size of source file in case of io.SeekEnd and 0 in case of io.SeekStart (I get the size from the source before launching the copy via streaming).

That's fine and works, BUT... 

what happen if during streaming some transformations occur between reading and writing (such as PGP encoding, Dos2Unix encoding etc..) I'm not sure it will work, because I don't know the size in advance, the seek method could return a bad value and upload BlockBlobClient API might fails.

Is there another api to use to upload via streaming that accepts a reader descriptor instead of a readerseek descriptor ?

I also work with MINIO S3 SDK and if that helps, the MINIO S3 SDK accepts a reader type descriptor when putting the file.

Best Regards

**Comment by ior308** [comment]
Dear, any news ?

**Comment by mohsha-msft** [comment]
Hey @ior308 ,

I sincerely apologize for replying late on this thread. 
I'm aware of this issue and I think it was reported in [this PR](https://github.com/Azure/azure-sdk-for-go/pull/15958/files) as well. Let me fix that. I'll keep you informed.

**Comment by mohsha-msft** [comment]
Fixed in `sdk/storage/azblob/v0.3.0`
