### ISSUE TITLE
DatasetCompression model doesn't align with its Swagger definition

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#16298]
The `DatasetCompression` in the [models.go](https://github.com/Azure/azure-sdk-for-go/blob/8a696eee495ea9373f6853a9d1574e7db356d7ff/services/datafactory/mgmt/2018-06-01/datafactory/models.go) was a discriminator but is changed to be a regular model in the Swagger in the commit: https://github.com/azure/azure-rest-api-specs/commit/a159bb4420f176c580480d7ef344fe5716c2ef38

**Comment by Alancere** [comment]
released in https://github.com/Azure/azure-sdk-for-go/releases/tag/v60.0.0
