### ISSUE TITLE
outdated wiki for client certificate credentials

### ISSUE THREAD

**Issue by baywet** [Azure/azure-sdk-for-go#16296]
Hi from the Microsoft Graph team 👋

The following wiki section instructs people to pass-in a path for to the certificates when the actual code only accepts a certificate object.
The wiki should be updated to provide an example of loading the certificate in memory and pass it to the credentials.

https://github.com/Azure/azure-sdk-for-go/wiki/Azure-Identity-Examples#authenticating-a-service-principal-with-a-client-certificate

https://github.com/Azure/azure-sdk-for-go/blob/8a696eee495ea9373f6853a9d1574e7db356d7ff/sdk/azidentity/client_certificate_credential.go#L50

https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/19

**Comment by chlowell** [comment]
Thanks for opening this! The authentication content in the wiki has been superseded by package docs and the [Azure SDK for Go docs](https://docs.microsoft.com/azure/developer/go/azure-sdk-authentication). I replaced it with a notice to that effect. The updated example you're looking for is in the package docs: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#example-NewClientCertificateCredential
