### ISSUE TITLE
azservicebus receiveMessages never finishes when network is lost, gets stuck in drainLink

### ISSUE THREAD

**Issue by flexarts** [Azure/azure-sdk-for-go#16340]
This bug is regarding the azservicebus data plane API.
I'm using `github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v0.3.1`

I am having a problem with the following code:

```go
	var notification types.FtpUploadNotification
	ctx, cancel := context.WithTimeout(context.TODO(), 20 * time.Second)
	defer cancel()

	messages, err := servicebus_handler.ReceiveMessages(ctx, 1, nil)
	if err != nil {
		return notification, err
	} else if len(messages) == 1 {
		body, err := messages[0].Body()
		if err == nil {
			json.Unmarshal(body, &notification)
			err := servicebus_handler.CompleteMessage(ctx, messages[0])
			if err != nil {
				panic(err)
			}
		}
		return notification, nil
	} else {
		return notification, errors.New("no message received")
	}
```

When during the timeout of 20 sec a network interruption happens the code is stuck in the following part of `receiver.go` in `receiver.DrainCredit(context.Background())`(Line 376).

```go
func (r *Receiver) drainLink(ctxForLoggingOnly context.Context, receiver internal.AMQPReceiver, messages []*ReceivedMessage) ([]*ReceivedMessage, error) {
	// start the drain asynchronously. Note that we ignore the user's context at this point
	// since draining makes sure we don't get messages when nobody is receiving.
	if err := receiver.DrainCredit(context.Background()); err != nil {
		tab.For(ctxForLoggingOnly).Debug(fmt.Sprintf("Draining of credit failed. link will be closed and will re-open on next receive: %s", err.Error()))

		// if the drain fails we just close the link so it'll re-open at the next receive.
		if err := r.amqpLinks.Close(context.Background(), false); err != nil {
			tab.For(ctxForLoggingOnly).Debug(fmt.Sprintf("Failed to close links on ReceiveMessages cleanup. Not fatal: %s", err.Error()))
		}
	}
```

The parameter `ctxForLoggingOnly` is containing the 20 sec timeout but is not used in the `receiver.DrainCredit(context.Background())` call. When I replace the `context.Background())` with `ctxForLoggingOnly` it is respecting the timeout and tries to reconnect in the outer code.

Can i somehow archive it in another way in the calling code?

Thanks in advance,
Dominic

**Comment by richardpark-msft** [comment]
Hi @flexarts,

I'll take a look at this. The underlying AMQP stack is supposed to signal us that the link is dead/detached so there must be something missing there.

To your other question about propagating the context - this is a spot where we typically don't want to interrupt it since it can leave messages in an internal queue without your knowledge. So the drain is needed to leave the link in a clean state. Under normal conditions this isn't an issue but, as you noted, there's a bug in our drain code that appears to not be signaling.

**Comment by flexarts** [comment]
Thanks @richardpark-msft the patch works like charm. Reconnecting is now possible in the outer code!
Have a wonderful Christmas time :)
