### ISSUE TITLE
RoleAssignmentsClient ListComplete with filter = principalId eq {id} returns empty list

### ISSUE THREAD

**Issue by manalivaltix** [Azure/azure-sdk-for-go#16373]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

import path of package 	"github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization"
I am using the RoleAssignmentsClient to get the complete list of role assignments for a given managed Identity. I get the principalId of the managedIdentity, and i use that principal id in the  filter.

principalId eq "abf1348e-3b2a-4294-b3e0-64ea3d872be1"

However, ListComplete returns an empty list. I am able to get the role assignment using the following CLI. 
az role assignment list --assignee abf1348e-3b2a-4294-b3e0-64ea3d872be1

I also made sure my software has permissions to read the roleAssignments.

**Comment by lirenhe** [comment]
@manalivaltix, do you have the sample code for the problem you face?

**Comment by manalivaltix** [comment]
// GetRoleAssignmentsClient - Get azure role definitions client
func (s *AzureService) GetRoleAssignmentsClient() (*authorization.RoleAssignmentsClient, error) {
	roleClient := authorization.NewRoleAssignmentsClient(s.subscriptionID)
	authorizer, err := s.GetAuthorizer()
	if err != nil {
		log.Printf("Error while getting authorizer %v", err)
		return nil, err
	}
	roleClient.Authorizer = authorizer
	return &roleClient, nil
}

func (s *AzureService) ListRoleAssignmentsForUserIdentity(userIdentity *uuid.UUID) ([]*authorization.RoleAssignment, error) {

	if userIdentity == nil {
		return nil, fmt.Errorf("Invalid null userIdentity")
	}
	log.Printf("ListRoleAssignments for user identity %+v", userIdentity)

	client, err := s.GetRoleAssignmentsClient()
	if err != nil {
		log.Printf("error getting role assignment client: %v", err)
		return nil, err
	}

	filter := fmt.Sprintf("principalId eq %q", userIdentity.String())
	log.Printf("use filter %s", filter)

	roles := make([]*authorization.RoleAssignment, 0)
	// get role assignments
	for list, errL := client.ListComplete(context.TODO(), filter); list.NotDone(); errL = list.Next() {
		if errL != nil {
			log.Printf("Error while getting role assignments %v", errL)
			return nil, errL
		}
		r := list.Value()
		// check for valid params
		if r.ID == nil || r.Properties == nil || r.Properties.RoleDefinitionID == nil {
			log.Printf("Error: Role Assignement %+v id or Properties or RoleDefinitionID is null",
				r,
				miscutils.String(r.ID),
			)
			continue
		}
		roles = append(roles, &r)
	}
	return roles, nil
}

**Comment by tadelesh** [comment]
@manalivaltix, the SDK version you are using has already deprecated, please try our [latest version](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4) and feel free to reopen this issue if any further problems.
