### ISSUE TITLE
Request to add 2021-06-01 Stable Microsoft.Authorization Package

### ISSUE THREAD

**Issue by kaovd** [Azure/azure-sdk-for-go#16389]
### Service Package Request

The 2021-06-01 Stable package provides similar functionality to currently released preview package in the Authorization / Policy scope - although stable is preferred where possible.

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/resources/resource-manager/Microsoft.Authorization/stable/2021-06-01

**Comment by RickWinter** [comment]
There is the new release version of this package available at:
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/authorization/armauthorization

**Comment by lirenhe** [comment]
The package definition https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/readme.md#tag-package-policy-2021-06 contains preview feature so we released preview package.

**Comment by kaovd** [comment]
> The package definition https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/readme.md#tag-package-policy-2021-06 contains preview feature so we released preview package.

Thank you that makes it more clear why it is in preview
