### ISSUE TITLE
New Function for Attaching Disks to a VM

### ISSUE THREAD

**Issue by rohrerb** [Azure/azure-sdk-for-go#1638]
Hello,

Would it be possible for you to build a separate function to allow attaching of disks outside of the create_or_update VM?

` az vm disk attach --help`

**AzureCLI** offers the ability to attach disks with single call which in the end calls into create_or_update.
https://github.com/Azure/azure-cli/blob/b9ac9ecdc5e62b1f8dee18be35bc9e8cdbfa6573/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py#L1132
 
Having this new function will assistance us in resolving this item - https://github.com/terraform-providers/terraform-provider-azurerm/issues/795

Thank you,
-B

**Comment by joshgav** [comment]
Hi @rohrerb and thanks for the request. The Azure SDKs are a simple binding of the underlying HTTP APIs as described in [specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification) into various languages; we don't provide higher-level functionality in the SDKs, only in e.g. [samples](https://github.com/Azure-Samples/azure-sdk-for-go-samples) or tools like the CLI.

Can you and Terraform use the patterns described in #944 and #816 to accomplish your goals? We also have a sample illustrating how to attach and detach disks here: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/f1f27bfcee3cbec1b064ce8eac78320fea1b115c/compute/compute.go#L162.

@mcardosos can you provide further assistance if needed? Thanks!

**Comment by joshgav** [comment]
Closing now per [comment](https://github.com/Azure/azure-sdk-for-go/issues/1638#issuecomment-384733952). Thanks for the feedback!
