### ISSUE TITLE
Add new version of recovery service vault API

### ISSUE THREAD

**Issue by josh-barker** [Azure/azure-sdk-for-go#16388]
### Service Package Request

Hi, I'd like to work on updating the `azurerm_recovery_service_vault` resource to support storage_replication_type, as per [this](https://github.com/hashicorp/terraform-provider-azurerm/issues/8709) issue.

From what I can [see](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable), there are newer versions of the API.
Could a newer version be published?

Cheers

**Comment by RickWinter** [comment]
Thank you for using the SDK and the willingness to contribute to making it better.  We're in the process of refreshing all our ResourceManager pkgs to be complient with the new Azure SDK guidelines.  You can find the preview of the RecoveryService package at:
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/recoveryservices/armrecoveryservices

**Comment by tombuildsstuff** [comment]
@RickWinter any plans to add a Track1 SDK for this?

**Comment by josh-barker** [comment]
@RickWinter Could we also look at publishing the following endpoint too?

`https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vaults/xxx/monitoringConfigurations/notificationConfiguration?api-version=2017-07-01-preview`

This relates to https://github.com/hashicorp/terraform-provider-azurerm/issues/5423

**Comment by Alancere** [comment]
@josh-barker Does recoveryservices backup stable 2021-07-01 meet your needs(track1)?https://github.com/Azure/azure-sdk-for-go/tree/a51bae68638fee14f4fbc2f1003ea719119cfdd7/services/recoveryservices/mgmt/2021-07-01/backup

**Comment by josh-barker** [comment]
@Alancere 

recoveryservices backup stable 2021-07-01 supports the needed `StorageType` values.

However, I cannot find the 2nd endpoint - `https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vaults/xxx/monitoringConfigurations/notificationConfiguration?api-version=2017-07-01-preview`

Would you prefer me to raise a separate issue to publish the 2nd endpoint?

**Comment by RickWinter** [comment]
We will not be publishing an update to the old mgmt plan for this service.  It will be available based on the new design guidelines in the upcoming months.  There is a PR in progress to add it.

https://github.com/Azure/azure-sdk-for-go/pull/16518.

**Comment by lirenhe** [comment]
@josh-barker, our stable package should not contain preview features.  If you need this API, could you create an issue in https://github.com/Azure/azure-rest-api-specs/issues/new to ask service team to put this API into the latest API version?

**Comment by josh-barker** [comment]
Hi @lirenhe, I'll raise an issue in that repo.

Thanks!

**Comment by josh-barker** [comment]
@Alancere @lirenhe : when can recoveryservices backup stable 2021-07-01 be published?

**Comment by Alancere** [comment]
@josh-barker Here is the recovery services backup https://github.com/Azure/azure-sdk-for-go/tree/main/services/recoveryservices/mgmt/2021-07-01/backup -track1, track2 released https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/recoveryservices/armrecoveryservicesbackup , but that is stabe package-2021-08-01 version

**Comment by josh-barker** [comment]
I've been able to use track1.

Thanks @Alancere ! 🚀
