### ISSUE TITLE
What about adding subpackages*?

### ISSUE THREAD

**Issue by sadasant** [Azure/azure-sdk-for-go#16390]
(Hello, Go team!)

Go developers might want to import a single section of an SDK package directly. For example, regarding `azidentity`, developers might rather import a specific credential, like `github.com/Azure/azure-sdk-for-go/sdk/azidentity/environmentcredential`.

Submodules in Go might help as follows:

- Binary size, since a specific submodule will likely make the resulting package to be smaller (I haven’t confirmed).
- Navigating the code. Developers could go directly to a submodule to understand a specific feature.

What do you think? I believe we’re at the right time to think about this since we haven’t GAd.

---

Changed the title: From `submodules` to `subpackages`.

**Comment by JeffreyRichter** [comment]
Our plan is that each service gets its own module because they version independently of each other.
We then keep azcore & azidentity in their own modules also for versioning and for dependency management. That is, azidentity depends on azcore but not vice versa. All azidentity credentials share (depend on) a single pipeline policy and we wants these to all be versioned together and they are tightly coupled.

**Comment by sadasant** [comment]
@JeffreyRichter thank you for your response!

I understand and agree that each service gets its module! But what about sub-modules for services? This might not be a problem present in the existing surface of the Go SDK (I mentioned `azidentity` as an example). Still, based on my limited experience, SDK packages tend to grow over time, so I am inclined to propose we think of _service modules_ as folders containing sub-modules specific to distinct areas of work.

Let’s say the KeyVault Admin package that other languages have. This package has two clients, the backup and access control clients. These two have very distinct functionalities. Developers could lean towards wanting, for example, only the backup functionalities in a project. If possible, I would instead provide a set of submodules, like `azkeyvault/admin/backup` and `azkeyvault/admin/accesscontrol` (the names are examples).

Regarding `azidentity` specifically, in my experience, developers tend to use only one credential most of the time. Also, some credentials have a unique frame of reference, very much outside of other credentials. For example, the Authorization Code Credential tends to have a functionality to generate the /authorize URL completely foreign for other credentials.

Regarding keeping the same version across modules, wouldn’t that be satisfied by the `go.mod`? For example, if we tied version `1.2.3` of `azidentity` specifically to a git tag `azidentity-1.2.3` (to say a name), then all of the potential submodules of `azidentity` would be accessible from the git tag `azidentity-1.2.3`.

---

I’m asking these questions to understand and learn how I can be more effective over time! Any feedback is appreciated 🙏

**Comment by JeffreyRichter** [comment]
We can have sub-packages within a module, and we take advantage of this now (keyvault is an example).
I'm not opposed to sub modules within a service, but the value this would provide is about independent versioning and a service itself versions all at once. I do not think there is any other value of having sub modules; it would not impact compiled binary size as the Go linker already removes all unused code. 

Based on your last paragraph (about go.mod). I think you might be conflating sub modules and sub packages. Modules can be versioned independently of one another; subpackages share a version but everything in Go is in a package. That is, every module has 1 or more packages in it.

**Comment by sadasant** [comment]
> it would not impact compiled binary size as the Go linker already removes all unused code.

Good point! thank you! I was mixing things up.

> you might be conflating sub modules and sub packages

You are correct! I meant to say sub packages all this time.

When you say that keyvault is an example, do you mean the `crypto` folder in `azkeys`?

I think I understand the approach now! And it makes sense to me. Part of what feels like there’s something missing is that the packages are currently rather small.

Anyway, thank you for your responses! I’ll close this issue.
