### ISSUE TITLE
[szservicebus] Unauthorized access. 'Listen' claim(s) are required to perform this operation. 

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#16394]
Bug reported by internal customer:

```
*Error{Condition: amqp:link:detach-forced, Description: The link '<linkid>' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: '<servicebus>'.. TrackingId:<tracking-id>, SystemTracker:<gateway>
```

This is a bug we've seen before, and it appeared to be related to connection idleness. We added in a connection keep-alive, and in addition all the links that are created from a client are now consolidated into one connection, making it even less likely that a connection would be invalidly claimed to be "idle".

One other thing to note is that when this happened a sender link on the same connection _also_ detached. 

The customer then restarted the links and they worked the next time through, which indicates the connection might have recovered properly. Since the error itself is just a link detach it's quite possible it's recoverable.

NOTE, this was a connection string, not an MSI.

There are some areas we can look at, based on what we're seeing here:

1. The error came back from the ReceiveMessages() call. Since the receiver is lazy-initialized this means the negotiateClaim call happens immediately, which is probably where this error actually came from. 

    With claim negotiation you get 20 seconds from when the connection is created to properly authenticate ([claims based authorization](https://docs.microsoft.com/azure/service-bus-messaging/service-bus-amqp-protocol-guide#claims-based-authorization)). AFAICT, we're doing things in the right order, but it's possible there is something that can take longer than expected. 

2. It's possible there's something timestamp oriented that's incorrect (need to check if that matches the error given). We've seen some issues with other renewal methods when there is clock skew. We might be making an incorrect local time assumption.

3. There is a lock around negotiateClaim's internal call to amqp-common because we found a thread-safety issue. It could very well be that we're bottlenecking here. In reality these calls are very parallelizable.

4. Another possibility - we've (well, @jhendrixMSFT) has been fixing/looking at various issues where we could end up in a credit logjam. We should check and make sure our limits are tuned appropriately in the amqp-common/internal code.

**Comment by cghiban** [comment]
Not sure if it's related, but we're getting this message when we try to send a message:

> error publishing message acking anyway: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'G6:73468206:bfuTLxfCTv-vJErFRs2RKNeKGfRKB74MuRl7L47653nVdIPUP4uSOw' is force detached. Code: publisher(link12860924). Details: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00., Info: map[]}

If it isn't a bug, how should handle this? Or try reconnecting?

I'm using these versions:

> github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v0.3.2
> github.com/Azure/azure-event-hubs-go/v3 v3.3.17

In the past ( using `github.com/Azure/azure-service-bus-go v0.11.3`) there was a way to recover:

```
        err := q.sender.Send(ctx, &msg)
        if err != nil {
                if err = q.sender.Recover(ctx); err != nil {
                        fmt.Printf("azure.queue.sender: can't recover sender %T - %s", err, err.Error())
                        return "", err
                }
        
                q.sender.Send(ctx, &msg)
                //...
        }
```

Any ideas would help. Thank you

**Comment by richardpark-msft** [comment]
There have been a few meaningful fixes in this area and I've not seen this bug in the latest packages in our long term testing. Closing for now, will reopen later if it reappears.
