### ISSUE TITLE
Azure key vault signature encoding and decoding format documentation not clear, probably causing issues.

### ISSUE THREAD

**Issue by jaswinder6991** [Azure/azure-sdk-for-go#16397]
Using Keyvault for storing my Secp256K1 keys and using the sign API to sign my messages. The signature that I get from Azure back fails in a custom JS verification function intermittently. It succeeds 50% of the times mostly. I am thinking this is a problem with encoding and decoding my input and output respectively.
I am receiving a hash in hex format from an upstream application so this is what my flow looks like:
1. Converting my Hex string into Byte[]
2. Sha256 of this Byte[]
3. RawURL encoding of this Sha.
b64.RawURLEncoding.EncodeToString(sha)
4. Sending this to Key vault for signature.
5. Decoding the response using RawURLEncoding.
b64.RawURLEncoding.DecodeString(*keyOpsResp.Result)
6. Doing Hex of the []Byte array returned from 5th Step.

A JS function to verify if the signature is valid using, signature and the public key.
The golang sdk says that input output are URL encoded but it isn't clear if it is RawURL or simple URL, if it is padded or unpadded. Can we share more details around input and output encoding decoding.

**Comment by seankane-msft** [comment]
Hi @jaswinder6991 thanks for reporting this issue. Could you provide a code snippet for this situation? That will help me reproduce and debug the situation. What is the error code you are receiving from the service when you do this as well? If it helps, [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/keyvault/azkeys/crypto/crypto_client_test.go#L113-L141) is the test that we use to verify the `CryptoClient.Sign` function works as intended.
