### ISSUE TITLE
Wrong json model on Data Lake Storage "Path"

### ISSUE THREAD

**Issue by asafg6** [Azure/azure-sdk-for-go#16401]
### Bug Report

- import path of package in question: github.com/Azure/azure-sdk-for-go/services/storage/datalake/2019-10-31/storagedatalake
- SDK version: 58.3.0
- output of `go version`: go version go1.17 linux/amd64

- What happened?
 While trying to list paths got json parse error
```
Error = 'json: cannot unmarshal string into Go struct field Path.paths.contentLength of type int64' JSON = '{"paths":[{"contentLength":"0","etag":"0x8D9B8C1E77A2CCF","group":"$superuser","isDirectory":"true","lastModified":"Mon, 06 Dec 2021 14:08:40 GMT","name":"vms/7e5ffad1-c24d-11e8-911f-c4b301c47c6b","owner":"$superuser","permissions":"rwxr-x---"},{"contentLength":"0","etag":"0x8D9B8C4BB9B08F6","group":"$superuser","isDirectory":"true","lastModified":"Mon, 06 Dec 2021 14:28:55 GMT","name":"vms/dd981f75-c6ed-11e8-bb55-c4b301c47c6b","owner":"$superuser","permissions":"rwxr-x---"},{"contentLength":"24","etag":"0x8D9B8CD715E87DE","group":"$superuser","lastModified":"Mon, 06 Dec 2021 15:31:15 GMT","name":"vms/last","owner":"$superuser","permissions":"rw-r-----"}]}
```

- What did you expect or want to happen?
 To get the list of paths from the api
- How can we reproduce it?
 Use PathClient.List
- Anything we should know about your environment.
Using linux and go 1.17, nothing special

**Comment by asafg6** [comment]
I have this pull request that solves this issue
https://github.com/Azure/azure-sdk-for-go/pull/16403

**Comment by ArcturusZhang** [comment]
Hi @asafg6 thank you for your issue!

But unfortunately your PR cannot be merged, because our SDK is auto-generated from the corresponding swaggers, your changes will be overridden on your next release.
We will report this issue to the corresponding service team so that they can fix their swagger accordingly and this issue will be resolved then.

**Comment by ArcturusZhang** [comment]
Hey @asafg6 for normal cases we have cut the new features for data plane packages now, but considering your change is a bug fix, and there is really no alternative of this package out there now, we will have a review and merge your PR to unblock you.
Sorry for the inconvenience

**Comment by asafg6** [comment]
Thank you @ArcturusZhang 
What is the official data plane sdk?
I thought that this is it..

**Comment by lirenhe** [comment]
@asafg6, here is the list of client libraries for GO:  https://azure.github.io/azure-sdk/releases/latest/go.html

**Comment by asafg6** [comment]
@lirenhe Which one of those is the recommended sdk for Data Lake ???

**Comment by lirenhe** [comment]
There is no data lake now, that is why @ArcturusZhang mentioned,  'there is really no alternative of this package out there now'.
We will have a review and merge your PR to unblock you.

**Comment by asafg6** [comment]
Ok thanks :)  !
