### ISSUE TITLE
Bad codegen when additionalProperties is a discriminated type

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1648]
As property:
Spec: https://pastebin.com/Gqc1PfFj
Codegen: https://play.golang.org/p/reEn65mm-vX

As discriminated type:
Spec: https://pastebin.com/GUvXd8iu
Codegen: https://play.golang.org/p/nFw_W4Zusy8

Note that in the second example we don’t generate UnmarshalJSON for the User type (see the very end of codegen in first example).

**Comment by joshgav** [comment]
We don't yet have specs which utilize this feature so we haven't prioritized yet.

**Comment by chamons** [comment]
I just re-ran this against more recent autorest and we fail to generate https://pastebin.com/Gqc1PfFj with:

```
stderr: ERROR: Semantic violation: Discriminator must be a required property. (components > schemas > base)
  discriminator: { propertyName: 'type' }
```

and the same with the second one.

I'm unsure if this makes this issue state @jhendrixMSFT
