### ISSUE TITLE
how to refresh token (using azidentity)

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#16489]
I get a new credential using `azidentity.NewClientSecretCredential` like

```
cred, err := azidentity.NewClientSecretCredential(tenantID, clientID, clientSecret, &azidentity.ClientSecretCredentialOptions{})
	if err != nil {
		return cred, errors.Wrap(err, "unable to auth to azure")
	}
```

I'm able to auth to azure ... This works well.

What happens when the token lifetime expires. (by default after 3600 Secs)

How do I renew the token? 
Is there a way to do that?

**Comment by vijayrajah** [comment]
on further reading.. I think according to #10567 I do not need to worry about this. This is handled automatically in background.

Is this correct? Is this behavior enabled in current azidentity release?

**Comment by RickWinter** [comment]
> on further reading.. I think according to #10567 I do not need to worry about this. This is handled automatically in background.
> 
> Is this correct? Is this behavior enabled in current azidentity release?

Correct, The Identity package handles refreshing the token slightly prior to expiration.

**Comment by vijayrajah** [comment]
thanks for the confirmation @RickWinter
