### ISSUE TITLE
[Doc] add button to copy code to clipboard

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk-for-go#16493]
### Feature Request
It would be nice to be able to click a button to copy the code

**Comment by kurtzeborn** [comment]
@danieljurek, this is an interesting request.  My guess is we'd have to relay it to the docs team though since I don't think this is a feature we can add or would own.

(also, ignore all those linked PRs.  That's an overzealous automation script from the CLI team making that noise)

**Comment by RickWinter** [comment]
@benbp @danieljurek Can you elaborate on this issue?  What are we attempting to copy and where would it go?  Should this issue be closed?
