### ISSUE TITLE
[Doc] package landing page not expanded by default

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk-for-go#16491]
- What happened?
Go to https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets
Notice that the doc landing page of a package is not expanded by default
![image](https://user-images.githubusercontent.com/7583839/145091758-6138a829-0508-4634-a217-914b69f8e335.png)

- What did you expect or want to happen?
Why not expand it by default? I need to click to expand it.

- How can we reproduce it?
- Anything we should know about your environment.

**Comment by seankane-msft** [comment]
I believe this is out of our control. @jhendrixMSFT any idea on how to make this change?

**Comment by jhendrixMSFT** [comment]
This is by (their) design.  If you look at the docs for AWS it's the same thing.

https://pkg.go.dev/github.com/aws/aws-sdk-go
