### ISSUE TITLE
[Blobs] [Docs] azblob SEO

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-go#16498]
I struggled to find the latest Blobs docs for Go when getting started with the bug bash.  The README shows `NewServiceClientWithSharedKey` but everything I find when searching things like "go azblob docs" is for older versions where we used the `URL` pattern instead of `Client`.  I eventually gave up and asked for help.

There are a couple of things we need to fix:
- Add link to our ref docs from the README at https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md
- Update the docs for the older packages to point at the latest
- Update https://github.com/Azure/azure-sdk-for-go/blob/main/storage/README.md to point to the latest package (because its links took me down a different rabbit hole)

If we do any other UX studies for Go, I'd suggest asking customers to try finding the ref docs themselves to make sure every road leads to the correct ref docs.

**Comment by vibhansa-msft** [comment]
Closing this as README and Test cases and Samples exists for all clients in blob/datalake now.
