### ISSUE TITLE
[Blobs] [Docs] Ref docs structure

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-go#16502]
High level feedback about https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@main

1. I don't really know what to make of this page as it includes a verbatim README followed by the real documentation.  Is this standard practice in go?  It doesn't feel like it flows super well from the README into the ref docs.  I also think folks looking up our ref docs are potentially a different audience than the folks getting started so maybe we should just link the README?
1. The repo link on the right points to the root of the mono-repo rather than the blobs package.
1. Don't copy the exact same sample from the README in the Documentation Examples section.
1. Why don't our example code snippets have syntax highlighting?  I see it in all the ref docs below.
1. The snapshot example should say what a snapshot is in the blurb above the code.
1. We should add a blurb before the progress sample to explain what it is and why you'd want to read it.
1. Why do our sample have an empty "output" section at the bottom?  Should we print some output to make that more interesting?
1. As somebody who's not a go person, I find that Index **brutal** to use.  Can we change how that sorts so things like `BlobClient` are at the top of the list?  If not, can we provide some links in the documentation section that jump to the "important types"?
1. It'd be great to link "child" types back to their "parent" since navigation is so unpleasant.  For example, it's easy to go from [AbortCopyFromURL](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@main#BlobClient.AbortCopyFromURL) to [AbortCopyBlobOptions](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@main#AbortCopyBlobOptions) but painful to go the other direction.  If we added a reference to the method from the options/result type, we could make it far easier to zoom around your docs.
1. Do we need to include all the `MarshalXML`/`UnmarshalXML` methods for every type in the docs?  I don't think any customers will ever use them and they're not adding a lot of value.
1. I wonder more about `ToPtr` because I think the doc comments aren't worth the space it requires, but customers will actually use these.  Would it be worth it to hide the method in docs but add a comment on the type that you can use `ToPtr` if you need a reference?

**Comment by vibhansa-msft** [comment]
Closing this as samples and docs have been updated post Track-2 stablisation.
