### ISSUE TITLE
[Blobs] [Docs] README feedback

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-go#16500]
General feedback about https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md

### Create the client
1. In [Create the client](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md#create-the-client) you list the types of resources, but it'd be helpful to include the type of client like `Azure storage accounts, represented by ServiceClient.`
1. The flow in `Create the client` is kind of confusing.  We say "you need an endpoint and a credential, here's how to find the endpoint, and here's how to call the .ctor."  We skip over the credential.  I know it's in the next section, but the flow is awkward for the very first experience a customer will have using the library.
1. "For more information about blob service URL's and how to configure custom domain names for Azure Storage check out the **official documentation**" makes me feel like this documentation is unofficial?

### Credentials
1. Tell me what the different types of credentials are at https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md#types-of-credentials or link somewhere that does.  How would I decide between shared key vs. sas?
1. Add an example with `DefaultAzureCredential` and make it first.  It's the safest option with the least amount of code so we should put it first.
1. Make the connection string the second example.  It will help more customers get started faster, even if it's not good for them.
1. Can we make the AZ CLI snippets inline?  I feel like it makes it kind of harder to see the interesting bit at https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md#2-creating-the-client-from-a-connection-string when I've got an example CLI command in front of the important block of code.
1. I find https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md#3-creating-the-client-from-a-sas-token confusing.  It first says "provide the token as a string" which I don't think is explicitly shown.  Should this say "provide the SAS token as part of your endpoint URLs query parameters" or similar?
1. Can you link to the ref docs or a sample for using `ServiceClient.GetSasToken(...)` and similar methods on `ContainerClient`/`*BlobClient`?
1. Don't generate a SAS first.  It makes that example look so much more complicated than it really is if you need to use a different type of auth to get started with the type of auth we're demo'ing.  We should link to another section of the doc or ideally another sample elsewhere in the repo showing folks how to create SAS URIs.
1. Make anonymous access a separate section instead of merging it in the SAS section.  Combining different auth mechanisms into one section like that is difficult for new customers.

### Clients
1. At https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/README.md#clients, I don't think we're making it clear that there's a separate `BlobClient` for "generic operations that apply to any blob like downloading or setting properties" and the other types of blobs.
1. We should have separate bullets for each blob type with a little blurb about why you'd want to use that blob.
1. It'd be helpful to say new users should start with `BlockBlobClient` for uploading/downloading simple files to get started.  New users always stumble here.

### Example
1. I think having a single large block of code is less friendly than splitting it up by scenarios.  Take a look at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/README.md#examples where it's broken apart into Upload, Download, and Listing as a comparison.
1. Can we wrap lines ~80-120 characters?  The way it renders in github means I have to scroll right which can be unpleasant if you're working on a desktop.  I'm convinced UX designers at github have only ever used laptops.
1. Why do we use `ok` for errors from `os.LookupEnv` and then `err` for errors from the Azure client library?  Can we use `err` across both?
1. Can we use connection strings for the sample to cut out a bunch of non-Blobs code?
1. Why is `handle(err);` outdented?
1. If we're going to keep `fmt.Sprintf("https://%s.blob.core.windows.net/", accountName)`, then assign it to a variable so the Blobs code doesn't have crazy long lines or look so complex.  Plus it'll be easier to inspect in a debugger if someone's stepping through.
1. The last parameter to create the service client is `nil`.  Do we want to write that as `/* options */ nil` to explain what it does and give folks a hint they should explore for customization?
1. Is `handle` a standard function?  Should we be checking if there was an error before calling it like I typically see in go code?
1. On `// First, branch off of the service client and create a container client.` it'd be great to say "and create a container client with the authentication and settings" to communicate that we're sharing a pipeline along with "Note that this only creates a client and not a resource on the service."
1. According to the docs, go's container `Create` method fails if the container already exists.  We should add some sample code that ignores that failure so this sample doesn't blow up if a customer runs it a second time.
1. You have to explain whatever the `NopCloser` thing is.  I'd recommend pulling it out on its own line to keep the `Upload` method looking simple.  We should also move the `data` declaration between the blob and upload.  Right now it's data, blob, stream, upload.  It'd be nice to mix data + stream together in the middle.
1. I wouldn't use `"HelloWorld.txt"` as the blob name because I think it causes customers to think blobs are named like files on disk.
1. I would make "download" its own section in the sample instead of lumping it together with "upload" because a lot of people just want to copy/paste one side of that coin.
1. `get` is a weird name for a variable.  It makes me think it's a task/promise/etc. that I have to invoke when I think it's really more of a Response?
1. Remove the `if data != downloadedData.String() {` check.  I don't think it's interesting to unit test in samples.  If you really want to do something with the data, print it out?
1. I'm kind of surprised at the bit about separate channels for values/errors in the paging sample because it looks pretty hard to use.  Can we delete all the blank lines so it becomes one copy/pasteable unit?  We have a property called `ContainerListBlobFlatSegmentResult`?
1. Create another section for deleting blobs/containers instead of including it in Listing.

### Troubleshooting
1. Is it just I/O operations that return an error?  We won't fail if you don't pass a credential, etc.?
1. The error handling section should show how to access the status code, error code, and message.  Ideally we'll also talk about some of the other good things the message will contain that'll help you debug, diagnose, engage with support, etc.
1. Nit - move the `errResp` member inside the error handler so it's only scoped to the failure case
1. Does "set AZURE_SDK_GO_LOGGING to all" mean set an environment variable named `AZURE_SDK_GO_LOGGING`?  It might be helpful to make that explicit.
1. Move the "CAUTION" in the logging section from below the code sample where it's less obvious to directly below the line where we suggest customers do the dangerous thing.
1. Is "If you only want to include logs for azblob, you must create your own logger and set the log classification as LogCredential." still correct?  Why is logging secrets required for blobs?
1. Are there azcore samples with more details on logging that we could link to?  If not, let's file a docs bug against core to include some.

### Provide Feedback
1. Do customers without write access have the ability to assign labels when creating issues?
1. I don't see an `Azure.AzBlob` label in the repo today.

### Contributing
1. Link the repo's contributing.md?  Add your own contributing guide like https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/CONTRIBUTING.md?

**Comment by vibhansa-msft** [comment]
Readme and samples have been updated as per Track-2 guidelines. You can open a fresh one if something needs update in new documents.
