### ISSUE TITLE
Add stable API version for Azure Policy to support non-compliance messages

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/azure-sdk-for-go#16528]
### Feature Request

Please can we add either of the following stable API versions for `services/resources/mgmt` to support Azure Policy non-compliance messages. Currently these only exist in the SDK as preview.

For use in the Terraform provider, where the preference is to use stable API versions as opposed to preview.

Stable policy versions supporting non-compliance messages are:

* 2020-09-01
* 2021-06-01

### Related issues

* #16109

**Comment by Alancere** [comment]
@matt-FFFFFF package-2020-09-01 and package-2021-06-01 are both preview versions, I did not find a stable version about them

**Comment by matt-FFFFFF** [comment]
Thanks for looking. Those API versions work when I do a GET request to the RPs. Is there another dependency that you need that isn't available?

**Comment by lirenhe** [comment]
@matt-FFFFFF, the reason we release preview SDK is that the package definition contains preview freatures https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/readme.md#tag-package-policy-2021-06
We will release stable version when the APIs defined in Microsoft.Authorization/preview/2020-07-01-preview/policyExemptions.json become stable.

**Comment by matt-FFFFFF** [comment]
No problem. Thanks for looking into it!

**Comment by lirenhe** [comment]
Close this item as there is no further action on the SDK side. We are waiting for a stable api version for SDK generation

**Comment by tombuildsstuff** [comment]
@lirenhe where is that request tracked?

**Comment by lirenhe** [comment]
I created https://github.com/Azure/azure-rest-api-specs/issues/17376 to track the request.
