### ISSUE TITLE
[Docs Bug Bash] Feedback on Go Service Bus SDK 

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/azure-sdk-for-go#16521]
Hi,
Below are my feedbacks on Go Service Bus bug bash.  
1. For service bus management plane SDK readme: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/servicebus/armservicebus, it is better that we have samples about how to create a service bus, currently I only find sample code to create a client.
2. For service bus data plane SDK readme: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/README.md, I encountered a compile error for this part: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/README.md#using-a-service-principal. Below line has compile error, after changing `=` to `:=`, it passes compilation.
```go
client, err = azservicebus.NewClient("<ex: myservicebus.servicebus.windows.net>", credential, nil)
```

**Comment by lirenhe** [comment]
@haolingdong-msft, the samples for armservicebus could be found under https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/new-version/servicebus.  We need to improve how users could find samples for GO SDK

**Comment by richardpark-msft** [comment]
I've got a PR to address various readme issues for the `azservicebus` package (ie: data plane):

https://github.com/Azure/azure-sdk-for-go/pull/17009

@lirenhe, is all the feedback above addressed in `armservicebus`? If so, I'll close this issue after my PR merges.

**Comment by lirenhe** [comment]
@richardpark-msft, yes, the feedback for armservicebus is addressed.

**Comment by richardpark-msft** [comment]
Closing, all feedback is addressed.
