### ISSUE TITLE
ML Accounts List function giving error

### ISSUE THREAD

**Issue by anaskhansherwani** [Azure/azure-sdk-for-go#1654]
I am trying to call machine learning experimentation accounts List function. I am using the "github.com/Azure/azure-sdk-for-go/services/machinelearning/mgmt/2017-05-01-preview/experimentation" version.

When I make a call like this:
```
....
result, err := client.List(context.Background())
....
```
I get the following error:

```
experimentation.AccountsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field AccountListResult.value of type experimentation.StorageAccountProperties'
```

I can see in the detailed JSON it returns that storage account is a string ID, however, in models section, Storage Account is a struct with two fields: ID and access key.

**Comment by jhendrixMSFT** [comment]
Hello!  If you have the complete JSON body response handy could you please post it here?  Would help in our investigation.

**Comment by anaskhansherwani** [comment]
This is the complete error I am getting (I replaced id values):

```
panic: experimentation.AccountsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field AccountListResult.value of type experimentation.StorageAccountProperties' JSON = '{
  "value": [
    {
      "id": "/subscriptions/{my-sub-id}/resourceGroups/azure-newnetwork/providers/Microsoft.MachineLearningExperimentation/accounts/AzureML",
      "name": "AzureML",
      "type": "Microsoft.MachineLearningExperimentation/accounts",
      "location": "eastus2",
      "tags": null,
      "etag": null,
      "properties": {
        "state": "Enabled",
        "friendlyName": null,
        "seats": "2",
        "description": null,
        "creationTime": "2018-04-16T11:07:08.0964466+00:00",
        "keyVaultIdentifierId": "",
        "storageAccount": "/subscriptions/{my-sub-id}/resourceGroups/azure-newnetwork/providers/Microsoft.Storage/storageAccounts/azuremlnewstorage",
        "vsoAccountId": "",
        "accountType": "Standard",
        "accountId": "{account-id}",
        "discoveryUrl": "https://eastus2.experiments.azureml.net/discovery"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/{my-sub-id}/resourceGroups/ashley/providers/Microsoft.MachineLearningExperimentation/accounts/myTestExperimentation",
      "name": "myTestExperimentation",
      "type": "Microsoft.MachineLearningExperimentation/accounts",
      "location": "eastus2",
      "tags": null,
      "etag": null,
      "properties": {
        "state": "Enabled",
        "friendlyName": null,
        "seats": "2",
        "description": null,
        "creationTime": "2018-04-19T12:06:01.7400480+00:00",
        "keyVaultIdentifierId": "",
        "storageAccount": "/subscriptions/{my-sub-id}/resourceGroups/azure-newnetwork/providers/Microsoft.Storage/storageAccounts/azuremlnewstorage",
        "vsoAccountId": "",
        "accountType": "Standard",
        "accountId": "{account-id}",
        "discoveryUrl": "https://eastus2.experiments.azureml.net/discovery"
      },
      "identity": null
    }
  ],
  "nextLink": null
}'
```

**Comment by anaskhansherwani** [comment]
I am just wondering, why is it necessary to pass an account to create a new ML Workspace? I cannot find this option from portal, where you can easily create a new workspace. May be I am not understanding the whole workflow here. Whatever is the case, to create a workspace I need a Team Account for which I need a KeyVaultId, VsoAccountId, StorageAccount accessKey. Where do I get these values, if I were to use SDK.

**Comment by jhendrixMSFT** [comment]
@ragargms I believe you own the [machineLearningExperimentation.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearningexperimentation/resource-manager/Microsoft.MachineLearningExperimentation/preview/2017-05-01-preview/machineLearningExperimentation.json) spec.

**Comment by anaskhansherwani** [comment]
Any progress on this issue? I also encountered the same issue upon successful creation of ML Team Account using CreateOrUpdate method.

```
...
result, err := client.CreateOrUpdate(context.Background(),
	"ashley", //resource group name
	"dummyaccount", //account name to be created
	experimentation.Account{
		Name:     to.StringPtr("dummyaccount"),
		Location: to.StringPtr("eastus2"),
		AccountProperties: &experimentation.AccountProperties{
			StorageAccount: &experimentation.StorageAccountProperties{
				//dummy value for storage account id, otherwise exception is thrown
				StorageAccountID: to.StringPtr("/subscriptions/{sub_id}/resourcegroups/ashley/providers/Microsoft.Storage/storageAccounts/dummystorage"),
				//empty key value, otherwise 'value can not be null' exception is thrown
				AccessKey: to.StringPtr(""),
			},
			//dummy vso account id, otherwise exception is thrown
			VsoAccountID: to.StringPtr("/subscriptions/{sub_id}/resourceGroups/ashley/providers/Microsoft.KeyVault/vaults/dummyvso"),
			//dummy key vault id, otherwise exception is thrown
			KeyVaultID: to.StringPtr("/subscriptions/{sub_id}/resourceGroups/ashley/providers/Microsoft.KeyVault/vaults/dummykeyvault"),
		},
	})

if err != nil {
	panic(err.Error())
}
...
```
And the exception I got was similar to above:
```
panic: experimentation.AccountsClient#CreateOrUpdate: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field AccountProperties.storageAccount of type experimentation.StorageAccountProperties' JSON = '{
  "id": "/subscriptions/{sub_id}/resourceGroups/ashley/providers/Microsoft.MachineLearningExperimentation/accounts/dummyaccount",
  "name": "dummyaccount",
  "type": "Microsoft.MachineLearningExperimentation/accounts",
  "location": "eastus2",
  "tags": null,
  "etag": null,
  "properties": {
    "state": "Enabled",
    "friendlyName": null,
    "seats": "2",
    "description": null,
    "creationTime": "2018-04-30T01:06:07.1232314+00:00",
    "keyVaultIdentifierId": "",
    "storageAccount": "/subscriptions/{sub_id}/resourcegroups/ashley/providers/Microsoft.Storage/storageAccounts/dummystorage",
    "vsoAccountId": "/subscriptions/{sub_id}/resourceGroups/ashley/providers/Microsoft.KeyVault/vaults/dummyvso",
    "accountType": "Standard",
    "accountId": "{account_id}",
    "discoveryUrl": "https://eastus2.experiments.azureml.net/discovery"
  },
  "identity": null
}'
```
I also noticed that since properties like KeyVaultId and VsoAccountId are required to create Team Account, passing any dummy values work and account creates successfully (I verified from portal).

Firstly, why is it required to pass KeyVaultId and VsoAccountId in `experimentation.Account.AccountProperties`? Secondly, why it accepts any dummy values? Thirdly, why it fails to unmarshal the response. Are these all bugs, or do they just need a clarification/documentation?

**Comment by anaskhansherwani** [comment]
Is there any progress on this issue? I am thinking of ignoring the exception for now, is this a safe approach?

**Comment by ragargms** [comment]
Hello,

You need a team account in order to create a workspace. This is because workspaces are nested resources under accounts. As for the requirements for key vault, vso and storage account, we had those requirements earlier but key vault and vso got dropped soon after. We will update the model soon. However, you will still need to provide storage account and key for your storage account when you create an experimentation account. You can get the key for storage account from the Azure portal. You can also install machine learning workbench,  https://docs.microsoft.com/en-us/azure/machine-learning/service/quickstart-installation
which gives you a CLI interface to create accounts/workspaces etc.

**Comment by anaskhansherwani** [comment]
@ragargms Thank you for detailed reply. I will try workbench. 

Also, since I am trying to automate these artifacts, is there any way to pro-grammatically create ML Studio workspace and ML model management account? In portal, for example, we have the option to create a studio workspace. Is it possible in Go SDK?

**Comment by ragargms** [comment]
Do you want to create Studio workspace (using Machine Learning Studio workspace) or a workspace within the Machine Learning experimentation account (using Machine Learning Experimentation)? Note: These are two different types of workspaces/resources in Azure. You can automate creation of both. Currently, we do not support Machine Learning Experimentation account workspace creation through portal but you can certainly create these pro-grammatically.

**Comment by anaskhansherwani** [comment]
Yes I know these are different. I want to pro-grammatically create both of these (studio + within experimentation). However, I cannot find support for Studio workspace and model management in SDK. Can you please point out how it this possible using Go SDK.

**Comment by ragargms** [comment]
I see. Here's the swagger for Studio workspace:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearning/resource-manager/Microsoft.MachineLearning/stable/2016-04-01/workspaces.json

I will need to check about model management.

FYI: @hning86

**Comment by anaskhansherwani** [comment]
@ragargms thanks again. This is Rest API. Is it available in sdk as a function? Just like other CreateOrUpdate functions?

**Comment by ragargms** [comment]
Unfortunately not.

**Comment by jhendrixMSFT** [comment]
The fact that this package is missing from the SDK seems to be a bug as there is an entry for it in the config file.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearning/resource-manager/readme.md#tag-package-workspaces-2016-04-and-go
I can build and add this to the SDK unless @ragargms says I shouldn't.

**Comment by jhendrixMSFT** [comment]
@anaskhansherwani In v17.0.0 of the SDK the workspaces package has been added.
https://github.com/Azure/azure-sdk-for-go/tree/master/services/machinelearning/mgmt/2016-04-01/workspaces
Does this resolve your issue?

**Comment by anaskhansherwani** [comment]
@jhendrixMSFT thanks. This solves the problem.

**Comment by jhendrixMSFT** [comment]
Fantastic, thanks for letting me know.
