### ISSUE TITLE
Fix const names so they are consistent

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1659]
Adding in a new const with a name that collides with a preexisting one (usually due to fixing up stuttering but not always) can cause the preexisting ones to have their names change (it's a breaking change that could be avoided).  Here's a great example of that happening.
https://github.com/Azure/azure-sdk-for-go/pull/1652/files
In the v3 generator we solved this by always prefixing the const name with its type name, thus ensuring there can be no conflicts.  It would be a one-time breaking change across the SDK but would eliminate this problem for all future revisions.

**Comment by ArcturusZhang** [comment]
This issue is not resolved, but part of the design now, closing this issue.
