### ISSUE TITLE
[azservicebus] Authorization using Shared Access Signature Token

### ISSUE THREAD

**Issue by balogal** [Azure/azure-sdk-for-go#16641]
### Feature Request

Hi, with other SDKs, e.g. python or C#, I'm able to connect to an Azure Service Bus using a connection string that contains a [shared access signature token](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#generate-a-shared-access-signature-token) for authorization.

if I try to do the same with the `azservicebus` package, I run into the following error

```go
client, err := azservicebus.NewClientFromConnectionString("Endpoint=sb://example.servicebus.windows.net/;SharedAccessSignature=SharedAccessSignature sr=http%3A%2F%2Fexample.servicebus.windows.net%2F&sig=XXXXXXXXXXX&se=1639528312&skn=RootManageSharedAccessKey", nil)
if err != nil {
	panic(err)
}

// panic: key "SharedAccessKeyName" must not be empty
// or alternatively if Name additionally provided: panic: key "SharedAccessKey" must not be empty
```

Am I missing something here, or is there maybe an alternative way to get SAS token based auth working with this SDK? If not, is this feature already on the roadmap? I stumbled upon [#16104](https://github.com/Azure/azure-sdk-for-go/issues/16104), but wasn't sure if it's related.

**Comment by dunnry** [comment]
In the other referenced thread, this was commented on as being planned still.

Is there a workaround today that we could implement while we wait for this?  For instance, how hard would it be to add the CBS claims to another AMQP provider like Qpid Proton?  Has anyone looked at this?  I have only seen this done in the AMQPlite (C#) project.

**Comment by victorien-a** [comment]
I managed!

Just create a new "credential provider" local package. Where you put the code that renews your connection string.

`package sasCredentials

import (
	"context"
	"strconv"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
)

type SasCredential struct {
	cred azcore.TokenCredential
}

func NewSasCredential() (*SasCredential, error) {
	return &SasCredential{}, nil
}

func (c *SasCredential) GetToken(ctx context.Context, opts policy.TokenRequestOptions) (token *azcore.AccessToken, err error) {

	response, err := Some http call to receive your SAS string?
	parsed, err := ParseSig(res.SasToken)
	if err != nil {
		return nil, err
	}
// Parse the expiration time
	expire, err := strconv.ParseInt(parsed.Se, 10, 64)
	if err != nil {
		return nil, err
	}
	tm := time.Unix(expire, 0)
	newToken := &azcore.AccessToken{
		Token:     res.SasToken, // Thats the actual full SAS Token string 
		ExpiresOn: tm,
	}
	return newToken, nil
}

var _ azcore.TokenCredential = (*SasCredential)(nil)
`

Then in the main file. you initialize the client this way:
	credential, err := sasCredentials.NewSasCredential()
	client, err := azservicebus.NewClient("XXXXXXXXXXXXXXX.servicebus.windows.net", credential, nil)

Voila.
