### ISSUE TITLE
User authentication and cache persistence API

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#16643]
Add an `Authenticate` method to user credentials, and persistent token caching options. Looks like this in Python: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/samples/user_authentication.py

~~Blocked on a persistent token cache implementation from MSAL for Go (https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/58).~~

**Comment by camara-tech** [comment]
The mentioned blocker is now implemented here: https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-extensions-for-go/cache.

I'm interested in seeing this moved forward so that tools like AZCopy can support newer authentication mechanisms like  federated credentials

**Comment by chlowell** [comment]
Thanks for pointing this out. I updated the metadata. This feature is almost ready to ship--#21244 and #21245 have the implementation minus a Linux storage implementation which is almost complete but not quite ready for release.
