### ISSUE TITLE
Add spell check for modified files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-go#16658]
Warns on spelling error detection

This change will turn the Analyze pipeline yellow if there is a spelling error detected in a modified file in a PR. It does not block merging and logged warnings will appear in the summary of the pipeline run and in pipeline status emails.

**Comment by RickWinter** [comment]
Seems reasonable to block the PR and require the user to address.  Each file we touch would need to be brought into compliance as we touch them.

**Comment by danieljurek** [comment]
We'll do that in the next phase of the maturity model. That requires scanning the repo, analyzing the detections, cleaning up any obvious false positives, and opening up issues to address... There are other considerations like whether to exclude generated code. 

https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/367/Capabilities-and-State
