### ISSUE TITLE
Polling requests with empty bodies have a content-length set to a different number than 0

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#1666]
But not all of them
I fount the issue with [this operation](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/fe370e65085dcae43d61029af087bff84267022c/compute/compute_test.go#L125).
cc @jhendrixMSFT 

edit (by @marstr): Making link a permalink

**Comment by jhendrixMSFT** [comment]
What is the content-length being set to?  I don't believe any of  the polling requests should have bodies yes?

**Comment by mcardosos** [comment]
I dont believe they should have bodies.
This is the error I get...
`2018/04/20 13:58:51 cannot get the disk update future response: azure#WaitForCompletion: the number of retries has been exceeded: StatusCode=0 -- Original Error: Patch https://management.azure.com/subscriptions/11160a4e-7dc5-4c8e-a9d6-16251e5a4637/resourceGroups/azure-samples-go-CreateVM-XFPmb/providers/Microsoft.Compute/disks/az-samples-go-CCBgeaKEmU_OsDisk_1_bfaa1028922249239a95670fd3966853?api-version=2017-03-30: http: ContentLength=32 with Body length 0
`
