### ISSUE TITLE
Unable to interact with managed HSM using `azkeys` and `azkeys/crypto` packages

### ISSUE THREAD

**Issue by daniel-weisse** [Azure/azure-sdk-for-go#16676]
### Bug Report

- import path of package in question:
  ```Go
  "github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys"
  "github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys/crypto"
  ```
- SDK version: `v60.0.0`
- output of `go version`: `go version go1.17.5 linux/amd64`

I'm trying to create a Key Encryption Key in an Azure managed HSM using the Go SDK.
Once the key is created I want to use the key for key wrapping and unwrapping.

- What happened?
`azkeys.Client.CreateOCTKey`, `crypto.Client.WrapKey`, and `crypto.Client.UnwrapKey` functions fail with the following error:
  ```shell
  response has no WWW-Authenticate header for challenge authentication
  ```

- What did you expect or want to happen?
I am able to create the key, and use the created key, or an already existing key, to perform wrapping and unwrapping operations.

- How can we reproduce it?
Below are three code examples producing the error:

[Key creation](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys@v0.1.0#Client.CreateOCTKey):
```Go
import (
        "context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
  	"github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys"
)

func CreateKey() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}

	client, err := azkeys.NewClient("https://<vault-name>.managedhsm.azure.net/", cred, nil)
	if err != nil {
		panic(err)
	}

	resp, err := client.CreateOCTKey(context.TODO(), "key-encryption-key", &azkeys.CreateOCTKeyOptions{HardwareProtected: true, KeySize: to.Int32Ptr(256)})
	if err != nil {
		panic(err)
	}
	fmt.Println(*resp.Key.ID)
	fmt.Println(*resp.Key.KeyType)
}
```

[Key wrapping/unwrapping](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys@v0.1.0/crypto#Client.UnwrapKey):
```Go
import (
        "context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys/crypto"
	"github.com/Azure/go-autorest/autorest/to"
)

func UnwrapKey() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}

	client, err := crypto.NewClient("https://<vault-name>.managedhsm.azure.net/keys/key-encryption-key/<key-version>", cred, nil)
	if err != nil {
		panic(err)
	}

	keyBytes := []byte("5063e6aaa845f150200547944fd199679c98ed6f99da0a0b2dafeaf1f4684496fd532c1c229968cb9dee44957fcef7ccef59ceda0b362e56bcd78fd3faee5781c623c0bb22b35beabde0664fd30e0e824aba3dd1b0afffc4a3d955ede20cf6a854d52cfd")

	// Wrap
	wrapResp, err := client.WrapKey(context.TODO(), crypto.AES256, keyBytes, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(wrapResp.Result)

	// Unwrap
	unwrapResp, err := client.UnwrapKey(context.TODO(), crypto.AES256, wrapResp.Result, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(unwrapResp.Result)
}
```
Note that there is also a mistake in the documentation for [`crypto.NewClient()`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys@v0.1.0/crypto?utm_source=gopls#NewClient): 
It claims including the key version is not required, however passing `keyURL` without version gives the following error:
```shell
parameter keyVersion cannot be empty
```

- Anything we should know about your environment.
I am trying to run this on my workstation, where I can create keys in the managed HSM using the `az` CLI just fine.
E.g the following runs without errors and successfully creates the key:
  ```shell
  az keyvault key create --id https://<vault-name>.managedhsm.azure.net/keys/key-encryption-key --ops unwrapKey wrapKey --kty oct-HSM --size 256
  ```
  However I am unable to use the key from the Go SDK

Edit: fixed managed HSM vault url in code samples

**Comment by seankane-msft** [comment]
Thanks for reporting this issue @daniel-weisse . Can you try using the `azidentity.NewClientSecretCredential`? I have a PR to update all of our documentation to suggest this as well. The difference between the ClientSecretCredential and DefaultAzureCredential is you will have to specify the tenant ID, client ID, and client secret upon instantiation. 

```go
cred, err := azidentity.NewClientSecretCredential("myTenantID", "myClientID", "myClientSecret", nil)
if err != nil {
    panic(err)
}
```

The PR with the changes is in #16689

**Comment by daniel-weisse** [comment]
Using `azidentiy.NewClientSecretCredential()` I get the following error on `azkeys.Client.CreateOCTKey()`:
```shell
Post "https://<vault-name>.managedhsm.azure.net/keys/key-encryption-key/create?api-version=7.3-preview": http: Request.ContentLength=32 with nil Body
```

A similar Issue is encountered when calling `crypto.Client.WrapKey()` on a key I previously using the Azure CLI:
```shell
Post "https://<vault-name>.managedhsm.azure.net/keys/aesTestKey/c9024cdd0ee70938b9e806545ab5c349/wrapkey?api-version=7.3-preview": http: Request.ContentLength=294 with nil Body
```

**Comment by seankane-msft** [comment]
@daniel-weisse I have a fix for this issue in [this PR](https://github.com/Azure/azure-sdk-for-go/pull/16689). If you would like to try to run from the branch (using a replace directive would be easiest) to confirm that it works for your resources that would be great. If that PR does not work for you instance of Key Vault, you might have a permissions issue. I've been able to use verify my fix for both HSM and regular Key Vault instances. This fix will most likely be published in the beginning of the new year.

**Comment by daniel-weisse** [comment]
Thanks @seankane-msft, using your branch made it work. 
I can create keys and perform wrapping/unwrapping operations. 
I am also able to successfully create and use my client using `azidentity.NewDefaultAzureCredentials(nil)`.

Feel free to close once the change is merged :+1:

**Comment by seankane-msft** [comment]
Glad to hear that @daniel-weisse . I will leave this issue open until the release goes out at which point I'll update this.
