### ISSUE TITLE
Migration doc references missing `arm.NewDefaultConnection`

### ISSUE THREAD

**Issue by andrewbaxter** [Azure/azure-sdk-for-go#16685]
### Bug Report

https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md 

contains the following example:

```
credential, err := azidentity.NewClientSecretCredential("<TenantId>", "<ClientId>", "<ClientSecret>", nil)
connection := arm.NewDefaultConnection(credential, nil)
client := armresources.NewResourceGroupsClient(connection, "<SubscriptionId>")
```

However `NewDefaultConnection` doesn't appear in the code base at this time.

**Comment by jhendrixMSFT** [comment]
Migration guide is updated, thanks for reporting this issue.
