### ISSUE TITLE
amqp[:]link:detach-forced errors (servicebus)

### ISSUE THREAD

**Issue by cghiban** [Azure/azure-sdk-for-go#16695]
Not sure if it's bug, but we're getting these message when we try to send a message:

> link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'G6:73468206:bfuTLxfCTv-vJErFRs2RKNeKGfRKB74MuRl7L47653nVdIPUP4uSOw' is force detached. Code: publisher(link12860924). Details: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00., Info: map[]}

or

> link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link '15CpdZ60BgL-L4Tls0se1k2_PAn4vk8OX7wH_vfQDag_MQnkF8ikGg' is force detached. Code: RenewToken. Details: Unauthorized access. 'Send' claim(s) are required to perform this operation. 

Initially the messages are sent, but after a while we see one of these errors..

If it isn't a bug, how should handle this? Or try reconnecting?

I'm using these packages:

> github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v0.3.2
> github.com/Azure/azure-event-hubs-go/v3 v3.3.17

In the past ( using `github.com/Azure/azure-service-bus-go v0.11.3`) there was a way to recover:

```
        err := q.sender.Send(ctx, &msg)
        if err != nil {
                if err = q.sender.Recover(ctx); err != nil {
                        fmt.Printf("azure.queue.sender: can't recover sender %T - %s", err, err.Error())
                        return "", err
                }
        
                q.sender.Send(ctx, &msg)
                //...
        }
```

Any ideas would help. Thank you

**Comment by richardpark-msft** [comment]
Hi @cghiban, this is a bug on our side - the Sender needs to recover these errors internally. This is one change we're making in the newer SDKs to avoid people having to write recovery code or really inspect the errors by hand.

I'll be working on this.

**Comment by cghiban** [comment]
Thanks, Not to be pushy, but do you have an estimate on when this is going to be fixed?

**Comment by richardpark-msft** [comment]
Sorry about that @cghiban, I had a larger PR that it was part of. I'll pull that out and see if I can merge a mini-version of it for this issue.
