### ISSUE TITLE
How to create Azure AD app using service principal credentials with Microsoft Graph API

### ISSUE THREAD

**Issue by akhilesh2410** [Azure/azure-sdk-for-go#16703]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- I am getting 403 error with below code:
error i am getting 
`error": "graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Unknown\" Message=\"Unknown service error\" Details=[{\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"date\":\"2021-12-23T11:41:23\",\"message\":{\"lang\":\"en\",\"value\":\"Insufficient privileges to complete the operation.\"},\"requestId\":\"f192ac37-8b05-4a81-a582-13f0f5ca3594\"}}]"`

- What did you expect or want to happen?
azure ad app should be created 

- How can we reproduce it?
- Initialize Appclient using below code and call Create() function to create app.
- 	appClient := graphrbac.NewApplicationsClient(tenantID)
	credConfig := auth.NewClientCredentialsConfig(clientID, clientSecret, tenantID)
	//credConfig.Resource = azure.PublicCloud.ResourceIdentifiers.Graph
	credConfig.Resource = "https://graph.microsoft.com"
	authorizer, err := credConfig.Authorizer()
	if err != nil {
		return appClient, err
	}
	appClient.Authorizer = authorizer`

- Anything we should know about your environment.
I have created an Azure AD app using " az ad sp create-for-rbac --sdk-auth --role Owner" command.
Also i have given required api permission as mentioned below:
![api-permission](https://user-images.githubusercontent.com/36051426/147230960-37aa7de2-ef09-4c89-902b-555412acd607.png)

	I am not sure how i can create an Azure AD app client for microsoft Graph API SDK, since there is no method i have found for the same.

**Comment by lirenhe** [comment]
@akhilesh2410, could you check this sample on how to use graphrbac APIs? https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/graphrbac
Please note, Azure AD Graph API is now deprecated and please check this comment:   https://github.com/Azure/azure-sdk-for-python/issues/18131#issuecomment-834861564

Let me know if you have any questions. thanks

**Comment by akhilesh2410** [comment]
Hi @lirenhe ,
Thanks for the reply, but I was earlier using AAD Api for the code mentioned above and it was working fine, but since Azure AD API are deprecated i need to use Microsoft Graph API to create Azure AD App using go sdk. Can we do that using existing code i.e. https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/b49c4162aa1d96bc2b1b42afecbf4a21b420e568/graphrbac/graph.go#L53.
If not then what changes I need to make in code to create Azure AD app using Microsift Graph API ? I did found any code in Microsoft Graph SDK to create an Azure AD APP, or am I missing something ?

Kindly help.

**Comment by lirenhe** [comment]
The sample code will also be deprecated . There is an old issue discussing this https://github.com/Azure/azure-sdk-for-go/issues/7352 and you could find some information there.
So far, GO SDK is not supported in the Code Generator of MS Graph.  I suggest you to communicate with MS Graph team directly.  https://docs.microsoft.com/en-us/answers/topics/128347/microsoft-graph-sdk.html

**Comment by akhilesh2410** [comment]
Thanks for the update, will reach out to MS Graph team.

**Comment by lirenhe** [comment]
@akhilesh2410, just found this library,https://github.com/microsoftgraph/msgraph-sdk-go  and could you have a try?

**Comment by akhilesh2410** [comment]
@lirenhe : I already tried that out and there is nothing I found which we can use to create an app. I am in touch with MS Graph team to get into this issue.
