### ISSUE TITLE
Limit the interface requirement for BlockBlobClient.UploadStreamToBlockBlob body

### ISSUE THREAD

**Issue by radekg** [Azure/azure-sdk-for-go#16714]
### Feature Request

The `body` argument of the `BlockBlobClient.UploadStreamToBlockBlob` method is currently defined as `io.ReadSeekCloser`: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/highlevel.go#L601. It should be `io.Reader` only because:

- the `body` argument is passed to `copyFromReader` as `from io.ReadSeekCloser`: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/highlevel.go#L611
- which uses said `from` as the value of `reader` in the new `copier` instance declaration: https://github.com/Azure/azure-sdk-for-go/blob/9c90938df1e8a1dc239d21679acc32a7d00f4635/sdk/storage/azblob/chunkwriting.go#L53
- the `copier` type declares and accepts `reader` as `io.Reader`

Thus:

- `BlockBlobClient.UploadStreamToBlockBlob` `body` should be `io.Reader`
- `copyFromReader` `from` should be `io.Reader`

Using `io.ReadSeekCloser` is superfluous for those who want to implement their own types to pass as a reader to read from. The expectation is confusing because depending on what one reads from an implementation of `Seek` might be troublesome and _is totally unnecessary_ because `Seek` is never required by the actual `copier`.

I can prepare a PR if this change is acceptable.

**Comment by mohsha-msft** [comment]
Hey @radekg ,

Thanks for reaching out!

We've already addressed this issue.
```golang
func (bb BlockBlobClient) UploadStreamToBlockBlob(ctx context.Context, body io.Reader, o UploadStreamToBlockBlobOptions)
```
Can you please take a pull from `dev-azblob` instead of `main` i.e. `go get github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@dev-azblob`.

Please reach out if you need more clarification on this.

**Comment by radekg** [comment]
Awesome, thank you.
