### ISSUE TITLE
downloadBlobToWriterAt() does not execute Progress() function

### ISSUE THREAD

**Issue by discentem** [Azure/azure-sdk-for-go#16726]
### Bug Report

- Import path: sdk/storage/azblob

but more specifically https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/highlevel.go#L284

- SDK version: master

- What happened?
Setting `Progress` on `HighLevelDownloadFromBlobOptions` for `DownloadBlobToFile` does not work. The function does not appear to get executed. 

I think this is because [`o.Progress(progress) is commented out`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/highlevel.go#L284). Why is it commented out? 😛 And I suspect this would cause `Progress` to get skipped for all `DownloadBlob...` functions.
- What did you expect or want to happen?
Progress function should be executed during Downloads just as it is (working) for uploads. 
- How can we reproduce it?
Clone my project from this specific commit: https://github.com/discentem/bk_azureblob/tree/c063613fcd0f5ce8305734239375e2cf0ace94ac. Edit secrets_example.go with real values for `clientId`, `tenantId`, etc... and build/run it. You'll observe that the `Progress` function works for uploads but not for downloads. 

Download: https://github.com/discentem/bk_azureblob/blob/c063613fcd0f5ce8305734239375e2cf0ace94ac/main.go#L105
Upload: https://github.com/discentem/bk_azureblob/blob/c063613fcd0f5ce8305734239375e2cf0ace94ac/main.go#L128

**Comment by mohsha-msft** [comment]
Hey @discentem ,

Thanks for pointing this out! 
I've merged the changes in our development branch `dev-azblob` and we'll include these changes in the next release. 
Can you please use `dev-azblob` branch in the meantime. i.e. `go get github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@dev-azblob`

**Comment by discentem** [comment]
@mohsha-msft thanks so much for the merge! using `dev-azblob` branch works as expected. Not sure what the protocol here is but you can close the issue if it makes sense. Or will it stay open till the next release?

**Comment by mohsha-msft** [comment]
Hey @discentem ,

Thanks for the confirmation. The issue will stay open till we make next release of  the SDK.
