### ISSUE TITLE
the InternalError can not be converted to "StorageError"

### ISSUE THREAD

**Issue by andyliuliming** [Azure/azure-sdk-for-go#16722]
### Bug Report
get, downloadError := blockBlob.Download(ctx, nil)
stgError := azblob.StorageError{}

if the blob not found, both
errors.As(downloadError, &stgError)
errors.Is(downloadError, &stgError)

will be false.

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by RickWinter** [comment]
You have mentioned the package in question is the previous release of the compute resource manager.  The api you are having trouble with is a storage api, `blockblob.Download`.  Which storage package are you using?

**Comment by jhendrixMSFT** [comment]
This is about `azblob`.  The bug report template wasn't completed.
