### ISSUE TITLE
ContainerProperties values are absent in BlobContainer List and get API

### ISSUE THREAD

**Issue by bigdatasourav** [Azure/azure-sdk-for-go#16751]
### Bug Report

- import path of package in question - `github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-04-01/storage`
- SDK version- `v58.0.0+incompatible` and `v61.0.0+incompatible`
- output of `go version` - 1.17

- What happened? - In BlobContainer List and get API, for ContainerProperties values like `ImmutabilityPolicy`, `Version` always comes as `null` even if the value is associated.
  - Also `RemainingRetentionDays` property comes as `0`, even if it is available with a default value of 7.
ContainerProperties [reference](https://github.com/Azure/azure-sdk-for-go/blob/main/services/storage/mgmt/2021-04-01/storage/models.go#L1483
) 
- What did you expect or want to happen? - The ContainerProperties like `ImmutabilityPolicy`, `Version` and `RemainingRetentionDays` should come if available.
- How can we reproduce it? - Create a storage container and fetch the ContainerProperties.
- Anything we should know about your environment -N/A

**Comment by RickWinter** [comment]
Thank you for reporting this issue.  We will look into the issue.  In the interim you may want to consider switching to our new storage resource manager sdks.  They are currently in preview and will be GA'ing soon.
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/storage/armstorage
