### ISSUE TITLE
Remove the `go_mod_tidy_hack` from mgmt plane packages if possible

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-go#16772]
### Feature Request

The `go_mod_tidy_hack` in our mgmt plane packages and some data plane packages is importing the track 1 package into them to keep we away from the ambiguous import issues. But it is importing a 300M package but it is not actually using it.

We should consider remove it if possible as a refinement

**Comment by lirenhe** [comment]
All mgmt. SDK are refreshed to remove go_mod_tidy_hack
