### ISSUE TITLE
[KeyVault] - Add support for OKP key type

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-go#16775]
...and the EdDSA signature algorithm, when Key Vault supports them.

**Comment by aabkn301** [comment]
:information_source: this feature request will also enable signing with EdSA as we can do right now with KMS? Thx

**Comment by chlowell** [comment]
This will enable `azkeys.Client` to request EdDSA sign/verify from Key Vault.

**Comment by chlowell** [comment]
Moved this to the backlog because we don't know when Key Vault will support this.

**Comment by pallavit** [comment]
@chlowell are you planning to work on this or would @gracewilcox pick this up whenever we decide to do this for Go?

**Comment by chlowell** [comment]
It would be Grace. I reassigned this.
