### ISSUE TITLE
azblob - low memory mode?

### ISSUE THREAD

**Issue by AsafMah** [Azure/azure-sdk-for-go#16783]
azblob used to allocate a static buffer which was hundreds of MB in memory - https://github.com/Azure/azure-storage-blob-go/issues/233

This was solved by adding a TransferManager option - https://github.com/Azure/azure-storage-blob-go/pull/234, and with that a SyncPool type that should save in memory.

That did reduce the memory usage for us from 800mb to ~80mb

But that's still a lot.

Even with the settings of blockSize=1mb and concurrencySize=1, we still get dozens of MB of memory usage just for the SyncPool (see attached profile [profile.zip](https://github.com/Azure/azure-sdk-for-go/files/7837554/profile.zip))

What can we do to reduce the memory usage as much as possible? Preferably only have an overhead of a few MBs

**Comment by zezha-msft** [comment]
Hi @AsafMah, thanks for reaching out!

I took a look at your memory profile and it indeed looks like the sync pool is using more memory than expected.

Have you considered using `NewStaticBuffer` instead? It has a tight control on how much memory is used.
