### ISSUE TITLE
azblob house-keeping

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#16786]
`azblob` is missing an autorest.md file for easy rebuilds.  There is `swagger/README.md` however it's incomplete.

- referenced branch is missing
- swagger reference must be a commit hash, not HEAD

In addition, this is using an old version of the code generator.

**Comment by jhendrixMSFT** [comment]
The change in behavior is by design and comes from the autorest modeler itself (i.e. not the Go code generator) so we can't really fix it.  Ideally the swagger is fixed as the change affects all languages.

That said, there is a switch for M4 to enable the old, broken, behavior.  In the autorest.md file, I think you'd add it like this.

```yml
modelerfour:
  seal-single-value-enum-by-default: true
```

Please note that per the [docs](https://github.com/Azure/autorest/tree/main/packages/extensions/modelerfour), the switch is temporary and will be removed in future versions.  It would be best to fix the swagger.

**Comment by mohsha-msft** [comment]
Hey @jhendrixMSFT ,

[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. I have made necessary changes [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/autorest.md).  

Thanks a lot for your feedbacks!
