### ISSUE TITLE
Ability to change User-Agent for azkeys

### ISSUE THREAD

**Issue by simongottschlag** [Azure/azure-sdk-for-go#16803]
### Feature Request

Hi!

I've been trying to figure out how to set the User-Agent header for the new azkeys client: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/keyvault/azkeys

With the previous client, it was possible using the following:
```go
	err = keyClient.AddToUserAgent("sigstore")
	if err != nil {
		return keyvault.BaseClient{}, err
	}
```

Is there a way to do this today that I am missing?

**Comment by jhendrixMSFT** [comment]
It is a bit different in the new SDKs.  The general pattern is that the clients are created with mandatory/optional params and are then immutable.

When creating the client, the [`ClientOptions`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v0.21.0/policy#ClientOptions) allows you to specify an `ApplicationID` in the [`TelemetryOptions`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v0.21.0/policy#TelemetryOptions).

**Comment by simongottschlag** [comment]
@jhendrixMSFT thanks! I was in there looking, but didn't figure out that the ApplicationID was related to the User-Agent. 😊👍

**Comment by jhendrixMSFT** [comment]
Good point.  I've opened a PR to clarify the doc string.
