### ISSUE TITLE
ContainerClient.GetSASToken doesn't allow list permission

### ISSUE THREAD

**Issue by thomasyip-msft** [Azure/azure-sdk-for-go#16816]
[https://github.com/Azure/azure-sdk-for-go/blob/16752c62d9ad97894169573d56c6c1f5133a5467/sdk/storage/azblob/zc_container_client.go#L220](url)
func (c ContainerClient) GetSASToken(permissions BlobSASPermissions, start time.Time, expiry time.Time) (SASQueryParameters, error) 

Since this getSASToken is at the container level, it should use ContainerSASPermissions instead of BlobSASPermissions so that list permission can be given to the token

**Comment by mohsha-msft** [comment]
@thomasyip-msft , 

Thanks for reaching out! You're right. I'll fix the issue and we'll try include this in the upcoming release

**Comment by mohsha-msft** [comment]
Fixed in `sdk/storage/azblob/v0.3.0`
