### ISSUE TITLE
Inconsistent Tenant Id requirements?

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-sdk-for-go#16819]
### Bug Report

Adal requires "adfs" as tenant Id for an ADFS environment:
https://github.com/Azure/go-autorest/blob/a46566dfcbdc41e736295f94e9f690ceaf50094a/autorest/adal/config.go#L49

Keyvault only allows tenant UUID as tenant Id for an ADFS environment:
https://github.com/Azure/azure-sdk-for-go/blob/292117ae0883b3b8a8b2e2a06648e7ef09edc99e/services/keyvault/mgmt/2019-09-01/keyvault/models.go#L1769

go.mod file:
```
module keyvault

go 1.17

require (
	github.com/Azure/azure-sdk-for-go v61.1.0+incompatible
	github.com/Azure/go-autorest/autorest v0.11.24
	github.com/Azure/go-autorest/autorest/adal v0.9.18
	github.com/Azure/go-autorest/autorest/to v0.4.0
	github.com/gofrs/uuid v4.2.0+incompatible
)

require (
	github.com/Azure/go-autorest v14.2.0+incompatible // indirect
	github.com/Azure/go-autorest/autorest/date v0.3.0 // indirect
	github.com/Azure/go-autorest/autorest/validation v0.3.1 // indirect
	github.com/Azure/go-autorest/logger v0.2.1 // indirect
	github.com/Azure/go-autorest/tracing v0.6.0 // indirect
	github.com/golang-jwt/jwt/v4 v4.2.0 // indirect
	golang.org/x/crypto v0.0.0-20211215153901-e495a2d5b3d3 // indirect
)
```
Golang version: go1.17.6

Running Golang samples using code from go-autorest, the authentication process requires tenant Id using "adfs" for an ADFS Azure Stack environment. Meanwhile, running Key Vault creation such as `VaultProperties` requires tenant UUID for code found in azure-sdk-for-go. They are both tenant ID parameters but have different requirements and are used in similar Azure Golang projects. Is this expected?

Related issue: https://github.com/Azure/ms-rest-nodeauth/issues/132

**Comment by RickWinter** [comment]
We are in the process of updating all the resource manager SDKs in Go.  These are standardized on the azIdentity module for authentication.
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/keyvault/armkeyvault

**Comment by TheOnlyWei** [comment]
Hi @RickWinter, Azure Stack uses Profiles versions:
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-go?view=azs-2108

**Comment by tadelesh** [comment]
@TheOnlyWei As the related issue discussed, it can be more user friendly if we consolidate the type of tenant in keyvault and auth. But I think it will not block user as we can also pass uuid to the auth method for ad treat them as the same, right? As we are working on the new version of the go sdk, the change for the old version may be low priority. @jhendrixMSFT What do you think?

**Comment by TheOnlyWei** [comment]
@tadelesh, yes I agree it is more user friendly if we just used the UUID, but that is not the case currently. But when I pass the UUID as tenant ID, I get error described here:
https://github.com/Azure/azure-sdk-for-go/issues/16820

Note that obviously I cannot pass "adfs" as `TenantID *uuid.UUID` because of type mismatch. But I am not sure if the error is caused by a different issue.

**Comment by tadelesh** [comment]
@jhendrixMSFT From the issue [#16820](https://github.com/Azure/azure-sdk-for-go/issues/16820) solution, it seems customer need to use different value of TenantID when doing auth or calling key vault operation if using `adfs` auth method for azure stack. Is it by design as it may cause some misleading?

**Comment by jhendrixMSFT** [comment]
`TenantID` is generated as a `UUID` as that's what the swagger specifies.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1244-L1248

At this point, I think somebody from the service team needs to chime in about this.

**Comment by RickWinter** [comment]
> `TenantID` is generated as a `UUID` as that's what the swagger specifies.
> 
> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1244-L1248
> 
> At this point, I think somebody from the service team needs to chime in about this.

attn: @RandalliLama , @schaabs , @jlichwa

**Comment by jhendrixMSFT** [comment]
@chlowell do you know who is the current contact for keyvault?

**Comment by jhendrixMSFT** [comment]
This should no longer be an issue in our new ARM modules as UUIDs are simple string types.  You can see this in our new profile module.

https://github.com/Azure/azure-sdk-for-go/blob/main/profile/p20200901/resourcemanager/keyvault/armkeyvault/models.go#L695
