### ISSUE TITLE
Error Creating Key Vault For Azure Stack ADFS Environment

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-sdk-for-go#16820]
### Bug Report

Error thrown from here:
https://github.com/Azure/azure-sdk-for-go/blob/292117ae0883b3b8a8b2e2a06648e7ef09edc99e/services/keyvault/mgmt/2019-09-01/keyvault/vaults.go#L186

Error:
```
2022/01/12 17:28:56 azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to <ARM endpoint URL>/subscriptions/<subscription Id>/resourceGroups/azure-sample-golang-keyvault/providers/Microsoft.KeyVault/vaults/azure-sample-keyvault?api-version=2019-09-01: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>
 Endpoint <ARM endpoint>/<tenant Id>/oauth2/token?api-version=1.0
```

go.mod file:
```
module keyvault

go 1.17

require (
	github.com/Azure/azure-sdk-for-go v61.1.0+incompatible
	github.com/Azure/go-autorest/autorest v0.11.24
	github.com/Azure/go-autorest/autorest/adal v0.9.18
	github.com/Azure/go-autorest/autorest/to v0.4.0
	github.com/gofrs/uuid v4.2.0+incompatible
)

require (
	github.com/Azure/go-autorest v14.2.0+incompatible // indirect
	github.com/Azure/go-autorest/autorest/date v0.3.0 // indirect
	github.com/Azure/go-autorest/autorest/validation v0.3.1 // indirect
	github.com/Azure/go-autorest/logger v0.2.1 // indirect
	github.com/Azure/go-autorest/tracing v0.6.0 // indirect
	github.com/golang-jwt/jwt/v4 v4.2.0 // indirect
	golang.org/x/crypto v0.0.0-20211215153901-e495a2d5b3d3 // indirect
)
```
Golang version: go1.17.6

The error above occurred when creating Key Vault in Azure Stack ADFS environment. I used the tenant UUID as the tenant Id. Usually for ADFS environments, "adfs" is used. Sample usage code:
https://github.com/Azure-Samples/Hybrid-Golang-Samples/blob/03824a553017f2e3dbc63c3b498ad20a2888896e/keyvault/hybridkeyvault/keyvault.go#L41

Note that this bug might be related to the solution of this other bug that I created:
https://github.com/Azure/azure-sdk-for-go/issues/16819

**Comment by RickWinter** [comment]
Have you tried your code with the latest resource manager sdks?
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/keyvault/armkeyvault

**Comment by TheOnlyWei** [comment]
Hi @RickWinter, we usually don't use the latest SDK resource manager versions for Azure Stack. Profile versions are used for Azure Stack according to this documentation:
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-go?view=azs-2108

**Comment by tadelesh** [comment]
Related with this [issue](https://github.com/Azure/azure-sdk-for-go/issues/16819).

**Comment by tadelesh** [comment]
@TheOnlyWei It seems related to auth progress. Could you please paste the auth code here?

**Comment by TheOnlyWei** [comment]
@tadelesh The auth is also in the sample:
Getting Key Vault Client
https://github.com/Azure-Samples/Hybrid-Golang-Samples/blob/03824a553017f2e3dbc63c3b498ad20a2888896e/keyvault/hybridkeyvault/keyvault.go#L21

Getting Token
https://github.com/Azure-Samples/Hybrid-Golang-Samples/blob/03824a553017f2e3dbc63c3b498ad20a2888896e/keyvault/iam/oath.go#L28

**Comment by tadelesh** [comment]
@TheOnlyWei Have you tried to use "adfs" to check whether the token fresh step is success?

**Comment by TheOnlyWei** [comment]
@tadelesh that is what I am using.

https://github.com/Azure-Samples/Hybrid-Golang-Samples/blob/03824a553017f2e3dbc63c3b498ad20a2888896e/keyvault/app.go#L59

**Comment by TheOnlyWei** [comment]
@tadelesh Seems passing "adfs" as tenant ID resolved the issue. So for that function I needed both versions of tenant ID, the "adfs" string and the tenant UUID. Still not sure why we need both versions, which is related to the issue https://github.com/Azure/azure-sdk-for-go/issues/16819.

https://github.com/Azure-Samples/Hybrid-Golang-Samples/blob/80fc40684cc0b4c0ede358cbc2872b67b53c679c/keyvault/hybridkeyvault/keyvault.go#L33

**Comment by tadelesh** [comment]
@TheOnlyWei Thanks for the feedback. We may continue with the discussion of discrepancy at [#16819](https://github.com/Azure/azure-sdk-for-go/issues/16819).
