### ISSUE TITLE
Review for renaming of stuttering collision of GO track2 SDK 

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-sdk-for-go#16854]
I think as part of this exercise we’ll need to distill what exactly that guideline is.  We don’t have one in place as originally we weren’t planning on removing stuttering.

I need to look at these in more detail, but my knee-jerk is that we shouldn’t be renaming the ones where the names had stuttering removed.  i.e. ‘DataBoxJobDetails’ => ‘JobDetails’ should remain ‘JobDetails’ so that its fully qualified name is ‘databox.JobDetails’ (this matches what the swagger was conveying).  We should instead rename the thing it collides with, i.e. ‘JobDetails’ is renamed to something slightly different.

-Joel

Subject: RE: Review for renaming of stuttering collision of GO track2 SDK 

It would be great if we can base our decisions on guidelines.  

FWIW I’m not a big fan of shuffling AaBb into BbForAa.  Personally I’d rather stutter than name it like that.
Ex:
from: 'DataBoxJobDetails'
to: 'JobDetailsForDataBox'

_rick

Subject: Review for renaming of stuttering collision of GO track2 SDK 

Hi all,

As stuttering removing has been introduced into the latest autorest.go to make GO track2 API more idiomatic, we have encountered some collision for some existed models or clients. To let the renaming more reliable, we’d like to have a quick review through the mail. I’ve listed all such renaming in current preview GO SDKs with directives and the collision type in the following table. If any suggestion, please feel free to reply directly. Thanks.

rp	directive	type
cdn	directive:
- rename-model:
    from: 'CdnEndpoint'
    to: 'EndpointForCdn'	model collision
databox	directive:
- rename-model:
    from: 'DataBoxJobDetails'
    to: 'JobDetailsForDataBox'
- rename-model:
    from: 'DataboxJobSecrets'
    to: 'JobSecretsForDatabox'
- rename-model:
    from: 'DataBoxScheduleAvailabilityRequest'
    to: 'ScheduleAvailabilityRequestForDataBox'	model collision
databoxedge	directive:
- rename-model:
    from: 'DataBoxEdgeSku'
    to: 'SkuForDataBoxEdge'
- rename-model:
    from: 'DataBoxEdgeSkuList'
    to: 'SkuForDataBoxEdgeList'	model collision
guestconfiguration	directive:
- rename-model:
    from: 'AssignmentReport'
    to: 'BasicAssignmentReport'	model collision
labservices	directive:
- rename-model:
    from: 'LabServicesSku'
    to: 'SkuForLabServices'	model collision
redis	directive:
- rename-model:
   from: 'RedisResource'
   to: 'ResourceForRedis'	model collision
security	directive:
- from: swagger-document
  where: '$.paths.*[?(@.operationId.startsWith("SecurityConnectors_"))]'
  transform: >
    $["operationId"] = $["operationId"].replace("SecurityConnectors_", "ConnectorsForSecurity_");	operation group collision
signalr	directive:
- rename-model:
    from: 'SignalRResource'
    to: 'ResourceForSignalR'
- rename-model:
    from: 'SignalRResourceList'
    to: 'ResourceForSignalRList'	model collision
videoanalyzer	directive:
- rename-model:
    from: 'Properties'
    to: 'MetricProperties'
- from: swagger-document
  where: '$.paths.*[?(@.operationId.startsWith("VideoAnalyzerOperationStatuses_"))]'
  transform: >
    $["operationId"] = $["operationId"].replace("VideoAnalyzerOperationStatuses_", "OperationStatusesForVideoAnalyzer_")
- from: swagger-document
  where: '$.paths.*[?(@.operationId.startsWith("VideoAnalyzerOperationResults_"))]'
  transform: >
    $["operationId"] = $["operationId"].replace("VideoAnalyzerOperationResults_", "OperationResultsForVideoAnalyzer_")	operation group collision
model collision
webpubsub	directive:
- rename-model:
    from: 'WebPubSubResource'
    to: 'ResourceForWebPubSub'	model collision
web (appservice)	directive:
- rename-model:
    from: 'AppServiceCertificate'
    to: 'CertificateForAppService'
- rename-model:
    from: 'AppServiceCertificateCollection'
    to: 'CertificateCollectionForAppService'
- rename-model:
    from: 'AppServiceCertificatePatchResource'
    to: 'CertificatePatchResourceForAppService'	model collision

Regards,
Chenjie Shi

**Comment by jhendrixMSFT** [comment]
The guiding principle should be that the type that was renamed to not stutter should _not_ further be renamed to avoid a name collision.

Using DataBoxEdge as the example, there are types "DataBoxEdgeSku" and "Sku".  The former type is renamed to "Sku" to avoid stuttering which collides with the preexisting "Sku" type.  To avoid the collision, the preexisting "Sku" type should be appropriately renamed (e.g. maybe "SkuInfo" or "SkuData").  So the resulting codegen would look like this.

```go
package databoxedge

// SKU was renamed from DataBoxEdgeSku to not stutter.
type SKU struct { /*...*/ }

// SKUInfo was renamed via an Autorest directive to avoid colliding with SKU
type SKUInfo struct { /*...*/ }
```

**Comment by tadelesh** [comment]
Update for the renaming:

**cdn**
directive:
- rename-model:
    from: 'CdnEndpoint'
    to: 'LinkedEndpoint'

**databox**
directive:
- rename-model:
    from: 'JobDetails'
    to: 'BaseJobDetails'
- rename-model:
    from: 'JobSecrets'
    to: 'BaseJobSecrets'
- rename-model:
    from: 'ScheduleAvailabilityRequest'
    to: 'BaseScheduleAvailabilityRequest'

**databoxedge**
directive:
- rename-model:
    from: 'Sku'
    to: 'SkuType'

**guestconfiguration**
directive:
- rename-model:
    from: 'AssignmentReport'
    to: 'BaseAssignmentReport'

**labservices**
directive:
- rename-model:
    from: 'LabServicesSku'
    to: 'ExtendedSku'
- rename-model:
    from: 'PagedLabServicesSkus'
    to: 'PagedExtendedSkus'

**redis**
directive:
- rename-model:
   from: 'RedisResource'
   to: 'ResourceForRedis'

**security**
directive:
- from: swagger-document
  where: '$.paths.*[?(@.operationId.startsWith("Connectors_"))]'
  transform: >
    $["operationId"] = $["operationId"].replace("Connectors_", "AccountConnectors_");

**signalr**
directive:
- rename-model:
    from: 'SignalRResource'
    to: 'ResourceForSignalR'
- rename-model:
    from: 'SignalRResourceList'
    to: 'ResourceForSignalRList'

**videoanalyzer**
directive:
- rename-model:
    from: 'Properties'
    to: 'MetricProperties'
- from: swagger-document
  where: '$.paths.*[?(@.operationId.startsWith("OperationStatuses_"))]'
  transform: >
    $["operationId"] = $["operationId"].replace("OperationStatuses_", "PrivateEndpointConnectionsOperationStatuses_")
- from: swagger-document
  where: '$.paths.*[?(@.operationId.startsWith("OperationResults_"))]'
  transform: >
    $["operationId"] = $["operationId"].replace("OperationResults_", "PrivateEndpointConnectionsOperationResults_")

**webpubsub**
directive:
- rename-model:
    from: 'WebPubSubResource'
    to: 'ResourceForWebPubSub'
- rename-model:
    from: 'WebPubSubResourceList'
    to: 'ResourceForWebPubSubList'

**web (appservice)**
directive:
- rename-model:
    from: 'Certificate'
    to: 'AppCertificate'
- rename-model:
    from: 'CertificateCollection'
    to: 'AppCertificateCollection'
- rename-model:
    from: 'AppServiceCertificatePatchResource'
    to: 'AppCertificatePatchResource'

**Comment by jhendrixMSFT** [comment]
This has been resolved.
