### ISSUE TITLE
Should pageable operations return a Response/error like non-pageable operations

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#16872]
It’s an interesting point, and comes at a good time as we’re thinking about making some slight changes to the Pager types.

I was going to say that changing an operation from non-paged to paged is a breaking change.  But I suppose it doesn’t have to be.

I assume this is the case where some swagger forgot to annotate the operation as x-ms-pageable so it only returns the first page?  Or are there other scenarios?

@JeffreyRichter what do you think?

-Joel

Hi Joel, I notice the pageable operations and non-pageable operations generate different code. The pageable operation will generate a Pager struct, and the corresponding function will return this Pager. But if the operation is non-pageable, it will return the actual underlying struct (XXXListResult, error). This introduces inconsistency to customers and there will be breaking changes when service team convert an operation to pageable in a new api-version. Wrapping it will benefit our effect to control the major versions.

What do you think? We are doing this in DotNet mgmt. SDKs.

Thanks,
Dapeng Zhang

**Comment by jhendrixMSFT** [comment]
One downside I see is that this adds some complexity to the calling code as you now have to handle the error in two places.
```go
resp, err := client.ListPages(ctx, nil)
if err != nil {
  panic(err)
}
for resp.Pager.NextPage(ctx) {
  // use page
}
if resp.Pager.Err() != nil {
  panic(err)
}
```

**Comment by JeffreyRichter** [comment]
It is breaking for a non-pageable operation to change to pageable. Azure services should never do this. Having a different programming model pattern IS desired because it is different. LROs also have a different programming model and this is also desired.

**Comment by JeffreyRichter** [comment]
Also, we don't want 2 errors to deal with.
