### ISSUE TITLE
Add automation to upgrade codegen/testgen version

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#16879]
### Feature Request

Adding some automation that will submit a PR to increment codegen/testgen version in eng scripts whenever a new version is published

**Comment by weshaggard** [comment]
As a reference the autorest.csharp update happens as part of their release pipeline https://github.com/Azure/autorest.csharp/blob/feature/v3/eng/pipelines/build.yml#L129.
