### ISSUE TITLE
[Redis Cache] Managed Identity Support for Service and backups

### ISSUE THREAD

**Issue by adamyager** [Azure/azure-sdk-for-go#16909]
### Feature Request
Now that Redis Support Managed Identity, we need to be able to configure this via the API. In addition, and part of this, the persistence feature today can only use storage account keys via the API but can now leverage the same managed identity
There are other benefits in the release below.

**Comment by tombuildsstuff** [comment]
@Alancere was this work completed?

**Comment by Alancere** [comment]
yes, released https://github.com/Azure/azure-sdk-for-go/releases/tag/v62.1.0
