### ISSUE TITLE
azblob - implement UserDelegationCredential

### ISSUE THREAD

**Issue by alexg-axis** [Azure/azure-sdk-for-go#16916]
### Feature Request

This feature request is for the "new" `azblob` package.

#### Background

In order to create a SAS token, one uses the `azblob.BlobSASSignatureValues.NewSASQueryParameters` function:

https://github.com/Azure/azure-sdk-for-go/blob/8c965f7cbb93f9fdf1fec8df5416f193e0bd465e/sdk/storage/azblob/zc_sas_service.go#L33-L36

It specifies that it is compatible with `UserDelegationCredential`. This seems to be left from before the SDK was imported. There seems to be no `UserDelegationCredential` anywhere in this repository, in fact.

#### Request

It's quite the hassle to fetch a user delegation key and then manually create the final SAS token.

I request a feature to easily create a `UserDelegationCredential` for use with `NewSASQueryParameters` so that a delegated SAS token can be created using the SDK.

**Comment by mohsha-msft** [comment]
Hey @alexg-axis,

Thanks for reaching out!
We're planning to add that feature in march release most likely!

**Comment by alexg-axis** [comment]
@mohsha-msft Is it still planned for release in March?

**Comment by mt35-rs** [comment]
I also need this functionality.  We are trying to obey the "principle of least privilege" here, but not being able to (easily) work with service principals makes this really difficult.  Having to use a very privileged access key to create signed URLs seems totally backward.

**Comment by abdullah-lt** [comment]
Hi. Is there any update on this? 
Is there a way where I can generate SAS token without  SharedKeyCredential  as this requires the use of storage account key. But I want to use manage identity with `NewDefaultAzureCredential`

**Comment by alexg-axis** [comment]
@mohsha-msft Hi! Is there any timeline on when this will be fixed?

**Comment by zezha-msft** [comment]
Update: this feature is being actively worked on here -> https://github.com/Azure/azure-sdk-for-go/pull/19141

**Comment by siminsavani-msft** [comment]
Hi @alexg-axis ! We have released the User Delegation feature (https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv0.5.0) today. Please give it a try and let us know if you have any questions!

Examples can be found here:
https://github.com/Azure/azure-sdk-for-go/blob/7a3989f70fa6c2d4376d0c72c01b5afc32b527f7/sdk/storage/azblob/service/examples_test.go#L286
