### ISSUE TITLE
Azure storage account list result return empty when object is marshalled

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#16914]
Bug report

following function should be removed.

https://github.com/Azure/azure-sdk-for-go/blob/7327e7c8961c371a6bcb300bda711717e9f00cb6/services/storage/mgmt/2019-06-01/storage/models.go#L336-L339

**Comment by MartinForReal** [comment]
checked release note and found following comments:
https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md#v5500

**Comment by tadelesh** [comment]
@MartinForReal Yes, it is by design. As all the result param is read-only, it will marshal to an empty object when doing request.

**Comment by tadelesh** [comment]
@MartinForReal Does this change block your upgrade? I guess you want to marshal it completely in your own code instead of we try to ignore all the read-only param in the SDK request.

**Comment by MartinForReal** [comment]
yes. It's blocking my upgrade.

**Comment by MartinForReal** [comment]
I cherrypicked a workround and get pr merged. 
Thanks for following up. @tadelesh

**Comment by tadelesh** [comment]
@MartinForReal We are working on the new version of GO SDK (packages [here](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager), quick start [here](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-quickstart.md), migration guide [here](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md)) which has resolved such problem and will have more idiomatic features. We'll appreciate if you could have a try and give feedback. Thanks.
