### ISSUE TITLE
[azservicebus] Update nhooyr/websocket once it moves to the next rev (test dep only)

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#16924]
We use the nhooyr/websocket package as part of our examples/tests (only). It needs to update to the latest gin-gonic for a security update, which is getting flagged on our side by dependabot. Once this PR merges we should be okay to update:

https://github.com/nhooyr/websocket/pull/310

**Comment by richardpark-msft** [comment]
A little note about this - some systems might incorrectly flag this if they see the transitive oudated gin-gonic dependency show up in their go.sum file. If you run `go list -m all`, however, you'll see that the `replace` we've added in does properly force the version to be the patched gin-gonic.

So this is cosmetic and annoying, but not customer affecting.

**Comment by lpWeaveIndia** [comment]
Hey, 
We're using this library. In our case, websocket get's closed for some reason (don't know) and then receiver timed-out.
`failed to get reader: WebSocket closed: read timed out: context canceled`

Is that something related to this issue?

**Comment by richardpark-msft** [comment]
@lpWeaveIndia - I don't believe so. The release that's pending was to update an outdated dependency for security, not stability.

Is this with the Azure Service Bus SDK? If so, please feel free to file an issue - it'll walk you through what we need to troubleshoot.

**Comment by lpWeaveIndia** [comment]
> Is this with the Azure Service Bus SDK? 

Yeah, It's with `Azure Service Bus SDK` when trying to receive messages.

**Comment by richardpark-msft** [comment]
> > Is this with the Azure Service Bus SDK?
> 
> Yeah, It's with `Azure Service Bus SDK` when trying to receive messages.

Ah, okay. Can you file an issue and we can start troubleshooting what's going on.

**Comment by richardpark-msft** [comment]
There's an updated version of the websocket package so I was able to update in PR#20335. However, on Event Hubs, we're getting an issue when closing the websocket, which causes it to return "failed to close WebSocket: failed to read frame header: EOF". So won't close this entirely until we figure out what's going on there.
