### ISSUE TITLE
azblob: wrong example in error casting for StorageError

### ISSUE THREAD

**Issue by bcho** [Azure/azure-sdk-for-go#16920]
### Bug Report

- import path of package in question:`.../sdk/storage/azblob`
- SDK version: `main`
- output of `go version`: `go version go1.17.3 darwin/amd64`

- What happened?

In [zt_examples_test](https://github.com/Azure/azure-sdk-for-go/blob/916bcb2ef21f111dfde135817e902f9f0116cd3e/sdk/storage/azblob/zt_examples_test.go#L183), the doc states that we can extract the `StorageError` from response as:

https://github.com/Azure/azure-sdk-for-go/blob/916bcb2ef21f111dfde135817e902f9f0116cd3e/sdk/storage/azblob/zt_examples_test.go#L183-L187

However, this is not valid in current implementation, since we are returning the `StorageError` with pointer value in `handleError`:

https://github.com/Azure/azure-sdk-for-go/blob/916bcb2ef21f111dfde135817e902f9f0116cd3e/sdk/storage/azblob/zc_storage_error.go#L62-L65

I am also confused that, why we are declaring the `StorageError` struct itself as an error, but returning a pointer in `handleError`? Why not just declare the `*StorageError` as error and pass this pointer around?

- What did you expect or want to happen?

We should update the doc (but IMO updating the error interface for `StorageError` is better) to:

```go
		var stgErr *StorageError

		if errors.As(err, &stgErr) { // We know this error is service-specific
			switch stgErr.ErrorCode {
			case StorageErrorCodeContainerAlreadyExists:
```

- How can we reproduce it?

```go
internalErr := &InternalError{
  cause: &StorageError{},
}

{
    var target StorageError
    fmt.Println(errors.As(internalErr, &target))
}

{
    var target *StorageError
    fmt.Println(errors.As(internalErr, &target))
}
```

- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Failed operations now return an `*azcore.ResponseError`, and there is a helper `bloberror.HasCode()` to check for specific storage error codes.
