### ISSUE TITLE
Return confidence levels for text OCR in cognitive services go SDK

### ISSUE THREAD

**Issue by kynrai** [Azure/azure-sdk-for-go#16957]
### Feature Request

The API for cognitive services returns word confidences, but the go SDK returns a enum with High or Low,

https://github.com/Azure/azure-sdk-for-go/blob/main/services/cognitiveservices/v2.1/computervision/models.go#L526

This differs from the return spec in the docs and I would even argue High/Low is not as useful the percentage confidence as High/Low is subjective and can be easily derived from the confidence percentage but not vice versa.

It should be clear how to get the confidence values from the SDK.

**Comment by jhendrixMSFT** [comment]
This is based on the older cognitive services version which returned a confidence level instead of a floating-point value (introduced in v3.0).

@RickWinter do we have a plan for releasing new SDKs for CS?

**Comment by RickWinter** [comment]
Adding @achandmsft to comment on the CS SDK roadmap
