### ISSUE TITLE
Should all APIs in core return an error even if it's presently unused

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#16964]
For versioning tolerance, seems like we should have all core APIs return `(foo, error)` to accommodate future error expansion.  We document the APIs where `error` is always `nil`.

**Comment by JeffreyRichter** [comment]
I'd prefer not to do this. Returning (foo, error) hurts usability dramatically: variables must be defined, an if is required and you can't dot-compose the result with anything. 

The result is part of the method's contract. When creating a contract, if we think we can live forever with returning a single value, we should opt for this. I think there are many methods where this is true. If we can't do this, then yes, (foo, error) is the way we have to go.

**Comment by jhendrixMSFT** [comment]
I agree.  I only bring this up as the recent work for the `cloud` package required a few breaking changes to some constructors.

We could avoid this by adding a new API side-by-side with the new behavior.

**Comment by richardpark-msft** [comment]
I feel like this mildly bit us with UUID generation where we weren't sure what to do with the "rand fails" error. 

Just curious what APIs you're thinking of here. Are there some that might need the error? And if we did need to add some function side-by-side would it be similar to regexp.Compile/MustCompile?

**Comment by jhendrixMSFT** [comment]
The feature for the `cloud` package required that pipeline's constructor return an error (it doesn't at present).  This makes me wonder if future feature work might require a similar change (e.g. tracing).

I don't think that the MustCompile pattern would be good here, as it means that something that was previously no-fail now has the potential to panic.

In some cases, you might be able to rework a feature in such a way to avoid introducing the need for returning an error.  I don't think this will be possible in all cases though and might lead to some awkward code.

**Comment by JeffreyRichter** [comment]
I took at the crypto Rand Read function to see why it returns an error. My strong belief is that it never will. The reason its signature returns an error is because the Read method implements the io.Reader interface whose Read method returns an error. So, this was done to match the interface and I strongly believe that it will ALWAYS return a nil error.

**Comment by jhendrixMSFT** [comment]
To clarify, I was thinking about the APIs under `azcore/runtime` and `azcore/arm/runtime` that are mostly used by generated code.

I took a look at those APIs, the only ones that don't are `NewPipeline()` and the various constructors for the pipeline policies.

**Comment by jhendrixMSFT** [comment]
Not going to do this.
