### ISSUE TITLE
azblob constructors should return clients by reference

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#16972]
That is to say, they should return a pointer to a client instance. They currently return an instance by value. For example:
https://github.com/Azure/azure-sdk-for-go/blob/63f64be5fb3cd021b6064e8b0f20eb7746b53017/sdk/storage/azblob/zc_blob_client.go#L22

**Comment by mohsha-msft** [comment]
Hey @chlowell ,

[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. I have made the necessary changes.

Thanks a lot for your feedbacks!
