### ISSUE TITLE
Revert fork of gocov in CI once the original has been updated for generics

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#16982]
Tracking issue to back out various temporary changes in CI that were necessary for generics bring-up.

**Comment by jhendrixMSFT** [comment]
- https://github.com/Azure/azure-sdk-for-go/pull/16975
 - https://github.com/Azure/azure-sdk-for-go/pull/16979

**Comment by jhendrixMSFT** [comment]
Most of this has been cleaned up.  The remaining bit is the fork of `gocov`.

**Comment by RickWinter** [comment]
@jhendrixMSFT Should the title be changed to "remove gocov private fork"?   That's all that's left right?

**Comment by jhendrixMSFT** [comment]
Done
