### ISSUE TITLE
errors.As fails to match any error in the chain of *azblob.InternalError with azcore.HTTPResponse or azblob.StorageError

### ISSUE THREAD

**Issue by ArnavPrasadMicrosoft** [Azure/azure-sdk-for-go#16987]
### Bug Report

- path of package in question: `https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob`
- SDK version: `0.2.0`
- output of `go version`: 1.16

- What happened?
  - I was trying to check for a "BlobAlreadyExists" error in my project through the following piece of code:
```golang // Simulating a "BlobAlreadyExists" error using IfNoneMatch="*" option.
_, err = blockBlobClient.UploadBufferToBlockBlob(ctx, data, highLevelUploadToBlockBlobOption)
if err != nil {
  // This log gets printed.
  log.WithContext(ctx).Errorf("Error while uploading buffer to block blob: %v (%T)", err, err) // Type is (*azblob.InternalError)
  var errResp azcore.HTTPResponse
  var storageErr azblob.StorageError
  if errors.As(err, &errResp) {
    // This log does not get printed.
    log.WithContext(ctx).Errorf("Caught response error: %v, status code: %d", errResp.RawResponse(), errResp.RawResponse().StatusCode)
  }
  if errors.As(err, &storageErr) {
    // This log does not get printed either.
    log.WithContext(ctx).Errorf("Caught storage error: %v", storageErr)
  }
}
```
  - Currently, the generated azblob code that actually sends requests returns azcore.HTTPResponse when something goes wrong, but the handwritten code converts that to another type which doesn't expose the response: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/zc_storage_error.go#L76

**Comment by ezavgorodniy** [comment]
Yes, and related issue was closed due to inactivity :(

**Comment by joey-laminar** [comment]
Came upon this issue too, the solution was to define storageErr as a pointer:

```
var storageErr *azblob.StorageError
  if errors.As(err, &storageErr) {
    log.WithContext(ctx).Errorf("Caught storage error: %v", storageErr)
  }

```

**Comment by tasherif-msft** [comment]
Hi @ArnavPrasadMicrosoft!
Azure Core introduced https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/errors.go#L14 which can be cast using:
```
var responseErr *azcore.ResponseError
errors.As(err, &responseErr)
```
Let me know if solves the issue. 
I will close this in the meantime.

**Comment by jhendrixMSFT** [comment]
This is correct.  However, we haven't yet released an updated `azblob` that returns this error type.

**Comment by tasherif-msft** [comment]
@jhendrixMSFT you're correct, I have reopened the issue and updated my comment that this change should be available in the next release

**Comment by jhendrixMSFT** [comment]
This change has now been deployed in `azblob@v0.5.0`
