### ISSUE TITLE
Support for SQL Managed Instance - User Assigned Managed Identity

### ISSUE THREAD

**Issue by mdrakiburrahman** [Azure/azure-sdk-for-go#16998]
SQL Managed Instance now supports [User Assigned Managed Identity](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity). This feature is especially great because for Azure AD login, Customers can provide the UAMI [minimum reqd permissions](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity#permissions) one-time, and manage the lifecycle of the UAMI outside the MI lifecycle (allowing for synchronous onboarding to Azure AD rather than waiting for SAMI onboarding).

We are trying to onboard this into the Terraform Custom provider, before realizing that the AzureRM GO SDK doesn't support this feature yet. To be clear:
* it is possible to create a SQL MI with SystemAssigned Identity via REST API
* it is possible to create a SQL MI with UserAssigned Identity via REST API
* it is not possible to create a SQL MI with UserAssigned ánd SystemAssigned at the same time via the Go SDK

[Terraform Issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/15277).

Looking through `sql/mgmt/models.go` - I think UAMI support should be a fairly trivial but extremely beneficial feature to enable: https://github.com/Azure/azure-sdk-for-go/blob/ec2ed6d8450ad53978efa96822bf9c9431a63ab4/profiles/preview/preview/sql/mgmt/sql/models.go#L40

| Someone needs to update this^ to include UserAssigned as well

**Comment by aristosvo** [comment]
> it is not possible to create a SQL MI with UserAssigned Identity via the Go SDK

I think we should change this to ‘UserAssigned ánd SystemAssigned at the same time’

**Comment by mdrakiburrahman** [comment]
> > it is not possible to create a SQL MI with UserAssigned Identity via the Go SDK
> 
> I think we should change this to ‘UserAssigned ánd SystemAssigned at the same time’

Updated issue

**Comment by tombuildsstuff** [comment]
@aristosvo @mdrakiburrahman just to confirm, is it possible to create both at the same time using the API? The API would need to support "SystemAssigned, UserAssigned" if not

**Comment by aristosvo** [comment]
As far as I see it is supported in the spec. Might be wrong here, but the `ResourceIdentity` supports both at the same time.

**Comment by mdrakiburrahman** [comment]
Hey @tombuildsstuff, @aristosvo  - yea you can. So what happens is, when you create a SQL MI named `aiasqlmisvr01`, Azure already gives it a `SystemAssigned` Identity in Azure AD by default, without you doing anything, also named `aiasqlmisvr01`.

So then what you can do - prior to the SQL MI deployment, is create a `UserAssigned` Managed Identity (external to your creation of the SQL MI, you just create a UAMI like so: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp#create-a-user-assigned-managed-identity

And then, you can _assign_ this UAMI's unique identifier (`clientID/objectID`) to the SQL MI - so you end up with something like this:
![image](https://user-images.githubusercontent.com/46581776/152998566-3f7cf1ef-ed34-4324-9baa-15d46aaedfd3.png)

The reason this UAMI is extremely useful, is because Customers can give this access to read Azure AD ahead of time, so you can **synchronously** onboard the SQL MI to Azure AD Auth.

Previously, with just SAMI, this was an **async** process, because after the SQL MI SAMI creation, some Azure AD Admin would take several days to add the newly created SAMI to Azure AD - which is an operational nightmare.

So:
1. Azure SDK for GO needs to support the flow above, user passed in SAMI to SQL MI
2. Terraform consumes this capability

**Comment by ericshape** [comment]
PR: https://github.com/Azure/azure-rest-api-specs/pull/18467
