### ISSUE TITLE
Validate Azure UUUID

### ISSUE THREAD

**Issue by RafaelTomelin** [Azure/azure-sdk-for-go#16997]
Hi, 

Can I validate if Azure UUID is correct?

I creating inventory system with input and collect in Azure and when I'm going to collect or create Azure resource I need validate the UUID is validate.

Is possible to create a UUID with the Azure package and use this UUID with an index of my DB?

**Comment by jhendrixMSFT** [comment]
We don't provide any facilities for generating UUIDs as there are multiple packages available that do this, and we didn't want to favor any specific implementation as that doesn't always match with what existing codebases use.

Take a look at [these results](https://pkg.go.dev/search?q=uuid) for some popular implementations.
