### ISSUE TITLE
Azure Automation change tracking and inventory feature GO SDK support

### ISSUE THREAD

**Issue by balann** [Azure/azure-sdk-for-go#17000]
### Service Package Request

Is there any API or azure-sdk-for-go support  available for Azure Automation change tracking and inventory feature?

**Comment by Alancere** [comment]
Based on the information available, it does not appear that there is a specific API or azure-sdk-for-go support available for the Azure Automation change tracking and inventory feature. However, you can use Azure PowerShell or Azure CLI to manage Change Tracking and Inventory.

For more information, you can refer to the following resources:
[Change Tracking and Inventory overview](https://learn.microsoft.com/en-us/azure/automation/change-tracking/overview?wt.mc_id=knwlserapi_inproduct_azportal)
[Enable Change Tracking and Inventory from an Automation account](https://learn.microsoft.com/en-us/azure/automation/change-tracking/enable-from-automation-account?wt.mc_id=knwlserapi_inproduct_azportal#enable-change-tracking-and-inventory-from-an-automation-account)
[Manage Change Tracking and Inventory](https://learn.microsoft.com/en-us/azure/automation/change-tracking/manage-change-tracking?wt.mc_id=knwlserapi_inproduct_azportal#manage-change-tracking-and-inventory)
