### ISSUE TITLE
[Cognitive] remove unneeded parameter in Account Create

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#1701]
Per [./services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go#L371](https://github.com/Azure/azure-sdk-for-go/blob/fad8443a79b0e755c18c3bec29a8d2bedab0b421/services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go#L371), when a CognitiveServicesAccount is [created](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/cognitiveservices/mgmt/2017-04-18/cognitiveservices#AccountsClient.Create) it must include a user-provided empty `interface{}` as one of its [parameters](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/cognitiveservices/mgmt/2017-04-18/cognitiveservices#AccountCreateParameters).

This parameter appears to be useless. Is it, and if so can it be removed from the signature (as a breaking change I suppose)? Thanks!

@tombuildsstuff thanks for pointing this out!

**Comment by jhendrixMSFT** [comment]
@felixwa why is an empty object required and will it be fixed any time soon?

**Comment by jhendrixMSFT** [comment]
Swagger reference [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/cognitiveservices.json#L702).

**Comment by jhendrixMSFT** [comment]
This has been moved to the specs repo, see https://github.com/Azure/azure-rest-api-specs/issues/3157.
