### ISSUE TITLE
Firewall Delete failure

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#17013]
### Bug Report

The [`Delete`](https://github.com/hashicorp/terraform-provider-azurerm/blob/281664823315bc743bcb1e7fc8c845ebb715c907/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-05-01/network/azurefirewalls.go#L128) method of Azure Firewall now always fail with following error:

> StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '' is not supported. Only 'application/json' is supported."

This issue is impacting the Terraform AzureRM provider: hashicorp/terraform-provider-azurerm#14966.

To fix this issue, either the SDK add the `Content-Type: application/json` or `Accept: application/json` in the DELETE request. Or the service team remove the check for the request header. Since this is a DELETE request, where both the request and the response doesn't contain payload, so IMO the service team doesn't necessarily need to do the check.

**Comment by jhendrixMSFT** [comment]
We still need to root-cause when/why the service team made this change.  It's a breaking change within a deployed API version which they shouldn't be doing and impacts all languages.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT based on our logs this change started rolling out (at least to West Europe) on January 9/10th (as the test failures start on the 11th UTC), which then appears to have been rolled back, and subsequentially re-released on the 25/26th Jan (as our tests failed on the 27th UTC):

![Screenshot 2022-02-09 at 17 11 20](https://user-images.githubusercontent.com/666005/153241637-6939341a-b541-4209-b92e-ad4c4cc3a0f0.png)

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff thanks for the info, I've passed this along to the service team.

**Comment by krowlandson** [comment]
I can also confirm that this impacts deletion of both `AZFW_Hub` and `AZFW_VNet` Firewall SKUs.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
