### ISSUE TITLE
[azservicebus] Support SAS connections

### ISSUE THREAD

**Issue by dunnry** [Azure/azure-sdk-for-go#17033]
Right now, it does not appear to be possible to use `CBSTokenTypeSAS` in the SDK.  I have not been able to find an example of anyone using a `SharedAccessSignature` connection.

However, I could be wrong here and someone might have an example of how that would work.  Thanks!

**Comment by richardpark-msft** [comment]
@dunnry, just checking - are you referring to the same feature requested here?

https://github.com/Azure/azure-sdk-for-go/issues/16641

**Comment by dunnry** [comment]
Yes, I think that is the same thing - you can close this as duplicate.  I take it based on that, it is not currently possible

Thanks!

**Comment by richardpark-msft** [comment]
Closed in favor of https://github.com/Azure/azure-sdk-for-go/issues/16641.

**Comment by richardpark-msft** [comment]
> Yes, I think that is the same thing - you can close this as duplicate. I take it based on that, it is not currently possible
> 
> Thanks!

It's not done yet, but it's still planned.

**Comment by eugkonon** [comment]
Also, here's a related issue: https://github.com/Azure/azure-sdk-for-go/issues/16641
