### ISSUE TITLE
[servicebus] Check SDK support described types in message serialization and deserialization

### ISSUE THREAD

**Issue by ZejiaJiang** [Azure/azure-sdk-for-go#17047]
We received a [bug report](https://github.com/Azure/azure-sdk-for-java/issues/26065) in java SDK. Customer cannot cast property attribute from servicebus messages which are sent by .net SDK.

After investigation, we found that .net SDK support `Uri`, `DateTimeOffset` and `TimeSpan` object by using described types in amqp. But java SDK haven't mapped any of these described types.

Here is .net doc: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-dotnet#message-serialization

Please confirm this case in SDK.

**Comment by RickWinter** [comment]
@richardpark-msft we need to address if this is an issue in the Go SDK

**Comment by richardpark-msft** [comment]
Yeah, I can add a simple test in for this. @jhendrixMSFT , might be some work incoming but I recall we had good primitive type mapping to AMQP types happening in the serializer in go-amqp.

**Comment by richardpark-msft** [comment]
I've added in some tests. There are two types that we can't handle today - 'TypeCodeDecimal', which doesn't have a supported decode/encode path in go-amqp and 'TypeCodeChar'.

@ZejiaJiang  - are there any types from the AMQP primitives that can't support? And if so, how are you documenting that?

**Comment by richardpark-msft** [comment]
@ZejiaJiang, one of the types (TypeCodeChar) is actually 4 bytes long. Java has a 2-byte char type, so what do you map it too? (and do you also support round-tripping)?

**Comment by richardpark-msft** [comment]
(also, closing this issue as we don't have immediate plans to add support, but can if customers need it)

**Comment by ZejiaJiang** [comment]
@richardpark-msft 

I've checked the source code of proton-j which is the AMQP implemetion in java language.

The proton-j support these two types that you mentioned above. Here is the related code:

Decimal:
https://github.com/apache/qpid-proton-j/blob/b51cac846a2f8f72f8dbb838bcd1d755de8110ad/proton-j/src/main/java/org/apache/qpid/proton/codec/Decimal128Type.java#L60-L101
Proton-j seprates decimal into msb and lsb.

Char:
https://github.com/apache/qpid-proton-j/blob/b51cac846a2f8f72f8dbb838bcd1d755de8110ad/proton-j/src/main/java/org/apache/qpid/proton/codec/CharacterType.java#L63-L126
The character encoding seems like can lose data. 

Overall, the proton-j supports these types, and we didn't do extra work on these types.
