### ISSUE TITLE
Collection Tags from resource

### ISSUE THREAD

**Issue by RafaelTomelin** [Azure/azure-sdk-for-go#17051]
Hi,

I'm used this module "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources" to list the Resource Groups em collection the key and value form Tagsbut the return is not good.

The values from tags "*rg.Tags" I can't get the values from Tags
My code is:
`
func listResources(subscriptionId string, credential azcore.TokenCredential) {

	// rgInfo := make(map[string]interface{})
	client := armresources.NewResourceGroupsClient(subscriptionId, credential, nil)
	pager := client.List(nil)
	for pager.NextPage(context.Background()) {
		if err := pager.Err(); err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, rg := range pager.PageResponse().ResourceGroupListResult.Value {
			for k, v := range *rg.Tags {
				print("Key =>", k)
				print("*Value => ", *v)
				print("Value => ", v)
			}
		}
	}
}
`

What is the best practice to collect the Tags from resources?

**Comment by tadelesh** [comment]
@RafaelTomelin With the latest version of `armresources`, I think you did the right thing except a redundant pointer.
```go
pager := client.List(nil)
for pager.NextPage(ctx) {
	if err := pager.Err(); err != nil {
		log.Fatalf("failed to advance page: %v", err)
	}
	for _, rg := range pager.PageResponse().ResourceGroupListResult.Value {
		for k, v := range rg.Tags {
			fmt.Println("Key =>", k)
			fmt.Println("Value => ", *v)
		}
	}
}
```
