### ISSUE TITLE
[servicebus] Best way to determine if topic/subscription exists

### ISSUE THREAD

**Issue by bvwells** [Azure/azure-sdk-for-go#17065]
This is a request to have a documented way to determine whether a topic/subscription exists or not.

I've been trying to work out the best way to determine if a service bus topic/subscription exists or not. I might be missing something, but I was hoping to be able to call GetTopic/GetSubscription on the ServiceBus admin client and infer the topic/subscription existence from error returned. i.e.

```go
package main

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/admin"
)

func main() {
        credential, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}

	adminClient, err = admin.NewClient("<ex: myservicebus.servicebus.windows.net>", credential, nil)
	if err != nil {
		panic(err)
	}

	resp, err := adminClient.GetSubscription(context.Background(), "topicName", "subName", &admin.GetSubscriptionOptions{})
	if err != nil {
		panic(err)
	}
	_ = resp
}
```

At the moment, `GetTopic/GetSubscription` returns a 200 http response error so it is not possible to tell whether the topic/subscription exists or not.  In github.com/Azure/azure-service-bus-go it was possible to use `IsErrNotFound` to determine a topic/subscriptions existence from topic/subscription manager. I.e.

```go
package main

import (
	"context"

	servicebus "github.com/Azure/azure-service-bus-go"
)

func main() {
	namespaceName := "mynamespace"
	namespace, err := servicebus.NewNamespace(servicebus.NamespaceWithEnvironmentBinding(namespaceName))
	if err != nil {
		panic(err)
	}

	tm := namespace.NewTopicManager()

	_, err = tm.Get(context.Background(), "topicName")
	if err != nil {
		if servicebus.IsErrNotFound(err) {
			// topic exists!
		}
		// something went wrong
	}
}
```

The only way I have currently found to do this is to list the subscriptions and match based on the subscription name. Would be nice to get some clarity on this.

**Comment by richardpark-msft** [comment]
I'll take a look. The normal expectation is that the service would return a 404 if the asked-for-entity does not exist. I'll look at what's going on there.

**Comment by bvwells** [comment]
Thanks, I traced one of the requests through for GetSubscription and I can see that a 200 response is returned from the http request.  It suprised me that a 404 was not being returned.

**Comment by richardpark-msft** [comment]
Hi @bvwells, just wanted you to know I haven't ghosted you on this, we're still trying to understand what the right way is to expose this in the SDK as it's a bit of an unusual API. Will update this issue when I've got a conclusion/patch.

**Comment by bvwells** [comment]
Thanks for the update @richardpark-msft. There is no rush with this one as I have a workaround for the issue by listing topics and subscriptions to see whether they exist or not.

**Comment by richardpark-msft** [comment]
Thanks for your patience on that - this should be a bit more efficient.
