### ISSUE TITLE
Metadata not uploaded with UploadStreamToBlockBlob

### ISSUE THREAD

**Issue by patrickrad** [Azure/azure-sdk-for-go#17061]
### Bug Report

"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob" 
sdk/storage/azblob/v0.3.0
go version go1.16.3 linux/amd64

When using UploadStreamToBlockBlob to upload a blob, any added metadata is not uploaded. If I instead use UploadBufferToBlockBlob it works as expected and the metadata is uploaded as expected. 

The following code demonstrates the problem. The stream upload will not result in any metadata being uploaded, but the buffer upload will. I have verified that the metadata is missing both with listing the objects as well as by inspecting the object via the Azure portal.

        data := []byte("hello world this is a blob")
        md := make(map[string]string)
        md["key1"] = "value1"

        // stream upload
        opts1 := azblob.UploadStreamToBlockBlobOptions{Metadata: md}
        blobClient1 := containerClient.NewBlockBlobClient("blob-stream")
        _, err = blobClient1.UploadStreamToBlockBlob(ctx, bytes.NewReader(data), opts1)
        if err != nil {
                log.Fatalf("Failure to stream upload to blob: %+v", err)
        }

        // buffer upload
        opts2 := azblob.HighLevelUploadToBlockBlobOption{Metadata: md}
        blobClient2 := containerClient.NewBlockBlobClient("blob-buffer")
        _, err = blobClient2.UploadBufferToBlockBlob(ctx, data, opts2)
        if err != nil {
                log.Fatalf("Failure to stream upload to blob: %+v", err)
        }

**Comment by amishra-dev** [comment]
Thanks for the bug report @patrickrad 
As you are aware this is a prerelease SDK, we are continuously working on improving the quality of the SDK, we will pick this up as soon as we can.

**Comment by zezha-msft** [comment]
Thanks for reaching out!

The bug is here: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/highlevel.go#L594

**Comment by mohsha-msft** [comment]
Hey @patrickrad ,

[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. I have fixed the issue [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#BlockBlobClient.UploadStream) and [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/chunkwriting.go#L197).

Please reach out and reopen the issue if it still persists. 

Thanks a lot for your feedbacks!
