### ISSUE TITLE
Problem with return armresources/zz_generated_client - ClientListOptions

### ISSUE THREAD

**Issue by RafaelTomelin** [Azure/azure-sdk-for-go#17075]
Hi,

I'm creating the code to list all resources from Azure in the subscription and I'm used this package and functions:

packages
`	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	"github.com/Azure/go-autorest/autorest/to"
`

The code to call list resources
`
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("Authentication failure: %+v", err)
	}

	client := armresources.NewClient(os.Getenv("AZURE_SUBSCRIPTION_ID"), cred, nil)
	var t *armresources.ClientListOptions
	a := client.List(t)
	fmt.Println(a)
`
The filter in ClientListOptions, I'm leaving empty and return NIL
`
&{0xc00003c9c0 {{{[] <nil>}} <nil>} <nil> 0x748ee0 0x7519e0}
`

The return is a problem?
 I didn't configure the correct filters?

**Comment by ArcturusZhang** [comment]
Hi @RafaelTomelin thanks for this issue.
The case is that when you call a `List` function, it returns a `Pager` to you. No API calls happen until you actually iterate over it.
You could iterate it like this:
```
pager := client.List(t)
for pager.NextPage(ctx) {
        resp := pager.PageResponse()
        if resp.Value != nil {
           // you could iterate over the result on the slice `resp.Value`
        }
    }
```
For more samples, you could refer this document: https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-quickstart.md#L222
Or you could visit this repo: https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/new-version for more samples of our new SDK
