### ISSUE TITLE
How to get all available VersionIDs for a blob?

### ISSUE THREAD

**Issue by maaft** [Azure/azure-sdk-for-go#17070]
The API does not give a clear answer on this.

Anyone knows how to do this?

My goal is to delete all available VersionIDs for specific blobs.

**Comment by zezha-msft** [comment]
Hi @maaft, thanks for reaching out!

Listing all available versions can be achieved by calling the [list blob API](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs) with a _prefix_ equal to the blob name, and _include_ set to versions. 

If you have blobs that are prefixes of others, you'll need to filter those out as you are processing the results.

Please let us know if you have any other question.
