### ISSUE TITLE
InvalidResourceType when creating new RBAC assignment using SDK

### ISSUE THREAD

**Issue by DamirZelenic** [Azure/azure-sdk-for-go#17071]
### Bug Report

- import path of package in question
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization"

- SDK version e.g. `master`, `latest`, `18.1.0`
 v0.3.0

- output of `go version`
go version go1.17.6 darwin/arm64

- What happened?
When trying to create new RBAC role assignment using Create method I got:
```
RESPONSE 404: 404 Not Found
ERROR CODE: InvalidResourceType
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2020-10-01-preview'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2017-10-01-preview,2018-01-01-preview,2018-07-01,2018-09-01-preview,2018-12-01-preview,2019-04-01-preview,2020-03-01-preview,2020-04-01-preview,2020-08-01-preview,2021-04-01-preview'."
  }
}
```

- What did you expect or want to happen?
 Expect result like:
```
2022/02/15 11:45:19 Response result: armauthorization.RoleAssignmentsClientCreateResult{RoleAssignment:armauthorization.RoleAssignment{Properties:(*armauthorization.RoleAssignmentProperties)(0x14000202120), ID:(*string)(0x14000552710), Name:(*string)(0x14000552730), Type:(*string)(0x14000552720)}}
```

As error suggests there is unsupported api version in 
azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization@v0.3.0/zz_generated_roleassignments_client.go

line 87:
```
reqQP.Set("api-version", "2020-10-01-preview")
```

changing it to supported version, for example: 
```
reqQP.Set("api-version", "2020-08-01-preview")
```

produces expected result.
 
- How can we reproduce it?
```
rbacClient := armauthorization.NewRoleAssignmentsClient(subscriptionID, cred, nil)
	rbacres, err := rbacClient.Create(ctx,
		scope,
		uuid, //"<role-assignment-name>" must be unique
		armauthorization.RoleAssignmentCreateParameters{
			Properties: &armauthorization.RoleAssignmentProperties{
				PrincipalID:      to.StringPtr(principalID),
				PrincipalType:    armauthorization.PrincipalType("User").ToPtr(),
				RoleDefinitionID: to.StringPtr(roleDefID),
			},
		},
		nil)
```

**Comment by ArcturusZhang** [comment]
Hi @DamirZelenic thanks for this issue and sorry for the inconvenience!

We will confirm this with the corresponding service team to see if this api-version has been deployed to all the regions. Stay tuned.
As a workaround, we could downgrade the api-version in this package to 2021-08-01-preview to ensure everything could work properly here

**Comment by DamirZelenic** [comment]
Hi  @ArcturusZhang 
It is default AzureCloud. Subscription and RBAC role doesn't have any specific region?
Subscription location placement id:
```
"LocationPlacementId": "Public_2014-09-01"
```
In error message I see newer api being available "...2020-08-01-preview,2021-04-01-preview", only 10-01 is missing.
I can share Role Assignment Id if needed.

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang It is default AzureCloud. Subscription and RBAC assignment doesn't have any specific region? Subscription location placement id:
> 
> ```
> "LocationPlacementId": "Public_2014-09-01"
> ```
> 
> In error message I see newer api being available "...2020-08-01-preview,2021-04-01-preview", only 10-01 is missing. I can share Role Assignment Id if needed.

Please share that as well if possible. Thank you!
