### ISSUE TITLE
Add a CI check that flags all exported symbols that are missing doc comments.

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#17095]
We really need a CI check that flags all exported symbols that are missing doc comments.

_Originally posted by @jhendrixMSFT in https://github.com/Azure/azure-sdk-for-go/pull/17093#r809211410_

**Comment by benbp** [comment]
This does not appear to be a simple fix (see https://github.com/golangci/golangci-lint/issues/456), but I'm digging into config updates/workarounds for linting.

**Comment by benbp** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-go/issues/17095
