### ISSUE TITLE
[storage] panic if the server is not reachable while uploading

### ISSUE THREAD

**Issue by drakkan** [Azure/azure-sdk-for-go#17109]
### Bug Report

- "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
- sdk/storage/azblob/v0.3.0
- go version go1.17.7 linux/amd64

I use the azurite emulator and upload a large file using `UploadStreamToBlockBlob`, while the upload is still in progress I shutdown azurite to simulate a server unreachable status. After some seconds my application crash with this stacktrace:

```shell
panic: send on closed channel

goroutine 323 [running]:
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.staticBuffer.Put({0xc00548c1e0, 0xc000674000, 0xc00548c180}, {0xc000f8e000, 0xc0007f7ea0, 0x0})
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/highlevel.go:475 +0x3c
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.(*copier).write(0xc000238780, {{0xc000f8e000, 0x400000, 0x400000}, {0xc000378a20, 0x58}, 0x400000})
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/chunkwriting.go:175 +0x338
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.(*copier).sendChunk.func1()
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/chunkwriting.go:149 +0xd0
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.NewStaticBuffer.func1()
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/highlevel.go:454 +0x3b
created by github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.NewStaticBuffer
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/highlevel.go:452 +0xd3
```

please fix, thanks

**Comment by drakkan** [comment]
If you try to stop azurite while a download is in progress if you use `blockBlob.Download` the connection failure is detected as expected while if you use `blockBlob.DownloadBlobToWriterAt` it seems to hang forever (I waited for 10 minutes), so basically the high level APIs seem not really usable.

I noticed the same thing also using the old SDK, for example for multipart uploads I used my own wrapper and I'll port it to the new sdk, see [here](https://github.com/drakkan/sftpgo/blob/c19b03a3f7307deb166c34ed0a0ce162038b8a5b/vfs/azblobfs.go#L899)

**Comment by drakkan** [comment]
This is not an issue for me, I'll continue to use the low level APIs as with the old SDK

**Comment by ncw** [comment]
I've come across what is a very similar bug.

This occurs if the `io.Reader` passed into `UploadStreamToBlockBlob` returns an error before the end of the stream. Lets say the Reader was connected to a remote HTTP transfer and that returned an error.

```
panic: send on closed channel

goroutine 658 [running]:
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.staticBuffer.Put(...)
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/shared/transfer_manager.go:83
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob.(*copier).write(0xc0002fc140, {{0xc000c80000, 0x400000, 0x400000}, {0xc0003f0c00, 0x58}, 0x1400})
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/blockblob/chunkwriting.go:179 +0x354
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob.(*copier).sendChunk.func1()
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/blockblob/chunkwriting.go:153 +0xc7
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.NewStaticBuffer.func1()
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/shared/transfer_manager.go:62 +0x3b
created by github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.NewStaticBuffer
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/shared/transfer_manager.go:60 +0xce
exit status 2
FAIL	github.com/rclone/rclone/backend/azureblob	46.217s
```

Let me know if you'd like a new issue for this and if you need me to make a reproducer (this is part of the rclone integration tests so I could extract code probably).

**Comment by ncw** [comment]
Since this issue is closed, I made a new one with a reproducer: https://github.com/Azure/azure-sdk-for-go/issues/19612
