### ISSUE TITLE
Query Blob Contents

### ISSUE THREAD

**Issue by patrickrad** [Azure/azure-sdk-for-go#17102]
### Feature Request

Are there any plans on adding support for the Query Blob Contents functionality? I see that there is an internal function, Query in the file zz_generated_blob_client.go, but no public (which I guess should be in zc_blob_client.go?)
Functionality for unpacking the returned Avro formatted data would also be needed.

**Comment by amishra-dev** [comment]
Hi @patrickrad,
The Go library is still under development, we do plan to add the query api to the Go SDK in the future.

Thanks

**Comment by zezha-msft** [comment]
Thanks @patrickrad for the feature request. We will prioritize this feature once the library becomes GA.
