### ISSUE TITLE
InvalidResourceType when requesting resource reservation order list

### ISSUE THREAD

**Issue by Teiktos** [Azure/azure-sdk-for-go#17103]
### Bug Report

- Module: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations`
- SDK Version: `v61.5.0+incompatible`
   - Commit: edc69c25160e028b592dc707115f61686379e7a7
- Go Version: `go1.17.7 linux/amd64`

#### What happened?

A ReservationOrderClient was created and the List function was called ([link to function in file](https://github.com/Azure/azure-sdk-for-go/blob/1c1d87fc26d53f6c0817f7ef2b1b8dd3b669a811/sdk/resourcemanager/reservations/armreservations/zz_generated_reservationorder_client.go#L192)). This results in the following error:

```
failed to advance page: GET https://management.azure.com/providers/Microsoft.Capacity/reservationOrders
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: InvalidResourceType
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'reservationOrders' could not be found in the namespace 'Microsoft.Capacity' for api version '2021-07-01'. The supported api-versions are '2017-11-01,2018-06-01,2019-04-01,2020-06-01,2020-10-01-preview,2020-11-15-preview,2017-11-01-beta,2018-06-01-beta,2019-04-01-beta,2020-06-01-beta,2020-10-01-beta,2020-11-15-beta'."
  }
}
--------------------------------------------------------------------------------
```

Unlike in #17071 changing the api-version in the function from "2021-07-01" ([link to line in file](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/reservations/armreservations/zz_generated_reservationorder_client.go#L212)) to any of the  API versions from the previous error, results the following error message:

```
failed to advance page: unmarshalling type *armreservations.ReservationOrderList: json: cannot unmarshal string into Go struct field ReservationOrderList.value of type []*armreservations.ReservationOrderResponse
```

or in case of beta APIs in 

```
failed to advance page: GET https://management.azure.com/providers/Microsoft.Capacity/reservationOrders
--------------------------------------------------------------------------------
RESPONSE 501: 501 Not Implemented
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadRequest",
    "message": "Not Implemented."
  }
}
--------------------------------------------------------------------------------
```

#### What did you expect or want to happen?

A returned ReservationOrderClientListPager, with which a list of reservation orders can be accessed.

#### How can we reproduce it?

Create a ReservationOrderClient and call the List function.

```
package main

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations"
)

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	client := armreservations.NewReservationOrderClient(cred, nil)
	pager := client.List(nil)
	for {
		nextResult := pager.NextPage(ctx)
		if err := pager.Err(); err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		if !nextResult {
			break
		}
		for _, v := range pager.PageResponse().Value {
			log.Printf("Pager result: %#v\n", v)
		}
	}
}
```

#### Environment

- default Azure Public Cloud

**Comment by jhendrixMSFT** [comment]
Unrelated to the issue, but I have a question.  From the details you provided, I see you're importing version `v61.5.0+incompatible`.  All of our new packages under the `/sdk` directory are individual modules.  Are you unable to import module `armreservations` directly?  Or perhaps we haven't clearly documented this modularization.  Any insight into how you're handling imports/versions would be very helpful.

**Comment by ArcturusZhang** [comment]
This issue looks like the API is in the swagger but it is actually not implemented on the service side. We might need someone from the service side to answer this.

**Comment by msft-adrianma** [comment]
You are correct that version "2021-07-01" is not supported in ARM (azure resource manager) even though it is exposed in the Go SDK. We are working on fixing that. 
To unblock you can update the version to in zz_generated_reservationorder_client.go (as you mentioned above) to the version 
	reqQP.Set("api-version", "2019-04-01")
I was able to try your Go sample and see the reservation orders with this version.

![image](https://user-images.githubusercontent.com/43483041/161456658-0d6fb33d-b254-4084-9a07-61a57b22d8e6.png)

**Comment by jhendrixMSFT** [comment]
@msft-adrianma is this API version going to be deployed soon, or should we revert our SDK to use 2019-04-01?

**Comment by gaoyp830** [comment]
@jhendrixMSFT We have updated our manifest with 2021-07-01 version and it's currently in SDP. ETA is next Monday.

**Comment by jhendrixMSFT** [comment]
@Teiktos is this working for you now?
