### ISSUE TITLE
DefaultAzureCredential causes race data condition in goroutines

### ISSUE THREAD

**Issue by pleska** [Azure/azure-sdk-for-go#17144]
### Bug Report

Package: github.com/Azure/azure-sdk-for-go/sdk/azidentity
SDK version: latest
Package version: v0.13.1
go version go1.17.6 darwin/arm64

Using DefaultAzureCredential in more than one goroutine at the same time can cause a race data condition to be raised. The problem seems to be the NewChainedTokenCredential overwriting the stored credential from another routine vs. finding the cached one from a previous call on the credential. Since this is deferred until later in execution when the token is needed an actual API call needs to be made before the goroutines can use the credential or the race condition will happen. It would be ideal if the routines would prevent this race condition, use the cached credential or at least provide a way to obtain the credential and cache it on the azidentity API and not have to execute an API action to cause the credential to be obtained before calling other APIs in goroutines just to prevent this race condition.

**Comment by chlowell** [comment]
Thanks for opening this issue! I'll get it fixed for the next release.
