### ISSUE TITLE
Add deprecate package information in this repo

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-go#17148]
Due to the limitation of go package manager, there is not a very good way to mark a package is deprecated, therefore, in our readme file, add a new link and a new file, that includes the deprecated package information.
### Service Package Request

A file to list all the deprecated packages in Azure Golang SDK

**Comment by RickWinter** [comment]
Can you clarify what you are requesting to happen here.

cc: @kimprice @mikekistler

**Comment by kimprice** [comment]
Technically though we wouldn't list any packages as deprecated until we have a stable package to replace it, right?

**Comment by xboxeer** [comment]
> Technically though we wouldn't list any packages as deprecated until we have a stable package to replace it, right?

Yes, I think we can deliver this message after we have GO T2 GA, let me close this issue for now.
