### ISSUE TITLE
Add azidentity migration guide

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#17145]
Document how azidentity credentials line up with adal and provide an example of any new API patterns in track 2.

**Comment by weinong** [comment]
Any update on this?

**Comment by chlowell** [comment]
It's been on hold pending configuration API changes releasing this week. I expect to have it done this month.

**Comment by chlowell** [comment]
I've opened a PR: #17494. Please let me know if my draft is missing content that would help you.
