### ISSUE TITLE
Always allow “nil” to set default values for options 

### ISSUE THREAD

**Issue by kimprice** [Azure/azure-sdk-for-go#17149]
This issue came up from the November Blob Storage UX study.

For any options parameters, we should always allow "nil" to be passed in to set the default options. Doc comments should also specify something to the effect of “pass ‘nil’ to accept default values.” There were several instances where users were required to pass an empty instance to set the default options.

For example: UploadFileToBlockBlob currently requires an empty HighLevelUploadToBlockBlobOption instance instead of “nil”, nitpick: rename to use plural “Options” instead of “Option” for consistency

Is there a way that we can automatically check that all options parameters allow ‘nil’?

**Comment by jhendrixMSFT** [comment]
This has been fixed in `azblob@v0.5.0`
