### ISSUE TITLE
batch Rest API requests (azure portal uses this) using the GO SDK

### ISSUE THREAD

**Issue by djdongjin** [Azure/azure-sdk-for-go#17155]
### Feature Request

The issue is the same as #15957. We are also investigating this feature. While checking the traffic in azure portal, we found that vmss uses some of the batch operations to complete some tasks (e.g., stop multiple vms, etc). The traffic and URL is shown as below:

![image](https://user-images.githubusercontent.com/28295179/155420619-11b49b6e-3771-450f-af3d-b116b2656ec9.png)

The request body is a json that contains all requests within this batch.

Do you know where I can find any document about this API endpoint (https://management.azure.com/batch?...). And is it already available in SDK?

Thanks.

cc: @RickWinter

**Comment by djdongjin** [comment]
Hi @RickWinter @lirenhe 

Any update on this? Thanks.

Also, I saw the `Batch` label is attached. However, the `batch` in question seems not related to the Azure `Batch` service. It's more like just an Azure API that batches multiple API calls within one request.

Thanks!

**Comment by RickWinter** [comment]
@djdongjin Can you confirm which API you invoked to trigger this behavior.  Any details you can share would be helpful.

**Comment by djdongjin** [comment]
Hi @RickWinter ,

I used the vmss (flexible) API in azure portal. For example, the below figure shows a request to `stop` two vmss instances in the portal.

<img width="2298" alt="image" src="https://user-images.githubusercontent.com/28295179/156052974-5ede4b2b-4823-4ac3-946e-4f20a5f93528.png">

I believe the batch API is used extensively while accessing azure portal, since I saw many of these batch APIs.

**Comment by lirenhe** [comment]
@djdongjin, if you take a look at the swagger repo, https://github.com/Azure/azure-rest-api-specs, all mgmt plane api would include the resource provider name like Microsoft.RPName.
For https://management.azure.com/batch, this does not seem to belong to any RP.  You may check with ARM team directly for this API

**Comment by djdongjin** [comment]
@lirenhe 

Hi, thanks for replying. Could you please provide contact with the ARM team? GitHub repos, emails, etc.

Thanks.

**Comment by lirenhe** [comment]
Share the contact info offline and close this item.
Let me know if there are further questions. thanks
