### ISSUE TITLE
Support ARM cross-tenant authentication

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#17159]
### Bug Report

When using the Client Secret Auth method, the multitenant authentication (a.k.a auxiliary tenant) doesn't work as expected. The ultimate bear token that is set in the header as `x-ms-authorization-auxiliary` is actually signed by the primary tenant.

With some debugging, it appears the problem comes from: https://github.com/Azure/azure-sdk-for-go/blob/8379ab2ff08eb677863373331cdaa981f663a9f2/sdk/azidentity/client_secret_credential.go#L65-L66, where the `opts.TenantID` is not used at all for acquiring the token in the call of `c.client.AcquireTokenSilen`. Instead, the tenant of the `c.client` is used, which is the primary tenant.

This issue doesn't only apply to Client Secret Auth method, but also (at least) to the Client Cert, MSI and CLI Auth method.

**Comment by chlowell** [comment]
Thanks for opening this! We have API in place for ARM cross-tenant authentication but, as you've seen, the implementation is incomplete in that credentials always authenticate in the tenant set at construction. MSAL clients have the same limitation, so it's awkward for us to implement this today. It is technically feasible though--each credential could maintain a map of tenants to MSAL client instances. Still, that's a poor solution; it would be better to leverage MSAL support for this feature. I'll see where it fits on the roadmap.

**Comment by RickWinter** [comment]
Blocked on [[Feature Request] Enable changing tenant after client construction](https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/296)

**Comment by andyzhangx** [comment]
> Blocked on [[Feature Request] Enable changing tenant after client construction](https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/296)

@RickWinter I see https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/296 is closed, so what's the status of this issue now?

**Comment by RickWinter** [comment]
Charles recently added support to MSAL for GO.  In order to leverage that in azidentity we need two more things to happen 

1. A release of MSAL for GO with the changes 
2. An update to AzIdentity to leverage the new release.

Both items are slated to happen in the first part of 2023.

**Comment by chlowell** [comment]
azidentity v1.3.0-beta.3, in tandem with azcore v1.4.0-beta.1, supports ARM cross-tenant authentication. Usage looks like this:
```go
import "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"

auxTenants := []string{"TODO", "..."}
cred, err := azidentity.NewClientSecretCredential(tenantID, clientID, secret,
      // AdditionallyAllowedTenants prevents the credential from trying to
      // authenticate in an unexpected tenant. All credential types capable
      // of multitenant auth have this option.
      &azidentity.ClientSecretCredentialOptions{AdditionallyAllowedTenants: auxTenants},
)
if err != nil {
      // TODO: handle error
}
// armsubscription is just an example, all ARM clients have this same options API
client, err := armsubscription.NewSubscriptionsClient(cred,
      // client will add a token for each of these tenants to every request
      &arm.ClientOptions{AuxiliaryTenants: auxTenants},
)
```
