### ISSUE TITLE
Rename methods Upload*ToBlockBlob -> Upload* 

### ISSUE THREAD

**Issue by kimprice** [Azure/azure-sdk-for-go#17150]
This issue came up from the November Blob Storage UX study.

We should remove "ToBlockBlob" from all the Upload methods since they are methods on the BlockBlobClient. "ToBlockBlob" makes the methods unnecessarily verbose and caused confusion for users.

**Comment by mohsha-msft** [comment]
Done. Will be fixed in next release i.e. `0.4.0`.

**Comment by mohsha-msft** [comment]
Hey @kimprice ,

[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. I have fixed the issue [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/highlevel.go).

Please reach out and reopen the issue if it still persists. 

Thanks a lot for your feedbacks!
