### ISSUE TITLE
Add Kusto(Data Explorer) for synapse

### ISSUE THREAD

**Issue by adamyager** [Azure/azure-sdk-for-go#17179]
### Feature Request

Currently the REST API does support Kusto Clusters for synpase
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview
"kustoPool.json"

We would please ask this be supported for Go as well and is currently not.
https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/synapse/mgmt/2021-06-01-preview/synapse

**Comment by Alancere** [comment]
Hi @adamyager 
Is this [link](https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/synapse/mgmt/v2.0/synapse) what you need?

**Comment by adamyager** [comment]
correct. Quite confused on the naming convention here, but thats the one I need.
