### ISSUE TITLE
Track1 async LRO for PUT operation doesn't accept bodyless response

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#17196]
I'm not sure whether this is a SDK issue or service issue.

The [automation runbook draft content API](https://github.com/Azure/azure-rest-api-specs/blob/953c26995780b043102a8941a07e8175ffad4428/specification/automation/resource-manager/Microsoft.Automation/stable/2018-06-30/runbook.json#L164-L164) is a LRO, while when I try to create it via [`ReplaceContent()`](https://github.com/Azure/azure-sdk-for-go/blob/main/services/preview/automation/mgmt/2020-01-13-preview/automation/runbookdraft.go#L212) and wait via `WaitForCompletionRef()`, it failed with:

```
pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0
```

I can confirm that the API response of the polling has no body. Also I've noticed that for `PUT` operation, the response body [is a must have](https://github.com/hashicorp/terraform-provider-azurerm/blob/81fd92188d77124766c0d07c1c349dab901d83a2/vendor/github.com/Azure/go-autorest/autorest/azure/async.go#L882-L900). So my question is that whether current behavior of the async handling is as expected, or is this rather a service side issue?

**Comment by tadelesh** [comment]
It seems the service did not return poll url either in location or in header. Could you please help to paste the detail log here?

**Comment by magodo** [comment]
I can confirm that the service returned that in the header.

**Comment by tadelesh** [comment]
It should be a service issue as the follow up polling request should return a file response if operation completed. @zjalexander Could you help to have a look?

**Comment by tadelesh** [comment]
@jhendrixMSFT For `PUT LRO`, if operation finish, the body must be non-empty according to the [code](https://github.com/Azure/go-autorest/blob/82fc42f340cec32d30ce97f9277f9b8aaf8885df/autorest/azure/async.go#L882-L900). But as the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/953c26995780b043102a8941a07e8175ffad4428/specification/automation/resource-manager/Microsoft.Automation/stable/2018-06-30/runbook.json#L142-L147) shows, the response is a file which I doubt whether it would be an empty file that fall into an error.

**Comment by tombuildsstuff** [comment]
This can also be found in the API Management API: https://github.com/Azure/azure-sdk-for-go/issues/17196#issuecomment-1073591633 - and I recall seeing this in a number of other API's, so I believe this is SDK limitation rather than an API issue?

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT in the case mentioned above this is async, we're seeing a Location header with no body - @manicminer should be able to clarify in this specific case, but IIRC the API is defining both a 200 (non-LRO) and a 201 (LRO)

**Comment by tadelesh** [comment]
@jhendrixMSFT It is an async operation. But the final response is a 200 empty-body response which I suppose is a valid result for empty file.

**Comment by manicminer** [comment]
FWIW I'm seeing this with API Management - when restoring a soft-deleted instance with a PUT request, the LRO poll on conclusion returns a 200 with no body, which is failing [this check](https://github.com/Azure/go-autorest/blob/master/autorest/azure/async.go#L896-L898) in go-autorest.

**Comment by jhendrixMSFT** [comment]
The are two types of LRO polling.  Resource location (RELO for short), and status monitor.  For the former, an example would be creating a VM.  You PUT the resource and then GET on the resource URL which includes the resource and its provisioning state.  For status monitor, you PUT the resource, and a polling URL, _different_ from the resource URL, is returned.  GET on the polling URL _must_ always return a state (`inprogress`, `succeeded`, `failed`, `cancelled`).

Based on the earlier snippets, it looks to me like this service uses the status monitor pattern.  E.g. the URL returned in the `location` header.

`GET https://management.azure.com/subscriptions/****/resourceGroups/acctestRG-auto-220301130312427646/providers/Microsoft.Automation/automationAccounts/acctest-220301130312427646/runbooks/Get-AzureVMTutorial/operationResults/e4120aee-0707-4b83-ad40-a30179ab6a2c?api-version=2018-06-30`

Which is different from the URL of the resource and contains `/operationResults/<UUID>` which is typical for status monitor.

Can somebody confirm with the service team?  If this is status monitor, then the terminal response body _cannot_ be empty.

**Comment by tadelesh** [comment]
I see. Let me try to contact service team.

**Comment by tombuildsstuff** [comment]
@tadelesh any update on this one?

**Comment by tadelesh** [comment]
@sushil490023 could you help to take a look?

**Comment by wuxu92** [comment]
This issue is no longer a block as we have switched to hashicorp/go-azure-sdk? The track 1 sdk should not maintained anymore.
