### ISSUE TITLE
What is x-ms-original-file comment used for when generating examples

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17192]
Example: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/ze_generated_example_virtualmachines_client_test.go#L46

This shows up in the documentation which looks a little weird.  Navigate to https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#VirtualMachinesClient and expand one of the examples.

**Comment by tadelesh** [comment]
It is for code extraction used for some tooling for msdoc. I'll discuss with the tool author to try to make it more meaningful.

**Comment by tadelesh** [comment]
Will change to `generated by example file: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/examples/compute/CreateALinuxVmWithPatchSettingAssessmentModeOfImageDefault.json` after next round of refresh.
