### ISSUE TITLE
GetVirtualMachinesClient().List API does not returning all VMs in cloud

### ISSUE THREAD

**Issue by xqinca** [Azure/azure-sdk-for-go#17195]
### Bug Report

- import path of package in question
"github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-30/compute"

- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
github.com/Azure/azure-sdk-for-go v55.7.0+incompatible

- output of `go version`
go version go1.15.2 linux/amd64

- What happened?
azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name)
We call above API to get all the VMs in the resource group. Sometimes it's not returning all the VMs, only part of them received. Most of the time it's working fine. No error was returned. Is it a known issue? We know the SDK is not the latest.

- What did you expect or want to happen?
It should return all the VMs in the resource groups. Or it should return error if there is any error happened.

- How can we reproduce it?
It happened occasionally when there are around 20 resources groups in the cloud and each has 2 VMs in the resource groups. Call above API for all the resource groups.

- Anything we should know about your environment.

**Comment by tadelesh** [comment]
Could you help to give some logs or detailed info for the missing situation as it may caused by too many reasons.

**Comment by xqinca** [comment]
Here are the logs. The .List API doesn't work but the .Get API works.   Words after "<<<" are comments.

{“time":"2022-03-03T13:03:47.4472003Z","message":"[Fetching VMs for RG:  CAPIC_tn_intervpc_vrf1_westus2]"}
	<<< Calling azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name)
	<<< No VM in result

{“time":"2022-03-03T13:06:51.5738723Z","message":"[Fetching VM for:  /subscriptions/<subscription>/resourceGroups/CAPIC_tn_intervpc_vrf1_westus2/providers/Microsoft.Compute/virtualMachines/EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"}
	<<<  Calling azclient.GetVirtualMachinesClient().Get(context.Background(), resGrp.name, vmName, compute.InstanceView)

{“time":"2022-03-03T13:06:51.7572103Z","message":"[CreateVM:  EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"}
	<<< VM is successfully received

{“time":"2022-03-03T13:12:31.9647823Z","message":"[Fetching VMs for RG:  CAPIC_tn_intervpc_vrf1_westus2]"}
	<<< Calling azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name)  again after few minutes
	<<< Again No VM in the result

{“time":"2022-03-03T13:15:34.003544Z","message":"[Fetching VM for:  /subscriptions/<subscription>/resourceGroups/CAPIC_tn_intervpc_vrf1_westus2/providers/Microsoft.Compute/virtualMachines/EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"}
	<<<  Calling azclient.GetVirtualMachinesClient().Get(context.Background(), resGrp.name, vmName, compute.InstanceView) again

{“time":"2022-03-03T13:15:34.4161814Z","message":"[CreateVM:  EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"}
	<<< VM is successfully received


Below code is how do we call the .List API:

```
func (i *inventoryHandle) listVMs() ([]mo.Object, error) {
    clog.Info("Fetching VMs")
    var output []mo.Object
    azclient := *i.azClient

    for _, resGrp := range i.resGrptoRes {
        clog.Info(“Fetching VMs for RG:”, resGrp.name)
        result, err := azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name)
        if err != nil {
            clog.Warn(err)      // No error printed
            return nil, err
        }

        for result.NotDone() {
            clog.Info(“Got result”)     // This log was not printed
            for _, vm := range result.Values() {
                for _, objs := range i.createVM(vm, resGrp) {
                    output = append(output, objs)
                }
            }
            result.Next()
        }
    }
    return output, nil
}
```

**Comment by tadelesh** [comment]
> Here are the logs. The .List API doesn't work but the .Get API works. Words after "<<<" are comments.
> 
> {“time":"2022-03-03T13:03:47.4472003Z","message":"[Fetching VMs for RG: CAPIC_tn_intervpc_vrf1_westus2]"} <<< Calling azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name) <<< No VM in result
> 
> {“time":"2022-03-03T13:06:51.5738723Z","message":"[Fetching VM for: /subscriptions//resourceGroups/CAPIC_tn_intervpc_vrf1_westus2/providers/Microsoft.Compute/virtualMachines/EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"} <<< Calling azclient.GetVirtualMachinesClient().Get(context.Background(), resGrp.name, vmName, compute.InstanceView)
> 
> {“time":"2022-03-03T13:06:51.7572103Z","message":"[CreateVM: EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"} <<< VM is successfully received
> 
> {“time":"2022-03-03T13:12:31.9647823Z","message":"[Fetching VMs for RG: CAPIC_tn_intervpc_vrf1_westus2]"} <<< Calling azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name) again after few minutes <<< Again No VM in the result
> 
> {“time":"2022-03-03T13:15:34.003544Z","message":"[Fetching VM for: /subscriptions//resourceGroups/CAPIC_tn_intervpc_vrf1_westus2/providers/Microsoft.Compute/virtualMachines/EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"} <<< Calling azclient.GetVirtualMachinesClient().Get(context.Background(), resGrp.name, vmName, compute.InstanceView) again
> 
> {“time":"2022-03-03T13:15:34.4161814Z","message":"[CreateVM: EPG_web2_VM_8_CAPIC_tn_intervpc_vrf1_westus2]"} <<< VM is successfully received
> 
> Below code is how do we call the .List API:
> 
> ```
> func (i *inventoryHandle) listVMs() ([]mo.Object, error) {
>     clog.Info("Fetching VMs")
>     var output []mo.Object
>     azclient := *i.azClient
> 
>     for _, resGrp := range i.resGrptoRes {
>         clog.Info(“Fetching VMs for RG:”, resGrp.name)
>         result, err := azclient.GetVirtualMachinesClient().List(context.Background(), resGrp.name)
>         if err != nil {
>             clog.Warn(err)      // No error printed
>             return nil, err
>         }
> 
>         for result.NotDone() {
>             clog.Info(“Got result”)     // This log was not printed
>             for _, vm := range result.Values() {
>                 for _, objs := range i.createVM(vm, resGrp) {
>                     output = append(output, objs)
>                 }
>             }
>             result.Next()
>         }
>     }
>     return output, nil
> }
> ```

@xqinca I didn't find anything wrong from your code. If the problem happened occasionally, it seems caused by some corner case with the compute service. Could you please create a support ticket for azure directly?
