### ISSUE TITLE
Use SharedKeyLite

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#172]
Using SharedKeyLite scheme will make `storage` package code a lot cleaner. self-assigning as a cleanup task.

https://msdn.microsoft.com/en-us/library/azure/dd179428.aspx

Update (5/4/16): we just merged the storage/table client, which uses sharedkeylite signing. we shall convert queue/blob clients to it as well.

**Comment by ahmetalpbalkan** [comment]
this will also improve the REST call functions by removing the code setting the `Content-Length` header explicitly for the requests with a body.

**Comment by kpfaulkner** [comment]
@ahmetalpbalkan  Is it planned that SharedKey and SharedKeyLite will both be available (bool toggle?) or we'll simply go for "SharedKeyLite all the things" ?

Have already implemented this previously by having everything use Lite, just want to check that's the agreed approach? If so, I'll refactor a little over the weekend and submit a PR.

**Comment by ahmetalpbalkan** [comment]
@kpfaulkner I opened this issue to switch to SharedKeyLite and get rid of the SharedKey code back in the day when we had issues with it. So right now I'm not sure if there's a real need to switch.

**Comment by kpfaulkner** [comment]
Fair enough, I'll stash the code away for a rainy day.

Cheers

Ken

**Comment by mcardosos** [comment]
Fixed
