### ISSUE TITLE
Support polling relative URLs

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#17221]
Today, pollers reject relative URLs:
https://github.com/Azure/azure-sdk-for-go/blob/fc95da9cfa30aa95bb62d59950267634db929195/sdk/azcore/internal/pollers/util.go#L50-L53

I don't think anything other than autorest.testserver cases is blocked by this but grepping the Python repo I see that Azure Communication Services and Cognitive Services return relative URLs for polling, so it could be a future onboarding problem.

**Comment by jhendrixMSFT** [comment]
It could be that this requirement is specific to ARM, I'd have to go read their spec to confirm.

**Comment by jhendrixMSFT** [comment]
Confirmed, the ARM RPC [spec](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#asynchronous-operations) requires the polling URIs to be absolute.
