### ISSUE TITLE
[azservicebus] Configure cloud environment?

### ISSUE THREAD

**Issue by yarinm** [Azure/azure-sdk-for-go#17259]
We've been using the old library [azure-service-bus-go](https://github.com/Azure/azure-service-bus-go/) and using that SDK we were able to configure the cloud environment by using `servicebus.NamespaceWithEnvironmentBinding` or  just modifying the `servicebus.Namespace` attribute `Environment`

I couldn't find a way to do the same in the new SDK, what am I missing?

**Comment by jhendrixMSFT** [comment]
Richard can correct me if I'm wrong, but I don't believe this is supported yet.  Related to https://github.com/Azure/azure-sdk-for-go/issues/8328

CC @chlowell

**Comment by richardpark-msft** [comment]
Hi @yarinm, in the previous library the cloud binding was used to auto-add a suffix to the namespace name.

In azservicebus we no longer do that - you can just pass the entire hostname verbatim (<namespace>.servicebus.windows.net, for instance) if you want to use a TokenCredential, or just pass in a connection string, which will contain the full hostname in it automatically.
