### ISSUE TITLE
App Configuration: Setting semantics

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-go#17264]
But this argument is for getting a setting - it has different semantics than ListSetting().

Is there a reason we're not just using 'key' as a positional argument?

_Originally posted by @richardpark-msft in https://github.com/Azure/azure-sdk-for-go/pull/17240#discussion_r822956769_

**Comment by antkmsft** [comment]
Then the key will be duplicated in the `Setting`, and as a parameter, I think it will be confusing.
If you look at the Java or .NET SDK, they have either methods with this semantics, taking `Setting`, or an overload with string key and optional string label, but not a mix.

As of ideas, initially, I had `Setting` being a struct with private fields, which you could only create as `NewSetting()` with string key parameter. It had getters to get fields as pointers, and "Setters", such as `WithLabel()`, `WithValue()` also taking strings and not pointers. Not all fields were writeable - the same as in other SDKs. And it was not possible then for user to create a setting without key. `With...()` were retutning a copy of the struct, with the corresponding field being set. But I was told such API is not Go-like, where everything is much simpler, uses bare structs, pointers, relies on comments etc.

BTW, other SDKs `Setting` have IsReadOnly a read only field, we currently don't. Should we then drop an extra `isReadOnly` argument from the `SetReadOnly()` function?

**Comment by seankane-msft** [comment]
Based on the swagger, it looks like the setting value is the only required value. You could put the rest of the values in the `GetSettingOptions` struct and if a user does provide them the `Setting` struct can be constructed with them, otherwise it can be a Setting with just the value field set.

**Comment by richardpark-msft** [comment]
I'd had a discussion with @jhendrixMSFT for a similar function in Service Bus. I wonder if this is a possible signature:

```go
func GetSetting(ctx context.Context, name string, options *struct {
   label *string
   // other options
}) Setting
```

Which I believe would match what is expected from the user.
