### ISSUE TITLE
Feature Request: Azure Active Directory Groups

### ISSUE THREAD

**Issue by danielhelfand** [Azure/azure-sdk-for-go#1727]
I am looking to use Terraform to create and manage Azure Active Directory Groups. My main goal is to create groups and attach roles to those groups. 

Creating groups and roles have implications for other Azure services, such as Key Vault. Since Terraform is developed using Go and relies on azure-sdk-for-go, I thought it would make sense to open this issue here.

**Comment by joshgav** [comment]
Thanks @danielhelfand!

Can you meet your scenarios with [graphrbac#GroupsClient.Create](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac#GroupsClient.Create) and [authorization#RoleAssignmentsClient.Create](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization#RoleAssignmentsClient.Create)?

To get you started:

* Sample for creating an ADApplication: <https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/graphrbac/graph.go#L41>. Please open an issue in that repo if you'd like a sample for an AD Group specifically.
* Sample for creating a role assignment: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/authorization/auth.go#L43

cc @metacpp re adding this to Terraform.

**Comment by danielhelfand** [comment]
@joshgav As a follow up here, I think my understanding of RBAC with Azure might be misunderstood. I guess that roles aren't assigned to AD groups with Azure. It seems roles are more handled at the user, resource, and subscription levels.

However, groups do allow for controlling access to resources in Azure as documented [here](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-manage-groups). I'm wondering if a better approach may be to allow resources to restrict access to groups.

**Comment by vladbarosan** [comment]
@danielhelfand there is an SDK call for https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/groups.go#L121 , is there anything pending on the go SDK here ? Otherwise I would go ahead and close this issue.

**Comment by danielhelfand** [comment]
@vladbarosan Thanks for pointing this out. This looks like exactly what I'm looking for with this issue. I have another [issue](https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/186) open with `azure-sdk-for-go-samples` to show how to use it that I'll keep open, but this issue can be closed.
