### ISSUE TITLE
[azservicebus] Provide a Service Bus error type that customers can use for actionable errors.

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#17283]
(This has come up in a few different customer issues (ex: [#16088](https://github.com/Azure/azure-sdk-for-go/issues/16088#issuecomment-1062454958)), and it's worth a discussion.)

From looking at a few customers programs, I've seen a pattern that basically looks like this:

```go
for {
  client, receiver := GetReceiver()

ReceiveLoop:
  for {
    messages, err := receiver.ReceiveMessages(5)

    if err != nil {
      // customer might add in their own backoff.
      receiver.Close()
      client.Close()

      client, receiver = GetReceiver()
      continue
    }

    for _, msg := range messages {
      err = receiver.CompleteMessage(msg)

      if err != nil {
        // customer might add in their own backoff.
        client, receiver = GetReceiver()
        continue ReceiveLoop
      }
    }
  }
}
```

Where basically any error is treated as a "restart the client". This is probably typical and is basically a variant on "error from stateless call, probably retry it all". 

I think it's worthwhile to consider if there are some areas where that kind of retry logic would be wasteful or incorrect and it'd be worth adding in a programmatically useful type.

Something similar to this:

```go
package azservicebus

type Error struct {
  Code Code
  Inner error
}

func (e Error) Error() string { 
  return e.Inner.Error()
}

// NOTE: we should also make this work with errors.As()

type Code string

const (
  // (this is my first pass, so there might be more, just documenting one that immediately occurs to me).
  CodeNotFound = "notfound"
  CodeLockLost = "locklost"
  CodeUnauthorized = "unauthorized"
)
```

### Message lock lost (ie: 'locklost')

Messages (in peek lock mode) have a lock, which expires after a set period of time. Restarting a connection/link here would be unnecessary and expensive, so the "standard" error handling in the top level example would not be a good idea.

There are two internal paths that can happen when settling, both of which return separate error types:

```
// go-amqp amqp.Error, if you settled via normal AMQP constructs

{
  Condition:"com.microsoft:message-lock-lost"
  Description:"The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a5507261-5c0a-4aee-9df8-8af1326dea2a, TrackingId:8dd5ab0300007e6b008d6d84622bde3d_G38_B17, SystemTracker:<host>:Queue:queue-16db7812269186b4, Timestamp:2022-03-11T23:43:33"
  Info:map[string]interface {} nil
}
```

We also have a mode called 'backup' message settlement, where we use a separate link. When we do this the error comes back as an RPCError{}, since it happens on our RPC $management link, not the original receiver link.

```
// azservicebus rpcError (it's not exposed right now)
{
  RPCResponse: {
  	Code: 410
    Description: "The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a0ecf2d4-3f4f-4b72-9604-ce936e2c78e2, TrackingId:ed803096-27bb-401b-a037-ea12471d9259_B17, SystemTracker:<host>:Queue:queue-16db7aaedfe1797b, Timestamp:2022-03-12T00:31:03"
    Message: <the actual AMQP message received back from the RPC link>
  },
  RPCCode: 410,     // (replicated from the actual RPCResponse)
}
```

Customers would need to check both to check for the single logical error.

### Invalid permissions/Entity not found ('unauthorized'/'notfound')

These are "fail and fail hard" type of errors. They're probably deployment issues or similar, and will require human intervention. The "retry and recreate" logic in the sample at the top would also be bad here.

You'd normally get something like a 401 or possibly a 404 in HTTP parlance, and we could do something similar here. This gives customers that want to a chance to do something indicating the fatal nature of these problems.

### Possibly common questions

- Let the customer trigger off the actual error type 

  This ends up being somewhat messy. In some cases the error can come from different code paths, and won't be the same type. See the message lock lost section above for an example.

  In addition, this would place a dependency on the customer's code on lower level libraries like go-amqp, basically making it's public surface _our_ public surface. We don't do that today.

- Can we re-use some existing error type?
   
  `azcore.ResponseError` is the closest analogue to this, but won't work since it assumes you have a net.Response and is basically HTTP centric.

- Do we need string error codes?

  No, but it seemed nice to avoid the temptation of trying to shoe-horn all the error codes into what might appear to be http status codes.

**Comment by JeffreyRichter** [comment]
I think we'd need a complete list of errors that "go away by restarting the client" is guaranteed (or at least really likely) to fix the problem? I wouldn't want an SDK function to get into an infinite loop - customer will blame us for this.

**Comment by JeffreyRichter** [comment]
Is this the kind of thing we can ship without today and perhaps add later?
Joel & I had a similar design for errors that are HTTP-retryable and it never felt good and so we got rid of it.
This is practically identical to that and this also does not feel good to me.

**Comment by richardpark-msft** [comment]
> Is this the kind of thing we can ship without today and perhaps add later? Joel & I had a similar design for errors that are HTTP-retryable and it never felt good and so we got rid of it. This is practically identical to that and this also does not feel good to me.

There are some distinctions that I think are notable:

1. HTTP response errors are standardized as http.ResponseError and further, they have a `StatusCode` field with a documented range of errors (just HTTP). This means we've already (implicitly) documented how a customer can distinguish a 404 from a 401, for instance.

In AMQP, our errors can come from multiple places for the same operation (the message settlement section mentioned in the main issue is an example). We would have to do a mapping to something that logically represents the same failure to get a similar effect. 

There are standard AMQP condition codes but those only apply to operations done directly through the AMQP stack. Things done over the management link do not naturally come back that way, although we _could_ do something there.

In either case we'd be returning an error type that comes from a separate package that customers would not necessarily directly reference (go-amqp). 

2. AMQP is stateful in it's connection.

A customer could realistically just retry forever with an HTTP request. Since there's no intermediate state each request is as fresh as it can be.

AMQP doesn't work like that - we have a persistent TCP connection and stateful links. This means that failures can possibly carry meaning in that they indicate "this operation failed, but the connection is fine" (message lock lost) vs "this operation failed and this connection is dead" (credentials failed, entity not found, etc..).

Now, having typed that out I realize that a simple `bool` would not work here since the "it's fatal/terminal" behavior is probably "recreate the connectIon".

I've scheduled some time for us to talk about it more and I'll update the issue with our conclusions.

**Comment by richardpark-msft** [comment]
Okay, some more offline discussion happened and I think we have some approaches we can take. 

The core problem to solve here is how the customer can determine what is wrong, and whether they have to do something about it. In HTTP libraries we solve this easily by just having azcore.ResponseError, which has an HTTP status code that tells a customer a _lot_ about what's happened, by virtue of these being standardized in `http.Status*`.

In AMQP we don't and some of the errors aren't actually protocol level - they're errors that come back from Service Bus that have meaning there and there only. 

If we want, we can easily mimic a similar structure to what we represent in azcore.ResponseError, by creating azservicebus.ResponseError, defined like this:

```go
package azservicebus

type Code string

const (
   // entity is not found (queue, topic or subscription)
   CodeNotFound = "notfound"

   // credentials are invalid
   CodeUnauthorized = "unauthorized"

   // generically, anything that requires a connection restart. Imlicit to this - we attempted to retry and ran out of retries.
   CodeConnectionLost = "connlost"   

   // message lock expired, no retrying is possible.
   CodeLockLost = "locklost"
)

type Error struct {
  // a programmatic code
  Code Code

  // a user-readable error message, comes back from Error()
  Message string
}
```

Then customers can do something like this:

```go
err := receiver.CompleteMessage(context.TODO(), message)

var are azservicebus.Error

if errors.As(err, &are) {
  if are.Code == azservicebus.CodeLockLost {
     // this is okay, maybe rollback some processing.
  } else {
     // something fatal happened
  }
} else {
   // any other unstructured errors are basically fatal.
}
```
 
```go
messages, err := receiver.ReceiveMessages(context.TODO(), 1, nil)

var are azservicebus.Error

if errors.As(err, &are) {
  if are.Code == azservicebus.NotFound || are.Code  == azservicebus.CodeUnauthorized {
    // setup error, kill the app and send out a red alert (fail fast)
  }
} else if err != nil {
   // something more generic.
}

```

@JeffreyRichter , what do you think?

**Comment by richardpark-msft** [comment]
>  then I would expect the AMQP package to return an AMQPError.

@jhendrixMSFT, I know we're talking about final stages for go-amqp, what do you think of this?
