### ISSUE TITLE
Signed url support with SAS token

### ISSUE THREAD

**Issue by NamrataJha** [Azure/azure-sdk-for-go#17291]
Currently for creating a [signed url](https://pkg.go.dev/gocloud.dev/blob#Bucket.SignedURL) we need a SharedAccessKey credential which in turn requires azure access key.

Is there any way to generate this signed url only with SAS token. Currently we are unable to do so as SAS token url takes anonymous credential while opening the bucket - [https://pkg.go.dev/gocloud.dev/blob/azureblob#example-OpenBucket-UsingSASToken](https://pkg.go.dev/gocloud.dev/blob/azureblob#example-OpenBucket-UsingSASToken).
Or is there any alternative to signed url that we can use with SAS token?

Our requirement is to be able to publish and download blobs from azure storage account. 
Seeing as SAS tokens are so widely used, doesn't makes much sense to have access key as a necessary requirement and not support this via SAS token.

Please redirect to any resource if already available.

Thanks!

**Comment by mohsha-msft** [comment]
Hey @NamrataJha ,

Thanks for reaching out!

SAS Key is an encrypted string. The only way to decode it or verify it is  to use private key (i.e. Azure Access Key used to encrypt it). SAS is just like a document signed with private key. So you can check whether SAS is valid or not if you have public key but you cannot decode it. That's the whole point of Assymmetric key encryption. You can check [this](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/zc_shared_policy_shared_key_credential.go#L63) to know more about how we sign SAS string.

**Comment by mohsha-msft** [comment]
Based on your use-case, I suggest you use [AzCopy](https://github.com/Azure/azure-storage-azcopy). It's a command line tool to upload/download/transfer data to and from Azure.
[Public Documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)

**Comment by NamrataJha** [comment]
Oh we are using it as blob store for a go service, not sure if azcopy would be suitable for that.
Is there any alternative available for signed Url that can be generated with SAS token? 
Correct me if I am wrong here, but as per my understanding SAS url is kind of like a pre-signed url. Can we generate a new url for download purpose from a SAS but for a short duration of time?

**Comment by mohsha-msft** [comment]
No,

You cannot edit a SAS. As I mentioned, it is pre-signed string. We use start time, end time, resource type, etc. parameters to create a string and sign it with your Access Key. So editing a SAS would mean decoding it, changing the parameters, and sign it again. It's equivalent to creating a new SAS.

I suggest you create SAS for short duration directly instead of trying to change the SAS itself.

**Comment by NamrataJha** [comment]
Thanks @mohsha-msft.
One more thing is there any method in azure go sdk, using which I can download with my existing SAS url. No changes made. Like can I use this [blobUrl here](https://github.com/Azure/azure-storage-blob-go/blob/b32b5e3579400739418747a71c4bffaf8a19c4a0/azblob/zt_examples_test.go#L396), to download the same way we do with signed url?

**Comment by mohsha-msft** [comment]
Hey @NamrataJha ,

I would suggest you to use [GetSASToken()](https://github.com/Azure/azure-sdk-for-go/blob/be7dabfd93b625114b3a3ac7724affc3e7c0cabd/sdk/storage/azblob/zc_container_client.go#L233) method to create the SAS. We don't have methods to deal with already created SAS.

**Comment by NamrataJha** [comment]
Thanks @mohsha-msft, something like this would be really helpful for us and help to remove a dependency on access key for simple read and write operations on blob store.
