### ISSUE TITLE
Scope internal resource manager ci to not trigger for eng/common changes

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-for-go#17313]
The new internal resource manager pipeline will trigger for all `/eng` changes. There are likely reasons I am not aware of. I would like to exclude `/eng/common` changes (made via the sync PR process) from triggering this pipeline as I think it unnecessary.

https://github.com/Azure/azure-sdk-for-go/blob/04000266f5b36085ebf02b4fd97a3684d63d9415/sdk/resourcemanager/internal/ci.resourcemanager.yml#L12

@tadelesh thoughts?

**Comment by tadelesh** [comment]
It's OK. I've deleted it with his [PR](https://github.com/Azure/azure-sdk-for-go/pull/17317).
