### ISSUE TITLE
unmarshal error using armdatafactory QueryByPipelineRun api

### ISSUE THREAD

**Issue by slightnerd** [Azure/azure-sdk-for-go#17334]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
-> 'Azure\azure-sdk-for-go\sdk\resourcemanager\datafactory\armdatafactory'

- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.

-> 'master'

- output of `go version`

-> go version go1.17.7 windows/amd64

- What happened?
- 
A QueryByPipelineRun Api call was made to the armdatafactory and the following error occurred: "TestQueryByPipeLine Error :  unmarshalling type *armdatafactory.ActivityRunsQueryResponse: json: cannot unmarshal string into Go struct field ActivityRunsQueryResponse.value of type map[string]interface {}" 

The following is the payload returned and processed by the ActivityRun Unmarshal method in zz_generated_models.go source module.  If you look at the the code the handling of the handling of AdditionalProperties will not work for json keys : iterationHash, Id, recoveryStatus. The code is trying to map to a map[string[interface{} but this are just *string values.

{
   "value":[
      {
         "activityRunEnd":"2022-03-20T19:21:40.7680142Z",
         "activityName":"Azure Function1",
         "activityRunStart":"2022-03-20T19:21:38.4892688Z",
         "activityType":"AzureFunctionActivity",
         "durationInMs":2278,
         "retryAttempt":null,
         "error":{
            "errorCode":"",
            "message":"",
            "failureType":"",
            "target":"Azure Function1",
            "details":""
         },
         "activityRunId":"62025fb3-9dc8-4a27-8a56-614b40cb86bc",
         "iterationHash":"",
         "input":{
            "functionName":"filecascadetrigger",
            "method":"POST",
            "headers":{
               
            }
         },
         "linkedServiceName":"",
         "output":{
            "MessageType":"Info",
            "infilename":"payerx._VHTS_20220320_152124_44107.chrt2.map",
            "infolderpath":"ingestion/payers/filedrop/payerx",
            "outfilename":"payerx._VHTS_20220320_152124_44107.chrt2.map",
            "outfolderpath":"ingestion/payers/reject/payerx/DT_20220320",
            "outfolderreject":"ingestion/payers/reject/payerx/DT_20220320",
            "filesystem":"stgcontainerslltest1",
            "payer":"payerx",
            "datetime":"_VHTS_20220320_152138_78592",
            "filetype":"reject",
            "prevfiletype":"filedrop",
            "runid":"02d9bafc-692e-4b9f-bfb7-2eb0b0aa158c",
            "sheetmap":[
               ""
            ],
            "filekey":"FK_payerx__VHTS_20220320_152138_78592_",
            "effectiveIntegrationRuntime":"AutoResolveIntegrationRuntime (East US)",
            "executionDuration":0,
            "durationInQueue":{
               "integrationRuntimeQueue":0
            },
            "billingReference":{
               "activityType":"ExternalActivity",
               "billableDuration":[
                  {
                     "meterType":"AzureIR",
                     "duration":0.016666666666666666,
                     "unit":"Hours"
                  }
               ]
            }
         },
         "userProperties":{
         },
         "pipelineName":"pipelineCascade",
         "pipelineRunId":"02d9bafc-692e-4b9f-bfb7-2eb0b0aa158c",
         "status":"Succeeded",
         "recoveryStatus":"None",
         "integrationRuntimeNames":[
            "autoresolveintegrationruntime"
         ],
         "executionDetails":{
            "integrationRuntime":[
               {
                  "name":"AutoResolveIntegrationRuntime",
                  "type":"Managed",
                  "location":"East US"
               }
            ]
         },
	"id":"xxxxx"
      },
      {
         "activityRunEnd":"2022-03-20T19:21:57.8799965Z",
         "activityName":"Switch1",
         "activityRunStart":"2022-03-20T19:21:42.0336567Z",
         "activityType":"Switch",
         "durationInMs":15846,
         "retryAttempt":null,
         "error":{
            "errorCode":"",
            "message":"",
            "failureType":"",
            "target":"Switch1",
            "details":""
         },
         "activityRunId":"aadd067d-ec1e-4ff3-aaaa-8af5b93122f0",
         "iterationHash":"",
         "input":{
            
         },
         "linkedServiceName":"",
         "output":{
            "expression":"reject"
         },
         "userProperties":{
            
         },
         "pipelineName":"pipelineCascade",
         "pipelineRunId":"02d9bafc-692e-4b9f-bfb7-2eb0b0aa158c",
         "status":"Succeeded",
         "recoveryStatus":"None",
         "integrationRuntimeNames":null,
         "executionDetails":null,
         "id":"xxxxx"
      }
   ]
}

- What did you expect or want to happen?

-> I expected this to properly marshal the result.

- How can we reproduce it?

Any call to Activity run using a specific runid should cause the issue.

	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		fmt.Println("NewDefaultAzureCredential Error : ", err.Error())
		return
	}
	dtto := time.Now().AddDate(0, 0, 1)
	dtfrom := time.Now().AddDate(0, 0, -30)
	filterParameters := armdatafactory.RunFilterParameters{}
	filterParameters.LastUpdatedAfter = &dtfrom
	filterParameters.LastUpdatedBefore = &dtto

	client := armdatafactory.NewActivityRunsClient(subscriptionID, cred, nil)
	_, err := client.QueryByPipelineRun(ctx, resourceGroupName, factoryName, runid, filterParameters, nil)
** Error Happens here

- Anything we should know about your environment.
It is a typical azure environment. Running in labs with minimal security for now.

**Comment by tadelesh** [comment]
@slightnerd We have updated the type for some open object. Could you please try the new version [here](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fresourcemanager%2Fdatafactory%2Farmdatafactory%2Fv0.3.0)? Thanks for the feedback.

**Comment by slightnerd** [comment]
New version works great.

**Comment by tadelesh** [comment]
@slightnerd Thanks. I'll close the issue then.
