### ISSUE TITLE
Nil pointer exception if nil options passed in ListBlobsFlat

### ISSUE THREAD

**Issue by andrewbaxter** [Azure/azure-sdk-for-go#17335]
### Bug Report

On azblob v0.3.0

The code was changed to reuse the passed in options for subsequent pagination requests here: https://github.com/Azure/azure-sdk-for-go/pull/16992

However, if `nil` is passed in for options this causes a panic when the advancer tries to set the new marker.  This conflicts with conventions elsewhere in the code that allow nil values to be passed in (and previously a nil value was also accepted here).

**Comment by zezha-msft** [comment]
Thanks for reaching out!

We will take a look and make a fix in the next release.

**Comment by bcvanmeurs** [comment]
I can confirm I encountered the same bug.

**Comment by mohsha-msft** [comment]
Hey @andrewbaxter , @bcvanmeurs ,

Thanks for reaching out! 
I've fixed the issue and I'll ship it in the next release.

**Comment by bcvanmeurs** [comment]
Great, thanks!

**Comment by mohsha-msft** [comment]
Hey @andrewbaxter @bcvanmeurs  ,

[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. I have fixed the issue [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#ContainerClient.ListBlobsFlat).

Please reach out and reopen the issue if it still persists. 

Thanks a lot for your feedbacks!
