### ISSUE TITLE
Investigate adding support for the pipeline as an opt-in feature

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1733]
As a transition step we should investigate adding support for the pipeline as an opt-in feature.  Current prototype is to add a Pipeline field to the generated clients along with non-exported preparers and responders.  If the Pipeline field is not nil then the API will use it instead of the regular preparer/sender/responder.

**Comment by tombuildsstuff** [comment]
out of interest, what’s the timeframe for moving across to the new Pipeline approach exclusively?

**Comment by jhendrixMSFT** [comment]
It will probably depend to some degree on any feedback obtained once we have opt-in support for it.  While I can't commit to a firm date I don't anticipate it happening until after summer of this year as it's a pretty big breaking change.

**Comment by jhendrixMSFT** [comment]
After some discussion we've decided that we won't be doing this in the "v2" codegen.
