### ISSUE TITLE
Add support for MySQL/PostgreSQL flexible server API endpoints

### ISSUE THREAD

**Issue by csandanov** [Azure/azure-sdk-for-go#17331]
### Feature Request

I'd like to list available tiers for the flexible server deployment option, right now only single server supported.

**Comment by lirenhe** [comment]
@csandanov, could you provide more detail of the ask? e.g.
1. What version of the SDK that lacks of this feature
2. What API did you call and what is the expected behavior v.s. the actual behaviour?

**Comment by csandanov** [comment]
Oh, I'm sorry, after updating to v62.2.0 I see these APIs have already been added. Thank you for your response!
