### ISSUE TITLE
azservicebus dependency update fails

### ISSUE THREAD

**Issue by mibo-fdc** [Azure/azure-sdk-for-go#17357]
### Bug Report

go get -u ./...

fails with

github.com/edeka-digital/nemo/pkg/queue imports
	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus imports
	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal imports
	github.com/Azure/azure-sdk-for-go/sdk/messaging/internal/cbs: cannot find module providing package github.com/Azure/azure-sdk-for-go/sdk/messaging/internal/cbs

on the azure component.

Go 1.18 (but that shouldn't matter?)

**Comment by mibo-fdc** [comment]
I still get the same error unfortunately:

github.com/edeka-digital/nemo/pkg/queue imports
	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus imports
	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal imports
	github.com/Azure/azure-sdk-for-go/sdk/messaging/internal/cbs: cannot find module providing package github.com/Azure/azure-sdk-for-go/sdk/messaging/internal/cbs

**Comment by richardpark-msft** [comment]
@mibo-fdc - sorry about that, I didn't see that the issue auto-closed. 

https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fmessaging%2Fazservicebus%2Fv0.4.0

We've released v0.4.0, which fixes this issue. We bumped the minor version now that we're using Go 1.18 specific features.
