### ISSUE TITLE
Bot service slack channel doesn't save client id/secrets

### ISSUE THREAD

**Issue by shana** [Azure/azure-sdk-for-go#17358]
When creating or updating bot service slack channels, the `registerBeforeOAuthFlow` field must be set to true in order for the client id and secrets data to be saved. This field is incorrectly marked read-only in the spec, so generated clients don't include it when creating/updating slack channels, causing the `clientId`, `clientSecret`, `signingSecret` and `validationToken` fields to be ignored on the server side. This breaks all clients trying to automate creating slack channels using the azure sdk.

Whatever tests this is doing to confirm that these fields are being correctly received are misleading, because the json that the server returns includes the data that was sent and not the actual data that it saved. A second call to query the data returns all the fields set to null.

Rest API spec issue: https://github.com/Azure/azure-rest-api-specs/issues/18367

Field not included in the client:
https://github.com/Azure/azure-sdk-for-go/blob/b375326a136a64a03eb3d5ce0277f562c2ed455c/services/botservice/mgmt/2021-03-01/botservice/models.go#L2692-L2713

**Comment by youyu16** [comment]
@shana For null value returned, it is expected result, because we always exclude sensitive data. but you can check if Client ID changed after 15 mins.

**Comment by shana** [comment]
> @shana For null value returned, it is expected result, because we always exclude sensitive data. but you can check if Client ID changed after 15 mins.

@youyu16 @lirenhe That is not relevant for this issue. This is not about what the API returns, it's about how it handles the sensitive values.

1. The server side API only saves the sensitive values if `registerBeforeOAuthFlow` is set to `true`.
2. By default, `registerBeforeOAuthFlow` is set to be `false`.
3. `registerBeforeOAuthFlow` is marked `read only` in the API spec.
4. SDK clients see the `read only` flag on the `registerBeforeOAuthFlow` API spec and do not include the field in request payloads
5. Server side API does not see the `registerBeforeOAuthFlow` in the payload, assumes it is set to `false`, and discards sensitive values and never saves them.

I'm not sure how to make this explanation any clearer.

**Comment by lirenhe** [comment]
@youyu16, could you help to confirm whether the behaviour of 'registerBeforeOAuthFlow' is correctly defined in Swagger?
If not, please help to submit a PR for the Swagger fix and we could regenerate the SDK based on the updated Swagger spec. Thanks

**Comment by bobokids** [comment]
@shana , currently it's be design to keep registerBeforeOAuthFlow as false. when you call the API, you can get the rediectAction URL in response payload, and that will trigger the Slack UI to validate user and consent scopes, after consent by Allow button, bot service will be called and get the validated token. Would you try if this flow works for you?
Would you let us know what the scenario is for your case that need to store id/secret before the validation? from service point of view, we can support this behavior with some code change in Swagger and channel if you do have the requirement, but I would suggest to try the current flow if possible.

**Comment by shana** [comment]
That flow doesn't work in an automation scenario, this is being used to manage channels with terraform in CI. Slack tokens are managed separately and provided to the API, having it redirect to a UI for manual interaction is not feasible, obviously, this is running in a headless automation environment.

The slack token information works just fine with any manual steps if I pass registerBeforeOauthFlow set to true along with the request, I've set up multiple channels like this already. The API documentation for the call itself even notes that it should be set to true if you're automating it, so it's obviously meant to be settable, not readonly.

**Comment by bobokids** [comment]
@shana , thanks for the clarification. We will fix the issue per the description. An item in Bot Service repo was created to track the issue [here](https://github.com/microsoft/BotFramework-Services/issues/335).

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
