### ISSUE TITLE
Add Windows Web Account Manager (WAM) Brokered Authentication Support

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#17388]
This is a tracking work item for creating/finishing the new Azure.Identity.BrokeredAuthentication client library (separate package from the existing Azure Identity client library).

Related:
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity.BrokeredAuthentication/README.md
- Default to a silent auth experience that doesn't show the account picker UX if a user is already logged in. See https://github.com/Azure/azure-sdk-for-net/issues/36178

Dependencies:
- MSAL WAM is supported (Beta) in .NET and Python today
- MSAL WAM support (Beta) for Java and Javascript is not yet available but is expected to be available in time for this scheduled development milestone.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-go/issues/21754
- [ ] https://github.com/Azure/azure-sdk-for-go/issues/20410
```

**Comment by joshfree** [comment]
Link to dependency - https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/284

**Comment by chlowell** [comment]
Blocked on https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/243
