### ISSUE TITLE
go-redis/redis - Microsoft Entra Auth Sample

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#17384]
Tracking issue for dogfooding and creating code samples (or documentation) to show best practices for how to use AAD Auth with popular 3rd party OSS Redis clients when connecting to Azure.

Depending on the outcome of the dogfooding:

**Possible Outcome 1:** 0-1 days of extra work (minimal sample code is required to enable the experience):
- Check-in a thin / simple code sample project to our sdk repo.
- Share the sample with the Azure Redis team so that they can then share the sample with customers, publish updated docs, and also validate the service handles credential revocation and similar scenarios to test with the provided sample.

**Possible Outcome 2:** ~1 week of extra work (significant sample code is required to enable the experience):
- Discuss the investigation results with the Identity SDK and Redis teams before proceeding 
- Based on the discussion, decide on whether we should be building a sample or an extension library that is shipped instead.

**Possible Outcome 3:** (using AAD Auth with the client is blocked until code changes are first made to the OSS Redis client):
- Discuss the investigation results with the Identity SDK and Redis teams.
- File GitHub issue with 3rd party project.  Provide as much details as possible, including any code samples, gists, etc.

**Comment by scottaddie** [comment]
go-redis v9.5.2 [added an Options.CredentialsProviderContext feature](https://github.com/redis/go-redis/pull/2998) that supports Microsoft Entra authN. Let's add a code sample to this repo. Once completed, add a new table row to [this Learn doc section](https://learn.microsoft.com/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication#client-library-support) with a link to the sample.

**Comment by chlowell** [comment]
The example is live in the package docs for [v1.8.0-beta.2](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.8.0-beta.2#example-package-Redis). I'll leave this issue open to track updating the Learn doc after the stable v1.8.0 release.

**Comment by chlowell** [comment]
Closed by https://github.com/MicrosoftDocs/azure-docs-pr/pull/290302
