### ISSUE TITLE
Support version 4.2 in Cosmos DB API for MongoDB

### ISSUE THREAD

**Issue by polys** [Azure/azure-sdk-for-go#17390]
### Feature Request

See https://github.com/hashicorp/terraform-provider-azurerm/issues/15765

https://devblogs.microsoft.com/cosmosdb/azure-cosmos-db-api-for-mongodb-v4-2-is-here-three-reasons-to-upgrade-now/

**Comment by ArcturusZhang** [comment]
Hi @polys thanks for this issue.

The corresponding swagger has been released: https://github.com/Azure/azure-rest-api-specs/blob/568e394c3634d052ddec89f685b4afb5ab21aaec/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/cosmos-db.json#L8507
We will release a new version of cosmosdb very soon.
@Alancere could you please follow up on this?

**Comment by Alancere** [comment]
Hi @polys thanks for this issue!
Releasing a new package will require the service to submit a new SDK release request,
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by navba-MSFT** [comment]
Discussed with @RickWinter and removed the CXP Attention label.
