### ISSUE TITLE
How to create a Blob Block Client with null/anonymous credentials?

### ISSUE THREAD

**Issue by AsafMah** [Azure/azure-sdk-for-go#17400]
### Bug Report

- import path of package in question - "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
- SDK - azblob v0.3.0, azcore v0.21.1
- output of `go version`

I want to transfer from the old azblob library (that was in the other repo) to the new one.

I'm using blobs with SAS, so I don't need nor want any additional credentials.

When creating a client like so:
`azblob.NewBlockBlobClient("some_sas_url", credential, nil)`

The credential is required and can't be nil.

`azcore` used to have `NewAnonymousCredential`, but it was removed in version 0.20..
I haven't found anything that can serve the same purpose in `azidentity`

How to proceed?

**Comment by mohsha-msft** [comment]
Hey @AsafMah ,

Thanks for reaching out!
We have client constructors such as [NewBlockBlobClientWithNoCredential](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/zc_block_blob_client.go#L42) that can be used here.
