### ISSUE TITLE
Tables should have an OData query builder to help customers properly escape input

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-go#17419]
Per https://github.com/Azure/azure-sdk/issues/979, our min bar across languages is providing a helper to allow customers to safely construct queries with proper escaping.  [Relevant xkcd](https://xkcd.com/327/) for why we should add similar basic support in Go.

You can see .NET's version at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L1360 and https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/TableOdataFilter.cs#L28.

**Comment by jhendrixMSFT** [comment]
Can we get more info here?  We should already be escaping query params.  Generally speaking, "builders" are something of an anathema in Go.

**Comment by jhendrixMSFT** [comment]
CC @seankane-msft @JeffreyRichter
