### ISSUE TITLE
Support for client assertions

### ISSUE THREAD

**Issue by aramase** [Azure/azure-sdk-for-go#17417]
### Feature Request

In the [Azure Key Vault Provider for Secrets Store CSI Driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure) we're using:

1. [adal](https://github.com/Azure/go-autorest/blob/master/autorest/adal/cmd/adal.go) for service principal (client secret), managed identity (user-assigned and system-assigned)
2. [msal](https://github.com/AzureAD/microsoft-authentication-library-for-go) for the new workload identity federation support.

We eventually want to move to using Azure Identity go SDK for supported auth methods instead of relying on adal/msal individually. Using azure identity sdk will provide us with the benefit of token cache and relying on the sdk to make backward compatible changes when there are changes to msal in the future. 

Opening this issue as the azure identity go sdk doesn't support client assertions.

**Comment by scottaddie** [comment]
Some MSAL work (https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/292) must be completed before this feature can be added to Azure Identity.
