### ISSUE TITLE
[VirtualMachineClient] ListComplete response (iter.Value()) is not consistent with Get API and Azure CLI 

### ISSUE THREAD

**Issue by diyor-uptycs** [Azure/azure-sdk-for-go#17430]
### Bug Report

- `github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2021-12-01/compute`
- SDK version -`v61.4.0`, `v63.0.0`
- Go verion - `go version go1.17.8 linux/amd64`

- **What happened**?
**Resource** field (struct) has `properties`, `location` and `tags` fields set to `nil` for `VirtualMachine` response received from `ListComplete` call. 
![Screen Shot 2022-04-04 at 10 35 16](https://user-images.githubusercontent.com/99381687/161480891-7e431807-1654-4365-a998-abc962f7a812.png)

However, Azure CLI command (az vm list --resource-group {group_name}) and VirtualMachineClient's Get call return values for those fields. 
- **What did you expect or want to happen**?
Get consistent VirtualMachine data when using ListComplete, Get, and CLI commands 
- **How can we reproduce it**?
Compare outputs from ListComplete, Get and CLI command (az vm list)

Thanks!

**Comment by lirenhe** [comment]
@tadelesh, could you help to take a look?

**Comment by tadelesh** [comment]
@diyor-uptycs I've tried the API and it works fine. Could you please paste your code here?
![image](https://user-images.githubusercontent.com/1726438/162889712-a8e97fe3-7896-483d-9b15-4055645ee258.png)

**Comment by diyor-uptycs** [comment]
@tadelesh Can you expand `Resources` field? Can you see `properties` and `location` fields being not nil?
Try to compare those two fields to the result (the same fields) from the CLI command (az vm list --resource-group {group_name}).
Result of the CLI command provides value to those fields.

**Comment by tadelesh** [comment]
@diyor-uptycs Sorry for misunderstanding. You are right. The HTTP response for list API seems lose some param. CLI might use some special logic to put back such param. I'll involve the service team to have a look. Thanks for the feedback.

**Comment by jaylabell** [comment]
@Drewm3 Can you please take a look at this VM issue?

**Comment by Drewm3** [comment]
Moving Jayla's issues over to me.

**Comment by Drewm3** [comment]
@diyor-uptycs or @navba-MSFT, could you clarify the bug that you believe is occurring in the the REST API along with the specific API that you feel has the bug? It is unclear from the issue above.

**Comment by Drewm3** [comment]
Resolving this due to no update
