### ISSUE TITLE
Reconsider exporting symbols from internal modules

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#17450]
[`azcore/log`](https://github.com/Azure/azure-sdk-for-go/blob/a7dfae471f382c8e7bf80492cc054d2566ae4c9f/sdk/azcore/log/log.go#L15-L31) exports a type and constants from `sdk/internal/log`. This instance is low risk but the pattern is troubling in general because it makes `sdk/internal` not really internal. We should discuss whether to allow this pattern and, if we decide to allow it, what guard rails to place around `internal` modules (we'd want them around e.g. `keyvault/internal` as well).

**Comment by JeffreyRichter** [comment]
Sometimes we do this because of dependency management. Internal defines symbols we need low in the system (like by Core) and we also expose them publicly. I think that is the case here. Joel would know for sure.

-- Jeffrey Richter
________________________________

**Comment by richardpark-msft** [comment]
I have a similar situation in `azservicebus` - I have a set of constants that represent the receive mode and I use them in both `azservicebus/internal` and `azservicebus` code.

**Comment by chlowell** [comment]
I think it's okay for a module to re-export things from its own `internal` subpackages when necessary. I'm concerned about internal modules like `sdk/internal`. These are nominally private, accessible only to SDK authors who may not know parts of them are functionally public due to being re-exported by some public module.

**Comment by chkohner** [comment]
Also, if you're going to export internals, please make sure they are fully exported. Atm, you export `azcore.TokenCredential = shared.TokenCredential` but not the corresponding TokenRequestOptions used as a parameter (thus making the interface unusable in practice). Also, it's unclear from a consumer perspective what the distinction between azcore and azpolicy is. (Which, btw, `azpolicy.TokenRequestOptions` IS exporting the shared internal atm, where azcore is not...)

**Comment by chkohner** [comment]
As an additional note, if you're considering NOT exporting key internals at all, that'd be really unfortunate. If they are exported (correctly), I can at least leverage key components (e.g. `azidentity` for managed identities) to make generic REST calls to Azure endpoints that don't have great Go SDK support yet.

**Comment by jhendrixMSFT** [comment]
I agree that `azcore` shouldn't be exporting content from `internal`.  I think some of this design predates when we refactored `azcore`.  The only wrinkle here is how to handle `Should()`, `Write()`, and `Writef()`.  The current implementation permits only SDK authors to call these funcs as they live in `internal` which at some point we thought was desirable.  How much do we really care about that?

**Comment by JeffreyRichter** [comment]
These are for logging, right? If so, I think it still best that only client lib authores beable to call them. Our logging infrastrutue is for logging client lib operations and is not designed as a general purpose logging mechanism for customers to use themselves.

**Comment by jhendrixMSFT** [comment]
Correct, this is just for logging.

In essence, the `internal/log.Event` type is an extensible enum type, intended to be extended by SDK authors, and used by customers when programmatically selecting a subset of events to log.

Its APIs are split into two buckets.  One is intended to be called by customers, and the other to be called by SDK authors.  In order to enforce this dichotomy, the buckets are implemented in `azcore/log` and `internal/log` respectively.

The bucketing of the APIs requires the `Event` type to be defined in `internal/log` so it's consumable in both modules.  And since `Event` participates in customer-facing APIs, it must be exported from `azcore/log` which puts us into this weird place.

**Comment by jhendrixMSFT** [comment]
These have been cleaned up and will be included in the `azcore@v0.24.0` release.
