### ISSUE TITLE
[Cognitive Search]: Roadmap for Cognitive Search client SDK

### ISSUE THREAD

**Issue by ThorstenHans** [Azure/azure-sdk-for-go#17458]
### Feature Request

Hey team 👋🏼 ,

I'd love to interact with Azure Cognitive Search using the Azure SDK for Go. Are there any plans to bring support for

- creating / modifying the index
- managing documents in the index

to the new SDK?

Thanks

**Comment by jhendrixMSFT** [comment]
@RickWinter who's the right person to follow up on this?

**Comment by RickWinter** [comment]
@ThorstenHans Can you share which version of the library you are currently using.
