### ISSUE TITLE
azcore@v0.23.0 "build constraints exclude all Go files" due to // +build go1.18

### ISSUE THREAD

**Issue by adeturner** [Azure/azure-sdk-for-go#17472]
### Bug Report

- import path of package in question

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/core.go

- SDK version

azure-sdk-for-go/sdk/azcore@v0.23.0
azure-sdk-for-go/sdk/keyvault/azkeys@v0.5.0

- output of `go version`

```
go version go1.17.5 linux/amd64
```

- What happened?

1. go 1.17 environment
2. I upgraded packages with go get -u ./...
3. It seems azcore@v0.23.0 and keyvault/azkeys@v0.5.0 uses build constraints "// +build go1.18", e.g. [core.go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/core.go)

Building my app now gives...

```
package github.com/blah/sdk/brokers
        imports github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
        imports github.com/Azure/azure-sdk-for-go/sdk/azcore: build constraints exclude all Go files in ...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.23.0
package github.com/blah/secretManagers
        imports github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys: build constraints exclude all Go files in ...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/keyvault/azkeys@v0.5.0
```

If I switch to 1.18 its also breaking other packages in my program, specifically due to "github.com/Azure/azure-sdk-for-go/sdk/azcore/to" which has not maintained backward compatibility

```
$ go build ./...
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zc_blob_lease_client.go:25:16: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zc_block_blob_client.go:145:20: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zc_container_lease_client.go:25:16: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zm_lease_request_options.go:63:16: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zm_lease_request_options.go:142:16: undefined: to.StringPtr
```

- What did you expect or want to happen?

Clearer instructions on how to avoid the issue
Ideally move to a consolidated/tested bundle release of compatible sdk packages

- How can we reproduce it?

(lets see how we go)

- Anything we should know about your environment.

WSL

EDIT1:

It is worth saying that having checked again, the latest release notes and azkeys readme states "Go version 1.18 or higher".

The problem with this is that go 1.18 is new and reliability thought processes keep most people <1.18. We should also note that Go Generics are provided with caveats/risk that mean we might want to avoid them in SDKs for a few releases.  In https://go.dev/doc/go1.18 it says:

_"These new language changes required a large amount of new code that has not had significant testing in production settings. That will only happen as more people write and use generic code. We believe that this feature is well implemented and high quality. However, unlike most aspects of Go, we can't back up that belief with real world experience. Therefore, while we encourage the use of generics where it makes sense, please use appropriate caution when deploying generic code in production."_

EDIT2: 

This looks like the last set of versions I'm using that work ok together

	github.com/Azure/azure-sdk-for-go/sdk/azcore v0.22.0
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.13.2
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys v0.3.0
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.6.0
	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v0.3.3
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.3.0
	github.com/Azure/go-autorest/autorest v0.11.24
	github.com/Azure/go-autorest/autorest/azure/auth v0.5.11
	
	github.com/Azure/azure-sdk-for-go/sdk/internal v0.9.1 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal v0.2.1 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/messaging/internal v0.0.0-20211208010914-2b10e91d237e // indirect

**Comment by adeturner** [comment]
It is worth saying that having checked again, azkeys states "Go version 1.18 or higher". 

The problem with this is that go 1.18 is new and reliability thought processes keep most people <1.18.

We should also note that Go Generics are provided with caveats/risk that mean we might want to avoid them in SDKs for a few releases: 

In [https://go.dev/doc/go1.18](https://go.dev/doc/go1.18) it says: 

_"These new language changes required a large amount of new code that has not had significant testing in production settings. That will only happen as more people write and use generic code. We believe that this feature is well implemented and high quality. However, unlike most aspects of Go, we can't back up that belief with real world experience. Therefore, while we encourage the use of generics where it makes sense, please use appropriate caution when deploying generic code in production."_

**Comment by adeturner** [comment]
The change is also breaking other packages I'm using in the same program...

$ go build ./...
# github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zc_blob_lease_client.go:25:16: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zc_block_blob_client.go:145:20: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zc_container_lease_client.go:25:16: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zm_lease_request_options.go:63:16: undefined: to.StringPtr
...gopath/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/zm_lease_request_options.go:142:16: undefined: to.StringPtr

**Comment by ItalyPaleAle** [comment]
This looks very similar to the issue I'm experiencing: https://github.com/Azure/azure-sdk-for-go/issues/17476 However, in my case I am using Go 1.18

**Comment by chlowell** [comment]
Thanks for opening this issue. I see you've figured out a workaround, and I'm sorry you had to do it. Your EDIT2 is what I would have suggested: downgrade to the latest modules requiring azcore v0.22.0 until you can upgrade to Go 1.18 and we release a compatible azblob. (@mohsha-msft, do you have an ETA?)

Let me give some context to address your other concerns. We use major version 0 for the initial unstable releases of a module; v1.0 and up are stable. For major version 0 releases, we increment the minor version when we break backward compatibility, as in azcore v0.23.0, which adds type parameters to a few APIs and therefore requires Go 1.18. We thoroughly discussed the benefit and risk of using generics and are confident that our limited usage of them doesn't make the SDK less reliable (see [this comment](https://github.com/Azure/azure-sdk-for-go/issues/16195#issuecomment-970815474) for example).

**Comment by adeturner** [comment]
Thanks @chlowell 

Dont get me wrong the new SDK is great. Completely understand about beta status and I don't mind recoding things as required, however this feels like an alpha-like failure?  I think there's two things that would be great

1) a compatibility test suite which builds combinations of all elements of the new SDK to avoid this moving forward
2) an SDK that doesnt force my software architecture by implementing [backwards compatibility](https://play-with-go.dev/build-flags-backwards-compatibility_go115_en/). In this case I maintain a generic multicloud Clean Architecture and google functions still only support 1.16....

**Comment by mohsha-msft** [comment]
Hey @adeturner ,

Thanks for reaching out!

If you look at the go.mod file of azblob SDK, you'll find that it still uses azcore 0.22.0 and internal 0.9.1.

Please note that azcore 0.23.0 (Using Go1.18) is a major release and has breaking changes which azblob hasn't picked up yet. So, it's natural that it'll break because you're trying something which azblob hasn't adopted yet.I don't think it's azblob which is at fault here.

The recent release of azcore is breaking azblob and it is concerning. I'm in the middle of picking these changes but will most likely release the support at the start of June (0.5.0). It's not part of the next release (0.4.0). @chlowell 

So, as for now I suggest you use the older version of azcore only.

**Comment by chkohner** [comment]
Just as a note, the "avoid using generics in production comment" isn't just about the compiler being 1.18. There are supporting tools and the like that are not ready for generics. For example, going through and upgrading our project because of this issue, we still get the following in golangci-lint (even after upgrading it as well):

```txt
level=warning msg="[linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] gosimple is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] noctx is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] rowserrcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] staticcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] stylecheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] unparam is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] unused is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
```

**Comment by vangent** [comment]
@richardpark-msft 

I'm trying to pick up `github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v0.4.0` for a bug fix, and am running into this problem. I also use `github.com/Azure/azure-storage-blob-go v0.14.0`.  I don't have any direct dependency on `azcore` or `azkeys`.

Is there any way to use these two Azure packages together with `go 1.17`?

**Comment by vangent** [comment]
```
package gocloud.dev/pubsub/azuresb
	imports github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore: build constraints exclude all Go files in /home/runner/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.23.0
package gocloud.dev/pubsub/azuresb
	imports github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
	imports github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal
	imports github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal/sbauth
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/policy: build constraints exclude all Go files in /home/runner/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.23.0/policy
package gocloud.dev/pubsub/azuresb
	imports github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/to: build constraints exclude all Go files in /home/runner/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.23.0/to

```

**Comment by richardpark-msft** [comment]
Hi @vangent , the upgrade to Go 1.18 is SDK-wide, so there isn't an azservicebus package that will work on an earlier version.

In your particular case, azcore is depended on by azservicebus.

**Comment by vangent** [comment]
@richardpark-msft OK. That is disappointing; forcing your users to update to the single latest version of `go` is pretty aggressive. I'm not willing to do it for my project (we've committed to supporting the latest 2 versions), which I guess means that I can't update any Azure packages until `go.1.19` comes out.

**Comment by mohsha-msft** [comment]
[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. Please take a look at [go.mod file](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azblob/v0.4.0/sdk/storage/azblob/go.mod). It required minimum Golang version >= 1.18. It points to azcore 0.23.

**Comment by adeturner** [comment]
Thanks, appreciated. Confirmed it works fine now
