### ISSUE TITLE
azcosmos ContainerClient.ReadItem() api design flaws

### ISSUE THREAD

**Issue by haitch** [Azure/azure-sdk-for-go#17499]
### Bug Report

- import path of package in question, github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos
- SDK version 0.2.0
- output of `go version`: 1.17

## 1. ContainerClient.ReadItem() returns internal error (github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos)

error type is github.com/Azure/azure-sdk-for-go/sdk/azcore/**internal**/shared.ResponseError, which cannot be used with [errors.As](https://pkg.go.dev/errors#As)

```imports github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared: build constraints exclude all Go files in /Users/haitch/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.23.0/internal/shared```

## 2. the error String is huge and not helpful

```
GET https://xxxx.documents.azure.com:443/dbs/xxxx/colls/xxxx/docs/bm90LWV4aXN0cy1kb2N1bWVudC1pZA
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: NotFound
--------------------------------------------------------------------------------
{
  "code": "NotFound",
  "message": "Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found, \r\nRequestStartTime: 2022-04-10T06:50:29.4549940Z, RequestEndTime: 2022-04-10T06:50:29.4549940Z,  Number of regions attempted:1\r\n{\"systemHistory\":[{\"dateUtc\":\"2022-04-10T06:49:28.7245594Z\",\"cpu\":2.231,\"memory\":428563352.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0166,\"availableThreads\":32762,\"minThreads\":40,\"maxThreads\":32767}},{\"dateUtc\":\"2022-04-10T06:49:38.7346652Z\",\"cpu\":3.468,\"memory\":429484620.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0238,\"availableThreads\":32765,\"minThreads\":40,\"maxThreads\":32767}},{\"dateUtc\":\"2022-04-10T06:49:48.7447365Z\",\"cpu\":1.916,\"memory\":429666960.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0103,\"availableThreads\":32762,\"minThreads\":40,\"maxThreads\":32767}},{\"dateUtc\":\"2022-04-10T06:49:58.7547995Z\",\"cpu\":0.658,\"memory\":429515804.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0213,\"availableThreads\":32765,\"minThreads\":40,\"maxThreads\":32767}},{\"dateUtc\":\"2022-04-10T06:50:08.7649017Z\",\"cpu\":0.691,\"memory\":429184104.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0324,\"availableThreads\":32764,\"minThreads\":40,\"maxThreads\":32767}},{\"dateUtc\":\"2022-04-10T06:50:18.7748870Z\",\"cpu\":0.687,\"memory\":428968572.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0249,\"availableThreads\":32765,\"minThreads\":40,\"maxThreads\":32767}}]}\r\nRequestStart: 2022-04-10T06:50:29.4549940Z; ResponseTime: 2022-04-10T06:50:29.4549940Z; StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-northcentralus1-fd14.documents.azure.com:14096/apps/91a5d8eb-7c7e-4b40-bf9c-269041b81a21/services/cfa9e6b9-c360-47f9-8c0e-3ef86a4a1555/partitions/ff757c70-8c3d-4b5d-93a3-025134a4a56f/replicas/132937695024563992s/, LSN: 6, GlobalCommittedLsn: 6, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#6, UsingLocalLSN: True, TransportException: null, BELatencyMs: 0.273, ActivityId: ec0f89cf-8f14-4f1c-99d0-37d3c0fed187, RetryAfterInMs: , TransportRequestTimeline: {\"requestTimeline\":[{\"event\": \"Created\", \"startTimeUtc\": \"2022-04-10T06:50:29.4549940Z\", \"durationInMs\": 0.0134},{\"event\": \"ChannelAcquisitionStarted\", \"startTimeUtc\": \"2022-04-10T06:50:29.4550074Z\", \"durationInMs\": 0.0112},{\"event\": \"Pipelined\", \"startTimeUtc\": \"2022-04-10T06:50:29.4550186Z\", \"durationInMs\": 0.1679},{\"event\": \"Transit Time\", \"startTimeUtc\": \"2022-04-10T06:50:29.4551865Z\", \"durationInMs\": 1.2691},{\"event\": \"Received\", \"startTimeUtc\": \"2022-04-10T06:50:29.4564556Z\", \"durationInMs\": 0.0856},{\"event\": \"Completed\", \"startTimeUtc\": \"2022-04-10T06:50:29.4565412Z\", \"durationInMs\": 0}],\"requestSizeInBytes\":575,\"responseMetadataSizeInBytes\":140,\"responseBodySizeInBytes\":87};\r\n ResourceType: Document, OperationType: Read\r\n, Microsoft.Azure.Documents.Common/2.14.0"
}
--------------------------------------------------------------------------------
```

## 3. the itemResponse is nil
Which I cannot use to read the response code.

## 5. Proposal:
We want a public strong typed error that can be used with [errors.As](https://pkg.go.dev/errors#As)
  1. expose github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared.ResponseError by remove the "internal" from package path
  2. capture this error and convert to a public typed error

**Comment by haitch** [comment]
Proposal:
  1. expose github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared.ResponseError by remove the "internal" from package path
  2. capture this error and convert to a public typed error

**Comment by jhendrixMSFT** [comment]
We do publicly export `ResponseError` from the `azcore` package so you can use `errors.As` on it.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/errors.go#L16

As for the long error message, we return the info as provided by the service, and I agree that this isn't great in some cases.  Maybe @ealsur can provide more info.

**Comment by ealsur** [comment]
The error message is provided by the service, there is no generation or interference from the Go SDK into it. The message will vary in size and content depending on the error itself. I agree for this particular case, the content is rather large and including a lot of data from the service itself, this seems to be a service issue. For your case, the important part is the first sentence that points to https://aka.ms/cosmosdb-tsg-not-found.

As for handling any errors, as @jhendrixMSFT mentioned, you should be able to do `errors.As` with `ResponseError` and then check the `StatusCode` property or the `RawResponse`.

**Comment by haitch** [comment]
thanks a lot! **azcore.ResponseError** does works for me.
