### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by DaddyBlues** [Azure/azure-sdk-for-go#17500]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by DaddyBlues** [comment]
thank you for your concern. im still having an issue of duplication id expecially on Azure portal. i donno that there is another user on the same email which is setup as global admin which i though its my role. i need to get back to my account on Daddy Blues but not Daddy Rock. Daddy Rock is the hacker who been hacking me since 40 days. need suupport and i always given an old page year 2020 from him .please

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jhendrixMSFT** [comment]
This appears to be spam so I'm locking the conversation.
