### ISSUE TITLE
sdk/azcore: TokenCredential should not be internal

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/azure-sdk-for-go#17522]
### Bug Report

In `sdk/azcore`, the `TokenCredential` interface, as well as related structs such as `TokenRequestOptions` are in an internal package and cannot be used by third-party code.

We are working with APIs that are not supported by the SDKs yet, including some that have no roadmap to be supported. In order to interact with them, we need to retrieve access tokens. Because the `TokenRequestOptions` is internal, we cannot invoke `GetToken` on an `azcore.TokenCredential` object and retrieve an access token. Thus, we cannot make API calls without having to _also_ re-implement the entire auth flow.

- import path of package in question, e.g. `sdk/azcore`
- SDK version e.g. `0.23.0`
- output of `go version`: `go version go1.18 linux/amd64`

**Comment by chlowell** [comment]
`TokenCredential` and `TokenRequestOptions` are exported, though from different packages, so it's possible to implement custom credential types and acquire a token from any credential type in `azidentity`:
```go
package main

import (
    "context"

    "github.com/Azure/azure-sdk-for-go/sdk/azcore"
    "github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
    "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

// implementing TokenCredential
type CustomCredential struct {}

func (c *CustomCredential) GetToken(ctx context.Context, options policy.TokenRequestOptions) (*azcore.AccessToken, error) {
	return nil, nil
}

var _ azcore.TokenCredential = (*CustomCredential)(nil)

// calling GetToken()
func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}
	tk, err := cred.GetToken(
		context.TODO(), policy.TokenRequestOptions{Scopes: []string{"https://management.azure.com/.default"}},
	)
	if err != nil {
		panic(err)
	}
}

var _ azcore.TokenCredential = (*CustomCredential)(nil)
```

**Comment by ItalyPaleAle** [comment]
Thanks for the explanation. I'll take a look at that and will let you know if I run into any issue.

**Comment by jhendrixMSFT** [comment]
For some additional context, there are two reasons why we have internal types that are exported via type aliases.
- To break cyclic dependencies.
- To offer a type in one package (e.g. `azcore`) but its usage in another (e.g. `runtime`).

I've refactored the internal content that's actually exported under an `internal/exported` package to make it clear.  In this process, it was discovered that we didn't actually need to do this with `TokenCredential` and its related types, so those are now defined in the packages from where they're exported.
