### ISSUE TITLE
Increase User Agent Maximum length

### ISSUE THREAD

**Issue by ms-henglu** [Azure/azure-sdk-for-go#17539]
### Feature Request

Currently, the `user agent` only supports maximum length of 24 characters which is too short.
For example, we have a terraform provider, its name almost exceeds the limitation `terraform-provider-azapi` and there're more necessary information that we need to put into `user agent`. Would you please remove this limitation?

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/policy/policy.go#L104

**Comment by jhendrixMSFT** [comment]
The constraints on the application ID come from the [general SDK guidelines](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy), so this isn't something that we can just change without a highly compelling reason.  In addition, there's value in keeping User-Agent content short and concise.

If you need to add additional data to the User-Agent, you'll need to write your own pipeline policy that lets you include arbitrary data.
