### ISSUE TITLE
services/authorization/mgmt/2020-10-01/authorization uses the apiversion "2015-07-01"

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-go#17569]
### Bug Report

- What happened?

https://github.com/Azure/azure-sdk-for-go/tree/main/services/authorization/mgmt/2020-10-01/authorization still uses the apiversion "2015-07-01".
https://github.com/Azure/azure-sdk-for-go/blob/main/services/authorization/mgmt/2020-10-01/authorization/roleassignments.go#L93

- What did you expect or want to happen?

Since the directory is "2020-10-01/", I think, the api version should be "2020-10-01".

But it seems there's no api version "2020-10-01".

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastus2' and API version '2020-10-01' for type 'roleAssignments'. The supported api-versions are '2014-04-01-preview, 2014-07-01-preview, 2014-10-01-preview, 2015-05-01-preview, 2015-06-01, 2015-07-01, 2016-07-01, 2017-05-01, 2017-09-01, 2017-10-01-preview, 2018-01-01-preview, 2018-07-01, 2018-09-01-preview, 2018-12-01-preview, 2019-04-01-preview, 2020-03-01-preview, 2020-04-01-preview, 2020-08-01-preview, 2020-10-01-preview, 2021-04-01-preview, 2022-01-01-preview'. The supported locations are ''."}]}
```

**Comment by bingosummer** [comment]
cc @Alancere @lirenhe

**Comment by lirenhe** [comment]
@bingosummer, the SDK is generated based on the readme config in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/authorization/resource-manager/readme.md#tag-package-2020-10-01

Some of the Swagger are with earlier version. So could you try to use another version or preview version of this SDK?

**Comment by bingosummer** [comment]
```
      	{
      	  "error": {
      	    "code": "UnsupportedApiVersionForRoleDefinitionHasDataActions",
      	    "message": "Assignments to roles with DataActions and NotDataActions are not supported on API version '2015-07-01'. The minimum required API version for this operations is '2018-01-01-preview'."
      	  }
      	}
```

I hit the above error when assigning a role.

> So could you try to use another version or preview version of this SDK?

Seems the azure-sdk-for-go has only two versions for authorization (2015-07-01 and 2020-01-01). Is there a way to use another version or perview version of this SDK?

I checked the azure cli debug log, and found it's using api version `2020-04-01-preview`. azure-sdk-for-python has many versions for authorization. https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/authorization/azure-mgmt-authorization/azure/mgmt/authorization

**Comment by bingosummer** [comment]
switched to template deployment with the version `2020-04-01-preview` as a workaround.

**Comment by lirenhe** [comment]
@bingosummer,  you could find the preview version here https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/authorization/mgmt/2020-04-01-preview/authorization
