### ISSUE TITLE
Add APIView approval release gate

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#17594]
We want a step that blocks a stable release whose API hasn't been approved in APIView.

**Comment by RickWinter** [comment]
Changes for GA have been reviewed.  Required for all releases post-GA

**Comment by kurtzeborn** [comment]
This is done now (per @benbp)

**Comment by benbp** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-go/pull/18468
