### ISSUE TITLE
Storage error handling and docs need to be improved

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17613]
It's unclear what error type(s) are expected to be returned from API calls.  In addition, seems like `InternalError` can be removed.

It would be ideal if storage can just use `azcore.ResponseError` instead of a custom error type as this is against the design guidelines.

**Comment by mohsha-msft** [comment]
Ack. Targeting for release `0.5.0`

**Comment by jhendrixMSFT** [comment]
Fixed in `azblob@v0.5.0`
