### ISSUE TITLE
TextAnalysis GO SDK - Support for Opinion mining

### ISSUE THREAD

**Issue by Avinodh** [Azure/azure-sdk-for-go#17634]

**Comment by Avinodh** [comment]
More generally, it would be great to have full client feature parity in the GO SDK for textanalysis as compared to the [Python](https://github.com/Azure/azure-sdk-for-python/tree/azure-ai-textanalytics_5.1.0/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics), C#, and other "first-class" language SDKs in the official docs.

**Comment by SaurabhSharma-MSFT** [comment]
@Avinodh We are looking into it and get back to you for any additional information.

**Comment by Avinodh** [comment]
Thank you for taking a look @SaurabhSharma-MSFT . Any updates on this? Wanted to check if there is a possibility for this any time soon before writing a separate wrapper over HTTP for this!

**Comment by Avinodh** [comment]
Following up on this @SaurabhSharma-MSFT

**Comment by Avinodh** [comment]
@SaurabhSharma-MSFT - I would really appreciate an update here, if it is a timeline. The request here is for feature parity in the GO textprocessing library as compared to the other languages.

**Comment by Avinodh** [comment]
Hi folks, it has been 2 months since your last update. I would really appreciate any form of timeline here.

**Comment by navba-MSFT** [comment]
@assafi Could you please look into this feature request and provide an update on this ?

**Comment by Avinodh** [comment]
Has the textanalytics SDK  for Go been moved elsewhere? I don't see this in the source tree anymore!

**Comment by Avinodh** [comment]
@navba-MSFT - Could I  please have an update on the above? This SDK is no longer available.

**Comment by Avinodh** [comment]
Hi folks, this isssue has been open for over a year. It sees like the Go SDK is no longer available either, and there was no communication about this. Could I  please get some guidance regarding this

**Comment by navba-MSFT** [comment]
@Avinodh Apologies for the late reply. This issue is pending on Service team. 

@assafi Could you please look into this once you get a chance ?

**Comment by Avinodh** [comment]
@navba-MSFT - Following up once again - has there been any dscussion/conclusion as to why the Go SDK for this was pulled without notice?
