### ISSUE TITLE
ListClusterAdminCredentials returns empty list without any error.

### ISSUE THREAD

**Issue by 0x113** [Azure/azure-sdk-for-go#17648]
### Bug Report

- import path of package: `github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2022-01-01/containerservice`
- SDK version: `master`
- output of `go version`: `go version go1.17.3 linux/amd64`

- What happened?
I wanted to list cluster admin credentials, but the `ListClusterAdminCredentials` retruns an empty list, though the API requested (made from postman) returns values. 
Code: 
```
res, err := aksClient.ListClusterAdminCredentials(ctx, "rg-name", "cluster-name", "")
```
There is no error, but the returned list is empty. 
- What did you expect or want to happen?
I expected to get the cluster config
- How can we reproduce it?
1) Create an AKS cluster
2) Setup Service Principle to use Azure API
3) Query: `https://management.azure.com/subscriptions/{{subscriptionId}}/resourcegroups/{{rg-name}}/providers/Microsoft.ContainerService/managedClusters/{{cluster-name}}/listClusterAdminCredential?&api-version=2022-01-01`. It should return a list of Kubeconfigs
4) Create an aksClient and use the above function.
- Anything we should know about your environment.
  * The subscription on which I made the API call, as well I used the sdk was onboarded with Azure Lighthouse

**Comment by navba-MSFT** [comment]
@0x113 Thanks for reaching out to us and sharing this feedback. We will look into this and get back to you once we have an update.

**Comment by 0x113** [comment]
Thank you @navba-MSFT.

**Comment by navba-MSFT** [comment]
@0x113 Could you share your complete sample code snippet here too ? So that we can debug the same code. Awaiting your reply.

**Comment by 0x113** [comment]
Maybe not a full snippet, but I think the most crucial part:
```go
	credConfig := auth.NewClientCredentialsConfig(creds.clientID, creds.clientSecret, creds.tenantID)
	authorizer, err := credConfig.Authorizer()
	if err != nil {
		return nil, err
	}

	aksClient := containerservice.NewManagedClustersClient(azSubscriptionID)
	aksClient.Authorizer = authorizer
        // List admin credentials
        res, err := aksClient.ListClusterAdminCredentials(ctx, rg.Name, aksCluster.Name, "")
	if err != nil {
		return nil, err
	}
        log.Info("Azure data", "Kubeconfigs", res.Kubeconfigs) // <- Empty list
```

I check and I use the same data in my API call. Also, I did some initial debugging, and I used `ListClusterAdminCredentialsPreparer` to see the request. From there, the URL matches the one I use in Postman to call Azure API. But, I tried to send that request with both `http.Client`, and `aksClient.Send` ( I did not use any decorators). Both methods returns `(*http.Request, error')`. In both cases, the error was nil, but when I printed out the response, I've seen such message:
```go
json: unsupported type: func() (io.ReadCloser, error)
```
Perhaps there is something wrong with unmarshalling the response to the Golang struct, but I'm not sure.

**Comment by navba-MSFT** [comment]
@0x113 I tried to reproduce the issue using the sample code you had provided but it worked for me. I was able to fetch the Kubeconfig details:

![image](https://user-images.githubusercontent.com/57353862/165035553-cb154cb3-a7b7-4174-b57f-37a67e29e41f.png)

Sharing the screenshot here. Could you confirm if this is what you were looking for ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@0x113 A quick follow-up on this to check if you had a chance to look at the above comment. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@0x113 Thanks for getting back. Sharing my sample snippet here if that helps.

```
package main

import (
	"context"
	"log"
	"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2022-01-01/containerservice"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

var (
	subscriptionID      string
	objectID            string
	clientSecret        string
	clientID            string
	TenantID            string
	location            = "MyLocation"
	resourceGroupName   = "MyRG"
	managedClustersName = "MyClusterName"
	configName          = "MyConfigName"
)

func main() {
	subscriptionID = os.Getenv("AZURE_SUBSCRIPTION_ID")
	if len(subscriptionID) == 0 {
		log.Fatal("AZURE_SUBSCRIPTION_ID is not set.")
	}

	objectID = os.Getenv("AZURE_OBJECT_ID")
	if len(objectID) == 0 {
		log.Fatal("AZURE_OBJECT_ID is not set.")
	}

	clientSecret = os.Getenv("AZURE_CLIENT_SECRET")
	if len(clientSecret) == 0 {
		log.Fatal("AZURE_CLIENT_SECRET is not set.")
	}

	clientID = "7f68d8ff-XXXXX-XXXX-XXXX-XXXXXX309ed"
	if len(clientID) == 0 {
		log.Fatal("AZURE_CLIENT_ID is not set.")
	}

	TenantID = "72XXXX-XXXXX-XXXX-XXXX-XXXXXdb47"
	if len(clientSecret) == 0 {
		log.Fatal("AZURE_TENANT_ID is not set.")
	}
	ctx := context.Background()

	credConfig := auth.NewClientCredentialsConfig(clientID, clientSecret, TenantID)
	authorizer, err := credConfig.Authorizer()
	if err != nil {
		//return nil, err
	}

	aksClient := containerservice.NewManagedClustersClient(subscriptionID)
	aksClient.Authorizer = authorizer
	// List admin credentials
	res, err := aksClient.ListClusterAdminCredentials(ctx, resourceGroupName, managedClustersName, "")
	if err != nil {
		//return nil, err
	}
	log.Println("Azure data", "Kubeconfigs", res.Kubeconfigs) 

}
```

>C:\> go version
go version go1.18.1 windows/amd64

Please test this once you get a chance. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@0x113 Please let me know if you had any updates on this. Awaiting your reply.

**Comment by 0x113** [comment]
@navba-MSFT, sorry for the late response, but I was really busy. I'll try your snippet and get back to you as soon as possible.

**Comment by navba-MSFT** [comment]
@0x113 Thanks for getting back. I shall wait for the updates from you.

**Comment by navba-MSFT** [comment]
@0x113 Any update on this ?

**Comment by 0x113** [comment]
@navba-MSFT, I'm really sorry for not getting back. I've been quite busy in past last two weeks. I'll try to use your snipper during the weekend, and I'll get back to you.

**Comment by navba-MSFT** [comment]
@0x113 Thanks for getting back. I shall wait for your reply.

**Comment by navba-MSFT** [comment]
@0x113 The action is now pending on you to test the above sample and get back to us. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
