### ISSUE TITLE
sdk/azservicebus: Set retry options in client on initalization

### ISSUE THREAD

**Issue by andrholt** [Azure/azure-sdk-for-go#17686]
### Set retryOptions in service bus client when initializing client

When initializing a new service bus client, a set of options can be provided. The retryOption property in client is never set from input parameter, it is only used to create namespace interface. When creating a new sender with client, default retryOptions is used, and not from clientOptions, and it is not possible to customize this. Is it possible to set retryOptions to client?

**Comment by richardpark-msft** [comment]
@andrholt, thank you for reporting this. Working on this now.
