### ISSUE TITLE
PostgreSQL single server db creation doesn't actually create a database

### ISSUE THREAD

**Issue by csandanov** [Azure/azure-sdk-for-go#17707]
### Bug Report

This is how I create it:

```go
import github.com/Azure/azure-sdk-for-go/profiles/latest/postgresql/mgmt/postgresql
...
client := postgresql.NewDatabasesClient(subscriptionID)
client.Authorizer = authorizer
_, err = client.CreateOrUpdate(ctx, rgName, serverName, dbName, postgresql.Database{
	DatabaseProperties: &postgresql.DatabaseProperties{
		Charset:   &charset,
		Collation: &collation,
	},
})
```

go version `go1.17.8 darwin/amd64`
sdk version: `v62.2.0`

It's PostgreSQL 11 (GP_Gen5_2), no error returned when I run the code but then I connect via `psql` to list databases I don't see my new db. I tried creating a db via azure cli and it worked fine.

**Comment by jhendrixMSFT** [comment]
The `CreateOrUpdate()` API is a long-running operation (LRO) so it doesn't complete synchronously.  For LROs, we return a `Future` type to indicate this.

https://github.com/Azure/azure-sdk-for-go/blob/main/services/postgresql/mgmt/2020-01-01/postgresql/databases.go#L42

You'll need to call `WaitForCompletionRef()` on the future which will block until the LRO has reached a terminal state (success or failure).

**Comment by csandanov** [comment]
Thank you! Turns out the issue is caused by the invalid charset/collation, but the error returned only when execute `WaitForCompletionRef`

**Comment by navba-MSFT** [comment]
Thanks for the update. If you face this issue again, feel free to reopen this issue.
