### ISSUE TITLE
Getting missing MSI headers when updating storage account encryption

### ISSUE THREAD

**Issue by petitout** [Azure/azure-sdk-for-go#1772]
Hi,
I'm trying to update a storage account encryption with the following code :

```
...
_, err := storageClient.Update(context.Background(), groupName, accountName, storage.AccountUpdateParameters{
		Kind: storage.Storage,
		AccountPropertiesUpdateParameters: &storage.AccountPropertiesUpdateParameters{
			Encryption: &storage.Encryption{
				KeySource: storage.MicrosoftKeyvault,
				KeyVaultProperties: &storage.KeyVaultProperties{
					KeyName:     &keyName,
					KeyVaultURI: &keyVaultURI,
					KeyVersion:  &keyVersion,
				},
				Services: &storage.EncryptionServices{
					Blob: &storage.EncryptionService{
						Enabled: &enabled,
					},
					File: &storage.EncryptionService{
						Enabled: &enabled,
					},
				},
			},
		},
	})
...
```

and I got the following error :

```
Update failed: storage.AccountsClient#Update: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="MissingMsiHeaders" Message="MSI headers are missing from the request."
```

However this same code is working when I manually update the encryption in the Azure console.

I tried to use azure-sdk-for-go and go-autorest both in master and also go-autorest v11

**Comment by jhendrixMSFT** [comment]
Hello!  Sorry for the delay.  How are you creating the authorizer that's associated with storageClient?

**Comment by petitout** [comment]
``
authorizer, err := auth.NewAuthorizerFromEnvironment()
``

**Comment by jhendrixMSFT** [comment]
Thanks.  Are you intending to use MSI authorization?  Per the docs for ```auth.NewAuthorizerFromEnvironment()``` it attempts to create an authorizer based on the environment variables you have set in the following order.
1. Client credentials
2. Client certificate
3. Username password
4. MSI
If your intent is not to create an MSI authorizer then either we have a bug or your missing an environment variable.  Which vars have you set?

**Comment by petitout** [comment]
Hi,
we're setting :
- AZURE_TENANT_ID
- AZURE_CLIENT_ID
- AZURE_CLIENT_SECRET
- AZURE_SUBSCRIPTION_ID

that's all.

Thanks !

**Comment by jhendrixMSFT** [comment]
Hmm I can't repro this with a simple app.  Do you have a simplified repro handy?  Also what version of go-autorest are you using?

**Comment by petitout** [comment]
Hi,
I tried again using latest go-autorest (v10.11.0) and latest azure-sdk-for-go (v17.3.0).
And still have the issue with the following code snippet :

```
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/Azure/azure-sdk-for-go/profiles/latest/storage/mgmt/storage"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

const (
	location    = "westus"
	groupName   = "RESOURCE_GROUP_NAME"  //put your resource group name
	accountName = "STORAGE_ACCOUNT_NAME" //put your storage account name
	provider    = "Microsoft.Storage"
)

var (
	storageClient storage.AccountsClient
)

func init() {
	authorizer, err := auth.NewAuthorizerFromEnvironment()
	if err != nil {
		fmt.Printf("%s: %s\n", "Error while getting authorizer from env", err)
		os.Exit(1)
	}
	subscriptionID := getEnvVarOrExit("AZURE_SUBSCRIPTION_ID")
	storageClient = storage.NewAccountsClient(subscriptionID)
	storageClient.Authorizer = authorizer
}

func main() {
	updateStorageAccount()
}

func updateStorageAccount() {
	keyName := "KEY_NAME"                            //put your key name
	keyVaultURI := "https://PUT_YOUR_KEYVAULT/"      // put your key vault
	keyVersion := "38ca204b37fe4085984c5f90a118a1e2" //put you key id
	enabled := true
	_, err := storageClient.Update(context.Background(), groupName, accountName, storage.AccountUpdateParameters{
		Kind: storage.Storage,
		AccountPropertiesUpdateParameters: &storage.AccountPropertiesUpdateParameters{
			Encryption: &storage.Encryption{
				KeySource: storage.MicrosoftKeyvault,
				KeyVaultProperties: &storage.KeyVaultProperties{
					KeyName:     &keyName,
					KeyVaultURI: &keyVaultURI,
					KeyVersion:  &keyVersion,
				},
				Services: &storage.EncryptionServices{
					Blob: &storage.EncryptionService{
						Enabled: &enabled,
					},
					File: &storage.EncryptionService{
						Enabled: &enabled,
					},
				},
			},
		},
	})
	if err != nil {
		fmt.Printf("%s: %s\n", "Error while updating storage account", err)
		os.Exit(1)
	}
}

// getEnvVarOrExit returns the value of specified environment variable or terminates if it's not defined.
func getEnvVarOrExit(varName string) string {
	value := os.Getenv(varName)
	if value == "" {
		fmt.Printf("Missing environment variable %s\n", varName)
		os.Exit(1)
	}
	return value
}

```

**Comment by jhendrixMSFT** [comment]
Thanks a lot I can repro this issue.  I suspect this has something to do with the ```Identity``` field in ```AccountUpdateParameters``` but the documentation doesn't specify how it should be set, nor is the response error documented.  :(
@blueww can you please help with this issue or route to somebody that can?  To summarize, when calling the update API we receive the following response.
```
Error while updating storage account: storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="MissingMsiHeaders" Message="Managed Service Identity (MSI) is not set for this account."
```
I don't see ```MissingMsiHeaders``` documented [here](https://docs.microsoft.com/en-us/rest/api/storagerp/srp_error_codes_update_storage_account).

**Comment by blueww** [comment]
@petitout 
Have you follow all the steps in https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption-customer-managed-keys before enabled Keyvault in Storage Account?

I have tried to set keyvault with the above doc, and it works.

Please note, if your account don't have identity, you need to update it by set the identity as following, and you need to give the account identity permission for the Keyvault:

                       ` updateParameters.Identity = new Identity();`

**Comment by jhendrixMSFT** [comment]
@blueww can we get the docs updated with the ```MissingMsiHeaders``` error code?

**Comment by jhendrixMSFT** [comment]
@petitout have you tried the steps recommended by @blueww and if so did it resolve your issue?

**Comment by petitout** [comment]
Hi @jhendrixMSFT and @blueww,
sorry for the delay.

I tried this : I went in the Azure web console and went to encryption configuration of the keyvault. I selected "Use my own key" , selected a key and saved (equivalent to step 3 in the doc @blueww pointed to). This worked fine.
Then I unselected "Use my own key" to use Microsoft.storage encryption and saved.
After that I was able to update the encryption type (to use a keyvault key) using my code snippet without any problem.

@blueww I couldn't identify any REST API that could be used as a pre-requesite of my code snippet. Are they any ?

**Comment by blueww** [comment]
@petitout 

Good to know you find a way to make the feature work. 

I am not the feature owner, so I might not be the best person to answer the feature questions. 
(Our team owns storage SDK, but you question is more for feature itself instead of storage SDK.)

If you would like to know the rest API for the pre-requisite step, or any other questions for the feature, you might can open a question in https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption-customer-managed-keys 
Actually, What I get is how to do the pre steps from Powershell from the doc. So you might can also consider using Powershell to do the pre-requisite.

**Comment by jhendrixMSFT** [comment]
Sounds like this has been resolved so closing.  Please reopen as required.
