### ISSUE TITLE
ListForScope on RoleManagementPolicies Client to support filter

### ISSUE THREAD

**Issue by StickNitro** [Azure/azure-sdk-for-go#17728]
### Feature Request

Currently the RoleManagementPolicies client does not support the ability to specify a `$filter` with the request. List for Scope will return ALL role management policies which could be hundreds of records when you are potentially only interested in a specific role management policy.

Microsoft sample indicates that this API can accept a `$filter` query string parameter where you can query for a role management policy fir a given `roleDefinitionId`, for example, the following will return any role management policies for the specified roleDefinitionId:

`/roleManagementPolicies?api-version=2020-10-01-preview&$filter=roleDefinitionId eq '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'`

The Microsoft documentation is [here](https://docs.microsoft.com/en-us/rest/api/authorization/privileged-role-policy-rest-sample)

In the above scenario this would return a single role management policy which could then be updated as part of a terraform resource rather than currently having to retrieve ALL the role management policies and filter locally for the one you want.

Could we add an optional `filter` or `roleDefinitionId` parameter to the List for Scope client function (perhaps default to `nil`) and include in the request if a filter was provided?

**Comment by tadelesh** [comment]
@StickNitro is this issue still exist?
