### ISSUE TITLE
Receive scheduled messages

### ISSUE THREAD

**Issue by elahmo** [Azure/azure-sdk-for-go#17727]
### Feature Request

If possible, it would be good to be able to receive scheduled messages.

**Comment by SaurabhSharma-MSFT** [comment]
@elahmo We are looking into it and get back to you for any additional information.

**Comment by richardpark-msft** [comment]
CC: @jsquire, who would also be interested in customer feature requests.

**Comment by richardpark-msft** [comment]
@elahmo, can you give us an idea of what your scenario is for this?
