### ISSUE TITLE
Service Fabric Cluster - ClientCertificateCommonName CertificateIssuerThumbprint is returning the wrong case

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#17744]
### Bug Report

- `/servicefabric/mgmt/2021-06-01/servicefabric`
- `63.1.0`
- `go version go1.17.6 darwin/amd64`

When retrieving a service fabric cluster that is using ClientCertificateCommonName, the [CertificateIssuerThumbprint](https://github.com/Azure/azure-sdk-for-go/blob/main/services/servicefabric/mgmt/2021-06-01/servicefabric/models.go#L1140) is being returned as lower case. For additional context, every other Thumbprint with this resource is being returned in the correct case. 

To recreate this, create a Service Fabric Cluster using ClientCertificateCommonName and pass CertificateIssuerThumbprint as upper case.

**Comment by tadelesh** [comment]
@mbfrahry Thanks for your feedback. It seems a service problem. I'll involve service team to have a look.

**Comment by navba-MSFT** [comment]
@mbfrahry Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please share the sample code snippet you are using ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mbfrahry Could you please let us know if you had a chance to look at my above comment ? Please share your sample code snippet once you get a chance so that we can debug it further.

**Comment by mbfrahry** [comment]
Sure. I'm calling `CreateOrUpdate` with 

```
{
	"location": "eastus2",
	"properties": {
		"addOnFeatures": [],
		"certificate": {
			"thumbprint": "3341DB6CF2AF72C611DF3BE3721A653AF1D43ECD50F584F828793DBE9103C3EE",
			"thumbprintSecondary": "",
			"x509StoreName": "My"
		},
		"clientCertificateCommonNames": [{
			"isAdmin": true,
			"certificateCommonName": "firstcertcommonname",
			"certificateIssuerThumbprint": "3341DB6CF2AF72C611DF3BE3721A653AF1D43ECD50F584F828793DBE9103C3EE"
		}, {
			"isAdmin": false,
			"certificateCommonName": "secondcertcommonname",
			"certificateIssuerThumbprint": ""
		}],
		"clientCertificateThumbprints": [{
			"isAdmin": true,
			"certificateThumbprint": "3341DB6CF2AF72C611DF3BE3721A653AF1D43ECD50F584F828793DBE9103C3EE"
		}],
		"fabricSettings": [{
			"name": "Security",
			"parameters": [{
				"name": "ClusterProtectionLevel",
				"value": "EncryptAndSign"
			}]
		}],
		"managementEndpoint": "https://example:80",
		"nodeTypes": [{
			"capacities": {},
			"clientConnectionEndpointPort": 2020,
			"durabilityLevel": "Bronze",
			"httpGatewayEndpointPort": 80,
			"isPrimary": true,
			"isStateless": false,
			"multipleAvailabilityZones": false,
			"name": "first",
			"placementProperties": {},
			"vmInstanceCount": 3
		}],
		"reliabilityLevel": "Bronze",
		"upgradeMode": "Automatic",
		"vmImage": "Windows"
	},
	"tags": {}
}
```

The issue is that I'm sending 

```
"clientCertificateCommonNames": [{
			"isAdmin": true,
			"certificateCommonName": "firstcertcommonname",
			"certificateIssuerThumbprint": "3341DB6CF2AF72C611DF3BE3721A653AF1D43ECD50F584F828793DBE9103C3EE"
},
```

where `certificateIssuerThumbprint` is uppercased. But I'm receiving `3341db6cf2af72c611df3be3721a653af1d43ecd50f584f828793dbe9103c3ee` which is lower cased. 

The other thumbprints are returned with the correct casing.

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for clarifying the ask. I am adding the Service Team here to take a look into this ask.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
