### ISSUE TITLE
Provide abstraction for SDK authors to create custom polling trackers

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17743]
The current `runtime.Poller[T]` uses internal "polling trackers" to determine the behavior (Azure-AsyncOperation, Location, etc).  Some services might require custom polling trackers, e.g. the custom model trainer API for Form Recognizer uses a custom implementation (see python example [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_polling.py)).  While there's no need for this at present, it will become a requirement if/when we produce such SDKs.

I believe this can be done in a non-breaking way by adding a `PollingTracker` field (we can refine the name) to the `NewPollerOptions` type that, when specified, will be used in lieu of our polling tracker detection logic.

**Comment by jhendrixMSFT** [comment]
This prevents us from using the generic poller in `azcore` for things like key vault.

**Comment by RickWinter** [comment]
@jhendrixMSFT to post the PR

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming `azcore@v0.24.0`
