### ISSUE TITLE
NewListAllPager is failing to unmarshall type *armreservations.ListResult and return reservations

### ISSUE THREAD

**Issue by JulesCohonner** [Azure/azure-sdk-for-go#17741]
### Bug Report

Module: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations@0.4.0"
SDK Version: v63.4.0+incompatible
Commit: https://github.com/Azure/azure-sdk-for-go/commit/4dbc884ed47f19c14c6beb157aa2efca9cd66c8d
Go Version: go1.18.1 darwin/amd64

- What happened?

Using the example from https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations@v0.4.0?utm_source=gopls#ReservationClient.NewListAllPager the execution result into an error:

```
2022/04/26 11:36:45 failed to advance page: unmarshalling type *armreservations.ListResult: parsing time "\"2021-01-26T10:12:03.1777782Z\"" as "\"2006-01-02\"": cannot parse "T10:12:03.1777782Z\"" as "\""
exit status 1
````

- What did you expect or want to happen?

I expected to be able to list reservations 

- How can we reproduce it?

Using the example should reproduce the error

```
package main

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations"
)

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
		return
	}
	ctx := context.Background()
	client, err := armreservations.NewReservationClient(cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
		return
	}
	pager := client.NewListAllPager(&armreservations.ReservationClientListAllOptions{})
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
			return
		}
		for _, v := range nextResult.Value {
			// TODO: use page item
			_ = v
		}
	}
}
```

Thanks!

**Comment by jhendrixMSFT** [comment]
Looks like something in the [`ReservationProperties`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/Microsoft.Capacity/stable/2022-03-01/reservations.json#L1951) that's specified as `date` is actually a `date-time`.

**Comment by SaurabhSharma-MSFT** [comment]
@JulesCohonner Redirecting this to services team to look into it.

**Comment by JulesCohonner** [comment]
> @JulesCohonner Redirecting this to services team to look into it.

Great thanks for taking care of it

**Comment by jhendrixMSFT** [comment]
@gaoyp830 @msft-adrianma can either of you help with this?

**Comment by gaoyp830** [comment]
Hi @[JulesCohonner](https://github.com/JulesCohonner)
There is a bug that the Go sdk tries to convert datetime into date format. To unblock, can you please make the following change in Go sdk code:
In [this ](https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/reservations/armreservations/v0.4.0/sdk/resourcemanager/reservations/armreservations/zz_generated_models_serde.go#L323)line, change it to `err = unpopulateTimeRFC3339(val, "PurchaseDate", &p.PurchaseDate)`

**Comment by jhendrixMSFT** [comment]
@gaoyp830 this is _not_ a bug in the Go SDK.  Per [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/Microsoft.Capacity/stable/2022-03-01/reservations.json#L2034-L2038), `PurchaseDate` is incorrectly defined as having format `date`.  Given what's coming over the wire, the format should be `date-time`.  Note that such a change is breaking, so you'll need to follow up with the arch board on the best way to proceed.

**Comment by gaoyp830** [comment]
> @gaoyp830 this is _not_ a bug in the Go SDK. Per [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/Microsoft.Capacity/stable/2022-03-01/reservations.json#L2034-L2038), `PurchaseDate` is incorrectly defined as having format `date`. Given what's coming over the wire, the format should be `date-time`. Note that such a change is breaking, so you'll need to follow up with the arch board on the best way to proceed.

I am _not_ saying the bug is from Go SDK side, what I meant is there is a bug that convert datetime into date format. The fix should be on Reservations side which is gonna take a while because of the ARM review etc. At the meantime customer can use the workaround I have suggested above.

**Comment by gaoyp830** [comment]
@JulesCohonner service team has made a fix to return the data format from `date-time` to `date` to unblock other go customers. Please revert this workaround I suggested: 

> In [this ](https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/reservations/armreservations/v0.4.0/sdk/resourcemanager/reservations/armreservations/zz_generated_models_serde.go#L323)line, change it to `err = unpopulateTimeRFC3339(val, "PurchaseDate", &p.Purcha`
