### ISSUE TITLE
Cosmos DB - TransactionalBatch support

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-go#17771]
Add support for https://docs.microsoft.com/en-us/azure/cosmos-db/sql/transactional-batch

## Proposed API

The exposed new types are:

* TransactionalBatch - Represents the batch itself
* TransactionalBatchOptions - Options for execution of the batch
* TransactionalBatchItemOptions - Options at the individual operation level
* TransactionalBatchResponse - The batch response
* TransactionalBatchResponseOperationResult - The individual operation result within the batch response

### Creating a Transactional Batch

```
func (c *ContainerClient) NewTransactionalBatch(partitionKey PartitionKey) TransactionalBatch
```

On the Container, we can create the TransactionalBatch like so:

```
partitionKey := NewPartitionKeyString("myPartitionKeyValue")
batch := container.NewTransactionalBatch(partitionKey)
```

The batch is scoped to a Partition Key Value.

### Populating operations

A batch contains a list of operations to be executed as a single unit:

```
// CreateItem adds a create operation to the batch.
func (b *TransactionalBatch) CreateItem(item []byte, o *TransactionalBatchItemOptions)

// DeleteItem adds a delete operation to the batch.
func (b *TransactionalBatch) DeleteItem(itemId string, o *TransactionalBatchItemOptions)

// ReplaceItem adds a replace operation to the batch.
func (b *TransactionalBatch) ReplaceItem(itemId string, item []byte, o *TransactionalBatchItemOptions)

// UpsertItem adds an upsert operation to the batch.
func (b *TransactionalBatch) UpsertItem(item []byte, o *TransactionalBatchItemOptions)

// ReadItem adds a read operation to the batch.
func (b *TransactionalBatch) ReadItem(itemId string, o *TransactionalBatchItemOptions) 
```

Each operation that can be added contains some potential options:

```
type TransactionalBatchItemOptions struct {
	// IfMatchEtag is used to ensure optimistic concurrency control.
	// https://docs.microsoft.com/azure/cosmos-db/sql/database-transactions-optimistic-concurrency#optimistic-concurrency-control
	IfMatchEtag *azcore.ETag
}
```

### Executing a batch

After a batch is created, operations need to be added, and then the ExecuteTransactionalBatch method is used:

```
func (c *ContainerClient) ExecuteTransactionalBatch(ctx context.Context, b TransactionalBatch, o *TransactionalBatchOptions) (TransactionalBatchResponse, error)
```

Example:

```
partitionKey := NewPartitionKeyString("myPartitionKeyValue")
batch := container.NewTransactionalBatch(partitionKey)
batch.CreateItem(bodyOfAnItemToCreate, nil)
batch.ReadItem("idOfAnItemToRead", nil)
//... other operations

batchResponse, err := container.ExecuteTransactionalBatch(context, batch, nil)
```

The ExecuteTransactionalBatch method contains options for the execution:

```
// TransactionalBatchOptions includes options for transactional batch operations.
type TransactionalBatchOptions struct {
	SessionToken string
	ConsistencyLevel *ConsistencyLevel
	EnableContentResponseOnWrite bool
}
```

### Handling batch response

The batch response contains the raw HTTP response plus Request Charge, SessionToken, ActivityId and 2 important properties:

```
// QueryItemsResponse contains response from the query operation.
type TransactionalBatchResponse struct {
	Response
	// SessionToken contains the value from the session token header to be used on session consistency.
	SessionToken string
	// OperationResults contains the individual batch operation results.
	// The order of the results is the same as the order of the operations in the batch.
	OperationResults []TransactionalBatchResponseOperationResult
	// IsSuccess indicates if the transaction was successfully committed.
	// If false, one of the operations in the batch failed.
	// Inspect the OperationResults, any operation with status code http.StatusFailedDependency is a dependency failure.
	// The cause of the batch failure is the first operation with status code different from http.StatusFailedDependency.
	IsSuccess bool
}
```

`OperationResults` contain all the individual operation results, each operation in a batch has its own response.

Each operation result exposes:

```
// TransactionalBatchResponseOperationResult represents the result of a single operation in a batch.
type TransactionalBatchResponseOperationResult struct {
	// StatusCode contains the status code of the operation.
	StatusCode int32
	// RequestCharge contains the request charge for the operation.
	RequestCharge float32
	// ResourceBody contains the body response of the operation.
	// This property is available depending on the EnableContentResponseOnWrite option.
	ResourceBody []byte
	// ETag contains the ETag of the operation.
	ETag azcore.ETag
}
```

`IsSuccess` is used to determine if the batch committed all operations or if it had to be rolled back due to one operation failing.

After receiving the response, we need to inspect if the batch committed, and if not, which operation was the source of the failure:

```
if batchResponse.IsSuccess {
		// Transaction succeeded
		// We can inspect the individual operation results 
		for index, operation := range batchResponse.OperationResults {
			fmt.Printf("Operation %v completed with status code %v consumed %v RU", index, operation.StatusCode, operation.RequestCharge)
			if index == 1 {
				// Read operation would have body available
				var itemResponseBody map[string]string
				err = json.Unmarshal(operation.ResourceBody, &itemResponseBody)
				if err != nil {
					panic(err)
				}
			}
		}
	} else {
		// Transaction failed, look for the offending operation
		for index, operation := range batchResponse.OperationResults {
			if operation.StatusCode != http.StatusFailedDependency {
				fmt.Printf("Transaction failed due to operation %v which failed with status code %v", index, operation.StatusCode)
			}
		}
	}
```

**Comment by JeffreyRichter** [comment]
This looks pretty good.
Have you considered a slight change where the customer code does this:

batch := NewTransactionalBatch(partitionKey)
// .. add items to batch here
batchResponse, err = container.ExecuteBatch(ctx, batch, nil)

Here, I create the batch first (not associated with any container) and then I execute the batch against the container. I prefer this (unless there is a good reason not to do it this way) because all other I/O operations are against the container and this maintains that consistency. The container is the "client", not the "batch" - your pattern effectively turned a batch into a client. Clients have endpoints, credentials & http pipeline policy options; batches should not have these things but your version effectively does make the batch have these things.

**Comment by ealsur** [comment]
@JeffreyRichter Great point, I went ahead and adjusted the design, this makes it better because it removes any need for the TransactionalBatch struct to know how to send requests through the pipeline as you described and just limits to holding the operations.
