### ISSUE TITLE
New API version: 2022-02-03 for desktopvirtualization

### ISSUE THREAD

**Issue by alexwilcox9** [Azure/azure-sdk-for-go#17783]
### Feature Request

As advised in https://github.com/Azure/azure-sdk-for-go/pull/17669 I'd like to use the latest API version for desktopvirtualization.
Could you please reach out to the service team to look into this?

Many thanks,
Alex

**Comment by tombuildsstuff** [comment]
Related, the upstream Swagger PR has been merged for this: https://github.com/Azure/azure-rest-api-specs/pull/18748

**Comment by navba-MSFT** [comment]
PR https://github.com/Azure/azure-sdk-for-go/pull/17669 was created for this feature request and then the plan was to involve the Service Team to plan for the release (see [this](https://github.com/Azure/azure-sdk-for-go/pull/17669#issuecomment-1107700497) comment). So I am removing the CXP attention label from this and adding the Service Attention label.

**Comment by lirenhe** [comment]
@ArcturusZhang, could you help to follow up on this?  We will follow our own process for the SDK release so  PR https://github.com/Azure/azure-sdk-for-go/pull/17669 could not be merged.

**Comment by Alancere** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html)(see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)).Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md).If you could still repo this problem, please submit a support ticket in Azure directly.
