### ISSUE TITLE
Add entityId to secrets, keys, and certificates

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-go#17822]

**Comment by heaths** [comment]
This comes direct from swagger. Generally, we open simple tracking items like this but it's often just regenerating. That said, whether `entityId` is going to remain in the 7.4-preview.1 swagger is up in the air. /cc @vcolin7 who is driving the KV releases.

**Comment by vcolin7** [comment]
This feature has been removed from future plans for Key Vault.
