### ISSUE TITLE
AZBlobStore BlobBlatch Operations in Golang SDK 

### ISSUE THREAD

**Issue by PV99** [Azure/azure-sdk-for-go#17827]
### Feature Request

Pulling up this feature request from the Old SDK https://github.com/Azure/azure-storage-blob-go/issues/201: 

Though the blob service API docs [indicate](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch) that a Blob Batch aggregation operation would allow us to delete multiple blobs with a single request, it appears that this isn’t implemented in the Go client. Such a feature would be deeply appreciated.

If there is no nearby ETA for this feature, would you recommend hitting the HTTP API for the time being?

**Comment by navba-MSFT** [comment]
@PV99 Apologies for the late reply. Thanks for reaching out to us. I am looking into this. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@PV99 Could you please refer the [BatchTransferOptions](https://github.com/Azure/azure-sdk-for-go/blob/9173b98cee6b07d29c9544a795d12be619f9c70f/sdk/storage/azblob/zm_highlevel_util.go#L195) Available in the [AzBlob](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob#azure-blob-storage-sdk-for-go) Storage SDK for go ?

BatchTransferOptions identifies options used by [DoBatchTransfer](https://github.com/Azure/azure-sdk-for-go/blob/9173b98cee6b07d29c9544a795d12be619f9c70f/sdk/storage/azblob/highlevel.go#L261). DoBatchTransfer helps to execute operations in a batch manner. This can be used by users to customize batch works (for other scenarios that the SDK does not provide). Hope this helps.

**Comment by PV99** [comment]
Hey @navba-MSFT Thanks for the help! The issue with DoBatchTransfer is that it uses go routines to parallelize running operations in batch. This causes multiple http requests to be sent, whereas we would prefer to delete multiple blobs with a single http request like in the [blob batch api. ](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch). 

Are there plans for supporting the blob-batch api in the "AzBlob Storage SDK for go"  anytime soon?

**Comment by navba-MSFT** [comment]
@PV99 Thanks for getting back. I have got a reply from the product owners that they have plans on supporting the batch delete/set tier at some point, but it hasn’t been prioritized. Unfortunately there is no ETA that can be shared at this moment. Once it is released the details will be shared [here](https://github.com/Azure/azure-sdk-for-go/releases). Hope this answers.
