### ISSUE TITLE
[azservicebus] GetQueueRuntimeProperties() panic due to response not containing "CountDetails" node

### ISSUE THREAD

**Issue by frankwangnj** [Azure/azure-sdk-for-go#17868]
I'm using azservicebus@v0.3.5, and ran into the panic issue. It might still exist in the latest version. Please help check it.

Sometimes, when I call GetQueueRuntimeProperties(), the program panic with following stack information.

```
panic serving runtime error: invalid memory address or nil pointer dereference:
goroutine 10 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
receiver/qmonitor.(*QueueMonitor).queryOneQueue.func1()
/Users/frank/ems/cas-inline-receiver/src/qmonitor/qmonitor.go:36 +0x39
panic({0x71ad20, 0x9ff7a0})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/admin.newQueueRuntimeProperties(0x0)
/Users/frank/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/messaging/azservicebus@v0.3.5/admin/admin_client_queue.go:540 +0x46
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/admin.(*Client).GetQueueRuntimeProperties(0xc0003d4fd0, {0x7eeff0, 0xc000132000}, {0xc00026cadc, 0x2}, 0xc001fc0000)
/Users/frank/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/messaging/azservicebus@v0.3.5/admin/admin_client_queue.go:234 +0xe5
receiver/azureutil.(*SbqAdminClient).GetQueueRuntimeProperties(...)
```

I get the response from networking, and it does not contain "CountDetails" node in XML, which cause the panic in function newQueueRuntimeProperties().

```
<?xml version="1.0"?>
<entry xmlns="http://www.w3.org/2005/Atom">
  <id>https://sharon-rec-queue.servicebus.windows.net/q1?api-version=2017-04</id>
  <title type="text">q1</title>
  <published>2022-05-05T08:01:48Z</published>
  <updated>2022-05-05T08:01:48Z</updated>
  <author>
    <name>sharon-rec-queue</name>
  </author>
  <link rel="self" href="https://sharon-rec-queue.servicebus.windows.net/q1?api-version=2017-04"/>
  <content type="application/xml">
    <QueueDescription xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
      <LockDuration>PT1M</LockDuration>
      <MaxSizeInMegabytes>5120</MaxSizeInMegabytes>
      <RequiresDuplicateDetection>false</RequiresDuplicateDetection>
      <RequiresSession>false</RequiresSession>
      <DefaultMessageTimeToLive>P10675199DT2H48M5.4775807S</DefaultMessageTimeToLive>
      <DeadLetteringOnMessageExpiration>false</DeadLetteringOnMessageExpiration>
      <DuplicateDetectionHistoryTimeWindow>PT10M</DuplicateDetectionHistoryTimeWindow>
      <MaxDeliveryCount>10</MaxDeliveryCount>
      <EnableBatchedOperations>true</EnableBatchedOperations>
      <SizeInBytes>0</SizeInBytes>
      <MessageCount>0</MessageCount>
      <IsAnonymousAccessible>false</IsAnonymousAccessible>
      <AuthorizationRules/>
      <Status>Active</Status>
      <SupportOrdering>true</SupportOrdering>
      <AutoDeleteOnIdle>P10675199DT2H48M5.4775807S</AutoDeleteOnIdle>
      <EnablePartitioning>false</EnablePartitioning>
      <EntityAvailabilityStatus>Available</EntityAvailabilityStatus>
      <EnableExpress>false</EnableExpress>
      <MaxMessageSizeInKilobytes>256</MaxMessageSizeInKilobytes>
    </QueueDescription>
  </content>
</entry>
```

**Comment by richardpark-msft** [comment]
Hi @frankwangnj, 

Can you provide me with a time stamp and namespace/queue name where this occurred? This'll help us figure out if there was anything particular happening in Service Bus at the time.

If you're not comfortable putting that information here you can email it to me: ripark at microsoft.com

**Comment by richardpark-msft** [comment]
> Hi @frankwangnj,
> 
> Can you provide me with a time stamp and namespace/queue name where this occurred? This'll help us figure out if there was anything particular happening in Service Bus at the time.
> 
> If you're not comfortable putting that information here you can email it to me: ripark at microsoft.com

Hi @frankwangnj , if you pull the latest build (`go get github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus@HEAD` we've added some code to at least handle the failure gracefully. The CountDetails _should_ be there and I've not been able to replicate this bug locally so it might have been something specific to an instance of time. If you get a chance to send me some more details we can take a further look.

**Comment by richardpark-msft** [comment]
Hi @frankwangnj, 

I talked with the service team about this. There are apparently some windows of time where the queue's statistics are not available.  This is temporary.

I've added a fix so the code will no longer panic in this situation, and will just return an error instead. You can pick that fix up in this build, which just released:

https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fmessaging%2Fazservicebus%2Fv1.0.1

Closing, but if you want to ask more questions please feel free to reopen.
