### ISSUE TITLE
ReceivedMessage exports fields and a method which breaks mocking

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17877]
Return types that mix exported fields and methods are not mockable and require a constructor.  We should avoid this.

**Comment by jhendrixMSFT** [comment]
We should audit all return types to ensure this invariant.

**Comment by richardpark-msft** [comment]
For further context:

ReceivedMessage is basically a wrapper over the top of an actual amqp.Message (from go-amqp). It matches the ReceivedMessage that exists in other languages, where the goal was just to have a simple message format that could take a []byte payload.

```go
type ReceivedMessage struct {
   MessageID string
   To *string
   // many others...
}

func (rm *ReceivedMessage) Body() ([]byte, error) {}
```

This simplified message type does not map 1:1 with AMQP concepts - there are some payload types it cannot represent. To avoid having a potential silent failure the .Body field was turned into a .Body _function_, which allows us to return an error if we're in this state.

However, doing that makes it harder to write some mocks for customers, etc... So we'd like to eliminate this if possible.

**Comment by richardpark-msft** [comment]
Just to loop back on this - we're going to change the ReceivedMessage.Body() function back to a field. There were a small set of circumstances where it wouldn't work and the error that came back wasn't giving you much in any case.

In the cases where we can't convert it .Body will just be nil.
