### ISSUE TITLE
Resolve example problems for core RPs

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#17882]
1. compute, network, storage, resource, keyvault
2. resolve mock test failure from example problems

**Comment by Alancere** [comment]
network: https://github.com/Azure/azure-rest-api-specs/pull/18970
compute: https://github.com/Azure/azure-rest-api-specs/pull/18964
keyvault: https://github.com/Azure/azure-rest-api-specs/pull/18962
resources:https://github.com/Azure/azure-rest-api-specs/pull/18961
storage: https://github.com/Azure/azure-rest-api-specs/pull/18960
