### ISSUE TITLE
Possibility to disable SSL checks for azcosmos Client

### ISSUE THREAD

**Issue by emardo** [Azure/azure-sdk-for-go#17885]
### Feature Request

I am developing an Azure Function which needs to communicate with an Azure Cosmos DB, and for the initial development steps I need to set it all up on my local machine. Since I am using a mac and cannot run the Cosmos DB Emulator directly on it, I use Docker. The container is running fine, I can create a sample database etc. I tested the database connection first with a sample .NET app. For accessing the database container which has a self-signed certificate, I had to initialize the CosmosClient with options that disable the SSL checks.

Now, I have not been able to achieve the same with the Azure SDK for Go. When trying to create a database client, I receive an error like this:

> _**x509: “localhost” certificate is not standards compliant**_

which makes sense, as the certificate exported from the emulator is self-signed and not verified.

I would like to have the option to disable the certificate verification.

Some MongoDb adapters have the possibility to add a TLS configuration to skip certificate verification too, like this for example:
> _**client, err := mongo.Connect(ctx, options.Client().ApplyURI(connStr).SetDirect(true).SetTLSConfig(&tls.Config{InsecureSkipVerify: true}))**_

but the clients created with these adapters cannot read the data from the SQL API database in the Cosmos DB Emulator.

So my request would be to add a similar configuration option to the azcosmos Client, because configuring the default transport to skip certificate verification does not affect the SDK requests towards the Cosmos DB Emulator. I have searched for solutions for a few days now, but to no avail.

If there is something I have missed or there is any other way to connect the Go function to a Cosmos DB Emulator, I would be happy to know.

Thanks in advance!

**Comment by ealsur** [comment]
`azcosmos` uses the default Go HttpClient that exists in the `azcore` / Azure SDK pipeline, so you should be able to disable any SSL verification on the httpclient itself: https://stackoverflow.com/a/12122718/5641598

```
http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
```

**Comment by ealsur** [comment]
Unless there is a way to customize the Transport of the httpClient in the Pipeline @jhendrixMSFT ?

**Comment by jhendrixMSFT** [comment]
Yes.  In the `ClientOptions` you can set your own HTTP transport in the [`Transport`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/policy/policy.go#L43) field.  Just create an `*http.Client` configured as required and assign it here.

**Comment by emardo** [comment]
@jhendrixMSFT & @ealsur thank you for your comments

> I am assuming importing the certificate as the documentation says did not work? https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#import-certificate

This directed me in the right direction, the issue being the certificate not having been exported in pfx format. After importing the certificate into Keychain Access in the correct format and setting trust to Always, the connection to database succeeded without disabling SSL verification.

I will close the issue. Thank you guys!
