### ISSUE TITLE
azidentity.NewDefaultAzureCredential does not work as documented

### ISSUE THREAD

**Issue by wkalt** [Azure/azure-sdk-for-go#17889]
I followed a link on this page:
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-go?toc=%2Fazure%2Fdeveloer%2Fgo%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fbreadcrumb%2Ftoc.json

to this sample application:
https://github.com/Azure-Samples/storage-blobs-go-quickstart

I have a blob container I can write to with the `az` CLI tool, so by my reading NewDefaultAzureCredential should pick up my CLI credentials and allow the quickstart to work as documented. However, the quickstart produces a permission error when run:

```
[~/repos/storage-blobs-go-quickstart] (master) $ go run storage-quickstart.go 
Azure Blob storage quick start sample
Creating a container named quickstart-2709509216170575517
Creating a dummy file to test the upload and download
2022/05/11 13:00:52 Failure to upload to blob: ===== RESPONSE ERROR (ErrorCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:41dc8e43-d01e-0052-1871-6574b5000000
Time:2022-05-11T20:00:52.8716266Z, Details: (none)
exit status 1
```

This same issue is reported on the quickstart repo itself, here: https://github.com/Azure-Samples/storage-blobs-go-quickstart/issues/7

However the proposed fix there and on the linked SO post is just not to use default credentials.

Is this supposed to work without setting environment variables for keys (or am I possibly missing some detail)? In google cloud for instance the application default credential chain includes a lookup for CLI credentials, which allows devs to work with their gcloud credentials instead of separately managing keys for the storage lib.

**Comment by chlowell** [comment]
> Is this supposed to work without setting environment variables for keys (or am I possibly missing some detail)? In google cloud for instance the application default credential chain includes a lookup for CLI credentials, which allows devs to work with their gcloud credentials instead of separately managing keys for the storage lib.

That's how `DefaultAzureCredential` works as well. If you haven't set [the relevant environment variables](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#environment-variables) and are running on your local machine (i.e. managed identity isn't available), it will request an access token from the Azure CLI. It appears that's succeeding for you, because you would see a different error if `DefaultAzureCredential` couldn't acquire a token.

The error you are seeing typically means the principal (whoever's logged in to the Azure CLI) hasn't been assigned a role with permission to perform the operation. Azure RBAC roles are pretty granular, for example they separate creating a storage account from writing blobs in that account. So, it's not unusual to be forbidden to write data to a storage account you just created 😄

Looking at the sample, I think the Storage Blob Data Contributor role would do. The Azure Storage documentation has an article on [assigning data access roles](https://docs.microsoft.com/azure/storage/blobs/assign-azure-role-data-access?tabs=portal).

cc @Duffney: the sample readme should walk through assigning the necessary RBAC role instead of directing readers to an account access key, which isn't used in AAD token authentication

**Comment by wkalt** [comment]
@chlowell thanks for confirming it should work as expected.

I may just be being thick here, but just to confirm:
I am able to access my container using the az CLI using `az storage blob upload` and `az storage blob download`. I can put objects into it, and read those objects out, and list contents with the CLI. However when I do the same things through the library (using CLI credentials as I understand) I get permission errors. That's expected?

I need to test the data access role you linked, but since I just have "contributor" on this subscription rather than "owner", I'm currently blocked on a permission change.

**Comment by chlowell** [comment]
No, that's unexpected, provided you're doing all this in the same environment and didn't log in a different identity in between. Contributors and Owners of a subscription don't inherit a write role for the subscripton's storage accounts--subscription and storage roles are separate--but if `az storage blob upload` works, an `azblobs` client authenticating with `azidentity.AzureCLICredential` should be able to upload as well because the credential simply execs `az account get-access-token`.

It may help to turn on logging so you can verify `DefaultAzureCredential` is doing what we expect:

```go
import (
	"fmt"

	azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

azlog.SetListener(func(event azlog.Event, s string) {
	fmt.Println("azidentity: ", s)
})
azlog.SetEvents(azidentity.EventAuthentication)
```

Output should look like this:
```
azidentity:  Managed Identity Credential will use IMDS managed identity
azidentity:  NewDefaultAzureCredential failed to initialize some credentials:
	EnvironmentCredential: missing environment variable AZURE_TENANT_ID
azidentity:  *azidentity.AzureCLICredential.GetToken() acquired a token for scope https://storage.azure.com/.default

azidentity:  DefaultAzureCredential authenticated with AzureCLICredential
```

**Comment by wkalt** [comment]
I have modified the quickstart script to be a bit more concise, and adapted it to my specific storage account and container. Here's what I'm running:

```
package main

import (
        "context"
        "fmt"
        "log"
        "math/rand"
        "strconv"
        "time"

        azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
        "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
        "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
)

func randomString() string {
        r := rand.New(rand.NewSource(time.Now().UnixNano()))
        return strconv.Itoa(r.Int())
}

func main() {
        azlog.SetListener(func(event azlog.Event, s string) {
                fmt.Println("azidentity: ", s)
        })
        azlog.SetEvents(azidentity.EventAuthentication)

        ctx := context.Background()
        containerName := "lake"
        storageAccountName := "wyattlake"
        blobName := "quickstartblob" + "-" + randomString()
        blobURL := fmt.Sprintf("https://%s.blob.core.windows.net/%s/%s", storageAccountName, containerName, blobName)

        // Create a default request pipeline using your storage account name and account key.
        credential, err := azidentity.NewDefaultAzureCredential(nil)
        if err != nil {
                log.Fatal("Invalid credentials with error: " + err.Error())
        }

        data := []byte("\nhello world this is a blob\n")
        blobClient, err := azblob.NewBlockBlobClient(blobURL, credential, nil)
        if err != nil {
                log.Fatal(err)
        }
        // Upload to data to blob storage
        fmt.Printf("Creating a file at %s\n", blobURL)
        _, err = blobClient.UploadBuffer(ctx, data, azblob.UploadOption{})
        if err != nil {
                log.Fatalf("Failure to upload to blob: %+v", err)
        }
}
```

the output is the same as yours as far as I can tell, except with the permission errors:

```
[~/repos/storage-blobs-go-quickstart] (master) $ go run main.go 
azidentity:  Managed Identity Credential will use IMDS managed identity
azidentity:  NewDefaultAzureCredential failed to initialize some credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
Creating a file at https://wyattlake.blob.core.windows.net/lake/quickstartblob-5160584567682599703
azidentity:  &{%!s(azidentity.azureCLITokenProvider=0x75d0a0) }.GetToken() acquired a token for scope https://storage.azure.com/.default

azidentity:  DefaultAzureCredential authenticated with AzureCLICredential
2022/05/12 09:30:20 Failure to upload to blob: ===== RESPONSE ERROR (ErrorCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:a82cf440-901e-001e-3b1d-66e485000000
Time:2022-05-12T16:30:20.8589936Z, Details: (none)
exit status 1
```

However, I can definitely upload with the CLI. Same terminal, same login session:

```
[~/repos/storage-blobs-go-quickstart] (master) $ az storage blob upload -f ./my-file -c lake -n my-file2 --account-name wyattlake

There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
Finished[#############################################################]  100.0000%
{
  "client_request_id": "ea13f3c6-d210-11ec-a6b2-b10619b41ebf",
  "content_md5": "ZbT/8sDcC+emMlehJfx0og==",
  "date": "2022-05-12T16:31:03+00:00",
  "encryption_key_sha256": null,
  "encryption_scope": null,
  "etag": "\"0x8DA3434CEE56D6E\"",
  "lastModified": "2022-05-12T16:31:04+00:00",
  "request_id": "a45159da-601e-0025-341d-66a121000000",
  "request_server_encrypted": true,
  "version": "2021-04-10",
  "version_id": null
}
```

**Comment by Duffney** [comment]
> cc @Duffney: the sample readme should walk through assigning the necessary RBAC role instead of directing readers to an account access key, which isn't used in AAD token authentication

I agree, and will get the article updated with instructions for adding the necessary RBAC role. Using the key is an alternate method, but not a good fix for the situation. Does the readme or article call specific attention to using AAD token auth as a work around? I couldn't find it mentioned other than in the issues for the repo.

**Comment by wkalt** [comment]
@chlowell Thanks for that clarification. With --auth-mode login it indeed does not work, so this makes sense to me now.
