### ISSUE TITLE
Update azkeys and azsecrets paging API

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#17907]
Both have e.g. `ListDeletedSecrets()` instead of `NewListDeletedSecretsPager()`.

**Comment by richardpark-msft** [comment]
Also, `ListPropertiesOfKeys`

**Comment by richardpark-msft** [comment]
azsecrets:
* ~~ListDeletedSecrets~~
* ListPropertiesOfSecretVersions
* ListPropertiesOfSecrets
