### ISSUE TITLE
Add Support for Updating functions

### ISSUE THREAD

**Issue by dav009** [Azure/azure-sdk-for-go#17904]
### Feature Request

would it be possible to have the equivalent `UpdateClient` for the function below:
```
func (client AppsClient) CreateFunction(ctx context.Context, resourceGroupName string, name string, functionName string, functionEnvelope FunctionEnvelope) (result AppsCreateFunctionFuture, err error) 
```

thanks

**Comment by navba-MSFT** [comment]
@dav009 Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. 
Could you please elaborate your ask ? What is your use case ? What configuration are you trying to update for your functionApp ? Once we get more details we will be able to assist you better. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@dav009 Could you please provide us the above details so that we can assist you further ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@dav009 Since we didn't hear back from you, We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please provide us more details and feel free to reopen this thread. We would be happy to help.
