### ISSUE TITLE
Golang symbol issue when upgrading to armcontainerservices v0.5.0

### ISSUE THREAD

**Issue by giacomo-pati** [Azure/azure-sdk-for-go#17938]
### Bug Report

azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_agentpools_client.go:65:231: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_agentpools_client.go:130:193: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_agentpools_client.go:444:227: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:64:224: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:125:181: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:848:236: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:910: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:972:219: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:1037:223: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:1101:179: undefined: runtime.Poller
azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@v0.5.0/zz_generated_managedclusters_client.go:1101:179: too many errors

We upgraded from v0.3.1 to v0.5.0 and are facing above issue when trying to create/update AKS agent-pools.
Go version is v1.18.2

I've digged a bit into the code. I see that the actual version graph for armcontainerservice@v0.5.0 should result in:

github.com/Azure/azure-sdk-for-go/sdk/azcore v0.23.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.14.0
github.com/Azure/azure-sdk-for-go/sdk/internal v0.9.1

but when I issue a `go get -u -t ./...` in the module it upgrades to:

go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azcore v0.23.0 => v1.0.0
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.14.0 => v1.0.0
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/internal v0.9.1 => v1.0.0

My workaround so far is to have them in the go.mod replace section to fix the versions during upgrade but this can only be a temprary solution.

**Comment by giacomo-pati** [comment]
I've digged a bit into the code. I see that the actual version graph for armcontainerservice@v0.5.0 should result in:

github.com/Azure/azure-sdk-for-go/sdk/azcore v0.23.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.14.0
github.com/Azure/azure-sdk-for-go/sdk/internal v0.9.1

but when I issue a `go get-u -t ./...` in the module it upgrades to:

go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azcore v0.23.0 => v1.0.0
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.14.0 => v1.0.0
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/internal v0.9.1 => v1.0.0

My workaround so far is to have them in the go.mod replace section to fix the versions during upgrade but this can only be a temprary solution.

**Comment by jhendrixMSFT** [comment]
Unfortunately we're in a transitional period with our releases.  We just released the `v1.0.0` of `azcore` and `azidentity` and not all of our other modules have caught up.  When upgrading `armcontainerservice`, if you omit the `-u` and use `@latest` it will avoid updating the transitive dependencies.  Sorry for the hassle, this is our last round of breaking changes before GA.

`
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@latest
`

**Comment by lirenhe** [comment]
@giacomo-pati, we are starting to release the latest version of the SDKs this week.  @tadelesh could help to provide the update when this effort is completed. Thanks

**Comment by tadelesh** [comment]
@giacomo-pati Thanks for your feedback. We've already released the stable version of `armcontainerservices` which will be compatible with the latest `azcore` and `azidentity`.
