### ISSUE TITLE
Request sdk for service imds/dataplane

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#17959]
### Service Package Request

imds/dataplane

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/imds/data-plane

As requested in https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1273

**Comment by jhendrixMSFT** [comment]
I don't believe we'll be releasing any data-plane packages in our legacy SDK.

**Comment by RickWinter** [comment]
Including @sandeep-sen, @mikekistler on this request
