### ISSUE TITLE
recording: nextLink for page failed to find entry

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17985]
For reference in PR https://github.com/Azure/azure-sdk-for-go/pull/17984

TestClient_ListDeletedCertificates would fail.

`
Unable to find a record for the request GET https://thething.vault.azure.net/deletedcertificates?api-version=7.3\u0026$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDAhTURBd01ETXdJV05sY25ScFptbGpZWFJsTDBSRlRFTkZVbFF5TVRRNU16WXpNRE15T0NFd01EQXdNamdoT1RrNU9TMHhNaTB6TVZReU16bzFPVG8xT1M0NU9UazVPVGs1V2lFLSIsIlRhcmdldExvY2F0aW9uIjowfQ
`

Patching the value of `nextLink` resolved the issue.  Not sure what the underlying cause is, but it needs to be fixed.

**Comment by RickWinter** [comment]
In the reimagined new KeyVault SDKs this may not be an issue anymore.  Lets investigate to confirm, if this issue is no longer relevant, please close.

**Comment by chlowell** [comment]
I've forgotten the details of this one. @jhendrixMSFT, do you remember whether you copied that link verbatim? If so, one problem is that the test used an apparently live vault URL in playback instead of the fake one in the recording, and I believe I sorted that out while rewriting the test setup code.

**Comment by jhendrixMSFT** [comment]
The fix I made in https://github.com/Azure/azure-sdk-for-go/pull/17984/commits/7de085806c4fa5b602887cb84e5075a94359307f (and one other) was to modify the host so it matched the host from other recordings within the same file.

It would appear that the URL for the paging GET request was sanitized in the recording (as expected), however, the value of `nextLink` was not.

**Comment by chlowell** [comment]
I see, thank you. Definitely a test bug then. It doesn't happen anymore because we now replace the live Key Vault URL wherever it appears in bodies.
