### ISSUE TITLE
How to handle preview api in specs stable folder

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1798]

**Comment by joshgav** [comment]
Goal is to simplify relationships of preview and stable specs and packages.

**Comment by vladbarosan** [comment]
to clarify here there are 2 dimensions:
1. state of Specs/SDK's  which can be preview or stable .
2. state of the service API which can be preview or GA. 


The question here is about the preview API with stable spec. This shouldn't happen very often but what do we want to do with them ? Put them also in the preview folder ?

**Comment by jhendrixMSFT** [comment]
To close on this, swagger under a ```preview``` directory will generate packages under the ```preview``` directory in the SDK.  All swagger under the ```stable``` directory will go under their respective service directory (even if the API version has a ```-preview``` suffix).
