### ISSUE TITLE
issue with sshPubkeyCertificateThumbprint

### ISSUE THREAD

**Issue by stonevil** [Azure/azure-sdk-for-go#180]
Error response from Azure. Code: BadRequest, Message: The certificate with thumbprint [my_thumbprint] was not found.

**Comment by ahmetalpbalkan** [comment]
@stonevil can you please more details? The method you're calling (`ConfigureForLinux`) is a convenience method and has a few assumptions.

When you specify a certificate thumbprint we look at your `/home/{user}/.ssh/authorized_keys` for a public key with the specified thumbprint.

Also if the certificate is not uploaded to Azure in advance, I believe you will be getting that error.

**Comment by stonevil** [comment]
?
I do not think that is the right option for this like procedure.

Any automation project must be self contained and self managed.
I use a separate folder for all project related stuff to do not mix my key, know_hosts, cloud-config.yaml, etc.
It will more convenient to pass keys like []byte or path to folder with same base_name for keys.
base_name_id_rsa
base_name_id_rsa.pub
base_name_id_rsa.pem
base_name_id_rsa.cert
Or something like this.

Anyway. At OS X path to home totally different. /Users/{user}.
It will be much better to use http://golang.org/pkg/os/user/ for user home folder resolve.
sample code:
func homeFolder() string {
	u, err := user.Current()
	if err != nil {
		panic(err)
	}
	return u.HomeDir
}

**Comment by ahmetalpbalkan** [comment]
@stonevil please ignore my earlier answer, I wasn't entirely familiar with what this configuration set does. It looks like the path is actually on the created VM, so the `/home/{user}/.ssh/authorized_keys` should be okay.

However it looks like in order to specify a public key, the certificate must be already associated with the cloud service and thumbprint is the SHA1 fingerprint of the certificate. Please take a look at the “SSH” section here:

https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx

**Comment by stonevil** [comment]
One or another way it just doesn't work.

Keys generated with:
BASE_NAME ?= test01
KEY_NAME ?= $(BASE_NAME)_id_rsa
genkey:
	if [ ! -f $(KEY_NAME) ]; then \
		echo "Generate secure keys for $(BASE_NAME)" ; \
		ssh-keygen -f $(KEY_NAME) -t rsa \
		&& openssl req -x509 -key $(KEY_NAME) -nodes -days 3650 -newkey rsa:2048 -out $(KEY_NAME).pem -subj "/C=$(C)/ST=$(ST)/L=$(L)/O=$(O)/OU=$(OU)/CN=$(CN)" \
		&& openssl x509 -outform der -in $(KEY_NAME).pem -out $(KEY_NAME).cer ; \
	fi

.cer files uploaded to MANAGEMENT CERTIFICATES.
All generated keys file moved to $HOME/.ssh/authorized_keys

Thumbprint FE50FB8F72087E9F22C3B8A98FE6505900246A9D added to conifg file.
And still this same error:
BadRequest, Message: The certificate with thumbprint FE50FB8F72087E9F22C3B8A98FE6505900246A9D was not found

**Comment by stonevil** [comment]
Anyway. Why this procedure so different from azure-cli?

**Comment by paulmey** [comment]
Not sure if this is still open... but here goes.
The .cer files should be uploaded to the 'cloud service' not to 'management certificates'. You can use the [AddCertificate](https://github.com/Azure/azure-sdk-for-go/blob/master/management/hostedservice/client.go#L105) method.

The cli hides all this hideousness from the user, but does the same thing eventually.

**Comment by vishrutshah** [comment]
Closing this one as it has been inactive for a while. Feel free to reopen if you find any issues. Thanks!
