### ISSUE TITLE
azureml computeinstance API unclear on SetupScripts parameters when ScriptSource is set to "inline"

### ISSUE THREAD

**Issue by a30004053** [Azure/azure-sdk-for-go#18017]
### Bug Report

Based on the comment on acceptable sources:
https://github.com/Azure/azure-sdk-for-go/blob/main/services/machinelearningservices/mgmt/2021-07-01/machinelearningservices/models.go#L3777-L3779
when the script is set to "inline" we get the following error

> User specified setup script file not found. Details - SetupScriptsError:User specified setup scriptfile not found. 

- What happened?
When `ScriptSource` is set to `"inline"`, the API returns 

> ("Compute: (Name \"computeinstance1\" / Workspace Name \"AML-dev-agl\" / Resource Group \"xxx-xxx\")"): Code="BadRequest" Message="{\"id\":\"https://australiaeast.api.azureml.ms/batchai/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.BatchAI/locations/australiaeast/operationresults/00000000-0000-0000-0000-000000000000\",\"name\":\"00000000-0000-0000-0000-000000000000\",\"status\":\"Failed\",\"startTime\":\"2022-05-17T02:38:42.429Z\",\"endTime\":\"2022-05-17T02:42:56.623Z\",\"error\":{\"code\":\"SetupScriptsError\",\"message\":\"The specified Azure ML Compute Instance computeinstance1 user script setup failed with error \\\"User specified setup script file not found. Details - SetupScriptsError:User specified setup scriptfile not found. \\\". Please delete and try to recreate. If the problem persists, please follow up with Azure Support.\"}}"

- What did you expect or want to happen?
Compute instance created with a successfully executed SetupScript

- How can we reproduce it?
create data payload
```json
{
    "location": "australiaeast",
    "properties": {
        "computeType": "ComputeInstance",
        "properties": {
            "vmSize": "STANDARD_DS11_V2",
            "subnet": {
                "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1"
            },
            "applicationSharingPolicy": "Personal",
            "sshSettings": {
                "sshPublicAccess": "Enabled",
                "adminPublicKey": "ssh-rsa AAAAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            },
            "computeInstanceAuthorizationType": "personal",
            "setupScripts": {
                "scripts": {
                    "creationScript": {
                        "scriptSource": "inline",
                        "scriptData": "echo 'this is a test' >> /tmp/file",
                        "timeout": "15m"
                    }
                }
            }
        }
    }
}
```
and `PUT`
```bash
PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.MachineLearningServices/workspaces/ml-workspace-1/computes/computeinstance1?api-version=2022-02-01-preview
```

- Anything we should know about your environment.
run using `go 1.18.1`
Passing an existing script (in the workspaceStorage location), creates the instance successfully.
```json
   "setupScripts": {
        "scripts": {
         "creationScript": {
          "scriptSource": "workspaceStorage",
           "scriptData": "Users/user1/script.sh",
           "timeout": "15m"
           }
        }
    }
```

**Comment by navba-MSFT** [comment]
Adding the Service Team to look into this.

**Comment by Drewm3** [comment]
Fixing this to be Machine Learning as compared to standard VM computing.

**Comment by nthandeMS** [comment]
Inline scripts are not supported right now, per the Compute Instance team. We will update the API accordingly.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
