### ISSUE TITLE
unexpected InvalidBlockList error

### ISSUE THREAD

**Issue by meirf** [Azure/azure-sdk-for-go#1806]
Here's my code:

```
blockID := "MDAwMDA=" // base64 encoding of 00000
err := PutBlock(blockID, content, nil) // err is nil
block := storage.Block{ID: blockID, Status: storage.BlockStatusUncommitted}
err = b.PutBlockList(block, nil)
// err is "StatusCode=400, ErrorCode=InvalidBlockList, 
// ErrorMessage=The specified block list is invalid"
```
Note `content` is very small and easily fits in one block.

Detailed request:
```
PUT /foo?comp=blocklist HTTP/1.1
Host: mycontainer.blob.core.cloudapi.de
User-Agent: Go/go1.10.2 (amd64-darwin) azure-storage-go/v12.2.0-beta api-version/2016-05-31 blob
Content-Length: 96
Authorization: SharedKey mycontainer:KEYABC123=
x-ms-blob-content-type: text/html; charset=utf-8
x-ms-date: Mon, 07 May 2018 23:50:48 GMT
x-ms-version: 2016-05-31
Accept-Encoding: gzip
```

Any idea why my block list is invalid?

**Comment by jhendrixMSFT** [comment]
Hello!  Sorry for the delay.  Using the latest version of the SDK (16.2.2) I wasn't able to repro this issue however I didn't see any obvious bug fixes here that would explain the discrepancy.  Are you able to try this against the latest version?

**Comment by jhendrixMSFT** [comment]
Hmm I rolled back to v12.2.0 and I still can't repro the issue.

**Comment by jhendrixMSFT** [comment]
Hello @meirf is this still an issue for you?  If so do you have a simple repro handy?

**Comment by jhendrixMSFT** [comment]
Please reopen if this is still an issue and provide a minimal repro.
