### ISSUE TITLE
Go types representing ARM template and parameters

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-sdk-for-go#1810]
It would be great if it were possible to marshal/unmarshal entire ARM templates and parameters files to strongly typed Go structs.  At the moment it seems like these are handled everywhere as `interface{}`, which makes validating/modifying these painful and error prone.  As an idea I'd like to be able to do something like:

```golang
var template azure.ARMTemplate  // AFAICS a type like this is not currently defined anywhere?
err := json.Unmarshal(b, &template)
if err != nil {
	panic(err)
}
for res := range template.Resources {
	fmt.Printf("name: %s\n", res.Name())  // template.Resources might be an interface type implementing basics such as Name() string
	if vm, ok := res.(*azure.VirtualMachine); ok { // need some mechanism to jump from an apiVersion/type to a useful concrete type
		fmt.Printf("admin username: %s\n", vm.Properties.OsProfile.AdminUsername)
	}
}
```

**Comment by jim-minter** [comment]
@jackfrancis fyi

**Comment by lirenhe** [comment]
Close it as no action needed for this item. @jim-minter, please reopen this if you still need this design.
