### ISSUE TITLE
Cannot update tag of a recovery service managed group

### ISSUE THREAD

**Issue by csorzi** [Azure/azure-sdk-for-go#18186]
### Bug Report

- import path of package: `.../services/resources/mgmt/2020-06-01/resources`
- SDK version: v64.0.0
- go version: 1.18.x 

- What happened?
Terraform azurerm provider version 3.6.0(using the above specified go sdk) throws the following error after importing a resource group created by Recovery Services Vault and trying to update its tags:
```
resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ResourceGroupManagedByMismatch" Message="The managed by property of the resource group cannot be changed from its current value 'subscriptions/***/providers/Microsoft.RecoveryServices/'
```

- What did you expect or want to happen?
Tags can be updated via go sdk/API

- How can we reproduce it?
Specify a backup resource group in Recovery Services Vault that will get created by RSV, try to update its tags via Go/terraform azurerm provider(v3.6.0)

**Comment by navba-MSFT** [comment]
@csorzi Apologies for the late reply. Thanks for reaching out to us and sharing the update.

>How can we reproduce it?
Specify a backup resource group in Recovery Services Vault that will get created by RSV, try to update its tags via Go/terraform azurerm provider(v3.6.0)

Question:
Are you referring to the resource group of the recovery service vault ? Or Are you referring to the resource group of the backup  that you have configured in Recovery service vault ?

Awaiting your reply.

**Comment by csorzi** [comment]
I meant the former: you specify an RG for the backup, and if its not created beforehand by any other way its created by Recovery Services Vault itself.

**Comment by navba-MSFT** [comment]
@csorzi Could you use the below sample code and check if that helps ?

```
package main

// Import key modules.
import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	"github.com/Azure/go-autorest/autorest/to"
)

// Define key global variables.
var (
	subscriptionId    = "XXXXXXXXXXXXXXX" // !! IMPORTANT: Change this to your subscription.
	location          = "YourRGLocation"  // !! IMPORTANT: Change this to your RG Location in your subscription.
	resourceGroupName = "YourRGName" // !! IMPORTANT: Change this to a unique name in your subscription.
	ctx               = context.Background()
)


// Update the resource group by adding a tag to it.
func updateResourceGroup(subscriptionId string, credential azcore.TokenCredential) (armresources.ResourceGroupsClientUpdateResponse, error) {
	rgClient, err5 := armresources.NewResourceGroupsClient(subscriptionId, credential, nil)

	if err5 != nil {
		log.Fatal(err5)
	}
	update := armresources.ResourceGroupPatchable{
		Tags: map[string]*string{
			"new": to.StringPtr("tag"),
		},
	}
	return rgClient.Update(ctx, resourceGroupName, update, nil)
}

// Define the standard 'main' function for an app that is called from the command line.
func main() {

	// Create a credentials object.
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("Authentication failure: %+v", err)
	}

	// Call your function to add a tag to your new resource group.
	updatedRG, err := updateResourceGroup(subscriptionId, cred)
	if err != nil {
		log.Fatalf("Update of resource group failed: %+v", err)
	}
	log.Printf("Resource Group %s updated", *updatedRG.ResourceGroup.ID)

}
```
Please test this and let me know. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@csorzi I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if the above sample helped in achieving your requirement. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@csorzi The action is currently pending on you to try the above sample. Please provide an update once you get a chance. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
