### ISSUE TITLE
Cannot build the source code with library `azblob v0.4.x`

### ISSUE THREAD

**Issue by ninjadq** [Azure/azure-sdk-for-go#18199]
### Bug Report

The import path is `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
SDK version is `v0.4.1` and `v0.4.0`
Go version is `go version go1.17.7 linux/amd64`

- What happened?

When I build the source code, an error message occurred 
```
package command-line-arguments
        imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob: build constraints exclude all Go files in /home/dq/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.4.1
```
And the building process stopped.
- What did you expect or want to happen?
The source code should work correctly to generate a binary
- How can we reproduce it?
you can try this https://github.com/Azure-Samples/storage-blobs-go-quickstart sample code with changing the version of azblob

**Comment by jhendrixMSFT** [comment]
Per the quickstart [prerequisites](https://github.com/Azure-Samples/storage-blobs-go-quickstart#prerequisites), our SDKs require Go 1.18.
