### ISSUE TITLE
(*azblob.ContainerClient).ListBlobsFlat returns no error when using wrong cred

### ISSUE THREAD

**Issue by sfc-gh-llin** [Azure/azure-sdk-for-go#18194]
### Bug Report
- What happened?
I was trying to listBlobs with azidentity.NewClientSecretCredential as credential. However, I didn't get any errors with wrong tenantID, clientID or clientSecret.
- What did you expect or want to happen?
pager.Err() should say something like "wrong auth" instead of nil when cred is wrong
- How can we reproduce it?
Here is my code
```
package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
)

func main() {
	tentID := "asdasdasda"
	clientID := "asdfasdfasdf"
	clientSecret := "1231323"

	cred, err := azidentity.NewClientSecretCredential(tentID, clientID, clientSecret, nil)
	if err != nil {
		panic(err)
	}
	azBClient, err := azblob.NewServiceClient("https://<storageAccount>.blob.core.windows.net/", cred, nil)
	if err != nil {
		panic(err)
	}
	conClient, err := azBClient.NewContainerClient("<containerName>")
	if err != nil {
		panic(err)
	}
	pager := conClient.ListBlobsFlat(
		&azblob.ContainerListBlobsFlatOptions{})
	fmt.Println(pager.Err())

	for pager.NextPage(context.TODO()) {
		resp := pager.PageResponse()
		fmt.Println("page len: ", len(resp.Segment.BlobItems))
		for _, v := range resp.Segment.BlobItems {
			fmt.Println(*(v.Name))
		}
	}
}
```
And the output is like:
```
$ go run main.go
<nil>
```

As you can see we are getting nil error with some random cred. I am wondering is it designed like this or there should be some error? If this is designed like this, how do we know there is authentication error or the container is just empty?

Looking forward to your replies

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
As in the code
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
```
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.0.0
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.4.1
```
- output of `go version`
go version go1.18 darwin/arm64

- Anything we should know about your environment.

**Comment by mohsha-msft** [comment]
Hey @sfc-gh-llin ,

Thanks for reaching out!

Let me shine some light on the issue you raised. The function `conClient.ListBlobsFlat(&azblob.ContainerListBlobsFlatOptions{})` just creates a pager. But the actual request is sent when we try to fetch the first pager i.e. `pager.NextPage(context.TODO())`. Once we try to get the first pager, only after that can we expect err and resp to have non-null values.

Please check out [this example](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/zt_examples_test.go#L267) for more information.

```golang
// Pager Constructor
pager := serviceClient.ListContainers(&listContainersOptions)

// Send the request to fetch the pager. Next() function is where we first try to fetch a page.
for pager.NextPage(context.TODO()) {
    // Now both resp and err are available to us.   err := pager.Err() will contain the error now.
    resp := pager.PageResponse()
  
    for _, container := range resp.ContainerItems {
	fmt.Println(*container.Name)
    }
}

if pager.Err() != nil {
     log.Fatal(pager.Err())
}
```

I hope my explaination helps. If you have any questions, don't hesitate to reach out to me.

**Comment by mohsha-msft** [comment]
Please reopen this if your query is not resolved.
