### ISSUE TITLE
Error while performing create role assigment

### ISSUE THREAD

**Issue by miazamrai** [Azure/azure-sdk-for-go#18201]
I am trying to create role assignment but it is failing with the following error message.
 The role does have DataActions.
 
 authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedApiVersionForRoleDefinitionHasDataActions" Message="Assignments to roles with DataActions and NotDataActions are not supported on API version '2015-07-01'. The minimum required API version for this operations is '2018-01-01-preview'."

- import path: github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2020-10-01/authorization
- SDK version: github.com/Azure/azure-sdk-for-go v64.1.0+incompatible
- output of `go version` 1.18
- azure autorest 0.11.27

**Comment by jhendrixMSFT** [comment]
What Azure region are you executing this in?

**Comment by tadelesh** [comment]
@miazamrai Thank you for the feedback. Please note, the package `github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2020-10-01/authorization` has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Could you please upgrade to the new version first and feel free to feedback if any further problem?
