### ISSUE TITLE
Cant 'go get' anymore

### ISSUE THREAD

**Issue by pangteypiyush** [Azure/azure-sdk-for-go#18209]
### Bug Report

- What happened?
Trying to go get subscription module

```
go get -u -v github.com/Azure/azure-sdk-for-go/services/subscription/mgmt/2020-09-01/subscription
go: downloading github.com/Azure/azure-sdk-for-go v64.2.0+incompatible
go: github.com/Azure/azure-sdk-for-go/services/subscription/mgmt/2020-09-01/subscription: create zip: module source tree too large (max size is 524288000 bytes)
```

- What did you expect or want to happen?
Finish without an error.
The last version which I didnt had this issue:

```
go get github.com/Azure/azure-sdk-for-go@v50.2.0
go: added github.com/Azure/azure-sdk-for-go v50.2.0+incompatible
```

**Comment by OscarVanL** [comment]
I get this problem too when doing `go list -u -m -json all`

```
go: loading module retractions for github.com/Azure/azure-sdk-for-go@v16.2.1+incompatible: verifying go.mod: github.com/Azure/azure-sdk-for-go@v64.2.0+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/!azure/azure-sdk-for-go@v64.2.0+incompatible: 410 Gone
        server response: not found: create zip: module source tree too large (max size is 524288000 bytes)
```

**Comment by jhendrixMSFT** [comment]
I believe we will need to prune old API versions to reduce the repo size.

**Comment by jhendrixMSFT** [comment]
While we're working on removing old content, you should be able to use `v64.1.0` instead (unless you need something specific in `v64.2.0`).

**Comment by ceejatec** [comment]
@jhendrixMSFT That's unfortunately not true - we have a module which references v64.1.0 in its go.mod, but when running `go list -mod=readonly -m -u -json all` in that directory, we get the above error message anyway. I don't know *why* go is still trying to download that newer version.

**Comment by ceejatec** [comment]
Only workaround I've found so far is to set the GONOSUMDB environment variable to `github.com/Azure/azure-sdk-for-go`.

**Comment by jhendrixMSFT** [comment]
Thanks for the data-point.  It works for me, so there must be some other bit we don't yet understand.  At any rate, we should have an update out soon that shrinks the size under the 500MB limit.

**Comment by lootek** [comment]
> While we're working on removing old content, you should be able to use `v64.1.0` instead (unless you need something specific in `v64.2.0`).

no, we're not able to freeze version in go.mod due to an error:

```
go.mod:75:2: replace github.com/Azure/azure-sdk-for-go: version "v64.1.0" invalid: should be v0 or v1, not v64
```

the workaround that worked was to replace to freeze to the latest commit hash instead (it's an ugly and hopefully a temporary one though)

**Comment by prochac** [comment]
May I ask, why is the repo so heavy?
After running `go clean --modcache` and redownloading all modules I use,
Azure SDK makes **34%** of my `$GOPATH/go/mod` size.
Only competitor is github.com/aws/aws-sdk-go with 10%.

**Comment by jhendrixMSFT** [comment]
Azure uses date-based API versions in the query string to partition updates to a service that aren't backward-compatible (I don't believe AWS has such a mechanism).  Our legacy SDK, which predates Go modules, releases all of these API versions side-by-side to reduce/remove breaking changes across service updates.  You can see an example of this [here](https://github.com/Azure/azure-sdk-for-go/tree/main/services/network/mgmt).  Unfortunately, it does mean that the repo grows over time.  We have a work item to eliminate old/unused API versions to reduce the size, it just hasn't happened yet.

Going forward, our [new SDKs](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk) use Go modules to manage breaking changes, so we won't be releasing all API versions side-by-side.
