### ISSUE TITLE
scheduler: JobCollectionQuota.MaxJobOccurrence does not seem to do anything.

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#1823]
Setting this value:
https://github.com/Azure/azure-sdk-for-go/blob/56332fec5b308fbb6615fa1af6117394cdba186d/services/scheduler/mgmt/2016-03-01/scheduler/models.go#L755

does not seem to have any effect, I am unsure about the other packages.

**Comment by jhendrixMSFT** [comment]
@pinwang81 can you help route?

**Comment by lirenhe** [comment]
This item has been there for 3 years with no action from service team. Close this one and @katbyte, please let us know if the issue is still there and you need a fix for it.
