### ISSUE TITLE
cosmosdb: client.ListKeys() only returns write keys, but appears to also return read keys.

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#1824]
Looking at `client.ListKeys()` it returns a `DatabaseAccountListKeysResult` that contains a `*DatabaseAccountListReadOnlyKeysResult` pointer:

https://github.com/Azure/azure-sdk-for-go/blob/fad8443a79b0e755c18c3bec29a8d2bedab0b421/services/cosmos-db/mgmt/2015-04-08/documentdb/models.go#L447

This pointer seems to always be nil, regardless of database type.

**Comment by jhendrixMSFT** [comment]
@katbyte sorry for the delay.
The [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json#L1772) doesn't appear to properly model the response body.  I'll follow up with the service team about this.
```json
{
  "primaryMasterKey": "xxx",
  "secondaryMasterKey": "xxx",
  "primaryReadonlyMasterKey": "xxx",
  "secondaryReadonlyMasterKey": "xxx"
}
```

**Comment by jhendrixMSFT** [comment]
Opened https://github.com/Azure/azure-rest-api-specs/issues/3603 to track fixing the swagger.

**Comment by jhendrixMSFT** [comment]
Closing this, will track via the specs issue.
