### ISSUE TITLE
scheduler: JobRecurrence.Count silently fails & produces odd results when  > 2147483647

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#1826]
scheduler: JobRecurrence.Count silently fails & produces odd results when > 2147483647.

Could not determine a pattern.

**Comment by soggysec** [comment]
If I had to guess, it's because Count is defined as an Int32. 2147483647 = MAX_INT and incrementing it by 1 wraps it around to the MIN_INT, or -2147483648. An example is provided below. A better implementation would use an unsigned int, but you'll still have to account for wrapping

```
package main

import (
	"fmt"
)

func incCount(count *int32) {
	*count++
}

func main() {

	var count int32 = 2147483647
	fmt.Println("Before: ", count)
	incCount(&count)
	fmt.Println("After: ", count)
}
```
Running this:
```
go run test.go 
Before:  2147483647
After:  -2147483648
```

**Comment by katbyte** [comment]
I figured it was something to do with `MAX_INT`, as thats how I arrived at the value. However API should not silently fail when its encountered 🙂

**Comment by jhendrixMSFT** [comment]
@pinwang81 I found your user ID in the specs repo history.  Do you work on this service or know who can help?

**Comment by lirenhe** [comment]
@katbyte, as this item has been there or long time, did you still face this issue? If so, could you provide more detail?
