### ISSUE TITLE
Problem for `Dump Package properties`

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#18276]
This new added step cannot handle some internal tools under `eng/tools` folder. Log is [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1607851&view=logs&j=730d91e9-ccca-5f92-9343-3b1124b19442&t=57014ab0-c321-5206-21d1-de9826f53695).

**Comment by benbp** [comment]
@tadelesh not sure if this issue has been noticed or not? I'm going to add it to our engsys project so it comes past our planning meeting.
