### ISSUE TITLE
Dependabot alert  -Unhandled exception in gopkg.in/yaml.v3 #2

### ISSUE THREAD

**Issue by AsafMah** [Azure/azure-sdk-for-go#18280]
### Bug Report

- import path of package in question,-`azure-sdk-for-go/tree/main/sdk/storage/azblob`
- SDK version -`0.4.1`
- output of `go version` - go version go1.18.2 windows/amd64

- What happened?
We depend on azblob, and now we got this error - https://github.com/Azure/azure-kusto-go/security/dependabot/2
running `go mod why` shows it comes from azblob.
- What did you expect or want to happen?
not to get the error
- How can we reproduce it?
Depend on azblob with a dependabot active
- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Dupe of https://github.com/Azure/azure-sdk-for-go/issues/18249.  Needs an upstream fix in `go-vcr`
