### ISSUE TITLE
Feature request: Support for traffic manager / Load balancer

### ISSUE THREAD

**Issue by dhilton** [Azure/azure-sdk-for-go#183]
We have a use case where we'd like to use Terraform to create traffic managers / load balancers in Azure. To support this we need this client library to support it, so terraform can then support it via the stable library that it currently depends on.

I've seen mention in some of the other issues of a auto API code generation, does that mean that you wouldn't accept a PR to add this?

**Comment by dhilton** [comment]
It is - any idea on when that code generation will merge into master? Because that solves a couple of other issues I have or rather enables them to be solved rather quickly.

**Comment by ahmetalpbalkan** [comment]
cc: @brendandixon to give an update.

**Comment by brendandixon** [comment]
We hope to have an early alpha sometime in the next three weeks. However, what will be included is still being worked out. Our code generation process is still underdevelopment.

**Comment by dhilton** [comment]
Ah cool - thanks for the update, if there is anything I can do to help please just point at a repo/branch here. Good luck with the coding.

**Comment by brendandixon** [comment]
Thanks. We'll likely post a blog somewhere (possibly at https://ahmetalpbalkan.com) once it's available. Stay tuned!

**Comment by proffalken** [comment]
We're also very interested in this.

We're in the process of moving some of our Terraform code from AWS to Azure and load-balancing/traffic managers are definitely something that we need! :)

**Comment by dhilton** [comment]
Waves @proffalken we should swap notes some time, our code is here: https://github.com/alphagov/tsuru-terraform

**Comment by brendandixon** [comment]
@dhilton We've released the initial set of ARM Go packages. They are generated from Swagger definitions found here: https://github.com/Azure/azure-rest-api-specs. We do not yet have a Swagger definition file for the DNS REST API (see https://msdn.microsoft.com/en-us/library/azure/mt163862.aspx), but you can use ARM templates through the arm/resources package. I would go that route for now.

**Comment by dhilton** [comment]
OK cool - what's the versioning approach with that repo? I.e. If it's used as a dependency, is it likely to add any breaking changes or will it simply be a matter of adding extra API's to the client library? Is this the new preferred client lib to Azure?

**Comment by ahmetalpbalkan** [comment]
@dhilton right now none of the packages have a backwards compatibility or versioning story. If you take a look at the repo it consists of several totally independent packages `storage`, `arm` and `management (asm)`. Among those, `storage` and `management` have been fairly stable in the past 3-4 months and they had an almost complete rewrite recently so I don't expect those to break. OTOH, `arm` is likely to break based on user-comments we're currently collecting. That package is auto-generated and is in an alpha state; whereas you can call others beta or above.

As you can imagine, when you have 3 separate packages, versioning/tagging is a bit tricky as each have their own release cycles. But we'll be introducing versioning through tags soon.

Bottomline is, if you are relying on current snapshot of the repo, please use godep/gb etc. to vendor this snapshot (commit) of the repo (meaning, have a local copy of this repo in your project). Soon when we start using tags, you can vendor the tags directly and read the changelogs (also we'll start doing this) to see if you actually need to update the vendored version. Does that answer your question?

**Comment by garimakhulbe** [comment]
Old issue. This is added in Azure Go SDK. Closing this.

https://github.com/Azure/azure-sdk-for-go/tree/master/arm/trafficmanager
