### ISSUE TITLE
automation schedule interval property seems to have lost its type

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#1830]
Hello,

So it appears that the automation schedule interval property is missing a type somewhere (probably in the swagger). 

The portal only accepts decimal values but it fails to create/save them with the error:
<img width="371" alt="screen shot 2018-05-14 at 13 34 14" src="https://user-images.githubusercontent.com/1638467/40022000-8b6119e2-577b-11e8-9fbe-0a3de99f564b.png">

Looking at the [docs:](https://docs.microsoft.com/en-us/rest/api/automation/schedule/createorupdate) its type is blank
<img width="781" alt="screen shot 2018-05-14 at 13 16 44" src="https://user-images.githubusercontent.com/1638467/40021226-1d0c4be4-5779-11e8-8cad-14378e419505.png">

Looking at the resources site it appears to be an `int`, but when editing the value and putting a decimal value it rounds nearest integer.
<img width="191" alt="screen shot 2018-05-14 at 13 25 19" src="https://user-images.githubusercontent.com/1638467/40022013-9a1b0fa6-577b-11e8-8a0c-0cddd7829595.png">

Looking at the [SDK code](https://github.com/Azure/azure-sdk-for-go/blob/4b3cf752d4d7bf6bbf3cde9d5c4d1157098726e3/services/automation/mgmt/2015-10-31/automation/models.go#L6196) it is an `interface{}`, and whilst one might assume it casts to an `int`, is appears to not be the case
```
panic: interface conversion: interface {} is float64, not int
2018-05-14T13:04:30.224-0700 [DEBUG] plugin.terraform-provider-azurerm:
2018-05-14T13:04:30.224-0700 [DEBUG] plugin.terraform-provider-azurerm: goroutine 114 [running]:
```

So by all accounts it should be an `int`, but currently seems to have no definite type.

Imported package: `github.com/Azure/azure-sdk-for-go/services/automation/mgmt/2015-10-31/automation`

**Comment by jhendrixMSFT** [comment]
The interval doesn't specify the data type, see the swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/definitions.json#L2898.

**Comment by jhendrixMSFT** [comment]
This has been moved to the specs repo https://github.com/Azure/azure-sdk-for-go/issues/1830

**Comment by katbyte** [comment]
@jhendrixMSFT: Is that supposed to link to the specs repo? 🤔 links back here
