### ISSUE TITLE
Add deprecated messages for track1 mgmt. plane packages

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#18327]
1. Add deprecated comment for all the mgmt. packages
2. Do not add comment to packages under 'profiles`
3. Close all track1 release request
4. Release last track1 version

**Comment by RickWinter** [comment]
FYI, @mario-guerra for reference on the planned deprecation of previous versions of mgmt plane SDKs in GO.

**Comment by tadelesh** [comment]
Message: (compute for example)

Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
