### ISSUE TITLE
Flatten options bag Properties fields

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#18324]
Several options bags have a `Properties` field. This should be flattened for a couple reasons:
- `Properties` has several read-only fields. Users have to check the docs to know which fields have an effect when set.
- `Properties` sometimes duplicates an options bag's fields. For example, `CreateKeyOptions` and `Properties` both have a `Tags` field.

**Comment by RickWinter** [comment]
Is there more you want to do beyond what PR #18309 fixed?

**Comment by chlowell** [comment]
Yes, this issue tracks another round of unrelated API changes.

**Comment by chlowell** [comment]
Closing this because we decided to remove the `Properties` type.
