### ISSUE TITLE
Error while specifying Ingestion as the data source type for linked storage accounts

### ISSUE THREAD

**Issue by sapphire-sk** [Azure/azure-sdk-for-go#18322]
### Bug Report
I am trying to link storage accounts with data source type as Ingestion
The API version `2020-03-01-preview` supported DataSourceType enum with 'Ingestion' as one of the valid values for log analytics linked storage account.
However, this value was removed in `2020-08-01` leading to 'Invalid value' error when storage accounts are linked to a workspace where the data source type is specified as Ingestion

- import path: `../services/operationalinsights/mgmt/2020-08-01/operationalinsights/`
- SDK version: `github.com/Azure/azure-sdk-for-go v64.0.0`
- output of go version 1.18

Why is 'Ingestion' data source type no longer as part of the enum?

**Comment by navba-MSFT** [comment]
@sapphire-sk Thanks for reaching out to us and sharing this feedback. We are looking into this issue. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@sapphire-sk Could you please share your use case here ? Also what what scenario you are trying to fulfill with linked storage account for ingestion? Awaiting your reply.

**Comment by sapphire-sk** [comment]
Linking storage accounts to Log Analytics workspace allows having your own managed storage account to store the logs instead of a service owned storage account.

- In previous API, it was possible to link a storage account where the data source type is 'Ingestion' meaning this allowed the logging agents to send 'Ingestion' data captured from the resources to the linked storage account. These logs can then be analyzed and then categorize them as Failed or Succeeded Ingestion

- However, since the API no longer supports 'Ingestion', the logging agents cannot be configured to exclusively collect 'Ingestion' logs and send them to a customer managed storage account

**Comment by navba-MSFT** [comment]
@sapphire-sk I had filed this PR to address this https://github.com/Azure/azure-rest-api-specs/pull/19365

Once the swagger update  will be approved and merged by ARM, our product Owners will trigger the GO SDK generation.
Then it is a matter of a few days until it will be publicly available.

**Comment by navba-MSFT** [comment]
@sapphire-sk The PR has been merged now. So our Product Owners will check this further and then  trigger the GO SDK generation. This will take few days to be available publicly. No fixed ETA can be shared for this now. With that we will proceed with archival of this thread. If you need any further assistance on this in future feel free to reopen this thread. We would be happy to help.
