### ISSUE TITLE
azidentity - `NewDefaultAzureCredential` fails to get MSI credentials in GitHub Actions runner

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/azure-sdk-for-go#18352]
### Bug Report

- import
`github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.0.0` 
- output of `go version`
`go version go1.18.3 linux/amd64`

- What happened?
Within a GitHub Actions workflow, running within [Azapi Terraform provider](/Azure/terraform-provider-azapi) the `NewDefaultAzureCredential` func failed to get a MSI credential from the default endpoint because MSI was not enabled. The GitHub runner must have been hosted in Azure. The error was a HTTP 400 and it prevented the `NewDefaultAzureCredential` from continuing and trying other methods to get credentials.

- What did you expect or want to happen?
I want the `NewDefaultAzureCredential` func to continue if we get such an HTTP error, instead of failing.

- How can we reproduce it?
Use the `NewDefaultAzureCredential` func within a GitHub actions public runner.

- Anything we should know about your environment.
When I add an iptables rule to block access to 169.254.169.254, then the `NewDefaultAzureCredential` func works.

- Error detail
```text
Error:      	Received unexpected error:
                                DefaultAzureCredential authentication failed
        	            	GET http://169.254.169.254/metadata/identity/oauth2/token
        	            	--------------------------------------------------------------------------------
        	            	RESPONSE [400] Bad Request
        	            	--------------------------------------------------------------------------------
        	            	{
        	            	  "error": "invalid_request",
        	            	  "error_description": "Identity not found"
        	            	}
        	            	--------------------------------------------------------------------------------
```

**Comment by chlowell** [comment]
Can you double check your `azidentity` version? Since v0.13.0, `NewDefaultAzureCredential` doesn't do any I/O, making HTTP errors impossible. You could see this with an older version though.

**Comment by matt-FFFFFF** [comment]
Hey @chlowell,

Thanks for getting back to me!

The version of `azidentity` is v1.0.0. Of it's not azidentity doing this then it may be the policy client then that is. All I know is somewhere along the line the SDK is reaching out to get a MSI token and this fails on the public GitHub actions runners.

I've been able to work around it by putting in an iptables rule to block access to the endpoint.

**Comment by chlowell** [comment]
> If it's not azidentity doing this, then it may be the policy client then that is. All I know is somewhere along the line the SDK is reaching out to get a MSI token and this fails on the public GitHub actions runners.
> 

I think I understand what's happening here. Before I get into that, how do you intend to authenticate? For `DefaultAzureCredential`, all that's left after managed identity is the Azure CLI--is that available to GitHub Actions? If you want to authenticate a service principal, you need to set the right [environment variables](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#readme-environment-variables).

As for the cause of this error, IMDS responds with the 400 you pasted above when it has no managed identity assigned. The credential considers this error non-fatal, as you want, unless the application provided a client ID for a user-assigned managed identity. The reasoning there is that the application must expect the identity it specified will be available; its unavailability then indicates a configuration error. Authenticating some other identity makes that hard to debug and can result in unexpected behavior or mysterious failures, if the other identity has different permissions. For `DefaultAzureCredential`, this client ID comes from `AZURE_CLIENT_ID`. If you aren't setting that yourself somehow, I see the Terraform provider will do so if it's configured with a client ID: https://github.com/Azure/terraform-provider-azapi/blob/3708a6e2376656691d2b31a9a2d7ded8435e2946/internal/provider/provider.go#L172.

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF , @chlowell ,

Thank you so much for the investigation! Really appreciate it.

I raised a PR to fix it on the azapi side, which won't set `AZURE_CLIENT_ID` if it's empty. 

> The reasoning there is that the application must expect the identity it specified will be available; its unavailability then indicates a configuration error.

Totally agreed, but I think maybe specifying an empty client id should not be a fatal error? I'm not sure if it's a good idea to add a not-empty check on
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/default_azure_credential.go#L62

Thanks!

**Comment by magodo** [comment]
> Totally agreed, but I think maybe specifying an empty client id should not be a fatal error? I'm not sure if it's a good idea to add a not-empty check on https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/default_azure_credential.go#L62

I think we shall only set the client id when it is non empty. So instead of using `os.LookupEnv()`, we can simply use `os.Getenv()` and then check whether the client id is empty.

**Comment by chlowell** [comment]
> maybe specifying an empty client id should not be a fatal error? I'm not sure if it's a good idea to add a not-empty check

😆 I'm not sure either but here's my argument for keeping the current behavior. The SDK's only evidence of user intent is whether the variable is set. Our managed identity abstraction supports several platforms with different APIs and semantics. It's possible that in some scenario it makes sense for a user to specify an empty client ID (I don't know of one). Ignoring the empty value may mean not supporting that scenario or authenticating an unexpected identity and causing worse problems as I described above. The best the SDK can do is assume configuration is correct and allow the platform to point out problems via authentication errors.
