### ISSUE TITLE
Dependency check tool doesn't handle v2 modules

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#18350]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1629059&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0

`
github.com/Azure/azure-sdk-for-go/sdk/depcheck imports
	github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/communication/armcommunication/v2: module github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/communication/armcommunication@latest found (v1.0.0), but does not contain package github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/communication/armcommunication/v2
`

**Comment by tadelesh** [comment]
I reran the pipeline and came with a sucess. It is a little tricky here. After we merge the v2 release code into main, we need wait for the release ci and approve for release, and then we can have tag and package can be indexed by `pkg.go.dev`. During the time before tag finished, there will be no v2 package can be get, so other ci which include this v2 source code will fail then. We will make this gap time as short as possible, but it seems some ci broken are unavoidable.

**Comment by tadelesh** [comment]
I changed the script to use `tag` to verify the version and fall back to use `replace` if race.
