### ISSUE TITLE
Feature request: Support for dns service

### ISSUE THREAD

**Issue by dhilton** [Azure/azure-sdk-for-go#184]
http://azure.microsoft.com/en-gb/documentation/services/dns/

We'd like to be able to manage DNS entries via Terraform (so that we can create for example an API endpoint) so that we can version control our infrastructure.

We understand that DNS is still in preview but assume that the API is pretty static by now?

Again if you'd accept a PR, happy to help do the work.

**Comment by ahmetalpbalkan** [comment]
@dhilton this is pretty much the same discussion as #183. We need to generate code for the DNS service as well and that's currently work in progress. We're planning to have some alpha bits soon. Will update this issue once that's the case.

**Comment by brendandixon** [comment]
@dhilton I commented on #183. See my thoughts there.

**Comment by garimakhulbe** [comment]
Old issue. DNS is in Azure Go SDK. Closing it.
