### ISSUE TITLE
Getting error on deployment of market place image

### ISSUE THREAD

**Issue by salmanbukhari** [Azure/azure-sdk-for-go#1840]
I am trying to deploy "SQL Server 2014 SP2 Enterprise on Windows Server 2012 R2" by Microsoft. There is no option to Enable Programmatically Deployment below the Create button so I assume that it will be enabled by default for this image. I got the SKU, OFFER, PUBLISHER, and VERSION  from the automation script. 

![file](https://user-images.githubusercontent.com/6597538/40132086-cd13b4dc-5909-11e8-8f88-cb87947ab502.PNG)

But when I try to deploy a VM using this image I get error .

> compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'Offer with PublisherId: MicrosoftSQLServer and OfferId: SQL2014SP2-WS2012R2 not found. If this offer has been created recently, please allow upto 30 minutes for this offer to be available for Purchase. If error persists, contact support.'"

> 

I added OFFER and PLAN structs in the VM. I was able to run it using portal. Can someone help me?

**Comment by jhendrixMSFT** [comment]
@jaredmoo is this something you can help with?

**Comment by salmanbukhari** [comment]
I was creating the VM in US East Virginia and yes I was able to create the VM using the portal.

**Comment by anilyela** [comment]
This doesn't seem like a valid location in public azure. Can you double-check if this is the exact name of the region you were using in Portal. We have a region 'USGov Virginia' but that is only availalbe on Azure US gov cloud.

**Comment by salmanbukhari** [comment]
I am sorry I meant eastus.

**Comment by jhendrixMSFT** [comment]
@salmanbukhari do you have a small repro that I can take a look at?

**Comment by tombuildsstuff** [comment]
after looking into this briefly today / to provide some additional context here: it appears this particular kind of VM [requires a VM Extension to be installed for the SQL Server aspects to be fully configured](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1325#issuecomment-393808762))

**Comment by salmanbukhari** [comment]
@tombuildsstuff  I know that but I was just thinking that if that is the case then the error should be different. I will try using these parameters as well. Thanks

**Comment by siddthota** [comment]
Are you using Disk size as 127GB minimum? and also Managed disk expects it to be 1023GB. 

In your case based on your error, I see your terraform is not able to recognize the image. I remember getting the same error earlier, but l again entered my subscription, service principal details and logged back onto Azure and it worked fine. I feel at times the caching can be an issue. Can you check how your plan looks like?

**Comment by siddthota** [comment]
@salmanbukhari Did it work for you?

**Comment by jhendrixMSFT** [comment]
Hello @salmanbukhari any update?

**Comment by siddthota** [comment]
@jhendrixMSFT Hi, I'm working on similar item, My Terraform script is spinning up the vm, but not the SQL Config options.

Please do let me know if I need to add anything to make it work - https://github.com/terraform-providers/terraform-provider-azurerm/issues/1325

Thanks!

**Comment by jhendrixMSFT** [comment]
Please reopen if this has not been resolved.
