### ISSUE TITLE
InterfacesClient.Get() returns nil for ipConfigurations[].publicIpAddress.ipAddress

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#18412]
https://github.com/Azure/azure-sdk-for-go/blob/ca4d22fbbacf9ddc32b42a14113b13ea3feb9ccd/services/network/mgmt/2021-08-01/network/interfacesgroup.go#L199

as the title says

**Comment by tadelesh** [comment]
@xqi-aviatrix Thanks for your feedback. Please note, the package `github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-08-01` has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Could you please upgrade to the new version first and feel free to feedback if any further problem?

**Comment by xqi-aviatrix** [comment]
Thanks for the upgrade notification.

I have upgrade my code to use the new version of package. But I still face the problem that the PublicIpAddress in the returned NetworkInterce is nil.  I think I should use expand field to make it non-nill. Is there any example I can follow about how to use the Expand field?

niClient, err := armnetwork.NewInterfacesClient(currentSubscription, cred, nil)
                    if err != nil {
                        log.Fatalf("network interface client creation failed %s", err)
                        return
                    }

                    stringSlices := strings.Split(*event.ResourceID, "/")
                    niId := stringSlices[len(stringSlices)-1]
                    expand := "publicipaddress"
                    networkInterface, err := niClient.Get(ctx, *event.ResourceGroupName, niId, &armnetwork.InterfacesClientGetOptions{Expand: &expand})
                    if err != nil {
                        log.Fatalf("network interface retrival failed %s", err)
                        return
                    }


From: Chenjie Shi ***@***.***>
Date: Tuesday, June 14, 2022 at 9:22 PM
To: Azure/azure-sdk-for-go ***@***.***>
Cc: Xin Qi ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-sdk-for-go] InterfacesClient.Get() returns nil for ipConfigurations[].publicIpAddress.ipAddress (Issue #18412)

@xqi-aviatrix<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxqi-aviatrix&data=05%7C01%7Cxqi%40aviatrix.com%7C3b8ef3e42f1c4634423808da4e86a956%7C4780055ece374f02b33dfdad8493a4b6%7C0%7C0%7C637908637523607933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FaRcWGBZHW0usTSVkkCurl2u69lfOvJf028ctSIi5qw%3D&reserved=0> Thanks for your feedback. Please note, the package github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-08-01 has been deprecated. A replacement package is available github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkg.go.dev%2Fgithub.com%2FAzure%2Fazure-sdk-for-go%2Fsdk%2Fresourcemanager%2Fnetwork%2Farmnetwork&data=05%7C01%7Cxqi%40aviatrix.com%7C3b8ef3e42f1c4634423808da4e86a956%7C4780055ece374f02b33dfdad8493a4b6%7C0%7C0%7C637908637523607933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bqHR%2FWK%2BI%2Bf%2BaWSbuS38qfSCgpfAf6Fe3eSZKsn60t4%3D&reserved=0>. See Migration Guide<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fgolang%2Ft2%2Fmigration&data=05%7C01%7Cxqi%40aviatrix.com%7C3b8ef3e42f1c4634423808da4e86a956%7C4780055ece374f02b33dfdad8493a4b6%7C0%7C0%7C637908637523607933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=74lWWOjkVdrq0qvF20eS7nxAvJK%2FS%2FC8WYToPkV09MU%3D&reserved=0> for guidance on upgrading. Could you please upgrade to the new version first and feel free to feedback if any further problem?

**Comment by xqi-aviatrix** [comment]
I find some hint in this page https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources#section-readme and figure out the solution below

					networkInterface, err := niClient.Get(ctx, *event.ResourceGroupName, niName, &armnetwork.InterfacesClientGetOptions{Expand: to.Ptr("IPConfigurations/PublicIPAddress")})
