### ISSUE TITLE
ActivityLogsClient's List function does not return 400 with invalid selectParameter

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#18411]
https://github.com/Azure/azure-sdk-for-go/blob/ca4d22fbbacf9ddc32b42a14113b13ea3feb9ccd/services/preview/monitor/mgmt/2021-09-01-preview/insights/activitylogs.go#L53

The function returns normally with the following inputs
eventsCollection, err := alClient.List(context.Background(),
		"eventTimestamp ge '2022-06-14T00:00:00.6407898Z' and eventTimestamp le '2022-06-14T23:59:59.6407898Z'",
		"eventTimestamp,eventName,operationName,category,description")

But if I change the "description" to "descriptionn", the function call hangs there forever even without returning a 400 indication bad input select parameter.
eventsCollection, err := alClient.List(context.Background(),
		"eventTimestamp ge '2022-06-14T00:00:00.6407898Z' and eventTimestamp le '2022-06-14T23:59:59.6407898Z'",
		"eventTimestamp,eventName,operationName,category,descriptionn")

**Comment by tadelesh** [comment]
@xqi-aviatrix Thanks for your feedback. Please note, the package `github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2021-09-01-preview` has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Could you please upgrade to the new version first and feel free to feedback if any further problem?
