### ISSUE TITLE
aztables incorrectly disallows empty rowkey resulting in unreadable data

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-sdk-for-go#18424]
### Bug Report

- SDK version: `github.com/Azure/azure-sdk-for-go/sdk/data/aztables@v1.0.0`
- output of `go version`
`go version go1.18.3 darwin/arm64`

The `aztables` SDK and previous Azure Table Storage SDKs allow insertion of entities with empty row key - only a partition key is required. However, the `aztables` SDK (including v1.0.0) explicitly throws an error when performing a Get or Update requests on entities with empty row key. This is a breaking change from the previous SDK and renders data written with the previous SDK not readable. Furthermore, this is inconsistent with this SDK itself as it is still possible to create entities with empty row key values.

Here is what the old SDK did in the Get path:
https://github.com/Azure/azure-sdk-for-go/blob/1cdb007c833eea301e1866a02e5e6d41240f3ec4/storage/entity.go#L226

And here is what the new "Track 2" SDK is doing which is incorrect:
https://github.com/Azure/azure-sdk-for-go/blob/1cdb007c833eea301e1866a02e5e6d41240f3ec4/sdk/data/aztables/internal/table_client.go#L727

**Comment by jhendrixMSFT** [comment]
Fix will roll out in `aztables@v1.01.`

**Comment by berndverst** [comment]
Thanks for the quick turnaround @jhendrixMSFT
