### ISSUE TITLE
Create and update static web app

### ISSUE THREAD

**Issue by ng-druid** [Azure/azure-sdk-for-go#18423]
Hello,

I didn’t see anything that makes it possible to create or update a static web app using this sdk. Is that something that has been discussed.

Thanks

**Comment by navba-MSFT** [comment]
@ng-druid Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ng-druid Did you try the sample code present [here](https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/main/sdk/resourcemanager/appservice/staticsite) ? Awaiting your reply.

**Comment by ng-druid** [comment]
@navba-MSFT The sample you provided appears to be exactly what I was looking for. Thanks
