### ISSUE TITLE
StageBlockFromURL() fails when copying within the same account with SharedKeyCredential

### ISSUE THREAD

**Issue by yonsken** [Azure/azure-sdk-for-go#18426]
### Package imports
```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.0.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.0.0
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.4.1
```
### Go version
`go version go1.18 linux/amd64`

### Describe the bug
I am using (*azblob.BlockBlobClient).StageBlockFromURL to copy blobs within the same container. It works as expected when I use Service Principal credentials (azidentity.NewEnvironmentCredential) but fails when I use shared key credentials (azblob.SharedKeyCredential) to create the service client. Specifically, the error that I am getting is:
```
 ===== RESPONSE ERROR (ErrorCode=CannotVerifyCopySource) ===== 
Description=Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
```
I have the Storage Blob Data Owner role on the account.

### Expected behaviour
Block copy succeeds the way it does when I'm using Service Principal to authenticate.

### Actual behavior
I receive an SDK error with 401 response.

### Additional context
This seems to be very similar to [this issue reported for the .NET SDK in March](https://github.com/Azure/azure-sdk-for-net/issues/27358), however in that ticket the person was having issues with copying blobs across different accounts, while I am getting the same error when copying within the same one, which should work with shared key credentials:

> A source blob in the same storage account can be authorized via Shared Key. However, if the source is a blob in another account, the source blob must either be public or must be authorized via a shared access signature. If the source blob is public, no authorization is required to perform the copy operation.

### Environment
Running locally on Ubuntu 20.04 LTS.

**Comment by navba-MSFT** [comment]
@yonsken Could you please share the failing Server request id here ? while reproducing the issue with SharedKeyCredential. Awaiting your reply.

**Comment by yonsken** [comment]
@navba-MSFT Of course, 
`2cf1f042-101e-004f-18a0-8596bd000000`

Additional if required:
`87afe93c-001e-0021-5aa0-85c392000000`
`696759b0-101e-005f-12a1-8553d5000000`

**Comment by navba-MSFT** [comment]
@yonsken Apologies for the late reply. Thanks for getting back. I am looking into this. I will provide an update soon.

**Comment by navba-MSFT** [comment]
@yonsken I looked at the backend logs for the above failing request ID. Please follow the below 2 actions plans and let me know if that helps:

**Plan 1:**
Could you please change the access level of your container "cXXXs0" to `public` and test again?
>The value should be URL-encoded as it would appear in a request URI. The source blob must either be **public** or must be authorized via a shared access signature. If the source blob is **public**, no authorization is required to perform the operation.

More Info [here](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url).


**Plan 2:**
If the above Plan 1 doesn't help, then Could you please try with the test case sample from [here](https://github.com/Azure/azure-sdk-for-go/blob/f242365bc5fff8417eb32dbaaead37cb63b63122/sdk/storage/azblob/zt_block_blob_client_test.go#L103) and check if you see the same issue ?

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yonsken I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  had a chance to try the above suggestions. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yonsken Please let me know if you have any update on this. Awaiting your reply.

**Comment by yonsken** [comment]
@navba-MSFT Sorry for a delayed response, the Plan 1 worked. To be clear, I was aware of this solution but it doesn't work for my application since blobs being private is a security requirement. 

I have a few questions:
1. Is there a way to make this request succeed with a service client that was created with shared key credentials without making the container public?
2.  Is it expected that the same request succeeds with a service client that was created with service principal credentials?

**Comment by navba-MSFT** [comment]
@yonsken Thanks for getting back. Please find below the answers inline to your questions.

>Is there a way to make this request succeed with a service client that was created with shared key credentials without making the container public?
Yes it is possible. See the Plan 2 mentioned [above](https://github.com/Azure/azure-sdk-for-go/issues/18426#issuecomment-1162899397). You can use the test case sample from [here](https://github.com/Azure/azure-sdk-for-go/blob/f242365bc5fff8417eb32dbaaead37cb63b63122/sdk/storage/azblob/zt_block_blob_client_test.go#L103) and check if you see the same issue ?

>Is it expected that the same request succeeds with a service client that was created with service principal credentials?
AFAIK, it should be possible, but ensure that the SP has [Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#contributor) and [Storage Blob Data Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) permissions assigned on your storage account and test.

**Comment by navba-MSFT** [comment]
@yonsken I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  had a chance to follow the above suggestion. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yonsken The action is currently pending on you to follow the above plan and provide an update. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
