### ISSUE TITLE
Ability to create private cluster in AKS

### ISSUE THREAD

**Issue by Kronos11** [Azure/azure-sdk-for-go#18428]
### Service Package Request
Our team needs the ability to create [private AKS Clusters](https://docs.microsoft.com/en-us/azure/aks/private-clusters) using the go SDK so that it can be used in the [crossplane-azure provider](https://github.com/crossplane-contrib/provider-azure)

After this feature is added, it can be implemented in the crossplane azure provider to close [#235](https://github.com/crossplane-contrib/provider-azure/issues/235)

**Comment by jhendrixMSFT** [comment]
Looks like the `az` command for this is implemented [here](https://github.com/Azure/azure-cli/blob/a1b418c083cd7f671757ff32e4350e983192eedb/src/azure-cli/azure/cli/command_modules/acs/custom.py#L1473).  I didn't yet untangle which SDKs/APIs are involved.

**Comment by lirenhe** [comment]
@tadelesh, could you follow up on this?  Thanks

**Comment by tadelesh** [comment]
@Kronos11 Could you try `ManagedClustersClient` in `armcontainerserver` package [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice#ManagedClustersClient)?

**Comment by Kronos11** [comment]
> @Kronos11 Could you try `ManagedClustersClient` in `armcontainerserver` package [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice#ManagedClustersClient)?

I do see it available as an option,I am working on a PR for crossplane to get this added. It was a little difficult to find, but after changing the version of the api to 2019-11-01 I was able to see this option.

Created PR in crossplane: https://github.com/crossplane-contrib/provider-azure/pull/343

**Comment by lirenhe** [comment]
cc @xboxeer
