### ISSUE TITLE
[sqlvirtualmachine] API http GET on sqlvirtualmachine returns wrong state of storageConfigurationSettings

### ISSUE THREAD

**Issue by eissko** [Azure/azure-sdk-for-go#18434]
### Bug Report

- import path of package in question, e.g. `services\preview\sqlvirtualmachine\mgmt\2021-11-01-preview\sqlvirtualmachine\`
- SDK version e.g. `latest`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`: Go runtime version: go1.18.1 (terraform 1.2.1)

- What happened?
on this GET:
```
GET /subscriptions/***/resourceGroups/***/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/vmname?%24expand=%2A&api-version=2021-11-01-preview HTTP/1.1
```
we got HTTTP response:
```json
   ** simplified response to only attribute of interest **
        "storageConfigurationSettings": {
            "sqlDataSettings": {
                "luns": [
                    4
                ]
            },
            "sqlLogSettings": {},
            "sqlTempDbSettings": {},
            "diskConfigurationType": "EXTEND"
        },
```

- What did you expect or want to happen?
I expect to get response of current state of storageConfigurationSettings of sql virtual machine like so:

```json
   ** simplified response to only attribute of interest **
        "storageConfigurationSettings": {
            "sqlDataSettings": {
                "luns": [
                    1, 4
                ],
                "defaultFilePath" : "F:\\Data"
            },
            "sqlLogSettings": {
                "luns": [
                    3
                ],
                "defaultFilePath" : "G:\\Logs"
             },
            "sqlTempDbSettings": {
              "luns": [],
                "defaultFilePath" : "D:\\Temp\\Data\\tempdb.mdf"
             }
        },
```

- How can we reproduce it?
1, Deploy sql vm with "data drive" having disk as lun 1, then "log drive" having disk as LUN 3 and "temp drive" to temporary D: drive.
2, expand the "data drive" via azure portal with another disk/lun 4
3, make a GET request

- Anything we should know about your environment.
Yes. This is related to issue reported here:
 - https://github.com/hashicorp/terraform-provider-azurerm/issues/13356
 - https://github.com/hashicorp/terraform-provider-azurerm/issues/10054
 - https://github.com/Azure/azure-sdk-for-go/pull/17185

Thanks! @Alancere

**Comment by eissko** [comment]
For me it does not look like response to "sqlvirtualmachine" state but rather the state of SQL IAAS extension which only keeps the state of last operation executed but never the current state for sql virtual machine:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/18594305/174307881-5c5512c2-4873-498a-a9ad-f63a8d458606.png">

**Comment by eissko** [comment]
your response should most likely fit more to "sqlStorageUpdateSettings" not "storageConfigurationSettings" like depcited below:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/18594305/174313287-f3fb1b1b-05bc-41b0-92a0-1f171c8a02e8.png">

**Comment by eissko** [comment]
so as summary to this case. to mentioned GET I expect this response:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/18594305/174320423-b9d735b5-264c-4fc5-8a7b-0555a08e93a7.png">

if this is fixed, also azure provider can be fixed #13356

**Comment by eissko** [comment]
@RickWinter btw, this looks like API problem because I did test out of the SDK GO and it behaves this buggy way on pure API via https://docs.microsoft.com/en-us/rest/api/sqlvm/2021-11-01-preview/sql-virtual-machines/get. I opened the issue on https://github.com/Azure/azure-rest-api-specs/issues/19517. I hope this right place. 

Peter

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

@azureSQLGitHub Could you please look into this issue and provide an update ? Awaiting your reply.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
