### ISSUE TITLE
App Insights WebTestDefinition Missing Request and ValidationRules Structs

### ISSUE THREAD

**Issue by nerddtvg** [Azure/azure-sdk-for-go#18435]
Starting in REST API version 2018-05-01-preview, there was the addition of a `Standard` `kind` which required `Request` and `ValidationRules` structs and an optional `Configuration` field. This was also included in the 2020-10-05-preview version. Unfortunately the REST documentation itself is missing this information, but it is available in the ARM/Bicep docs. Can this be added into the Go SDK to match?

https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2018-05-01-preview/webtests?tabs=bicep

https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2020-10-05-preview/webtests?tabs=bicep

https://github.com/Azure/azure-sdk-for-go/blob/37b3dad150daade2fffb91063403989ddfded6d9/services/preview/appinsights/mgmt/2022-02-01-preview/insights/models.go#L2334-L2357

**Comment by tadelesh** [comment]
@nerddtvg Thank you for the feedback. Please note, the package `github.com/Azure/azure-sdk-for-go/services/preview/appinsights/mgmt/2022-02-01-preview/insights` has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/applicationinsights/armapplicationinsights](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/applicationinsights/armapplicationinsights). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Could you please upgrade to the new version first and feel free to feedback if any further problem?
