### ISSUE TITLE
Security: armsecurity.AlertsClient to allow filtering when requesting alerts?

### ISSUE THREAD

**Issue by mrozitron** [Azure/azure-sdk-for-go#18439]
Hi!  When paging over security alerts for a given subscription or resource group, is there a way to only request alerts that are, for example active, or have arrived since a given timestamp, etc?

Thanks!

**Comment by PramodValavala-MSFT** [comment]
@mrozitron The SDK uses the [Alerts - List REST API](https://docs.microsoft.com/en-us/rest/api/securitycenter/alerts/list) under the hood, which doesn't support any filtering of any kind.

You will have to filter them in your code. Feel free to raise a feature request for it over [here](https://feedback.azure.com/d365community/forum/45d643ce-2025-ec11-b6e6-000d3a4f0f84).

**Comment by mrozitron** [comment]
Done: https://feedback.azure.com/d365community/idea/2e59c3d0-fbf2-ec11-a81b-6045bd796569
