### ISSUE TITLE
List function results do not match the CLI

### ISSUE THREAD

**Issue by lmejbar** [Azure/azure-sdk-for-go#18445]
### Bug Report

- github.com/Azure/azure-sdk-for-go/sdk/azcore v1.0.0
- github.com/Azure/azure-sdk-for-go/sdk/internal v1.0.0 // indirect
- github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources v1.0.0
- github.com/AzureAD/microsoft-authentication-library-for-go v0.5.1 // indirect
- output of `go version` go 1.18

- What happened?
1. When I use the CLI and call `az vm list  --subscription xxxxxxxxx`, a list of VM is returned.
2. Using the Azure SDK, with the same tenant, client and secret. It's not working.

- How can we reproduce it?

```
package main

// Import key modules.
import (
	"context"
	"log"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	armresources "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

var (
	subscriptionId = "xxxxxxxxxxxxx"
)

func main() {
	tenantId := "xxxxxxxx"
	clientId := "xxxxxxxx"
	clientSecret := "xxxxxxx"

	opts := azidentity.ClientSecretCredentialOptions{}
	opts.Cloud = cloud.AzureChina
	cred, err := azidentity.NewClientSecretCredential(tenantId, clientId, clientSecret, &opts)
	if err != nil {
		log.Printf("Error creating credential: %v\n", err)
	}

	client, err := armresources.NewClient(subscriptionId, cred, nil)
	if err != nil {
		log.Printf("Error creating client: %v\n", err)
	}

	pager := client.NewListPager(nil)
	for pager.More() {
		var rawResponse *http.Response
		ctx := context.Background()
		ctxWithResp := runtime.WithCaptureResponse(ctx, &rawResponse)
		page, err := pager.NextPage(ctxWithResp)
		if err != nil {
			log.Printf("Error getting next page: %v\n", err)
		}

		for _, item := range page.Value {
			log.Println(*item.ID)
		}
	}
}
```

The output is : 

`The resource principal named https://management.core.windows.net/ was not found in the tenant named xxxxxxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.`

But with the same Client ID, Tenant ID and Secret i can list with the cmd az cli. Do you have any suggestions ? 
Thank you !

**Comment by jhendrixMSFT** [comment]
When creating the client, you need to use the same cloud configuration as the credential (it defaults to `cloud.AzurePublic`).
```go
armresources.NewClient(subscriptionId, cred, &arm.ClientOptions{
	ClientOptions: azcore.ClientOptions{
		Cloud: &opts,
	}
})
```

**Comment by lmejbar** [comment]
@jhendrixMSFT 
Hello Joel, 
Thank you for your answer, it's working. Do you have any recommandations to get additional information about compute services.
I'm using :

```
	client, err := armresources.NewClient(account, cred, &options)
	if err != nil {
		log.Printf("Error creating client: %v\n", err)
	}

	pager := client.NewListPager(nil)
```

Location, Tags, ID, Name, Type are provided is it possible to get the kind of information such as: 
VmType: Standard_D2s_v3
InstanceState: VM running
MemoryDisk: 64
OsVersion:
PrivateIPAddress: 10.70.96.36
PublicIPAddress:

**Comment by jhendrixMSFT** [comment]
You'll want to use the `armcompute` module for compute-specific needs.

```
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute
```

We have a handful of [samples](https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/main/sdk/resourcemanager/compute) too which you might find useful.

**Comment by lmejbar** [comment]
Thank you @jhendrixMSFT

**Comment by SandraGiacco** [comment]
Hi @jhendrixMSFT, I'm using the armcompute module and the armcompute.NewVirtualMachinesClient() function and it works great. However, I would like to know how I could retrieve the public and the private IPs. I was wondering whether I could use the armnetwork module and the IPConfigurationPropertiesFormat, but I'm not sure how to proceed to do so. 

Do you have any example, or at least an explanation (even a workaround). I am looking for a function to get VM IP addresses. (I am only able to find create / update IP function in the documentation...)

Please let me know if the armnetwork module is the correct one to intend to get the IP addresses.

Thanks in advance.

Sandra 
(Btw I am @lmejbar colleague 😉)
