### ISSUE TITLE
Add Log analytics query execution API support

### ISSUE THREAD

**Issue by Rohitrajak1807** [Azure/azure-sdk-for-go#18443]
### Feature Request

Currently working on a project that requires us to track resource usage on an ACI virtual node within an AKS cluster. Log analytics workspaces allows us to execute KQL queries to get the usage, but we require programmatic access to this feature.

**Comment by jhendrixMSFT** [comment]
The data-plane spec for this is https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/v1/OperationalInsights.json

**Comment by mblaschke** [comment]
Is there any ETA for this feature? Would be good to know when this API can be expected in the new SDK.

**Comment by Rohitrajak1807** [comment]
> Is there any ETA for this feature? Would be good to know when this API can be expected in the new SDK.

Well, it'd be great to get it ASAP. I don't have a particular ETA. For now, we're using this feature by making a plain HTTP request to Query Execute endpoint.(I works, but still looks hacky)

**Comment by franckbleyer1** [comment]
Le lun. 18 juil. 2022 à 10:24 AM, Rohit Rajak ***@***.***> a
écrit :

**Comment by mblaschke** [comment]
@Rohitrajak1807
want to share the code? is there any good way to use the new azure-sdk to send requests?

**Comment by Rohitrajak1807** [comment]
> @Rohitrajak1807 want to share the code? is there any good way to use the new azure-sdk to send requests?

https://gist.github.com/Rohitrajak1807/b1605d8ec8dc0fb8a58faa1e14ed9943
This is a working example.

**Comment by mblaschke** [comment]
any progress here?
the old sdk is deprecated and there is no replacement currently.

**Comment by jhendrixMSFT** [comment]
Please take a look at the [`azquery`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery)` module as it contains some of this functionality (and other).

**Comment by Rohitrajak1807** [comment]
> Please take a look at the [`azquery`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery) module as it contains some of this functionality (and other).

Thank you @jhendrixMSFT will check it out.

**Comment by RickWinter** [comment]
@Rohitrajak1807 can you confirm you were successful with the azquery package.

**Comment by Rohitrajak1807** [comment]
> @Rohitrajak1807 can you confirm you were successful with the azquery package.

I'll need some time. The project that required this feature is no longer being developed (it was a fast to fail product). I'll create a setup manually and go through the steps

**Comment by gracewilcox** [comment]
Hi @Rohitrajak1807! I assume your use of the azquery module was successful since you released [your module](https://pkg.go.dev/github.com/webdevops/azure-loganalytics-exporter) with azquery as a dependency. The azquery module is [officially GA this week](https://devblogs.microsoft.com/azure-sdk/announcing-the-stable-release-of-the-azure-monitor-query-client-module-for-go/). We hope azquery addresses your needs and would love to hear any feedback you have.
