### ISSUE TITLE
Messages failing to send

### ISSUE THREAD

**Issue by dibrinsofor** [Azure/azure-sdk-for-go#18467]
### Bug Report

- import path `.../sdk/messaging/azservicebus`
- SDK version`latest`
- go-version `1.18`

Setup azure app service to send messages to a queue using
```go
func SendMessage(message string) {
	client := GetClient()
	sender, err := client.NewSender("mlsa3", nil)
	if err != nil {
		panic(err)
	}
	// defer sender.Close(context.TODO())

	sbMessage := &azservicebus.Message{
		Body: []byte(message),
	}
	err = sender.SendMessage(context.TODO(), sbMessage, nil)
	if err != nil {
		panic(err)
	}
}
```
on the azure portal, it reflects that requests are coming through but is not registering the messages. I have tried to lookup logs but cannot pinpoint where the problem is coming from. the queue name is accurate, and I am generating the client with an accurate uri `<queue_name>.servicebus.windows.net`

**Comment by richardpark-msft** [comment]
Hi @dibrinsofor,

Let's try a few things, see if we can flush this bug out of hiding. :)

First, can you turn on debug logging for the package? This'll give us a bit more information about what's happening internally, and might give us the context we need to see where the failure is.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/README.md#logging

This should give us enough information to see if there is a bug on the sending side.

Here are a few other things that are worth looking into:

* Is it possible your messages are being received by a receiver before you see them in the portal?
* Does your queue have auto-forwarding setup?
* Are there any messages in your dead letter queue for your queue?
