### ISSUE TITLE
Additional retry logic for 410 response 

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#1848]
There’s an additional retry logic that needs to be added to SDKs. This one is due to wireserver upgrades that happen once a month. Wireserver sits between the VM and IMDS service. 
During the time of wireserver upgrade, token requests timeout with a 410 error code. The 90% percentile for the upgrade/restart is 2-3 minutes.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.9.1
