### ISSUE TITLE
Add support for postgres 14 flexible server 

### ISSUE THREAD

**Issue by m-rcl** [Azure/azure-sdk-for-go#18506]
### Feature Request

Azure is offering [postgres 14](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions) flexible server but the sdk is currently limited to Versions 11 12 and 13.

https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v1.0.0/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/zz_generated_constants.go#L263

**Comment by lirenhe** [comment]
@tadelesh, this seems to be a service ask, could you follow up with the service team? Thanks

**Comment by navba-MSFT** [comment]
@m-rcl Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by ArcturusZhang** [comment]
Hi @m-rcl we will update the SDK once the swagger update is merged. And for your information, to workaround this, you do not have to wait for us to update the SDK, you could still send the corresponding value in this way:
```
version := ServerVersion("14")
```

**Comment by navba-MSFT** [comment]
@m-rcl I wanted to do quick follow-up to check if you had a chance to look at the above comment and try the suggestion of using version using `version := ServerVersion("14")`. Please let us know if you are still facing this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@m-rcl Thanks for getting back. I see that there is a pending PR with terraform already. see https://github.com/hashicorp/terraform-provider-azurerm/pull/17517

**Comment by m-rcl** [comment]
@navba-MSFT  thanks for the hint! I didn't realize the PR was opened for Terraform!

**Comment by navba-MSFT** [comment]
@m-rcl You're welcome. You could also follow-up on this PR https://github.com/hashicorp/terraform-provider-azurerm/pull/17517 to check the ETA for the release.
