### ISSUE TITLE
Successfully Authenticate AzureChina with an Azure Public Credential

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#18508]
https://github.com/Azure/azure-sdk-for-go/blob/e1d15b65278a1c714f2dd1349fa4098d72d0fe7b/sdk/azidentity/client_secret_credential.go#L33

I try to authenticate Azure_China with an Azure_Public credential. I expect authentication errors returned, but no error returns and authentication succeeded as if the authentication endpoint was Azure_Public

![Screen Shot 2022-06-30 at 4 43 33 PM](https://user-images.githubusercontent.com/89810801/176796590-c2f32f59-ccfb-4e4b-9bc7-3b6d9fed180a.png)

**Comment by chlowell** [comment]
Authentication happens in the credential's `GetToken` method, not its constructor, so you won't see an error in a case like this until the first `GetToken` call. I don't see anything in your screenshot that would call `GetToken`. Does your program work when you add this?
```go
import "github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"

// normally you don't need to think about this, because
// Azure SDK clients call GetToken automatically as needed
tokenOptions := policy.TokenRequestOptions{
    Scopes: []string{"https://management.core.chinacloudapi.cn//.default",
}
tk, err := cred.GetToken(ctx, tokenOptions)
if err != nil {
    // client IDs and secrets are validated by Azure AD.
    // If they're incorrect, you'll land here.
}
```

**Comment by xqi-aviatrix** [comment]
Thanks for the quick reply. Yes, after adding the code above, I got the error stating the application cannot be found

However, In my original code I could use the new created `cred` to create a client like below and then read resource under Azure public with the client, althought the credential is created with Azure China option.    

      `credential_options := &azidentity.ClientSecretCredentialOptions{ClientOptions: policy.ClientOptions{Cloud: cloud.AzureChina}}
	cred, err := azidentity.NewClientSecretCredential(
		tenant_id_auzre_public,
		client_id_auzre_public,
		client_secret_auzre_public,
		credential_options)
	if err != nil {
		log.Fatalf("Authentication Failure: %#v", err)
		return
	}
	ctx := context.Background()
        alClient, err := armmonitor.NewActivityLogsClient(currentSubscription, cred, nil)
	if err != nil {
		log.Fatalf("activity log client creation failed %s", err)
		return
	}`

**Comment by chlowell** [comment]
Clients are similar to credentials in that they don't attempt to authenticate until necessary. You won't get an error about your invalid service principal configuration until you call a method that sends a request to the service (methods that do this have a `Context` parameter).

**Comment by xqi-aviatrix** [comment]
I also try the method that have Context parameter from the client created with this problematic `cred`. It returns Azure Public resource without returning error
is it the same method with Context parameter as you mentioned?

`//eventTimestamp le '2022-06-15T23:59:59.6407898Z' and
	var selectFilter string = "eventTimestamp,operationName,resourceId,resourceType,resourceGroupName,status,level,category"
	eventsCollectionPager := alClient.NewListPager("eventTimestamp ge 2022-06-27T00:00:00.6407898Z",
		&armmonitor.ActivityLogsClientListOptions{Select: &selectFilter})

	totalEventCnt := 0
	eventListStack := make([]*armmonitor.ActivityLogsClientListResponse, 0)

	for eventsCollectionPager.More() {
		eventList, err := eventsCollectionPager.NextPage(ctx)
		if err != nil {
			log.Fatalf("activity log event next page failed %s", err)
		}
		eventListStack = append(eventListStack, &eventList)
	}`

**Comment by xqi-aviatrix** [comment]
I also try VirualMachinesClient which has method with Context parameter directly. The same behavior without error returned


`vmClient, err := armcompute.NewVirtualMachinesClient(currentSubscription, cred, nil)
	if err != nil {
		log.Fatalf("virtual machine client creation failed %s", err)
		return
	}

	statusOnly := "true"
	var instanceViewExpand armcompute.InstanceViewTypes = "instanceView"
	pager := vmClient.NewListAllPager(&armcompute.VirtualMachinesClientListAllOptions{StatusOnly: &statusOnly})
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, vm := range nextResult.Value {
			// log.Println(*vm.ID)
			stringSlice := strings.Split(*vm.ID, "/")
			instanceView, err := vmClient.Get(ctx,
				stringSlice[4],
				*vm.Name,
				&armcompute.VirtualMachinesClientGetOptions{Expand: &instanceViewExpand})
			if err != nil {
				log.Fatalf("failed to get vm: %v", err)
			}vmClient, err := armcompute.NewVirtualMachinesClient(currentSubscription, cred, nil)
	if err != nil {
		log.Fatalf("virtual machine client creation failed %s", err)
		return
	}

	statusOnly := "true"
	var instanceViewExpand armcompute.InstanceViewTypes = "instanceView"
	pager := vmClient.NewListAllPager(&armcompute.VirtualMachinesClientListAllOptions{StatusOnly: &statusOnly})
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, vm := range nextResult.Value {
			// log.Println(*vm.ID)
			stringSlice := strings.Split(*vm.ID, "/")
			instanceView, err := vmClient.Get(ctx,
				stringSlice[4],
				*vm.Name,
				&armcompute.VirtualMachinesClientGetOptions{Expand: &instanceViewExpand})
			if err != nil {
				log.Fatalf("failed to get vm: %v", err)
			}
}
}`

**Comment by chlowell** [comment]
> I also try VirualMachinesClient which has method with Context parameter directly (e.g vmClient.Get). The same behavior that Azure public resources returned but not error returned
> 

Sounds like you have the credential and client configured for the public cloud (which is the default). Can you share more of the code you're running, showing credential and client construction?

**Comment by xqi-aviatrix** [comment]
Hi, here are most of my sample code without credential details. currentSubscription is subscription under an Azure Public tenant

`credential_options := &azidentity.ClientSecretCredentialOptions{ClientOptions: policy.ClientOptions{Cloud: cloud.AzureChina}}
	cred, err := azidentity.NewClientSecretCredential(
		tenant_id_auzre_public,
		client_id_auzre_public,
		client_secret_auzre_public,
		credential_options)
	if err != nil {
		log.Fatalf("Authentication Failure: %#v", err)
		return
	}
	ctx := context.Background()


	vmClient, err := armcompute.NewVirtualMachinesClient(currentSubscription, cred, nil)
	if err != nil {
		log.Fatalf("virtual machine client creation failed %s", err)
		return
	}

	statusOnly := "true"
	var instanceViewExpand armcompute.InstanceViewTypes = "instanceView"
	pager := vmClient.NewListAllPager(&armcompute.VirtualMachinesClientListAllOptions{StatusOnly: &statusOnly})
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, vm := range nextResult.Value {
			// log.Println(*vm.ID)
			stringSlice := strings.Split(*vm.ID, "/")
			instanceView, err := vmClient.Get(ctx,
				stringSlice[4],
				*vm.Name,
				&armcompute.VirtualMachinesClientGetOptions{Expand: &instanceViewExpand})
			if err != nil {
				log.Fatalf("failed to get vm: %v", err)
			}
			log.Printf("VM ID is %s", *instanceView.ID)
			log.Printf("VM Name is %s", *instanceView.Name)
			log.Printf("VM status: %s", *instanceView.Properties.InstanceView.Statuses[1].DisplayStatus)
			log.Printf("VM image info: %s", *instanceView.Properties.InstanceView.OSName+*instanceView.Properties.InstanceView.OSVersion)
			log.Printf("region: %s", *instanceView.Location)
			log.Printf("tags: %d", len(instanceView.Tags))

		}
	}

	alClient, err := armmonitor.NewActivityLogsClient(currentSubscription, cred, nil)
	if err != nil {
		log.Fatalf("activity log client creation failed %s", err)
		return
	}
	//eventTimestamp le '2022-06-15T23:59:59.6407898Z' and
	var selectFilter string = "eventTimestamp,operationName,resourceId,resourceType,resourceGroupName,status,level,category"
	eventsCollectionPager := alClient.NewListPager("eventTimestamp ge 2022-06-02T00:00:00.6407898Z",
		&armmonitor.ActivityLogsClientListOptions{Select: &selectFilter})

	totalEventCnt := 0
	eventListStack := make([]*armmonitor.ActivityLogsClientListResponse, 0)

	for eventsCollectionPager.More() {
		eventList, err := eventsCollectionPager.NextPage(ctx)
		if err != nil {
			log.Fatalf("activity log event next page failed %s", err)
		}
		eventListStack = append(eventListStack, &eventList)
	}

	for eventListIndex := len(eventListStack) - 1; eventListIndex >= 0; eventListIndex-- {
		eventsCollection := eventListStack[eventListIndex].Value
		if err != nil {
			log.Fatalf("activity log event next page failed %s", err)
			return
		}

		totalEventCnt = totalEventCnt + len(eventsCollection)
		for eventIndex := len(eventsCollection) - 1; eventIndex >= 0; eventIndex-- {
			event := eventsCollection[eventIndex]
			if event.ResourceType.Value != nil && *event.ResourceType.Value == "Microsoft.Network/networkSecurityGroups/securityRules" {
				if event.Status.Value != nil && *event.Status.Value == "Succeeded" {
					log.Printf("EventTime is %s, OperationName is %s, Resource Id is %s, Resource Type is %s, ResourceGroup is %s, Status is %s, Event ID is %s, severity level is %s, category %s",
						*event.EventTimestamp, *event.OperationName.Value, *event.ResourceID,
						*event.ResourceType.Value, *event.ResourceGroupName, *event.Status.Value,
						*event.ID, *event.Level, *event.Category.Value)

				}
			}
		}
		log.Printf("current event count is %d", len(eventsCollection))
	}

	log.Printf("total event count is %d", totalEventCnt)`

**Comment by xqi-aviatrix** [comment]
Thanks a lot for your investigation.
