### ISSUE TITLE
Add function for CosmosDB SDK to create client with connection string.

### ISSUE THREAD

**Issue by dmytrohridin** [Azure/azure-sdk-for-go#18520]
### Feature Request

Currently CosmosDB SKD does not support creating client from the connection string.
For .NET SDK this feature is present. Also, for example, servise bus go SDK support creating client from connection string.
It would be nice if CosmosDB SDK for Go also will support this

**Comment by dmytrohridin** [comment]
if there will no objections - I can try to add this one

**Comment by ealsur** [comment]
Sounds like a good idea, should be fairly easy to implement

**Comment by ealsur** [comment]
I don't see why not. It would require API reviews but I guess if the API name follows the Service Bus one, it should work.

**Comment by ealsur** [comment]
Will be included in the 0.3.2 release on the August 9th release train
