### ISSUE TITLE
Some services DELETE APIs cannot be called with GenericClient BeginDelete

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-go#18538]
### Bug Report

package: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/resources/armresources/zz_generated_client.go
sdk version: `master`/`latest`

I am using [GenericClient BeginDelete](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/resources/armresources/zz_generated_client.go#L287) to issue deletes for a bunch of resources including Event Hub Consumer Groups.

I have noticed though that I get a JSON deserialization error when deleting Event Hub Consumer groups. The actual error is
```
json: cannot unmarshal string into Go value of type ClientDeleteResponse
```

The reason for this error is that this API seems to return the string literal `""`. If you look at the implementation of the type-specific SDK, it never attempts to deserialize the response [see here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/eventhub/armeventhub/zz_generated_consumergroups_client.go#L135).

It feels like the async workflow + poller should be hardened for this case and allow me to successfully delete things via the async pattern?

Note that, this works for almost every resource I tried it for, so in some ways this could be an issue with eventhubs API, since what they are doing seems very strange...

**Comment by tadelesh** [comment]
@matthchr Thanks for your feedback. We do have some logic to handle such sync operation with poller. The error happens when we try to unmarshall the response to a response object. Commonly, the service should return an `{}` instead of `""` with no swagger response defined. Then SDK could unmarshall it to an empty response struct. @jhendrixMSFT What do you think?

**Comment by jhendrixMSFT** [comment]
If there's no response schema defined, then the service shouldn't return anything.  Is there a link to the swagger?

**Comment by tadelesh** [comment]
> If there's no response schema defined, then the service shouldn't return anything. Is there a link to the swagger?

@jhendrixMSFT Swagger is [here](https://github.com/Azure/azure-rest-api-specs/blob/2794e65131c037cb2bb19362582098db9bde3a56/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2021-11-01/consumergroups.json#L93). In `armeventhub` package, we will not unmarshall the response because no response schema defined, thus no error will happen. But for `armresource` package, the common deletion is an LRO which will fall back to `NonPoller` and the response unmarshall will fail.

**Comment by jhendrixMSFT** [comment]
Thanks for the links.  Given that the 200 response doesn't define a model, it really looks like a bug that they're returning anything.  Can you please follow up with the event hubs team about this?  Worse case we can harden against this, but I'd like to avoid that as I think their behavior is broken.

**Comment by matthchr** [comment]
Thanks @tadelesh for the investigation. Yes you have seen exactly what I was getting at. It's fine for their SDK because you never attempt to read the body, but in the generic client you do (via `NonPoller`).

@jhendrixMSFT did you want me to contact the eventhub team? Or @tadelesh? I don't have any contact on their team but I assume that you guys might? I do agree that this looks more like a service bug.

**Comment by jhendrixMSFT** [comment]
Sorry, that was meant for @tadelesh.

**Comment by tadelesh** [comment]
@matthchr @jhendrixMSFT I'll follow up with service team. @navba-MSFT Could you help to involve eventhub team?

**Comment by navba-MSFT** [comment]
@tadelesh Adding Service team to look into this.

**Comment by matthchr** [comment]
@tadelesh, @RickWinter -- can we get the service teams attention here? Haven't seen any acknowledgement they've seen this issue.

**Comment by tadelesh** [comment]
@kasun04 , @Saglodha Could you help to take a look?

**Comment by Saglodha** [comment]
@tadelesh , thanks for reaching out. Our team would investigate, and I would share updates soon.

**Comment by Saglodha** [comment]
Hi @matthchr , @tadelesh - Our team investigated and could confirm a reported bug for similar issue which was fixed. Could you please retry the operation and confirm if you're still facing the issue?
