### ISSUE TITLE
Is internal package publicly usable ?

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#18548]
https://github.com/Azure/azure-sdk-for-go/blob/dbfd8d07e92683015bd51568fa9991cff499b170/sdk/resourcemanager/internal/testutil/helper.go#L7

I am trying to write test cases for code using Azure Go SDK. This internal testutil package seems useful but I cannot import it locally. Is there any other tools from Azure SDK that I can use for developing test cases, specially about simulating the behavior of Azure SDK clients in large scale, like VirtualMachinesClient?

**Comment by lirenhe** [comment]
@tadelesh, could you take a look? thanks

**Comment by tadelesh** [comment]
@xqi-aviatrix, sorry for the delayed reply. Unfortunately, all the test utils we used for SDK in under internal packages which cannot be imported outside the package. Could you elaborate more about your requirements? I don't quite get the idea of simulating in large scale.

**Comment by xqi-aviatrix** [comment]
Thanks for the reply @tadelesh 

We want to make a test case that simulates, for example, a vm client fetched 10k vms from Azure.

I find the record playing functions in your internal package is useful in this case that I can put 10k vms info into a json and let the record playing function read those vms and consumes them as if they are read from azure backend by vm client.

**Comment by tadelesh** [comment]
> Thanks for the reply @tadelesh
> 
> We want to make a test case that simulates, for example, a vm client fetched 10k vms from Azure.
> 
> I find the record playing functions in your internal package is useful in this case that I can put 10k vms info into a json and let the record playing function read those vms and consumes them as if they are read from azure backend by vm client.

Got it. @jhendrixMSFT Is that possible we expose the recording related helper in `github.com/Azure/azure-sdk-for-go/sdk/internal/recording`?

**Comment by xqi-aviatrix** [comment]
Got it. thanks
