### ISSUE TITLE
InvalidResourceType when requesting quota usage list

### ISSUE THREAD

**Issue by erlisb** [Azure/azure-sdk-for-go#18567]
### Bug Report

- Module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/quota/armquota `v0.5.0`
- SDK version : `v65.0.0`
  - commit : 7393edcd0c85ff6a71dc7b30e28d48629bc69f6b
- go version `go1.18.3 linux/amd64`

- What happened?

A quota [NewUsagesClient ](https://github.com/Azure/azure-sdk-for-go/blob/a32e468782b79017ac47b9a3bf0383416f1df7a3/sdk/resourcemanager/quota/armquota/zz_generated_usages_client.go#L35)was created and the [NewListPager ](https://github.com/Azure/azure-sdk-for-go/blob/a32e468782b79017ac47b9a3bf0383416f1df7a3/sdk/resourcemanager/quota/armquota/zz_generated_usages_client.go#L119)method is called, which uses the [listCreateRequest ](https://github.com/Azure/azure-sdk-for-go/blob/a32e468782b79017ac47b9a3bf0383416f1df7a3/sdk/resourcemanager/quota/armquota/zz_generated_usages_client.go#L148) method. The following error is produced : 

```
2022/07/09 19:45:59 failed to advance page: GET https://management.azure.com/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/providers/Microsoft.Compute/locations/westeurope/providers/Microsoft.Quota/usages
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: InvalidResourceType
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'locations' could not be found in the namespace 'Microsoft.Compute' for api version '2021-03-15-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2020-12-01,2021-03-01,2021-04-01,2021-07-01,2021-11-01,2022-03-01'."
  }
}
--------------------------------------------------------------------------------
exit status 1

```

- What did you expect or want to happen?

Get a list of current usage for all resources for the scope specified, same as provided [here ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/quota/resource-manager/Microsoft.Quota/stable/2021-03-15/examples/getComputeUsages.json)

- How can we reproduce it?

Create an [NewUsagesClient ](https://github.com/Azure/azure-sdk-for-go/blob/a32e468782b79017ac47b9a3bf0383416f1df7a3/sdk/resourcemanager/quota/armquota/zz_generated_usages_client.go#L35)and call the [NewListPager ](https://github.com/Azure/azure-sdk-for-go/blob/a32e468782b79017ac47b9a3bf0383416f1df7a3/sdk/resourcemanager/quota/armquota/zz_generated_usages_client.go#L119)method : 

```
func getQuota(location, quotaName, limit string) {

	credentials, err := azidentity.NewClientSecretCredential(tenantId, clientId, clientSecret, nil)

	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()

	client, err := armquota.NewUsagesClient(credentials, nil)

	if err != nil {
		log.Fatal(err)
	}

	pager := client.NewListPager("subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/providers/Microsoft.Compute/locations/westeurope",
	nil)

		for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range nextResult.Value {
			// TODO: use page item
			_ = v
		}
	}
}
```

- Anything we should know about your environment.
  - Azure Public Cloud
  

Thank you,
Erlis

**Comment by lirenhe** [comment]
This seems to be a service issue.  @tadelesh, could you help to take a look?

**Comment by tadelesh** [comment]
@erlisb Thanks for your feedback. It seems the service use the wrong api-version for the resource query. I'll involve service team to have a look.

**Comment by navba-MSFT** [comment]
@erlisb Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@erlisb The QuotaRP is in private preview, and the Compute RP is not supported, only network RP is supported.

**Comment by navba-MSFT** [comment]
@erlisb The Compute RP will be supported for Quota API in a couple of weeks tentatively. Hope this helps.

**Comment by navba-MSFT** [comment]
@erlisb I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by erlisb** [comment]
@navba-MSFT , I will check it again and provide you a feedback. Thanks.

**Comment by navba-MSFT** [comment]
@erlisb Thanks for getting back. Like I mentioned above The Compute RP will be supported for Quota API in a _couple of weeks_ tentatively. So you might have to try it then.

**Comment by erlisb** [comment]
Hi @navba-MSFT, it seems that neither of RPs (Compute, Network & Storage) is working in the current armquota version : 

Microsoft.Compute : 

```
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'locations' could not be found in the namespace 'Microsoft.Compute' for api version '2021-03-15-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2020-12-01,2021-03-01,2021-04-01,2021-07-01,2021-11-01,2022-03-01,2022-08-01'."
  }
}
```

Microsoft.Network : 

```
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'locations' could not be found in the namespace 'Microsoft.Network' for api version '2021-03-15-preview'. The supported api-versions are '2014-12-01-preview,2015-05-01-preview,2015-06-15,2016-03-30,2016-06-01,2016-07-01,2016-08-01,2016-09-01,2016-10-01,2016-11-01,2016-12-01,2017-03-01,2017-04-01,2017-06-01,2017-08-01,2017-09-01,2017-10-01,2017-11-01,2018-01-01,2018-02-01,2018-03-01,2018-04-01,2018-05-01,2018-06-01,2018-07-01,2018-08-01,2018-10-01,2018-11-01,2018-12-01,2019-02-01,2019-04-01,2019-06-01,2019-07-01,2019-08-01,2019-09-01,2019-11-01,2019-12-01,2020-01-01,2020-03-01,2020-04-01,2020-05-01,2020-06-01,2020-07-01,2020-08-01,2020-11-01,2021-01-01,2021-02-01,2021-03-01,2021-04-01,2021-05-01,2021-06-01,2021-08-01,2021-12-01,2022-01-01'."
  }
}
```

Microsoft.Storage : 

```
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'locations' could not be found in the namespace 'Microsoft.Storage' for api version '2021-03-15-preview'. The supported api-versions are '2021-09-01,2021-08-01,2021-06-01,2021-05-01,2021-04-01,2021-02-01,2021-01-01,2020-08-01-preview,2019-06-01,2019-04-01,2018-11-01,2018-07-01,2018-03-01-preview,2018-02-01,2017-10-01,2017-06-01,2016-12-01,2016-07-01,2016-01-01'."
  }
}
```

Do you know if there is an actual ETA for this fix ?  A _couple of weeks_ doesn't seem very optimistic.

Thank you,
Erlis

**Comment by navba-MSFT** [comment]
@erlisb Thanks for getting back. As mentioned in my above comment, Compute RP is yet to be supported. So the above error is expected now. There are a few more RPs along with Compute RP which will be supported. I didn't get a fixed ETA from the Product Owners. So I can only provide the tentative ETA as of now which is in next 2 - 4 weeks.

**Comment by navba-MSFT** [comment]
@erlisb I hope you had a chance to look at the above comment. We will proceed with archival of this GitHub thread. The fix will be released in couple of weeks, post that if you see the same issue, feel free to reopen this thread. We would be happy to help.

**Comment by erlisb** [comment]
Hi @navba-MSFT, 

is there any update on this issue ?

Thanks,
Erlis

**Comment by navba-MSFT** [comment]
@erlisb Are you still facing the same issue ? If Yes, let me know. I will follow-up with the product owners and update the status. Awaiting you reply.

**Comment by bpineau** [comment]
Hi @navba-MSFT , I'm facing the same issue on both Microsoft.Network and Microsoft.Compute RP. Are any of those supported?

Using the [SDK documentation example](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/quota/armquota@v0.5.0#example-Client.NewListPager) (with my subscription and region names), I also get similar failure messages: "The resource type 'locations' could not be found in the namespace 'Microsoft.Network'", "The resource type 'locations' could not be found in the namespace 'Microsoft.Compute'").
