### ISSUE TITLE
New Generic Poller doesn't correctly handle case where Poll request succeeds, but with failed state

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-go#18581]
### Bug Report

I was specifically testing with `github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.1-0.20220609210213-3e53bd32358a` but I think any current version of `Poller[T]` will have this issue.

This shows up most obviously as a change in behavior of the `Poll` function of the `Poller[T]`. In the old, non-generic implementation, a `Poll` that recieved a valid HTTP response (HTTP status code 200), but whose contents contained a `Failed` state with an error, would classify that as an `error` in Golang and return the `error` to the caller of `Poll`. You can see this [here](https://github.com/Azure/azure-sdk-for-go/blob/c12bc86e645ab04ee8cab2796929998358ede2dc/sdk/azcore/internal/pollers/poller.go#L107), the snippet from `Poll` is:
```go
	if Failed(l.lro.Status()) {
		l.err = shared.NewResponseError(resp)
		l.resp = nil
		return nil, l.err
	}
```

Now though, if the `Poller[T]` has a successful response such as:
```json
{"name":"6ec3dd1f-ebf8-4a8c-a8dc-9c5f8fd37358","status":"Failed","startTime":"2022-07-12T20:45:59.39Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: 'a675d3d1-a6fd-4938-bafe-e491662d2966'"}}
```

This is _not_ classified as an `error` and `Poll` doesn't return an `error`. As far as I can tell in the current `Poller[T]` impl, there is no equivalent "if failed" check. See the [code](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/internal/pollers/async/async.go#L100).

**Comment by jhendrixMSFT** [comment]
Per offline discussion, the pattern is now as follows.

```go
poller := BeginLRO()
for !poller.Done() {
    resp, err := poller.Poll()
    // handle above
}

result, err := poller.Result()
// here's where you discover if the LRO succeeded or failed
```
