### ISSUE TITLE
Unable to expand planInformation on Reservation Order

### ISSUE THREAD

**Issue by mdnix** [Azure/azure-sdk-for-go#18590]
### Bug Report

- import path of package `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/reservations/armreservations v1.0.0`
-  go version `go1.18 darwin/arm64`

I'm trying get more information about a Reservation Order. In particular I'm interested in the planInformation which can be expanded. 

```go
reservationOrder, err := r.order.Get(ctx, reservationOrderID, &armreservations.ReservationOrderClientGetOptions{Expand: to.StringPtr("schedule")})
```
This doesn't work since the expand parameter seems to be wrong. It contains an unnecessary `$` character.

By removing the character from the SDK locally I was able to expand the field:
https://github.com/Azure/azure-sdk-for-go/blob/a191440ceec66c5c3d25b57ba6449279a684ef1c/sdk/resourcemanager/reservations/armreservations/zz_generated_reservationorder_client.go#L181

It also seems to be wrong in the documentation:
https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/reservation-order/get?tabs=HTTP#getreservationwithexpandpayments

**Comment by jhendrixMSFT** [comment]
The OpenAPI [definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/Microsoft.Capacity/stable/2022-03-01/reservations.json#L320) includes the `$` but the service appears to reject it.

**Comment by navba-MSFT** [comment]
@mdnix Apologies for the late reply. Thanks for reaching out to us and reporting this issue. I am adding the Service team to look into this.

@rkapso Could you please look into this issue and provide an update ?
