### ISSUE TITLE
Support for CosmosDB Change Feed Processors in go?

### ISSUE THREAD

**Issue by lmorchard** [Azure/azure-sdk-for-go#18615]
### Feature Request

Azure Cosmos DB [supports a Change Feed](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed).

I've found support for Change Feed Processors in the C#, Node.js, and Java flavors of the Azure SDK. But, there doesn't seem to be support for it in this SDK for go.

We have a project that's currently using a Change Feed Processor implemented in C#. We'd like to move it to golang for consistency with other parts of the project.

Thank you!

**Comment by anthonysomerset** [comment]
Hi All, this is a blocker for Teleport (https://goteleport.com/) to support Azure Native backends and allow for native hosting of Teleport with Azure environments, would be great if this could get some TLC - thanks

**Comment by ealsur** [comment]
@anthonysomerset can you clarify a bit what are the requirements? Is change feed processor or change feed queries (also known as change feed pull model) what is required?

CFP is going to be a long ways off, there are higher and more critical items to deliver first.

**Comment by anthonysomerset** [comment]
Hi @ealsur the teleport folks would have to elaborate, i am just an interested potential teleport customer/user that only uses Azure and would like azure native support for Teleport to be able to take next steps with their product - they just stated that to support CosmosDB they need Change Feed support in the Go SDK in order to bring the feature through - https://github.com/gravitational/teleport/issues/6117#issuecomment-1564381191

**Comment by mjaow** [comment]
@ealsur looks it doesn't support golang even in pull mode, right? So what might be suggestion for those golang users? Would we have to use mongo db api since it supports changestream for golang?

**Comment by ealsur** [comment]
@mjaow At the moment Change Feed cannot be consumed from the NoSQL API Go SDK. It is available in other languages and through integrations, like Azure Functions.

**Comment by SuperMohit** [comment]
I see that, there is no SDK for Go, but do we have a REST doc(swagger), that we can use meanwhile?
