### ISSUE TITLE
Tenants List should return all the fields available in the API

### ISSUE THREAD

**Issue by hermanschaaf** [Azure/azure-sdk-for-go#18619]
### Feature Request

The [TenantIDDescription](https://github.com/Azure/azure-sdk-for-go/blob/v61.6.0/services/subscription/mgmt/2020-09-01/subscription/models.go#L459-L465) struct returned by calls to `TenantsClient.ListComplete` contains only two fields: `ID` and `TenantID`:

```
// TenantIDDescription tenant Id information.
type TenantIDDescription struct {
	// ID - READ-ONLY; The fully qualified ID of the tenant. For example, /tenants/00000000-0000-0000-0000-000000000000.
	ID *string `json:"id,omitempty"`
	// TenantID - READ-ONLY; The tenant ID. For example, 00000000-0000-0000-0000-000000000000.
	TenantID *string `json:"tenantId,omitempty"`
}
```

However, the [underlying API](https://docs.microsoft.com/en-us/rest/api/resources/tenants/list?tabs=HTTP) returns many more useful fields, including `countryCode`, `displayName`, `domains`, `tenantCategory` `defaultDomain` and `tenantType`. It would be great if these fields could also be made accessible through the Go SDK.

**Comment by navba-MSFT** [comment]
@hermanschaaf Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
The above PR has been filed and it is currently under review.

**Comment by navba-MSFT** [comment]
@hermanschaaf Did you try to list tenant using the below package and check if that helps ?

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions#TenantsClient

**Comment by hermanschaaf** [comment]
Hi @navba-MSFT, ah thanks, yes this SDK looks like it would work--it definitely contains the fields, at least! From the comment on the linked PR it sounds like the one I was using is actually deprecated? I will use the new one, thanks so much for your help.
