### ISSUE TITLE
Subscriptions List should include all the fields available in the API

### ISSUE THREAD

**Issue by hermanschaaf** [Azure/azure-sdk-for-go#18620]
### Feature Request

The subscriptions [Model struct](https://github.com/Azure/azure-sdk-for-go/blob/v61.6.0/services/subscription/mgmt/2020-09-01/subscription/models.go#L293-L308) includes a number of fields, but not all the fields available in the REST API according to the documentation. Specifically, the following fields are missing in the Go struct:

- `tenantId` - The subscription tenant ID.
- `tags` - The tags attached to the subscription.
- `managedByTenants` - An array containing the tenants managing the subscription.

We are particularly interested in the tenant ID in order to automatically determine the tenant for a given subscription.

**Comment by hermanschaaf** [comment]
After digging a bit more, I can see that this is because the fields are not part of the OpenAPI definition here: https://github.com/Azure/azure-rest-api-specs/blob/0c21498807897f2d523f3b63166a75e278ca0c64/specification/subscription/resource-manager/Microsoft.Subscription/stable/2016-06-01/subscriptions.json#L210

However, these fields are returned by the API and are documented here: https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list?tabs=HTTP#subscription

Would the fix be to add the fields to the REST API definition? Would a PR to that effect be accepted?

**Comment by RickWinter** [comment]
The package you are using is part of the previous versions.  The most recent version is available here:
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/subscription/armsubscription

**Comment by hermanschaaf** [comment]
@RickWinter Thanks, I wasn't aware that I should be using the more recent version there. 

Having checked that implementation, it seems like the new version is also missing subscription fields from the API like `tenantId` and `tags`: https://github.com/Azure/azure-sdk-for-go/blob/77190ec7d546094c51ff1b61073dd9580394a579/sdk/resourcemanager/subscription/armsubscription/zz_generated_models.go#L445-L465 Is there a way to map subscriptions to their tenants in either the new or the old SDK versions?

**Comment by navba-MSFT** [comment]
@hermanschaaf Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update. I have created the above PR and it is currently under review.

**Comment by hermanschaaf** [comment]
Hi @navba-MSFT, I see this issue has the `needs-author-feedback` tag attached to it--is there something I can help with at this stage?

**Comment by navba-MSFT** [comment]
The above PR is pending for quite sometime now. Adding Service team to look into this and take this forward.
