### ISSUE TITLE
azcore/policy retry: missing documentation about handling of retry-after header

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-for-go#18638]
https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azcore/runtime/policy_retry.go#L173-L177

I was surprised to see no mention of the handling of retry-after header by the client.
I had to look at the code to find the above code snippet.
This behavior is not documented in the RetryDelay option that can be set on the clients:

https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azcore/policy/policy.go#L84-L87

**Comment by jhendrixMSFT** [comment]
Fixes will ship in the August release.
