### ISSUE TITLE
azcore/policy : Missing default referenced in doc comments: StatusCodesForRetry

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-for-go#18637]
StatusCodesForRetry seems to be in autorest? I suppose this is a mistake?

https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azcore/policy/policy.go#L93-L98

**Comment by jhendrixMSFT** [comment]
Fixes will ship in the August release.
