### ISSUE TITLE
CosmosDB: Add Patch/Increment method

### ISSUE THREAD

**Issue by marwan-at-work** [Azure/azure-sdk-for-go#18682]
It looks like CosmosDB has a distributed counter through its patch method: https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.models.cosmospatchoperations.increment?view=azure-java-stable

I'm hoping this SDK has it or plan on adding as it's a common feature in most databases I work with such as Google Cloud Firestore with Go. 

Thanks!

**Comment by ealsur** [comment]
Support for Patch (including Increment) is part of the future deliverables.

**Comment by volmedo** [comment]
> Support for Patch (including Increment) is part of the future deliverables.

Is there an ETA for this?

**Comment by ealsur** [comment]
@volmedo No ETA. There is currently a PR open that adds these APIs in progress

**Comment by volmedo** [comment]
oh, I saw [the PR](https://github.com/Azure/azure-sdk-for-go/pull/19440) is being worked on just right now! 🎉
