### ISSUE TITLE
x-ms-version is not changed when using a different storage profile for Azure Stack Hub

### ISSUE THREAD

**Issue by ephrain1021** [Azure/azure-sdk-for-go#18688]
### Bug Report

- import path of package in question: github.com/Azure/azure-sdk-for-go/profiles/2020-09-01/storage/mgmt/storage
- SDK version: latest
- output of `go version`:  go version go1.17.5 darwin/amd64

- What happened? 

I am trying to use azure-sdk-for-go/tree/main/sdk/storage/azblob to access container of storage account on Azure Stack Hub.
However, that does not work and returns following error:
```
===== RESPONSE ERROR (ErrorCode=InvalidHeaderValue) =====
Description=The value for one of the HTTP headers is not in the correct format.
RequestId:21b4164c-292b-09f6-4898-58e9e9552a82
Time:2022-07-01T03:35:49.7989476Z, Details: 
HeaderName: x-ms-version
HeaderValue: 2019-12-12
```

After digging into the source code of azblob, it looks like x-ms-version is hardcoded as 2019-12-12.
```
req.Raw().Header.Set("x-ms-version", "2019-12-12")
```

If I try to change the value 2019-12-12 to 2019-07-07, my testing program can access the container of storage account on Azure Stack Hub successfully.
However, this approach might not be a good solution since we patch the azblob sdk manually.

So, I followed another suggestion to use "profiles" that had been illustrated in the sample of https://github.com/Azure-Samples/Hybrid-Golang-Samples/tree/master/dataplane.
This sample used "profile", and an older (deprecated) version of azblob, azure-storage-blob-go/azblob.
The default profile used in the sample was "github.com/Azure/azure-sdk-for-go/profiles/2020-09-01/storage/mgmt/storage".
This sample was able to access the container of storage account on Azure Stack Hub.
However, I noticed that changing the "profile" only changed the api-version, not the x-ms-version, in the HTTP request.

1. profile 2017-03-09 => api-version 2016-01-01, x-ms-version 2019-02-02
2. profile 2018-03-01 => api-version 2016-01-01, x-ms-version 2019-02-02
3. profile 2019-03-01 => api-version 2017-10-01, x-ms-version 2019-02-02
4. profile 2020-09-01 => api-version 2017-10-01, x-ms-version 2019-02-02

- What did you expect or want to happen?

I expect that x-ms-version should be changed to align with the profile.
It should be natural to use an older x-ms-version with an older profile for storage account, right?

- How can we reproduce it?

Just run the sample https://github.com/Azure-Samples/Hybrid-Golang-Samples/tree/master/dataplane, and use different storage profiles.

- Anything we should know about your environment.

None.

**Comment by tadelesh** [comment]
@ephrain1021 Profile only affect control plane (create resource group, create storage account, etc.). The version `2019-02-02` is the data plane request api version which is bind with `github.com/Azure/azure-storage-blob-go/azblob`. If you use `v0.10.0`, then is will always be `2019-02-02`.

**Comment by ephrain1021** [comment]
Hi @tadelesh, thanks for your explanation.

Another question: Does azure-sdk-for-go/tree/main/sdk/storage/azblob supports Azure Stack Hub 2102 or 2108 update, or we can only use github.com/Azure/azure-storage-blob-go/azblob to access?

Thank you very much.

**Comment by tadelesh** [comment]
@jhendrixMSFT Could you help to answer?

**Comment by jhendrixMSFT** [comment]
@mohsha-msft can confirm but I don't believe that `azblob` supports any of the stack profiles.

**Comment by mohsha-msft** [comment]
Hey @jhendrixMSFT 

Yes, I've never tested it. I'm quite certain we don't as of now.
