### ISSUE TITLE
[CosmosDB]: Optimistic Concurrency Control

### ISSUE THREAD

**Issue by marwan-at-work** [Azure/azure-sdk-for-go#18691]
Hi there,

Can this client be used for optimistic concurrency control for Upsert-ing a document? If so, are there any examples to follow? 

Thanks!

**Comment by ealsur** [comment]
Yes, the examples are in the `example_test` file: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/example_test.go#L507 also on the Pkg Go site: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos#example-ContainerClient.ReplaceItem-OptimisticConcurrency

**Comment by ealsur** [comment]
Basically the flow is the same as any other SDK. Read the document, get the Etag, send the replace with the Etag, if you get 412, read the document again, apply the changes, repeat the replace with the new Etag
