### ISSUE TITLE
How can I get VM Private and Public IP addresses 

### ISSUE THREAD

**Issue by SandraGiacco** [Azure/azure-sdk-for-go#18705]
Hi @jhendrixMSFT, I'm using the armcompute module and the armcompute.NewVirtualMachinesClient() function and it works great. However, I would like to know how I could retrieve the public and the private IPs. I was wondering whether I could use the armnetwork module and the IPConfigurationPropertiesFormat, but I'm not sure how to proceed to do so. 

Do you have any example, or at least an explanation (even a workaround). I am looking for a function to get VM IP addresses. (I am only able to find create / update IP function in the documentation...)

Please let me know if the armnetwork module is the correct one to intend to get the IP addresses.

Thanks in advance.

Sandra 

_Originally posted by @SandraGiacco in https://github.com/Azure/azure-sdk-for-go/issues/18445#issuecomment-1195663594_

**Comment by jhendrixMSFT** [comment]
For things like this where the question is "how do I do X like the CLI", I take a look at how the Azure CLI does it.  The source for the `az vm list` command is [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/custom.py#L1302).  This calls [`get_vm_details`](https://github.com/Azure/azure-cli/blob/e52c1e93840d7525033d2caee7f13eec5fa61def/src/azure-cli/azure/cli/command_modules/vm/custom.py#L1232) to retrieve the VM properties.  Based on this, I put together a rough sample of what I think the Go code would look like.

```go
nicClient, _ := armnetwork.NewInterfacesClient("subID", nil, nil)
vmClient, _ := armcompute.NewVirtualMachinesClient("subID", nil, nil)

vm, _ := vmClient.Get(context.Background(), "resourceGroup", "vmName", nil)
for _, nicRef := range vm.Properties.NetworkProfile.NetworkInterfaces {
	nicID, _ := arm.ParseResourceID(*nicRef.ID)
	nic, _ := nicClient.Get(context.Background(), nicID.ResourceGroupName, nicID.Name, nil)
	for _, ipCfg := range nic.Properties.IPConfigurations {
		if ipCfg.Properties.PublicIPAddress != nil {
			// do something with the public IP
		} else if ipCfg.Properties.PrivateIPAddress != nil {
			// do something with the private IP
		}
	}
}
```

**Comment by JessicaGreben** [comment]
Thanks @jhendrixMSFT for the [example](https://github.com/Azure/azure-sdk-for-go/issues/18705#issuecomment-1196930026), helped a lot.
The only missing piece was that I needed to make another api call to get publicIP object.

Here is an example of how to do that:
ref: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/public-ip-addresses/get?tabs=Go#get-public-ip-address
```
publicIPClient, err := armnetwork.NewPublicIPAddressesClient(subscriptionID, cred, nil)
publicID, err := arm.ParseResourceID(*ipCfg.Properties.PublicIPAddress.ID)
client, err := armnetwork.NewPublicIPAddressesClient(<subscriptionID>, cred, nil)
publicIP, err := publicIPClient.Get(ctx, publicID.ResourceGroupName, publicID.Name, &armnetwork.PublicIPAddressesClientGetOptions{Expand: nil})
// do something with public IP
```
