### ISSUE TITLE
Doc cmd for module import is incorrect

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#18759]
### Bug Report
the current (as of 29-Jul-2022), mentions this
```
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute
```

This imports old V1 version of the module (2022-05-16)

Instead it should  be
```
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v3
```
This will import the current v3.0.0 Version

The same is true for `resourcemanager/machinelearning/armmachinelearning/v2`

I haven't checked others

**Comment by tadelesh** [comment]
@vijayrajah Thanks for your feedback. We've noticed this issue and will fix with this [PR](https://github.com/Azure/azure-sdk-for-go/pull/18760).
