### ISSUE TITLE
Typo for the error code "IncrementalCopyOfEarlierVersionSnapshotNotAllowed"

### ISSUE THREAD

**Issue by rainmaker2022** [Azure/azure-sdk-for-go#18767]
### Bug Report
The error code "IncrementalCopyOf**Eralier**VersionSnapshotNotAllowed" here has a typo. It should be "IncrementalCopyOf**Earlier**VersionSnapshotNotAllowed".

https://github.com/Azure/azure-sdk-for-go/blob/39b49a59b5db52c5a2761ed2d53b7e0676c72ae0/sdk/storage/azblob/zz_generated_constants.go#L619

If the user uses it to parse the error code, they will never succeed unless the server also uses a typo error code.
Thanks!

- import path of package in question: `sdk/storage/azblob/zz_generated_constants.go`
- SDK version:`latest`

**Comment by zezha-msft** [comment]
Thanks @rainmaker2022.

@siminsavani-msft  looks like the typo is still in the main branch: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/internal/generated/zz_constants.go#L518

**Comment by jhendrixMSFT** [comment]
Fixed in `azblob@v0.5.0`.
