### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by charlesATswin** [Azure/azure-sdk-for-go#18766]
Hello, 

I am trying to create my own Dapr middleware and thus need to build Dapr. I am having the same issues with both `dapr` and `components-contrib`, when I go to build I get the following error at the end of the build processes.

`build github.com/Azure/azure-sdk-for-go/sdk/azcore/to: cannot load github.com/Azure/azure-sdk-for-go/sdk/azcore/to: no Go source files
make: *** [Makefile:64: test] Error 1
`
After going to the relevant [github.com/Azure/azure-sdk-for-go/](git) it looks like the URI structure has changed.

I am not familiar with Go or Make so am having some issues in figuring out how I can change the URI that it is looking for to the correct dependency. 

Thanks,
Charles

System Info:
go version go1.13.8 linux/amd64
GNU Make 4.2.1 Built for x86_64-pc-linux-gnu
components-contrib:: commit 3b96384de90d6ba7547b88ce920575fe7c443f23 -- on master
dapr:: commit commit ab5d32de7d25c0619006ac4e80a0bf779d0feca9 -- on master

**Comment by tadelesh** [comment]
It seems the path of the package `github.com/Azure/azure-sdk-for-go/sdk/azcore/to` is correct. What do you mean "the URI structure has changed"?

**Comment by charlesATswin** [comment]
When I go to `github.com/Azure/azure-sdk-for-go/sdk/azcore/to` I get a 404. Going through the browser I need to go to `https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azcore/to`. I figured that might be why I am getting the error?
