### ISSUE TITLE
Azure Monitor Query for GO

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#18776]
### Azure Monitor Query

Add support for Azure Monitor Query

**Comment by simongottschlag** [comment]
Hi!

I created https://github.com/Azure/azure-sdk-for-go/issues/19021 which was closed in favor of this issue for tracking.

The main question from my side was (even though it may have been vague) if it is possible to set metrics (not query) for a resource using this SDK.

Looking at the JS/TS SDK as a reference, it doesn't seem to support it and the same goes for the current PR for this SDK.

@scottaddie do you know if this is planned?

**Comment by scottaddie** [comment]
@simongottschlag Thanks for clarifying your ask. The Azure Monitor Query library doesn't support setting of metrics. It's intended to be a tool for querying only. Can you please provide a little more detail on your use case?

**Comment by simongottschlag** [comment]
> @simongottschlag Thanks for clarifying your request. The Azure Monitor Query library doesn't support setting of metrics. It's intended to be a tool for querying only. Can you please provide a little more detail on your use case?

@scottaddie ok, thanks! I would like to set custom metrics using the SDK. To be more specific, I would like a Container App in this case set custom metrics on itself.

**Comment by scottaddie** [comment]
The initial beta release shipped yesterday. For more details, see https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery.
