### ISSUE TITLE
Should I make the creation of a new client a singleton?

### ISSUE THREAD

**Issue by veerun14** [Azure/azure-sdk-for-go#18787]
PR https://github.com/Azure/azure-sdk-for-go/pull/17742 adds support for AAD authentication by use of azcore.TokenCredential.

My question is should the client created this way be made a singleton across your app?
The Performance guide in the documentation [here ](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips?tabs=trace-net-core) suggests use of a singleton, but that is for .Net SDK and not for Go

What happens when the token is expired? Should I add a retry?

**Comment by chlowell** [comment]
> should the client created this way be made a singleton across your app?

Our clients for HTTP services (including AAD) share a single `http.Client` by default. If you aren't replacing that `http.Client`, I doubt there's much to be gained by using a singleton `azcosmos.Client`.

> What happens when the token is expired? Should I add a retry?

The Cosmos client and `azidentity` credential handle retries and token refreshing internally. When a Cosmos client method returns an authentication error, the error is either not retriable (think "wrong password") or the client has exhausted its allowed retries (think "network down"). So, you probably don't want to simply call the method again, but it may be possible for your application to recover. The [azidentity troubleshooting guide](https://aka.ms/azsdk/go/identity/troubleshoot) has more information about specific authentication errors.
