### ISSUE TITLE
Stop providing snippets in markdown

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#18786]
All snippets and samples should be compiled to ensure correctness.  The Go tooling provides this validation when the code is contained in documentation examples.  

For each package, we need to ensure

1. Readme samples are references to Examples in documentation on pkg.go.dev
2. Example code in markdown is removed.
3. All Champion scenarios have corresponding examples in doumentation.

**Comment by jhendrixMSFT** [comment]
I agree with this.  However, I think there's value in having very targeted _examples_ (not end-to-end samples) inline with the docs.

That said, we should take this one step further.  Remove all samples/docs from README.md and keep things in `doc.go` or the like ([example](https://github.com/golang/go/blob/master/src/net/net.go)).
