### ISSUE TITLE
[azservicebus] NewListRulesPager not working with Custom Properties in Correlation Filter

### ISSUE THREAD

**Issue by balram2697** [Azure/azure-sdk-for-go#18785]
### Bug Report

NewListRulesPager not working with Custom Properties in Correlation Filter

- SDK version - github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v1.0.2
- output of `go version` - go version go1.18.1 linux/amd64

- What happened?
listRulesPager.NextPage(ctx) gives below error when the rule filter is of type Correlation filter and contains Custom Properties.
Error: type d5p1:string of parameter check is not a handled type for SQL parameters

- What did you expect or want to happen?
NewListRulesPager  should not return error.
- How can we reproduce it?
Create a Rule on Subscription with filter of type Correlation filter and add Custom field in it. 
Try to fetch the Rule using NewListRulesPager
![image](https://user-images.githubusercontent.com/28356383/182827185-3e5e187f-6896-436f-b289-ac5941a707a3.png)

**Comment by richardpark-msft** [comment]
Hi @balram2697, I'm looking at this.
