### ISSUE TITLE
[track2] Provide a way to redact fields based on pattern when logging response body

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-for-go#18799]
### Feature Request

When we enable logging of response body, everything is logged and we can't parse/filter it easily.
even the client handshake is logged, logging the token :

```
==> REQUEST/RESPONSE (Try=1/113.371455ms, OpTime=113.649859ms) -- RESPONSE RECEIVED
   POST https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token
   Content-Length: 220
   Content-Type: application/x-www-form-urlencoded; charset=utf-8
   User-Agent: azsdk-go-azidentity/v1.0.0 (go1.18.4; linux)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-store, no-cache
   Content-Length: 1447
   Content-Security-Policy-Report-Only: REDACTED
   Content-Type: application/json; charset=utf-8
   Date: Sun, 07 Aug 2022 04:06:25 GMT
   Expires: -1
   P3p: REDACTED
   Pragma: no-cache
   Set-Cookie: REDACTED
   Strict-Transport-Security: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Ests-Server: REDACTED
   X-Ms-Request-Id: b7b9aec6-782f-4240-97fd-6dec8e753100
   X-Xss-Protection: REDACTED
   --------------------------------------------------------------------------------
{"token_type":"Bearer","expires_in":86399,"ext_expires_in":86399,"access_token":"eyJ0eXAiOiJKV1Qi... }
``` 

Logging the body of service to service communication is very useful in test environments, but we need ways to do this safely.

We'd like a way to redact property values based on property name. For example, redact anything with "token" in the property name. or based on heuristics of the value.

This allows us to always enable full request body logging in our e2e suites safely, and potentially in production to flip the environment variable for troubleshooting s2s calls.

We can do this with a custom pipeline policy, but that would mean replacing the entire logging middleware that is already built-in the sdk.

**Comment by jhendrixMSFT** [comment]
This should be achievable today with a custom log listener, so no need to change the pipeline policy.  Granted, this filter would apply to the entire output to be logged, not just the response body.

```go
package main

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
)

func main() {
	log.SetListener(func(e log.Event, msg string) {
		// filter msg before logging it
	})
}
```

**Comment by Nishant-Kumar07** [comment]
My team is trying to access the response error returned here - https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/internal/exported/response_error.go#L99 

As part of the RawResponse, I do see the bearer token being displayed, is there a way or plan to redact/hide the bearer token? 

Will this "Github issue" take care of the problem or should i raise a new github issue?

**Comment by jhendrixMSFT** [comment]
Please let me know if a custom log listener is working for your filtering.

**Comment by serbrech** [comment]
We do want the log, but we need to redact some fields. This is hard to do reliably when the only thing we can work with is a string.

**Comment by weinong** [comment]
@jhendrixMSFT we just hit the issue and left bearer token in the log. if custom log listener is required to use this feature safely, you should disclose that with a big warning

**Comment by serbrech** [comment]
@jhendrixMSFT I think the problem is that the custom log listener just moves all the parsing logic onto us, while we DO want to be able log the body, but we also want to do this SAFELY.

The swagger definitions have standard annotations to mark properties as secret, could this be leveraged?
Alternaively, providing some kind of filtering using heuristics/entropy for secrets and/or property names deny list would probably cover 99% of the needs.

- this should be per property on the json body, not on the whole json. (i.e: redact the properties that hit the entropy threshold)
- yes, we could plug our own one in the current log hook, but I really think this would be worth having in the SDK itself, to make this secure by default.

Example of simple entropy analyzer that would detect bearer token:

https://github.com/securego/gosec/blob/970cc2957fb03f53cc97ddc3568347a31a80589d/rules/hardcoded_credentials.go#L49

**Comment by weinong** [comment]
the AAD token payload is well structure enough that SDK should redact it easily

```
{"token_type":"Bearer","expires_in":599,"ext_expires_in":599,"access_token":"<should-have-been-redacted>"}
```

**Comment by jhendrixMSFT** [comment]
We discussed this at length today and decided to leave logging as is for the following reasons.
- There are legitimate debugging cases where having the generated token in the log is desirable (e.g. inspecting claims in the token).  If we redact it by default, we don't want to have to add a flag to turn that off.
- Logging of the body is opt-in and there is a disclaimer in the doc comment that this can leak sensitive information.
- This behavior is consistent with how logging works in the other languages.
- Adding your own filter for this (and other) is pretty trivial.

Here's a custom log listener that will redact the access token.

```go
log.SetListener(func(e log.Event, s string) {
	tokenFilter := regexp.MustCompile(`"access_token":"(\S+)"`)
	res := tokenFilter.FindStringSubmatch(s)
	if len(res) > 1 {
		// second submatch is the captured access token
		s = strings.Replace(s, res[1], "REDACTED", -1)
	}
	fmt.Fprintf(os.Stderr, "[%s] %s: %s\n", time.Now().Format(time.StampMicro), e, s)
})
```
I've tested this and it works as expected.
```
[May  4 13:06:53.743935] Response: ==> REQUEST/RESPONSE (Try=1/342.3448ms, OpTime=342.4981ms) -- RESPONSE RECEIVED
   POST https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token
   Content-Length: 223
   Content-Type: application/x-www-form-urlencoded; charset=utf-8
   User-Agent: azsdk-go-azidentity/v1.2.2 (go1.20.3; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-store, no-cache
   Content-Length: 1407
   Content-Type: application/json; charset=utf-8
   Date: Thu, 04 May 2023 20:06:52 GMT
   Expires: -1
   P3p: REDACTED
   Pragma: no-cache
   Set-Cookie: REDACTED
   Strict-Transport-Security: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Ests-Server: REDACTED
   X-Ms-Request-Id: 8a006efa-cc8a-4174-908b-b695d4d77b00
   X-Xss-Protection: REDACTED
   --------------------------------------------------------------------------------
{"token_type":"Bearer","expires_in":86399,"ext_expires_in":86399,"access_token":"REDACTED"}
   --------------------------------------------------------------------------------
```

**Comment by serbrech** [comment]
I think it's suboptimal considering the consequences of logging the token, and it doesn't follow a "secure by default" principle.
If we, as microsoft 1P teams specialized in GO get bitten by this, imagine our customers.

This is the sort of things that pushes teams to develop their own wrappers and tooling. 
We have to write tooling and linters to ensure that ALL usages of the SDK in all our services overwrite the log listener safely, It is otherwise unsafe to use.

**Comment by serbrech** [comment]
Can we not have another hook _above_ that call, that gives us a structured argument?
Parsing the whole string forces use to drop to regex and string matching, while internally, you perfectly know what are the message, headers, body, etc...

At least give us a chance to write decent code to filter it?

**Comment by serbrech** [comment]
Thinking more about the bullet points in your reply:

> There are legitimate debugging cases where having the generated token in the log is desirable (e.g. inspecting claims in the token). If we redact it by default, we don't want to have to add a flag to turn that off.

This is definitely the exception rather than the rule, and if you need to inspect a token in logs, then you know you have to proceed with caution and not ship it to your log sink.

- There are other places to inspect the headers than the logs as well
- if you **do** want to always log the claims part of the token, then I feel like it's a very valid step to require you to explicitely say: "please include the token in the log string" because it makes it clear that what you are doing is not secure.

Your own SDK design guidelines state: 
> When implementing authentication, don’t open up the consumer to security holes like PII (personally identifiable information) leakage or credential leakage.

It's the first sentence under authentication: 
https://azure.github.io/azure-sdk/general_implementation.html#authentication

This log statemenmt is part of the authentication handshake that the SDK performs and definitely allows to leak the credential

**Comment by jhendrixMSFT** [comment]
Response logging works at the raw HTTP level so there is no structured data type from which to intelligently filter the data.  All it does is read the `*http.Response.Body` and send it to the log listener.

@JeffreyRichter can you comment on the PII/credential leakage issue?  As I recall, it was determined by the arch board that this scenario wasn't considered a breach of security (I forget how you worded it).

**Comment by weinong** [comment]
The AAD token flow and token response are well known and ubiquitous in Azure SDK. This should be the least the SDK can do.

**Comment by serbrech** [comment]
@jhendrixMSFT As far as I can tell, the response body is just this part in the log string:   

{"token_type":"Bearer","expires_in":86399,"ext_expires_in":86399,"access_token":"REDACTED"}

There are multiple parts to this log string. 
- some arbitrary messages and separators
- the request, in a format that you control.
- part of the response, again in a special format.
- and finally the body.

If we had these as a struct, and not just a string, we could at least assume that the content of the Body field is json, and parse it accordingly.
When the argument is a string, processing it means we rely on your log stack not changing the shape of that log string, or using clever regexes.

**Comment by jhendrixMSFT** [comment]
Hmm, having a singular callback would make it difficult to have a default filter that could be removed.  Perhaps a slice of filters?  That way, the auth policies could have a default one for redacting the access token, and callers could remove it as required.  They can also add additional filters without removing the in-box ability to redact the access token.

**Comment by jhendrixMSFT** [comment]
```go
// LogOptions configures the logging policy's behavior.
type LogOptions struct {
...
	// BodyFilters contains callbacks that can be used to filter request and response bodies.
	// Each filter is executed in succession, passing the result from the previous filter to the next.
	// When IncludeBody is false this field is ignored.
	BodyFilters []func(string) string
...
}
```

**Comment by jhendrixMSFT** [comment]
Playing around with this some, it doesn't have to be a slice (either approach would work).

**Comment by serbrech** [comment]
This would help yes.
should the signature use `[]byte` to match a body though?

did you consider a middleware style of API, instead of just a body filtering slice?

**Comment by JeffreyRichter** [comment]
Joel & I have discussed this at length. We are resistant to adding 1st class support for this issue as it only applies to a specific service with a specific JSON property at this time while we also already have multiple fully-supported mechanisms available for you to deal with this. 

First, you can manipulate the log string before logging it. I understand that this is a process-wide perf hit that you would like to avoid. 

So, second, you can turn off our built-in logging policy and inject your own into the pipeline for a specific client and your logging policy can have the logic for this specific service/JSON property trivially.

Also, by default, our SDK does no logging at all and even when turned on does not log bodies by default and so our SDK does not leak any privileged information by default. 

If you desire assistance with building your customer logging policy, we are happy to help with that.
