### ISSUE TITLE
Read Only Fields in DenyAssignmentProperties and Missing Clients 

### ISSUE THREAD

**Issue by wenjungaogaogao** [Azure/azure-sdk-for-go#18811]
### Bug Report

- import path of package in question:
  - "github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-09-01-preview/authorization"
  - And other apiversions as well.
  
- SDK version e.g. `master`
  -  master
  
- output of `go version`
  - go version go1.18.2 linux/amd64 

- What happened?
  1. The principal field is marked as [read only](https://github.com/Azure/azure-sdk-for-go/blob/25ab76cd46123e154aeb9e8b6db56e3c0ec3b2df/services/preview/authorization/mgmt/2020-04-01-preview/authorization/models.go#L758)    
  2. There's no sdk for denyAssignments create and list. List is public preview while create can only be performed by Azure internal. Details [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/deny-assignments).
 
- What did you expect or want to happen?
  1. Making the principal field non read-only. Now, upon put we need to copy the definition of DenyAssignmentProperties as otherwise the principal field will be dropped when MarshalJSON().
  2. Now we have to put/get deny assignments via generic armresource client. It'd be great if it can have a dedicated client in track 2.

**Comment by tadelesh** [comment]
@wenjungaogaogao We have deprecated `github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-09-01-preview/authorization`. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.

**Comment by wenjungaogaogao** [comment]
@tadelesh Thanks for the quick response. 
However DenyAssignment related model and client are not available in the auth sdk.

**Comment by tadelesh** [comment]
@Alancere Please help to release a new version for authorization with tag `package-2022-04-01`.

**Comment by tadelesh** [comment]
Meanwhile, @wenjungaogaogao feel free to share your experience using the Azure SDK in this [survey](https://aka.ms/azsdk/go/issuesurvey).

**Comment by tadelesh** [comment]
Please try new version: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization/v2@v2.0.0
