### ISSUE TITLE
Server issues don't result in request-id showing up in error message

### ISSUE THREAD

**Issue by brphelps** [Azure/azure-sdk-for-go#18845]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`

` 	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob" `

- SDK version e.g. `master`, `latest`, `18.1.0`

` github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.4.1 `

  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.

`I don't think this is a valid command`
- output of `go version`

`go version go1.18.1 linux/amd64` 

- What happened?

We had an error come out of the azblob lib that looked like this: 

```
couldn't save snapshot JSON to blob storage: blob upload failed: ===== INTERNAL ERROR =====
Put "https://<accountname>.blob.core.windows.net/snapshot-blobs/17435035/8fc23938-db12-40c5-9ebe-156dc1a13941": dial tcp: lookup <accountname>.blob.core.windows.net on 10.127.5.10:53: server misbehaving
```

- What did you expect or want to happen?

I dialed up support, and they don't see any server errors. They expect to see the request ID coming back in this case. The library is clearly indicating something went wrong on the server, but support can't seem to determine what it is.

- How can we reproduce it?

No idea, this appears to be a transient server issue that isn't being correctly reported by the client?

- Anything we should know about your environment.

Not that I know of!

**Comment by jhendrixMSFT** [comment]
Looks like DNS failed to resolve the host name, so the request was never made which is why there's no request ID.  This specific error message comes from the standard library.

https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L44
