### ISSUE TITLE
Create Azure Monitor Query library for Go

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-go#18879]
Ship an Azure Monitor Query library for Go. The library should have the same features at the .NET, Java, JavaScript, and Python libraries. Checklist of items to address before GA:

- [ ] Document champion scenarios in README (same scenarios documented in the other languages' libraries)
- [ ] Create a troubleshooting guide

**Comment by RickWinter** [comment]
Duplicate issue, https://github.com/Azure/azure-sdk-for-go/issues/18776
