### ISSUE TITLE
ListByResourceGroupComplete  not showing resource id correctly

### ISSUE THREAD

**Issue by garimakhulbe02** [Azure/azure-sdk-for-go#18895]
### Bug Report

- Import
```Go
import (
"github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/resources"
//azure-sdk-for-go/blob/main/services/resources/mgmt/2020-10-01/resources/resources.go 
)
```

- SDK version 
  v66.0.0

- Output of `go version`
1.17

- Description
I am using ```ListByResourceGroupComplete``` with tags as filter to get list of resource in resource group for specified tag. I have a gallery image version in resource group which I need to delete, so I am listing it in tagged resources and then try to delete it. The issue is the resource ID comes back from ```ListByResourceGroupComplete``` for gallery image is in incorrect format which is failing delete.

    have
    /subscriptions/<>/resourceGroups/<>/providers/microsoft.compute/**galleries/0.25342.36885**
    
    want
    /subscriptions/<>/resourceGroups/<>/providers/microsoft.compute/**galleries/<>/images/<>/versions/0.25342.36885**

code for reference
```Go
        filter := fmt.Sprintf("tagName eq '%s' and tagValue eq '%s'", tagName, tagValue)
	resultItr, err := resourcesCl.ListByResourceGroupComplete(ctx, resourceGroupName, filter, "", nil)
	if err != nil {
		logger.TraceErrorf("Error listing resources in '%s:%s': %v", subscriptionID.String(), resourceGroupName, err)
		return nil, err
	}

	var rids []string
	for resultItr.NotDone() {
		logger.TraceInfof("resultItr: %v", resultItr.Value())
		rids = append(rids, to.String(resultItr.Value().ID))
		logger.TraceInfof("ID: %v", to.String(resultItr.Value().ID)) // this ID is in wrong format
		if err := resultItr.NextWithContext(ctx); err != nil {
			logger.TraceErrorf("Error getting next page of resources in '%s:%s': %v", subscriptionID.String(), resourceGroupName, err)
			return nil, err
		}
	}

      //resource client from this code
      //func (azCl *azureClient) getResourcesClient(logger *log.Logger, subscriptionID uuid.UUID) (*resources.Client, error) {
      // 	authorizer, err := azCl.getAuthorizer(logger)
      // 	if err != nil {
      // 		return nil, err
      // 	}
      
      // 	client := resources.NewClientWithBaseURI(azCl.environment.ResourceManagerEndpoint, subscriptionID.String())
      // 	client.Sender = security.SecureHTTPClient()
      // 	client.Authorizer = authorizer
      // 	client.RequestInspector = azCl.DecorateRequest(logger)
      // 	client.ResponseInspector = LogResponse(logger)
      
      // 	return &client, nil
      // }
```

To reproduce, create a gallery image version and tagged it. Then try to list it using ```ListByResourceGroupComplete``` with tag filter. The resource id for the version will be incorrect.

**Comment by garimakhulbe02** [comment]
@ArcturusZhang can you taka a look?

**Comment by tadelesh** [comment]
@garimakhulbe02 It seems a service issue. But we have deprecated package `github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2021-12-01/compute`. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v3). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details. If the issue still exists in the new version, feel free to leave a comment and we'll involve service team to have a look.
