### ISSUE TITLE
EventGrid subscription validation on Webhook example

### ISSUE THREAD

**Issue by imperugo** [Azure/azure-sdk-for-go#18915]
### Feature Request

Hi, 
in my scenario I've few EventGrid subscription in different HTTP endpoints served by an go application using Gin.
In order to be sure that the request is coming from a trusted source (Azure in this case), I'm going to validate the request using a middleware.

Looking online I didn't found any example that explain how to do that.

```golang
package middlewares

import (
	"github.com/gin-gonic/gin"
	"github.com/Azure/azure-sdk-for-go/services/eventgrid/mgmt/2021-12-01/eventgrid"
)

func EventNotificationMiddleware() gin.HandlerFunc {

	return func(c *gin.Context) {
		// Non è una chiamata da Azure Event Grid
		if len(c.GetHeader("Aeg-Event-Type")) == 0 {
			c.Next()
			return
		}
		
		

		// ... here need to validate the Request Subscription + SAS 
		//if c.Request.Body .... is from azure {
		//	c.Next()
		//	return
		//}
		//
		//return
	}
}
```

Do you have any hint?

**Comment by tadelesh** [comment]
@imperugo We have deprecated `github.com/Azure/azure-sdk-for-go/services/eventgrid/mgmt/2021-12-01/eventgrid` package. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventgrid/armeventgrid](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventgrid/armeventgrid). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details. From your description, it seems you need to handle with the raw response. You could refer to [this](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-guideline.md#raw-http-response) for some help.

**Comment by imperugo** [comment]
Hi @tadelesh 
thanks for the quick answer. 
I just replaced the packaged and took a look to your link suggestion but I didn't find what I was looking for.

In my scenario some applications are raising events into EventGrid and other applications are subscribers for that events thanks to the web-hook.

As far as I understood reading the documentation the first thing to do in order to have the subscribed confirmed on a web-hook is do that https://docs.microsoft.com/en-us/azure/event-grid/receive-events

The page shows the .NET Core and Node but I didn't find any similar in GO. **That's the first point**.

The second one is that the endpoint must have the "allowAnonymous" but it means everyone can call it. 
In order to prevent that EventGrid add an SAS token into the query string so I can validate it in order to accept the request.

<img width="813" alt="Screenshot 2022-08-23 at 11 30 20" src="https://user-images.githubusercontent.com/758620/186124279-bbc97015-432d-40b8-8cd7-5e99431afcfa.png">

How can I do that validation in Go? (**second point**)

Thanks

**Comment by tadelesh** [comment]
@imperugo Thanks for the clarify. @jhendrixMSFT Could you help as it seems related to data plane?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

We don't, at present, have a Go SDK for event grid.  I will follow up on what our plans are for releasing this.  In the meantime, you'll have to directly use the REST endpoints (not super helpful, but the best we have at present).

I'm not very familiar with the event grid service but can try to help you through this if you have questions.

**Comment by jhendrixMSFT** [comment]
We now have a beta SDK, `azeventhubs` for interfacing with EventHubs.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs

Please feel free to reopen this issue if it's still a problem.
