### ISSUE TITLE
Support `showonly` parameter for azure blob storage LIST API, in `ContainerListBlobsFlatOptions`

### ISSUE THREAD

**Issue by xstephen95x** [Azure/azure-sdk-for-go#18921]
### Feature Request

We are trying to use the new `azblob` package in this SDK to access ADLSGen2 / "hierarchical namespaces". 

In the documentation:
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues
It says 

> When you use the [List Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs) operation without specifying a delimiter, the results will include both directories and blobs.

This is troublesome because the SDK currently provides no means of determining what is a file and what is a directory in the LIST results. There is no distinguishing type or characteristic available in the returned data structures. 

However, in the API Documentation:
https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs

> showonly={deleted,files,directories} 

Is an available parameter for we could use with ADLSGen2 to filter LIST results for only files or only directories.

The SDK does not currently support this parameter:
https://github.com/Azure/azure-sdk-for-go/blob/072ff86c4c7aebcf27c822cca840daf1d2305943/sdk/storage/azblob/internal/generated/zz_container_client.go#L755 

And it would be very helpful to be able to specify this parameter in `ContainerListBlobsFlatOptions`, so we can explicitly request only files or only directories. 

This way, we can use the `containerClient.ListBlobsFlat` with both flat and hierarchical namespaces, and get the same behavior if we specify `showonly=files`.

**Comment by zezha-msft** [comment]
Thanks @xstephen95x  for reaching out!

We haven't quite caught up to the latest service version. In the meantime, an easy way to tell directories apart from files is that the directories have a special metadata: "hdi_isfolder": "true". Please try it out and let us know if it is a reasonable mitigation for now.

**Comment by xstephen95x** [comment]
@zezha-msft I think `hdi_isfolder` should be a tenable workaround for now...
We've also found another workaround, in that you can call `ListHierarchy` with an empty string as the delimiter `delimiter=""` , and this seems to only return files and not directories.

However, You should really consider explicit support for `showonly` in the SDK :)

**Comment by vibhansa-msft** [comment]
As per the public documentation that you have quoted: 
```
-files: Optional. Version 2020-12-06 and later. Only for accounts enabled with hierarchical namespace. When a request includes this parameter, the list only contains files.
-directories: Optional. Version 2020-12-06 and later. Only for accounts enabled with hierarchical namespace. When a request includes this parameter, the list only contains directories.
```
Both these features are supported only for HNS enabled accounts. As of now azblob does not support HNS specific features or APIs natively. This support will come with our datalake sdk later.

**Comment by xstephen95x** [comment]
@vibhansa-msft While you're correct, this does have to do with HNS, i don't believe your comment is entirely correct.
> As of now azblob does not support HNS specific features or APIs natively.

This has nothing to do with HNS specific APIs. `azblob` supports the Azure Storage Blob REST API.

I'm requesting a feature for interacting with the Blob API, not the data lake API.
