### ISSUE TITLE
Autogenerated Container Instance Model Is Not Up To Date

### ISSUE THREAD

**Issue by bmayfi3ld** [Azure/azure-sdk-for-go#18920]
### Bug Report

The field for dnsNameLabelResusePolicy was updated to AutoGeneratedDomainNameLabelScope in the latest swagger spec. (after the release of version 2021-10-01?) 

https://github.com/Azure/azure-rest-api-specs/pull/18081/files

But this is not reflected in the current Go model.

[	DNSNameLabelReusePolicy *AutoGeneratedDomainNameLabelScope `json:"dnsNameLabelReusePolicy,omitempty"`](https://github.com/Azure/azure-sdk-for-go/blob/945e8ed5471a61f3292a28e11be8e3fc5af15a56/sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_models.go#L585)

If you try to use the current field in an container creation call you receive the expected error. 

`
{
  "error": {
    "code": "InvalidRequestContent",
    "message": "The request content was invalid and could not be deserialized: 'Could not find member 'dnsNameLabelReusePolicy' on object of type 'IpAddress'. Path 'properties.ipAddress.dnsNameLabelReusePolicy', line 1, position 362.'."
  }
}
`

go.mod info

github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerinstance/armcontainerinstance v1.0.0

go1.19 linux/amd64

**Comment by navba-MSFT** [comment]
@bmayfi3ld Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@bmayfi3ld I have created a SDK release request, hoping it will be reviewed soon: https://github.com/Azure/sdk-release-request/issues/3107

**Comment by tadelesh** [comment]
@navba-MSFT it is not an SDK discrepancy from swagger. The issue is from the property name `dnsNameLabelReusePolicy` not the enum name. Please contact service team to figure out if it is a service bug. I've closed the release request you created.

**Comment by navba-MSFT** [comment]
Thanks @tadelesh for clarifying.

@bmayfi3ld  May I know your use case ? What are you trying to accomplish ?

**Comment by bmayfi3ld** [comment]
I'm trying to use the field AutoGeneratedDomainNameLabelScope but currently it is incorrectly named (and json tagged) DnsNameLabelReusePolicy in the github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerinstance/armcontainerinstance v1.0.0 package.    When used it gives the error in the original post. 

From how I read the armcontainerinstance package, it is autogenerated. It looks like its reference to https://github.com/Azure/azure-rest-api-specs in https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/containerinstance/armcontainerinstance/autorest.md needs to be updated to include the corrected field name that was done in azure-rest-api-specs.

**Comment by tadelesh** [comment]
@bmayfi3ld I got it. Sorry for the wrong interpretation. It seems after service team fix the swagger correctness issue, there is no release request for this RP. @navba-MSFT Could you help to let service team to fire the request as this will also affect other languages' SDK.

**Comment by navba-MSFT** [comment]
@tadelesh Just to confirm, Are you asking me to create an SDK release request again ?

**Comment by tadelesh** [comment]
> @tadelesh Just to confirm, Are you asking me to create an SDK release request again ?

I don't know the reason why service team did not raise the release request after the swagger change. So, it could be better that we confirm with service team first.

**Comment by navba-MSFT** [comment]
@bmayfi3ld @tadelesh I had reached out to the service team and got their reply. This fix had been put off due to changes needed to be made in swagger. If you want to use this field, please create your container in portal in the meantime.

Also, for the release you created I see you used version 2021-11-01, but should instead be 2021-10-01. Hope this answers.

**Comment by bmayfi3ld** [comment]
Looks like that PR fixes the problem.

**Comment by navba-MSFT** [comment]
@bmayfi3ld Thanks for your reply. If you have any further queries or concerns, feel free to reopen this issue. We would be happy to help on this.
