### ISSUE TITLE
azblob: what to do with "unrecorded" tests

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#18935]
Tests are currently split into two buckets, recorded and unrecorded.  It might simply be the case that the tests in the unrecorded bucket work and just need to be run/recorded.  At any rate, these tests aren't being executed at present, so we need to figure out what to do with them.

**Comment by vibhansa-msft** [comment]
Regular pipeline runs recorded and unrecorded both and we do get the code coverage report for them as well,
