### ISSUE TITLE
azblob: uncomment the commented-out tests

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#18933]
There are a lot of tests currently commented out.  Assuming they are salvageable, uncomment them.

**Comment by vibhansa-msft** [comment]
@siminsavani-msft  : as part of your effort on improving the testing, we can clear this if required.

**Comment by vibhansa-msft** [comment]
Closing this as most test cases are uncommented and test coverage is also good.
