### ISSUE TITLE
Is it possible to validate model objects on client side (without calling Azure API)?

### ISSUE THREAD

**Issue by AlexPykavy** [Azure/azure-sdk-for-go#18936]
Does Azure SDK for Go support running client-side validation (without calling Azure API) on the model object to quickly verify its fields?

For example, to check the VM properties for length and allowed characters.

**Comment by AlexPykavy** [comment]
Hello @tadelesh, thank you for your response. It explains why this functionality is missing.

I'm just wondering 🤔 maybe you know how Azure Portal performs such a validation in a web browser? Is it hardcoded in JavaScript or client sends some requests to API to validate fields? Or at least know where to ask this question.

**Comment by AlexPykavy** [comment]
And I'm closing the issue anyway because the initial request was considered.

**Comment by tadelesh** [comment]
> Hello @tadelesh, thank you for your response. It explains why this functionality is missing.
> 
> I'm just wondering 🤔 maybe you know how Azure Portal performs such a validation in a web browser? Is it hardcoded in JavaScript or client sends some requests to API to validate fields? Or at least know where to ask this question.

AFAIK, portal logic is always implemented by the service team separately. @xboxeer Do you know where to fire the issue?
