### ISSUE TITLE
Unable to Update AKS Nodepool to Enable Autoscaling Because of Erroneous Error Message

### ISSUE THREAD

**Issue by georgejdli** [Azure/azure-sdk-for-go#18941]
### Bug Report

- import path of package in question, `"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice" v1.0.0` 
- SDK version `v66.0.0+incompatible`
- output of `go version`: go1.19 darwin/arm64

- What happened? I get an error that is incorrect from the API when trying to update an AKS nodepool to enable autoscaling.

```
PUT https://management.azure.com/subscriptions/<sub-id>/resourceGroups/<my-resource-group>/providers/Microsoft.ContainerService/managedClusters/<my-AKS-cluster>/agentPools/mynodepool
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameter
--------------------------------------------------------------------------------
{
  "code": "InvalidParameter",
  "message": "AgentPool 'mynodepool' has set auto scaling as enabled but is not on Virtual Machine Scale Sets, this is not allowed. Please see https://aka.ms/aks-vmss-enablement for more details.",
  "subcode": ""
}
```
The nodepool is using Virtual Machine Scale Sets. I am able to enable to autoscaling via the Azure Portal and the Azure CLI.

For reference the Azure CLI is using api-version=2022-04-01

Looking at the generated source code for armcontainerservice I can see that it is using the same API version:
```go
reqQP.Set("api-version", "2022-04-01")
```

Why does the azure-sdk-for-go and the Azure CLI have different results for the same operation request?

- What did you expect or want to happen? For the request to succeed without errors.
- How can we reproduce it? 
```go
pollerResp, err := agentPoolClient.BeginCreateOrUpdate(
		ctx,
		clustGrp,
		clustName,
		rainNodePoolName,
		armcontainerservice.AgentPool{
			Properties: &armcontainerservice.ManagedClusterAgentPoolProfileProperties{
				OrchestratorVersion: to.Ptr(""),
				Count:               to.Ptr(4),
				VMSize:              to.Ptr("standard_b4ms"),
				OSType:              to.Ptr(armcontainerservice.OSTypeLinux),
				Mode:                to.Ptr(armcontainerservice.AgentPoolModeUser),
				ScaleDownMode:       to.Ptr("Deallocate"),
				EnableAutoScaling:   to.Ptr(true),
				MaxCount:            to.Ptr(4),
				MinCount:            to.Ptr(int32(0)),
			},
		},
		nil,
	)
```

- Anything we should know about your environment.

**Comment by georgejdli** [comment]
Looks like you need to explicitly set the "AgentPoolType" for azure-sdk-go whereas in the azure cli it defaults to "VirtualMachineScaleSets".

I guess this is more of a documentation issue: the error message is confusing and the sdk docs don't say "Type" param is required for autoscaling.

The below configuration worked for me after adding the "Type" field to the properties struct
```go
pollerResp, err := agentPoolClient.BeginCreateOrUpdate(
		ctx,
		clustGrp,
		clustName,
		rainNodePoolName,
		armcontainerservice.AgentPool{
			Properties: &armcontainerservice.ManagedClusterAgentPoolProfileProperties{
				OrchestratorVersion: to.Ptr(""),
				Count:               to.Ptr(4),
				VMSize:              to.Ptr("standard_b4ms"),
				OSType:              to.Ptr(armcontainerservice.OSTypeLinux),
				Mode:                to.Ptr(armcontainerservice.AgentPoolModeUser),
				ScaleDownMode:       to.Ptr("Deallocate"),
				EnableAutoScaling:   to.Ptr(true),
				MaxCount:            to.Ptr(4),
				MinCount:            to.Ptr(int32(0)),
                                 Type:                to.Ptr(armcontainerservice.AgentPoolTypeVirtualMachineScaleSets),
			},
		},
		nil,
	)
```

**Comment by tadelesh** [comment]
@xboxeer Can we have some more user-friendly method to help customer to understand how to use the API? For DPG, I know service doc or rest doc will be attached to API doc though I don't find related info of this customer's issue from swagger spec.

**Comment by xboxeer** [comment]
@tadelesh AKS is a complex resource and I can find out that create or update AKS managed cluster is defined [here](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=Go%2CHTTP#managedclusteragentpoolprofile), however it does not specified any information about when should we setup the `Type` property in agent pool profile: https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=Go%2CHTTP#agentpooltype
This is more like a service team document issue, even if we add link direct to the rest api reference page, our customer still don't know the type is required in creating this resource
We need an alternative way to simplify the creation of complex resources. 
@georgejdli May I know how do you aware of that the type of agentpoolproperties need to be assigned when creating managed cluster? by looking through CLI trace or the portal arm template?

**Comment by georgejdli** [comment]
@xboxeer I saw the "type" property being sent in the CLI debug output even though I did not explicitly set that option in the CLI command. I tried it with azure-sdk-for-go and it worked.

Would it be possible to make the "type" default to AgentPoolTypeVirtualMachineScaleSets when not set? 
Looking at the generated client code I see that "type" is omitted from the request if not set.

**Comment by georgejdli** [comment]
Doesn’t sound like there’s a satisfactory way of resolving this documentation issue but at the very least there’s this GitHub issue to refer back to in case others run into the same problem.
