### ISSUE TITLE
Role Assignments API fails for new roles

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#1895]
👋 

When attempting to use the Role Assignments API to create a role assignment for a new role (such as `Virtual Machine User Login`) - the API returns the following error message:

```
authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedApiVersionForRoleDefinitionHasDataActions" Message="Assignments to roles with DataActions and NotDataActions are not supported on API version '2015-07-01'. The minimum required API version for this operations is '2018-01-01-preview'."
```

Whilst I can understand this behaviour, this is a poor user experience when users would expect the role assignment to silently handle calling the new API in the background. Would it be possible to reach out to the service team here?

In the mean time it appears there's support for this new version in the SDK - so we could look into migrating across to that version.

Thanks!

**Comment by joshgav** [comment]
Thanks for the insightful feedback as always @tombuildsstuff, cc @ravbhatnagar from Resource Manager service team. Azure APIs don't automatically transform requests and use updated versions cause semantic consistency between versions isn't guaranteed and we may not get the user's intention right. Also, the old API version is still live and supported for *direct* (i.e. without transformation) use.

Glad to see you were able to address this in Terraform by upgrading to the later API in https://github.com/terraform-providers/terraform-provider-azurerm/pull/1284.
