### ISSUE TITLE
Update track2 armmonitor package to 2021-08-01 to support Azure Monitor Log Alert V2 

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#18960]
### Feature Request

Azure Monitor Log Alert is a monitor resource under API path: `/SUBSCRIPTIONS/{}/RESOURCEGROUPS/{}/PROVIDERS/MICROSOFT.INSIGHTS/SCHEDULEDQUERYRULES/{}`. Current `armmonitor` is using API version 2018-04-16, which corresponds to the "old" version of that resource. While there is a new version (v2) for it since 2020-05-01, which has breaking changes on the data model, see [this](https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-common-schema-definitions#monitoringservice--log-alerts-v2) and [this](https://cloudadministrator.net/2021/11/04/azure-monitor-log-alert-v2/) for details.

We have an app which wants to manage both the v1 and v2 monitor log alerts resources. This means we would like to use both API versions in a Go module. As current version of the `armmonitor` is v0, which means it requires to update to v1 with the 2018-04-16 version, and then upgrade it to v2 by using the 2020-05-01 version.

**Comment by tadelesh** [comment]
@xboxeer Monitor contains preview swagger in tags that prevent us release the stable SDK. Could you help to contact with service team to see if the service is GA? Also, I wonder when will .NET SDK release stable monitor?

**Comment by magodo** [comment]
@tadelesh Can you release 2021-08-01, which is a stable version from its naming?

**Comment by tadelesh** [comment]
> @tadelesh Can you release 2021-08-01, which is a stable version from its naming?

`2021-08-01` may only contains a sub-set of monitor operation and we need to release SDK module with complete RP operations. We are working with monitor team to see how to release the stable version.

**Comment by magodo** [comment]
@tadelesh One Go module can use either the old version or this new v0.8.0 armmonitor, which doesn't meet my requirement here that we want to manage both versions of monitor log alerts.

**Comment by tadelesh** [comment]
I see. For the preview modules, it seems impossible. Could you help to explain the reason you need to use the old version?

**Comment by magodo** [comment]
@tadelesh It is explained in the description of this issue.

**Comment by tadelesh** [comment]
I mean why the app could not migrate to the new version but need to use two version paralleled.

**Comment by magodo** [comment]
The app basically `GET` Azure resources, because both versions exist in Azure, that means we need to be able to `GET` for both.
