### ISSUE TITLE
Support `UserDelegationCredential` in BlobSASSignatureValues.NewSASQueryParameters and on ServiceClient

### ISSUE THREAD

**Issue by bmorck** [Azure/azure-sdk-for-go#18976]
### Feature Request

Within the previous [azblob SDK](https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob), there was support for a UserDelegationCredential. This credential could be supplied to [BlobSASSignatureValues.NewSASQueryParameters](https://github.com/Azure/azure-storage-blob-go/blob/v0.15.0/azblob/sas_service.go#L45) and is returned from [ServiceURL.GetUserDelegationCredential](https://github.com/Azure/azure-storage-blob-go/blob/v0.15.0/azblob/url_service.go#L33) or created using [NewUserDelegationCredential](https://github.com/Azure/azure-storage-blob-go/blob/v0.15.0/azblob/user_delegation_credential.go#L10) by supplying a UserDelegationKey. 

Currently, within the new azblob SDK the [UserDelegationKey is supported](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azblob/v0.4.1/sdk/storage/azblob/zz_generated_models.go#L1000) but is not used in any methods. Additionally there is a comment on  BlobSASSignatureValues.NewSASQueryParameters that indicated that `UserDelegationCredential` can be used, [but it only accepts a `SharedKeyCredential`](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azblob/v0.4.1/sdk/storage/azblob/zc_sas_service.go#L51)

> NewSASQueryParameters uses an account's StorageAccountCredential to sign this signature values to produce the proper SAS query parameters. See: StorageAccountCredential. Compatible with both UserDelegationCredential and SharedKeyCredential

Due to this, we would like the `UserDelegationCredential` to be supported on the ServiceClient (as it was supported on the ServiceURL in the previous azblob SDK, and in `BlobSASSignatureValues.NewSASQueryParameters`. 

Currently we are generating User Delegation Key using the [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/get-user-delegation-key) and manually generating the User Delegation SAS using the User Delegation Key returned from the API call. This is a verbose method of constructing the SAS and using the SDK would allow for a simpler and more readable method of working with User Delegation SAS.

**Comment by zezha-msft** [comment]
Thanks for the feature request, it is being actively worked on.

**Comment by siminsavani-msft** [comment]
Hi @bmorck ! We have released the User Delegation feature (https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv0.5.0) today. Please give it a try and let us know if you have any questions!

Examples can be found here:
https://github.com/Azure/azure-sdk-for-go/blob/7a3989f70fa6c2d4376d0c72c01b5afc32b527f7/sdk/storage/azblob/service/examples_test.go#L286
