### ISSUE TITLE
Support GetSASURL for User Delegation SAS within ContainerClient 

### ISSUE THREAD

**Issue by bmorck** [Azure/azure-sdk-for-go#18977]
### Feature Request

Currently [ContainerClient.GetSASURL](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azblob/v0.4.1/sdk/storage/azblob/zc_container_client.go#L234) only supports Service SAS. This means that `ContainerClient.GetSASURL` will only supply a SAS if the client was authenticated using a Shared Key.

We would like to be able to call `GetSASURL` and receive a User Delegation SAS if the ContainerClient was authenticated using Azure Active Directory. 

Our use case does not use Shared Keys as they are long-lived credentials and provide less fine-grained permissions than Azure Active Directory. We will also be using SAS as it provides short-lived configurable access to resources. 

Additionally, I have posted another issue (https://github.com/Azure/azure-sdk-for-go/issues/18976) to support User Delegation Credentials.

**Comment by zezha-msft** [comment]
Thank you for the feature request. It is being addressed in this PR: https://github.com/Azure/azure-sdk-for-go/pull/19141

**Comment by jhendrixMSFT** [comment]
This has been added in `azblob@v0.5.0`
