### ISSUE TITLE
Cosmos DB: Support for Preferred Regions

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-go#18984]
Support Preferred Regions on configuration to route operations to the selected regions.

Same feature exists on other SDKs: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-sdk-availability

Requires https://github.com/Azure/azure-sdk-for-go/issues/18983

Requirements:

* Have a **Public API** surface in ClientOptions that allows the user to set the PreferredRegions. This step requires API review and approval.
* As part of the Client creation, create an associated GlobalEndpointManager (internal to the client) that takes the defined preferred regions as part of the input.

**Comment by jay-most** [comment]
Notes: Time 3-4 weeks -> T-Shirt Size - M (work with Joel. shape the public API surface. + 3d-5d)
