### ISSUE TITLE
Cosmos DB: Add GlobalEndpointManager

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-go#18983]
Add internal GlobalEndpointManager to handle:

Requires https://github.com/Azure/azure-sdk-for-go/issues/18982

* Periodic account information refresh (5M)
* Marking regions as unavailable

Reference: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs

**Comment by jay-most** [comment]
3 - 4 weeks - > T-Shirt  L

**Comment by ealsur** [comment]
Design content:



![Image](https://github.com/Azure/azure-sdk-for-go/assets/1633401/f2a734f1-1679-497f-b605-d5247fc514bd)


LocationCache is already present (done in https://github.com/Azure/azure-sdk-for-go/issues/18982) -> https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/cosmos_location_cache.go

GEM just needs to wrap the LocationCache Marking of unavailable and provide background refresh capabilities that wire the Account Properties (regions + MultiMaster) into the locationCache
