### ISSUE TITLE
Cosmos DB: Diagnostics for operations

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-go#18986]
Similarly to other Cosmos DB SDKs, expose Diagnostics for each operation that includes relevant troubleshooting information.

Initially it can be scoped to:

* Relevant client configuration (like which Preferred Regions)
* All requests involved in an operation, including retries handled by cross-region management

**Comment by jay-most** [comment]
Notes: Time :)

**Comment by ealsur** [comment]
https://github.com/Azure/azure-sdk-for-go/pull/22288 Added logging support and examples.

**Comment by simorenoh** [comment]
https://github.com/Azure/azure-sdk-for-go/pull/22593 and https://github.com/Azure/azure-sdk-for-go/pull/22598 add logging of account and client settings
