### ISSUE TITLE
Automation rule Trigger Logic Enums for Incident Created, Updated and Alert Created

### ISSUE THREAD

**Issue by deepanshumarwah** [Azure/azure-sdk-for-go#18992]
### Feature Request

Currently there are no enums for Sentinel `AutomationRuleTriggerLogic` for `when` and `on` condition. The portal currently supports 3 trigger cases as per below screenshot. 
![image](https://user-images.githubusercontent.com/55777311/187612092-5aa25b8f-1241-43af-8fa3-cd6d3f0f7468.png)

However, the SDK doesn't contain logic for these 3 cases. It should be something similar to `ActionTypeBasicAutomationRuleAction`

https://github.com/Azure/azure-sdk-for-go/blob/661e00897e7823e520c1301918c3599641f8af17/services/preview/securityinsight/mgmt/2022-01-01-preview/securityinsight/enums.go#L25-L34

I understand that I need to create a separate issue for rest api in different repo. But just for reference the api also currently does not support other 2 trigger conditions. 

https://github.com/Azure/azure-rest-api-specs/blob/ad5f2295c36461875b75f83e9579eadddf73d356/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json#L6381-L6397

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

@amirkeren Could you please look into this and provide an update once you get a chance ?

**Comment by deepanshumarwah** [comment]
Hi Team 

Any eta on this ?

**Comment by amirkeren** [comment]
I'll contact the relevant team and have them follow up here

**Comment by NatashaDorfman** [comment]
Hi @deepanshumarwah & @amirkeren 

1. SDKs were released last time 6 months ago. Triggers for _update incident_ and _alert created_ were introduced later. I'll update this issue, when next version of SDKs will be released.
2. API does support all 3 trigger conditions. _On_ condition is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-09-01-preview/AutomationRules.json#L1276), _when_ [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-09-01-preview/AutomationRules.json#L1298)

**Comment by deepanshumarwah** [comment]
> Hi @deepanshumarwah & @amirkeren
> 
> 1. SDKs were released last time 6 months ago. Triggers for _update incident_ and _alert created_ were introduced later. I'll update this issue, when next version of SDKs will be released.
> 2. API does support all 3 trigger conditions. _On_ condition is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-09-01-preview/AutomationRules.json#L1276), _when_ [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-09-01-preview/AutomationRules.json#L1298)

Thanks @NatashaDorfman

**Comment by navba-MSFT** [comment]
Thanks @NatashaDorfman .

@deepanshumarwah Please let us know if you have any follow-up questions on this.

**Comment by NatashaDorfman** [comment]
New [GO SDK]( https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/securityinsights/armsecurityinsights/v2@v2.0.0-beta.2) was released.

Cc  @deepanshumarwah & @amirkeren.

**Comment by deepanshumarwah** [comment]
Thank you so much @NatashaDorfman . Much Appreciated
