### ISSUE TITLE
ContainerServicesClient.ListOrchestrators is no longer available

### ISSUE THREAD

**Issue by mega-alex** [Azure/azure-sdk-for-go#19007]
### Service Package Request

https://docs.microsoft.com/en-us/rest/api/aks/container-services/list-orchestrators?tabs=HTTP

This used to be available in the older `"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-09-01/containerservice"` package as `ContainerServicesClient.ListOrchestrators(...)` but appears to be missing from the new ARM packages.

**Comment by tadelesh** [comment]
@mega-alex Thanks for your feedback. Firstly, we've deprecated the package `github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-09-01/containerservice`. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice). See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Secondly, it seems after `2020-09` version, `location.json` has been removed from the service release tag. I'll check with service team.

**Comment by mega-alex** [comment]
I followed the migration guide, but what I was saying is there is no equivalent way to list all available orchestrator versions in the new ARM SDKs. I can't find any reference to that endpoint or similar method names anywhere in the new packages. There is a way to list available upgrades to a cluster, but no way to just list what versions of kubernetes are available without a cluster provisioned.

**Comment by tadelesh** [comment]
@mega-alex Thanks for your explanation. We'll reach out container service team to see why they remove the swagger for the recent version.

**Comment by navba-MSFT** [comment]
@mega-alex Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mega-alex In the package [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice), We have the **type** [**ManagedClusterPoolUpgradeProfile**](https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/containerservice/armcontainerservice/v1.0.0/sdk/resourcemanager/containerservice/armcontainerservice/zz_generated_models.go#L1022) which provides the list of available upgrade versions.

More Info [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice#ManagedClusterPoolUpgradeProfile).

```
type ManagedClusterPoolUpgradeProfile struct {
	// REQUIRED; The Kubernetes version (major.minor.patch).
	KubernetesVersion *[string](https://pkg.go.dev/builtin#string) `json:"kubernetesVersion,omitempty"`

	// REQUIRED; The operating system type. The default is Linux.
	[OSType](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice#OSType) *OSType `json:"osType,omitempty"`

	// The Agent Pool name.
	Name *[string](https://pkg.go.dev/builtin#string) `json:"name,omitempty"`

	// List of orchestrator types and versions available for upgrade.
	Upgrades []*[ManagedClusterPoolUpgradeProfileUpgradesItem](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice#ManagedClusterPoolUpgradeProfileUpgradesItem) `json:"upgrades,omitempty"`
}
```
Could you please check this and let us know if that serves your requirement ? Awaiting your reply.

**Comment by mega-alex** [comment]
You need to have an active cluster already to check that correct? In previous versions of the SDK there was a method to list orchestrator versions that would list all K8s version regardless of if you had a deployed cluster or not. 

This functionality was previously available with 
```
func (client ContainerServicesClient) ListOrchestrators(ctx context.Context, location string, resourceType string) (result OrchestratorVersionProfileListResult, err error) {
```

But there does not seem to be an equivalent way to get that information, the actual API it would need to hit is https://docs.microsoft.com/en-us/rest/api/aks/container-services/list-orchestrators?tabs=HTTP

**Comment by navba-MSFT** [comment]
@mega-alex Thanks for getting back. I will check this further and get back to you.

**Comment by navba-MSFT** [comment]
@mega-alex I had reached out to the product owners and got their reply. As far as I know, the list orchestrator versions method is not included in the track 2 Go SDK. The reason behind this is that the track 2 go SDK no longer supports multi api, and always uses the latest API tag defined in swagger to generate the SDK. Unfortunately, the specification corresponding to the list orchestrator API is only defined in the [location.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-04-01/location.json#L37) of the 2019-04-01 API version, which is deprecated and has not been sorted out and migrated to the [managedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-07-01/managedClusters.json) of the latest API version.

**Comment by mega-alex** [comment]
Is there any timeline for supporting this? It is pretty essential for us to be able to list available kubernetes versions.

**Comment by navba-MSFT** [comment]
@mega-alex Thanks for your reply. For the list orchestrator API, Our Product Owners have opened this [PR](https://github.com/Azure/azure-rest-api-specs/pull/20709) to add a new version of the locations.json file, which is based on the [file in version 2019-04-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-04-01/location.json), So please track this PR for the fix release. Please let us know if you have any further questions on this.
