### ISSUE TITLE
CostManagement Pagination Increase from 1000

### ISSUE THREAD

**Issue by drkennetz** [Azure/azure-sdk-for-go#19002]
### Feature Request

Hi team,

I have recently been writing a CostManagement app that can report on all the costs in my subscription. Using my App, I have been able to tease out a nice results set for date, cost by resourceId on that day, resource group, resource type, resource id:

```
2022-08-02 7.332697854251375 rg-test Microsoft.Storage/storageAccounts storageAcctest
...
```
The issue is, the app only gives me the first 1000 results from the QueryDefinition. I then tried to overcome that by running the query on each day in the time range passed, but some days have even more than 1000 results (and this process is substantially slower). I then figured I'm being blocked by some internal pagination. When I went to find out where to change it, I found out that a `QueryClient` can in fact take `*QueryClientUsageOptions`, so I figured this may be where I can pass in pagination increases, but this isn't implemented. It's just an empty struct.

I do see that the response of the QueryClient.Usage() has a `*NextLink` although I do not know if that can be followed to the next result set.

It would be nice if we could increase the pagination size. Thanks, and let me know if you need any more information!

**Comment by drkennetz** [comment]
I have a working PR for this, but I don't know how to update the autorest.go to include changes and these are generated files. Any help would be appreciated!

**Comment by lirenhe** [comment]
@drkennetz,  as this ask is for service team, could you create a support ticket directly for your ask? 
https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by drkennetz** [comment]
@lirenhe It is both a service request and a feature request. You can get around the pagination issue by adding a `Skiptoken` to the `QueryClientOptions` struct, which allows you to receive the next result. I have this implemented locally, but I don't know how (or where) to make the change in the code that auto-generates this code, and I was wondering if you all could help out with that (even if it was to just point me to docs about what to change in the generator).

The addition is about 12 lines of code, and the affected files are the zz_generated_query_client.go file, and the zz_generated_models.go file.

**Comment by drkennetz** [comment]
@tadelesh happy to help with this, I just need some help with the autorest part. It's a really easy implementation.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by navba-MSFT** [comment]
@ccmixpdevs  Could you please look into this and provide an update ? Thanks in advance.

**Comment by drkennetz** [comment]
@navba-MSFT Thanks for the follow up Adding a SkipToken to the QueryClientUsageOptions and adding the URI parsing to zz_generated_query_client.go can at least allow users to retrieve all results for a time frame with some additional code, even if pagination isn't increased by the service.

**Comment by tadelesh** [comment]
@drkennetz Thanks for your feedback. From the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2021-10-01/costmanagement.json#L950), it seems this API is not defined as a pageable operation. But the response model has `nextLink` property which always belong to a pageable result. And if we want to add `SkipToken` param you mentioned, we also need to update the swagger definition first and auto-generated the SDK. So, we'll let service team to have a look first.

**Comment by drkennetz** [comment]
@tadelesh oh I see, thank you for the clarification. I look forward to hearing back!

**Comment by drkennetz** [comment]
You can iterate over NextLink until it is exhausted with something like 

for nextlink {
...
}

This has been my workaround until it gets implemented in the swagger spec. I tried a PR but I am unfamiliar with swagger and no one really worked with me on it.

**Comment by jkroepke** [comment]
@drkennetz do you can provide a full example?
