### ISSUE TITLE
supporting latest version of eventhub.namespace

### ISSUE THREAD

**Issue by ayalonsivan** [Azure/azure-sdk-for-go#19020]
### Service Package Request

Hi,

I am currently trying to get all the properties for Microsoft.EventHub namespaces.
According to Azure API , the latest stable version (2021-11-01)  properties supports encryption and private endpoint connection :

@ https://docs.microsoft.com/en-us/azure/templates/microsoft.eventhub/2021-11-01/namespaces?pivots=deployment-language-bicep

In the SDK, the latest supported version for eventhub namespaces is 2017, which does not support these kinds of properties.

Does the SDK have a timeline for implementing the 2021 version?

**Comment by jhendrixMSFT** [comment]
I believe this is supported in our latest `armeventhub` module.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub

**Comment by richardpark-msft** [comment]
Yeah, this is purely an ARM (management plane) feature, as we don't export an ATOM layer for EH. Removing myself for now, but I can re-add if there's something I can provide here.

**Comment by tadelesh** [comment]
@ayalonsivan You could try . It uses the API version `2021-11-01`.

> I believe this is supported in our latest `armeventhub` module.
> 
> https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub

@ayalonsivan This package use API version `2021-11-01`. You could try it. If any further questions, feel free to leave a comment.
