### ISSUE TITLE
SDK support for Metrics (Data plane)

### ISSUE THREAD

**Issue by simongottschlag** [Azure/azure-sdk-for-go#19021]
Hi!

I've been trying to figure out if the SDK supports Metrics (Data plane) but haven't found anything about it: https://docs.microsoft.com/en-us/rest/api/monitor/metrics%20(data%20plane)/create?tabs=HTTP

Am I missing something obvious or doesn't it exist?

Thanks!

**Comment by jhendrixMSFT** [comment]
I believe this is being tracked in https://github.com/Azure/azure-sdk-for-go/issues/18776.  @scottaddie is this correct?

**Comment by scottaddie** [comment]
Joel's comment above is accurate. Keep an eye on that issue for tracking purposes. The current GA target for the Azure Monitor Query library for Go is November. The library [already exists for .NET, Java, JavaScript, and Python](https://devblogs.microsoft.com/azure-sdk/announcing-the-new-azure-monitor-query-client-libraries/).

**Comment by jhendrixMSFT** [comment]
Closing as this is being tracked already.
