### ISSUE TITLE
[azservicebus] timeout error when accepting next session is not exported type

### ISSUE THREAD

**Issue by arussellf5** [Azure/azure-sdk-for-go#19039]
pkg: github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
version: v1.1.0
go version: go 1.18.5

In testing, if I call the `azservicebus` client's `AcceptNextSessionForSubscription()` method and there is no session to accept, I get the following timeout error:

```
*Error{Condition: com.microsoft:timeout, Description: The operation did not complete within the allotted timeout of 00:01:04.9800000. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:0d5d0118-2aaa-4b60-92af-7a3882f93837_B0, SystemTracker:nalb-int-tests:Topic:14prizb4|0tzhfbtr, Timestamp:2022-09-06T19:25:22 TrackingId:03ff398b38f8438fba50b343d7b09534_G18, SystemTracker:gateway7, Timestamp:2022-09-06T19:25:22, Info: map[]}
```

This timeout error formerly contained a `*amqp.Error` which allowed for type checking. The timeout error is no longer exported, so I cannot check the type using `errors.Is()` or `errors.As()`, and specifically handle the case of a foreseeable timeout. The [documentation](https://github.com/Azure/azure-sdk-for-go/blob/sdk/messaging/azservicebus/v1.1.0/sdk/messaging/azservicebus/client.go#L306) for the `AcceptNextSessionForSubscription()` method claims that "if the operation fails it can return an *azservicebus.Error type if the failure is actionable." Would you please fix the current implementation so that the timeout error is exported?

**Comment by arussellf5** [comment]
Also as a footnote, the timeout occurred over 7 minutes after the request was made, not "within the allotted timeout of 00:01:04.9800000" as reported on the error message.

**Comment by richardpark-msft** [comment]
Hi @arussellf5, I've got a fix for this. We do have an exported error type (*azservicebus.Error), which has a Code field. There's a few examples in the example*.go's in that PR if you want to see what it will look like.

To your second question:

> Also as a footnote, the timeout occurred over 7 minutes after the request was made, not "within the allotted timeout of 00:01:04.9800000" as reported on the error message.

This is happening because we consider the com.microsoft:timeout error a retryable error, which means the error message you're seeing is a result of the last attempt and comes from the service.

**Comment by arussellf5** [comment]
@richardpark-msft thanks for responding so quickly to this! Truly appreciated.

**Comment by ryepup** [comment]
Any idea when this will be released?

**Comment by richardpark-msft** [comment]
We release monthly (if there are changes). This one will go out in the second week of October, by our release schedule.
