### ISSUE TITLE
RoleAssignmentsClient.Create in armauthorization is not idempotent

### ISSUE THREAD

**Issue by rht-b** [Azure/azure-sdk-for-go#19060]
Creating the same role assignment twice results in success the first time, but the second time results in an error: `The role assignment already exists.` The input to roleAssignmentsClient.Create has same (`Scope`, `RoleAssignmentGuid`, Properties{`PrincipalId`, `RoleDefinitionId`}) in different invocations.

It happens with `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization v1.0.0`, for API Version is `2015-07-01`. We had also tried with API Version `2020-10-01-preview` by setting `api-version` queryfilter with ClientOptions by overriding Transport.

This issue has already been address for azure-cli https://github.com/Azure/azure-cli/issues/8568, but still exists in go sdk.

RoleAssignmentClient.Create in armauthorization should be idempotent and creating role assignment (which pre-exists) with a role on a given scope for a user managed identity (with either same or different role assignment guid) should not result in an error.

**Comment by tadelesh** [comment]
@rht-b Thanks for your feedback. Our SDK is generated from the service API definition and will not add any specific logic which is a little bit different from the CLI. We'll let service team to help to resolve the idempotent issue from the service backend.

**Comment by tadelesh** [comment]
@navba-MSFT Could you help to reach out to the correct team.

**Comment by navba-MSFT** [comment]
@tadelesh Adding Service team to look into this.

 @darshanhs90, @AshishGargMicrosoft please look into this issue and provide your pointers. Thanks in advance.
