### ISSUE TITLE
armsecurity.ContactsClient is using an old API version

### ISSUE THREAD

**Issue by shai-binyamin-sysdig** [Azure/azure-sdk-for-go#19089]
### Feature Request
armsecurity.ContactsClient is currently implemented using API version 2017-08-01-preview, while a new API version exists (2020-01-01-preview) which returns more properties.
Would it be possible to use the newer API version?

**Comment by tadelesh** [comment]
@shai-binyamin-sysdig Thanks for reaching out. I've asked service team to raise the SDK release request. Please wait for the next SDK version.

**Comment by tadelesh** [comment]
@navba-MSFT I've reached out to @simanor on Teams but has not got response yet.

**Comment by SivM** [comment]
ACK.
ETA - end of October (due to local holidays).

**Comment by navba-MSFT** [comment]
Thanks @SivM 
 @shai-binyamin-sysdig  @tadelesh  Hope you had a chance to look at the above comment about the ETA for the release. If you have any follow-up question, please feel free to ask.

**Comment by tadelesh** [comment]
Thanks @navba-MSFT. We'll release the new version after receiving the release request.

**Comment by lirenhe** [comment]
Let's close this item after we release the new package.

**Comment by navba-MSFT** [comment]
@shai-binyamin-sysdig > ACK. ETA - end of October (due to local holidays).

Hello @SivM, Could you please let us know the status on this ? Awaiting you reply.

**Comment by simanor** [comment]
Hello and sorry for the delayed response.
Release request has been submitted - https://github.com/Azure/sdk-release-request/projects/1411

**Comment by navba-MSFT** [comment]
Thanks @simanor. 

@lirenhe @tadelesh for visibility.

**Comment by navba-MSFT** [comment]
> > @lirenhe @tadelesh for visibility.
> 
> Thanks @navba-MSFT. The new package will be released before the end of this month.

@tadelesh Are there any updates on the release ?

**Comment by lirenhe** [comment]
This is released https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity@v0.9.0
Thanks @tadelesh and  @Alancere

**Comment by navba-MSFT** [comment]
Thanks @lirenhe 

@shai-binyamin-sysdig Hope this helps. Please feel free to reopen this thread if you need any further assistance. We would be happy to help.
