### ISSUE TITLE
Diagnostic Settings -  Category on the logs is null

### ISSUE THREAD

**Issue by yaminSapir** [Azure/azure-sdk-for-go#19090]
### Bug Report
- SDK function: armmonitor.NewDiagnosticSettingsClient
- apiVersion: "2021-05-01-preview"
- output : "logs": [
                    {
                        **"category": null,**
                        **"categoryGroup": "audit",**
                        "enabled": true,
                        "retentionPolicy": {
                            "enabled": false,
                            "days": 0
                        }
                    },
                    {
                        "category": null,
                        "categoryGroup": "allLogs",
                        "enabled": true,
                        "retentionPolicy": {
                            "enabled": false,
                            "days": 0
                        }
                    }
                ],

It seems that instead of “category”, the api returns “categoryGroup”, but on the SDK there is no such parameter.

- What happened?
- When we’re trying to get the diagnostic settings, the category on the logs is null.
It seems that instead of “category”, the api returns “categoryGroup”, but on the SDK there is no such parameter.

- What did you expect or want to happen?
the function needs to return non-null category
- How can we reproduce it?
create diagnostic settings for Azure Key Vault:
client, _ := armmonitor.NewDiagnosticSettingsClient(cred, &arm.ClientOptions{
      ClientOptions: policy.ClientOptions{
         Transport: &apiVersionTransporter{
            apiVersion: "2021-05-01-preview",
            httpClient: http.DefaultClient,
         },
      },
   })
   diagnosticSettings, err := client.List(c.context, s.id, nil)
   if err != nil {
      return err
   }

**Comment by lirenhe** [comment]
@tadelesh could you help to take a look?

**Comment by tadelesh** [comment]
@yaminSapir Sorry for delayed reply. The API-version in the SDK is not `2021-05-01-preview`, but `2017-05-01-preview`. We will let service team to update the release tag and release the new version.

**Comment by navba-MSFT** [comment]
@yaminSapir Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
Adding the Service team.

@sameergMS, @dadunl  Please look into this ask and provide an update once you get a chance. Thanks in advance.

**Comment by rushabh268** [comment]
We are looking for category in the diagnostic setting response and not seeing it - any update would be helpful!

**Comment by tadelesh** [comment]
We've released a new [version](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor@v0.8.0) of armmonitor package which contains the latest diagnostic setting API. Please upgrade and have a try.
