### ISSUE TITLE
Geo-redundancy retry policy for storage

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#19107]
Current implementation is missing primary/secondary storage locations in retry policy.

**Comment by juanmaia** [comment]
Is this planned to be implemented at the client level?

**Comment by estebanreyl** [comment]
Are there any updates on this? I was trying to see if I can implement this sort of geo redundancy on the client to move ACR's remaining unmigrated workloads to the new table SDK but ran into difficulties adding a fallback to the pager abstraction. Any updates would be appreciated.

**Comment by jhendrixMSFT** [comment]
@vibhansa-msft the bot closed this due to age. If this is still on the radar for storage can you please open a new issue and link to this one?
