### ISSUE TITLE
Resource verification in WWW-Authenticate causes failures when using test doubles

### ISSUE THREAD

**Issue by nagyesta** [Azure/azure-sdk-for-go#19109]
### Bug Report

- Using these dependencies:
  - github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.3
  - github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys v0.7.0
  - github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.10.0
- output of `go version`: go version go1.18.2 linux/amd64

- What happened?

Renovate opened a PR for updating azsecrets to v0.10.0. The tests [started to break](https://github.com/nagyesta/lowkey-vault-example-go/actions/runs/3048452802/jobs/4913532172) as resource verification does not allow non-original resources to be used such as `resource="https://localhost:8443"` when requests are sent to `https://localhost:8443/secrets/secret-name/`.

I am getting this error:
> failed to create a secret: the challenge resource "https://localhost:8443" doesn't match the requested domain

I think it is due to these lines: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/keyvault/internal/challenge_policy.go#L188-L190

```go
        if !strings.HasSuffix(req.URL.Host, "."+parsed.Host) {
		return &challengePolicyError{err: fmt.Errorf(`the challenge resource "%s" doesn't match the requested domain`, scope)}
	}
```

- What did you expect or want to happen?

I have expected the tests to pass, just like on the `main` branch even in use-cases with local test doubles.

As it is more complicated for any test double to always use a domain name which contains a `.` (like: `vault.localhost`) and make sure that the requests still end up on `localhost` (for example it is harder to set up on CI), this check enforcing that the actual host used by the vault will end with a `.`+`<resource.host>` makes testing harder. If the exact match of the host names would be allowed too, or even better the exact match of the host authority, then it could solve the issue.

- How can we reproduce it?

Check out this branch: https://github.com/nagyesta/lowkey-vault-example-go/tree/renovate/github.com-azure-azure-sdk-for-go-sdk-keyvault-azsecrets-0.x

Follow the instructions in the [Readme.md](https://github.com/nagyesta/lowkey-vault-example-go/tree/renovate/github.com-azure-azure-sdk-for-go-sdk-keyvault-azsecrets-0.x#usage)

- Anything we should know about your environment.

It is using a local test double that will always return the base URL of the request (e.g. `https://localhost:8443`) as `resource` value in the `WWW-Authenticate` response header. The same test double is working well with the Java, .Net and Python SDK-s, I assume those are not as strict.

**Comment by chlowell** [comment]
Thanks for opening this. We released new Key Vault clients today with an option to disable this verification. For example, using `azkeys`:
```go
azkeys.NewClient(vaultURL, credential, &azkeys.ClientOptions{DisableChallengeResourceVerification: true})
```
(the API is the same for `azcertificates` and `azsecrets`)

See https://aka.ms/azsdk/blog/vault-uri for more information about what motivated us to add this verification. It's okay to disable it in local testing but please consider carefully before disabling it in production.

**Comment by nagyesta** [comment]
Thank you @chlowell ! Just seen the release notes for all of them, I think it should work. Thank you for the flexibility and helping local test double usage!

**Comment by nagyesta** [comment]
Thanks again @chlowell , I have updated all example projects and they are working well! The only minor issue I have noticed was with the blog post you have linked. The Java example says:
```java
String vaultUrl = "https://myvault.vault.azure.net";
String credential = new DefaultAzureCredentialBuilder().build();
SecretClient secretClient = new SecretClientBuilder()
    .vaultUrl(vaultUrl)
    .credential(credential)
    .disableChallengeResourceVerification(true)
    .buildClient();
```
The real code does not receive the boolean parameter, so it should look like this instead:
```java
String vaultUrl = "https://myvault.vault.azure.net";
String credential = new DefaultAzureCredentialBuilder().build();
SecretClient secretClient = new SecretClientBuilder()
    .vaultUrl(vaultUrl)
    .credential(credential)
    .disableChallengeResourceVerification()
    .buildClient();
```

Anyway, it worked well, thank you for fixing it!

**Comment by heaths** [comment]
@nagyesta thanks for pointing that out. It was changed last minute. I will update the blog post.
