### ISSUE TITLE
Customer Feedback 2022/09/16

### ISSUE THREAD

**Issue by cjoakim** [Azure/azure-sdk-for-go#19139]
### Service Package Request

I'm submitting this request, with the following questions, on behalf of a customer of ours.

1) Is "direct mode" supported in the Go SDK for CosmosDB SQL API?   If not, what is the timeline?
2) Are cross-partition queries supported, with the x-ms-documentdb-query-enablecrosspartition header?
3) Are "Bulk Executor" operations supported, similar to the C# and Java SDKs?   If not, what is the timeline?
4) Are query metrics supported in the Go SDK, similar to the other language SDKs?

Sincerely,
Chris Joakim
CosmosDB GBB
chjoakim@microsoft.com

**Comment by ealsur** [comment]
1. No, there are only 2 Cosmos SDKs that have Direct mode: .NET and Java. There are currently no plans to provide Direct mode on the Go SDK.
2. See https://github.com/Azure/azure-sdk-for-go/issues/18578
3. No. There are no planned timelines yet, see https://github.com/orgs/Azure/projects/103/views/13 for more details on upcoming planned work. If a customer wants this feature, they can create the feature request in this repository and it will triaged and analized.
4. Query Metrics are part of the service response and already present on the Query response: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/cosmos_query_response.go#L20
