### ISSUE TITLE
[azappconfig] GetAll configuration settings returns older data

### ISSUE THREAD

**Issue by pravinpushkar** [Azure/azure-sdk-for-go#19135]
### Bug Report

We want to retrieve all configuration settings data from the `config store`.  Code is similar to the suggested sample code provided at this link - https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/data/azappconfig#list-configuration-setting-revisions

See our implemented code here - https://github.com/dapr/components-contrib/blob/42fc9ae0f2115db22b758aefd056d2ad1c56be4f/configuration/azure/appconfig/appconfig.go#L200

Below curl commands are executed w.r.t our project `dapr`  - 

For update -

See below logs - 
For update - 

➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2\?key\=config1.   -> Getting individual key -  response is as expected

**{"config1":{"value":"val111"}}**%
➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2      -> Getting all keys -  Response is unexpected

**{"config1":{"value":"val1"}**,"config2":{"value":"val2"},"config3":{"value":"val3"},"config4":{"value":"1"},"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%

Similar out output for deleted keys also - 
➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2     -> Getting all keys -  Response is unexpected

{"config1":{"value":"val1"},"config2":{"value":"val2"},"**config3":{"value":"val3"}**,"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%      

➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2**\?key\=config3**         -> Getting individual key -  response is as expected

{"errorCode":"ERR_CONFIGURATION_GET","message":"fail to get [config3] from Configuration store pravin-app-config-2: GET https://pravin-app-config-2.azconfig.io/kv/config3\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 Not Found\

**Comment by RickWinter** [comment]
The API you are calling is NewList**Revisions**Pager.  That API returns all the revisions of settings which match the filter.  If I understand correctly, you only want the current revisions.  Those can be retrieved by using NewList**Settings**Pager

**Comment by pravinpushkar** [comment]
@RickWinter I can see the this API is not available with v0.4.0 and saw this got merged only few days back here - https://github.com/Azure/azure-sdk-for-go/pull/19120

Any suggestion on how to use this API or when will the next release be available ?

**Comment by RickWinter** [comment]
Go allows you to grab the latest change or in fact any change.  For this particular change you can pull the module using this command:
`go get github.com/Azure/azure-sdk-for-go/sdk/data/azconfig@4d445978fe75fae0e41b43100591da3cd1746722`

**Comment by pravinpushkar** [comment]
@RickWinter I am getting the following error while trying to use the commit - 

```
➜  components-contrib git:(fix/configapi_getall) ✗ go get github.com/Azure/azure-sdk-for-go/sdk/data/azconfig@4d445978fe75fae0e41b43100591da3cd1746722

go: module github.com/Azure/azure-sdk-for-go@4d445978fe75fae0e41b43100591da3cd1746722 found (v65.0.1-0.20220914204640-4d445978fe75+incompatible), but does not contain package github.com/Azure/azure-sdk-for-go/sdk/data/azconfig
```
I have github.com/Azure/azure-sdk-for-go v65.0.0+incompatible and tried with v66.0.0 but same error.
Is it possible for a new beta release v0.4.1 ?

**Comment by pravinpushkar** [comment]
Thank you very much for the help @RickWinter. I have pointed our sdk to this commit and getAll works as expected.

**Comment by pravinpushkar** [comment]
@RickWinter Re-opening this again for a query. Is it possible to release 0.4.1 or next version with this fix ? We have a release in a week's time and it will be great to use a release instead of a commit.
