### ISSUE TITLE
More function on generic resources for `armresources` package

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#19149]
### Feature Request

We are currently building a library based on the track2 SDK. The tool aims to fill in the gap that Azure resource list API only returns ARM tracked resources, but not the proxy resources. In order to discover the proxy resources, we will recursively call `GET` (i.e. list) on the *known" child resource types of the existing tracked resources. E.g. given a vnet, we will call `GET` against `<vent>/subnets` to discover any child resourcse.

Currently, there is no way to do this easily using the track2 SDK. We would want something similar to [`GetByID`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources#Client.GetByID), but returns a [`ClientListResponse`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources#ClientListResponse), and with paging taken into consideration.

**Comment by jhendrixMSFT** [comment]
Given that our SDKs are generated from OpenAPI specs, if the spec doesn't describe such a contract, we won't generate it.

**Comment by magodo** [comment]
Understand this fact. In this case, I have to vendor the code from SDK and modify based on it. E.g. https://github.com/magodo/azlist/tree/main/armresources.

**Comment by jhendrixMSFT** [comment]
I see.  Presumably the only thing that prevents you from wrapping the generated client and adding your own method(s) is that you don't have access to the client's pipeline yes?

**Comment by magodo** [comment]
Probably yes, and also the `client.host`.
