### ISSUE TITLE
How to run query in log analytics workspace?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-sdk-for-go#19166]
Team,

Could you please suggest the procedure to run Kusto query in log analytics workspace using this sdk.. As per my understanding we need to import operationalinsights package but, its been hours I'm unable to to find the url to it.

How to consume its go module. Should I import this one
`github.com/Azure/azure-sdk-for-go/services/operationalinsights/v1/operationalinsights
`
Is there any doc available to run kusto query inside log analytics workspace. Please suggest. Thank you.

Regards

**Comment by smartaquarius10** [comment]
@gracewilcox oh great. Thank you so much. By any chance is it possible to authenticate it with AAD pod identity for using in AKS..

Actually I am writing custom metrics server in AKS where I have to use this.

**Comment by gracewilcox** [comment]
No problem! You should be able to authenticate with ADD pod identity with our [azidentity](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity) library using the [ManagedIdentityCredential](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#managed-identity) or the [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#defaultazurecredential).

The azquery docs [here](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/monitor/azquery#create-a-logs-client) show an example of creating a default credential then using it to create a LogsClient. You can then use this authenticated LogsClient for your queries. An example of creating a managed identity credential can be found [here](https://github.com/Azure/azure-sdk-for-go/blob/28e8c577ca7b6e54dcc7c81e902fb72509f745e0/sdk/azidentity/example_test.go#L31).

**Comment by gracewilcox** [comment]
Azquery also includes a separate metrics client for [querying the metrics](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/monitor/azquery#metrics-query) of a specific resource.

**Comment by smartaquarius10** [comment]
@gracewilcox , Bingo.. You're super awesome.. Thank you so so so so much.. Nailed it.. 

Will start working on this immediately. Will reach out to u if stuck.. Hope you don't mind :) 
Have a great day

**Comment by smartaquarius10** [comment]
@gracewilcox , one small thing forgot to ask.. Can we use it this library in production as I need to run horizontal pod autoscaler for which I have to use it.

**Comment by gracewilcox** [comment]
Hi! This library should work in your production environment, but azquery is currently unstable. There may be breaking changes in the coming months, as we work towards the stable release.

For running the above query, please try the [QueryWorkspace](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/monitor/azquery#logs-query) function from the LogsClient. That function runs a Kusto query against a specified log analytics workspace. The function linked above uses our separate MetricsClient which queries data from [Azure Monitor Metrics](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/data-platform-metrics) and does not use Kusto.

**Comment by smartaquarius10** [comment]
@gracewilcox , Oh ok.. No issue.. if there is any notification channel please let me know for the updates regarding stable release. Meanwhile, I'll try writing my custom metrics server and use it in our environment. In case of any issue will contact you. Have a nice day.. Take care. :)

**Comment by gracewilcox** [comment]
As an update, `azquery` is officially stable. We also now have a migration guide to move from `operationalinsights` to the `azquery` module.

[Migration Guide](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/monitor/azquery/MIGRATION.md)
