### ISSUE TITLE
Missing resources.subscriptions REST client

### ISSUE THREAD

**Issue by lzap** [Azure/azure-sdk-for-go#19167]
### Service Package Request

Hello,

I am unable to find Go client for resources.subscriptions REST call: https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/get?tabs=HTTP

Is it possible that this hasn't been implemented yet? Thanks!

**Comment by jhendrixMSFT** [comment]
I think this is the module you're looking for.

https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/resources/armsubscriptions

**Comment by lzap** [comment]
Ah, how I could miss this one, thanks!

Unfortunately, the documentation is a bit off. The main example does not work as `NewClient` no longer accepts two but three arguments. I don't know how to provide a token, credential type does not seep to implement such interface. I guess I will have to figure this out somehow:

```
cred, _ := azidentity.NewDefaultAzureCredential(nil)
client, _ := armsubscriptions.NewClient("00000000", cred, nil)
```

**Comment by lzap** [comment]
Ah figured it out, examples in Go documentation are correct! Thanks.
