### ISSUE TITLE
[Feature Request] Azure SDK for Go Readme optimize

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-go#19186]
### Feature Request

There are some issues we find when customer trying to use our new version SDK, please include below content in Golang SDK readme
1. An individual part/document of upgrading Golang to 1.18 version, and a link to this document in Golang SDK Readme
2. Add a link/Replace the SDK Reference link at the top of the Readme and navigate customer to actual Track 2 libraries list -> https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk
3. Try to remove retracted modules from `pkg.go.dev`

**Comment by tadelesh** [comment]
Issue to remove doc of retracted modules from pkg.go.dev: https://github.com/golang/go/issues/56121
