### ISSUE TITLE
How to run single kusto query using armoperationalinsights package?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-sdk-for-go#19198]
Team,

Is it possible to run a single kusto query using [this ](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/operationalinsights/armoperationalinsights#readme)package.

I don't have any log analytics query pack in my subscription. As far as I remember, the old [operationalinsights ]("github.com/Azure/azure-sdk-for-go/services/operationalinsights/v1/operationalinsights")package has that function but it is incompatible with azidentity. 

Please suggest. Thank you.

Regards,
Tanul

**Comment by jhendrixMSFT** [comment]
This looks similar to https://github.com/Azure/azure-sdk-for-go/issues/19166, did that not work?

**Comment by gracewilcox** [comment]
Hi Tanul! The names have changed over time, but if you're referring to [this](https://github.com/Azure/azure-sdk-for-go/blob/90ea274b63e63989967d1896f6223112e137bc6a/services/operationalinsights/v1/operationalinsights/query.go#L40) function from our old track one library, the [QueryWorkspace](https://github.com/Azure/azure-sdk-for-go/blob/90ea274b63e63989967d1896f6223112e137bc6a/sdk/monitor/azquery/logs_client.go#L76) function in the new track two library performs the same functionality. They both execute a Kusto Query against a Log Analytics Workspace.

**Comment by smartaquarius10** [comment]
@jhendrixMSFT @gracewilcox , 

I'm extremely sorry for disturbing you. I was doing the silly mistake in the code. Extra space in workspace id. 

Actually working for so long so got stuck in a loop. Just took a break of 1.5 hour and immediately figured it out. 

Thank you so much once again. Its working now from local machine with the combination of azidentity and azquery :)

Now, next step is to use AAD pod identity. I'll try to complete it immediately and in case of any issue will reach out to you. Hope you don't mind. Thank you so much for the superb help and support

Hope you have a great weekend. Cheers :)
