### ISSUE TITLE
containerregistry/armcontainerregistry lacks implementation regarding image repositories and tags

### ISSUE THREAD

**Issue by HDYA** [Azure/azure-sdk-for-go#19195]
### Feature Request

As legacy mode will be deprecated next Match, is there any plan to implement operations regarding image repositories and tags?
It appears that containerregistry/armcontainerregistry hasn't been updated for months.

the following features has not been implemented by armcontainerregistry:

* get access key

* image untag
* repository delete
* image / repository list

Although the latter 3 can use a workaround with Docker API, we still lack the interface to get access key for it

**Comment by xboxeer** [comment]
> ### Feature Request
> As legacy mode will be deprecated next Match, is there any plan to implement operations regarding image repositories and tags? It appears that containerregistry/armcontainerregistry hasn't been updated for months.
> 
> the following features has not been implemented by armcontainerregistry:
> 
> * get access key
> * image untag
> * repository delete
> * image / repository list
> 
> Although the latter 3 can use a workaround with Docker API, we still lack the interface to get access key for it

Hi @HDYA , do we know for these features, are they already implemented in ACR's REST API? if it is, what version of that API?

**Comment by tadelesh** [comment]
@HDYA For `get access key`, it seems service does not provide REST API for it now. We'll involve service team to have a look. BTW, current SDK contains API for token authentication which could be a better way for auth. You could refer the [usage doc](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions) and SDK [examples](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/containerregistry/armcontainerregistry/ze_generated_example_tokens_client_test.go).
@jhendrixMSFT Repository delete, list and image list untag seems data plane API that could be found [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerregistry/data-plane/Azure.ContainerRegistry/stable/2021-07-01/containerregistry.json). Do we have plan for track2 ACR data plane module?

**Comment by RickWinter** [comment]
@tadelesh, @lirenhe The current armcontainerregistry package is based on a much older version of the code generator.  We should ship an update beta based on the latest swagger, 2021-07-01.

**Comment by tadelesh** [comment]
> @tadelesh Chenjie Shi FTE, @lirenhe Renhe Li FTE The current armcontainerregistry package is based on a much older version of the code generator. We should ship an update beta based on the latest swagger, 2021-07-01.

@RickWinter `armcontainerregistry` is our mgmt. plane package and it is generated by the latest tag: `package-2022-02-preview`. The version `2021-07-01` you mentioned is a data plane swagger version, do you mean we need to generate the data plane package with the latest codegen and ship it?

**Comment by aittam** [comment]
Uhm I am bit confused as well, I was looking at how to making a specific image tag immutable. 
Basically what `az acr repository update --name myregistry --image myimage:1.2.3 --write-enabled false` does.

I saw that in an older version there was this:
https://github.com/Azure/azure-sdk-for-go/blob/0788f2c48518d6461b4a3ae1b62872590b08f027/services/preview/containerregistry/runtime/2019-07/containerregistry/models.go#L124-L133

but I struggle to find how I should accomplish that with the current SDK.

**Comment by tadelesh** [comment]
@aittam Thanks for your feedback. Unfortunately, we do not have any replacement for it currently. We are now working on the new version of ACR package. I will update the status in this issue continuously.

**Comment by aittam** [comment]
thanks @tadelesh for your reply.

**Comment by tadelesh** [comment]
@HDYA @aittam We have released a beta version of ACR data plane module: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry@v0.1.0. Please have a try and feedbacks are welcomed.
