### ISSUE TITLE
armcontainerservice/managedclusters - Get-Version  function / method for AKS is missing

### ISSUE THREAD

**Issue by AdamRussak** [Azure/azure-sdk-for-go#19203]
### Bug Report
currently, there is no Function to receive the available AKS versions, a command that is available in a simple CLI command.
`az aks get-versions --location eastus --output table`

i would expect to see a command (or set of them) that supports commands that are available in the CLI: https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli

this is not a feature nor a bug, but it's closer to a bug than a feature as it is something already supported by API and other Azure tools.

**Comment by AdamRussak** [comment]
my same code that was used to exctract the output i used above:
```go
client, err := armcontainerservice.NewManagedClustersClient(subscription.Id, auth(id), nil)
	core.OnErrorFail(err, "failed to create client")
	pager := client.NewListPager(nil)
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		core.OnErrorFail(err, "failed to advance page")
		for _, v := range nextResult.Value {
			supportedAKS := findSupportedAksVersions(SplitAzIDAndGiveItem(*v.ID, "/", 4), *v.Name, subscription.Id, id)
			l := getAksConfig(supportedAKS)
			log.Debug("current Version is: " + *v.Properties.KubernetesVersion)
			r = append(r, Cluster{*v.Name, *v.Properties.KubernetesVersion, l, *v.Location, *v.ID, "", microsoftSupportedVersion(l, *v.Properties.KubernetesVersion)})
		}
	}
```

**Comment by ArcturusZhang** [comment]
Hi @AdamRussak I use the `--debug` flag to see which request the azure cli command line is sending while processing your argument (you could also have a try, just append `--debug` to your command line)
It is using this API: https://github.com/Azure/azure-rest-api-specs/blob/41caa3033eefe466ee5254431ff586968f7e6841/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-08-01/location.json#L37
And this API is not included in the our SDK. We will follow up with the container service team to include this API in the next version
cc @lirenhe and @Alancere for awareness

**Comment by AdamRussak** [comment]
Hi @ArcturusZhang,
first I appreciate you taking it forward!
second, as I wrote in my ticket, it's not a bug or feature, but I opened the ticket because the API call was missing for the GO SDK.
and again! thank you ! :)

**Comment by navba-MSFT** [comment]
Adding service team to look into this. 

@qike-ms, @jwilder, @thomas1206, @seanmck Could you please look into this once you get a chance ? Thanks in advance.

**Comment by AdamRussak** [comment]
hi,
any update? or expected timeline?

**Comment by priyamshet** [comment]
Is there a timeline when we can expect this to be available in Go Sdk?.

**Comment by lirenhe** [comment]
@tadelesh, could you help to check?

**Comment by FumingZhang** [comment]
cc @Azure/aks-pm, @palma21

**Comment by mingmingshiliyu** [comment]
> my code that was used to exctract the output i used above:
> 
> ```go
> client, err := armcontainerservice.NewManagedClustersClient(subscription.Id, auth(id), nil)
> 	core.OnErrorFail(err, "failed to create client")
> 	pager := client.NewListPager(nil)
> 	for pager.More() {
> 		nextResult, err := pager.NextPage(ctx)
> 		core.OnErrorFail(err, "failed to advance page")
> 		for _, v := range nextResult.Value {
> 			supportedAKS := findSupportedAksVersions(SplitAzIDAndGiveItem(*v.ID, "/", 4), *v.Name, subscription.Id, id)
> 			l := getAksConfig(supportedAKS)
> 			log.Debug("current Version is: " + *v.Properties.KubernetesVersion)
> 			r = append(r, Cluster{*v.Name, *v.Properties.KubernetesVersion, l, *v.Location, *v.ID, "", microsoftSupportedVersion(l, *v.Properties.KubernetesVersion)})
> 		}
> 	}
> ```
``` shell
{"error":{"code":"AuthorizationFailed","message":"The client '73e3d34d-ed62-4182-88e3-58fbf4734ddf' with object id '73e3d34d-ed62-4182-88e3-58fbf4734ddf' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/read' over scope '/subscriptions/f3c1e2e2-6a29-4071-b344-f14e93c36082' or the scope is invalid. If access was recently granted, please refresh your credentials."}}```
how to resolve this bro.i`ve added all I can do,

**Comment by mjnovice** [comment]
Any updates on this ?

**Comment by FumingZhang** [comment]
There's a new API could be used to get/list supported k8s versions. The corresponding operation is [ListKubernetesVersions](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go#L1086C15-L1086C36) in ManagedClustersClient.
