### ISSUE TITLE
ContentMd5 contains invalid UTF-8

### ISSUE THREAD

**Issue by lemonglutton** [Azure/azure-sdk-for-go#19206]
### Bug Report

path of package: azure-sdk-for-go/storage/azblob 
SDK version: v0. 4. 1
Go version: go1.18.2 linux/amd64

Hey I have trouble with fetching contentMD5 property when using blob client in azureblob. I'm not sure if that's an issue or I'm missing something here, because that has happened to me already twice, both 2 of my images(png) with autogenerated contentMD5 had not valid utf-8 chars after being decoded from base64. Thanks in advance!

Description:
During using of  `ContentMD5` field of result of GetProperties method, which was used on azure blobClient I have encountered problem with invalid UTF-8. Golang is not able to parse following contentMD5: `vgBvo5aW9PG5jOO+1U/0fw==` ,which was autogenerated during file upload.
Its being decoded from base64 to such byte array: `190 0 111 163 150 150 244 241 185 140 227 190 213 79 244 127`, which contains not valid utf-8 characters.

Steps to reproduce:
Having a blob with autogenerated contentMD5 like, for example v`gBvo5aW9PG5jOO+1U/0fw==` try to make valid utf-8 string out of it.

Expected result:
Using contentMD5 getter I'm getting valid utf-8 string(array of bytes), so I can work with this data futher with no complications

Environment:
Windows10
OS build: 19042.1889

WSL 2
Kernel version 5.10.16
OS: Ubuntu-20.04

**Comment by jhendrixMSFT** [comment]
Can you please clarify your statement "Gloang is not able to parse..."?  The `ContentMD5` fields should all be represented as `[]byte` and I don't believe there's any requirement that its contents restricted to UTF-8.

**Comment by PawelSmorczewskiSopraSteria** [comment]
> Can you please clarify your statement "Gloang is not able to parse..."? The `ContentMD5` fields should all be represented as `[]byte` and I don't believe there's any requirement that its contents restricted to UTF-8.

Yep, thx for response. I suspected that base64 when decoded is valid UTF-8. Currently when trying to marshall this decoded `[]byte` I get `"marshal message: proto: field contentMd5 contains invalid UTF-8"` - thats what I meant by "Golang is not able to parse"

**Comment by jhendrixMSFT** [comment]
Thanks for clarifying.  This field is just a MD5 hash of the blob contents, so invalid UTF-8 chars are possible.

**Comment by PawelSmorczewskiSopraSteria** [comment]
@jhendrixMSFT ok I got it, so I believe solution for me would be either to use hex.EncodeToString to convert this binary string to hex string or to encode it once more to base64. Both of those method should give me string, which I can marshall and return in response
