### ISSUE TITLE
Can `Cancelled` be added as a terminal state?

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-go#19209]
This is related to https://github.com/Azure/azure-resource-manager-rpc/issues/144 where `Cancelled` is used in a large percentage of specifications instead of `Canceled`. You can see it is used a lot in this repository https://github.com/Azure/azure-sdk-for-go/search?q=cancelled . 

Rather than adding `Canceled` to the specifications that already use `Cancelled`, would it not be a better user experience to update the `IsTerminalState` to support the alternative spelling?

https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azcore/internal/pollers/util.go#L24-L40

**Comment by jhendrixMSFT** [comment]
Fix will be included in the next update of `azcore` post `v1.4.0`.
