### ISSUE TITLE
Poor support for extra headers in API calls

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1922]
There is no first-class support for including custom headers in API calls (e.g. see C# [impl](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/RedisCache/Management.Redis/Generated/IRedisOperations.cs#L54) customHeaders param).  While this can be worked around for some APIs by calling preparer/sender/responder explicitly there is no way to do this for LRO polling operations as we don't expose a preparer for the LRO poll request.  Unclear how important this is as nobody has complained about it but it does mean that we can't implement all of the Autorest tests for the generator.

**Comment by jhendrixMSFT** [comment]
Using a custom `RequestInspector` works better than preparer/sender/responder
```go
	client.RequestInspector = func(p autorest.Preparer) autorest.Preparer {
		return autorest.PreparerFunc(func(r *http.Request) (*http.Request, error) {
			r, err := p.Prepare(r)
			if err != nil {
				return r, err
			}
			r.Header.Add("customHeader", "value")
			return r, nil
		})
	}
```

**Comment by ArcturusZhang** [comment]
This issue should have been resolved, closing
