### ISSUE TITLE
Request for retail prices API support

### ISSUE THREAD

**Issue by rohan-rayaraddi** [Azure/azure-sdk-for-go#19225]
### Feature Request

I would like to request for the support of the retail API via SDK so that we can use the SDK for all our requirements. Currently we would need to use the retail API https://learn.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices

**Comment by lirenhe** [comment]
@rohan-rayaraddi, could you check whether this SDK could solve your problem?  https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/costmanagement/armcostmanagement

**Comment by rohan-rayaraddi** [comment]
Apologies for the late response. Our use-case is mainly to fetch the retail prices of offerings prior to creating the resources and hence we would not be able to use the cost management libraries.
