### ISSUE TITLE
armsubscription SubscriptionsClient NewListLocationsPager does not return location metadata

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-sdk-for-go#19241]
### Bug Report

**Description**
When using `armsubscription` go package
```bash
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/subscription/armsubscription
```

Calling `SubscriptionsClient.NewListLocationsPager` does not return all location metadata.

**Steps to reproduce**
1. Create a `armsbuscription.SubscriptionsClient`
2. Get locations pager using client.

```go
locations := []*armsubscription.Location{}
client, _ := armsubscription.NewSubscriptionsClient(credentials, nil)
pager := client.NewListLocationsPager(nil)

for pager.More() {
	page, _ := pager.NextPage(ctx)

	locations = append(locations, page.LocationListResult.Value...)
}
```

**Expected**
Expect to see the same location metadata that is returned from the [REST API](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list-locations?tabs=HTTP)

**Actual**
Location model does not return metadata properties such as `regionType`, `regionCategory`, `geographyGroup`, `geographGrup`, `pairedRegion`.

**Comment by ArcturusZhang** [comment]
Hi @wbreza thanks for this issue.
In the generated SDK, this API is using a very old api-version 2016-06-01: https://github.com/Azure/azure-rest-api-specs/blob/7a2ac91de424f271cf91cc8009f3fe9ee8249086/specification/subscription/resource-manager/Microsoft.Subscription/stable/2016-06-01/subscriptions.json#L42
We will work with the corresponding service team to make sure a new version of the SDK that consumes a new api-version list location operation.

**Comment by ArcturusZhang** [comment]
Well I had a closer look, it turns out that only 2016-06-01 api-version contains the desired API - how could the doc site show we have a list location operation with 2020-01-01 api-version?

**Comment by ArcturusZhang** [comment]
Hi @wbreza it turns out that the API your doc links to is in this module: https://github.com/Azure/azure-sdk-for-go/blob/204c2d8f86d5cd11cff0f3d9e0050921d46e973d/sdk/resourcemanager/resources/armsubscriptions/zz_generated_client.go#L211 (this actually has a newer api-version comparing with the document)
But in the meantime, it is very un-intuitive that this subscription related operation can only be found in resources/armsubscriptions module. I will open an internal email thread to track this issue.

**Comment by wbreza** [comment]
After switching over to the `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions` API I am able to retrieve all the additional Location metadata.

I would consider deprecating the originally referenced API to avoid any further confusion.
