### ISSUE TITLE
armsubscription SubscriptionsClient Get does not return subscription TenantID

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-sdk-for-go#19243]
### Bug Report

**Description**
When using `armsubscription` go package
```bash
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/subscription/armsubscription
```

Calling `SubscriptionsClient.Get` does not return TenantID.

**Steps to reproduce**
1. Create a `armsbuscription.SubscriptionsClient`
2. Get a subscription by id using client.

```go
client, _ := armsubscription.NewSubscriptionsClient(credentials, nil)

// `subscription` does not container TenantID property
subscription, _ := client.Get(ctx, subscriptionId)
```

**Expected**
Expect to see `TenantID` on the returned response like from the [REST API](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/get?tabs=HTTP)

I would expect all the properties available by the REST API also returned in the response models.

**Actual**
`TenantID` is not returned in the result.

**Comment by tadelesh** [comment]
@wbreza You may use another module `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions` to get `TenantID`. Here is some sample code:
```
package main

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions"
)

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	client, err := armsubscriptions.NewClient(cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	subscription, _ := client.Get(ctx, "sub-id", nil)
	_ = subscription
}

```
