### ISSUE TITLE
Storage Queues SDK

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#19258]

**Comment by berndverst** [comment]
@jhendrixMSFT given that `go-autorest/adal` will go out of support by end of March, we need a *stable* `1.0` release of Storage Queues SDK before then. Or `go-autorest/adal` support needs to be extended.

https://github.com/Azure/go-autorest

**Comment by sandeep-sen** [comment]
@berndverst we have released the first beta of `azqueue` which can be found at `sdk/storage/azqueue` let us know of any feedback.
