### ISSUE TITLE
[azeventhubs] ReceiveEventsOptions support prefetching messages

### ISSUE THREAD

**Issue by shubham1172** [Azure/azure-sdk-for-go#19276]
### Feature Request

Currently the ReceiveEventsOptions is kept empty, for future expansion.

https://github.com/Azure/azure-sdk-for-go/blob/06734c5c5ab728ffcbc4df605bc57d20a93e572e/sdk/messaging/azeventhubs/partition_client.go#L67-L70

This proposal is to add a prefetch option to allow EH to pull more messages at once from the hub. This is similar to the track 1 SDK's `ReceiveWithPrefetchCount`.

https://pkg.go.dev/github.com/Azure/azure-event-hubs-go/v3#ReceiveWithPrefetchCount

**Comment by shubham1172** [comment]
Based on a quick scan, there seems to be some in-build pre-fetching https://github.com/Azure/azure-sdk-for-go/blob/06734c5c5ab728ffcbc4df605bc57d20a93e572e/sdk/messaging/azeventhubs/partition_client.go#L96

Is there a way for external consumers to control this already? If not, the `ReceiverEventsOptions` can be probably used for the same.

**Comment by jhendrixMSFT** [comment]
I believe this feature is already in the works but will defer to @richardpark-msft for any details.

**Comment by shubham1172** [comment]
Thanks for the updates!

**Comment by richardpark-msft** [comment]
@shubham1172 , this has been released in 0.2.0:

https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fmessaging%2Fazeventhubs%2Fv0.2.0
