### ISSUE TITLE
Document the endpoint URL requirement for the various client constructors

### ISSUE THREAD

**Issue by cmackenzie1** [Azure/azure-sdk-for-go#19274]
### Feature Request

Previously, before `v0.5.0`, one could call `UploadStream` without specifying the container name, which is already present in the URL when instantiating the client using `azblob.NewClientWithNoCredential`. 

Now with `v0.5.0`, you must specify the container name in the `client.UploadStream` args. 

Is it possible to get a utility function to get the container name from the URL used when creating the client?

**Comment by jhendrixMSFT** [comment]
You can use `azblob.ParseURL()` to parse a URL into its constituent parts.

Would you mind telling us a bit more about your scenario?  When we redisgned `azblob`, we envisioned the client in the root package to take just a blob storage service URL (I see that we don't properly document this).  I'd like to understand the pattern you're using to see if we need to make some changes.

**Comment by cmackenzie1** [comment]
Thanks for the quick responses @jhendrixMSFT , very much appreciated. 

I am OK with going the route creating the client and getting the container name from the URL. It seems the most straight forward and inline with the other object storage clients we use like S3 and GCS.

```go
client, err := azblob.NewClientWithNoCredential(blobUrl, nil)
parts, err := azblob.ParseURL(blobUrl)
if err != nil {
    return nil, fmt.Errorf("invalid url: %v", err)
}
containerName = parts.ContainerName
```

**Comment by jhendrixMSFT** [comment]
Just make sure that when you call `azblob.NewClientWithNoCredential()` that `blobUrl` is only the service URL and not the full blob URL.  The constructor will accept it, but the APIs won't work as expected (we need to document and fix this).

**Comment by cmackenzie1** [comment]
Thanks. While testing I ran into interesting behavior so let me know if I should create a new issue or not for it.

When doing the following I end up with an unnamed object under the prefix of `key` instead of the `key` itself being the object name.

```go
parts, err := azblob.ParseURL(blobUrl)
if err != nil {
   panic(fmt.Errorf("invalid url: %v", err))
}

client, err := azblob.NewClientWithNoCredential(parts.String(), nil)
if err != nil {
    panic(fmt.Errorf("unable to create azure blob client: %v", err))
}

_, err := c.client.UploadStream(ctx, containerName, key, body, &azblob.UploadStreamOptions{
		BlockSize: 2 * 1024 * 1024, // 2 MB
		HTTPHeaders: &blob.HTTPHeaders{
			BlobContentEncoding: &contentEncoding,
			BlobContentType:     &contentType,
		},
	})
```
<img width="1299" alt="Screen Shot 2022-10-04 at 10 54 38 AM" src="https://user-images.githubusercontent.com/10947617/193891270-3f1a294b-66cd-4437-8f2c-a40dd6b49caf.png">

**Comment by jhendrixMSFT** [comment]
This is what I was alluding to earlier.

When you call one of the Upload APIs, it concatenates the `containerName` and `blobName` params to the URL passed to the client constructor.  This is why you must pass only the service URL to the client constructor (like in the example).

**Comment by cmackenzie1** [comment]
I tried with just `https://mirio.blob.core.windows.net/?se=2023-10-04T23%3A41%3A43Z&sig=REDACTED&sp=w&spr=https&sr=c&st=2022-10-04T15%3A41%3A43Z&sv=2021-06-08` as the serviceUrl and manually specifying the `containerName` and `key` - I get the same result. 

I was following this example, 
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/examples_test.go#L51-L70

**Comment by cmackenzie1** [comment]
Found the underlying issue. It only occurs when the URL contains any query parameters. 

https://cs.github.com/Azure/azure-sdk-for-go/blob/51f810429dd6f9a5233d076e449b2b212b7d52bc/sdk/azcore/runtime/request.go?q=JoinPaths#L66-L68

In go 1.19 a new method for joining URL paths was added, https://pkg.go.dev/net/url@go1.19#JoinPath

**Comment by jhendrixMSFT** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/19245 is in progress to get this fixed.

**Comment by jhendrixMSFT** [comment]
I will keep this open to track fixing the docs so it's clear that the constructors take only the service URL (the context here is very helpful).

**Comment by jhendrixMSFT** [comment]
@cmackenzie1 can I ask where you got the SAS URL in your earlier [comment](https://github.com/Azure/azure-sdk-for-go/issues/19274#issuecomment-1267394734)? Looks like we also add a superfluous trailing `/` in the [`GetSASURL`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blob/client.go#L265-L268) APIs, so I'm curious if this is how you obtained it (or maybe the bug is elsewhere).

**Comment by jhendrixMSFT** [comment]
Oh looks like the portal provides this.

**Comment by cmackenzie1** [comment]
Yup, the SAS URL was generated in the Azure UI. `Storage accounts > Containers > Shared access token`
