### ISSUE TITLE
Distributed Tracing

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#19280]
Add distributed tracing support to Core
```[tasklist]
- [x] Azure.Core abstraction layer
- [x] CodeGen to light up feature
- [x] OTel adapter
- [ ] Beta Release
- [ ] Stable Release
```

**Comment by richardpark-msft** [comment]
Looking at this from the lens of Service Bus we're missing some features (or it could be that they're not 1:1 with the Java/.NET layers)

- `Links`, which we can use to link multiple spans together, don't exist (yet). This is different than the parent/child relationship between spans. From @lmolkova's gist: [`builder.addLink`](https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#:~:text=EventData%20or%20EventDataBatch-,builder.addLink((SpanContext)msg.SpanContext)%3B,-%7D%20else%20%7B)

- Getting a SpanContext, which has fields like the TraceID, SpanID and trace options (unsure of this last one). [getDiagnosticId](https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#:~:text=spanContext.getTraceId().copyLowerBase16To(chars%2C%203)%3B)
