### ISSUE TITLE
How to insert logs in log analytics workspace?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-sdk-for-go#19292]
Hello,

Is it possible to insert logs in log analytics workspace using azure sdk in golang. For reading the logs I'm using this [azquery package](https://github.com/Azure/azure-sdk-for-go/tree/90ea274b63e63989967d1896f6223112e137bc6a/sdk/monitor/azquery)

Can anyone share a sample of inserting the logs as well. Thank you.

Regards,
Tanul

**Comment by smartaquarius10** [comment]
@gracewilcox , Hey, Hope you are doing well.

If possible, could you please help on this. Unable to pass logs to log analytics workspace.

**Comment by gracewilcox** [comment]
Hi @smartaquarius10! I am very sorry I missed this issue. Inserting logs into Azure Monitor is very new. The official release of the [Log Ingestion API](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-ingestion-api-overview) just happen this week.

There is currently no client library for Go. Instead, you can use the API directly, the Azure Portal, or the beta SDK's in select languages (Python, C#, Java, JavaScript). Here is a [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-ingestion) to the Monitor Ingestion library in Java.

Hope this answers your question!

**Comment by gracewilcox** [comment]
Azure Monitor Ingestion SDK is not currently on the schedule, but here is the issue to track its progress.
https://github.com/Azure/azure-sdk-for-go/issues/19703

**Comment by smartaquarius10** [comment]
@gracewilcox Thank you so much for sharing.
