### ISSUE TITLE
Confusing error message upon 400 Bad Request

### ISSUE THREAD

**Issue by vgarg** [Azure/azure-sdk-for-go#193]
I am using the StorageAccountsClient to create a new Storage Account. It's working pretty well in most cases. However, in case wrong values are passed e.g. wrong location (uswest instead of westus), the SDK throws an error message of the type:

> `autorest.Client:ShouldPoll Response to https://management.azure.com/subscriptions/ddc30f29-****-****-****-********/resourceGroups/vivekrg1/providers/Microsoft.Storage/storageAccounts/vivekst?api-version=2015-05-01-preview requires polling but polling is disabled`

It would be nice for the SDK to bail out with the actual error message e.g. 400 Bad Request. Invalid Location.

Here is the code snippet being used:

	cp := storage.StorageAccountCreateParameters{}
	cp.Location = location
	cp.Properties.AccountType = t

	smc := p.StorageAccountsClient(subID)
	smc.PollingMode = autorest.PollUntilDuration
	smc.PollingDuration = 15 * time.Minute

	sa, err := smc.Create(resGroupName, storageAccountName, cp)
	if err != nil {
		return nil, err
	}
	return &sa, nil

Btw: Thanks for adding the ARM support. Cool stuff.

**Comment by brendandixon** [comment]
@vgarg I'll look into it. The initial call *should* have returned an error which would prevent the call to poll. Likely a simple logic error on my part.

**Comment by brendandixon** [comment]
@vgarg I see the bug. I had intended to expand the logic evaluating HTTP return codes and it, somehow, got left out of the generated code. I'll try to regenerate and get a fix out soon.

**Comment by vgarg** [comment]
@brendandixon awesome. thanks.

**Comment by brendandixon** [comment]
@vgarg I just pushed #195 which addresses this. Enjoy and let me know of any other issue you find.
