### ISSUE TITLE
Understanding various clients in sdk/storage/azblob

### ISSUE THREAD

**Issue by rayterrill** [Azure/azure-sdk-for-go#19311]
There are a number of clients available in sdk/storage/azblob. At least:

- sdk/storage/azblob/client
- sdk/storage/azblob/blob/client
- sdk/storage/azblob/service/client

Is there one that's "better" (in terms of go-forward support)? Or at they all available on a case-by-case basis?

It looks like sdk/storage/azblob/client has documentation and a fairly simplified set of methods. I was looking for a simple mechanism to detemine if a blob exists already - found that in both azblob/blob/client and azblob/service/client (but not azblob/client unless I'm missing something). Just trying to understand why there are so many clients and when they should be used.

On a related note, the blob quickstart in the docs (https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-go) appears to reference a NewServiceClient that no longer exists? https://github.com/Azure-Samples/storage-blobs-go-quickstart/blob/aa59f94f1d8b6c44963d702416cd3becfee62e77/storage-quickstart.go#L46

I also see https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob#next-steps which seems to indicate the different clients are intentional and targeted to specific use cases.

**Comment by vibhansa-msft** [comment]
Hi @rayterrill,

Thanks for reaching out. As you have seen there are bunch of clients defined and each cater to specific needs. For e.g., if you wish to perform some container level operations then you go for container client and so on.
'azblob/client' is a generic client which provides simple apis to do basic upload/download/list operations. 

For you use case (check existence of a blob) you can create object of 'azblob/blob/client' and use 'GetProperties' api. If you wish to refer some code for this, we have an example [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blob/examples_test.go#L216). For non-existent blob GetProperties shall return 404 error.

**Comment by rayterrill** [comment]
Sounds good - that's what I ended up doing, but wanted to confirm because it originally threw me off to see a number of clients vs a single client. Appreciate the assist!
