### ISSUE TITLE
Make RP registration policy more reusable

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-go#19320]
### Feature Request

We are using the Azure SDK for Go (Track 2) in the context of a Kubernetes reconciler. One of the tenants of a Kubernetes reconciler is to not block the goroutine running the reconciliation process for a long time. If you encounter a failure, retries will be handled automatically if you return that failure to the coordinating infrastructure.

As part of following that best practice, we disable retries in the SDK. Retries will be done by the reconciliation infrastructure instead so there need not be SDK specific retries (or their corresponding delays).

We would love to use the SDKs built in [RP registration policy](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/arm/runtime/policy_register_rp.go), but unfortunately there's no good way to avoid a delay waiting for the RP to register.

**Our ideal solution:** would send the initial request to ARM, check the response, issue the RP registration call to ARM if the response was `MissingSubscriptionRegistration` and then return an error that said something like: `RP registration is ongoing`

We investigated 2 options for achieving this with the existing policy:
1. Disable RP registration entirely. This is well supported in the SDK but doesn't meet our needs of automatically registering RPs.
2. Enable RP registration, set `MaxAttempts = 1` and `PollingDelay` and `PollingDuration` to `0 seconds`. This results in the RP registration request being sent to ARM, but then the policy immediately times out with a context cancellation. This gets us almost there, but the problem is that we can't differentiate this error from a networking timeout and so the user on our end would see spurious timeout errors we couldn't suppress/hide from them. This is confusing.

**What we've done in the meantime**: We copied the [RP registration code](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/arm/runtime/policy_register_rp.go) and [modified it](https://github.com/Azure/azure-service-operator/pull/2516) to remove the delays and return a well-established error.

**What would we like:**

I'm not sure that many other use-cases will want this exact behavior, although it's possible other people in the context of a Kubernetes operator will. In any case, what would be nice is either this option officially supported by the SDK with a flag passed to `NewRPRegistrationPolicy`, _or_ a publicly exported set of function(s) that did most of the work of actually detecting this error and sending a new request, so that we don't have to duplicate code to achieve it.

If this is something you're willing to entertain, we might be willing to send you a PR to do it. Open to thoughts on what the best user experience would look like.

**Comment by jhendrixMSFT** [comment]
We could add a feature that, when `PollingDuration < 0`, the policy doesn't wait for the terminal registration state.  Still need to decide how best to surface this.

**Comment by jhendrixMSFT** [comment]
Thinking about this a bit more.  The RP registration code is just copied from the [`armresources`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources#ProvidersClient.Register) module.  It might be best to simply disable the policy and roll your own RP registration handling that uses this module instead.  What do you think?

**Comment by matthchr** [comment]
That's basically what I've done, and yeah, it might make sense to just have that be the official answer.

I did notice that the official implementation of this doesn't use some builtins like `NewResponseError`, instead opting to define its own error structure:
```
// minimal error definitions to simplify detection
type requestError struct {
	ServiceError *serviceError `json:"error"`
}

type serviceError struct {
	Code    string                `json:"code"`
	Details []serviceErrorDetails `json:"details"`
}

type serviceErrorDetails struct {
	Code   string `json:"code"`
	Target string `json:"target"`
}
```

Curious if you know the reasoning for that? I've followed that approach in my fork (which was part of where I was thinking there was a good bit of duplicate code), but possibly there's no good reason to do that and I could instead just use `NewResponseError` and delete all of that...

In any case, happy to close this.

**Comment by jhendrixMSFT** [comment]
The official Azure policy is that for error responses, the only parts that are contractual are the service error code and the HTTP status code; this is why we only return an `*azcore.ResponseError` from our APIs.

For this policy, as you know, we need to extract some of the details from the error in order to register the RP.  Could have done it a few different ways, I just copied the code from the track 1 implementation.

**Comment by jhendrixMSFT** [comment]
Closing per our discussion.
