### ISSUE TITLE
Using this with golang.org/x/oauth2/microsoft ?

### ISSUE THREAD

**Issue by lyda** [Azure/azure-sdk-for-go#1932]
I'd like to use the `oauth2` library for getting my OAuth token. Not clear on how to use an `oauth2.Token` with this SDK.

**Comment by vladbarosan** [comment]
@lyda here is a gist which does what you might need: https://gist.github.com/vladbarosan/74019046b8e9c9a49ff67d6634e7736d#file-xoauth2example-go

Let us know if that is what you are looking for.

**Comment by lyda** [comment]
Not quite, but thanks for the reply. I can get the `oauth2.Token`, the issue is then using it with this SDK.

I need to implement a `autorest.Authorizer` using the `oauth2.Token` I guess? I need to do something like the following although I also need to get the groups my authorized user is a member of, but that seems simple enough.

```
func Me(authorizer autorest.Authorizer) (graphrbac.User, error) {
  uclient := graphrbac.NewUsersClient("myorganization")
  uclient.Authorizer = authorizer

  req, _ := uclient.GetPreparer("")
  r := strings.NewReplacer("users", "me")
  req.URL.Path = r.Replace(req.URL.Path)

  resp, err := uclient.GetSender(req)
  if err != nil {
  	return graphrbac.User{}, err
  }

  return uclient.GetResponder(resp)
}
```

**Comment by vladbarosan** [comment]
Hi @lyda, correct you need to create the authorizer. Note that  oauth2 is using the AAD v2 endpoint which is not fully supported in Azure ( https://github.com/golang/oauth2/blob/master/microsoft/microsoft.go#L23 ) . Graph's spec seems to suggest that is the case for them also :  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6/graphrbac.json#L30

**Comment by vladbarosan** [comment]
Closing this. @lyda please reply if you have any follow up.
