### ISSUE TITLE
Some diagnostic settings results don't return from API

### ISSUE THREAD

**Issue by liron-l** [Azure/azure-sdk-for-go#19328]
import path of package in question:
`services/preview/monitor/mgmt/2021-07-01-preview/insights`

SDK version:
latest

What happened?
Older API version is used which causes some results to not return
```
func (client DiagnosticSettingsClient) ListPreparer(...) {
...
   const APIVersion = "2017-05-01-preview"
...
}
```
we should use older version like sent from azure portal 
```
const APIVersion = "2021-05-01-preview"
```
otherwise some result does not return.

**Comment by tadelesh** [comment]
@liron-l Thanks for you feedback. We are trying to let service team to upgrade the tag version which we use to generate our Go SDK. Will let you know if any update.

**Comment by tadelesh** [comment]
Same request with: https://github.com/Azure/azure-sdk-for-go/issues/19090

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by tadelesh** [comment]
@liron-l We've released a new [version](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor@v0.8.0) of `armmonitor` package which could resolve your problem. Could you please migrate to our new version of SDK and try the new package? Thanks.
