### ISSUE TITLE
Azidentity build constraints exclude all Go files

### ISSUE THREAD

**Issue by Tomelin** [Azure/azure-sdk-for-go#19337]
Hi,

I'm following[ this tutorial](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash) to create a new package for me, but it is return this error:

Command to exeuted
/usr/local/go/bin/go run main.go
```
package main

// Import key modules.
import (
  "log"

  "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
  "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

// Define key global variables.
var (
  subscriptionId = "<subscription ID>"
)

// Define the function to create a resource group.

func main() {
  cred, err := azidentity.NewDefaultAzureCredential(nil)
  if err != nil {
    log.Fatalf("Authentication failure: %+v", err)
  }

  // Azure SDK Azure Resource Management clients accept the credential as a parameter
  client := armresources.NewClient(subscriptionId, cred, nil)

  log.Printf("Authenticated to subscription", client)
}
```

return
package command-line-arguments
        imports github.com/Azure/azure-sdk-for-go/sdk/azidentity: build constraints exclude all Go files in /MyHome/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azidentity@v1.1.0

I'm using go with this version:
go Version
go version go1.17.4 linux/amd64

**Comment by jhendrixMSFT** [comment]
`azidentity`, and our SDKs in general, require a minimum of Go 1.18.  Please see the [README](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md) for more details.
