### ISSUE TITLE
[azeventhubs] stress: $cbs link opened more than once

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#19347]
The $cbs link is used for authentication. It's an exclusive link - you can only have one of these open for your connection.

In our code we make this happen using a mutex, which protects the code that actually creates (and disposes) the $cbs link. I recently got an error in one of our stress tests where this somehow did NOT work, but it's unclear what led to that:

> 

There were some small windows where it seemed like we might leak a link on certain kinds of errors. Those are being addressed in PR#19326, but we'll need to keep an eye out and see if the error comes back. For now, I'm also making it so all the tests are in verbose mode in some runs.

**Comment by RickWinter** [comment]
@richardpark-msft Is there a feature, test work, or something else to be done?

**Comment by richardpark-msft** [comment]
I wasn't able to repro this (it seems like it must be some leaky abstraction). I went through the code and saw one potential leak, but it's hard to prove if it fixes this or not.

(that fix was made in #19326)

**Comment by richardpark-msft** [comment]
Here are some log events. Note that we went 172 rounds (receiving 1,000,000 events each time) before it occurred.

1000000 events received
2022/10/29 11:08:27 [r:172/9223372036854775807,p:0] All messages received (1000000/1000000)
2022/10/29 11:08:27 [r:172/9223372036854775807,p:0] Done receiving messages from partition
2022/10/29 11:08:32 [r:173/9223372036854775807,p:0] Starting to receive messages from partition
2022/10/29 11:08:32 [r:173/9223372036854775807,p:0] Done receiving messages from partition
panic: received 0/1000000, but then got err: *Error{Condition: amqp:not-allowed, Description: A link to connection '2033874' $cbs node has already been opened., Info: map[]}

**Comment by richardpark-msft** [comment]
Turns out the issue was that, by respecting the cancellation context, we were failing to cleanup. 

For Close() operations we're now ignoring the context and there's another issue (#19504) for some potential neatening-up of the approach.
