### ISSUE TITLE
CDN FrontDoor Route Rulesets returns ID with resource group name in lowercase

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-sdk-for-go#19378]
### Bug Report

- import path: `.../services/cdn/mgmt/2021-06-01/cdn`
- SDK version: `v66.0.0+incompatible`
- go version: `go version go1.18.3 linux/amd64`

When Terraform attempts to parse the CDN FrontDoor RuleSet IDs it causes the Terraform Azure Provider to crash because the expected casing of `resourceGroups` is returned as `resourcegroups` by the CDN FrontDoor Route API.

**What Happened:**
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
**What did you expect or want to happen:**
The casing in the returned CDN FrontDoor RuleSet ID to be in the expected casing.

How can we reproduce it?
1) Use the Azure Portal to create a CDN FrontDoor Route with an associated RuleSet.
2) Attempt to import that CDN FrontDoor Route via Terraform using the AzureRM Provider v3.27.0.

**Comment by tombuildsstuff** [comment]
@WodansSon this should be caught at import time and normalized as required in the Read function - why is this causing a panic?

**Comment by tadelesh** [comment]
Seems terraform related issue. Close for now. The SDK terraform using is our previous SDK version and is has been announced deprecated in Sept. 2022.
