### ISSUE TITLE
SDK track2: Aggregate retry errors on failures

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-for-go#19388]
### Feature Request

When retry happen in the SDK, and the request eventually fails, we only get to know the final error.
The intermediary errors might be different and provide the full picture.

For example,
TryTimeout = 30s
RetryDelay = 1s

you issue the call with a **context a deadline of 60s** and issue a PUT request.

First attempt fails because the server took 35s to reply, so the SDK abort and retry
2nd attempt also fails, but this time with `contextDeadlineExceeded`, and the error returned by the SDK call does not contain anything about the first attempt.

I would really like to see the intermediary errors aggregated and surfaced in the final error returned.

without that, I have to inject a PerRetryPolicy just to intercept the information, and the complexity this might incur might just lead to roll our own retry instead.

**Comment by jhendrixMSFT** [comment]
We do surface this in the logs, but I assume this is insufficient and that you want to react to this programmatically yes?

**Comment by serbrech** [comment]
Yes, also the sdk logs don't have access to the current request, and most http server have a per-request logger stashed in the context. As a result, the SDK logs can't flow in the correct log sink, which makes them much less useful.

**Comment by jhendrixMSFT** [comment]
We could solve this in a few ways.
- Chain each error by wrapping. This might be hard to work with though, and also means that all errors will be visible to unwrapping.
- Have a `RetriedErrors` type with a slice of errors. We'd return an instance of this type as appropriate.

I'm leaning towards the second options. Open to other suggestions.

Regarding the in-context logger you mentioned, is there something our logging should be doing to better interoperate with this?

**Comment by serbrech** [comment]
If the log listener was getting the request, we could grab the logger off the context and log in to the right per-request sink.
Not sure how practical that would be for you, but it would really be useful.

Could the events passed to the log interceptor have the request when it makes sense?

I think this might actually mostly resolve our usecase. We probably won't act on the intermediary error, but we definitely need to log them.

Without the request (or its context), we can't log them in a meaningful way.

We can only figure it out by looking at tracing because we inject it at the transport level. But that's very inconvenient.

**Comment by serbrech** [comment]
@jhendrixMSFT 
I accidentally took a look at how AWS go sdk provides this...
https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging/#logger

They allow to inject a logger at config tine (that's somewhat the equivalent of the listener func)

But it's better because they can check whether the logger injected supports context logger interface, and pass the request context if it does

> "accidentally?"

I was searching for the environment variable that I need to set to enable logging, and I ended up googling: 
"GO SDK LOGGING all"
The top result is the documentation page above 😄

**Comment by serbrech** [comment]
@RickWinter @jhendrixMSFT 
is there any new development regarding the logging integration with the request context?

In the current form, The logs are completely useless in any multithreaded system as there is no way to correlate the current request or thread to the log outptut. for us it actually ends up in a different kusto table, so there is no way to make sense of them in the context of a single request. you would have to guess from the timestamps.

I shared above how the aws sdk provides a hook that takes in the context to resolve the logger.

**Comment by jhendrixMSFT** [comment]
To make sure I understand, is the ask for the ability to specify a logger via the context so that client API calls can have their logging output written to discreet sinks?  Maybe something like this.
```go
// ContextLogger is used in conjunction with WithContextLogger to create a
// context-specific logger.
type ContextLogger struct {
	Events   []Event
	Listener func(Event, string)
}

// WithContextLogger adds the specified ContextLogger to the parent context.
func WithContextLogger(parent context.Context, ctxLogger ContextLogger) context.Context {
	return context.WithValue(parent, shared.CtxWithLoggerKey{}, ctxLogger)
}
```

**Comment by serbrech** [comment]
Exactly. If we're able to provide a logger to framework via the context, we'd be able to have framework logs together with our request logs when enabled, where it makes sense.
