### ISSUE TITLE
[armsubscription] Subsctiption model is incomplete

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#19380]
### Bug Report

The current Subscription Model  https://github.com/Azure/azure-sdk-for-go/blob/77190ec7d546094c51ff1b61073dd9580394a579/sdk/resourcemanager/subscription/armsubscription/zz_generated_models.go#L445-L465

does not have `Tags`, `TenantID` & `ManagedByTenants` fields

these fields are present in older SDK https://github.com/Azure/azure-sdk-for-go/blob/06af0db58a7fa031182beb15f5afe8c8c9d82958/services/resources/mgmt/2021-01-01/subscriptions/models.go#L528-L548

**Comment by tadelesh** [comment]
@vijayrajah Please use another module `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions` which has the latest version of `subscription` model (`2021-01-01`). We are working with service team to remove the out-of-date API from `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/subscription/armsubscription`. For the new API version `2022-01-01`, we could not find the corresponding spec definition [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/resources/resource-manager/Microsoft.Resources/stable), so it might be a preview or private version currently.

**Comment by vijayrajah** [comment]
@tadelesh -- Thanks for looking into this.

So, long term, we can use this `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions`. I mean  this module is the one we need to use going forward right ?

**Comment by tadelesh** [comment]
> @tadelesh Chenjie Shi FTE -- Thanks for looking into this.
> 
> So, long term, we can use this `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions`. I mean this module is the one we need to use going forward right ?

Yes.
