### ISSUE TITLE
Cant build on go 1.19.2

### ISSUE THREAD

**Issue by nobuenhombre** [Azure/azure-sdk-for-go#19382]
### Bug Report

- SDK version `latest`
- output of `go version`
go version go1.19.2 linux/amd64

- What happened?
I follow this instructions
https://learn.microsoft.com/en-us/graph/tutorials/go?view=graph-rest-1.0&tabs=aad&tutorial-step=2

and i have error: **Build constraints exclude all the Go files in '/home/myUser/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.4/policy'**

![Screenshot from 2022-10-18 19-06-17](https://user-images.githubusercontent.com/2649024/196470348-d48a0774-e9f1-4441-84d0-5359d5fd4107.png)

- What did you expect or want to happen?
no errors

- How can we reproduce it?
just follow this instructions
https://learn.microsoft.com/en-us/graph/tutorials/go?view=graph-rest-1.0&tabs=aad&tutorial-step=2

- Anything we should know about your environment.
Ubuntu 20.04
Go 1.19.2

**Comment by jhendrixMSFT** [comment]
It would appear that the build is using a version of Go predating 1.18.  Our build constraints are for Go 1.18+ ([example](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azcore/policy)). We do build with 1.19 in our CI system as well.

**Comment by nobuenhombre** [comment]
> It would appear that the build is using a version of Go predating 1.18. Our build constraints are for Go 1.18+ ([example](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azcore/policy)). We do build with 1.19 in our CI system as well.

How it could be?
output of go version
go version go1.19.2 linux/amd64

**Comment by jhendrixMSFT** [comment]
Does it repro from the command line too, or just in GoLand?  I can build `azcore` locally so I'm at a bit of a loss.
```
PS D:\git\Azure\azure-sdk-for-go\sdk\azcore> git checkout sdk/azcore/v1.1.4
Note: switching to 'sdk/azcore/v1.1.4'.
...
HEAD is now at ca5ebc8601 Prepare azcore v1.1.4 for release (#19250)
PS D:\git\Azure\azure-sdk-for-go\sdk\azcore> go build ./...
PS D:\git\Azure\azure-sdk-for-go\sdk\azcore>
```

**Comment by nobuenhombre** [comment]
> Does it repro from the command line too, or just in GoLand? I can build `azcore` locally so I'm at a bit of a loss.
> 
> ```
> PS D:\git\Azure\azure-sdk-for-go\sdk\azcore> git checkout sdk/azcore/v1.1.4
> Note: switching to 'sdk/azcore/v1.1.4'.
> ...
> HEAD is now at ca5ebc8601 Prepare azcore v1.1.4 for release (#19250)
> PS D:\git\Azure\azure-sdk-for-go\sdk\azcore> go version
> go version go1.19.2 windows/amd64
> PS D:\git\Azure\azure-sdk-for-go\sdk\azcore> go build ./...
> PS D:\git\Azure\azure-sdk-for-go\sdk\azcore>
> ```

you are right.
i re-create project without GoLand, using only midnight commander text editor
and project run and build succesfull,
so problem under GoLand

thanks, I'm sorry for the trouble

**Comment by jhendrixMSFT** [comment]
No worries, hope you find the solution (I haven't used GoLand so I have no clue).

**Comment by nobuenhombre** [comment]
I found why it happend.
I use GoLand 2021.3.4 + manually installed Go 1.9.2 (without GoLand),
After upgrade to 2022.1.4 problem was solved.
i think it is because GoLand 2021.3.4 - max supported go version 1.17.
and 2022.1.4 - max supported go version 1.18.

![Screenshot from 2022-10-19 08-44-51](https://user-images.githubusercontent.com/2649024/196600104-3a8077af-0346-4747-8901-420f641e913d.png)

**Comment by jhendrixMSFT** [comment]
Thanks for the details, maybe this will help others that hit the same issue.
