### ISSUE TITLE
StreamAnalytics - please support 2021-10-01-preview so we can use UserAssigned

### ISSUE THREAD

**Issue by baselsalam** [Azure/azure-sdk-for-go#19407]
Version 2021-10-01 came out a year ago.

Please support the various features in this version, like "UserAssigned" identity.

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2021-10-01-preview

**Comment by lirenhe** [comment]
@tadelesh, could you help to check whether we supported this in track 2?

**Comment by tadelesh** [comment]
> @tadelesh Chenjie Shi FTE, could you help to check whether we supported this in track 2?

No, we only release the stable version (`2020-03-01`) service team tagged default in swagger readme config. I'll contact service team to check whether they need to release the beta version.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by navba-MSFT** [comment]
@atpham256 Could you please look into this once you get a chance ? Thanks in advance.

**Comment by baselsalam** [comment]
Any update on this please?
