### ISSUE TITLE
Unexported return type in exported function PageResponse

### ISSUE THREAD

**Issue by vraj416** [Azure/azure-sdk-for-go#19413]
### Bug Report

On latest version of SDK

Requesting that `[containerClientListBlobFlatSegmentResponse](https://github.com/Azure/azure-sdk-for-go/blob/303017d00c8e30e4f717212944a370658fdd76a4/sdk/messaging/azeventhubs/internal/blob/zz_generated_response_types.go#L1700)` be an exported type given that it's returned from an exported function.

From the go lint package, it seems to be discouraged as it can make testing and creating interfaces difficult.
[Link to stackoverflow discussion](https://stackoverflow.com/a/54833377)

**Comment by richardpark-msft** [comment]
Hi @vraj416, I'm not sure if I understand what you're pointing out here. 

containerClientListBlobFlatSegmentResponse (the type at line 1700) is in the internal package and we don't export this type to callers of azeventhubs. 

Am I missing some case where you're seeing it exposed?

**Comment by vraj416** [comment]
Hi Richard, thanks for your response. The type `containerClientListBlobFlatSegmentResponse` is returned from exported function [PageResponse](https://github.com/Azure/azure-sdk-for-go/blob/486d2d90a0f76a9f1adbdfa352e8933afe7cd70f/sdk/storage/azblob/zz_generated_pagers.go#L69)

**Comment by richardpark-msft** [comment]
Ah, I see what's going on now.

There are two versions of the azblob package. There's an internal one, used by Event Hubs. That's the one you initially flagged in your issue. That one isn't for public consumption, and is basically an internal implementation, specifically for Event Hubs checkpoint store.

The version you just linked  is the public version of the package. For that one I'll defer to @jhendrixMSFT , as that's part of our auto-generated layer, and there might be a reason for it to not be exported (or just a bug).

**Comment by jhendrixMSFT** [comment]
That commit is an old version of `azblob`.  We've sinced released an updated version of it that resolves this, and other, issues.

**Comment by richardpark-msft** [comment]
Sounds like updating to the latest version is the path, @vraj416. Are you running into this in some way where upgrading would not work?
