### ISSUE TITLE
[AppConfig] Support for Entra authentication challenge

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-for-go#19423]
Provide customers with a proper way to obtain AAD authentication tokens with proper audience for different clouds.

**Comment by chlowell** [comment]
#19448 added an API for extending azcore's bearer token policy for challenge handling/auth param discovery. #19447 has an example implementation for Key Vault.

**Comment by sandeep-sen** [comment]
Waiting on service change from the Entra team.
