### ISSUE TITLE
[AppConfig] Support for configuration snapshot

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-for-go#19424]
Add APIs to the SDK for the new REST APIs of the configuration snapshot feature in App Config.

**Comment by jhendrixMSFT** [comment]
From the [.NET APIView](https://apiview.dev/Assemblies/Review/8b7f5312697a458ab9e65c2fd9cdc2dd?diffRevisionId=84507059af4e49bea90eb42b6bae0ec6&diffOnly=False&revisionId=a40562bf411a4e7fa2c9b96d4676ab33&doc=False) it looks like adding six APIs and their supporting types.

```
ArchiveSnapshot
CreateSnapshot
GetConfigurationSettingsForSnapshot
GetSnapshot
GetSnapshots
RecoverSnapshot
```

**Comment by MBSolomon** [comment]
Stable Swagger not available yet.

**Comment by jhendrixMSFT** [comment]
Addressed in https://github.com/Azure/azure-sdk-for-go/pull/22118
