### ISSUE TITLE
Support NetworkAccessPolicy as part of OSDisk struct

### ISSUE THREAD

**Issue by harshavmb** [Azure/azure-sdk-for-go#19434]
### Feature Request

OS disk struct [here](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2021-11-01/compute/models.go#L10596-L10621) doesn't contain `NetworkAccessPolicy` flag which is present part of [managed_disk_properties](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2021-11-01/compute/models.go#L5396-L5453). 

Without this, our disks are open to internet with `NetworkAccessPolicyAllowAll` (applied by default). Though a disk attached to a running VM can't have an export SAS URL. We would like to have an argument which enables us to explicitly apply `NetworkAccessPolicyDenyAll`/`NetworkAccessPolicyAllowPrivate` flag to avoid exposure to internet. 

In the end, we would need something like below to be added to `OSDisk` struct::

```
type OSDisk struct {
  // existing arguments as-is
  // NetworkAccessPolicy - Possible values include: 'NetworkAccessPolicyAllowAll', 'NetworkAccessPolicyAllowPrivate', 
  //'NetworkAccessPolicyDenyAll'
  NetworkAccessPolicy NetworkAccessPolicy `json:"networkAccessPolicy,omitempty"`
}
```

This isn't just for a VM but also for VMSS resources. I'm new to this repo, hence not aware of contributing. 

Shall you need more details, please revert to me. 

Thanks,
Harsha

**Comment by tadelesh** [comment]
@harshavmb Thanks for your feedback. Our SDK is auto-generated by service swagger definition. From computer [spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-08-01/computeRPCommon.json#L903), it seems no related model with your feature. I think it should be a feature request. Could you please open an issue [here](https://github.com/Azure/azure-rest-api-specs/issues) that our service team could jump to help?

**Comment by harshavmb** [comment]
@tadelesh 

As asked, I opened an issue [here](https://github.com/Azure/azure-rest-api-specs/issues/21325).

**Comment by tadelesh** [comment]
Close as it is swagger issue.
