### ISSUE TITLE
Provide model related convenient methods

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#19433]
### Feature Request

Provide some convenient methods for SDK models in core lib, such as:
1. Deep copy between two same model
2. Copy between two different model with same field name and type
3. Equals method for model

The original requests are from AKS migration.

**Comment by tadelesh** [comment]
@jhendrixMSFT @JeffreyRichter What's your opinion?

**Comment by JeffreyRichter** [comment]
I'd like to see use cases for why these are necessary.
In general, we only put in the SDK, things that that the SDK needs. We do NOT want the SDK to be a dumping group for "convenient" functionality and these things seem like convenient functionality. The use case would have to be extremely useful and needed by many customers for us to take on this ask with documentation, tests, and long-term support.

All of these methods could be written using reflection by anyone - they would not be SDK-specific.

**Comment by tadelesh** [comment]
Basic copy function could be accomplished by this lib: https://github.com/jinzhu/copier.

**Comment by MartinForReal** [comment]
We adopt reconciler pattern in our code and if the status of azure resource meets the expectation, there will not be any new update requests. 
With this feature, we can make a deep copy first and check if the resources have changed after reconciliation. 

In other scenario, We need to implement a deep copy method to avoid shallow copy. 
deepcopy method is provided in protobuf, kubernetes api(https://github.com/kubernetes/code-generator/blob/master/cmd/deepcopy-gen/main.go).
