### ISSUE TITLE
Azure Error Interface

### ISSUE THREAD

**Issue by mussa572** [Azure/azure-sdk-for-go#19449]
Hi Team, 

I am looking to parse error Generated by azure api more specially from the Azure container service. AWS api provide the Error interface which makes it easy to parse the error link below. 

https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/

```
if azureErr, ok := err.(ezureerr.Error); ok {
             Get error details
             log.Println("Error:", azureErr.Code(), azureErr.Message())

           Prints out full error message, including original error if there was one.
            log.Println("Error:", azureErr.Error())

```

I am looking to something like above. Just wondering if there is such interface I can use for parsing Azure errors?

**Comment by jhendrixMSFT** [comment]
The type you're looking for is `*azcore.ResponseError`.  Please see the [docs](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#ResponseError) for more information.
