### ISSUE TITLE
Unable to write to container with SAS token

### ISSUE THREAD

**Issue by isabellachen** [Azure/azure-sdk-for-go#19454]
### Bug Report

I've been trying to achieve the basic example (create a container, upload and download a blob) with a SAS token.

I've been using[ this example](https://github.com/Azure/azure-sdk-for-go/blob/7a3989f70fa6c2d4376d0c72c01b5afc32b527f7/sdk/storage/azblob/service/examples_test.go#L286) which got me so far as to get a SAS token on the account level. But I am unable to execute the PUT request with the SAS token.

It would be really great if there could be an example of how to achieve this as it's a common need. 

```sh
User Delegation Key has been created for  mystorageaccount1
SAS URL:  https://mystorageaccount1.blob.core.windows.net/?se=2022-11-02T07%3A19%3A09Z&sig=6X7C...&ske=2022-11-02T07%3A18%3A57Z&skoid=e55...&sks=b&skt=2022-10-31T07%3A18%3A57Z&sktid=47d...&skv=2020-10-02&sp=r&spr=https&sr=c&st=2022-10-31T07%3A18%3A59Z&sv=2022-10-31

2022/10/31 15:19:09 PUT https://mystorageaccount1.blob.core.windows.net/testcontainer/loremipsum.txt
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:5efa6c73-401e-0034-29f9-ecd771000000
Time:2022-10-31T07:19:09.6147261Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>
--------------------------------------------------------------------------------
exit status 1
```

main.go
```go
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"strings"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service"
)

func handleError(err error) {
	if err != nil {
		log.Fatal(err.Error())
	}
}

func main() {
	accountName := "mystorageaccount1"

	cred, err := azidentity.NewDefaultAzureCredential(nil)
	handleError(err)

	svcClient, err := service.NewClient(fmt.Sprintf("https://%s.blob.core.windows.net/", accountName), cred, nil)
	handleError(err)

	// Set current and past time and create key
	currentTime := time.Now().UTC().Add(-10 * time.Second)
	pastTime := currentTime.Add(48 * time.Hour)
	info := service.KeyInfo{
		Start:  to.Ptr(currentTime.UTC().Format(sas.TimeFormat)),
		Expiry: to.Ptr(pastTime.UTC().Format(sas.TimeFormat)),
	}

	udc, err := svcClient.GetUserDelegationCredential(context.Background(), info, nil)
	handleError(err)
	fmt.Println("User Delegation Key has been created for ", accountName)

	blobSasQueryParams, err := sas.BlobSignatureValues{
		Version:       "2022-10-31",
		Protocol:      sas.ProtocolHTTPS,
		StartTime:     time.Now().UTC().Add(time.Second * -10),
		ExpiryTime:    time.Now().UTC().Add(48 * time.Hour),
		Permissions:   to.Ptr(sas.ContainerPermissions{Read: true}).String(),
		ContainerName: "testcontainer",
	}.SignWithUserDelegation(udc)
	handleError(err)

	sasURL := fmt.Sprintf("https://%s.blob.core.windows.net/?%s", accountName, blobSasQueryParams.Encode())
	
	fmt.Println("SAS URL: ", sasURL)

	// This URL can be used to authenticate requests now
	client, err := azblob.NewClientWithNoCredential(sasURL, nil)
	handleError(err)

	containerName := "testcontainer"
	blobData := "Lorem ipsum"
	blobName := "loremipsum.txt"
	uploadResp, err := client.UploadStream(context.TODO(),
		containerName,
		blobName,
		strings.NewReader(blobData),
		&azblob.UploadStreamOptions{
			Metadata: map[string]string{"Foo": "Bar"},
			Tags:     map[string]string{"Year": "2022"},
		})
	handleError(err)
	fmt.Println(uploadResp)

	blobDownloadResponse, err := client.DownloadStream(context.TODO(), containerName, blobName, nil)
	handleError(err)

	reader := blobDownloadResponse.Body
	downloadData, err := io.ReadAll(reader)
	handleError(err)
	fmt.Println("⬇️", string(downloadData))
	if string(downloadData) != blobData {
		log.Fatal("Uploaded data should be same as downloaded data")
	}

	err = reader.Close()
	if err != nil {
		return
	}
}

```

**Comment by souravgupta-msft** [comment]
Hi @isabellachen. Thanks for reaching out.
I see that you are using User Delegation SAS for your operations (create a container, upload and download a blob). Please note that we have identified a bug in the authentication using User Delegation SAS and we are working on getting it fixed, which will be part of our next release. I would also like to point out that User Delegation SAS cannot be used for some operations like creating, deleting or listing containers. Please refer [this](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-permissions) for more details.

As an alternative, you can create Account SAS for your use case. Yo can refer this [example](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/service/examples_test.go#L260). Just make sure to set the correct `Permissions` for `sas.AccountSignatureValues` for your use case.

**Comment by isabellachen** [comment]
@souravgupta-msft Thank you for the response.

I would like to know where in the code I am using the SAS to create a container as the container "testcontainer' has already been created in Azure prior to running the code. I am trying to upload a blob to the already created container.

I followed the [example which does it with the account key](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) and "testcontainer" was created when the example was run.

Would be great if you could provide an example and/or a bit more details for how to upload and download a blob to a pre-existing container with SAS. 

Or at least help me understand why, when I create the client with the SAS and attempt to upload the blob to the pre-existing container "testcontainer" I get the error above: "403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature."

I would have expected this code to create a blob and upload the data to that blob on "testcontainer":

```go
client, err := azblob.NewClientWithNoCredential(sasURL, nil)
	handleError(err)

	containerName := "testcontainer"
	blobData := "Lorem ipsum"
	blobName := "loremipsum.txt"
	uploadResp, err := client.UploadStream(context.TODO(),
		containerName,
		blobName,
		strings.NewReader(blobData),
		&azblob.UploadStreamOptions{
			Metadata: map[string]string{"Foo": "Bar"},
			Tags:     map[string]string{"Year": "2022"},
		})
	handleError(err)
	fmt.Println(uploadResp)
```

**Comment by souravgupta-msft** [comment]
> I've been trying to achieve the basic example (create a container, upload and download a blob) with a SAS token.

@isabellachen, from your above statement I thought you also wanted to create container using SAS token.


> Or at least help me understand why, when I create the client with the SAS and attempt to upload the blob to the pre-existing container "testcontainer" I get the error above: "403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature."

You are using User Delegation SAS here. 
```
udc, err := svcClient.GetUserDelegationCredential(context.Background(), info, nil)
	handleError(err)
	fmt.Println("User Delegation Key has been created for ", accountName)

blobSasQueryParams, err := sas.BlobSignatureValues{
		Version:       "2022-10-31",
		Protocol:      sas.ProtocolHTTPS,
		StartTime:     time.Now().UTC().Add(time.Second * -10),
		ExpiryTime:    time.Now().UTC().Add(48 * time.Hour),
		Permissions:   to.Ptr(sas.ContainerPermissions{Read: true}).String(),
		ContainerName: "testcontainer",
}.SignWithUserDelegation(udc)
```
Like I had mentioned in the previous comment, we have identified a bug in authentication using User Delegation SAS. We have a PR #19485 open for this.

> Would be great if you could provide an example and/or a bit more details for how to upload and download a blob to a pre-existing container with SAS.

Can you clarify which kind of SAS you want to use from the types mentioned [here](https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature#types-of-shared-access-signatures).
Irrespective of what kind of SAS you choose, your flow remains the same post client creation.
```
client, err := azblob.NewClientWithNoCredential(sasURL, nil)
```

**Comment by isabellachen** [comment]
Sorry, my mistake, I did say that I wanted to create a container with the user delegation SAS token. Thank you for specifically pointing out that is not possible with the user delegation SAS.

So, when the bug is fixed uploading the blob post client creation as I have done should work?

```go
client, err := azblob.NewClientWithNoCredential(sasURL, nil)
	handleError(err)

	containerName := "testcontainer"
	blobData := "Lorem ipsum"
	blobName := "loremipsum.txt"
	uploadResp, err := client.UploadStream(context.TODO(),
		containerName,
		blobName,
		strings.NewReader(blobData),
		&azblob.UploadStreamOptions{
			Metadata: map[string]string{"Foo": "Bar"},
			Tags:     map[string]string{"Year": "2022"},
		})
	handleError(err)
	fmt.Println(uploadResp)
```

**Comment by souravgupta-msft** [comment]
You will have to make the following change in your code. Rest of the code will remain the same.

```
blobSasQueryParams, err := sas.BlobSignatureValues{
          Protocol:      sas.ProtocolHTTPS,
          StartTime:     time.Now().UTC().Add(time.Second * -10),
          ExpiryTime:    time.Now().UTC().Add(48 * time.Hour),
          Permissions:   to.Ptr(sas.BlobPermissions{Read: true, Write: true, Create: true, Tag: true}).String(),
          ContainerName: Container,
}.SignWithUserDelegation(udc)
```

We will keep you posted once the PR is merged.

**Comment by isabellachen** [comment]
Thank you for the example! Looking forward to the bug fix.

**Comment by souravgupta-msft** [comment]
The PR has been merged. You can import from the main branch and validate.

**Comment by souravgupta-msft** [comment]
Closing this as fix will be part of the next release. Feel free to reopen if the issue persists.
