### ISSUE TITLE
Replacement for NewBearerAuthorizerCallback

### ISSUE THREAD

**Issue by jeffpuckett** [Azure/azure-sdk-for-go#19455]
### Feature Request
Autorest will not be supported in a few months. I don't see a replacement for the NewBearerAuthorizationCallback call. This is important with the new workflow identity model. Add a replacement and/or update the documentation with recommended alternatives. Thanks.

**Comment by chlowell** [comment]
The new API has something similar, but not exactly equivalent to, NewBearerAuthorizationCallback. If you want to insert custom authentication logic though, it's better to write a credential type (something implementing [azcore.TokenCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#TokenCredential)).

I haven't heard of work**flow** identity but if you mean work**load** identity, there's a simpler way. The latest azidentity beta has a [ClientAssertionCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.2.0-beta.3#ClientAssertionCredential) implementing the necessary authentication flow. It's pretty straightforward to build workload identity support on top of that; https://github.com/Azure/azure-sdk-for-go/issues/15615#issuecomment-1211012677 has an example implementation. (If you do mean work**flow** identity, please share a link to some documentation of it so I can come up with a better suggestion.)

**Comment by jeffpuckett** [comment]
I mean workload not workflow :eekemoji: sorry about that. 

Gonna be honest - I don't know exactly what I'm doing in terms of code. What I'm looking for is to get a keyvault client in an AKS pod using workload identity. I may have to dig some to figure out how to get the authorizer from this example. What stinks is the example published in workload identity is using autorest. But I think I can since this gets the token back. Thanks.

**Comment by chlowell** [comment]
The code would look like this given the workload identity implementation from https://github.com/Azure/azure-sdk-for-go/issues/15615#issuecomment-1211012677:
```go
cred, err := newWorkloadIdentityCredential(tenantID, clientID, file, nil)
if err != nil {
    // TODO: handle error
}
client := azsecrets.NewClient(vaultURL, cred, nil)
```
Most of the work is in configuring the cluster and pod. Sounds like you've seen docs for that already. Can you please share a link to the published example showing autorest? I'd like to update it.

**Comment by jeffpuckett** [comment]
here is the autorest example. thank you SO MUCH. https://github.com/Azure/azure-workload-identity/tree/main/examples/msal-go

**Comment by chlowell** [comment]
You're welcome, and thanks for the link. I'll mark this issue as addressed, but feel free to continue discussion here or to open another issue, if you encounter another problem.
