### ISSUE TITLE
Build Key Vault administration module

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#19461]
This module would contain clients for APIs not directly related to certs, keys or secrets, such as Key Vault RBAC and full vault backup/restore. See for example [Azure.Security.KeyVault.Administration](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/keyvault/Azure.Security.KeyVault.Administration). Start with `backuprestore.json` and `rbac.json` from [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/data-plane#tag-package-73).

**Comment by gracewilcox** [comment]
Tasks TODO

- [ ] learn about service (3 days)
- [ ] code generation (3 days)
- [ ] code changes (6 days)
- [ ] generate api view (1 day)
- [ ] tests (4 days)
- [ ] docs (3 days)
- [ ] archboard + feedback (5 days)

25 days
