### ISSUE TITLE
azcore: add support for dropping to HTTP/1 and/or TLS renegotiation in the default transport policy

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#19469]
Some endpoints don't support HTTP/2 and/or require TLS renegotiation to be enabled.  We can update the default transport policy to detect when these are required and react accordingly.

**Comment by jhendrixMSFT** [comment]
One place where this might get squirrely is callers provider a custom transporter (e.g. `httptrace`) which would remove this logic.  In that case, clients would then be broken.  We might need to export this policy so that callers can wrap it with a tracing implementation as needed.

**Comment by RickWinter** [comment]
Adding a workaround that can be used to configure a custom http client until an official fix is available, Thanks @chlowell for providing

```
import (
       "crypto/tls"
       "net/http"

       "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
       "github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
)

opts := arm.ClientOptions{ClientOptions: policy.ClientOptions{
       Transport: &http.Client{
              Transport: &http.Transport{
                     TLSClientConfig: &tls.Config{
                           Renegotiation: tls.RenegotiateFreelyAsClient,
                     },
              },
       },
}}
client, err := armsubscription.NewSubscriptionsClient(cred, &opts)
```

**Comment by YoshicoppensE61** [comment]
There are multiple people still suffering from this in the issue mentioned above https://github.com/Azure/terraform-provider-azapi/issues/184

**Comment by jhendrixMSFT** [comment]
The HTTP/1.1 issue appears to be a red herring (bad URL was provided).

**Comment by jhendrixMSFT** [comment]
TLS renegotiation has been enabled in `azcore@v1.7.1`
