### ISSUE TITLE
Add support for partial document updates in `azcosmos`

### ISSUE THREAD

**Issue by volmedo** [Azure/azure-sdk-for-go#19474]
### Feature Request

I recently learned about Cosmos DB supporting [partial document update](https://learn.microsoft.com/en-us/azure/cosmos-db/partial-document-update). Being able to patch documents from our Go service would greatly simplify our data model, as it is the perfect tool to support some of our use cases. Other SDKs, such as .NET and Java SDKs, have support for this since almost a year ago.

Any plans on adding a `PatchItem` method to `ContainerClient` and `TransactionalBatch`?

**Comment by ealsur** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-go/issues/18682

**Comment by volmedo** [comment]
sorry, clearly my search on existing issues wasn't great.

**Comment by ealsur** [comment]
No worries! If that's ok we can close this one, the future work is tracked through the other

**Comment by volmedo** [comment]
sure!
