### ISSUE TITLE
Managed Identity/IMDS auth: Configurable retry time-out

### ISSUE THREAD

**Issue by arluca** [Azure/azure-sdk-for-go#1948]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation can make the current thread wait for as long as 15 minutes. For response time sensitive services this might not be acceptable. It could also result in service unavailability if all threads are blocked for a token to be generated when a sudden burst arrives after a cold start.
The developer may want to fast fail after certain time interval says for example 10 seconds if the call is still failing.

Can we make the retry max configurable?

**Comment by jhendrixMSFT** [comment]
Do you have a sample I can investigate?  Until recently (see https://github.com/Azure/go-autorest/pull/281) the retry logic for refreshing an IMDS token had a cap of five iterations with a one second sleep in between.  If you're seeing delays up to 15 minutes there must be something additional at work here.

**Comment by jhendrixMSFT** [comment]
@arluca Do you have a repro you can share?

**Comment by arluca** [comment]
@jhendrixMSFT : Apologies for the delay. I don't have a repro on this. My understanding is that all SDKs had the same retry logic; however, that might not be true. @yugangw-msft can chime in. 

Ideally, the retry logic shouldn't be as simple as waiting one second between each try. There should be some randomization.

**Comment by jhendrixMSFT** [comment]
@arluca Recent implementations no longer have this simple one-second cap, specifically we follow the [recommended guidelines](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token#retry-guidance) (see my previous comment).  Do we still need to make this configurable?

**Comment by arluca** [comment]
@jhendrixMSFT : Yes, it would be great to have the ability to set the max retry limit. This is based on customer feedback, where they want to limit it to a 1-2 seconds and fail, rather than wait for the token.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.12.0
