### ISSUE TITLE
Invalid SAS URL gets generated from the sdk

### ISSUE THREAD

**Issue by mukhoakash** [Azure/azure-sdk-for-go#19507]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened? SAS URL generated doesn't follow azure storage api conventions
- What did you expect or want to happen? SAS URL generated should follow the azure storage api conventions
- How can we reproduce it?
Generate a SAS URL for a container using the sdk. It will generate something like this:
`https://myaccount.blob.core.windows.net/mycontainer/?sv=2012-02-12&st=2009-02-09&se=2009-02-10&sr=c&sp=r&si=YWJjZGVmZw%3d%3d&sig=dD80ihBh5jfNpymO5Hg1IdiJIEvHcJpCMiCMnN%2fRnbI%3d `

There is an extra `/` before the `?` in the SAS URL which is not interpreted correctly by the azure apis.

The correct SAS URL is:
`https://myaccount.blob.core.windows.net/mycontainer?sv=2012-02-12&st=2009-02-09&se=2009-02-10&sr=c&sp=r&si=YWJjZGVmZw%3d%3d&sig=dD80ihBh5jfNpymO5Hg1IdiJIEvHcJpCMiCMnN%2fRnbI%3d `

- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Which version of `azblob` are you using?  This should be fixed in [`v0.5.1`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/CHANGELOG.md#051-2022-10-11).

**Comment by souravgupta-msft** [comment]
@mukhoakash, can you verify the Go SDK version you are using. As @jhendrixMSFT pointed out, this is already fixed in [v0.5.1](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/CHANGELOG.md#051-2022-10-11). Can you please upgrade and validate.

**Comment by mukhoakash** [comment]
Hi @souravgupta-msft @jhendrixMSFT I have been using v0.5.0. I will upgrade to v0.5.1 and verify the fix. Thanks for your help here.

**Comment by souravgupta-msft** [comment]
@mukhoakash, did you get a chance to upgrade to v0.5.1 and validate?

**Comment by mukhoakash** [comment]
Hey @souravgupta-msft, I haven't had a chance to test the fix using the version upgrade. While I have gone through the changes which were made in v0.5.1. I will get back to you once I test it. Thanks!

**Comment by mukhoakash** [comment]
Hey @souravgupta-msft I have verified that this is working properly now. You can resolve this. Thank you.
