### ISSUE TITLE
[azservicebus] AcceptNextSessionForSubscription hangs, gets in an unrecoverable state

### ISSUE THREAD

**Issue by ryepup** [Azure/azure-sdk-for-go#19509]
### Bug Report

- import path: github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
- SDK version: 1.1.0
- go version: 1.18.x

#### What happened?

We use session receivers extensively, and have one loop always listening for the next available session. Usually we get a `com.microsoft:timeout, Description: The operation did not complete within the allotted timeout of 00:01:05.` error when there are no new sessions available, and keep looping.

I'm not clear what happened, but after some time `AcceptNextSessionForSubscription` stops returning the `com.microsoft:timeout` errors, and hangs forever.

We applied the workaround from #18517, but that did not recover our connections. Once we get a deadline exceeded instead of a `com.microsoft:timeout`, we are unable to get a new session until we restart the process.

#### What did you expect or want to happen?

I want the AMQP connections / links to automatically recover.

#### How can we reproduce it?

I'm not sure. My best guess is something with the network, but I have no evidence.

#### Anything we should know about your environment.

We're running in AKS in different azure regions, and have seen the issue in different regions.

### Analysis

We use `log.SetListener` to capture logs, and see a few sequences around the hang:

|event|message|
|-|-|
|azsb.Receiver|Received 0/1 messages|
|azsb.Conn|Closing links for error link detached, reason: *Error(nil)|
|azsb.Receiver|Response router has shut down|
|azsb.Receiver|Failure when receiving messages: link detached, reason: *Error(nil)|

Those 4 repeat themselves in different orders for few seconds, then about 20s later we get a different pattern:

|event|message|
|-|-|
|azsb.Receiver|Asking for 1 credits|
|azsb.Receiver|Only need to issue 1 additional credits|

Those repeat for about a minute, then we get a few more of our expected `com.microsoft:timeouts`, then we're back to repeating the first `*Error(nil)` pattern, and then the `Asking for 1 credits` pattern. After a few minutes it settles down and our `context.WithDeadline` workaround starts cancelling every `AcceptNextSessionForSubscription` call until we restart the process.

I've attached an export of our logs: [results.csv](https://github.com/Azure/azure-sdk-for-go/files/9954358/results.csv)

The `*Error(nil)` looks similar to #17029. Maybe related to https://github.com/Azure/go-amqp/issues/127?

### Workaround

Similar to #18517, we use a `context.WithDeadline` to allow  `AcceptNextSessionForSubscription` to exit, but instead of retrying `AcceptNextSessionForSubscription`, we return an error that eventually restarts the whole process.

**Comment by richardpark-msft** [comment]
Hey @ryepup, looking at this now.

**Comment by ryepup** [comment]
y'all are fast!

**Comment by richardpark-msft** [comment]
Hey @ryepup, I'm still looking at this but I must be missing some component to reproduce it. I'm adding in some more long-haul tests to see if there's something that only happens over a longer period of time.

> We applied the workaround from https://github.com/Azure/azure-sdk-for-go/issues/18517, but that did not recover our connections. Once we get a deadline exceeded instead of a com.microsoft:timeout, we are unable to get a new session until we restart the process.

Sessions are allocated at the AMQP connection level, so restarting the connection itself would be required (ie, the azservicebus.Client). That might be what you did, but I just wanted to confirm. 

Can you show me a pseudo-ish-code version of your application so I can get a sense of how it's structured?

**Comment by ryepup** [comment]
I'm not sure how to reproduce it either, this feels like a tough one.

What we're doing at a high level:

1. open one `azservicebus.Client` for the application, use a `context.Context` to manage the lifetime of all the goroutines. We only close this when the app shuts down.
2. run an infinite `for` loop calling `AcceptNextSessionForSubscription`
3. when we get a new session, we start a few new goroutines to handle it:
    1. start another loop calling `RenewSessionLock` until the context is cancelled
    2. start another loop calling `ReceiveMessages` until the context is cancelled - this step is wrapped in a loop and `context.WithTimeout` as in the #18517 workaround
    3. when we get a message, it gets passed through a channel to the rest of our business logic. Further down the line that code calls `Complete`, `Abandon`, or `DeadLetter` on the message. In some rare error cases we close our context (and thus all these goroutines) before finalizing the message. In other cases it can take 10+ minutes before the business logic finalizes the message
    4. eventually the session receives a "shut down" message, which cancels the context and calls `Close()` on the session receiver
    5. these goroutines are very long-lived; can exist for days or weeks
4. sometimes we get the session id from another source, and start the same set of goroutines as above with `AcceptSessionForSubscription`

**Comment by richardpark-msft** [comment]
Hi @ryepup, don't have this repro'd yet, but I'm adding in some more testing around this area to see if we can flush it out.
