### ISSUE TITLE
Race condition reported in sdk/internal 1.0.1

### ISSUE THREAD

**Issue by ianeal** [Azure/azure-sdk-for-go#19528]
### Bug Report

Race condition detected in sdk/internal/temporal/resource.go

SDK version latest (using latest go modules as of yesterday, Nov 08, 2022)
	github.com/Azure/azure-sdk-for-go/sdk/azcore v1.2.0
	github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor v0.8.0
	github.com/Azure/azure-sdk-for-go/sdk/internal v1.0.1 // indirect

go version go1.19.3 linux/amd64

- What happened?

Ran go program with the -race flag and it detected the following problem.

`==================
WARNING: DATA RACE
Read at 0x00c0003aa400 by goroutine 4183:
  github.com/Azure/azure-sdk-for-go/sdk/internal/temporal.(*Resource[...]).Get()
      github.com/Azure/azure-sdk-for-go/sdk/internal@v1.0.1/temporal/resource.go:52 +0xd9
  github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime.(*BearerTokenPolicy).Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/arm/runtime/policy_bearer_token.go:68 +0x18b
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*retryPolicy).Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/policy_retry.go:127 +0x70e
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  densify.com/cloudaudit.git/cloudclients/azureclient.(*LoggingPolicy).Do()
      densify.com/cloudaudit.git/cloudclients/azureclient/azureclient.go:107 +0x64
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.telemetryPolicy.Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/policy_telemetry.go:66 +0x25b
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*telemetryPolicy).Do()
      <autogenerated>:1 +0x64
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.includeResponsePolicy()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/policy_include_response.go:19 +0x30
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.policyFunc.Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/pipeline.go:76 +0x36
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.Pipeline.Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/pipeline.go:96 +0x256
  github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor.(*MetricsClient).List()
      github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor@v0.8.0/metrics_client.go:64 +0x105
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).getMetricsDataForResource()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:506 +0x7b5
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).CollectMetrics.func1()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:356 +0x15b4
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).CollectMetrics.func5()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:432 +0x66

Previous write at 0x00c0003aa400 by goroutine 4162:
  github.com/Azure/azure-sdk-for-go/sdk/internal/temporal.(*Resource[...]).Get()
      github.com/Azure/azure-sdk-for-go/sdk/internal@v1.0.1/temporal/resource.go:99 +0x68e
  github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime.(*BearerTokenPolicy).Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/arm/runtime/policy_bearer_token.go:68 +0x18b
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*retryPolicy).Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/policy_retry.go:127 +0x70e
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  densify.com/cloudaudit.git/cloudclients/azureclient.(*LoggingPolicy).Do()
      densify.com/cloudaudit.git/cloudclients/azureclient/azureclient.go:107 +0x64
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.telemetryPolicy.Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/policy_telemetry.go:66 +0x25b
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*telemetryPolicy).Do()
      <autogenerated>:1 +0x64
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.includeResponsePolicy()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/policy_include_response.go:19 +0x30
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.policyFunc.Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/runtime/pipeline.go:76 +0x36
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/request.go:84 +0x23c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.Pipeline.Do()
      github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.2.0/internal/exported/pipeline.go:96 +0x256
  github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor.(*MetricsClient).List()
      github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor@v0.8.0/metrics_client.go:64 +0x105
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).getMetricsDataForResource()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:506 +0x7b5
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).CollectMetrics.func1()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:356 +0x15b4
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).CollectMetrics.func5()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:432 +0x66

Goroutine 4183 (running) created at:
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).CollectMetrics()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:304 +0x1fbd
  main.listener.Handle.func3()
      /home/ian/GolandProjects/workspace-aws-sdk-v2/cloudcollector-v2/collector.go:131 +0x3e

Goroutine 4162 (running) created at:
  densify.com/cloudcollector.git/azurecollection.(*AzureMonitor).CollectMetrics()
      densify.com/cloudcollector.git/azurecollection/azurecollection.go:304 +0x1fbd
  main.listener.Handle.func3()
      /home/ian/GolandProjects/workspace-aws-sdk-v2/cloudcollector-v2/collector.go:131 +0x3e
==================`

- What did you expect or want to happen?

Expect no data race condition to be reported.

- How can we reproduce it?

Appears to be related to using a single armmonitor metricsClient but using multiple go routines to fetch the workload metrics for the various resources.  

Don't currently have a test program I could provide, but if needed I could provide one.  

However, I believe the fix simply involves moving  "now, acquire, expired, resource := time.Now(), false, false, er.resource" line inside the er.cond.L.Lock()

- Anything we should know about your environment.

Running on Linux Mint 20.3 Una

**Comment by jhendrixMSFT** [comment]
The fix will roll out in `internal@v1.1.1` later today.
