### ISSUE TITLE
Write a tool to help export test status of all mgmt. modules

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#19540]
Sample:

|module | tag | live test result | live test coverage | mock test result | mock test coverage|
|---|---|---|---|---|---|
|apimanagement | package-2022-09-01 | 100%(12/12) | 56%(1041/1820) | 100%(78/78) | 56%(1041/1820)|
|aad | package-2022-09-01 | / | / | 100%(78/78) | 56%(1041/1820)|
|avg | / | 100% | 56% | 100% | 56%|

**Comment by Alancere** [comment]
export: https://chenjieshistorage.z13.web.core.windows.net/mgmtReport2.html

**Comment by tadelesh** [comment]
Add operation coverage:
1. Test generator will generate live test code with a print line to print out operation id
2. Calculate live test operation id coverage with: grep above print log and remove duplication to count called operation id / all operation id from mock test log
3. Calculate mock test operation id coverage with: grep all `=== RUN   TestMockTest/` to count all operation id - `--- SKIP: TestMockTest/` to count test without example / all operation id count
