### ISSUE TITLE
[Cosmos DB] Add support for deleting all documents by partition key

### ISSUE THREAD

**Issue by volmedo** [Azure/azure-sdk-for-go#19563]
### Feature Request

Cosmos DB Service API supports [deleting every document within a logical partition](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-delete-by-partition-key?tabs=dotnet-example) in a single operation (in preview mode).

Adding a `DeleteAllItemsByPartitionKey` to the `Container` type would be an extremely useful feature that several use cases and data models could benefit from.

**Comment by ealsur** [comment]
We'll schedule the work once this feature is GA, thanks for your feedback (adding it to the tracking boards)

**Comment by volmedo** [comment]
Thanks @ealsur.

The article mentions it is supported in the Java SDK from version 4.19.0, which dates back to September 10 2021. Thus, the feature has been in preview for, at least, more than a year now. Do you know if that's something that happens frequently? Does that fact give any information about when the feature could be released?

Also, I understand your resources are limited and investing them in supporting features not generally available may not be a priority. But IMO having access to this functionality in the Go SDK would be valuable, even if the feature is still in preview.

**Comment by ealsur** [comment]
@volmedo I don't know the per-feature roadmap honestly (or why it has been in preview for this long).

Having "preview" APIs on clients really depends on the language and if it's possible. As you mention, our current resources are limited and should focus them when available on GA features/critical components (like failover).

The [Go SDK guidelines](https://azure.github.io/azure-sdk/golang_introduction.html) do not mention about flighting "preview" APIs, I will defer to @jhendrixMSFT to see if this is possible on Go or desired.

**Comment by ealsur** [comment]
@c-brooks The service API is not yet GA, we don't know when this feature (on the service side) will release and if the client APIs might need to change. Any work done for this feature is uncertain from the SDK surface perspective.

Based on the Azure SDK guidelines, in order to provide these non-GA APIs, there might be a Go-specific way to mark them as "You should not use this in production", hence my last comment.

To reiterate, the work can be started by anyone but this feature is not meant for production usage as it is still under preview and public API surface for SDKs is reviewed by the Architecture team.

**Comment by ealsur** [comment]
@kanilsz There are two parts of any feature, the client APIs (SDKs) and the Service. For Delete By Partition Key, the Service part is not yet GA. A client SDK cannot have an API in GA if the Service side of it is not. The date is not driven by the client APIs, but by the Service.

**Comment by kanilsz** [comment]
@ealsur Is there any chance that is could be on the service side and then in SDK?

**Comment by ealsur** [comment]
@kanilsz Not sure I understand your question, sorry. This feature is in Preview in the Service side at the moment. Once the feature goes GA on the Service side, then we can include it in an SDK release.

**Comment by kanilsz** [comment]
@volmedo could we know somehow when it goes to GA?

**Comment by onionhammer** [comment]
Any update on this going GA?
