### ISSUE TITLE
Unable to create private DNS zone for redis private endpoint

### ISSUE THREAD

**Issue by amiramw** [Azure/azure-sdk-for-go#19564]
### Bug Report

- import path of package in question, e.g. `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork`
- SDK version e.g. `1.10`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`: `go1.19.2 darwin/arm64`

I'm trying to create private DNS zone for an Azure cache redis private endpoint.
I'm trying to use `armnetwork.PrivateDNSZoneGroupsClient.BeginCreateOrUpdate()` API. I provided resourceGroupName, endpointName, dnsGroupName and `PrivateDNSZoneConfig` with full name of the `PrivateDNSZoneID` in various formats (for example: /subscriptions/<subId>/resourceGroups/<groupId>/providers/Microsoft.Network/privateEndpoints/<endpointName>/privateDnsZoneGroups/<groupId>/privateDnsZones/privatelink.redis.cache.windows.net

None of them works for me and I get the message: 

`Private Dns Zone group /subscriptions/<subId>/resourceGroups/<groupId>/providers/Microsoft.Network/privateEndpoints/<endpointName>/privateDnsZoneGroups/<groupId> has invalid private dns zone ids .`

1. Should the private DNS zone exist prior to calling this API? If so how can I create it programmatically? 
2. If not, what is the expected structure of PrivateDNSZoneID I should pass to this API?

**Comment by Alancere** [comment]
armredis create private endpoint you could refer to: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/redis/armredis/redis_live_test.go#L320
