### ISSUE TITLE
containerservice.NetworkProfile.NetworkPolicy type doesn't allow empty policy

### ISSUE THREAD

**Issue by austintackaberry** [Azure/azure-sdk-for-go#19582]
### Bug Report

https://github.com/Azure/azure-sdk-for-go/blob/v63.4.0/services/containerservice/mgmt/2022-03-01/containerservice/models.go#L2891

- What happened?

NetworkProfile.NetworkPolicy type is `NetworkPolicy` which means that you have to set NetworkPolicy to either "azure" or "calico". The problem with this is that you can't create a dual stack AKS cluster.

"calico" is not supported for dual stack clusters and "azure" is not supported with kubenet. And kubenet is the only network plugin that supports dual stack.

**Comment by matthchr** [comment]
NetworkPolicy is not listed as optional in our OpenAPI specification: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-09-01/managedClusters.json#L3129

I suspect that this is a track1 vs track2 Go SDK thing, and that the track2 SDK correctly generates this as `*NetworkPolicy`. Can you confirm @jhendrixMSFT?

**Comment by jhendrixMSFT** [comment]
Correct, in our new SDK we do generate this as pointer-to-type https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/containerservice/armcontainerservice/models.go#L2081.

For the legacy SDK, can you not simply leave the field empty?  Or is validation preventing that?

**Comment by austintackaberry** [comment]
I was able to set it to empty string and it worked. Thanks!
