### ISSUE TITLE
Unit-testing with track 2 SDK 

### ISSUE THREAD

**Issue by prashantcfc** [Azure/azure-sdk-for-go#19580]
Hi, 

In the latest Azure SDK, there are no interfaces unlike the previous versions, e.g

(https://github.com/Azure/azure-sdk-for-go/blob/v63.4.0/services/preview/eventgrid/mgmt/2021-06-01-preview/eventgrid/eventgridapi/interfaces.go)

These were quite helpful in unit-testing/mocking.

Going forward, what's the recommendation for writing unit-tests for clients that consume the SDK in the absence of these interfaces?

Also, is there a way to inject a mock server while initialising clients with the latest SDK ?

**Comment by jhendrixMSFT** [comment]
Our current POR is to generate fakes alongside the SDK.  This is not an interface-based mock solution like in our previous versions.  You can find further info in https://github.com/Azure/azure-sdk-for-go/issues/16613 which is tracking this work (closing this as duplicate).

**Comment by prashantcfc** [comment]
@jhendrixMSFT any tentative timeline when fakes would be available?
