### ISSUE TITLE
Deprecate loadtestservice package

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#19589]
We need to deprecate this package and ship the new one as a `Beta`

https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/loadtestservice/armloadtestservice

It should instead by loadtesting/armloadtesting.

**Comment by ArcturusZhang** [comment]
We need to do the following：
1. change the information in the corresponding [readme.go.md](https://github.com/Azure/azure-rest-api-specs/blob/c71a66dab813061f1d09982c2748a09317fe0860/specification/loadtestservice/resource-manager/readme.go.md) to the new name
2. release a new RP with the name from the latest commit in swagger for `loadtesting`
3. retract the old `loadtestservice/armloadtestservice`

**Comment by ArcturusZhang** [comment]
loadtesting/armloadtesting/v0.1.0 is released here: https://github.com/Azure/azure-sdk-for-go/pull/19604

We accidentally released v1.0.0 for this module, then we retracted version v1.0.0 and v1.0.1 (containing the retraction).

Closing this issue
