### ISSUE TITLE
Enable gofmt/govet/golint for ./arm/...

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#196]
@brendandixon please feel free to edit .travis.yml accordingly when you feel comfortable enabling those checks for the `arm` package.

**Comment by brendandixon** [comment]
@ahmetalpbalkan It's on the to-do list.

**Comment by ahmetalpbalkan** [comment]
apparently done. :)

@brendandixon GitHub protip: If you add your commit message something like "Fixes #xxx" or "Closes #xxx", when commit is merged, issue(s) will close automatically once the commit is merged. https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by brendandixon** [comment]
@ahmetalpbalkan Sweet. I did not know that.
