### ISSUE TITLE
List metric statistic values

### ISSUE THREAD

**Issue by meirf** [Azure/azure-sdk-for-go#1961]
AWS Cloudwatch has an api which allows fetching metric statistics:

 - [CloudWatch GetMetricStatistics REST](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html)
 - [CloudWatch GetMetricStatistics Go implementation](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.GetMetricStatistics)

I have been able to find the REST definition for azure which appears to have similar functionality:

 - [Azure list metric values REST](https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list)

but I can't find the Go implementation. `azure-sdk-for-go ` has a lot of code in it, but I can't find the code for listing metric values.

---

Some more details:
I am trying to get status code statistics for an application gateway.

**Comment by meirf** [comment]
@jhendrixMSFT any thoughts on this?

**Comment by jhendrixMSFT** [comment]
@meirf I believe the package you want is located [here](https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/monitor/mgmt/2018-03-01/insights).  Let me know if this works for you.

**Comment by meirf** [comment]
It looks like I'll end up using this to get data from Germany:
`github.com/Azure/azure-sdk-for-go/services/monitor/mgmt/2017-09-01/insights.NewMetricsClientWithBaseURI`

I'm closing this issue. You can see my reasoning below. (If you're feeling generous ptal at the below and let me know if I'm making a big mistake.)

Germany currently supports these api versions:

- 2016-06-01
- 2016-09-01
- 2017-05-01-preview
- 2017-09-01-preview
- 2018-01-01

These are 3 api versions in this repo for metrics:

- services/monitor/mgmt/2017-05-01-preview/insights (deprecated -> services/preview/monitor/mgmt/2017-05-01-preview/insights)
- services/monitor/mgmt/2017-09-01/insights
- services/monitor/mgmt/2018-03-01/insights (deprecated -> services/preview/monitor/mgmt/2018-03-01/insights)

I can't use services/monitor/mgmt/2018-03-01/insights since it's not supported in germany. And I prefer services/monitor/mgmt/2017-09-01/insights since it's later than services/monitor/mgmt/2017-05-01-preview/insights and appears to have a better API.
