### ISSUE TITLE
PartnerDestination (Channel) APIs are missing

### ISSUE THREAD

**Issue by prashantcfc** [Azure/azure-sdk-for-go#19621]
### Service Package Request

Hello,

The latest Azure SDK seems to be based on stable APIs (https://github.com/Azure/azure-rest-api-specs/tree/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/stable/2022-06-15) -- These do not contain specifications for PartnerDestinations.

Since I want to leverage the go SDK to create channels of type PartnerTopic as well as PartnerDestination -- what would be the right way going forward ?

**Comment by ahamad-MS** [comment]
This is by design as Partner Destination feature is not ready for GA and hence is not part of 2022-06-15 swagger and hence corresponding GO SDK will not have support for it.

If you need to support both Partner topic scenarios as well as partner destination scenarios using single API version/SDK, then you need to keep using GO SDK corresponding to API version 2021-10-15-preview.

**Comment by lirenhe** [comment]
Currently, we don't have the SDK for 2021-10-15-preview.    
@prashantcfc, will this SDK package for 2021-10-15-preview solve your problem?
@ArcturusZhang, could you help to check whether we could release that or there are other workarounds.  

Thanks

**Comment by prashantcfc** [comment]
@ahamad-MS @lirenhe Yes, I need the SDK package for 2021-10-15 preview APIs.

It is missing in the latest codebase of go SDK. Without this package, how can I consume PartnerDestination APIs (2021-10-15 preview) ?

**Comment by ArcturusZhang** [comment]
Hi @prashantcfc  You could use the base arm client defined [here](https://github.com/Azure/azure-sdk-for-go/blob/df8390a6777e2040ecbaa531efd20318be6f462e/sdk/azcore/arm/client.go#L35) to directly send raw rest api call as a workaround.

In the meantime, we will work with the corresponding service team to release a new beta version of the package as soon as possible

**Comment by prashantcfc** [comment]
@ArcturusZhang Why would you release a 'beta' version of preview APIs ? I didn't understand this...

Also, may I know the reason why the preview APIs were removed from the SDK ? These were present in the older releases.

**Comment by Alancere** [comment]
package released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventgrid/armeventgrid@v0.6.0
