### ISSUE TITLE
Batch API Request for Flex VM instances deletion

### ISSUE THREAD

**Issue by vishwa-krishnan** [Azure/azure-sdk-for-go#19636]
### Feature Request

Currently the Golang sdk has a virtual machine client "BeginDelete" function that takes one vm name for deletion. The request is to provide a batch api that takes multiple vm names for deletion just like in a VMSS client API "BeginDeleteInstances". This is required to scale down the VMs in a better way without being rate limited.

**Comment by lirenhe** [comment]
Seems to be a request for service team, can CXP team help?

**Comment by xboxeer** [comment]
@vishwa-krishnan this feature need Azure VM service implement a new API that support batch delete VM, even if SDK team provide a wrapped function that support deleting VM in batch, we'll still hit the rate limit of API call
I'd suggest you can raise your feature request in this place: [Share your ideas](https://feedback.azure.com/d365community/forum/ec2f1827-be25-ec11-b6e6-000d3a4f0f1c) to let Azure VM team aware of this feature request

**Comment by fitzgeraldsteele** [comment]
Responded directly to @vishwa-krishnan via email:

I validated to GO SDK batch delete VM for VMSS Flex works as expected. [See this sample implementation ](https://github.com/Azure/vm-scale-sets/blob/golang-delete/vmss-flex-golang-sample/main.flex.go)

Happy to leave this issue open until you're able to validate what you were seeing on your side that wasn't working

**Comment by fitzgeraldsteele** [comment]
In the sample I set Orchestration mode explicitly. And you see instance ids are flex style, not uniform.

**Comment by fitzgeraldsteele** [comment]
Generally, check the OrchestrationMode property.

**Comment by navba-MSFT** [comment]
@vishwa-krishnan Thanks for getting back. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
