### ISSUE TITLE
Azure FrontDoor Standard

### ISSUE THREAD

**Issue by alexander-e-andrews** [Azure/azure-sdk-for-go#19640]
### Service Package Request

Please add support for the new version of azure Frontdoors standard and premium. Current armfrontdoor.NewFrontDoorsClient gets from /providers/Microsoft.Network while the new Frontdoors exist under /providers/Microsoft.Cdn

**Comment by lirenhe** [comment]
@alexander-e-andrews, the Go SDK is auto generated from OpenAPI files in https://github.com/Azure/azure-rest-api-specs/tree/main/specification, could you help to specify what source of API definition file you needed?  thanks

**Comment by alexander-e-andrews** [comment]
@lirenhe Through that I found that it had been implemented under the cdn as AFD. Thank you
