### ISSUE TITLE
Please stop changing the public interface

### ISSUE THREAD

**Issue by vangent** [Azure/azure-sdk-for-go#19654]
I'm having to rewrite my whole library for the second time this year when upgrading from 0.4.1 to 0.5.1. Come on.

**Comment by siminsavani-msft** [comment]
Hi @vangent ! We really appreciate your feedback and patience! We wanted to improve the user experience of the SDK which led to a large refactoring and a refactor this big is unlikely to occur again as we are wrapping things up for GA release soon. Just as a note, there may be minor breaking changes as we clean things up. We look forward to your feedback on how we can improve the experience of the Go SDK and apologies for the inconvenience!

**Comment by vangent** [comment]
Thank you for the response, and apologies for my frustration.

Minor breaking changes are generally OK with me, they are easy to fix.

I was frustrated by the 2 *major* refactorings in a short period of time: one major migration from the old libraries (https://github.com/Azure/azure-storage-blob-go) to the new one (https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob), and then another one between 0.4 and 0.5 in the new one. Both included changing many names in the API, changing packages, and other changes that were really not obvious how to port from one version to the other. Both took me many hours to handle (commits below if you're interested). I manage a library, and I can't hide all details of the API, so it's causing churn for my users as well. 

Overall, I wish you had held off on recommending the move from the old packages to 0.4 if you were going to refactor everything again; then I would have only had to go through that once.

https://github.com/google/go-cloud/commit/e1a8e6f0c1d3ba55d8839194b16e0674d519f731
https://github.com/google/go-cloud/commit/0c45fa60411312d52335c521a8a8411a15e1ce71

**Comment by vibhansa-msft** [comment]
We are planning for a GA of azblob and by then we wish to fix these inconsistencies. Post GA there shall not be any breakages unless absolutely necessary. Thanks for your patience.

**Comment by vibhansa-msft** [comment]
Closing this as GA will be done this week.
