### ISSUE TITLE
Blob storage uploads fail for files > 2GB on azblob v0.5.1

### ISSUE THREAD

**Issue by ben-east** [Azure/azure-sdk-for-go#19651]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- `import github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service`
- `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.5.1`
- `go version go1.19.3 linux/amd64`

What happened?

File uploads to Azure blob storage fail for files larger than ~2GB. We were able to reproduce this using a minimal blob storage client and a 3GB file generated via `fallocate -l 3G big_file`. After monitoring the progress, it appears that the file is fully uploaded but the client fails on some terminal step. We've verified that the full file size is reported as uploaded by the progress function. 

The error message:

```
fail to upload blob: Put "https://my-storage-account.blob.core.windows.net/artifacts/beneast-test-blob?blockid=N2I5OGJiYzgtNjk3Yi00ZGNhLTQzYmQtY2Y3Y2VjZTcyYWVk&comp=block": net/http: HTTP/1.x transport connection broken: http: ContentLength=24528 with Body length 0
```

- What did you expect or want to happen?
The upload should complete without errors

- How can we reproduce it?
Generate a file using `fallocate -l 3G big_file`, then create a block blob client, upload the large file to Azure storage. A little example may be:

```
serviceClient, err := azblob.NewServiceClient(storageAccountURL, credential, nil)
containerClient, err := serviceClient.NewContainerClient(containerName)
blobClient, err := containerClient.NewBlockBlobClient(blobPath)

var bytesWritten int64
uploadOption := azblob.UploadOption{
    Progress: func(bytes int64) {
        bytesWritten = bytes
    },
    Concurrency: 4
}
blobClient.UploadFile(ctx, file, uploadOption)
```

- Anything we should know about your environment.
We've reproduced in multiple Azure environments, and believe this is specific to the blob storage SDK that is used. This issue appeared after updating from `azblob @ 0.4.1` to `azblob @ 0.5.1`.

**Comment by jhendrixMSFT** [comment]
I can repro this.  However, in my case, the error left the blob in an incomplete state.  It looks like this happens when the `*http.Request.Body` has a length less than what's specified in `*http.Request.ContentLength`.
