### ISSUE TITLE
How do I get the public type for generated.BlobPrefix etc.?

### ISSUE THREAD

**Issue by vangent** [Azure/azure-sdk-for-go#19655]
### Bug Report

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container#ListBlobsHierarchyResponse
Version `0.5.1`

The response has:
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/generated#BlobHierarchyListSegment

I would like to pass these `BlobPrefix` and `BlobItemInternal` things around in functions in my code, but their types are not public. They are in an `internal/generated` package that I can't access.

**Comment by jhendrixMSFT** [comment]
The `generated.BlobItemInternal` type is exposed as a type alias `container.BlobItem`.  There is no corresponding type alias for `BlobPrefix` at present.  That said, I get that this is non-intuitive.  Will discuss options with the team.

**Comment by jhendrixMSFT** [comment]
These missing types, and some others I found, have been added and will go out in `v0.6.0`.  Please note that type `BlobItemInternal` has been renamed to `BlobItem`.  Thanks for the bug report.

**Comment by sfc-gh-kleonhard** [comment]
When attempting to create a fake, in-memory, blob store for unit testing, I stumbled onto this issue. Are these available as type aliases somewhere?

- generated.ListBlobsFlatSegmentResponse
- generated.BlobFlatListSegment
- generated.BlobClientDownloadResponse

**Comment by jhendrixMSFT** [comment]
@sfc-gh-kleonhard please see https://github.com/Azure/azure-sdk-for-go/issues/19775 which I believe will address this.

**Comment by vangent** [comment]
> When attempting to create a fake, in-memory, blob store for unit testing

Consider Go CDK! https://github.com/google/go-cloud/
