### ISSUE TITLE
ImagesClient does not support creating images from ARM64 architecture snapshots

### ISSUE THREAD

**Issue by Narunas-K** [Azure/azure-sdk-for-go#19665]
### ImagesClient does not support creating images from ARM64 architecture snapshots

import path: `"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"@v4.0.0 `
go version:  `go1.19 darwin/arm64`

I am trying to create image from ARM64 Virtual Machine Disk snapshot. However, ImagesClient is not supporting creating image from ARM64 architecture snapshots. For code snippet below getting the response:
```
failed to finish create image request: PUT https://management.azure.com/subscriptions/xxxxxxxx/resourceGroups/rq/providers/Microsoft.Compute/images/imageName
RESPONSE 409: 409 Conflict
ERROR CODE: OperationNotAllowed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "OperationNotAllowed",
    "message": "Creating an image with snapshot source that has CPU Architecture 'Arm64' is not supported. Please select a source resource with a supported CPU Architecture: 'x64'."
  }
}
```
```
        imageClient, err := armcompute.NewImagesClient("subscriptionId", creds, nil)
	poller, err := imageClient.BeginCreateOrUpdate(ctx,
		rg,
		imageName,
		armcompute.Image{
			Location: lo.ToPtr("West Europe"),
			Properties: &armcompute.ImageProperties{
				HyperVGeneration: lo.ToPtr(armcompute.HyperVGenerationTypesV2),
				StorageProfile: &armcompute.ImageStorageProfile{
					OSDisk: &armcompute.ImageOSDisk{
						OSState:            lo.ToPtr(armcompute.OperatingSystemStateTypesGeneralized),
						OSType:             lo.ToPtr(armcompute.OperatingSystemTypesLinux),
						StorageAccountType: lo.ToPtr(armcompute.StorageAccountTypesPremiumLRS),
						Snapshot: &armcompute.SubResource{
							ID: snapshot.ID,
						},
					},
				},
			},
		},
		nil)
```

**Comment by navba-MSFT** [comment]
@Narunas-K Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Narunas-K AFAIK, this issue is by design. We can replicate this issue with other SDKs too. 

This is described in the Azure Compute Gallery documentation here - [Create an image definition and image version - Azure Virtual Machines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/virtual-machines/image-version?tabs=portal)

> “Many new features like ARM64, Accelerated Networking and TrustedVM are only supported through Azure Compute Gallery and not available for managed images.” 

Hope this helps.

**Comment by Narunas-K** [comment]
@navba-MSFT  thank you! Do you know if it is planned to support ARM64 architecture for managed images at all? Or managed images will be deprecated as a feature in Azure?

**Comment by navba-MSFT** [comment]
@Narunas-K Did you get a chance to look at the[ above comment ](https://github.com/Azure/azure-sdk-for-go/issues/19665#issuecomment-1343773002)? Could you please let us know if you have any follow-up questions on this ?

**Comment by Narunas-K** [comment]
@navba-MSFT  sorry for confusion, I got all information that I needed. Thank you for your help. Resolving the question.
