### ISSUE TITLE
PrivateDNS does not expose ResourceGroup

### ISSUE THREAD

**Issue by pieterlexis-tomtom** [Azure/azure-sdk-for-go#19666]
### Bug Report

- import path of package in question: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns"
- SDK version: Module version 1.0.0
  - I can see the code missing in current master (c8c9838f7dc383a0bc2ad7b6cc09d51eb619d8f6)
- output of `go version`: `go version go1.19.2 linux/amd64`

##  What happened?
The [`PrivateZone` model](https://github.com/Azure/azure-sdk-for-go/blob/b59a1b2dd4fd1ba32d8c08033aa92859f3a12db0/sdk/resourcemanager/privatedns/armprivatedns/zz_generated_models.go#L60) does not expose the ResourceGroup field. 

This means that after listing the zones in a subscription, I cannot call `Get` (or any other function of the `PrivateZonesClient`) as it requires the `ResourceGroup` parameter.

As a work-around, I could parse the `Id` field myself, as it is formatted as `/subscription/{subid}/resourceGroups/{resourcegroupid}/......`, but I prefer a `ResourceGroup` field in the `PrivateDNS` object.

When using the `az` command-line client, the resource group is included as separate field in the output:

![screenshot-2022-12-06_17:09:51](https://user-images.githubusercontent.com/99655972/205965003-d3fc4915-6bef-46f8-88e4-6e8f638ecd7f.png)

**Comment by lirenhe** [comment]
@ArcturusZhang, I think you have provided some utililty function to parse the resourceId, could you share more details here?

**Comment by raych1** [comment]
The issue you're encountering stems from the fact that the Swagger does not expose the resource group as a property in the model. Consequently, users cannot directly access the resource group in the SDK code.

As you mentioned, I also recommend extracting the resource group value from the resource identifier path. For your convenience, I'm sharing a [code snippet](https://github.com/Azure/azure-sdk-for-net/blob/532f79a16465ef4975082426996e06c179aac123/sdk/core/Azure.Core/src/ResourceIdentifier.cs#L510) from our Go common module that is used to parse the resource identifier path. Please feel free to use it as a reference.

**Comment by pieterlexis-tomtom** [comment]
Alright, thank you!
