### ISSUE TITLE
azblob: evaluate if we need to URL encode container names

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#19671]
Do we need to URL path encode container names like we do blob names?  No customers have complained about this yet.

**Comment by gapra-msft** [comment]
Container names shouldn't need any additional encoding due to resource naming restrictions set by the service https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names

**Comment by jhendrixMSFT** [comment]
That's what I thought.  I must have misunderstood the original question.  Thanks for confirming.
