### ISSUE TITLE
Getting error while using SAS token for container

### ISSUE THREAD

**Issue by mukhoakash** [Azure/azure-sdk-for-go#19682]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

Azblob sdk version v0.6.0

- What happened? Use azblob to create and use SAS Token
- What did you expect or want to happen? The SAS Token should work properly
- How can we reproduce it? 
Observing this error:
```
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:d451b518-d01e-000c-1f65-0be56e000000
Time:2022-12-09T00:32:05.1086133Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rwl
2022-12-09T00:30:44Z
2022-12-16T00:30:44Z
/blob/cositestdemo/cosi-driver-test-conb9c1f3a4-5d6b-4700-b416-ac5b4f49593b


https,http
2020-02-10
c





</AuthenticationErrorDetail></Error>
--------------------------------------------------------------------------------
```
- Anything we should know about your environment.

**Comment by vibhansa-msft** [comment]
Can you share the code snippet on how you created the SAS token and how you intend to use it.

**Comment by mukhoakash** [comment]
Please find the creation of SAS token here: https://github.com/Azure/azure-cosi-driver/blob/839a5a19c27b225dfd3a8edc97b3f2fbff3c8648/pkg/azureutils/container_ops.go#L198

The usage of this token works when I used a SAS token generated from the Azure portal.

**Comment by vibhansa-msft** [comment]
Kindly refer to this example for SAS generation :
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/sas/examples_test.go#L110

**Comment by souravgupta-msft** [comment]
@mukhoakash, can you please share what operation you are trying to achieve after creating the SAS. Please note that you are using [Service SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas) here and it can't be used for some operations like creating, listing or deleting containers. Refer [this](https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specify-permissions) for more details.
If you want to achieve the above operations, you can you use [Account SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas). Please refer this [example](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/service/examples_test.go#L259).

**Comment by mukhoakash** [comment]
@souravgupta-msft  I am trying to read and write blob data in the container using the SAS generated.

**Comment by souravgupta-msft** [comment]
Can you add `ContainerName` parameter as well in `sas.BlobSignatureValues` in your [code](https://github.com/Azure/azure-cosi-driver/blob/839a5a19c27b225dfd3a8edc97b3f2fbff3c8648/pkg/azureutils/container_ops.go#L217). You can refer this [example](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/sas/examples_test.go#L117). Please try this option and let me know if this works.

**Comment by mukhoakash** [comment]
@souravgupta-msft I am able to create a valid SAS Token with v0.6.1. Please note that there is an error in this [example](https://github.com/Azure/azure-sdk-for-go/blob/4149835b9dc1661115dad514cbdc087edd65d1c8/sdk/storage/azblob/sas/examples_test.go#L110). 
This example incorrectly shows the creation of SAS URL as 
```  
sasURL := fmt.Sprintf("https://%s.blob.core.windows.net/?%s", accountName, sasQueryParams.Encode())
``` 

The correct way should have been:

```
sasURL := fmt.Sprintf("https://%s.blob.core.windows.net/%s?%s", accountName, containerName, sasQueryParams.Encode())
```

**Comment by souravgupta-msft** [comment]
The given [example](https://github.com/Azure/azure-sdk-for-go/blob/4149835b9dc1661115dad514cbdc087edd65d1c8/sdk/storage/azblob/sas/examples_test.go#L110) is correct. Here we are creating `azblob.Client` which expects service URL as a parameter. You can check [this](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/client.go#L49) for more details.
```
sasURL := fmt.Sprintf("https://%s.blob.core.windows.net/?%s", accountName, sasQueryParams.Encode())
azClient, err := azblob.NewClientWithNoCredential(sasURL, nil)
```
If you are creating client using container package, then you have to add container name in the [sasURL](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/container/client.go#L51).
```
sasURL := fmt.Sprintf("https://%s.blob.core.windows.net/%s?%s", accountName, containerName, sasQueryParams.Encode())
containerClient, err := container.NewClientWithNoCredential(sasURL, nil)
```

**Comment by souravgupta-msft** [comment]
Given either of the above options, you have to add `ContainerName` parameter in `sas.BlobSignatureValues` in your [code](https://github.com/Azure/azure-cosi-driver/blob/839a5a19c27b225dfd3a8edc97b3f2fbff3c8648/pkg/azureutils/container_ops.go#L217).
```
sasQueryParams, err := sas.BlobSignatureValues{
		Protocol:    sas.Protocol(parameters.signedProtocol),
		StartTime:   start,
		ExpiryTime:  expiry,
		Permissions: permission.String(),
		IPRange:     sas.IPRange(parameters.signedIP),
		Version:     parameters.signedversion,
                ContainerName: containerName,
	}.SignWithSharedKey(cred)
```

**Comment by souravgupta-msft** [comment]
I am closing this issue since you are able to create valid SAS. Feel free to reopen if the issue persists.

**Comment by mukhoakash** [comment]
@souravgupta-msft I have used the containerName and it hadn't worked. I had to use the above snippet along with the containerName to make it work. https://github.com/Azure/azure-cosi-driver/pull/10

**Comment by mukhoakash** [comment]
> 

I see your point. I will document it in the driver to create the proper client so use the SAS token correctly. Thank you!

**Comment by souravgupta-msft** [comment]
You can also use [GetSASURL()](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/container/client.go#L310) method in the container package for creating SAS token.
