### ISSUE TITLE
Support fast content verification checks for multi-block concurrent uploads

### ISSUE THREAD

**Issue by bmorck** [Azure/azure-sdk-for-go#19680]
### Feature Request

Our product utilizes the Azure Blob Go SDK to upload large blobs. To do this, we are leveraging the `blockblob.UploadStream` method to perform concurrent multi-block uploads. This is necessary for our product since non-concurrent uploads using methods such as `blockblob.Upload` would be too slow and not adequately support our users' needs. 

An additional requirement of our product is robust content verification checks. Currently, the  `blockblob.UploadStream` does not compute an MD5 hash of the entire blob after the upload. Additionally, while there does seem to be a CRC64 hash included in the repsonse of the upload, the computation of the CRC64 has is not exposed to SDK users so we cannot compare against this. 

To support our requirement of fast and robust content verification requests we would like the following:
* An MD5 hash to be computed on the entire blob upon upload
OR
* Expose the computation of the CRC64 within the SDK
OR (more generally)
* Introduce some hash of the data that we can replicate the computation of and verify against

Additionally, even with a hash exposed consumers of the SDK, we still need to perform a double read of the data we upload. One read is performed to compute the hash of the data on our end and then another read is performed to upload the data. This introduces additional latency and can be prevented with the following:
* An addition of an HTTP trailer to the upload request where we can append a hash of the data to that we compute as it is being streamed to Azure. This hash would then be used by the API to compare with the hash it computes.

**Comment by vibhansa-msft** [comment]
@bmorck  : few points on your concern - 

- CRC64 that SDK computes is per block basis and verified by storage backend to ensure consistency during upload. `blockblob.UploadStream` method breaks down the input stream in block and then uploads. As this breaking down logic is inside SDK and not exposed to user application, CRC64 is computed inside SDK. There is no need to expose this outside.

- MD5 sum, on other hand, is computed on entire data (file/blob level). As this is on entire content user application needs to compute the sum and provide it as input to upload methods. SDK will just upload the data and set this md5 sum in blob properties. On `GetProperties` you will get this sum back. Neither SDK nor backend tries to recompute or validate this MD5sum. This is totally opaque and user application is free to use it the way it wants it.

- for HTTP Trailer that you mentioned, CRC64 is doing exactly the same.

**Comment by bmorck** [comment]
Hi @vibhansa-msft Thanks for the reply. I have some comments / questions in response:

* If I understand correctly, the SDK computes the CRC64 for each block individually and supplies the CRC64 to the API during upload via an HTTP trailer. And the backend serving the API re-computes the CRC64 for each block and compares this with the value supplied from the upload. Does this sound correct?
* The SDK nor API computes an MD5 hash for multi-block concurrent uploads (using the `blockblob.UploadStream`) and there is no plan to support this.  To use a MD5 hash for multi-part concurrent, we need to compute it ourself and set it on the Blob properties. Does this sound correct?
* Originally we were looking for the implementation of the CRC64 algorithm to be exposed to an SDK user because from my experimentation it is returned as a response to a call to the `blockblob.UploadStream` method within the `UploadStreamResponse.XMSContentCRC64` field. We originally believed this was a CRC64 checksum computed on the entire set of data so we wanted to know how it was computed so we could compare against it. However, given your reply above, this does not seem to be the case and I'm not sure what the `XMSContentCRC64` field corresponds to. Could you provide some insight on this?
* Lastly, as a general question, it sounds like there is no plan to support a checksum of any form that is computed on the entire set of data from a multi-block concurrent upload (by using `blockblob.UploadStream)`. Rather the best we can get is a checksum computed on the individual blocks. Does this sound correct?

**Comment by vibhansa-msft** [comment]
@bmorck 
- First part is correct crc64 is per block basis and validated at backend. As its per block it's not exposed to user in any form.
- MD5 is not computed by SDK at any level, user has to compute at their end and supply it as input to upload API. It will be set in blob system properties which you can retrieve back using get-property api for that blob.
- For data consistency during upload SDK is using CRC64 on per block basis. MD5 sum is something customer can use at their level for additional validations, and computation and comparison of this will totally be in user application. Even if user supplied it in upload, backend just stores it and return it back in properties.

**Comment by vibhansa-msft** [comment]
Closing this as the required information has been shared. Feel free to reopen in case you have any further questions.
