### ISSUE TITLE
Manifests API missing from `armcontainerregistry` SDK

### ISSUE THREAD

**Issue by JasonEtco** [Azure/azure-sdk-for-go#19689]
## Bug Report

- Import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry`
- Output of `go version`: `1.19.1`

### What happened?

Hello! The [Manifests API](https://learn.microsoft.com/en-us/rest/api/containerregistry/manifests) is missing from the generated types for the `armcontainerregistry` SDK. I've found it in the old, deprecated package: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v67.1.0+incompatible/services/preview/containerregistry/mgmt/2022-02-01-preview/containerregistry

### What did you expect or want to happen?

I'd expect to be able to use the Manifests API using the `armcontainerregistry` SDK

### How can we reproduce it?

You can see it in the generated types. Other language SDKs do generate these endpoints and related types, with the search for example: https://github.com/search?q=org%3AAzure%20ManifestWrapper&type=code

Some relevant versions:

```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.2.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.0.0
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appcontainers/armappcontainers v1.0.0
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/blueprint/armblueprint v0.5.0
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry v0.6.0
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources v1.0.0
```

**Comment by ArcturusZhang** [comment]
Hi @JasonEtco thanks for this issue
Unfortunately the API in your document is a data plane API. The "old deprecated package" [services/preview/containerregistry/mgmt/2022-02-01-preview/containerregistry](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v67.1.0+incompatible/services/preview/containerregistry/mgmt/2022-02-01-preview/containerregistry) do not have it.

In your search results, the `ManifestWrapper` all come from data plane SDKs, for instance dotnet `Microsoft.Azure.ContainerRegistry`. A clear characteristic of mgmt plane SDK is that in their namespace, there is always a word "mgmt", "management" or "manager" inside it.

@RickWinter could you help on this?

**Comment by RickWinter** [comment]
The manifests APIs you referring to are not part of ARM.  They will be provided by the azcontainerregistry package.  I've opened issue #19690 to track this request
