### ISSUE TITLE
azblob always fails with timeout

### ISSUE THREAD

**Issue by stijndehaes** [Azure/azure-sdk-for-go#19686]
### Bug Report

I am using github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.6.0

And when using cli credentials or managed identity credentials the library always failes.
Shared key credentials do work

```golang
creds, _ := azidentity.NewAzureCLICredential(nil)
bb, _:= blob.NewClient("https://storageAccount.blob.core.windows.net/containerName/dummy.json", creds, nil)
_, err = bb.DownloadFile(context.Background(), f, nil)
```

this fails with:

```
RESPONSE 500: 500 Operation could not be completed within the specified time.
ERROR CODE: OperationTimedOut
````

**Comment by stijndehaes** [comment]
Never mind, we were in the process of migration to a new owner of our subscription. This was an unfurtunate side effect of that

**Comment by siminsavani-msft** [comment]
Thanks for updating this thread! Let us know if you run into any other issues!
