### ISSUE TITLE
azblob package v0.6.0 does not compile on MacOS

### ISSUE THREAD

**Issue by abastie** [Azure/azure-sdk-for-go#19684]
### Bug Report

- import path  `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- Commit `220ae2b` azblob `0.6.0`tag
- output of `go version` : `go version go1.19.2 darwin/arm64`

Basically I compiled using the azblob package version 0.6.0 on MacOS and got this error : 

```
# github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob
../../go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.6.0/blockblob/mmf_unix.go:21:63: undefined: syscall.MAP_ANONYMOUS
```

I searched online and this is a MacOS specific error, this syscall is MAP_ANON on MacOS.

Not happing in the version 0.5.0 of azblob.

**Comment by jhendrixMSFT** [comment]
This will be fixed in `v0.6.1` later today.  Sorry for the hassle (we don't have macOS in our CI :()
