### ISSUE TITLE
Requests to the Azure metadata service take minutes to time out

### ISSUE THREAD

**Issue by johananl** [Azure/azure-sdk-for-go#19699]
### Bug Report

- import path of package in question: `"github.com/Azure/azure-sdk-for-go/sdk/azidentity"`
- SDK version: `v1.2.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`: `go version go1.19.1 linux/amd64`

- What happened?

When using a custom credential chain with a managed identity credential, requests to the Azure metadata take minutes to time out instead of 1 second. This seems to be caused by the fact that...

https://github.com/Azure/azure-sdk-for-go/blob/f8cb16d25c435299b972737b2021aa1854d95e07/sdk/azidentity/default_azure_credential.go#L100

...which is set when using the **default** chain isn't set when using a custom chain.

- What did you expect or want to happen?

I expected the metadata request to time out after 1 second when not running on Azure so that the next credential in the chain is attempted.

- How can we reproduce it?

```go
package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

func main() {
	clientID := azidentity.ClientID("abcd1234-...")
	subscriptionID := "foo"
	opts := azidentity.ManagedIdentityCredentialOptions{ID: clientID}

	managed, err := azidentity.NewManagedIdentityCredential(&opts)
	if err != nil {
		panic(err)
	}

	cred, err := azidentity.NewChainedTokenCredential([]azcore.TokenCredential{managed}, nil)
	if err != nil {
		panic(err)
	}

	client, err := armresources.NewResourceGroupsClient(subscriptionID, cred, nil)
	if err != nil {
		panic(err)
	}

	res, err := client.Get(context.TODO(), "foo", nil)
	if err != nil {
		panic(err)
	}

	fmt.Println(*res.ID)
}
```

The code above blocks for more than two minutes at `client.Get()` on my machine.

- Anything we should know about your environment.

I _think_ this problem is hard to reproduce if on your dev machine you get a **fast** network failure for `169.254.169.254`. On my machine, requests to this address are dropped silently, in which case it would make sense that the SDK would give up after a short amount of time and try another credential rather than hang for a long time.

**Comment by chlowell** [comment]
`DefaultAzureCredential` sets that timeout because it's designed to help developers get started and is commonly used in environments where IMDS isn't available. Other credentials don't impose similar timeouts because there isn't an obvious good default value, and we don't want to take control over timeouts from applications. You can set your own with timeout with `context`:
```go
// the timeout applies to the client method call, including authentication
ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
defer cancel()
res, err := client.Get(ctx, "foo", nil)
```

**Comment by johananl** [comment]
@chlowell thanks for responding quickly.

I think we're talking about two different things. Your code snippet sets a timeout on the `Get()` request. I'm talking about setting a timeout on the request the SDK does to **IMDS** before calling `Get()`.

Say I define a custom credential chain with IMDS as the 1st credential and Azure CLI as the 2nd one. In that case, when running this code on an environment without IMDS I want the request to IMDS to time out quickly so that Azure CLI auth is attempted. I don't necessarily want to time out the `Get()` request quickly, or maybe even at all - the two timeouts are different AFAICT.

**Comment by chlowell** [comment]
Thanks, I did overlook that distinction! You could use a tiny wrapper to apply a timeout only to authentication:
```go
import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

type wrapper struct {
	cred *azidentity.ManagedIdentityCredential
}

func (w *wrapper) GetToken(ctx context.Context, opts policy.TokenRequestOptions) (azcore.AccessToken, error) {
	c, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	return w.cred.GetToken(c, opts)
}
```
However, this doesn't work with `ChainedTokenCredential` because you need an unexported type to signal the timeout error is non-fatal. This is a good argument for exporting that type; I'll open a PR.

In the meantime, if the Azure CLI isn't available in your non-dev environment, you could put `AzureCLICredential` ahead of managed identity in the chain. It fails fast when the CLI isn't installed.

**Comment by johananl** [comment]
Thanks @chlowell. Yes, I already have a workaround in place. Wanted to report this to improve things for other users.
Thanks for looking into this!

**Comment by johananl** [comment]
@chlowell are you talking about exporting the `credentialUnavailableError` type so that we can use a wrapper and check the error type in user code? AFAICT this won't be enough because of the following check:

https://github.com/Azure/azure-sdk-for-go/blob/7511cc07bf639e2f1e6e2b36eca5a056da4e8d33/sdk/azidentity/managed_identity_client.go#L178-L181

We return a `credentialUnavailableError` only when `cancel` isn't nil, and `cancel` gets assigned only when `c.imdsTimeout > 0`:

https://github.com/Azure/azure-sdk-for-go/blob/7511cc07bf639e2f1e6e2b36eca5a056da4e8d33/sdk/azidentity/managed_identity_client.go#L165-L169

Am I missing something?

BTW, I'm happy to open a PR once we figure out the right solution.

**Comment by chlowell** [comment]
Yes, that's what I have in mind. With `CredentialUnavailableError` exported, the wrapper can signal the chain to try another credential after a managed identity timeout. Then the wrapper needs only to know whether a timeout has occurred. It doesn't have to rely on the wrapped credential for that because it has the `Context` which would have timed out. I'm imagining something like this:
```go
func (w *wrapper) GetToken(ctx context.Context, opts policy.TokenRequestOptions) (azcore.AccessToken, error) {
	c, cancel := context.WithTimeout(ctx, time.Second)
	defer cancel()
	tk, err := w.cred.GetToken(c, opts)
	// special case: timeout; signal the chain to keep iterating
	if ctxErr := c.Err(); errors.Is(ctxErr, context.DeadlineExceeded) {
		err = &azidentity.CredentialUnavailableError{Message: "managed identity timed out"}
	}
	// otherwise, propagate the wrapped credential's return
	return tk, err
}
```

**Comment by chlowell** [comment]
We chose to export an `error` constructor rather than an error type for this in azidentity v1.3.0-beta.2. Updating my examples above, a wrapper would now look like this:
```go

import (
	"context"
	"errors"
	"time"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

type wrapper struct {
	cred *azidentity.ManagedIdentityCredential
}

func (w *wrapper) GetToken(ctx context.Context, opts policy.TokenRequestOptions) (azcore.AccessToken, error) {
	c, cancel := context.WithTimeout(ctx, time.Second)
	defer cancel()
	tk, err := w.cred.GetToken(c, opts)
	if ctxErr := c.Err(); errors.Is(ctxErr, context.DeadlineExceeded) {
		// timeout: signal the chain to try its next credential, if any
		err = azidentity.NewCredentialUnavailableError("managed identity timed out")
	}
	return tk, err
}
```

**Comment by chlowell** [comment]
Yes! #19859 implemented a more robust wrapper for DefaultAzureCredential to use internally and added that wrapper as an example for ChainedTokenCredential.
