### ISSUE TITLE
repo is over 100 MB of Go source code and growing

### ISSUE THREAD

**Issue by rsc** [Azure/azure-sdk-for-go#1969]
For vgo I put in a limit of 100 MB of uncompressed source code for any module, thinking surely that would be plenty. (There must be some limit, of course, or else we fill people's disks when receiving a zip bomb.)

It looks like this project recently crossed the 100 MB line, just for the go sources in it:

```
$ git clone https://github.com/Azure/azure-sdk-for-go
$ cd azure-sdk-for-go
$ ls -lR | grep '\.go$' | awk '{s+=$5}END{print s}'
116335208
$ 
```

Sizes for recent major versions:

    v14.0.0 66,432,773
    v15.0.0 80,010,402
    v16.0.0 114,745,301
    v17.0.0 116,277,454

I am going to raise the limit to 500 MB but I wanted to file this issue to let you know about the problem, so that you can look to see if the rate of growth here is really intentional and/or think about whether to break this repo into multiple modules.

**Comment by joshgav** [comment]
Thanks for letting us know @rsc. This will be a consideration for us as we adopt modules here.

**Comment by marstr** [comment]
Howdy @rsc, thanks for thinking of us!

We've been thinking about splitting up this repository for sometime, but have balked at the overhead of managing a repository per Azure Resource Provider. Modules present a solution that we're excited about. Tentatively, we intend on shipping each of the subfolders in "services" and "profiles" as its own module with its own semver.

**Comment by joshgav** [comment]
related: https://github.com/golang/vgo/commit/0cf06bb651c56f86ec7b7685f39092ddb7daba39

**Comment by jhendrixMSFT** [comment]
Work to split each RP/API version tuple into modules is in progress, tracked in https://github.com/Azure/azure-sdk-for-go/issues/2993

**Comment by tombuildsstuff** [comment]
x-post: https://github.com/Azure/azure-sdk-for-go/issues/18209

**Comment by ceejatec** [comment]
Indeed. If it was thought that 100MB was too big 3 years ago, how did it end up at 512MB+ today?
