### ISSUE TITLE
ContainerRegistry data plane library

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#19690]
Add the azcontainerregistry SDK to the set of data-plane libraries

**Comment by jhendrixMSFT** [comment]
Looks like a dupe of https://github.com/Azure/azure-sdk-for-go/issues/19483?

**Comment by jhendrixMSFT** [comment]
Closing as dupe.

**Comment by JasonEtco** [comment]
Thanks for triaging @RickWinter / @jhendrixMSFT 🙏 I'll subscribe to #19483.
