### ISSUE TITLE
Dealing with some benign errors 

### ISSUE THREAD

**Issue by kenegozi** [Azure/azure-sdk-for-go#197]
When a call returns UnexpectedStatusCodeError, there is no programatic way to tell what status code was actually return to let the user code decide how to proceed.

solution proposed is to expose .Got() (returning .got)

An example scenario: when creating a queue that already exist, user code might decide this is fine, but have no way to be sure of that. The Queue service doc say in this case the response is 204, the following code is possible with the suggestion solution:

	qc := az.GetQueueService()

	err = qc.CreateQueue(queueName)
	if storageError, ok := err.(*storage.UnexpectedStatusCodeError); ok {
		if storageError.Got() != http.StatusNoContent {
			panic(err)
		}
	}

	qc.GetMessages(queueName, storage.GetMessagesParameters{})

**Comment by ahmetalpbalkan** [comment]
> when creating a queue that already exist, user code might decide this is fine

for that generally you can use `GetQueue`. But the patch makes sense.

**Comment by kenegozi** [comment]
you mean 'QueueExists'? a race condition would still potentially yield that error.

**Comment by ahmetalpbalkan** [comment]
Agreed. Most convenience methods such as DeleteBlobIfExists, or CreateContainerIfNotExists here and in our SDKs such as Python, .NET etc also rely on making two requests (one HEAD and then [POST/PUT/DELETE]) to determine existence of the resource. That's one of the reasons I followed the same pattern developing similar methods in the ./storage/... package. However, your patch makes sense, we can expose fields of the error type just fine.

**Comment by kenegozi** [comment]
oh man don't get me started on these ..IfExists methods. I've code-reviewed naive usages of these inside and outside of Microsoft so many times ... In recent versions of the .NET SDK they started to silently discard the "already exists" case in the IfExists methods (breaking changes ftw). I'm glad that the go SDK is shaping up with much less of a surprise factor (which is very go-i, one of the reasons I decided on Go for my current endeavor in favor of .NET)

**Comment by ahmetalpbalkan** [comment]
@kenegozi that's great. By the way the Go SDK is not settled in the stone, we appreciate feedback in all packages. `storage` and `management` are hand-written but `arm` package is auto-generated. If you happen to encounter any surprise behavior please let us know ––we are deliberately trying keep any client-side logic outside the SDK to avoid such surprises and expect users to know about the endpoints they are using and the valid values they must be passing etc.
