### ISSUE TITLE
[Question] When are new API versions for a service released?

### ISSUE THREAD

**Issue by alxy** [Azure/azure-sdk-for-go#19704]
As I did not find that in the README, I just wanted to know if there is some general guideline when new Azure REST API versions are added to this Go SDK? Is there also a guideline if only `stable` versions are considered, or also `preview` ones?

**Comment by lirenhe** [comment]
Th mgmt. SDK is released based on the request from service team so they would decide when and what version to release.
Do you have any specific question or ask?
