### ISSUE TITLE
maintenance: support API version "2022-07-01-preview"

### ISSUE THREAD

**Issue by alexwilcox9** [Azure/azure-sdk-for-go#19709]
### Service Package Request
I was advised to raise a ticket here in order to get the new maintenance API version added to the Azure Go SDK

Thanks,
Alex

https://github.com/Azure/azure-rest-api-specs/pull/20366

**Comment by lirenhe** [comment]
@Alancere, please follow up with service team on this ask. thanks

**Comment by Alancere** [comment]
Hi @alexwilcox9, the release-request pr has been proposed, and the expected release time is 2023-01-27. 
https://github.com/Azure/sdk-release-request/issues/3573

**Comment by tadelesh** [comment]
New beta released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/maintenance/armmaintenance@v1.1.0-beta.2
