### ISSUE TITLE
Unable to get instance view for VMSS flex VMs

### ISSUE THREAD

**Issue by erika-boren** [Azure/azure-sdk-for-go#19707]
### Bug Report

- import path: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4`
- version: `v4.0.0`
- go version: `go1.19.1 darwin/amd64`

Unable to get the instance view for VMSS flex VMs. The GetInstanceView requires the VM id, which doesn't exist for a flex VM. However, I see in the doc below it says to use the vm name in place of the ID. I tried using the name but get a 400 invalid parameter. 
https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids

```
resp, err := client.GetInstanceView(ctx,"rg-name", "vm-flex-test", "vm-flex-test_032c7bb7", nil)

GET https://management.azure.com/subscriptions/redacted-subid/resourceGroups/rg-name/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-flex-test/virtualMachines/vm-flex-test_032c7bb7/instanceView
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidParameter",
    "message": "Virtual Machine Scale Set VM instanceId must be a number.",
    "target": "instanceId"
  }
}
--------------------------------------------------------------------------------
```

**Comment by tadelesh** [comment]
According to this [issue](https://github.com/Azure/azure-sdk-for-go/issues/19588#issuecomment-1322221933) replied with service team, you may use instanceIDs as parameter.

**Comment by erika-boren** [comment]
Flex instances don't have instanceIDs and that issue says to use the instance name instead, which is what I tried and posted above.

**Comment by navba-MSFT** [comment]
@erika-boren Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@erika-boren Could you please check if the below sample helps ?

```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
)

var (
	subscriptionID    = "b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f"
	resourceGroupName = "STORAGE-RESOURCES"
	vmName            = "azurestoragetestvm"
)

func main() {

	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatal(err)
	}
	ctx := context.Background()

	// Create an Azure Compute VM client
	client, err := armcompute.NewVirtualMachinesClient(subscriptionID, cred, nil)

	// Retrieve the instance view of the Virtual Machine

	instanceView, err := client.InstanceView(ctx, resourceGroupName, vmName, nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Print the instance view
	fmt.Println(instanceView)

}

```
InstanceView - Retrieves information about the run-time state of a virtual machine. If the operation fails it returns an *azcore.ResponseError type. Generated from API version 2022-03-01 
resourceGroupName - The name of the resource group. 
vmName - The name of the virtual machine. 
options - VirtualMachinesClientInstanceViewOptions contains the optional parameters for the VirtualMachinesClient.InstanceView method.

More info [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute@v1.0.0#VirtualMachinesClient.InstanceView).

**Comment by erika-boren** [comment]
I'm not able to get the instance view for flex instances within a VMSS using the VirtualMachinesClient. It says the resource is not found.

client, err := armcompute.NewVirtualMachineScaleSetVMsClient(sub, creds, nil)
resp, err := client.InstanceView(ctx, rgName, *vm.Name, nil)

GET https://management.azure.com/subscriptions/subscription-redacted/resourceGroups/resource-group-name/providers/Microsoft.Compute/virtualMachines/az-vm-dev-wus3-flex-test_01234567/instanceView
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: ResourceNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Compute/virtualMachines/az-vm-dev-wus3-flex-test_01234567' under resource group 'resource-group-name' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}

**Comment by navba-MSFT** [comment]
@erika-boren Thanks for getting back and clarifying the ask. I was able to get the sample working with just VMSS Uniform orchestration mode. However with the Flexible orchestration Mode, I faced the same below error:

```
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidParameter",
    "message": "Virtual Machine Scale Set VM instanceId must be a number.",
    "target": "instanceId"
  }
}
--------------------------------------------------------------------------------
```
Flexible orchestration Mode: {scale-set-name}_**{8-char-guid}**
Uniform orchestration mode: {scale-set-name}_{instance-id}

Though our article mentions this, For Virtual Machine Scale Sets in Flexible Orchestration mode, the instance ID is simply the name of the virtual machine. I tried with both **{8-char-guid}** and **{scale-set-name}_{8-char-guid}**. But both failed.

I am checking this with the Product Owners further and I will update this thread.

**Comment by navba-MSFT** [comment]
@erika-boren Apologies for the late reply. [VMSS Flex does not support instance view](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes#autoscaling-and-instance-orchestration), as there is not currently a way to get full instance view of Azure VMs. VMSS Uniforms had some internal simplifications that made it possible, but it was not possible to port that to VMSS Flex. The long term plan is to support getting instance view information at scale via Azure Resource Graph. We are hoping that lands in Q2CY2023. 

In the meantime, options are:
•	Use List All VM API with statusonly=true and VMSS filter. That will get your powerState, provisioningState, and platformFaultDomain for all instances within the VMSS Flex.

•	Use Get VM Instance View API on each individual VM instance...watch retry headers so that you don't run into throttling.

**Comment by erika-boren** [comment]
How do we get the IP of a Flex VM using the SDK?

**Comment by navba-MSFT** [comment]
@erika-boren The above option #1 mentioned above you will get the `ipConfigurations` property in the response. That should help you get the required details.

**Comment by navba-MSFT** [comment]
@erika-boren If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
