### ISSUE TITLE
[Monitor Ingestion] Create Azure Monitor Ingestion library for Go

### ISSUE THREAD

**Issue by gracewilcox** [Azure/azure-sdk-for-go#19703]
Issue to track progress for the Monitor Ingestion SDK for Go

```[tasklist]
# Ship Ingestion Library
- [x] Generate code (2 days)
- [ ] Convenience layer- batching, gzip (9 days)
- [ ] Feedback (3 days)  (PR, Archboard)
- [x] Tests (5 days) (unit tests, stress tests)
- [x] Samples (1 day)
- [x] Documentation- readme (1 day)
```
total: 21 days

```[tasklist]
# Features 
- [ ] Upload
- [ ] Upload with gzip and batching
```

**Comment by hazcod** [comment]
@gracewilcox Does this also include sending logs to Sentinel SIEM?

**Comment by gracewilcox** [comment]
Hi @hazcod. This planned module will not interact directly with Azure Sentinel. The Monitor Ingestion SDK will allow users to upload logs to Azure Monitor. You could upload logs generated by Sentinel to Azure Monitor, but you can't use this module to send logs to Sentinel itself. The API documentation for Monitor Ingestion can be found [here](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-ingestion-api-overview). Ingestion has also been released in other language SDKs. The link to the Python one can be found [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-ingestion)

We do have a Sentinel SDK called Security Insights which can be found [here](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/securityinsights/armsecurityinsights). The Sentinel API documentation can also be found [here](https://learn.microsoft.com/en-us/rest/api/securityinsights/).
