### ISSUE TITLE
azblob package v0.6.1 does not compile on Solaris

### ISSUE THREAD

**Issue by MichaelEischer** [Azure/azure-sdk-for-go#19715]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version: [v0.6.1](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv0.6.1) ` 39b9fd0`
- output of `go version`: `go version go1.19.4 linux/amd64` .

Cross-Compiling using `GOOS=solaris GOARCH=amd64 go build [...]` leads to the following error:
```
# github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob
Error: ../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.6.1/blockblob/mmf_unix.go:22:23: undefined: syscall.Mmap
Error: ../../../go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.6.1/blockblob/mmf_unix.go:31:17: undefined: syscall.Munmap
```
See also https://github.com/restic/restic/actions/runs/3720574784/jobs/6310140771

Without https://github.com/Azure/azure-sdk-for-go/pull/19685 the build fails as type `mmb` is missing.

**Comment by vibhansa-msft** [comment]
As of now, we support only Windows, Linux and MAC. We investigated on the Solaris part but Go 1.19 does not support memory mapping on Solaris. [this](https://groups.google.com/g/golang-checkins/c/ONnePl_MbPc?pli=1) points that support will come with Go 1.20+. You might need to wait for that and then build.
