### ISSUE TITLE
Add support to set timeout in ManagedIdentityCredential

### ISSUE THREAD

**Issue by JorTurFer** [Azure/azure-sdk-for-go#19721]
In [KEDA](https://github.com/kedacore/keda) we support managed identities with AAd-Pod-Identity and with WI. We'd like to introduce a custom chained token because in our use case, we support using a different clientId than the default value for a better permission segmentation. 

We have been working with different implementations depending on the podIdentity set by the user, but for the sake of the unification, and due to the new SDK allows us to unify both using chained credential, we want to unify them. Our problem is that we cannot set the timeout for `ManagedIdentityCredential` because it's an internal and the default value is too long (60 sec if I'm not wrong) for waiting before trying the next credential in the chain.

I have checked `DefaultAzureCredential` and it sets the timeout in 1 second 
```
msiCred, err := NewManagedIdentityCredential(o)
	if err == nil {
		creds = append(creds, msiCred)
		msiCred.mic.imdsTimeout = time.Second
	}
```
This is perfect and could solve our use case perfectly, but it's an internal setter and we don't have any change to modify that value. It'd be nice if `ManagedIdentityCredentialOptions` supports a new parameter to set this timeout instead of setting it inside `DefaultAzureCredential`. I guess that this could be solved just adding a new property there and configuring the timeout before returning `ManagedIdentityCredential`.

If you think that it's something feasible, I'm willing to contribute with the needed changes

**Comment by chlowell** [comment]
You can use the `context.Context` parameter of client and credential methods to control timeouts and cancellation. #19699 has examples showing how to replicate this internal timeout (note some of those examples require `azidentity` to export a new error type, which I'm working on).

Your scenario sounds unusual though. Why does your application chain credentials to support custom client IDs? Can it simply take an optional ID as configuration and then construct a single credential with that value?

**Comment by JorTurFer** [comment]
The problem we have faced is that KEDA stack a lot of permissions in its managed identity due to what KEDA is for (for getting autoscaling metrics, we need to have administrator permissions in azure services). 
Our users requested us a better permission segmentation to reduce the potential breach, and that's why we support the option to set a specific managed identity for a specific scaler instead of using the KEDA managed identity, with this approach, we can reduce the amount of stack permissions in the same identity, that's why we allow the option of giving another managed identity to use. 
At this point, maybe @tomkerkhove or @v-shenoy can give you more info about the reasons.

Most probably I'm missing something in the middle, but why we can't just have the option to specify the timeout to `ManagedIdentityCredential`? I mean, if you decided that `DefaultAzureCredential` requires a different timeout (and I get it totally because it's part of a chain) and you also supported to create custom chains (because the chain is public), I think that making this parameter configurable makes sense totally.

I have also tried using our current implementations as part of the chained token credential, but the internal implementation of the chain requires `credentialUnavailableError` to continue with the chained elements, and that error is internal of the SDK, so basically we are blocked. 
ATM, we have ad-hoc code for Aad-pod-identity and Aad WI (using custom providers with an if) and we want to unify it integrating the `azidentity` with a chained token credential.

**Comment by chlowell** [comment]
> Our users requested us a better permission segmentation to reduce the potential breach, and that's why we support the option to set a specific managed identity for a specific scaler instead of using the KEDA managed identity
> 

This makes sense to me but I'm still missing something here. How do you use a chain of credentials to implement this? `ChainedTokenCredential` enables fallback behavior when one credential is unable to authenticate. If you represent multiple managed identities as multiple `ManagedIdentityCredential` instances, fallback among them isn't really what you want and may cause incorrect behavior because the chain is linear: it starts with the first credential and stops when one succeeds. Which `ManagedIdentityCredential` succeeds depends more on the runtime environment than the application's configuration, unless you can guarantee the desired credential is always first in the chain but if you can do that, why use a chain at all?

> I have also tried using our current implementations as part of the chained token credential, but the internal implementation of the chain requires `credentialUnavailableError` to continue with the chained elements, and that error is internal of the SDK, so basically we are blocked.

#19733 exports this type.

> Most probably, I'm missing something in the middle, but why we can't just have the option to specify the timeout to `ManagedIdentityCredential`?
> 

I have a few concerns about adding such an option. The most important in my mind is that we want the SDK to have a single, idiomatic way to do things wherever feasible. All our clients and credentials already have a timeout and cancellation API via the standard library's `context.Context`. If we were to add an IMDS-specific timeout option, `ManagedIdentityCredential` would then have two timeout APIs: one that's consistent with the standard library and the rest of the Azure SDK, and a quirky one that applies only to a specific managed identity implementation. The quirky API would also create practical problems because we would implement it via `context.Context`, bringing the two timeout APIs into conflict. Also, the quirky API would be made redundant by exporting `CredentialUnavailableError`--which I think we should do in any case--because with that error type applications can recreate the timeout behavior of `DefaultAzureCredential` with `context` ([for example](https://github.com/Azure/azure-sdk-for-go/issues/19699#issuecomment-1366258523)).

**Comment by JorTurFer** [comment]
> How do you use a chain of credentials to implement this?

Currently, we are not using the chained token credential, we have just got an if and we create one or another depending on it. I'd like to unify both in a single chain and also including az-cli for local development. This could simplify a lot the credential management for all the services with support for `azidentity`.

> If we were to add an IMDS-specific timeout option, `ManagedIdentityCredential` would then have two timeout APIs

I tend to agree with you here, but there are already 2 timeouts indeed. I only want to make both public, because otherwise we can't use the `ManagedIdentityCredential` due to its timeout. Furthermore, I can write my own `ManagedIdentityCredential` managing the timeout as you suggested, but for adding the `c, cancel := context.WithTimeout(ctx, time.Second)`, I need to code the `GetToken`, which basically requires the whole TokenCredential. I can do it (we have it already done), but every time when it's possible, I prefer to use "sdk supported types" instead of my own types. 

Said this,  I guess that https://github.com/Azure/azure-sdk-for-go/pull/19733 is enough for us, we can return that error and build the chain with our current implementations (updating the errors)

**Comment by chlowell** [comment]
> Furthermore, I can write my own `ManagedIdentityCredential` managing the timeout as you suggested, but for adding the `c, cancel := context.WithTimeout(ctx, time.Second)`, I need to code the `GetToken`, which basically requires the whole TokenCredential (I can't reuse the already existing `ManagedIdentityCredential`).

Do you mean something other than #19733 prevents you from writing a simple wrapper like [this](https://github.com/Azure/azure-sdk-for-go/issues/19699#issuecomment-1352295710)?

**Comment by JorTurFer** [comment]
> Do you mean you need something more than #19733 to write a wrapper like [this](https://github.com/Azure/azure-sdk-for-go/issues/19699#issuecomment-1352295710)?

Good point! I guess that wrapping it will be enough. Thanks for pointing it 🙇 
In any case, wrapping it looks like a patch, not like a fix, I mean, it solves the problem, but more code outside the SDK is required, I can't just use SDK types to compose my own chain as I want, I need to add other types just to use the SDK types in the same way as the SDK itself

**Comment by chlowell** [comment]
I hear you; the simplest wrapper is more code than setting an option. However, we don't want a redundant, esoteric option that conflicts with cancellation via `context`. Incidentally, we released an `azidentity` beta this week that enables wrapping, and I've updated my example here: https://github.com/Azure/azure-sdk-for-go/issues/19699#issuecomment-1379290680.

**Comment by JorTurFer** [comment]
> I hear you; the simplest wrapper is more code than setting an option. However, we don't want a redundant, esoteric option that conflicts with cancellation via context. Incidentally, we released an azidentity beta this week that enables wrapping, and I've updated my example here: https://github.com/Azure/azure-sdk-for-go/issues/19699#issuecomment-1379290680.

Thanks! I'll give a try (I hope this week), the good part is that we have e2e test with both cases (aad-pod-identity and workload identity), so I think we can detect it works or not :)

**Comment by JorTurFer** [comment]
We have created our custom chain and it works for both scenarios!
Thanks a lot for your help 🙇
