### ISSUE TITLE
[azservicebus] Asking for a negative count of messages results doesn't return an error

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#19743]
This should return a validation error because the number of requested messages is negative:

```go
// (blocks today)
receiver.ReceiveMessages(context.TODO(), -1, nil)
```

This is a definite error case, should return a validation error. It is possible to request negative credits in AMQP, but that's not something we're trying to enable here and it's possible it doesn't even do that at the moment with our stack.

**Comment by serbrech** [comment]
note that if you ask for 0, it blocks indefinitely.
