### ISSUE TITLE
[Reference book update] Mark all folders in track 1 SDK as deprecated

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-go#19750]
### Feature Request

Our deprecation message only exists in the first package like scree shot below
<img width="935" alt="image" src="https://user-images.githubusercontent.com/5089150/210588395-be7d8517-49c7-43da-abc4-5f902e1f36c6.png">
we should add deprecation message at the second line for all the packages so that customers won't get confused

**Comment by tadelesh** [comment]
Duplicate with https://github.com/Azure/azure-sdk-for-go/issues/19731.
