### ISSUE TITLE
Support of Azure workload identity?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-sdk-for-go#19765]
Hello @gracewilcox,

Happy new year. Hope you are doing well.

Does this azure golang sdk support azure workload identity. We are planning to migrate from AAD pod identity to Azure workload identity in Azure kubernetes.

Any updates on this integration?

Thank you. Have a nice day.

Kind Regards,
Tanul

**Comment by chlowell** [comment]
The latest beta, v1.3.0-beta.1 supports Workload Identity. You can use either [WorkloadIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.3.0-beta.1#WorkloadIdentityCredential) or [DefaultAzureCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.3.0-beta.1#DefaultAzureCredential). DefaultAzureCredential expects environment variable configuration from the Workload Identity webhook (more information about that [here](https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html)).

**Comment by smartaquarius10** [comment]
@chlowell , Hey thanks. When will it be production ready.. As its currently the beta version?

**Comment by chlowell** [comment]
We're targeting early April for the next stable release. I suppose we might delay this feature if the AKS implementation is still in preview at that time.

**Comment by smartaquarius10** [comment]
@chlowell , Thanks :)
