### ISSUE TITLE
Export some missing types

### ISSUE THREAD

**Issue by Mr-Rain** [Azure/azure-sdk-for-go#19775]
### Feature Request

Hi, In https://github.com/Azure/azure-sdk-for-go/commit/d5cc623ac82a71b6f5b26b7abacfad4bba5f5069, the developer @jhendrixMSFT  exports some missing types like BlobItem, BlobPrefix and BlobTag. But when we using "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob" to write codes and do unit tests. We found some types like BlobFlatListSegment, BlobTags are also needed to mock test data. Can you please evaluate whether these types can be added? Or there is other methods to mock parameters like azblob.ListBlobsFlatSegmentResponse.Segment?

**Comment by vibhansa-msft** [comment]
@Mr-Rain : Can you share a sample code on how you wish you use these unexported types?

**Comment by vibhansa-msft** [comment]
Below if the example on how to use flat pager from azblob
```
	pager := client.NewListBlobsFlatPager("testcontainer", &azblob.ListBlobsFlatOptions{
		Include: container.ListBlobsInclude{Deleted: true, Versions: true},
	})

	for pager.More() {
		resp, err := pager.NextPage(ctx)
		handleError(err) // if err is not nil, break the loop.
		for _, _blob := range resp.Segment.BlobItems {
			fmt.Printf("%v", _blob.Name)
		}
	}
```

If I understand correctly you wish to mock the response returned back by NextPage?
can you share a use-case why you need to do that.

**Comment by Mr-Rain** [comment]
Yes, I want to mock the response returned back by NextPage. I write an exporter to provider metrics for Prometheus and use the NewListBlobsFlatPager method in the code. In unit test of my code, I need to mock the response returned back by NextPage to ensure my code correctly handle the response and make the correct metrics.

**Comment by tbtonner** [comment]
Also running into the same issue when trying to mock and unit test the azure go sdk with `azblob v0.5.1`. Need `BlobFlatListSegment` in order to mock `NextPage` on an `azblob.Client` but as mentioned it's seemingly not exported anywhere public and located in internal packages.

**Comment by sfc-gh-kleonhard** [comment]
Same issue here on BlobFlatListSegment

**Comment by souravgupta-msft** [comment]
The fix has been merged and will be part of our next release. Feel free to reopen if the issue persists.

**Comment by Mr-Rain** [comment]
Is there a schedule for when the next version will be released? Thanks!

**Comment by souravgupta-msft** [comment]
We will be releasing this week. I will keep you posted in this thread.

**Comment by souravgupta-msft** [comment]
The azblob SDK is now GA. Please check out the release [v1.0.0](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv1.0.0).
