### ISSUE TITLE
Creating a Managed Data Disk using blob as source

### ISSUE THREAD

**Issue by salmanbukhari** [Azure/azure-sdk-for-go#1977]
There is an option to create a Disk using blob as a source. I want to create a VM with data disks from the specified blob. I cannot find any option in DataDisk to specify source blob URI. Can it be done in VM creation request? I know we can create a disk using blob and attach it to VM. I found two structs DataDisk and Disk. the later has the option to be created using source blob.

**Comment by jhendrixMSFT** [comment]
@gatneil do you know the answer?

**Comment by gatneil** [comment]
@singhkays, do we support this?

**Comment by singhkays** [comment]
Nope, cannot create a Managed VM with blob as source. Have to create the disk first and attach at VM creation.

**Comment by jhendrixMSFT** [comment]
Hello @salmanbukhari does this answer your question?

**Comment by salmanbukhari** [comment]
Yes @jhendrixMSFT thanks.
