### ISSUE TITLE
bug(armazuredata): Wrong API version for `armazuredata.NewSQLServerRegistrationsClient`

### ISSUE THREAD

**Issue by erezrokah** [Azure/azure-sdk-for-go#19789]
### Bug Report

Example Go code using `v0.5.0` of the API:

```go
package azuredata

import (
        "context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/azuredata/armazuredata"
)

func fetchSqlServerRegistrations(ctx context.Context) error {
	svc, err := armazuredata.NewSQLServerRegistrationsClient(...)
	if err != nil {
		return err
	}
	pager := svc.NewListPager(nil)
	for pager.More() {
		p, err := pager.NextPage(ctx)
		if err != nil {
			return err
		}
		fmt.Println(p.Value)
	}
	return nil
}
```

- output of `go version` - `go version go1.19.3 darwin/arm64`

I'm getting an error when trying the above code. The error is:
```
The resource type 'sqlServerRegistrations' could not be found in the namespace 'Microsoft.AzureData' for api version '2019-07-24-preview'. The supported api-versions are '2019-05-10-preview'
```

Setting the API version via `ClientOptions` to `2019-05-10-preview` fixes the issue.
Looks like the client defaults to `2019-07-24-preview`:
https://github.com/Azure/azure-sdk-for-go/blob/a97519174f72085debd57f0b1189aaa2b62f5f7b/sdk/resourcemanager/azuredata/armazuredata/zz_generated_sqlserverregistrations_client.go#L268

**Comment by lirenhe** [comment]
@erezrokah, due to our version policy, we could not release a SDK with previous api version, could you continue to use the above workaround for your work?  Thanks

**Comment by erezrokah** [comment]
Thanks for the quick reply @lirenhe ❤️ I can use the workaround, however is it expected that the default API version used by this package causes an error? I would expect the client defaults to work (or at least no set a version altogether)

**Comment by lirenhe** [comment]
I believe this is a service decision not to support sqlServerRegistrations in the latest api version. The Go SDK is auto generated from the Swagger spec so could you create a support ticket for the service team to clarify this behavior?

**Comment by erezrokah** [comment]
> so could you create a support ticket for the service team to clarify this behavior?

Thanks for the reply @lirenhe, how should I got about doing that? Can you please link to the team's ticketing system?

**Comment by lirenhe** [comment]
Please follow this:  https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by erezrokah** [comment]
Thanks @lirenhe I submitted a support ticket and will report back once I have more information

**Comment by erezrokah** [comment]
Hi all 👋 I got the following response from Azure Support.
TDLR: This API is deprecated and we should use https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/azurearcdata/armazurearcdata@v0.5.0#SQLServerInstancesClient.NewListPager

Redacted response(s):
```
SQL Server Registry is no longer supported, and that customer should use the Arc-enabled SQL Server Extension to register for security updates now.
--------------------------------------------------------------------------------
To get started using REST API's, view the intro guide here: https://learn.microsoft.com/en-us/rest/api/azure/ 

and to view the SQL Server Instance specifications: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurearcdata/resource-manager/Microsoft.AzureArcData/preview/2022-03-01-preview/examples/CreateOrUpdateSqlServerInstance.json

You can view the documentation for the Go SDK here: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/azurearcdata/armazurearcdata@v0.5.0#SQLServerInstancesClient.BeginCreate 

SQL Server Registrations are represented as SQL Server Instances in Azure, so to "register" your instance, you would need to use either the REST APIs or the Go SDK to create a SQL Server Instance resource in Azure, and the parameters in your create request should map to what is described in the documentation here: https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-extended-security-updates?view=sql-server-ver16#single-sql-server-instance 
```

Closing as resolved
