### ISSUE TITLE
bug(armhealthbot): Wrong API version for `armhealthbot.NewBotsClient`

### ISSUE THREAD

**Issue by erezrokah** [Azure/azure-sdk-for-go#19790]
### Bug Report

Example Go code using `v1.0.0` of the API:

```go
package healthbot

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/healthbot/armhealthbot"
)

func fetchBots(ctx context.Context) error {
	svc, err := armhealthbot.NewBotsClient(...)
	if err != nil {
		return err
	}
	pager := svc.NewListPager(nil)
	for pager.More() {
		p, err := pager.NextPage(ctx)
		if err != nil {
			return err
		}
		fmt.Println(p.Value)
	}
	return nil
}

```

- output of `go version` - `go version go1.19.3 darwin/arm64`

I'm getting an error when trying the above code. The error is:
```
The resource type 'healthBots' could not be found in the namespace 'Microsoft.HealthBot' for api version '2021-06-10'. The supported api-versions are '2020-12-08,2021-08-24,2022-08-08'
```

Setting the API version via `ClientOptions` to `2022-08-08` fixes the issue.
Looks like the client defaults to `2021-06-10`:
https://github.com/Azure/azure-sdk-for-go/blob/a97519174f72085debd57f0b1189aaa2b62f5f7b/sdk/resourcemanager/healthbot/armhealthbot/zz_generated_bots_client.go#L284

**Comment by lirenhe** [comment]
@tadelesh, could you check with service team about whether we should release a new version for this package?  Thanks

**Comment by tadelesh** [comment]
@erezrokah According to service swagger spec, it should support API version `2021-06-10`. @navba-MSFT I think it is a service problem, could you help with?

**Comment by navba-MSFT** [comment]
@erezrokah @tadelesh Thanks for reaching out to us and reporting this issue. As you rightly pointed it, `2021-06-10 `version is indeed supported. 

Ref: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/healthbot/resource-manager/readme.go.md
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/healthbot/resource-manager/Microsoft.HealthBot/stable/2021-06-10

I am looking into this issue further. I will get back to you with an update.

**Comment by navba-MSFT** [comment]
@erezrokah @tadelesh I am working with the Service team to address this. I have no ETA for the fix. I will keep you posted about the progress.

**Comment by erezrokah** [comment]
Thank you for looking into this @navba-MSFT, I appreciate the quick response

**Comment by navba-MSFT** [comment]
@erezrokah @tadelesh We have resolved this issue and the SDK should work with the API 2021-06-10.
This change will take a few days to propagate on all the regions, but it should be all resolved by the **end of next week.** Hope this helps.

**Comment by erezrokah** [comment]
Thanks for the quick fix @navba-MSFT, @lirenhe and @tadelesh. I'll verify this works and follow up

**Comment by erezrokah** [comment]
I can confirm this issue is resolved. Thanks everyone 🚀
