### ISSUE TITLE
`Azure Identity` - support customized Default Credential

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-sdk-for-go#19799]
### Feature Request

We use [Azure Identity Client Module](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#azure-identity-client-module-for-go) to address token authentication issue. Currently, [NewDefaultAzureCredential](https://github.com/Azure/azure-sdk-for-go/blob/4474d1e0354dbd50a405e94f56625a9aa62edb3c/sdk/azidentity/default_azure_credential.go#L51) creates the Credentials in a fixed order. Our requirement is to enable only part of these credentials and make the creation order of credentials sortable.

At first, we tried to rewrite our own NewDefaultAzureCredential, but we found some credentials assign values to private fields(like [NewManagedIdentityCredential](https://github.com/Azure/azure-sdk-for-go/blob/4474d1e0354dbd50a405e94f56625a9aa62edb3c/sdk/azidentity/default_azure_credential.go#L100), [NewChainedTokenCredential](https://github.com/Azure/azure-sdk-for-go/blob/4474d1e0354dbd50a405e94f56625a9aa62edb3c/sdk/azidentity/default_azure_credential.go#L123)), which cannot be migrated to our code.

Is it possible to make credentials in NewDefaultAzureCredential selectable and sortable? Or is it possible to expose the operation of assigning values to private fields to public users so that we can write our own default credential?

**Comment by chlowell** [comment]
> At first, we tried to rewrite our own NewDefaultAzureCredential, but we found some credentials assign values to private fields(like [NewManagedIdentityCredential](https://github.com/Azure/azure-sdk-for-go/blob/4474d1e0354dbd50a405e94f56625a9aa62edb3c/sdk/azidentity/default_azure_credential.go#L100), [NewChainedTokenCredential](https://github.com/Azure/azure-sdk-for-go/blob/4474d1e0354dbd50a405e94f56625a9aa62edb3c/sdk/azidentity/default_azure_credential.go#L123)), which cannot be migrated to our code.
> 

You can implement the behavior of `ManagedIdentityCredential.imdsTimeout` with a small wrapper: https://github.com/Azure/azure-sdk-for-go/issues/19699#issuecomment-1379290680. `ChainedTokenCredential.name` is used only in log messages; why do you need to override its default value, "ChainedTokenCredential"?

**Comment by ms-zhenhua** [comment]
Hi @chlowell, thank you for your solution. But it seems that `azidentity.NewCredentialUnavailableError` is only available in azidentity v1.3.0, which is still in `beta` stage. Do you have any plan to support it in v1.2.x? If not, may I know when do you plan to roll out the standard v1.3.0?
