### ISSUE TITLE
[azappconfig] AddSetting should handle content-type

### ISSUE THREAD

**Issue by Eviradnus** [Azure/azure-sdk-for-go#19797]
### Get AppConfig settings Content-Type back

The v0.1.0 & v0.2.0 provided a way to add AppConfig settings with a Content-Type (using a generous `Setting` struct); it's now impossible (from v0.3.0 onwards, only the label is accessible in the `AddSettingOptions`).

It would be nice to get this feature back, typically for Azure KeyVault references.

**Comment by jhendrixMSFT** [comment]
Fix will come out in this month's release.
