### ISSUE TITLE
Mock Clients for VMSS, VMAS, and VM

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/azure-sdk-for-go#19839]
### Feature Request
 
For the VMSS and VMAS clients it would be nice to have a set of mock interfaces. Currently trying to test some functionality and basically the easiest way to test is I have to build a mock client for the 

```go
VirtualMachineScaleSetsClient, err := armcompute.NewVirtualMachineScaleSetsClient(SubscriptionID, credential, &armConfig)
	VirtualMachineScaleSetVMsClient, err := armcompute.NewVirtualMachineScaleSetVMsClient(SubscriptionID, credential, &armConfig)
```

I have notices that everyone ends up implementing their own mocks for this code and was wondering when the team plans on adding them into the sdk for people to use.

**Comment by jhendrixMSFT** [comment]
This work is tracked in https://github.com/Azure/azure-sdk-for-go/issues/16613 where you can see the current thinking (feel free to add any input on the design thus far).

While I can't commit to a specific timeline, this is high on my list of priorities, and I hope to have a beta out relatively soon.
