### ISSUE TITLE
bug(`armsecurity.Contact`): Trying to paginate over results fails with an unmarshalling error

### ISSUE THREAD

**Issue by erezrokah** [Azure/azure-sdk-for-go#19833]
### Bug Report

Example Go code using `v0.9.0` of the API:

```go
package security

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity"
)

func fetchContacts(ctx context.Context) error {
	svc, err := armsecurity.NewContactsClient(...)
	if err != nil {
		return err
	}
	pager := svc.NewListPager(nil)
	for pager.More() {
		p, err := pager.NextPage(ctx)
		if err != nil {
			return err
		}
		fmt.Println(p.Value)
	}
	return nil
}

```

- output of `go version` - `go version go1.19.3 darwin/arm64`

I'm getting an error when trying the above code. The error is:
```
unmarshalling type *armsecurity.ContactList: unmarshalling type *armsecurity.ContactList: json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```

Looks like there's a mismatch in the code here:
https://github.com/Azure/azure-sdk-for-go/blob/2a983c938d002d4f27b2d277fc352b636b4d8eb5/sdk/resourcemanager/security/armsecurity/contacts_client.go#L255

though I'm not sure what's the correct code should look like

**Comment by tadelesh** [comment]
Duplicate with https://github.com/Azure/azure-sdk-for-go/issues/19740.

**Comment by erezrokah** [comment]
Thanks for the tip @tadelesh, closing as duplicate
