### ISSUE TITLE
go: create zip: module source tree too large (max size is 524288000 bytes)

### ISSUE THREAD

**Issue by woohgit** [Azure/azure-sdk-for-go#19845]
### Bug Report

Can't update to `v67.0.4`.

```
go version go1.19.2 linux/amd64
```

```
go: downloading github.com/Azure/azure-sdk-for-go v67.4.0+incompatible
go: create zip: module source tree too large (max size is 524288000 bytes)
go: create zip: module source tree too large (max size is 524288000 bytes)
go: create zip: module source tree too large (max size is 524288000 bytes)
go: create zip: module source tree too large (max size is 524288000 bytes)
go: create zip: module source tree too large (max size is 524288000 bytes)
go: create zip: module source tree too large (max size is 524288000 bytes)
```

From sum server: https://sum.golang.org/lookup/github.com/!azure/azure-sdk-for-go@v67.4.0+incompatible

Response:
```
not found: create zip: module source tree too large (max size is 524288000 bytes)
```

**Comment by tadelesh** [comment]
> ### Bug Report
> Can't update to `v67.0.4`.
> 
> ```
> go version go1.19.2 linux/amd64
> ```
> 
> ```
> go: downloading github.com/Azure/azure-sdk-for-go v67.4.0+incompatible
> go: create zip: module source tree too large (max size is 524288000 bytes)
> go: create zip: module source tree too large (max size is 524288000 bytes)
> go: create zip: module source tree too large (max size is 524288000 bytes)
> go: create zip: module source tree too large (max size is 524288000 bytes)
> go: create zip: module source tree too large (max size is 524288000 bytes)
> go: create zip: module source tree too large (max size is 524288000 bytes)
> ```
> 
> From sum server: https://sum.golang.org/lookup/github.com/!azure/azure-sdk-for-go@v67.4.0+incompatible
> 
> Response:
> 
> ```
> not found: create zip: module source tree too large (max size is 524288000 bytes)
> ```

@woohgit Please use the latest [v68.0.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible).
