### ISSUE TITLE
Event Hubs: "conn" package is not exported in new SDK

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/azure-sdk-for-go#19840]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs`
- SDK version: `0.4.0`
- output of `go version`: `1.19.4`

### Description

In the new "track 2" SDK for Event Hubs, the `conn` package is marked as internal: `github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs/internal/conn`

Because of that, we cannot use the `ParsedConnectionFromStr` method to parse a connection string like the SDK does. We need to do that in Dapr to be able to determine if the user passed a connection string that includes an entity path or not, and behave accordingly.

**Comment by richardpark-msft** [comment]
This has been released!

https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fmessaging%2Fazeventhubs%2Fv0.5.0

**Comment by ItalyPaleAle** [comment]
Thank you @richardpark-msft , updating now :)
