### ISSUE TITLE
Key Vault auth policy specifies tenant ID for token requests

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#19841]
Once `azcore/policy.TokenRequestOptions` has a `TenantID` field (part of #17159), Key Vault's auth policy should set that field and update its value upon receiving a challenge, so that token requests always specify the correct tenant. This is a low priority because a vault's tenant changes only when that vault moves to a new tenant, a vanishingly rare scenario that can currently be handled by creating a new client after the move.

**Comment by gracewilcox** [comment]
Tracked in https://github.com/Azure/azure-sdk-for-go/issues/22928
