### ISSUE TITLE
ResourceGroup Always Omits Name

### ISSUE THREAD

**Issue by pkrauss-prot** [Azure/azure-sdk-for-go#19857]
### Bug Report

- import path of package in question, `services/resources/mgmt/2019-07-01/features/models.go`
- SDK version `v68.0.0`
  - commit ec2ed6d8450ad53978efa96822bf9c9431a63ab4
- go version go1.19.1 linux/amd64

- What happened? `features.ResourceGroup` with either the built in helper `MarshalJSON` or using `json.Marshal` skips marshaling the resource group name.
- What did you expect or want to happen? I expect my Marshaled byte code to include the name of the resource group
- How can we reproduce it? Return a single or multiple resource groups and attempt to marshal to json

```
=== RUN   TestGetResourceGroups
response status:  200
{
    "location": "eastus",
    "properties": {}
}
{
    "location": "eastus",
    "properties": {}
}
...
```

- Anything we should know about your environment. Nothing worth noting.

**Comment by jhendrixMSFT** [comment]
Unfortunately, this is by design in our legacy SDK.  Our updated SDKs no longer have this behavior.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armfeatures

**Comment by pkrauss-prot** [comment]
Ahhh okay, as I suspected, it looked way to deliberate. Is the teams suggestion to support both the legacy SDKs and new SDKs auth handlers? Honestly that was the only reason I was not using the newer SDK where it supported service implementations.
