### ISSUE TITLE
AKS cluster minor version update failed

### ISSUE THREAD

**Issue by zhilong1115** [Azure/azure-sdk-for-go#19850]
### Bug Report

I feel sdk version is unrelevent. But I am using this version: github.com/Azure/azure-sdk-for-go@v59.2.0

- What happened?
```
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: 
Code="OperationNotAllowed" Message="The specified orchestrator version 1.24 is not supported in regions: westus2. Please 
see [https://aka.ms/aks-supported-k8s-ver](https://www.google.com/url?q=https://aka.ms/aks-supported-k8s-ver&sa=D) for 
version details."
```
- What did you expect or want to happen?     
I think it should pick latest patch of 1.24 and listed when I check supported k8s version via:
```
❯ az aks get-versions --location westus2 -o table
KubernetesVersion    Upgrades
-------------------  -----------------------
1.25.4               None available
1.25.2               1.25.4
1.24.6               1.25.2, 1.25.4
1.24.3               1.24.6, 1.25.2, 1.25.4
1.23.12              1.24.3, 1.24.6
1.23.8               1.23.12, 1.24.3, 1.24.6
```
Also, I can update cluster successfully with patch version set.
- How can we reproduce it?
Create and update aks cluster with major.minor
- Anything we should know about your environment.

**Comment by xboxeer** [comment]
@zhilong1115 A design principle of Azure SDK is that SDK should not make any assumption that the error returned by Azure service can be mitigated on client side (in your case, pick the latest patch of 1.24). you should either switch to a newer version of AKS when creating or write error handling code for this version not supported error

**Comment by jbpaux** [comment]
I think this issue is on ARM side rather than the SDK which just send the requested update job. Same issue can occur using other languages.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
