### ISSUE TITLE
Storage: doc comment of service.Client.GetSASURL suggests using CanGetAccountSASToken, which does not exist

### ISSUE THREAD

**Issue by mattyhall** [Azure/azure-sdk-for-go#19864]
### Bug Report

- import path of package in question: **storage/azblob/service**
- SDK version e.g. `master`, `latest`, `18.1.0`:  **master, v0.5.1**
- output of `go version`: **`go version go1.19.5 darwin/amd64`**

- What happened?
In my application I am given a service client and I would like to know if I can call `GetSASURL` on it - i.e. if the client was created with a shared key credential. The doc comment for this function suggests using `CanGetAccountSASToken` which is a method that existed in v0.4.1. It seems that in v0.5.1 and on master this method no longer exists.

Is there a different way we are supposed to find this information? If so I think the doc comment needs updating. Otherwise would it be possible to have this method added back?

**Comment by vibhansa-msft** [comment]
Thanks for reaching out. 
As user is creating the client, we assume user is well aware that SAS can be created or not. Is there any specific reason for application to check this part ? We have taken a note and will update the document accordingly, as this method is no longer supported.

**Comment by mattyhall** [comment]
This is for a library that wraps cloud APIs (AWS, Azure etc) and provides a unified interface across them. The "user" in this case is the user of this library and they are allowed to pass a client that was created using any authentication method and the library should do the right thing. In cases where a shared key is used we need to create a SAS URL, otherwise we can use the normal URL.

Are the reasons for removing this API (or the fact that it has been removed) documented anywhere?

**Comment by siminsavani-msft** [comment]
Hi @mattyhall ! The CanGetAccountSASToken API is removed because the check that occurred in this API is now present in the GetSASURL API itself so there is no need for it.

Thank you for bringing it to our attention, I will work on improving the documentation here.

**Comment by mattyhall** [comment]
Thanks both for the replies. I can see the check in `GetSASURL` itself and if it fails it returns an error. Would it be possible to define an error for this and export it, rather than creating a new one inline? Then users are free to handle it if they wish

**Comment by siminsavani-msft** [comment]
@mattyhall, that's a great suggestion! I will work on defining an error code for this. Thank you!

**Comment by siminsavani-msft** [comment]
A new errortype MissingSharedKeyCredential has been added.
