### ISSUE TITLE
Issue with ConnectionString and Azure SDK

### ISSUE THREAD

**Issue by jefflaubtgcs** [Azure/azure-sdk-for-go#19868]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0` 
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

How do I tell from Azure what Level SDK version is on for the Azure Storage Account?
Or REVISION?
Verified the Connection String Created by Terraform works successfully with Azure Storage Explorer with Signed version of 2019-10-10.
This can be archived by right clicking on the Azure Storage Account under your subscription. Selecting Storage account or service. Then select Conention String(Key or SAS) fill in the Connection String parameter.
If I try a different signed version such as 2021-06-08 The Connection String does not work with Azure Storage Explorer.
I am unclear if something wrong with terraform, the sas service string or Azure SDK

Once my application is deployed to AKS I see the following error using signed version of 2019-10-10
2023-01-23 20:18:53.252 <fc8d48ad54be93925b65a9cc0567489f> DEBUG 1 --- [io-8080-exec-10] lVisionDataProcessorAzureBlobServiceImpl : Fetching existing Blob Container: mycontainer
2023-01-23 20:18:53.253 <fc8d48ad54be93925b65a9cc0567489f> DEBUG 1 --- [io-8080-exec-10] lVisionDataProcessorAzureBlobServiceImpl : Uploading to Blob storage as blob: https://abc.blob.core.windows.net/mycontainer/tgcs%2F2023-01-23%2F3535%2F461%2F4033%2F735%2Fbb250ca6-ab00-4709-bcab-3c20d44c2611%2Fbb250ca6-ab00-4709-bcab-3c20d44c2611.png
2023-01-23 20:18:53.359 <fc8d48ad54be93925b65a9cc0567489f> ERROR 1 --- [io-8080-exec-10] s.i.RetailVisionDataProcessorServiceImpl : Error uploading the image message :If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0ff0c461-b01e-00ce-7a67-2fb8a0000000
Time:2023-01-23T20:18:53.3051919Z</Message><AuthenticationErrorDetail>sr is mandatory. Cannot be empty</AuthenticationErrorDetail></Error>"
2023-01-23 20:18:53.361 <fc8d48ad54be93925b65a9cc0567489f> DEBUG 1 --- [io-8080-exec-10] .t.t.f.s.SpringBootRestfulControllerUtil : Error Occurred (412) 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/storage_account_sas
Terraform doc to create the Connection String. Note I am able to recreate on one environment but not on another environment.

Where Connection string is as following
BlobEndpoint=https://abc.blob.core.windows.net/;QueueEndpoint=https://abc.queue.core.windows.net/;FileEndpoint=https://abc.file.core.windows.net/;TableEndpoint=https://abc.table.core.windows.net/;SharedAccessSignature=?sv=2019-10-10&ss=bqtf&srt=sco&sp=rwdlacuptf&se=2024-01-23T19:49:57Z&st=2023-01-23T19:49:57Z&spr=https&sig=KAhpu9iXHUSkftN3Ok%2FvcoaD%2Fz52jNrUwI1vcV8nl6M%3D

**Comment by navba-MSFT** [comment]
@jefflaubtgcs Thanks for reaching out to us and reporting this issue. I looked at the backend logs for the failing request ID. I see that the SAS token is being used to Authorize to the storage account. but the SAS token doesn't seem to be quite right. 

> **sr is mandatory. Cannot be empty**

Could you please let us know how are you generating the SAS token ? Awaiting your reply.

**Comment by jefflaubtgcs** [comment]
@navba-MSFT I generated the string using terraform code. Did some additional testing today. Seem no issues with inserting the string into yaml so that is good. I am trying to understand as well why 2019-10-10 works with Azure Storage Explorer but 2021-06-08 does not. Both do not work with the application. The Connection string was generated using terraform. Following this document. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/storage_account_sas with all permissions set to true.

**Comment by jefflaubtgcs** [comment]
Is there a relation between what can be used with Azure Storage Account and the Application version of Azure.Storage.Blobs which is using version 12.12.0?

Here I see.
Server Version: 2021-02-12, 2020-12-06, 2020-10-02, 2020-08-04, 2020-06-12, 2020-04-08, 2020-02-10, 2019-12-12, 2019-07-07, and 2019-02-02

**Comment by siminsavani-msft** [comment]
Hi @jefflaubtgcs , please view this example to create a client using connection string: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/container/examples_test.go#L86

Here's an example of creating a client with SAS as well: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/container/examples_test.go#L274

**Comment by jefflaubtgcs** [comment]
@siminsavani-msft Do you have a sample using terraform? Currently I am using terraform not Azure Functions. Where can I locate the signed version?  The Connection string seems fine using Azure Storage Explorer using 2019-10-10 signed version however not working with 2021-06-08. Seems the application is not working with either signed version and the application is using Azure Storage Client 12.10.0

**Comment by siminsavani-msft** [comment]
@jefflaubtgcs There seems to be a bug on terraform. You may want to check out the terraform github repository: https://github.com/hashicorp/terraform-provider-azurerm and the documentation: [https://learn.microsoft.com/en-us/azure/developer/terraform/](https://learn.microsoft.com/en-us/azure/developer/terraform/). The SDK team doesn't work directly with terraform so we won't be able to assist you with questions regarding it. Since this is not an SDK related, I will be closing this issue.
