### ISSUE TITLE
How can I get "InternalFqdn" field value from NetworkInterface - InterfaceDNSSettings

### ISSUE THREAD

**Issue by lrxtom2** [Azure/azure-sdk-for-go#1987]
Hi team,
I want to use this field "InternalFqdn" in golang, but i can't get this field returned anything.
Could you please tell me that how to use this to get the field returned?

Thanks for all of that.

reference:
github.com/Azure/azure-sdk-for-go/services/network/mgmt/2017-09-01/network
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/get

**Comment by jhendrixMSFT** [comment]
@MikhailTryakhov it seems the API doesn't return anything for this field.  Is that expected?

**Comment by MikhailTryakhov** [comment]
Hi @jhendrixMSFT  could you please address this question to Mohammed Waqar from DNS team?

**Comment by jhendrixMSFT** [comment]
@muwaqar can you please help?

**Comment by lrxtom2** [comment]
Hi,
Thanks for working.
Any update?

**Comment by jhendrixMSFT** [comment]
Ping @muwaqar

**Comment by lrxtom2** [comment]
Thanks for @muwaqar 
Waiting for update.

**Comment by muwaqar** [comment]
@lrxtom2 : Sorry we have been trying to find out the right owner for this issue and the current behavior. Can you please confirm that when you issue this API call, is the NIC attached to the VM? If not, can you please attach it to the VM and issue this call again and see if the InternalFQDN is now populated?

**Comment by lrxtom2** [comment]
@jhendrixMSFT  That's very kind of you.

**Comment by jhendrixMSFT** [comment]
Tracked in https://github.com/Azure/azure-sdk-for-go/issues/1987.
