### ISSUE TITLE
Getting unauthorized error when trying to retrieve appconfig setting

### ISSUE THREAD

**Issue by chrismason** [Azure/azure-sdk-for-go#19874]
### Bug Report

- import path of package in question: `sdk/data/azappconfig`
- SDK versions:
  - `azure-sdk-for-go`: `v63.2.0`
  - `azure-sdk-for-go/sdk/azcore`: `v1.3.0`
  - `azure-sdk-for-go/sdk/data/azappconfig`: `v0.5.0`
- `go version`: `go1.19.4 darwin/amd64`

I am trying to use the go sdk to read feature flags from azure app configuration. I am able to query a list of settings from app config but not able to query an individual flag. When I try to call the individual flag I am getting a 401 unauthorized. The code in question is below:

```go
opts := azappconfig.ClientOptions{}
client, err := azappconfig.NewClientFromConnectionString(cfg.AppConfigConnectionString, &opts)
if err != nil {
    return nil, err
}

var any = "*"
var keyFilter = ".appconfig.featureflag/*"
selector := azappconfig.SettingSelector{KeyFilter: &keyFilter, LabelFilter: &any, Fields: azappconfig.AllSettingFields()}
pager := client.NewListSettingsPager(selector, nil)
for pager.More() {
    page, err := pager.NextPage(context.TODO())
    if err != nil {
        return nil, err
    }
    // this works
    for _, setting := range page.Settings {
        fmt.Printf("Setting key: %s value: %s\n", *setting.Key, *setting.Value)
    }
}

flagKey := fmt.Sprintf(".appconfig.featureflag/%s", "test")
resp, err := client.GetSetting(context.TODO(), flagKey, nil)
if err != nil {
    // This is where the code returns a 401
    fmt.Printf("error: %v\n", err)
    return nil, err
}
fmt.Printf("Response %v\n", resp)
```

When I run the program the output I get is:
For the listing of settings:
```
Setting key: .appconfig.featureflag/test value: {"id": "test", "description": "", "enabled": true, "conditions": {"client_filters": []}}
```
For the individual query:
```
error: GET https://<appconfigname>.azconfig.io/kv/.appconfig.featureflag/test
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
Response contained no body
--------------------------------------------------------------------------------
```

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

Interesting to note that if you switch to using AAD authentication you'll receive a 404 instead.  This is because feature flags aren't "real key/values" from App Config's perspective.  I do agree that it's weird though that they're returned when listing settings.

**Comment by jhendrixMSFT** [comment]
Also wanted to add that we have a work item tracking better support for feature flags in the SDK https://github.com/Azure/azure-sdk-for-go/issues/12432

**Comment by jhendrixMSFT** [comment]
The 404 is a red herring.  Using AAD auth the bug doesn't repro.  It revolves around our URL-encoding of the `key` parameter during path construction (removing it resolves the issue, but I don't believe this is how we'll be fixing it).  We must have a bug in our HMAC auth policy someplace.

https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-hmac

**Comment by jhendrixMSFT** [comment]
Fix will come out in this month's release.  Thanks for the bug report.
