### ISSUE TITLE
CopyFromURL returns ambiguous error when file size is bigger than 256Mib

### ISSUE THREAD

**Issue by N-o-Z** [Azure/azure-sdk-for-go#19880]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version:
  - github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.4
  - github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.1.0
  - github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.6.1  
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- go version go1.19.3 linux/amd64

- Actual behavior: When using CopyFromURL on blobs larger than 256Mib the error code returned is `CannotVerifyCopySource` and StatusCode is `409`
- To determine that the issue was indeed failure due to blob size we must parse the error string
- The expected behavior is to provide a specific error code which indicates the exact reason for the failure.  For instance `CannotVerifyCopySource` is also returned upon authentication errors
- How can we reproduce it? Perform CopyFromURL on blob of size > 256Mib

**Comment by souravgupta-msft** [comment]
Hi @N-o-Z. Thanks for reaching out. The error code `CannotVerifyCopySource` and status code `409` is coming from the service. If you want to get the reason for failure, you can follow the below code.
```
var responseErr *azcore.ResponseError
errors.As(err, &responseErr)
fmt.Println(responseErr.RawResponse.Status)
```
 It will print the following.
`409 The source request body for synchronous copy is too large and exceeds the maximum permissible limit (256MB).`

**Comment by N-o-Z** [comment]
@souravgupta-msft thanks for the reply!
The error message is prone to change without prior notification and I don't think it's a good coding practice to rely on it. I would have expected a designated error code for this specific scenario

**Comment by souravgupta-msft** [comment]
This is not controlled on the SDK side as of now. SDK just forwards what the backend service returns.

**Comment by N-o-Z** [comment]
@souravgupta-msft thanks - is there aother place where I could submit this issue other than the sdk project?

**Comment by souravgupta-msft** [comment]
Just for understanding, why can't you match the 409 status code returned in this case.
The [API doc](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url#request-headers) also states the same.
`If the size of the source blob is greater than 256 MiB, the request fails with a 409 (Conflict) error.`

**Comment by N-o-Z** [comment]
Simply because this is not the only error which returns 409.
For example see the x-ms-tags REPLACE option

**Comment by souravgupta-msft** [comment]
As I had stated earlier this error code is something which is coming from the backend. SDK is just relaying it to the user.
I will forward your concern to the backend team. Closing this issue as nothing can be done from the SDK side.
