### ISSUE TITLE
Azure Savings Plan Orders and Savings Plan SDK for Go

### ISSUE THREAD

**Issue by vijayprasath99** [Azure/azure-sdk-for-go#19897]
For SavingsPlan orders and SavingsPlans, I was able to find the REST API (docs: https://learn.microsoft.com/en-us/rest/api/billingbenefits/savings-plan/list?tabs=HTTP). I'm opening a ticket to request this be added to the AzureSDK.

**Comment by jhendrixMSFT** [comment]
I believe this already exists, please take a look at the following.

https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/billingbenefits/armbillingbenefits
