### ISSUE TITLE
Generated const Enum types should not be pointers

### ISSUE THREAD

**Issue by NickKeller** [Azure/azure-sdk-for-go#19905]
## Import Path
- *"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armpolicy"*
## SDK Version
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armpolicy v0.6.0 but present on master branch
## output of `go version`
```
➜  ~/go/src/go.goms.io/aks/rp git:(nikelle/e2elargeheader) (hcpnikelleebld61875511-eastus-svc-0) (Development)
command: go version
go version go1.19.5 darwin/amd64
```

## What happened?
The generated go model for enum types specifies a pointer to the enum type. For example, the [ParameterDefinitionsValue struct](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/resources/armpolicy/zz_generated_models.go#L710) specifies the `ParameterType` as a pointer. However, the [possible values for ParameterType](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/resources/armpolicy/zz_generated_constants.go#L169) are all constants. Golang does not let you take the address of a constant, so this leads to having to redeclare and use the ParameterTypes like so:
```golang
import (
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armpolicy"
)

var (
	ParameterTypeArray    armpolicy.ParameterType = "Array"
	ParameterTypeBoolean  armpolicy.ParameterType = "Boolean"
	ParameterTypeDateTime armpolicy.ParameterType = "DateTime"
	ParameterTypeFloat    armpolicy.ParameterType = "Float"
	ParameterTypeInteger  armpolicy.ParameterType = "Integer"
	ParameterTypeObject   armpolicy.ParameterType = "Object"
	ParameterTypeString   armpolicy.ParameterType = "String"
)

func main(){
	var parameter = armpolicy.ParameterDefinitionsValue{
		Type: &ParameterTypeArray, //would love to just use armpolicy.ParameterTypeArray here
                 // etc
	}
}
```

This seems to be present with all enum types, at least in the armpolicy data models. I don't know about the other ARM resources
## What did you expect or want to happen?
Either the `Type *ParameterType` field on the `ParameterDefinitionsValue` should not be a pointer, or the available `ParameterTypes` should be created with the `var` declaration rather than `const`
## How can we reproduce it?
This should give you the compile error
```golang
import (
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armpolicy"
)

func main(){
	var parameter = armpolicy.ParameterDefinitionsValue{
		Type: &armpolicy.ParameterTypeArray,
	}
}
```

**Comment by jhendrixMSFT** [comment]
We have the [`to`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.3.0/to) package in `azcore` to help with this.  You can write the following.
```go
var parameter = armpolicy.ParameterDefinitionsValue{
	Type: to.Ptr(armpolicy.ParameterTypeArray),
}
```

**Comment by jhendrixMSFT** [comment]
I will add that discoverability of the `to` package is difficult, and you're not the first person to run into this.  We're working on some "getting started" type docs that we hope will improve the discoverability.
