### ISSUE TITLE
Resource provider not registred automatically for `Microsoft.Security/pricings`

### ISSUE THREAD

**Issue by ms-henglu** [Azure/azure-sdk-for-go#19900]
With track2 sdk, creating of a Microsoft.Security/pricings@2022-03-01 resource is failing to a newly created subscription without a registered Microsoft.Security provider. 

```bash
│ PUT https://management.azure.com/subscriptions/[subscription-id]/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2022-03-01
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE: Subscription Not Registered
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "Subscription Not Registered",
│     "message": "Please register to Microsoft.Security in order to view your security status"
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
╵
```

This might be caused by the fact that the automatic resource registration is checking for the error code `MissingSubscriptionRegistration` but the API is returning `Subscription Not Registered`

https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azcore/arm/runtime/policy_register_rp.go#L83

**Comment by tadelesh** [comment]
@eliagrady I wonder if the error is returned from ARM or your service which is not consistent with the [guide](https://github.com/Azure/azure-resource-manager-rpc/blob/13e38b290b7bdde85285139271143bb876ec0c14/v1.0/subscription-lifecycle-api-reference.md#subscription-states). Could you help to take a look?
