### ISSUE TITLE
Cannot retrieve effective routes for Virtual Hub 

### ISSUE THREAD

**Issue by Alexandru-Postescu** [Azure/azure-sdk-for-go#19925]
- Package Name: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork
- Package Version: latest
- Operating System: Mac OS
- GO version: 1.18 

### Describe the bug
I am trying to retrieve the effective routes for a virtual hub but the sdk always returns an empty struct.
###  Steps to reproduce
```go
poller, err := vhubClient.BeginGetEffectiveVirtualHubRoutes(context.Background(), rgName, name,
		&armnetwork.VirtualHubsClientBeginGetEffectiveVirtualHubRoutesOptions{EffectiveRoutesParameters: ...})

if err != nil {
	...
}

values, err := poller.PollUntilDone(context.Background(), nil)
if err != nil {
	...
}
	
return values // type of  armnetwork.VirtualHubsClientGetEffectiveVirtualHubRoutesResponse which is an empty struct
```
### Expected behaviour
To be able to retrieve EffectiveVirtualHubRoutes from armnetwork.VirtualHubsClientGetEffectiveVirtualHubRoutesResponse

**Comment by navba-MSFT** [comment]
@Alexandru-Postescu Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Alexandru-Postescu Could you please confirm if you are able to retrieve the effective hub virtual routes by directly invoking [this REST API ](https://learn.microsoft.com/en-us/rest/api/virtualwan/virtual-hubs/get-effective-virtual-hub-routes?tabs=HTTP)?  

Could you try with the below sample and test again ?

```
cred, err := azidentity.NewDefaultAzureCredential(nil)
if err != nil {
	log.Fatalf("failed to obtain a credential: %v", err)
}
ctx := context.Background()
client, err := armnetwork.NewVirtualHubsClient("subid", cred, nil)
if err != nil {
	log.Fatalf("failed to create client: %v", err)
}
poller, err := client.BeginGetEffectiveVirtualHubRoutes(ctx, "rg1", "virtualHub1", &armnetwork.VirtualHubsClientBeginGetEffectiveVirtualHubRoutesOptions{EffectiveRoutesParameters: nil})
if err != nil {
	log.Fatalf("failed to finish the request: %v", err)
}
_, err = poller.PollUntilDone(ctx, nil)
if err != nil {
	log.Fatalf("failed to pull the result: %v", err)
}
```

More Info [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2#VirtualHubsClient.BeginGetEffectiveVirtualHubRoutes).

**Comment by Alexandru-Postescu** [comment]
@navba-MSFT I can confirm that it works retrieving the virtual hub effective routes using az cli. Anyway, the code sample you provided does not help me retrieve the effective routes from the response of the poller. 
Consider the following example: 
```
cred, err := azidentity.NewDefaultAzureCredential(nil)
if err != nil {
	log.Fatalf("failed to obtain a credential: %v", err)
}
ctx := context.Background()
client, err := armnetwork.NewInterfacesClient("subid", cred, nil)
if err != nil {
	log.Fatalf("failed to create client: %v", err)
}
poller, err := client.BeginGetEffectiveRouteTable(ctx, "rg1", "nic1", nil)
if err != nil {
	log.Fatalf("failed to finish the request: %v", err)
res, err = poller.PollUntilDone(ctx, nil) // res is of type [InterfacesClientGetEffectiveRouteTableResponse] which contains a property [EffectiveRouteListResult] from where I can retrieve the effective routes
if err != nil {
	log.Fatalf("failed to pull the result: %v", err)
}

```
In this case, the poller returns a struct with a property from where I can retrieve the effective routes.
In the case of Hub virtual effective routes the poller returns an empty struct.. There is another way to retrieve the response using this sdk?

**Comment by navba-MSFT** [comment]
@Alexandru-Postescu Thanks for your reply. Could you please check if the below sample helps ?

```
package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-03-01/network"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
	// Define the Azure subscription ID and resource group name.
	subscriptionID := "<subscription-id>"
	resourceGroup := "<resource-group-name>"
	virtualHubName := "<virtual-hub-name>"

	// Create an authorizer using a client ID and secret.
	authorizer, err := auth.NewAuthorizerFromClientCredentials(context.Background(), "<azure-ad-tenant-id>", "<client-id>", "<client-secret>")
	if err != nil {
		fmt.Println(err)
		return
	}

	// Create a VirtualHub client.
	virtualHubClient := network.NewVirtualHubsClient(subscriptionID)
	virtualHubClient.Authorizer = authorizer

	// Get the effective routes for the Virtual Hub.
	effectiveRoutes, err := virtualHubClient.GetEffectiveRoutes(context.Background(), resourceGroup, virtualHubName)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("Effective Routes:")
	for _, route := range *effectiveRoutes.Value {
		fmt.Println("-", *route.Name)
	}
}

```

**Comment by Alexandru-Postescu** [comment]
I can confirm it works, but we just migrated from that package to not rely on deprecated packages.

**Comment by navba-MSFT** [comment]
@Alexandru-Postescu Thanks for the confirmation. Could you please refer [this](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-guideline.md#logging) to get the raw http request and response and paste here. We can then compare the request / response headers and the underlying rest api being invoked and compare it with the Azure CLIs request / response headers.

**Comment by Alexandru-Postescu** [comment]
@navba-MSFT thank you. I was able to retrieve the effective routes from the body by using runtime.WithCaptureResponse():
`ctxWithResp := runtime.WithCaptureResponse(ctx, &rawResponse)`. The response from the az cli is the same as the body.

**Comment by navba-MSFT** [comment]
@Alexandru-Postescu Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
