### ISSUE TITLE
How to create Private Link Service & Private Endpoints (dynamically) ?

### ISSUE THREAD

**Issue by swapnild2111** [Azure/azure-sdk-for-go#19949]
Hello Team,
I have been looking through sdk go language examples to find how to create private link service and private endpoints. Could not find anything... Can you please help?

Private link service - did not find any examples
Private endpoints - I have a scenario where user inputs names and I need to create private endpoint dynamically. I could find couple of functions for each resources individually like postgress etc but am not sure how to decide it dynamically.

Awaiting reply.

**Comment by jhendrixMSFT** [comment]
Are you looking for these?
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/network/armnetwork/privateendpoints_client.go
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/network/armnetwork/privatelinkservices_client.go

**Comment by swapnild2111** [comment]
Awesome, was looking exactly for this! Thank you very much :)
