### ISSUE TITLE
legacy SDK - BotService needs regenerate to include breaking changes from Swagger

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#19944]
### Service Package Request

Breaking changes are introduced in: https://github.com/Azure/azure-rest-api-specs/pull/22077/files#diff-1a1e934f09320fd0a63bb514460cb21c92fc67bcedb9b470d83a00e28e64c706L2046. While the current SDK is still generated from a commit prior to https://github.com/Azure/azure-rest-api-specs/pull/22077. There needs a regenerate for those existing versions.

At least, the 2021-05-01-preview is impacted for terraform users.

@tadelesh I saw you [approved this breaking change](https://github.com/Azure/azure-rest-api-specs/pull/22077#event-8197433237), do you think it makes sense to always update the impacted packages accordingly, to make the SDK up to date?

**Comment by tadelesh** [comment]
We have officially announced the deprecation of previous version of Go SDK. We strongly encourage customer to migrate to the new version of Go SDK. Any further release of previous version of Go SDK will be limited within security fix or high business impact requirements.
