### ISSUE TITLE
Azure CLI vs Go SDK generates different result for Compute Disk

### ISSUE THREAD

**Issue by djuneja-uptycs** [Azure/azure-sdk-for-go#19951]
### Bug Report

- Import package: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4`
- SDK Version:  `v4.0.0`
- Go version being used: `1.19.3`
- Azure CLI version used to compare data: `2.44.1`

#### Description
  * We have our automation fromework dependent on Azure CLI. We compare the Azure CLI response with the Azure Go SDK response.
  * We created a VM which resulted in implicit Disk creation as well. But when we are trying to fetch the resourceId information from the CLI, that is different from the information provided by SDK. Eg:
CLI response for resourceId:
`/subscriptions/8e3f6178-c684-46e2-a023-52168f1aeaee/resourceGroups/QA-AZ-WIN-DD/providers/Microsoft.Compute/disks/qa-az-windows10-1_OsDisk_1_984dbf8db66c4e70b4dc0b005831b672`
SDK response for resourceId:
`/subscriptions/8e3f6178-c684-46e2-a023-52168f1aeaee/resourceGroups/QA-AZ-WIN-DD/providers/Microsoft.Compute/disks/qa-az-windows10-1OsDisk1984dbf8db66c4e70b4dc0b005831b672`

in the above examples, the resourceId output is completely different.
  * In many cases we have seen that even the `resourceGroup` information for Compute Disk is different for CLI vs SDK.

#### Expectation?
  * The expectation was to have similar output pattern in case of CLI and SDK

#### Steps to reproduce?
  * Create a VM with Disk.
  * Run the CLI command to get the Disk information
  * Run the Go-SDK to get the same Disk information
  * Tally the output response.

**Comment by tadelesh** [comment]
@djuneja-uptycs Which SDK operation did you use and which property you used to get disk id? From my test, the SDK return of managedDisk id of osDisk is the same with the CLI.
