### ISSUE TITLE
Lack of Ha port in LoadBalancer

### ISSUE THREAD

**Issue by EtienneDeneuve** [Azure/azure-sdk-for-go#1996]
According to terraform azure rm provider the go SDK don’t support yet the new load balancer with HA Ports. 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/372

**Comment by jhendrixMSFT** [comment]
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ha-ports-overview

**Comment by jhendrixMSFT** [comment]
@seyadava do we have swagger for this yet?

**Comment by seyadava** [comment]
@anzaman I see you have committed some changes on Network specs. Can you weigh in on this? Or include people who can help?

**Comment by EtienneDeneuve** [comment]
Hi Guys,

In terraform we have made it working using the following :

From our side, we have successfully deployed a Azure Load Balancer with HA Ports with the following configuration :
```hcl
resource "azurerm_lb_rule" "lb_haports_rule" {
  backend_port = 0
  frontend_ip_configuration_name = "${azurerm_lb.private-lb-gateway.frontend_ip_configuration.0.name}"
  frontend_port = 0
  loadbalancer_id = "${azurerm_lb.private-lb-gateway.id}"
  name = "lb_haports_rule"
  protocol = "All"
  backend_address_pool_id = "${azurerm_lb_backend_address_pool.gateway_backend_pool.id}"
  probe_id = "${azurerm_lb_probe.lb_gateway_probe_fw.id}"
  resource_group_name          = "${var.resource_group_name}"
}
```

And it's working ! We simply add "All" in protocol.

Maybe there's nothing to code in go sdk.

**Comment by MikhailTryakhov** [comment]
As I can see in PS using protocols to "All" is expected scenario https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-configure-ha-ports

**Comment by jhendrixMSFT** [comment]
Sounds like this has been resolved so closing, please reopen as required.

**Comment by asubmani** [comment]
Request that this be re-opened. This was never fixed, the workaround suggested by @EtienneDeneuve does not work any more (it never really used HA ports). 
This should be fixed in the Azure Go SDK so that the provider maintainers can implement the fix for 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/372
