### ISSUE TITLE
[azservicebus] Expose an error type for unauthorized_client error

### ISSUE THREAD

**Issue by stigok** [Azure/azure-sdk-for-go#19966]
### Feature Request

Exposing actionable errors has both been discussed in https://github.com/Azure/azure-sdk-for-go/issues/17283 and partly implemented in https://github.com/Azure/azure-sdk-for-go/pull/17786. However, there is not a good way to detect whether the error is due to client credential errors.

The specific response of such an error is currently:
```
(connlost): ClientSecretCredential authentication failed
POST https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/token
--------------------------------------------------------------------------------RESPONSE 400 Bad Request--------------------------------------------------------------------------------
{
  "error": "unauthorized_client",
  "error_description": "AADSTS700016: Application with identifier '<app id>' was not found in the directory '<tenant id>'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: <trace id>\r\nCorrelation ID: <correlation id>\r\nTimestamp: 2023-02-07 20:32:58Z",
  "error_codes": [
    700016
  ],
  "timestamp": "2023-02-07 20:32:58Z",
  "trace_id": "<trace id>",
  "correlation_id": "<correlation id>",
  "error_uri": "https://login.microsoftonline.com/error?code=700016"
}
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#client-secret
```

When using the blob clients I have access to the errors through [`bloberror.HasCode`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/bloberror/error_codes.go#L18), which works pretty good.

I guess I miss a `CodeUnauthorizedClient` exposed here, or an equivalent.

**Comment by richardpark-msft** [comment]
Sorry @stigok, I didn't see this issue until just now.

Can you give me an idea of what you would do with this error if you could distinguish it from other errors? Generally it seems like errors like this have to be reviewed by a human to rectify.

**Comment by stigok** [comment]
I can see now that this issue isn't as clear as it could be. We are generating ephemeral service accounts using Vault. These credentials are rotated on set intervals. If I could catch authentication errors like this it could signal a recreation of the Service Bus client, using a fresh set of credentials.

After some more time has passed here, I think the error you see here is due to the newly created ephemeral credentials not having propagated to Azure's authentication servers yet, hence the _Application with identifier '<app id>' was not found in the directory_ error. It seems that when the credentials have expired, no errors at all are bubbling up from the ServiceBus client, but the calls to `ReceiveMessages` just hangs forever. To work around this, I can pass a `context.WithTimeout`.

**Comment by richardpark-msft** [comment]
Ah, okay, sounds like there's two issues:

1. (small) FEATURE REQUEST: Can I distinguish "credential expired" using something similar to what we do for LockLost [example](https://github.com/Azure/azure-sdk-for-go/blob/4ba48a3ef868bd34b5424041e56b2d187f34a3a1/sdk/messaging/azservicebus/example_receiver_test.go#L104). Your use case sounds perfectly valid to me.
2. BUG: ReceiveMessages doesn't return, even after credentials have expired. This shouldn't happen. 

I'll take a look at both of these on Monday. Thank you for getting back to me.

**Comment by richardpark-msft** [comment]
Just a little background:

Your issue was somewhat interrelated with another issue with SAS tokens, which also have a lifetime/expiration. Now both that code path and yours will return a azservicebus.Error (as of the next release), which is great.

If you want to peek under the hood, you can turn on debug logging for azservicebus [link](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/README.md#logging). We log what our token refreshes look like, how long they should be valid for, etc..., which can help trace issues like this if it's related to expiration.

Example:

```text
2023/03/22 14:05:16 [Authentication] *azidentity.AzureCLICredential.GetToken() acquired a token for scope https://servicebus.azure.net//.default
2023/03/22 14:05:16 [azsb.Auth] (queue-174ED9BBF0DDDCA1/$management) negotiate claim, token expires on 2023-03-22T15:25:29-07:00
2023/03/22 14:05:16 [azsb.Auth] negotiating claim for audience amqps://<host>/queue-174ED9BBF0DDDCA1/$management with token type jwt and expiry of 1679523929
```
