### ISSUE TITLE
Feature request: Need a Batch API to Fetching the details of a set of VMs

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#19968]
https://github.com/Azure/azure-sdk-for-go/blob/9adda3e39ec3fea73c0a66390ae88f13ec7e6859/sdk/resourcemanager/compute/armcompute/zz_generated_virtualmachines_client.go#L515

**Comment by xqi-aviatrix** [comment]
For now, the sdk only has this Get API to fetch details of a single vm

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Could you please check and let me know if the below sample helps ?

```
package main

import (
    "context"
    "fmt"
    "log"

    "github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute"
    "github.com/Azure/azure-sdk-for-go/arm/compute"
)

func main() {
    // Create a new virtual machines client
    vmClient := compute.NewVirtualMachinesClient(<subscription_id>)

    // Define a list to hold the virtual machine details
    var vmList []compute.VirtualMachine

    // Define a context
    ctx := context.Background()

    // Define a list of resource group names
    resourceGroupNames := []string{"resourceGroup1", "resourceGroup2", "resourceGroup3"}

    // Iterate through the resource group names
    for _, resourceGroupName := range resourceGroupNames {
        // Define a list of virtual machine names
        vmNames := []string{"vm1", "vm2", "vm3"}

        // Iterate through the virtual machine names
        for _, vmName := range vmNames {
            // Get the virtual machine details
            vm, err := vmClient.Get(ctx, resourceGroupName, vmName, "")
            if err != nil {
                log.Fatalf("Error getting virtual machine: %v", err)
            }

            // Append the virtual machine details to the list
            vmList = append(vmList, vm)
        }
    }

    // Print the virtual machine details
    for _, vm := range vmList {
        fmt.Printf("Name: %s\n", *vm.Name)
        fmt.Printf("Resource Group: %s\n", *vm.ResourceGroup)
        fmt.Printf("Location: %s\n", *vm.Location)
        fmt.Printf("Size: %s\n", *vm.HardwareProfile.VMSize)
```

**Comment by xqi-aviatrix** [comment]
Hi @navba-MSFT , thanks for the code sample. If this vmNames contains 7 vms, the code above will make 7 rest calls which is inefficient. what I ask is to have an API, for example GetVms, which takes vmNames as the parameter and return all the 7 vms in a single API call

**Comment by navba-MSFT** [comment]
@xqi-aviatrix You can leverage the below sample code which uses resource graph to send a single request (API call) to fetch the VM details and get the response.

```
package main

import (
	"context"
	"fmt"
	"log"
	"strconv"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph"
)

func main() {

	// To configure DefaultAzureCredential to authenticate a user-assigned managed identity,
	// set the environment variable AZURE_CLIENT_ID to the identity's client ID.

	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}

	ctx := context.Background()
	// Create and authorize a ResourceGraph client
	client, err := armresourcegraph.NewClient(cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}

	// Create the query request, Run the query and get the results
	results, err := client.Resources(ctx,
		armresourcegraph.QueryRequest{
			Query: to.Ptr("Resources | where type =~ 'Microsoft.Compute/virtualMachines' and name in ('VM1', 'VM2', 'VM3') | project name, type, location, properties"),
			Subscriptions: []*string{
				to.Ptr("1234-5678-1234-123456")},
		},
		nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	} else {
		// Print the obtained query results
		fmt.Printf("Resources found: " + strconv.FormatInt(*results.TotalRecords, 10) + "\n")
		fmt.Printf("Results: " + fmt.Sprint(results.Data) + "\n")
	}

}

```
Please update the VM names and the subscription id in the above sample. Hope this helps.

**Comment by xqi-aviatrix** [comment]
thanks for the sample. That works for the vms, but how about vmss vms? VirtualMachineScaleSetVMsClient only supports Get call but Azure resource group does not support vmss vm yet. pls refer to [https://learn.microsoft.com/en-us/answers/questions/1060604/azure-resource-graph-explo[…]query-virtual?page=1&orderBy=Helpful&comment=answer-1063629](https://learn.microsoft.com/en-us/answers/questions/1060604/azure-resource-graph-explorer-how-to-query-virtual?page=1&orderBy=Helpful&comment=answer-1063629#newest-answer-comment)

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Thanks for getting back. You can leverage the [same above sample](https://github.com/Azure/azure-sdk-for-go/issues/19968#issuecomment-1427676298) but change the query as below:

> **Query: to.Ptr("Resources | where type =~ 'Microsoft.Compute/virtualMachineScaleSets' | project name, type, location, properties"),**

This should serve the purpose.

**Comment by xqi-aviatrix** [comment]
> @xqi-aviatrix Thanks for getting back. You can leverage the [same above sample](https://github.com/Azure/azure-sdk-for-go/issues/19968#issuecomment-1427676298) but change the query as below:
> 
> 
> 
> > **Query: to.Ptr("Resources | where type =~ 'Microsoft.Compute/virtualMachineScaleSets' | project name, type, location, properties"),**
> 
> 
> 
> This should serve the purpose. 
> 
> 

This is to quote Vmss not vmss vms

**Comment by navba-MSFT** [comment]
@xqi-aviatrix For the Flex orchestration mode of VMSS the instance view is not supported. However, I was able to test with the below query that looks for virtual machine scale set resources and gets various details including the virtual machine size and the capacity of the scale set. The query uses the toint() function to cast the capacity to a number so that it can be sorted. 

Finally, the columns are renamed into custom named properties.

> **Query: to.Ptr("Resources | where type=~ 'microsoft.compute/virtualMachineScaleSets' | where name contains 'MyNodePoolVMName' | project subscriptionId, name, location, resourceGroup, Capacity = toint(sku.capacity), Tier = sku.name | order by Capacity desc"),**

**Comment by xqi-aviatrix** [comment]
> @xqi-aviatrix For the Flex orchestration mode of VMSS the instance view is not supported. However, I was able to test with the below query that looks for virtual machine scale set resources and gets various details including the virtual machine size and the capacity of the scale set. The query uses the toint() function to cast the capacity to a number so that it can be sorted.
> 
> Finally, the columns are renamed into custom named properties. So leverage [the same above sample](https://github.com/Azure/azure-sdk-for-go/issues/19968#issuecomment-1427676298) but change the query as below:
> 
> > **Query: to.Ptr("Resources | where type=~ 'microsoft.compute/virtualMachineScaleSets' | where name contains 'MyNodePoolVMName' | project subscriptionId, name, location, resourceGroup, Capacity = toint(sku.capacity), Tier = sku.name | order by Capacity desc"),**

Thanks for the details, but this query is to get the vmss info but not vmss vms.  vmss and vmss vm are two diferent resources in Azure.

Through [VirtualMachineScaleSetVMsClient](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute@v1.0.0#NewVirtualMachineScaleSetVMsClient) we can get each vmss vm's instance view by using the Get call sequentially. It will be great if VirtualMachineScaleSetVMsClient can support GetVms to get multiple vmss vms' instance view in one API call

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Thanks for your reply. As mentioned above, If you are using VMSS Flex mode then this [**doesn't** support instance view](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes#autoscaling-and-instance-orchestration). 

As there is not currently a way to get full instance view of Azure VMs. VMSS Uniforms had some internal simplifications that made it possible, but it was not possible to port that to VMSS Flex. The long term plan is to support getting instance view information at scale via **Azure Resource Graph.** 

In the meantime, the only workarounds is to	Use Get VM Instance View API on each individual VM instance.

**Comment by xqi-aviatrix** [comment]
@navba-MSFT thanks for the answers. I have no more question, so close this issue
