### ISSUE TITLE
Missing Primary Attribute for InterfaceIPConfigurationPropertiesFormat

### ISSUE THREAD

**Issue by thetonymaster** [Azure/azure-sdk-for-go#1997]
**InterfaceIPConfigurationPropertiesFormat** is missing the Primary Attribute for the 2017-03-09, profile. The request fails if this attribute is not set.

**Comment by bganapa** [comment]
linked issue https://github.com/Azure/azure-rest-api-specs/issues/2578
This needs change in the swagger spec of network version 2015-06-15

**Comment by knithinc** [comment]
This is because the "Primary" property is not present in the REST Spec for NRP API version 2015-06-15 which is in the 2017-03-09 Profile.  We'll submit a PR to fix the spec.

**Comment by jhendrixMSFT** [comment]
This is fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v17.3.0
