### ISSUE TITLE
Blob Client doesn't parse blob base URLs correctly and fails to connect

### ISSUE THREAD

**Issue by guliyevemil1** [Azure/azure-sdk-for-go#19989]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`

github.com/Azure/azure-sdk-for-go/tree/main/sdk/azcore/runtime

- SDK version e.g. `master`, `latest`, `18.1.0`

main

  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.

3c862202e0142047b7621d5505d64a3756ca6e73

- output of `go version`
go version go1.19.5 darwin/arm64

- What happened?
Can't download stream with Azure Blob client, because it thinks the blob URL is missing a Host

`no Host in request URL`

- What did you expect or want to happen?
I would have expected it to parse the URL correctly

- How can we reproduce it?
I think, based on the way the code has been written, it shouldn't work on macOS or Linux (I can't say about Windows), because you are using `path.Join` which removes the double slash that we see in URLs `https://www.example.com`

- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Can you please provide a snippet of the API you're calling and the parameters that are causing it to fail?

**Comment by guliyevemil1** [comment]
I think it should fail on Linux/macOS with any URL as input. I didn't save my code, so I don't have a snippet handy.

**Comment by vibhansa-msft** [comment]
Version of azblob you are using is couple of months old. Recently we have done a GA of 'azblob' package. Kindly upgrade and validate. If issue persists, it will be helpful if you can share your code snippet that experience the issue or the location where you see filepath.join() in SDK creates the problem.
