### ISSUE TITLE
Increase live test operation coverage for 20 core RPs to 60%+ in mgmt. SDK

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#19987]
@Alancere Please update the status in this issue's comment.
Refer: https://chenjieshistorage.z13.web.core.windows.net/mgmtReport.html

**Comment by Alancere** [comment]
| mgmt | coverage | pr link |
|---|---|---|
| armcompute | 33.1% | https://github.com/Azure/azure-sdk-for-go/pull/20048 |

**Comment by lirenhe** [comment]
Some challenges by leveragijng dotnet recording => test scenario => go live test.

**Comment by lirenhe** [comment]
5 services completed including 2 PRs not merged.  Please focus on the operation coverage

**Comment by Alancere** [comment]
mgmt report: https://chenjieshistorage.z13.web.core.windows.net/mgmtReport.html

**Comment by lirenhe** [comment]
60% of average coverage.
