### ISSUE TITLE
Need Help: Which Client I should use to Receive Events from Eventhub 

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#19991]
https://github.com/Azure/azure-sdk-for-go/blob/bccc40e7da832c0e06e9c863b33e7698d00dc7e8/sdk/resourcemanager/eventhub/armeventhub/zz_generated_eventhubs_client.go#L28

I found some samples on https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-go-get-started-send#receive-events
but they are not using the sdk under resourcemanager

**Comment by jhendrixMSFT** [comment]
For sending/receiving events from Event Hubs you want the [`azeventhubs`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs) module.

The `armeventhub` module is for managing Event Hubs (creation, deletion etc).  Generally speaking, modules with the `arm` prefix are for Azure Resource Management.

**Comment by xqi-aviatrix** [comment]
thanks for the quick reply!
