### ISSUE TITLE
[azidentity] Make env var constants public

### ISSUE THREAD

**Issue by mblaschke** [Azure/azure-sdk-for-go#19999]
### Feature Request

I'm wondering why these azidentity constants are private, so I'm asking to make them public so they can be used in applications:

```go
const (
	azureAuthorityHost             = "AZURE_AUTHORITY_HOST"
	azureClientCertificatePassword = "AZURE_CLIENT_CERTIFICATE_PASSWORD"
	azureClientCertificatePath     = "AZURE_CLIENT_CERTIFICATE_PATH"
	azureClientID                  = "AZURE_CLIENT_ID"
	azureClientSecret              = "AZURE_CLIENT_SECRET"
	azureFederatedTokenFile        = "AZURE_FEDERATED_TOKEN_FILE"
	azurePassword                  = "AZURE_PASSWORD"
	azureRegionalAuthorityName     = "AZURE_REGIONAL_AUTHORITY_NAME"
	azureTenantID                  = "AZURE_TENANT_ID"
	azureUsername                  = "AZURE_USERNAME"

	organizationsTenantID   = "organizations"
	developerSignOnClientID = "04b07795-8ddb-461a-bbee-02f9e1bf7b46"
	defaultSuffix           = "/.default"
	tenantIDValidationErr   = "invalid tenantID. You can locate your tenantID by following the instructions listed here: https://docs.microsoft.com/partner-center/find-ids-and-domain-names"
)
```

source: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/azidentity.go#L29

**Comment by chlowell** [comment]
> I'm wondering why these azidentity constants are private
> 

The environment variable constants are private because they're typically used to configure applications externally, for example in Kubernetes manifests, and they're easy to copy from the [package documentation](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#EnvironmentCredential). So, they've seemed more like clutter than useful public API. Can you describe your use case for setting them programmatically?

**Comment by mblaschke** [comment]
to avoid having fixed strings and use constants in applications :)

**Comment by chlowell** [comment]
But what does your application do with them? I'm curious about your scenario because to me it seems unusual for application code to read or set these variables. `azidentity` reads them where appropriate and they're typically set outside the application.

**Comment by mblaschke** [comment]
eg for msgraph-sdk-for which doesn't use azidentity so i have to read environment variables to setup azure environment support.

fine if you want to hide them and just keep them in documentation, just though it might be a good idea to keep them public as i don't see a reason to hide them.

**Comment by jhendrixMSFT** [comment]
I don't want to derail the conversation, but which msgraph SDK are you using?  If it's [this one](https://github.com/microsoftgraph/msgraph-sdk-go), there is support for `azidentity`.

**Comment by mblaschke** [comment]
Yes I'm talking about this sdk and yes it's using azidentity but without the automatic Azure environment configuration. If you want AzureChina support you have to do all the stuff in your applications.

My idea was to use constants and was wondering why you're setting these as private and if there is a reason for it. Avoiding typos, having autocompletion instead of digging through the documentation, getting the list of available environment variables which azidentity uses etc.

**Comment by jhendrixMSFT** [comment]
I see, thanks for clarifying.  Maybe we need to improve support for non-public clouds via env config (presumably this would alleviate the need for the constants to be exported, and also make it easier on SDK users to use non-public clouds).

Generally speaking, we try to export the minimum viable public surface area.  We do this mainly for versioning tolerance; once it's public, we can't change/remove it as we don't want any breaking changes.  This allows us to add/export it later if consumers ask for it (i.e. you can always add it later, but you can't take it back).

**Comment by chlowell** [comment]
Thank you for taking the time to propose and discuss this. I'm marking the issue addressed because at this time we don't plan to export these constants, but please feel free to continue the discussion here if you have more to add. For my part, I believe exporting these constants would be convenient for your scenario, however it doesn't strictly require them and I'm not certain this is a common scenario.
