### ISSUE TITLE
Improved block blob Upload function for io.Reader in azblob

### ISSUE THREAD

**Issue by patrickrad** [Azure/azure-sdk-for-go#20011]

**Comment by patrickrad** [comment]
module: azblob
branch: main

For an application that wants to upload a block blob based on the data from an io.Reader there is only one function to use, azblob.UploadStream() There are however two drawbacks with this function:

1) It will do a memory copy on all data in underlying function calls, blockblob/chunkwriting.go: copyFromReader()

2) copyFromReader uses multiple block list uploads. This costs more in dollar and cents compared to a single blob upload and is therefore highly undesirable.

For applications with an io.Reader of unknown size this API might be necessary. But if you do know the size of the io.Reader, an API similar to the internal function blockblob/client.go: uploadFromReader() would be beneficial and would solve both problems mentioned above.

I therefore wonder if it would be possible to add a function similar to  blockblob/client.go:uploadFromReader() at the azblob level (in client.go)?
One could maybe even argue that such a function could replace both UploadFile() and UploadBuffer since the application could simply create an io.Reader from the file or buffer.

**Comment by vibhansa-msft** [comment]
@patrickrad : azblob.UploadStream() takes a stream as input and hence it assumes the size of the stream is not known. As the size is not known it creates small chunks of data and upload them in parallel. If you already know the length of the stream, you can use other API like UploadBuffer().
For your second question on uploading multiple blocks, in case of UploadStream as size is not known it splits data into 1mb buffer by default. However, while calling this api you can provide the blockSize as input and higher blockSize means less number of calls to putBlock.

**Comment by patrickrad** [comment]
Hi @vibhansa-msft 

Using UploadBuffer will force a new memory allocation of a buffer of the same size as the reader, plus a memory copy to fill that buffer
Looking in copyFromReader() function it looks like the same will be happening for UploadStream, i.e. extra memory buffer(s) being allocated and then the reader being copied in.

Both these approaches will thus double the memory requirements plus force a memory copy of all the data. This might not matter for small amounts a data but will become a problem when the amount of data grows, especially on systems with limited memory and CPU resources (as is the case with my system).

Instead, with just two functions I think an application could have all it really needs and without any unnecessary extra memory allocations and copying needed:
- UploadStream(), for readers of unknown size (just like it works today)
- UploadReader, for readers with a know size.

Current users of UploadBuffer and UploadFile could use UploadReader instead by simply creating the io.Reader themselves from their buffer/file.

**Comment by jhendrixMSFT** [comment]
@patrickrad part of the reason why we perform a copy in `UploadStream()` is because internally, we require the HTTP request body to be an `io.ReadSeeker`; this is to support retries when the HTTP request fails (we seek back to the beginning and try again).  So even if we had an API that accepted just an `io.Reader`, we'd still need to make a copy to support seeking (early on we had a version that required an `io.ReadSeeker` but we got a lot of complaints on the `io.Seeker` requirement).  We might be able to elide this by checking if the underlying type implements the `io.Seeker` interface.

**Comment by patrickrad** [comment]
@jhendrixMSFT , yes my reader would be an io.ReadSeeker. In my current use case the reader is an open file with an offset. In future versions I might want to wrap a ReaderSeeker around mutlple files (with an offsets in each)

I see the problem with retries and I think because of that it is perfectly fine to do a copy if you don't know the size or only have a reader. But still, would having two functions not be enough anyway?

* UpladStream(), unkown size and an io.Reader as input
* UploadReader, known sizes and an io.ReadSeeker as input

Worst case, if there are those that for some reason have a reader of know size that can't be a ReadSeeker there could be an
UploadReaderSeeker function I guess. Maybe bit of an over kill though

An important note about a potential UploadReader though. If during retries you need to seek back, it is important to seek to the position the reader was at to begin with, not to 0

**Comment by jhendrixMSFT** [comment]
We are very judicious when it comes to adding new APIs.  In this case, my concern is that there's a lot of overlap between UploadStream() and UploadReader() which might add confusion, especially since they almost do the same thing (not ruling it out, but we should explore other options first).

Have you looked at using the block blob [`Upload`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob#Client.Upload) method?  This would prevent copies of the data and multiple block problems stated earlier.  The seeking to non-zero would be a problem though, so you'd need to wrap it in something like an `io.SectionReader`.  Then use our [`streaming.NopCloser`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.4.0/streaming#NopCloser) to add an `io.Closer`.  Would something like this work?

**Comment by patrickrad** [comment]
I looked at block blob Upload but I don't understand why it closes the reader. Why would a library close my reader, it has no way of knowing if I want to use it more? Depending on how the application got the reader, it might not even be able to recreate it again. Closing readers (files) can also have side affects, only the application would know when this could be done.

I was also thinking about what you mentioned earlier about HTTP retries since this is what forces the seek part. I would not expect the library to do retries in the first place. If the HTTP request failed, why not simply tell the application and it can decide for it self if it should try again or not.

My overall feeling is that some of these upload functions are trying to be more helpful than necessary, the affect instead being that they are taking away control from the application thereby denying certain use cases. If you have a stream, i.e. a reader of unknown size, I think it makes more sense. I can then see why block lists are used and it makes sense to do HTTP retries of individual blocks to avoid failing the entire upload. But for a single block blob upload of a known size I can't see any reason why the library would need more than simply an io.Reader, its size and leave HTTP retries to the application. This would give the application full control and it would be able to handle any use cases without interference from the library.

**Comment by jhendrixMSFT** [comment]
Closing of the body comes from the underlying HTTP transport when processing the `*http.Request` (see the [doc comments](https://pkg.go.dev/net/http#Request) for `Request.Body`).  To prevent closure, wrap the reader in an [`io.NopCloser`](https://pkg.go.dev/io#NopCloser) or a [`streaming.NopCloser`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.4.0/streaming#NopCloser) to preserve the `io.Seeker`.

Client retries can be disabled via [`RetryOptions`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.4.0/policy#RetryOptions) when creating a client.  Set `MaxRetries` to -1.

**Comment by jhendrixMSFT** [comment]
Correct, it will never use block lists.

From the docs, the `Upload()` API is just a wrapper around the [put blob](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=azure-ad) REST endpoint.

**Comment by vibhansa-msft** [comment]
Closing this as a proper fix was suggested in the thread. Feel free to reopen in case this does not work for you.
