### ISSUE TITLE
Auto accept marketplace terms for VM image API is not working

### ISSUE THREAD

**Issue by praveenvaltix** [Azure/azure-sdk-for-go#20012]
### Bug Report

Import path: "github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering"
SKD version: github.com/Azure/azure-sdk-for-go v47.0.0
go version: go1.15.3 linux/amd64

- What happened?
Valtix has a VM image in Azure marketplace. Our software using customer's AD principals to create VM images in customer's VNets. These VM images are listed on Azure marketplace. Typically, customer has to execute a azure cli command to accept the terms before the first VM is deployed.
Azure CLI: 
az vm image terms accept --publisher valtix --offer datapath --plan valtix_dp_image --subscription subscription-id

We would like to automate this via our software to auto accept the terms. We enhanced the AD role to add these 2 actions.
Microsoft.Compute/register/action
Microsoft.MarketplaceOrdering/agreements/offers/plans/sign/

Following is the azure client code snippet for reference -

```
// autoAcceptImageTerms - auto accept terms
// this should be invoked only for marketplace images
func (s *AzureService) autoAcceptImageTerms(imageReference *compute.ImageReference) error {
	log.Printf("Auto accept terms and conditions for image %+v", imageReference)

	publisher := miscutils.String(imageReference.Publisher)
	offer := miscutils.String(imageReference.Offer)
	product := miscutils.String(imageReference.Sku)

	client, err := s.GetMarketplaceAgreementsClient()
	if err != nil {
		log.Printf("Error %v", err)
		return err
	}

	// sign the marketplace terms
	_, err = client.Sign(
		context.TODO(),
		publisher,
		offer,
		product,
	)

	if err != nil {
		log.Printf("Error %v", err)
		return err
	}

	log.Printf("Auto accept terms success")

	return nil
}

# the client above is from the following snippet
// GetMarketplaceAgreementsClient - get marketplace agreements client
func (s *AzureService) GetMarketplaceAgreementsClient() (*marketplaceordering.MarketplaceAgreementsClient, error) {
	client := marketplaceordering.NewMarketplaceAgreementsClient(s.subscriptionID)
	authorizer, err := s.GetAuthorizer()
	if err != nil {
		log.Printf("Error while getting authorizer %v", err)
		return nil, err
	}
	client.Authorizer = authorizer
	return &client, nil
}

```

When this method executed, we are seeing the following error (s) -

Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: 'XXX' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='valtix' offer = 'datapath', sku = 'valtix_dp_image', Correlation Id: 'XXX'.'"

failed auto registering Resource Provider: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Compute/register/action' over scope '/subscriptions/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials.". Original error: autorest/azure: Service returned an error. Status=<nil> Code="MissingSubscriptionRegistration" Message="The subscription is not registered to use namespace 'Microsoft.Compute'. 

- What did you expect or want to happen?
We expected the API to succeed. 

- How can we reproduce it?

- Anything we should know about your environment.

**Comment by navba-MSFT** [comment]
@praveenvaltix Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by lirenhe** [comment]
@praveenvaltix,  seems you are using the previous version of the SDK, could you try the latest one https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/marketplaceordering/armmarketplaceordering

**Comment by navba-MSFT** [comment]
@praveenvaltix I wanted to do quick follow-up to check if you had a chance to look at the above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@praveenvaltix I wanted to do quick follow-up to check if you had a chance to look at the suggestion in the above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by praveenvaltix** [comment]
Hi @navba-MSFT I will try this on a newer version shortly.

**Comment by navba-MSFT** [comment]
Sure @praveenvaltix . Please keep you posted with the updates.

**Comment by navba-MSFT** [comment]
@praveenvaltix Please let me know if you had any updates on this.

**Comment by navba-MSFT** [comment]
@praveenvaltix The action is currently pending on you to try with latest [armmarketplaceordering](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/marketplaceordering/armmarketplaceordering) package. Please feel free to reopen this thread, if you face any issues. We would be happy to help.
