### ISSUE TITLE
azblob "panic: runtime error: invalid memory address or nil pointer dereference" azblob.(*ContainerClient).ListBlobsFlat.func1(...)

### ISSUE THREAD

**Issue by andrePKI** [Azure/azure-sdk-for-go#20023]
### Bug Report

- import path of package 
 github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
 
- SDK version
0.4.1 (I think)
- output of `go version`
I'm sorry but I cannot run go myself

- What happened?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7398c8]

goroutine 103 [running]:
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.(*ContainerClient).ListBlobsFlat.func1({0xd509d8?, 0xc00012a740?}, {{{0xc0004702f0, 0xc0000b62e8, 0xc0004702e0, 0x0, 0x0, 0xc000c007b0, 0x0}, 0x0, ...}, ...})
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.4.1/zc_container_client.go:204 +0x28
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob.(*containerClientListBlobFlatSegmentPager).NextPage(0xc0006407e0, {0xd509d8, 0xc00012a740})
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.4.1/zz_generated_pagers.go:42 +0x1a6
mycomp.corp/openshift/harvester/pkg/azure.(*BlobStorageContainerClient).MapBlobs(0xc00003c070?, {0xd509d8, 0xc00012a740}, 0x1, 0xc00061cf00)
	/app/pkg/azure/storage.go:58 +0x9d
mycomp.corp/openshift/harvester/pkg/workers.QueueBlobsAsWorkItems({0xd509d8, 0xc00012a740}, 0x0?, 0xc000708ba0, 0x0?, 0x0?, {0xc00003c041, 0x12}, {0xc00003e029, 0x7})
	/app/pkg/workers/blobs.go:32 +0x18c
created by main.main
	/app/cmd/harvester/main.go:61 +0x6c5
```
The code runs fine with up to 150 blobs, after around 1700 blobs, it throws the above error. We don't think it is a shortage of memory,  the OpenShift pod in which it runs is not limited and does not use excessive or increasing memory (using 0.309 of 8.0 MiB, with limit of 256MiB).

- What did you expect or want to happen?
Just have the code run to completion

- How can we reproduce it?
```
...azblob.NewServiceClientWithSharedKey()
...svcClient.NewContainerClient()
....MapBlobs( ,, BlobMapper(),, )
```
`BlobMapper()` processes each blob in the container.

Run this on a storage account with a container holding at least 1700 items

- Anything we should know about your environment.

I did check the release notes of newer versions, but I don't see anything related. We will try to build the program using the latest version of azure-sdk-for-go (I am dependent on colleagues to do that for me) but I am afraid it will yield a similar error.
To me it occurs a nil-pointer reference on line 204 of sdk/storage/azblob@v0.4.1/zc_container_client.go

Hope this helps to fix it!

**Comment by jhendrixMSFT** [comment]
There has been some significant refactoring since this version of `azblob`.  Please try `v1.0.0` and let us know if the issue persists.
