### ISSUE TITLE
Need Help: Get metrics for all the Instances in a single Query

### ISSUE THREAD

**Issue by smit1682** [Azure/azure-sdk-for-go#20027]
Hello,

 I am doing a project on Monitoring Azure Services, In which I have to collect all metrics (CPU utilization, Number of total running VMs, etc.)
 
I am currently using the below client,

`client := insights.NewMetricsClient(context.GetStringValue(consts.ObjectAccountId))`

using this client and method:

`List(ctx context.Context, resourceURI string, timespan string, interval *string, metricnames string, aggregation string, top *int32, orderby string, filter string, resultType ResultType, metricnamespace string)`

I can retrieve metrics by specifying resourceURI

In resourceURI I have to give only one instance, so I can only retrieve one data.
(for example: resourceURI: subscriptions/....../vm1)

Can we get metrics for all the VMs in a single query?
If I only give resource group(resorce_group_1) and service(virtual machine), I need all metrics(CPU Percent) data for all the instances(vm_1,vm_2, etc).

(One way I found is to add **log analytics** agents and  try queries, but is there any other way using azure-sdk ?)

**Comment by navba-MSFT** [comment]
@smit1682 Thanks for reaching out to us and reporting this issue. You can leverage the Resource Graph query to send a **single request (API call) to fetch the VM details** and get the response. See the similar sample code [here](https://github.com/Azure/azure-sdk-for-go/issues/19968#issuecomment-1427676298). That sample ONLY shows the VM properties. 

Please note that you should update that sample code to fetch the CPU details instead.

Alternatively you can enumerate though all VMs and leverage [the metricclient package. ](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor#PredictiveMetricClient.Get)

**Comment by smit1682** [comment]
Hi @navba-MSFT , Thank you for the reply, I go through the **Resource Graph query** , but as I understand it only provides properties of the resource. (it has a Resource table, which contains all the properties-related data)

which can provide data about the total VMs available in resource group, location etc.
This table does not contain any performance-related data. (Avg CPU usage, Network in and out bytes, etc)

Suppose in Azure Service bus if we need the total number of service buses or the status of each service bus we can use Resource Graph query,
But Metric data like Open connections or Closed connections this data is not provided by any query.
(If there is any query for metric data please provide help with it)

So Is there any way to collect this metric data using any single API?

One way is (as you suggested) can enumerate through all service bus instances and collect all the individual data but it would be an inefficient way for more instances.

**Comment by navba-MSFT** [comment]
@smit1682 Thanks for your reply and clarifying your ask. The [monitor metrics List ](https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list?tabs=HTTP)API takes resource URI as the parameter. So you need to enumerate through each of the VM resource and gets its URI and get the metric value for each. There is no single API call which can get you the metrics for ALL VMs.

**Comment by gracewilcox** [comment]
From what it looks like you're doing, it is recommended to query metrics with the azquery module using [MetricsClient.QueryResource](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery#MetricsClient.QueryResource)

QueryResource does not support multiple resource URIs, so you would still need to make a separate call for each VM.

**Comment by navba-MSFT** [comment]
@smit1682 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@smit1682 If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by smit1682** [comment]
@navba-MSFT Thank you for your assistance.
All queries are resolved form my side.

Again thank you for you quick response.
