### ISSUE TITLE
May Encounter a bug setting StringContainsAdvancedFilter for Event Grid Subscription

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#20026]
https://github.com/Azure/azure-sdk-for-go/blob/5d69bfc657e607a324b568a4ecac0e1d22ead05d/sdk/resourcemanager/eventgrid/armeventgrid/zz_generated_models.go#L1608

**Comment by xqi-aviatrix** [comment]
I figured it out

**Comment by xqi-aviatrix** [comment]
I figure it out but may encounter a bug in Azure. Here are the code I use to create the filters

```
Actually I figure it out, but may find a bug in Azure

Here are the filters I set in program

```
AdvancedFilters: []armeventgrid.AdvancedFilterClassification{
					&armeventgrid.StringContainsAdvancedFilter{
						OperatorType: to.Ptr(armeventgrid.AdvancedFilterOperatorTypeStringContains),
						Key:          to.Ptr("data.resourceProvider"),
						Values: []*string{
							to.Ptr("microsoft.compute"),
							to.Ptr("microsoft.network"),
							to.Ptr("microsoft.resources"),
						},
					},
					&armeventgrid.StringContainsAdvancedFilter{
						OperatorType: to.Ptr(armeventgrid.AdvancedFilterOperatorTypeStringNotContains),
						Key:          to.Ptr("data.operationName"),
						Values: []*string{
							to.Ptr("microsoft.authorization/policies/auditifnotexists/action"),
							to.Ptr("microsoft.authorization/policies/audit/action"),
						},
					},
				},
```
But the Azure backend created the following filters


![Screenshot 2023-02-17 at 11 21 45 PM](https://user-images.githubusercontent.com/89810801/219847364-d5356973-3fbb-4fc2-8fcb-11a5098be9f5.png)


Due to limitation, I cannot create an Azure support ticket.

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Thanks for reaching out to us and reporting this issue.
