### ISSUE TITLE
[armmonitor] ListAtSubscriptionScope missing in new management package

### ISSUE THREAD

**Issue by jkroepke** [Azure/azure-sdk-for-go#20039]
### Feature Request

I'm currently using 

https://github.com/Azure/azure-sdk-for-go/blob/2187aca40bbf6931ffac666977e5d29128d82585/services/preview/monitor/mgmt/2021-05-01-preview/metrics/metrics.go#L195

to fetch multiple metrics from Azure Monitor using 1 REST call. 

This API is only available at `2021-05-01-preview`.

I also tried to do the REST call with normal List call

```
res, err := client.List(ctx, "subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a", &armmonitor.MetricsClientListOptions{
			Timespan:        to.Ptr("PT1M"),
			Interval:        to.Ptr("PT1M"),
			Metricnames:     to.Ptr("Available Memory Bytes"),
			Aggregation:     to.Ptr("average"),
			Top:             to.Ptr(int32(10)),
			Orderby:         nil,
			Filter:          to.Ptr("Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-win' or Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-linux'"),
			ResultType:      nil,
			Metricnamespace: to.Ptr("microsoft.compute/virtualmachines"),
		})
```

but it errored with `ApiVersion: 2018-01-01 does not support query at non Arm resource Id level`

How I could use a preview api with https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/monitor/armmonitor ?

Can I manually change the used ApiVersion in that rest call?

**Comment by jkroepke** [comment]
It seems like this is NOT a preview feature, since its in 2021-05-01.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-05-01/metrics_API.json#L40

Can the referenced Api version in https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/monitor/armmonitor bumped from 2018-01-01 to 2021-05-01?

**Comment by tadelesh** [comment]
When you create the metrics client, you could specify the API version with options: 
```
client, err := armmonitor.NewMetricsClient(cred, &&arm.ClientOptions{ClientOptions: policy.ClientOptions{
	APIVersion: "2021-05-01",
}})
```

**Comment by jkroepke** [comment]
@tadelesh Thanks! What about add the SDK methods for API calls from newer API versions? Could that possible?

**Comment by tadelesh** [comment]
@jkroepke oh, I see. The new API version has some additional features. I'll contact with service team to ask for the new version.

**Comment by jkroepke** [comment]
@tadelesh I also raise a question here, if the default version can be bumped here (https://github.com/Azure/azure-rest-api-specs/issues/22716), then all SDKs should benefit from it

**Comment by jkroepke** [comment]
@tadelesh https://github.com/Azure/azure-rest-api-specs/issues/22716 is resolved now. Running the CodeGen should solve the issue now?

I'm not sure, if I'm looking at https://github.com/azure-sdk/azure-sdk-for-go/commit/889425043711befabb833fb48b91d87747d9517a, the older APIVersion is still in use.

**Comment by tadelesh** [comment]
The service team changed the tag used for generating SDK. I'll double check with them and I think the updated SDK will be released in March.

**Comment by tadelesh** [comment]
The_ new API version will be adapted into armmonitor@0.9.0 which I believe will be released no later than 24th, March.
