### ISSUE TITLE
[azcore] Create clients directly from a pipeline

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-go#20041]
### Feature Request

It would be helpful for the Track 2 SDKs to expose the ability for a client to be created directly from a pipeline for a few main reasons

In a large transfer AzCopy job, with repeated TokenCredentialPolicies we have experienced customers hitting client_request_loop errors due to refreshing the token too many times. https://github.com/Azure/azure-storage-azcopy/issues/1957 My understanding is that there are too many BearerTokenPolicies and they try to refresh all approximately around the same time close to the expiry. The AAD endpoint thinks the same client is refreshing the token and limits us thinking we are choosing not to use the refreshed token. 

One potential way to share a pipeline would be to use the existing NewXXXClient method on an existing client, but this is problematic for a couple reasons
1. A customer may only want multiple BlobClients (in the context of Azure Storage) so creating the ContainerClient is not useful
2. Customer logic could be generic and apply across multiple services (ex: AzCopy has generic logic for blob, file share, datalake services)
3. It is inconvenient to carry around multiple credential types and have repeated switch statements to create any given type of client based on the credential type.

**Comment by jhendrixMSFT** [comment]
Regarding the too many refreshes, I've separated that into https://github.com/Azure/azure-sdk-for-go/issues/20044

**Comment by jhendrixMSFT** [comment]
Per discussion, there is no longer a need for this functionality.
