### ISSUE TITLE
Sharing a TokenCredential shouldn't result in excessive refresh requests

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#20044]
If N clients are sharing the same `azcore.TokenRequest` with the same scopes, when the token needs to be refreshed, it should only happen once, not once per client.

This might already be the case today, but needs confirmation and possibly documentation.

**Comment by chlowell** [comment]
Closed by #20367, first released in azidentity v1.3.0-beta.4
