### ISSUE TITLE
Default behaviour of SDK changed from 55.7.0 2020-06-01 to V67.0 2022-05-01

### ISSUE THREAD

**Issue by pmatety** [Azure/azure-sdk-for-go#20042]
Hi

Recently upgrade Azure SDK version from 55.7.0 2020-06-01 to V67.0 2022-05-01, observed some changes in default behavior related to zone property in the regions where zones are supported.

https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support

In the regions mentioned in above Microsoft docs. When I create a public ip(PIP) resource using 55.7.0 2020-06-01, I see zones are auto populated on the pip resource on Azure portal, but when the same request is sent using V67.0 2022-05-01, I don't see zones are auto populated on the pip resource on Azure portal.

Can someone confirm the change in Azure backend with the latest SDK version. Find the attached images of PIP resources created with both the versions.
 
Package: compute
SDK version: Did an upgrade from 55.7.0/2020-06-01 to V67.0/2022-05-01

Thanks,
Prashanth.

![image](https://user-images.githubusercontent.com/20165472/220466090-e8c97f2a-7633-4e6f-91e6-aa32f41b7164.png)

![image](https://user-images.githubusercontent.com/20165472/220466261-3c9f820b-ae2a-4405-80e2-5c4018301dd3.png)

**Comment by yangzhufrank** [comment]
the issue may be related to the API behavior change.

![image](https://user-images.githubusercontent.com/97370106/220799300-5881dc28-d3fe-4010-978b-7c1f8f87b86f.png)

the new API(cx uses the version 2022-05-01) need specify the "zone" parameter.

**Comment by navba-MSFT** [comment]
@pmatety Thanks for reaching out to us and reporting this issue. Did you try specifying the `zone ` parameter and test with newer api-version ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@pmatety I wanted to do quick follow-up to check if you had a chance to look at the above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@pmatety The action is pending on you to try the above suggestion. Please feel free to reopen this thread. We would be happy to help.
