### ISSUE TITLE
generate 2018-03-01 profile

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#2027]
Please use https://github.com/Azure/azure-rest-api-specs/blob/master/profile/2018-03-01-hybrid.json to generate a new hybrid profile. Thanks!

**Comment by marstr** [comment]
The 2018-03-01 profile is a different enough beast, with the granularity set at Resource Types, that I'm not going to be able to get to this item until we tinker with the profileBuilder pretty significantly. I'm going to move this back into the backlog for now as blocked.

**Comment by jhendrixMSFT** [comment]
Fixed in the `latest` branch and will be included in the December release.
