### ISSUE TITLE
Length limitation of ApplicationID in TelemetryOption

### ISSUE THREAD

**Issue by RichardChen820** [Azure/azure-sdk-for-go#20289]
### Feature Request

When I was trying to add some specific information to the user-agent in the outgoing http request, I found there's 24 characters length limitation of ApplicationID in TelemetryOption.
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/policy/policy.go#:~:text=//%20It%20has%20a%20maximum%20length%20of%2024%20characters%20and%20must%20not%20contain%20any%20spaces.

Is there any special reason to have this limitation in Go SDK? Since I haven't seen such limitation in other languages.
Is it possible to support longer string, or even remove this restriction？

**Comment by jhendrixMSFT** [comment]
The restriction comes from our general Azure SDK [design guidelines](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy).  I believe the underlying goal is to prevent excessive growth of the User-Agent.

Can we get more information on how this restriction is problematic?

CC @JeffreyRichter

**Comment by RichardChen820** [comment]
Umm.. 24 characters seems too short. For example, if I want to add a telemetry information like `<application>/0.1.10-preview`, except the length which occupied by the version and forward slash, there's only 9 characters left can be used for describing my application, it is too short to put a clear, meaningful application information in it.

CC @zhenlan

**Comment by JeffreyRichter** [comment]
The ApplicationId is for customer usage; typically, an app using an Azure SDK. And, while it is for customer usage, it has minimal value as the value is stored by Azure services and is typically not readable by any customers.
If you are building an Azure SDK, then you do not use the ApplicationId field and therefore, this limit does not apply to you; the SDK version info will be in the user-agent string.
If you are a customer using this field, then you could use "<application>/0.1.10-p" and truncate "review". As I said, this string value isn't that useful to the customer anyway. It does let a service team know what apps (not SDKs) are calling into the service.
