### ISSUE TITLE
PATCH/dictionary change for Managed Identities

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#2028]
Verify that updates to managed identities are handled by a PATCH (and not PUT) operation.

cc @arluca

**Comment by joshgav** [comment]
@tombuildsstuff noticed you thumbs-upped this - could you help us prioritize by pointing us to your use case? are you using user-assigned identities in Terraform? Thanks!

**Comment by tombuildsstuff** [comment]
@joshgav sure, [we use MSI via the endpoints in the `adal` package](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/config.go#L286), so we're not touching these directly; but I wondered if this was an API change or an SDK change? I don't believe this'll affect us either way, but I wanted to be sure :)

**Comment by joshgav** [comment]
The details are that updating an identity should be a PATCH operation, which it already is in the Go SDK, see https://github.com/Azure/azure-sdk-for-go/blob/fbe7db0e3f9793ba3e5704efbab84f51436c136e/services/msi/mgmt/2015-08-31-preview/msi/userassignedidentities.go#L495, thus closing.

@tombuildsstuff as it turns out this is an internal update and there won't be an API or SDK change.

**Comment by tombuildsstuff** [comment]
@joshgav oh cool, thanks for confirming :)
