### ISSUE TITLE
feat(azcore-cloud): Support `AzureGermanCloud`

### ISSUE THREAD

**Issue by erezrokah** [Azure/azure-sdk-for-go#20293]
### Feature Request

The GO SDK supports 3 out of the 4 available cloud names:
https://github.com/Azure/azure-sdk-for-go/blob/29ba2147d093a47b1e0f50d4675c3494f013d3e4/sdk/azcore/cloud/cloud.go#L11

Would it be possible to add `AzureGermanCloud` too?
The Azure CLI supports it, see https://learn.microsoft.com/en-us/cli/azure/manage-clouds-azure-cli

**Comment by jhendrixMSFT** [comment]
We had this early on but removed it before GA as the German cloud closed last year.

https://learn.microsoft.com/en-us/previous-versions/azure/germany/germany-welcome

**Comment by erezrokah** [comment]
Ah, thanks did not know that. Will close this issue then 👍
