### ISSUE TITLE
[Monitor Query] Migrate to data plane metrics query API

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-go#20314]
As part of the migration away from the ARM API, we'll need to add API surface to support batch metrics queries. Up to 50 resource IDs in the same subscription and region can be queried in a single API call.

**Comment by lchelsmaersk** [comment]
Hey @scottaddie and @gracewilcox. We are super excited and can't wait to have the batch API available in the golang SDK!

**Comment by lchelsmaersk** [comment]
Hey @scottaddie. Is there an ETA for when the golang SDK will support the new Azure Monitor metrics batch API? My team has an application that makes heavy use of Azure Monitor, and would benefit from batched requests. While we could write our own implementation for interacting with the batch API, we are happy with the golang SDK and would like to use it for this use case as well.

**Comment by scottaddie** [comment]
@lchelsmaersk Thank you for your interest in this feature. We're busy discussing a couple design options with the architecture team. Late July to early August is our target for the initial Beta release that includes this feature.

**Comment by gracewilcox** [comment]
> Hey @scottaddie. Is there an ETA for when the golang SDK will support the new Azure Monitor metrics batch API? My team has an application that makes heavy use of Azure Monitor, and would benefit from batched requests. While we could write our own implementation for interacting with the batch API, we are happy with the golang SDK and would like to use it for this use case as well.

Hi @LasseHels! We released the first beta for metrics batch query yesterday. You can use this feature with azquery [v1.2.0-beta.1](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery@v1.2.0-beta.1).

**Comment by LasseHels** [comment]
@gracewilcox Thanks for letting us know! We will take a look 🎉.
