### ISSUE TITLE
Senders and Receivers do not respect context cancellation or default timeout

### ISSUE THREAD

**Issue by erinborders** [Azure/azure-sdk-for-go#20323]
### Bug Report
- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
- SDK version e.g. `master`, `latest`, `18.1.0`
azservicebus v1.2.0
- output of `go version`
<img width="346" alt="Screenshot 2023-03-02 at 12 04 50 PM" src="https://user-images.githubusercontent.com/48973620/222500360-c43359d1-de31-43d1-a5fa-71878a426dc3.png">

Not sure if has updates, but I've been noticing an issue where the SendMessages() and ReceiveMessages() methods don't respect the passed in context's timeout. 

For some background, I noticed that senders and receivers fail silently on initialization - if given the wrong fully qualified namespace or queue name, neither the client nor the sender/receiver return a failure. We only see failures when trying to send or receive messages from the queue. So I added logic to send nil messages, or receive 0 messages, upon initialization so that if the sender, receiver or client is created incorrectly, trying to enqueue or dequeue should return an error and let us know right away.

However, when unit testing this logic, we don't want to be waiting longer than we have to, especially when we know the queue in question doesn't exist - so I created a context with cancellation like so:
![Screenshot 2023-03-02 at 11 29 03 AM](https://user-images.githubusercontent.com/48973620/222496813-de43e6c3-2568-4b3c-9f49-0fed7c956923.png)
And passed it into our create receiver function:
![Screenshot 2023-03-02 at 11 29 13 AM](https://user-images.githubusercontent.com/48973620/222496921-a43d8315-0299-4b7f-bb0f-75a2bdc71a8b.png)
For reproduction purposes, I'm following [this example](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus@v1.2.0#Receiver.ReceiveMessages) from the docs:
![Screenshot 2023-03-02 at 11 28 27 AM](https://user-images.githubusercontent.com/48973620/222494644-909150b9-9d74-41b6-a5a1-23055b85e303.png)

However, the receive messages function does not respect the timeout I give it - as you can see here, it did eventually time out but only after 4x the original duration.
<img width="279" alt="Screenshot 2023-03-02 at 11 48 44 AM" src="https://user-images.githubusercontent.com/48973620/222497676-c4803a27-8bbe-4e4d-9977-577d516471f3.png">

This also suggests that the receiver is not respecting the default timeout of 60s mentioned [here](https://github.com/Azure/azure-sdk-for-go/issues/19630). The same is true for the send messages:
<img width="262" alt="Screenshot 2023-03-02 at 12 01 30 PM" src="https://user-images.githubusercontent.com/48973620/222500049-5097ef77-1619-449d-8f48-6148d382f560.png">

I'd like to be able to have these send/receive messages methods timeout after ideally a few seconds so that my tests aren't hanging any longer than necessary.

**Comment by erinborders** [comment]
Interestingly enough - the dead letter receiver does respect the given timeout. Creating a context with a timeout of a second causes the expected behavior in that the cancellation stops the receive messages method. Just something to note.

**Comment by richardpark-msft** [comment]
Hi @erinborders, I'll take a look.

> For some background, I noticed that senders and receivers fail silently on initialization - if given the wrong fully qualified namespace or queue name, neither the client nor the sender/receiver return a failure. We only see failures when trying to send or receive messages from the queue. 

This is normal since the clients are lazily initialized. We only start up the connection and links when you do an operation and that's the only time we can validate that the namespace you passed in actually exists.

They should have a reasonable timeout however. I probably have some spot where we're doing retries on a "fatal" error, so I'll see what's going on.

**Comment by imiller31** [comment]
@richardpark-msft is there any way to ping the queue to see if it exists without attempting to send a garbage "HealthCheck" message? It seems like a bad pattern to have to send a message to see if the queue exists.

We'd rather be able to fail fast before sending a message at all.

**Comment by richardpark-msft** [comment]
@erinborders, I was just trying this out and I'm not seeing the same behavior.

```go
cred, err := azidentity.NewDefaultAzureCredential(nil)
require.NoError(t, err)

client, err := NewClient("non-existent-namespace.servicebus.windows.net", cred, nil)
require.NoError(t, err)

// sender version, cancels within 2 seconds.

// sender, err := client.NewSender("hello", nil)
// require.NoError(t, err)

// ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
// defer cancel()

// err = sender.SendMessage(ctx, &Message{}, nil)
// require.NoError(t, err)

// receiver version, one I ran before this.

receiver, err := client.NewReceiverForQueue("hello", nil)
require.NoError(t, err)

ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
defer cancel()

messages, err := receiver.ReceiveMessages(ctx, 1, nil)
require.NoError(t, err)
require.Empty(t, messages)
```

There are some factors that might make a difference though, so we probably want to enable debug logging so we can see them:

https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus#logging

This'll give us a better idea of what the library is doing underneath.

**Comment by richardpark-msft** [comment]
@imiller31, clients being lazily-initialized is how all the Azure SDK clients work so we don't really have a way, apart from using them, that you can do what you're asking.

However, for Receivers you could just PeekMessages(), which is non-mutating and would help you do a connection check without having to receive any messages.

**Comment by erinborders** [comment]
Thank you, this solved my issue!
