### ISSUE TITLE
[Mgmt Plane][Go] Unblock Track 1 to Track 2 migration

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-for-go#20338]
- [ ] [Mgmt Plane][Go] fill in the gaps between Track 1 and Track 2
- [ ] [Mgmt Plane][Go] Improve the migration experience for customers moving from Track 1 to Track 2

**Comment by jhendrixMSFT** [comment]
Is there a detailed list that we're tracking for this?
