### ISSUE TITLE
Support bearer challenge for identity based managed disks

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#20355]
OAuth with managed disks, a special kind of page blob, needs to support bearer challenge.

**Comment by vibhansa-msft** [comment]
This goes in Identity package or azidentity alredy has the support and we need to add it to azblob sdk.

**Comment by jhendrixMSFT** [comment]
The bearer token policy has extensibility points for handling challenges.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/policy/policy.go#L136

Here's an example of how keyvault uses it.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/keyvault/internal/challenge_policy.go#L54-L55
