### ISSUE TITLE
Lack of Constants for consistent error messages

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/azure-sdk-for-go#20372]
### Feature Request
Working with the SDK and its errors there are a couple of operations where we are searching for a specific error code back from the api. 

```go
package errors

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
)

const (
	RESOURCE_NOT_FOUND = "ResourceNotFound"
)

func IsNotFoundErr(err *azcore.ResponseError) bool {
	if err == nil {
		return false
	}
	if err.ErrorCode == RESOURCE_NOT_FOUND {
		return true
	}
	return false
}
```
I, and many other projects spun of the SDK, manually declare the resource as a constant, but i feel this could be dangerous should you ever decide you want to change the contract of the api to return a different message, and leads to a lot of repeated code as seen below in my grep. 

I wonder if we could start adding the error codes as consts somewhere or maybe i searched the wrong place?

## Frequently mentioned in our code review for new reviewers people expect them in the SDK
No value from github.com/Azure/azure-sdk-for-go/sdk/azcore we can reference for this?

@[charliedmcb](https://github.com/charliedmcb) charliedmcb [yesterday]
Or better a function within the lib we can call to check if its a not found error

Author
@[Bryce-Soghigian](https://github.com/Bryce-Soghigian) Bryce-Soghigian [yesterday]
Seems the sdk is a bit inconsistent with this type of behavior, and how we export the consts
~/dev/azure-sdk-for-go (main) » rg "ResourceNotFound" bsoghigian@MacBook-Air
sdk/data/aztables/error_codes.go
28: ResourceNotFound TableErrorCode = "ResourceNotFound"
59: ResourceNotFound,

sdk/data/aztables/client_test.go
206: require.Equal(t, string(ResourceNotFound), httpErr.ErrorCode)

sdk/data/aztables/transaction_batch_test.go
378: require.Equal(t, string(ResourceNotFound), httpErr.ErrorCode)

sdk/azcore/internal/exported/response_error_test.go
426: "code": "ResourceNotFound",
434: if code != "ResourceNotFound" {
435: t.Fatalf("expected %s got %s", "ResourceNotFound", code)
439: "code": "ResourceNotFound",
447: if code != "ResourceNotFound" {
448: t.Fatalf("expected %s got %s", "ResourceNotFound", code)

sdk/messaging/azeventhubs/internal/blob/zc_service_client.go
116:// If the container is not found, a ResourceNotFoundError will be raised.

sdk/messaging/azeventhubs/internal/blob/zz_generated_blob_client.go
693:// return an HTTP status code of 404 (ResourceNotFound).

sdk/messaging/azeventhubs/internal/blob/zz_generated_constants.go
680: StorageErrorCodeResourceNotFound StorageErrorCode = "ResourceNotFound"
798: StorageErrorCodeResourceNotFound,

sdk/storage/azblob/service/client.go
141:// If the container is not found, a ResourceNotFoundError will be raised.

sdk/storage/azblob/client.go
118:// If the container is not found, a ResourceNotFoundError will be raised.

sdk/storage/azblob/internal/generated/zz_constants.go
579: StorageErrorCodeResourceNotFound StorageErrorCode = "ResourceNotFound"
697: StorageErrorCodeResourceNotFound,

sdk/storage/azblob/bloberror/error_codes.go
135: ResourceNotFound Code = "ResourceNotFound"

sdk/storage/azblob/internal/generated/zz_blob_client.go
708:// return an HTTP status code of 404 (ResourceNotFound).

This is what i get back from the grep. No one single standard place these consts are being exported, so for now this is what works.

@[tallaxes](https://github.com/tallaxes) tallaxes [2 minutes ago]
I was wondering about the same thing, and everybody else will too. Let's raise an issue?

**Comment by JeffreyRichter** [comment]
If we pick apart your grep results, I see this:

1. These files are defining ResourceNotFound constants and so I think we are providing what you're asking for:
sdk/data/aztables/error_codes.go 
sdk/messaging/azeventhubs/internal/blob/zz_generated_constants.go (code generated; not hand written)
sdk/storage/azblob/internal/generated/zz_constants.go (code generated; not hand written)
sdk/storage/azblob/bloberror/error_codes.go

2. These are test files and are using the ResourceNotFound constants (also what you're asking for?)
sdk/data/aztables/client_test.go 
sdk/data/aztables/transaction_batch_test.go

3. sdk/azcore/internal/exported/response_error_test.go we could use a constant here but it is also a test file - we could improve this one

4. These grep results are in comments, in generated code files (not hand-written code), and refer to ResourceNotFoundError; not ResourceNotFound - so I think these are not related to your request at all, right?:
sdk/messaging/azeventhubs/internal/blob/zc_service_client.go
sdk/messaging/azeventhubs/internal/blob/zz_generated_blob_client.go
sdk/storage/azblob/service/client. Go
sdk/storage/azblob/client. Go
sdk/storage/azblob/internal/generated/zz_blob_client.go

**Comment by Bryce-Soghigian** [comment]
@JeffreyRichter  my request isn't to update all of these, Its more to expose common constants we can use when using this client in our Resource Provider. 

I would like to be able to reference an SDK Constant or set of constants that I can use throughout our RP.

**Comment by JeffreyRichter** [comment]
I'm still having trouble understanding what your ask is exactly.
The error string that Azure services return are defined on a per-service basis. Some service might return "ResourceNotFound" and some other service might not. So, the error string constants are defined by each service. We could not possibly have constants for Azure ALL services in our azcore module. Plus, even if we could, we would not want to because then the set of possible error strings would not be scoped to a specific service and this would deteriorate the customer experience.

Your RP is its own service, and you can/should define constants for the error strings specific to your RP service and then use them in your RP code.

**Comment by Bryce-Soghigian** [comment]
I just want constants for the arm api response error codes, ResourceNotFound, OperationNotAllowed, etc

**Comment by Bryce-Soghigian** [comment]
we are building a node provisoner which will be a client of CRP. Can I message you on teams with a relevant pr that is still not publically available to give you more context?
