### ISSUE TITLE
[docs] Update https://aka.ms/azsdk/go to point to our packages page

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#20389]
Looks like every language redirects their aka.ms/azsdk/<lang> link to point to their packages page. We should do the same - today it just goes to our root-level repo readme to an anchor that doesn't even exist anymore.

Packages page: https://azure.github.io/azure-sdk/releases/latest/go.html

**Comment by RickWinter** [comment]
Updated the link
