### ISSUE TITLE
Refresh mgmt. packages to adapt new client factory feature

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#20385]
- [x] Update test generator to change example generation logic.
- [x] Update codegen and testgen version in eng sys.
- [x] Refresh all modules.
- [x] Update all readme to use new client factory to create clients.
- [x] Release all modules with new minor version.
- [x] Refresh all samples using new client factory.
- [x] Update get started and migration guide to use new client factory.
- [x] Update Sandeep's PR for MSDoc.

**Comment by lirenhe** [comment]
First round.
