### ISSUE TITLE
How to read all items from a container???

### ISSUE THREAD

**Issue by magom001** [Azure/azure-sdk-for-go#20393]
I am competely lost!

How, in the name of God, does one run a simple SQL query on a container???

There is `NewQueryItemsPager` but it requires a `PartitionKey`, which does not make ANY sense what so ever. I have a container with a single partition key '/id'. 

How am I supposed to get all available items with this API?

```go
	pk := azcosmos.NewPartitionKeyString("123")
	queryPager := clientsContainer.NewQueryItemsPager("SELECT * FROM c", pk, nil)

	for queryPager.More() {
		queryResponse, err := queryPager.NextPage(context.Background())
		if err != nil {
			log.Fatal("Error readin query response:", err)
		}

		for _, item := range queryResponse.Items {
			fmt.Printf("Received item: %s\n", string(item))
		}
	}
```

But what if I just want to get a list of items that satisfy a particular SQL query???

**Comment by ealsur** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/18578

You are describing a cross partition query. Those are not supported at the moment. See the linked issue.

**Comment by magom001** [comment]
@ealsur, I read the linked issue, I am not familiar with the inner working of the cosmos db, but I do not get it: if I use data explorer in azure, I can run a simple "SELECT * FROM blabla" and it outputs all items in a given container. Are we talking here about the same thing? If yes, maybe put it into the README to avoid duplicates of this in the future

**Comment by ealsur** [comment]
`SELECT * FROM bla` is a cross partition query. Yes, what Data Explorer is doing is performing a cross partition query and aggregating results across all partitions. Cross partition queries are not trivial. Yes, a `SELECT *` might sound simple, but as aggregations and other operations (like ORDER BY) are added, it becomes complex.

Not sure what you mean by including it on the README. The README and public godev docs include all supported operations, and for queries, the operations require a Partition Key, by definition they are single Partition Key queries.
