### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by tianon** [Azure/azure-sdk-for-go#204]
Do you think a `v1.3` (or more?) would be warranted, especially since #111 basically broke everything? :smile:

(It's also worth noting that `We currently do not have any releases yet.` is in `README.md`, but isn't exactly true anymore: https://github.com/Azure/azure-sdk-for-go/tags)

**Comment by ahmetalpbalkan** [comment]
@tianon yeah we started to break things **massively** after those tags. The docker-machine and docker-registry repos vendor one of those tags.

We'll be doing some 2.0 soon, please read my comment here for the current status: https://github.com/Azure/azure-sdk-for-go/issues/183#issuecomment-136931588

**Comment by tianon** [comment]
Heh, docker-registry is actually the very reason I'm here -- they currently pull in https://github.com/Azure/azure-sdk-for-go/commit/97d9593768bbbbd316f9c055dfc5f780933cd7fc, which comes after `v1.2` (https://github.com/docker/distribution/blob/7a305cc8cdf1427455fc7021e51629498332c965/Godeps/Godeps.json#L20-L23).

**Comment by tianon** [comment]
So do you want to keep this issue open as a clear pointer for folks looking for newer tag, or just close it?  I don't mind either way. :+1:

**Comment by ahmetalpbalkan** [comment]
Heh I just remembered that we had to take a hotfix due to a memory leak in the Blob Storage SDK. Are you having any issues with the vendored code in docker-registry right now?

Let's keep it open as a work item. Thanks for bringing this up.

**Comment by tianon** [comment]
Naw, I'm actually working on some Debian packaging, and was trying to figure out what to package.  From our conversation here, I think I'll just package a snapshot instead of 1.2 for now until 2.0 drops. :+1:

**Comment by ahmetalpbalkan** [comment]
@tianon if you're packaging docker registry, you should probably keep the same vendored commit number?

**Comment by tianon** [comment]
We only get one commit/snapshot for the whole of the Debian archive (regardless of which packages build-depend on it), which is why I was hoping for something more "sanctioned" than some random commit somewhere. :smile:

**Comment by tianon** [comment]
(So if that commit is pretty "decent", why not tag it as `v1.3` in the interim?)

**Comment by tianon** [comment]
FWIW, docker-machine is using https://github.com/Azure/azure-sdk-for-go/commit/515f3ec74ce6a5b31e934cefae997c97bd0a1b1e, which isn't even quite `v1.2` (https://github.com/docker/machine/blob/08208bd1415f26e5bc2e5339f002fb7954b70e50/Godeps/Godeps.json#L10-L14)

**Comment by ahmetalpbalkan** [comment]
We can do that but it doesn't help much other than docker-registry, which also works with the commit number for now. When we tag `v2.0`, I'll be bumping that as well.

The case with `docker-machine` is it nearly predates all the code that's currently in the repo. We basically rewrote all that. Historically, this SDK was created just for docker-machine, and it was pretty hacky. 

At some point in the future, I'll be bumping vendored versions in both and fix breaking changes.

**Comment by dhilton** [comment]
Is there a feel for when v2.0 might drop? Before christmas? Just trying to get a feel for when it's worth revisiting #183 and the cascade of features to Terraform and others upstream.

**Comment by brendandixon** [comment]
@dhilton The ARM portion of the SDK is bounded by how fast we can get good specs into the https://github.com/Azure/azure-rest-api-specs repository. We had a good start, but they've dragged a bit lately. We're looking into what's holding things up.

**Comment by ahmetalpbalkan** [comment]
We have tags now. Closing.
