### ISSUE TITLE
Publish events using managed identity to event grid topic

### ISSUE THREAD

**Issue by pradnyoday** [Azure/azure-sdk-for-go#20419]
Is there any way we can send the events to event grid topic by authenticating using manged identity?
If no, Can this be implemented?

We have tried authenticating via manged identity but, we found out no way to pass the credentials to the eventgrid client.
We need this feature so that we can authenticate to eventgrid in  multiple regions using the same managed identity.

**Comment by pradnyoday** [comment]
The adal package is deprecating by march end. Is this possible via azidentity?

**Comment by jhendrixMSFT** [comment]
We have an adapter for connecting credentials from `azidentity` to our legacy SDK.  While it doesn't support event grid key auth, it should in theory work with managed identity.

https://github.com/jongio/azidext/tree/master/go/azidext
