### ISSUE TITLE
Should there be a package called `Azure/azure-sdk-for-go/sdk/storage/azfile`?

### ISSUE THREAD

**Issue by chiyoi** [Azure/azure-sdk-for-go#20442]
### Service Package Request

I'm still using `Azure/azure-storage-file-go/azfile` but it doesn't support *Managed Identities* passwordless login method.

Should it be refactored to this repository like `azblob` and `azqueue`?

**Comment by souravgupta-msft** [comment]
Hi @chiyoi. Thanks for reaching out. We are currently working on adding the `azfile` package in the [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go) repo. Will keep you posted when we will do its preview.

**Comment by vibhansa-msft** [comment]
If you are looking for OAuth based authentication for Files then you have to wait for sometime. As of now we are building AzFile with STG78 compliance which does not support this feature, in later releases it will be ported to AzFile. We already have this item in our backlog so closing this from here.
