### ISSUE TITLE
Execute Stored Procedures in Azure Comsos DB

### ISSUE THREAD

**Issue by karunmotorq** [Azure/azure-sdk-for-go#20455]
### Feature Request

Is it possible as of now to run a stored procedure in a cosmos db collection from the SDK? If not what are the alternative methods?

**Comment by ealsur** [comment]
@karunmotorq Sproc executions are not support atm. You can use TransactionalBatch to define a set of operations to be executed as a single transaction unit in case the use case of the Sproc is to execute multiple related operations as one.
