### ISSUE TITLE
feat(storage-queues): Add support for getting a queue ACL in the new SDK

### ISSUE THREAD

**Issue by erezrokah** [Azure/azure-sdk-for-go#20476]
### Service Package Request

[`get-queue-acl`](https://learn.microsoft.com/en-us/rest/api/storageservices/get-queue-acl) is supported in the old queue client see:
https://github.com/Azure/azure-sdk-for-go/blob/8ba0f8054d505231ca97a35484c6e1fe371e6787/sdk/storage/azqueue/queue_client.go#L139

but not in the new one, see:
https://github.com/Azure/azure-sdk-for-go/blob/8ba0f8054d505231ca97a35484c6e1fe371e6787/sdk/resourcemanager/storage/armstorage/queue_client.go#L38

Are there plans in adding that method to the new client?

**Comment by jhendrixMSFT** [comment]
These two modules serve slightly different purposes.  The first module `azqueue` is the "data-plane" module used for [accessing data](https://learn.microsoft.com/rest/api/storageservices/queue-service-rest-api) within Azure storage queues.  The second module `armstorage` is the Azure Resource Manager module used for [managing the acquisition](https://learn.microsoft.com/rest/api/storagerp/) of queues and other storage resources.

Generally speaking, modules that have the prefix `arm` are for Azure Resource Management, and modules with the `az` prefix are the data-plane counterparts.

**Comment by erezrokah** [comment]
Ah, thanks for clarifying @jhendrixMSFT, looks like I mixed up the data plane SDK with the old `go-autorest` SDK.

It does appear that some `armstorage` resources do expose the policy, for example:
https://github.com/Azure/azure-sdk-for-go/blob/deba68cd6adccf7eaac3594af9d515d9e093b1eb/sdk/resourcemanager/storage/armstorage/models.go#L1631
https://github.com/Azure/azure-sdk-for-go/blob/deba68cd6adccf7eaac3594af9d515d9e093b1eb/sdk/resourcemanager/storage/armstorage/models.go#L3087

While the queue resource, requires an API call to the data plane:
https://github.com/Azure/azure-sdk-for-go/blob/deba68cd6adccf7eaac3594af9d515d9e093b1eb/sdk/data/aztables/client.go#L624

Is it possible to get some context to that difference? What should be expected to be under the "data-plane" and what should be expected to be under the resource management module?

**Comment by jhendrixMSFT** [comment]
That I don't know.

@vibhansa-msft do you know who can answer the above question?

**Comment by tasherif-msft** [comment]
@erezrokah the client you mentioned as "old" is actually our newest release of Azure Storage Queues. Please use that one. I will close this issue.

**Comment by erezrokah** [comment]
> Is it possible to get some context to that difference? What should be expected to be under the "data-plane" and what should be expected to be under the resource management module?

Hi @tasherif-msft, do you mind following up my question ⬆️ ?

**Comment by tasherif-msft** [comment]
You use the management plane to control resources in your subscription. You use the data plane to use capabilities exposed by your instance of a resource type (queues being the resource in this instance)
