### ISSUE TITLE
Need Help: SQL Client Does not Fetch Tags related Data

### ISSUE THREAD

**Issue by smit1682** [Azure/azure-sdk-for-go#20496]
Hello All, 
  I am collecting properties of SQL database instances. In which I have to fetch Tags(system tags) related to that instance.
  I am using the below methods to collect all the information.

```
client := sql.NewDatabasesClient(context.GetStringValue(consts.ObjectAccountId))

client.Authorizer = session.Authorizer

serverClient := sql.NewServersClient(context.GetStringValue(consts.ObjectAccountId))

serverClient.Authorizer = session.Authorizer

response, err := serverClient.ListByResourceGroup(azureContext.Background(),context.GetStringValue(consts.ObjectResourceGroup))

for _, server := range *response.Value {

		response, err := client.ListByServer(azureContext.Background(), context.GetStringValue(consts.ObjectResourceGroup), *server.Name, "", "")

		for _, database := range *response.Value {  
                            //TAGS =  database.Tags 
                 }
}
```

I am getting all the properties like 
"kind", "properties", "location", "id", "name", "type", "tags"

But in the tags field I am getting nil

   ```
Response = {autorest.Response} 
   Kind = {*string | 0xc000557ca0} "v12.0,user"
   DatabaseProperties = {*sql.DatabaseProperties | 0xc0000fc100} 
   Location = {*string | 0xc000557c90} "East US 2"
   Tags = {map[string]*string} nil
   ID = {*string | 0xc0000e4080} "/subscriptions/xyz/resourceGroups/DefaultResourceGroup-EUS2/provide"
   Name = {*string | 0xc0000e4090} "aqasde"
   Type = {*string | 0xc0000e40a0} "Microsoft.Sql/servers/databases"
```
(I have verified that there are Tags in Azure Portal )

Any suggestion how to fetch tags using this API call.

**Comment by SaurabhSharma-MSFT** [comment]
@smit1682 Can you please share the SQL module and version you are using ?

**Comment by smit1682** [comment]
@SaurabhSharma-MSFT thank you for your reply, 
we are using the latest version that azure cloud provides us.

**Comment by SaurabhSharma-MSFT** [comment]
@smit1682 Sorry for the delay.  I meant which GO Package you are using and the version as I do not see "ListByResourceGroup" in   [armsql package](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql#section-readme)

**Comment by SaurabhSharma-MSFT** [comment]
@smit1682 Can you please update me with the details so that I can investigate it further. Thanks

**Comment by smit1682** [comment]
@SaurabhSharma-MSFT Sorry for the delay,
we are using go 1.19
and for package we are using 
`"github.com/Azure/azure-sdk-for-go/profiles/2019-03-01/resources/mgmt/insights"`
`"github.com/Azure/azure-sdk-for-go/profiles/latest/sql/mgmt/sql"`

**Comment by SaurabhSharma-MSFT** [comment]
@smit1682 Thanks but I do not see the latest package of https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/profiles/latest/sql/mgmt/sql/sqlapi has any function named .ListByResourceGroup
I could see this function available under this deprecated package- https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/sql/mgmt/2014-04-01/sql.  Are you trying to use this?

**Comment by smit1682** [comment]
@SaurabhSharma-MSFT I am using .ListByResourceGroup function, which is written down in below root path,
github.com/Azure/azure-sdk-for-go/services/sql/mgmt/2014-04-01/sql/servers.go

there is any other way to fetch tags of SQL, if possible please suggest to me any function or package.
