### ISSUE TITLE
[armmonitor@v0.9.0] metricnames query value is urlencoded but should not be urlencoded

### ISSUE THREAD

**Issue by mblaschke** [Azure/azure-sdk-for-go#20501]
### Bug Report

- `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor v0.9.0`
-  `go version go1.20.2 darwin/arm64`

not sure when it started but at least armmonitor v0.9.0 seems to urlencode value of `,` which is used for `Metricnames` in `armmonitor.MetricsClientListOptions`.

This leads to following error:
```
{
  "additionalInfo": [
    {
      "type": "string",
      "info": "TraceId={df413c94-ff72-495f-8854-2f81df05273f}"
    },
    {
      "type": "string",
      "info": "ExceptionType=Microsoft.Online.Metrics.MetricsMP.Utilities.RPRequestFormatException"
    }
  ],
  "code": "BadRequest",
  "message": "Failed to find metric configuration for provider: Microsoft.KeyVault, resource Type: vaults, metric: ServiceApiHit,Availability, Valid metrics: ServiceApiHit,ServiceApiLatency,ServiceApiResult,SaturationShoebox,Availability"
}
```

If i do a ``req.Raw().URL.RawQuery = strings.ReplaceAll(req.Raw().URL.RawQuery, "%2C", ",")`` in transportPolicy it's working.

Azure Monitor API seems to expect a `,` instead of urlencoded `%2C`

This could also affect `Aggregation`

**Comment by lirenhe** [comment]
@tadelesh, could you help to check whether this is an SDK or service issue?

**Comment by mblaschke** [comment]
IMHO i think the urlencoding is fine but Azure API is not handling in properly

it seems it does something like `split(metricNames, ",")` and doesn't to urldecoding before

**Comment by yummydsky** [comment]
`Insights` has been marked as deprecated, but `armmonitor` still can NOT work properly. Can someone help to fix this and release it? Thanks a lot.

**Comment by tadelesh** [comment]
According to service team's explanation, the metric name may contain `,`, so it's better to encode the name first, then pass to SDK to do another encode. I don't know if it is the case you meet. @mblaschke , @yummydsky

**Comment by yummydsky** [comment]
For example, I want to query these metrics `"Percentage CPU, Available Memory Bytes, Network In, Network Out"`

In this file, line 112 will encode URL.RawQuery which contains `"Percentage CPU, Available Memory Bytes, Network In, Network Out"`. After encode, the metricsNames in RawQuery will become `"Percentage%20CPU%2C%20Available%20Memory%20Bytes%2C%20Network%20In%2C%20Network%20Out"`
which can not pass the metricNames rule check(split metrics by comma sign.)

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/monitor/armmonitor/metrics_client.go#L112
``` 
 70 func (client *MetricsClient) listCreateRequest(ctx context.Context, resourceURI string, options *MetricsClientListOptions) (*policy.Request, error) {
 71     urlPath := "/{resourceUri}/providers/Microsoft.Insights/metrics"
 72     urlPath = strings.ReplaceAll(urlPath, "{resourceUri}", resourceURI)
 73     req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
 74     if err != nil {
 75         return nil, err
 76     }
 77     reqQP := req.Raw().URL.Query()
 78     if options != nil && options.Timespan != nil {
 79         reqQP.Set("timespan", *options.Timespan)
 80     }
 81     if options != nil && options.Interval != nil {
 82         reqQP.Set("interval", *options.Interval)
 83     }
 84     if options != nil && options.Metricnames != nil {
 85         reqQP.Set("metricnames", *options.Metricnames)
 86     }
 87     if options != nil && options.Aggregation != nil {
 88         reqQP.Set("aggregation", *options.Aggregation)
 89     }
 90     if options != nil && options.Top != nil {
 91         reqQP.Set("top", strconv.FormatInt(int64(*options.Top), 10))
 92     }
 93     if options != nil && options.Orderby != nil {
 94         reqQP.Set("orderby", *options.Orderby)
 95     }
 96     if options != nil && options.Filter != nil {
 97         reqQP.Set("$filter", *options.Filter)
 98     }
 99     if options != nil && options.ResultType != nil {
100         reqQP.Set("resultType", string(*options.ResultType))
101     }
102     reqQP.Set("api-version", "2021-05-01")
103     if options != nil && options.Metricnamespace != nil {
104         reqQP.Set("metricnamespace", *options.Metricnamespace)
105     }
106     if options != nil && options.AutoAdjustTimegrain != nil {
107         reqQP.Set("AutoAdjustTimegrain", strconv.FormatBool(*options.AutoAdjustTimegrain))
108     }
109     if options != nil && options.ValidateDimensions != nil {
110         reqQP.Set("ValidateDimensions", strconv.FormatBool(*options.ValidateDimensions))
111     }
112     req.Raw().URL.RawQuery = reqQP.Encode()
113     req.Raw().Header["Accept"] = []string{"application/json"}
114     return req, nil
115 }

**Comment by yummydsky** [comment]
any updates?

**Comment by tadelesh** [comment]
> any updates?

Service team has rolled out some fix for the encoding. Also, they mentioned that they do not strip whitespace from the metric names at this time. So, for your example, the right query should be: `Percentage CPU,Available Memory Bytes,Network In,Network Out` or after encoding: `Percentage%20CPU%2CAvailable%20Memory%20Bytes%2CNetwork%20In%2CNetwork%20Out`.

**Comment by yummydsky** [comment]
> > any updates?
> 
> Service team has rolled out some fix for the encoding. Also, they mentioned that they do not strip whitespace from the metric names at this time. So, for your example, the right query should be: `Percentage CPU,Available Memory Bytes,Network In,Network Out` or after encoding: `Percentage%20CPU%2CAvailable%20Memory%20Bytes%2CNetwork%20In%2CNetwork%20Out`. If you still encounter the same problem, is it possible that you could open an ICM ticket that you could communicate with service guys directly.

How can I try the fix for the encoding? Do I need to upgrade `azure-sdk-for-go` or something?

**Comment by tadelesh** [comment]
It should be a service fix. You just need to run your test.
