### ISSUE TITLE
[azservicebus] consider allowing to set MaxBytes on MessageBatch struct

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-for-go#20547]
```golang
mb := &MessageBatch{
    maxBytes: maxBytes,
}
```

The only way to create a message batch is to call `sender.NewMessageBatch()`
it is possible to pass the `maxSize` there, but then the `Sender` verifies the link (call recover routine).
This is unecessarily restrictive and makes testing harder IMO.

Consider exporting the MessageBatch constructor:

**https://github.com/Azure/azure-sdk-for-go/blob/988beb5e7b638420819920db946f49f1c9169da6/sdk/messaging/azservicebus/message_batch.go#L35-L41**

or even making the MaxBytes public and dropping the constructor. There isn't much that can go wrong IMO.

**Comment by richardpark-msft** [comment]
@serbrech: Can you clarify this:

> This is unecessarily restrictive and makes testing harder IMO.

Do you have a code snippet I can look at?

**Comment by serbrech** [comment]
if I have code that is adding messages to a messageBatch, it will fail on the first message added to the batch, because the messageSize is 0.
I am unable to create a messageBatch with a size other than 0, because the property is internal.
so testing any code that uses messageBatch needs layers of abstraction over the sender, just so that I can abstract the MessageBatch

**Comment by serbrech** [comment]
it's similar issue as the Poller.
you return a concrete type with unexported properties, and behavior that cannot be faked.

**Comment by serbrech** [comment]
I fail to see how maxSize would be a problem to expose. On the messageBatch.
It's already exposed via the option of sender.NewMessageBatch but I can't call that because it calls the link. This makes it impossible to use your sender and make the code testable, I think one of the key principle of the sdk is testability, and that does not fulfill it IMO.
