### ISSUE TITLE
azcore should support api-key authentication scheme

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-for-go#20541]
### Feature Request

Some Azure services use an api-key, usually in a request header, for authentication.  Azure Core for Go should include a class for defining this form of authentication to allow Go clients to support services that use api-key authentication.

An example is the Python AzureKeyCredential class:

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-core/latest/azure.core.html#azure.core.credentials.AzureKeyCredential

**Comment by richardpark-msft** [comment]
If we add KeyCredential it seems logical to add in AzureNamedKeyCredential as well.

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-core/latest/azure.core.html#azure.core.credentials.AzureNamedKeyCredential

**Comment by jhendrixMSFT** [comment]
Possibly also AzureSASCredential.

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-core/latest/azure.core.html#azure.core.credentials.AzureSasCredential

**Comment by jhendrixMSFT** [comment]
Will likely punt on NamedKeyCredential for now since AFAIK only storage uses these and they have their own SharedKeyCredential.

**Comment by jhendrixMSFT** [comment]
Will go out in `azcore@v1.8.0-beta.4`
