### ISSUE TITLE
Include the details and additionalInfo in the ResponseError 

### ISSUE THREAD

**Issue by mingqishao** [Azure/azure-sdk-for-go#20555]
### Feature Request

We are using `Poller` to poll the result of asynchronous operations.  According to [Azure Resource Management's API guideline](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content), The error returned from resource provider might be also have `additionalInfo` and `details`.  I'm trying to use below codes to capture the the error's detail. But the azcore.ResponseError doesn't have the information of `additionalInfo` and `details`.

So is there other better way I can use to capture the `additionalInfo` and `details` of Azure's error returned from Poller? Thank you.

```
var resErr *azcore.ResponseError
errors.As(err, &resErr)
```

**Comment by jhendrixMSFT** [comment]
This is by design.  Per Azure guidelines, the only parts of a service response error that are contractual are the HTTP status code and the error code provided either via the response body or the `x-ms-error-code` header.

Can we get more information on why you need programmatic access to the other bits of information?

CC @JeffreyRichter

**Comment by mingqishao** [comment]
We are Azure Kubernetes Service team. We are using Golang SDK to talk with other dependencies Azure service. We need those information to construct our error and pass to our client

**Comment by jhendrixMSFT** [comment]
If this is purely informational, the string returned from `Error()` will contain the full text (in that case it's probably best to just propagate the `*azcore.ResponseError`).  Is this the case?

**Comment by mingqishao** [comment]
We want to return client a standard Azure Error format to customer, the format should look like below.  We don't want to put the dependency error's full text into the `message` field, instead we want to put it into the `details` with original structure.

```json
{
  "error": {
    "code": "Some_Error_Code", // define by us
    "message": "Dependency error with short message",
    "target": "",
    "additionalInfo": [],
    "details": [
      {
        "code": "",
        "target": "",
        "message": "",
        "additionalInfo": [
        ]
      }
    ]
  }
}
```

**Comment by jhendrixMSFT** [comment]
My understanding, and @JeffreyRichter can correct me if I'm wrong, is that _only_ the HTTP status code and error code are to be considered "standard Azure error format"; everything else is informational and subject to change.  This is why our SDKs don't expose data other than these bits as it's not to be relied upon/programmatically used.

How do you expect callers to programmatically use this data?
