### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Seizal** [Azure/azure-sdk-for-go#20560]
### Feature Request

Hello,

 I would like to know if a new documentation is being written because many appellations have changed, such as `me.MailFoldersItemMessagesRequestBuilderGetQueryParameters` and `users.ItemMailFoldersItemMessagesRequestBuilderGetQueryParameters`.
 It is very difficult to find one's way around.

Thank you very much for your help and support. Your assistance is greatly appreciated.

**Comment by jhendrixMSFT** [comment]
@Seizal can we get more information, e.g. which module(s) are you using?

**Comment by Seizal** [comment]
Of course, 
I'm using the module github.com/microsoftgraph/msgraph-sdk-go v0.60.0.

**Comment by jhendrixMSFT** [comment]
Thanks.

Looks like this is in regards to msgraph-sdk-go?  If so, can you please open an issue in that repo.  The msgraph SDK is owned and managed by a separate team.

**Comment by Seizal** [comment]
Very well, I will do it. My question was mainly about the fact that there is still no output documentation. But I understand because the version is not finalized yet. I am mainly looking for information that can help me move forward on my project related to this module.

Thank you

**Comment by jhendrixMSFT** [comment]
Understood.  Unfortunately, nobody on the azure-sdk-for-go team is knowledgeable on the msgraph SDKs.  Opening an issue in their repo is the best way forward.

**Comment by Seizal** [comment]
Out of curiosity, what are the possibilities with SDK-for-go? Can we create authentication for a web service, send and retrieve emails, for example?

Thank you

**Comment by jhendrixMSFT** [comment]
There used to be an aad-graph package for this.  However, that's been deprecated for msgraph which is the current solution.
