### ISSUE TITLE
Broken error message on Key Vault encrypt without algorithm

### ISSUE THREAD

**Issue by carlpett** [Azure/azure-sdk-for-go#2060]
(This is probably more of an issue in Key Vault itself, rather than this library, but not clear where to report)

If the `Algorithm` field of `keyvault.KeyOperationsParameters` is left blank in a call to `Encrypt`, the error message given is:
`keyvault.BaseClient#Encrypt: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Property  has invalid value\r\n"`
Note the empty property name.

As an additional note, it would be nice with some guidance and/or reference material in the docs regarding the choice of algorithms.

**Comment by jhendrixMSFT** [comment]
@schaabs from KeyVault should be able to help out.
Also I found some documentation about the algorithms, dunno how much it helps.
https://docs.microsoft.com/en-us/azure/key-vault/about-keys-secrets-and-certificates#BKMK_RSAAlgorithms

**Comment by ArcturusZhang** [comment]
Hi @carlpett it has been long for this issue, does this issue still exist?

**Comment by carlpett** [comment]
@ArcturusZhang It has indeed been long, and I'm no longer working with the client where I used Azure, so I cannot validate it. Perhaps you have some MS-internal change log you can check if the error messages have been improved? The problem, as I recall, was that the error is `Message="Property has invalid value\r\n"`, rather than something like `Message="Property "Algorithm" has invalid value\r\n"`.
Ideally, this would be fixed in KeyVault itself, rather than this library, but you could of course hide the problem by handling it here if there are long lead times in changing KeyVault.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang Dapeng Zhang FTE It has indeed been long, and I'm no longer working with the client where I used Azure, so I cannot validate it. Perhaps you have some MS-internal change log you can check if the error messages have been improved? The problem, as I recall, was that the error is `Message="Property has invalid value\r\n"`, rather than something like `Message="Property "Algorithm" has invalid value\r\n"`.
> Ideally, this would be fixed in KeyVault itself, rather than this library, but you could of course hide the problem by handling it here if there are long lead times in changing KeyVault.

Sometimes for other services I have seen this kind of error responses:
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter automaticRepairsPolicy is invalid.",
    "target": "automaticRepairsPolicy"
  }
}
```
But I do not know how it is in key vault. Let me find a way to check with this.

**Comment by ArcturusZhang** [comment]
Hi @RandalliLama @schaabs @jlichwa do we have any updates on this?

**Comment by botondev** [comment]
Hi, I am receiving this using Terraform, but there I have no option for setting any algorithm. I am still looking for a solution. Does anyone know anything? Thank you.

**Comment by botondev** [comment]
Hi again!

I just found that setting up
"x509_certificate_properties" in terraform "azurerm_key_vault_certificate" resource, solves the problem.

Hopefully, this information helps someone in the future.

Thank you

**Comment by rickychew77** [comment]
> Hi again!
> 
> I just found that setting up "x509_certificate_properties" in terraform "azurerm_key_vault_certificate" resource, solves the problem.
> 
> Hopefully, this information helps someone in the future.
> 
> Thank you

hey @botondev , know it's been a while, trying luck but could you elaborate more how that `x509_certificate_properties` helps? We have configured that too in Terraform but still giving error below:

`Error: keyvault.BaseClient#CreateCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Property  has invalid value\r\n"`
