### ISSUE TITLE
How to use sdk to set acl for blob

### ISSUE THREAD

**Issue by ChronosSong** [Azure/azure-sdk-for-go#20632]
### Feature Request

How to set acl for blob like azure cli, not for setting acl at the container layer, but for finer-grained authorization to blob.
e.g: `az storage fs access set-recursive --acl "user::rwx,group::r-x,other::---,default:user:$SERVICE_PRINCIPAL_ID:r-x" -p $BLOB -f $STORAGE_CONTIANER --account-name $STORAGE_ACCOUNT`

**Comment by vibhansa-msft** [comment]
ACLs are supported only for HNS enabled account over 'dfs' endpoint.  azblob as of today does not support dfs endpoint, this feature will come along when datalake sdk is released.
