### ISSUE TITLE
data/azcosmos: query value will cause error

### ISSUE THREAD

**Issue by chiyoi** [Azure/azure-sdk-for-go#20651]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos`
- SDK version: `azcosmos@v0.3.3`
- output of `go version`: `go version go1.20.2 darwin/amd64`

- What happened?

When querying values like `select value c.id from c`, cosmos endpoint will return array of values (for example strings), but the SDK tried to unmarshal it into `map[string]any`, causing:
```
unmarshalling type *azcosmos.queryServiceResponse: json: cannot unmarshal string into Go struct field queryServiceResponse.Documents of type map[string]interface {}
```

- What did you expect or want to happen?

`cosmos_query_response.go: line 61`: 
change ...`[]map[string]interface{}`...
into ...`[]any`... or ...`[]interface{}`...

- How can we reproduce it?

```go
func reproduce() {
	client, _ := ...// ...: get a container client
	pager := client.NewQueryItemsPager("select value c.id from c", ..., nil) // ...: choose the right partition key
	for pager.More() {
		_, err := pager.NextPage(context.TODO())
		fmt.Println(err) // unmarshalling type *azcosmos.queryServiceResponse: json: cannot unmarshal string into Go struct field queryServiceResponse.Documents of type map[string]interface {}
	}
}
```

- Anything we should know about your environment.

/

**Comment by ealsur** [comment]
@chiyoi please see https://github.com/Azure/azure-sdk-for-go/pull/20656
