### ISSUE TITLE
Add Go content for ACR quick start doc in MSLearn

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#20653]
See: https://github.com/MicrosoftDocs/azure-docs/issues/104728
Doc: https://learn.microsoft.com/en-us/azure/container-registry/quickstart-client-libraries?pivots=programming-language-python

**Comment by raych1** [comment]
Added content for Go at https://github.com/MicrosoftDocs/azure-docs/pull/110386

**Comment by raych1** [comment]
Document was released.
