### ISSUE TITLE
ListBlobsFlatSegmentResponse uses non-external type for BlobItems

### ISSUE THREAD

**Issue by sblackstone** [Azure/azure-sdk-for-go#20664]
### Bug Report

When listing blob items, e.g.

```
	for pager.More() {
		resp, err := pager.NextPage(ctx)
		if err != nil {
			return err
		}
		for _, blob := range resp.Segment.BlobItems {
			callback(blob)
		}
	}
```

The type for `resp.Segment.BlobItems` is `*generated.BlobItem` which does not appear to be exported by SDK making it difficult to pass around to other functions in my application.

**Comment by souravgupta-msft** [comment]
As mentioned above, please update to latest version of [azblob](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv1.0.0). You can use `container.BlobItem` for your use case.

**Comment by sblackstone** [comment]
Hello,

Was running 1.0.0.   container.BlobItem works correctly.

It seems like the reflection and re-assigned types used in `azblob` are confusing the tooling.  I spent a considerable amount of time looking through the Godoc before filing this bug trying to determine the correct type and it wasn't obvious.

I'll know for the future to `grep` the code for where the generated type is set to the exported type, but I foresee this causing you future erroneous bug reports.


<img width="898" alt="image" src="https://user-images.githubusercontent.com/131382/233719856-1a0938a3-9b46-45d1-9692-76a8ed9c0219.png">

**Comment by souravgupta-msft** [comment]
Hi @sblackstone. Thanks for pointing this. I understand your concern here. I would like to point out that `azblob` package is intended to be used for general use cases like creating, deleting, listing of containers/blobs. If you want to drill down further you can import the respective packages. Like in your case, you are using `azblob.NewListBlobsFlatPager` which internally calls the `container.NewListBlobsFlatPager` method. So, you can import the `container` package directly which has all the generated types exported like `container.BlobItem`.

**Comment by souravgupta-msft** [comment]
Closing this issue. Feel free to post any queries you have in this thread.
