### ISSUE TITLE
Azure Blob Storage SDK delete folder

### ISSUE THREAD

**Issue by wale-kobai** [Azure/azure-sdk-for-go#20665]
### Feature Request

Our account has the hierarchical namespace feature enabled, and when trying to delete an empty or non-empty folder, we get the response `RESPONSE 400: 400 The requested operation is not supported on a directory. ERROR CODE: OperationNotSupportedOnDirectory`

The workaround for us is to use the storage explorer to delete the folders or call the endpoint `dfs.core.windows.net/container/folder?recursive=true`

I would like to request the ability to delete a folder using the azure go sdk when  the hierarchical namespace feature is enabled

**Comment by vibhansa-msft** [comment]
Storage accounts with hierarchical namespace feature enabled are not fully supported by azblob package. There are few apis that work on blob endpoint which might work, however apis which are specific to dfs endpoint will fail. We do have plans to add this support soon.
