### ISSUE TITLE
Question: How to paginate over `armconsumption.PriceSheetResult.Properties.Pricesheets`

### ISSUE THREAD

**Issue by erezrokah** [Azure/azure-sdk-for-go#20671]
For reference the REST API is https://learn.microsoft.com/en-us/rest/api/consumption/price-sheet/get?tabs=HTTP#pricesheetresult

and the Go code I'm using is similar to:

```go
client, err := armconsumption.NewPriceSheetClient(...)
if err != nil {
	return nil, err
}
opts := &armconsumption.PriceSheetClientGetOptions{Expand: to.Ptr("properties/meterDetails")}
resp, err := client.Get(ctx, opts)
if err != nil {
	return nil, err
}

allPricesSheets := resp.PriceSheetResult.Properties.Pricesheets
nextLink := resp.PriceSheetResult.Properties.NextLink
for nextLink != nil {
	parsedNextLink, err := url.Parse(*nextLink)
	if err != nil {
		break
	}
	token := parsedNextLink.Query().Get("skiptoken")
	if token == "" {
		break
	}
	opts.Skiptoken = to.Ptr(token)
	paginatedResponse, err := client.Get(ctx, opts)
	if err != nil {
		return nil, err
	}
	allPricesSheets = append(allPricesSheets, paginatedResponse.PriceSheetResult.Properties.Pricesheets...)
}

return allPricesSheets, nil
```

Is that the correct way to paginate over price sheets?

> Could be related to https://github.com/Azure/azure-sdk-for-go/issues/4142

**Comment by lirenhe** [comment]
Could you follow this for paging? https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination

**Comment by lirenhe** [comment]
cc  @tadelesh

**Comment by erezrokah** [comment]
> Could you follow this for paging? https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination

Hi @lirenhe and thank you for the response. I'm not sure how to follow that guide as I don't think the Price Sheets Get operation returns a pager. Can you please advise?

**Comment by tadelesh** [comment]
Since it is not a normal pageable operation, you could not follow the guide, sorry for the wrong instruction. I think the code you provided is good for the customized paging operation (you need to update nextLink in the loop). Could you try it first? If there is something exception, I could involve service team to help.
