### ISSUE TITLE
Support for Azure Workload Identity stable version

### ISSUE THREAD

**Issue by vsur06** [Azure/azure-sdk-for-go#20687]
### Service Package Request
Hi can you please share the timeline for a stable version for azure golang sdk to support azure workload identity. I see from this [thread](https://github.com/Azure/azure-sdk-for-go/issues/19765) that the version supported is v1.3.0-beta.1, and the plan to have the stable version was originally by early April.
Can you please share any updates.

Thank you!

**Comment by chlowell** [comment]
New plan is to ship a stable version including the workload identity API from v1.3.0-beta.5 on May 9. I think it's unlikely, but we could get feedback in the meantime that requires an API change and/or delaying the release. I'll add another update here if the plan changes.

**Comment by vsur06** [comment]
Sure, thank you, Charles! I'll wait for your update on this.

**Comment by chlowell** [comment]
[azidentity v1.3.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.3.0#WorkloadIdentityCredential) is available now. Please open another issue if you encounter any problems using it.
