### ISSUE TITLE
azqueue Create() behavior does not match the method's documentation

### ISSUE THREAD

**Issue by eduardodbr** [Azure/azure-sdk-for-go#20683]
### Bug Report

- github.com/Azure/azure-sdk-for-go/sdk/storage/azqueue v0.1.0
- go version go1.20.3 darwin/arm64

The documentation for (q *QueueClient) Create() states ` If a queue with the same name already exists, the operation fails.`. However, if a queue with the same name already exists it does not fail or return any error.  

When creating a new queue, azure API returns 201 after creating it, but if it already exists it returns 204. I was expecting the method's documentation to be more clear about not returning an error or return [409 QueueAlreadyExists](https://learn.microsoft.com/en-us/rest/api/storageservices/queue-service-error-codes).

To reproduce:

```
        connStr := "" // update this
	queueName := "test"
	client, err := azqueue.NewServiceClientFromConnectionString(connStr, nil)
	if err != nil {
		panic(err)
	}
	queueClient := client.NewQueueClient(queueName)
	resp, err := queueClient.Create(context.Background(), &azqueue.CreateOptions{})
	if err != nil {
		panic(err)
	}
	resp, err = queueClient.Create(context.Background(), &azqueue.CreateOptions{})
	if err != nil {
		panic(err)
	}
```

**Comment by tasherif-msft** [comment]
Hi @eduardodbr, good catch, we will correct our documentation to reflect the behavior.
