### ISSUE TITLE
azqueue GetAccessPolicy returns 404

### ISSUE THREAD

**Issue by disq** [Azure/azure-sdk-for-go#20694]
### Bug Report

- github.com/Azure/azure-sdk-for-go/sdk/storage/azqueue v0.1.0
- go version go1.19.1 darwin/arm64

I build the queue URL using:
```go
	queueURL := runtime.JoinPaths("https://"+*accName+".queue.core.windows.net", url.PathEscape(*queueName))
```

After creating the `QueueClient`, `client.GetProperties()` seems to work, but `client.GetAccessPolicy()` fails with:

> GET https://the_account_name.queue.core.windows.net/the_queue_name\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 The specified resource does not exist.\nERROR CODE: ResourceNotFound\n--------------------------------------------------------------------------------\n\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.\nRequestId:a62c90e9-e003-0090-2393-779299000000\nTime:2023-04-25T16:32:34.0640516Z</Message></Error>\n--------------------------------------------------------------------------------\n

I was expecting to get the access policy assigned to the queue. Documentation for the method is [here](https://learn.microsoft.com/en-us/rest/api/storageservices/get-queue-acl).

**Comment by tasherif-msft** [comment]
Hi @disq I will attempt to repro this and get back to you

**Comment by disq** [comment]
> Hi @disq I will attempt to repro this and get back to you

@tasherif-msft Any luck? Let me know if you need any more info

**Comment by disq** [comment]
@tasherif-msft Yes it's happening consistently with multiple queues but the az cli (`az storage queue policy list --connection-string ... --queue-name ...`) works... I tried overriding the API version to `2021-02-12` (which is what the CLI uses... azqueue seems to use `2018-03-28`) with a custom transporter but it's still the same error.

**Comment by tasherif-msft** [comment]
@disq can you share which method you're using to create your queue client and how you're passing your credential? if you can share your full code snippet and just redact any sensitive information, that would help repro your issue.

**Comment by disq** [comment]
@tasherif-msft The code is publicly here: https://github.com/cloudquery/cloudquery/pull/10323/files#diff-c9bb3a1a217756575eb01adad5eb0b927b27fa55022bdf66c5e46a7ed3a8751aR45-R55

I also tried generating a ServiceClient and then creating the QueueClient from that but it leads to the same http request with the same result (404) in the end.

**Comment by disq** [comment]
@tasherif-msft and here's a bare-bones `main.go` gist that shows the issue: https://gist.github.com/disq/d8de7925b700660a397dd652bd6771b9

```
go run main.go
2023/05/02 10:39:46 Found subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023/05/02 10:39:47 Found storage account cqdestinationazblob
2023/05/02 10:39:48 Found queue anothertestqueue
2023/05/02 10:39:49 Error:GET https://cqdestinationazblob.queue.core.windows.net/anothertestqueue
--------------------------------------------------------------------------------
RESPONSE 404: 404 The specified resource does not exist.
ERROR CODE: ResourceNotFound
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:6954655e-d003-0040-77da-7cafcf000000
Time:2023-05-02T09:39:49.0573352Z</Message></Error>
--------------------------------------------------------------------------------
exit status 1
```

**Comment by tasherif-msft** [comment]
Hi @disq so I was looking at your request ID, and it seems it's a permissions issue. Although queues does support OAuth, please refer to https://learn.microsoft.com/en-us/rest/api/storageservices/get-queue-acl#authorization "Only the account owner may call this operation."
So the service principal being used does not have the proper permissions here

**Comment by disq** [comment]
> it's a permissions issue

@tasherif-msft `az storage queue policy list` works for me using the same credentials/account, so could it be something else?
