### ISSUE TITLE
storage - implement SetBlobProperties API

### ISSUE THREAD

**Issue by kenegozi** [Azure/azure-sdk-for-go#207]
see https://msdn.microsoft.com/en-us/library/azure/ee691966.aspx

some blobs need these to be useful. for example Content-Type for various media files must be set for clients (including browsers) to treat them correctly.

**Comment by ahmetalpbalkan** [comment]
@kenegozi want to contribute? Shouldn't be that hard.

**Comment by kenegozi** [comment]
@ahmetalpbalkan why is BlobProperties.LastModified a string and not a time.Time?

**Comment by ahmetalpbalkan** [comment]
@kenegozi good question, I don't remember to be honest. Might be a mistake. Looks like Go supports RFC1123 just fine, so we can change.

**Comment by kenegozi** [comment]
hmm there is no apparent way for xml unmarshal to deal with non rfc3339 dates.

It is easy peasy when working with headers, it's just that pesky ListBlobs operation that makes this a no-go.

For now I'll keep dates as strings, and will come up with another solution for dates throughout the package separately.

**Comment by jerbob92** [comment]
Way I fixed that in my own application:
```
```

**Comment by mcardosos** [comment]
Functionality already added.
