### ISSUE TITLE
Release Microsoft.ApiManagement/preview/2022-08-01

### ISSUE THREAD

**Issue by xaviergxf** [Azure/azure-sdk-for-go#20701]
Hi can https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01 please be released to this SDK?

2022-08-01 is the latest GA

Blocks [https://github.com/hashicorp/terraform-provider-azurerm/issues/21543](https://github.com/hashicorp/terraform-provider-azurerm/issues/21543)

**Comment by lirenhe** [comment]
@xaviergxf, based on the comment in https://github.com/hashicorp/terraform-provider-azurerm/issues/21543,  it seems you would like us to release a new Go SDK with old version.  Please note, that version of the library for azure-sdk-for-go were  deprecated last year and moving forward, we will only release track 2 libraries.

Please let me know if you have other questions. Thanks

**Comment by xaviergxf** [comment]
Ok i undestand, thanks. You may close this ticket
