### ISSUE TITLE
[CosmosDB] Support for `merge partitions` feature

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-sdk-for-go#20709]
### Feature Request

This is a request for the CosmosDB Go SDK to support the `merge partitions` preview feature as described here:
https://learn.microsoft.com/en-us/azure/cosmos-db/merge?tabs=azure-powershell%2Cnosql

We, the Dapr team, received a request from a user (who otherwise is a DotNet user), to support this (preview) feature.

**Comment by ealsur** [comment]
@berndverst Go is considered a "Gateway" SDK, currently there are no operations in the Go SDK that need any work to be merge compliant, all the operations exposed in the current SDK are merge compliant.

**Comment by ealsur** [comment]
To give more details on what operations are affected by merge operations: cross-partition queries, change feed consumption.

Because the current SDK does not have any of that, hence, it is merge compliant.

When those features are added (for example, when cross-partition queries are added) they would be merge-compliant by default.

**Comment by berndverst** [comment]
@ealsur a user is getting this error:

```
ESPONSE 400: 400 Bad Request
2023-04-27T06:37:07.268559588Z       ERROR CODE: BadRequest
2023-04-27T06:37:07.268563988Z       --------------------------------------------------------------------------------
2023-04-27T06:37:07.268568088Z       {
2023-04-27T06:37:07.268572588Z         "code": "BadRequest",
2023-04-27T06:37:07.268591589Z         "message": "Message: {"Errors":["The collection cannot be accessed with this SDK version as it has partition merge enabled. Learn more:https:\/\/aka.ms\/cosmosdbsdksupportformerge."]}
```

**Comment by ealsur** [comment]
@berndverst this is a service validation, apparently it is not considering that the Go SDK useagent represents a client that is merge proof, I'll contact the service team regarding this, thanks for reporting.

**Comment by ealsur** [comment]
@berndverst next version is planned for release on 5/9.
