### ISSUE TITLE
Add `string X509ThumbprintString` property to `CertificateProperties`

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-go#20719]
Add a `string X509ThumbprintString` property to `CertificateProperties` that returns the hex representation of `byte[] X509Thumbprint` and hide the older member as its rare in managed code to need a `byte[]` representation of the thumbprint.

**Comment by gracewilcox** [comment]
This feature is not relevant to the Go. In our SDK, we're sticking as close to the Key Vault API as possible. 

If needed, it is easy for users to cast to a string by calling [hex.EncodeToString()](https://pkg.go.dev/encoding/hex#EncodeToString).
