### ISSUE TITLE
NewClientFromConnectionString doesn't support SAS tokens with custom endpoints

### ISSUE THREAD

**Issue by jlaundry** [Azure/azure-sdk-for-go#20718]
### Bug Report

- SDK: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.0.0 h1:u/LLAOFgsMv7HmNL4Qufg58y+qElGOt5qv0z1mURkRY=`
- `go version go1.20.2 darwin/amd64`

### Reproduction Steps

1. Start Azurite
2. Create a SAS token (example below uses the default Azurite access key)
3. Try to create a client with NewClientFromConnectionString:

```go
connectionString := "AccountName=devstoreaccount1;SharedAccessSignature=sig=PTTuImbY50brWEx%2FEBwY9czhUpSYzi5IGVg6utbiD2A%3D&sp=raw&sr=c&sv=2020-02-10;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
containerName := "89d52d33-166d-4e69-8c0b-39e5c1e7940f"
client, err := azblob.NewClientFromConnectionString(connectionString, nil)
content := []byte("hello")
_, err = client.UploadBuffer(context.TODO(), containerName, "test.txt", content, nil)
```

### Expected

Client uploads a file to `http://127.0.0.1:10000/devstoreaccount1/89d52d33-166d-4e69-8c0b-39e5c1e7940f/test.txt`

### Actual

Client errors, as the upload was attempted to `https://devstoreaccount1.blob.core.windows.net/89d52d33-166d-4e69-8c0b-39e5c1e7940f/test.txt`

**Comment by siminsavani-msft** [comment]
Hi @jlaundry ! Could you please share the client errors you are getting?

**Comment by jlaundry** [comment]
Hi @siminsavani-msft - the 'error' is `connection string is either blank or malformed. The expected connection string should contain key value pairs separated by semicolons. For example 'DefaultEndpointsProtocol=https;AccountName=<accountName>;AccountKey=<accountKey>;EndpointSuffix=core.windows.net'`

But this error message occurs **after** the client has tried to connect to `devstoreaccount1.blob.core.windows.net` instead of `127.0.0.1:10000`...

I've had a chance to look at this more, the issue is

https://github.com/Azure/azure-sdk-for-go/blob/8849196dfa482cef8345590dc7bd12c8ad3c5de1/sdk/storage/azblob/internal/shared/shared.go#L101-L103

which ignores the BlobEndpoint parameter in the connection string - this not only breaks Azurite local connections, but as `defaultSuffix` is a const pointed to `core.windows.net`, this also breaks sovereign cloud endpoints (i.e., US Gov uses `blob.core.usgovcloudapi.net`).

**Comment by siminsavani-msft** [comment]
Wow, thank you for your contribution! Will take a look shortly!
