### ISSUE TITLE
azidentity credential.GetToken(r.Context(),nil) will it cache the token?

### ISSUE THREAD

**Issue by pillaimithun** [Azure/azure-sdk-for-go#20723]
I am using "github.com/Azure/azure-sdk-for-go/sdk/azidentity" for auth. The go lang code is somewhat similar to below:

Each http request is intercepted and an auth token is added in the header. 
credential object is initialised only once at application start up.

Question: **When a new access token is requested, will the SDK first checks the cache for a valid token that matches the specified scopes and resource? Or for every call to GetToken it tries to generate a new token always?**

`credential, err := azidentity.NewDefaultAzureCredential(nil)`

```
if credential != nil {
		token, err := credential.GetToken(r.Context(), policy.TokenRequestOptions{
			Scopes: []string{
				appID,
			},
		})
		if err != nil {
			return err
		}
		r.Header.Add("Authorization", fmt.Sprintf("Bearer %s", token.Token))
}

```

Note: I read somewhere in documentation like in Python SDK, the access token is cached in memory for the duration of the application process. Here the question is how it behaves in go SDK

**Comment by jhendrixMSFT** [comment]
The token is cached in memory and is refreshed within a window of time before it expires.
