### ISSUE TITLE
Filter does not seem to work when used with VirtualMachineClient

### ISSUE THREAD

**Issue by unmarshall** [Azure/azure-sdk-for-go#20728]
### Bug Report

Package Versions as in go.mod of the test application:
```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.5.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.2.2
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4 v4.2.1
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2 v2.2.1
```

- What happened?
armcompute.VirtualMachineClient provides a method `NewListAllPager` to list all virtual machines given a subscription and optionally a filter. If a filter is specified then the response returned is `400` Bad request.

```go
factory, err := armcompute.NewClientFactory(subscriptionID, tokenCredential, nil)
if err != nil {
	return err
}
client := factory.NewVirtualMachinesClient()
// filter := "resourceGroup eq 'test-resource-group' and resourceType eq 'Microsoft.Compute/virtualMachines'"
filter := "resourceGroup eq 'test-resource-group'"
pager := client.NewListAllPager(&armcompute.VirtualMachinesClientListAllOptions{
    Filter: &filter,
})
for page.More() {
    page, err := pager.NextPage(ctx)
    if err != nil {
        return err // here an error is returned
    }
}
```
Error received:
```
GET https://management.azure.com/subscriptions/<subscription-id>/providers/Microsoft.Compute/virtualMachines
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadRequest",
    "message": "The request URL is not valid."
  }
}
```
> NOTE: We tried to filter conditions. In the above code both are mentioned (one is commented out). None of the filters seem to work with virtual machine client.

To confirm if there was anything wrong with the filter we used another API which lists the resources via a resource client.
```go
factory, err := armresources.NewClientFactory(subscriptionID, tokenCredential, nil)
if err != nil {
    return err
}
client := factory.NewClient()
filter := "resourceGroup eq 'test-resource-group' and resourceType eq 'Microsoft.Compute/virtualMachines'"
pager := c.ResourcesClient.NewListPager(&armresources.ClientListOptions{
		Filter: &filter,
})
for page.More() {
    page, err := pager.NextPage(ctx)
    if err != nil {
        return err // here an error is returned
    }
}
```
The above code properly returned the expected result. There was no error reported in the filter. The filter is exactly the same in both the cases. One API reports a failure and the other accepts it.

**What did you expect or want to happen?**
  The filter which follows an OData filter grammar should have worked consistently with a VM client to filter out VirtualMachines instead of returning a 400 Bad Request response.
**How can we reproduce it?**
  Use the above code and test it.
**Anything we should know about your environment.**
  No

**Comment by lirenhe** [comment]
@unmarshall,  it seems the value you provided for the $filter is not correct.
Could you follow https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all?tabs=HTTP#uri-parameters to update the filter value?  Thanks

**Comment by unmarshall** [comment]
@lirenhe as per the documentation:
```
Allowed value is 'virtualMachineScaleSet/id' eq /subscriptions/{subId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmssName}'
```
Is the only allowed value `virtualMachineScaleSet`? We do not use VirtualMachineScaleSet and we do not plan to use it as well. What we are trying to do is quite simple - filter VMs based on certain tags. This seems to be possible when listing resources but not possible when listing virtual machines. Is this a limitation?

**Comment by lirenhe** [comment]
I think this is the current behaviour.  I added the label of service attention to involve service team for confirm.

**Comment by navba-MSFT** [comment]
@unmarshall Apologies for the late reply. Thanks for reaching out to us and reporting this issue. To filter based on certain tags, Please leverage the below sample code:

```
//Sample Code

package main

import (
	"context"
	"fmt"
	"log"
	"strconv"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph"
)

var (
	subscriptionID string
	TenantID       string
)

func main() {

	// To configure DefaultAzureCredential to authenticate a user-assigned managed identity,
	// set the environment variable AZURE_CLIENT_ID to the identity's client ID.

	clientID := "XXXXXXXXXXXXXXXX"
	clientSecret := "XXXXXXXXXXXXXXXX"
	tenantID := "XXXXXXXXXXXXXXXX"

        // Constructs a ClientSecretCredential. Pass nil for options to accept defaults.
	cred, err := azidentity.NewClientSecretCredential(tenantID, clientID, clientSecret, nil)
	if err != nil {
		log.Fatalf("failed to create credential: %v", err)
	}

	ctx := context.Background()

	// Create and authorize a ResourceGraph client
	client, err := armresourcegraph.NewClient(cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}

	// Create the query request, Run the query and get the results. Update the Tags and subscriptionID details below.
	results, err := client.Resources(ctx,
		armresourcegraph.QueryRequest{
			Query: to.Ptr("Resources | where type =~ 'Microsoft.Compute/virtualMachines' and tags.Environment=~ 'Production' | project name, type, location, properties"),
			Subscriptions: []*string{
				to.Ptr("XXXXXXXXXXXXXXXXXXXX")},
		},
		nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	} else {
		// Print the obtained query results
		fmt.Printf("Resources found: " + strconv.FormatInt(*results.TotalRecords, 10) + "\n")
		fmt.Printf("Results: " + fmt.Sprint(results.Data) + "\n")
	}

}
```

**Comment by navba-MSFT** [comment]
@unmarshall I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@unmarshall Thanks for your reply. I am glad that the above sample worked fine. **[_Here_](https://learn.microsoft.com/en-us/azure/governance/resource-graph/samples/starter?tabs=azure-cli#show-vms)** are the sample Resource Graph queries for Azure VMs. To know more about the Resource Query language refer **_[this](https://learn.microsoft.com/en-us/azure/governance/resource-graph/concepts/query-language)_** article. Hope this helps.

**Comment by navba-MSFT** [comment]
@unmarshall I hope you had a chance to look at my [above ](https://github.com/Azure/azure-sdk-for-go/issues/20728#issuecomment-1545073602)comment. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by lirenhe** [comment]
> /reopen

do you have any further questions on this?  Feel free to reopen it.

**Comment by artificial-aidan** [comment]
Is there any way to get typed resources out of the graph api? Is there any plan to support more filtering on the rest api? Or is the answer always the graph api?
