### ISSUE TITLE
ResourceGroup Value in the Virtual Machine "id" filed is in Capital Latter (even if it is configured small case)

### ISSUE THREAD

**Issue by saheb-uptycs** [Azure/azure-sdk-for-go#20738]
### Bug Report

  - importing "https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute"
  - using https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute v4.2.1 in go.mod
  - go version go1.19 linux/amd64

- Created resource group on Azure portal **_test-resource-group_**
- Created Virtual Machine **_vm-test_** in resource group  **_test-resource-group_**
 - List Virtual Machine using  REST API  `clientFactory.NewVirtualMachinesClient().NewListAllPager(nil)` 

 - Output  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/**_TEST-RESOURCE-GROUP_**/providers/Microsoft.Compute/virtualMachines/vm-test" 
- expected Output "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/**_test-resource-group_**/providers/Microsoft.Compute/virtualMachines/vm-test" 

 - What happened?
 ResourceGroup Value in the Virtual Machine "id" filed is in Capital Latter
 Here expectation is to return resourceGroups value in the Virtual Machine "id" filed is in small case (**_test-resource-group_**)  not in capital case (**_TEST-RESOURCE-GROUP_**)

-How can we reproduce it?
Use the code from
https://github.com/Azure/azure-sdk-for-go/blob/36f766d2feba70f64bed923c23b57602998e16c8/sdk/resourcemanager/compute/armcompute/virtualmachines_client_example_test.go#L7655
but with a real subscription.

```
RESPONSE 200 OK
{
            "properties": {
                 "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test-resource-group/providers/Microsoft.Compute/virtualMachines/vm-test"

                 ----  Rest of the Body -----
             }
}
```

**Comment by SaurabhSharma-MSFT** [comment]
@saheb-uptycs sorry for the delay.  I could see the same behavior and currently investigating.  I will update you as soon as possible. Thanks.

**Comment by techkiran406** [comment]
@SaurabhSharma-MSFT any update on this.

**Comment by TravisCragg-MSFT** [comment]
@saheb-uptycs We are aware of this issue, and unable to make the change at this time. I would recommend validating / changing the case of the RG name
