### ISSUE TITLE
azblob BlockBlobClient.UploadFile fails with broken connection errors for certain files

### ISSUE THREAD

**Issue by ben-east** [Azure/azure-sdk-for-go#20735]
### Bug Report

- importing `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- using `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.0.0` in `go.mod`
- `go version go1.20.3 linux/amd64`

- What happened?

BlockBlobClient fails uploads only for certain files, I believe based on their length. I've managed to capture an example file from our production environment and have isolated some minimal code that can reproduce it. The `Progress` function reports that the full size of the file is transferred before an error is returned. 

The errors come in 2 flavors -- one that reports a `ContentLength` of ~9 exabytes:

```
Put "https://MyStorageAccount.blob.core.windows.net/MyStorageContainer/MyTestFile.txt?blockid=NjMwYWZiMTItMGNkMi00NmI0LTU1MWItYjhmZjIxZGIxZDk0&comp=block": net/http: HTTP/1.x transport connection broken: http: ContentLength=9223372036456316927 with Body length 0
```

and another that reports a smaller `ContentLength`:

```
Put "https://MyStorageAccount.blob.core.windows.net/MyStorageContainer/MyTestFile.txt?blockid=ODcyNDBkZGItOGRhOC00YzYyLTc0YzItNDk5ZmVmZDdkNGJk&comp=block": net/http: HTTP/1.x transport connection broken: http: ContentLength=4194304 with Body length 4193321
```

- What did you expect or want to happen?

I expect the file to upload to blob storage successfully

- How can we reproduce it?

Generate a file with an unfortunate size -- for the case I'm examining, the file size is `398457897`. You can do a `fallocate -l 398457897 testfile.txt` if you'd like.

Here's some (messy) code that reproduces the issue reliably for me (you'll want to update the constants as appropriate for your testing): 

```
package main

import (
	"context"
	fmt "fmt"
	"log"
	"os"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
)

const (
	filepath = "/home/ben.east/workspace/testfile.txt"
	storageAccountName = "MyStorageAccount"
	storageContainerName = "MyStorageContainer"
)

func Upload(ctx context.Context, bucket string, key string, source string) (error) {
	credential, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		return fmt.Errorf("unable to get credential: %w", err)
	}

	storageAccountURL := fmt.Sprintf("https://%s.blob.core.windows.net/", storageAccountName)
	client, err := azblob.NewClient(storageAccountURL, credential, nil)
	if err != nil {
		return fmt.Errorf("failed to get storage account client: %s. %w", storageAccountName, err)
	}

	containerClient := client.ServiceClient().NewContainerClient(bucket)
	blobClient := containerClient.NewBlockBlobClient(key)

	sourceFile, err := os.Open(source)
	if err != nil {
		return fmt.Errorf("unable to open file: %w", err)
	}
	defer sourceFile.Close()

	uploadOptions := &azblob.UploadFileOptions{
		Progress: func(bytesTransferred int64) {
			log.Printf("transferred bytes %d", bytesTransferred)
		},
	}
	_, err = blobClient.UploadFile(ctx, sourceFile, uploadOptions)
	if err != nil {
		return fmt.Errorf("fail to upload blob: %w", err)
	}
	return nil
}

func main() {
	err := Upload(context.Background(), storageContainerName, "test/testfile.txt", filepath)
	if err != nil {
		log.Fatalf("failed to upload: %v", err)
	}
	log.Println("succeeded")
}
```

execute `go run main.go` and you should see the error

- Anything we should know about your environment.

This seems to occur only for certain files, and I believe it's related to the size of the file. I've been able to reproduce with a real artifact grabbed from our production environment, and again with a generated file of the same size.

**Comment by souravgupta-msft** [comment]
Hi @ben-east. Thanks for reporting this. I am able to reproduce this issue.
For now to unblock yourself you can set the block size to some value (say 4MB) in the UploadFileOptions. Meanwhile we will try to fix this.

**Comment by ben-east** [comment]
Thank you! Ran a variety of tests with `BlockSize` set, and was unable to reproduce the issue. I'll move forward with this for the time being.

**Comment by ben-east** [comment]
Thanks @souravgupta-msft! I may have delays before I can get around to testing this. Do you know when the changes are planned to be released? At a minimum, I'll pull the next release and validate against it.

**Comment by souravgupta-msft** [comment]
@ben-east we will do the next release of azblob somewhere around the second week of June.
