### ISSUE TITLE
Question: How can I only query the VMs' cost within a subscription?

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#20741]
https://github.com/Azure/azure-sdk-for-go/blob/f252cd9f178d89af5a3b0f595e72c8b1479904c7/sdk/resourcemanager/costmanagement/armcostmanagement/constants.go#L507

Can I only query the VMs's cost within a subscription through the armcostmanagement pkg?  Or can the API support something like below?

```
{
	Dimensions: &armcostmanagement.QueryComparisonExpression{
		Name:     to.Ptr("ResourceId"),
		Operator: to.Ptr(armcostmanagement.QueryOperatorTypeContains),
		Values: []*string{
			to.Ptr("microsoft.compute/virtualmachines")},
	},
},
```

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Could you please check if the below snippet helps ? 

```
Dimensions: &armcostmanagement.QueryComparisonExpression{
                            Name:     to.Ptr("ResourceType"),
                            Operator: to.Ptr(armcostmanagement.QueryOperatorTypeContains),
                            Values: []*string{
                                to.Ptr("Microsoft.Compute/virtualMachines"),
                        },
                    },
                },
            },
        },
```
[Reference](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/costmanagement/armcostmanagement#QueryComparisonExpression).

**Comment by xqi-aviatrix** [comment]
Thank you for answering the question @navba-MSFT 
I am going to close this issue
