### ISSUE TITLE
storage - implement PutBlockBlob API

### ISSUE THREAD

**Issue by kenegozi** [Azure/azure-sdk-for-go#208]
When uploading a smaller blob, it is much simpler in many cases to use the PutBlob API call with body (as described here https://msdn.microsoft.com/en-us/library/azure/dd179451.aspx)  and avoid the need for multiple requests uploading blocks and committing them.

Per the official documentation the upper limit is 64 MB ... A common scenario with much smaller sizes is uploading images and thumbnails to blob storage later to be served to browsers/clients.

**Comment by ahmetalpbalkan** [comment]
@kenegozi this is actually very similar to #129. What a user ideally wants is an API just uploads the blob whatever the size is.

I don't think we should provide two APIs such as `PutSingleBlockBlob` (the one that you described that accepts up to 64 MB) and a `PutBlockBlob` (described over at #129). Ideally there should be only one.

If you'd like to take a stab at it, there's a planned design at #129.

**Comment by kenegozi** [comment]
I appear as if the philosophy of the SDK is to avoid surprised, and map rest API calls to SDK methods. a PutBlockBlob should just call the PutBlob REST API with BlockBlob type and a body.

A helper that potentially magically break things down to multiple calls is super cool but belong in a separate, higher level package (blobutil is a good suggestion, similar to std package's 'io' and 'ioutil').

**Comment by ahmetalpbalkan** [comment]
@kenegozi Agree with your “no surprises” argument. IMO the problem with accepting a 1 GB blob and then transmitting that over the wire and seeing the REST call to fail might be a bit frustrating. On the other hand adding the 64 MB check to the client SDK is also one of the things we want to avoid (duplicating the validation).

But let's go with your idea, storage.PutBlockBlob and blobutil.PutBlockBlob and make it clear in the docs and refer from one to another in the comments?

**Comment by kpfaulkner** [comment]
Is this still desired? Have blobutil.PutBlockBlob that does the chunking and putList for you?

**Comment by kenegozi** [comment]
It's been a while, and I've been away from doing golang/azure work recently, so if you have a good way to provide the usage to users that you are happy with then this can be closed as "no thanks"
