### ISSUE TITLE
Add azureAdAuthenticationSettings to armsqlvirtualmachine.SQLVirtualMachine

### ISSUE THREAD

**Issue by almog-t** [Azure/azure-sdk-for-go#20806]
### Feature Request

I would like to be able to query the Azure AD Authentication state from SQL virtual machines using the SDK. I expected to find it under armsqlvirtualmachine.SQLVirtualMachine, like other fields in the SQL VM configuration, but it's not there at the moment. azureAdAuthenticationSettings is the field I'm interested in, part of the REST API specs since the 2022-08-01 version (see https://github.com/Azure/azure-rest-api-specs/blob/06bf50ba45fe22722dfc6340b58fe45a3a71f7c6/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/preview/2022-08-01-preview/sqlvm.json#L2105).

**Comment by navba-MSFT** [comment]
@almog-t Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@almog-t In the stable version [2022-02-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/stable/2022-02-01/sqlvm.json) we don't have `azureAdAuthenticationSettings `this attribute and it is currently in the `2022-08-01-preview` and `2023-01-01-preview `preview versions only.

@tadelesh Do we have the go SDK for the preview versions ?

**Comment by navba-MSFT** [comment]
@tadelesh I will follow-up with the service team and then check if I can create an SDK release request.

@almog-t In the meantime, As a workaround, you could try to leverage the [ClientOptions ](https://github.com/Azure/azure-sdk-for-go/blob/b96c5c011836554ff6229f1385c425340e1311e8/sdk/azcore/policy/policy.go#L31) with api-version `2023-01-01-preview`. 

```

type fixApiVersionTransporter struct {
	apiVersion string
	httpClient *http.Client
}

func (t *fixApiVersionTransporter) Do(req *http.Request) (*http.Response, error) {
	reqQP := req.URL.Query()
	reqQP.Set("api-version", t.apiVersion)
	req.URL.RawQuery = reqQP.Encode()

	return t.httpClient.Do(req)
}


ClientOptions: policy.ClientOptions{
			Transport: &fixApiVersionTransporter{
				apiVersion: "2023-01-01-preview",
				httpClient: http.DefaultClient,
			},
		},
```

**Comment by navba-MSFT** [comment]
@tadelesh Here is the SDK release request: https://github.com/Azure/sdk-release-request/projects/1766

@almog-t The release process is time consuming. So in the meantime, I would request you to follow the workaround suggested [here](https://github.com/Azure/azure-sdk-for-go/issues/20806#issuecomment-1562406472).

**Comment by navba-MSFT** [comment]
@almog-t The AzureAdAuthenticationSettings parameter is available in below routes for 2022-08-01-preview:

•	Python SDK - [https://learn.microsoft.com/en-us/python/api/azure-mgmt-sqlvirtualmachine/azure.mgmt.sqlvirtualmachine.models.aadauthenticationsettings?view=azure-python-preview](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpython%2Fapi%2Fazure-mgmt-sqlvirtualmachine%2Fazure.mgmt.sqlvirtualmachine.models.aadauthenticationsettings%3Fview%3Dazure-python-preview&data=05%7C01%7Cnavba%40microsoft.com%7Ce118cdedfd3448a3b00d08db618bda3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211025544526615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zJqXdEHWPlFK8ySBZttTQE4S5%2FIBM1EQGTFtZTeCqg8%3D&reserved=0)
•	Azure CLI - [https://learn.microsoft.com/en-us/cli/azure/sql/vm?view=azure-cli-latest#az-sql-vm-enable-azure-ad-auth-examples](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fcli%2Fazure%2Fsql%2Fvm%3Fview%3Dazure-cli-latest%23az-sql-vm-enable-azure-ad-auth-examples&data=05%7C01%7Cnavba%40microsoft.com%7Ce118cdedfd3448a3b00d08db618bda3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211025544682836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5ulOpg4DIo2nI8DDo59ANnlP8UC4X5tC8ziRh9Mgz5o%3D&reserved=0)
•	RESTful APIs - [https://github.com/Azure/azure-rest-api-specs/blob/389d3c2b3256fa48e3d78e07769907857b215536/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/preview/2022-08-01-preview/sqlvm.json#L2105](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2F389d3c2b3256fa48e3d78e07769907857b215536%2Fspecification%2Fsqlvirtualmachine%2Fresource-manager%2FMicrosoft.SqlVirtualMachine%2Fpreview%2F2022-08-01-preview%2Fsqlvm.json%23L2105&data=05%7C01%7Cnavba%40microsoft.com%7Ce118cdedfd3448a3b00d08db618bda3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211025544682836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Zb9gnpG1GpNdgIY7o%2BXyFOZYr6tdzf6FSKyYDLJwnxE%3D&reserved=0)

Could you please follow the above suggestion for now ?

**Comment by navba-MSFT** [comment]
@almog-t The Go package with tag package-preview-2022-08 has been released: [https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine@v0.9.0](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkg.go.dev%2Fgithub.com%2FAzure%2Fazure-sdk-for-go%2Fsdk%2Fresourcemanager%2Fsqlvirtualmachine%2Farmsqlvirtualmachine%40v0.9.0&data=05%7C01%7Cnavba%40microsoft.com%7Cebbce57319ab47dedb4008db61927a70%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211054023903402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hnKaRHuBUASaZr4jEkJgO3lk%2BAzGLYjVOUc85vuhUhU%3D&reserved=0).
