### ISSUE TITLE
NewThreatIntelligenceIndicatorClient.Delete always returns err=nil

### ISSUE THREAD

**Issue by hazcod** [Azure/azure-sdk-for-go#20805]
### Bug Report

Version: `github.com/Azure/azure-sdk-for-go/sdk/azcore v1.6.0`
Go version: `go version go1.20.4 darwin/arm64`
Import path: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/securityinsights/armsecurityinsights/v2`

I've noticed that `insights.NewThreatIntelligenceIndicatorClient.Delete` always returns `nil` as an error, even tough I am deleting using a non-existant TI indicator name. You would expect this to return an error.

The example code appends a random suffix to the name, which should fail the method:

```go
cred, err := azidentity.NewClientSecretCredential(s.creds.TenantID, s.creds.ClientID, s.creds.ClientSecret, nil)
if err != nil {
	return fmt.Errorf("could not authenticate to MS Sentinel: %v", err)
}

tiClient, err := insights.NewThreatIntelligenceIndicatorClient(s.creds.SubscriptionID, cred, nil)
if err != nil {
	return fmt.Errorf("could not create TI client: %v", err)
}

_, err := tiClient.Delete(ctx, s.creds.ResourceGroup, s.creds.WorkspaceName, *ti.Name+"21312312f", nil)
logger.Fatal(err)

// -> always nil
```

**Comment by hazcod** [comment]
(This was found during debugging because none of the TI items are being deleted)

**Comment by lirenhe** [comment]
@hazcod,  have you tried to use the Rest API to delete this indicator and what is the result?

**Comment by hazcod** [comment]
@lirenhe Seems to be a service thing:

```go

				var rawResponse *http.Response
				ctxWithResp := runtime.WithCaptureResponse(ctx, &rawResponse)

				_, _ := tiClient.Delete(ctxWithResp, s.creds.ResourceGroup, s.creds.WorkspaceName, "FOOBAR", nil)
				
				logger.Tracef("%+v", *rawResponse)

{Status:200 OK StatusCode:200 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Cache-Control:[no-cache] Content-Length:[0] Date:[Fri, 09 Jun 2023 07:05:53 GMT] Expires:[-1] Pragma:[no-cache] Server:[Kestrel] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Content-Type-Options:[nosniff] X-Ms-Correlation-Request-Id:[38b7730b-a853-4f92-ad09-2cbdcba4010a] X-Ms-Ratelimit-Remaining-Subscription-Deletes:[14999] X-Ms-Request-Id:[38b7730b-a853-4f92-ad09-2cbdcba4010a] X-Ms-Routing-Request-Id:[CANADACENTRAL:20230609T070553Z:38b7730b-a853-4f92-ad09-2cbdcba4010a]] Body:0x140005a9060 ContentLength:0 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0x140000c0000 TLS:0x14000284580}  module=sentinel_ti

```

**Comment by hazcod** [comment]
@lirenhe Hi, any update on this one?

**Comment by lirenhe** [comment]
> @lirenhe Hi, any update on this one?

I marked this item as 'Service Attention', but seems we didn't get any reply from service team.
As we confirmed this is a service bug,  could you create a support ticket?  https://azure.microsoft.com/en-us/support/create-ticket directly?

**Comment by hazcod** [comment]
I've created Azure support case 2306290040003041.

**Comment by hazcod** [comment]
Bug report still going back and forth without any progress fyi..

**Comment by hazcod** [comment]
Bug ticket was open for months with MS... and now it is automagically resolved.
