### ISSUE TITLE
Deprecation notice for armcompute.VirtualMachineSizeTypes but no alternative mentioned in armcompute.HardwareProfile

### ISSUE THREAD

**Issue by unmarshall** [Azure/azure-sdk-for-go#20841]
### Bug Report

**Package Versions as in go.mod of the test application:**
```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.5.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.2.2
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4 v4.2.1
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2 v2.2.1
```
**Go Version:**
`go version go1.20.1 darwin/arm64`

**What happened?**
There is a deprecation notice mentioned at [armcompute/constants.go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/constants.go#L2175). However [armcompute/models.go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/models.go#L3442-L3458) defines `HardwareProfile` which continues to use `VirtualMachineSizeTypes` and an alternative is not very clearly mentioned. 

We use the GO SDK to create VMs and for that we set VirtualMachineSizeType. The alternative that is provided in the [doctstring](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/constants.go#L2175) mentions the API to get all the available VM sizes or the list of available VM sizes which the given VM can be scaled to. However in our case we already know the VM size string and would just like to set this when creating the VM. 

Can you suggest an alternative for `VirtualMachineSizeTypes` as i do not see anything other than `VMSizeProperties *VMSizeProperties` that is available as part of `HardwareProfile`.

**What did you expect or want to happen?**
A deprecation notice should be followed by explaining how an alternative can be used. This is not very clear in our case.

**Comment by navba-MSFT** [comment]
@unmarshall Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@unmarshall You could leverage the **[VMSizeProperties type](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4#VMSizeProperties)** which represents the properties of a virtual machine size, including its name, number of cores, amount of memory, and so on.

**Comment by navba-MSFT** [comment]
@unmarshall Thanks for your reply. Apologies for the delay in getting back. If you already know the VM size string and would like to set it directly when creating the VM, you can still use the [HardwareProfile.VMSize](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#HardwareProfile) property and set it to the VM size string.

The VMSizeProperties type represents the properties of a virtual machine size, including its name, number of cores, amount of memory, and so on. It is used to get information about the available VM sizes or the list of available VM sizes which the given VM can be scaled to. However, it is not necessary to use this type if you already know the VM size string.

So, in your case, you can continue to use the VM size string and set it directly in **[HardwareProfile.VMSize](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#HardwareProfile)**. You do not need to do the mapping between the VM type alias to VCPUsAvailable and VCPUsPerCore.

**Comment by unmarshall** [comment]
Hello,

Thanks for your response and confirmation that we can continue to use `VMSize`. If this is always going to be supported then can you please either remove or reword the doc string which states that this is going to be deprecated and will be removed on Dec 23 2023? The reference is given to `VirtualMachineSizeTypes` which is the type for `VMSize` field.

Doc string in question:
```
// Specifies the size of the virtual machine.
// The enum data type is currently deprecated and will be removed by December 23rd 2023.
// Recommended way to get the list of available sizes is using these APIs:
// List all available virtual machine sizes in an availability set [https://docs.microsoft.com/rest/api/compute/availabilitysets/listavailablesizes]
// List all available virtual machine sizes in a region [https://docs.microsoft.com/rest/api/compute/resourceskus/list]
// List all available virtual machine sizes for resizing [https://docs.microsoft.com/rest/api/compute/virtualmachines/listavailablesizes].
// For more information about virtual machine sizes, see Sizes for
// virtual machines [https://docs.microsoft.com/azure/virtual-machines/sizes].
// The available VM sizes depend on region and availability set.
VMSize *[VirtualMachineSizeTypes](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#VirtualMachineSizeTypes) `json:"vmSize,omitempty"`
```

**Comment by navba-MSFT** [comment]
@unmarshall Thanks for your reply.

Adding Service team to confirm and update the docs (if need be).

**Comment by raych1** [comment]
> Adding Service team to confirm and update the docs (if need be).

Hi @Drewm3 , do you know who can help with the doc update?

**Comment by TravisCragg-MSFT** [comment]
@raych1  Please work with me for a doc update.

**Comment by TravisCragg-MSFT** [comment]
@unmarshall Please use the VM Size List APIs to get available SKUs for a region and your subscription. That is the path we are moving forward with, and new features will likely only be supported with that API.

**Comment by unmarshall** [comment]
@TravisCragg-MSFT As long as [HardwareProfile.VMSize](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#HardwareProfile) is available for us to use we would like to stick to using this directly. All the list of [HardwareProfile.VMSize](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#HardwareProfile) is already known to us.
