### ISSUE TITLE
Ability to specify the arm region hit by autogenerated sdks

### ISSUE THREAD

**Issue by OliverMKing** [Azure/azure-sdk-for-go#20891]
It would be good to have an option to specify the arm region hit by an autogenerated client.

When hitting the ARM url we can use `https://uksouth.management.azure.com/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/providers/Microsoft.DevHub/workflows?api-version=2022-04-01-preview` to specify that we want to hit the `uksouth` endpoint.

We have no way of doing this in the autogenerated clients. Here's a snippet of what I'd envision this looking like 

```Go
cred, err := azidentity.NewClientSecretCredential(a.tenantId, a.clientId, a.clientSecret, nil)
if err != nil {
	return nil, err
}

client, err := armdevhub.NewWorkflowClient(subscriptionId, cred, &opts{location: "uksouth"})
```

The key part would be the location option when creating the client. Alternatively, this could be added when making the request.

```Go
pager := client.NewListByResourceGroupPager(resourceGroup, &opts{location: "uksouth"})
```

**Comment by jhendrixMSFT** [comment]
You can do this today with cloud configuration.  The below code creates custom cloud configuration, copying from `cloud.AzurePublic`
```go
// create a new cloud configuration, copying from cloud.AzurePublic
azurePublicUKSouth := cloud.Configuration{
	ActiveDirectoryAuthorityHost: cloud.AzurePublic.ActiveDirectoryAuthorityHost,
	Services:                     map[cloud.ServiceName]cloud.ServiceConfiguration{},
}
armUKSouth := cloud.AzurePublic.Services[cloud.ResourceManager]
armUKSouth.Endpoint = "https://uksouth.management.azure.com"
azurePublicUKSouth.Services[cloud.ResourceManager] = armUKSouth

// create a client using the custom cloud configuration
client, err := armnetwork.NewPrivateEndpointsClient(subscriptionID, cred, &arm.ClientOptions{
	ClientOptions: azcore.ClientOptions{
		Cloud: azurePublicUKSouth,
	},
})
```
