### ISSUE TITLE
[AKS] configure AAD integration

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#2089]
@koalalorenzo in [2069#comment](https://github.com/Azure/azure-sdk-for-go/issues/2069#issuecomment-398852391):

> Since AKS went GA with new features, it would be nice to know if there is already the possibility to use the API to create a new AKS cluster with these new features (one of those is Azure Active Directory + RBAC).
>
> Is this a possibility? Is there already an API to deploy a kubernetes cluster with Azure Active Directory enabled?

I believe you'll need to follow instructions [here][4] to create the principal, then use the properties of that principal to populate the [ServicePrincipalProfile][1] within the [Properties][2] struct of [containerservice.CreateOrUpdate][3].

@NeilPeterson is the author of that article - Neil, is it possible to programmatically create the service principal with the properties described in that article? Thanks!

[1]: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice#ServicePrincipalProfile
[2]: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice#Properties
[3]: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice#ContainerServicesClient.CreateOrUpdate
[4]: https://docs.microsoft.com/en-us/azure/aks/aad-integration

**Comment by vladbarosan** [comment]
A couple things to add 
 - note that although AKS is GA this specific feature is in preview
 - a small correction to what @joshgav  linked, you need to configure [ManagedClusterProperties](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice#ManagedClusterProperties) and use the `enableRBAC` flag.

**Comment by neilpeterson** [comment]
I was able to hack together something using the Azure CLI, not sure it would be helpful or how it would translate to the go client.

Create the following file:

```
[
    {
      "resourceAccess": [
        {
          "id": "7ab1d382-f21e-4acd-a863-ba3e13f7da61",
          "type": "Role"
        },
        {
          "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
          "type": "Scope"
        },
        {
          "id": "06da0dbc-49e2-44d2-8312-53f166ab848a",
          "type": "Scope"
        }
      ],
      "resourceAppId": "00000003-0000-0000-c000-000000000000"
    },
    {
      "resourceAccess": [
        {
          "id": "311a71cc-e848-46a1-bdf8-97ff7156d8e6",
          "type": "Scope"
        }
      ],
      "resourceAppId": "00000002-0000-0000-c000-000000000000"
    }
  ]
```

Run this script:

```
#!/bin/bash

SERVER_APP=AKSAADServer036
SERVER_SECRET=P@ssword12
CLIENT_APP=AKSAADClient036

# Create AKS AAD sever app
SERVER_ID=$(az ad app create --display-name $SERVER_APP --identifier-uris http://$SERVER_APP --password $SERVER_SECRET --required-resource-accesses serverManifest.json --query appId -o tsv)
az ad app update --id $SERVER_ID --set groupMembershipClaims="All"

# Create AKS AAD client app
CLIENT_PERMS=$(cat <<EOF
[{"resourceAccess": [{"id": "318f4279-a6d6-497a-8c69-a793bda0d54f","type": "Scope"}],"resourceAppId": "$SERVER_ID"}]
EOF
)
CLIENT_ID=$(az ad app create --display-name $CLIENT_APP --native-app --required-resource-accesses "$CLIENT_PERMS" --query appId -o tsv)

# Get tenant ID
TENANT_ID=$(az account list --query [0].[tenantId] -o tsv)

echo "Client application ID: $SERVER_ID"
echo "Server application ID: $CLIENT_ID"
echo "Server application secret: $SERVER_SECRET"
echo "Tenant ID: $TENANT_ID"
```

@amanohar may know more.

**Comment by joshgav** [comment]
Thank you @neilpeterson! We'll try to turn that into Go code and add it to the samples repo in https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/197.

**Comment by joshgav** [comment]
related: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1429

**Comment by vladbarosan** [comment]
Closing this we are tracking the issue in the Samples repo Azure-Samples/azure-sdk-for-go-samples#197.

**Comment by lukasmrtvy** [comment]
@neilpeterson: You have to also do `az ad sp create --id $SERVER_ID` to assign SP to App
