### ISSUE TITLE
storage - allow setting headers on PutBlob request

### ISSUE THREAD

**Issue by kenegozi** [Azure/azure-sdk-for-go#209]
Add an argument to the PutBlockBlob call suggested in issue #208 to allow the user to set custom headers. The most important one is Content-Type, e.g. without this one images that are uploaded to blob storage cannot be treated as images by browser requests.

Since PutBlockBlob is a new API call on the SDK, it should be fine to add the trailing argument to it and not the others. Also the others can utilize the suggested #207 to set these headers, however the whole idea in this one (PutBlockBlob) is to allow a simple flow with a single API call.

**Comment by ahmetalpbalkan** [comment]
@kenegozi we can still break. Reiterating my comment on #208, we will come up with a non-existing method, so we can potentially get a `BlobProperties` parameter in the method.

Also, in case of block uploads and then commits with PutBlockList, the PutBlockList call also takes all those properties (such as x-ms-content-type, as you said) so we should probably add that parameter initially to `PutBlockList` (will be a breaking change, but fine for now) and the `PutBlockBlob` that'll come up can just make use of that change to `PutBlockList`.

How does this sound? Want to contribute?

**Comment by tomclegg** [comment]
This feature would make it possible to supply [conditional headers](https://msdn.microsoft.com/en-us/library/azure/dd179371.aspx), which I currently need to use with `DeleteBlob`. If an `addHeaders map[string]string` argument is going to be the way to do this, eventually we'll need it for every API method. Perhaps it should all get added to all methods at once?

**Comment by ahmetalpbalkan** [comment]
@tomclegg I doubt if this should be a map[string]string. I prefer to have it a type (just like BlobProperties) or perhaps since it's really common we can come up with something separate, like `AccessCondition` that also exists in C# Storage SDK (https://github.com/Azure/azure-storage-net/blob/f525e18b485f65577d5528f20437a79977b084c3/Lib/Common/AccessCondition.cs#L26) and plumb that all the way deep in the call stack to handle it centrally in one place. This will be a breaking change but it is okay.

I'm +1 for idea, my preference would be having a struct for this rather than a map. What do you think?

**Comment by kenegozi** [comment]
three possible solutions:

1. passing map[string]string (or map[string]interface{} and properly
dealing with dates)
    and providing consts for the various header values
pros: simplest solution to implement, minimal breaking changes, no
surprises and magic to users, forward-compatible with new headers, easy to
cover metadata as well
cons: less discoverability (although a set of consts such as
storage.BlobHeaderBlobType etc similar to http.Status... cover that)

2. (re?)using BlobProperties and writing manual or automatic code to
translate to/from Header
pros: more discoverability.
cons: many problems - see below

3. Providing a Fluent Builder   -
 blobClient.NewPutBlobRequest(cont,blob).ContentType("...").Meta("foo","bar").Send()
pros: most discoverable, minimal magic, easy to future-proof, easy to
suuport metadata
cons: more work, more breaking change.

my suggestion:

1. Do fluent builders, but first only support generic .Header(k,v) and
.Meta(k,v) possibly adding typed builders (such as ContentType) in a
non-breaking way going forward.
2. Provide a bunch of const for header names.
3. On the return value of GetBlob... return a derivative of a map, and then
start adding typed header-getters from it in a non-breaking manner.
4. specifically downloading a blob should not return a reader, but a struct
with a reader *and* headers map


How does this sound?


BlobProperties work well with the listing API that unmarshal xml, but is
not so great for the other operations.

I did a full change to take a struct and marshal it to/from headers on all
blob operations but I ended up giving up on it as it is too magical and
even clumsy.

you can see my experiment at
https://github.com/kenegozi/azure-sdk-for-go/tree/blob-props

some problems:

1. how to really model empty values - there sometimes is a distinction
between not setting a header, and setting it to a zero value. putting
pointers (or sql.NullString etc) is awkward.

1.a. especially on the Get side - you got back a struct, but not sure what
are actual values sent back and what are zero values of the struct.

2. new (or missing) headers - how do we deal with that?

3. Some operations has some headers some others do not. The general struct
could mislead users - you only get runtime errors and not compile errors.
Also some headers are read only (e.g. you cannot set ETag on a blob) - at
this point it is no better than a map with const keys

**Comment by brendandixon** [comment]
The generated parts of the SDK rely on https://github.com/Azure/go-autorest which uses Decorators (vs. Fluent) builders. Its model does allow for exactly this kind of request modification.

**Comment by tomclegg** [comment]
IMO built-in support for known headers would be great (proper `time.Time` types, func/field names instead of strings), and it should also be possible to set arbitrary headers. Having access to the `http.Request` somewhere along the way would let you log it, pass it to your own `http.Client` to `Do`, munge its URL, etc., in addition to setting headers. I suppose this would just have to be done in such a way that you can regenerate the Authorization header after changing other headers.

**Comment by ahmetalpbalkan** [comment]
@tomclegg I bet we can find such a place to do this in the existing model without changing a lot of things. A more pluggable/flexible model probably would require a bigger change. I'm open to both.

**Comment by kenegozi** [comment]
Auth headers could be added at the last minute (just before Do/Send/Execute)

Ken Egozi.
http://kenegozi.com/ <http://kenegozi.com/blog>
http://www.activegiver.com/

**Comment by ahmetalpbalkan** [comment]
Does anyone want to take a stab at it? If not I can try.

**Comment by Misterhex** [comment]
+1

**Comment by Misterhex** [comment]
#257

**Comment by vishrutshah** [comment]
Closing this one as it has been inactive for a while. Feel free to reopen if you find any issues. Thanks!
