### ISSUE TITLE
Azure Sql Server: VulnerabilityAssessmentsSettingsClient

### ISSUE THREAD

**Issue by lalivelor** [Azure/azure-sdk-for-go#20912]
### Service Package Request
Hi, looking for a way to use the VulnerabilityAssessmentsSettings API for Sql servers.
Specifically this struct: `VulnerabilityAssessmentState`.
A relevant API client is found [here](https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/preview/sql/mgmt/v5.0/sql/vulnerabilityassessmentssettings.go). However, this package is [deprecated](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/preview/sql/mgmt/v5.0/sql).
The [new armsql version ](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql) doesn't seem to have this option.

Any alternative would be much appreciated.
Thanks so much

**Comment by lirenhe** [comment]
@raych1, could you help to take a look?  Thanks

**Comment by raych1** [comment]
Hello @lalivelor , the [last armsql version](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql) doesn't include these APIs when released. 

We will release a new version this month which will include these APIs.

**Comment by lalivelor** [comment]
Hi @raych1 , I was wondering if you could share an updated ETA for the new release.
Thanks so much

**Comment by raych1** [comment]
@lalivelor , sorry for the delay. A breaking change was identified in the new version and we are working on the fix before release. We are still targeting the release by end of July.

**Comment by raych1** [comment]
@lalivelor , it was released by end of July. Let me know if there're still any questions.
