### ISSUE TITLE
armpolicy -- inconsistent & case-sensitive

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#20923]
consider a policy definition like 

```
{
	"id": "/providers/Microsoft.Management/managementGroups/somemg/providers/Microsoft.Authorization/policyDefinitions/A4C6C44C-3CE3-4A50-A280-513EEDCB78F2",
	"name": "A4C6C44C-3CE3-4A50-A280-513EEDCB78F2",
	"type": "Microsoft.Authorization/policyDefinitions",
	"properties": {
		"displayName": "limit Data Bricks workspaces SKUs",
		"metadata": {
			"Id": "A4C6C44C"
		},
		"parameters": {
			"effect": {
				"type": "string",
				"metadata": {
					"displayName": "Effect",
					"description": "The effect for this policy to take. e.g. Audit"
				},
				"defaultValue": "Audit",
				"allowedValues": [
					"Deny",
					"Audit",
					"Disabled"
				]
			},
			"allowedDbSku": {
				"type": "Array",
				"metadata": {
					"displayName": "SKU",
					"description": "Allowed SKUs for databricks workspaces."
				},
				"defaultValue": [
					"trial"
				],
				"allowedValues": [
					"trial",
					"standard"
				]
			}
		},
		"policyrule": {
			"if": {
				"allOf": [
					{
						"field": "type",
						"equals": "Microsoft.Databricks/workspaces"
					},
					{
						"field": "Microsoft.DataBricks/workspaces/sku.name",
						"NotIn": "[parameters('allowedDbSku')]"
					}
				]
			},
			"then": {
				"effect": "[parameters('effect')]"
			}
		}
	}
}
```

This is an invalid policy, since the `policyrule` is outside of the `properties` block

when you un-marshall this JSON using following go code

```
func parseDefinitionJSON(defJson string) (armpolicy.Definition, error) {

	defb, err := os.ReadFile(defJson)
	if err != nil {
		return armpolicy.Definition{}, errors.Wrap(err, "error while reading from file "+defJson)
	}

	// now parse the string

	var defns armpolicy.Definition

	err = defns.UnmarshalJSON(defb)
	if err != nil {
		return armpolicy.Definition{}, errors.Wrap(err, errPolicyDefnInvalidJSON.Error())
	}

	return defns, nil

}
```

this does not throw any error while un-marshaling.  

While the service (azure policy RET API) throws an error. (using something like azure github actions)

*Is there a way to validate the JSON before submitting to the API to create the policy definition?*

Additionally, it seems the field names are case-sensitive in go (while un-marshalling), but the service is case-in-sensitive

Example:
```
{
	"id": "/providers/Microsoft.Management/managementGroups/somemg/providers/Microsoft.Authorization/policyDefinitions/A4C6C44C-3CE3-4A50-A280-513EEDCB78F2",
	"name": "A4C6C44C-3CE3-4A50-A280-513EEDCB78F2",
	"type": "Microsoft.Authorization/policyDefinitions",
	"properties": {
		"displayName": "limit Data Bricks workspaces SKUs",
		"metadata": {
			"Id": "A4C6C44C"
		},
		"parameters": {
			"effect": {
				"type": "string",
				"metadata": {
					"displayName": "Effect",
					"description": "The effect for this policy to take. e.g. Audit"
				},
				"defaultValue": "Audit",
				"allowedValues": [
					"Deny",
					"Audit",
					"Disabled"
				]
			},
			"allowedDbSku": {
				"type": "Array",
				"metadata": {
					"displayName": "SKU",
					"description": "Allowed SKUs for databricks workspaces."
				},
				"defaultValue": [
					"trial"
				],
				"allowedValues": [
					"trial",
					"standard"
				]
			},
			"policyrule": {
				"if": {
					"allOf": [
						{
							"field": "type",
							"equals": "Microsoft.Databricks/workspaces"
						},
						{
							"field": "Microsoft.DataBricks/workspaces/sku.name",
							"NotIn": "[parameters('allowedDbSku')]"
						}
					]
				},
				"then": {
					"effect": "[parameters('effect')]"
				}
			}
		}
	}
}
```

here `policyrule` is all lower case instead of `policyRule`. When we parse the JSON, using the SDK, the field `Definition.Properties.PolicyRule` is nil, but if we go ahead and create this policy, using other tools, (like azure github policy actions), this policy gets created properly.

instead if this is set as `policyRule`, the JSON is parsed properly and `Definition.Properties.PolicyRule` has the proper field value in go SDK. 

The azure REST service seems to be able to cope with case-in-sensitivity, but GO SDK seems to enforce case-sensitivity.

**Comment by lirenhe** [comment]
@raych1, could you help to take a look?

**Comment by raych1** [comment]
Hello @vijayrajah , it's by design the unknown property is dropped off when Go sdk `un-marshall` a JSON string.

Both `swagger` and `Go Sdk` are case sensitive, as per the swagger definition `policyRule` needs to be matched in case to succeed the sdk call.

**Comment by vijayrajah** [comment]
> Both `swagger` and `Go Sdk` are case sensitive, as per the swagger definition `policyRule` needs to be matched in case to succeed the sdk call.

Then, why isn't azure github actions (with I think uses typescript), doesn't throw an error.

The issue is that this behavior, is in-consistent between the SDKs

**Comment by raych1** [comment]
@vijayrajah , REST api talks to service directly and service might support case insensitive. Can you share the details about github action where uses azure JS sdk?

**Comment by vijayrajah** [comment]
Hello @raych1  -- This is the github actions we are using 

https://github.com/Azure/manage-azure-policy

**Comment by raych1** [comment]
@vijayrajah  what I'm seeing in your referenced repo uses the `policyRule` in correct case format, e.g. [here](https://github.com/Azure/manage-azure-policy/blob/1ed950c25977c56949fee5ce2b07e6fd7aa47958/src/azure/policyHelper.ts#L166).
