### ISSUE TITLE
CosmosDB providers seems to not work with IN clause with string slice

### ISSUE THREAD

**Issue by marloncristian** [Azure/azure-sdk-for-go#20945]
### Bug Report

Version: `github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos v0.3.5`
Go Version: `go version go1.20.4 windows/amd64`
Import Path: `github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos`

I have been working on a project that heavily relies on the AzCosmos library to interact with Azure Cosmos DB, and it has been an excellent tool so far. However, recently I encountered a problem that appears to deviate from the library's intended functionality. I have thoroughly researched the issue and attempted various solutions, but unfortunately, I have been unable to resolve it on my own.

I have a simple query on my code that executes a filter using IN clause passing as parameter a []string:
```
  	ids := []string{ "a", "b" }
	query_ := cosmosdb.Q{
		Query:  "select * from c where c.id in (@ids)",
		Params: cosmosdb.P{"@ids": ids},
	}
```

It simply returns an empty set instead of the correct set I am expecting. The only way to bypass the issue so far is "Sprintf'out" the values into the query string. I genuinely appreciate your time and assistance in helping me resolve this issue.

**Comment by ealsur** [comment]
Seems like the JSON serialization for that query and parameters is:

```
{"query":"select * from c where c.id in (@ids)","parameters":[{"name":"@ids","value":["a","b"]}]}
```

The service does not seem to be responding as expected, we'll investigate

**Comment by ealsur** [comment]
Example code that would generate 1 parameter per value:

```
ids := []string{ "2", "1" }
opt := QueryOptions{
	QueryParameters: []QueryParameter{},
}

query := "select * from c where c.id IN ("

for i, id := range ids {
	paramName := fmt.Sprintf("@prop%d", i)
	query += paramName
	if i < len(ids) - 1 {
		query += ", "
	}

	opt.QueryParameters = append(opt.QueryParameters, QueryParameter{paramName, id})
}

query += ")"
```

**Comment by ealsur** [comment]
For cross-language reference, in C#, we have to do the same thing:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/387ab62dbb55bcc99491bf16b88a32ad1cd663a5/Microsoft.Azure.Cosmos/src/ReadManyQueryHelper.cs#L253-L264

**Comment by marloncristian** [comment]
Hey @ealsur 

I would like to express my sincere appreciation for your prompt response. Your quick action in addressing my concerns was crucial, and I am genuinely grateful for it. I understand that finding an elegant solution may not always be possible sometimes.

Thanks anyway
