### ISSUE TITLE
CopyFromURL fails with "409 The copy source must be a block blob"

### ISSUE THREAD

**Issue by flavianmissi** [Azure/azure-sdk-for-go#20942]
### Bug Report

package: `sdk/storage/azblob`
SDK version: `v1.0.0`
`go version go1.20.4 darwin/amd64`

#### What happened?
When trying to copy a blob (AppendBlob), I'm getting a `409 The copy source must be a block blob` with a `CannotVerifyCopySource` error code. 

#### What did you expect or want to happen?
I expected the blob to be copied

#### How can we reproduce it?
1. Create a blob of type AppendBlob
2. Copy it using `CopyFromURL`
3. You'll get an error

I wrote a test for it in github.com/distribution/distribution where you can see it happen ([tests](https://github.com/distribution/distribution/pull/3936/commits/0ed314ed25c8c7a146f916829bfe0811f2843bd5); [broken call to CopyFromURL](https://github.com/distribution/distribution/blob/97b1d649c4938d0f608d96454d6a8326b1f96acd/registry/storage/driver/azure/azure.go#L285)).
The interesting thing is that calling `CopyFromURL` from the append blob client instead of the block blob yields the exact same error. I found that using `StartCopyFromURL` works with either append or block blob clients.

#### Anything we should know about your environment.
This is happening in the [distribution image registry](github.com/distribution/distribution), which is the base for almost all registries out there.
There was a recent update of the azure-sdk-for-go, and that's when the code started breaking

**Comment by vibhansa-msft** [comment]
CopyFromURL works when block-blob is source. What you are trying to achieve is unsupported scenario from Azure Storage.

**Comment by flavianmissi** [comment]
How is one supposed to copy and append blob?

**Comment by souravgupta-msft** [comment]
You can use [StartCopyFromURL](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/appendblob/client.go#L306) for append blob as source.

**Comment by flavianmissi** [comment]
So basically, `NewAppendBlobClient(dst).CopyFromURL(ctx, src, nil)` is not expected to work when copying an append blob; but `NewAppendBlobClient(dst).StartCopyFromURL(ctx, src, nil)`, or even `NewBlockBlobClient(dst).StartCopyFromURL(ctx, src, nil)` both do work and are the expected way of doing it.

Could you expand on what's behind this behaviour? I understand that these are different API calls, but I cannot make sense of why Azure only allows append blob copy via the async API.
