### ISSUE TITLE
Get cloud config for go track2 sdk from resource manager endpoint

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#20959]
### Feature Request

In track2 go sdk, clould config can be fetched from resource manager endpoint. 

https://github.com/Azure/go-autorest/blob/c2958ac74c65c138045daa60f149c5f9d949d743/autorest/azure/metadata_environment.go#L96-L141

I'm wondering if there is any utility available in track2 go sdk with which we can easily fetch cloud config from resource manager endpoint. Thanks!

Background: https://github.com/kubernetes-sigs/cloud-provider-azure/ is migrating sdk from track1 to track2. 
cloud provider will accept a param which holds value of resource endpoint url. 

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/11f66ee392b34fe8958756188e5782ce6d448f91/pkg/provider/config/azure_auth.go#L76 

If the param is set, the cloud provider will fetch endpoint info from arm resource which is serving at resource endpoint url. 

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/11f66ee392b34fe8958756188e5782ce6d448f91/pkg/provider/config/azure_auth.go#L268-L274

This feature is feasible when the application is running in air-gap environment and azurestack environment.

**Comment by chlowell** [comment]
Track 2 doesn't have a helper like that. I don't see a reason not to add one. In the meantime, you can copy values from `EnvironmentFromURL` into a track 2 `cloud.Configuration` (see [this doc](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.6.0/cloud) for more about the API). Or, here's a sketch of a wholly track 2 solution:
```go
import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions"
)

res, err := http.Get("https://management.azure.com/metadata/endpoints?api-version=2019-05-01")
if err != nil {
	// TODO
}
body, err := io.ReadAll(res.Body)
if err != nil {
	// TODO
}
md := []struct{
	Authentication struct{
		Audiences []string
		LoginEndpoint string
	}
	Name, ResourceManager string
}{}
err = json.Unmarshal(body, &md)
if err != nil {
	// TODO
}
c := cloud.Configuration{
	ActiveDirectoryAuthorityHost: md[0].Authentication.LoginEndpoint,
	Services: map[cloud.ServiceName]cloud.ServiceConfiguration{
		cloud.ResourceManager: {
			Audience: md[0].Authentication.Audiences[0],
			Endpoint: md[0].ResourceManager,
		},
	},
}
client, err := armsubscriptions.NewClient(
	// TODO: credential,
	&arm.ClientOptions{ClientOptions: policy.ClientOptions{Cloud: c}},
)
```
