### ISSUE TITLE
Parse cloud config from config file in track2 go sdk

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#20964]
### Feature Request
In track1 sdk, AZURE_ENVIRONMENT_FILEPATH is supported. the end user can override endpoint value with the ones in custom config files.
When the AZURE_ENVIRONMENT_FILEPATH is not empty and is a file path, sdk will try to load the cloud config from file before creating new client instance. The [default endpoint value](https://github.com/Azure/go-autorest/blob/be633f7b83b41fc9bd41f4e99aa8664a9fa070fb/autorest/azure/environments.go#L96) will be overridden by the ones in config file if any. 

https://github.com/Azure/go-autorest/blob/be633f7b83b41fc9bd41f4e99aa8664a9fa070fb/autorest/azure/environments.go#L293-L331 

This feature is feasible when the app is running in hybrid cloud environment and arm requests are sent to ARM endpoint via proxies. In this scenario, the end user should customize the endpoint value .

**Comment by tadelesh** [comment]
Another ask from AKS team. IIRC, we have discussed it last year when we start to help ASK to do the migration. The answer is that AKS could do it easily and we will not provide it. I doubt if it is commonly used in track1. If so, maybe we could revisit this feature and to see whether we should add it or at least add some doc to help to do the migration.

**Comment by tadelesh** [comment]
@chlowell could you help to evaluate?

**Comment by chlowell** [comment]
I agree with your assessment--it's easy to implement in application code and probably an unpopular feature anyway, so I don't see value in adding it to azcore.

**Comment by MartinForReal** [comment]
Thanks for the update!
