### ISSUE TITLE
Add API to azcore.Client for shallow copying with new client name

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#20973]
I think it would look something like this.
```go
// WithClientName returns a shallow copy of the Client with its tracing client name changed to clientName.
//   - clientName - the fully qualified name of the client ("package.Client"); this is used by the tracing provider when creating spans
func (c *Client) WithClientName(clientName string) *Client { /*...*/ }
```
This is similar to how [`*http.Request.WithContext()`](https://pkg.go.dev/net/http#Request.WithContext) works.

**Comment by JeffreyRichter** [comment]
This is a public API exposed to customers?

**Comment by jhendrixMSFT** [comment]
The API is on the `azcore.Client` type which is not typically exposed to customers (SDK clients use internally use this).  However, since this client is our raw HTTP client "escape hatch" mechanism, in those scenarios, customers would see this API.

Since this is an exported type from `azcore` there's no way to avoid making the API exported.  However, we could probably do some type-aliasing magic so that the API shows up in the `runtime` package if we think exposing it in the "escape hatch" scenario is unwanted.
