### ISSUE TITLE
Feature Request: Support "Kafka Enabled" flag EventHub

### ISSUE THREAD

**Issue by Ycallaer** [Azure/azure-sdk-for-go#2099]
Hi,
Currently there is a flag "kafka enabled" on eventhub which is currently under global preview.
This flag is however not reflected in the Go sdk, blocking also the exposure through terraform.
Would it be possible to make this flag available in the SDK ?

Thank you

**Comment by joshgav** [comment]
@ShubhaVijayasarathy this seems to not be available in the API spec: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventhub/resource-manager/Microsoft.EventHub. Can you help? Thanks!

**Comment by joshgav** [comment]
related: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1417

**Comment by ShubhaVijayasarathy** [comment]
this is not a API specification. Enabling this flag, lets you talk to Event Hubs like you would talk to Apache Kafka. This means, the producers and consumers talking to Apache Kafka can now do the same with just configuration change with Event Hubs. This feature gives you the PaaS Kafka flavor in Azure. Here's more details on this - https://docs.microsoft.com/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview

**Comment by joshgav** [comment]
This depends on https://github.com/Azure/azure-rest-api-specs/pull/3294.

**Comment by vladbarosan** [comment]
@Ycallaer this is now available in v18 of the SDK https://github.com/Azure/azure-sdk-for-go/blob/v18.0.0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
