### ISSUE TITLE
how does one consume armresourcegraph QueryResponse

### ISSUE THREAD

**Issue by unmarshall** [Azure/azure-sdk-for-go#21004]
### Bug Report
- What happened?
As recommended we are now migrating to use [resourcegraph API](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph@v0.7.1). The API seems to work fine when i just print out the `ClientResourcesResponse.Data` but if i now want to iterate over rows/JsonObjectArray then i am currently not able to find a way or an example to do just that. The data type of `Data` is `any`.

I have checked the documentation links and each and every example is incomplete. 
Example (the list is not comprehensive):

- https://learn.microsoft.com/en-us/azure/governance/resource-graph/first-query-go
- https://learn.microsoft.com/en-us/samples/azure-samples/azure-cxp-developer-support/this-sample-code-uses-the-armresourcegraph-go-sdk-package-to-list-the-azure-mysql-db-resource-properties/
- All examples in https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph@v0.7.1#example-Client.Resources-BasicQuery
- There are also no unit tests which i could refer to (https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/resourcegraph/armresourcegraph). Only examples are given which does not contain code on how to even consume `Data`

All the examples fall short of how to extract values from `Data`. You cannot range over it because its not an iterable. You cannot cast it to a slice as that is not allowed and is also incorrect. I even tried to change the options via:
```go
Options: &armresourcegraph.QueryRequestOptions{
	ResultFormat: to.Ptr(armresourcegraph.ResultFormatObjectArray),
},
```
But since type of `Data` is `any` it becomes difficult to consume it.

- What did you expect or want to happen?
At least give one complete example on how to iterate either over table rows (if ResultFormat is set to `ResultFormatTable`) or consume `ResultFormatObjectArray`.

- How can we reproduce it?
Just use the resource graph query to return a result which has more than 1 rows.

- Anything we should know about your environment. 
```
Testing on MacOs Version 13.4
Golang Version 1.20.5
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph v0.7.1
```

**Comment by raych1** [comment]
Thanks @unmarshall for reporting this issue. 

I want to mention that SDK code is generated automatically, and the examples are all generated from the REST api examples. I would ask if service team could consider adding more REST API examples.

Actually, the example you referenced [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph@v0.7.1#example-Client.Resources-BasicQuery) includes the response example and how does the data look like. 

```go
// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.QueryResponse = armresourcegraph.QueryResponse{
	// 	Count: to.Ptr[int64](3),
	// 	Data: []any{
	// 		map[string]any{
	// 			"name": "myNetworkInterface",
	// 			"type": "microsoft.network/networkinterfaces",
	// 			"id": "/subscriptions/cfbbd179-59d2-4052-aa06-9270a38aa9d6/resourceGroups/RG1/providers/Microsoft.Network/networkInterfaces/myNetworkInterface",
	// 			"location": "centralus",
	// 			"tags":map[string]any{
	// 				"tag1": "Value1",
	// 			},
	// 		},
       //...
```

**Comment by unmarshall** [comment]
>I would ask if service team could consider adding more REST API examples.

It would be nice if you could give idiomatic ways to consume the response using `Go` as this repository is specifically for `Go` based SDK.
Also in [comment](https://github.com/Azure/azure-sdk-for-go/issues/21004#issuecomment-1587270285) i have pointed out some additional problems (lack of ease for consumers).

**Comment by raych1** [comment]
> It would be nice if you could give idiomatic ways to consume the response using `Go` as this repository is specifically for `Go` based SDK. Also in [comment](https://github.com/Azure/azure-sdk-for-go/issues/21004#issuecomment-1587270285) i have pointed out some additional problems (lack of ease for consumers).

@unmarshall , sdk code is generated automatically based on the swagger. Generated code has no idea of unmarshalling the `any` type.  The design change request needs the service team's response.

**Comment by unmarshall** [comment]
>The design change request needs the service team's response.

I thought this was more a question/comment for the design team and only an information for me. The generated code in this case has created consumption difficult. API responses should be typed or sufficient metadata information should be provided allowing the consumers to do proper casts (If a Cast is required then its a sign of design smell anyways).

For now I have figured out a way to consume the response (even though it does not look pretty). I will leave it to your judgement on how you see your own response type. If you do not see any issue then feel free to close the ticket.

**Comment by raych1** [comment]
I close this issue as you figured out the right solution. Thanks again for reporting this.
