### ISSUE TITLE
Update clientnames in azblob to be used correctly

### ISSUE THREAD

**Issue by siminsavani-msft** [Azure/azure-sdk-for-go#21023]
Placeholder issue to keep track of clientnames in azblob. Waiting on azcore release in July.

RE: https://github.com/Azure/azure-sdk-for-go/pull/20724#discussion_r1218695548

**Comment by jhendrixMSFT** [comment]
Depends on https://github.com/Azure/azure-sdk-for-go/issues/20973

**Comment by siminsavani-msft** [comment]
Fixed by #21188
