### ISSUE TITLE
NewDefaultAzureCredential is not using locally available Azure CLI credential

### ISSUE THREAD

**Issue by rchaganti** [Azure/azure-sdk-for-go#21029]
### Bug Report
Documentation of azidentity package indicates that the NewDefaultAzureCredential() attempts to authenticate via different mechanisms in the following order.
- Environment
- Workload Identity
- Managed Identity
- Azure CLI

However, it is not loading the locally available Azure CLI credentials.

## What happened?
```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

var subscriptionId = "5073fd1-21e034f70820"
var resourceGroup *armresources.ResourceGroup

func main() {
	azlog.SetListener(func(event azlog.Event, s string) {
		fmt.Println(s)
	})

	azlog.SetEvents(azidentity.EventAuthentication)

	cred, err := azidentity.NewDefaultAzureCredential(nil)

	if err != nil {
		log.Fatal(err)
	}

	clientFactory, err := armresources.NewClientFactory(subscriptionId, cred, nil)
	rgClient := clientFactory.NewResourceGroupsClient()

	ctx := context.Background()
	resourceGroupResp, err := rgClient.Get(ctx, os.Args[1], nil)
	if err != nil {
		log.Fatal(err)
	}

	resourceGroup = &resourceGroupResp.ResourceGroup
	jsonData, err := json.MarshalIndent(*resourceGroup, "\t", "\t")
	if err != nil {
		log.Fatalf("Failed to marshal resource group to JSON: %v", err)
	}
	fmt.Println(string(jsonData))
}
```

With the Azure CLI login within the local environment, the above program fails to use the local Azure CLI credentials.

```shell
$ go run azrg.go bicep
Managed Identity Credential will use IMDS managed identity
NewDefaultAzureCredential failed to initialize some credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
        WorkloadIdentityCredential: no client ID specified. Check pod configuration or set ClientID in the options
2023/06/18 21:01:40 DefaultAzureCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
--------------------------------------------------------------------------------
connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
--------------------------------------------------------------------------------
exit status 1
```
## What did you expect or want to happen?
I expected NewDefaultAzureCredential to load the local Azure CLI credentials.

## How can we reproduce it?
You can run the above program with a local Azure CLI login. When the program fails, change `NewDefaultAzureCredential` to `NewAzureCLICredential` to make it work.

## Anything we should know about your environment.
I am running this in a development container created using the following definition.
```json
{
	"image": "mcr.microsoft.com/vscode/devcontainers/base",
	"containerEnv": {
		"TZ": "Asia/Calcutta"
	},
	"customizations": {
		"vscode": {
			"settings": {},
			"extensions": [
				"golang.go",
				"ms-vscode.azure-account"
			]
		}
	},
	"features": {
		"ghcr.io/devcontainers/features/go:1": {
            		"version": "latest"
		},
		"azure-cli": {
			"version": "latest"
		}
	},
	"remoteUser": "vscode"
}
```
Thanks!

**Comment by chlowell** [comment]
`DefaultAzureCredential` tries to authenticate a managed identity before invoking the Azure CLI--that's the `GET http://169.254.169.254/metadata/identity/oauth2/token`. This apparently gets a 403 response in your dev container. `DefaultAzureCredential` doesn't go on to try the CLI after that because it can't know whether you expected managed identity authentication to succeed. I don't know how to configure a dev container such that this doesn't happen, but you can work around it in your code by using `AzureCLICredential` directly i.e., just call its constructor instead of `NewDefaultAzureCredential`:
```diff
-cred, err := azidentity.NewDefaultAzureCredential(nil)
+cred, err := azidentity.NewAzureCLICredential(nil)
```

**Comment by rchaganti** [comment]
> This apparently gets a 403 response in your dev container.

Yes. It is because the dev container is not running on Azure. It has no authentication context. 

> DefaultAzureCredential doesn't go on to try the CLI after that because it can't know whether you expected managed identity authentication to succeed.

Documentation gives a different impression. Here is what [the docs say](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash):
_"The DefaultAzureCredential type simplifies authentication by combining commonly used credentials types. It chains together type used to authenticate deployed Azure applications with credentials used to authenticate in a development environment."_

Looking at [the code](https://github.com/Azure/azure-sdk-for-go/blob/fb99a64943cb1d4594ce1e1bc0c0feeb90d083a8/sdk/azidentity/default_azure_credential.go#L110), it is appending to error messages, but not exiting. The very next check is for Az CLI creds. I may be missing something here but why / how does it exit before checking CLI creds?

**Comment by chlowell** [comment]
I think what you're missing is that `New*` functions are constructors that don't attempt to authenticate. In case that seems strange, the big reasons for this design are:
1. authentication usually requires network I/O, which we don't want constructors to do
2. whether authentication succeeds depends in part on its scope, which isn't known at construction

The docs, and my comments generally, focus on how `DefaultAzureCredential` behaves while authenticating, which it does in its `GetToken` method (clients call this method as necessary). `NewDefaultAzureCredential` collects error messages from other constructors so it can include them in a `GetToken` error, if authentication fails.

**Comment by rchaganti** [comment]
Thanks for the clarification, @chlowell. I see your point and understand this after looking at the constructor code. This can be closed.

**Comment by ottosulin** [comment]
We are seeing same issue when authenticating to Key Vault. The error is the same: 
`WorkloadIdentityCredential: no client ID specified. Check pod configuration or set ClientID in the options, ManagedIdentityCredential: managed identity timed out, AzureCLICredential: Azure CLI not found on path`

We're running Function Apps with custom handler using Managed Identity, and getting this error when running on Azure (i.e. not locally).

I tried changing the auth explicitly to `azidentity.NewAzureCLICredential` but that didn't help.

Here's the relevant part of our code:
```
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		return "", fmt.Errorf("failed to obtain a credential: %v", err)
	}

	client, err := azsecrets.NewClient(azv.VaultURI, cred, nil)
	if err != nil {
		return "", fmt.Errorf("unable to initialize Keyvault Client: %v", err)
	}

	vaultResponse, err := client.GetSecret(context.Background(), secretname, version, nil)
	if err != nil {
		return "", fmt.Errorf("failed to get secret \"%s\": %v", secretname, err)
	}
```

**Comment by chlowell** [comment]
> We're running Function Apps with custom handler using Managed Identity, and getting this error when running on Azure

Try using `ManagedIdentityCredential` directly i.e., call `azidentity.NewManagedIdentityCredential`. `DefaultAzureCredential` imposes a short timeout on managed identity authentication (the [troubleshooting guide](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/TROUBLESHOOTING.md#troubleshoot-defaultazurecredential-authentication-issues) has more details).

**Comment by ottosulin** [comment]
Will test that. After scouring through a lot of logs, it looks like they are actually getting the tokens eventually, but they are sometimes failing which could be caused by that short timeout.

**Comment by ottosulin** [comment]
Thanks @chlowell that worked!
