### ISSUE TITLE
Doc: NewDefaultAzureCredential example needs an update to reflect implementation

### ISSUE THREAD

**Issue by rchaganti** [Azure/azure-sdk-for-go#21030]
## What happend?
I followed the example @ https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#3-use-defaultazurecredential-to-authenticate-resourceclient to try out how authentication works when using the azidentity package.

```go
package main

// Import key modules.
import (
  "log"

  "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
  "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

// Define key global variables.
var (
  subscriptionId = "<subscription ID>"
)

// Define the function to create a resource group.

func main() {
  cred, err := azidentity.NewDefaultAzureCredential(nil)
  if err != nil {
    log.Fatalf("Authentication failure: %+v", err)
  }

  // Azure SDK Azure Resource Management clients accept the credential as a parameter
  client, _ := armresources.NewClient(subscriptionId, cred, nil)

  log.Print("Authenticated to subscription", client)
}
```
This example indicates that the error from the NewDefaultAzureCredential can be used to validate if client authentication is successful. However, as indicated by @richardpark-msft, the clients are lazily initialized, and the actual authentication is not tried until a call with context occurs. 

## What is expected?
I expect a documented way to find out if the client is authenticated or not.

**Comment by chlowell** [comment]
I agree the example is misleading. Here's a revised version:
```go
package main

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/subscription/armsubscription"
)

var subscriptionID = "<subscription ID>"

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		// TODO: handle error
	}
	// Azure SDK Azure Resource Management clients accept the credential as a parameter.
	// The client will authenticate with the credential as necessary.
	client, err := armsubscription.NewSubscriptionsClient(cred, nil)
	if err != nil {
		// TODO: handle error
	}
	_, err = client.Get(context.TODO(), subscriptionID, nil)
	if err != nil {
		// TODO: handle error
	}
}
```
@bobtabor-msft can you please update the article? (note I changed the ARM module so the example can show a simple client call that doesn't create or modify anything)

> I expect a documented way to find out if the client is authenticated or not.

You can simply call whatever client method(s) your application needs. Clients handle authentication internally and will return any authentication error.

**Comment by rchaganti** [comment]
Thank you, @chlowell.

**Comment by chlowell** [comment]
Thanks for opening this! We've published the revised article.
