### ISSUE TITLE
[azblob] how to configure FIPS only mode?

### ISSUE THREAD

**Issue by Slach** [Azure/azure-sdk-for-go#21047]
### Feature Request

I am trying to implement a FIPS compatible version of my software which supports Azblob as remote storage.

For AWS GO SDK v2, I can just set a `AWS_USE_FIPS_ENDPOINT` environment variable.
Have you something similar for Azure?

**Describe the solution you'd like**

explicit config option which will restrict ciphers list and TLS version from client side without recompilation with slow `GOEXPERIMENT=boringcrypto`

**Comment by vibhansa-msft** [comment]
As of now we do not have FIPS compliance. We can add this as a feature request to our backlog but unless there is a request from multiple customers for this, it will be on low priority only.
