### ISSUE TITLE
[azeventhubs] Allow specifying ContentEncoding in amqp messages via EventData

### ISSUE THREAD

**Issue by JakeDern** [Azure/azure-sdk-for-go#21046]
### Feature Request

Hello, it is my understanding that amqp messages have a ContentEncoding field in addition to ContentType that could be used for specifying things like compression. 

Through [EventData ](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#EventData) it is possible to specify ContentType, but not ContentEncoding which is also present in the [amqp annotated message properties](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#AMQPAnnotatedMessageProperties).

Can we extend it to include both? I can take a look at adding it myself if you're accepting contributions. Thanks!

**Comment by richardpark-msft** [comment]
We do intentionally keep EventData to a small set of properties, for simplicity. You'll want to use an AMQPAnnotatedMessage.

The code to do that is actually not that complicated. Probably the weirdest part is just knowing which field you want to insert your data payload into:

```go
&azeventhubs.AMQPAnnotatedMessage{
  Body: azeventhubs.AMQPAnnotatedMessageBody {
      Data: [][]byte{ yourDataSlice },
  }
}
```

And then inserting the properties into the right spots is pretty simple as well: [link](https://github.com/Azure/azure-sdk-for-go/blob/9c53d0f158c2e15112f501c2f0763d65f51fbbe1/sdk/messaging/azeventhubs/event_data.go#L80)

Your other option is also just to add in an `ApplicationProperties` and add in some data to include the equivalent info you want to include for the ContentEncoding. That way any downstream consumers can still just use the normal EventData class/struct without having to dive into the AMQPAnnotatedMessage.

**Comment by JakeDern** [comment]
Thanks for the quick response, we'll just use AMQPAnnotatedMessage like you suggested
