### ISSUE TITLE
Expose PolicyFunc util to public

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#21057]
### Feature Request

PolicyFunc  https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.6.1/internal/exported#PolicyFunc is useful when policy can be defined in one function. 

I'm wondering if we can add a type definition in policy package.

Thanks!

**Comment by jhendrixMSFT** [comment]
Closing per discussion on the PR.
