### ISSUE TITLE
[azfile] Az File Go SDK to support generation of SAS key from azidentity creds.

### ISSUE THREAD

**Issue by saisankargochhayat** [Azure/azure-sdk-for-go#21051]
### Feature Request
Today the only way we can create a SAS key is using a client using shared key - `NewClientWithSharedKeyCredential`
And use the same to create a SAS key for file share, however with the articles recommendation - https://learn.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys is to handle authentication via azidentity or managed identity in both cases we don't have support for SAS link creation.
It would be helpful to add that so that services don't need to handle shared key in service code and also the shared key support is in **deprecation** path.

**Comment by souravgupta-msft** [comment]
@saisankargochhayat, Azure Files does not have support for signing SAS using azidentity creds. You can only use Shared Key for creating SAS in azfile.

**Comment by souravgupta-msft** [comment]
Closing this as it is not supported by the service.
