### ISSUE TITLE
Multi-level log support

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#21055]
### Feature Request

It would be better if we could support multi-level loggers in azcore. e.g. adopting https://github.com/go-logr/logr

Scenario:

We need the following info for debugging purposes:
+ error message(error, v0)
+ client got invoked (info/v1)
+ number of retry attempt (debug /v2)
+ endpoint url(debug /v3)
+ payload content(debug /v4 )
+ credential tokens(debug /v5)

For general purpose, only v0-1 is set, 
For debugging purposes, v2-5 is set. 

Current implementation:
All of logs will be sent to log listener, and most of entries are not used. 
Auth tokens are sent to log listener if including bodies is set to true, which I think is not safe.

**Comment by tadelesh** [comment]
@jhendrixMSFT I found  some guideline for log level [here](https://azure.github.io/azure-sdk/general_azurecore.html#logging-policy). Could you help to evaluate this request?

**Comment by MartinForReal** [comment]
As I mentioned in issue description, following info are needed

+ error message(error, v0)
+ client got invoked (info/v1)
+ number of retry attempt (debug /v2)
+ endpoint url(debug /v3)
+ payload content(debug /v4 )
+ credential tokens(debug /v5)

In current implementation, I can get all the log entries or nothing. 

If I need to know whether the client has been invoked, "client got invoked" is all I need. But if I set the log listener, all of log entries will be sent to log listener. These log entries will consume a lot of space. If I set "includebody" to true, bearer token, exchange token, client secret will be sent to log listener. And I think it is not safe. 

And for custom policy(percall policy/ retry policy), logger is needed. It would be better if we can reuse the logger defined in azcore.  log generated by custom policy is needed only when the program behavior is not expected. 

With this feature, I can set verbosity to a higher level only when needed. And it won't generate too many log entries if everything goes well.

**Comment by jhendrixMSFT** [comment]
The problem with "log levels" is that the numeric assignment is arbitrary and left to the whims of the SDK authors.  Picking one at random from your list, why is "endpoint URL" a 3 and not a 1?  How does an SDK developer decide?  Furthermore, what SDK developers perceive to be "verbose" might not be verbose to all customers (and vice versa).  This is why we elected to go with a "logging event source" design; the event source indicates the kind of logging event, allowing application developers to decide which events are important to them to include in their logging (should they have the need to customize the listener).

I believe our current logging covers the majority of info in your bulleted list.  The only ones that I think are missing to some extent are "client got invoked" and "error message".  For the former, are you looking for the SDK client.method name that was called (e.g. "VirtualMachinesClient.BeginCreateOrUpdate() was called")?  For the latter, while we _should_ be logging some error conditions, I suspect there are gaps.  We also don't have a `Error` logging event.  Is there something specific you're looking for here?  Perhaps if an SDK API returns an error you want that sent to the log listener with an `Error` event type?

**Comment by MartinForReal** [comment]
I see. Thanks for the explanation! 

Yes! With "SDK client. Method name that was called" info, I can confirm that the client is processing the request. That is helpful for debugging. Error event is very helpful too!

**Comment by MartinForReal** [comment]
Can we expose github.com/Azure/azure-sdk-for-go/sdk/internal/log/log.  and add an event type for percall policy?
because the custom policy can share the same log structure.

**Comment by MartinForReal** [comment]
And in azidentity package, exchange tokens, bearer tokens and client secrets are not written to log unless with proper configuration.  They can be found in the response body which is not safe.
