### ISSUE TITLE
[armnetwork] support etag in network resources. 

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#21056]
### Service Package Request

Etag header is not added in network client. It will be very helpful if network client can generate etags header accordingly.

client consumers can put objects in cache and compare etag when needed. In this way, client consumer can reduce the number of arm requests.

**Comment by tadelesh** [comment]
@MartinForReal actually, we will generate response with etag header if srv has such definition in swagger. But I don't see it for network. Do you mean you need commonly support for etag/conditional request?

**Comment by MartinForReal** [comment]
Yes. Exactly!

**Comment by tadelesh** [comment]
@jhendrixMSFT @JeffreyRichter do we have plan to commonly support conditional request?

**Comment by MartinForReal** [comment]
I noticed that Etag and utils has been added to azcore package. But the etag struct is not used in network /compute client.

**Comment by MartinForReal** [comment]
related: https://github.com/Azure/azure-sdk-for-go/issues/21058

**Comment by jhendrixMSFT** [comment]
The service team is really in the best position to support this via their OpenAPI specs.  I don't see how we can automatically include this in generated code unless we knew that every operation for every RP had support for conditional requests.

**Comment by JeffreyRichter** [comment]
Most Azure services do not support conditional/etag headers and so our clients do not automatically emit support for them. For services that do support them, the service MUST declare this support in their swagger file(s) and then the code generator will emit automatically support for these headers.

**Comment by tadelesh** [comment]
Our SDK will honor service's swagger definition to support conditional request.
