### ISSUE TITLE
[azopenai] Embeddings type changes

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21073]
Feedback from @JeffreyRichter about the embeddings field:

> The Embedding field in [azure-sdk-for-go/sdk/cognitiveservices/azopenai/models.go is a slice of *float32; I think it should be a slice of *float64 instead.

**Comment by JeffreyRichter** [comment]
I'd actually prefer []float64 (no pointer). @jhendrixMSFT & I talked about having the generator remove the pointer from slices and want to make this change to the generator.

**Comment by richardpark-msft** [comment]
Latest autorest did get us to []float32's and (after chatting with other teams) float32 is the correct type.
