### ISSUE TITLE
azidentity.NewDefaultAzureCredential doesn't verify that az cli is configured with the correct cloud

### ISSUE THREAD

**Issue by simonmcc** [Azure/azure-sdk-for-go#21090]
### Bug Report

- import path of package in question
```
go 1.20

	github.com/Azure/azure-sdk-for-go/sdk/azcore v1.6.1 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.3.0 // indirect
```
- SDK version: `latest`
- output of `go version`: `go version go1.20.4 darwin/arm64`

- What happened?

When using `azidentity.NewDefaultAzureCredential()` with a client options block specifying `azure.USGovernmentCloud`, if we fall through to AzureCLI authentication, the AzureCLI isn't checked for being configured with the matching cloud.

- What did you expect or want to happen?

azidentity should warn about the clouds not matching, or allow the caller to update the AzureCLI config to match (by calling `az cloud set -n AzureUsGovernment` or `az cloud set -n AzureCloud` under the covers?)

- How can we reproduce it?

```
package main

import (
	"context"
	"fmt"
	"log"
	"os/exec"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud"
	azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

const (
	AzureUsGovernment_Subscription = "4d47ec28-1799-4c7b-9e34-81300079de6b"
)

func main() {

	azlog.SetListener(func(event azlog.Event, s string) {
		fmt.Println("azidentity: ", s)
	})
	azlog.SetEvents(azidentity.EventAuthentication)

	// manually set AzureCLI to AzureCloud
	set_cloud := exec.Command("az", "cloud", "set", "--name", "AzureUsGovernment")
	//set_cloud := exec.Command("az", "cloud", "set", "--name", "AzureCloud")
	stdout, err := set_cloud.Output()
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	fmt.Println(string(stdout))

	ctx := context.Background()

	// Interact with AzureUsGovernment
	opts := azcore.ClientOptions{Cloud: cloud.AzureGovernment}
	cred, err := azidentity.NewDefaultAzureCredential(&azidentity.DefaultAzureCredentialOptions{ClientOptions: opts})
	if err != nil {
		log.Fatal(err)
	}

	rgClientFactory, err := armresources.NewClientFactory(AzureUsGovernment_Subscription, cred, nil)
	if err != nil {
		log.Fatal(err)
	}

	rgClient := rgClientFactory.NewResourceGroupsClient()
	resultPager := rgClient.NewListPager(nil)

	resourceGroups := make([]*armresources.ResourceGroup, 0)
	for resultPager.More() {
		pageResp, err := resultPager.NextPage(ctx)
		if err != nil {
			break
		}
		resourceGroups = append(resourceGroups, pageResp.ResourceGroupListResult.Value...)
		log.Printf("Resource Group: %s", pageResp.ResourceGroupListResult.Value)
	}
	for resource := range resourceGroups {
		log.Printf("Resource Group Name: %s,ID: %s", resourceGroups[resource].Name, resourceGroups[resource].ID)
	}
}
```

- Anything we should know about your environment.

We have multiple deployments spread across AzureCloud & AzureUsGovernment, so switching between clouds is very comon for us.

**Comment by chlowell** [comment]
Thanks for opening this issue, it's an interesting case. We don't want azidentity to change Azure CLI configuration because that would make its behavior more difficult to reason about and would have mysterious, potentially dangerous side effects. For example, azidentity setting the CLI's cloud might get your Go application working and make your scripts target a different cloud. So, we simply leave all the details of authentication to the Azure CLI and let you configure it directly. The docs are mysterious on this point though, so I opened #21100 to clarify that `ClientOptions` here doesn't apply to the Azure CLI.
