### ISSUE TITLE
resourceGroupLocation

### ISSUE THREAD

**Issue by waytai** [Azure/azure-sdk-for-go#2109]
where  I can find resourceGroupLocation if am not westus ?
I can't find my resourceGroupLocation

**Comment by marstr** [comment]
There's a list of Azure Regions taht can be found here:  
https://azure.microsoft.com/en-us/global-infrastructure/regions/

If you are using the Azure CLI, you can get a list with a dynamically populated list of locations and API Versions supported by each Azure resource provider by running:

``` bash
az provider list
```

**Comment by vladbarosan** [comment]
@waytai does this solve your problem ?

**Comment by marstr** [comment]
Closing this out, because I believe it's been answered. :)
