### ISSUE TITLE
arm: Better debugging for json errors

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#211]
As seen in #210, it happens. 

We should append the body (to be decoded as json) as %q to the errors from the json package. Otherwise they'll be impossible to debug with just a "decoding failed" message.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Seems reasonable.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Noted and will add in next release.

**Comment by ahmetalpbalkan** [comment]
We don't close issues without fixing them.

**Comment by brendandixon** [comment]
@ahmetalpbalkan The latest release includes the JSON in error messages when parsing (or other) errors occur. Please take a look.

**Comment by ahmetalpbalkan** [comment]
Cool. (Fixed in #221)

**Comment by brendandixon** [comment]
Changes merged from PR #221
