### ISSUE TITLE
[azopenai] Model renames

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21106]
We have a few models that come from OpenAI that don't match our conventions in Azure. This is renaming/rearranging will affect all of the SDKs, so it's probably post beta.2.

> A new nits here (can be fixed later).
`ImageGenerationOptions` needs a better name, maybe something like `ImageGenerationSettings` (or perhaps `CreateImageSettings` so it aligns with `CreateImageOptions`). 
> And ideally, it would contain all required settings and the optional ones moved to `CreateImageOptions`.

_Originally posted by @jhendrixMSFT in https://github.com/Azure/azure-sdk-for-go/pull/21054#discussion_r1254982862_

**Comment by jhendrixMSFT** [comment]
Thinking more, our typical pattern is that all required params are discrete and only the optional ones are grouped.

**Comment by richardpark-msft** [comment]
Leaving this as-is for now, we're trying to do less changes from the default client at this point.
