### ISSUE TITLE
/github.com/azure-samples/azure-sdk-for-go-samples/quickstarts/deploy-vm$ go run main.go 

### ISSUE THREAD

**Issue by waytai** [Azure/azure-sdk-for-go#2110]
failed to create group: resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '47000f32-1714-4b72-b022-aa1b21cfa03f' could not be found."

**Comment by marstr** [comment]
Make sure to check your subscription ID. You can find this in the Portal or using the Azure CLI by running:

``` bash
az login
```
or 

``` bash
az account list
```

**Comment by waytai** [comment]
thank you I have changed azure.PublicCloud.ResourceManagerEndpoint to azure.ChinaCloud.ResourceManagerEndpoint
