### ISSUE TITLE
Support for CognitiveServices version 2023-05-01 

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-sdk-for-go#21103]
### Feature Request

There has been a stable api version [2023-05-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2023-05-01) has been released for cognitiveservices. Please include this in the SDK. So that we can use in the downstream terraform.
```[tasklist]
### Tasks
```

**Comment by lirenhe** [comment]
@jayendranarumugam, the CognitiveServices version 2023-05-01 will be released in this month.

One quick question, as terraform won't use the Go track 2 SDK, so will this release be helpful in the  downstream terraform?

**Comment by jayendranarumugam** [comment]
Hi @lirenhe, apologies for the confusion I just found that terraform is using their own SDK under https://github.com/hashicorp/go-azure-sdk and it seems this API version is already available at there. Would you like to close this issue or keep it open ?
