### ISSUE TITLE
Add support for Base64Url primary type in generator

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#2111]
We haven't implemented support for Base64Url types, we simply emit them as strings.  This leads to confusion about the contents of such fields, see https://github.com/Azure/azure-rest-api-specs/pull/3286 for an example.

**Comment by jhendrixMSFT** [comment]
Looks like keyvault data-plane swaggers are the only ones affected.

**Comment by chamons** [comment]
Today this is generated as:

```
// KeyOperationsParameters - The key operations parameters.
type KeyOperationsParameters struct {
	// REQUIRED; algorithm identifier
	Algorithm *JSONWebKeyEncryptionAlgorithm `json:"alg,omitempty"`

	// REQUIRED; an unpadded, url-encoded, base-64 string
	Value []byte `json:"value,omitempty"`
}
```

That is a []byte now, not a string as mentioned. @jhendrixMSFT does that make this fixed, or is there something deeper I'm missing?

**Comment by RickWinter** [comment]
This is fixed in track2 and will not be backported to the previous generator.
