### ISSUE TITLE
[azopenai] Get live test pipeline running

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21124]
We want to have some form of live testing for the azopenai package.

This'll work similar to how we did KeyVault HSM.

I believe what we need is:
- [ ] Create a KeyVault specifically for this pipeline that we can use to store the pre-determined secrets
- [ ] Hook up a pipeline YAML that uses those secrets, rather than relying on a bicep template.

There's an additional challenge that we occasionally throttle since some of the resources are over-subscribed. I plan on handling that using some "for live test only" retry policies.

**Comment by richardpark-msft** [comment]
CC: @benbp, this is the live test pipeline I was discussing with you earlier.

It will never create its own resources, we'll need to store some secrets and use them for the pipeline instead.

**Comment by benbp** [comment]
@richardpark-msft I created a keyvault/variable group for adding an openai subscription config(s) (I'll send details offline)

**Comment by richardpark-msft** [comment]
This is done. :)
