### ISSUE TITLE
feature: List VMs in a ScaleSet

### ISSUE THREAD

**Issue by piyushdatazip** [Azure/azure-sdk-for-go#21144]
### Feature Request

API to GET instances related to a VMSS is missing in the VMSS sdk. Though a lot of VMSS methods expect input of InstanceIDs I haven't found a way to get the InstanceIDs first.

```
subscriptions/{subscriptionID}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmss}/virtualMachines?api-version=2022-03-01&$expand=instanceView
```

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by hilaryw29** [comment]
Looking into this, thanks!

**Comment by piyushdatazip** [comment]
> Hi @piyushdatazip, List VMSS VMs - https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list?tabs=HTTP should return a list of all the virtual machines in your scale set, including their instance ids. Is this what you're looking for?

Yes, I've looked into this, did used the filter but it was not able to find the instanceIDs, empty response. (Feedback on this, Docs are not clear with example how exactly the filter has to be applied.) I read CLI code, and cli command `list-instances` uses a different endpoint which is same as UI as well, which I mentioned in the issue description.

**Comment by hilaryw29** [comment]
Hi @piyushdatazip, would you mind sharing the following info:

- Is your ScaleSet under Flexible orchestration mode? Or Uniform orchestration mode?
- Are you using the InstanceIds for Batch APIs? Or are you trying to perform start/stop operations on your VMs?
- Can you share the "List VMSS VMs" command you used to find the Instance Ids so I can troubleshoot on my side? You should not be getting empty Instance Ids.

Please note that you are expected to parse the InstanceId from the API payload. There isn't a way via API to only get a list of instance ids. However, here are some commands that might help you get what you're looking for:

If your scale set is in Uniform orchestration mode, try:

- CLI: `az vmss list-instances --resource-group <resourceGroupName> --name <scaleSetName> --output table`
- You can also extract InstanceId from your CLI results using the `--query` parameter (https://learn.microsoft.com/en-us/cli/azure/query-azure-cli?tabs=concepts%2Cbash)
- REST API: You do not need to use the $filter parameter, you will have to parse the payload for instanceId
`GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines?api-version=2023-03-01`

If your scale set is in Flexible orchestration mode, try:
- REST API: You do not need to use the $filter parameter, you can parse the payload for either "name" or "instanceId"
`GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines?api-version=2023-03-01`

**Comment by hilaryw29** [comment]
Hi @piyushdatazip, just checking if this was able to resolve your question? Let me know if there's anything else I can do to help. Thanks!

**Comment by piyushdatazip** [comment]
These are what already found, and I would strictly avoid making an api call since I am already working with SDK, against the coding norms followed in my team. 
Since CLI codebase has a separate function implementation to list down the instances related to VMSS, I would like to have similar in sdk too.

**Comment by piyushdatazip** [comment]
This is a blocker for many applications we want to implement in our system.

**Comment by hilaryw29** [comment]
Got it, engaging Go SDK team on this. Will share update as soon as we are able.

**Comment by piyushdatazip** [comment]
Thanks a lot for supporting on this issue @hilaryw29 !

**Comment by jhendrixMSFT** [comment]
@piyushdatazip which API in the Go SDK are you calling?

**Comment by jhendrixMSFT** [comment]
I think this is the API you want.  Can you please take a look and see if it works for you?

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5#VirtualMachineScaleSetVMsClient.NewListPager

**Comment by piyushdatazip** [comment]
Thanks @jhendrixMSFT this is what i've been looking for, thanks a lot for the time and help @hilaryw29
