### ISSUE TITLE
when using webAppClient in go sdk kind is nil

### ISSUE THREAD

**Issue by embonshai** [Azure/azure-sdk-for-go#21215]
### Bug Report

- github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appservice/armappservice/v2@v2.1.1
- go version go1.19 darwin/arm64

- What happened?
   I am interested to figure out whether a function app is code or container based.
   I am using the GetConfiguration sdk api to get the "kind" property and realize if its code/container from it but it returns nil value.
   When I execute the function app rest api: https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/{resource-group-name}/providers/Microsoft.Web/sites/{function-app-name}?api-version=2022-09-01
   I get the kind property with value: "functionapp,linux,container"

- What did you expect or want to happen?
  I expect that there will be a way via the api to understand if a function app is code/container based
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by navba-MSFT** [comment]
@embonshai Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@embonshai Please use the below sample snippet:

```
// main is the entry point of the program.
func main() {
	// Set the Azure subscription ID and other constants.
	subscriptionID = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	location := "West US"
	resourceGroupName := "RGName"
	FunctionAppName := "MyFuncAppName"

	// Check if the Azure subscription ID is provided; exit with an error if not.
	if len(subscriptionID) == 0 {
		log.Fatal("AZURE_SUBSCRIPTION_ID is not set.")
	}

	// Create an Azure credential for authentication.
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatal(err)
	}
	ctx := context.Background()

	// Get the resource using the getResource function.
	genericResource, err := getResource(ctx, cred)
	if err != nil {
		log.Fatal(err)
	}

	// Print the retrieved resource details.
	log.Println("Get resource ID:", *genericResource.ID)
	log.Println("Kind:", *genericResource.Kind)
	log.Println("Location:", *genericResource.Location)
	// log.Println("State:", *&genericResource.Properties)

}

// getResource retrieves information about a specific Azure resource.

func getResource(ctx context.Context, cred azcore.TokenCredential) (*armresources.GenericResource, error) {
	// Create a new Azure resource client.
	resourceClient, err := armresources.NewClient(subscriptionID, cred, nil)
	if err != nil {
		return nil, err
	}

	// Call the Get method on the resource client to retrieve the desired resource.
	resp, err := resourceClient.Get(
		ctx,
		resourceGroupName,
		resourceProviderNamespace,
		"/",
		resourceType,
		FunctionAppName,
		apiVersion,
		nil)
	if err != nil {
		return nil, err
	}

	// Return the retrieved resource information.
	return &resp.GenericResource, nil
}

```

**Comment by navba-MSFT** [comment]
@embonshai The action is pending on you try the above sample code. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
