### ISSUE TITLE
[azquery] Resource not found.

### ISSUE THREAD

**Issue by arorainms** [Azure/azure-sdk-for-go#21228]
### Bug Report

- azquery
- `latest`
 - go version go1.18.7 linux/amd64

- What happened? Trying to read LoadBalancer native platform metrics using the MetricsClient of azquery package. The code is running on AKS pod. The QueryResource method fails, and gives the error
```
GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx2/resourceGroups/xx/providers/Microsoft.Network/loadBalancers/xx/providers/Microsoft.Insights/metrics
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: NotFound
--------------------------------------------------------------------------------
{
  "code": "NotFound",
  "message": "Resource: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx2/resourceGroups/xx/providers/Microsoft.Network/loadBalancers/xx is not found"
}
```
- What did you expect or want to happen?  i expect the method to read the metrics from LoadBalancers and give the values, timestamp etc.
- How can we reproduce it? Sharing the snippet to read load balancer metrics
```
func QuerySnatMetrics(ctx context.Context, logger logging.VerboseLogger) {
	resourceURI := "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx2/resourceGroups/xx/providers/Microsoft.Network/loadBalancers/xx"

	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		handleMainFuncError(logger, "Unable to fetch creds %v", err, exitCodeSnatMetrics)
	}

	client, err := azquery.NewMetricsClient(cred, nil)
	if err != nil {
		handleMainFuncError(logger, "Unable to create metrics client %v", err, exitCodeSnatMetrics)
	}
    
	res, err := client.QueryResource(ctx, resourceURI,
		&azquery.MetricsClientQueryResourceOptions{
			Timespan:        to.Ptr(azquery.TimeInterval("PT5M")),
			Interval:        to.Ptr("PT1M"),
			MetricNames:     nil,
			Aggregation:     to.SliceOfPtrs(azquery.AggregationTypeAverage),
			Top:             nil,
			OrderBy:         to.Ptr("Average desc"),
			Filter:          to.Ptr("BackendIPAddress eq '*'"),
			ResultType:      nil,
			MetricNamespace: to.Ptr("Microsoft.Network/loadBalancers"),
		})

	if err != nil {
		handleMainFuncError(logger, "Unable to read snat metrics due to %v", err, exitCodeSnatMetrics)
	}

	// Print out metric name and the time stamps of each metric data point
	for _, metric := range res.Value {
		fmt.Println(*metric.Name.Value)
		for _, timeSeriesElement := range metric.TimeSeries {
			for _, metricValue := range timeSeriesElement.Data {
				logger.Printf("Metric TimeStamp: ", metricValue.TimeStamp.String())
			}
			for _, metadataValue := range timeSeriesElement.MetadataValues {
				logger.Printf("Backend IP Address: ", *metadataValue.Value)
			}
		}
	}
}
```
- Anything we should know about your environment. The code runs on a pod in Linux node of CBL Mariner image in AKS. It uses managed identity credential, the pod has environment variable of AZURE_CLIENT_ID set, and necessary access granted.

**Comment by arorainms** [comment]
Getting the same error on using AzureCliCredential on local. Double checked the resource id too. It is correctly provided.

**Comment by gracewilcox** [comment]
Hi @arorainms! 

I tested your code out on my machine with a load balancer resource id and also received the same 404 error. I think the issue is that the service returned an unclear error message, and the real problem is with your filter.

I believe you need to specify the specific metric name before you specify the filter since different metrics have different valid filters. I added a metric name and was able to get a successful query response. 

```go
res, err := client.QueryResource(context.Background(), resourceURI,
		&azquery.MetricsClientQueryResourceOptions{
			Timespan:        to.Ptr(azquery.TimeInterval("PT5M")),
			Interval:        to.Ptr("PT1M"),
			MetricNames:     to.Ptr("DipAvailability"),
			Aggregation:     to.SliceOfPtrs(azquery.AggregationTypeAverage),
			Top:             nil,
			OrderBy:         to.Ptr("Average desc"),
			Filter:          to.Ptr("BackendIPAddress eq '*'"),
			ResultType:      nil,
			MetricNamespace: to.Ptr("Microsoft.Network/loadBalancers"),
		})
```
More reading on load balancer metrics: 
* https://learn.microsoft.com/azure/load-balancer/load-balancer-monitor-metrics-cli
* https://learn.microsoft.com/azure/load-balancer/load-balancer-standard-diagnostics

Please let me know if this worked for you! Hope you have a great day!

**Comment by arorainms** [comment]
@gracewilcox, thanks for your prompt response.  
i sense a fix in documentation and [example code](https://github.com/Azure/azure-sdk-for-go/blob/1139a3bbd083a1ae68104afd8c17d22921d496aa/sdk/monitor/azquery/example_test.go#L231C4-L231C15).
As per it, the MetricName can be passed as nil.
Should the nil handling be done in azquery sdk to get the response for all the metrics? 
Can the SDK be improved to emit a proper error message?
Please let me know, what do you think?

**Comment by gracewilcox** [comment]
Hi @arorainms! Thank you for your feedback. Queries can fail for a variety of different reasons, so we won't be able to validate the query in the SDK itself. However, I do think our documentation can be improved so created an issue to track it.
