### ISSUE TITLE
azblob new version update Doc

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#21268]
Current `Readme.md` sample of doing `go get` does not have a version, hence `v1.0.0` is used

https://github.com/Azure/azure-sdk-for-go/blob/a4e183332f2a2d0cc0c9dcea1a0bb728e0731707/sdk/storage/azblob/README.md?plain=1#L37

Please update the docs to use `v1.1.0` (the current latest version)

Like
`go get github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v1.1.0`

**Comment by jhendrixMSFT** [comment]
Or `azblob@latest` so the version number doesn't become stale.

**Comment by souravgupta-msft** [comment]
azblob v1.1.0 is already published: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
`go get github.com/Azure/azure-sdk-for-go/sdk/storage/azblob` should ideally fetch the latest version of the package. If not, you can try the suggestion in the previous comment.
