### ISSUE TITLE
Use fake to do the mock test for mgmt. plane

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#21266]
1. Remove mock-service-host dependency
2. Manual change code
3. Change test generator to support
4. Change pipeline

**Comment by lirenhe** [comment]
In progress of 3,  @Alancere and @tadelesh, please follow up with the issue found.

**Comment by tadelesh** [comment]
Add one task: try to remove `nextLink` property for pageable operation payload in example to prevent infinite loop in fake.

**Comment by tadelesh** [comment]
Add one task: investigate and fix the logic for optional parameters in operation.
