### ISSUE TITLE
Armresourcehealth metadata client funcs return api version error

### ISSUE THREAD

**Issue by Nombyy** [Azure/azure-sdk-for-go#21270]
### Bug Report

 

 

- import path of package in question `sdk/resourcemanager/resourcehealth/armresourcehealth`

- SDK version `main`, `293e7f75c6a08aea5fab7e89a9ec2eb426fdcd6f`

- output of `go version`: `go version go1.19 darwin/arm64`

 

 

- What happened?

  - metadata client funcs produce an api version error:

    -  `"Failed to get status metadata: GET [https://management.azure.com/providers/Microsoft.ResourceHealth/metadata/status\n--------------------------------------------------------------------------------\nRESPONSE](https://management.azure.com/providers/Microsoft.ResourceHealth/metadata/status/n--------------------------------------------------------------------------------/nRESPONSE) 404: 404 Not Found\nERROR CODE: InvalidResourceType\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"InvalidResourceType\",\n    \"message\": \"The resource type 'metadata' could not be found in the namespace 'Microsoft.ResourceHealth' for api version '2022-10-01'. The supported api-versions are '2018-07-01,2018-07-01-rc,2018-07-01-preview,2018-07-01-beta,2018-07-01-alpha'.\"\n  }\n}\n--------------------------------------------------------------------------------\n"`

  - Potentially related to version being set e.g. https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/resourcehealth/armresourcehealth/metadata_client.go#L77

- How can we reproduce it?

  - Try to make calls using the metadata client e.g. https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/resourcehealth/armresourcehealth/metadata_client_example_test.go

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by raych1** [comment]
> Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @stephbaron.

It appears that the above github account doesn't have an MS account linked. 

I confirmed that metadata endpoint isn't registered in backend arm manifest for 2022-10-01 version.

+@abhayohri to help on this issue.

**Comment by abhayohri** [comment]
Ack looking into this

**Comment by abhayohri** [comment]
the metadata endpoint is now available for the 2010-10-01 api version

**Comment by Nombyy** [comment]
Thanks @abhayohri ! Verified that the SDK works for the endpoint now.
