### ISSUE TITLE
arm: Add User-Agent header to queries

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#213]

**Comment by brendandixon** [comment]
@ahmetalpbalkan See my comments on #212

**Comment by brendandixon** [comment]
@ahmetalpbalkan The issue is addressed in the latest. Please take a look.

**Comment by ahmetalpbalkan** [comment]
We can close this now. Pardon my ignorance, what do we return as UA string now? :-)

**Comment by brendandixon** [comment]
Changes merged from PR #221

**Comment by brendandixon** [comment]
Each package sets the UA string to:

Azure-SDK-for-Go/%s;Package/%s;API/%s

With the semantic version filling the first %s, the package name the second, and the API version the third. For example:

"Azure-SDK-for-Go/0.1.0-beta;Package/authorization;API/2015-01-01

**Comment by ahmetalpbalkan** [comment]
Hmm there's no mention of arm here. in this case wouldn't arm/storage potentially collide with storage/?

**Comment by brendandixon** [comment]
@ahmetalpbalkan Ah, good point! I'll get a new PR ready. It'll be the same that lights up golint / govet Travis for the ARM packages.

**Comment by brendandixon** [comment]
Change added a while ago. Closing.
