### ISSUE TITLE
postgres 10 support

### ISSUE THREAD

**Issue by featheredtoast** [Azure/azure-sdk-for-go#2130]
Azure supports version 10 of Postgres, but currently this is not supported via this sdk. Please allow "10" as a valid postgres version parameter.

**Comment by vladbarosan** [comment]
Hi @featheredtoast the specs have not been updated to reflect that the new version is available. We will reach out to the service team for that.

Meanwhile, the underlying type of the `ServerVersion` is a string, can you try to just specify version `10.0` ?

**Comment by featheredtoast** [comment]
Hi @vladbarosan thanks for the quick response - I should note I'm trying to trace this issue through [Terraform](https://github.com/terraform-providers/terraform-provider-azurerm) and it appears to be depending on the azure-sdk lib to determine valid input.

For reference, Terraform reports the following:

`Error: azurerm_postgresql_server.server: expected version to be one of [9.5 9.6], got 10.0`.

**Comment by vladbarosan** [comment]
@featheredtoast oh I see. Looking at it, https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_postgresql_server.go#L123 seems to validate strictly against the enum. 

@tombuildsstuff is there a way to disable that validation function ?

**Comment by featheredtoast** [comment]
Thanks for pointing me in the right direction @vladbarosan - I've sent a PR to the Terraform provider plugin that allows a version specified as "10.0" here which should help alleviate things until enums are available: https://github.com/terraform-providers/terraform-provider-azurerm/pull/1457

**Comment by vladbarosan** [comment]
@featheredtoast this is now available in the `latest` branch. This will be present in our next minor release if no breaking change is coming .

https://github.com/Azure/azure-sdk-for-go/blob/latest/services/postgresql/mgmt/2017-12-01/postgresql/models.go#L125

**Comment by vladbarosan** [comment]
This is available in [v18.1](https://github.com/Azure/azure-sdk-for-go/blob/v18.1.0/services/postgresql/mgmt/2017-12-01/postgresql/models.go#L125)
