### ISSUE TITLE
Metrics for Azure

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#2131]
Hi 

This is probably/definitely the wrong place to ask but I can't figure anywhere better. I'm trying to get CPU/Memory stats for app services via Go. I'm assuming this repo/sdk doesn't cover this,  am I right?  If so, any suggestions on another repo might hold the answers?

Again, sorry for spam but unsure where else I can ask.

Ken

**Comment by jhendrixMSFT** [comment]
Hello @kpfaulkner, is this what you're looking for?
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2018-02-01/web/appserviceenvironments.go#L2692

**Comment by kpfaulkner** [comment]
Started using a similar method for app service plans.
I cannot get the filter working for the life of me. I cant leave it blank/empty-string. If I try something that I *think* should work, "(name.value eq 'CpuPercentage')" then it seems to hang on the 

resp, err := client.ListMetricsSender(req)

line.

One thing (no idea if related) I've noticed the SDK has a hardcoded api-version that isn't valid for the region I'm using (southeastasia). The SDK currently has 2018-02-01 which isn't valid for the region. For the moment I've hardcoded the latest version that IS suitable for the region, but unsure if there is a way to override it (I dont believe there is).

**Comment by jhendrixMSFT** [comment]
There is an older API version available however I don't know if it's supported in your region.
https://github.com/Azure/azure-sdk-for-go/tree/master/services/web/mgmt/2016-09-01/web
Let me know if that doesn't help and I'll loop in some folks from the service.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT sorry to bundle onto this issue, but is there a timeframe for GA API's being rolled out to all supported regions?

Given this new API version's been out (e.g. not in Preview) for 4 months - IMO it's not great that it's still not fully rolled out across all supported (existing) regions; I'm specifically thinking in the context of when we should be adopting new API versions and how this errors presented to users.

Thanks!

**Comment by kpfaulkner** [comment]
Hi

Ended up rolling my own code for getting the metrics. Will check out the older version of the SDK.

Cheers

Ken

**Comment by jhendrixMSFT** [comment]
@ruslany is this something you can answer?  I dug up your name from github history in the specs repo.
CC @joshgav

**Comment by kylebrandt** [comment]
I played some with the SDK today also in hopes in being able to query various metrics. Some issues I've run into:

- Not really a Go thing. I don't understand the term "insights" in the Azure world. Basic queries I see from inspecting Grafana's Azure data source have `microsoft.insights` in the url for things that are just "Azure Metrics"? Should all metrics one would see in Azure's portal be queryable using `services/[prieview]/mgmt/2018-03-01/insights`?
 - When I create a NewMetricsClient with a Subscription ID and the example LogRequest functions, I don't see the subscription in the URI being dumped when I try to call `c.List`, it seems to start with the resourceURI argument of list instead. 

Would it be possible to get an example of querying something common, like a cpu metric on a VM in a resource group, or perhaps translate some examples from https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-rest-api-walkthrough? Having an example might help me sort out if I'm running into possible bugs or just my own confusion.

**Comment by kylebrandt** [comment]
I was able to get a basic call working this morning. Some code snippets (sloppy since currently just sketching, but it gets a resposne) in case it helps someone:

```
// GetAzureMonitorContext returns a Azure Monitor API context which
// contains the information needs to query the azure API
func (sc *SystemConf) GetAzureMonitorContext() insights.MetricsClient {
	c := insights.NewMetricsClient(sc.AzureMonitorConf.SubscriptionId)
	c.RequestInspector = LogRequest()
	c.ResponseInspector = LogResponse()
	ccc := auth.NewClientCredentialsConfig(sc.AzureMonitorConf.ClientId, sc.AzureMonitorConf.ClientSecret, sc.AzureMonitorConf.TenantId)
	at, err := ccc.Authorizer()
	if err != nil {
		log.Fatal("azure conf: ", err)
	}
	c.Authorizer = at
	return c
}
```

```
func AzureQuery(e *State, T miniprofiler.Timer, query string) (r *Results, err error) {
	c := e.Backends.AzureMonitor
	// TODO fix context
	ctx := context.Background()
	fmt.Println(c.SubscriptionID)
	tg := "PT1M"
	z, err := c.List(ctx, "/subscriptions/<NY-SUB-ID>/resourceGroups/<MY-RESOURCE-GROUP-NAME>/providers/Microsoft.Compute/virtualMachines/<VM-NAME>",
		"2018-07-17T19:15:58Z/2018-07-17T20:15:58Z",
		&tg,
		"Percentage CPU",
		"Average",
		nil,
		"asc",
		"",
		insights.Data,
		"Microsoft.Compute/virtualMachines")

	fmt.Println(err)
	fmt.Println(z)
	return nil, nil
}
```

**Comment by jhendrixMSFT** [comment]
Regarding the hang, I wrote a repro for this and what I observe is the server sends back an HTTP 500 with an XML response body.  However we expect JSON in the response, so we don't detect the service returned an actual error object so the runtime treats this as a transient 500 and attempts to retry the request.

**Comment by kpfaulkner** [comment]
@jhendrixMSFT I ended up still using my hand rolled stuff but purely because I got that working and it was "good enough". Once I get a little bit of spare time (mythical stuff at the moment) I'll go back to investigating the SDK again.

Summary of current code is:

endTime := time.Now().UTC()
startTime := endTime.Add(time.Duration(-5) * time.Minute)
myURL := fmt.Sprintf("https://management.azure.com/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Web/serverFarms/%s/providers/microsoft.insights/metrics?timespan=%s/%s&metricnames=CpuPercentage&api-version=2018-01-01", subscriptionID, resourceGroup, appServicePlan, startTime.Format("2006-01-02T15:04:05Z"), endTime.Format("2006-01-02T15:04:05Z"))

preparer := autorest.CreatePreparer(
	autorest.AsGet(),
	autorest.WithBaseURL(myURL),
	a.WithAuthorization())

ctx := context.Background()
req, err := preparer.Prepare((&http.Request{}).WithContext(ctx))
client := &http.Client{}
res, err := client.Do(req)

**Comment by jhendrixMSFT** [comment]
@kpfaulkner thanks this is super helpful.  I believe the SDK API for this is here: https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/monitor/mgmt/2018-03-01/insights/metrics.go#L66
The one I pointed to in the ```web``` package appear to be broken so I don't think you'll have much luck with them, I'm following up on that separately.

**Comment by kylebrandt** [comment]
Used the SDK to add Azure metrics support for Bosun. Still an experimental feature so subject to change, but so far it seems to be working. Most of the code is in https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/azure.go and some client creation in https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/conf/system.go in case that helps someone

I don't really know what I am doing with the imports, I just ended up with some imports that seem to be working :P

**Comment by jhendrixMSFT** [comment]
I've opened https://github.com/Azure/azure-rest-api-specs/issues/3621 to track getting the issue with the APIs in the ```web``` package fixed.

**Comment by jhendrixMSFT** [comment]
I've created a small sample using the ```monitor/insights``` package for retrieving metric data, hopefully somebody finds it useful.
https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/222
