### ISSUE TITLE
Track 2 SDK, `ParseResourceType` func doesn't support management group scoped provider

### ISSUE THREAD

**Issue by ms-henglu** [Azure/azure-sdk-for-go#21319]
### Bug Report

- import path of package in question: "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
https://github.com/Azure/azure-sdk-for-go/blob/28771743d1a87b2362aadce96177fce406b502fd/sdk/azcore/arm/internal/resource/resource_type.go#L85

- SDK version: latest
- output of `go version`: go version go1.19.3 darwin/arm64

- What happened?

Input: /providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network

Output: error invalid resource ID: /providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network

- What did you expect or want to happen?

This should be a valid ID for type `Microsoft.Resources/providers`
refs: https://github.com/Azure/azure-rest-api-specs/blob/e680f9bf4f154ec427ba7feac432ed8efd9665d0/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L2053

- How can we reproduce it?

```go
import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)


id := "/providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network"
resourceType, err := arm.ParseResourceType(id)

```

- Anything we should know about your environment.

**Comment by lirenhe** [comment]
@raych1, could you help to take a look?

**Comment by raych1** [comment]
@ArcturusZhang , from the referenced spec - https://github.com/Azure/azure-rest-api-specs/blob/e680f9bf4f154ec427ba7feac432ed8efd9665d0/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L2053, `/providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/register` is a valid resource id but failed in parsing. Can you confirm?

**Comment by teowa** [comment]
Same error for `/subscription/00000000-0000-0000-0000-000000000000/Microsoft.Network`, from https://github.com/Azure/azure-rest-api-specs/blob/e680f9bf4f154ec427ba7feac432ed8efd9665d0/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L2262, shoud be a valid resource id but failed in parsing.

**Comment by raych1** [comment]
Feel free to re-open this issue if needed.

**Comment by teowa** [comment]
Hi @raych1 , can we reopen this one? Incorporating support for parsing the Resource Provider is crucial as it's extensively utilized within Azure. The [Provider REST API](https://learn.microsoft.com/en-us/rest/api/resources/providers?view=rest-resources-2021-04-01) offers a range of endpoints that the Azure Portal, Azure CLI, and Azure PowerShell frequently rely on:
```
https://management.azure.com/providers/{resourceProviderNamespace}
https://management.azure.com/subscriptions/{subscriptionId}/providers/{resourceProviderNamespace}
https://management.azure.com/providers/Microsoft.Management/managementGroups/{groupId}/providers/{resourceProviderNamespace}
```

Enabling this functionality is pivotal as it will remove obstacles when managing Providers within Golang-based projects.
