### ISSUE TITLE
EventGrid: Unable to Publish Cloud Events due to `ResourceNotFound` error

### ISSUE THREAD

**Issue by lthela2** [Azure/azure-sdk-for-go#21349]
I am trying to publish the CloudEvents to EventGrid but I am seeing the below error for any EventGrid I use:

```
"details": [
      {
        "code": "ResourceNotFound",
        "message": "No HTTP resource was found that matches the request URI 'https://lthela-test.westus-1.eventgrid.azure.net/api/events/topics/lthela-test:publish?api-version=2023-06-01-preview'. Report '4e8fff7a-06dc-4738-ad90-989d624c3ecf:8/10/2023 6:47:45 PM (UTC)' to our forums for assistance or raise a support ticket."
      }
    ]
```

I am currently migrating to EventGrid track2 SDK from Autorest and I am seeing the above error. We did not see such errors while we were publishing Event Grid events using Api version 2018-01-01.

Below is the code:
```
eventGridTopicEndpoint := "https://lthela-test.westus-1.eventgrid.azure.net/api/events"
topicKey := ""
publisherClient, err := azeventgrid.NewClientWithSharedKeyCredential(eventGridTopicEndpoint, topicKey, nil)

if err != nil {
	fmt.Println("error creating publisher client", err)
	return
}

_, err = publisherClient.PublishCloudEvents(context.TODO(), "lthela-test", []messaging.CloudEvent{}, nil)

if err != nil {
	fmt.Println("error publishing cloud events", err)
	return
}
```

Am I missing something? Is something wrong with my code?
```[tasklist]
### Tasks
```

**Comment by richardpark-msft** [comment]
Hi @lthela2, 

To confirm - our azeventgrid package currently only works with the new "Pull-based delivery" functionality in EventGrid. [(link)](https://learn.microsoft.com/en-us/azure/event-grid/pull-delivery-overview#pull-delivery-1).

This is a separate product from the current EventGrid product, which (based on your autorest comment) is what I assume you're using.

Is that correct?

**Comment by lthela2** [comment]
Are you asking if it is a push-based delivery? 
The autorest client did not include "/topics/{topicName}:publish" url path. Even in the REST API the endpoint for PublishCloudEvents is different for different api versions as mentioned above. [link](https://learn.microsoft.com/en-us/rest/api/eventgrid/dataplane/publish-cloud-event-events/publish-cloud-event-events?tabs=HTTP)
Are you planning to add support for our case in the future?

**Comment by richardpark-msft** [comment]
Let me add @sandeep-sen, the PM for our group.

At this moment the client we're working on is only for pull-based delivery.

**Comment by richardpark-msft** [comment]
Okay, first revision of the Event Grid publisher client is now available.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventgrid@v0.2.0/publisher

Closing. If you find any bugs or missing features please feel free to file more issues. We're actively working on this :)

**Comment by lthela2** [comment]
Thanks @richardpark-msft! Tested the publisher client. It's working as expected. Will let you know if I see any other issues.
