### ISSUE TITLE
The mediaType fields aren't available in azcontainerregistry.ManifestAttribute

### ISSUE THREAD

**Issue by ribbybibby** [Azure/azure-sdk-for-go#21361]
### Bug Report

According to [this page](https://learn.microsoft.com/en-us/rest/api/containerregistry/manifests/get-list?tabs=HTTP#acrmanifests) the ACR list manifests response should include the `mediaType` and `configMediaType` fields in the manifest attributes.

However, those fields don't seem to be present in the [corresponding `ManifestAttribute` struct](https://github.com/Azure/azure-sdk-for-go/blob/4b91f97771d98ea60da9fb1139e03d40c10245b7/sdk/containers/azcontainerregistry/models.go#L249-L278) in `github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry`.

I want to use this SDK to access those attributes.

**Comment by tadelesh** [comment]
In this latest stable version of ACR, there is no `mediaType` property: https://github.com/Azure/azure-rest-api-specs/blob/1df6d6f671dc5059016fbc2c0a624e01f0b2972c/specification/containerregistry/data-plane/Azure.ContainerRegistry/stable/2021-07-01/containerregistry.json#L1969. For `configueMediaType`, I need to confirm with the team and will reply later.

**Comment by ribbybibby** [comment]
Hi @tadelesh. Did you check with the team about `configMediaType`?

If `mediaType` is not a valid property then perhaps it should be removed from the example.

That being said, I do think `mediaType` would be a useful property for the API to expose. Do you know where I could log a request to add that?
