### ISSUE TITLE
AzCosmos: EnableContentResponseOnWrite option is not working for PatchItem

### ISSUE THREAD

**Issue by rahul-rk1** [Azure/azure-sdk-for-go#21389]
### Bug Report

- import path of package in question, e.g. `.../azure-sdk-for-go/sdk/data/azcosmos`
- SDK version `latest`
  - Commit:ecf3749bd6defa947e613d7f861316b4e0cd9bfb
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- go1.20.1

- What happened?
On providing option EnableContentResponseOnWrite true for PatchItem, itemResponse is empty
What did you expect or want to happen?
itemResponse must not be empty, the actual item response must be available in this case
- How can we reproduce it?
Just try to perform PatchItem with option EnableContentResponseOnWrite set to true and check if the itemResponse has the actual value

**Comment by rahul-rk1** [comment]
The fix is to replace the below in PatchItem function 
```
if o == nil {
o = &ItemOptions{}
} 
```
with :
```
if o == nil {
o = &ItemOptions{}
} else {
h.enableContentResponseOnWrite = &o.EnableContentResponseOnWrite
}
```

**Comment by ealsur** [comment]
@rahul-rk1 Are you comfortable sending a PR with the fix? We can review it and get it in for the next release.

**Comment by furious-steel** [comment]
@ealsur Created PR with the fix: https://github.com/Azure/azure-sdk-for-go/pull/21395

**Comment by rahul-rk1** [comment]
> @rahul-rk1 Are you comfortable sending a PR with the fix? We can review it and get it in for the next release.

Now that PR is created, When can we expect this to be released?

**Comment by ealsur** [comment]
@rahul-rk1 Release cycle is monthly

**Comment by ealsur** [comment]
@ jhendrixMSFT When is the next release date for SDKs?

**Comment by jhendrixMSFT** [comment]
It was last week but we can release bugfix updates out-of-band no problem.

**Comment by ealsur** [comment]
@rahul-rk1 already working on the release, see linked PRs.

**Comment by ealsur** [comment]
https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fdata%2Fazcosmos%2Fv0.3.6
