### ISSUE TITLE
Unable to get the `name` field for `privateEndpointConnections` when we call from `azure-sdk-for-go` or through REST API.

### ISSUE THREAD

**Issue by sunilk3vm** [Azure/azure-sdk-for-go#21394]
### Bug Report

- import path of package in question, e.g. `azure-sdk-for-go/blob/v61.1.0/services/machinelearningservices/mgmt/2021-07-01/machinelearningservices`

- What happened?
    -  I am trying to fetch the PrivateEndPointConnection `name` which is already mentioned in the sdk here https://github.com/Azure/azure-sdk-for-go/blob/v61.1.0/services/machinelearningservices/mgmt/2021-07-01/machinelearningservices/models.go#L3277 but the `Name` field is not coming when we call it.
   - I have also tried this API https://learn.microsoft.com/en-us/rest/api/azureml/2023-04-01/workspaces/get?tabs=HTTP#code-try-0, So I am getting `privateEndpointConnections` field in response but the`name` field is missing for it.
  Even I have also checked this version 2021-07-01.
  
    -  So if you see the sample response, there is a `name` field for `privateEndpointConnections` but when we make an api call, it is not coming.
- What did you expect or want to happen?
   - I need `privateEndpointConnections` `name` field in the response.
- How can we reproduce it?
   - create a Machine Learning workspace and add a Private Endpoint Connection to that workspace. Now, go back to the API doc and try to fetch that newly added workspace and see if the `name` field is coming for `privateEndpointConnections`.
   - You can also verify from the SDK.

**Comment by lirenhe** [comment]
@sunilk3vm, it looks you are using the previous version of the SDK,  could you have a try of the latest version?  Thanks.
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/machinelearningservices/armmachinelearningservices
