### ISSUE TITLE
azcore/tracing.Span should have an .AddError() function (similar to AddEvent)

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21399]
This is available in the OpenTelemetry Span, and it's a good way to record the full error. I was prototyping tracing in Service Bus and realized it was missing.

**Comment by jhendrixMSFT** [comment]
This was explicitly removed, see tracking issue https://github.com/Azure/azure-sdk-for-go/issues/20933.  See conversation [here](https://github.com/Azure/azure-sdk-for-go/pull/20916#discussion_r1213659621).
