### ISSUE TITLE
Add API support to check if purge protection is enabled for of an Azure App configuration

### ISSUE THREAD

**Issue by misraved** [Azure/azure-sdk-for-go#21405]
### Feature Request

The latest Go SDK does not include support for checking if purge protection is enabled for an Azure App configuration.

API links that do not include the above feature - https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/appconfiguration/mgmt/2020-06-01/appconfiguration#ConfigurationStoreListResult

Issue reference - https://github.com/turbot/steampipe-plugin-azure/issues/642

**Comment by jhendrixMSFT** [comment]
The current version of this SDK can be found [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appconfiguration/armappconfiguration/v2) and contains setting/detection of purge protection via the `EnablePurgeProtectioin` field in `ConfigurationStoreProperties`.

**Comment by misraved** [comment]
Thanks @jhendrixMSFT for providing a link to the latest SDK 👍.

Using the latest version solved my issue 👍.
