### ISSUE TITLE
Storage Queue Update Message VisibilityTimeout set to 0

### ISSUE THREAD

**Issue by WorldIsM** [Azure/azure-sdk-for-go#2140]
VisibilityTimeout is mandatory field according to 
https://docs.microsoft.com/en-us/rest/api/storageservices/update-message

But if I am setting it to 0 through: storage.UpdateMessageOptions{ VisibilityTimeout: 0}
VisibilityTimeout is removed from URI causing:
"error":"storage: service returned error: StatusCode=400, ErrorCode=InvalidQueryParameterValue, 
ErrorMessage=Value for one of the query parameters specified in the request URI is invalid.

**Comment by jhendrixMSFT** [comment]
Thanks for reporting this, we'll get this fixed in the next release.
Also note that the queue functionality in this storage package has been deprecated, replaced by ```azqueue``` found [here](https://github.com/azure/azure-storage-queue-go).

**Comment by WorldIsM** [comment]
Thanks, will take a look.

**Comment by jhendrixMSFT** [comment]
The fix is in v18.  https://github.com/Azure/azure-sdk-for-go/releases/tag/v18.0.0
