### ISSUE TITLE
Add API support to identify the Authentication mode of an Azure App configuration

### ISSUE THREAD

**Issue by misraved** [Azure/azure-sdk-for-go#21404]
### Feature Request

The latest Go SDK does not include support for identifying the authentication mode used in an Azure App configuration.

API links that do not include the above feature - https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/appconfiguration/mgmt/2020-06-01/appconfiguration#ConfigurationStoreListResult

Issue reference - https://github.com/turbot/steampipe-plugin-azure/issues/643

**Comment by jhendrixMSFT** [comment]
This is the legacy version of our App Configuration SDK.  The current version can be found [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appconfiguration/armappconfiguration/v2).

I _think_ this contains what you're looking for.  Specifically the `CreatedByType` field in the `SystemData` struct.

**Comment by misraved** [comment]
Thanks @jhendrixMSFT for pointing me in the right direction 👍.
