### ISSUE TITLE
System data is always null in azure_postgresql_flexible_server

### ISSUE THREAD

**Issue by madhushreeray30** [Azure/azure-sdk-for-go#21414]
### Bug Report

The SDK link is > https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/postgresql/mgmt/2021-06-01/postgresqlflexibleservers

**Comment by jhendrixMSFT** [comment]
This is our legacy SDK.  The latest SDK for PostgreSQL flexible servers can be found [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v3).  Can you please give it a try and see if it resolves your issue?

**Comment by madhushreeray30** [comment]
@jhendrixMSFT thanks! I have tried out with the latest SDK and it solves the problem 👍

**Comment by jhendrixMSFT** [comment]
Glad it's working!
