### ISSUE TITLE
Improve changelog generation logic

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-for-go#21412]
### Feature Request

When new stable version is generated, the change log would override the previous beta version change log rather than adding on top of it. 

The reason behind this is keeping both change log would cause confusion of the breaking change is against previous beta version but actually the breaking change is against previous stable version. 

We would like to see the change log being added separately with explicitly mentioning the breaking change base is previous stable version.  This way, we can avoid the confusion and keep all the change logs for every release version.

//CC: @lirenhe

**Comment by tadelesh** [comment]
fixed by: https://github.com/Azure/azure-sdk-for-go/pull/21794
