### ISSUE TITLE
[azservicebus] Add a helper function to convert between azservicebus.ReceivedMessage and azservicebus.Message

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21469]
One common activity is to receive a message and then send it again (possibly to a different topic/queue) or in one case, brought up by a customer, to schedule it for future delivery.

We don't provide a way to convert from `ReceivedMessage` to `Message`, which makes this task a bit tedious, and also means if we add new fields customers will have to keep pace or else risk their messages silently slicing off attributes.

The simplest thing would be to add a method to ReceivedMessage that will properly convert to Message so it can be sent.

Note that `azeventhubs` has a nicer design in that ReceivedEvent actually embeds Event. I don't think this would be considered backwards compatible, so a helper method is probably the best option.

Suggested route:
```go
type ReceivedMessage struct{ 
// elided
}

// Does a shallow copy of the attributes from ReceivedMessage -> Message
func (r ReceivedMessage) Message() Message {
  return message
}

```

**Comment by JeffreyRichter** [comment]
This all sounds fine to me.
