### ISSUE TITLE
Pass in the azure region of AAD endpoints in the client options instead of setting the environment variable "AZURE_REGIONAL_AUTHORITY_NAME"

### ISSUE THREAD

**Issue by lthela2** [Azure/azure-sdk-for-go#21497]
We currently set the "AZURE_REGIONAL_AUTHORITY_NAME" env variable close to creation of ClientSecretCredential and ClientCertificateCredential since we use the azidentity clients and do not directly interface with MSAL clients. It will be more convenient if we can pass this in as a client option instead of setting an environment variable.

**Comment by chlowell** [comment]
We don't have a programmatic option for this because we prefer to avoid first-party only APIs, and only first-party apps can use regional authorities. If third-party apps could use them as well, we would consider adding an option.

**Comment by lthela2** [comment]
Why is `ClientSecretCredential` letting us set the AzureRegion? Are 1P apps allowed to use secrets?
We are setting the Azure region to use for `ClientCertificateCredential` but the set environment variable is getting used for `ClientSecretCredential` too and this is causing below errors in Fairfax and Mooncake. However, I don't see such errors in PublicCloud.

```
POST https://chinanorth2.login.chinacloudapi.cn/3d0a72e2-8b06-4528-98df-1391c6f12c11/oauth2/v2.0/token

--------------------------------------------------------------------------------

RESPONSE 400 Bad Request

--------------------------------------------------------------------------------

{

  "error": "invalid_request",

  "error_description": "AADSTS100007: This request was received by an Azure AD regional authentication endpoint. Only managed identities and Microsoft internal service identities are supported. SN+I authentication is required.  All others, send your request to login.microsoftonline.com: in MSAL avoid using .WithAzureRegion(), in App Service, set REGION_NAME to null.\r\nTrace ID: daa2e598-9905-4434-a55a-707533adaf01\r\nCorrelation ID: 38433597-36b6-405b-9294-6f6d1acba2ba\r\nTimestamp: 2023-09-07 18:16:49Z",

```

**Comment by chlowell** [comment]
> Are 1P apps allowed to use secrets?

Some are.

> We are setting the Azure region to use for `ClientCertificateCredential` but the set environment variable is getting used for `ClientSecretCredential` too and this is causing below errors in Fairfax and Mooncake.

Whether a credential uses a regional endpoint is set at construction, so in this case I suggest unsetting AZURE_REGIONAL_AUTHORITY_NAME before calling `NewClientSecretCredential`.

**Comment by lthela2** [comment]
But setting and unsetting the environment variable can cause race conditions.

**Comment by AzureMarker** [comment]
@chlowell We want to use this feature but setting it via environment variable is not really viable. We only want to enable this for certain clients in our code. We could set the environment variable, make the client, then unset it, but that isn't thread safe. Another client could be created at the same time in a different goroutine/thread that we don't want the option enabled in (option would be unintentionally enabled at that point in the second client). We could work around this even more (introduce a mutex, etc), but it would be better for the library to support setting this property at a per-client level, not via environment variable.

**Comment by chlowell** [comment]
I'm sorry this feature is hard to use as is and I understand it would be easier to use in your scenario if it had a programmatic option. Still, we don't plan to add such an option at this time because only first-party apps can use the feature. We don't want to add an option that most developers shouldn't try to use, or to receive issues from external developers who try to use it anyway, or to get stuck maintaining a vestigial API after first-party requirements change.
