### ISSUE TITLE
Question regarding usage of MSI and AKS workload identity

### ISSUE THREAD

**Issue by shashankram** [Azure/azure-sdk-for-go#21495]
Hi, we have a Go app currently hosted outside AKS that needs to run in AKS and requires credentials to authenticate with Azure to fetch information regarding VMs and their network interfaces. Currently, when using MSI, we fetch the credentials using `azidentity.NewManagedIdentityCredential(nil)` and pass that credential to the azure client as `armresources.NewClient(subscriptionID, cred, nil)`.

I am wondering how can we achieve the same using workload identity for AKS and what configurations are necessary. Does the client app need to use a different API when it want's to leverage workload identity using k8s service accounts? Is the mechanism for obtaining auth tokens the same or is there a different workfow involved?

Thanks

**Comment by chlowell** [comment]
First you need to configure Workload Identity on the cluster. See the [AKS docs](https://learn.microsoft.com/azure/aks/workload-identity-deploy-cluster) for more information on that. With that done, your application can simply call `azidentity.NewWorkloadIdentityCredential` instead of `azidentity.NewManagedIdentityCredential`. Both credential types have the same interface, so their differences are transparent to Azure SDK clients.

**Comment by shashankram** [comment]
> First you need to configure Workload Identity on the cluster. See the [AKS docs](https://learn.microsoft.com/azure/aks/workload-identity-deploy-cluster) for more information on that. With that done, your application can simply call `azidentity.NewWorkloadIdentityCredential` instead of `azidentity.NewManagedIdentityCredential`. Both credential types have the same interface, so their differences are transparent to Azure SDK clients.

Thanks for the quick response and clarification. Are there any other caveats to be aware of when transitioning from standard MSI to workload identity?

**Comment by chlowell** [comment]
Not for the Azure SDK. In an application workload identity is like MSI in that configuration is simple and usually comes from the hosting environment. The work of transitioning is in configuring the cluster, which is more involved than configuring MSI on most platforms.
