### ISSUE TITLE
Go Managed Identity example in README.md still references environment variable for user-assigned managed identity client id

### ISSUE THREAD

**Issue by christopherabrooks** [Azure/azure-sdk-for-go#21509]
### Bug Report

- [azure-sdk-for-go/sdk/azidentity/README.md](https://github.com/Azure/azure-sdk-for-go/blob/sdk/azidentity/v1.3.1/sdk/azidentity/README.md#specify-a-user-assigned-managed-identity-for-defaultazurecredential) (1.3.1 and 1.4.*)

**_This_** functionality no longer exists, now replaced with credential options parameter:

> ### Specify a user-assigned managed identity for DefaultAzureCredential
> To configure DefaultAzureCredential to authenticate a user-assigned managed identity, **_set the environment variable AZURE_CLIENT_ID to the identity's client ID_**.

**Comment by chlowell** [comment]
Is this feature not working for you? It should--we haven't removed the implementation and our unit test for it still passes:
https://github.com/Azure/azure-sdk-for-go/blob/bd79d36ce1bb052df2db67ff466d7c75f58180f2/sdk/azidentity/default_azure_credential.go#L100-L104

**Comment by christopherabrooks** [comment]
I see that now - debugging...

**Comment by christopherabrooks** [comment]
found the typo on my env variable.  closing.

**Comment by christopherabrooks** [comment]
closing - false alarm
