### ISSUE TITLE
Const BLOB access levels but need pointer

### ISSUE THREAD

**Issue by KappelTQUS** [Azure/azure-sdk-for-go#21502]
### Bug Report

Hello!
I am currently writing a storage service connected to several databases, storages, ... .
Consequently, I used the azblob package to up-/download blobs.

```
The problematic command:
blobClient.UploadStream(context.TODO(), containerName, blobName, strings.NewReader(...), &azblob.UploadStreamOptions{
	AccessTier: blob.AccessTierHot,
})
```

AccessTier requires a pointer to type blob.AccessTier. Constants for these values are provided, but only (as mentioned) as const.
Go does not allow for a pointer to a const value (at least I couldn't make it work), and wrote following workaround:

```
var (
	coolAccess    blob.AccessTier = "Cool"
	hotAccess     blob.AccessTier = "Hot"
	archiveAccess blob.AccessTier = "Archive"
)
```

```
blobClient.UploadStream(context.TODO(), containerName, blobName, strings.NewReader(...), &azblob.UploadStreamOptions{
	AccessTier: &hotAccess,
})
```

This works without any problems.
I might be missing something to make it work (and am sorry if that's the case), but I believe using const creates an issue here.

imported package of branch main at commit 56c7173:
import "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob"

go version: go1.20.7 darwin/amd64

Thank you.

**Comment by jhendrixMSFT** [comment]
We have a function [`to.Ptr[T]`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.7.1/to#Ptr) to simplify these kinds of conversions.
