### ISSUE TITLE
Missing timeCreated attribute for VirtualMachineScaleSetVMProperties

### ISSUE THREAD

**Issue by amos-arbiv** [Azure/azure-sdk-for-go#21515]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

The timeCreated attribute is missing from VirtualMachineScaleSetVMProperties struct. 
full path to latest SDK: https://github.com/Azure/azure-sdk-for-go/blob/2187aca40bbf6931ffac666977e5d29128d82585/services/compute/mgmt/2022-08-01/compute/models.go#L22851

- What happened?
The actual timeCreated attribute is not present as part of the struct. 
- What did you expect or want to happen?
I expect to see timeCreated in the struct.
- How can we reproduce it?
ListAll VMs inside a VMSS. 
- Anything we should know about your environment.
Nothing

**Comment by jhendrixMSFT** [comment]
We'd have to move to the latest API version https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-07-01/virtualMachineScaleSet.json#L5611-L5616

**Comment by lirenhe** [comment]
@amos-arbiv, we are targeting the release a new version of Compute this month which will contain the timeCreated attribute.
But please use the latest version of GO SDK:  https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute

@Alancere, please help to follow up about the release.

**Comment by Alancere** [comment]
package released: package released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5@v5.2.0
