### ISSUE TITLE
Get list of Subscriptions from Multi Tenant

### ISSUE THREAD

**Issue by ronyrv13** [Azure/azure-sdk-for-go#21539]
Hello Team,
I am new to azure-sdk-for-go, and I am working on a multi Tenant environment
I created a multi tenant app (App registration) and using it's credential I need to list subscriptions from both Tenants.

I am using ARM cross-tenant authentication feature from [azidentity ](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity)
But I am not getting Subscription list from auxiliary tenant, instead getting only from primary Tenant.

	auxTenants := []string{"TENANT-1-ID}

	cred, err := azidentity.NewClientSecretCredential("PRIMARY-TENANT-ID",
		"APP-CLIENT-ID", "APP-SECRET",
		&azidentity.ClientSecretCredentialOptions{
			AdditionallyAllowedTenants: auxTenants})

	if err != nil {
		log.Default().Fatal(err)
	}
   
   // SUBSCRIPTION LISTING LOGIC--
   
    client, err := armsubscription.NewSubscriptionsClient(cred,
	      &arm.ClientOptions{AuxiliaryTenants: auxTenants},
	)
    ctx := context.TODO()
    pager := client.NewListPager(nil)
 
    for pager.More() {
	subscriptionList, err := pager.NextPage(ctx)
	if err != nil {
		log.Default().Fatal(err)
	}
	for _, item := range subscriptionList.Value {
		subscriptions = append(subscriptions, structs.Subscription{SubscriptionID: *item.SubscriptionID, SubscriptionName:       *item.DisplayName})
	}
       }

Here I am getting list of Subscriptions from PRIMARY-TENANT-ID **only**, I am **not getting** the sub list from auxTenant !!

**Am I wrong here ?
How can I get list of Subscriptions from Both Tenants?**

cc: @chlowell

**Comment by chlowell** [comment]
Auxiliary tenants don't apply to this API because the operation isn't cross-tenant. The service simply lists subscriptions for the tenant that issued the primary access token i.e., the credential's configured tenant. So, you have to create a credential and client for each tenant like this:

```go
credA, err := azidentity.NewClientSecretCredential("tenant A", "clientID", "secret", nil)
if err != nil {
	// TODO
}
credB, err := azidentity.NewClientSecretCredential("tenant B", "clientID", "secret", nil)
if err != nil {
	// TODO
}
for _, cred := range []azcore.TokenCredential{credA, credB} {
	client, err := armsubscription.NewSubscriptionsClient(cred, nil)
	if err != nil {
		// TODO
	}
	pager := client.NewListPager(nil)
	for pager.More() {
		page, err := pager.NextPage(context.TODO())
		if err != nil {
			// TODO
		}
		if v := page.Value; v != nil {
			// TODO: do something with the subscriptions
		}
	}
}
```

**Comment by ronyrv13** [comment]
Thank you @chlowell for helping me out.
I truly appreciate your time and expertise, keep doing great things team.
