### ISSUE TITLE
Latency in create / update of recordset in DNS zone

### ISSUE THREAD

**Issue by Um-e-Hani** [Azure/azure-sdk-for-go#21572]
Hello Team,

I am currently using azure-sdk-for-go for creating recordsets in a DNS zone. For that, I am creating a new client secret credential and then using that credential for creating a new recordsets client.

My configuration structs are as follows:

`type config struct {
	SubscriptionID string
	ResourceGroup  string
	ZoneName       string
	CName          string
	TTL            int64
	recordType     armdns.RecordType
	RelativeCname  string
}`

`type spConfig struct {
	TenantID string
	ID       string
	Secret   string
}`

This is the script I am using to create the recordset:
	
	// create new client secret credential
	cred, err := azidentity.NewClientSecretCredential(spConfig.TenantID, spConfig.ID, spConfig.Secret, nil)
	if err != nil {
		log.Fatalf("unable to create new client secret credential: %v", err)
	}

	// create new recordsets client
	client, err := armdns.NewRecordSetsClient(
		config.SubscriptionID,
		cred,
		&arm.ClientOptions{
			ClientOptions: policy.ClientOptions{
				Cloud: cloud.AzurePublic,
			},
		},
	)
	if err != nil {
		log.Fatalf("unable to create new azure dns recordsets client: %v", err)
	}

	recordSet := armdns.RecordSet{
		Properties: &armdns.RecordSetProperties{
			CnameRecord: &armdns.CnameRecord{
				Cname: &config.CName,
			},
			TTL: &config.TTL,
		},
	}

	// create recordset
	_, err = client.CreateOrUpdate(ctx, config.ResourceGroup, config.ZoneName, config.RelativeCname, config.recordType, recordSet, nil)
	if err != nil {
		log.Fatalf("unable to create / update record set: %v", err)
	}

The record type I am using is CNAME.

The issue is that when I create a new recordset using this client, it takes quite some time for the alias to take effect (around 3-5 minutes avg). On the contrary, creating a new recordset directly form the azure portal is immediately effective (within a few seconds). 

Is there any way to cater for this latency? 

Please let me know. I would love to hear from you soon.

**Comment by Alancere** [comment]
Hi @Um-e-Hani, are there any logs? [AZURE_SDK_GO_LOGGING](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-guideline.md#logging)
