### ISSUE TITLE
Add networkProfile data in hybrid compute machineProperties 

### ISSUE THREAD

**Issue by David3310273** [Azure/azure-sdk-for-go#21592]
### Feature Request

In some occasions, the machine's network info may be also important, such as IP address, subnet mask. Moreover, this data has been included in the REST api response, so just add this part of data in golang sdk response struct.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/hybridcompute/armhybridcompute/models.go#L349

**Comment by David3310273** [comment]
> Hi @David3310273 thanks for this issue!
> 
> Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look. I also sent some internal emails to the contact of the corresponding service team about this.

thank you for your effort.

**Comment by Alancere** [comment]
package released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/hybridcompute/armhybridcompute/v2@v2.0.0-beta.1
