### ISSUE TITLE
Bug in OpenAI Sample

### ISSUE THREAD

**Issue by bobtabor-msft** [Azure/azure-sdk-for-go#21629]
### Bug Report

- Import package: `github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai`
- SDK version: `main`, `latest`, `0.3.0`
- Go version: `1.18`
- Docs example issue

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai#example-Client.GetChatCompletions-BringYourOwnDataWithCognitiveSearch

... this line of code:

```
Deployment: "gpt-4",
```

... should not be hard coded.  Instead, it should be:

```
Deployment: modelDeploymentID,
```

... because if I choose a different model (like gpt-35-turbo ... which is one of a set of limited options from the Azure OpenAI Studio currently) when creating a deployment, the code sample will throw 400 error.

**Comment by sandeep-sen** [comment]
`modelDeploymentID` defined at [azure-sdk-for-go/ai/azopenai/example_client_getchatcompletions_extensions_test.go#L22](https://github.com/Azure/azure-sdk-for-go/blob/70a613f70cdd318b47b49a183a4275f5dd93f2b0/sdk/ai/azopenai/example_client_getchatcompletions_extensions_test.go#L22)

`Deployment` assigned at [azure-sdk-for-go/ai/azopenai/example_client_getchatcompletions_extensions_test.go#L77](https://github.com/Azure/azure-sdk-for-go/blob/70a613f70cdd318b47b49a183a4275f5dd93f2b0/sdk/ai/azopenai/example_client_getchatcompletions_extensions_test.go#L77)
