### ISSUE TITLE
Mismatched MAC signature for Blob Batch API when `/` in blob path

### ISSUE THREAD

**Issue by robherley** [Azure/azure-sdk-for-go#21649]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version:
  - `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.1.0`
- output of `go version`
  - `go version go1.20.2 darwin/amd64` 

- What happened?

   When calling the Delete [Blob Batch API](learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=azure-ad) with a blob path that has a `/`, I am getting `AuthenticationFailed` errors with `The MAC signature found in the HTTP request ... is not the same as any computed signature`. However, if I call the same API with a blob path that doesn't have a `/`, the request works fine. Also, if I call the single [blob delete](https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob?tabs=azure-ad) API with a `/` in the blob path, it works fine.  

- What did you expect or want to happen?

   A blob with a `/` in the path can be deleted by the batch API.

- How can we reproduce it?

  I made a gist that reproduces the case, with some logs: https://gist.github.com/robherley/64e656f8326b70ecd9cafec65f9e68f4

- Anything we should know about your environment.

  I was unable to reproduce this in Azurite, but have tested this with multiple storage accounts on `blob.core.windows.net`

**Comment by robherley** [comment]
Placing a breakpoint at: https://github.com/Azure/azure-sdk-for-go/blob/0cda95c7a7e55361d9602a7c8a141eec584f75cc/sdk/storage/azblob/internal/exported/shared_key_credential.go#L96

The value is: 

```
DELETE\n\n\n\n\n\n\n\n\n\n\n\nx-ms-date:Thu, 28 Sep 2023 20:38:01 GMT\n/robstorage123/go-sdk-repro/foo%2Fbar%2Ffile2.txt
```

Which looks correct, but I'm not sure how the subrequests escapes are supposed to be handled on the azure blob side.

Weirdly enough, I was able to get it working my commenting out this line from the client that escapes the name:
https://github.com/Azure/azure-sdk-for-go/blob/a50bf6de8d5d19367660473632b81fe35d7b2e4c/sdk/storage/azblob/container/batch_builder.go#L47

Which resulted in a `stringToSign` as:

```
DELETE\n\n\n\n\n\n\n\n\n\n\n\nx-ms-date:Thu, 28 Sep 2023 21:04:31 GMT\n/robstorage123/go-sdk-repro/foo/bar/file2.txt
```

And that works 🤔 which technically matches the error response that uses unencoded `/` characters:

```
<AuthenticationErrorDetail>The MAC signature found in the HTTP request &apos;1Z4JigwM6+SBWsHckBnT/6fzoQWw5GBKZA2ULkYxNM8=&apos; is not the same as any computed signature. Server used following string to sign: &apos;DELETE











x-ms-date:Thu, 28 Sep 2023 19:10:12 GMT
/robstorage123/go-sdk-repro/foo/bar/file2.txt&apos;.</AuthenticationErrorDetail>
```

**Comment by souravgupta-msft** [comment]
Hi @robherley. Thanks for reporting this bug and providing detail explanation on it.
I have created a PR to fix this. It will be part of our next release.
