### ISSUE TITLE
AzureCLICredential's requestToken() assumes azure-cli's current active subscription's user can be used for requesting an access token

### ISSUE THREAD

**Issue by sgoings** [Azure/azure-sdk-for-go#21651]
### Bug Report

- import path: `"github.com/Azure/azure-sdk-for-go/sdk/azidentity"`
- sdk version: `v1.3.1`
- go version: `go1.21.1 linux/amd64`

#### What Happened / Reproduction Steps

```
$ az account show # shows azure cli's active subscription 
{
  "environmentName": "AzureCloud",
  "homeTenantId": "<TENANT B>",
  "id": "<SUBSCRIPTION GUID>",
  "isDefault": true,
  "managedByTenants": [],
  "name": "Super Secret Subscription",
  "state": "Enabled",
  "tenantId": "<TENANT B>",
  "user": {
    "name": "dev@supersecrettenantb.com",
    "type": "user"
  }
}
```
 
Given the code:

```
	credential, err := azidentity.NewAzureCLICredential(&azidentity.AzureCLICredentialOptions{
		TenantID: "<TENANT ID A>",
	})
	if err != nil {
		log.Fatal(err)
	}

	token, err := credential.GetToken(context.Background(), policy.TokenRequestOptions{
		Scopes:   []string{"499b84ac-1321-427f-aa17-267ca6975798/.default"}, // Azure DevOps Scope
		TenantID: "<TENANT ID A>",
	})
	if err != nil {
		log.Fatal(err)
	}
```

Users will receive the error:
```
FATA[2023-09-27 23:29:10] AzureCLICredential: ERROR: AADSTS50020: User account 'dev@supersecrettenantb.com'
from identity provider 'https://sts.windows.net/<TENANT ID B>/' does not exist in tenant '<TENANT ID A>'
and cannot access the application '04b07795-8ddb-461a-bbee-02f9e1bf7b46'(Microsoft Azure CLI)
in that tenant (<TENANT ID A>). The account needs to be added as an external user in the tenant first.
Sign out and sign in again with a different Azure Active Directory user account.

Trace ID: 24c592eb-3a72-45ad-8d8f-dbe85f480700
Correlation ID: 175a0813-1632-4d2f-a212-bf49d0b66e7e
Timestamp: 2023-09-28 19:37:20Z
Interactive authentication is needed. Please run:
 z login --scope 499b84ac-1321-427f-aa17-267ca6975798/.default
```

This is due to how [AzureCLICredential relies on az account get-access-token](https://github.com/Azure/azure-sdk-for-go/blob/0cda95c7a7e55361d9602a7c8a141eec584f75cc/sdk/azidentity/azure_cli_credential.go#L116) to [find the current active subscription to determine the user account to authenticate with / grab an access token for.](https://github.com/Azure/azure-cli/blob/0a62d499ac898dcc9227e055ba48cf7c44ccbd0c/src/azure-cli-core/azure/cli/core/_profile.py#L362)

####  What I Expect to Happen

I expect AzureCLICredential to request an access token using the user account I specify (or maybe minimally, the subscription ID I specify?) instead of trying to deduce this information using the user ID that is mapped to azure cli's currently active subscription.

**Comment by chlowell** [comment]
I'm a little confused. As you've seen, AzureCLICredential simply invokes `az account get-access-token` and leaves all the details to `az`, so the behavior you describe is by design--we expect developers to configure `az` directly. Are you asking for AzureCLICredential to expose a configuration API for `az` which would allow changing the CLI's logged in user or default subscription?

**Comment by sgoings** [comment]
> Are you asking for AzureCLICredential to expose a configuration API for az which would allow changing the CLI's logged in user or default subscription?

Yes that could be one way of doing it.

In my specific scenario, a user is logged into multiple tenants (A and B). azidentity should provide a way to configure the request of an access token on behalf of account A (in tenant A) despite azure cli's active subscription being one of a user account B (in tenant B).

I don't think that azidentity's AzureCLICredential provider should have a side effect where it is changing azure-cli's active subscription, however.

**Comment by chlowell** [comment]
This is pretty strange in the context of authentication because access tokens have nothing to do with subscriptions, however it seems that the CLI associates each user account with a subscription and uses it as the key to identify the account. Does AzureCLICredential work as expected after you run `az account set <subscription associated with the right account>`?

**Comment by sgoings** [comment]
Yes, AzureCLICredential works as expected in this usecase where I'm balancing multiple tenants after I run `az account set <subscription associated with the right account>`.

However, I do not want `azidentity` or the service I'm building atop it to change azure-cli's active subscription just to get an AAD access token for a specific user in a specific tenant as this would introduce significant undesirable side effects. A library or an application should not change the user's context unknowingly out from underneath them (in this case, the "active" subscription wired up to azure-cli).

**Comment by chlowell** [comment]
> However, I do not want azidentity or the service I'm building atop it to change azure-cli's active subscription just to get an AAD access token for a specific user in a specific tenant as this would introduce significant undesirable side effects.

100% agree. `azidentity` won't set the CLI's configuration. When I raised the possibility earlier I was just trying to understand your scenario.

> The patch I'm using locally is to be able to supply --subscription to the az account get-access-token call

What API did you add for specifying the subscription ID? I guess a `SubscriptionID` field on `AzureCLICredentialOptions`?

**Comment by chlowell** [comment]
Thanks for opening this issue. It's the first report we've had across all the Azure SDKs of the configured subscription being crucial to `az` account selection. After discussing it the team decided not to add a subscription option because the `az account set` solution is straightforward and consistent with our intent to leave all the details of account selection to the CLI.

**Comment by sgoings** [comment]
> Seth: However, I do not want azidentity or the service I'm building atop it to change azure-cli's active subscription just to get an AAD access token for a specific user in a specific tenant as this would introduce significant undesirable side effects.

> Charles: 100% agree. azidentity won't set the CLI's configuration. When I raised the possibility earlier I was just trying to understand your scenario.

> Charles: Thanks for opening this issue. It's the first report we've had across all the Azure SDKs of the configured subscription being crucial to az account selection. After discussing it the team decided not to add a subscription option because the az account set solution is straightforward and consistent with our intent to leave all the details of account selection to the CLI.

All I ask is for `azidentity` to allow users to access setting `--subscription` when `azidentity` goes to run  `az account get-access-token` under the hood. I _cannot_ use the `az account set` solution, because that introduces an action that could destructively disturb other uses of `az` (relying on the active subscription) happening on the system at the same time.
