### ISSUE TITLE
[Question] What should WorkloadIdentityCredentialOptions look like for multi-tenant credentials

### ISSUE THREAD

**Issue by shashankram** [Azure/azure-sdk-for-go#21653]
Hi, I am leveraging workload identity to allow my app in Kubernetes to authenticate with the Azure API. I am wondering how [WorkloadIdentityCredentialOptions](https://github.com/Azure/azure-sdk-for-go/blob/sdk/azidentity/v1.3.1/sdk/azidentity/workload_identity.go#L34) should be configured for multi-tenancy. For e.g., my app in AKS cluster in tenant1 needs to be able to access resources in tenant2 and tenant3.

I see the `AdditionallyAllowedTenants` field that allows to specify the additional tenants, but unsure how it relates to the `TenantID` field. Per my understanding, `TenantID` is the ID of the tenant where the managed identity resides, which could be tenant2 and tenant3 in my example, while the k8s app runs in tenant1. How do these 2 fields relate to each other for a multi-tenant app needing to access resources in different tenants using a federated credential?

Thanks

**Comment by chlowell** [comment]
`TenantID` is the default tenant for the credential's token requests. The credential requests tokens from that tenant when a caller (e.g. an SDK client) doesn't specify a different tenant to `GetToken()`. When a caller specifies a different tenant, the credential checks it against `AdditionallyAllowedTenants`, which is an allow list of other tenants from which the credential may request tokens. So in your case, `AdditionallyAllowedTenants` would be something like `[]string{"tenanat2", "tenant3"}`. Note that actually getting a token from a tenant other than the configured default requires specifying a tenant when calling `GetToken()`. Most SDK clients don't do that, so you may need to create a client and credential for each tenant.

**Comment by shashankram** [comment]
> `TenantID` is the default tenant for the credential's token requests. The credential requests tokens from that tenant when a caller (e.g. an SDK client) doesn't specify a different tenant to `GetToken()`. When a caller specifies a different tenant, the credential checks it against `AdditionallyAllowedTenants`, which is an allow list of other tenants from which the credential may request tokens. So in your case, `AdditionallyAllowedTenants` would be something like `[]string{"tenanat2", "tenant3"}`. Note that actually getting a token from a tenant other than the configured default requires specifying a tenant when calling `GetToken()`. Most SDK clients don't do that, so you may need to create a client and credential for each tenant.

Not sure I understand this. Based on [WorkloadIdentityCredentialOptions](https://github.com/Azure/azure-sdk-for-go/blob/sdk/azidentity/v1.3.1/sdk/azidentity/workload_identity.go#L34), there are the `TenantID` and `AdditionallyAllowedTenants` field. What's the reference to `GetToken()` you make? I don't follow what TenantID corresponds to in this options struct. Is it the tenant the client resides in or the tenant it wants to access resources in? 

If I need to use multiple clients per tenants, then I could simply use `NewDefaultAzureCredential()` and set the tenant ID via the `AZURE_TENANT_ID` env var.

**Comment by chlowell** [comment]
> What's the reference to GetToken() you make?

[GetToken()](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#WorkloadIdentityCredential.GetToken) is the method that performs authentication i.e. requests a token. It decides which tenant to request a token from according to its arguments and the credential's configuration.

> I don't follow what TenantID corresponds to in this options struct. Is it the tenant the client resides in or the tenant it wants to access resources in?

The value is the tenant from which the credential requests tokens by default. A tenant won't issue a token to a principal it doesn't know and tokens aren't valid across tenants. The tenant for a given token request is therefore both a tenant the principal is registered in and the tenant whose resources the principal wants to access.

> If I need to use multiple clients per tenants, then I could simply use NewDefaultAzureCredential() and set the tenant ID via the AZURE_TENANT_ID env var.

You could do accomplish the same by setting `WorkloadIdentityCredentialOptions.TenantID` or calling `NewWorkloadIdentityCredential()`, which reads AZURE_TENANT_ID.

**Comment by shashankram** [comment]
> > I don't follow what TenantID corresponds to in this options struct. Is it the tenant the client resides in or the tenant it wants to access resources in?
> 
> The value is the tenant from which the credential requests tokens by default. A tenant won't issue a token to a principal it doesn't know and tokens aren't valid across tenants. The tenant for a given token request is therefore both a tenant the principal is registered in and the tenant whose resources the principal wants to access.
> 

With workload identity, it's a bit different because the app can reside in a specific tenant and still access resources in different tenant by using a federated credential. This is what makes the current config confusing. Why is the `AdditionallyAllowedTenants` exposed if `TenantID` is enough? What is the significance of `AdditionallyAllowedTenants`?

My goal is to ensure an app registered in tenant1 can use a an identity federated across multiple tenants to access resources in those tanants regardless of the tenant it resides in.
For this use case, do I need a client per resource tenant or can I use a single client somehow with the use of `AdditionallyAllowedTenants`?

**Comment by chlowell** [comment]
>  What is the significance of AdditionallyAllowedTenants?

`AdditionallyAllowedTenants` is an allow list of tenants a credential may request tokens from in addition to its default tenant (the value of `TenantID`). So, this is an error:
```go
cred, _ := azidentity.NewWorkloadIdentityCredential(
	&azidentity.WorkloadIdentityCredentialOptions{
		// N.B. when this isn't set programmatically, the value comes from AZURE_TENANT_ID
		TenantID: "tenant1",
	},
)
// err will be non-nil because "tenant2" is neither the default nor an allowed tenant
_, err := cred.GetToken(context.TODO(), policy.TokenRequestOptions{
	Scopes: []string{"..."},
	TenantID: "tenant2",
})
```

> My goal is to ensure an app registered in tenant1 can use a an identity federated across multiple tenants to access resources in those tanants regardless of the tenant it resides in.
For this use case, do I need a client per resource tenant

If your app has the same client ID in all the tenants whose resource you want to access and your code calls `GetToken()` directly, you can use one instance of `WorkloadIdentityCredential`, setting its `AdditionallyAllowedTenants` appropriately. Otherwise, use one client and credential instance per tenant.

**Comment by shashankram** [comment]
Thanks @chlowell for sharing the details. I'll try this.
