### ISSUE TITLE
[azopenai] Fix error types

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21671]
The generated error types need to be pared down to _only_ the parts that we consider programatically set. 

APIView discussion:
https://apiview.dev/Assemblies/Conversation/aac23326de874fd39ce9e7332f95a2f7#356661ef10374eb89e8d4a5d7eed5bb3

**Comment by RickWinter** [comment]
@richardpark-msft Is this relevant work we still plan to do?

**Comment by richardpark-msft** [comment]
This must have been fixed. There's only one exposed error type and we embedded an azcore.ResponseError in there, which is what I would have expected.
