### ISSUE TITLE
Bug when using custom URL together with default account name

### ISSUE THREAD

**Issue by blez** [Azure/azure-sdk-for-go#21676]
### Bug Report

- SDK version
v68.0.0
- output of `go version`
go version go1.20.7 linux/amd64

- What happened?
I'm creating a new client and trying to upload a file to Azurite.
```
client, _ := storage.NewClient("devstoreaccount1", defaultAccoutKey, custim_url, "2019-12-12", false)
blobService := client.GetBlobService()
container := blobService.GetContainerReference(myBucket)
blob := container.GetBlobReference(myBlobName)
err = blob.CreateBlockBlobFromReader(bytes.NewReader(myData), nil)
```
As you can see (on line 1) account name is a default storage emulator account name (devstoreaccount1). But the URL I use is not the default one, but a custom. 

When I call `CreateBlockBlobFromReader` it returns me connection refused error with the default storage emulator blob URL (127.0.0.1:10000) inside

I think the reason is in this piece of code https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/storage/client.go#L502-L510
It checks if accountName is a default. If yes it sets the host URL to default ignoring the provided custom URL.
So the fix should be simple enough.

- What did you expect or want to happen?
The library must use the provided custom URL instead of rewriting it to the default one.

- How can we reproduce it?
Look at the provided code

**Comment by tanyasethi-msft** [comment]
Hi @blez, Thank you for reporting this. 

[azure-sdk-for-go/storage/README.md at v68.0.0 · Azure/azure-sdk-for-go (github.com)](https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/storage/README.md)
❗ IMPORTANT: This package is in maintenance only and will be deprecated in the future. Please use one of the following packages instead.

 Please use the latest azblob package : https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv1.2.0
