### ISSUE TITLE
[Question] Get instanceView when listing all VMs

### ISSUE THREAD

**Issue by jacobkilby** [Azure/azure-sdk-for-go#21682]
I have some code that lists all VMs in a subscription and I would like to get the instance view in the request. I used to do this

```
filter := "$expand=instanceView"
pager := vmClient.NewListAllPager(&armcompute.VirtualMachinesClientListAllOptions{
    Filter: &filter,
})
```
And then use the pager but attempting to do this with the filter now gives me a 400 bad request. Is there a different way of doing this?

**Comment by raych1** [comment]
@jacobkilby , it should be `Expand`.

```go
&armcompute.VirtualMachinesClientListAllOptions{Expand: &filter}
```
