### ISSUE TITLE
Fakes for networking were deleted in commit baac183ffa684d94f697f0fc6f480e02cfb00f3d

### ISSUE THREAD

**Issue by divega** [Azure/azure-sdk-for-go#21687]
### Bug Report

Not sure if this is a bug report or a feature request. It depends on whether all the fakes that were under sdk/resourcemanager/network/armnetwork/fake were deleted intentionally or accidentally in https://github.com/Azure/azure-sdk-for-go/commit/072a486b550c2a6587921a732529d59d83dc4b95. 

I am collaborating with a project that was planning to use these fakes to abstract Azure Networking resources in unit testing. If there was an explicit decision to remove them for the SDK, we are interested in what is the guidance for unit testing. If they were unintentionally removed, please bring them back.

**Comment by RickWinter** [comment]
@jhendrixMSFT, @Alancere as part of the release the fakes were removed.  We need to regenerate a new beta with the fakes

**Comment by divega** [comment]
Thanks for the answer @RickWinter. It has become clear that we shouldn't take a dependency on these fakes until they become part of a release. Could you elaborate a bit on the roadmap around this (or point me to it if it's already written somewhere)?

**Comment by tadelesh** [comment]
@divega please use the latest beta: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v4@v4.3.0-beta.1
