### ISSUE TITLE
`x-ms-immutability-policy-mode` does not respect `ImmutabilityPolicyMode` values

### ISSUE THREAD

**Issue by KastenMike** [Azure/azure-sdk-for-go#21685]
Whatever service is returning the calls I guess has different consts to this repo or uses `strings.ToLower()`.

`getPropertiesHandleResponse` (generated) is assigning `resp.Header.Get("x-ms-immutability-policy-mode")` to `ImmutabilityPolicyMode`. In this repo `ImmutabilityPolicyModeLocked` is "Locked" but calls like `NewBlobClient(blob).GetProperties(ctx, nil)` are returning `&ImmutabilityPolicyMode("locked")` which is not ideal because `ImmutabilityPolicyMode("locked") == ImmutabilityPolicyModeLocked` is false meaning we can't use these types for checking and instead need to do something like `strings.EqualFold(string(ImmutabilityPolicyMode("locked")), string(ImmutabilityPolicyModeLocked))`.

**Comment by KastenMike** [comment]
Oh it seems the returned value is `BlobImmutabilityPolicyModeType` although it cast to `ImmutabilityPolicyMode`

**Comment by KastenMike** [comment]
Maybe the swagger or whatever is generating the client was set to `ImmutabilityPolicyMode` by mistake and should instead be `BlobImmutabilityPolicyModeType`?

**Comment by KastenMike** [comment]
OK I see similar mentioned here already https://github.com/Azure/azure-sdk-for-go/issues/16791#issuecomment-1011518946

**Comment by vibhansa-msft** [comment]
These values are as per the return values coming back from backend. SDK is just using the same value while returning back status.

**Comment by KastenMike** [comment]
So it's a mistake on the backend then? If the expected type is "Locked" but "locked" is returned
