### ISSUE TITLE
Custom `LastModified` for `HasVersionsOnly` blob version

### ISSUE THREAD

**Issue by KastenMike** [Azure/azure-sdk-for-go#21697]
FEAT/BUG? You decide. I guess this is not on this repo but on a backend service but maybe someone here knows a person involved~

Lets say you have a blob X with 1 version ("2023-10-01.1234Z") and you delete it, some kind of delete marker version is created that has `HasVersionsOnly=true` and is only visible when `DeletedWithVersions: true` is set. 

The problem is this delete marker version will have a new VersionID e.g. "2023-10-05.6789Z" but for some reason it is given the same `LastModified` value as the last live one so it has `LastModified: 2023-10-01` and `VersionID: 2023-10-05`. It would be better if rather than copying the `LastModified` value it would instead use the same value as its own VersionID for LastModified too. This makes it easier for sorting.

**Comment by vibhansa-msft** [comment]
This is a limitation from backend and can not be solved at SDK level.
