### ISSUE TITLE
NewListPager is not returning all VMs

### ISSUE THREAD

**Issue by carlos4ndre** [Azure/azure-sdk-for-go#21707]
### Bug Report

When using [NewListPager](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/virtualmachines_client.go#L742) or even [NewListAllPager](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/virtualmachines_client.go#L813) of the [VirtualMachinesClient](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/virtualmachines_client.go) we do not get the VMs that are provisioned under a VMSS with an orchestration mode of type `uniform`, but `flexible` seems to be working fine.

This was experienced using the latest version of `resourcemanager/compute/armcompute/v5`.

The expected behaviour is to be able list all VMs managed or not by VMSSs.

**Comment by hilaryw29** [comment]
Hi @carlos4ndre, could you please try [NewListPager ](https://github.com/Azure/azure-sdk-for-go/blob/c0e76f5175d47899fca2b5cb698bb42c983b7c46/sdk/resourcemanager/compute/armcompute/virtualmachinescalesetvms_client.go#L352)from the [VirtualMachineScaleSetVms ](https://github.com/Azure/azure-sdk-for-go/blob/c0e76f5175d47899fca2b5cb698bb42c983b7c46/sdk/resourcemanager/compute/armcompute/virtualmachinescalesetvms_client.go)client instead?

Let me know if this works. Thanks!

**Comment by carlos4ndre** [comment]
@hilaryw29 Thank you for the suggestion, that's exactly what I ended up doing, however the goal of this issue was to have the [NewListPager](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/virtualmachines_client.go#L742) from the [VirtualMachinesClient](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/compute/armcompute/virtualmachines_client.go) client to list all VMs regardless of the VMSS orchestration mode.

As you pointed out in the documentation, the VMs under VMSS with orchestration mode of Uniform are slightly different and that complicates the abstraction for unifying all VMs into a single API call.

The underlying data structures of both types [VirtualMachine](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5#VirtualMachine) and [VirtualMachineScaleSetVM](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5#VirtualMachineScaleSetVM) are not that different, but I imagine different enough to cause problems down the line, unless their data type or interfaces converges on future releases.

Thanks for you help, I'm closing the issue.
