### ISSUE TITLE
Unable to create client for backup vault policy using armdataprotection

### ISSUE THREAD

**Issue by ankitmunot** [Azure/azure-sdk-for-go#21722]
Hello Team,
I am new to azure-sdk-for-go, and I am working on creating a backup vault policy using armdataprotection.
When I try to create a client for armdataprotection, I receive the following error message

**NewClientFactory not declared by package armdataprotection (compile)**

```
func main() {
	cred, err := azidentity.NewClientSecretCredential("TENANT-ID", "APP-CLIENT-ID", "APP-SECRET",nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	clientFactory, err := armdataprotection.NewClientFactory("<subscription-id>", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	
}
```
**Is there something I am missing here?**
**How can I create client for armdataprotection**

cc: @Alancere

**Comment by jhendrixMSFT** [comment]
What version of the `armdataprotection` module are you using?

**Comment by jhendrixMSFT** [comment]
Did you execute `go mod tidy` after updating your `go.mod` file?

**Comment by ankitmunot** [comment]
Hello @jhendrixMSFT Yes, I executed the `go mod tidy`
My `go.mod` after using `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dataprotection/armdataprotection/v2`

![image](https://github.com/Azure/azure-sdk-for-go/assets/31029103/24323af6-fd5d-42e7-b91c-ed85af5bf4b8)

My `go.mod` after using `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dataprotection/armdataprotection`

<img width="651" alt="image" src="https://github.com/Azure/azure-sdk-for-go/assets/31029103/7bd28386-2b12-4c54-b6bb-b7c1d2794fb0">

**Comment by jhendrixMSFT** [comment]
`NewClientFactory()` only exists in `armdataprotection/v2`.

**Comment by raych1** [comment]
> @raych1 Yes I did try using `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dataprotection/armdataprotection/v2 `but then I get error messages like <img alt="image" width="683" src="https://user-images.githubusercontent.com/31029103/273837432-87ae61e8-b1fa-4592-a208-f3a6fe675174.png">

@ankitmunot do you use vscode? That is editor issue. You can still run the code with the warnings. Alternatively, you can open the folder of your code intead of parent folders in vscode which should clean up those errors.

**Comment by ankitmunot** [comment]
Thank you @raych1 @jhendrixMSFT  for helping me out.
I appreciate your time and expertise.
