### ISSUE TITLE
[generator] Automation 2018-01-preview has incorrectly handled name collision

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#2174]
https://travis-ci.org/Azure/azure-sdk-for-go/jobs/399235066

**Comment by vladbarosan** [comment]
The name is `CountType1` but in the preparer it thinks it is `CountType`. note that its not obvious why the renaming occurred in the first place. we might just not need to rename it at all.

**Comment by jhendrixMSFT** [comment]
The adding of the '1' suffix is coming from the front-end, i.e. the modeler passes us JSON with a field name of "CountType1".

**Comment by jhendrixMSFT** [comment]
Fixed in the latest generator version.
