### ISSUE TITLE
Feature Request : Add support for Azure Event Hub in Emulator

### ISSUE THREAD

**Issue by bhapas** [Azure/azure-sdk-for-go#21758]
### Feature Request

This is a feature request to add support for Azure Event Hub to an emulator for local development and testing.

**Comment by richardpark-msft** [comment]
@bhapas, we don't have an emulator in Go, but let me check to see if we have anything for other languages.

**Comment by richardpark-msft** [comment]
@bhapas, I found out there's an Azure Feedback item about the emulator for tracking this: [Azure Feedback (Event Hubs emulator)](https://feedback.azure.com/d365community/idea/39679808-7626-ec11-b6e6-000d3a4f032c).

Closing this issue, in favor of just tracking it there.
