### ISSUE TITLE
NetworkPolicyNotSupported error when supplying NetworkPolicy in kubernetesClustersClient.CreateOrUpdate method

### ISSUE THREAD

**Issue by lfshr** [Azure/azure-sdk-for-go#2176]
NetworkPolicyNotSupported is being thrown when kubernetesClustersClient.CreateOrUpdate is being called with NetworkPolicy specified.

```go
NetworkPolicy := containerservice.NetworkPolicy("calico")

parameters := containerservice.ManagedCluster{
	Name:     &name,
	Location: &location,
	ManagedClusterProperties: &containerservice.ManagedClusterProperties{
		AgentPoolProfiles:       &agentProfiles,
		DNSPrefix:               &dnsPrefix,
		KubernetesVersion:       &kubernetesVersion,
		LinuxProfile:            &linuxProfile,
		ServicePrincipalProfile: servicePrincipalProfile,
		NetworkProfile:          networkProfile,
		NetworkPolicy:          networkPolicy,
	},
}

ctx := client.StopContext
future, err := kubernetesClustersClient.CreateOrUpdate(ctx, resGroup, name, parameters)
```

```
Status=400 Code="NetworkPolicyNotSupported" Message="NetworkPolicy is not supported" Target="networkProfile"
```

**Comment by tombuildsstuff** [comment]
@lfshr I'm unfamiliar with Network Policies, but are they perhaps only supported on a given version of Kubernetes?

**Comment by lfshr** [comment]
@tombuildsstuff none of the documentation indicated such. It may only be a thing on kubenet.

**Comment by vladbarosan** [comment]
@lfshr is this related ? https://github.com/Azure/AKS/issues/435

**Comment by vladbarosan** [comment]
@lfshr is this issue resolved by #2178 resolution ?

**Comment by lfshr** [comment]
@vladbarosan this issue is unrelated. It's also low priority as there is only one network policy at the minute (calico), which is default when not specified. Same goes for #2177

**Comment by lirenhe** [comment]
@lfshr, as this issue was reported a couple of years ago, does this issue still occur?

**Comment by lfshr** [comment]
> @lfshr, as this issue was reported a couple of years ago, does this issue still occur?

I don't really have my environment set up to test. As it was a few years ago, and AKS now supports Kubenet with Calico, I'd assume this could be closed.

**Comment by lirenhe** [comment]
Thanks @lfshr.  Close this item.
