### ISSUE TITLE
Missing a constant for armcontainerservice NetworkPlugin

### ISSUE THREAD

**Issue by dipankardas011** [Azure/azure-sdk-for-go#21761]
Missing a constant in armcontainerservice.NetworkPlugin
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice#NetworkPlugin

> Here none is absent

Why to add?
because some custom CNI solutions like cilium I have to mention `none` as networkPlugin

> **Note**
Unable to find which particular file to modify as the file referenced by go pkg is a generated file

I would like to work on this issue
```[tasklist]
### Tasks
- [ ] find which particular file to change as the constants.go is a generated file
- [ ] add a entry for the constant
```

**Comment by dipankardas011** [comment]
For now I have to do this
```go
parameter.Properties.NetworkProfile = &armcontainerservice.NetworkProfile{
	NetworkPlugin: to.Ptr[armcontainerservice.NetworkPlugin]("none"),
}
```

**Comment by dipankardas011** [comment]
https://github.com/Azure/azure-sdk-for-go/blob/6186b6bb6de7407156a7762afad57f0c58aac0b6/sdk/resourcemanager/containerservice/armcontainerservice/zz_generated_constants.go#L741-748

**Comment by dipankardas011** [comment]
I want to add

```diff
 const ( 
 	// NetworkPluginAzure - Use the Azure CNI network plugin. See [Azure CNI (advanced) networking](https://docs.microsoft.com/azure/aks/concepts-network#azure-cni-advanced-networking) 
 	// for more information. 
 	NetworkPluginAzure NetworkPlugin = "azure" 
 	// NetworkPluginKubenet - Use the Kubenet network plugin. See [Kubenet (basic) networking](https://docs.microsoft.com/azure/aks/concepts-network#kubenet-basic-networking) 
 	// for more information. 
 	NetworkPluginKubenet NetworkPlugin = "kubenet" 
+       // for no CNI plugin
+       NetworkPluginNone NetworkPlugin = "none"
 ) 
```

**Comment by jhendrixMSFT** [comment]
I suspect you can remove the reference to the `v1` module, unless there's a specific reason you need to use both?

**Comment by dipankardas011** [comment]
sure will refactor and see if it works
