### ISSUE TITLE
NetworkPolicy not being returned on kubernetesClustersClient.Get method

### ISSUE THREAD

**Issue by lfshr** [Azure/azure-sdk-for-go#2177]
NetworkPolicy not being returned on kubernetesClustersClient.Get method

Related to #2176

**Comment by vladbarosan** [comment]
@lfshr is this issue resolved by https://github.com/Azure/azure-sdk-for-go/issues/2178 resolution ?

**Comment by lirenhe** [comment]
@lfshr, as this issue was reported a couple of years ago, does this issue still occur?

**Comment by lfshr** [comment]
> @lfshr, as this issue was reported a couple of years ago, does this issue still occur?

Same story with this one. I'd assume it could be closed.

**Comment by lirenhe** [comment]
Thanks @lfshr, close this one.
