### ISSUE TITLE
Feature to create AKS cluster with Azure Monitor Metrics addon (Managed Prometheus)

### ISSUE THREAD

**Issue by lalitmsft** [Azure/azure-sdk-for-go#21773]
### Feature Request

- I can't find the below cli feature while creating aks cluster using [armcontainer package]("github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4"). Is there any plan to provide this feature in the sdk or can you please suggest some workaround to enable this while create a new aks cluster using this sdk

Azure Cli [Feature Reference](https://github.com/Azure/azure-cli/pull/26201)

**Comment by raych1** [comment]
@lalitmsft , I synced up with you offline and provided the solution to enable the addon when calling the API. But I don't see any workspace id was set in the request payload. It doesn't seem that the azure monitor workspace id can be specified from the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/4c38cb9966cd6afbb03c7e9b14997720a728baee/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json#L6473C5-L6506C10). 

I shared you the contact of service team, and let me know if you still need any help.
