### ISSUE TITLE
Unable to import certificate with lifetime actions

### ISSUE THREAD

**Issue by MarkPorohnja** [Azure/azure-sdk-for-go#21780]
### Bug Report

- package: github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azcertificates v1.0.0
- go version go1.21.1 windows/amd64

- What happened?
  - It is not possible to import a certificate into a key vault with specified lifetime actions, but without specifying the content type of the Secret properties (e.g. ContentType: "application/x-pem-file"). This is a known issue that [has already been fixed for azure cli](https://github.com/Azure/azure-cli/issues/27220)
- What did you expect or want to happen?
  - Certificate is imported with lifetime actions without specifying the content type.
- How can we reproduce it?
  - import the certificate using azcertificates.ImportCertificate() func with any lifetime action specified.
- Error: 400 Bad Request
```{
  "error": {
    "code": "BadParameter",
    "message": "Property policy has invalid value\r\n"
  }
}
```

**Comment by gracewilcox** [comment]
Hi @MarkPorohnja! If you are importing a PFX file, you do not have to specify the content type, but you must if you are importing a PEM file. You can do this by adding a `CertificatePolicy` to `ImportCertificateParameters`.

```go
	pemCertPolicy := azcertificates.CertificatePolicy{
		SecretProperties: &azcertificates.SecretProperties{
			ContentType: to.Ptr("application/x-pem-file"),
		},
	}
	importParam := azcertificates.ImportCertificateParameters{
		Base64EncodedCertificate: to.Ptr("PEM_CERT_VALUE"),
		CertificatePolicy:        &pemCertPolicy,
	}
	_, err := client.ImportCertificate(context.Background(), "pemCert", importParam, nil)
	if err != nil {
		// TODO: handle error
	}
```

Hope that answered your question!
