### ISSUE TITLE
ACR - list repositories - no Host in request URL

### ISSUE THREAD

**Issue by rubensymc** [Azure/azure-sdk-for-go#21785]
Following an example from https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry#pkg-overview `ListRepositories`, I am running into an error: `failed to advance page: no Host in request URL`

Code Snippet:
```
import (
	"context"
	"fmt"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry"
)

func main() {	
        cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	client, err := azcontainerregistry.NewClient("<acr-name>.azurecr.io", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}

	ctx := context.Background()
	pager := client.NewListRepositoriesPager(nil)
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range page.Repositories.Names {
			fmt.Printf("repository: %s\n", *v)
		}
	}
}
```

Note: I did ensure I ran "az login" and "az acr login -n <acr-name>" prior to executing.

Go version: `go version go1.21.3 windows/amd64`

**Comment by jhendrixMSFT** [comment]
In the call to `azcontainerregistry.NewClient()` you must specify the complete URL, e.g. `https://<acr-name>.azurecr.io`.

**Comment by rubensymc** [comment]
ah right, thank you @jhendrixMSFT
