### ISSUE TITLE
[azotel] The latest otel package is causing a "Component Governance" alert for codespell

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21791]
The weird thing is that codespell is a Python module (apparently) and it's only coming up because the 3rd party OpenTelemetry package packages up a requirements.txt.

```
--- Component: ---
codespell 2.2.4 - pip
--- Found at: ---
/go/pkg/mod/go.opentelemetry.io/otel@v1.16.0/requirements.txt
```
 
**Component Governance alert**
 
|GPL-2.0 requires legal review           |codespell 2.2.4                         |High                          
 
I'm not quite sure what the right fix is here. Is it intentional that we scan into code that's not used? I would think we'd only care about what's in go.mod.

**Comment by lmolkova** [comment]
So if I understand the problem:
- the codespell Python module has GPL license
- OTel-go uses it to do spell-checking during build time and is not distributing it in any shape or form, so it's not subject to GPL license - https://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL
- We don't  run otel CI pipeline and are not even executing this module

It seems like the alert is false-positive. I'd just suppress it unless someone believes we should get approval from CELA.

**Comment by richardpark-msft** [comment]
This no longer shows up in our component governance list, so I'm just going to close this. All the reasons that @lmolkova listed apply and we'd want to ignore it anyways.
