### ISSUE TITLE
HDInsights 2018-06-01-preview SDK is available but API isn't

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#2180]
👋🏻

I've spent a few hours this morning upgrading to v18 of the SDK - and at the same time looked into moving over to `2018-06-01-preview` of the HDInsights SDK. Unfortunately whilst the SDK is available the API isn't (I've checked the Resource Provider and it's not exposed there) - is there a timeframe for this going live?
Thanks :)

**Comment by jhendrixMSFT** [comment]
@wawon-msft can you please comment?

**Comment by jhendrixMSFT** [comment]
Ping @wawon-msft, CC @joshgav

**Comment by jhendrixMSFT** [comment]
The squishy answer I got was "1-2 deployment cycles" which is pretty vague (Tom I think you're on that thread).  In the meantime the recommendation is to use the old API version.  Sorry I don't have a better answer.
