### ISSUE TITLE
StorageAccount id is lower case in container registry 'Classic' sku.

### ISSUE THREAD

**Issue by lrxtom2** [Azure/azure-sdk-for-go#2181]
Hi team,
We found a issue that rest api always return lower case storage account id in container registry when sku set to 'Classic'. It's not make sense and the issue from rest api level.

Reference:
https://docs.microsoft.com/zh-cn/rest/api/containerregistry/registries/get#storageaccountproperties

Thanks,
Chang

**Comment by tombuildsstuff** [comment]
Duplicate of #1943

**Comment by jhendrixMSFT** [comment]
Closing since this is a dupe (thanks Tom for pointing that out).
