### ISSUE TITLE
Missing `publicNetworkAccess` field on Azure SQL Server sdk api response  #21573

### ISSUE THREAD

**Issue by MaayanLaav** [Azure/azure-sdk-for-go#21815]
Go version 1.21.1

I'm using version:

- Import path: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql v1.0.0

I'm trying to fetch Azure Sql servers using ServersClient.NewListPager(nil) and for some returned sql servers the field `publicNetworkAccess` is missing. (his value should be 'Enabled' or 'Disabled')
When I looked in the built-in azure json that described those sql servers json I saw that the field is exist, In addition when I am using the azure CLI I am also getting this field appropriately. 

This bug is reproduced in some sql servers and not in all sql servers.

here is an example for response from the sdk with the described bug above:
```
{
  "kind": "v12.0",
  "location": "eastus",
  "name": "mysqlserver",
  "properties": {
    "administratorLogin": "mysqladmin",
    "administrators": {
      "administratorType": "***",
      "login": "***",
      "principalType": "***",
      "sid": "***",
      "tenantId": "***"
    },
    "fullyQualifiedDomainName": "mysqlserver.database.windows.net",
    "minimalTlsVersion": "1.2",
    "privateEndpointConnections": [],
    "restrictOutboundNetworkAccess": "Disabled",
    "state": "Ready",
    "version": "12.0"
  }
``` 

Thanks

**Comment by Alancere** [comment]
Hi @MaayanLaav, could you try using [v1.1.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql@v1.1.0) or [v2.0.0-beta.2](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql/v2@v2.0.0-beta.2)?
