### ISSUE TITLE
Can't use certificates from Windows cert store.

### ISSUE THREAD

**Issue by dandan2095op** [Azure/azure-sdk-for-go#21824]
Currently, the environment credential can be created from a secret or a certificate. In our senario, all certificates are stored in Windows cert store and I have tried several Go packages that interact with Windows API, I can only get the content of the cert itself but I can't get the private key. All the packages wrap the key and implement crypto.Signer and crypto.Decrypter for key based operations. However, the NewClientCertificateCredential method requires a rsa.PrivateKey object which I cannot acquire.

So it would the best if the NewCredFromCert method accepts a thumbprint as input and get the corresponding cert and private key from Windows cert store.

Thanks!

**Comment by manicminer** [comment]
@dandan2095op Curious which libraries you might have found to work with the system store? I've had success on macOS (Keychain) and Windows with [github.com/github/smimesign/certstore](https://github.com/github/smimesign/tree/main/certstore), but it'd be great to find a native solution that doesn't require cgo.

**Comment by chlowell** [comment]
We haven't implemented this feature because the cert store isn't accessible from the standard library. If there were a well maintained third-party package with the right license that doesn't require cgo, we could consider it--let me know if you have one in mind.

In the meantime, here's a workaround. ClientCertificateCredential is really a helper for computing JWT assertions from a given private key. If you can't get a key, you can use [ClientAssertionCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ClientAssertionCredential) instead, which implements the same auth flow but lets your application compute assertions. So, you write a callback that returns a JWT in the [specified format](https://learn.microsoft.com/entra/identity-platform/certificate-credentials#assertion-format), signing it with your `crypto.Signer`. You can craft the JWT yourself or integrate your signing logic with a JWT package, for example:

```go
import (
	"context"
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

type signingMethodStoredCert struct{}

func (signingMethodStoredCert) Alg() string {
	return "RS256"
}

func (signingMethodStoredCert) Sign(signingString string, key interface{}) ([]byte, error) {
	h := crypto.SHA256.HashFunc().New()
	h.Write([]byte(signingString))
	// TODO: get a crypto.Signer for the stored cert
	var signer crypto.Signer
	return signer.Sign(rand.Reader, h.Sum([]byte{}), &rsa.PSSOptions{Hash: crypto.SHA256})
}

func (signingMethodStoredCert) Verify(signingString string, sig []byte, key interface{}) error {
	// TODO
	return nil
}

var _ jwt.SigningMethod = (*signingMethodStoredCert)(nil)

func signWithStoredCert(context.Context) (string, error) {
	clientID := "TODO"
	tenantID := "TODO"
	jwt.RegisterSigningMethod("RS256", func() jwt.SigningMethod { return signingMethodStoredCert{} })
	j := jwt.NewWithClaims(signingMethodStoredCert{}, jwt.MapClaims{
		"aud": fmt.Sprintf("https://login.microsoftonline.com/%s/oauth2/v2.0/token", tenantID),
		"exp": json.Number(strconv.FormatInt(time.Now().Add(10*time.Minute).Unix(), 10)),
		"iss": clientID,
		"jti": uuid.New().String(),
		"nbf": json.Number(strconv.FormatInt(time.Now().Unix(), 10)),
		"sub": clientID,
	})
	j.Header = map[string]interface{}{
		"alg": "RS256",
		"typ": "JWT",
		"x5t": base64.StdEncoding.EncodeToString([]byte("TODO: thumbprint")),
	}
	return j.SignedString(nil)
}

func main() {
	cred, err := azidentity.NewClientAssertionCredential(tenantID, clientID, signWithStoredCert, nil)
	if err != nil {
		// TODO
	}
}
```
(there may be a better way to do this; I'm not very familiar with `jwt`)

**Comment by dandan2095op** [comment]
> @dandan2095op Curious which libraries you might have found to work with the system store? I've had success on macOS (Keychain) and Windows with [github.com/github/smimesign/certstore](https://github.com/github/smimesign/tree/main/certstore), but it'd be great to find a native solution that doesn't require cgo.

@manicminer I tried this package from Google. https://github.com/google/certtostore/tree/master

**Comment by dandan2095op** [comment]
> We haven't implemented this feature because the cert store isn't accessible from the standard library. If there were a well maintained third-party package with the right license that doesn't require cgo, we could consider it--let me know if you have one in mind.
> 
> In the meantime, here's a workaround. ClientCertificateCredential is really a helper for computing JWT assertions from a given private key. If you can't get a key, you can use [ClientAssertionCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ClientAssertionCredential) instead, which implements the same auth flow but lets your application compute assertions. So, you write a callback that returns a JWT in the [specified format](https://learn.microsoft.com/entra/identity-platform/certificate-credentials#assertion-format), signing it with your `crypto.Signer`. You can craft the JWT yourself or integrate your signing logic with a JWT package, for example:
> 
> ```go
> import (
> 	"context"
> 	"crypto"
> 	"crypto/rand"
> 	"crypto/rsa"
> 	"encoding/base64"
> 	"encoding/json"
> 	"fmt"
> 	"strconv"
> 	"time"
> 
> 	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
> 	"github.com/golang-jwt/jwt/v5"
> 	"github.com/google/uuid"
> )
> 
> type signingMethodStoredCert struct{}
> 
> func (signingMethodStoredCert) Alg() string {
> 	return "RS256"
> }
> 
> func (signingMethodStoredCert) Sign(signingString string, key interface{}) ([]byte, error) {
> 	h := crypto.SHA256.HashFunc().New()
> 	h.Write([]byte(signingString))
> 	// TODO: get a crypto.Signer for the stored cert
> 	var signer crypto.Signer
> 	return signer.Sign(rand.Reader, h.Sum([]byte{}), &rsa.PSSOptions{Hash: crypto.SHA256})
> }
> 
> func (signingMethodStoredCert) Verify(signingString string, sig []byte, key interface{}) error {
> 	// TODO
> 	return nil
> }
> 
> var _ jwt.SigningMethod = (*signingMethodStoredCert)(nil)
> 
> func signWithStoredCert(context.Context) (string, error) {
> 	clientID := "TODO"
> 	tenantID := "TODO"
> 	jwt.RegisterSigningMethod("RS256", func() jwt.SigningMethod { return signingMethodStoredCert{} })
> 	j := jwt.NewWithClaims(signingMethodStoredCert{}, jwt.MapClaims{
> 		"aud": fmt.Sprintf("https://login.microsoftonline.com/%s/oauth2/v2.0/token", tenantID),
> 		"exp": json.Number(strconv.FormatInt(time.Now().Add(10*time.Minute).Unix(), 10)),
> 		"iss": clientID,
> 		"jti": uuid.New().String(),
> 		"nbf": json.Number(strconv.FormatInt(time.Now().Unix(), 10)),
> 		"sub": clientID,
> 	})
> 	j.Header = map[string]interface{}{
> 		"alg": "RS256",
> 		"typ": "JWT",
> 		"x5t": base64.StdEncoding.EncodeToString([]byte("TODO: thumbprint")),
> 	}
> 	return j.SignedString(nil)
> }
> 
> func main() {
> 	cred, err := azidentity.NewClientAssertionCredential(tenantID, clientID, signWithStoredCert, nil)
> 	if err != nil {
> 		// TODO
> 	}
> }
> ```
> 
> (there may be a better way to do this; I'm not very familiar with `jwt`)

Thanks @chlowell , I'll try your suggestion to see whether it would work.

**Comment by dandan2095op** [comment]
> @dandan2095op Curious which libraries you might have found to work with the system store? I've had success on macOS (Keychain) and Windows with [github.com/github/smimesign/certstore](https://github.com/github/smimesign/tree/main/certstore), but it'd be great to find a native solution that doesn't require cgo.

Hi @manicminer , did you get the private key using this package? It looks like the private key is also wrapped.
// winPrivateKey is a wrapper around a HCRYPTPROV_OR_NCRYPT_KEY_HANDLE.
type winPrivateKey struct {
	publicKey crypto.PublicKey

	// CryptoAPI fields
	capiProv C.HCRYPTPROV

	// CNG fields
	cngHandle C.NCRYPT_KEY_HANDLE
	keySpec   C.DWORD
}

**Comment by manicminer** [comment]
@dandan2095op I haven't tried yet with `github.com/google/certtostore`. Using [`github.com/github/smimesign/certstore`](https://github.com/github/smimesign/tree/main/certstore), I was able to get authentication working with the [HashiCorp Azure SDK](https://github.com/hashicorp/go-azure-sdk) using a key from the system certificate store on both Windows and macOS. For our purposes, we need a solution without cgo.
