### ISSUE TITLE
(&azcore.ResponseError{}).Error() panics

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-sdk-for-go#21838]
### Bug Report

- import path of package in question: "github.com/Azure/azure-sdk-for-go/sdk/azcore"
- SDK version: v1.8.0
- output of `go version`: go version go1.21.1 linux/amd64

The expression `(&azcore.ResponseError{}).Error()` panics because the implementation of `Error()` requires multiple internal fields to be set.

The minimum instantiation of `azcore.ResponseError` that doesn't panic when `Error()` is called is something like:
```
(&azcore.ResponseError{
	RawResponse: &http.Response{
		Request: &http.Request{
			URL: &url.URL{},
		},
		Body: io.NopCloser(bytes.NewReader(nil)),
	},
}).Error()
```

This isn't something that we see is causing a production problem (although perhaps there is a minor robustness issue in the highly improbable production case that any of these fields is not set).

But, it's something that trips us up from time to time in a unit test context - when unit testing some other behavior, it's easy to inadvertently instantiate a ResponseError that will then cause a panic when Error() is called.

If only to simplify unit testing, it would be neat if `(*azcore.ResponseError) Error()` did not panic on a zero value `&azcore.ResponseError{}`.

**Comment by jhendrixMSFT** [comment]
Fix will go out in `azcore@v1.9.0` in November.
