### ISSUE TITLE
Zones is missing in VirtualMachineScaleSetVM

### ISSUE THREAD

**Issue by feiskyer** [Azure/azure-sdk-for-go#2183]
`Zones` is missing in VirtualMachineScaleSetVM. We need this to support availability zones in Kubernetes. Kubernetes is using 2017-12-01 compute api, but zones is also missing in latest 2018-04-01 version.

`Zones` has already been in VirtualMachineScaleSet, so we need add this also to VirtualMachineScaleSetVM.

https://github.com/Azure/azure-sdk-for-go/blob/fbe7db0e3f9793ba3e5704efbab84f51436c136e/services/compute/mgmt/2018-04-01/compute/models.go#L7548-L7570

Could some one help to add this?

cc @brendandburns @khenidak
cc @joshgav @joshgav @jhendrixMSFT

**Comment by joshgav** [comment]
This is a bug with the compute API spec, I opened an issue in the specs repo: https://github.com/Azure/azure-rest-api-specs/issues/3358 and will close this one.
