### ISSUE TITLE
Storage: authenticated requests must reject http endpoints by default

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#21841]
This was done for Entra authentication in `azcore`, see https://github.com/Azure/azure-sdk-for-go/issues/21674. It should be expanded to all authentication schemes in blob storage.

For authentication types where http is allowed (SAS?), you can provide a mechanism to turn off the https requirement.

**Comment by vibhansa-msft** [comment]
As these checks are being done in AzCore already, so we need to do any specific handling in storage moudles?

**Comment by vibhansa-msft** [comment]
I see core is already handling this for Key, SAS and OAuth as part of this pr  :https://github.com/Azure/azure-sdk-for-go/pull/21832/files

**Comment by jhendrixMSFT** [comment]
Does it also need to be applied to shared key authentication?

**Comment by vibhansa-msft** [comment]
Other than SAS it shall be ok to reject http. SAS can be created only for http endpoint so not allowing http there may not work. For other modes it shall be ok. As part of the above PR, which I linked, I see key auth related changes are also done in core itself so is there any expectation or code change from the storage SDK side?

**Comment by jhendrixMSFT** [comment]
`azblob` has its own `SharedKeyCredential` policy that needs to be updated https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/internal/exported/shared_key_credential.go#L189-L218

**Comment by souravgupta-msft** [comment]
Hi @roelarents. We have discussed this scenario internally and have decided to re-enable http endpoints for shared key based auth mode. You can currently either use SAS (where http is supported) or enable HTTPS in Azurite.
We'll do a release next week to fix this.
