### ISSUE TITLE
ARM client calls with policy.WithHTTPHeader() can "leak" headers to AAD

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-sdk-for-go#21847]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/azcore`
- SDK version: `v1.8.0`
- output of `go version`: `go version go1.21.1 linux/amd64`

We have a case where we use `policy.WithHTTPHeader()` to set headers when making an ARM call using an autorest-generated client. We discovered that if the ARM client's credential's cache is empty or stale, then when the credential makes a `GetToken()` call to AAD, the `policy.WithHTTPHeader()` headers are _also_ applied on that call (I didn't expect that to happen).

_Our_ bug was that we were incorrectly setting `Content-Type: application/json` in `policy.WithHTTPHeader()`, whereas under the covers the azidentity libraries send an `application/x-www-form-urlencoded` payload.  We inadvertently stomped the AAD call's `Content-Type` header and as a result saw an "AADSTS9000410: Malformed JSON" error from AAD which confused us.

Clearly we shouldn't have been setting `Content-Type` in the first place, and that's our bug to fix, but more generally it doesn't feel ideal that these headers can "leak" from the "context" of an ARM call over to AAD.

I don't know if there's much to be done about this, but I wanted to mention it just in case.

**Comment by jhendrixMSFT** [comment]
We had a similar problem with tracing, see https://github.com/Azure/azure-sdk-for-go/issues/21784.

This would also impact https://github.com/Azure/azure-sdk-for-go/issues/21704 if we are to implement it.

**Comment by serbrech** [comment]
When you configure headers and querystring and pass it to a call to a client, you don't expect these to be passed to a background GetToken.

I think that the background token renewal should not reuse the same context as the one passed to the call. At least it should not amend its querystring/headers? 

Imagine you pass specific headers (like caching, etags, repeatability headers, referer, ...) to a client call. You wouldn’t want those headers to inadvertently impact the token renewal process happening in the background.

**Comment by jim-minter** [comment]
I think that context cancellation is a good example of where you would want propagation.

**Comment by jhendrixMSFT** [comment]
Yes exactly, we can't not honor any cancellation/deadline/timeout provided by the caller's context.

**Comment by serbrech** [comment]
header and query string are per call to the client.
why would that not be passed as an option.
you even have an existing option type that you pass to all client calls.
why wouldn't that have query string and header on it?

that's also where header that are declared in swagger end up, except that they get a good name, I believe?
so it would make sense if you get

PutSomethingOptions {
    KnownHeader string // declared in swagger
    OtherKnownHeader string
    Headers http.Headers // user can pass anything
}

**Comment by serbrech** [comment]
timeout deadline and cancellation are always driven by the context in go.
but making the context a backdoor way of passing parameters is unusual, not discoverable, and leads to propagation concerns

**Comment by jhendrixMSFT** [comment]
I too would prefer if optional headers/query params were passed via options for the reasons you cite.

**Comment by jhendrixMSFT** [comment]
This will be fixed in `azcore@v1.9.0`
