### ISSUE TITLE
[placeholder] Issue to talk about dependency updating

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21848]

**Comment by richardpark-msft** [comment]
@lirenhe, sounds like have a tool that can automate package updates? Just wondering if you could point me to it (if it's public)

**Comment by lirenhe** [comment]
Could you try this one created by @jhendrixMSFT ? https://github.com/Azure/azure-sdk-for-go/pull/22214/files

**Comment by jhendrixMSFT** [comment]
All that script does is execute `go mod tidy` for all the `go.mod` files it finds under the current working directory.

If we want to ensure releases have current dependencies, perhaps we should integrate a check into the release pipeline that will block the release if `go get -u` introduces a delta in `go.mod`. This would require SDK maintainers to update their dependencies before release (I'm loathe to do this automatically but could be convinced it's safe).

**Comment by richardpark-msft** [comment]
Here's another thing:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow

It seems to have the level of control that we want - controlling the cadence, even whether we update direct or indirect dependencies.

**Comment by richardpark-msft** [comment]
Some more options, so we can consolidate PRs:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

You can configure it to include more updates in a single PR, rather than firing off a single PR for each dep update.
