### ISSUE TITLE
Update arm recording library to use the core recording framework.

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#21858]
Currently arm has its own recording implementation.  This needs to be consolidated to use the same recording framework as core.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/internal/testutil/recording.go

**Comment by tadelesh** [comment]
We've already used `recording` assets from core: https://github.com/Azure/azure-sdk-for-go/blob/cacb59ff743111ba22870446e609b7e9fd9afc30/sdk/resourcemanager/compute/armcompute/availabilityset_live_test.go#L17. For the existed code under arm, we only need to remove it from the code.

**Comment by lirenhe** [comment]
Issue resolved.
