### ISSUE TITLE
Azure Event Hub messaging sdk rebalance ownership

### ISSUE THREAD

**Issue by ZachTB123** [Azure/azure-sdk-for-go#21868]
### Bug Report

Note sure if this a bug report and may be more of a question.

I have an Event Hub with two partitions. I initially spin up a client to consume from the Event Hub following the code example here: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#example-package-ConsumingEventsWithCheckpoints. When starting up, I log a message to show which partition ids it is consuming from. In this example, I see it it is consuming from partition 0 and 1. I then start up another instance of my consumer and see that it takes ownership of partition 1 and the previous client I have running lost ownership over partition 1. I then shut down the second consumer that had ownership over partition 1. I make sure to call `Close()` on the partition processor on shutdown. Even with doing that, I am not seeing the initial consumer take back ownership over partition 1. Per the sample I linked earlier, `processor.NextPartitionClient(context.TODO())` is not receiving another client.

Am I missing a step here?

**Comment by richardpark-msft** [comment]
@ZachTB123, you haven't missed anything, the SDK should (but doesn't currently) relinquish control over the old partitions when it's shutdown, which means any new processors will need to wait for the expiration interval before a partition is considered available. 

I'll add this in.

**Comment by richardpark-msft** [comment]
@ZachTB123, we're releasing a new package tomorrow that should fix this issue. When you stop running the processor it'll automatically relinquish any partitions it owns, making them available immediately.
