### ISSUE TITLE
Azure SQL Database BeginCreateOrUpdate is in a loop forever and not working after retry

### ISSUE THREAD

**Issue by sam-orca** [Azure/azure-sdk-for-go#21860]
### Describe the bug

When I use BeginCreateOrUpdate on DatabaseClient (armsql 1.1.0), the call run indefinitely without  any time scale to stop. If I stop the calls, and try again I got the error
```
RESPONSE 200: 200 OK
        ERROR CODE: DuplicateGeoDrRelation
        --------------------------------------------------------------------------------
        {
          "name": "xxx,
          "status": "Failed",
          "startTime": "2023-11-01T13:59:38.787Z",
          "error": {
            "code": "DuplicateGeoDrRelation",
            "message": "The databases xxx' in server xx and 'xx in server 'xxxx' are already in a replication relation."
          }
        }
```
### Reproduce steps
- Create a Azure SQL Server in subscription A and another server in subscription B
- Add a database with tier S0 to the server in subscription A
- Populate data into the database (2G)
- Copy the database into the server in subscription B with tier Basic
### Sample copy code
```
databaseParams := armsql.Database{
		Location: &location,
		Properties :&armsql.DatabaseProperties{
                      CreateMode:                       to.Ptr(armsql.CreateModeCopy),
                      SourceDatabaseID:                 to.Ptr(sourceDbId),
                      ZoneRedundant:                    False,
                      ReadScale:                        to.Ptr(armsql.DatabaseReadScaleDisabled),
                      RequestedServiceObjectiveName:    to.Ptr(serviceObjectiveName),
                      RequestedBackupStorageRedundancy: to.Ptr(armsql.BackupStorageRedundancyLocal),
                      HighAvailabilityReplicaCount:     to.Ptr(int32(0)),
                      AutoPauseDelay:                   to.Ptr(MaxAutoPauseDelay),
	       },
	       SKU: to.Ptr(armsql.SKU{
	                      Name:     to.Ptr("Basic"),
	                      Tier:     to.Ptr("Basic"),
	                      Capacity: to.Ptr(int32(5)),
               })
	}
poller, err = databaseClient.BeginCreateOrUpdate(
		ctx, ResourceGroup, targetSqlServerName, targetDBName, databaseParams, options)
poller.PollUntilDone(ctx, nil)
		
```
### Expected behavior
Finish with error or successful 

### Environment Summary
Go 1.18
armsql 1.1.0
<img width="2316" alt="Screenshot 2023-11-01 at 14 42 20" src="https://github.com/Azure/azure-sdk-for-go/assets/93520404/9477aeb6-73dc-4a5e-a7c2-da52be6183ed">

**Comment by raych1** [comment]
Hi @sam-orca , is s0 sku the same as basic tier? Did you try to move this DB by azure portal? Can you try and see if that works? Thanks.

**Comment by sam-orca** [comment]
hi @raych1 , 
S0 is Standard tier with 10 DTU, 
Basic is Basic tier with 5 DTU
If you use azure portal, the operation will be stopped because the size of the existing database are bigger than max target database size. 
Just want to note, the steps I give your guys, are just a simplest way to replicate the issue. The same issue happen on a lot of copy operation when you try to copy from database with one tier to the other tier as well. 
P4 -> GP_S_Gen5_8 for example.

**Comment by sam-orca** [comment]
Other notes, when we got stuck, no copy operation could be performed. I have tried through Azure portal as well.

**Comment by sam-orca** [comment]
New update on the issue, it is no longer possible to copy Azure SQL database cross tier using Azure portal anymore. On some certain type of database, it is still possible to use Golang lib. However, most of the cases, now start to come back with exception now. In some rare cases, we could still get into the waiting loop forever. I guess it will go away soon. So, may be safe to close the current issue

**Comment by raych1** [comment]
@sam-orca , thank you for the update. Hopefully we will see the consistency between azure portal and Go SDK. Feel free to re-open this issue if you see this issue again in the future.
