### ISSUE TITLE
NilPointer dereference on BlobIndexTag deletion

### ISSUE THREAD

**Issue by daniel-meyer-dme** [Azure/azure-sdk-for-go#21869]
Hello,
in the latest versions removing all BlobIndexTags leads to a Panic due to a built-in incompatibility which was introduced with https://github.com/Azure/azure-sdk-for-go/commit/5e4becb50868a1ac3a825313e273b0716e687615

// SetTags operation enables users to set tags on a blob or specific blob version, but not snapshot.
// Each call to this operation replaces all existing tags attached to the blob.
**// To remove all tags from the blob, call this operation with no tags set.**
// https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tags
```
func (b *Client) SetTags(ctx context.Context, tags map[string]string, options *SetTagsOptions) (SetTagsResponse, error) {
	serializedTags := shared.SerializeBlobTags(tags)
	blobSetTagsOptions, modifiedAccessConditions, leaseAccessConditions := options.format()
	resp, err := b.generated().SetTags(ctx, *serializedTags, blobSetTagsOptions, modifiedAccessConditions, leaseAccessConditions)
	return resp, err
}
```

Calling it now without any tags set (empty map) the  [shared.SerializeBlobTags(tags)](https://github.com/Azure/azure-sdk-for-go/blame/main/sdk/storage/azblob/internal/shared/shared.go#L147C2-L147C2) returns nil which will be dereferenced on line 4.

**Comment by souravgupta-msft** [comment]
Hi @daniel-meyer-dme. Thanks for reporting this issue. We have merged the fix and it will be part of our next release.
