### ISSUE TITLE
Feature Request: No Attribute for isEnabled For Security Center(Microsoft Defender) Pricing in go sdk

### ISSUE THREAD

**Issue by lchavan-uptycs** [Azure/azure-sdk-for-go#21878]
### Feature Request

- Azure Go SDK used: [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity](http://github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity) v0.8.0
- according to the rest api docs https://learn.microsoft.com/en-us/rest/api/defenderforcloud/pricings/list?view=rest-defenderforcloud-2023-01-01&tabs=Go we have a attribute `Extensions` which have attribute `IsEnabled`  that is missing in Go SDK response object

**Comment by Alancere** [comment]
Hi @lchavan-uptycs, please use latest version: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity@v0.11.0#Extension

**Comment by lchavan-uptycs** [comment]
@Alancere ok will checkout the latest version 
Thank you!!
