### ISSUE TITLE
Feature Request: No API For SQL server periodic recurring scan data

### ISSUE THREAD

**Issue by lchavan-uptycs** [Azure/azure-sdk-for-go#21877]
### Feature Request

- Azure Go SDK used: [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql](http://github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql) v1.0.0
- In SQL Server we can't get data regarding periodic recurring scan of server which is given by the powershell CLI cmd https://learn.microsoft.com/en-us/powershell/module/az.sql/get-azsqlservervulnerabilityassessmentsetting?view=azps-10.4.1 in attribute `RecurringScansInterval`

**Comment by Alancere** [comment]
SDK is a generate from [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/SqlVulnerabilityAssessmentsSettings.json#L61), which needs to support the first.

**Comment by Alancere** [comment]
package released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql/v2#VulnerabilityAssessmentScansClient
