### ISSUE TITLE
Can we assign/map the Encryption key while we are creating a new secret in azure similar to AWS ?. Please help to understand

### ISSUE THREAD

**Issue by Roopan92** [Azure/azure-sdk-for-go#21880]
### Feature Request

In AWS, We have a method to map the Encryption Key (New/Existing KMS) to a secret during the creation flow.

Do we have similar concept in Azure or how the encryption works in Azure Key Vault (Secrets).

Thanks,
Roopan

**Comment by gracewilcox** [comment]
Hi @Roopan92! Key Vault [encrypts](https://learn.microsoft.com/en-us/azure/key-vault/secrets/about-secrets#encryption) secrets at rest with its own internal keys. There is not an option for the user to specify a key to encrypt with.

What is your specific use case? If you want extra protection on your data, you can encrypt the secret with your own key before storing it in Key Vault.

**Comment by Roopan92** [comment]
> Hi @Roopan92! Key Vault [encrypts](https://learn.microsoft.com/en-us/azure/key-vault/secrets/about-secrets#encryption) secrets at rest with its own internal keys. There is not an option for the user to specify a key to encrypt with.
> 
> What is your specific use case? If you want extra protection on your data, you can encrypt the secret with your own key before storing it in Key Vault.



> Hi @Roopan92! Key Vault [encrypts](https://learn.microsoft.com/en-us/azure/key-vault/secrets/about-secrets#encryption) secrets at rest with its own internal keys. There is not an option for the user to specify a key to encrypt with.
> 
> What is your specific use case? If you want extra protection on your data, you can encrypt the secret with your own key before storing it in Key Vault.

Having below 2 queries,

1) We have a use case to implement in Azure similar to AWS. If you see the below screenshot we have an option to choose an encryption key (KMS) while we creating a secret in AWS.

![image](https://github.com/Azure/azure-sdk-for-go/assets/33746861/577e3efb-6b65-4a1f-a3d8-90591a5a2561)

So, do we have that option to choose?

2) Did we had EncryptionKey as a property in the SecretAttributes Model in azure go-sdk and removed later?. If yes, please explain why.

**Comment by gracewilcox** [comment]
Hi @Roopan92, to answer your questions:

1. No, it is not possible in Azure to choose an encryption key when creating a secret. The service handles the encryption automatically for you when creating a secret. You can read more about the Azure Key Vault encryption process [here](https://learn.microsoft.com/en-us/azure/key-vault/secrets/about-secrets#encryption).
2. No, EncryptionKey has never been a property in the SecretAttributes model. It is not a capability of the service.

Is there a reason you must use your own encryption key?

**Comment by Roopan92** [comment]
@gracewilcox - Sorry for the delay response.

Got your answer, but few more queries below

- How to achieve the custom encryption of the secret before strong into the key vault?
- Also how can we use DEK (Data Encryption Key)
-

**Comment by gracewilcox** [comment]
Hi @Roopan92!

There are multiple approaches to encryption. You could use the [Client.Encrypt](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys#Client.Encrypt) and [Client.Decrypt](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys#Client.Decrypt) methods in the [azkeys](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys) module. There are also other methods to encrypt and decrypt that don't involve Azure.

I'm a little unclear on your second question, but if you want to use keys with Azure, you can use the [azkeys](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys) module.
