### ISSUE TITLE
[azblob] Blob metadata doesn't load metadata keys with nil values

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21887]
### Bug Report

**Package and version**: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.2.0` (I don't think this is a newer/older package issue)

**Details**

Blobs let you store metadata with a blob, independent of the content. These are just key/value pairs, where the values are `*string`s. It is possible to set the value of a blob property to null, and then retrieve that value as well. In the BlobItem type it looks like this:

```go
// BlobItem - An Azure Storage blob
type BlobItem struct {
  // Dictionary of
  Metadata map[string]*string `xml:"Metadata"`
}
```

However, our blob package doesn't seem to be able to deserialize this. Instead of getting back a map with an `ownerid` key and a `nil` value it returns an empty map altogether. 

You can use code like this to see the bug:

```go
pager := cc.NewListBlobsFlatPager(&container.ListBlobsFlatOptions{
  Include: container.ListBlobsInclude{
    Metadata: true,
  },
})

for pager.More() {
  page, err := pager.NextPage(context.Background())

  for _, blob := range page.Segment.BlobItems {
    // blob.Metadata will just be a nil - it won't contain an `ownerid` key.
    fmt.Printf("%s, %#v\n", *blob.Name, blob.Metadata)
  }
}
```

In the XML response from Azure Storage you can see they do send us back enough information to construct the map:

```xml
// a whole bunch of other XML elided
  <Metadata>
      <ownerid />
  </Metadata>
```

**Comment by jhendrixMSFT** [comment]
Is creating metadata without a value a supported scenario? Per the [REST docs](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata?tabs=microsoft-entra-id#request-headers) it doesn't imply that it is although it's a big vague. In addition, the portal won't let you create metadata without a value.

Could it be that we have a bug that's allowing creation of metadata with a `nil` value? But then you'd think the service would reject it.

**Comment by jhendrixMSFT** [comment]
Metadata with `nil` values will be skipped, see the example [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/internal/generated/zz_blob_client.go#L2429-L2435).

**Comment by jhendrixMSFT** [comment]
Ok this isn't about `nil` values but empty values.
```go
_, err = client.SetMetadata(context.Background(), map[string]*string{
	"key1": to.Ptr(""),
}, nil)
```
Which the server accepts.

**Comment by richardpark-msft** [comment]
There are two routes to getting metadata that I just tried:

1. <blob>.GetProperties

  When you get the properties of a blob where the `ownerid` property was to "" (as you have) you get back a metadata map with a key of `Ownerid` (note that the capital `O`). The value, is an empty string, which is great!

  Java returns the metadata with the correct casing and an empty string for the value.

2. <container>.NewListBlobsFlatPager, with the 'Metadata: true` in the options

  When you do this you get back an empty metadata map.

  Java returns a metadata map with the `ownerid` property set to `null` (not a string value of null).

@jhendrixMSFT, which one are you using? And now I wonder if the results are different if there's more than one key in that metadata - my use case only has a single key.

**Comment by jhendrixMSFT** [comment]
`GetProperties` returns metadata in HTTP headers and, due to the standard library's canonicalization of HTTP headers, the casing will _not_ be preserved.

My repro uses `NewListBlobsFlatPager`. However, I've noticed that the server is sending back the `null` string value.
```xml
<key1>null</key1>
```
`key1` was created as per my sample above. So, I can only assume that the service changed the empty value to `null`.

**Comment by jhendrixMSFT** [comment]
In my experiment I added `key2` via the portal and I suspect that when I did this the service changed the empty value to `null`. At any rate, I will fix the unmarshaller to handle keys with empty values. My preference would be to leave the value as `nil`. However, for consistency with the header version I can set it to the empty string if we think that's better.
