### ISSUE TITLE
[Identity] Evaluate expires_on field in AzureCLICredential

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-go#21886]
As of [Azure CLI v2.54.0](https://github.com/Azure/azure-cli/milestone/135), the `az account get-access-token` command returns a new `expires_on` field containing a POSIX timestamp. This behavior is a departure from previous versions, in which the local datetime was returned in an `expiresOn` field. Update `AzureCliCredential` to also consider the new `expires_on` field.

Related links:
- https://github.com/Azure/azure-sdk-for-cpp/pull/5076#issuecomment-1784680918
- https://github.com/Azure/azure-cli/pull/27476

**Comment by scottaddie** [comment]
Marking as blocked until the az cli release ships.

**Comment by antkmsft** [comment]
> Marking as blocked until the az cli release ships.

Az CLI v.2.54.0 has shipped, I was able to obtain it via Winget.

**Comment by ahsonkhan** [comment]
Office hour discussion conclusion across languages:
https://github.com/Azure/azure-sdk-for-cpp/issues/5116#issuecomment-1832731537
