### ISSUE TITLE
Question: How can I query the data transfer cost grouped by regions with Usage API?

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#21916]
As the title asks.

https://github.com/Azure/azure-sdk-for-go/blob/f252cd9f178d89af5a3b0f595e72c8b1479904c7/sdk/resourcemanager/costmanagement/armcostmanagement/forecast_client.go#L120

**Comment by Alancere** [comment]
You can refer to this [example](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/costmanagement/armcostmanagement/forecast_client_example_test.go#L158), which seems to have some filter related examples
