### ISSUE TITLE
servicebus resend the msg after the msg is acknowledged successfully by asb client

### ISSUE THREAD

**Issue by emmettxie05** [Azure/azure-sdk-for-go#21912]
### Bug Report

- import path of package in question  :  github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
- SDK version azservicebus v1.4.1
- go version 1.19

- What happened?
Our code use ReceiveModePeekLock to receive msg.  when my code call func CompleteMessage to ack one msg, it returns nil error, which means success,  but later service bus resend the msg with same msg id (uuid), our svc tries to acknowledge the msg again, then we get error "error":"(locklost): *Error{Condition: com.microsoft:message-lock-lost, Description: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions ".  
Then the process would repeat  and we get the same error till the msg moves to deadletter queue.   The issue is hard to reproduce,  I see twice after the svc receive thousands of asb msgs. 
- What did you expect or want to happen?
if the msg is acknowledged successfully,  service bus should not resend the same msg
- How can we reproduce it?
  just receive , parse and acknowledge the asb message, after process thousands of asb msgs, the issue may happen.  

- Anything we should know about your environment.

**Comment by richardpark-msft** [comment]
@emmettxie05, trying to narrow this down a bit so I can repro this locally (we do have quite a few tests, but maybe I've missed a case).

- Are you renewing locks at any time? Or are you just using the default lock timeout?
- How long is your lock timeout set on the queue/subscription side?
- Are you using queues or topics+subscriptions?
- Are you explicitly setting the message ID? Or just letting it get autogenerated by the library?

**Comment by emmettxie05** [comment]
> @emmettxie05, trying to narrow this down a bit so I can repro this locally (we do have quite a few tests, but maybe I've missed a case).
> 
> * Are you renewing locks at any time? Or are you just using the default lock timeout?
No, I just use default lock timeout
> * How long is your lock timeout set on the queue/subscription side?
we don't  set it, if should be some default value
> * Are you using queues or topics+subscriptions?
It is topics + subscriptions
> * Are you explicitly setting the message ID? Or just letting it get autogenerated by the library?
we don't provide the explicit  message ID,  but use auto-generated one.

**Comment by gkampitakis** [comment]
I am noticing a similar issue with versions `v1.5.0` after around 1.5k reading and `completing` messages I start to get errors 

```
(locklost): rpc: failed, status code 410 and description: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions .
```

and then same messages are resent. 

For my our case: 
- Are you renewing locks at any time? Or are you just using the default lock timeout?
No, just the default
- How long is your lock timeout set on the queue/subscription side?
30seconds
- Are you using queues or topics+subscriptions?
Queues
- Are you explicitly setting the message ID? Or just letting it get autogenerated by the library?
Just the autogenerated.


The setup we use, is we have a pool of receivers for processing in parallel so a message might be received from one client and marked as completed from another client. (not sure if this information is relevant).

**Comment by gkampitakis** [comment]
An update on my side, it was a misconfiguration on our side, keeping messages buffered in the service and indeed locks were expiring.

**Comment by emmettxie05** [comment]
> An update on my side, it was a misconfiguration on our side, keeping messages buffered in the service and indeed locks were expiring.

So you mean, if the message is kept in service, and service does not send ACK immediately, then the locks would be expiring, and we would see the error mentioned in the issue?  But if service does not send ack immediately, ASB would resend this new message, right?

**Comment by gkampitakis** [comment]
> So you mean, if the message is kept in service, and service does not send ACK immediately, then the locks would be expiring

Not immediately. It depends on the message lock duration that you have set up. So if you keep a message buffered for longer (or processing) than this period, the lock expires and the Service Bus, yes, redelivers it.

**Comment by richardpark-msft** [comment]
@emmettxie05, does it sound like this might be the issue you're seeing? If the lock expires you don't get an active notification. You can avoid this by using receiver.RenewLock(), at periodic intervals, or extending the lock timeout on the queue/subscription itself.

I haven't been able to repro this bug using our tests.
