### ISSUE TITLE
Selected user account does not exist in tenant 'Microsoft Services'

### ISSUE THREAD

**Issue by bkievitk-gozamm** [Azure/azure-sdk-for-go#21915]
### Bug Report

When using NewInteractiveBrowserCredential, we are seeing 

"Selected user account does not exist in tenant 'Microsoft Services' and cannot access the application '<id>' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account."

Our app is set up with "Supported account types" = "Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)" and our goal is for any Microsoft user to be able to log in through our app.

Example Code:

	cred, _ := azidentity.NewInteractiveBrowserCredential(&azidentity.InteractiveBrowserCredentialOptions{
		ClientOptions: policy.ClientOptions{
			Cloud: cloud.AzurePublic,
		},
		AdditionallyAllowedTenants: []string{"https://login.microsoftonline.com/common"},
		ClientID:                   clientId,
		TenantID:                   tenantId,
		RedirectURL:                "http://localhost:4300/login_microsoft",
	})

	token, err := cred.GetToken(context.TODO(), policy.TokenRequestOptions{
		Scopes:   []string{"openid", "profile", "email"},
		TenantID: tenantId,
	})
	fmt.Printf("%+v\n", err)
	fmt.Printf("%+v\n", token)

**Comment by chlowell** [comment]
As the error states, your application tried to authenticate a user who doesn't exist in `tenantId`, which I guess is some specific tenant. You want instead to authenticate users in their home tenants. The `/common` endpoint will handle that, so `common` isn't an additionally allowed tenant, it's the one you want to use in all cases. Try this:
```go
cred, _ := azidentity.NewInteractiveBrowserCredential(&azidentity.InteractiveBrowserCredentialOptions{
	// you could omit this because AzurePublic is the default cloud
	ClientOptions: policy.ClientOptions{
		Cloud: cloud.AzurePublic,
	},
	ClientID:    clientId,
	TenantID:    "common",
	RedirectURL: "http://localhost:4300/login_microsoft",
})
```

**Comment by bkievitk-gozamm** [comment]
Thanks for the response. I was able to get a step further with the "common" tenantID, but now running into a missing client_secret with the error below and now sure how to provide that to the NewInteractiveBrowserCredential.

RESPONSE 401 Unauthorized
--------------------------------------------------------------------------------
{
  "error": "invalid_client",
  "error_description": "AADSTS70002: The provided request must include a 'client_secret' input parameter. Trace ID: 94eceb22-15ff-4e13-a4e6-5d674106d102 Correlation ID: bfb80e64-09b9-40c9-afe5-bb3920564ed7 Timestamp: 2023-11-15 02:19:26Z",
  "error_codes": [
    70002
  ],
...

How do I provide the client_secret to the interactive browser?

Also a question on setting the redirect URI in portal.azure.com. It says that redirects can start with https or http://localhost, but when I try http://localhost:4300/login_microsoft it seems to fail. Should this read starts with https or is exactly http://localhost?

**Comment by chlowell** [comment]
That error means the Entra app doesn't have a redirect URI for mobile and desktop applications. [This doc](https://learn.microsoft.com/entra/identity-platform/quickstart-register-app#configure-platform-settings) describes how to add one in the Azure Portal.

The underlying authentication library we use to implement browser authentication redirects only to `http://localhost` and allows specifying only the port. It ignores any path, so given `http://localhost/login_microsoft` it will redirect to `http://localhost`. Does your application need to specify the path?

**Comment by bkievitk-gozamm** [comment]
Thanks. I have a Web redirect already set up (I'm using http://localhost, was just hoping I could use a path too) as well as a secret. The problem is, I don't know how to pass the secret to the NewInteractiveBrowserCredential so I'm getting an invalid_client. Sorry for posting two questions in one last time.

**Comment by chlowell** [comment]
It's no trouble, ask as many questions as you like. NewInteractiveBrowserCredential doesn't take a client secret because that credential type is intended for applications like CLI tools that authenticate users on those users' machines and therefore can't protect a client secret. If your application has a redirect URI only for the "Web" platform, Entra will consider it a server application and expect a client secret for authentication. To authenticate users interactively without a client secret, your application needs a redirect URI for the desktop apps (see [this doc](https://learn.microsoft.com/entra/identity-platform/quickstart-register-app#configure-platform-settings) for a walkthrough).
