### ISSUE TITLE
Codegen fails on operations that return an externally defined type

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-for-go#21931]
### Bug Report

codegen version: autorest.go@4.0.0-preview.60

This is the spec pull request which has the issue.
https://github.com/Azure/azure-rest-api-specs/pull/26493/checks?check_run_id=18516475575

**Comment by jhendrixMSFT** [comment]
The issue here is an operation that returns a schema with the `x-ms-external` attribute set. Fixable, but would first like to understand if we really need to support this.

**Comment by jhendrixMSFT** [comment]
Turns out this is an authoring error and will be fixed. Closing for now as we don't need to support this.
