### ISSUE TITLE
Feature Request: Configurable Timeout for AzureCLICredential in `azidentity`

### ISSUE THREAD

**Issue by Aricg** [Azure/azure-sdk-for-go#21985]
#### Description
 make the timeout duration configurable in the `AzureCLICredential` of the `azidentity` package. Currently, the timeout is hardcoded to 10 seconds.

#### Justification

```
  Error: Failed to get release foo in namespace default: exit status 1: Error: failed to get token: expected an empty error but received: AzureCLICredential: signal: killed
```

#### Suggested Implementation
The timeout could be made configurable through the `AzureCLICredentialOptions` struct. For instance, a new field `Timeout` could be added to this struct. This new field would then be used in the `authenticate` method of `AzureCLICredential`.
this would I believe be a Non-Intrusive Addition: Adding a new field to a struct in Go does not alter the existing behavior of the struct for current users. Existing code that creates and uses AzureCLICredentialOptions without setting the new Timeout field will continue to function as before, as Go initializes unspecified fields to their zero value.

#### Current Code Reference
The current implementation with the hardcoded timeout is located here:
[azure_sdk_for_go/azure_cli_credential.go at e1d15b65278a1c714f2dd1349fa4098d72d0fe7b](https://github.com/Azure/azure-sdk-for-go/blob/e1d15b65278a1c714f2dd1349fa4098d72d0fe7b/sdk/azidentity/azure_cli_credential.go#L82)

#### Additional Context
This feature request is motivated by intermittent failures observed in projects that use `azidentity`, specifically when integrating with tools like `kubelogin`. An example of such an issue can be found here: [kubelogin issue #223](https://github.com/Azure/kubelogin/issues/223)

**Comment by Aricg** [comment]
Its configurable in the python sdk

```
from azure.identity.aio import AzureCliCredential

# Create an AzureCliCredential with a custom timeout of 30 seconds
credential = AzureCliCredential(process_timeout=30)
```
https://github.com/Azure/azure-sdk-for-python/blob/ca7bc6c1ab786160c96dad4c1d1b2457001bf91c/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L181

**Comment by chlowell** [comment]
You can control this timeout by setting a deadline on the `Context` you pass to the client method or to `GetToken()`. Since v1.3.0 we impose the default timeout only when the given `Context` has no deadline:
https://github.com/Azure/azure-sdk-for-go/blob/7d4a3cbaadd5bf9f16322e1e2c673a633f146fb1/sdk/azidentity/azure_cli_credential.go#L105-L110

**Comment by Aricg** [comment]
thanks. https://github.com/Azure/kubelogin/pull/362
