### ISSUE TITLE
Subnet previously used by deleted api management service cannot be deleted

### ISSUE THREAD

**Issue by torresdal** [Azure/azure-sdk-for-go#2199]
I'm currently implementing support for the API Mangement service in Terraform and ran into an issue where our integration tests fail when trying to delete a subnet previously used by a deleted API Management service. (ref: https://github.com/terraform-providers/terraform-provider-azurerm/pull/1516)

The actual error :

`autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet testsubnet1 is in use by /subscriptions/0967fd64-a807-47e1-bf05-0e55e24a68d5/providers/Microsoft.ApiManagement/service?vnetResourceGuid=4b40d13c-b439-4ea8-b898-844b4413c252&subnet=testsubnet1&api-version=2016-07-07 and cannot be deleted." Details=[]`

**Note:** We can eventually delete the subnet, but usually it takes close to an hour before we can do so.

Taking into account that it takes from 30-50 minutes to create the API Management service in Azure and only seconds to delete it, it would be safe to assume that the actual underlying Azure resources are still being deleted behind the scenes, after [`ServiceClient.Delete()`](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2017-03-01/apimanagement#ServiceClient.Delete) has succeeded. It would also be natural to assume that these resources are the ones preventing the subnet to be deleted.

What I would expect is that [`ServiceClient.Delete()`](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2017-03-01/apimanagement#ServiceClient.Delete) would return a `azure.Future` (instead of `autorest.Response`) and where `WaitForCompletion()` would succeed when all underlaying API Management resources are properly deleted, or at least detached from resources like subnet.

**Comment by jhendrixMSFT** [comment]
@promoisha is this something you can help with?

**Comment by torresdal** [comment]
@jhendrixMSFT @promoisha Any update on this?

**Comment by jhendrixMSFT** [comment]
This will be tracked in https://github.com/Azure/azure-rest-api-specs/issues/4409.
