### ISSUE TITLE
[sdk/azcore/cloud] Add proper managed service identities to cloud configurations

### ISSUE THREAD

**Issue by MaxHorstmann** [Azure/azure-sdk-for-go#22018]
### Feature Request

Cloud configurations (`AzureChina`,`AzureGovernment`,`AzurePublic`) ship with AD hosts included. It would be helpful if they also came with the respective managed service identities included.

See PR #22017 for a suggestion.

**Comment by RickWinter** [comment]
@chlowell, @scottaddie Is this something Identity has considered doing?

**Comment by chlowell** [comment]
I don't understand the proposal. Applications don't need cloud-specific information to authenticate managed identities. The linked PR adds an audience for a "managedServiceIdentity" service; I don't know what that service is, but in general we don't add authentication information for services directly to `azcore`. Instead, each client library does that at runtime when imported, [like this](https://github.com/Azure/azure-sdk-for-go/blob/e8defc77367f50a8e61ba3cf9fbe221d81d4f39d/sdk/monitor/azquery/cloud_config.go#L17). So far as I can tell, we don't have a client library for a "managedServiceIdentity" service, which explains why we don't add this audience to cloud configurations today. That also means we have no use for the audience added in the PR i.e., no client would use that value.

@MaxHorstmann, can you describe the scenario you're trying to unblock with this issue/PR?

**Comment by MaxHorstmann** [comment]
Hi @chlowell, thanks for your response. Honestly, it's been a few months and I longer recall the details here, so I'd suggest we close this for now. If anyone else feels the need to investigate further I can make an effort to refresh my memory. :) Thanks again!
