### ISSUE TITLE
[aztables] Field of type aztables.EDMDateTime is being written as String instead of DateTime 

### ISSUE THREAD

**Issue by nathan815** [Azure/azure-sdk-for-go#22019]
### Bug Report

I have an entity struct `MyEntity` with field CreatedTime of type `*aztables.EDMDateTime`. When I upsert this entity into a table, CreatedTime is written with type `String`. I am expecting it to be of type `DateTime`. 

Version outputs:

```
# go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore       
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.8.0

# go list -m github.com/Azure/azure-sdk-for-go/sdk/data/aztables
github.com/Azure/azure-sdk-for-go/sdk/data/aztables v1.0.2

# go version
go version go1.21.3 windows/amd64
```

Self-contained reproducible example:

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/data/aztables"
)

func main() {
	ctx := context.Background()
	err := InsertTestEntity(ctx)
	if err != nil {
		panic(err)
	}
}

type MyEntity struct {
	aztables.Entity
	Name        string
	CreatedTime *aztables.EDMDateTime
}

func InsertTestEntity(ctx context.Context) error {
	client := newTableClient("test")
	client.CreateTable(ctx, nil)
	now := aztables.EDMDateTime(time.Now())
	entity := MyEntity{
		Entity:      aztables.Entity{PartitionKey: "test", RowKey: "test"},
		Name:        "test",
		CreatedTime: &now,
	}
	entityJson, err := json.Marshal(entity)
	if err != nil {
		return fmt.Errorf("failed to marshal entity to json: %w", err)
	}
	_, err = client.UpsertEntity(ctx, entityJson, &aztables.UpsertEntityOptions{
		UpdateMode: aztables.UpdateModeReplace,
	})
	if err != nil {
		return fmt.Errorf("failed to add entity: %w", err)
	}
	return nil
}

func newTableClient(tableName string) *aztables.Client {
	accountName, ok := os.LookupEnv("AZURE_STORAGE_ACCOUNT")
	if !ok {
		panic("AZURE_STORAGE_ACCOUNT environment variable not found")
	}
	accountKey, ok := os.LookupEnv("AZURE_STORAGE_ACCESS_KEY")
	if !ok {
		panic("AZURE_STORAGE_ACCESS_KEY environment variable not found")
	}

	cred, err := aztables.NewSharedKeyCredential(accountName, accountKey)
	if err != nil {
		panic(err)
	}
	serviceURL := fmt.Sprintf("https://%s.table.core.windows.net/%s", accountName, tableName)
	client, err := aztables.NewClientWithSharedKey(serviceURL, cred, nil)
	if err != nil {
		panic(err)
	}
	return client
}
```

Screenshot of table entity in portal:

![image](https://github.com/Azure/azure-sdk-for-go/assets/1972782/1bf638bb-ce92-449b-88bf-7760105cc6f7)

Am I doing something wrong here?

**Comment by nathan815** [comment]
@jhendrixMSFT Thank you! 

I am curious - is this due to a technical limitation with Go's type system, or this was intentional by design?

**Comment by jhendrixMSFT** [comment]
I think it's a bit of both. Table storage uses [`odata.type`](https://learn.microsoft.com/en-us/rest/api/storageservices/payload-format-for-table-service-operations#property-types-in-a-json-feed) annotations to describe a type. If you look at the JSON that's sent over the wire, you'll see two entries for the `CreatedTime` field (the value and its `odata.type`).
```json
"CreatedTime":"2023-11-20T14:52:09.0392181Z","CreatedTime@odata.type":"Edm.DateTime"
```
If you were to define you struct as follows.
```go
type MyEntity struct {
	aztables.Entity
	CreatedTime time.Time
}
```
It would require you to define a custom marshaler for `MyEntity` that emits the `odata.type` annotation for `CreatedTime` which is burdensome.

We probably could have made your original example work with a slight change to the marshaler for `aztables.EDMDateTime`. I'm not sure why we didn't do that, and the person that wrote this is no longer on the team (I wasn't involved in this design).

**Comment by nathan815** [comment]
Got it. Thanks for the explanation!

**Comment by jhendrixMSFT** [comment]
Closing. Please ping back if you have further questions.
