### ISSUE TITLE
Machine Readable Error Messages, or Error Message Contract

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/azure-sdk-for-go#22047]
### Feature Request
We have been working with the azure sdk for go for our oss project, and we have ran into a couple of issues with the azcore.ResponseError type (not all of them are the fault of the sdk, but worth mentioning).

1. Brittle Error Message Contract. 
2. Very human readable, not very machine readable messages back in response. 

https://github.com/Azure/azure-sdk-for-go-extensions/blob/main/pkg/errors/armerrors.go is one example of a package we wrote. But this code is brittle because there is no message guarantee. 

It would be nice if we could have a couple of things. 

1. Rather than having to parse the error message contents, we could get back a subcode telling us this is a quota error, and what kind of quota error(Zonal, TotalCoresQuota, or SKUFamilyQuota). This would fall on the individual RP to give us this back? Currently we do a very grotesque parsing of the error message looking for a specific term to determine which type of quota error it is and how to respond. This approach scares me as the contract here is not guaranteed and there is no other way to do this(please share if there is) 
2. Proper json messages so we can choose which parts of the error to log or share.

**Comment by jhendrixMSFT** [comment]
The error contract specified across all Azure services is that only the HTTP status code and error code (either in the body or in the `x-ms-error-code` header) are contractual and to be programmatically used (the message is considered volatile and subject to change). Looking at your examples, it would seem that in some cases, the service returns a generic `OperationNotAllowed` with details in the message which isn't very helpful. Do you happen to have an example HTTP response in such cases? I'm wondering if some of this info is returned via other HTTP headers (SDK [logging](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#hdr-Built_in_Logging) can help with this).

CC @JeffreyRichter

**Comment by JeffreyRichter** [comment]
I agree with everything Joel said. Plus, if you want better errors from a particular service, then you must reach out to that service team to get them to change the service - this will benefit SDKs in all programming languages as well as customers not using an SDK at all.
