### ISSUE TITLE
Wrong wording in HTTPRange doc

### ISSUE THREAD

**Issue by tomyl** [Azure/azure-sdk-for-go#22054]
https://github.com/Azure/azure-sdk-for-go/blob/9858c485b320dd70ac8464bf83820baea133efbb/sdk/storage/azblob/internal/exported/exported.go#L14-L16

Shouldn't it say
>  An HTTPRange which has an offset but a zero value count indicates from the offset to the resource's end.
?

**Comment by tomyl** [comment]
> "A zero-value HTTPRange indicates the entire resource." : it mentions the same, which part you feel is wrong here ?

The last sentence in the doc which I believe refers to the case when `Offset > 1` and `Count == 0` however the doc says `but no zero value count` which I interpret as `Count != 0`.

**Comment by souravgupta-msft** [comment]
@tomyl, thanks for pointing this. The doc has been updated.
