### ISSUE TITLE
Azure CosmosDB SDK for Go support cross-partition queries?

### ISSUE THREAD

**Issue by amirvalipour-se** [Azure/azure-sdk-for-go#22090]
### Feature Request

I am using the Azure CosmosDB SDK for Go for my application, and I need to perform a cross-partition query in Cosmos DB. However, I'm not sure if the SDK supports this or how to correctly implement it.
Do we already have this feature?????

**Comment by ealsur** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-go/issues/18578

**Comment by ealsur** [comment]
@KiraTheGenius Please use the existing Issue to track this feature's progress if you want. No, the SDK currently does not support cross-partition queries.
