### ISSUE TITLE
EventHub partitions are not equally spread across all service instances; 

### ISSUE THREAD

**Issue by dmoeff** [Azure/azure-sdk-for-go#22097]
I have Kubernetes service with 32 instances connected to Azure EventHub with 32 partitions. Some of the instances of the service are not able to connect to any partition, where other are connected to 2 partitions. My expectation is every instance of the service to process events from a single partition when the number of instances is equal to the number of partitions.

My service is using github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs v1.0.2 package and is running on AKS cluster. It is built on top of [ConsumingEventsWithCheckpoints](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#example-package-ConsumingEventsWithCheckpoints) example using go version 1.21

**Comment by richardpark-msft** [comment]
How long does this unbalanced situation last? Are we talking "never resolves" or "resolves after a few minutes?"

**Comment by richardpark-msft** [comment]
@dmoeff, I was able to reproduce this with a better test than I had. I have the draft PR out, and will get it out early next year.

**Comment by ilyasse05** [comment]
i have the same problem look forward to the solution ;)

**Comment by richardpark-msft** [comment]
Released as part of https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fmessaging%2Fazeventhubs%2Fv1.0.3
