### ISSUE TITLE
Documentation shows wrong module version in go get commands

### ISSUE THREAD

**Issue by divega** [Azure/azure-sdk-for-go#22127]
For example, the documentation for v4 of the network module shows the command to get the v2 version of the module:

https://github.com/Azure/azure-sdk-for-go/blob/b1a2f3d47742f35adc340eb68f7d9418364f3dc7/sdk/resourcemanager/network/armnetwork/README.md?plain=1#L23

I haven't checked but I wouldn't be surprised if other versions are incorrect.

The bug in the documentation is reflected in https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v4#section-readme as well.

**Comment by raych1** [comment]
@divega , thanks for reporting this issue.  readme.md will be updated in this month's release.

**Comment by raych1** [comment]
The module version has been corrected at https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/network/armnetwork/README.md. 

And the next release in this month will have the new right version.

**Comment by tadelesh** [comment]
New version released.
