### ISSUE TITLE
[azidentity]Support authorize with shared key

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#22138]
### Feature Request

Sharedkey should be supported when the blob container enabled accesssharedkey.
https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key

**Comment by jhendrixMSFT** [comment]
`azidentity` is for authenticating with Entra, not the various forms of key authentication.

`azblob` already supports key authentication with the `SharedKeyCredential` type ([example](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/examples_test.go#L47-L52)).

**Comment by jhendrixMSFT** [comment]
CC @chlowell

**Comment by MartinForReal** [comment]
Thanks for your help! @jhendrixMSFT
