### ISSUE TITLE
[azblob] How to handle service errors

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#22139]
We use azure storage extensively. We have a job that enumerates all the blobs in a container.

Occasionally, we see errors like

```
RESPONSE 503: 503 Egress is over the account limit.\nERROR CODE:
ServerBusy\n--------------------------------------------------------------------------------\n\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ServerBusy</Code><
Message>Egress is over the account limit.\nRequestId:xxxxxxxx-d01e-0040-5435-2d2753000000\nTime:2023-12-12T19:56:04.6617055Z</Message></Error>\n
```

```
503: 503 Operations per second is over the account limit.\nERROR CODE: ServerBusy\n--------------------------------------------------------------------------------\n\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ServerBusy</Code><Message>Operations per second is over the account limit.\nRequestId:xxxxxxxx-101e-0008-3080-274dce000000\nTime:2023-12-05T13:37:07.3856984Z</Message></Error>\
```

and few other 5xx errors

according to the [docs](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist?source=recommendations#timeout-and-server-busy-errors), we can retry if we encounter these errors.

is there a way in the SDK to implement these re-try mechanisms? (like using exponential backoff scheme)

**Comment by vibhansa-msft** [comment]
SDK already has the retry policy in place for any retriable error. This being 503 will be retried by SDK internally. Even after retries if the request continues to fail, then failure will be reported back to user application. You can use the SDK request-response logging to see the retries being done and failing due to egress throttle here. As this is an egress throttle, you might want to check why application is generating so much of traffic before putting more load on the server.

**Comment by souravgupta-msft** [comment]
@vijayrajah, you can refer [this](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/policy/policy.go#L84-L129) for the default retry policy. If you want to have your own retry logic, you can override this in the [`ClientOptions`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/container/client.go#L44) while creating the client.

**Comment by souravgupta-msft** [comment]
Closing this. If you have other questions, please continue in this thread.
