### ISSUE TITLE
Cosmos DB Account deletion future fails to wait

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#2213]
Hello,

So without changing anything, deletions of cosmos DBs in the terraform provider started to prematurely return around July 4th. This may have been triggered when we updated to v18.0.0 of Azure/azure-sdk-for-go / v10.12.0 of Azure/go-autorest.

[provider issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1525)
[and pr that works around it](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1533)

The code 
```go
    err = future.WaitForCompletionRef(ctx, client.Client)
	if err != nil {
		if response.WasNotFound(future.Response()) {
			return nil
		}
		return fmt.Errorf("Error issuing AzureRM delete request for CosmosDB Account '%s': %+v", name, err)
    }
```

Now returns true for `response.WasNotFound(future.Response())` even when the account is still exists and is deleting. to get around this we had now just poll ourselves.

**Comment by vladbarosan** [comment]
Hi @katbyte just tried this against our latest release and couldn't repro the issue. Also I took a look and it doesnt seem to be any change for this API in the new go-autorest version.

Also not sure how it gets inside the if statement you have there Is your context expiring (note that deleting the account can take some minutes ) or what is the error ?

**Comment by vladbarosan** [comment]
@katbyte we are closing this as no repro,,please let us know if it reemerges or/and if you have any further details.

**Comment by tombuildsstuff** [comment]
hey @vladbarosan 

I've dug out the error message we saw from this:

> pollingTrackerBase#updatePollingState: the response from the async operation has an invalid status code: StatusCode=0

FWIW whilst this error message is being returned upon Resource Group deletion, we were only seeing this in our CosmosDB Account tests - which makes us believe it's an issue with the CosmosDB Accounts?

Thanks
