### ISSUE TITLE
[KeyVault]Get Secret Versions function is missing in sdk.

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#22136]
### Bug Report

- import path of package in question
- github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault
- SDK version master

- What happened? GetSecretVersion is not defined in secretsClient. https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault#SecretsClient
- What did you expect or want to happen?  Get Secret Versions should be supported. https://github.com/Azure/azure-sdk-for-go/issues/15570 GetSecretWithVersion should also be supported.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2023-07-01/secrets.json#L174-L204

**Comment by jhendrixMSFT** [comment]
I think you'll need to use the data-plane SDK for this?

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets

CC @gracewilcox

**Comment by gracewilcox** [comment]
Joel is right. The GetSecret method is in the azsecrets module. The method also allows you to specify the version of the secret.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets#Client.GetSecret

**Comment by MartinForReal** [comment]
Thanks for your insight!
