### ISSUE TITLE
[azblob] file upload validation

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#22141]
This is a re-open of #20092 

I see the changes have been merged.

Is there a doc / Code sample that can be used as reference ?

**Comment by souravgupta-msft** [comment]
@vijayrajah, thanks for reaching out. You can refer [this](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client_test.go#L4727) test as reference for validating the blob during upload. As mentioned in previous comment, if you use [blockblob.Upload](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L170), the blob is uploaded as a single chunk, and you can use either md5 or crc64 for validating the content during upload.
Whereas if you use [UploadBuffer](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L526), [UploadFile](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L541) or [UploadStream](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L561), the blob is uploaded in multiple chunks and you will not be able to validate the content during upload.

**Comment by souravgupta-msft** [comment]
Closing this. For other queries, please continue in this thread.
