### ISSUE TITLE
(&azcore.ResponseError{RawResponse: &http.Response{}}).Error() panics

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-sdk-for-go#22147]
### Bug Report

- import path of package in question: "github.com/Azure/azure-sdk-for-go/sdk/azcore"
- SDK version: v1.9.0
- output of `go version`: go version go1.21.4 linux/amd64

Similar issue to #21838.

The expression `(&azcore.ResponseError{RawResponse: &http.Response{}}).Error()` panics.  This is because `runtime.Payload(&http.Response{})` panics, because it calls the standard library function `io.ReadAll` on a nil `resp.Body` and `io.ReadAll` doesn't nil-check its Reader (https://github.com/golang/go/issues/64714).

For completeness, note that `runtime.Payload(nil)` also panics because it doesn't nil-check resp, but I think that code path is not reachable via `azcore.ResponseError`.  It'd be nice to fix for other callers of runtime.Payload() though.

This isn't something that we see is causing a production problem (although perhaps there is a minor robustness issue in the highly improbable production case that any of these fields is not set).

But, it's something that trips us up from time to time in a unit test context - when unit testing some other behavior, it's possible to inadvertently instantiate a ResponseError that will then cause a panic when Error() is called.

If only to simplify unit testing, it would be neat if `(*azcore.ResponseError) Error()` did not panic on `&azcore.ResponseError{RawResponse: &http.Response{}}`.

**Comment by jhendrixMSFT** [comment]
We can fix this, but note that per the [docs](https://pkg.go.dev/net/http#Response), the response body will never be `nil` (`http.NoBody` when there's no body).

**Comment by jhendrixMSFT** [comment]
Fix will be in `internal@v1.5.2` to be released in early Jan.

**Comment by jhendrixMSFT** [comment]
Release will go out week of 2/5
