### ISSUE TITLE
InvalidApiVersionParameter when trying to create VNet with an empty resource group name

### ISSUE THREAD

**Issue by kdomanski** [Azure/azure-sdk-for-go#2214]
I'm using `github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-04-01/network.VirtualNetworksClient#CreateOrUpdate` to create a virtual network. This works perfectly under normal circumstances, however at some point a bug in my code resulted in an empty `resourceGroupName` being passed to the call.

The call failed, of course, but instead of an error mentioning the missing parameter, I received the following misleading error:
```
Code="InvalidApiVersionParameter"
Message="The api-version '2018-04-01' is invalid. The supported versions are '2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

**Comment by vladbarosan** [comment]
This would fail client side if the network spec would refer https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L290

**Comment by vladbarosan** [comment]
Closing in favor of https://github.com/Azure/azure-rest-api-specs/issues/4073
