### ISSUE TITLE
 I want to get the enterprise application name.

### ISSUE THREAD

**Issue by djshf55** [Azure/azure-sdk-for-go#22172]
hello
I want to import the list of names of "enterprise applications" in "microsoft Entra ID" into azure-sdk-for-go. Does such sdk exist?
I've been looking for such an SDK, but I couldn't find it, so I'm contacting you.

**Comment by Alancere** [comment]
azure-sdk-for-go doesn't seem to have an SDK for microsoft Entra ID to operate enterprise applications.
