### ISSUE TITLE
AzKeys - Get Key - Any way to filter the keys using the tags?

### ISSUE THREAD

**Issue by Roopan92** [Azure/azure-sdk-for-go#22175]
### Bug Report

- [Azkyes - GetKey] - (https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys#Client.GetKey)
- SDK version Latest

- What happened? - I need to filter the keys by using the existing Tags. Is there any way to achieve without fetching all the keys list and then iterate to filter?
- What did you expect or want to happen? - need to fetch specific key by passing some filter as tags

**Comment by gracewilcox** [comment]
Hi @Roopan92. The `GetKey` method does not have the option to filter by tags. However, you can specify the specific name and version of the key.

**Comment by Roopan92** [comment]
Thanks @gracewilcox - As workaround we are listing, iterating and finding the key with the specific tags.

**Comment by gracewilcox** [comment]
For more information on the capabilities of the Azure SDK for Go, I recommend looking at the REST API documentation. Our SDK directly builds on top of the REST API, so if the API doesn't have a capability, the SDK won't have it.

REST API links:
[Keys](https://learn.microsoft.com/rest/api/keyvault/keys/operation-groups?view=rest-keyvault-keys-7.4)
[Certificates](https://learn.microsoft.com/rest/api/keyvault/certificates/operation-groups?view=rest-keyvault-certificates-7.4)
[Secrets](https://learn.microsoft.com/rest/api/keyvault/secrets/operation-groups?view=rest-keyvault-secrets-7.4)

**Comment by Roopan92** [comment]
Got it @gracewilcox. Thanks for your support.
