### ISSUE TITLE
Listing all Recovery vaults replication protected items

### ISSUE THREAD

**Issue by MaayanLaav** [Azure/azure-sdk-for-go#22182]
I am looking for a way to list all replication protected items inside a recovery vault and I didn't find any appropriate method to do so using the SDK.

I noticed that there is a way to list all backup protected items using the SDK, as described here:
https://learn.microsoft.com/en-us/rest/api/backup/backup-protected-items/list?view=rest-backup-2023-02-01&tabs=HTTP

However, I couldn't find a corresponding method for listing replication protected items.

Thanks, Maayan Laav

**Comment by jhendrixMSFT** [comment]
I think this is what you're looking for.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/recoveryservices/armrecoveryservicesbackup/v3#BackupProtectedItemsClient

**Comment by MaayanLaav** [comment]
Hey @jhendrixMSFT.
When using this client, I only receive backup-protected items, and not the replicated protected items. Is there a specific client intended for replicated items?

**Comment by jhendrixMSFT** [comment]
Got it, I previously misunderstood the question.

Is it this one? https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/recoveryservices/armrecoveryservicessiterecovery/v2#ReplicationProtectedItemsClient.NewListPager
