### ISSUE TITLE
azopenai for audio not support m4a

### ISSUE THREAD

**Issue by hungpham1309** [Azure/azure-sdk-for-go#22195]
### Bug Report

- What happened?
the current lib only support mp3 file, not m4a
this is the code
	args := newTranscriptionOptions(azopenai.AudioTranscriptionFormatVerboseJSON, WHISPER, buf.Bytes())
	transcriptResp, err := u.OpenApiClient.GetAudioTranscription(context.Background(), args, nil)

- What did you expect or want to happen?
Should work normal for m4a

- How can we reproduce it?
/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai/custom_client_audio.go is hardcode .mp3

- Anything we should know about your environment.

**Comment by richardpark-msft** [comment]
Hey @hungpham1309, I repro'd this and I've got a PR out for it. Once that's in you'll be able to fix this by filling in the `Filename` field in the AudioTranscriptionOptions struct, which will be used to provide the filename.

**Comment by richardpark-msft** [comment]
@hungpham1309: this bug has been fixed in the latest release.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai@v0.4.1?tab=versions
