### ISSUE TITLE
[Questions] Get the blob container size and the blob counts for a specific container?

### ISSUE THREAD

**Issue by alifirat** [Azure/azure-sdk-for-go#22228]
Hi, 

For monitoring purposes, I would like to get the blob size and the blobs count for a specific container inside a storage account. 

What I was able to find is the storage account used capacity but no way to filter on a specific blob container so:
- is it possible ?
- if yes, can you please provide me some examples?

**Comment by vibhansa-msft** [comment]
Unfortunately, there is no direct API to do this. Storage backend does not expose this data directly, so user application has to compute this manually. What you can do as a workaround is to create a container client and then list blobs recursively and count the size and number of blobs in your application itself.
