### ISSUE TITLE
Problem while using `github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported` package.

### ISSUE THREAD

**Issue by Nivedita-coder** [Azure/azure-sdk-for-go#22276]
While importing `"github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported"`

Error:
`could not import github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported (invalid use of internal package "github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported")`

Using that package in below code:

```
type CustomTokenCredential struct {
	accessToken string
}

func (c *CustomTokenCredential) GetToken(ctx context.Context, options exported.TokenRequestOptions) (*exported.AccessToken, error) {
	return &azcore.AccessToken{
		Token:     c.accessToken,
		ExpiresOn: time.Now().Add(90 * 24 * time.Hour),
	}, nil
}

var _ azcore.TokenCredential = (*CustomTokenCredential)(nil)

**Comment by jhendrixMSFT** [comment]
You can find the exported definition of `TokenRequestOptions` in the `policy` package.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.9.1/policy#TokenRequestOptions

**Comment by jhendrixMSFT** [comment]
Can you please clarify how it's now working? I'm assuming you're getting some kind of "authentication failed" error back from the service?

**Comment by Nivedita-coder** [comment]
> Can you please clarify how it's now working? I'm assuming you're getting some kind of "authentication failed" error back from the service?

It's showing `2024/01/24 15:52:16 Error sending mail: error status code received from the API`

**Comment by jhendrixMSFT** [comment]
Hmm that error message isn't really actionable. I'm not familiar with the MSGraph SDK. Is there an option to get verbose logging so we can see the raw response from the service?

**Comment by Nivedita-coder** [comment]
Right now, I don't have an option to get verbose logging.
But, this is an issue with MSGraph SDK, it's basically comes after replacing cred with acessToken. I'll try to reach out MSGraph SDK community. Thanks @jhendrixMSFT for your help! 🙌

**Comment by jhendrixMSFT** [comment]
Sounds good. I'm going to close this then but please ping back if there are further problems on the Azure SDK side.
