### ISSUE TITLE
Azlog: Allow to only log Response Body on failures

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-go#22286]
### Feature Request

In Cosmos DB, customers send document information (might contain PII) in the body of the requests and the response on successful operations, contain the document information too.

For example, a call to `CreateItem` would, on a successful response, contain the created document.

When enabling logging through `AZURE_SDK_GO_LOGGING`, customers can log Request and Responses, and for the Responses, they include the Body.

From a logging perspective, the Body is useful on error scenarios (the service returned an error, which included details in the body), but for success responses, logging the body might contain PII information. 

The current PolicyOptions, allow to set to include the body:

https://github.com/Azure/azure-sdk-for-go/blob/6cdec79da53b0e16e3a47104da782a94ecf83244/sdk/azcore/runtime/policy_logging.go#L71-L75

but this affects all (success and failure) responses:

https://github.com/Azure/azure-sdk-for-go/blob/6cdec79da53b0e16e3a47104da782a94ecf83244/sdk/azcore/runtime/policy_logging.go#L141-L143

Would it be possible to define a behavior that only logs the body on failure responses (HTTP status code >= 400)?

Similar (but not equal) issue: https://github.com/Azure/azure-sdk-for-go/issues/18799

**Comment by jhendrixMSFT** [comment]
Our current thinking is that we'll add a new logging event `ResponseError` that writes the contents of `azcore.ResponseError.Error()` to the log whenever one is created.

**Comment by jhendrixMSFT** [comment]
The new functionality will go out in `azcore@v1.10.0` which should be first week of March. Note that in order to get the new functionality, you must update `newCosmosError()` to use `runtime.NewResponseErrorWithErrorCode()`.

**Comment by simorenoh** [comment]
We have updated the azcore version to 1.10.0 in this PR and merged it: https://github.com/Azure/azure-sdk-for-go/pull/22288/ - thanks @jhendrixMSFT!
