### ISSUE TITLE
[azopenai] Assistants API support

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#22293]
Tracking some of the work that needs to happen here:

- [x] Find an appropriate location for the new package.
- [x] List* style APIs should use pagers (looks like the generation isn't doing that)
  - [x] Assistants, AssistantsFiles, MessagesFiles, Messages, RunSteps, Runs
  - [x] The pagers are "directional" which might mean some logic needs to take into 
        account if they're going forwards or backwards. 
  - [x] Some response objects have a 'HasMore' field indicating more data.
- [x] ModelName should be renamed to DeploymentName
- [x] Objects in the swagger need to be named to avoid generating names like `Paths1Ih5M1JAssistantsGetResponses200ContentApplicationJSONSchema`
- [ ] Option models still have `Client` as their prefix. Ex: `ClientListMessagesOptions`
- [x] Failure when unmarshalling ThreadRun: 
      `unmarshalling type *assistants.ThreadRun: unmarshalling type *assistants.ThreadRun: struct field ExpiresAt: parsing time "1706143129" as "\"2006-01-02T15:04:05.999999999\"": cannot parse "1706143129" as "\""`
- [x] Readme
- [x] Samples
- [ ] MORE

**Comment by richardpark-msft** [comment]
Looks like there's a TypeSpec bug where the unixtime decorator isn't being propagated properly for all fields (it worked for `createdAt` but not for any of the other time fields (`expiresAt` is just one example):

```typespec
@doc("Data representing a single evaluation run of an assistant thread.")
@added(ServiceApiVersions.v2024_02_15_preview)
model ThreadRun {

 @projectedName("json", "created_at")
  @encode(DateTimeKnownEncoding.unixTimestamp, int32)
  @doc("The Unix timestamp, in seconds, representing when this object was created.")
  createdAt: utcDateTime;

   #suppress "@azure-tools/typespec-azure-core/no-nullable" "OpenAI uses explicit nullability, distinct from optionality"
  @projectedName("json", "expires_at")
  @encode(DateTimeKnownEncoding.unixTimestamp, int32)
  @doc("The Unix timestamp, in seconds, representing when this item expires.")
  expiresAt: utcDateTime | null;
```

```json
// (in definitions/ThreadRun)

      "created_at": {
          "type": "integer",
          "format": "unixtime",
          "description": "The Unix timestamp, in seconds, representing when this object was created.",
          "x-ms-client-name": "createdAt"
        },
        "expires_at": {
          "type": "string",
          "format": "date-time",
          "description": "The Unix timestamp, in seconds, representing when this item expires.",
          "x-nullable": true,
          "x-ms-client-name": "expiresAt"
        },
```

**Comment by richardpark-msft** [comment]
Can't seem to pass additional_instructions:

`// 	  "message": "1 validation error for Request\nbody -> additional_instructions\n  extra fields not permitted (type=value_error.extra)",`

**Comment by jeffreytwoods2** [comment]
Is support for streaming on the TODO list as well? Looking forward to seeing the Assistants API come to the azopenai package

**Comment by richardpark-msft** [comment]
> Is support for streaming on the TODO list as well? Looking forward to seeing the Assistants API come to the azopenai package

It's on the list for a future revision but I don't have a solid date for it yet.

**Comment by richardpark-msft** [comment]
@jeffreytwoods2, I know this is a LONG time after you asked, but streaming support is coming along with our support for Assistants V2.
