### ISSUE TITLE
Support v2 APIM Api

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/azure-sdk-for-go#22307]
### Service Package Request

Can we support the following api : - [https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2023-05-01-preview](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2023-05-01-preview)?

This would allow Terraform to be able to create v2 versions of APIM which can be provisioned in minutes rather than hours.

Many thanks

**Comment by lirenhe** [comment]
@Alancere, could you follow up with service team on this?

**Comment by Alancere** [comment]
Hi @ross-p-smith, A [release-request](https://github.com/Azure/sdk-release-request/projects/1974) has been requested and it is expected to be released in 2024-02-23.

**Comment by tombuildsstuff** [comment]
@ross-p-smith just a heads up that [Terraform no longer uses the Azure SDK for API Management](https://github.com/hashicorp/terraform-provider-azurerm/blob/2e5be258ee9482f54376463528228526a5919e1a/internal/services/apimanagement/client/client.go#L9-L54), but instead uses `hashicorp/go-azure-sdk`- as such [I’ve added support for this new API Version to that SDK](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/apimanagement/2023-05-01-preview) which will enable supporting this in Terraform.

**Comment by Alancere** [comment]
closed [release-request](https://github.com/Azure/sdk-release-request/projects/1974#card-91720856).
