### ISSUE TITLE
[azquery?] List Metrics at Subscription Scope

### ISSUE THREAD

**Issue by joshk0** [Azure/azure-sdk-for-go#22319]
### Service Package Request

Hello, I am looking to download compute usage metrics for Azure virtual machines within a subscription. While it's possible for me to get the resource ids of every single virtual machine and use the new [Metrics Batch](https://learn.microsoft.com/en-us/rest/api/monitor/metrics-batch/batch?view=rest-monitor-2023-10-01&tabs=HTTP) API available in v1.2.0-beta1 release of monitor/azquery, it seems much easier to use this endpoint: [List At Subscription Scope Post](https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list-at-subscription-scope-post?view=rest-monitor-2023-10-01&tabs=HTTP#post-request-for-subscription-level-metric-data) because I want to get the metrics of all instances at once without needing to identify them ahead of time.

However, I see that this is not currently a method that is plumbed into the Azure SDK for Go.

It also seems unusual that the Metrics Batch API was written to avoid throttling / performance issues with excessive requests on individual resource metric calls; but that it still requires resource IDs that would require their own API calls to enumerate.

Is the List At Subscription Scope metrics API still recommended for this kind of use case, and if so, could it be plumbed into the Go SDK?

Thank you!

**Comment by gracewilcox** [comment]
Hi @joshk0! Good news, the List At Subscription Scope Post endpoint already exists in the SDK in the `armmonitor` module. You can use [ListAtSubscriptionScopePost](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor#MetricsClient.ListAtSubscriptionScopePost) or [ListAtSubscriptionScope](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor#MetricsClient.ListAtSubscriptionScope).

For historic reasons, much of the current metrics functionality use an ARM (Azure Resource Manager) endpoint, so you can find the code in our ARM package. When the service releases this functionality in the data plane, we'll add it to our data plane module. The Metrics Batch API is currently the only metrics API in the data plane, but the service team is planning to add more.

If you're interested, here's further reading on [data plane vs control plane (ARM)](https://learn.microsoft.com/azure/azure-resource-manager/management/control-plane-and-data-plane) and more information on the [metrics rest api](https://learn.microsoft.com/azure/azure-monitor/essentials/data-platform-metrics#rest-api).
