### ISSUE TITLE
[azservicebus] Memory leak when receiving messages

### ISSUE THREAD

**Issue by gkampitakis** [Azure/azure-sdk-for-go#22318]
### Bug Report

- Package in question azure-sdk-for-go/sdk/messaging/azservicebus
- SDK version v1.6.0
- go version 1.21

### What happened?

This is a continuation of https://github.com/Azure/azure-sdk-for-go/issues/22157.  Trying to move out of https://github.com/Azure/azure-service-bus-go. Same usage of `azservicebus` but this time with higher load in production setup.  

We are noticing a memory leak as you can see on the screenshots below. 

<img width="885" alt="Screenshot 2024-01-31 at 22 52 51" src="https://github.com/Azure/azure-sdk-for-go/assets/50364739/5b591c46-d9b8-4df4-9ac7-fd9c11820d54">

Service running for a bit more than a day, we can see there is a an increase of memory happening periodically.  Looking at profiling data looks like the culprit is `(*Session).mux`
<img width="1736" alt="Screenshot 2024-01-31 at 22 47 07" src="https://github.com/Azure/azure-sdk-for-go/assets/50364739/f27d0c9f-04b8-4c15-b28c-503826f32dec">

Our Service Bus instance was affected with a huge increase of memory consumption jumping from a steady `17%`  up to `86%` and would kept raising if we hadn't rolled back. 

![Screenshot 2024-01-31 at 23 07 59](https://github.com/Azure/azure-sdk-for-go/assets/50364739/0eb7ff5c-14bf-41d3-9ba4-038b315cfc56)

even though there was a noticeable improvement in reducing number of active connections

![Screenshot 2024-01-31 at 23 20 58](https://github.com/Azure/azure-sdk-for-go/assets/50364739/019e3718-126f-470e-8991-de1a256f852a)

### What did you expect or want to happen?

I would expect the new SDK to have a different memory footprint (either higher or lower memory consumption) but after some time i was expecting the memory usage of the service to be stable as before and not increasing time over time.

Also it was not expected that the Service Bus instance will be affected.

### How can we reproduce it?

Not sure how easy it is to be reproduced as we needed production load to notice this. But outlining the setup here so it might make troubleshooting easier. 

1. We have a **fixed** number of producer goroutines that are receiving messages and a number of consumer goroutines that process messages and communicate via a go channel. At the start of the service we create a pool of receivers client.NewReceiverForQueue for receiving messages in parallel. 
2. A message will never be received and settled by the same receiver (this was causing the issues before)
3. Senders/receivers are long lived
4. Typical message size is ~3Kib and max message can be up to 256Kib.

- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Per discussion with @richardpark-msft we need to apply a similar, cross-receiver settlement fix, like we did in `go-amqp`.

**Comment by richardpark-msft** [comment]
@gkampitakis, got the PR out for this. Once it's merged will you be able to try it out before we tag it?

**Comment by gkampitakis** [comment]
@richardpark-msft I can probably try testing on staging but not on production 🫤

**Comment by gkampitakis** [comment]
@richardpark-msft Hey sorry for the delay. We have been running this [commit](https://github.com/Azure/azure-sdk-for-go/commit/7899ebe6149808221856e8f1b823bf1cf10bc08f) on staging for a week now and 
a. the memory footprint looks much better than before
b. we don't see any indications of memory leaks 🎉

**Comment by richardpark-msft** [comment]
Awesome! Thank you for testing that, and thanks for coming along on this journey :)

Closing this issue now, and the official package will ship next week, provided no other roadblocks pop up.
