### ISSUE TITLE
AADSTS7000218: The request body must contain the following parameter

### ISSUE THREAD

**Issue by bkievitk-gozamm** [Azure/azure-sdk-for-go#22386]
### Bug Report

Using basically the same code as https://github.com/Azure/azure-sdk-for-go/issues/21814, but in cred.GetToken, we are getting:

{
  "error": "invalid_client",
  "error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: <...> Correlation ID: <...> Timestamp: 2024-02-14 02:40:29Z",
  "error_codes": [
    7000218
  ],
  "timestamp": "2024-02-14 02:40:29Z",
  "trace_id": "<...>",
  "correlation_id": "<...>",
  "error_uri": "https://login.microsoftonline.com/error?code=7000218"
}

We have "Allow public client flows" enabled as a Web configured app.

**Comment by chlowell** [comment]
Does your application have `http://localhost` registered as a redirect URI for "mobile and desktop applications"? Entra considers applications having only a "web" redirect URI to be confidential clients i.e., it requires them to authenticate with a secret.
