### ISSUE TITLE
[Managed Clusters] Enabling azure monitor metrics - Managed Prometheus

### ISSUE THREAD

**Issue by grzesuav** [Azure/azure-sdk-for-go#22385]
### Feature Request

hi, need equivalent of https://github.com/Azure/azure-cli/pull/26201 / https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-enable?tabs=cli#aks-cluster

**Comment by lirenhe** [comment]
@grzesuav, our GO SDK is generated based on the API definition spec defined in https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks,  so could you be specific about what API you want to use and is currently missing in the SDK?  thanks

**Comment by grzesuav** [comment]
got it, I was confused with multiple API versions of library...
