### ISSUE TITLE
ManagedIdentityClient fails for either "failed to retreive secret key from the identity endpoint" or "expected a 401 response, received"

### ISSUE THREAD

**Issue by Shaked** [Azure/azure-sdk-for-go#22399]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
```
"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
```

- SDK version e.g. `master`, `latest`, `18.1.0`
```
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.5.1
github.com/microsoftgraph/msgraph-sdk-go v1.33.0
```
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `go list -m <module>`, for example `go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore`.
```
go list -m github.com/Azure/azure-sdk-for-go/sdk/azidentity
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.5.1
go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.9.2
go list -m github.com/microsoftgraph/msgraph-sdk-go
github.com/microsoftgraph/msgraph-sdk-go v1.33.0
```
- output of `go version`
```
go version
go version go1.21.6 darwin/arm64
```

- What happened?
I am trying to use ManagedIdentity with a custom endpoint, similar to this implementation: https://github.com/gsoft-inc/azure-cli-credentials-proxy. With the azure-sdk-for-python everything works as expected. However, with azure-sdk-for-go there are two issues:

1. The query params are added correctly only when I add the `?` sign to the end of the URL. This part seems to be related to this line: https://github.com/Azure/azure-sdk-for-go/blob/4a5bfaf4207656db342beeaccff953a335c4bcc6/sdk/azidentity/managed_identity_client.go#L373
2. Once added (i.e. `http://azcliproxy/token?`), then it fails with the assumption of a 401, which is in this line: https://github.com/Azure/azure-sdk-for-go/blob/4a5bfaf4207656db342beeaccff953a335c4bcc6/sdk/azidentity/managed_identity_client.go#L381-L384

- What did you expect or want to happen?
The same as with the azure-sdk-for-python - it should work with the generated token from the custom endpoint I have supplied.

- How can we reproduce it?
You can build the azcliproxy either from the .NET project or from this Go gist https://gist.github.com/Shaked/e16e36c93048423fc0e6d574c78aa6b2. Then run it on the same network with a project that uses the following lines:

```
cred, _ := azidentity.NewDefaultAzureCredential(nil)
scopes := []string{"https://graph.microsoft.com/.default"}
graphClient, err := msgraphsdk.NewGraphServiceClientWithCredentials(cred, scopes)
if err != nil {
  log.Fatalf("Failed to create graph client: %v", err)
}
me, err := graphClient.Me().Get(context.Background(), nil)
if err != nil {
  log.Fatalf("Failed to get me: %v", err)
}
log.Printf("Me: %#v", ,me.GetDisplayName())
```

Make sure to set the following environment variables:
```
        - name: IDENTITY_ENDPOINT
          value: "http://azcliproxy:8080/token"
        - name: IMDS_ENDPOINT
          value: "dummy_required_value"
```

- Anything we should know about your environment.

The exact same azcliproxy work with this python code: 

```
import loguru
from azure.identity import DefaultAzureCredential
import os
import asyncio

async def run_msgraph():
    from msgraph import GraphServiceClient

    credential = DefaultAzureCredential()
    scopes = ["https://graph.microsoft.com/.default"]
    client = GraphServiceClient(credentials=credential, scopes=scopes)
    me = await client.me.get()
    if me:
        print(me.display_name)
    else:
        print("No user found")

asyncio.run(run_msgraph())
```

This use case is important for bypassing UMI dependency while working on a local machine, where federated tokens are not available and ideally SP secrets are not something I'd like to use. 

In case this is not a bug I'd like to understand the differences between the python code and the Go code and if there's anything that can be done to overcome this issue. 

Thank you! 
```[tasklist]
### Tasks
```

**Comment by chlowell** [comment]
Thanks for opening this issue! Firstly, I have to underline that our managed identity client supports only Azure platforms. We don't support or test anything else. If you want to imitate an Azure platform's managed identity service, I suggest targeting a simpler one, like App Service (set `IDENTITY_ENDPOINT` and `IDENTITY_HEADER`; respond like [this](https://learn.microsoft.com/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#connect-to-azure-services-in-app-code)). Setting `IDENTITY_ENDPOINT` and `IMDS_ENDPOINT` configures our managed identity client for Azure Arc, which has a somewhat elaborate protocol that your endpoint evidently doesn't implement. Your Python code is fragile because it depends on the way `azure-identity` handles unexpected responses. That behavior is undefined, which is to say the current behavior is an implementation detail that could change at any time. So, I think the best way to move forward with this approach is to imitate a simpler service.

**Comment by Shaked** [comment]
@chlowell 

> I suggest targeting a simpler one, like App Service (set IDENTITY_ENDPOINT and IDENTITY_HEADER; respond like [this](https://learn.microsoft.com/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#connect-to-azure-services-in-app-code)).

It worked. Thanks for the tip!
