### ISSUE TITLE
armalertsmanagement does not seem to correctly generate the scope when updating an alert. 

### ISSUE THREAD

**Issue by ihulsbus** [Azure/azure-sdk-for-go#22393]
### Bug Report

- import path: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/alertsmanagement/armalertsmanagement`
Paired with `github.com/Azure/azure-sdk-for-go/sdk/azidentity` version `v1.5.1`
- SDK version: `0.9.0`
- output of `go version`: `go version go1.20.4 darwin/arm64`

please describe:

#### What happened?
  using the `ChangeState()` function in `*armalertsmanagement.AlertsClient`, I get a scope error: 
```
2024/02/15 15:42:40 failed to finish the request: POST https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.AlertsManagement/alerts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/changestate
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client 'XXXXX' with object id 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' does not have authorization to perform action 'Microsoft.AlertsManagement/alerts/changestate/action' over scope '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
```
I verified my access, which is valid, I verified what the correct URL should be and tested it via `az rest --method post --url ...`, which worked under the same credentials the script uses

#### What did you expect or want to happen?
I expect my alert to be updated. 

#### How can we reproduce it?
I generate the client with the following code:
```go
cred, err := azidentity.NewDefaultAzureCredential(nil)
if err != nil {
	log.Fatalf("failed to obtain a credential: %v", err)
}

monitorClientFactory, err = armalertsmanagement.NewClientFactory(subscriptionID, cred, nil)
if err != nil {
	log.Fatalf("failed to create client: %v", err)
}

alertsClient = monitorClientFactory.NewAlertsClient()
```

I then retrieve my alerts with the pager function. These alerts are put in an array and after parsing the alert ID through a regex to get the accurate alert UUID, I pass it to the `ChangeState()` function:

the original `*alert.ID` looks like `/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/myAwesomeResourceGroup/providers/microsoft.operationalinsights/workspaces/MyAwesomeLaw/providers/Microsoft.AlertsManagement/alerts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`

```go
r, err := regexp.Compile(`([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$`)
if err != nil {
	log.Fatal(err)
}

result := r.FindStringSubmatch(*alert.ID)

_, err = alertsClient.ChangeState(defaultContext, result[1], armalertsmanagement.AlertStateAcknowledged, &armalertsmanagement.AlertsClientChangeStateOptions{Comment: &closureComment})
if err != nil {
	log.Fatalf("failed to finish the request: %v", err)
}
```
the url the package generates `https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.AlertsManagement/alerts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/changestate`

seems to be missing the scope of the alert (`resourceGroups/myAwesomeResourceGroup`). the URL that it should be is: 
`https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/myAwesomeResourceGroup/providers/Microsoft.AlertsManagement/alerts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/changestate`

Additionally the request parameters are not in the error output, but I expect them to be `?api-version=2019-03-01&newState=Closed`

#### Anything we should know about your environment.
nothing specific. The environment is pretty standard

**Comment by Alancere** [comment]
Hi @ihulsbus, according to the code you provided above, my execution result is successful. See that your error is AuthorizationFailed, please check your permissions.

**Comment by ihulsbus** [comment]
Hi @Alancere, 

I verified my permissions extensively, and they are correct.

In the mean time I created the following workaround:

1.  Manually construct the URL as specified (`https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/myAwesomeResourceGroup/providers/Microsoft.AlertsManagement/alerts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/changestate`
2. Create the params like `?api-version=2019-03-01&newState=Closed`
3. Get a bearer token with `az account get-access-token` (using the same account as used for `alertsClient.ChangeState`)
4. In a Golang http POST request, set the URL to the one generated in step 1; set the query params to the one from step 2; Set the `Authorization` header to the bearer token from step 3 (utilising the same account as before); 
5. Execute the http request. 
6. The alert gets closed correctly and without any errors. 

In my opinion, the SDK is generating an incorrect URL, and thus the error returned is not so much an matter of incorrect permissions but more an incorrect scope, which I cannot correct with the SDK myself.

**Comment by ihulsbus** [comment]
The relevant snippets of the workaround:

models:
```golang
type HttpVar struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AlertUpdateBody struct {
	Comments string `json:"comments"`
}
```

update alert:

`alertID` is the uuid of the alert, like: `273a69c2-2fe1-4504-8ce8-bd1026565f38`
```golang
func UpdateAlert(ctx context.Context, alertID string) error {
	var params []m.HttpVar
	var body m.AlertUpdateBody
        var closureComment string = "comment"

	url := fmt.Sprintf("https://management.azure.com/subscriptions/%s/resourceGroups/%s/providers/Microsoft.AlertsManagement/alerts/%s/changestate", c.Config.SubscriptionID, c.Config.ResourceGroup, alertID)
	params = append(params, m.HttpVar{Key: "api-version", Value: "2019-03-01"}, m.HttpVar{Key: "newState", Value: "Closed"})
	body.Comments = closureComment

	marshaledBody, err := json.Marshal(body)
	if err != nil {
		return err
	}

	response, err := httpClient.Request(ctx, "POST", url, marshaledBody, params)
	if err != nil {
		return fmt.Errorf("%s | Body: %s", err.Error(), string(response))
	}

	return nil
}
```

http request:
```golang
func (h HttpClient) Request(ctx context.Context, method, url string, body []byte, queryParams []m.HttpVar) ([]byte, error) {
	var err error

	// Create a Bearer string by appending string access token
	var bearer = "Bearer " + h.token.AccessToken

	req, err := http.NewRequestWithContext(ctx, method, url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}

	// add authorization header to the req
	req.Header.Add("Authorization", bearer)
	if body != nil {
		req.Header.Add("Content-Type", "application/json")
	}

	// appending url params to potential existing url params
	q := req.URL.Query()
	for _, param := range queryParams {
		q.Add(param.Key, param.Value)
	}

	// assign encoded param string to http request
	req.URL.RawQuery = q.Encode()

	// execute
	resp, err := h.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("errored when sending request to the server: %s", err.Error())
	}

	defer resp.Body.Close()
	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode != 200 {
		err = fmt.Errorf("non 200 response code received: %d", resp.StatusCode)
		return responseBody, err
	}

	return responseBody, nil
	}
}
```

**Comment by Alancere** [comment]
Hi @ihulsbus, The new version has been released, please use it https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/alertsmanagement/armalertsmanagement@v0.10.0
