### ISSUE TITLE
Subnet struct does not support the routeTable property

### ISSUE THREAD

**Issue by vgarg** [Azure/azure-sdk-for-go#224]
As per the documentation at [1] the the properties JSON for a subnet looks as follows:

```
{ 
   "properties":{ 
      "addressPrefix":"10.1.0.0/24",
      "networkSecurityGroup":{ 
         "id":"/subscriptions/{guid}/../microsoft.network/networkSecurityGroups/myNSG1"
      },
    "routeTable": { "id": "/subscriptions/{guid}/../Microsoft.Network/routeTables/myRT1" }
   }
}
```

We know this approach works as we have used the same approach within an ARM template.

Now we have a need to create another subnet at runtime and I am using the GO SDK to do so. However there does not appear to be a way to specify the routeTable for the subnet using the SDK.

On our end, we need the fix urgently. For now I guess I could just hack the SDK and add the missing property in the Subnet struct. Does that sound like something that would work?

[1] https://msdn.microsoft.com/en-us/library/azure/mt163621.aspx

**Comment by brendandixon** [comment]
@vgarg I took a quick look at the Swagger that backs the SDK (see https://github.com/Azure/azure-rest-api-specs). I could find no references to "routeTable" in the arm-network Swagger. Could you, please, look it over as well? You are likely more familiar with the Network ARM templates than I am.

@devigned @vgarg's issue appears to be a Swagger problem.

**Comment by vgarg** [comment]
@brendandixon Indeed, I see no mention of routeTable in the swagger JSON. Looks like the swagger JSON and the actual REST API documentation are out of sync. Or perhaps the routeTable property is new, and did not cause a version change?

**Comment by brendandixon** [comment]
@vgarg Unclear. Let me follow-up with @devigned as he oversees the Swagger.

**Comment by brendandixon** [comment]
@vgarg It looks like the ARM Network Swagger was recently updated. It now includes the routeTable. See https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-05-01-preview/swagger/network.json#L6039. We're working an update to the ARM packages that will include these changes.

**Comment by devigned** [comment]
@brendandixon we need to automate the codegen pipeline... We should talk about this soon.

**Comment by brendandixon** [comment]
@devigned Sounds good to me. :)

**Comment by ahmetalpbalkan** [comment]
Apparently fixed, closing.
