### ISSUE TITLE
[sdk/ai/azopenai] Could this sdk be used to invoke gptv/openai_gpt-4-vision

### ISSUE THREAD

**Issue by dugenkui03** [Azure/azure-sdk-for-go#22436]
### Service Package Request
sdk/ai/azopenai

**Comment by richardpark-msft** [comment]
@dugenkui03, yes, although I just realize I didn't have a formal example for it. I'll add one.

You can see how I do it in our own testing: [gpt vision test](https://github.com/Azure/azure-sdk-for-go/blob/4b5cb6878d9cfafce643d9a8dee82bc7d8a0a029/sdk/ai/azopenai/client_chat_completions_test.go#L236)

I'll be adding a standalone example as well - it'll look quite similar to the test I linked above.

**Comment by dugenkui03** [comment]
@richardpark-msft could this sdk be used to invoke gemini-x-version

**Comment by richardpark-msft** [comment]
> @richardpark-msft could this sdk be used to invoke gemini-x-version

gemini-x-version, as in Google's Gemini product? No, this library is only for Azure OpenAI or OpenAI.

**Comment by dugenkui03** [comment]
@richardpark-msft Could we use this sdk invoke gpt-4o, and does gpt-4o support video as input?
