### ISSUE TITLE
Feature Request: minimumTlsVersion attribute is missing from Eventhub Namespace Ressponse

### ISSUE THREAD

**Issue by lchavan-uptycs** [Azure/azure-sdk-for-go#22449]
### Feature Request

- Azure Go SDK used: [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/eventhub/armeventhub) v1.2.0
- In eventhub namespace we can't get data minimum tls version of namespace which is given by the rest api call https://learn.microsoft.com/en-us/rest/api/eventhub/namespaces/list?view=rest-eventhub-2024-01-01&tabs=HTTP in `minimumTlsVersion`

**Comment by lirenhe** [comment]
Looks we need to update the package for armeventhub.  @Alancere, could you take a look at this ask? Thanks

**Comment by Alancere** [comment]
Hi @lchavan-uptycs, you cloud try [armeventhub@v1.3.0-beta.1](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub@v1.3.0-beta.1)

**Comment by lchavan-uptycs** [comment]
Thanks @Alancere @lirenhe , I can see the data what I wanted 
one more question, any fix dates this change will be available in general release?
