### ISSUE TITLE
Service Request: Upgrade Azure OpenAI SDK to 2024-02-15-preview

### ISSUE THREAD

**Issue by davidgwking** [Azure/azure-sdk-for-go#22444]
### Service Package Request

[A new version of the Azure OpenAI spec is now available: `2024-02-15-preview`](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference)

As of the latest release, the Go SDK is currently setting the `api-version` header to `2023-12-01-preview`: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/ai/azopenai/client.go#L247

Is there a timeline on a release upgrading to `2024-02-15-preview`?

Thank you!

**Comment by richardpark-msft** [comment]
(@davidgwking, will be releasing this tomorrow)

**Comment by davidgwking** [comment]
> (@davidgwking, will be releasing this tomorrow)

Thank you!

**Comment by richardpark-msft** [comment]
@davidgwking , as promised: https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fai%2Fazopenai%2Fv0.5.0

Thank you for your interest. Let us know what you think - we're in the feedback portion of this development so if something's too difficult, or not explained well we'd like to address it.

**Comment by davidgwking** [comment]
Hi @richardpark-msft, I've tried to implement logprobs and top_logprobs today and ran into some issues:> i've opened the following issue: https://github.com/Azure/azure-sdk-for-go/issues/22538
