### ISSUE TITLE
Why should this be hardcoded to Https?

### ISSUE THREAD

**Issue by yanivsag** [Azure/azure-sdk-for-go#22448]
https://github.com/Azure/azure-sdk-for-go/blob/bac2559f8c41323bc04ad06c356de22f50d97df5/sdk/storage/azblob/container/client.go#L351

I suggest basing this on the URL, since it makes the method unusable for users of the azurite storage emulator.

**Comment by vibhansa-msft** [comment]
Hi @yanivsag 
GetSasURL is just a helper method to generate SAS from SharedKey or UserDelegationKey. We have used 'https' as default, but that does not restrict you in anyway. You can create your own BlobSignatureValue in context of your application and generate a SAS which allows both http and https.

**Comment by vibhansa-msft** [comment]
0.3.0 was not a GA release. For the security reasons HTTP was not allowed in certain auth flows. By default its HTTPs now and for HTTP you need to create SAS by calling respective SDK apis and not through GetSASToken(). For now you can use this as a workaround, let me discuss this with team and see what shall be the correct way to handle this.

**Comment by yanivsag** [comment]
got it, thanks!

**Comment by vibhansa-msft** [comment]
This has been fixed as part of #22704
