### ISSUE TITLE
Doc comment checker doesn't check fields within structs

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#22446]
While we validate doc comments for exported funcs/methods/types, it appears that we don't check for doc comments within structs.

**Comment by jhendrixMSFT** [comment]
Yep, we look at types but not their contents.

https://github.com/Azure/azure-sdk-for-go/blob/main/eng/tools/doccheck/main.go#L63-L67

**Comment by chlowell** [comment]
I seem to remember this coming up before and us deciding to do nothing because generated types use docstrings from the API spec, which often don't follow the Go convention and generally don't admit a simple heuristic for making them so.

**Comment by jhendrixMSFT** [comment]
I think you're right. And in some cases, there are no doc strings in the OpenAPI at all, so generating a `// Foo field...` doc comment to satisfy the tool is pretty useless.
