### ISSUE TITLE
How to upload the BYOK through azure go lang sdk to the azure keyvault keys

### ISSUE THREAD

**Issue by Roopan92** [Azure/azure-sdk-for-go#22452]
### Bug Report

- import path of package - https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys#Client.ImportKey
- SDK version - latest

Ref Link: https://learn.microsoft.com/en-us/azure/key-vault/keys/byok-specification

- What happened? 
 - Need to import the key into the keyvault - BYOK

- What did you expect or want to happen?
    - Need to import the BYOK through azure sdk to the keyvault.
- How can we reproduce it?
- Please provide the sample go code for import BYOK into the keyvault
- Anything we should know about your environment. - NA

**Comment by Roopan92** [comment]
@heaths - Do you have any idea on this issue?
Because you already gave the solution for this issue https://github.com/Azure/azure-sdk-for-go/issues/22173. Try to seek help from you.

Please provide the sample code for Import BYOK into azure key vault.

Sample BYOK Request from: https://learn.microsoft.com/en-us/azure/key-vault/keys/byok-specification
{
  "schema_version": "1.0.0",
  "header":
  {
    "kid": "<key identifier of the KEK>",
    "alg": "dir",
    "enc": "CKM_RSA_AES_KEY_WRAP"
  },
  "ciphertext":"BASE64URL(<ciphertext contents>)",
  "generator": "BYOK tool name and version; source HSM name and firmware version"
}

**Comment by Roopan92** [comment]
@gracewilcox - Any update here?

**Comment by gracewilcox** [comment]
Hi @Roopan92! I can't at this moment create a sample for you, but I created the above issue to track when I do add more samples to the Key Vault SDK's.

**Comment by Roopan92** [comment]
Thanks @gracewilcox - Can you please help which function we can use from the below package
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys.

Just want to know how to import BYOK into azure key vault using azure go lang SDK

**Comment by gracewilcox** [comment]
Hi @Roopan92! I would use the [ImportKey](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys#Client.ImportKey) method to import your key into Azure.

**Comment by Roopan92** [comment]
Thanks for your response @gracewilcox.

But how will you use this **ImportKey** function for the BYOK scenraio as we have byok file and we need to the send the API request like below,

Sample BYOK Request from: https://learn.microsoft.com/en-us/azure/key-vault/keys/byok-specification
{
"schema_version": "1.0.0",
"header":
{
"kid": "",
"alg": "dir",
"enc": "CKM_RSA_AES_KEY_WRAP"
},
"ciphertext":"BASE64URL()",
"generator": "BYOK tool name and version; source HSM name and firmware version"
}

Please help.

**Comment by Roopan92** [comment]
unresolve
