### ISSUE TITLE
[azblob] Error occurs when trying to connect to storage emulator  

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-sdk-for-go#22457]
### Bug Report  
   
When trying to connect to the storage emulator (Azurite) using `azblob@v1.3.0`, the following error occurs:  
   
```  
panic: authenticated requests are not permitted for non TLS protected (https) endpoints  
```  
   
Downgrading to `azblob@v1.2.0` solves the issue.  
   
#### Environment  
   
- azblob@v1.3.0  
- go version go1.21.6 linux/amd64  
- Ubuntu 23.10 on WSL2  
   
### Reproduction Steps  
   
1. Start Azurite.  
2. Execute the following code:  
```go  
package main  
   
import (  
	"context"  
	"fmt"  
  
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"  
	"github.com/google/uuid"  
)  
   
func main() {  
	conn := "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"  
	client, err := azblob.NewClientFromConnectionString(conn, nil)  
	if err != nil {  
		panic(err)  
	}  
  
	name := uuid.New().String()  
	_, err = client.CreateContainer(context.Background(), name, nil)  
	if err != nil {  
		panic(err)  
	}  
	fmt.Printf("Container: %v\n", name)  
}  
```  
   
#### Actual Behavior  
   
```sh  
$ go run main.go  
panic: authenticated requests are not permitted for non TLS protected (https) endpoints  
   
goroutine 1 [running]:  
main.main()  
        /home/moris/w/sandbox/go-blob/main.go:21 +0x166  
exit status 2  
```  
   
#### Expected Behavior (v1.2.0)  
   
```sh  
$ go get -u github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v1.2.0   
go: downgraded github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.3.0 => v1.2.0  
$ go mod tidy  
$ go run main.go  
Container: e5667565-2772-4eb0-ba62-48dc40959387  
```

**Comment by vibhansa-msft** [comment]
Access over HTTP using Go-SDK was disabled in our last release for the security reasons. However, we have observed lot of customers using Azurite or Azure Stack are having trouble due to this restriction. We are working on reverting this back, next release will have the fix.

**Comment by wh7f** [comment]
The following files also have this problem. I am prompted with this error when using azopenai. Can it be fixed?

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/runtime/policy_bearer_token.go#L83

**Comment by souravgupta-msft** [comment]
OAuth does not allow HTTP endpoints.
@jhendrixMSFT to comment on this.

**Comment by wh7f** [comment]
https://github.com/Azure/azure-sdk-for-go/blob/sdk/ai/azopenai/v0.4.1/sdk/ai/azopenai/custom_client.go#L91

Not related to OAuth, I need to connect to other endpoints that are compatible with the OpenAI protocol.

**Comment by jhendrixMSFT** [comment]
@wh7f can you please provide more info about how this is manifesting for OpenAI? We can't send bearer tokens over unencrypted HTTP.

**Comment by m-moris** [comment]
@vibhansa-msft 
@souravgupta-msft 

Thank you for the quick fix on my issue. Greatly appreciated!

**Comment by wh7f** [comment]
> @wh7f can you please provide more info about how this is manifesting for OpenAI? We can't send bearer tokens or authentication keys over unencrypted HTTP. Also, it would be best to open a new issue since your scenario has nothing to do with blob storage.

OK, we can discuss it in a new issue. Thank you for your support
https://github.com/Azure/azure-sdk-for-go/issues/22482
