### ISSUE TITLE
[Notification Hubs] Unable to remove APNS|GCM|... credentials from a Notification Hub

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#2246]
### Bug Report

* import path of package in question: `github.com/Azure/azure-sdk-for-go/services/notificationhubs/mgmt/2017-04-01/notificationhubs`
* SDK version: `v18.0.0`
* output of `go version`: `go version go1.10.2 darwin/amd64`

---

:wave: me again!

So I've been looking into Notification Hubs and have found a bug in the SDK;

Looking to the Portal, it's possible to add APNS/GCM Credentials for a given Notification Hub using the following (redacted) request:

```
{
	"location": "westeurope",
	"properties": {
		"apnsCredential": {
			"properties": {
				"endpoint": "https://api.development.push.apple.com:443/3/device",
				"keyId": "XXXXXXXXXXXX",
				"appName": "uk.co.toms.app",
				"appId": "XXXXXXXXXXXX",
				"token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..."
			}
		}
	}
}
```

which works as expected using the `CreateOrUpdate` method of the `notificationhubs` SDK (2017-04-01/v18.0.0). It's also possible to successfully retrieve these credentials using the `` method/endpoint which is :thumbs_up: so far.

The issue comes with removing these credentials - in the Portal this is done by submitting the following request:

```
PATCH /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tom-nhtest/providers/Microsoft.NotificationHubs/namespaces/tom-nhnamespace/notificationHubs/tom-nothub HTTP/1.1
...

{"properties":{"ApnsCredential":null}}
```

which returns a 200 OK which is :thumbs_up:. However I'm unable to replicate this request using the Go SDK as the top level properties have the attribute `omitempty`; setting this to an empty object gets translated as (in this case, trying to remove the APNS Credentials):

```
{
	"location": "westeurope",
	"properties": {
		"apnsCredential": {}
	}
}
```

which returns an error from the API:

```
HTTP/1.1 400 Bad Request
...

{"error":{"message":"Request payload is not in the expected format.","code":"BadRequest"}}
```

As such I don't think there's a way of removing credentials from a Notification Hub using the SDK today. For the moment I can workaround this by making a DELETE call and force-recreating the Notification Hub, which whilst isn't great will allow us to ship this at the moment (albeit with a disclaimer).

Relevant PR from our side: https://github.com/terraform-providers/terraform-provider-azurerm/pull/1589

Thanks!

**Comment by marstr** [comment]
I think this one is going to need some investigation. I'm going to leave it for team triage tomorrow.

**Comment by joshgav** [comment]
Hi @tombuildsstuff, have you considered the `notificationhubs#Client.Patch` method? ([godoc](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/notificationhubs/mgmt/2017-04-01/notificationhubs#Client.Patch)).

Won't solve your problem but perhaps we can handle PATCH differently than PUT.
