### ISSUE TITLE
[Key Vault] Add more samples

### ISSUE THREAD

**Issue by gracewilcox** [Azure/azure-sdk-for-go#22475]
Increase the number of samples in the Key Vault modules, including a sample for `ImportKey` as requested in [this issue](https://github.com/Azure/azure-sdk-for-go/issues/22452) and `ImportCertificate` as requested in [this issue](https://github.com/Azure/azure-sdk-for-go/issues/21873).

An increase in samples will hopefully fill the documentation gap, especially helping new users unfamiliar with the Go SDK.

**Comment by Roopan92** [comment]
@gracewilcox  - Any update here?. We need an sample for Importkey of BYOK

**Comment by Roopan92** [comment]
@gracewilcox - Any update?

**Comment by Roopan92** [comment]
@gracewilcox - Any examples added for Import BYOK In azure?. I don't see any still
