### ISSUE TITLE
Add support for the `dimensions` param of new embedding models

### ISSUE THREAD

**Issue by mtaran** [Azure/azure-sdk-for-go#22483]
### Feature Request

The `dimensions` param was added to the embeddings request JSON with the new embeddings models, reference [here](https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-dimensions).

**Comment by richardpark-msft** [comment]
@mtaran : You can pull this and give it a shot now if you'd like - mostly we're just discussing how one of the features will ultimately get exposed, but that doesn't affect Dimensions.

`go get github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai@HEAD`

**Comment by richardpark-msft** [comment]
This package has been officially released:
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai@v0.5.1
