### ISSUE TITLE
[azeventhubs] Processor.NextPartitionClient can hang for ever in some cases, ignoring context cancellation 

### ISSUE THREAD

**Issue by PaulBernier** [Azure/azure-sdk-for-go#22539]
### Bug Report

- https://github.com/Azure/azure-sdk-for-go/blob/6e61c5ea1c948e54cbf69f8e0876468df7843065/sdk/messaging/azeventhubs/processor.go#L196
- SDK version: github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs v1.0.3
- go version go1.22.0 darwin/amd64

- `Processor.NextPartitionClient` blocks for ever, even though the context has been cancelled
- Upon context cancellation that method should return (nil)
- Looking at the code it's clear the method is stuck on `<-p.runCalled`, and this can happen if the call to Run of the processor immediately errored and never unblocked this line. I believe the fix should be as easy as replacing that line by 
```
	select {
	case <-p.runCalled:
	case <-ctx.Done():
		return nil
	}
```

**Comment by richardpark-msft** [comment]
@PaulBernier, thank you for that. PR is out, fix should be in main soon.
