### ISSUE TITLE
Support diacritical marks for resource group names 

### ISSUE THREAD

**Issue by dany74q** [Azure/azure-sdk-for-go#22537]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/profiles/latest/web/mgmt/web`
- SDK version: `v68.0.0`
  - Specify the exact commit: `2187aca40bbf6931ffac666977e5d29128d82585`
- output of `go version`: `go version go1.21.3 darwin/arm64`

- What happened?
```
web.AppsClient#Get: Invalid input: autorest/validation: 
validation failed: 
parameter=resourceGroupName constraint=Pattern value="testötest" details: 
value doesn't match pattern ^[-\w\._\(\)]+[^\.]$
```
- What did you expect or want to happen?
Support diactrical marks, as it's supported, at least in the swedish regions (a-la `swedencentral`)
- How can we reproduce it?
Create a resource group with diactrical marks from the portal, try to retrieve it with the sdk.
- Anything we should know about your environment.
N/A

**Comment by jhendrixMSFT** [comment]
The package being imported is from our legacy SDK which is no longer supported.

I believe that [`armappservice`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appservice/armappservice/v2) is the latest SDK that has replaced `/web/mgmt/web`.

**Comment by dany74q** [comment]
Hey @jhendrixMSFT !

This is an SDK-wide issue actually, the webapps usage is just an example.
It stems from the swagger validation, for instance here:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2023-01-01/WebApps.json#L30858

**Comment by jhendrixMSFT** [comment]
We've removed client-side validation in our latest SDKs, sorry I didn't clarify that earlier.

You can globally disable client-side validation in the legacy SDKs by setting [`validation.Disabled`](https://github.com/Azure/go-autorest/blob/main/autorest/validation/validation.go#L28) to `false` (I forgot about this).

Please keep in mind that `v68.0.0` is the legacy SDK which is out of support.
