### ISSUE TITLE
Notification Hub Namespaces Delete Future is broken

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#2254]
### Bug Report

* import path of package in question: `github.com/Azure/azure-sdk-for-go/services/notificationhubs/mgmt/2017-04-01/notificationhubs`
* SDK version: `v18.0.0`
* output of `go version`: `go version go1.10.2 darwin/amd64`

---

👋 

Whilst working on support for Notification Hubs within Terraform - I've noticed the delete future seems to hang for the lifetime of the context passed in, and eventually fails with the following error; but only ~50% of the time.

```
* azurerm_notification_hub_namespace.test: Error waiting for the deletion of Notification Hub Namespace "acctestnhn-7935624892261362245" (Resource Group "acctestrg-7935624892261362245"): Future#WaitForCompletion: context has been cancelled: StatusCode=202 -- Original Error: context deadline exceeded
```

~In the interim I've worked around this by polling for the Notification Hub Namespace ourselves until we get a 404~ (update: maybe not) - but I can't tell if the Swagger or the API needs to be fixed here?

Relevant link from our side: 
https://github.com/terraform-providers/terraform-provider-azurerm/pull/1589

Thanks!

**Comment by marstr** [comment]
👋 

Doesn't seem like a Swagger error to me! That means @jhendrixMSFT and I are on the case.

Looking at your PR, could you tell me a little bit more about how the `ARMClient.StopContext` is initialized and what its lifetime looks like? I want to rule out the error your seeing coming from a timeout or cancellation from your Context. :)

**Comment by marstr** [comment]
If you're pretty confident that `ARMClient.StopContext` isn't calling for cancellation, then it could be coming from this line: [Azure/go-autorest/autorest/azure/azync.go#L168](https://github.com/Azure/go-autorest/blob/e6d2a85bbb5cd2a3162e4942594e1e520e442b0b/autorest/azure/async.go#L168)

Mind checking your client's `PollingDuration` to ensure that it doesn't just need to be increased?

From there we can look into whether or not Future's implementation is being wonky for you.

**Comment by tombuildsstuff** [comment]
👋🏻 hey @marstr

Sorry I’d meant to provide more info for how we ended up working around this; after some experimentation I noticed if we repeatedly call the Delete method (and then poll ourselves to verify this has gone) this seems to eventually take place, which makes me wonder if this is a service issue instead? Unfortunately I’ve not had time to investigate either way

Hope that helps!

**Comment by marstr** [comment]
Oh oh, that's very interesting. So I've actually got it backwards (sorry about that), you're not having trouble with premature polling cancellation from the Future. You're having trouble with either:
a) The Future not recognizing that the namespace has indeed been deleted.
b) The namespace just legitimately isn't getting deleted by the service.

**Comment by jhendrixMSFT** [comment]
Network trace seems to indicate that the portal and SDK do the same thing.  When experimenting with my test program I've noticed that sometimes if click on the namespace in the portal while the future is polling the delete succeeds.

**Comment by jhendrixMSFT** [comment]
@matt-gibbs to summarize, if I create a namespace then delete it the delete never happens and the SDK times out waiting for the async operation to complete.  When the ```DELETE``` is requested the API returns a 202 (accepted) and polling the URL in the ```Location``` header returns status ```InProgress``` so it seems like the delete starts but never finishes?

**Comment by matt-gibbs** [comment]
investigating

**Comment by jhendrixMSFT** [comment]
@matt-gibbs any update?

**Comment by RickWinter** [comment]
@matt-gibbs Can this issue be resolved?

**Comment by marstr** [comment]
Howdy - lot's has changed in the last few years. I actually ended up moving to work for @matt-gibbs on Notification Hubs, before he moved to GitHub.

Without getting into detail - enough has changed in our RP that there's no reason to believe that a bug this old is still applicable. We should close it as stale.

**Comment by RickWinter** [comment]
Marking this old issue as addressed.  If the bug still reproduces on current SDK and service please open a new issue
