### ISSUE TITLE
`compute/armcompute` - support for more OSDisk properties

### ISSUE THREAD

**Issue by bubbletroubles** [Azure/azure-sdk-for-go#22565]
### Feature Request

The [OSDisk type](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5#OSDisk) doesn't support some properties available in the [Microsoft.Compute disks](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/disks) API, namely:
- diskAccessId
- networkAccessPolicy
- publicNetworkAccess

These are needed to configure VM Operating System disks properties to determine if they are publicly accessible or not.

**Comment by Alancere** [comment]
Hi @bubbletroubles, please use [Disk](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5#Disk) try again.
