### ISSUE TITLE
Resource provider not registered automatically for Microsoft.Security/pricings

### ISSUE THREAD

**Issue by felipebbc** [Azure/azure-sdk-for-go#22563]
When enabling Defender for Cloud plans through the Terraform AzApi provider, the automatic registration of the Microsoft.Security provider does not occur.

Sample code:
```
resource "azapi_update_resource" "subscription_dfc_plans" {
  parent_id = "/subscriptions/${local.subscription_id}"
  type      = "Microsoft.Security/pricings@2024-01-01"
  name      = "CloudPosture"
  body = jsonencode({
    properties = {
      pricingTier = "Standard"
    }
  })
}
```

Error message:
```
 Error: checking for presence of existing Resource: (ResourceId "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Security/pricings/CloudPosture" / Api Version "2024-01-01"): GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Security/pricings/CloudPosture
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE: Subscription Not Registered
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "Subscription Not Registered",
│     "message": "Please register to Microsoft.Security in order to view your security status"
│   }
│ }
│ --------------------------------------------------------------------------------
```
This issue was partially addressed with #20848 by adding the non-standard error code `Subscription Not Registered`.

However, the sdk also checks if the response has a 409 error code:
https://github.com/Azure/azure-sdk-for-go/blob/6387cfc7d4421e4df032c64fc7fab4cf36f7c622/sdk/azcore/arm/runtime/policy_register_rp.go#L90-L92

Since the error message from the Microsoft.Security/pricings@2024-01-01 returns a **404 error code**, the provider registration doesn't move forward.

Also, the provider registration requires that the error message contain the provider name in the `error.details.target` field

https://github.com/Azure/azure-sdk-for-go/blob/6387cfc7d4421e4df032c64fc7fab4cf36f7c622/sdk/azcore/arm/runtime/policy_register_rp.go#L202-L207

The error message from the Microsoft.Security/pricings@2024-01-01 does not contain the `error.details.target` field, it only contains `error.code` and `error.message`:

I tested out a solution adding the 404 code on line 91 and adding a regex to extract the resource provider name from the error.message. It works but I understand this is not a good solution. 

Looking for a solution to this issue that will allow automatic resource provider registration in this scenario.

**Comment by jhendrixMSFT** [comment]
This new feature will be available in `azcore@v1.11.0` scheduled for release the first week of April.
