### ISSUE TITLE
armnginx.BeginCreate fails with MissingApiVersionParameter error

### ISSUE THREAD

**Issue by ornj** [Azure/azure-sdk-for-go#22571]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/nginx/armnginx"`
- SDK version: `v1.0.1`
- output of `go version`: `go version go1.21.4 darwin/arm64`
- What happened: Duplicated [example code](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/nginx/armnginx#example-CertificatesClient.BeginCreate) for creating a certificate. Request failed due to missing the required `api-version` query parameter (err error below)
- What did you expect or want to happen:
  - Expected this request to fail since the example body is empty
  - Expected the SDK to correctly set the API Version query parameter
- How can we reproduce it?
  - Copy the example code and modify the strings it to use an existing subscription and NGINXaaS deployment 
  - I expect other clients/methods to fail in a similar way

**Example Error**

```
PUT https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Nginx.NginxPlus/nginxDeployments/xxxxxx/certificates/xxxxxx
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: MissingApiVersionParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "MissingApiVersionParameter",
    "message": "The api-version query parameter (?api-version=) is required for all requests."
  }
}
--------------------------------------------------------------------------------
```

**Comment by Alancere** [comment]
Hi @ornj, please use the latest [armnginx@v3.0.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/nginx/armnginx/v3@v3.0.0) try again
