### ISSUE TITLE
Allow armcostmanagement's queries to group by RegionId

### ISSUE THREAD

**Issue by tbtonner** [Azure/azure-sdk-for-go#22599]
### Feature Request

armcostmanagement's `QueryDefinition` should allow a `QueryGrouping` in `QueryColumnTypeDimension` to `RegionId`. 

Currently, only `ResourceLocation` works as a way to group by regions, but the values returned are in a completely unuseful format that later needs to be converted, seemingly manually.

Please see the related [learn question](https://learn.microsoft.com/en-us/answers/questions/1609547/converting-cost-api-resourcelocations-to-azure-loc) posed about this, where the suggested solution was to use [Get-FinOpsRegion](https://microsoft.github.io/finops-toolkit/powershell/data/Get-FinOpsRegion). This, however, seems  like something that should be done directly in the SDK or API directly as the `FinOps tool-kit` is hard-coding these mappings.

Example in sdk to what should be possible post feature:

```go
query := armcostmanagement.QueryDefinition{
	Type: to.Ptr(armcostmanagement.ExportTypeActualCost),
	Dataset: &armcostmanagement.QueryDataset{
		Aggregation: map[string]*armcostmanagement.QueryAggregation{
			"UsageQuantity": {
				Function: to.Ptr(armcostmanagement.FunctionTypeSum),
				Name:     to.Ptr("UsageQuantity"),
			},
		},
		Grouping: []*armcostmanagement.QueryGrouping{
			{
				Name: to.Ptr("RegionId"),
				Type: to.Ptr(armcostmanagement.QueryColumnTypeDimension),
			},
		},
		Timeframe: to.Ptr(armcostmanagement.TimeframeTypeCustom),
		TimePeriod: &armcostmanagement.QueryTimePeriod{
			From: to.Ptr(start),
			To:   to.Ptr(end),
		},
	},
}
```

**Comment by Alancere** [comment]
Hi @tbtonner Sorry, the go sdk is automatically generated by [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-11-01/costmanagement.json#L2511) and does not support customization. Depending on the FinOpsRegion you provide, you can refer to the following implementation https://github.com/microsoft/finops-toolkit/blob/a4dc87e7c5ba1a1c3ee3ffa3f8b06cb971bdba15/src/powershell/Public/Get-FinOpsRegion.ps1#L36

**Comment by flanakin** [comment]
@tbtonner The Cost Management team is planning to align the location values to what Azure Resource Manager shows but there's no ETA for that today. In the meantime, I would recommend using [FOCUS exports](https://learn.microsoft.com/azure/cost-management-billing/costs/tutorial-improved-exports) to get the standard Azure region names baked into the dataset. [Learn more about FOCUS](https://aka.ms/ftk/focus). The region IDs are coming in a future update, but they're simply the lowercase version without a space. You could also use [FinOps hubs](https://aka.ms/ftk/hubs) that sits on top of FOCUS exports and provides some additional capabilities.
