### ISSUE TITLE
containerservice.ManagedClusterPropertiesAutoScalerProfile (AKS) does not accept some duration values which are otherwise valid

### ISSUE THREAD

**Issue by krishna-birla** [Azure/azure-sdk-for-go#22592]
Original Issue: https://github.com/Azure/azure-sdk-for-go/issues/14311

# Bug Report

- `github.com/Azure/azure-sdk-for-go/profiles/latest/containerservice/mgmt/containerservice`
- azure-sdk-for-go@v46.1.0+incompatible
  - Specify the exact commit if possible; one way to get this is the REVISION column output by `dep status "github.com/Azure/azure-sdk-for-go"`.
- `go version`
  - go1.15.6 darwin/amd64
- What is the error? -> `containerservice.ManagedClusterPropertiesAutoScalerProfile.ScanInterval = &("1m")` throws an error: "_containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Invalid value specified for the cluster-autoscaler parameter 'scan-interval'. Please refer to https://aka.ms/cluster-autoscaler for more details._"
- What is expected? -> Cluster creation should pass.
- How to reproduce? -> Create AKS cluster with `containerservice.ManagedClusterPropertiesAutoScalerProfile.ScanInterval = &("1m")`

## Extra observations
`containerservice.ManagedClusterPropertiesAutoScalerProfile.ScanInterval = &("1m")` fails but `containerservice.ManagedClusterPropertiesAutoScalerProfile.ScanInterval = &("60s")` passes.

Similar issues exist with other fields, for example:

`containerservice.ManagedClusterPropertiesAutoScalerProfile.ScaleDownDelayAfterFailure = &("3m30s")` throws an error: "_containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Invalid value specified for the cluster-autoscaler parameter 'scale-down-delay-after-failure'. Please refer to https://aka.ms/cluster-autoscaler for more details._" even though it is a valid value.

Similarly:

`containerservice.ManagedClusterPropertiesAutoScalerProfile.ScaleDownDelayAfterFailure = &("180s")` throws an error: "_containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Invalid value specified for the cluster-autoscaler parameter 'scale-down-delay-after-failure'. Please refer to https://aka.ms/cluster-autoscaler for more details._"

but

`containerservice.ManagedClusterPropertiesAutoScalerProfile.ScaleDownDelayAfterFailure = &("3m")` passes.

**Comment by krishna-birla** [comment]
The original issue: https://github.com/Azure/azure-sdk-for-go/issues/14311 got closed by the bot. Was this issue resolved?

**Comment by jhendrixMSFT** [comment]
The package cited is from the legacy SDK which is no longer supported. This might be fixed in the latest version of the [`armcontainerservice`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4) SDK. Can you please try it?
