### ISSUE TITLE
Load Balanced Endpoint

### ISSUE THREAD

**Issue by Trane9991** [Azure/azure-sdk-for-go#226]
Hello,
is it possible to create Load Balanced Endpoint or add endpoint to existing LoadBalancer Set? 
Can't find functionality for this.

**Comment by ahmetalpbalkan** [comment]
@Trane9991 are you looking for Azure Service Management APIs or Azure Resource Manager APIs in this context? If you have a documentation to REST API documents on MSDN we can easily check.

**Comment by Trane9991** [comment]
@ahmetalpbalkan 
I think this is Azure Service Management APIs. I believe this functionality are described by link below:
https://msdn.microsoft.com/en-us/library/azure/dn469417.aspx

**Comment by ahmetalpbalkan** [comment]
@Trane9991 You're right. I don't think we implemented this endpoint. You can see implemented endpoints of this class here: https://github.com/Azure/azure-sdk-for-go/blob/master/management/virtualmachine/client.go I think it should be easy to add taking the existing ones as implementation reference if you would like to take a look at it.

**Comment by ahmetalpbalkan** [comment]
We no longer maintain ASM code. Closing.
