### ISSUE TITLE
PublicNetworkAccess property for SQL Server is turning out to be null

### ISSUE THREAD

**Issue by djuneja-uptycs** [Azure/azure-sdk-for-go#22606]
### Bug Report
  * Our use case requires us to fetch the information of our SQL servers created in our Azure cloud environment.
  * When trying to fetch all the SQL Servers, there is one in particular that returns a `null` value for the property `PublicNetworkAccess`.
  * We are heavily relying on this property as a lot of our assessments and compliance checks are failing due to this.

### Sample Code:
```
func (c *clientImpl) ListServersByResourceGroup(ctx context.Context, resourceGroup string) ([]*armsql.Server, error) {
	ctx = azure.CtxWithOperationName(ctx, "ListServersByResourceGroup")
	servers := make([]*armsql.Server, 0)
	pager := c.serverClient.NewListByResourceGroupPager(resourceGroup,
		&armsql.ServersClientListByResourceGroupOptions{Expand: nil})
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		if err != nil {
			return nil, err
		}
		servers = append(servers, nextResult.Value...)
	}
	return servers, nil
}
```
### Libraries versions used:
  * `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql` -> `v1.0.0` (tried with latest `v1.2.0` as well)

### Expectation:
The expectation was to get all the SQL servers for a given resource group with correct `PublicNetworkAccess` property.

### Output:
The return type is a pointer to string, that means it can be empty. Surprisingly, other SQL servers are all having correct information, there is only 1 SQL server which is having this issue. There is nothing special about the resource, we created it just like any other SQL server resource.

**Comment by Alancere** [comment]
Hi @djuneja-uptycs, could you use https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql/v2@v2.0.0-beta.4 try again.

**Comment by djuneja-uptycs** [comment]
@Alancere thanks for the recommendation. I tried with the version you mentioned and yes it seems to return the correct data to me. However it does look like the beta version, of the `armsql/v2`. When is it production ready build scheduled for? I would like to use that in my code base instead, as I have had issues with the beta versions of the SDKs.

**Comment by djuneja-uptycs** [comment]
@Alancere do we have any update on the production ready releases? Also wanted to know how wide the impact is. So far we only saw one of our instances have this issue but is this issue predictable or random?

**Comment by Alancere** [comment]
The go sdk depends on [spec swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/readme.md#tag-package-composite-v5) to generate a beta or stable based on whether the input-file has a preview.
