### ISSUE TITLE
request for (*blockblob.Client).StageBlock streamable option like (*azblob.Client).UploadStream

### ISSUE THREAD

**Issue by benmcclelland** [Azure/azure-sdk-for-go#22630]
### Feature Request

Currently [(*blockblob.Client).StageBlock()](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L206) requires passing in body of type io.ReadSeekCloser. This is requiring caching the full stage block body in memory before submitting the upload.

Ideally I would like the equivalent of [(*azblob.Client).UploadStream()](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/client.go#L144) that only needs an io.Reader and can be streamed to the upload without requiring a seekable reader.

The use case for this is to use the StageBlock for the multipart part upload in our s3 to azure gateway [versitygw](https://github.com/versity/versitygw), specifically here:
https://github.com/versity/versitygw/blob/bcd667c4d4213440243985a143199a198207dfd2/backend/azure/azure.go#L586C18-L586C28

**Comment by tanyasethi-msft** [comment]
Hi @benmcclelland , Thanks for this request. 

`StageBlock()` internally calls [PutBlock rest API](https://learn.microsoft.com/en-us/rest/api/storageservices/put-block?tabs=microsoft-entra-id), for which data needs to be stored beforehand, and cannot be fetched from the stream. 

Instead, if you want to do a multi part upload, you can use `UploadStream`
`UploadStream` internally does a parallely `stageBlock` and then does a put block list.
