### ISSUE TITLE
[azopenai] Expose "model" field from openai chat completion object on GetChatCompletionsResponse 

### ISSUE THREAD

**Issue by chriscasola** [Azure/azure-sdk-for-go#22664]
### Feature Request

Exposing the model field would be helpful so that we can log the model that was ultimately used by the client. It is not always possible to tell from the request because there is an internal "LLM gateway" at our company that redirects requests to certain models within Azure's open AI deployments.

I can contribute this, but I'm not sure where/how to change the generated API model objects.

**Comment by richardpark-msft** [comment]
Let me see what's missing here - the code is purely autogenerated but I note that OpenAI has the model field but our typespec (which specifies the service) doesn't.

**Comment by richardpark-msft** [comment]
@chriscasola - thanks for reporting this, and your patience. Just released the latest package, which now has this field:

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai@v0.5.1
