### ISSUE TITLE
LimitObject not exposed in armquota package

### ISSUE THREAD

**Issue by circa10a** [Azure/azure-sdk-for-go#22708]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/quota/armquota@v1.0.0`
- SDK version: `latest`
  - `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/quota/armquota v1.0.0`
- output of `go version`: `go version go1.22.1 darwin/amd64`

- What happened?
  - When trying to access a quota limit value, I expected the limit value to be an exported field, but is not. The example in this codebase portray this data to be exported as `&armquota.LimitObject` but it is actually exported as `LimitJSONObjectClassification` which does not give the quota limit data expected.
  - [Example in codebase](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/quota/armquota/client_example_test.go#L39-L56)
- What did you expect or want to happen?
  - I expected to be able to get quota limit values with the SDK
- How can we reproduce it?
  - code below
- Anything we should know about your environment.
  - Nothing special

## Code to reproduce

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/quota/armquota"
)

var (
	family       = "standardLASv3Family"
	location     = "eastus"
	subscription = "some-id"
)

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armquota.NewClientFactory(cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}

	scope := fmt.Sprintf("subscriptions/%s/providers/Microsoft.Compute/locations/%s", subscription, location)

	res, err := clientFactory.NewClient().Get(ctx, family, scope, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}

	// Expected to get have LimitObject (and mainly LimitObject.Value) but get LimitJSONObjectClassification
	limit := res.CurrentQuotaLimitBase.Properties.Limit

	fmt.Println(limit)
}
```

**Comment by Alancere** [comment]
Hi @circa10a, I will replace it with my subscriptionId according to the code you provided above. The following is the expected result of execution

![image](https://github.com/Azure/azure-sdk-for-go/assets/46921893/47573c92-30d6-426d-ab29-b99c4e72d132)

**Comment by circa10a** [comment]
![Screenshot 2024-04-07 at 7 37 32 AM](https://github.com/Azure/azure-sdk-for-go/assets/21261388/8043f9df-2145-46a3-bcdf-711476e5e202)

I'm unable to see how the `Value` field is accessible from the `LimitJSONObjectClassification` interface. Can you provide any sample code to access that field?

```
❯ go run main.go
# command-line-arguments
./main.go:105:20: limit.Value undefined (type armquota.LimitJSONObjectClassification has no field or method Value)
```

**Comment by Alancere** [comment]
> ![Screenshot 2024-04-07 at 7 37 32 AM](https://private-user-images.githubusercontent.com/21261388/320289343-8043f9df-2145-46a3-bcdf-711476e5e202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDI5NDgsIm5iZiI6MTcxMjU0MjY0OCwicGF0aCI6Ii8yMTI2MTM4OC8zMjAyODkzNDMtODA0M2Y5ZGYtMjE0NS00NmEzLWJjZGYtNzExNDc2ZTVlMjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAyMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZDA1MGU2ZTZmNmJkMGE0ZTQ2ODM3N2ZjZTZhODlkYTU2YWMxZGJiZWE3NWNmYmZjM2NhNzEyZmI3YmQ0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EyEOmDHQkXoAkJF7ouoENOA1wIv3RSgNqQZ_90yEnNg)
> 
> I'm unable to see how the `Value` field is accessible from the `LimitJSONObjectClassification` interface. Can you provide any sample code to access that field?
> 
> ```
> ❯ go run main.go
> # command-line-arguments
> ./main.go:105:20: limit.Value undefined (type armquota.LimitJSONObjectClassification has no field or method Value)
> ```

Maybe your Azure Subscription doesn't have the associated resources, so there's no return value?

**Comment by circa10a** [comment]
I don't think that's the case here. Are you able to provide some sample working code that fetches the limit value?

**Comment by Alancere** [comment]
> I don't think that's the case here. Are you able to provide some sample working code that fetches the limit value?

I'm using the code you provided above.
LimitJSONObjectClassification type is an interface, you need to convert it to get to the Value
![image](https://github.com/Azure/azure-sdk-for-go/assets/46921893/381f3982-998c-4e17-9f74-1a46bc5504e3)

**Comment by circa10a** [comment]
Example code if anyone else finds this issue:

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/quota/armquota"
)

var (
	family       = "standardLASv3Family"
	location     = "eastus"
	subscription = "some-id"
)

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armquota.NewClientFactory(cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}

	scope := fmt.Sprintf("subscriptions/%s/providers/Microsoft.Compute/locations/%s", subscription, location)

	res, err := clientFactory.NewClient().Get(ctx, family, scope, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}

	limit := *res.CurrentQuotaLimitBase.Properties.Limit.(*armquota.LimitObject).Value

	fmt.Println(limit)
}
```
