### ISSUE TITLE
When create instance of client for blockblob, can the url does not spcify the contatiner & Blob

### ISSUE THREAD

**Issue by jurejoy** [Azure/azure-sdk-for-go#22742]
### Feature Request
When create instance of client for blockblob(blockblob.NewClientWithSharedKeyCredential), can the url does not spcify the contatiner & Blob. When it try to upload files, the parameters of container and blob can be spicifed later. It's easy to just create an instance of client, and let user to desice what to do next.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/examples_test.go
![image](https://github.com/Azure/azure-sdk-for-go/assets/16313985/62bd6ee8-7ed7-4bc6-a5f9-bc8861c58331)

**Comment by souravgupta-msft** [comment]
@jurejoy, thanks for reaching out. We cannot have container or blob names in the Upload methods in blockblob clients. This is by design.
You instead try the [UploadFile](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/client.go#L138) method in azblob client.

**Comment by jurejoy** [comment]
Thanks for the update, then what's the difference between client.uploadfile and blockblobclient.uploadfile? Does client.upload do the same way like uploading parallelly each blocks and commit later on?

**Comment by souravgupta-msft** [comment]
There is no difference between azblob client.UploadFile and blockblobclient.UploadFile. The azblob client.UploadFile internally creates the blockblob client and calls its UploadFile method. It does the upload in parallel.
