### ISSUE TITLE
Storage blob missing AccesseTierType "cold"

### ISSUE THREAD

**Issue by jurejoy** [Azure/azure-sdk-for-go#22756]

**Comment by souravgupta-msft** [comment]
Access tier type cold is already supported, https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blob/constants.go#L60
Please update to use the latest release [azblob v1.3.2](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv1.3.2).
