### ISSUE TITLE
[azopenaiassistants] Function Tools Support

### ISSUE THREAD

**Issue by pkrauss-prot** [Azure/azure-sdk-for-go#22767]
### Bug Report

- import path of package in question.
"github.com/Azure/azure-sdk-for-go/sdk/ai/azopenaiassistants"
- SDK version 
"v0.1.0"
- output of `go version` 
"go version go1.21.8 linux/amd64"

- What happened? 
azopenaiassistants is obviously very new and being at a release v0 has no guarantees. However I noticed that the current implementation does not use the existing interface for `RequiredActionClassification`. Current implementation is using a concrete implementation that only returns `Type` and not the `SubmitToolOutputsAction` with both `Type` and `SubmitToolOutputs`.
- What did you expect or want to happen? 
I was hoping that the interface was used so that i could return the `SubmitToolOutputs` to process function calls.
- How can we reproduce it? 
```go
// this should be waiting in status "requires_action"
lastGetRunResp, err = client.GetRun(context.Background(), "a thread id", "a run id", nil)
// is concrete so you cannot swap it out for `SubmitToolOutputsAction`
lastGetRunResp.RequiredAction
```
- Anything we should know about your environment.
Nope pretty standard.

**Comment by richardpark-msft** [comment]
Looking at this. It looks like something didn't _quite_ generate properly there since, as you noted, the RequiredAction model did get generated.
