### ISSUE TITLE
Blockblob.StageBlock support stream

### ISSUE THREAD

**Issue by jurejoy** [Azure/azure-sdk-for-go#22777]
### Feature Request
When using Blockblob.StageBlock, could you clarify if below features is supported or any workaround?

1. Is it possible for blockblob.stageblock support stream like uploadstream?
2. In some scenario, copy files from some resource like s3 or some other objective storage, the response body has no io.ReadSeekerCloser, can you just provide io.Reader instead?
![image](https://github.com/Azure/azure-sdk-for-go/assets/16313985/ba084fdc-26dc-48b0-bd81-4ac5b81f9a13)

**Comment by tanyasethi-msft** [comment]
Hi @jurejoy, Thanks for your comment. 

1. You can use [UploadStream](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/client.go#L144) instead.
`UploadStream` internally does a parallel stageBlock and then does a put block list.

2. `StageBlock()` internally calls [PutBlock rest API](https://learn.microsoft.com/en-us/rest/api/storageservices/put-block?tabs=microsoft-entra-id), for which data needs to be stored beforehand, and cannot be fetched from the stream.
So, if your response body has no `io.ReadSeekerCloser`, we recommend using `UploadStream`, which will use `io.Reader`.

**Comment by jurejoy** [comment]
Thanks for the explanation. Further question is, if I want to control the files blocks along with the blockID in "UploadStream", is it possible to do the same way like in StageBlock().

**Comment by jurejoy** [comment]
When use [UploadStream](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/chunkwriting.go#L39), what is the max value for concurrency & block size, looks like the default is 1 and 1MB

**Comment by tanyasethi-msft** [comment]
There is no max value for concurrency and block size for `UploadStream`
