### ISSUE TITLE
Cloudinit support

### ISSUE THREAD

**Issue by fatih** [Azure/azure-sdk-for-go#228]
Hi,

Azure has support for CloudInit: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-how-to-inject-custom-data/ and according to the documents it's currently only available via the CLI. 

I couldn't find in the documents how to pass a custom script via a `user_data`, because I've assumed may be the SDK for go might have a support. Is there any support for CloudInit in the current Go SDK? If not is there any plans to add it?

Thanks

**Comment by ahmetalpbalkan** [comment]
Hi @fatih, the cloud-init data is passed to the Azure Compute REST APIs through the `osProfile.customData` field in the VM configuration struct.

* REST API reference for this call is here: https://msdn.microsoft.com/en-us/library/azure/mt163591.aspx
* In the Go SDK this corresponds to the following struct/field: https://github.com/Azure/azure-sdk-for-go/blob/3dcabb61c225af4013db7af20d4fe430fd09e311/arm/compute/models.go#L393
* You can use it with `arm/compute/VirtualMachinesClient#CreateOrUpdate(...)` method. https://github.com/Azure/azure-sdk-for-go/blob/1a29bf058b780f6a05fc67111efae7930c4a1621/arm/compute/virtualmachines.go#L117

Does this help?

**Comment by fatih** [comment]
Hi @ahmetalpbalkan, I've looked for the keyword `cloudinit` or `user_data` (as this is the norm for others, such as AWS or DO). Never thought it was something called `CustomData`. The rest should be fairly easy on our side. Thanks for your detailed response, much appreciated.
