### ISSUE TITLE
[arm/network] Deletion of specific load balancing rules

### ISSUE THREAD

**Issue by pravinpushkar** [Azure/azure-sdk-for-go#22813]
### Feature Request

Problem - 

I have few load balancing rules already defined in the azure load balancer under `load balancing rules`.

Now I want to replace these rules with another set of rules via `go sdk`.
The method `BeginCreateOrUpdate` on the `*armnetwork.LoadBalancersClient` does not replace the rules, it fails with reference error with frontend IP Configuration.

RESPONSE 400: 400 Bad Request\nERROR CODE: InvalidResourceReference

Another option was to get the exact rule and delete it just as we have delete buttons on each rules. But SDK does not provide anu delete method on `*armnetwork.LoadBalancerLoadBalancingRulesClient`

How should we proceed in this case ?

**Comment by Alancere** [comment]
Hi @pravinpushkar, it seems that only through the [LoadBalancersClient.BeginCreateOrUpdate](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v5#LoadBalancersClient.BeginCreateOrUpdate) to create or update FrontendIPConfigurations, Please set all `FrontendIPConfigurations` including those that are not updated and those that are to be updated
![image](https://github.com/Azure/azure-sdk-for-go/assets/46921893/1d8afd56-daff-4897-a1ce-e9b549080fe2)

**Comment by pravinpushkar** [comment]
Thanks
