### ISSUE TITLE
`azcosmos` forces min go version to 1.22.0 instead of 1.18

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-sdk-for-go#22827]
### Bug Report

`azcosmos` v1.0.0 forces the min Go version to 1.22.0 instead of the standard 1.18 used by the rest of the Azure SDK for Go.

This was caused in https://github.com/Azure/azure-sdk-for-go/pull/22394 by @simorenoh.

Please release a patch version v1.0.1 with the `go.mod` set to 1.18 again.

**Comment by berndverst** [comment]
cc @jhendrixMSFT @ealsur

**Comment by berndverst** [comment]
For my own needs Go 1.21 would be ok too -- I'm trying to Backport this to Dapr 1.12 (which we still have to support), but Dapr 1.12 has to stick with Go 1.21

**Comment by jhendrixMSFT** [comment]
I thought the POR was to set this to `1.21` due to requiring a new feature in Go 1.21. We must support N and N-1 versions at minimum.

**Comment by berndverst** [comment]
```
go mod tidy -go=1.21
go: github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos@v1.0.0 requires go@1.22.0, but 1.21 is requested
```

**Comment by ealsur** [comment]
Release on https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fdata%2Fazcosmos%2Fv1.0.1
