### ISSUE TITLE
Uploadstream support user generated checksum

### ISSUE THREAD

**Issue by jurejoy** [Azure/azure-sdk-for-go#22841]
### Feature Request
When checking the [models.go](https://github.com/Azure/azure-sdk-for-go/blob/113f7caa0b982024bb369c220fe57f85d44564b3/sdk/storage/azblob/blockblob/models.go#L326C15-L326C16), looks like option support TransferValidationType, but when use this, it report the error like below.
![d2943479e63d16d042bce7a4578ab9e](https://github.com/Azure/azure-sdk-for-go/assets/16313985/be43b7d1-2441-475d-8222-0d6ee1ab4c29)

Do see some explanation this this  [PR](https://github.com/Azure/azure-sdk-for-go/pull/21033), but need confirm if currently this feature still does not support for "Uploadstream"

**Comment by tanyasethi-msft** [comment]
@jurejoy - As the error suggests, this is not possible. Since UploadStream is a multi part upload, cheksum validation is not supported. Suggest you to use `Upload` instead.
