### ISSUE TITLE
"Signature did not match" with UserDelegationCredential

### ISSUE THREAD

**Issue by levinandrew** [Azure/azure-sdk-for-go#22846]
### Bug Report

- import path of package in question
  - `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas`
  - `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.3.2`
- output of `go version`
  - `go version go1.22.0 darwin/arm64` 

- What happened?
I fail to do a SAS upload to a signed URL
```
PUT https://studcteststorage.blob.core.windows.net/studctest/sas_upload_test.txt/ -------------------------------------------------------------------------------- 
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. 
ERROR CODE: AuthenticationFailed --------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?>
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:b304660c-d01e-003d-0cce-9f3224000000 Time:2024-05-06T16:00:21.9356046Z
</Message>
<AuthenticationErrorDetail>
Signature did not match. String to sign used was w 2024-05-07T16:00:21Z /blob/studcteststorage/studctest/sas_upload_test.txt/ <RG-B Managed Identity Object ID> <Tenant ID> 2024-05-04T16:00:21Z 2024-05-07T16:00:21Z b 2023-11-03 https 2023-11-03 b 
</AuthenticationErrorDetail>
</Error> 
```
Note: I redacted `<RG-B Managed Identity Object ID>` and `<Tenant ID>` above.

- What did you expect or want to happen?
I expected the SAS PUT request to work without issue. I am able to successfully write blobs to the container by calling methods like https://github.com/Azure/azure-sdk-for-go/blob/e13ea6e16ac0a4e20f167ce788d6fc5b5f017bcc/sdk/storage/azblob/client.go#L144 
after creating a client like this
```
url := fmt.Sprintf("https://%s.blob.core.windows.net", accountName)
opts := &azidentity.WorkloadIdentityCredentialOptions{
	TenantID: *tenantID,
	ClientID: *rgBmanagedIdentityClientID,
}
cred, err := azidentity.NewWorkloadIdentityCredential(opts)
client, err := azblob.NewClient(url, cred, nil)

_, err = client.UploadStream(ctx, containerName, key, src, &azblob.UploadStreamOptions{
	Concurrency: 1,
	BlockSize:   1 << 20, // 1mb
})
```

- How can we reproduce it?
Here is the code that gives the 403 error:
```
url := fmt.Sprintf("https://%s.blob.core.windows.net", accountName)
opts := &azidentity.WorkloadIdentityCredentialOptions{
	TenantID: *tenantID,
	ClientID: *rgBmanagedIdentityClientID,
}
cred, err := azidentity.NewWorkloadIdentityCredential(opts)
client, err := azblob.NewClient(url, cred, nil)

expiry := time.Now().Add(24 * time.Hour).UTC()
info := azblobService.KeyInfo{
	Start:  to.Ptr(time.Now().UTC().Add(-48 * time.Hour).Format(sas.TimeFormat)),
	Expiry: to.Ptr(expiry.Format(sas.TimeFormat)),
}

serviceClient := client.ServiceClient()
udc, err := serviceClient.GetUserDelegationCredential(ctx, info, nil)

sigVals := sas.BlobSignatureValues{
	Protocol:      sas.ProtocolHTTPS,
	ExpiryTime:    expiry,
	Permissions:   perm.String(),
	ContainerName: containerName,
	BlobName:      path,
}

query, err := sigVals.SignWithUserDelegation(udc)

signedUrl := fmt.Sprintf(
	"https://%s.blob.core.windows.net/%s/%s?%s",
	accountName,
	containerName,
	blobKey,
	query.Encode(),
)

sasClient, err := azblob.NewClientWithNoCredential(signedUrl, nil)
resp, err := sasClient.UploadStream(ctx, "", "", strings.NewReader("SAS upload test"), &azblob.UploadStreamOptions{})
```

- Anything we should know about your environment.

My infrastructure setup is as follows:

I have a resource group (let's call it RG-A)with a k8s cluster, a managed identity, and other resources. In another resource group (say RG-B), I have only a managed identity and a storage account with a container. 

I can successfully write blobs from an app running in the k8s cluster in RG-A to the storage container in RG-B. (Only the SAS is giving me trouble.) In RG-B, I gave `Storage Account Contributor` and `Storage Blob Data Owner` roles to the RG-B managed identity. Then, I created a federated credential that allows the k8s cluster in RG-A to auth to the managed identity in RG-B, by using the following command:

```
az identity federated-credential create \
  --name fc-x-tenant-test \
  --identity-name rg-B-managedIdentity \
  --resource-group rg-B \
  --issuer <RG-A AKS Cluster OIDC Provider URL> \
  --subject system:serviceaccount:default:<RG-A Service Account name>
```

Also, I logged the query with a previous version of the code (the only difference being I hadn't set the start time to 2 days in the past yet, it was only being set to 10 seconds in the past).
```
Query {
	version:2023-11-03 
	services: 
	resourceTypes: 
	protocol:https 
	startTime:{wall:0 ext:0 loc:<nil>} 
	expiryTime:{wall:151009920 ext:63850466819 loc:<nil>} 
	snapshotTime:{wall:0 ext:0 loc:<nil>} 
	ipRange:{Start:[] End:[]} 
	identifier: 
	resource:b 
	permissions:w 
	signature:bDcn0MCs1kGakVX9OOtKt/ApBllv68AJLZnwZK4g+5g= 
	cacheControl: contentDisposition: contentEncoding: contentLanguage: contentType: 
	signedOID:<RG-B Managed Identity Object ID> 
	signedTID:<Tenant ID> 
	signedStart:{wall:0 ext:63850380409 loc:<nil>} 
	signedService:b 
	signedExpiry:{wall:0 ext:63850466809 loc:<nil>} 
	signedVersion:2023-11-03 
	signedDirectoryDepth: authorizedObjectID: unauthorizedObjectID: correlationID: encryptionScope: stTimeFormat: seTimeFormat:
}
```

**Comment by johannesvietze** [comment]
Hi,

we are currently analyzing a similar issue in our productive environment where a blobstorage upload failed. Our best guess currently is, that the node time was off by a few seconds.

import path of package in question
```
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/bloberror"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob"
```

SDK version e.g. master, latest, 18.1.0
`github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.3.2`

go version in prod is `1.22.1 linux/amd64`

code where the error happens:
`blockblobClient, err := createBlockBlobUploadClient(destPath)
	if err != nil {
		return err
	}

	_, err = blockblobClient.UploadStream(ctx, data, &blockblob.UploadStreamOptions{})`

Here is the error we've encountered:

`PUT https://xxxxxxxxxxxxxx.blob.core.windows.net/xxxxxxxxxxxxxx/xxxxxxxxxxxxxx/xxxxxxxxxxxxxx.zip\n--------------------------------------------------------------------------------\nRESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nERROR CODE: AuthenticationFailed\n--------------------------------------------------------------------------------\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a9ba6d7b-f01e-002b-5a84-9f2a94000000\nTime:2024-05-06T07:09:35.3537024Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '+vWptkqk4dfaIzum/0fvvQjVBwTOaEAiGlu34TY9P2k=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n985458\n\napplication/octet-stream\n\n\n\n\n\n\nx-ms-date:Mon, 06 May 2024 07:09:35 GMT\nx-ms-version:2023-11-03\n/xxxxxxxxxxxxxx/xxxxxxxxxxxxxx/xxxxxxxxxxxxxx.zip\nblockid:wfCx0A6XRlxSWrV4EJ7X7AAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\ncomp:block'.</AuthenticationErrorDetail></Error>\n--------------------------------------------------------------------------------\n`

**Comment by levinandrew** [comment]
Hi @johannesvietze thank you for looking into this!!

I see that your `AuthenticationErrorDetail` says `The MAC signature found in the HTTP request '+vWptkqk4dfaIzum/0fvvQjVBwTOaEAiGlu34TY9P2k=' is not the same as any computed signature...`, while my `AuthenticationErrorDetail` says `Signature did not match. String to sign used was...`. 

Does that mean these are different causes of the 403?


Also, 
>Our best guess currently is, that the node time was off by a few seconds

what do you mean by  "node time"? I thought that there might be some clock skew causing the start time window to be after the actual time of the attempted upload, so I made it the Start time be a full 2 days in the past
```
info := azblobService.KeyInfo{
	Start:  to.Ptr(time.Now().UTC().Add(-48 * time.Hour).Format(sas.TimeFormat)),
	Expiry: to.Ptr(expiry.Format(sas.TimeFormat)),
}
```
and the issue still persists. (and from `Signature did not match. String to sign used was w 2024-05-07T16:00:21Z /blob/studcteststorage/studctest/sas_upload_test.txt/ <RG-B Managed Identity Object ID> <Tenant ID> 2024-05-04T16:00:21Z 2024-05-07T16:00:21Z b 2023-11-03 https 2023-11-03 b`, I can verify the start time was a full 2 days in the past)

**Comment by levinandrew** [comment]
@vibhansa-msft @tanyasethi-msft my issue was that I cannot specify the blob name in the `BlobSignatureValues`; however, I can specify it there when I use a SharedKeyCredential and sign with `SignWithSharedKey` instead of using a UserDelegationCredential

**Comment by tanyasethi-msft** [comment]
Hi @levinandrew , Thanks for reporting this. 
While creating `BlobSignatureValues`, you can specify the `BlobName` to generate the SAS for an Azure Storage blob. 

In the code above, while creating BlobSignatureValues,
`Permissions:   perm.String()`
What are the permissions given?

Also, 
`resp, err := sasClient.UploadStream(ctx, "", "", strings.NewReader("SAS upload test"), &azblob.UploadStreamOptions{})`
The blob name and container name are "", "". Is that intentional, and why is it so?
