### ISSUE TITLE
[sdk-wide] `go get -u all` + `go mod tidy` automation

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#22852]
Our goal here is just to have it happen on a weekly cadence, with the merge happening automatically and the testing in the weekly pipeline to validate.

Weekly pipelines for a package should do this:
1. `go get -u all`
2. `go mod tidy` 
3. Run tests
4. `git commit go.mod go.sum`
5. `git push`

Steps 4 and 5 are probably new, but we believe some teams must have some process like this in place (for instance, Java) so hopefully we can lean a bit on what they've done.

CC: @benbp, @alzimmermsft (who probably has heard of something like this for Java)

**Comment by benbp** [comment]
@richardpark-msft @jhendrixMSFT we have a pretty similar example of this already working in the go repo for the post-release steps: https://github.com/Azure/azure-sdk-for-go/blob/main/eng/pipelines/templates/jobs/archetype-go-release.yml#L112-L120

**Comment by benbp** [comment]
If you want to push to main directly we have this template: https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/git-push-changes.yml

The weekly pipelines already appear to be wired up with github permissions.

**Comment by richardpark-msft** [comment]
Moving conversation to here: https://github.com/Azure/azure-sdk-for-go/issues/21848
