### ISSUE TITLE
Possible bug in the Azure cosmos SDK: undefined min function in cosmos_location_cache.go

### ISSUE THREAD

**Issue by TreyVanderpool** [Azure/azure-sdk-for-go#22868]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `latest`
- output of `go version`: go version go1.20.14 linux/amd64

- What happened?
go get -u -v github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos it posts error at the end that the "min" function is undefined.
github.com/Azure/azure-sdk-for-go (download)
get "golang.org/x/net/http2": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/http2?go-get=1
get "golang.org/x/net/http2": verifying non-authoritative meta tag
golang.org/x/net (download)
get "golang.org/x/net/http/httpguts": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/http/httpguts?go-get=1
get "golang.org/x/net/http/httpguts": verifying non-authoritative meta tag
get "golang.org/x/net/idna": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/idna?go-get=1
get "golang.org/x/net/idna": verifying non-authoritative meta tag
get "golang.org/x/text/secure/bidirule": found meta tag vcs.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/secure/bidirule?go-get=1
get "golang.org/x/text/secure/bidirule": verifying non-authoritative meta tag
golang.org/x/text (download)
get "golang.org/x/text/transform": found meta tag vcs.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
get "golang.org/x/text/unicode/bidi": found meta tag vcs.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/bidi?go-get=1
get "golang.org/x/text/unicode/bidi": verifying non-authoritative meta tag
get "golang.org/x/text/unicode/norm": found meta tag vcs.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
get "golang.org/x/net/http2/hpack": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/http2/hpack?go-get=1
get "golang.org/x/net/http2/hpack": verifying non-authoritative meta tag
github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos
**# github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos
go/src/github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos/cosmos_location_cache.go:119:20: undefined: min**

- What did you expect or want to happen?
Be able to download existing code with no issues.

- How can we reproduce it?
run command: go get -u -v github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos

- Anything we should know about your environment.
ubuntu 22 through Windows WSL2

**Comment by jhendrixMSFT** [comment]
The latest version of `azcosmos` (`v1.0.1`) [requires Go 1.21](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/go.mod#L3) or later to compile. It was erroneously set to `1.22` in `v1.0.0`.
