### ISSUE TITLE
Our ORCA Scans report Malware in azure/azure-sdk-for-go

### ISSUE THREAD

**Issue by peterlharding** [Azure/azure-sdk-for-go#22889]
### Bug Report

<img width="1195" alt="image" src="https://github.com/Azure/azure-sdk-for-go/assets/160167/649e9b19-4e2c-43f3-a403-ce75bb8bf12e">

Path: /go/pkg/mod/github.com/!azure/azure-sdk-for-go@v57.0.0+incompatible/eng/common/scripts/Queue-Pipeline.ps1

This is coming out of an image Latitude Financial Services has implemented for a CICD image based on Alpine3.19 go 1.22.2 image - which is used in CICD pipelines.

The severity appears low and we haven't found a security provider which has flagged this as a significant issue.  But thought it was worth brining to your attention.

We were using the 1.22.2 version of this build - https://github.com/docker-library/golang/blob/eb57429622f401af7c5afffeb3cd88022c9b9782/1.22/alpine3.19/Dockerfile

The current release in the image is go 1.22.3

Our security people have picked this up in ORCA scans of both our CICD image and A Buildkite Elastic CI Stack image.  I am attempting to confirm whether this could be a false positive scan result

**Comment by jhendrixMSFT** [comment]
`v57.0.0` is a _very_ old version of the legacy SDK that's been out of support for some time now. We recommend upgrading your SDKs to their latest versions. Please see the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md) and ping back if you have any questions.
