### ISSUE TITLE
StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="InvalidResourceType" 

### ISSUE THREAD

**Issue by arthas3014** [Azure/azure-sdk-for-go#22888]
Message="The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'. The supported api-versions are '2018-05-31,2018-08-31,2018-08-01-preview,2018-10-01-preview,2018-12-01-preview,2019-01-01,2019-03-01-preview,2019-04-01-preview,2019-05-01-preview,2019-10-01,2019-11-01,2021-10-01,2022-10-01,2023-03-01,2023-04-01-preview,2023-08-01,2023-09-01,2023-11-01,2024-01-01'."

go version: 1.21.4
azure-sdk-for-go: v68.0.0+incompatible

**Comment by jhendrixMSFT** [comment]
Can we please get more info, what module and version are you using?

**Comment by jhendrixMSFT** [comment]
Ok it looks like you're using the legacy SDK which is no longer supported. The latest SDK for Microsoft.CostManagement can be found [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/costmanagement/armcostmanagement/v2).

Please see the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md) for details about migrating and ping back if you have any questions.
