### ISSUE TITLE
Hi Foljs Q

### ISSUE THREAD

**Issue by devak8** [Azure/azure-sdk-for-go#22904]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `go list -m <module>`, for example `go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Can you please provide more information? It's unclear what the ask is.
