### ISSUE TITLE
[keyvault:azkeys] cannot get key in cross tenent scenario 

### ISSUE THREAD

**Issue by suqin-haha** [Azure/azure-sdk-for-go#22928]
### Bug Report

- import path `"github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys"`
- SDK version `azkeys@v1.1.0` : https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys@v1.1.0
- go version 1.22

Condition: In cross tenant CMEK scenario, https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-configure-cross-tenant-new-account?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=azure-portal

Detailed use case I asked in Microsoft QA platform: https://learn.microsoft.com/en-us/answers/questions/1663980/how-to-get-key-info-from-other-tenant

I cannot get the key. Return unauthorized message:
```
client, err := azkeys.NewClient(vaultURL, cred, nil)
if err != nil {
    log.Fatalf("failed to create client: %v", err)
}
resp, err := client.GetKey(context.TODO(), "key-name-xxx", "71e9...", nil)
if err != nil {
    log.Fatalf("failed to get key: %v", err)
}

--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: Unauthorized
--------------------------------------------------------------------------------
{
  "error": {
    "code": "Unauthorized",
    "message": "AKV10032: Invalid issuer. Expected one of https://sts.windows.net/90a59e9d-.../, https://sts.windows.net/f8cde.../, https://sts.windows.net/e2d54e.../, found https://sts.windows.net/.../."
  }
}
```

Expect to have Key information returned. 

Reproduce: Just like the [link I put above](https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-configure-cross-tenant-new-account?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=azure-portal). 
- Two tenant A, B. 
- A create vault and key. 
- B register multi-tennant application with federated identity set for CMEK
- A give the permission/role to the application created in B
- Use Azkey SDK to get the key by the application (I use client secret credential)

NOTE: 
1. Same problem for .Net. https://github.com/Azure/azure-sdk-for-net/issues/18359
2. I asked question in Microsoft QA platform too (no answer yet): https://learn.microsoft.com/en-us/answers/questions/1663980/how-to-get-key-info-from-other-tenant

**Comment by gracewilcox** [comment]
Same as https://github.com/Azure/azure-sdk-for-go/issues/19841

Looking into now

**Comment by gracewilcox** [comment]
Hi @suqin-haha! We are aware that we don't currently have cross tenant auth in Key Vault. Planning to add this functionality.

**Comment by suqin-haha** [comment]
> Hi @suqin-haha! We are aware that we don't currently have cross tenant auth in Key Vault. Planning to add this functionality.

Thanks @gracewilcox 
And Could the SDK also have a `region` field in the key information?
The purpose of this `get key cross tenant` feature is for Key Validation when costumers provide their own key. In the same scenario, the region is also important since `DiskEncryptionSet` requuires key in the Same region. Although, there is a hacky way to get the region, https://learn.microsoft.com/en-us/answers/questions/1661177/how-to-get-azure-key-key-vault-region, but it's better if we could have a `region` field in the key information. :)

BTW, if it's possible, a general estimate time line about this feature would a lot helpful, Thanks!

**Comment by gracewilcox** [comment]
> > Hi [@suqin-haha](https://github.com/suqin-haha)! We are aware that we don't currently have cross tenant auth in Key Vault. Planning to add this functionality.
> 
> Thanks [@gracewilcox](https://github.com/gracewilcox) And Could the SDK also have a `region` field in the key information? The purpose of this `get key cross tenant` feature is for Key Validation when costumers provide their own key. In the same scenario, the region is also important since `DiskEncryptionSet` requuires key in the Same region. Although, there is a hacky way to get the region, https://learn.microsoft.com/en-us/answers/questions/1661177/how-to-get-azure-key-key-vault-region, but it's better if we could have a `region` field in the key information. :)

Hi @suqin-haha! The region is determined by the vault that contains the key. If you want to programmatically learn the region of the vault, I would use our [`armkeyvault`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault) module. The [VaultsClient.Get method](https://github.com/Azure/azure-sdk-blog/pull/515#discussion_r1811348190) returns a [Vault](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault#Vault) struct with a region field.

**Comment by suqin-haha** [comment]
> > > Hi [@suqin-haha](https://github.com/suqin-haha)! We are aware that we don't currently have cross tenant auth in Key Vault. Planning to add this functionality.
> > 
> > 
> > Thanks [@gracewilcox](https://github.com/gracewilcox) And Could the SDK also have a `region` field in the key information? The purpose of this `get key cross tenant` feature is for Key Validation when costumers provide their own key. In the same scenario, the region is also important since `DiskEncryptionSet` requuires key in the Same region. Although, there is a hacky way to get the region, https://learn.microsoft.com/en-us/answers/questions/1661177/how-to-get-azure-key-key-vault-region, but it's better if we could have a `region` field in the key information. :)
> 
> Hi [@suqin-haha](https://github.com/suqin-haha)! The region is determined by the vault that contains the key. If you want to programmatically learn the region of the vault, I would use our [`armkeyvault`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault) module. The [VaultsClient.Get method](https://github.com/Azure/azure-sdk-blog/pull/515#discussion_r1811348190) returns a [Vault](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault#Vault) struct with a region field.

Hi @gracewilcox 
I have tried it before, and still int he cross tenant scenario, the key is from our customer, we only know the key. We cannot and should not have access to the full vault client. And some action (like disk encryption) needs the region to be the same, it's like a black box, only way is to try it, and it's cost too much to try it. So If we can expose the region to the key would be really great in this scenario. 

Correct me if I am wrong, just want a cheap and reliable way to validate the key and region looks not a sensitive information. Thanks!

**Comment by gracewilcox** [comment]
Hi @suqin-haha! Getting the region just from the key is not currently possible. 

Please open a separate issue in this repo describing the new feature, and we can appropriately route your request to the service team.
