### ISSUE TITLE
Go mgmt. SDK release toolchain need to support TypeSpec

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#22929]
```[tasklist]
### Tasks
- [ ] SDK generation
- [ ] ChangeLog generation
- [ ] Breaking change detection
```

**Comment by lirenhe** [comment]
Can we prioritize changelog generation first?

**Comment by tadelesh** [comment]
> Can we prioritize changelog generation first?

we need to generate sdk from typespec first, then most of the logic could be reuse for changelog tool and breaking change detection tool.
