### ISSUE TITLE
Add support for usage stats when streaming chat completion

### ISSUE THREAD

**Issue by jonasbleyl** [Azure/azure-sdk-for-go#22940]
### Feature Request

When streaming a Chat Completion request, one can now specify an option to enable the token usage statistics in the stream options:

https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options

> **include_usage:** boolean
> If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value.

Please could you add support for this!

**Comment by richardpark-msft** [comment]
@glecaros, do you want to take this since you're generating the 05-01 surface?

**Comment by richardpark-msft** [comment]
@jonasbleyl, I looked into this. We don't currently support this flag in Azure OpenAI, and we typically don't add features to the library unless they work with both. I don't have an ETA on this at this point either, unfortunately.
