### ISSUE TITLE
azidentity: az-cli resource does not include trailing slash, leading to auth-tokens being rejected by Microsoft Fabric SQL Endpoints

### ISSUE THREAD

**Issue by aslatter** [Azure/azure-sdk-for-go#22957]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/azidentity`
- SDK version: v1.5.1
- output of `go version`: `go version go1.22.1 darwin/arm64`

- What happened? Entra auth tokens generated by the az-cli auth-method are rejected by Microsoft Fabric SQL endpoints. 
- What did you expect or want to happen? Similar tokens generated by the C# Azure Identity SDK are accepted.
- How can we reproduce it? Attempt to use the 'sqlcmd' executable to run queries against Microsoft Fabric SQL endpoints. 'sqlcmd' is a Go executable, using the `azidentity` SDK. For example, running the following on MacOS should attempt az-cli auth:

   ```sh
   az login
   sqlcmd -G -S <fabric sql endpoint>.datawarehouse.fabric.microsoft.com -Q 'SELECT 1;'
   ```
- Anything we should know about your environment.

If I patch azidentity to include a trailing slash in the *resource* we pass to the az-cli after stripping off the `/.default` suffix the auth tokens are accepted by Microsoft Fabric SQL endpoints:

```diff
diff --git a/sdk/azidentity/azure_cli_credential.go b/sdk/azidentity/azure_cli_credential.go
index b9976f5fed..01e3557023 100644
--- a/sdk/azidentity/azure_cli_credential.go
+++ b/sdk/azidentity/azure_cli_credential.go
@@ -113,8 +113,11 @@ func (c *AzureCLICredential) GetToken(ctx context.Context, opts policy.TokenRequ
 // defaultAzTokenProvider invokes the Azure CLI to acquire a token. It assumes
 // callers have verified that all string arguments are safe to pass to the CLI.
 var defaultAzTokenProvider azTokenProvider = func(ctx context.Context, scopes []string, tenantID, subscription string) ([]byte, error) {
+       resource := scopes[0]
        // pass the CLI a Microsoft Entra ID v1 resource because we don't know which CLI version is installed and older ones don't support v2 scopes
-       resource := strings.TrimSuffix(scopes[0], defaultSuffix)
+       if strings.HasSuffix(resource, defaultSuffix) {
+               resource = strings.TrimSuffix(resource, defaultSuffix) + "/"
+       }
        // set a default timeout for this authentication iff the application hasn't done so already
        var cancel context.CancelFunc
        if _, hasDeadline := ctx.Deadline(); !hasDeadline {
```

I really don't know if this is a Fabric bug or an *azidentity* Go-SDK-bug, but the C# SDK when used in similar manner includes a trailing slash in the resource.

Specifically, this test C# program generates an Entra token with an *aud* claim of `https://database.windows.net/`:

<details>
  <summary>Click me</summary>

```csharp
using Dapper;
using Microsoft.Data.SqlClient;

var server = Environment.GetEnvironmentVariable("SQL_ENDPOINT");
var connString = $"Server={server};Authentication=Active Directory Default; Encrypt=True;";

using var sqlConnection = new SqlConnection(connString);

sqlConnection.Open();
Console.WriteLine("Connected successfully!");

foreach (var o in sqlConnection.Query("SELECT 1;"))
{
    Console.WriteLine(o);
}
```  

</details>

(Note that *Microsoft.Data.SqlClient* version 5.2.0 isn't working for me in this test, so I used 5.1.5)

And this test Go program generates an Entra token with an *aud* cliam of `https://database.windows.net` (note the missing slash), which doesn't work against Microsoft Fabric (unless I used my patched version of *azidentity*):

<details>
  <summary>Click me</summary>
 
 ```go
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"os"

	_ "github.com/microsoft/go-mssqldb"
	"github.com/microsoft/go-mssqldb/azuread"
)

func main() {
	var host string
	var database string
	var query string

	flag.StringVar(&host, "host", "", "SQL endpoint")
	flag.StringVar(&database, "database", "", "SQL database")
	flag.StringVar(&query, "query", "", "SQL query")
	flag.Parse()

	if host == "" {
		errAndExit("missing flag -host")
	}
	if database == "" {
		errAndExit("missing flag -database")
	}

	connString := fmt.Sprintf("server=%s;database=%s;fedauth=ActiveDirectoryDefault;", host, database)

	db, err := sql.Open(azuread.DriverName, connString)
	if err != nil {
		errAndExit("opening db: %s", err)
	}
	defer db.Close()

	_, err = db.Exec(query)
	if err != nil {
		errAndExit("running query: %s", err)
	}

}

func errAndExit(format string, a ...any) {
	fmt.Fprintf(os.Stdout, format, a...)
	fmt.Fprintln(os.Stdout)
	os.Exit(1)
}

```

</details>

**Comment by chlowell** [comment]
Thanks for opening this issue. We can't solve this problem in azidentity because the resource/scope must be exactly correct. Adding a trailing `/` in all cases would create the problem you're experiencing for other clients. The caller, in this case `go-mssqldb`, is responsible for passing the correct scope. `go-mssqldb` apparently trims trailing slashes in all cases; I opened https://github.com/microsoft/go-mssqldb/issues/197 to track fixing that.

**Comment by aslatter** [comment]
`go-mssqldb` is passing the scope `https://database.windows.net/.default`. The *azidentity* SDK is trimming this to `https://database.windows.net`. Is the expectation that the service-endpoint should be accepting the slash-less version?

**Comment by chlowell** [comment]
The problem isn't really the service's behavior, though a change there could prevent it. All v2 default scopes like `foo/.default` have an equivalent v1 resource like `foo`, so the rule for converting between the two is to add or remove `/.default`. `https://database.windows.net/` is apparently the correct v1 resource in this case, making the corresponding v2 scope `https://database.windows.net//.default`, and that's what `go-mssqldb` should specify. The fact that the service doesn't accept `https://database.windows.net` suggests `https://database.windows.net/.default` is similarly invalid. But it could in principle accept both resource/scope pairs, with and without the extra `/`, and that would prevent this problem.

**Comment by aslatter** [comment]
Thanks for your help! I'll see if I can get some clarity on the service end of things.
