### ISSUE TITLE
arm/compute.VirtualMachinesClient.Deallocate errors on 200 OK

### ISSUE THREAD

**Issue by axw** [Azure/azure-sdk-for-go#230]
When using the VirtualMachinesClient.Deallocate method, a 200 OK response causes an error. The code is only allowing for 202 Accepted.

```
autorest:WithErrorUnlessStatusCode GET https://management.azure.com
/subscriptions/6f0e3b87-f601-40fd-9727-76d05563fedd/providers/Microsoft.Compute/locations/southeastasia/operations/9136bb98-77e2-495c-994b-8aff2b51547a?monitor=true&api-version=2015-06-15 failed with 200 OK
```

**Comment by brendandixon** [comment]
@axw This is certainly a bug. I need to see if the Swagger is incorrect (likely), but even if it is, the code generator can do better (e.g., always include 200 in the suite of accepted return codes). Let me dig a bit and I'll try to get a new build out soon.

**Comment by axw** [comment]
Thanks! This is fixed on master.
