### ISSUE TITLE
[azeventhubs] Producer Client loses connection

### ISSUE THREAD

**Issue by smodi2-tmo** [Azure/azure-sdk-for-go#23008]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
  
   -> `github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs`

- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `go list -m <module>`, for example `go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore`.
   
   -> ` v1.2.1`
    
- output of `go version`
  
   -> `go1.22.4 linux/amd64`

- What happened?
   -> I have created a Producer client and using it to send multiple events concurrently to an Event Hub. I am sending about 90 requests per second. My sender which sends requests expects responses in 10 seconds. Usually, all requests are processed in less than 1 second. However, after some time, the Eventhub producer client loses the connection and prints the logs as shown below after 4:14 pm. At that time, It takes more than 10 seconds to process the requests and the sender closes the connection.

```
6/6/24 4:08:17.622 PM | [azeh.Conn] Creating link for partition ID ''
6/6/24 4:08:17.622 PM | [azeh.Conn] Creating new client, current rev: 0
6/6/24 4:08:18.212 PM | [azeh.Conn] Client created, new rev: 1, took 590ms
6/6/24 4:08:18.607 PM | [azeh.Conn] (c:1,l:W8bX2,p:): Succesfully created link for partition ID ''
6/6/24 4:14:53.836 PM | [azeh.Conn] (c:1,l:W8bX2,p:) Error when cleaning up old link: write tcp 192.168.61.97:41092->10.77.208.34:5671: i/o timeout
6/6/24 4:14:53.836 PM | [azeh.Conn] Error closing old client: write tcp 192.168.61.97:41092->10.77.208.34:5671: i/o timeout
6/6/24 4:14:53.836 PM | [azeh.Conn] Creating a new client (rev:1)
6/6/24 4:14:53.836 PM | [azeh.Conn] Creating new client, current rev: 1
6/6/24 4:14:54.273 PM | [azeh.Conn] Client created, new rev: 2, took 436ms
6/6/24 4:14:54.273 PM | [azeh.Conn] Creating link for partition ID ''
6/6/24 4:14:54.273 PM | [azeh.Conn] Skipping connection recovery, already recovered: 2 vs 1. Links will still be recovered.
6/6/24 4:14:54.273 PM | [azeh.Conn] Skipping connection recovery, already recovered: 2 vs 1. Links will still be recovered.
6/6/24 4:14:54.273 PM | [azeh.Conn] Skipping connection recovery, already recovered: 2 vs 1. Links will still be recovered.
```

- What did you expect or want to happen?
   -> Producer client should not be losing connection.
- How can we reproduce it?
   -> Create an API handler. Create a producer client and process requests concurrently. Send events using below code
   ```
  
    func SendEvent(ctx context.Context, eventHubName EventHubName, event any, batchOptions *azeventhubs.EventDataBatchOptions) error {
	    
	    marshalledEvent, err := json.Marshal(event)
	    if err != nil {
		    return fmt.Errorf("error marshalling data to JSON: %w", err)
	    }
    
	    // get the producer client from the context
	    producerClient, ok := (*FromContext(ctx))[eventHubName]
	    if !ok {
		    return ProducerClientNotFound(string(eventHubName))
	    }
    
	    batch, err := producerClient.NewEventDataBatch(ctx, batchOptions)
	    if err != nil {
		    return err
	    }
    
	    // convert the event to Azure EventData object
	    eventData := &azeventhubs.EventData{
		    Body:        marshalledEvent,
		    ContentType: to.Ptr("application/json"),
	    }
    
	    if err := batch.AddEventData(eventData, nil); err != nil {
		    return err
	    }
	    defer duration(track(ctx, "SendEventDataBatch"))
	    // send the batch of events to the event hub
	    err = producerClient.SendEventDataBatch(ctx, batch, nil)
	    if err != nil {
		    return err
	    }
	    return nil
    }

   ```
- Anything we should know about your environment.
   -> I am running the service as an OpenFaaS serverless function in a K8s Cluster.
        Eventhub  namespace config: Standard Tier, 2 Throughput Units

**Comment by richardpark-msft** [comment]
Hey @smodi2-tmo, sorry for the long delay on my reply here.

> 6/6/24 4:14:53.836 PM | [azeh.Conn] (c:1,l:W8bX2,p:) Error when cleaning up old link: write tcp 192.168.61.97:41092->10.77.208.34:5671: i/o timeout
> 6/6/24 4:14:53.836 PM | [azeh.Conn] Error closing old client: write tcp 192.168.61.97:41092->10.77.208.34:5671: i/o timeout

Our underlying AMQP stack maintains a persistent TCP connection to the Event Hub namespace - if there's an interruption producing the client will pause while we reestablish the connection, which can be relatively expensive. This can account for some of the delay.

The other part of the delay is coming from our retry policy, which purposefully provides a backoff timeout to prevent retrying an operation too rapidly. This is configured in ProducerClientOptions.RetryPolicy, here: 

* ProducerClientOptions.RetryPolicy: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#ProducerClientOptions
* RetryOptions: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs@v1.2.1/internal/exported#RetryOptions

Some connectivity drops can happen, just by nature of networks so you might need to adjust your tolerances on how long an operation can take or change the retry options to suit your needs - potentially lowering the number of retries (so you get an error faster), or reducing the amount of wait time so more retries occur quicker. 

I'll add in a stress test for our library, just to be sure, but closing this issue as I think it's considered a normal thing to have to deal with network retries.

Please reopen if I've missed any detail in here, or you want more information.
