### ISSUE TITLE
Cannot Deserialize AutomationRule that uses boolean conditions

### ISSUE THREAD

**Issue by ryan00** [Azure/azure-sdk-for-go#23027]
### Bug Report
https://github.com/Azure/azure-sdk-for-go/blob/edf8e3fc894943f19de268ae70dad9379fd4e377/sdk/resourcemanager/securityinsights/armsecurityinsights/polymorphic_helpers.go#L152

SDK version: latest
go version: go1.22.3 linux/amd64

The condition is not being deserialized correctly when the Condition Type == Boolean

https://learn.microsoft.com/en-us/rest/api/securityinsights/automation-rules/create-or-update?view=rest-securityinsights-2024-03-01&tabs=HTTP#automationrulebooleancondition

To reproduce create an automation rule that has a boolean condition and call 

func (client *AutomationRulesClient) Get(ctx context.Context, resourceGroupName string, workspaceName string, automationRuleID string, options *AutomationRulesClientGetOptions) (AutomationRulesClientGetResponse, error)

expected output is a properly deserialized AutomationRule when boolean triggering conditions are used.

**Comment by Alancere** [comment]
Hi @ryan00, please use [armsecurityinsights/v2@v2.0.0-beta.4](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/securityinsights/armsecurityinsights/v2@v2.0.0-beta.4) try again.

**Comment by ryan00** [comment]
I will give that link try, I am fine with closing this issue and I can follow up with any other issues in a new ticket. Thanks again.
