### ISSUE TITLE
 Storage SDK is missing `copy` feature

### ISSUE THREAD

**Issue by somesylvie** [Azure/azure-sdk-for-go#23054]
### Feature Request
Please add the [copy blob](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id) feature to the azblob blob storage SDK (I'm specifically looking for copying a blob within Azure rather than from a public URL). This feature is available for .NET, Java, Python, JavaScript, and TypeScript, but is missing for Go.

**Comment by tanyasethi-msft** [comment]
Hey @somesylvie, You can use this method - [blob.StartCopyFromURL](https://github.com/Azure/azure-sdk-for-go/blob/c00d659e25b61d8cab9af614b2c598fe7b7b0734/sdk/storage/azblob/blob/client.go#L215C1-L222C1) to copy a blob within Azure.
It provides the functionality for CopyBlob API

**Comment by somesylvie** [comment]
> Hey @somesylvie, You can use this method - [blob.StartCopyFromURL](https://github.com/Azure/azure-sdk-for-go/blob/c00d659e25b61d8cab9af614b2c598fe7b7b0734/sdk/storage/azblob/blob/client.go#L215C1-L222C1) to copy a blob within Azure. It provides the functionality for CopyBlob API

Then I would have to create a new client every time I want to copy a file, since the `blob` client is blob-specific. This is counter to what I expect from a client, which is usually something reusable

**Comment by souravgupta-msft** [comment]
Copy Blob is a blob specific operation. You will have to create the blob client if you want to call this API.
If you want a client which is reusable, you can create a service client and then do this,
`svcClient.NewContainerClient(containerName).NewBlobClient(blobName).StartCopyFromURL(.....)`
