### ISSUE TITLE
Virtual Machines Managed Identity Info is Missing

### ISSUE THREAD

**Issue by lchavan-uptycs** [Azure/azure-sdk-for-go#23050]
### Bug Report

Issue: Virtual Machines Managed Identity Info is Missing

Go-sdk version: `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5 v5.7.0`
CLI cmd used: `az vm list`

We had A VM's resources with attached Managed Identity, which should get `clientId` and `principalId` in `Identity` attribute as follow
```
{
  "id": "/subscriptions/<subscription-id>/resourceGroups/<group>/providers/Microsoft.Compute/virtualMachines/<vm-name>",
  "identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "/subscriptions/<subscription-id>/resourceGroups/<group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<mi-name>": {
        "clientId": "11111111-1111-1111-1111-111111111111",
        "principalId": "11111111-1111-1111-1111-111111111112"
      }
   }
}
```
but in our case we are receiving
```
{
  "id": "/subscriptions/<subscription-id>/resourceGroups/<group>/providers/Microsoft.Compute/virtualMachines/<vm-name>",
  "identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "/subscriptions/<subscription-id>/resourceGroups/<group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<mi-name>": {
        "clientId": null,
        "principalId": null
      }
   }
}
```
as we can see in the response we are getting the info related to resource id of the Managed Identity but not the clientId and principalId

code snippet to reproduce
```
listPager := client.NewListAllPager(nil)
for listPager.More() {
  resp, err := listPager.NextPage(ctx)
  if err != nil {
	  panic(err)
  }

  for _, res := range resp.Value {
	  print(res.Name, res.Identity.UserAssignedIdentities)
  }
}
```
 in the `res.Identity.UserAssignedIdentities` attribute we should see the desired data
 
**CLI output**
![screenshot_from_2024-06-12_18-09-52](https://github.com/Azure/azure-sdk-for-go/assets/91864935/c78e329b-ddab-4377-a463-10539849c9cd)

**UI output**
![screenshot_from_2024-06-12_18-08-40](https://github.com/Azure/azure-sdk-for-go/assets/91864935/bef6a7e5-1d6a-43dd-858f-0adea556a636)

**Comment by Alancere** [comment]
repo can obtain clientId and principalId
![image](https://github.com/Azure/azure-sdk-for-go/assets/46921893/68c706b3-022f-47fb-b1dc-042e9660ec6d)

Hi @lchavan-uptycs, there could be a delay, please try again.
