### ISSUE TITLE
Question: how to avoid a login on each run when using NewInteractiveBrowserCredential

### ISSUE THREAD

**Issue by rtrigo-opengov** [Azure/azure-sdk-for-go#23112]
Hello Team! I have a smiliar problem than the one reported on this issue https://github.com/Azure/azure-sdk-for-go/issues/21814

Probably is a me problem, but i couldn't find any recent documentation regarding my use case.

Basically, i want my code to authenticate interactively using the browser, but not each time the user runs the app, only the first time , and save the credentials on a file. 

I did follow the example referenced on the doc linked on issue 21814, but seems to be from an old version, and several things aren't exported anymore (for example `azidentity.AuthenticationRecord`). 

What's the best approach to save somehow the session that the user initiated interactively?

I don't have much code to show really, currently i'm doing the following, and that works, but as i said it opens a browser on every run.

```
		cred, err = azidentity.NewInteractiveBrowserCredential(&azidentity.InteractiveBrowserCredentialOptions{
			TenantID: "some-tenant-number"})
```

Using `github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.7.0` 
go version `go1.22.4 darwin/arm64`

- What happened?
  The user gets the interactive login each time it runs the app
- What did you expect or want to happen?
   Have some way to cache it locally, similar experience than when running `az login` command line
- How can we reproduce it?
   Login using NewInteractiveBrowserCredential
- Anything we should know about your environment.
   Not really

Thanks!

**Comment by chlowell** [comment]
You can still use the persistent caching feature, it's just stayed in beta while we released a couple stable versions with other features. The package docs for the latest beta release have [an example](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.7.0-beta.1#example-package-PersistentUserAuthentication) showing how to do what you want. The next beta, v1.8.0-beta.1, will also include persistent caching, with some breaking changes to the AP (I'll update the example for that version).
