### ISSUE TITLE
[azcosmos] 1.0.3 - The provided cross partition query can not be directly served by the gateway

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-for-go#23128]
### Bug Report

```
POST https://xxxxxxxxxxxxxx.documents.azure.com:443/dbs/xxxxxxxxxxxxxxx
                                        --------------------------------------------------------------------------------
                                        RESPONSE 400: 400 Bad Request
                                        ERROR CODE: 400 Bad Request
                                        --------------------------------------------------------------------------------
                                        {
                                          "code": "BadRequest",
                                          "message": "The provided cross partition query can not be directly served by the gateway.
This is a first chance (internal) exception that all newer clients will know how to handle gracefully.
This exception is traced, but unless you see it bubble up as an exception (which only happens on older SDK clients), then you can safely ignore this message.\r\nActivityId: 21657cbb-1c5f-4826-b850-ab7da56a63d2, Microsoft.Azure.Documents.Common/2.14.0",
```
Is that missing implementation in the go client for cross partition queries?
We use cross partition queries without trouble in other places. is thast just a transient error?

**Comment by ealsur** [comment]
The Go SDK currently only allows Single Partition queries in the public API. How are you executing a cross-partition query?

**Comment by ealsur** [comment]
Reference: https://github.com/Azure/azure-sdk-for-go/issues/18578

**Comment by jim-minter** [comment]
Some clarifications @ealsur :smile:

We currently do cross-partition queries by manually and selectively setting "x-ms-documentdb-query-enablecrosspartition: true" and removing the "x-ms-documentdb-partitionkey" header via client `PerCallPolicies` on simple cross-partition queries initiated via NewQueryItemsPager.  We're not blocked here but we would really like to see #18578 implemented and have native support in the Go client for this, it's well overdue.

We would really like to see better parity between the Go client and .NET/Java/Python for complex cross-partition query support, at least in basic cases to begin with.  We can get by for now, but perhaps this issue could be an RFE for that if there isn't one already open?

**Comment by ealsur** [comment]
Thanks for the details. So the error you are getting is what I mentioned on that issue: https://github.com/Azure/azure-sdk-for-go/issues/18578#issuecomment-1839225168 

> .... if the query has any [aggregates or TOP, ORDER BY, OFFSET LIMIT, DISTINCT, and GROUP BY it won't work](https://learn.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api#queries-that-cannot-be-served-by-gateway)

If the ask is to support cross-partition queries, please add a +1 to the existing Issue to reduce duplication.
