### ISSUE TITLE
Question: How can I count the number of blobs in a storage container?

### ISSUE THREAD

**Issue by QuentinBisson** [Azure/azure-sdk-for-go#23137]
I tried to get around to counting the number of blobs in my storage container to make sure I do not delete it until it is empty because I could not find any other way to count the number of items but I stumbled upon the issue that I need another role to be able to access the blobs.

If you have a simpler way to count items, I would love some help but if you do not, do you have guidance on how to create the role assignment with the go sdk?

**Comment by tanyasethi-msft** [comment]
Hey @QuentinBisson ,
You can use the below method to list the blobs in your storage container. 

https://github.com/Azure/azure-sdk-for-go/blob/154d77d54caacbcb8a5265910e594796fd7d842f/sdk/storage/azblob/client.go#L118
Just create a new client and use an empty marker to start enumeration from the beginning and then count. 
Example - 
`var count = container.ListBlobs().Count();`


If you are using azure-cli, you can use the following command - 
`az storage blob list --account-name <name> --container-name <name> --num-results "*" --query "length(@)"`

If your account has large blob storage with millions of blobs - 
If you are using azure portal, 
![image](https://github.com/Azure/azure-sdk-for-go/assets/124860586/4a572252-bb04-4108-946e-c484e51e8355)
Please feel free to re-open this issue if the problem still exists.

**Comment by QuentinBisson** [comment]
You're definitely right and I did not think of this considering I was using the container API and not the blob api. The issue with the container api not returning the number of items is that I need data permissions now to get access to something that would be better as a container metadata in my opinion but there's nothing in the API to fix this (so this is not a go sdk issue) 

Thank you
