### ISSUE TITLE
Pagination of Availability Statuses does not work

### ISSUE THREAD

**Issue by jkroepke** [Azure/azure-sdk-for-go#23148]
### Bug Report

- import path of package in question, e.g. `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth`
- SDK version e.g. `1.3.0`,`1.4.0-beta.2`,
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `go list -m <module>`, for example `go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore`.
- output of `go version` go version go1.22.4 darwin/arm64

- What happened? Pagination of Availability Statuses returns into 400 Bad Request
- What did you expect or want to happen? Pagination works
- How can we reproduce it?

```go
package main

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth"
)

func main() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}

	client, err := armresourcehealth.NewAvailabilityStatusesClient("...", cred, nil)
	if err != nil {
		panic(err)
	}

	pager := client.NewListBySubscriptionIDPager(nil)

	for pager.More() {
		_, err := pager.NextPage(context.Background())
		if err != nil {
			panic(err)
		}
	}
}

```

- Anything we should know about your environment.
I error appears only, if the Rest API has multiple pages

I can observe that the first response contains a nextLink property. Following the nextLink property return into a Bad Request 400: `{"message":"Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.","code":"InvalidODataQueryOptions"}`

**Comment by Alancere** [comment]
reproduce, I can successfully return the result.
![image](https://github.com/user-attachments/assets/d1860898-9835-4065-9308-2a8777d4285c)

**Comment by jkroepke** [comment]
@Alancere did you run the code without stopping in the first loop?

The first fetch works fine, following the next link return an error

**Comment by Alancere** [comment]
> @Alancere did you run the code without stopping in the first loop?
> 
> The first fetch works fine, following the next link return an error

The first time it stopped, the first time it was normal, the second time the nextLink url was added with skiptoken

**Comment by jkroepke** [comment]
it seems fixed by upstream
