### ISSUE TITLE
Add tracing to the Cosmos Client

### ISSUE THREAD

**Issue by kjg** [Azure/azure-sdk-for-go#23185]
### Feature Request

I see that many of the packages such as aztables and azidentity have build in tracing support, but it appears that azcosmos does not yet have this.

Is this on the roadmap at all or would you be open to accepting a contribution adding this to the cosmos implementation?

**Comment by Pilchie** [comment]
Also tagging @simorenoh and @ealsur.

**Comment by jhendrixMSFT** [comment]
This should be pretty straightforward, just need to add calls to `runtime.StartSpan` in the APIs. It should look like [this](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/security/keyvault/azkeys/client.go#L45-L47). Just be sure that `err` doesn't get shadowed so that the correct value is captured.

**Comment by kjg** [comment]
@jhendrixMSFT it looks like the Tracer is added to all azcore Client based clients, but cosmos seems to use Pipelines directly without an azcore Client. Would it make sense to just add [this little bit](https://github.com/Azure/azure-sdk-for-go/blob/62f7a3d0e97610a8303e313f25ab4502766b8886/sdk/azcore/core.go#L140) from azcore's NewClient into cosmos's NewClient functions?

Also, would you like for me to open a PR for these changes, or do you foresee this being added from your side? Thanks!!

**Comment by jhendrixMSFT** [comment]
Good point. We will also need to update the `azcosmos.Client` to use the `azcore.Client` internally so this is properly wired up.

**Comment by jhendrixMSFT** [comment]
@ealsur I took a stab at updating the cosmos client to use an `*azcore.Client` internally. Looks like a lot of tests will need to be updated though. Not sure how you want to proceed here but below is my conversion so you can get an idea.

https://github.com/jhendrixMSFT/azure-sdk-for-go/commit/859e79f9887c2ed01d9f951e44e42aefc8da454c

**Comment by Pilchie** [comment]
Thanks @jhendrixMSFT.  Just wanted to point out that it might be a couple of weeks before we're able to pick this up.

**Comment by ealsur** [comment]
@jhendrixMSFT Is the recommendation that all clients inherit from `azcore.Client`? Which are the benefits? Otherwise we could simply create a Tracer of our own?

Creating the Tracer would not be enough though right? We would need to wire the Tracer on all operations?

**Comment by jhendrixMSFT** [comment]
Not inherit but embed. This way, you get all the wiring and any other future changes for free. If not, you'd want to reimplement the body of [`NewClient`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/core.go#L127-L152) with the same content.

**Comment by ealsur** [comment]
@jhendrixMSFT Let's say we embed it, do we need to implement calls to the tracer anyway around the user methods? Just trying to measure the effort required.

**Comment by jhendrixMSFT** [comment]
Yeah, each method will require adding a call to `runtime.StartSpan`.
