### ISSUE TITLE
ARM Resource Health NewEmergingIssuesClient().NewListPager NextPage is failing to unmarshall armresourcehealth.EmergingIssue.RefreshTimestamp

### ISSUE THREAD

**Issue by gjansen42** [Azure/azure-sdk-for-go#23187]
### Bug Report

github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth v1.3.0
go version go1.21.0 linux/arm64

Using example code from https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth#EmergingIssue

RefreshTimestamp format error

Output:
failed to advance page: unmarshalling type *armresourcehealth.EmergingIssueListResult: unmarshalling type *armresourcehealth.EmergingIssueListResult: struct field Value: unmarshalling type *armresourcehealth.EmergingIssuesGetResult: struct field Properties: unmarshalling type *armresourcehealth.EmergingIssue: struct field RefreshTimestamp: parsing time "\"2024-07-13 18:23:06Z\"" as "\"2006-01-02T15:04:05.999999999Z07:00\"": cannot parse " 18:23:06Z\"" as "T"

Reproduce by running the example code.

Thanks!

**Comment by Alancere** [comment]
It is a problem with the parsing time of [armresourcehealth@v1.3.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth@v1.3.0). Please use [armresourcehealth@v1.4.0-beta.2 ](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth@v1.4.0-beta.2)temporarily.

**Comment by gjansen42** [comment]
Using 1.4.0-beta.2 worked
