### ISSUE TITLE
Input required: ConnectedServiceNameARM when deploying test resources with federated auth

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#23208]
The `Deploy test resources` task fails with `Input required: ConnectedServiceNameARM`, [for example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3971918&view=logs&j=f2fdcfc0-517a-54da-5470-14d969dcefd1&t=9254bef8-9afb-50a0-0ab7-2d5dcfa2f4fc&l=9), when `UseFederatedAuth: true`.

**Comment by chlowell** [comment]
Same problem for [go - azservicebus](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3974086&view=logs&j=f2fdcfc0-517a-54da-5470-14d969dcefd1&t=9254bef8-9afb-50a0-0ab7-2d5dcfa2f4fc&l=9). I see these pipelines both set `CloudConfig`, so I guess we're missing some service connection configuration there.

**Comment by benbp** [comment]
This will be resolved with https://github.com/Azure/azure-sdk-for-go/pull/23240, merging in two weeks (I am out next week).

**Comment by benbp** [comment]
Closing this issue as it's resolved for the nightly pipeline live tests. I will open a similar issue in azure-sdk-tools tracking this issue as it pertains to sovereign clouds, as that will be a common change.
