### ISSUE TITLE
AuthorizationFailed

### ISSUE THREAD

**Issue by aohanhongzhi** [Azure/azure-sdk-for-go#23235]
### Service Package Request

  https://github.com/Azure-Samples/azure-sdk-for-go-samples.git

https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/main/sdk/resourcemanager/network/securitygroups

I have create a App registrations but I don't know how connect it to my vm resource

![image](https://github.com/user-attachments/assets/1d2d165b-e3ed-4682-a1ca-b9d2f732a42c)

```go
GOROOT=/opt/eric/go #gosetup
GOPATH=/home/eric/Project/Go #gosetup
GOPROXY=https://goproxy.cn,direct #gosetup
GONOPROXY= #gosetup
/opt/eric/go/bin/go build -o /home/eric/.cache/JetBrains/GoLand2024.2/tmp/GoLand/___go_build_github_com_Azure_Samples_azure_sdk_for_go_samples_sdk_resourcemanager_network_securitygroups github.com/Azure-Samples/azure-sdk-for-go-samples/sdk/resourcemanager/network/securitygroups #gosetup
/home/eric/.cache/JetBrains/GoLand2024.2/tmp/GoLand/___go_build_github_com_Azure_Samples_azure_sdk_for_go_samples_sdk_resourcemanager_network_securitygroups
2024/07/23 11:18:19 PUT https://management.chinacloudapi.cn/subscriptions/75a2691b-c0a3-410f-9ea1-2aff67fcb91c/resourcegroups/vm-rblc-grow-put_group
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '3e743de1-81c1-4cc4-a0f3-4055a21b1d1f' with object id '3e743de1-81c1-4cc4-a0f3-4055a21b1d1f' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/75a2691b-c0a3-410f-9ea1-2aff67fcb91c/resourcegroups/vm-rblc-grow-put_group' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
--------------------------------------------------------------------------------

Process finished with the exit code 1

```

**Comment by jhendrixMSFT** [comment]
@chlowell do we have an e2e example for this?

**Comment by chlowell** [comment]
Judging by the error message, it appears what's missing here is assigning a role to the service principal allowing it to add resources to the resource group, such as the built-in "Contributor" role. We have [this document](https://aka.ms/azsdk/identity/AppRegistrationAndRoleAssignment#assign-azure-roles-using-the-azure-portal) describing RBAC (Role Based Access Control) for SDK users. It's based on the Microsoft Learn's [RBAC overview](https://learn.microsoft.com/azure/role-based-access-control/overview) and [role assignment guide](https://learn.microsoft.com/azure/role-based-access-control/role-assignments-steps).

@aohanhongzhi can you please try adding a role assignment for your service principal? "Contributor" scoped to the resource group should suffice.

**Comment by aohanhongzhi** [comment]
> Judging by the error message, it appears what's missing here is assigning a role to the service principal allowing it to add resources to the resource group, such as the built-in "Contributor" role. We have [this document](https://aka.ms/azsdk/identity/AppRegistrationAndRoleAssignment#assign-azure-roles-using-the-azure-portal) describing RBAC (Role Based Access Control) for SDK users. It's based on the Microsoft Learn's [RBAC overview](https://learn.microsoft.com/azure/role-based-access-control/overview) and [role assignment guide](https://learn.microsoft.com/azure/role-based-access-control/role-assignments-steps).
> 
> @aohanhongzhi can you please try adding a role assignment for your service principal? "Contributor" scoped to the resource group should suffice.

thanks for your reply ,   I want to update `networkSecurityGroups` , But I didn't find any role which have the `'Microsoft.Network/networkSecurityGroups/write'` permission. so could you tell me which role have the permission.

![Snipaste_2024-07-23_16-56-44](https://github.com/user-attachments/assets/286027b6-5efb-4f1d-834d-e7c11aca5228)

all role（only 35） here:

![Snipaste_2024-07-24_09-28-22](https://github.com/user-attachments/assets/d29e369c-666d-40ab-ac06-b371b250e99f)


![Snipaste_2024-07-24_09-28-53](https://github.com/user-attachments/assets/b0610085-7553-40e9-98c6-60d886216fa9)

Is there any permission that hasn't been granted to me？

**Comment by chlowell** [comment]
The "Contributor" role I mentioned above is a "privileged administrator role" listed separately:

![image](https://github.com/user-attachments/assets/981e73cd-8fa3-4038-9362-2522ed5136b4)

The less privileged [Network Contributor](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles/networking#network-contributor) role should do as well, it has Microsoft.Network/* permissions.

If you can't find appropriate built-in roles, you can define a [custom role](https://learn.microsoft.com/azure/role-based-access-control/custom-roles).
