### ISSUE TITLE
Unexpected behaviour for pager returned for NewListBlobsHierarchyPager

### ISSUE THREAD

**Issue by Shahmeerm** [Azure/azure-sdk-for-go#23249]
### Bug Report

Import path of package: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
SDK Version: `1.2.1`
Go Version: `go1.21.11 darwin/arm64`

We were using the `pager` returned by `ServiceClient().NewContainerClient(params.containerName).NewListBlobsHierarchyPager({ /* params*/ })` and `pager.More()` method was return `true` even in cases when client credentials had no permissions to perform listing of blobs.

- What did you expect or want to happen?
As per the comment on `page.More()` method, it should have returned false in case there were no more pages to follow (Because client credentials had no sufficient permissions to ListBlobs)

- How can we reproduce it?
Providing code piece that you can test by providing any credentials which do not have `ListBlobs` permission. This would go into an infinite loop because `pager.More()` keeps return `true`
```
credential, err := azblob.NewSharedKeyCredential(<ACCOUNT_NAME>, <ACCOUNT_KEY>)
if err != nil {
	fmt.Println("Error getting the azure blob credential: ", err)
	return nil, err
}

client, err := azblob.NewClientWithSharedKeyCredential(<CONTAINER_URL>, credential, nil)
if err != nil {
	fmt.Println("Error getting the azure blob client: ", err)
	return nil, err
}

pSize := pageSize
prefix := "/"
client.ServiceClient().NewContainerClient(params.containerName).NewListBlobsHierarchyPager("/", &container.ListBlobsHierarchyOptions{
	MaxResults: &pSize,
	Prefix:     &params.prefix,
})

pageErrCount := 0
// pager.More() keeps returning `true` even when credentials have no permission to list blobs
for pager.More() {
	resp, errPage := pager.NextPage(ctx)
	if errPage != nil {
		fmt.Println("Error fetching next page: ", errPage)
		pageErrCount++
	}
}

fmt.Println("Total page errors: ", pageErrCount)
return nil, nil
```
- Anything we should know about your environment.
Nothing specific. All information provided should be enough

**Comment by tanyasethi-msft** [comment]
Hi @Shahmeerm , 
The issue arises because the checks happen when `pager.NextPage(ctx)` is called rather than `pager.More()`
So, in this case, errPage is getting the authorization error, but the code flow goes on, since there is no break inside. 
Next, the `pager.More()` again returns true, and the code goes in an infinite loop.
In your code, add a statement to break when the errPage is not nil. 

```
for pager.More() {
	resp, errPage := pager.NextPage(ctx)
	if errPage != nil {
		fmt.Println("Error fetching next page: ", errPage)
		pageErrCount++
                break
	}
}

```

**Comment by Shahmeerm** [comment]
@tanyasethi-msft Thank you for the response. 

We got this after all even before reporting the issue. However, `pager.More()` is not doing what the comment says in SDK.
```
// More returns true if there are more pages to retrieve.
func (p *Pager[T]) More() bool {
	if p.current != nil {
		return p.handler.More(*p.current)
	}
	return true
}
```
Shouldn't `pager.More()` return false in this case when the permissions to `ListBlob` is not even there.
More clarity is needed in the comment so the developers who are consuming the SDK are aware of a potential infinite loop.

**Comment by tanyasethi-msft** [comment]
The comment `More returns true if there are more pages to retrieve.` signifies that it will return `false` are no more pages to retrieve, and it doesn't do any other checks like authorization etc. 
Nevertheless, as per your feedback, we will improve the documentation provided.
