### ISSUE TITLE
[Azure Container Registry] Expose authenticationClient/authenticationPolicy in containerregistry package 

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-sdk-for-go#23253]
### Service Package Request

azure cloud provider team needs to migrate [credential provider](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/) to track2 client. Credential provider will exchange token for kubelet when kubelet try to fetch image from acr. 
acr token exchange logic has been implemented in authenticationClient. 
https://github.com/Azure/azure-sdk-for-go/blob/0eb9152a4b06ba5c01bb5f048f8ae839f0898bdb/sdk/containers/azcontainerregistry/authentication_client.go#L37-L55

I'm wondering if the client can be exposed to the public so that it can be reused. Thanks!

**Comment by jhendrixMSFT** [comment]
This is being tracked in https://github.com/Azure/azure-sdk-for-go/issues/20571

I believe there is a plan to expose, just uncertain when it will happen.

@tadelesh FYI
