### ISSUE TITLE
CosmosDB: Allow running queries without Partition Key

### ISSUE THREAD

**Issue by calmh** [Azure/azure-sdk-for-go#23304]
As per #18578 which was closed by a ridiculous auto-close policy.

<img width="775" alt="Screenshot 2024-08-09 at 20 52 31" src="https://github.com/user-attachments/assets/7a6c5c73-981e-47ec-bde9-edd3ed9cce06">

🙄

**Comment by Pilchie** [comment]
I see that @ealsur re-opened #18578, so lets continue to use that to track this.
