### ISSUE TITLE
ClientOptions.InsecureAllowCredentialWithHTTP is not actually used

### ISSUE THREAD

**Issue by jieliu2000** [Azure/azure-sdk-for-go#23313]
### Bug Report

There is a property "InsecureAllowCredentialWithHTTP" in policy.ClientOptions but it is not actually used. This is quite useful for unit testing. In my project I created a mock http server, but without this option, it simply returns error because my mock server is not HTTPS.

- The file that needs to be changes: `sdk/ai/azopenai/custom_client.go`
- SDK version: master
- go version: 1.22

I believe that we need to change both NewClientWithKeyCredential and NewClientForOpenAI in custom_client.go. When creating NewKeyCredentialPolicy we need to consider the values of  in InsecureAllowCredentialWithHTTP options

**Comment by richardpark-msft** [comment]
@jieliu2000, this has (just now) been released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai@v0.6.1

**Comment by jieliu2000** [comment]
@richardpark-msft , Thanks a lot for the quick fix.
