### ISSUE TITLE
AuthorizationFailure for azure storage sdk 

### ISSUE THREAD

**Issue by jdattatr-tibco** [Azure/azure-sdk-for-go#23312]
Is OAuth Client credentials supported by the sdk?

I have created service principal.To my storage account I added the role  to this principal  of Storage Account Contributor.

When I run my go app which creates a new directory in the share I get bellow error

RESPONSE 403: 403 This request is not authorized to perform this operation.
ERROR CODE: AuthorizationFailure

**Comment by RickWinter** [comment]
Can you share a snippet of code surrounding how you constructing the ManagedIdentity credential.
