### ISSUE TITLE
Auto-generated PR from Swagger getting closed

### ISSUE THREAD

**Issue by bearzz23** [Azure/azure-sdk-for-go#23327]
### Feature Request

Hello!

Our team has been making changes to Swagger API definitions (e.g. https://github.com/Azure/azure-rest-api-specs/pull/29148) which leads to PR to this Go SDK repository to be automatically created like this one: https://github.com/azure-sdk/azure-sdk-for-go/pull/10609, but all of them seem to be closed automatically after a while. 

What is the correct process for getting these PRs merged and the SDK updated? Sorry if this has already been mentioned in a section in the Contribution guide (I can help updating the guide if needed. )

**Comment by lirenhe** [comment]
For the PR about mgmt. plane in spec repo, we will create a SDK PR to verify whether we could still generate SDK from the modified spec and detect any breaking change in the SDK.   Those PRs are for review only without the need to merge them.  For SDK release, please create release request in release planner and Azure SDK team will handle it.

**Comment by lirenhe** [comment]
> Could this be part of why I find a lot of things are missing in this SDK and most files that I find missing features are auto generated with no clear indicator of what needs to be changed? For example #23323 that I opened yesterday.

@michaelschuett-tomtom, I am not fully understand your ask,  could you help to describe what you expected and what the actual behavior currently?

**Comment by bearzz23** [comment]
Makes sense! Will use the Release Planner to create a release plan. Thanks for your help!
