### ISSUE TITLE
The API mysqlflexibleservers:ListByResourceGroup of package(github.com/Azure/azure-sdk-for-go/profiles/latest/mysql/mgmt/mysqlflexibleservers) always return `PublicNetworkAccess` property value as `Enabled`

### ISSUE THREAD

**Issue by ParthaI** [Azure/azure-sdk-for-go#23320]
### Bug Report

- import path of package: `github.com/Azure/azure-sdk-for-go/profiles/latest/mysql/mgmt/mysqlflexibleservers`
- SDK version: `v68.0.0+incompatible`
   - GO package ref: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/profiles/latest/mysql/mgmt/mysqlflexibleservers
- output of `go version`: `go version go1.21.4 darwin/arm64`

- What happened?
    - I am attempting to use the [ListByResourceGroup](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/mysql/mgmt/2021-05-01/mysqlflexibleservers#ServersClient.ListByResourceGroup) API call from the [mysqlflexibleservers](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/profiles/latest/mysql/mgmt/mysqlflexibleservers#ServersClient) package.
    - This API returns an attribute called `PublicNetworkAccess` under the [Network](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/mysql/mgmt/2021-05-01/mysqlflexibleservers#Network) property.
    - However, the `PublicNetworkAccess` value we receive is always `Enabled`, regardless of whether it is actually enabled or disabled in the portal.
    - Additionally, I tried with the [Azure API Explorer](https://learn.microsoft.com/en-us/rest/api/mysql/flexibleserver/servers/list-by-resource-group?view=rest-mysql-flexibleserver-2023-12-30&tabs=HTTP#code-try-0), is returning the data as Expected.

- What did you expect or want to happen?
   -  I would like to obtain the correct value for the `PublicNetworkAccess` attribute.
- How can we reproduce it?
  -  Create MySQL Flexible server.
  - Disable public access on the MySQL Flexible server page in portal > Settings > Networking > Uncheck Allow public access to this resource through the internet using a public IP address.
  - Run the following standalone Go Code:
 ```go
package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/profiles/latest/mysql/mgmt/mysqlflexibleservers"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
	ctx := context.Background()

	clientID := "your-client-id"
	clientSecret := "your-client-secret"
	tenantID := "your-tenant-id"
	subscriptionID := "your-subscription-id"
	resourceGroup := "Your_RG"

	authorizer := auth.NewClientCredentialsConfig(clientID, clientSecret, tenantID)
	auth, err := authorizer.Authorizer()
	if err != nil {
		panic(err)
	}

	client := mysqlflexibleservers.NewServersClient(subscriptionID)
	client.Authorizer = auth
	result, err := client.ListByResourceGroup(ctx, resourceGroup)
	if err != nil {
		panic(err)
	}

	for _, server := range result.Values() {
		if server.ServerProperties != nil {
			if server.ServerProperties.Network != nil {
				fmt.Printf("ServerName: %s, Network Public Access: %s\n", *server.Name, server.Network.PublicNetworkAccess)
			}
		}
	}

}
```
   -  Result `ServerName: test53, Network Public Access: Enabled`

- Anything we should know about your environment.
   -  N/A

**Comment by ParthaI** [comment]
Thanks, @jhendrixMSFT, for the quick response. The [armmysqlflexibleservers/v2](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/mysql/armmysqlflexibleservers/v2) is working as expected. 👍

**Comment by jhendrixMSFT** [comment]
Thanks for confirming.
