### ISSUE TITLE
armoperationalinsights TablesClient does not support updating Table Plan

### ISSUE THREAD

**Issue by CWoodall2100** [Azure/azure-sdk-for-go#23345]
### Service Package Request

We are enabling Diagnostic settings on our AKS clusters and storing them in the Log Analytics Workspace in the resource specific tables _(AKSControlPlane and AKSAuditAdmin)_. 

The Azure Portal, CLI, and REST APIs support updating these tables from the default Analytics plan to the Basic plan, but the SDK does not. 

We are looking for these options to be available in the SDK to help reduce our costs by 80%

References: 

- https://learn.microsoft.com/en-us/rest/api/loganalytics/tables/update?view=rest-loganalytics-2023-09-01&tabs=Java#examples
- https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/operationalinsights/armoperationalinsights@v1.2.0#TableProperties

**Comment by Alancere** [comment]
Hi @CWoodall2100, please use https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/operationalinsights/armoperationalinsights/v2@v2.0.0-beta.4 try again.

**Comment by CWoodall2100** [comment]
@Alancere Thanks for the quick turnaround on this one! I have confirmed it does work now with these changes.

Any ETA on when the next official release for armoperationinsights will be?

**Comment by lirenhe** [comment]
> @Alancere Thanks for the quick turnaround on this one! I have confirmed it does work now with these changes.
> 
> Any ETA on when the next official release (non-beta) for armoperationinsights will be?

We don't have the information about their next official release.  Could you contact service team directly on this?

**Comment by CWoodall2100** [comment]
@lirenhe Could you point me to their contact information?

**Comment by lirenhe** [comment]
I think you could create a support ticket directly in https://support.microsoft.com/en-us/contactus

**Comment by jonathan-hurley** [comment]
`armoperationalinsights` hasn't had a release yet, so I am guessing this feature has not been released.
