### ISSUE TITLE
FIPS compliancy

### ISSUE THREAD

**Issue by pavolloffay** [Azure/azure-sdk-for-go#23354]
### Feature Request

Related to https://github.com/Azure/azure-sdk-for-go/issues/21047 

This library depends on x/crypto which does not have FIPS validated crypto algorithms:

```
./vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_certificate_credential.go:19:	"golang.org/x/crypto/pkcs12"

```

Not FIPS compliant: pkcs12.ToPEM() performs a MAC check operation, for which it uses getSafeContents(), which calls verifyMac(), which calls pbkdf(), which is implemented in x/crypto, and thus not FIPS validated.

References:
- pkcs12.ToPEM(): [https://cs.opensource.google/go/x/crypto/+/master:pkcs12/pkcs12.go;bpv=1;bpt=1;l=114](https://www.google.com/url?q=https://cs.opensource.google/go/x/crypto/%2B/master:pkcs12/pkcs12.go;bpv%3D1;bpt%3D1;l%3D114&sa=D&source=docs&ust=1724170458043417&usg=AOvVaw3KbkB5ZSHu67oZAj1he_86)
- getSafeContents(): [https://cs.opensource.google/go/x/crypto/+/master:pkcs12/pkcs12.go;l=284;drc=b2d3a6a4b4d36521cd7f653879cf6981e7c5c340](https://www.google.com/url?q=https://cs.opensource.google/go/x/crypto/%2B/master:pkcs12/pkcs12.go;l%3D284;drc%3Db2d3a6a4b4d36521cd7f653879cf6981e7c5c340&sa=D&source=docs&ust=1724170458043457&usg=AOvVaw1KT_MSJ1YYss3b2p08aert)
- verifyMac(): [https://cs.opensource.google/go/x/crypto/+/master:pkcs12/mac.go;drc=b2d3a6a4b4d36521cd7f653879cf6981e7c5c340;l=30](https://www.google.com/url?q=https://cs.opensource.google/go/x/crypto/%2B/master:pkcs12/mac.go;drc%3Db2d3a6a4b4d36521cd7f653879cf6981e7c5c340;l%3D30&sa=D&source=docs&ust=1724170458043480&usg=AOvVaw0hQQcexvVNAt_MzPXMKG9a)
- pbkdf(): [https://cs.opensource.google/go/x/crypto/+/master:pkcs12/pbkdf.go;drc=b2d3a6a4b4d36521cd7f653879cf6981e7c5c340;l=33](https://www.google.com/url?q=https://cs.opensource.google/go/x/crypto/%2B/master:pkcs12/pbkdf.go;drc%3Db2d3a6a4b4d36521cd7f653879cf6981e7c5c340;l%3D33&sa=D&source=docs&ust=1724170458043499&usg=AOvVaw0NwrITN3vjngCVRqhNswVC)

Would you accept a patch to fix this?

**Comment by jhendrixMSFT** [comment]
What would be the replacement for the current crypto module?

**Comment by pavolloffay** [comment]
I don't know exactly. I am not sure if there is an alternative in the main `crypto` package. If no then could we add a build tag to use the implementation from openssl?

**Comment by chlowell** [comment]
Only `azidentity.ParseCertificates` calls `pkcs12.ToPEM` (see [here](https://github.com/Azure/azure-sdk-for-go/blob/855748ac2e886dc1204cd377033086338a43fe80/sdk/azidentity/client_certificate_credential.go#L103)). This is a helper method for getting a cert and key to pass to [NewClientCertificateCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewClientCertificateCredential). That constructor takes the cert and key as types from the standard library's `crypto` module, so applications aren't required to call `ParseCertificates`. Is the `pkcs12.ToPEM` call a problem even if it's never executed?

**Comment by pavolloffay** [comment]
@chlowell I got this reply from our FIPS folks:

> Not FIPS compliant: pkcs12.ToPEM() performs a MAC check operation, for which it uses getSafeContents(), which calls verifyMac(), which calls pbkdf(), which is implemented in x/crypto, and thus not FIPS validated.

**Comment by chlowell** [comment]
Sure, that makes sense. What I want to understand is whether this is a static analysis or a runtime problem. Our cert authentication implementation doesn't require applications to call `pkcs12.ToPEM()`, so we have a straightforward workaround if your application can comply by simply not calling that function. But if the fact that the module contains a line invoking `pkcs12.ToPEM()` makes your application noncompliant even if it never executes that line, that's a hard problem 😄

**Comment by pavolloffay** [comment]
This is supposed to be a runtime problem. 

Are you saying that the app importing azure SDK will never  cause invoking `pkcs12.ToPEM()` at runtime?

**Comment by chlowell** [comment]
> Are you saying that the app importing azure SDK will never cause invoking `pkcs12.ToPEM()` at runtime?

Yes. `azidentity` invokes `pkcs12.ToPEM()` only when you call [azidentity.ParseCertificates](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ParseCertificates) with a PKCS#12 (PFX) cert. That function exists to help apps get the `[]*x509.Certificate` and `crypto.PrivateKey` for [azidentity.NewClientCertificateCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewClientCertificateCredential) but you don't have to use it, the constructor parameters are simple standard library types you can get however you like.

> This is supposed to be a runtime problem.

😅 Great! Then we have a couple straightforward workarounds:
- parse certs yourself i.e. don't call `azidentity.ParseCertificates`
- use only PEM format for certs

**Comment by pavolloffay** [comment]
This is great, thanks :)

Would it be possible to deprecate->remove `azidentity.ParseCertificates` so that we get rid of x/crypto import entirely from this package?

**Comment by jhendrixMSFT** [comment]
Removing it would be a breaking change and that bar is very high, so it seems unlikely.

**Comment by pavolloffay** [comment]
`azidentity.ParseCertificates` is also called from:
* `azidentity.NewEnvironmentCredential`
* `azidentity.NewDefaultAzureCredential`
* `azidentity.NewOnBehalfOfCredentialWithCertificate`

**Comment by chlowell** [comment]
You're quite right, `NewEnvironmentCredential` and `NewDefaultAzureCredential` call `ParseCertificates` when `AZURE_CLIENT_CERTIFICATE_PATH` is set, because they must parse the specified file. "Parse certs yourself" is still the best guidance: when you need to authenticate with a cert, parse it in your own code and call a constructor that takes `[]*x509.Certificate` and `crypto.PrivateKey` i.e., [NewClientCertificateCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewClientCertificateCredential) or [NewOnBehalfOfCredentialWithCertificate](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewOnBehalfOfCredentialWithCertificate).
