### ISSUE TITLE
Manage the MaxIntegratedCacheStaleness via the SDK

### ISSUE THREAD

**Issue by AndrewRPorter** [Azure/azure-sdk-for-go#23368]
### Feature Request

It does not look like we are able to set the `MaxIntegratedCacheStaleness` in the Go SDK like we can in the Dotnet SDK for example per https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-integrated-cache?tabs=dotnet#adjust-maxintegratedcachestaleness.

It looks like most SDKs have a `DedicatedGatewayRequestOptions.MaxIntegratedCacheStaleness` as part of the `QueryOptions`. Can we add support for such options in the Go SDK?

-------

I would be more than happy to offer an outside contribution for this if that is acceptable as well.

**Comment by AndrewRPorter** [comment]
Hey @Pilchie 👋🏻, I am happy to help implement this if this is a feature the Go SDK should have.

**Comment by Pilchie** [comment]
> Hey @Pilchie 👋🏻, I am happy to help implement this if this is a feature the Go SDK should have.

That would be awesome @AndrewRPorter. Go right ahead!

**Comment by AndrewRPorter** [comment]
Closing this now as support has been added and should be included in the next `azcosmos` release.
