### ISSUE TITLE
Prepare the repo to support tsp-client

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-go#23364]
tsp-client is the way we generated Azure TypeSpec SDK. It requires an initial setup on the repo, which is quite simple, but need knowledge from Go people :)

You just need to have this file, but with the go dependency:
https://github.com/Azure/azure-sdk-for-python/blob/main/eng/emitter-package.json

You may also commit the lock file as necessary:
https://github.com/Azure/azure-sdk-for-python/blob/main/eng/emitter-package-lock.json

**Comment by lirenhe** [comment]
We already have the above files.
https://github.com/Azure/azure-sdk-for-go/blob/main/eng/emitter-package.json
https://github.com/Azure/azure-sdk-for-go/blob/main/eng/emitter-package-lock.json

Please let me know if there are any other ask to support tsp-client.
