### ISSUE TITLE
Add Configuration For AzureGerman Cloud

### ISSUE THREAD

**Issue by mahadzaryab1** [Azure/azure-sdk-for-go#23371]
### Feature Request

According to the documentation on https://learn.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-cli, it looks like there's an option `AzureGermanCloud` but no configuration is present at https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/cloud/cloud.go#L9-L22. Can this configuration be added here?

**Comment by mahadzaryab1** [comment]
I'd be happy to open a PR for this if someone can point me to the correct AD host for Germany.

**Comment by jhendrixMSFT** [comment]
The Azure German cloud has closed. See https://learn.microsoft.com/previous-versions/azure/germany/germany-welcome for more info.

Duplicate of https://github.com/Azure/azure-sdk-for-go/issues/20293
