### ISSUE TITLE
Enhancement: combine event hub in-memory and blob checkpointing feature

### ISSUE THREAD

**Issue by ifeify** [Azure/azure-sdk-for-go#23370]
### Feature Request

This is regarding the checkpointing feature in the Event Hub Go client. I'm wondering if we can combine the benefits of in-memory checkpoints and persistent checkpointing to blob storage. Persisting to blob storage on _every_ checkpoint has resulted in slower performance for my team's application (which requires low-latency processing of telemetry). In-memory persistence, on the other hand, means data will be lost when the application dies or restarts. 

I propose adding an option to only persist to blob storage after a time interval or after a certain number of checkpoints.

**Comment by richardpark-msft** [comment]
> I propose adding an option to only persist to blob storage after a time interval or after a certain number of checkpoints.

We've generally left this pattern up to the application writer. Generally your app wants full visibility when you bypass certain areas of safety.

Now, your application is in full control of when UpdateCheckpoint is called, so if you want to do a "only write after 'x' time" style pattern it's a simple update to wrap the update with your own logic:

```go
if time.Since(lastCheckpointTime) > arbitraryDuration {
	if err := partitionClient.UpdateCheckpoint(context.TODO(), events[len(events)-1], nil); err != nil {
		return err
	}

	lastCheckpointTime = time.Now()
}
```

The compromise, as you mention, is whether you're okay with possibly reprocessing events if you lose a processor instance and have to start again.

Closing as we're not going to add this to the SDK at this time.
