### ISSUE TITLE
feedback on azidentity/cache

### ISSUE THREAD

**Issue by weinong** [Azure/azure-sdk-for-go#23388]
1. Why does `Authenticate()` method take `*policy.TokenRequestOptions` when `GetToken()` takes `opts policy.TokenRequestOptions`?
2. Does `TokenRequestOption` have to be the same between `Authenticate()` and `GetToken()`? Using `nil` seems to work just fine with `Authenticate()`. Does it really matter?
3. If I want the cache to be isolated by the user, am I supposed to use `AuthenticationRecord.HomeAccountID` to create the cache?

**Comment by chlowell** [comment]
Thanks for trying out persistent caching. I intend to ship a stable version of it this quarter, so please share any feedback you have soon ☺️ 

> 1. Why does `Authenticate()` method take `*policy.TokenRequestOptions` when `GetToken()` takes `opts policy.TokenRequestOptions`?

The pointer is intended to express that `TokenRequestOptions` is truly optional for `Authenticate()`. Callers don't need to set any of its fields. However, `GetToken()` requires `TokenRequestOptions.Scopes` (I would agree it should therefore be a parameter, but it's too late to make that change).

> 2. Does `TokenRequestOption` have to be the same between `Authenticate()` and `GetToken()`? Using `nil` seems to work just fine with `Authenticate()`. Does it really matter?

It probably doesn't matter to most applications. There are reasons to set `TokenRequestOptions` fields for `Authenticate()` though:
- running in a private cloud (must specify `Scopes`)
- to prevent a subsequent `GetToken()` call from sending a request
    - `Authenticate()` acquires an access token for ARM in the user's home tenant by default. Set `Scopes` to request a token for a difference audience and/or `TenantID` to acquire a token from a different tenant
 
> 3. If I want the cache to be isolated by the user, am I supposed to use `AuthenticationRecord.HomeAccountID` to create the cache?

The [`Name` option](AuthenticationRecord) is the only isolation mechanism. Caches are partitioned by OS user. Is that what you want, or do you mean that you want to partition the cache by Entra user?
