### ISSUE TITLE
[azopenaiassistants] CreateMessage support for multi content

### ISSUE THREAD

**Issue by wesleymds** [Azure/azure-sdk-for-go#23399]
### Feature Request

Hi, it seems that it's currently not possible to create a thread message with multiple types of content, like images. Is there a plan to implement this feature? I only found a way to do it using ChatCompletion.

**Comment by richardpark-msft** [comment]
@wesleymds, I don't have a release date on that, but I note that support for it is in our codegen source so it is coming:

https://github.com/Azure/azure-rest-api-specs/blob/71f4640e8af8f4d186039368ef7be05c3140f59a/specification/ai/OpenAI.Assistants/messages/models.tsp#L80

**Comment by wesleymds** [comment]
Thank you for the reply @richardpark-msft.
