### ISSUE TITLE
unmarshalling JSON error: network.NewUsagesClient returns float64 instead of int64

### ISSUE THREAD

**Issue by mblaschke** [Azure/azure-sdk-for-go#2340]
### Bug Report

```
networkClient := network.NewUsagesClient(*subscription.SubscriptionID)
networkClient.Authorizer = AzureAuthorizer
for _, location := range locationGroupArray {
    _, _ := networkClient.List(context, location)
}
```

results in following error:
```
panic: network.UsagesClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number 8.0 into Go struct field Usage.currentValue of type int64' JSON = '{
  "value": [
    {
      "currentValue": 8.0,
      "id": "/subscriptions/xxxxxxxxxxxxx/providers/Microsoft.Network/locations/westeurope/usages/VirtualNetworks",
      "limit": 50.0,
      "name": {
        "localizedValue": "Virtual Networks",
        "value": "VirtualNetworks"
      },
      "unit": "Count"
    },
```

Might be a duplicate from #906 but it's still not working. When will this be fixed? The definition is still using int64 😞

**Comment by jhendrixMSFT** [comment]
It looks like a bug in the swagger as it's been defined as int64.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-06-01/usage.json#L111
The ```limit``` field also has the same problem.
I've opened issue https://github.com/Azure/azure-rest-api-specs/issues/3537 to track fixing the swagger.

**Comment by jhendrixMSFT** [comment]
@mblaschke finally heard back from the service team, they're working on a fix now.

**Comment by vladbarosan** [comment]
Closing as it is tracked in  Azure/azure-rest-api-specs#2366
