### ISSUE TITLE
azcore.ResponseError fails to marshal

### ISSUE THREAD

**Issue by KStillings-Slalom** [Azure/azure-sdk-for-go#23454]
### Bug Report

When trying to marshal the azcore.ResponseError into a data object, an unsupportedType occurs.
If we null out the azcore.ResponseError.RawResponse.Request object, the error marshals out as expected.

It appears this might be related to [21838](https://github.com/Azure/azure-sdk-for-go/issues/21838) and [22147](https://github.com/Azure/azure-sdk-for-go/issues/22147)

It would be nice to be able to marshal this out as well so we can return a full error context back to the client.

**Comment by jhendrixMSFT** [comment]
The safest thing for us to do is omit the `RawResponse` field from marshaling. It's lossy though, so calling `Error()` on the unmarshaled instance won't contain full info. This shouldn't be a problem as that output is not contractual (only `ErrorCode` and `StatusCode` are), but I'd like to know a bit more about your scenario.

**Comment by jhendrixMSFT** [comment]
Fix will be in upcoming `v1.14.1` release.
