### ISSUE TITLE
Fakes support in azblob

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-sdk-for-go#23476]
### Feature Request

As pointed out in issue #16613, there wasn't a timeline for the fakes support in azblob packages. Wonder what's the status now before I commit to go down the mock interfaces path.

Thanks.

**Comment by Karpantoja** [comment]
Filtraciones

**Comment by vibhansa-msft** [comment]
We do not have this on our priority list for now as we are occupied with other backlog items and feature asks. Have added this to our backlog along with other low priority items.
