### ISSUE TITLE
Incorrect code on Get Started Website

### ISSUE THREAD

**Issue by aryanmehrotra** [Azure/azure-sdk-for-go#23488]
Hey, I am not sure if this is the right place to report but - code to start receiving from eventhub is wrong @ https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-go-get-started-send

**Option param missing**

```
if err := partitionClient.UpdateCheckpoint(context.TODO(), events[len(events)-1]); err != nil {
```

Should be 

```
if err := partitionClient.UpdateCheckpoint(context.TODO(), events[len(events)-1], nil); err != nil {
				return err
			}
```

**Comment by richardpark-msft** [comment]
Created https://github.com/MicrosoftDocs/azure-docs/pull/124673/. 

There were some other little housekeeping things to do as well so there are some small updates in there.
