### ISSUE TITLE
[Automation] RunbookDraftClient.ReplaceContentPreparer sending content as JSON

### ISSUE THREAD

**Issue by hbuckle** [Azure/azure-sdk-for-go#2350]
### Bug Report

* import path of package in question - `.../services/automation/mgmt/2015-10-31/automation`
* SDK version - `19.1.0`
* output of `go version` - `go1.10.2 windows/amd64`

When updating a runbook draft with ReplaceContent the body is being sent as JSON, so line breaks and double quotes are not correctly passed:

```
PUT https://management.azure.com/subscriptions/xxx/resourceGroups/testytest/providers/Microsoft.Automation/automationAccounts/testytest/runbooks/testy/draft/content?api-version=2015-10-31 HTTP/1.1
Host: management.azure.com
Content-Length: 95
Authorization: Bearer xxx
Content-Type: text/powershell
Accept-Encoding: gzip

"# Comment\r\nWrite-Output \"testing\"\r\nWrite-Output \"more testing\""
```

Changing [`autorest.WithJSON`](https://github.com/Azure/azure-sdk-for-go/blob/4e8cbbfb1aeab140cd0fa97fd16b64ee18c3ca6a/services/automation/mgmt/2015-10-31/automation/runbookdraft.go#L325) to `autorest.WithString` resolves the issue:

```
PUT https://management.azure.com/subscriptions/xxx/resourceGroups/testytest/providers/Microsoft.Automation/automationAccounts/testytest/runbooks/testy/draft/content?api-version=2015-10-31 HTTP/1.1
Host: management.azure.com
Content-Length: 85
Authorization: Bearer xxx
Content-Type: text/powershell
Accept-Encoding: gzip

# Comment
Write-Output "testing"
Write-Output "more testing"
```

**Comment by jhendrixMSFT** [comment]
This was fixed in the swagger unfortunately it didn't get merged in time for the v19 release.  The fix is already checked into the ```latest``` branch and will get rolled out in v20 since it's a breaking change.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v20.0.0
