### ISSUE TITLE
[azblob]  container Client.FilterBlobs returns error is the query contains a space character

### ISSUE THREAD

**Issue by ryepup** [Azure/azure-sdk-for-go#23546]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container`
- SDK version: `1.4.1`
- `go version`: `1.21.2`

- What happened?

Tried to use [`container/Client.FilterBlobs`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v1.4.1/container#Client.FilterBlobs) with the following query: `"deploymentID"='id' AND "sha256hash"='hash'`

This returned a 400:

- RESPONSE 400: 400 Error parsing query at or near character position 20: unexpected '1'
- ERROR CODE: InvalidQueryParameterValue

```xml
<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>InvalidQueryParameterValue</Code>
    <Message>Error parsing query at or near character position 20: unexpected &apos;1&apos;
        RequestId:4f294f5a-001e-0005-4e90-16410a000000
        Time:2024-10-04T19:08:44.6743253Z</Message>
    <QueryParameterName>where</QueryParameterName>
    <QueryParameterValue>
        &quot;sha256hash&quot;=&apos;hash&apos;+AND+&quot;deploymentID&quot;=&apos;id&apos;</QueryParameterValue>
    <Reason>This query parameter value is invalid.</Reason>
</Error>
```

- What did you expect or want to happen?

To get back a list of blobs with matching tags.

- How can we reproduce it?

Call `FilterBlobs` with a query containing spaces anywhere: `"test"='I have a space'` will also do it

```go
cred, err := azidentity.NewDefaultAzureCredential(nil)
client, err := container.NewClient("MY STORAGE URL", cred, nil)
resp, err := client.FilterBlobs(ctx, `"sha256hash"='hash' AND "deploymentID"='id'`, nil)
```
Looks like the same issue as #17421, which was fixed for another client in #19742

- Anything we should know about your environment.

No

**Comment by ryepup** [comment]
We did find a workaround using the fixed [`service.Client.FilterBlobs`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v1.4.1/service#Client.FilterBlobs) from #19742

```go
cred, err := azidentity.NewDefaultAzureCredential(nil)
client, err := azblob.NewClient("MY STORAGE URL", cred, nil)
resp, err := client.ServiceClient().FilterBlobs(ctx, `@container='MY CONTAINER NAME' AND "sha256hash"='hash' AND "deploymentID"='id'`, nil)
```

**Comment by tanyasethi-msft** [comment]
Thanks for reporting this. This is identified as a bug and a fix will be available in our next release. We will update here accordingly.

**Comment by tanyasethi-msft** [comment]
Hi @ryepup , Next release is scheduled in Jan 2nd week of 2025.
