### ISSUE TITLE
Azure SDK for Go: Get Method in armhybridcompute.MachinesClient Fails to Parse Machine Extensions

### ISSUE THREAD

**Issue by netaza** [Azure/azure-sdk-for-go#23552]
In the latest version of the Azure SDK for Go (azure-sdk-for-go/sdk/resourcemanager/hybridcompute/armhybridcompute), the Get request in machines_client.go does not return the machine extensions (always nil).

Although the extensions are included in the response from the API, the SDK is not correctly parsing them into the return value. This causes a discrepancy between the API response and the SDK output, preventing users from accessing machine extension data via the SDK.

**Comment by lirenhe** [comment]
As 'the extensions are included in the response from the API', this does not seem to be a service issue.  @netaza, could you share some sample code that could repo this problem?  thanks
