### ISSUE TITLE
Data race in azblob client

### ISSUE THREAD

**Issue by muroj** [Azure/azure-sdk-for-go#23677]
#### Environment Info

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container`
- `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.4.1`
- `go version go1.23.2 darwin/arm64`

My program is detecting a data race while enumerating containers and blobs in parallel.  Here is a minimal snippet demonstrating my approach. 

```golang
client, err := azblob.NewClient(url, credential, nil)
ctrPager := client.NewListContainersPager(nil)

for ctrPager.More() {
  resp, err := ctrPager.NextPage(context.TODO())

  for _, c := range resp.ContainerItems {

    // limit blob enumeration, some containers have millions of blobs
    ctx, cancel := context.WithTimeout(context.Background(), time.Second*60)
    defer cancel()

    go func(c *service.ContainerItem) {
      blobPager := client.NewListBlobsFlatPager(*c.Name, nil)
      for blobPgr.More() {
        
      var blobs container.ListBlobsFlatResponse
        result := make(chan struct{})

        go func() {
          blobs, err = blobPgr.NextPage(ctx)
          handleError(err)
          result <- struct{}{}
        }()

        select {
        case <-ctx.Done():
          fmt.Printf("context cancelled while processing blobs for container: %s, %v\n", *c.Name, ctx.Err())
        case <-result:
          doStuff()
        }
      }
    }(c)
  }
}
```

Running this program results in the following data race, which occurs in the [Blob  Pager](https://github.com/Azure/azure-sdk-for-go/blob/47b7a8a545174788f2bc750fdebda9bf4eb1e0ae/sdk/storage/azblob/container/client.go#L283).

```
WARNING: DATA RACE
Write at 0x00c0001f4358 by goroutine 106:
  github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container.(*Client).NewListBlobsFlatPager.func2()
      /Users/jmuro/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.4.1/container/client.go:283 +0x8c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*Pager[go.shape.struct { github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated.ListBlobsFlatSegmentResponse; ClientRequestID *string; ContentType *string; Date *time.Time; RequestID *string; Version *string }]).NextPage()
      /Users/jmuro/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.14.0/runtime/pager.go:79 +0x5b4
  main.getContainerStats.func1()
      /Users/jmuro/acme/ops/util/azure/storage/utils/azure_storage_stats.go:168 +0x84

Previous write at 0x00c0001f4358 by goroutine 104:
  github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container.(*Client).NewListBlobsFlatPager.func2()
      /Users/jmuro/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.4.1/container/client.go:283 +0x8c
  github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*Pager[go.shape.struct { github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated.ListBlobsFlatSegmentResponse; ClientRequestID *string; ContentType *string; Date *time.Time; RequestID *string; Version *string }]).NextPage()
      /Users/jmuro/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.14.0/runtime/pager.go:79 +0x5b4
  main.getContainerStats.func1()
      /Users/jmuro/acme/ops/util/azure/storage/utils/azure_storage_stats.go:168 +0x84
```

I am new to go routines, contexts, and channels, so I wouldn't be surprised if my code is buggy. Regardless, I'd like confirmation on whether the azure go SDK is thread safe. In particular, is it safe to share the clients between go routines? [This go sdk design doc](https://azure.github.io/azure-sdk/golang_introduction.html#client-immutability) implies that clients _should be_ threadsafe, but is that the case?  The .[NET SDK doc explicitly mentions thread safety](https://learn.microsoft.com/en-us/dotnet/azure/sdk/thread-safety), but the go SDK doc does not.

**Comment by jhendrixMSFT** [comment]
Hello!

You are correct that SDK clients are goroutine safe. However, `Pager[T]` and `Poller[T]` types returned from SDK methods are not. In your example, the following is not goroutine safe.
```go
        go func() {
          blobs, err = blobPgr.NextPage(ctx)
          handleError(err)
          result <- struct{}{}
        }()
```
Here, it's possible for multiple goroutines to call `NextPage()` on the same `blobPgr` instance which is not goroutine safe.

Please ping back if you have further questions.

**Comment by jhendrixMSFT** [comment]
It appears this wasn't doc'ed. I've added doc comments about this in https://github.com/Azure/azure-sdk-for-go/pull/23679
