### ISSUE TITLE
A 'v2.0' being appended to tenant ID during authentication

### ISSUE THREAD

**Issue by Benjababe** [Azure/azure-sdk-for-go#23699]
### Bug Report
```
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.8.0
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.4.1

go version go1.22.2 windows/amd64
```

Sample code:
```go
azCred, err := azidentity.NewDefaultAzureCredential(nil)
if err != nil {
	return err
}

serviceURL := utils.Env("AZURE_STORAGE_SERVICE_ADDRESS").(string)
if serviceURL == "" {
	serviceURL = "https://fail.blob.core.windows.net/"
}
azBlobClient, err = azblob.NewClient(serviceURL, azCred, nil)
if err != nil {
	return err
}

_, err = azBlobClient.CreateContainer(context.Background(), "test-container", nil)
if err != nil {
	println(err.Error())
	return err
}
```

I'm receiving this error with the Blob Storage SDK since the past hour, It was working fine yesterday.

```
DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
	ClientSecretCredential authentication failed. 
		GET https://login.microsoftonline.com/xxxxxxxx-de26-4ebd-be02-cbe43432e9bev2.0/.well-known/openid-configuration
		--------------------------------------------------------------------------------
		RESPONSE 400: 400 Bad Request
		--------------------------------------------------------------------------------
		{
		  "error": "invalid_tenant",
		  "error_description": "AADSTS90002: Tenant 'xxxxxxxx-de26-4ebd-be02-cbe43432e9bev2.0' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant. Trace ID: ffa2ec51-1d36-4fd9-897a-871f790a7c00 Correlation ID: f57f4acb-0bca-431d-995e-422f10e6a8ad Timestamp: 2024-11-06 09:04:35Z",
		  "error_codes": [
		    90002
		  ],
		  "timestamp": "2024-11-06 09:04:35Z",
		  "trace_id": "ffa2ec51-1d36-4fd9-897a-871f790a7c00",
		  "correlation_id": "f57f4acb-0bca-431d-995e-422f10e6a8ad",
		  "error_uri": "https://login.microsoftonline.com/error?code=90002"
		}
		--------------------------------------------------------------------------------
		To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#client-secret
```

Though I'm pretty sure `AZURE_TENANT_ID` is set properly in my environment variables.

![Image](https://github.com/user-attachments/assets/4410a602-4751-42ef-8543-102f90435c01)

The `https://login.microsoftonline.com/xxxxxxxx-de26-4ebd-be02-cbe43432e9bev2.0/.well-known/openid-configuration` URL doesn't work but if I remove the `v2.0` at the end of the tenant ID, it returns what I assume is the expected response.

![Image](https://github.com/user-attachments/assets/d9da6e3b-22e5-4d45-931a-997baaec10e7)

Does anyone know what could be causing this issue? Thanks a ton!

**Comment by chlowell** [comment]
This appears to be a regression in `github.com/AzureAD/microsoft-authentication-library-for-go` v1.3.0, released yesterday. Please comment if your application uses a different version. If you're on v1.3.0, please try reverting to v1.2.3

**Comment by MKrkkl** [comment]
I have been facing this during today as well with workload identity in pod running in aks cluster. 

` WARN: ChainedTokenCredential: failed to acquire a token. Attempted credentials: AzureCLICredential: fork/exec /bin/sh: no such file or directory ManagedIdentityCredential: failed to authenticate a system assigned identity. The endpoint responded with {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"} DefaultAzureCredential: failed to acquire a token. Attempted credentials: EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set WorkloadIdentityCredential authentication failed. GET https://login.microsoftonline.com/111111-22222-4444-9999-888888888v2.0/.well-known/openid-configuration -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request -------------------------------------------------------------------------------- { "error": "invalid_tenant", "error_description": "AADSTS90002: Tenant '111111-22222-4444-9999-888888888v2.0' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.  ....., "error_uri": "https://login.microsoftonline.com/error?code=90002" } -------------------------------------------------------------------------------- To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#workload
 WARN:  ChainedTokenCredential: failed to acquire a token. Attempted credentials: AzureCLICredential: fork/exec /bin/sh: no such file or directory ManagedIdentityCredential: failed to authenticate a system assigned identity. The endpoint responded with {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"} DefaultAzureCredential: failed to acquire a token. Attempted credentials: EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set WorkloadIdentityCredential authentication failed. GET https://login.microsoftonline.com/111111-22222-4444-9999-888888888v2.0/.well-known/openid-configuration -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request -------------------------------------------------------------------------------- { "error": "invalid_tenant", "error_description": "AADSTS90002: Tenant '111111-22222-4444-9999-888888888v2.0' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant. ....., "error_uri": "https://login.microsoftonline.com/error?code=90002" } -------------------------------------------------------------------------------- To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#workload
`

I will try to downgrade azidentity...

**Comment by chlowell** [comment]
This was caused by a bug in `github.com/AzureAD/microsoft-authentication-library-for-go` v1.3.0 which has now been fixed with v1.3.1. So you can solve this issue by upgrading that module.

If you're authenticating via ADFS, wait for v1.3.2 or pin v1.2.3; v.1.3.1 has another bug affecting ADFS clients

**Comment by MKrkkl** [comment]
I was just about to comment that dowgrading auth lib helps, but now I can just update the package. Thank you @chlowell

**Comment by Benjababe** [comment]
Upgrading to v1.3.0 managed to make it work for me. Thanks so much @chlowell !
