### ISSUE TITLE
Add Mock Test To Verify CAE Support in Mgmt SDK

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-go#23751]
## Description

On par with #23481 , we need to add a mock test case to verify mgmt SDK can support CAE.

**Comment by tadelesh** [comment]
it the original CAE support pr, we have already added mock unit tests for CAE support: https://github.com/Azure/azure-sdk-for-go/blob/40c4586ea84f7609e31cb09067e027d94f760f92/sdk/azcore/runtime/policy_bearer_token_test.go#L361
