### ISSUE TITLE
On certain query failures, we don't receive an error from the Go client

### ISSUE THREAD

**Issue by avivka** [Azure/azure-sdk-for-go#23812]
### Bug Report

- azure-kusto-go : `sdk/resourcemanager/kusto/armkusto`
- go version: `1.23.0`
- SDK version: `v1.0.0-preview-5` (which seems to be the latest)

- What happened?
On certain query failures, we don't receive an error from the Go client (azure-kusto-go). For example, when running `(c *Client) Mgmt`, we get an error if the query fails due to a `429 Too Many Requests` response, but we don’t get one if it fails due to `UpdatePolicy_FailedDescendantTransaction`.
Do you know what could cause this?

- What did you expect or want to happen?
We expect that in the relevant case, `UpdatePolicy_FailedDescendantTransaction` will fail on `429 Too Many Requests` as well
- How can we reproduce it?
Run `(c *Client) Mgmt` on azure kusto for go's client

**Comment by jhendrixMSFT** [comment]
Hello! This looks to be an issue with the [Kusto SDK](https://github.com/Azure/azure-kusto-go). Can you please move this issue to their repo? It's owned by a separate team.

CC @sandeep-sen

**Comment by sandeep-sen** [comment]
I don't have the permission to transfer this issue to https://github.com/Azure/azure-kusto-go 
@yogilad and @AsafMah could you please transfer this issue to your repo.

**Comment by avivka** [comment]
Thanks all for the prompt response and connections, I've opened a new bug report at what seems to be the right repo, thanks(:
https://github.com/Azure/azure-kusto-go/issues/271
