### ISSUE TITLE
Include ShareSizeLimitReached error code in fileerrors

### ISSUE THREAD

**Issue by wonwuakpa-msft** [Azure/azure-sdk-for-go#23833]
### Feature Request

Can the ShareSizeLimitReached error code be included in https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azfile/fileerror/error_codes.go 
This is stemming from a now [closed customer reported bug in AzCopy](https://github.com/Azure/azure-storage-azcopy/issues/2685#issuecomment-2520878551)

@vibhansa-msft

**Comment by vibhansa-msft** [comment]
@tanyasethi-msft this particular error code shall be included in azfile/fileerror/error_codes.go but I don't see this error code in auto generated code as well (azfile/internal/generated/zz_constants.go). Is this missing from swagger file itself?
