### ISSUE TITLE
File/Directory Clients Use BlobClient Instead of generatedFileClientWithDFS

### ISSUE THREAD

**Issue by Bharat-Goyal** [Azure/azure-sdk-for-go#23841]
### Feature Request

- `github.com/Azure/azure-sdk-for-go/sdk/storage/azdatalake`
- v 1.3.0
- go 1.22 

What happened?
-The File uses the `blobClient()` instead of the `generatedFileClientWithDFS()` even though there are equivalent methods in the internal `PathClient` 
	- [GetProperties](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azdatalake/v1.3.0/sdk/storage/azdatalake/file/client.go#L236)
	- [SetMetadata](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azdatalake/v1.3.0/sdk/storage/azdatalake/file/client.go#L353)
	- [DownloadStream](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azdatalake/v1.3.0/sdk/storage/azdatalake/file/client.go#L557)

What did you expect or want to happen?
- If there is a `ClientWithDFS` that exists, the code should use that instead of the blobClient.
- Use case: a restricted networking space that allows only `.dfs.core.` endpoints if hierarchical namespace is enabled.

**Comment by Bharat-Goyal** [comment]
Alternatively if you allow the use of the `internal` packages (I only need the generated internal path client) I can extend the existing clients in my own codebase with these changes.

**Comment by Bharat-Goyal** [comment]
I have a similar request for the Lease Path Client, it exclusively uses the blob endpoint which results in the same issue for me. Is there any reason why that is the case because the generated internal package's `PathClient` has a `Lease` method that achieves the same functionality. 

Side question: is there a strong reason for not allowing the import of the `internal.generated` package? It seems like that code is far more similar to the older versions of the sdk like `Azure/azure-sdk-for-go/services/storage/datalake/2018-11-09/storagedatalake`

**Comment by Bharat-Goyal** [comment]
Actually, backing up first, could you maybe give more context on why the methods I've linked above and the Lease Path Client always only use the blob endpoint? It seems a little confusing that some requests default to the blob endpoint while others use the hierarchical namespace endpoint.

**Comment by vibhansa-msft** [comment]
Blob endpoint and DFS endpoints are not compatible in a way that a file created using DFS endpoint can not be edited/modified using blob endpoint. To maintain the compatibility across tools and applications all Azure Storage SDKs use blob endpoint for all file upload/download cases. Only DFS specific operations like GetAccessControl / SetAccessControl etc are over DFS endpoint.
