### ISSUE TITLE
How to generate an UserDelegationKey using a custom RequestID (x-ms-client-request-id)

### ISSUE THREAD

**Issue by ioria90** [Azure/azure-sdk-for-go#23846]
Hi,

I'm trying to create an UserDelegationCredential and I would like to use the RequestId (x-ms-client-request-id Header in Get User Delegation Key Rest API) but I cannot find a way.

I saw that GetUserDelegationCredential in the service/client.go has the possibility to specify GetUserDelegationCredentialOptions but this type is empty and also the implementation of format() method return nil.

Instead, generated.ServiceClientGetUserDelegationKeyOptions has RequestID and Timeoutbut I cannot find a way to specify them when using GetUserDelegationCredential.

What I'm doing wrong?

**Comment by tanyasethi-msft** [comment]
Thanks @ioria90 , This seems to be a bug, We will be fixing it in the next release in January 2025.

**Comment by tanyasethi-msft** [comment]
Hi @ioria90, on discussing within the team, this seems to be a design choice to not yet the user specify a custom request id since we do this for the users in the pipeline.

**Comment by ioria90** [comment]
Hi @tanyasethi-msft , thank you for the reply. I’m just confused on how I should implement the flow for using a custom request-id, because  I need it to check only the logs the request made on the services. How can I do it with the ask? Should I use the pipeline then? 
Thank you.
