### ISSUE TITLE
`ResourceExistsError` mentioned in documentation, but does not exist in code

### ISSUE THREAD

**Issue by maxburke** [Azure/azure-sdk-for-go#23875]
### Bug Report

Import path: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
SDK version: azblob@1.5.0
go version: `go version go1.22.5 darwin/arm64`

Looking at the documentation for `Client.CreateContainer` (https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#Client.CreateContainer), which I found linked off of https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-go?tabs=roles-azure-portal, I noticed that the Client.CreateContainer function mentions a `ResourceExistsError`:

> CreateContainer is a lifecycle method to creates a new container under the specified account. If the container with the same name already exists, a ResourceExistsError will be raised. This method returns a client with which to interact with the newly created container.

But this `ResourceExistsError` isn't defined anywhere within the azure-sdk-for-go.

Where is this error defined? Or is the documentation wrong?

**Comment by tanyasethi-msft** [comment]
Hey @maxburke This seems like a bug in documentation - We have updated the document. The "ContainerAlreadyExists" error is correct in this case.
