### ISSUE TITLE
Incomplete Data in Azure SubAssessments

### ISSUE THREAD

**Issue by bbernays** [Azure/azure-sdk-for-go#23887]
### Bug Report

- import path of package in question, e.g. `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity`
- SDK version e.g. `v0.14.0`
- output of `go version`

The `armsecurity.SubAssessment` struct is missing lots of data that is included in the response from the API. One example of the data missing is according to the docs `properties.resourceDetails` can be  [AzureResourceDetails](https://learn.microsoft.com/en-us/rest/api/defenderforcloud/sub-assessments/list?view=rest-defenderforcloud-2019-01-01-preview&tabs=HTTP#azureresourcedetails), [OnPremiseResourceDetails](https://learn.microsoft.com/en-us/rest/api/defenderforcloud/sub-assessments/list?view=rest-defenderforcloud-2019-01-01-preview&tabs=HTTP#onpremiseresourcedetails) or [OnPremiseSqlResourceDetails](https://learn.microsoft.com/en-us/rest/api/defenderforcloud/sub-assessments/list?view=rest-defenderforcloud-2019-01-01-preview&tabs=HTTP#onpremisesqlresourcedetails)

While in the Go SDK only ever returns `Source` in the `ResourceDetails` struct

**Comment by tadelesh** [comment]
the struct you mentioned is used in the `properties.resourceDetails` which is a polymorphic type. you need use specific way to get that property. one example:
```go
pager := clientFactory.NewSubAssessmentsClient().NewListAllPager("subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23", nil)
for pager.More() {
	page, err := pager.NextPage(ctx)
	if err != nil {
		log.Fatalf("failed to advance page: %v", err)
	}
	for _, v := range page.Value {
		switch *v.Properties.ResourceDetails.GetResourceDetails().Source {
			case armsecurity.SourceAzure:
				detail := v.Properties.ResourceDetails.(*armsecurity.AzureResourceDetails)
				log.Println(*detail.ID)
			case armsecurity.SourceOnPremise:
				detail := v.Properties.ResourceDetails.(*armsecurity.OnPremiseResourceDetails)
				log.Println(*detail.MachineName)
			case armsecurity.SourceOnPremiseSQL:
				detail := v.Properties.ResourceDetails.(*armsecurity.OnPremiseSQLResourceDetails)
				log.Println(*detail.DatabaseName)
		}
	}
}
```

**Comment by bbernays** [comment]
Thank you very much! This has resolved my question
