### ISSUE TITLE
ContactsClientAPI.ListComplete returns an unmarshal error

### ISSUE THREAD

**Issue by amass01** [Azure/azure-sdk-for-go#23883]
Hi,

We are using the sdk to retrieve security contacts and we are hitting an un-marshal error

- import path of package in question: `"github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/v3.0/security/securityapi"`
- SDK version:
```
❯ go list -m github.com/Azure/azure-sdk-for-go         
github.com/Azure/azure-sdk-for-go v68.0.0+incompatible
```
-  `go version go1.23.3 darwin/arm64`

- What happened?
`ContactsClientAPI.ListComplete` return an unmarshal error:
```
security.ContactsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal array into Go value of type security.ContactList'
```

- What did you expect or want to happen?
Receive the contacts list ))

- How can we reproduce it?
Call `ContactsClientAPI.ListComplete`

Thanks!

**Comment by jhendrixMSFT** [comment]
This is from the legacy SDK which is no longer supported (all packages under `github.com/Azure/azure-sdk-for-go/services` are legacy packages).

The latest security client SDK can be found [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity). Can you please migrate and see if it resolves your issue?

Please see the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md) for common questions/answers on migration.

**Comment by amass01** [comment]
thanks for the quick reply, will let you know how it goes after migration!

**Comment by tadelesh** [comment]
@jliusan please follow up after customer's migration.

**Comment by amass01** [comment]
@tadelesh @jliusan migrated to the new API and we are still hitting an unmarshal error:

```
unmarshalling type *armsecurity.ContactList: unmarshalling type *armsecurity.ContactList: json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```

**Comment by jliusan** [comment]
@amass01 could you turn on logging by setting environment variable AZURE_SDK_GO_LOGGING to all and configure policy.LogOption to print the body of this call? Please help to show the detail  info in the raw response.

https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-guideline.md#logging

**Comment by amass01** [comment]
```
[Dec 23 16:07:59.417325] Response: ==> REQUEST/RESPONSE (Try=1/2.951570625s, OpTime=2.951620584s) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/XXX/providers/Microsoft.Security/securityContacts?api-version=2020-01-01-preview
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armsecurity/v0.12.0 (go1.23.3; darwin)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Api-Supported-Versions: REDACTED
   Cache-Control: no-cache
   Content-Length: 456
   Content-Type: application/json; charset=utf-8
   Date: Mon, 23 Dec 2024 14:07:59 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   X-Cache: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: REDACTED
   X-Ms-Request-Id: 94fd56ac-71f6-4062-b858-432cb88e8c23
   X-Ms-Routing-Request-Id: REDACTED
   X-Msedge-Ref: REDACTED
   --------------------------------------------------------------------------------
[{"properties":{"alertNotifications":{"state":"On","minimalSeverity":"High"},"notificationsByRole":{"state":"On","roles":["AccountAdmin","ServiceAdmin"]},"emails":"XXX","phone":"XXXXX"},"id":"XXXXX","name":"default","type":"Microsoft.Security/securityContacts","etag":"\"XXXXX\"","location":"West Europe"}]
   --------------------------------------------------------------------------------

[Dec 23 16:07:59.417378] Retry: response 200
[Dec 23 16:07:59.417411] Retry: exit due to non-retriable status code
```

**Comment by jliusan** [comment]
@amass01 please upgrade to the latest version https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity@v0.14.0

**Comment by amass01** [comment]
that worked, thank u!!!
