### ISSUE TITLE
ARM Support for SQL

### ISSUE THREAD

**Issue by andrewduch** [Azure/azure-sdk-for-go#239]
Looking forward to future iterations of the auto-generated ARM packages. In the current version, I don't see SQL present anywhere. Are there plans to generate an ARM package for SQL? There are some ARM-only commands I'm looking to take advantage of.

Thanks!

**Comment by akromm** [comment]
I have started working on the spec.  I will try to get it done soon, but I'm not sure how long it will take with other obligations I have.

**Comment by devigned** [comment]
:+1: @akromm you are awesome!

**Comment by brendandburns** [comment]
@ahmetalpbalkan looks like this is now present:

https://github.com/Azure/azure-sdk-for-go/tree/master/arm/sql

Should we close this issue?

**Comment by ahmetalpbalkan** [comment]
@brendandburns sounds about right.
