### ISSUE TITLE
Move OData filter params into their own struct param

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#2414]
### Feature Request

E.g. swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/consumption/resource-manager/Microsoft.Consumption/stable/2018-03-31/consumption.json#L42
E.g. codegen https://github.com/Azure/azure-sdk-for-go/blob/master/services/consumption/mgmt/2018-03-31/consumption/usagedetails.go#L58

We should group OData params into their own struct; this would provide resilience against breaking changes (e.g. adding a new OData param) and would add convenience when you don't want to specify any OData params.

**Comment by jhendrixMSFT** [comment]
Somewhat related to https://github.com/Azure/azure-sdk-for-go/issues/1716 however we should group OData filter params separately from other optional params.

**Comment by RickWinter** [comment]
This has been done in track2 and will NOT be backported to track1
