### ISSUE TITLE
Mistyped LoadBalancer::OutNatRule struct field/typo.

### ISSUE THREAD

**Issue by aznashwan** [Azure/azure-sdk-for-go#243]
The issue is concerning [this](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/network/models.go#L1189) line of code.

Either there is a plural typo in the fields name or the respective field should have been an `*[]int`.

[Sorry for the barebones issue report; I have not had the opportunity to read the API specs yet and thus cannot say which of the above it really is...]

**Comment by brendandixon** [comment]
@aznashwan Good catch! The problem, however, is in the underlying Swagger from which we generated the ARM packages. I believe this line -- https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json#L5343 -- is needs correcting.

Would you mind filing an issue against it?

**Comment by aznashwan** [comment]
@brendandixon: thanks a lot for pointing that out. I've taken the liberty of creating a [PR](https://github.com/Azure/azure-rest-api-specs/pull/80) on the issue (which will at the very least raise awareness in case it's approach is flawed).

Thanks again!

**Comment by brendandixon** [comment]
@aznashwan Thanks!

**Comment by aznashwan** [comment]
@brendandixon: thanks again for pointing out the problem so precisely; the fix has gotten in for a while now; but the sdk hasn't been updated yet.

Were you guys planning a re-gen of the arm packages soon anyhow or should I just submit a quick manual patch myself?

**Comment by brendandburns** [comment]
@brendandixon I believe that the name is actually correct.  The [documentation in the swagger](https://github.com/Azure/azure-rest-api-specs/tree/master/arm-network/2016-06-01#L6019) says: "Gets or sets the number of outbound ports to be used for SNAT"

So having this be plural is correct.  If that is true, I think we can close this issue.

**Comment by brendandixon** [comment]
@brendandburns Let's close then.
