### ISSUE TITLE
List action documentation implies a return of complete results rather than the first page [nit]

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#245]
From https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/network#RoutesClient.List:

>List the List network security rule operation retrieves all the routes in a route table.

But it doesn't retrieve all the routes. It returns the first page and then one can use `ListNextResults` to get the subsequent page(s). Also, the generated sentence doesn't really parse in English correctly.

The confusion worsens when one sees the `ListAll` and reads the description:

>ListAll the list NetworkSecurityGroups returns all network security groups in a subscription

But it also doesn't "return all", but rather the first page and then one is expected to use `ListAllNextResults` to page through the results.

It's minor and I'm not sure there's a better naming scheme, but it has just made me go "Wait, what?" a couple times when consuming the package for the first time. At the very least we could clean up the doc comments from the generator.

**Comment by brendandixon** [comment]
@colemickens All of this derives from the Swagger. File a PR against the ARM Network Swagger files (https://github.com/Azure/azure-rest-api-specs/tree/master/arm-network).

**Comment by colemickens** [comment]
Makes sense. I'll file an issue over there. Thanks.
