### ISSUE TITLE
VMSS wait for update errors out w/o any info

### ISSUE THREAD

**Issue by kargakis** [Azure/azure-sdk-for-go#2466]
I set a script with invalid size in cse.ProtectedSettings of a VMSS and get back an empty error in the client instead of a useful error message hinting that my update was invalid.
```
FATA[0065] cannot wait for VMSS "ss-master" update: Code="" Message=""
```

Relevant code (vmss includes the updated value):
```go
        res, err := u.ssc.CreateOrUpdate(context.Background(), u.ResourceGroup, u.Name, vmss)
	if err != nil {
		return vmss, fmt.Errorf("cannot update VMSS %q: %v", u.Name, err)
	}
	if err := res.WaitForCompletion(context.Background(), u.ssc.BaseClient.Client); err != nil {
		return vmss, fmt.Errorf("cannot wait for VMSS %q update: %v", u.Name, err)
	}
	if vmss, err = res.Result(u.ssc); err != nil {
		return vmss, fmt.Errorf("error during VMSS %q update: %v", u.Name, err)
	}
```

**Comment by kargakis** [comment]
When adding [debug logs in azure requests and responses](https://github.com/Azure/azure-sdk-for-go/blob/master/README.md#inspecting-and-debugging) I see that the VMSS switches to Updating provisioning state and then Failed/

**Comment by kargakis** [comment]
FWIW the issue with the VMSS upgrade failing was that the size of the script was higher than the upper limit.

**Comment by jhendrixMSFT** [comment]
@kargakis thanks for the additional info.  By chance do you have the JSON response body from the error case?  What I'd like to know is if the service returned an error and the SDK failed to parse it.

**Comment by vladbarosan** [comment]
Closing this as stale. @kargakis if you have any updates provide them please.
