### ISSUE TITLE
calling GroupsClient.List using $filter fails with InvalidFilterInQueryString

### ISSUE THREAD

**Issue by TheoBrigitte** [Azure/azure-sdk-for-go#2480]
### Bug Report

* import path: `github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-02-01/resources`
* SDK version: `v19.1.0` (commit `4e8cbbfb1aeab140cd0fa97fd16b64ee18c3ca6a`)
* go version: `go version go1.10.3 darwin/amd64`

* What happened?

Calling `GroupsClient.List(ctx, "name eq 'foo'", nil)`  fails with
```
resources.GroupsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidFilterInQueryString" Message="Invalid $filter 'name eq 'foo'' specified in the query string."
```

* What did you expect or want to happen?

I would expect to get a list of resource group who's name are equal to `foo`.

According to the documentation found here: https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#filter-parameter

`name eq 'foo'` is a valid filter

* How can we reproduce it?

I used this program https://gist.github.com/TheoBrigitte/9d1fadca91c69c337f6ff467599db848

* Anything we should know about your environment.

- none -

**Comment by jhendrixMSFT** [comment]
@chidmdxx what is the proper syntax here?  The [REST API docs](https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/list) for this don't have any examples.

**Comment by TheoBrigitte** [comment]
There are some filter examples under [`insights.ActivityLogsClient.List`](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights#ActivityLogsClient.List)

e.g.
```go
filter := "eventTimestamp le '2014-07-20T04:36:37.6407898Z' and resourceGroupName eq 'resourceGroupName"
```

**Comment by jhendrixMSFT** [comment]
@TheoBrigitte Unfortunately that syntax doesn't work for [resources.GroupsClient.List](https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2018-02-01/resources/groups.go#L423).  I tried updating the filter to ```resourceGroupName eq 'foo'``` but I still get a ```InvalidFilterInQueryString``` error.

**Comment by jhendrixMSFT** [comment]
Per an offline conversation with @chidmdxx the [resources.GroupsClient.List](https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2018-02-01/resources/groups.go#L423) operation supports filtering on tags only.  I've opened issue https://github.com/Azure/azure-rest-api-specs/issues/3853 to track getting the docs updated with this info.  Sorry for the confusion.
