### ISSUE TITLE
Automation GetContent functions wrongly use ByUnmarshallingJSON

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-sdk-for-go#2486]
### Bug Report

* import path of package - `.../services/automation/mgmt/2015-10-31/automation`
* SDK version - `18.0.0`
* output of `go version` - go version go1.10.3 windows/amd6

* What happened?
Trying to make use of ```GetContent``` from ```dscconfiguration```. The api call will return just a string and not a json body. ```GetContentResponder``` however is trying to [Unmarshal](https://github.com/Azure/azure-sdk-for-go/blob/master/services/automation/mgmt/2015-10-31/automation/dscconfiguration.go#L356) a json object resulting in an error.

>automation.DscConfigurationClient#GetContent: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'invalid character 'c'
looking for beginning of value' JSON = 'configuration bla {}'

* What did you expect or want to happen?
Just return the string, do not attempt to unmarshal as it is not a json object that is returned

* How can we reproduce it?
Call the GetContent function.

**Comment by jhendrixMSFT** [comment]
I believe this is a problem with the swagger as the return type specified is [string](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/dscConfiguration.json#L306), needs confirmation.

**Comment by vladbarosan** [comment]
Investigating, it might be an issue with the generator. If so will have a fix in the next sdk release.

**Comment by vladbarosan** [comment]
@bgelens out of curiosity are you receiving any content type header ?

**Comment by bgelens** [comment]
@vladbarosan I get ```text/powershell``` as content type

**Comment by bgelens** [comment]
Just fyi, with [runbookdraft](https://github.com/Azure/azure-sdk-for-go/blob/master/services/automation/mgmt/2015-10-31/automation/runbookdraft.go#L190) and [runbook](https://github.com/Azure/azure-sdk-for-go/blob/master/services/automation/mgmt/2015-10-31/automation/runbook.go#L363) there is no unmarshaling happening. The content type there is text/powershell as well.

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v20.0.0

**Comment by bgelens** [comment]
Awesome! Thanks 👍
