### ISSUE TITLE
DiagnosticsProfile field is missing in VirtualMachineScaleSetVMProfile on 2016-03-30 version

### ISSUE THREAD

**Issue by marinsalinas** [Azure/azure-sdk-for-go#2495]
### Bug Report

* import path of package in question. `.../services/compute/mgmt/2016-03-30/compute/models.go#L3498`
* SDK version `latest`, `master`
* output of `go version go1.10.1 darwin/amd64`

* What happened?
Trying to set the DiagnosticProfile field to CreateOrUpdate Request for VMScaleSet and this field does not exist.
* What did you expect or want to happen?
I would be able to set DiagnosticProfile field on VirtualMachineScaleSetVMProfile as the documentation describes https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#virtualmachinescalesetvmprofile

* How can we reproduce it?
Trying to set this field.
* Anything we should know about your environment.
No

**Comment by vladbarosan** [comment]
Hi @marinsalinas . The API version you mentioned is not exposing the Diagnostics Profile property. This would be first available in the [2017-03-30 API Version](https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2017-03-30/compute/models.go#L6696). 

Note that the latest API version from Compute is [2018-06-01](https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2018-06-01/compute/models.go) and also the property is exposed there.

**Comment by vladbarosan** [comment]
P
