### ISSUE TITLE
AKS update flow broken in 2018-03-31

### ISSUE THREAD

**Issue by JackQuincy** [Azure/azure-sdk-for-go#2502]
### Bug Report

* import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`../services/containerservice/mgmt./2018-03-31/`

* SDK version e.g. `master`, `latest`, `18.1.0`
    * Specify the exact commit if possible; one way to get this is the REVISION
      column output by `dep status "github.com/Azure/azure-sdk-for-go`.
`master`

* output of `go version`
irrelevant

* What happened?
Got this error trying to update AKS cluster with a  new count with the sdk
E0816 11:39:58.321092       1 azure_container_service_pool.go:193] Failed to update AKS cluster (%q): %vmi-platform-qa-akscontainerservice.ManagedClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterProperties.AadProfile.ServerAppSecret constraint=Null value=(*string)(nil) details: value can not be null; required parameter

* What did you expect or want to happen?
the sdk to pass the request to the service and the cluster to scale
* How can we reproduce it?
Enable RBAC + AAD and then try to update the cluster using a normal pattern of get, update model, put. The service nils out this field as it is a secret, just like with service principal secret and this should not be enforced. We can just depend on the service to return the right error.
* Anything we should know about your environment.
Nothing special here.

caused by this rule
https://github.com/Azure/azure-sdk-for-go/blob/520918e6c8e8e1064154f51d13e02fad92b287b8/services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go#L79
normal update path of  Get, update, Put will not have this set. This will be validated in service and shouldn't be validated in the client.

**Comment by vladbarosan** [comment]
@JackQuincy the PUT operation is supposed to be idempotent and the swagger defines the property as required, so everything is correct here.

If you want server side validation ( and not client validation) then you should have the operation in the spec as not required ( although preferably to have the validation as early as possible ).

**Comment by feiskyer** [comment]
@vladbarosan This doesn't seem right. See user's report here: https://github.com/kubernetes/autoscaler/issues/1105#issuecomment-413518236

```sh
containerservice.ManagedClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterProperties.AadProfile.ServerAppSecret constraint=Null value=(*string)(nil) details: value can not be null; required parameter
```

**Comment by vladbarosan** [comment]
@feiskyer I had a look, still not sure what is incorrect in what I mentioned. 
Also is the autoscale feature in that api verison ? there is a PR for adding a preview api version which seems to contain the auto scale feature https://github.com/Azure/azure-rest-api-specs/pull/3620

**Comment by vladbarosan** [comment]
To mention if the desire is to update an existing resource a PATCH operation should be implemented by the service

**Comment by feiskyer** [comment]
@vladbarosan Shouldn't `CreateOrUpdate` be treated as a patch on API server? e.g. if some parameters are not provided, what will do in api server?

> Also is the autoscale feature in that api verison ? there is a PR for adding a preview api version which seems to contain the auto scale feature Azure/azure-rest-api-specs#3620

That is based on cluster-autoscaler, and makes CA much more easier to setup.

**Comment by vladbarosan** [comment]
@feiskyer  not sure what you mean. The call is a PUT operation that has to be idempotent, i.e. having the resource being created before or not should be irrelevant. Also the property in question in the specs is marked as required. If that can be optional then you can make it optional and the SDK wont validate it but in that case Create needs to work without it.

Otherwise if you want PATCH semantic a PATCH operation needs to be implemented and added to the specs.

**Comment by JackQuincy** [comment]
This is a bug in our swagger. we need to update it to behave like the service principle profile
