### ISSUE TITLE
GroupsClient.ListComplete only returns first 100 results

### ISSUE THREAD

**Issue by tiwood** [Azure/azure-sdk-for-go#2525]
### Bug Report

Package: github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac
SDK version: latest
Go version: go version go1.10.3 darwin/amd64

I had the assumption GroupsClient/ListComplete should return all Azure AD group objects, but instead it just return the first 100.

In the following loop I only had access to the first 100 objects:
```go
resp, err := client.ListComplete(context, "")
for _, v := range *resp.Response().Value {}
```

**Comment by vladbarosan** [comment]
Hi @tiwood the `ListComplete` is a convenience call we have that returns an iterator. The iterator will go across pages automatically when using it compared to the List call. 

You can see an example in our samples repo:  https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/resources/groups.go#L98

**Comment by fiunchinho** [comment]
will the `List` function return all elements? or do I need to always use `ListComplete` and iterate if I need the full list?
