### ISSUE TITLE
Mysql Service api should return database password information

### ISSUE THREAD

**Issue by olblak** [Azure/azure-sdk-for-go#2535]
### Feature Request
When we use a tool like Terraform to manage mysql services, it's not possible at the moment to detect if the database password was changed via another way than the api, it would be interesting to return such informations. cfr. the azure terraform provder issue [Azure Terraform Provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1823) for a context

**Comment by vladbarosan** [comment]
@olblak thanks for opening this. I followed the issue you mentioned. To be clear the ask here is not for the password itself, but for some metadata about it ( e.g. last time changed etc) ?
