### ISSUE TITLE
Add Azure Container Instances Secured Environment Variables

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-sdk-for-go#2544]
### Feature Request

Add Azure Container Instances Secured Environment Variables to the Azure GO SDK. 

It seems like perhaps the current SDK (2018-06-01) was generated before the ACI secured environment variables were merged into the REST spec.

[Azure REST spec for container instances environment variables](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2018-06-01/containerInstance.json#L1132)

[ACI Environment variable spec from the Azure GO SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerinstance/mgmt/2018-06-01/containerinstance/models.go#L520)

Thanks

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v20.0.0.

**Comment by neilpeterson** [comment]
@jhendrixMSFT thanks a bunch.
