### ISSUE TITLE
Generate the rest of the Authorization clients

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#255]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json

That swagger spec references actions relating to role assignments. I don't see equivalent generated code in this project.

Where can I see what swaggers were consumed when generating this sdk? Where does the build script for this repo live since the arm packages are autogenerated?

**Comment by brendandixon** [comment]
@colemickens The version used to generate the code is defined in the rake file accompanying the Autorest branch of my fork (https://github.com/brendandixon/autorest/blob/beta-gosdk/AutoRest/Generators/Go/rakefile.rb). That file says version  2015-01-01 was used to generate the code.

**Comment by colemickens** [comment]
This was resolved with #258.
