### ISSUE TITLE
Client Testing

### ISSUE THREAD

**Issue by flyinprogrammer** [Azure/azure-sdk-for-go#2556]
### Feature Request

At this point in maturity, there are a series of clients that we should expect to always exist  in this project. Would there be value in testing that these clients always exist, and support some basic functionality?

For example, https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/212, where the `compute.DisksClient` was removed from the 2018-06-01 compute API.

It seems like the samples project would be a good source of basic functionality to always test for before releasing.

**Comment by jhendrixMSFT** [comment]
We can look into having a branch of the samples that targets the ```latest``` profile so it always targets the latest API version.
