### ISSUE TITLE
DNSZone Client

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#260]
According to the [docs](https://msdn.microsoft.com/en-us/library/mt130622.aspx) for creating or updating a zone, the request body should be:

```
{
  "location": "global",
  "tags": {},
  "properties": { }
}
```

The go-sdk has changed this as follows:

```
client := meta.(*ArmClient)
	dnsZonesClient := client.dnsZonesClient

	log.Printf("[INFO] preparing arguments for Azure ARM DNS Zone creation.")

	name := "mytestzone"
	location := "global"
	resGroup := d.Get("resource_group_name").(string)

	zone := dns.Zone{
		Location:   &location,
		Properties: &dns.ZoneProperties{},
	}

	zoneParams := dns.ZoneCreateOrUpdateParameters{
		Zone: &zone,
	}

	resp, err := dnsZonesClient.CreateOrUpdate(resGroup, name, zoneParams, "", "*")
	if err != nil {
		return err
	}
```

This makes the request look as follows:

```
{
	"Zone": {
		"location": "global",
		"properties": {}
	}
}
```

This throws an error as follows:

```
{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Could not find member 'Zone' on object of type 'ResourceDefinition'. Path 'Zone', line 1, position 8.'."}}
```

This feels like the `CreateOrUpdate` func is incorrect **OR** the docs are incorrect

Thoughts?

Paul

**Comment by brendandixon** [comment]
The DNS Swagger (see https://github.com/Azure/azure-rest-api-specs/blob/master/arm-dns/2015-05-04-preview/swagger/dns.json#L383 and https://github.com/Azure/azure-rest-api-specs/blob/master/arm-dns/2015-05-04-preview/swagger/dns.json#L894) disagrees with the documentation. Please file a Github issue against the Swagger and I'll poke around internally.

Thank you raising this issue.

**Comment by stack72** [comment]
Hi @brendandixon

Thanks for the response. Even if the docs are wrong, by following the code in the SDK, the request returns an error. What should the actual request struct look like?

Thanks

Paul

**Comment by brendandixon** [comment]
@stack72 My guess is that the documentation is correct and the SDK is wrong (meaning, the underlying Swagger is wrong). I forwarded the issue to someone on the ARM DNS team. They should respond with better guidance.

**Comment by stack72** [comment]
Hi @brendandixon, is there any update on this? It is currently a blocking feature for me right now

thanks

Paul

**Comment by brendandixon** [comment]
@stack72 Let me check on this. There was internal chatter and I had asked folks to respond here. It seems they've not yet had the chance. Thanks for the "ping."

**Comment by brendandixon** [comment]
@stack72 I just updated the arm/dns package (see #266). The changes *should* address your problem. Please let us know otherwise. Thank you.

**Comment by stack72** [comment]
@brendandixon thanks so much for pushing this out. I have gotten further:

```
{
	"error": {
		"code": "NoRegisteredProviderFound",
		"message": "No registered resource provider found for location 'global' and API version '2015-11-01' for type 'dnszones'. The supported api-versions are '2015-05-04-preview'. The supported locations are ', global'."
	}
}
```

**Comment by brendandixon** [comment]
@stack72 Odd. Those values come from the Swagger as well. Sigh. Let me look into this.

**Comment by stack72** [comment]
Thanks @brendandixon - fwiw, I see this from [another commit](https://github.com/Azure/azure-sdk-for-go/commit/897283e274c7d21bee11ea1f9d695a76e71b8e02):

```
+The ARM packages now align with the following API versions (*highlighted* packages are new or
 +updated in this release):
 +
 +- *arm/authorization 2015-07-01*
 +- *arm/cdn 2015-06-01*
 +- arm/compute 2015-06-15
 +- arm/dns 2015-05-04-preview
 +- *arm/intune 2015-01-14-preview*
 +- arm/logic 2015-02-01-preview
 +- *arm/network 2015-06-15*
 +- *arm/notificationhubs 2014-09-01*
 +- arm/redis 2015-08-01
 +- *arm/resources/authorization 2015-01-01*
 +- *arm/resources/features 2014-08-01-preview*
 +- *arm/resources/resources 2014-04-01-preview*
 +- *arm/resources/subscriptions 2014-04-01-preview*
 +- *arm/scheduler 2016-01-01*
 +- arm/storage 2015-06-15
 +- arm/web 2015-08-01
 +
```

So DNS *should* be `2015-05-04-preview`

When I changed it locally, I got a much more friendly error :)

```
{
	"code": "BadRequest",
	"message": "The zone name 'acceptancetestdnszone1' does not have enough labels. Required two or more."
}
```

This means it will then work when we change that const

thanks for all the work here

Paul

**Comment by brendandixon** [comment]
@stack72 Yes, but the DNS Swagger contains this:

```json
  "swagger": "2.0",
  "info": {
    "title": "DnsManagementClient",
    "description": "Client for managing DNS zones and record.",
    "version": "2015-11-01"
  },
  "host": "management.azure.com",
  "schemes": [
    "https"
  ],
```

Notice the incorrect version. That is the bug. Sigh.

**Comment by stack72** [comment]
got it - thanks for finding the issue!

**Comment by stack72** [comment]
@ahmetalpbalkan or @brendandixon the DNS API version has been updated - any chance the sdk can be regenerated now? This will unblock a lot of my DNS based work :)

**Comment by brendandixon** [comment]
@stack72 Got it. We have a couple of other changes we'd like to get in at the same time. For example, we will no longer vendor packages we rely on, we're additional factory methods, we're improving errors, and so forth. Could you give us a day or so?

**Comment by stack72** [comment]
@brendandixon this upcoming release sounds great. Thanks for letting me know.

**Comment by brendandixon** [comment]
@stack72 We pushed the change. Could please let us know if the issue is now addressed. Thanks!

**Comment by stack72** [comment]
Looks like the issue is address - thanks @brendandixon
