### ISSUE TITLE
Update Microsoft.Network /NetworkInterface Tag property fails

### ISSUE THREAD

**Issue by rezamt** [Azure/azure-sdk-for-go#2608]
### Bug Report

* import `"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources"`
* SDK version `master`
* `go version  go1.10.3 darwin/amd64`

I am trying to update the resource (Microsoft.Network/networkInterfaces) Tags and getting the following error:

resources.Client#UpdateByID: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="OnlyTagsSupportedForPatch" Message="PATCH request content includes properties property. Only tags property is currently supported." Details=[]

Here are more detail about the API version:    "Microsoft.Network":    "2018-07-01"

```
       resourceID := "/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/rg-demo-resourcegroup/providers/Microsoft.Network/networkInterfaces/vmint01"       

        genericResource := resources.GenericResource{
		Tags:  <TAGS>,
	}

_, err := resourcesClient.UpdateByID(context.Background(), resourceID, genericResource)

```

**Comment by jhendrixMSFT** [comment]
This looks to be a codegen bug, working on a fix.

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v22.1.1.
