### ISSUE TITLE
Virtual Network Gateway

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#261]
there are differences between the SDK and the documentation for the virtual network gateway. Currently, the [docs](https://msdn.microsoft.com/en-us/library/mt130667.aspx) suggest that we pass the following style of request to the API:

```
{
    "name": "myvirtualgateway1",
    "location": "West US",
    "tags": {
        "key1": "value1"
    },
    "properties": {
        "gatewayType": "DynamicRouting",
        "gatewaySize": "Default",
        "bgpEnabled": True,
        "vpnClientAddressPool": ["{vpnClientAddressPoolPrefix}"],
        "defaultSites": ["mysite1"]
    }
}
```
1. Documentation suggests that GatewayType should be `StaticRouting` or `DynamicRouting`. When looking at the SDK, all I can see for GatewayType is as follows:

`network.VirtualNetworkGatewayType`

this is an Enum for `ExpressRoute` or `Vpn`. So the values in the docs wouldn't line up with any of those Enum values
1. The documentation says that the gatewaySize is a string. When using the SDK, I cannot see that:

```
type VirtualNetworkGatewayPropertiesFormat struct {
    IPConfigurations       *[]VirtualNetworkGatewayIPConfiguration `json:"ipConfigurations,omitempty"`
    GatewayType            VirtualNetworkGatewayType               `json:"gatewayType,omitempty"`
    VpnType                VpnType                                 `json:"vpnType,omitempty"`
    EnableBgp              *bool                                   `json:"enableBgp,omitempty"`
    GatewayDefaultSite     *SubResource                            `json:"gatewayDefaultSite,omitempty"`
    Sku                    *VirtualNetworkGatewaySku               `json:"sku,omitempty"`
    VpnClientConfiguration *VpnClientConfiguration                 `json:"vpnClientConfiguration,omitempty"`
    ResourceGUID           *string                                 `json:"resourceGuid,omitempty"`
    ProvisioningState      *string                                 `json:"provisioningState,omitempty"`
}
```

the size is not in the SDK to send as part of the request
1. The docs also say that the Default Site is a string but the SDK suggests that the `GatewayDefaultSite` is a SubResource. What is it a SubResource of?
2. The docs suggest that the `vpnClientAddressPool` is a string for a single address. Whereas the SDK requires me to construct the following:

```
vpnConfiguration := network.VpnClientConfiguration{
        VpnClientAddressPool: &network.AddressSpace{},
    }
```

Where AddressSpace is a *[]string. Which is the correct source of truth?

So to summarise, the only part of the resource that aligns between docs and SDK is `enable_bgp` (which is a bool), `name` (string) and `location` (string)

Paul

**Comment by brendandixon** [comment]
@stack72 Paul -- Unfortunately, all the variances you've described exist in the underlying Swagger (see https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json). The ARM Network service did change their API from version 2015-05-01-preview to 2015-06-15. Is it possible that the documentation you've found is for the prior version?

Why don't you poke around on the documentation and I'll poke around internally a bit.

**Comment by vishrutshah** [comment]
Closing this one as it has been inactive for a while. Feel free to reopen if you find any issues. Thanks!

**Comment by stack72** [comment]
@vishrutshah so is this fixed? From what I can tell it's Inactive as no one has updated the documentation

**Comment by vishrutshah** [comment]
@stack72 Thanks for getting back. No I am not 100% sure whether documentation has been fixed or not. If you think it's not i'll reopen it. Thanks!

@eduardkoller Could you please follow up internally to find out what are the action items. 

cc:
@jhendrixMSFT @mcardosos

**Comment by marstr** [comment]
Howdy @stack72, I'm going to transfer this issue over to [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs). As @brendandixon pointed out, this is an issue stemming from the Swagger file and will be impacting all AutoRest generated Azure SDKs.

Once I've transferred the issue, I'll close out this one.
