### ISSUE TITLE
Allow auth.NewAuthorizerFromEnvironment() to pick up Azure CLI credentials

### ISSUE THREAD

**Issue by nphmuller** [Azure/azure-sdk-for-go#2610]
### Feature Request

If we want to use to Azure Go SDK for developer tooling, the user has to jump through some hoops to get authenticated:
- When using `auth.NewAuthorizerFromEnvironment()` there are multiple environment variables that have to be set manually.
- When using `auth.NewAuthorizerFromFile()` the user has to first explicitly create a set of credentials and create an environment variable pointing to the file that contains the credentials.

If we compare this with AWS it's much easier: You simply run `aws configure` which saves your credentials to `~/.aws/credentials`. All tooling can look for this file and use the credentials in this file to call the AWS API.

This command looks a lot like `az login` from the Azure CLI. It would be great if the following could be accomplished:
- The developer simply runs `az login`.
- `auth.NewAuthorizerFromEnvironment()` (or perhaps a new `auth.NewAuthorizerFromCli()`) now automatically uses the credentials set by Azure CLI as an authorizer.

Take for example a look at this project: https://github.com/mozilla/sops
It's way more complicated for a developer to configure [Azure KeyVault](https://github.com/mozilla/sops#encrypting-using-azure-key-vault) than it is to configure [AWS KMS](https://github.com/mozilla/sops#2usage).

**Comment by nphmuller** [comment]
The Azure SDK for .NET has implemented this in their [AppAuthentication](https://github.com/Azure/azure-sdk-for-net/tree/cad93fea6a56879c88172492023a2fca595279ba/src/SdkCommon/AppAuthentication) package. Specifically the [AzureCliAccessTokenProvider](https://github.com/Azure/azure-sdk-for-net/blob/cad93fea6a56879c88172492023a2fca595279ba/src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs).

Although instead of using a config file, it simply calls Azure CLI itself. Which sounds a bit more brittle, but has been working fine for me.

**Comment by nphmuller** [comment]
The Python SDK for Azure has also implemented this: https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli

It even uses the Azure CLI's config file. They cheated a bit though, because they simply called functions of the Azure CLI code directly, since it's also written in Python.

**Comment by nphmuller** [comment]
I've created this issue on the Azure CLI side of things: https://github.com/Azure/azure-cli/issues/7217

**Comment by mattfarina** [comment]
@vladbarosan Was this closed because it was implemented? I don't see it and I'm in the same position as @nphmuller.

**Comment by nphmuller** [comment]
@mattfarina It's implemented since version 11.1.0 of go-autorest :)
A possible reason you're not seeing it is because the azure sdk for go has not updated its go-autorest dependency to that version yet.

**Comment by nphmuller** [comment]
The ‘latest’ branch of the sdk has just been updated. So the next release will probably contain the new auth method.

**Comment by mattfarina** [comment]
@nphmuller When I look at https://github.com/Azure/azure-sdk-for-go/blob/f27fc0e7e6fb0b34a2a6229fcd46f36ed471f88f/services/keyvault/auth/auth.go I don't see it. Where should I be looking? You can change the commit id for latest. I just grabbed it so we see the same thing.

**Comment by nphmuller** [comment]
@mattfarina When I wrote the response yesterday it was only available here:
https://github.com/Azure/go-autorest/blob/ea233b6412b0421a65dc6160e16c893364664a95/autorest/azure/auth/auth.go

https://github.com/Azure/azure-sdk-for-go/pull/2927 just got merged, so now it's also available in the file you mentioned (latest branch only for now).

**Comment by mattfarina** [comment]
@nphmuller thanks.

Because there are now two methods... is there a best way to use the two methods together? Wait for one to return an error and then try the other?

**Comment by nphmuller** [comment]
The ones in go-autorest are the default one. It requires the azure resource url to be passed as a parameter. Since for many resources the same url is used (https://management.azure.com/), there’s an overload which uses that url by default.

KeyVault has it’s own resource url. So the KeyVault authorizer contains a couple of methods which call the methods in go-autorest with the KeyVault resource URL.

So for KeyVault both could be used. Although you would have to pass the KeyVault resource URL manually each time if you used the methods in go-autorest. So it's probably easier to use the ones in the KeyVault package.
