### ISSUE TITLE
[ADLS] Request for Storage package for Azure Data Lake Store

### ISSUE THREAD

**Issue by AndreasHaure** [Azure/azure-sdk-for-go#2627]
### Service Package Request

Similar to the storage packages that are currently offered: [Storage - Blobs](https://github.com/Azure/azure-storage-blob-go),  [Storage - Files](https://github.com/Azure/azure-storage-file-go) and [Storage - Queues](github.com/Azure/azure-storage-queue-go) we would love to have a storage package specifically for the **Azure Data Lake Storage**.

Most of our data is stored in ADLS and in order not to have to design and maintain our own sdk for go we would love to have this package available as part of the azure sdk for go.

Thank you in advance.

**Comment by jhendrixMSFT** [comment]
Is this what you're looking for?
https://github.com/Azure/azure-sdk-for-go/tree/master/services/datalake/store/2016-11-01/filesystem

**Comment by AndreasHaure** [comment]
Hadn't noticed that you've already build such a client for the ADLS. Thank you!
