### ISSUE TITLE
Template Deployment Delete errors on `2016-02-01`

### ISSUE THREAD

**Issue by thetonymaster** [Azure/azure-sdk-for-go#2628]
### Bug Report

"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources"

go version
go version go1.9.4 darwin/amd64

* What happened?

Error when deleting a Template Deployment

* What did you expect or want to happen?

A Template Deployment successfully deleted, error received

pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: unexpected end of JSON input

* How can we reproduce it?

	future, err := deployClient.Delete(ctx, resourceGroup, name)
	if err != nil {
		return fmt.Errorf("Error deleting template %+v", err)
	}

	err = future.WaitForCompletion(ctx, deployClient.Client)
	if err != nil {
		return fmt.Errorf("Error deleting template %+v", err)
	}

**Comment by seyadava** [comment]
Can you provide the fiddler trace please? I want to look at the raw response to identify source of issue.

**Comment by bganapa** [comment]
@marstr / @joshgav  anything known here?

**Comment by seyadava** [comment]
This is failing on go-autorest package. I've created another issue on go-autorest package to track this issue: https://github.com/Azure/go-autorest/issues/318

**Comment by jhendrixMSFT** [comment]
Closing since we're tracking via the issue in go-autorest.
