### ISSUE TITLE
ARM: Body closed if error response

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#263]
In arm/... packages we have the following responder pattern:

```go
err = autorest.Respond(
	resp,
	autorest.WithErrorUnlessStatusCode(http.StatusOK),
	autorest.ByUnmarshallingJSON(&result),
	autorest.ByClosing())
result.Response = autorest.Response{Response: resp}
return result
```

If the server returns an error response, we return an `autorest.Error` which contains the HTTP status code. However `ByClosing()` closes the `Body` in the returned `autorest.Response` whether `err` variable is nil or not.

```go
return ResponderFunc(func(resp *http.Response) error {
	err := r.Respond(resp)
	if resp != nil && resp.Body != nil {
		resp.Body.Close()
	}
	return err
})
```

Therefore if a service error occurs, the default responders in the SDK (`[operation]Responder()`) will return a `(model, error)`, however `model.Response.Body` is always closed when it is returned to the caller.

**This makes it impossible to read the `error` object in the returned JSON response** (related: https://github.com/Azure/go-autorest/pull/13) unless user rolls their own Preparer/Sender/Responder.

Unless I'm wrong we need either:

* a `ByClosingIfNotError()` method which would not close Body and expect caller to read the response body and close it (would lead to open HTTP connection leaks easily if the user is unaware of this)
* OR the `ByCheckingAzureError()` implementation in https://github.com/Azure/go-autorest/pull/13 which reads the response and then closes, so the `ByClosing()` would be a no-op.

Do we know how Terraform folks actually read the errors at all? It does not seem possible with the current code?

cc: @brendandixon

**Comment by brendandixon** [comment]
@ahmetalpbalkan I believe the best answer is https://github.com/Azure/go-autorest/pull/13 on which I've commented.

**Comment by ahmetalpbalkan** [comment]
@brendandixon I don't think this has anything to do with that issue yet. I'm saying I think we should keep body open `if err != nil`.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Not sure I agree, but I prefer flexible libraries so....instead of modifying and changing the semantics of this responder, let's add a new one:

```go
func ByClosingUnlessError() RespondDecorator {
	return func(r Responder) Responder {
		return ResponderFunc(func(resp *http.Response) error {
			err := r.Respond(resp)
			if err == nil && resp != nil && resp.Body != nil {
				resp.Body.Close()
			}
			return err
		})
	}
}
```

autorest.ByClosingIfError covers the opposite case.

**Comment by ahmetalpbalkan** [comment]
@brendandixon Okay do we agree on the that we should add this method to autorest and this SDK should switch to it? If so, I'll send a PR right away.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Sure.

**Comment by ahmetalpbalkan** [comment]
ok so https://github.com/Azure/go-autorest/pull/13 does not need any closing (so `ByClosing()` in case of error would be met by `NopCloser`). If we get that in the only change we'd need to make as far as this problem goes is `autorest.WithError... --> azure.WithError...`.

**Comment by ahmetalpbalkan** [comment]
this has been fixed lately with azure.WithErrorUnless.
