### ISSUE TITLE
Delete Resource Group fails with updatePollingState error

### ISSUE THREAD

**Issue by weinong** [Azure/azure-sdk-for-go#2645]
### Bug Report

* import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`services/resources/mgmt/2018-05-01/resources` though, its more like a bug in `github.com/Azure/go-autorest/autorest/azure/async.go`
* SDK version e.g. `master`, `latest`, `18.1.0`
    * Specify the exact commit if possible; one way to get this is the REVISION
      column output by `dep status "github.com/Azure/azure-sdk-for-go`.
```
$ dep status "github.com/Azure/azure-sdk-for-go"
PROJECT                            CONSTRAINT  VERSION   REVISION  LATEST    PKGS USED
github.com/Azure/azure-sdk-for-go  v20.1.0     v20.1.0   2935c02   v20.1.0   2
github.com/Azure/go-autorest       ^10.15.3    v10.15.3  a35eae3   v10.15.3  8
github.com/dgrijalva/jwt-go        v3.2.0      v3.2.0    06ea103   v3.2.0    1
```
* output of `go version`
```
$ go version
go version go1.10.4 windows/amd64
```

* What happened?
In some scenario ARM would not follow the typical Async behavior, e.g. returning operation status indicating the state. Instead, it returns `ServiceError` directly. When this happens, the SDK failed with `pollingTrackerBase#updatePollingState: the response from the async operation has an invalid status code: StatusCode=0`. This is extremely undesired as detail is lost.
* What did you expect or want to happen?
At least the response needs to be returned in the `error` object.
* How can we reproduce it?
I captured the response from ARM. You can repro from https://github.com/weinong/azure-sdk-for-go-bug
* Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.15.4
