### ISSUE TITLE
Nil dereference panic in network issues where resp==nil

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#265]
Related: https://github.com/Azure/go-autorest/pull/20

I have a piece of code like:

```go
...stuff
time.Sleep(5 * time.Second)
_, err := publicIPAddressClient.CreateOrUpdate(resourceGroup, name,
		network.PublicIPAddress{...})
```

and if **I disconnect my internet** during sleep (net.Dial should be returning an error), it panics with nil dereference panic.

It panics in evaluating `resp.StatusCode` expression in the call to autorest.NewErrorWithError:

```go
func (client PublicIPAddressesClient) CreateOrUpdate(resourceGroupName string, publicIPAddressName string, parameters PublicIPAddress) (result PublicIPAddress, ae error) {
	...
	resp, err := client.CreateOrUpdateSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		return result, autorest.NewErrorWithError(err, "network/PublicIPAddressesClient", "CreateOrUpdate", resp.StatusCode, "Failure sending request")
	}
	...
```

I think we should just pass `resp` to `NewErrorWithError` and let it handle `if resp==nil`.

**Comment by colemickens** [comment]
+1

**Comment by brendandixon** [comment]
@ahmetalpbalkan @colemickens Agreed.

**Comment by ahmetalpbalkan** [comment]
addressed in autorest. Generated code should now use `autorest.NewErrorWithResponse`.
