### ISSUE TITLE
RetryableError is not retried

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#267]
I just got an error saying

> `Error creating machine: Error in driver during machine creation: network/InterfacesClient:CreateOrUpdate 429 Failure responding to request -- Original Error: azure: Service returned an error. Code="RetryableError" Message="A retryable error occured." Status=429`

does swagger spec actually specify retryable errors and do we make use of any retry logic in the SDK. I have been getting TLS handshake and network timeouts from Network RP all the time in the past week and it immediately fails. 

Maybe we could make use of some retries in case of connectivity issues even if we don't have retryable codes specified in swagger specs.

**Comment by brendandixon** [comment]
@ahmetalpbalkan There is no default retry for errors today. The 429 you received ("too many requests") suggests you may have been thrzottled. A retry under, in that case, would require a moderate delay. Retrying general errors, say HTTP 500, is a bit risky. We can consider adding the support.

**Comment by ahmetalpbalkan** [comment]
It's very unlikely that I got throttled (doesn't throttling a different status code?). I tend to think HTTP 500s are meant to be retried on the user and with a reasonable backoff. Unless we have such retries (especially in operation status checks via polling), the entire operation might seem like failed yet it actually would succeed.

I think we should consider reducing flakiness somehow. Based on my experience in the past week, RPs aren't reliable at all and they drop connections or return such errors all the time.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I'm happy to adjust the ARM packages based on observed behavior. Let's chat and come up with what we should do.

**Comment by ahmetalpbalkan** [comment]
this won't happen when we poll correctly, so closing.
