### ISSUE TITLE
Application Insights -> AdditionalProperties not unmarshalled on MetricsResultInfoType

### ISSUE THREAD

**Issue by jcorioland** [Azure/azure-sdk-for-go#2695]
### Bug Report

* import path: `github.com/Azure/azure-sdk-for-go/services/appinsights/v1/appinsights`
* SDK version `20.1.0` (dep ensure)
* output of `go version`

```bash
go version go1.10.4 linux/amd64
```

## Bug

I am currently exploring the Application Insights Go SDK, trying to retrieve Metrics from App Insights, doing the following:

```go
metricsResult, err := appinsights.GetMetricsMethod(context.Background(), metricsBody)
    if err != nil {
        log.Printf("unable to get retrive metric: %v", err)
    } else if metricsResult.StatusCode != 200 {
        log.Printf("unable to get retrive metric: %v", metricsResult.Status)
    } else {
        for _, entry := range *metricsResult.Value {
            if *entry.Status != 200 {
                log.Printf("entry.Status: %v", *entry.Status)
            } else {
                for _, segment := range *entry.Body.Value.Segments {
                    log.Printf("segment.Start: %v", *segment.Start)
                    log.Printf("segment.End: %v", *segment.End)
                    for k, v := range segment.AdditionalProperties {
                        log.Printf("Key: %v, Value: %v", k, v)
                    }
                }
            }
        }
    }
```

The AdditionalProperties map on the segment is always empty. I’ve put an http proxy to have better understanding on the response and there are additional properties in the JSON response:

![capture](https://user-images.githubusercontent.com/4435138/45537098-a8ba6280-b803-11e8-9275-1113749b3702.jpg)

When I am running the code, I only get end/start information, but nothing in the AdditionalProperties map, unfortunately. I have debug the whole process and it seems to really occur at the json unmarshalling level. I am pretty new to Golang, so I am not familiar with that, but I do not understand why I don’t get all the results from the response. From what I understand in the [code](https://github.com/Azure/azure-sdk-for-go/blob/master/services/appinsights/v1/insights/models.go#L2375), this map should get all the unmatched properties during unmarshalling, right?

![capture2](https://user-images.githubusercontent.com/4435138/45537161-cee00280-b803-11e8-978f-db849827ce32.png)

Thanks!

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v21.0.0.  Note though that the package name has changed, it's now `github.com/Azure/azure-sdk-for-go/services/appinsights/v1/insights`.  Unfortunately the old package wasn't cleaned up, I'll get this resolved for the next release.
