### ISSUE TITLE
Unable to create MySQL server via the create method on the SDK

### ISSUE THREAD

**Issue by greensombrero** [Azure/azure-sdk-for-go#2718]
### Bug Report

import path: "github.com/Azure/azure-sdk-for-go/services/mysql/mgmt/2017-12-01/mysql"
SDK Version: v20.1.0 

dep status github.com/Azure/azure-sdk-for-go
PROJECT                            CONSTRAINT     VERSION        REVISION  LATEST    PKGS USED
github.com/Azure/azure-sdk-for-go  ^20.1.0        v20.1.0        2935c02   v20.1.0   4  
github.com/Azure/go-autorest       ^10.15.4       v10.15.4       a88c19e   v10.15.4  9  
github.com/dgrijalva/jwt-go        v3.2.0         v3.2.0         06ea103   v3.2.0    1  
github.com/dimchansky/utfbom       branch master  branch master  5448fe6   5448fe6   1  
github.com/jessevdk/go-flags       v1.4.0         v1.4.0         c6ca198   v1.4.0    1  
github.com/sethvargo/go-password   v0.1.1         v0.1.1         d207206   v0.1.1    1  
golang.org/x/crypto                branch master  branch master  0e37d00   0e37d00   2  

go version go1.10.2 darwin/amd64

I'm trying to create a Azure DB for MySQL via the SDK API and I'm running into what I think is a false validation error.  The error I get is the following:

mysql.ServersClient#Create: Invalid input: autorest/validation: validation failed: parameter=parameters.Properties constraint=Null value=mysql.ServerPropertiesForDefaultCreate{AdministratorLogin:(*string)(0xc420294030), AdministratorLoginPassword:(*string)(0xc4202f4170), Version:"5.7", SslEnforcement:"Enabled", StorageProfile:(*mysql.StorageProfile)(nil), CreateMode:"Default"} details: field "parameters.Properties" doesn't exist

Here is the code I'm using:

r, err := client.Create(context.Background(), config.ResourceGroup, config.ServerName, mysql.ServerForCreate{
		Sku: &mysql.Sku{
			Name: &sku,
		},
		Properties: mysql.ServerPropertiesForDefaultCreate{
			AdministratorLogin:         &adminLogin,
			AdministratorLoginPassword: &rootPassword,
			Version:                    mysql.FiveFullStopSeven,
			SslEnforcement:             mysql.SslEnforcementEnumEnabled,
			CreateMode:                 mysql.CreateModeDefault,
		},
		Location: &config.Location,
	})
	if err != nil {
		fmt.Println("Error creating server ", err)
		os.Exit(1)
	}

The SDK is a bit confusing on the create method because the way the properties field is defined on the struct it points to an interface type BasicServerPropertiesForCreate but I think I set everything up to work correctly and I'm very confused by this error.  

Maybe I have something wrong I'd be happy to see a good example on how to create a MySQL server through the API.

Thanks!

**Comment by greensombrero** [comment]
I've done some more digging into the SDK code and I've found the validation is searching for a Properties field on the ServerPropertiesForDefaultCreate struct which doesn't have a Properties field.  It also appears to look for it on the ServerForCreate struct which does have that property.  I'm unclear why it is searching for it on the first struct (ServerPropertiesForDefaultCreate) as it isn't defined there.  I'm still trying to fully grok the validation framework but something appears to be misconfigured here.

**Comment by tombuildsstuff** [comment]
@greensombrero taking a look at the code above I think you're missing a `&` from the start of the Properties assignment (to make this `Properties: &mysql.ServerPropertiesForDefaultCreate{...}`).

For reference - here's how we (Terraform) provision MySQL Servers via the Azure SDK for Go for example: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_mysql_server.go#L208-L220 - which is otherwise basically the same as above.

Hope that helps :)

**Comment by greensombrero** [comment]
Thanks that is a weird one because normally I would expect the compiler to complain about not passing something as a pointer where it is needed.  The interface implementation doesn't take a pointer receiver so I'm kind of surprised that works but it definitely does.  I've probably been staring at it for too long.
