### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#274]
We should rewrite the README in a way it links to separate independent SDKs we have:

* arm
* storage
* management

and each of those can have their own readmes/samples. It currently shows only the `management/` package examples in the root.

Also the examples are going out of date for arm/ as we develop, we should bring them up to date.

We should probably also have a note on vendoring for this package.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Agreed.

**Comment by ahmetalpbalkan** [comment]
assigning @garimakhulbe it's a good exercise :wink:

**Comment by esell** [comment]
Just piggybacking onto this, I can open up a new issue though if you want...

Would it make sense to also update the README with regards to the SDKs usage of glide? I have been playing with go for a bit but had never heard of glide so it wasn't quite obvious to me why things were breaking when I tried to pull this SDK into a new project. 

Doing a simple `go get` as is documented in the README ended up pulling in the most current version of `go-autorest` which breaks the SDK. 

I'm open to submitting a PR for the updates but I wanted to make sure it was something that made sense to you all first.

**Comment by ahmetalpbalkan** [comment]
@esell Thanks for bringing this up, I think we should just bring the docs in the repo up-to-date in general.

**Comment by garimakhulbe** [comment]
Sorry for replying late. Good suggestion. Thanks. Its next in my TODO list.
Will keep this in mind.

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe are you going to be taking a stab at it soon? The current README does not reflect the state of things and what's actually used.

**Comment by garimakhulbe** [comment]
cc @mcardosos
