### ISSUE TITLE
storage - add support for blob type 'Append'

### ISSUE THREAD

**Issue by dovreshef** [Azure/azure-sdk-for-go#275]
As detailed here: http://blogs.msdn.com/b/windowsazurestorage/archive/2015/04/13/introducing-azure-storage-append-blob.aspx

**Comment by preetpalS** [comment]
Isn't this issue solved? (https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#BlobType)

**Comment by ahmetalpbalkan** [comment]
@preetpalS Ah, right. This is contributed in #278. Closing.
