### ISSUE TITLE
add package godoc for arm/

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#276]
generated docs are missing synopsis for arm/... packages

![image](https://cloud.githubusercontent.com/assets/159209/12758981/a41d00ea-c993-11e5-8551-6d73e5fe0107.png)

**Comment by brendandixon** [comment]
@ahmetalpbalkan Odd. Any ideas? The comments remain in the packages and nothing in the build has changed (that I know of). What drives creation of GoDoc?

**Comment by ahmetalpbalkan** [comment]
@brendandixon well as far as I can tell none of these packages have godoc. There should be a file in the pkg like:

```go
// Package dns does blah blah.
package dns

...
```

**Comment by brendandixon** [comment]
@ahmetalpbalkan Very odd. I know we had GoDoc at one time, yet I cannot find when / where the package comments were removed. I'll take this up with @garimakhulbe.
