### ISSUE TITLE
Requesting an azure-sdk-for-go release with go-autorest V.10.15.4

### ISSUE THREAD

**Issue by tariq1890** [Azure/azure-sdk-for-go#2776]
Title says it all! We were hoping the latest release included that.

**Comment by jhendrixMSFT** [comment]
We'll be releasing v21.0.0 next week (targeting 9/24) and it will have v10.15.4 of go-autorest.

**Comment by jhendrixMSFT** [comment]
Note that if you run `dep ensure -update` it will automatically update to `v10.15.4` of go-autorest.
