### ISSUE TITLE
RouteTable field of SubnetPropertiesFormat is emtpy

### ISSUE THREAD

**Issue by pdumais** [Azure/azure-sdk-for-go#2794]
with the sdk from  master, when I cal SubnetsClient.ListComplete and iterate thru the subnets and read "subnet.SubnetPropertiesFormat.RouteTable" I get an object that is only populated with the ID field. All other fields are nil.

I'm thinking this might be because it is lazy-loaded but I can't find any examples or information about deeply nested objects being lazy loaded.

**Comment by jhendrixMSFT** [comment]
I observe the same thing.  @mikhailtryakhov can you comment on this?  For reference this is the operation.  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/virtualNetwork.json#L489

**Comment by jhendrixMSFT** [comment]
And to clarify, I don't see the data coming across the wire so I don't believe this is an issue with the SDK.

**Comment by allegradomel** [comment]
Hi @pdumais, was [this thread ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4730)helpful? If your issue is resolved we can close this issue.

**Comment by pdumais** [comment]
It's been a while, but I remember ending up using some workaround. I'm ok with closing
