### ISSUE TITLE
Generator ignores if inherited attributes are required

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#2797]
In Azure/autorest#1540 @mcardosos says:
> A concrete example...
> RedisCreateParameters inherits form Resource, where location is marked as required.
> Location should be included in the method's validation section.

**Comment by chamons** [comment]
@jhendrixMSFT - Is validation a track 1 thing not done in track 2 go?

I isolated the example down to this json:

https://gist.github.com/f944b2a430f27a7669c4d1d50d24d74d

and got this generated code:

https://gist.github.com/chamons/00719b0ac596aa3b5fe87d94b394b6f9

which doesn't have any validate calls at all. 

I also ran the entire file, and didn't see any either.

**Comment by chamons** [comment]
Same question applies to https://github.com/Azure/azure-sdk-for-go/issues/2182 as well

**Comment by RickWinter** [comment]
Track2 does NOT do client side validation.
