### ISSUE TITLE
[Recovery Services] ProtectedItemsClient returns some azure resource ID's with Subscriptions capitalized.

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#2824]
### Bug Report

* import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
```"github.com/Azure/azure-sdk-for-go/services/recoveryservices/mgmt/2016-06-01/backup"```
* SDK version e.g. `master`, `latest`, `18.1.0`
```
{
			"checksumSHA1": "XiQW2U5GBOhOfPTwFlFeM2thDCs=",
			"path": "github.com/Azure/azure-sdk-for-go/services/recoveryservices/mgmt/2016-06-01/backup",
			"revision": "2935c0241c74bd8549b843978dd6fc1be6f48b4a",
			"revisionTime": "2018-08-31T14:25:13Z",
			"version": "=v20.1.0",
			"versionExact": "v20.1.0"
		},
```
* output of `go version`
```go version go1.10.3 darwin/amd64
```

* What happened?
`backup.ProtectedItemsClient` returns its response.ID and `response.Properties.PolicyID` in an unexpected format, `Subscriptions` is unexpectedly capitalized. This stands out as the protection policy client returns ID's as lowercase so when using it as an input to this client a different value is returned.

* What did you expect or want to happen?
id returned with subscription in lower case

* How can we reproduce it?
* Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
@sumitmal can you please comment on this?

**Comment by katbyte** [comment]
@marstr, any updates on this one?

**Comment by marstr** [comment]
I have a thread going internally. I'm still being routed to the correct owner, so no update yet.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT - is there any update here? :)

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff looks like the email thread died.  :(  Working on it...

**Comment by pvrk** [comment]
@katbyte, @tombuildstuff: I want to understand, if the sequence failing because the Subscription is returned in uppercase? Because this issue is marked as blocked, I want to understand more on this scenario. Adding @adittulasi for information.

**Comment by pvrk** [comment]
#customer-response-expected

**Comment by pvrk** [comment]
#please-close
since we didn't receive a response. Can re-open if the sequence is failing.

**Comment by katbyte** [comment]
This is still an issue @pvrk. Yes this causes issues and other APIs to fail because they expect subscriptions to be lowercase and we are getting it as uppercase.

**Comment by katbyte** [comment]
@pvrk, @jhendrixMSFT, any progress on this? we have another PR that has uncovered many many more case differences with the recovery services API: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4003/files

**Comment by pvrk** [comment]
@TAdityaAnirudh: can you please check this?

**Comment by TAdityaAnirudh** [comment]
Thanks for the clarification @katbyte . We will fix it in upcoming release.

Out of curiosity, why are those APIs expecting Subscription ID in lower case only? Shouldn't we be fixing those APIs instead of updating every other response?

**Comment by katbyte** [comment]
@TAdityaAnirudh & @pvrk, most if not every other azure api we work with returns it in lowercase (or expects it to be). recovery services seems to be the exception here so it stands to reason recovery services should change to be consistent with the rest of azure.

**Comment by TAdityaAnirudh** [comment]
Fix has been checked-in. It should be deployed by end of November.

**Comment by katbyte** [comment]
Thanks @TAdityaAnirudh!

**Comment by pvrk** [comment]
@katbyte : Now, the subscription ID is returned in lower case and for all other resource IDs, case is preserved. I hope I can close this issue.

**Comment by katbyte** [comment]
Hi @pvrk, it looks like the azure file share backup APIs are still returning `subscription` in the wrong case. Was it fixed for all api endpoints? do we need to upgrade to a newer version of the API?

**Comment by pvrk** [comment]
@katbyte : Thanks for the feedback. Will check and let you know.

**Comment by pvrk** [comment]
@katbyte : We internally checked once more and saw that the fix is present even for AFS APIs. Can you please provide any particular API where you are still seeing the wrong case behavior?

**Comment by pvrk** [comment]
Closing this bug due to lack of response. We have checked internally once again and doesn't see this issue getting re-produced after the fix was provided.
