### ISSUE TITLE
Method to delete multiple role assignments by ID in authorization API

### ISSUE THREAD

**Issue by tariq1890** [Azure/azure-sdk-for-go#2825]
### Feature Request

Currently we delete roleAssignments by ID one at a time 

`func (client RoleAssignmentsClient) DeleteByID(ctx context.Context, roleAssignmentID string) (result RoleAssignment, err error) ` (roleassignments.go L279)

It would be a nice pass an slice of roleAssignmentIDs instead and achieve the deletions through a single SDK call.

**Comment by tariq1890** [comment]
@jhendrixMSFT Any thoughts on this?

**Comment by jhendrixMSFT** [comment]
It seems this would best be served by a new API from the service that accepts a list of assignment IDs.  @ifross89 is this API owned by your team?

**Comment by tariq1890** [comment]
Any update on this?

**Comment by tariq1890** [comment]
Hi @jhendrixMSFT . The person that you tagged Ian is not a member of the AAD/Identity team. Who do we reach out to ?

**Comment by jhendrixMSFT** [comment]
@joshgav can you help route this?

**Comment by joshgav** [comment]
Role definitions and assignments are actually a feature of Azure Resource Manager (RM) as described [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview). While the identities usually come from AAD, authorization via roles is configured within RM.

Per that including @ravbhatnagar from RM - can you add this to the Authorization RP API?

**Comment by tariq1890** [comment]
@ravbhatnagar Can you help us with this?
