### ISSUE TITLE
SDK Has redis functionality but there are no docs to support it

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#283]
This SDK has [Redis](https://github.com/Azure/azure-sdk-for-go/tree/master/arm/redis) functionality - but the docs are no where to be found on the MSDN documentation site

https://msdn.microsoft.com/en-us/library/mt420159.aspx

Paul

**Comment by brendandixon** [comment]
@stack72 That's odd. I'll raise the point internally. Thanks!

**Comment by stack72** [comment]
Thanks @brendandixon

**Comment by stack72** [comment]
@brendandixon any update on this?

**Comment by brendandixon** [comment]
@stack72 Not that I've heard. I pinged them again.

**Comment by brendandixon** [comment]
@stack72 So, I've heard: The documentation is coming, but I would not hold your breath. :) Do you have a specific question or issue?

**Comment by stack72** [comment]
@brendandixon thanks for the information  - I guess i was looking for some indication on how to use that part of the API.

**Comment by brendandixon** [comment]
@stack72 I have no idea. :)

**Comment by brendandixon** [comment]
@stack72 The perils of generated code...

**Comment by stack72** [comment]
Any word on this?

P.

**Comment by ahmetalpbalkan** [comment]
@stack72 it would be nice if you could open an issue for Missing Redis Service Specs at https://github.com/Azure/azure-rest-api-specs/ and we can forward internally.

**Comment by ahmetalpbalkan** [comment]
oops ignore my comment. @brendandixon it appears like there is arm-redis at specs: https://github.com/Azure/azure-rest-api-specs/ should we incorporate?

**Comment by brendandixon** [comment]
@ahmetalpbalkan Sure. @garimakhulbe can handle that.

**Comment by stack72** [comment]
Thanks all. Does each set of arm specs need to be individually converted?

**Comment by stack72** [comment]
Hi @brendandixon / @ahmetalpbalkan / @garimakhulbe 

Any idea if we can get some docs on this? 

Thanks

Paul

**Comment by ahmetalpbalkan** [comment]
cc: @devigned do you know where we might REST API docs for the Redis service?

**Comment by devigned** [comment]
@SiddharthChatrolaMs can you point us in the right direction?

**Comment by garimakhulbe** [comment]
@SiddharthChatrolaMs @devigned Any update on this? Customer is looking for MSDN documentation for redis.

**Comment by stack72** [comment]
*ping*

**Comment by stack72** [comment]
Ping again on this

**Comment by tombuildsstuff** [comment]
Hey @garimakhulbe @SiddharthChatrolaMs @devigned 

Is this going to be added anytime soon? I'm trying my best to implement Redis support - but I've only got a few usage examples, which makes it hard to ensure I've covered all the edge cases

**Comment by tombuildsstuff** [comment]
@brendandixon @garimakhulbe @devigned @ahmetalpbalkan is there any kind of update on this? This issue's been open for over 6 months without any real response?

![inline](https://i.makeagif.com/media/7-23-2015/RbsnpX.gif)

I'm adding support for [Redis to Terraform](https://github.com/hashicorp/terraform/pull/9537) - but it's hard when all I've got is the ARM templates, which aren't complete - and I believe there's a few bugs in the SDK, but it's impossible to tell without the docs..

Should I be investing my time in GCE instead? ¯\_(ツ)_/¯

**Comment by amarzavery** [comment]
@brendandixon @garimakhulbe @ahmetalpbalkan
I came across this issue via internal email. Every language SDK is supposed to have some kind of documentation story of the client side API. 
All the azure sdks should have links to the docs right at the top of the repo.

The REST API docs that will be generated from swagger (rest-api-specs) repo is a separate and independent project. I am not aware about it's timeline.

However @tombuildsstuff, did you take a look at the GO SDK documentation over here: https://godoc.org/github.com/Azure/azure-sdk-for-go ? 

I did find documentation for the redisCache Go sdk over there. The link is: https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/redis


**NOTE: The doc site is slow but it will eventually load.**

I found this link at the top of the go sdk repo:
![image](https://cloud.githubusercontent.com/assets/4521223/19746210/32e03432-9b8a-11e6-80f1-cf0bf09f8937.png)

**Comment by ahmetalpbalkan** [comment]
> NOTE: The doc site is slow but it will eventually load.

@amarzavery it looks like godoc.org is currently having some issues. it often caches the documentation and updates periodically. If the issue persists, please report them to https://github.com/golang/gddo/issues

**Comment by colemickens** [comment]
@amarzavery I believe the problem in this thread is the fact that we are missing the actual REST documentation on MSDN.

Aka, where is the Redis equivalent of this page: https://msdn.microsoft.com/en-us/library/azure/mt163647.aspx

**Comment by amarzavery** [comment]
@ahmetalpbalkan - We upload our docs at this site http://azure.github.io/azure-sdk-for-node/ 
The https://azure.github.io/projects/sdks/ provides docs for different language SDKs in Azure. It would be nice if GO sdk can also publish their docs over here. 

This is the github repo https://github.com/Azure/azure.github.io that powers azure.github.io

**Comment by ahmetalpbalkan** [comment]
@amarzavery I don't think any go developer will go to to that website to read SDK docs. The canonical way to read any go package documentation is to navigate to godoc.org/[package-name].

**Comment by tombuildsstuff** [comment]
The main problem here for me isn't so much where the documentation belongs - but what is required for each usage tier (Basic/Standard/Premium); which presumably would work best as an msdn page?

An example here is that the default Redis configuration - which appears to be 3 values, but given it's a map of values, I can only guess that those 3 key/value combinations are the defaults? Simply adding the field documentation to goDoc won't help with that IMO?

Whilst GoDoc certainly makes sense for the methods, given this documentation is more for API usage and expected responses - is that the right place for it? This is a larger problem with the Azure SDK - there's no documentation for the Redis SDK beyond what methods are available as far as I recall?

// @ahmetalpbalkan @amarzavery @stack72

**Comment by vishrutshah** [comment]
@eduardkoller Could you please follow up on documentation with Redis team. Thanks!

**Comment by mcardosos** [comment]
@tombuildsstuff @stack72 
Here it is the [documentation](https://docs.microsoft.com/en-us/rest/api/redis/).
