### ISSUE TITLE
How does Azure Go SDK compared with Azure Python SDK?

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-sdk-for-go#2837]
Is there any documentation comparing the Azure Go SDK and Azure Python SDK? 
It would be better to have list of supported azure services and features?

**Comment by jhendrixMSFT** [comment]
I'm not aware of any such documentation.
Regarding list of supported services the best we have at present is the docs on [godoc.org](https://godoc.org/github.com/Azure/azure-sdk-for-go) but I'm guessing you're looking for something higher level?
@lmazuel can comment on the Python side.

**Comment by lmazuel** [comment]
Hi @himanshu219 
If you're question is supported Azure services and Azure features, most of the SDK now are auto-generated from a common meta-description of the service ([called a Swagger](https://github.com/Azure/azure-rest-api-specs)). This coverage is equivalent. It might happen that Go merge something a little before I released on PyPI, but in most cases that's not critical (and at worst open a Python issue and I'll catch up to the latest).
That's true for all packages you see on that repo and the Python one.

If you see a package on an external repo, like Storage:
https://github.com/Azure/azure-storage-blob-go
https://github.com/Azure/azure-storage-python

They are manually written, and you should then ask the question directly on these repos to the team owners for more details.

Thank you,

**Comment by himanshu219** [comment]
Thanks guys, appreciate your help. So the usecase is that I am writing a common module for azure services and I was thinking to choose between one of the two and wanted to know if there is any major differences in supported azure services in both the SDK's to avoid any hiccups(feature not supported in current SDK version like issues) in future. It's good to know that  both the SDK's are auto generated by Swagger and would be almost equivalent.
