### ISSUE TITLE
How can i get the virtual machine power on status?

### ISSUE THREAD

**Issue by lsytj0413** [Azure/azure-sdk-for-go#2838]
As the title, how can i get the virtual machine status, such as power off, deallocated from the sdk?

**Comment by jhendrixMSFT** [comment]
I believe you want `InstanceView()` but not totally sure.  Can you try it?  If it doesn't work we can engage somebody from the compute team to answer.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2018-10-01/compute/virtualmachines.go#L574

**Comment by lsytj0413** [comment]
yes, i have seen that the InstanceView returns **statues[1].code** with the value **PowerState/running**, but i'm not sure it is the right answer because it is un-documented.

**Comment by jhendrixMSFT** [comment]
@hyonholee can you help answer?

**Comment by tariq1890** [comment]
I'd like this as well. Please let it not be added to the list of issues that will be ignored.

**Comment by hyonholee** [comment]
Statuses[1].DisplayStatus of InstanceViewStatus will show power state.

**Comment by tariq1890** [comment]
Are there links to documentation which will display all the valid values of InstanceViewStatus/DisplayStatus?

**Comment by anton-yurchenko** [comment]
> Are there links to documentation which will display all the valid values of InstanceViewStatus/DisplayStatus?

@tariq1890 have you found a list of possible values?

**Comment by FelipeMFlores** [comment]
@tariq1890 @anton-yurchenko 
I found this:
https://docs.microsoft.com/en-us/azure/virtual-machines/states-lifecycle
