### ISSUE TITLE
Return azure.RequestError instead of error where possible

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#285]
Would be nice to not have to try and cast to azure.RequestError for errors coming from the SDK.

**Comment by colemickens** [comment]
Or I suppose DetailedError once it's regenerated.

**Comment by brendandixon** [comment]
@colemickens We originally returned azure.RequestError...but that causes challenges for Go's type system when other code is expecting only an "error". Hence, we now return error and callers must cast.

**Comment by colemickens** [comment]
I'm not sure I follow. Does `azure.DetailedError` not implement the `error` interface? If it does, why would callers be confused?

**Comment by ahmetalpbalkan** [comment]
I'm not understanding the issue or responses here.

**Comment by colemickens** [comment]
Alright, I'm convinced this was not a good idea. Thanks all.
