### ISSUE TITLE
Improve enum names for . values

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#2904]
Found while investigating PR https://github.com/Azure/azure-rest-api-specs/pull/4016

This PR contains a discriminator value `Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria` which the generator changes to `MicrosoftAzureMonitorMultipleResourceMultipleMetricCriteria` for the enum name and value.  The removal of the `.` from the enum value is problematic as it doesn't match the value sent over the wire.

**Comment by jhendrixMSFT** [comment]
On further investigation the values are correct (i.e. the `.` isn't being removed) however the names are just terrible and should be shortened.

**Comment by vladbarosan** [comment]
After investigating, this would bring breaking changes and also wouldn't be safe for a couple of discriminator values. Closing for now.
