### ISSUE TITLE
`MetricAlertMultipleResourceMultipleMetricCriteria` type is missing in Azure monitor metric alerts

### ISSUE THREAD

**Issue by JunyiYi** [Azure/azure-sdk-for-go#2920]
### Feature Request

Now we can only create an Azure metric alert using [`MetricAlertSingleResourceMultipleMetricCriteria`](https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/createorupdate#request-body). But from the documentation as well as the error message returned by Azure (`Scopes property is invalid. Only single resource is allowed for criteria type SingleResourceMultipleMetricCriteria. If you want to create an alert on multiple resources, use MultipleResourceMultipleMetricCriteria odata.type.`), we should also be able to use [`MetricAlertMultipleResourceMultipleMetricCriteria`](https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/createorupdate#metricalertmultipleresourcemultiplemetriccriteria) as well.

**Comment by jhendrixMSFT** [comment]
This support was added in `v21.2.0` of the SDK, see https://github.com/Azure/azure-sdk-for-go/blob/v21.2.0/services/preview/monitor/mgmt/2018-03-01/insights/models.go#L3292 for reference.
