### ISSUE TITLE
DeploymentsClient CreateOrUpdate stopped returning a typed response

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#294]
```
commit f704479992cd6232ab22c70717feb4ba6532f2b0
Author: Garima A <garima0079@gmail.com>
Date:   Thu Feb 11 15:16:03 2016 -0800

    updated for long-running operations support

```

```
@@ -173,7 +171,7 @@ func (client DeploymentsClient) CheckExistenceResponder(resp *http.Response) (re
 // resourceGroupName is the name of the resource group. The name is case
 // insensitive. deploymentName is the name of the deployment. parameters is
 // additional parameters supplied to the operation.
-func (client DeploymentsClient) CreateOrUpdate(resourceGroupName string, deploymentName string, parameters Deployment) (result DeploymentExtended, ae error) {
+func (client DeploymentsClient) CreateOrUpdate(resourceGroupName string, deploymentName string, parameters Deployment) (result autorest.Response, ae error) {
        req, err := client.CreateOrUpdatePreparer(resourceGroupName, deploymentName, parameters)
        if err != nil {
                return result, autorest.NewErrorWithError(err, "resources/DeploymentsClient", "CreateOrUpdate", nil, "Failure preparing request")
```

Why did this happen? Can we get the typed version back?

**Comment by colemickens** [comment]
https://github.com/Azure/azure-sdk-for-go/pull/281#discussion_r52695500

I think this blocks me from upgrading.

**Comment by colemickens** [comment]
(I'm still upgrading anyway since I don't need the response, still think this should be fixed if it can be)

**Comment by garimakhulbe** [comment]
Sdk sends back last response in autorest.Response for long-running operations. We changed typed to autorest.Response for uniformity in lro.

**Comment by colemickens** [comment]
Does the last response usually contain data? Is there a way for the caller to read the response body? Or does the LRO not return a useful body in these cases?

**Comment by brendandixon** [comment]
@colemickens No, it does not. The long-running operations vary in their behavior, but generally, they do not return the full response upon success. You'll need to issue a subsequent GET to obtain the details.

**Comment by colemickens** [comment]
Okay, thanks for the information.
