### ISSUE TITLE
LRO: Resource Group Deployment: creation now polls, but deletion polling regressed

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#295]
Before. Creation of a resource group deployment did not poll, but deletion did.
```
azure-sdk-for-go: 95361a2573b1fa92a00c5fc2707a80308483c6f9
go-autorest: bebca455f60b24bf6a2459e9e862ff42da86f5e0
```

After: Creation of a resource group deployment polls for completion of the deployment. However, deletion is now an instantaneous return.
```
azure-sdk-for-go: b4e3bc02a65dca5237084eba6e94f06a169f09c3
go-autorest: c8bdeef20f02ae8a6494040b1a7838692648ec03
```

This is the response from the delete resource group call with the current/"after" versions:
```
HTTP/1.1 202 Accepted
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: https://management.azure.com/subscriptions/aff271ee-e9be-4441-b9bb-42f5af4cbaeb/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1LVUJFOjJEMjAxNjAzMTQ6MkQyMDQ1MTktV0VTVFVTIiwiam9iTG9jYXRpb24iOiJ3ZXN0dXMifQ?api-version=2015-11-01
Retry-After: 15
x-ms-ratelimit-remaining-subscription-writes: 1194
x-ms-request-id: 90d4302d-21a9-4d03-a7c6-cc79950da6de
x-ms-correlation-request-id: 90d4302d-21a9-4d03-a7c6-cc79950da6de
x-ms-routing-request-id: WESTUS:20160315T040152Z:90d4302d-21a9-4d03-a7c6-cc79950da6de
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Tue, 15 Mar 2016 04:01:52 GMT
content-length: 0
```

**Comment by brendandixon** [comment]
@colemickens Which API are you using (package/method)? Have you checked the corresponding Swagger to see if the x-ms-long-running attribute is attached? If it's not, then the generator does not know to generate polling logic.

**Comment by colemickens** [comment]
This is the method: https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/groups.go#L175

To be honest, I can't find the Swagger spec for it in the [spec repo](https://github.com/Azure/azure-rest-api-specs). ??

Either way, the generated code looks like it installs the LRO support when it Sends: https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/groups.go#L220

Here is a mitmproxy flow of it polling before I upgraded the sdk. You can clearly see the polling: 
https://gist.github.com/anonymous/af8de2e771faf8677d5f/raw

Here's what it does after I upgrade the sdk. No polling, it just returns after the first 202: 
https://gist.githubusercontent.com/anonymous/b01501d544c3d5b47bdf/raw

These deletion were both for 4 machine cluster resource groups.

**Comment by ahmetalpbalkan** [comment]
@colemickens https://github.com/Azure/azure-rest-api-specs/blob/244f3bf801273039d9faa2484c1938a142b88c9b/arm-resources/resources/2015-11-01/swagger/resources.json#L593-L624

**Comment by garimakhulbe** [comment]
Is it sending location header back? It seems from the logs. If yes, Sdk does not do polling for location header currently. We are in process of updating code for this. 
Not sure how it was polling earlier for the same call.

**Comment by colemickens** [comment]
@garimakhulbe Okay, thanks!

**Comment by garimakhulbe** [comment]
@colemickens...New release will fix this issue. Let us know if issue persists.

**Comment by colemickens** [comment]
This is fixed. Thanks!
