### ISSUE TITLE
InvalidApiVersionParameter creating subnets

### ISSUE THREAD

**Issue by gdhagger** [Azure/azure-sdk-for-go#297]
Received the following response from Azure when trying to create a subnet.

```
{
	"error": {
		"code": "InvalidApiVersionParameter",
		"message": "The api-version '2015-06-15' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
	}
}
```

Other network related operations seem to success with that API version

**Comment by gdhagger** [comment]
I was mistaken. The error message is caused by some broken data in the request.

**Comment by ahmetalpbalkan** [comment]
@gdhagger did you omit the name or something like that? If so we probably should return a friendlier error message.

**Comment by gdhagger** [comment]
Sort of...

The values are being computed by [Terraform](https://www.terraform.io/) and a bug/feature on that side was resulting in either nothing or nonsense being entered for the resource group name.

**Comment by ahmetalpbalkan** [comment]
@gdhagger was it the empty resource group name caused this problem? I appreciate any details, we may have a chance surfacing a better error message if we get a better sense of the issue.

**Comment by gdhagger** [comment]
Yes, I believe so.
