### ISSUE TITLE
add go.mod and separate services into independent modules

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#2993]
### Feature Request

Investigate and adopt modules for this and the [go-autorest](https://github.com/Azure/go-autorest) repo.

Strongly consider splitting every service in `./services` into separate modules/packages so they can be versioned independently.

**Comment by joshgav** [comment]
cc @tombuildsstuff @feiskyer

**Comment by tombuildsstuff** [comment]
@joshgav sorry for the delayed reply here - is the intention/thought here that we'd be able to have SemVer within a version of an RP within the services folder, or to split these packages out altogether?

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff Each API version within an RP will be its own module since they independently rev.

**Comment by jhendrixMSFT** [comment]
Related: https://github.com/Azure/azure-sdk-for-go/issues/2564

**Comment by LorbusChris** [comment]
There has been no movement in https://github.com/Azure/azure-sdk-for-go/projects/2 for 3 months. Is there anything that can be done to speed things up?

**Comment by michaelbironneau** [comment]
This is still an issue - do you have a timeframe on resolution?

**Comment by RickWinter** [comment]
Completed in track2 will NOT be backported to track1.
