### ISSUE TITLE
Errors in Latest Release?

### ISSUE THREAD

**Issue by andrewduch** [Azure/azure-sdk-for-go#300]
I've done a clean go get of azure-sdk-for-go and the go-autorest packages. azure-sdk-for-go is filled with all of these errors:

github.com/Azure/azure-sdk-for-go/arm/web/hostingenvironments.go:106: too many arguments in call to azure.DoPollForAsynchronous
github.com/Azure/azure-sdk-for-go/arm/web/hostingenvironments.go:175: too many arguments in call to azure.DoPollForAsynchronous
github.com/Azure/azure-sdk-for-go/arm/web/hostingenvironments.go:244: too many arguments in call to azure.DoPollForAsynchronous

**Comment by ahmetalpbalkan** [comment]
@andrewduch we develop the `go-autorest` and `azure-sdk-for-go` projects independently, therefore using tip of master branch from these projects are not necessarily going to be compatible. As our README.md highlights:

> NOTE: This repository is under heavy ongoing development and is likely to break over time. We currently do not have any releases yet. **If you are planning to use the repository, please consider vendoring the packages in your project and update them when a stable tag is out.**

You can find what version of go-autorest works with the current version of azure-sdk-for-go at [`glide.lock`](https://github.com/Azure/azure-sdk-for-go/blob/master/glide.lock) file. In a nutshell, if you're using Azure SDK for Go, we strongly recommend hosting your dependencies locally in your project.

That should fix your problem. If not, please let us know. Closing for now.
