### ISSUE TITLE
Support for Partner Center SDK

### ISSUE THREAD

**Issue by jjmartin** [Azure/azure-sdk-for-go#3002]
### Feature Request

I'd like to see support for the Partner Center SDK - specifically the Scenarios described here:
https://docs.microsoft.com/en-us/partner-center/develop/manage-invoices

(if there is already support, i'd like to see better documentation showing me how to get there)

**Comment by marstr** [comment]
Howdy @jjmartin,

I poked around in our [Open API Spec repository](https://github.com/Azure/azure-rest-api-specs) (from which the vast majority of this repository is auto-generated) and didn't find this service marked-up. My best guess is that this functionality is provided by the Billing RP. 

I'm going to move this issue over to the specs repository for further action.

**Comment by marstr** [comment]
Closing this in favor of Azure/azure-rest-api-specs#4252.
