### ISSUE TITLE
Security Center Workspace API silently fails when subscription pricing is Free

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#3007]
### Bug Report

* import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
```
"github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/2017-08-01-preview/security"
```
* SDK version e.g. `master`, `latest`, `18.1.0`
```
v21.1.0
```
* output of `go version`
```
go version go1.10.3 darwin/amd64
```

* What happened?
When trying to update or create the security centre workspace when the subscription pricing tier is `Free` it silently fails and sets the workspace id to "". When the subscription is changed to `Standard` the API still sets the workspace id to "", however after 5-15 min the new value eventually appears. 

* What did you expect or want to happen?
The API call to fail (or succeed if it was supposed too)

* How can we reproduce it?
Set the security centre subscription pricing tier to `Free` and try to update the workspace ID.

**Comment by chlahav** [comment]
hi @katbyte,
can you please respond with a set of commands that replicate this issue?
we did not manage to replicate it for further investigation
what we did:
- selected a free ASC subscription
- changed the workspace settings to use a manual workspace
- when we used Get workspace settings everything looks as expected (workspaceId field was updated)
- logs from a newly created VMs appeared in the new workspace

thanks

**Comment by katbyte** [comment]
Hi @chlahav,

We are using the rest API via the GO SDK.

So we basically call the create or update functions it provide and then do a get right after to make sure the requested changes were made. I can see fom our nightly tests that the workspace change is not always reflected, as well as ripping out the retry code and trying them with free. Below is the payloads sent to azure:

put:
```
```

read
```
```

**Comment by chlahav** [comment]
Hi @katbyte,
is this a new workspace?
we did find an edge case that might explain your issue
if you create a new workspace and set the workspaceSettings soon afterwards it takes a little bit of time until it will show the workspace ID.
This issue does not affect the agents that are installed or any functionality aside for the "workspaceId" field in our API.

**Comment by katbyte** [comment]
Hi @chlahav,

Yes this would be for a new workspace. If that is the case shouldn't the create function be a future that doesn't return success until the workspace ID has been supplied and is available?

**Comment by chlahav** [comment]
Hi @katbyte,
The workspace and its ID are available, but it takes a little time to be able to return it through this specific API.
since the setting was saved and started to work as expected immediately we feel confident to return a success status.
we will work to make the ID available to the API as well and eliminate this edge case.
thanks for pointing out this issue

**Comment by katbyte** [comment]
Thanks! look forward to this being fixed

**Comment by philbal611** [comment]
@chlahav 
Any update on the resolution of this issue?
