### ISSUE TITLE
Missing Go API Version Configuration in Swagger Spec Repository

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#3036]
Swagger to SDK for Go relies on AutoRest `batch` mode to generate all of the Go bits. However, when new API Versions are added the Go configuration often goes stale. In order to provide a more consistent experience between Go and other languages, we should either:
- Abandon the current approach of relying on `batch`
- Build tooling to detect when Go config has gone stale so that we can update it.

**Comment by marstr** [comment]
@bsiegel, we're talking about this at Go triage, and are sorta wanting to sit on it until we understand if there are big changes coming to the way that Swagger-To-SDK works. Think this work makes sense to start on now, or should we wait?

**Comment by bsiegel** [comment]
@marstr I think the approach I'm going to take is to have a configuration file or script file in each language repo which codifies:
- The version of autorest to use
- The correct flags and all other needed parameters to run autorest for the language
- The set of actions to take after running autorest

As the language SDK maintainers, please feel free to construct the process you want/need, including the mode used for autorest and any post-autorest actions (which I gather is what the "tooling" above is meant to be). We can work later to make sure the SDK build service follows that process.

**Comment by chamons** [comment]
I believe this will be solved by moving to autorest.md files and supporting the existing _meta.json files with https://github.com/Azure/azure-sdk-for-go/pull/15111.

**Comment by RickWinter** [comment]
This is part of the Swagger->SDK work which is not being done
