### ISSUE TITLE
ARM: error messages from long running operations are not useful

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#310]
If I trigger an operation that I know that it will fail after the long running operation is started, it gives error message:

    azure:DoPollForAsynchronous 0 Polling terminated with status 'Failed'

couple of issues with this:

- in non-polling methods we clearly specify where (pkg+method) the error comes from
- there's probably an `"error"` field in the response that says `"status":"Failed"`, we should append it to the `error.message` to the error
- what is that `0`?
- "polling" word is not very user friendly

Check out my suggestion:

    arm/network.SubnetsClient#CreateOrUpdate: Long running operation 'Failed': Cannot 
      update the subnet with running virtual machines.

**Comment by brendandixon** [comment]
@ahmetalpbalkan We'll happily take pull requests. :)

**Comment by ahmetalpbalkan** [comment]
I believe the changes need to be done at the generator as well as go-autorest, is the generator code upstream?

**Comment by brendandixon** [comment]
@ahmetalpbalkan Not yet. @garimakhulbe can make all the necessary changes. I can work with her.

**Comment by garimakhulbe** [comment]
Yes, both will change. Lets hold on this. I will soon complete the generator tests and we will able to merge it to upstream. Will look into this after that.

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe please prioritize this one, people already started hitting the issue. (see reference above)

**Comment by garimakhulbe** [comment]
@ahmetalpbalkan This is fixed.
