### ISSUE TITLE
Contributing.md file is stale

### ISSUE THREAD

**Issue by leitzler** [Azure/azure-sdk-for-go#3103]
I was about to create a PR when I read the CONTRIBUTING document. It says that PRs should target `master` when in preview, and `dev` after release. How am I supposed to know if this repo is in preview?

Even better, the github pull request template asks me to check that I’m targeting `latest`..

All three exists. And I’d be glad to submit a PR to fix this confusion, if I only knew where to target it ;)

**Comment by vladbarosan** [comment]
Hi @leitzler , thanks for opening the issue. We will update the Contributing document. If you intend to make a PR please make it against the `latest` branch.  Please note, don't target the auto generated code since that will be overwritten.

**Comment by vladbarosan** [comment]
Will be fixed in v22
