### ISSUE TITLE
Correct Way to Express the Concatenation of Decorators

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-go#311]
Small issues, but I'm trying to figure out the correct way to express an idiom using the SDK that concatenates decorators, and presents them as one.  For example, I am currently decorating a client with an inspector that logs the response data.

``` go
    client := compute.NewVirtualMachinesClient(subscriptionID)
    client.ResponseInspector = byInspecting()
```

I would like to add another decorator in addition to the logging decorator, and I'm not sure that the SDK provides anything for this out-of-the-box.  I wrote the following method to do what I want, but I would prefer an intrinsic solution.

``` go
func byConcatDecorators(decorators ...autorest.RespondDecorator) autorest.RespondDecorator {
    return func(r autorest.Responder) autorest.Responder {
        return autorest.DecorateResponder(r, decorators...)
    }
}
```

Given my byConcatDecorators methods I can now attach as many decorators as I want, e.g.

``` go
    client := compute.NewVirtualMachinesClient(subscriptionID)
    client.ResponseInspector = byConcatDecorators(
                byInspecting(), 
                templateCapture())
```

I read some of the test cases and code around this feature, and I found things that are close, but not quite what I want.  (See DecorateResponder in responder.go or TestByClosing[...] tests in responder_test.go)  I suspect something exists, but my n00b eyes can't see it. :grinning:

**Comment by brendandixon** [comment]
@boumenot At present the SDK, and go-autorest, does not expose this directly. However, I like the idea. We could easily formalize your approach (which, by the way, is the correct way to do this). I would rename the "Inspectors," making them basic decorators that we could apply. Nice idea.

**Comment by ahmetalpbalkan** [comment]
@boumenot that's a cool hack. +1 for renaming the field and providing the concat decorators in go-autorest.

**Comment by brendandixon** [comment]
@boumenot @garimakhulbe can pick this up. I'll work with her as needed.

**Comment by vishrutshah** [comment]
@mcardosos Please verify first whether this has been implemented in runtime or not.

**Comment by marstr** [comment]
This is a great idea, but for the moment I'm going to throw it on the backlog.

**Comment by joshgav** [comment]
we're working on an entirely new model at https://github.com/Azure/azure-pipeline-go, so check that out. closing this, re-open if needed. thanks!
