### ISSUE TITLE
Resource Group creation/update does not support Unicode names

### ISSUE THREAD

**Issue by lagalbra** [Azure/azure-sdk-for-go#3114]
### Bug Report

- import path of package in question: `.../services/resources/mgmt/2018-05-01/resources`
- SDK version: `master` (commit ID 100a309838ef6b0878b014e5ae541c83a7cbdfaa as of this post)
- output of `go version`: n/a

- What happened?
    - Creating a Resource Group with `CreateOrUpdate` fails when the resource group name contains Unicode characters (such as Chinese characters)
- What did you expect or want to happen?
    - Documentation of allowed characters: https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions
- How can we reproduce it?
    - Call [CreateOrUpdate](https://github.com/Azure/azure-sdk-for-go/blob/100a309838ef6b0878b014e5ae541c83a7cbdfaa/services/resources/mgmt/2018-05-01/resources/groups.go#L119) with `resourceGroupName = "世"`
- Anything we should know about your environment.
    - The regular expression of characters allowed is [here in the SDK code](https://github.com/Azure/azure-sdk-for-go/blob/100a309838ef6b0878b014e5ae541c83a7cbdfaa/services/resources/mgmt/2018-05-01/resources/groups.go#L124), which [does not validate Unicode characters](https://play.golang.org/p/dSsnktzjWBd)

**Comment by jhendrixMSFT** [comment]
I believe our codegen should emit this regex as `^[-\p{L}\._\(\)]+$`.  Will investigate.

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v22.0.0

**Comment by jhendrixMSFT** [comment]
Please us https://github.com/Azure/azure-sdk-for-go/releases/tag/v22.1.0 instead as v22.0.0 introduced a regression in the regex.
