### ISSUE TITLE
How to get the NewVirtualMachinesClient?

### ISSUE THREAD

**Issue by michael1011101** [Azure/azure-sdk-for-go#3117]
Hi,
I want to create a NewVirtualMachinesClient to list all of the virtual machines in my resource group.
Is there any useful samples for this problem?

And I have tried to write the code, and set the environment, AZURE_SUBSCRIPTION_ID, AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET.
Code 
`
        vm := compute.NewVirtualMachinesClient(subscriptionID)
        authorizer, err := auth.NewAuthorizerFromEnvironment()
        if err == nil {
              vm.Authorizer = authorizer
        }

        ctx := context.Background()
        result, err := vm.List(ctx, resourceGroupName)
`
And I meet the error message:

> compute.VirtualMachinesClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'fb82f07d-72ab-47e0-a3f9-af4d5c8bad54' with object id 'fb82f07d-72ab-47e0-a3f9-af4d5c8bad54' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/4d8f6383-1247-4235-bf46-b64cc2a16b03/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute'."

**Comment by joshgav** [comment]
@michael1011101 you'll need to assign one of the Virtual Machine roles to the service principal. Here's a way to do that with az CLI, the second command is what you must run or automate:

```sh
# list available VM roles
# first `brew install jq` or `apt install jq`
az role definition list --output json | jq '.[] | select(.roleName | match("^Virtual Machine"))'

# associate a role with a principal
role=Virtual Machine Contributor
principal=https://myapp.joshgav.com
az role assignment create --role $role --assignee $principal
```

**Comment by jhendrixMSFT** [comment]
@michael1011101 were you able to get this working?

**Comment by jhendrixMSFT** [comment]
Closing as stale.  Please re-open if you need further assistance.
