### ISSUE TITLE
Support for Event Hub

### ISSUE THREAD

**Issue by simonwistow** [Azure/azure-sdk-for-go#314]
It'd be great to be able to get support for Event Hubs (or at least a util library for generating SAS Authorization headers easily).

**Comment by ahmetalpbalkan** [comment]
@simonwistow Looks like Event Hub team manages SDKs at their own centralized repo: https://github.com/Azure/azure-event-hubs Could you please consider opening an issue there?

**Comment by simonwistow** [comment]
https://github.com/Azure/azure-event-hubs/issues/113

**Comment by ahmetalpbalkan** [comment]
@simonwistow thanks!

**Comment by ahmetalpbalkan** [comment]
Closing this to continue discussion on azure-event-hubs repo. Thanks for reporting!
