### ISSUE TITLE
support authn/z via AADv2 & OpenIDConnect; support MS Graph API authorization

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#3148]
### Feature Request

* Port Microsoft Authentication Library package from [C#](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) for use with Go. 
* Support OpenIDConnect flows.
    * Provide the ID token or a `user` struct when the OIDC flow completes.
* Support [AADv2](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview) flows.
    * But continue to support `resource` scopes and test with Azure services still expecting v1.
    * Test OAuth with a [Microsoft Graph](https://developer.microsoft.com/graph) service and provide a sample.

MSAL/AADv2 also enables MSA-based logins to third-party apps but that is dependent on service-side updates too.

Related: https://github.com/Azure/go-autorest/issues/133

**Comment by Alex-Bowman-Aw** [comment]
Looks like Microsoft are planning to retire support for ADAL and are recommending migration to MSAL

**Comment by RickWinter** [comment]
Track2 supports MSAL and AADv2 with the azidentity package.
