### ISSUE TITLE
Getting 0.00000000 values when trying to query metrics against my Event Hub

### ISSUE THREAD

**Issue by scschneider** [Azure/azure-sdk-for-go#3151]
### Bug Report

Imported Package: 
"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights"

Azure SDK for Go Master branch

go version go1.11.1 darwin/amd64

I am trying to use "https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/insights/insights.go" to pull IncomingMessages from my Event Hub, but end up getting 0.00000000 results for each time series:

[Incoming Messages @ 2018-10-26T21:57:00Z - min: 0.000000, max: 0.000000 Incoming Messages @ 2018-10-26T21:58:00Z - min: 0.000000, max: 0.000000 Incoming Messages @ 2018-10-26T21:59:00Z - min: 0.000000, max: 0.000000 Incoming Messages @ 2018-10-26T22:00:00Z - min: 0.000000, max: 0.000000 Incoming Messages@ 2018-10-26T22:01:00Z - min: 0.000000, max: 0.000000]

I am pushing data to the Event Hub and when using the REST API for PowerShell, I get actual values but 0 when using Go.

Auth seems fine since I was able to slightly change values, re run and get either 400 or 401 status codes.

To reproduce, copy the config and iam packages locally and change your imports to reflect the local location.
- create a new package and copy the contents of: `https://raw.githubusercontent.com/Azure-Samples/azure-sdk-for-go-samples/master/insights/insights.go` (be sure to update import path for iam and config)
- do a `go get github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights`
- apply config values to:
clientID = {your client id}
clientSecret = {your client secret}
tenantID = {your tenant id}
subscriptionID = {your subscription id}
authorizationServerURL = "https://management.core.windows.net/"
everything else default
- from main, call GetMetricsData:
resourceId := "/subscriptions/{subscription}/resourceGroups/{resource group}/providers/Microsoft.EventHub/namespaces/{namespace}"
ctx := context.Background()
metrics := []string{"IncomingMessages"}
metrics, err := ehmonutil.GetMetricsData(ctx, resourceId, metrics)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(metrics)
- go run main.go

**Comment by jhendrixMSFT** [comment]
@scschneider What's the PS command you're using to retrieve the data?

**Comment by scschneider** [comment]
After creating the header as `$authHeader`, I run this command:
```
$request = "https://management.azure.com/subscriptions/{SUBSCRIPTION}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.EventHub/namespaces/{NAMESPACE}/providers/microsoft.insights/metrics?metricnames=incomingmessages&api-version=2018-01-01"

$result = Invoke-RestMethod -Uri $request `
    -Headers $authHeader `
    -Method Get
```

Then I can display the data with `$result.value.timeseries.data`

**Comment by shelleybess** [comment]
I am also getting occasional zero/nil values. It is not consistent. One request will succeed and the follow a minute later will return only some values.

One request the following fail:

ServerErrors
UserErrors
OutgoingBytes
ConnectionsClosed
IncomingMessages

After a few successful requests the following fail:

SuccessfulRequests
QuotaExceededErrors
ThrottledRequests
IncomingRequests
IncomingMessages
OutgoingMessages
IncomingBytes
OutgoingBytes
ActiveConnections
ConnectionsOpened
ConnectionsClosed has
CaptureBacklog
CapturedBytes
Size
SUCCREQ
FAILREQ

**Comment by jhendrixMSFT** [comment]
For event hubs the metrics don't report a min/max value which is why they're always zero.  Instead they report a total for that interval.  Here's an example of the raw response.
```json
{
  "timeStamp": "2018-11-06T17:27:00Z",
  "total": 0.0
},
```
The sample is very basic and doesn't take this into account.

**Comment by jhendrixMSFT** [comment]
Digging into this a bit more, if you run the `ListMetricDefinitions()` you'll find the following for `IncomingMessages`.
```json
    {
      "id": "/subscriptions/{id}/resourceGroups/{rg}/providers/Microsoft.EventHub/namespaces/{ns}/providers/microsoft.insights/metricdefinitions/IncomingMessages",
      "resourceId": "/subscriptions/{id}/resourceGroups/{rg}/providers/Microsoft.EventHub/namespaces/{ns}",
      "namespace": "Microsoft.EventHub/namespaces",
      "name": {
        "value": "IncomingMessages",
        "localizedValue": "Incoming Messages"
      },
      "isDimensionRequired": false,
      "unit": "Count",
      "primaryAggregationType": "Total",
      "supportedAggregationTypes": [ "None", "Average", "Minimum", "Maximum", "Total", "Count" ],
      "metricAvailabilities": [
        {
          "timeGrain": "PT1M",
          "retention": "P93D"
        },
        {
          "timeGrain": "PT5M",
          "retention": "P93D"
        },
        {
          "timeGrain": "PT15M",
          "retention": "P93D"
        },
        {
          "timeGrain": "PT30M",
          "retention": "P93D"
        },
        {
          "timeGrain": "PT1H",
          "retention": "P93D"
        },
        {
          "timeGrain": "PT6H",
          "retention": "P93D"
        },
        {
          "timeGrain": "PT12H",
          "retention": "P93D"
        },
        {
          "timeGrain": "P1D",
          "retention": "P93D"
        }
      ],
      "dimensions": [
        {
          "value": "EntityName",
          "localizedValue": "EntityName"
        }
      ]
    },
```
The default aggregation type is `Total` which is why min/max are omitted in the response.  If I specify `"Minimum,Maximum"` for the aggregation parameter I see the following in the response.
```json
{
  "timeStamp": "2018-11-06T21:13:00Z",
  "minimum": 1.0,
  "maximum": 1.0
},
```
I'll update the sample to specify this aggregation.

**Comment by jhendrixMSFT** [comment]
Sample has been updated.  Thanks for reporting this.
