### ISSUE TITLE
[Scheduler] Entire API has been deprecated in favour of an entirely different service

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#3155]
Hello,

It appears that between v21.1 and v21.3 of the SDK the scheduler api has been deprecated in favour of the Logic Apps service. I am wondering if this is a mistake as the service doesn't appear to have been [discontinued](https://azure.microsoft.com/en-us/services/scheduler/)

I also feel like this is not an appropriate use of the deprecation keyword as the API still functions and logic apps is not a replacement API, it is an entirely new service.

**Comment by tombuildsstuff** [comment]
Checking [the PR which deprecated this SDK](https://github.com/Azure/azure-sdk-for-go/pull/2888) I also don't see any information about the deprecation plan - @jhendrixMSFT would it be possible to give some more context here?

Thanks!

**Comment by jhendrixMSFT** [comment]
You're right we didn't do a good job documenting this.  I've found the following resources that hopefully provide more context.
https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-overview
https://docs.microsoft.com/en-us/azure/scheduler/migrate-from-scheduler-to-logic-apps
Looks like the scheduler APIs will be available until September 2019.
CC @joshgav

**Comment by bmperdue** [comment]
I cannot access the Scheduler in the portal anymore and I am not able to migrate my changes. What do I do?

**Comment by lirenhe** [comment]
Close it as this is a service team decision. There is no action needed on SDK team
