### ISSUE TITLE
Guard Against Empty Query Parameter Values

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-go#316]
I have had two people report strange errors in packer.

``` text
Error: azure: Service returned an error. Code="InvalidApiVersionParameter" Message="The api-version '2015-06-15' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'." Status=400
```

I was discussing the issue with @ahmetalpbalkan, and he mentioned that this is caused by query parameter values being empty.  The error message is unintuitive, and difficult to debug.  It would be better if these issues could be flagged, and a proper error message surfaced.

I assume not all parameters need a value, and empty is perfectly acceptable. I also assume there's a well known list of parameters that can never be empty that we can guard against.
### Issues:
1. https://github.com/mitchellh/packer/issues/3454
2. https://github.com/Azure/packer-azure/issues/215

**Comment by ahmetalpbalkan** [comment]
@boumenot it's still crucial to come up with a minimal repro URL so that we can see if it's missing URL segments or missing query strings or something else causing us to build up a malformed URL.

If the URL we generate is bad enough that ARM can't really parse the query arguments, then it's our problem. Otherwise we can take it up to the ARM team to provide a better error message.

**Comment by brendandixon** [comment]
@boumenot @ahmetalpbalkan Uh, the message says that the _passed_ API version is incorrect. The ARM packages hard-coded (as part of code generation) the API version for a Service and pass that among the query parameters. The value comes from the Swagger.

Which service is failing? What API calls? This should not be a possible error (assuming correct Swagger).

**Comment by ahmetalpbalkan** [comment]
@brendandixon empty string or missing argument is incorrect argument for them. This can be all services as api-version is checked at the ARM layer and if you provide malformed URL to ARM you'll get this error from all RPs.

**Comment by garimakhulbe** [comment]
@boumenot About the errors, they are for arm-storage. Storage spec is updated to new api version recently so I will regenerate the sdk. This will resolve this issues.
![image](https://cloud.githubusercontent.com/assets/9362976/14867487/95ec8b8a-0c7d-11e6-9b82-282c187f4cd2.png)

**Comment by brendandixon** [comment]
@ahmetalpbalkan The error reports back an API version. That suggest to me the string is not blank, but incorrect. How are you inferring that the string is blank?

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe I don't think you should regenerate.  I am almost sure this is a malformed URL bug but I was not able to repro. The API version is not wrong and we don't delete API versions easily. As Chris reported, it works most of the time and issues he pointedshow that in case of wrong user-supplied argument they get this error.

I'm just leaving my 2 cents experience here, but until you have a repro and see why it really happens I don't think any arguments here are going to be credible.

**Comment by ahmetalpbalkan** [comment]
There is one thing that is certain, if an user input goes to `pathParameters := map[string]interface...` and thus `autorest.WithPathParameters`, it should be checked if the string is empty or not. @garimakhulbe this is something we can improve right away.

**Comment by brendandixon** [comment]
@ahmetalpbalkan @garimakhulbe Not clear. It is legal to pass query parameters without a value. :)

**Comment by ahmetalpbalkan** [comment]
I'm talking about path components like `/{subscriptionID}/resourcegroups/}{resourceGroupsName}`

**Comment by brendandixon** [comment]
@ahmetalpbalkan Ah, those should not be empty / null.

**Comment by garimakhulbe** [comment]
@brendandixon Yes, Its legal pass query with no value. 
```
http://localhost.../abc=&xyz=
```

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe I didn't say query argument.

**Comment by garimakhulbe** [comment]
Version 2015-06-15 is coming from swagger but listed in version list.

```JSON
 {
  "swagger": "2.0",
  "info": {
    "title": "StorageManagementClient",
    "description": "The Storage Management Client.",
    "version": "2015-06-15"
  },
```

```
 The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'." Status=400
```
I think we need to report this ARM team.

**Comment by ahmetalpbalkan** [comment]
@brendandixon 

![image](https://cloud.githubusercontent.com/assets/159209/14868320/da48afee-0c81-11e6-9519-a38ae90758a9.png)

There is nothing checking for that now https://github.com/Azure/azure-sdk-for-go/blob/a1883f7b98346e4908a6c25230c95a8a3026a10c/arm/resources/resources/groups.go#L263-L280

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe unless we confirm what full URL triggers this error first, no we do not need to. That's the first thing they are going to ask you.

**Comment by boumenot** [comment]
I cannot reproduce the exact error message any more in packer-azure.  I suspect we're now robust against these failures.  (I think.)  I was able to reproduce the issue with Fiddler and manually changing the URL.

The URL in question for the above failures looks like this.

> POST /subscriptions/112ffcad-4258-4d8c-b660-45124afff157/resourceGroups//providers/Microsoft.Storage/storageAccounts/paitcus43/listKeys?api-version=2015-06-15 HTTP/1.1

Note the double slash between resourceGroups and providers.  If I remove the resource group from the URL path the error message is shown.  Removing other parts of the URL result in different and more reasonable errors IMHO.

I was the one that said empty query parameters, not @ahmetalpbalkan. I does look like variable substitution in the path is what we want to guard against.

**Comment by boumenot** [comment]
When I set the api-version to an expected value the error message changes.

> POST /subscriptions/112ffcad-4258-4d8c-b660-45124afff157/resourceGroups//providers/Microsoft.Storage/storageAccounts/paitcus43/listKeys?api-version=2016-02-01 HTTP/1.1

Yields this for an error.  This is a much more reasonable and understandable error.

{"message":"No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/112ffcad-4258-4d8c-b660-45124afff157/resourceGroups/providers/Microsoft.Storage/storageAccounts/paitcus43/listKeys?api-version=2016-02-01'."}

**Comment by paulmey** [comment]
I have a repro of this on my MSDN account: https://gist.github.com/paulmey/715979f6482e8534ecee58524af5a5f8#file-gistfile1-txt

**Comment by paulmey** [comment]
I think I figured it out. This is failing because the uri is broken. The resource group name is empty and hence, the path becomes `.../resourceGroups//providers/Microsoft.Storage/storageAccounts`. Not sure which part of ARM would pick that up, but if you then use one of the proposed versions, it replies `autorest/azure: error response cannot be parsed: "{\"message\":\"No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/a0d401b5-25c9-42b5-96eb-3486b828a25a/resourceGroups/providers/Microsoft.Storage/storageAccounts/paulmeyhashiconf/listKeys?api-version=2016-06-01'.\"}"`. @boumenot, I'll add a check for the resource group to the packer builder. I think we can close this issue?

**Comment by paulmey** [comment]
+1 empty resourceGroup parameter is never valid

**Comment by brendandixon** [comment]
@paulmey I believe @garimakhulbe is adding input parameter validation that may cover this case. Check with her to see.

**Comment by garimakhulbe** [comment]
I added null check for required parameter for some tests in generator. I will add the same for empty parameter.

**Comment by vishrutshah** [comment]
Closing this one as seems to be fixed. Feel free to reopen if you find any issues. Thanks!
