### ISSUE TITLE
Setter functions for Azure SDK Go? | Used for unit testing

### ISSUE THREAD

**Issue by kmachspeed** [Azure/azure-sdk-for-go#3164]
### General Question

Hi, few questions:

Looking to mock some functions for unit testing but could not find an interface for the functions in `services/network/mgmt/2018-08-01/network` (i.e. ListComplete). If it isn't in there somewhere, are there plans to add one?

It also seems like the return values which are structs have unexported fields, which makes it difficult to mock the response of the functions. Is there some kind of setter function somewhere in the code or someway of setting the values of those fields?

For example, here's the getter function for the struct field `page` in `PublicIPAddressListResultPage` in `services/network/mgmt/2018-08-01/network/models.go`.

I'd like to set `page.pialr` in my unit tests, but could not find a function for that

```
// Response returns the raw server response from the last page request.
func (page PublicIPAddressListResultPage) Response() PublicIPAddressListResult {
	return page.pialr
}
```

Using
`Go version 1.11`

Thanks!

**Comment by apratina** [comment]
@jhendrixMSFT : Any suggestion on this one? Is there a setter function available for setting the un-exported fields in the struct?

**Comment by jhendrixMSFT** [comment]
Regarding interfaces, this has come up before: https://github.com/Azure/azure-sdk-for-go/issues/409.  One issue that became apparent is that some of the interfaces could be quite large making them tedious to mock (I don't think splitting into multiple smaller interfaces is a feasible solution).  Happy to hear any feedback/suggestions.
Regarding pageable types unfortunately I don't have a good answer for you.  In retrospect we should have made this an interface.  I think the best we could do at present is add a constructor for the pageable and iterator types.

**Comment by jhendrixMSFT** [comment]
This is scheduled to ship in v23 of the SDK later this month.

**Comment by jhendrixMSFT** [comment]
Fix is available in https://github.com/Azure/azure-sdk-for-go/releases/tag/v23.0.0
