### ISSUE TITLE
Deletion of user assigned identities not supported 

### ISSUE THREAD

**Issue by parikhamol** [Azure/azure-sdk-for-go#3165]
__import path__ :`github.com/Azure/azure-sdk-for-go/services/msi/mgmt/2015-08-31-preview/msi/userassignedidentities.go`

__SDK version__ : master

 `commit id: 100a309838ef6b0878b014e5ae541c83a7cbdfaa`

__Go version__: `1.10.1 darwin/amd64`

On calling the delete api for user assigned identities i get the following error message :

`Error deleting MSI. Error: msi.UserAssignedIdentitiesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\'InvalidApiVersionParameter\\' Message=\\'The api-version '2015-08-31-preview' is invalid. The supported versions are '2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.``

However, in the go sdk none of the above supported versions have the msi package. The only one that has it is __2015-08-31-preview.__

There seems to be a mismatch of version because creating a user assigned identities with the same api version was successful.

Azure documentation for curl command to delete the user assigned identities also mentions that same API version . https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-manage-ua-identity-rest

**Comment by jhendrixMSFT** [comment]
Can you please provide the request headers and body for the API call that's failing?  Easiest way to do that is to enable built-in logging through environment variables, see the instructions [here](https://github.com/azure/azure-sdk-for-go#built-in-basic-requestresponse-logging).  Once we have the request payload I can forward it on to the service team so they can investigate.

**Comment by parikhamol** [comment]
https://github.com/Azure/azure-sdk-for-go/blob/ca4654c50e30248fa542c1f0dd07fbde21d9b9a2/services/preview/msi/mgmt/2015-08-31-preview/msi/userassignedidentities.go#L167

If you look at this line, the API version is hardcoded. Since this API version isn't part of the supported version i don't see how this API call will work.

**Comment by jhendrixMSFT** [comment]
The packages in the Go SDK are generated from OpenAPI specs.  For this API, defined [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/msi/resource-manager/Microsoft.ManagedIdentity/preview/2015-08-31-preview/ManagedIdentity.json#L282), it explicitly states API version `2015-08-31-preview` [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/msi/resource-manager/Microsoft.ManagedIdentity/preview/2015-08-31-preview/ManagedIdentity.json#L4).  So either the spec is wrong or the service is broken.  The service team has asked for a sample request body to help in their diagnosis.  Do you have one available?

**Comment by jhendrixMSFT** [comment]
Note that there's a new, stable, API version for identity management.  Can you take a look and see if it resolves your issue?
github.com/Azure/azure-sdk-for-go/services/msi/mgmt/2018-11-30/msi

**Comment by jhendrixMSFT** [comment]
@parikhamol wondering if this is still a problem for you and/or the new API version resolved it for you?
