### ISSUE TITLE
Azure can return Int instead string

### ISSUE THREAD

**Issue by sylr** [Azure/azure-sdk-for-go#3171]
### Bug Report

```
"github.com/Azure/azure-sdk-for-go/services/batch/mgmt/2017-09-01/batch"
master
go 1.11
```

I've been getting this error since yesterday using [`PoolClient.ListByBatchAccount(...)`](https://github.com/sylr/prometheus-azure-exporter/blob/master/pkg/azure/batch.go#L76)

```Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field ResizeOperationStatus.nodeDeallocationOption of type batch.ComputeNodeDeallocationOption' JSON```

I've looked at the JSON sent by Azure and there is indeed an Int present in the JSON (twice out of dozens of occurences) where the lib is expecting a string:

```
                "resizeOperationStatus": {
                    "nodeDeallocationOption": 0,
                    "resizeTimeout": "PT15M",
                    "startTime": "2018-10-29T13:51:26.7338118Z",
                    "targetDedicatedNodes": 1
                },
```

According to the [doc](https://github.com/Azure/azure-sdk-for-go/blob/master/services/batch/2018-08-01.7.0/batch/models.go#L3122-L3129) `nodeDeallocationOption` should only be a string but it obviously isn't.

Thank you

**Comment by jhendrixMSFT** [comment]
Thanks for reporting this, it's a problem with the swagger definition.  I've ported this issue to the specs repo, https://github.com/Azure/azure-rest-api-specs/issues/4356.
