### ISSUE TITLE
panic: Error response from Azure. Code: BadRequest, Message: The location constraint is not valid

### ISSUE THREAD

**Issue by sharminakteranee** [Azure/azure-sdk-for-go#318]
I'm facing the problem while Creating a Linux Virtual Machine.

"panic: Error response from Azure. Code: BadRequest, Message: The location constraint is not valid

goroutine 1 [running]:
panic(0x761640, 0xc8203ce860)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
main.main()
	/home/tiger123/Desktop/azure.go:32 +0x319
exit status 2"

Any one know why this error appearing to me ??

**Comment by colemickens** [comment]
What value are you putting in the `VirtualMachine` struct for `Location`?

**Comment by sharminakteranee** [comment]
I used "West US"

**Comment by ahmetalpbalkan** [comment]
Do you see west us in "azure location list" command? It might not be available to your subscription.

**Comment by sharminakteranee** [comment]
I got this---
$ azure location list
error:   'location' is not an azure command. See 'azure help'.

**Comment by ahmetalpbalkan** [comment]
@sharminakteranee hmm maybe run `azure config more arm` first and then run it?

**Comment by ahmetalpbalkan** [comment]
@sharminakteranee have you been able to find out the locations available to your subscription?

**Comment by sharminakteranee** [comment]
"West Europe" was default, But I also created for "West US".

**Comment by ahmetalpbalkan** [comment]
@sharminakteranee I'm not sure I follow. So did you see "West US" in the locations list available to your subscription? Does your code work now?

**Comment by sharminakteranee** [comment]
no, not working. I think I've to change my default subscription.
