### ISSUE TITLE
Event Hub Namespace Metrics occasionally return nil values

### ISSUE THREAD

**Issue by shelleybess** [Azure/azure-sdk-for-go#3192]
### Bug Report

- Package and other info:

github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights
PROJECT: github.com/Azure/azure-sdk-for-go
VERSION: v19.1.0
REVISION: 4e8cbbf
Go Version: 1.10.2 darwin/amd64

- What happened?

Using the SDK to get metrics results in intermittent nil values. The metrics with no value are not consistent. For example, one pull results in the following having no value:  

ServerErrors
UserErrors
OutgoingBytes
ConnectionsClosed
IncomingMessages  

The next few may be successful, then the following are nil:

SuccessfulRequests
QuotaExceededErrors
ThrottledRequests
IncomingRequests
IncomingMessages
OutgoingMessages
IncomingBytes
OutgoingBytes
ActiveConnections
ConnectionsOpened
ConnectionsClosed has
CaptureBacklog
CapturedBytes
Size
SUCCREQ
FAILREQ  

We catch the nil values and simply omit that data point, but it results in breaks in our data.

- What did you expect or want to happen?

Successfully retrieve metric values.

- How can we reproduce it?

Use the SDK to retrieve all metrics from an Event Hub namespace in one minute intervals logging the metric values.

![image](https://user-images.githubusercontent.com/24594686/47820246-f6931780-dd2a-11e8-98b5-c6b8e47a1373.png)

- Anything we should know about your environment.

**Comment by lirenhe** [comment]
@shelleybess, as the issue have been there for long time, do you still face the same issue again? If so, could you provide the code that could reproduce this issue?
