### ISSUE TITLE
Azure Service Bus Topics/Queue SDK

### ISSUE THREAD

**Issue by michaelbironneau** [Azure/azure-sdk-for-go#320]
Hello,

Would you entertain a PR for Service Bus Topics/Queue client implementation? I cobbled one together for a project (see [here](https://github.com/michaelbironneau/asbclient)). It could certainly do with some improvement but roughly speaking is this something you'd consider including?

Thanks

**Comment by ahmetalpbalkan** [comment]
@michaelbironneau I think we are generally open to it, although I believe most of us (Go SDK authors) have not used Service Bus before.

Our north star is to code-generate the data plane SDKs (blob, table, queue and servicebus), however that is something we are not actively pursuing and rest of the `storage/` package is currently hand written. We also have merged a community-contributed Table SDK  (#217) this week. 

If you think you have something good enough that will do the job for 90% of the potential users, I am personally open to review it. However I suggest deploying it and using it in production first before sending the pull request.

**Comment by pmcatominey** [comment]
I believe this is fixed now as of v4 beta

**Comment by garimakhulbe** [comment]
@michaelbironneau we have servicebus in version v4 now. 
@pmcatominey thanks for reminding on this.

Closed.
cc: @jhendrixMSFT @mcardosos
