### ISSUE TITLE
Feature Request: Support setting shared access policies in IoT Hub

### ISSUE THREAD

**Issue by polarking** [Azure/azure-sdk-for-go#3200]
### Feature Request

Hi!

It would be great to support setting up Shared access policies for IoT Hub through the SDK.
Initially it would be great to use as part of terraform, and is initially why I'm requesting this feature: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2201

Thanks!

**Comment by jhendrixMSFT** [comment]
Hello!  Looking at the [REST API docs]https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security) I believe you can do this through the [IotHubResourceClient.CreateOrUpdate method](https://github.com/Azure/azure-sdk-for-go/blob/master/services/iothub/mgmt/2018-04-01/devices/iothubresource.go#L217), specifically by setting the [AuthorizationPolicies](https://github.com/Azure/azure-sdk-for-go/blob/master/services/iothub/mgmt/2018-04-01/devices/models.go#L1017) field in your `IotHubProperties`.  Can you have a look to see if this works?

**Comment by ArcturusZhang** [comment]
Staled issue, closing
