### ISSUE TITLE
Resource group names can't contain numbers anymore since v22.0.0

### ISSUE THREAD

**Issue by jomeier** [Azure/azure-sdk-for-go#3214]
Hi,

with Version v22.0.0 resource group names can't contain numbers anymore. Escpecially if I create a deployment with 

https://github.com/Azure/azure-sdk-for-go/blob/v22.0.0/services/resources/mgmt/2018-02-01/resources/deployments.go

CreateOrUpdate(...)

the validation of my resource group name fails because it contains letters and numbers. 

Versions below v22 work as expected.

The problem seems to be introduced by this PR here:

https://github.com/Azure/azure-sdk-for-go/issues/3114

Best regards, 

Josef

**Comment by jhendrixMSFT** [comment]
Just posted a fix in https://github.com/Azure/azure-sdk-for-go/releases/tag/v22.1.0, terribly sorry about that!
