### ISSUE TITLE
Azure Polling Error - Unable to obtain polling URI for POST 

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-go#328]
A user of Packer reported the following error in his [PR](https://github.com/mitchellh/packer/pull/3528)

```text
==> azure-arm: Powering off machine ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-b1tmy27mlh'
==> azure-arm:  -> ComputeName       : 'pkrvmb1tmy27mlh'
==> azure-arm: Capturing image ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-b1tmy27mlh'
==> azure-arm:  -> ComputeName       : 'pkrvmb1tmy27mlh'
==> azure-arm: azure#updatePollingState: Azure Polling Error - Unable to obtain polling URI for POST : StatusCode=0
```

He's reported that he's seen this issue a couple of time.  Capture is a long running task, and the code just waits  for it to complete.

```go
_, err = s.client.Capture(resourceGroupName, computeName, *parameters, cancelCh)
if err != nil {
    return err
}
```

I suspect the SDK's polling has an edge case that it isn't handling.

**Comment by brendandixon** [comment]
@boumenot Can we get more details? It's not really possible to address this without more data.

**Comment by boumenot** [comment]
I'll reach out for details, and see if I can reproduce this on my end.

**Comment by tasquith** [comment]
Hi,

I've just ran the same case again, with the debug flag set.

Please find the gist below containing my output from Charles Proxy.

https://gist.github.com/tasquith/de1a91fe08e852e1c680988e5dc61baf 

The error on the command line is as follows:

==> azure-arm: Capturing image ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-5kykx0hyl1'
==> azure-arm:  -> ComputeName       : 'pkrvm5kykx0hyl1'
==> azure-arm: compute.VirtualMachinesClient#Generalize: Failure responding to request: StatusCode=409 -- Original Error: azure: Service returned an error. Code="OperationNotAllowed" Message="Operation 'generalize' is not allowed on VM 'pkrvm5kykx0hyl1' since the VM is running. Please power off explicitly in case you shut down the VM from inside the guest operating system." Status=409

Cheers,

Tom

**Comment by tasquith** [comment]
Looking at the GIST, it seems like the container name containing caps caused it - I changed it to lowercase and it ran again with no issues.

**Comment by boumenot** [comment]
Argh.  I will add appropriate checks to Packer to ensure we catch, and handle this better.  Let me find the right internal team to, and ask them about this.  We should have been able to catch this sooner.

**Comment by boumenot** [comment]
After further review, this is my issue.  The Packer code checks for an error, but discards the HTTP response.  

The code looks like this

```go
_, err := s.client.Capture(resourceGroupName, computeName, *parameters, cancelCh)
if err != nil {
    return err
}
```

The error contains this message.

```text
azure#updatePollingState: Azure Polling Error - Unable to obtain polling URI for POST : StatusCode=0
```

But the response contains this error message.
```text
{
  "error": {
    "code": "InvalidParameter",
    "target": "vhdPrefix",
    "message": "'tom-service-DISCOVERY-server-base-v1.core.local' is not a valid captured VHD blob name prefix. A valid prefix matches regex '^[^_\\W][\\w-._]{0,23}(?<![-.])$'."
  }
}
```

I always **assumed** (and you know that's bad) that the error would always contain the error, but it does not.  The code must account for both cases.

@brendandixon or @garimakhulbe Should I give priority to the HTTP error over the error returned by the method call, or should I combine both when surfacing it to the user.  There's an APIError struct under arm/compute/models.go, so my plan is to use this when decoding HTTP errors for Compute APIs.  

I briefly reviewed the code for APIError, and I can't see how it's connected to existing calls.  Is it intended to be?

**Comment by boumenot** [comment]
Here's a snippet from a capture.

```text
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 344
Content-Type: application/json; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-served-by: f8d979a0-4652-4ce7-a380-0856bf3e34db_131067927349331832
x-ms-request-id: d9425ce1-3246-4afc-ae8f-43c6fec5f9ed
Server: Microsoft-HTTPAPI/2.0
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1193
x-ms-correlation-request-id: 132355c4-f929-429c-b5ec-95b078ff6f0f
x-ms-routing-request-id: CENTRALUS:20160516T180210Z:132355c4-f929-429c-b5ec-95b078ff6f0f
Date: Mon, 16 May 2016 18:02:09 GMT

{
  "error": {
    "code": "InvalidParameter",
    "target": "destinationContainerName",
    "message": "Container name images--ASADF is invalid. Container names must be 3-63 characters in length and may contain only lower-case alphanumeric characters and hyphen. Hyphen must be preceeded and followed by an alphanumeric character."
  }
}
```

**Comment by boumenot** [comment]
Thanks!

**Comment by dothebart** [comment]
hm, I just saw this over here when creating an image with packer.

**Comment by dothebart** [comment]
ok, scratch that - my packer was to old.
