### ISSUE TITLE
AAD Domain Service creation fails with 400/InvalidRequestContent

### ISSUE THREAD

**Issue by tiwood** [Azure/azure-sdk-for-go#3285]
### Bug Report

- github.com/Azure/azure-sdk-for-go/services/domainservices/mgmt/2017-01-01/aad
- SDK version v21.3.0
- go version go1.11.2 darwin/amd64

I'm trying to create Azure AD Domain Services with the SDK.

I'm doing the following:

```go
properties := aad.DomainServiceProperties{
		TenantID:   &tenantID,
		DomainName: &domainName,
		VnetSiteID: &virtualNetworkID,
		SubnetID:   &subnetID,
}

//create the Azure AD Domain Services resource (long-running operation)
future, err := client.CreateOrUpdate(ctx, resourceGroupName, domainName, properties)
```

The following error is returned:

aad.DomainServicesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'tenantId' on object of type 'ResourceDefinition'. Path 'tenantId', line 1, position 12.'."

Things I've tried

- Progressively removed properties from the properties object
- If the properties object is empty, the API asks for 'Location'
- If just 'Location' is given the requests fails after 1 minute with a null reference (TenantID is missing)

I assume the API expects something different from the provided body.

**Comment by vladbarosan** [comment]
@tiwood it seems there was an issue with the service specs. this has been fixed here https://github.com/Azure/azure-rest-api-specs/pull/4353

Since its a breaking change for the sdk its going to make its way in the next major bump of the sdk at the end of the month,.

**Comment by tiwood** [comment]
@vladbarosan thank you for the heads up.
