### ISSUE TITLE
How to create/delete resources group by azure-sdk-for-go/management

### ISSUE THREAD

**Issue by valeravorobjev** [Azure/azure-sdk-for-go#329]
Hi! Please, tell me how to create/delete resources group by azure-sdk-for-go/management

And I want to create vm, hosted service, storage service etc **at one resource group**!

**Comment by marstr** [comment]
This thread seems to have gone neglected, and for far too long. You can find examples of how to do this operation here: [Sample](https://github.com/Azure/azure-sdk-for-go/blob/master/management/examples/example.go)

In general, I suspect you'd be better served now by using the new ARM model. You can find an example of how to do a lot of these examples by heading over to [Azure-Samples for Go](https://github.com/Azure-Samples?utf8=%E2%9C%93&q=&type=&language=go). In particular you may want to checkout the [portion on adding a Virtual Machine](https://github.com/Azure-Samples/virtual-machines-go-manage).

If you don't feel like this sufficiently answered your question, feel free to re-open.
