### ISSUE TITLE
Support for Azure Stack endpoints

### ISSUE THREAD

**Issue by manojvas** [Azure/azure-sdk-for-go#330]
It looks like the Environment endpoints are hard-coded all over the code. Is there a way or support in SDK to point to Azure stack endpoints ? For e.g. In xPlat CLI and Powershell, you can change enpoints by using command

 azure account env add AzureStack --resource-manager-endpoint-url "https://api.azurestack.local" --management-endpoint-url "https://api.azurestack.local" --active-directory-endpoint-url  "https://login.windows.net" --portal-url "https://portal.azurestack.local" --gallery-endpoint-url "https://portal.azurestack.local" --active-directory-resource-id "https://azurestack.local-api/" --active-directory-graph-resource-id "https://graph.windows.net/"

Is a similar support available in GO-SDK ?

**Comment by brendandixon** [comment]
@manojvas The ARM packages definitely allow you to set the base URI to use. Each client created (e.g., such as the VirtualMachinesClient) has a factory method accepting a base URI (e.g., https://github.com/Azure/azure-sdk-for-go/blob/master/arm/compute/virtualmachines.go#L41). That should do it!

I hope this helps.

**Comment by manojvas** [comment]
@brendandixon  Thank you for the prompt response. Glad to know that the support exists today. I will try this out today with with Azure Stack.

**Comment by colemickens** [comment]
@manojvas Do all Azure Stack installations use the same set of endpoints? Or are the hostnames customized to the user's environment? If the same DNS names are use for all Azure Stack setups, we could add an Azure Stack Environment definition.

**Comment by manojvas** [comment]
I believe the host names(alteast the ARM endpoints) are customized for users environment as these endpoints reside on-prem. Adding and environment definition which can be modified easily will be a helpful.

**Comment by colemickens** [comment]
If the endpoints are all different then there's not much point in adding it to the SDK. You can simply define a new AzureEnvironment struct with the appropriate values and begin using it the same way the existing Environments are used.

**Comment by ahmetalpbalkan** [comment]
@manojvas it appears like @colemickens reply answers your question. You should be able to use the `AzureEnvironment` struct to configure the API endpoints. Let us know if this does not solve your problem.
