### ISSUE TITLE
Got InvalidHeaderValue with PutPage

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#331]
PutPage returns an InvalidHeaderValue error.

StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.

What could I be doing wrong?

**Comment by colemickens** [comment]
Can you show us the code you're executing or the request/response?

**Comment by colemickens** [comment]
Additionally, if it's helpful, here's an example of someone using PutPage: https://github.com/Microsoft/azure-vhd-utils-for-go/blob/7db4795475aeab95590f8643969e06b633ead4ec/upload/upload.go#L82

**Comment by ahmetalpbalkan** [comment]
@mcardosos make sure you read the documentation at https://msdn.microsoft.com/en-us/library/azure/ee691975.aspx People often make mistake and put random values to the Range header, it should be multiples of 512 bytes such as 0-511, 512-1023 etc.

**Comment by mcardosos** [comment]
Ok, I read the documentation more carefully. Thanks.
