### ISSUE TITLE
Deleting a Virtual Machine

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#332]
Hi

when i specify the parameters for a virtual machine, a storage blob gets created for the disk. When the VM is Deleted, the storage blob doesn't get deleted

Is Delete the correct method to call for VMs? Or should we use something like Deallocate first?

Paul

**Comment by brendandixon** [comment]
@stack72 Good question. We don't know. You may try filing the same question against the related Swagger. If you do not get a response, re-raise it here and we'll see what we can learn.

**Comment by ahmetalpbalkan** [comment]
@stack72 In Azure Resource Manager mode (`Microsoft.Compute` resource provider), there is no option to delete the blob (at least as of today). This was a little bit disappointing for me as well when I figured it out.

I advise inspecting the VM first, figuring out its OS disk, deleting the VM itself and finally deleting its OS disk.

**Comment by stack72** [comment]
Hi @ahmetalpbalkan 

thanks for the response here. So I don't think it's quite that simple. All we have for a VHD is a uri - are you suggesting we try and split the URI to find the resource group and the storage account and the container name? That could work (but it's very hacky). We need all of those pieces to delete a blob.

I guess, for me, the functionality I would expect would be to be able to pass a flag to the os_disk, something like delete_on_termination and then Azure would clean that up for me. 

P.
