### ISSUE TITLE
Display the Best Error Message

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-go#334]
This is similar to a previous [issue](https://github.com/Azure/azure-sdk-for-go/issues/328) that I logged.

Azure returns a better error message than the one returned by the SDK.  Unfortunately, it returns a status of 200/OK, which means you have to look inside the body to determine that it's an error. :frowning: 

### Request
This request is part of the polling that occurs when doing a deployment.

```text
GET https://management.azure.com/subscriptions/112ffcad-4258-4d8c-b660-45124afff157/resourcegroups/packer-Resource-Group-f027xktypx/providers/Microsoft.Resources/deployments/pkrdpf027xktypx/operationStatuses/08587374643198384305?api-version=2015-11-01 HTTP/1.1
Host: management.azure.com
User-Agent: Azure-SDK-for-Go/2.1.1-beta arm-resources/2015-11-01;packer/0.10.2.dev (8d5dadb6d358e3e97caf522b9f30a56bf6d88f5a+CHANGES)
Authorization: Bearer eyJ0eXAiOiJKV1Q.....dciOq18jB2h_DA
Accept-Encoding: gzip
```

### Response
```text
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Vary: Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 14998
x-ms-request-id: 2ed97f97-63ba-4b9d-894f-ab42978fd4e1
x-ms-correlation-request-id: 2ed97f97-63ba-4b9d-894f-ab42978fd4e1
x-ms-routing-request-id: CENTRALUS:20160525T021706Z:2ed97f97-63ba-4b9d-894f-ab42978fd4e1
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Wed, 25 May 2016 02:17:06 GMT
Content-Length: 469

{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"}]}}
```

**Comment by ahmetalpbalkan** [comment]
@boumenot what's the error message SDK is giving you in this case? this particularly looks odd as it's HTTP 200 and status:Failed.

**Comment by boumenot** [comment]
It is similar to this.

```text
Build 'azure-arm' errored: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details."
```

**Comment by boumenot** [comment]
Yet another instance of this.  The code was trying to fetch a secret from KeyVault.  Azure returned a 403, but the SDK did not return an error.

**Comment by colemickens** [comment]
The SDK has KeyVault support? [I thought we were still lacking even a Swagger spec?](https://github.com/Azure/azure-rest-api-specs/issues/67) Or is it that hitting KeyVault API using `go-autorest` exhibits this undesired behavior too?

**Comment by boumenot** [comment]
Oh snap!  You're right @colemickens.  I took the code from you originally - I should have known that.  Disregard my KeyVault addendum, but the original issue still stands.

**Comment by ahmetalpbalkan** [comment]
Yeah this is mostly because all Resource Providers introduce their own `error` object schema, often not defined in the Swagger specs.

C# SDK does manual work creating certain error types from Swagger and manually mapping them to responses of RPs. We currently don't do that. Perhaps in the `error` object we can save the full JSON string and offer that in the string dump?

**Comment by paulmey** [comment]
This error and its `details` property are actually [defined in swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-02-01/swagger/resources.json#L1630). So no reason not to have it... :wink:
I think @ahmetalpbalkan's proposal to save the raw json of the error response to allow lazy decoding should work excellently in most cases.

**Comment by ahmetalpbalkan** [comment]
@paulmey unfortunately, not for all RPs... We can define a nillable field for details and print it in the error if there is data... Please feel free to send a PR to go-autorest.

**Comment by garimakhulbe** [comment]
"details" text is added to response error object in sdk. We can close this issue. 

```
error:
     code:
     message:
     details:
````

**Comment by boumenot** [comment]
w00t!

**Comment by shyam2j** [comment]
Hello All,

I am getting similar error. Can someone suggest me where to check for more detailed error logs?
Below is the error I am getting. I tried giving image_version, but couldnt help.

--> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -
- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Me
ssage="At least one resource deployment operation failed. Please list deployment operations for deta
ils. Please see https://aka.ms/arm-debug for usage details."

Thanks in advance
Shyam
