### ISSUE TITLE
Incorrect example code for ARM - azure.AzureResourceManagerScope is missing

### ISSUE THREAD

**Issue by jen20** [Azure/azure-sdk-for-go#337]
The example code in the README for the ARM library shows the following for initializing:

```go
  spt, err := helpers.NewServicePrincipalTokenFromCredentials(c, azure.AzureResourceManagerScope)
  if err != nil {
    log.Fatalf("Error: %v", err)
  }
```

Where the `azure` namespace comes from the following import:

```
  "github.com/Azure/go-autorest/autorest/azure"
```

The `azure.AzureResourceManagerScope` symbol was removed in Azure/go-autorest#053f51b, in favour of nesting it inside Environment structures.

**Comment by ahmetalpbalkan** [comment]
related: #274, we should update READMEs and examples to bring them up to date.

**Comment by colemickens** [comment]
I  agree we should fix this. @jen20 if it helps in the meantime, you can consult this example which is built as part of the CI for go-autorest. https://github.com/Azure/go-autorest/blob/master/autorest/azure/example/main.go

**Comment by garimakhulbe** [comment]
This snippet is removed in updated README. Closing this.
