### ISSUE TITLE
Virtual Machine Managed Disks Azure Stack

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#3373]
### Service Package Request

Hi, We are looking to implement managed disk support in the Azure Stack provider for terraform as it was added in the 2018-08 Stack API update. However it appears that in the latest versioned profile (2017-03-09) support isn't there and the 2018 profiles haven't been added yet.

**Comment by jhendrixMSFT** [comment]
Related to https://github.com/Azure/azure-sdk-for-go/issues/2027.

**Comment by jhendrixMSFT** [comment]
The 2018 profile is in the `latest` branch and will be included with v24 of the SDK later this month.

**Comment by jhendrixMSFT** [comment]
The 2018-03-01 stack profile is now available in v24 of the SDK.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT 👋 sorry to re-raise an old issue; whilst profile `2018-03` got added during v24 of the SDK, this issue was originally about the `2018-08` profile, which features support for Managed Disks. Would it be possible to re-open this and add support for that profile?

Thanks!

**Comment by jhendrixMSFT** [comment]
I don't see a `2018-08` profile defined.
https://github.com/Azure/azure-rest-api-specs/tree/master/profile
Do you have a link to this profile?  I can follow up with the stack team about it.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT it's documented here: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles

> Yyyy-mm-dd-hybrid
> This profile is released in March and September every year. It has optimal stability and compatibility with various clouds. Yyyy-mm-dd-hybrid is designed to target global Azure and Azure Stack. The Azure API versions listed in this profile will be the same as the ones that are listed on Azure Stack. You can use this profile to develop code for hybrid cloud solutions.

Given that timeline I'm assuming that a `2018-08` Profile exists (but is missing from the Swagger repo) and that there's a `2019-03` Profile coming in the not-too-distant future, but I maybe mis-understanding that?

**Comment by jhendrixMSFT** [comment]
@bganapa to comment

**Comment by bganapa** [comment]
Thanks @jhendrixMSFT for looping me in. @tombuildsstuff , we do not have 2018-08 profile for azurestack. 2018-03 profile got released only in august of 2018 though we started coining that in March of 2018 for various reasons.  So the managed disk support is available in 2018-03-01-hybrid profile itself.  2019-03-01-hybrid profile is in the works and we expect that to be released by May first week.
