### ISSUE TITLE
Return detailed error on deployment failure

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-sdk-for-go#339]
On a deployment `CreateOrUpdate`, a possible error return JSON looks like this:
``` json
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"StorageAccountTypeNotSupported\",\r\n        \"message\": \"Disk osdisk uses blablob which is a Blob storage account. Please retry with General purpose storage account.\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}
```
However useful, the `details` get lost in translation. This object is deserialized into a `operationResource` by `DoPollForAsynchronous`/`updatePollingState`, the error ends up being deserialized as a `ServiceError` struct, which does not handle the `details` array.

**Comment by paulmey** [comment]
Would this fix it in the generated code? 
https://github.com/Azure/azure-rest-api-specs/pull/267/commits/18935a975900118c8517c4600b7499cb85c12821

**Comment by garimakhulbe** [comment]
@paulmey this is done.

**Comment by paulmey** [comment]
Thanks, I'll update my dependencies and profit from your hard work! :+1:
