### ISSUE TITLE
Loadbalancer, backend pool allocation through sdk failure

### ISSUE THREAD

**Issue by HasnainRaza14** [Azure/azure-sdk-for-go#3395]
I am trying to create a loadbalancer using this code:

https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/network/loadbalancer.go

The loadbalancer gets created but, I do not see any support available for backend pools for the loadbalancer in sdk, like how to configure backend pool IP's where the load balancer will be sending requests. 

I need to create a new backend pool for my loadbalancer through sdk, is there anyway I can do that?

**Comment by jhendrixMSFT** [comment]
Looking at [LoadBalancersClient.CreateOrUpdate](https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2017-09-01/network/loadbalancers.go#L48) it looks to me that you specify it in the `LoadBalancer` parameter, specifically in the `LoadBalancerPropertiesFormat.BackendAddressPools` slice.  Can you try it?

**Comment by ArcturusZhang** [comment]
Closed due to no response from the author
