### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jen20** [Azure/azure-sdk-for-go#34]
Currently as I'm implementing new features I'm writing local test harnesses. What is the current testing story to get these more automated?

**Comment by ahmetalpbalkan** [comment]
@jen20 current story is we have unit tests for "logic" parts in the management SDK. Other than that we have an integration suite that covers important methods but one must set up the environment and certs correctly to run these tests (and it will run on user's machine) but that's the best we came up with lately.

Storage SDK is blob-only and all the functionality is tested against the real API in the Travis-CI.

**Comment by tombuildsstuff** [comment]
@ahmetalpbalkan given it's been a while, are there any expanded thoughts on testing as a whole for the SDK?

I can't help feeling the bugs that I'm raising (e.g. #413 / #426) would be caught by some basic Integration/usage tests. As I can see it right now there's a few hand-rolled tests for a few isolated components of the SDK - but not much else.

Whilst I hate to suggest generating more code - would it make sense to auto-generate some Integration tests for now via AutoRest? I feel that'd catch the low hanging fruit for incorrect types? A side effect is that it'd also give some nice usage documentation for the API as a whole?

Once these exist it'd be nice to start running integration tests against the real API. As discussion was previously raised in #36 - would MS be able/willing to support this?

**Comment by ahmetalpbalkan** [comment]
@mcardosos can answer.

**Comment by mcardosos** [comment]
Hello @tombuildsstuff 
About testing the SDK, our plan is to test it in three different points. Take into account this is a WIP
- Test the swaggers against the APIs. This way we can find if the swagger is reflecting correctly the API behavior. The issues you have reported would be found this way :)
- Test AutoRest. 
- Test the SDK, in a similar way in which you are suggesting. This would catch bugs that escaped testing the swaggers against the APIs and the AutoRest tests.

**Comment by vishrutshah** [comment]
@mcardosos Please update test strategy into README.

**Comment by joshgav** [comment]
this issue is a bit stale, we're working on the items listed. closing, thanks!
