### ISSUE TITLE
ARM Resource ignores api version param

### ISSUE THREAD

**Issue by zlepper** [Azure/azure-sdk-for-go#340]
Looking at the following line of code: https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/resources.go#L81

The apiVersion parameter that is passed to the call is completely ignored. 
This seems like quite an oversigt, as it prevents user from using other versions of the api, even though the code seems to be should be able to support it.

**Comment by garimakhulbe** [comment]
API parameter should never be exposed to user and we will remove it from method parameters. Every new release of SDK always ties to a single version of api and you can find that version inside client.go for each resource provider.
https://github.com/Azure/azure-sdk-for-go/blob/master/arm/authorization/client.go#L30

**Comment by garimakhulbe** [comment]
Api-version is not exposed to users now. Closing this.
