### ISSUE TITLE
Documentation for Container Service Exists...

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#345]
but there is nothing in the go sdk?

Is this something that is planned?

P.

**Comment by ahmetalpbalkan** [comment]
@rgardler @anhowe any timelines for a Swagger spec for Container Service RP?

**Comment by rgardler** [comment]
The Swagger specs for ACS were published on 6/28

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/containerService.json

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe do you think we can code generate using the new specs soon?

**Comment by stack72** [comment]
Hi all

Any thoughts on this?

P.

**Comment by garimakhulbe** [comment]
@stack72 We will add this by end of this week.

**Comment by garimakhulbe** [comment]
This is added in sdk version v3.1.0-beta.
https://github.com/Azure/azure-sdk-for-go/tree/master/arm/compute/containerservice
