### ISSUE TITLE
DNS Zone

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#346]
Is there any way that the DNS Zone nameservers can be exposed when we make a request to `Get` a zone?

The Azure SDK for .net supports this https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Dns/DnsManagement/Generated/Models/ZoneProperties.cs#L53

Thanks

Paul

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe it looks like this property is introduced in DNS swagger's new 2016-04-01 version. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-dns/2016-04-01/swagger/dns.json#L1073-L1079 

It appears like we'll need to make a release with newly generated code.

**Comment by isamuelson** [comment]
How soon can a new release happen?

**Comment by garimakhulbe** [comment]
today EOD.

**Comment by isamuelson** [comment]
great! thank you.

**Comment by isamuelson** [comment]
any news?

**Comment by ahmetalpbalkan** [comment]
@isamuelson it is under code review at https://github.com/Azure/azure-sdk-for-go/pull/350 , we'll probably tag it later today, feel free to grab the code from there and start using in the meanwhile.

**Comment by ahmetalpbalkan** [comment]
@isamuelson Please check the `v3.0.0-beta` release.
