### ISSUE TITLE
Have operation id in long running operation failures

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-sdk-for-go#348]
When we return an error that has a message like:

> compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: Long running operation terminated with status 'Failed': Code="OperationNotAllowed" Message="Unable to update the VM. The requested  VM size 'Standard_DS1' may not be available in the resources supporting the existing allocation. Please try again later, try with a different VM size or create a VM with a new availability set or no
> availability set binding."

The inner error that says `Long running operation terminated with status 'Failed': Code=...`.

So can we add something like `OperationID=` there, reflecting the `x-ms-operation-id` header. That would help us correlate the issues the customers are seeing directly from the error message.

Example here: https://github.com/docker/machine/issues/3542 If there was an operation ID in the returned string I would go fetch the logs on our backend easily.

**Comment by marstr** [comment]
@garimakhulbe has moved on to another team, and this issue needs to be re-triaged.

**Comment by marstr** [comment]
@salameer : Please take note of this for our next triage meeting.

**Comment by marstr** [comment]
(Triaging) This is a solid idea, but without external interest is low enough pri that it belongs on the Backlog.

**Comment by jhendrixMSFT** [comment]
This will be addressed in the fix for https://github.com/Azure/azure-sdk-for-go/issues/796.
