### ISSUE TITLE
Using Cosmos DB with Table Storage API

### ISSUE THREAD

**Issue by philippgille** [Azure/azure-sdk-for-go#3502]
### Bug Report

I would like to use Cosmos DB as key-value store, and therefore I chose to use the Table Storage API, because according to the documentation of the "multi-model" capabilities the Table Storage API is the key-value store model.

But:

1. The documentation regarding the use of Table Storage with this Go SDK is not very extensive. For example:
    - I couldn't find any examples of how to do simple CRUD operations
    - Parameters are undocumented, for example there's `func (e *Entity) Get(timeout uint, ml MetadataLevel, options *GetEntityOptions) error`, but what should `timeout` be? Seconds or milliseconds? It's not in the GoDoc or anywhere else. Then, in the `GetEntityOptions`, there's a `RequestID` field. Does that need to be set? With which value?
2. I can probably figure out the above things with trial-and-error, but I don't even get that far because of the **following problem, which is the reason I open this GitHub issue**: In the Azure Portal on the Cosmos DB page the connection string is shown, which looks similar to this: `DefaultEndpointsProtocol=https;AccountName=foo;AccountKey=Abc123def456==;TableEndpoint=https://foo.table.cosmosdb.azure.com:443/;`. There are multiple issues:
    - When creating a storage client with `storage.NewClientFromConnectionString(connString)` **I get the following error**: `azure: base storage service url required`. Now clearly the connection string contains a `TableEndpoint`, but looking at the code ([here](https://github.com/Azure/azure-sdk-for-go/blob/fbe7db0e3f9793ba3e5704efbab84f51436c136e/storage/client.go#L254)), it's only used when the connection string contains a `sharedaccesssignature`? Why does the connection string in the Azure portal not work in the SDK by default? Or why doesn't the GoDoc contain a note about any specific changes required to the connection string?
    - Maybe `NewClient` can be used instead? What's meant to be passed as `serviceBaseURL`? Also, there's a `useHTTPS` parameter. Does that imply this client only works with HTTP(S)? On one documentation page about Cosmos DB or Table Storage I read that TCP should be used for better performance. Is this not possible with the SDK?

Info:

- Imported package: `"github.com/Azure/azure-sdk-for-go/storage"`
- Package version: `v23.0.0`, Commit `07f918ba2d513bbc5b75bc4caac845e10f27449e`
- Go version: `go version go1.10.1 windows/amd64`

**Comment by jhendrixMSFT** [comment]
Hello!  Unfortunately our support for connection strings isn't very good.  What steps in the portal did you take to get such a connection string?  If I click on my Cosmos DB account in a resource group then click Keys I see a slightly different connection string.
That said I don't believe that the tables functionality in this package is going to work with Cosmos DB; it was designed to be used with classic table storage and thus hasn't been tested against Cosmos DB (looking at the code I'm pretty sure it won't work at all as it constructs the URLs assuming table storage, e.g. https://storageaccount.table.core.windows.net/tablename).
There is another package, github.com/Azure/azure-sdk-for-go/services/cosmos-db/mongodb, that uses the `mgo` driver for interfacing with Cosmos DB.  I'm not familiar with this package so don't know if it will work for you.

**Comment by jhendrixMSFT** [comment]
CC @joshgav

**Comment by philippgille** [comment]
> What steps in the portal did you take to get such a connection string?

Dashboard -> Azure Cosmos DB -> <MyDbName> -> Connection String (under *Settings*) -> PRIMARY CONNECTION STRING

It's the same that's shown under Dashboard -> Azure Cosmos DB -> <MyDbName> -> Quickstart -> CONNECTION STRING

> There is another package, [...], that uses the mgo driver for interfacing with Cosmos DB. I'm not familiar with this package so don't know if it will work for you.

Are there any internal performance benchmarks for simple use-cases for the different Cosmos DB models (key-value, document, graph, SQL) for the other SDKs that have better support of Cosmos DB? I just need a key-value store and wanted to avoid any possible overhead of the other models and Table Storage sounded like the right thing.

And generally: Are there any plans to support the multiple Cosmos DB models in the Go SDK in the future?

**Comment by PaulCheng** [comment]
The GO sdk ver 40.6.0+ enabled support for CosmosDB Table API endpoint.

**Comment by MehaKaushik** [comment]
Closing old issues, please reopen if you have any more questions.
