### ISSUE TITLE
VMs created for DevTest-labs does not appear in VM list

### ISSUE THREAD

**Issue by zlepper** [Azure/azure-sdk-for-go#352]
It seems that vms created using the DevTest-labs ARM api are not added to the vm list for the Lab they were created under. 
The seem to respect any rules set for the lab, such as schedules, so it's only a visual thing, it does however prevent you from editing Labs specific configurations for the machine using the Azure Portal. 

I created the machines with the NewVirtualMachineClient using the CreateOrUpdateResource method on the client instance.

**Comment by ahmetalpbalkan** [comment]
@zlepper can you please provide more info? VirtualNetworkOperationsClient does not sound right. Have the calls succeeded? Can you see anything on Azure Portal or Azure CLI? Any more inputs are appreciated. I don't think we clearly understand the problem on your side. The developers of Go SDK team are not really familiar with DevTest Labs product, but if you could provide more info, we can route your issue accordingly.

**Comment by zlepper** [comment]
Sorry, was supposed to be NewVirtualMachineClient instead of VirtualNetworkOperationsClient. 
The calls succeed and the machine is created as intended, with all templates and schedules and such attached. The machine appears in the Virtual Machine list in the Azure portal. 
However when I select the lab it is supposed to be in in the Azure Portal, then it's not in the labs list.

**Comment by ramankumarlive** [comment]
@zlepper Are you using a service principal credential to create the VM? If yes, then you can find the VM under Settings --> All VMs

**Comment by zlepper** [comment]
Yes i do, and they are there, thank you. 

But may I know why they don't appear on the first vm list?

**Comment by ramankumarlive** [comment]
You will see the VMs created using your credentials only in the lab dashboard by default. You can see all the lab VMs created by all other lab users by going to All VMs. This is to ensure that the default dashboard is not cluttered with many VMs and also to give you a better performance.
