### ISSUE TITLE
Unable to delete Service Bus Namespace

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#358]
Hi,

I'm getting the following error when attempting to delete a Service Bus namespace with the arm package:
```
servicebus.NamespacesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Long running operation terminated with status 'Failed': Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'northeurope' and API version '2014-09' for type 'namespaces'. The supported api-versions are '2014-09-01, 2015-08-01'. The supported locations are 'australiaeast, australiasoutheast, centralus, eastus, eastus2, westus2, westus, northcentralus, southcentralus, westcentralus, eastasia, southeastasia, brazilsouth, japaneast, japanwest, northeurope, westeurope, centralindia, southindia, westindia, canadacentral, canadaeast'."
```

From what I can see the API Versions don't match as the day component is missing in the error message.

**Comment by garimakhulbe** [comment]
Thats odd because sdk is set to correct version(with day). Have you checked request url using fiddler if final request formed has wrong version? We will also investigate at our end and get back to you soon.

**Comment by garimakhulbe** [comment]
Can you also provide sdk and go-autorest versions you are using?

**Comment by pmcatominey** [comment]
Looked into this again and the error occurs in the status polling request:

Successful call to DELETE the resource:
```
Received Azure RM Request status code 202 Accepted for https://management.azure.com/subscriptions/sub-id/resourceGroups/acctestlbrg-1234/providers/Microsoft.ServiceBus/namespaces/acctestnet1234?api-version=2014-09-01
```

Error from call to GET the result:
```
Received Azure RM Request status code 400 Bad Request for https://management.azure.com/subscriptions/sub-id/resourceGroups/acctestlbrg-1234/providers/Microsoft.ServiceBus/namespaces/acctestnet1234/operationresults/acctestnet1234?api-version=2014-09
```

I'm using the version from the commit 2cdbb8553a20830507e4178b4d0803794136dde7.

**Comment by garimakhulbe** [comment]
Are you still getting this issue?

**Comment by garimakhulbe** [comment]
No response. Assuming it resolved. Closed.

**Comment by pmcatominey** [comment]
Hey, apologies I missed this.

It appears to have been resolved, cheers.
