### ISSUE TITLE
Clarify how to do paging (+ fix auto-gen'd godoc comments)

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#363]
> `func (client VirtualMachinesClient) ListAll() (result VirtualMachineListResult, err error)`
> 
> `ListAll` gets the list of Virtual Machines in the subscription. Use nextLink property in the response to get the next page of Virtual Machines. Do this till nextLink is not null to fetch all the Virtual Machines.

---

> `func (client VirtualMachinesClient) ListAllNextResults(lastResults VirtualMachineListResult) (result VirtualMachineListResult, err error)`
> 
> `ListAllNextResults` retrieves the next set of results, if any.

---

First, "Do this till next Link is not null" - `s/till/until/g` or at least 'til, if we must contract it.

Second, I'm pretty sure it should be "Do this until nextLink is null" but even then, that's not really how we want people to consume paging at the Go SDK level.

As is, I'm just going to keep calling ListAllNextResults until the list returned is nil or empty.

**Comment by colemickens** [comment]
I'd suggest that we should autogenerate ListAll functions.

**Comment by marstr** [comment]
@salameer @jhendrixMSFT @mcardosos 

How would everybody feel about placing this in the backlog? I think this is something we should try to burn-down, and probably soon but not in the next release.

In addition to ListAll, we could try to device a channel based return value.

**Comment by jhendrixMSFT** [comment]
ListAll has been implemented, the remaining work item is the doc fix.
