### ISSUE TITLE
More File Storage Share operations

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#364]
hi,

According to the MSDN docs, there are many activities you can perform on a file share:

https://msdn.microsoft.com/en-us/library/azure/dn166997.aspx

the only actions available in the SDK are:

* Create
* CreateIfNotExists
* Delete
* DeleteIfExists

After I have created a share, how can i read the properties of a share / make sure that share exists on subsequent requests?

Thanks

Paul

**Comment by ahmetalpbalkan** [comment]
@stack72 this is mostly because we implemented only the parts we needed in other projects. Is your requirement just to make sure share exists?

**Comment by stack72** [comment]
Hi @ahmetalpbalkan 

Thanks for getting back to me on this. Ideally, I would be able to set the ACLs and Metadata on the share. So I think ideally, needing the full operations that are documented would be useful here

Paul

**Comment by ahmetalpbalkan** [comment]
@stack72 hmm we have the similar methods in blob.go, porting them to file.go should not be a big deal. Would you be willing to send a PR?

**Comment by enieuw** [comment]
I've opened up a PR at #395 in which I ported most of the blob operations to file which I needed to create a terraform file share resource

**Comment by stack72** [comment]
Closed via #395
