### ISSUE TITLE
Container Service Package

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#365]
Hi 

According to the release notes for v.3.1.0-beta

```
Added a new arm/compute/containerservice (2016-03-30) package.
```

Unfortunately, this isn't the correct namespace. The files in the container service folder are actually marked as `package compute`

Therefore, when I try to import these packages using govendor, nothing happens. I have tried:

```
govendor fetch github.com/Azure/azure-sdk-for-go/arm/compute/containerservice/...

govendor fetch github.com/Azure/azure-sdk-for-go/arm/compute/compute/...

govendor fetch github.com/Azure/azure-sdk-for-go/arm/compute/...
```

Do these need to be in the compute tree? Shouldn't they just be in a location of their own so they can be imported as:

```
govendor fetch github.com/Azure/azure-sdk-for-go/arm/containerservice/...
```

I have tried to find out how you do this in your examples but there is no examples outside of CreateStorage Account

Paul

**Comment by garimakhulbe** [comment]
We have kept container service inside compute because other sdks have it like this(in compute). I will discuss this with my team and update it accordingly by end of this week.

**Comment by ahmetalpbalkan** [comment]
Would just fixing the `package` declaration work? I agree that it should be at the arm/containerservice but it appears like azure-rest-api-specs repo also put it under compute. I don't know why but I opened an issue there. It's a top level RP and I believe it should be generated as such.

**Comment by colemickens** [comment]
(I thought package declaration had to match the directory it lived in? hence needing to actually rearrange layout as well)

**Comment by garimakhulbe** [comment]
Container service is kept in compute because both APIs are managed by same team/org. I got this from one of devs worked on container service swagger.

We can put container service code directly in compute directory if we update file naming convention to like model_<api>.go, client_<api>.go because code generation from two swaggers in same directory overwrites common files.

**Comment by colemickens** [comment]
I'd prefer to see it just put it in its own package. I really don't see why it's worth the effort to special case the ContainerService just because the Compute team happens to own both. As Ahmet said, they're both top level RPs...

**Comment by stack72** [comment]
Thanks for looking into this folks! Nice to see that i'm not the only one that feels this is weird :)

**Comment by stack72** [comment]
Hi all

Is there any status on this?

Paul

**Comment by garimakhulbe** [comment]
Sorry for delay. We are still working on this. According to new specifications container service methods are now merged in computeClient so we are updating Go SDK for that. Will update you soon.

**Comment by colemickens** [comment]
What's the latest here? This one's been open a while. CC: @mcardosos, @jhendrixMSFT.

**Comment by stack72** [comment]
@colemickens I believe that it has been removed form the 5.0.0-beta release - https://github.com/Azure/azure-sdk-for-go/pull/394#issuecomment-249946367

**Comment by colemickens** [comment]
Yeah, I think so as well... just want to know what the status for it returning.

**Comment by jhendrixMSFT** [comment]
This is now resolved as of https://github.com/Azure/azure-sdk-for-go/pull/425 merged today.
