### ISSUE TITLE
SKU param missing from Create Service Bus Namespace call

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#366]
According to the documentation: https://msdn.microsoft.com/en-us/library/azure/mt639408.aspx#Anchor_0 I should be able to specify SKU options when creating/updating the namespace resource. There isn't a field on the `NamespaceProperties` struct to set this value, it is however included in the `NamespaceResource` struct which comes from the response.

The REST docs also have the `sku` parameter listed as a string by mistake.

**Comment by garimakhulbe** [comment]
Added in new release of Azure Go SDK - _v3.2.0-beta_. Please take a look.
https://github.com/Azure/azure-sdk-for-go/blob/master/arm/servicebus/models.go#L185
