### ISSUE TITLE
Kind param missing from Create Service Bus Namespace call

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#367]
According to the Microsoft documentation https://msdn.microsoft.com/en-us/library/azure/mt639408.aspx#Anchor_0 I should be able to set the `Kind` parameter when creating/updating a service bus namespace. However there isn't a field to set it on the `NamespaceProperties` struct.

Looking at the definitions it seems the `Kind` type is also missing a value compared to the `NamespaceType` type: https://github.com/Azure/azure-sdk-for-go/blob/master/arm/servicebus/models.go#L41. Specifically it doesn't support the value `NotificationHub`.

**Comment by garimakhulbe** [comment]
I have raised this to internal team.

**Comment by garimakhulbe** [comment]
Kind and SKU parameters have been added in spec and new release of Azure Go SDK - _v3.2.0-beta_. Take a look. 

https://github.com/Azure/azure-sdk-for-go/blob/master/arm/servicebus/models.go#L185
