### ISSUE TITLE
[docs] Instructions on how to create service principal account

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#370]
Apparently Node SDK maintains a doc here: https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md

We should link to this instead of blog posts etc in https://github.com/Azure/azure-sdk-for-go/tree/master/arm#first-a-sidenote-authentication-and-the-azure-resource-manager

**Comment by marstr** [comment]
Fixed. If you do not feel my PR truly fixed your issue, feel free to reopen.
