### ISSUE TITLE
storage base url

### ISSUE THREAD

**Issue by rootfs** [Azure/azure-sdk-for-go#373]
The default storage base URL is defined [here](https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L24). Are there any other base URLs in different environments (e.g. USGovernmentCloud/GermanCloud/etc)?

@ahmetalpbalkan @colemickens

**Comment by colemickens** [comment]
The storage account suffixes are defined in `go-autorest`: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L50

**Comment by rootfs** [comment]
thanks!
