### ISSUE TITLE
Download function content

### ISSUE THREAD

**Issue by alonrolnik** [Azure/azure-sdk-for-go#3780]
### Service Package Request

Hi,
I'm trying to find out how to download through the SDK a function content similar to what in the UI
![image](https://user-images.githubusercontent.com/2459199/50477282-6264ca00-09d4-11e9-9519-d262eb493a3b.png)
Any help will be appreciated

I tried already what described in [here](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#download-your-function-app-files) but without much success (keep getting HTTP 403)

Thanks.

**Comment by vladbarosan** [comment]
Hi @alonrolnik, those actions refer to the Kudu Deployment API which is not exposed currently in this SDK.
There is an issue tracking this #1065.

Meanwhile I would suggest taking a look at the [Kudu API](https://github.com/projectkudu/kudu/wiki/REST-API#zip) and in case of any problem opening an issue in the Kudu repo.
