### ISSUE TITLE
Generate KeyVault Client

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#379]
See this for the python sdk: https://github.com/Azure/azure-sdk-for-net-pr/pull/702

Looks like there is a Swagger spec for KeyVault now. https://github.com/Azure/azure-rest-api-specs/pull/387

I think it's control plane only, but we should still support it.

**Comment by garimakhulbe** [comment]
This is added in new version _v3.2.0-beta_ of Azure Go SDK.

**Comment by colemickens** [comment]
woot! Thanks @garimakhulbe !
