### ISSUE TITLE
Remove Logic from Hosted Service Client

### ISSUE THREAD

**Issue by jen20** [Azure/azure-sdk-for-go#38]
When creating a hosted service, there is a call made to check the name availability. My opinion is that we should remove this call and make it a user responsibility, since they have to handle the `ConflictError` which can result from the race between checking the availability and creating the hosted service. 

However, the check being present makes it very difficult to find out what actual error gets returned if you hit the race condition!

**Comment by hopetobelievein** [comment]
I don't mind.

**Comment by jen20** [comment]
It would be reasonable to have the logic elsewhere, but I think we should expose a way of making the individual calls directly, and then have some blocking API (which waits for the result) for other uses. It becomes much easier to use with something like `.SetPartial()` when using the API to write a Terraform provider if the API calls are actually exposed.

**Comment by ahmetalpbalkan** [comment]
:+1:  Makes sense. there should be a method to check HS name availability which makes only 1 REST API request and another method to create HS with specified name, again something makes only 1 REST API call.

Historically we probably added the logic to get something done quickly but it would be good to fix it now. Having this extra logic would also confuse the caller and make them look into the code to see what it is actually doing. Thanks @jen20.

**Comment by ahmetalpbalkan** [comment]
Fixed in #44?

**Comment by jen20** [comment]
Not fixed yet afaik.

**Comment by jeffmendoza** [comment]
This sounds good
