### ISSUE TITLE
Get authentication details when using SDK

### ISSUE THREAD

**Issue by KarlGW** [Azure/azure-sdk-for-go#3804]
### Feature Request

This might already be implemented, but I have read the docs and cannot seem to find anything about it.

When using:

```
deviceConfig := auth.NewDeviceFlowConfig(appID, tenantID)
authorizer, err := deviceConfig.Authorizer()
```

Is there some way to get the access & refresh token when using these (For usage with my own custom REST calls)? All examples are quite sparse, and I cannot find any further examples on how to use the authentication after I have authenticated.

**Comment by jhendrixMSFT** [comment]
Unfortunately there isn't right now, you'd basically have to copy most of the implementation for `DeviceFlowConfig.Authorizer()`, omitting the last part acquiring a bearer authorizer.  I will add this functionality to `DeviceFlowConfig` to avoid having to copy the code.

**Comment by KarlGW** [comment]
@jhendrixMSFT a that sounds great! I was afraid I had missed something basic and was making a fool out of myself. Thank you for looking into it!

**Comment by jhendrixMSFT** [comment]
This has been added in https://github.com/Azure/go-autorest/releases/tag/v11.3.0 of go-autorest.  Sample code is as follows (error checking omitted for brevity).
```go
deviceConfig := auth.NewDeviceFlowConfig("appID", "tenantID")
spToken, _ := deviceConfig.ServicePrincipalToken()
spToken.EnsureFresh()
token := spToken.Token()
fmt.Println(token.AccessToken)
fmt.Println(token.RefreshToken)
```
The call to `EnsureFresh()` will only hit the network on the initial call and when the token is about to expire.
