### ISSUE TITLE
operationalinsights API returning all linked workspace service properties as lowercase

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#3805]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
  ```github.com/Azure/azure-sdk-for-go/services/preview/operationalinsights/mgmt/2015-11-01-preview/operationalinsights```

- SDK version e.g. `master`, `latest`, `18.1.0`
  ```v21.3.0```
- output of `go version`
  ```go version go1.11.2 darwin/amd64```

- What happened?
It seems this API is returning everything for a linked workspace service in lowercase. Most notably the resource group and workspace name. This is a problem because workspace and resource group names and can contain uppercase characters.

- What did you expect or want to happen?
the resource and workspace name's to be returned in the proper case. The validation error also implies this:
```Workspace Name can only contain alphabet, number, and '-' character. You can not use '-' as the start and end of the name```

- How can we reproduce it?
terraform, see [this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2593)

**Comment by jhendrixMSFT** [comment]
@katbyte does this repro with the stable 2015-03-20 API version?

**Comment by katbyte** [comment]
The `2015-03-20` version doesn't seem to exist:
```
github.com/terraform-providers/terraform-provider-azurerm/azurerm imports
	github.com/Azure/azure-sdk-for-go/services/preview/operationalinsights/mgmt/2015-03-20/operationalinsights: module github.com/Azure/azure-sdk-for-go@latest (v36.1.0+incompatible) found, but does not contain package github.com/Azure/azure-sdk-for-go/services/preview/operationalinsights/mgmt/2015-03-20/operationalinsights
```

and i can confirm this is an issue as of today:
```
--- FAIL: TestAccAzureRMLogAnalyticsLinkedService_linkedServiceProperties (101.73s)
    testing.go:569: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        DESTROY/CREATE: azurerm_log_analytics_linked_service.test
          id:                                      "/subscriptions/1234567/resourcegroups/acctestrg-191106141929423440/providers/microsoft.operationalinsights/workspaces/acctestlaw-191106141929423440/linkedservices/automation" => "<computed>"
          linked_service_name:                     "automation" => "automation"
          linked_service_properties.#:             "1" => "1"
          linked_service_properties.0.resource_id: "/subscriptions/1234567/resourceGroups/acctestRG-191106141929423440/providers/Microsoft.Automation/automationAccounts/acctestAutomation-191106141929423440" => "/subscriptions/1234567/resourceGroups/acctestRG-191106141929423440/providers/Microsoft.Automation/automationAccounts/acctestAutomation-191106141929423440"
          name:                                    "acctestlaw-191106141929423440/Automation" => "<computed>"
          resource_group_name:                     "acctestrg-191106141929423440" => "acctestRG-191106141929423440"
          resource_id:                             "/subscriptions/1234567/resourceGroups/acctestRG-191106141929423440/providers/Microsoft.Automation/automationAccounts/acctestAutomation-191106141929423440" => "<computed>"
          tags:                                    "" => "<computed>"
          workspace_name:                          "acctestlaw-191106141929423440" => "acctestLAW-191106141929423440" (forces new resource)

```

**Comment by shemers** [comment]
Hi @katbyte,
My apologies for the delay in response, 
We have involved the engineering team, they have started investigating this issue.
I will keep you posted.

**Comment by lirenhe** [comment]
@katbyte, as this issue has been there for long time, could you still reproduce this issue by using the latest version of Go SDK?

**Comment by tombuildsstuff** [comment]
@shemers did you hear back from the engineering team on this one?

**Comment by shemers** [comment]
Hi @tombuildsstuff, 
yes, we are working with the engineering teem regarding this request, 
unfortunately, this is not straightforward fix as originally hopped, 
the case conversion is done as part of the write process, and not the fetch process. 
as such we are collaborating with other teams to make sure that the fix won't cause an issue in other areas. 
also, even after the fix is implemented, we cannot backward support this.
Sorry I don't have any better message to share.

**Comment by tombuildsstuff** [comment]
This is still waiting on the Engineering Team

@jhendrixMSFT heads up I think this is a bug in the close-bot?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for .NET and Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
