### ISSUE TITLE
add IconUri to OSImage

### ISSUE THREAD

**Issue by mischief** [Azure/azure-sdk-for-go#388]
https://msdn.microsoft.com/en-us/library/azure/jj157192.aspx says OSImage should have IconUri, but https://godoc.org/github.com/Azure/azure-sdk-for-go/management/osimage#OSImage lacks it.

**Comment by ahmetalpbalkan** [comment]
@mischief we manually authored the `./management` pkgs. Therefore the fields on some types may be incomplete, and some endpoints might be missing altogether. 

Do you need this field? If so, we are open to contributions for this package or we can add it if you like.
