### ISSUE TITLE
`LinkedServicesClient` does return `tags` in LinkedService object

### ISSUE THREAD

**Issue by metacpp** [Azure/azure-sdk-for-go#3883]
### Bug Report

- import path of package:
`.../services/preview/operationalinsights/mgmt/2015-11-01-preview/operationalinsights`

- SDK version: `24.0.0`
  - REVISION: 1951233eb944a49aa5f7278cba8e3e32a8c958af

- output of `go version`: 1.11.0

- What happened?
Get API does not return tags in `LinkedService` object.

- What did you expect or want to happen?
tags should be contained in `LinkedService` object.

- How can we reproduce it?
1. Call `CreateOrUpdate` API with preset tags.
2. Call `Get` API.

- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
@metacpp do you see them in the response body?

**Comment by metacpp** [comment]
@jhendrixMSFT sorry for the late response.

Yes. we're using preview API, but its version is higher than `2015-03-20`. I did a quick experimentation, looks like `2015-03-20` is not supported in `west europe`. Any idea for me to find a supported region of this API?

**Comment by yossi-y** [comment]
We currently ignore tags in all APIs. We also don’t support storing tags for linked services.

About the version question, you can find the latest version that consolidates operationalInsights API under 2020-03-01-preview: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2020-03-01-preview

**Comment by ArcturusZhang** [comment]
Hi @metacpp this issue should be resolved in the new api-version. Therefore I will close this now.
If it persists, please feel free to open a new issue about it. Thanks!
