### ISSUE TITLE
Need getter method for networkInterface by ID

### ISSUE THREAD

**Issue by tariq1890** [Azure/azure-sdk-for-go#3917]
I am currently using the apiVersion "2018-10-01". There seems to be no Getter method for NIC's by ID. All I see is a getter method for NIC by name where one would also have to specify a resource group Name.

My use case is the following:

i) List all Virtual Machines.
ii) Iterate through each VM
iii) In every iteration, query the VM's networkProfile and retrieve the NIC ID (this is the only field available)
iv) Get the NIC reference by NIC ID

Granted that I can get the resource group and NIC name from the NIC ID. But It is inconvenient to use regex operations to just extract the NIC name and the resource group. Furthermore, I would need different regexes for different VM types. I don't want to use multiple regexes like this for just to have to retrieve NICs

For eg:- I would need the following regular expressions

`/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/virtualMachineScaleSets/%s/virtualMachines/%s/networkInterfaces/%s`

`/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/virtualMachines/%s/virtualMachines/%s/networkInterfaces/%s`

**Comment by jhendrixMSFT** [comment]
@MikhailTryakhov is it possible to retrieve a network interface by ID?

**Comment by tariq1890** [comment]
Do we have the Go SDK equivalent of `az vmss nic list` ?

**Comment by jhendrixMSFT** [comment]
Yes the API you want is `InterfacesClient.ListVirtualMachineScaleSetNetworkInterfaces`, see https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2018-12-01/network/interfacesgroup.go#L958.

**Comment by tariq1890** [comment]
Thanks. I don't see a similar method for VirtualMachines though.

**Comment by tariq1890** [comment]
To rephrase my earlier, I don't see an equivalent for `az vm nic list`. Thanks for the responses @jhendrixMSFT  :)

**Comment by jhendrixMSFT** [comment]
I think the equivalent to `az vm nic list` would be to call `VirtualMachinesClient.Get()` then iterate over the `VirtualMachine.VirtualMachineProperties.NetworkProfile.NetworkInterfaces` slice.
For reference, you can see how the python CLI commands work for VM by looking at the following file.
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
Then search for `vm nic`, then look at the custom command for `list` which maps to `list_vm_nics` https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py#L1384

**Comment by tariq1890** [comment]
@jhendrixMSFT We use a similar method to what we do in the python flows. But `NetworkProfile.NetworkInterfaces` returns only a reference to the NICs not the complete struct which encapsulates all the fields of the NIC object. 

`ListVirtualMachineScaleSetNetworkInterfaces` fits the bill in this regard though. We just need something similar for `VMs`
