### ISSUE TITLE
Updating SecurityGroup

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#3921]
Hi

I'm writing up a tool to help update securitygroups (specifically inbound IP whitelists). Given I want to update multiple security groups at once (based on the rule name), I initially had a naive (but working) process of:

1) retrieve all resource groups in subscription
2) get all security groups in each resource group
3) find rules, update where appropriate and call the securitygroup client function CreateOrUpdate (which requires the resourcegroup name).

Then I realised that the securitygroup client had a function ListAll() which would list all security groups across the subscription, so I didn't then have to retrieve the resource groups and perform lots of calls.
BUT...  to update the securitygroup I think I still need a resourcegroup for the given security group.

I can't find either a method to allow updating WITHOUT the resourcegroup being supplied, nor can I find the resourcegroup for the retrieved securitygroup (which I could pass to the already mentioned CreateOrUpdate function).

Does anyone know if there is a way to solve the above? (either save without RG required, or retrieve RG from SG?)

If need be, I can keep the existing method (loop through RGs)... but would prefer not having to do that.

Thoughts?

Thanks

Ken

**Comment by kpfaulkner** [comment]
I suppose I could extract the RG from the "ID" field returned in the SG. Will attempt that for now, but if anyone has any better approach when using this SDK I'm all ears.

Cheers

Ken

**Comment by lirenhe** [comment]
@kpfaulkner, this item has been there for years so i will close it.
As the SDK is auto generated from Swagger, you may check the rest API directly for the solutions.
Please let us know if you still have problem.
