### ISSUE TITLE
TLS config

### ISSUE THREAD

**Issue by Caiyeon** [Azure/azure-sdk-for-go#3942]
Hi, is there a way to configure tls settings? Specifically, I would like to enforce TLS1.2 as a minimum, and restrict the list of ciphersuites used in client https calls.

**Comment by jhendrixMSFT** [comment]
I'm not an expert in this topic but I believe you'll need to replace the default HTTP client with your own that specifies the TLS version in the transport.  Something like this.
```go
client := aad.NewFooClient("subscriptionID")
client.Sender = &http.Client{
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{
			MinVersion: tls.VersionTLS12,
			MaxVersion: tls.VersionTLS12,
		},
	},
}
```
Looking at `http.DefaultClient` etc you probably need to set more than the fields listed here but this should give you a direction I think.

**Comment by Caiyeon** [comment]
Thank you for the timely response and example. So it's completely safe to overwrite the sender with a custom http client?

**Comment by jhendrixMSFT** [comment]
As long as the provided type implements the `Sender` interface yes.

**Comment by jhendrixMSFT** [comment]
Closing as I believe this is answered.  Please reopen if you have more questions.
