### ISSUE TITLE
storage: client_test call to regexp.Compile

### ISSUE THREAD

**Issue by Quasilyte** [Azure/azure-sdk-for-go#3944]
https://github.com/Azure/azure-sdk-for-go/blob/392ea0b046cfb0cb05942ea92baf22af9ff7f9df/storage/client_test.go#L262-L265

If const-pattern (from literal string) regexp compilation failed, code should probably panic, since it's programmer error and pattern should be fixed.
Right now it just returns false silently.

I propose using `regexp.Must` there.
This way, code is simpler and more robust at the same time.

**Comment by jhendrixMSFT** [comment]
Thanks for the suggestion.  I agree with you however the `storage` package has been deprecated, replaced by [azblob](https://github.com/Azure/azure-storage-blob-go/tree/master/azblob), so we aren't actively fixing issues in it.
