### ISSUE TITLE
Add AddToUserAgent for keyvault client 

### ISSUE THREAD

**Issue by ritazh** [Azure/azure-sdk-for-go#3956]
### Feature Request

We need to be able to add our own userAgent header to keyvault client to identify callers for telemetry and reporting. Similar to https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L424 for storage.

cc @jhendrixMSFT @khenidak

**Comment by jhendrixMSFT** [comment]
This is a dupe of https://github.com/Azure/go-autorest/issues/360 and was resolved in go-autorest version 11.4.0.

**Comment by jhendrixMSFT** [comment]
Ooops my mistake not a dupe of 360 but this should already work?

**Comment by jhendrixMSFT** [comment]
@ritazh which keyvault client are you referring to?

**Comment by ritazh** [comment]
@jhendrixMSFT This one: https://github.com/Azure/azure-sdk-for-go/blob/master/services/keyvault/2016-10-01/keyvault/client.go

**Comment by jhendrixMSFT** [comment]
After you create your client you should be able to call `AddToUserAgent()` to append custom data.  Here's an example.
```go
client := keyvault.New()
client.AddToUserAgent("custom user agent stuff")
```
Any API calls made via that client will have the "custom user agent stuff" appended to the standard SDK user-agent string.

**Comment by ritazh** [comment]
oh oops! I only saw the `AddToUserAgent` from storage client. Thanks for the tip!
