### ISSUE TITLE
Managed Identity: Configurable timeout based on time

### ISSUE THREAD

**Issue by arluca** [Azure/azure-sdk-for-go#3975]
### Feature Request

Currently, the retry logic in the Azure SDKs for Managed Identity token generation supports a configurable time out based on counts. For response time sensitive services this has not been enough. Per customer feedback, they would like to have timeout configuration based on time (i.e. milliseconds)
This will allow for quicker fail after certain.
Can we make the retry max configurable based on time?
@binderjoe FYI

**Comment by jhendrixMSFT** [comment]
@arluca to make sure I understand, the ask is to add a cap to the max time spanning retries?  E.g. it might retry N number of times within X amount of time?  So whichever value is exceeded first fails token generation.

**Comment by arluca** [comment]
Yes. But also the ability to just set the time, without having to set the number of tries. Apologies for the delay in responding.

Thanks,
-Arturo
Managed Service Identity<http://aka.ms/msidocs>

**Comment by jhendrixMSFT** [comment]
Actually I think you can achieve this today by setting `MaxMSIRefreshAttempts` to 1 and using a context with the required deadline (sample code below).  Are you able to try this out and verify it works as required?
```go
package main

import (
	"context"
	"os"
	"time"

	"github.com/Azure/azure-sdk-for-go/services/redis/mgmt/2018-03-01/redis"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/adal"
	"github.com/Azure/go-autorest/autorest/azure"
)

func createSPT() (autorest.Authorizer, error) {
	tenantID := os.Getenv("AZURE_TENANT_ID")
	oauthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantID)
	if err != nil {
		return nil, err
	}
	clientID := os.Getenv("AZURE_CLIENT_ID")
	clientSecret := os.Getenv("AZURE_CLIENT_SECRET")
	spToken, err := adal.NewServicePrincipalToken(*oauthConfig, clientID, clientSecret, azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		return nil, err
	}
	// limit MSI token acquisition retry attemps to one
	spToken.MaxMSIRefreshAttempts = 1
	return autorest.NewBearerAuthorizer(spToken), nil
}

func main() {
	auth, _ := createSPT()
	client := redis.NewClient(os.Getenv("AZURE_SUBSCRIPTION_ID"))
	client.Authorizer = auth
	// specify a context with a 500 millisecond timeout
	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	defer cancel()
	client.Create(ctx, "rgName", "redis1", redis.CreateParameters{})
}
```

**Comment by arluca** [comment]
Let me chat with the customer.

Arturo Lucatero [LinkedIn<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Farturo-lucatero&data=04%7C01%7C%7C1f19e83c655c43523fb208d61833ec23%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636723008644823124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=RKgUrONgQDBbP4wIa0fUm3K1n%2B5GCYvqn%2FBiZ0eGk0Y%3D&reserved=0> | Twitter<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FArLucaID&data=04%7C01%7C%7C1f19e83c655c43523fb208d61833ec23%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636723008644833136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=o2%2FWgOKikQzXxhgnEM%2BBhUhScrWpPYkZsj2BvqelJkg%3D&reserved=0>]
Managed Identities for Azure resources docs<http://aka.ms/msidocs> | Onboarding to Azure IAM<https://microsoft.sharepoint.com/teams/AzureMSI/SitePages/Home.aspx> | Azure IAM office hours<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzureRBACMSI-OfficeHours&data=04%7C01%7C%7C1f19e83c655c43523fb208d61833ec23%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636723008644843145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=i5udbijTDcf0PE2JGJM6LBiG4D%2Bwcn0V9EqNJB4ZNb0%3D&reserved=0>

**Comment by arluca** [comment]
@jhendrixMSFT : This helps with limiting the number of tries; however, what about limiting the period of time before it times out (even within a single try?)

**Comment by jhendrixMSFT** [comment]
In this sample the context should time out after 500ms and cancel the in-flight request.  Are you saying that isn't happening?

**Comment by jhendrixMSFT** [comment]
Per offline discussion this works for the customer so closing.
