### ISSUE TITLE
Listed template deployments lack error details

### ISSUE THREAD

**Issue by axw** [Azure/azure-sdk-for-go#399]
[arm/resources/resources.DeploymentPropertiesExtended](https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/resources#DeploymentPropertiesExtended) lacks an "error" field, as described in the docs here: https://msdn.microsoft.com/en-us/library/azure/dn848363.aspx.

**Comment by mcardosos** [comment]
Hello!
I think the model you are looking for is [DeploymentValidateResult](https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/resources#DeploymentValidateResult), which includes [ResourceManagementErrorWithDetails](https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/resources#ResourceManagementErrorWithDetails). It is returned by [Validate](https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/resources#DeploymentsClient.Validate).

**Comment by axw** [comment]
@mcardosos No, I'm not looking to validate a template - I want to know about its status after starting it. We want to be able to start deployments and then asynchronously poll their status.

**Comment by colemickens** [comment]
Looks like it's missing in the Swagger spec: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-09-01/swagger/resources.json#L1883

Can you file an issue over in the `azure-rest-api-specs` repo?

**Comment by axw** [comment]
@colemickens done, thanks.

**Comment by marstr** [comment]
Seeing as this has been opened in the Azure/azure-rest-api-specs repo, I'll close out this copy. If folks believe there is Go specific conversation to be had, feel free to open this issue back up.
