### ISSUE TITLE
Listing Activity Logs does not return event data for the ResourceHealth or ServiceHealth categories

### ISSUE THREAD

**Issue by cmendible** [Azure/azure-sdk-for-go#3990]
### Bug Report

- import path:
"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights"
"github.com/Azure/go-autorest/autorest/azure/auth"

- output of `go version`
go version go1.11.4 windows/amd64

- What happened?
Listing events for Activity Logs do not show results for ResourceHealth or ServiceHealth categories. I can see activity in  the portal but listing all events orusing teh follwoing filters do not show the expected results.

```
eventTimestamp ge '2019-01-28T12:13:58Z' and eventTimestamp le '2019-02-01T12:13:58Z' and category eq 'ResourceHealth'

eventTimestamp ge '2019-01-28T12:13:58Z' and eventTimestamp le '2019-02-01T12:13:58Z' and category eq 'ServiceHealth'
```

Even filtering by time stamp and correlationId return cero results.

- What did you expect or want to happen?
Get the even data for the Service Health and Resource Health Categories.

- How can we reproduce it?

Run the sample I provide here: https://github.com/cmendible/go.samples/tree/master/azure-health replacing &lt;subscriptionID> with a valid subscription.

Perhaps it has something to do with the REST API and not the SDK?

- Anything we should know about your environment.
Nope

Thanks!

**Comment by jhendrixMSFT** [comment]
According to the [docs](https://docs.microsoft.com/en-us/rest/api/monitor/activitylogs/list) for this API I don't believe the `category` keyword is allowed in the filter.  I realize this doesn't answer your question, I will contact somebody from the service team to see if they can clarify.

**Comment by cmendible** [comment]
True (It works with Administrative category).

If you remove that filter and browse through the results no event for the ServiceHealth or ResourceHealth categories are shown.

Thanks for looking in to it

**Comment by jhendrixMSFT** [comment]
@Adarsh1994-MS are you the right person to help answer this question?

**Comment by Adarsh1994-MS** [comment]
@jhendrixMSFT No, I do not have context about this.

**Comment by jhendrixMSFT** [comment]
@Adarsh1994-MS do you know who can help?  To summarize, how to "Get the even data for the Service Health and Resource Health Categories."

**Comment by cmendible** [comment]
Hi guys any news on this one?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay, trying to find the right person to get you an answer.

**Comment by nkiest** [comment]
Certain categories are not available via the current API version, including ResourceHealth and Policy. All activity logs can be streamed to a destination using diagnostic settings https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings
