### ISSUE TITLE
Relative links broken

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#400]
There are some links here and there, such as `[...](/examples)` in arm/README.md but those are broken right now. That one should be `(/arm/examples)` instead (or maybe `(./examples)`, I'm not sure).

Somebody should go through these links and validate them ideally.

**Comment by garimakhulbe** [comment]
@mcardosos Please look into this.

**Comment by mcardosos** [comment]
PR sent :3
