### ISSUE TITLE
Error creating service bus topic due to bad date format

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#402]
I get the following error when trying to create a topic with the SDK:
```
2016/09/21 17:58:00 Failed to create topic:  servicebus.TopicsClient#CreateOrUpdate: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'parsing time ""2016-09-21T16:57:59.47"" as ""2006-01-02T15:04:05.999999999Z07:00"": cannot parse """ as "Z07:00"' JSON = '{"id":"/subscriptions/subscription-id/resourceGroups/acctestlbrg-1234/providers/Microsoft.ServiceBus/namespaces/acctestnet1234/topics/azsbtopic1234","name":"azsbtopic1234","type":"Microsoft.ServiceBus/Topic","location":"North Europe","tags":null,"properties":{"defaultMessageTimeToLive":"10675199.02:48:05.4775807","maxSizeInMegabytes":1024,"requiresDuplicateDetection":true,"duplicateDetectionHistoryTimeWindow":"00:10:00","enableBatchedOperations":true,"sizeInBytes":0,"filteringMessagesBeforePublishing":false,"isAnonymousAccessible":false,"status":"Active","createdAt":"2016-09-21T16:57:59.47","updatedAt":"2016-09-21T16:57:59.627","supportOrdering":true,"autoDeleteOnIdle":"10675199.02:48:05.4775807","enablePartitioning":false,"isExpress":false,"entityAvailabilityStatus":"Available","enableSubscriptionPartitioning":false,"enableExpress":false}}'
```

The error is caused due to the createdAt field in the JSON response missing a `Z` from the end of the timestamp, this is not the case for a Get request issued after creation.

I have created a [gist](https://gist.github.com/pmcatominey/f759fd9569d5edea8ece80189c50269d) which shows how to reproduce the error.

Tested against a vendored copy of the SDK at revision 63d3f3e3b12ffb726ba3f72fef1aa8c1c7cd1012.

**Comment by mcardosos** [comment]
Hello!
I was able to reproduce the issue. Let's see what I can find :3
Thanks for reporting

**Comment by jhendrixMSFT** [comment]
@mcardosos I hit this issue as well when writing the sample for managing web apps.  I have a tentative fix, we should discuss.

**Comment by jhendrixMSFT** [comment]
Hi @pmcatominey just letting you know I merged a fix for this issue, thanks for reporting it.

**Comment by pmcatominey** [comment]
Thanks @jhendrixMSFT.

Does the fix require a bump of the vendored go-autorest package?

**Comment by jhendrixMSFT** [comment]
@pmcatominey yes thanks for pointing this out, it's been resolved in https://github.com/Azure/azure-sdk-for-go/pull/405.
