### ISSUE TITLE
"Storage - Table" package is not available

### ISSUE THREAD

**Issue by seym45** [Azure/azure-sdk-for-go#4026]
### Service Package Request

I didn't find any package for Azure storage -Table. Can we have one compatible with Golang?

**Comment by jhendrixMSFT** [comment]
There is limited table functionality mixed in the `storage` package, https://github.com/Azure/azure-sdk-for-go/blob/master/storage/table.go
Take a look at some of the tests https://github.com/Azure/azure-sdk-for-go/blob/master/storage/table_test.go for examples of how they work.

**Comment by kpfaulkner** [comment]
Will we get a similar repo to azure-storage-blob-go but for tables?

**Comment by jhendrixMSFT** [comment]
I haven't heard any plans to do this, doesn't mean it won't happen though.  Is there specific functionality you're looking for that is missing from the current implementation?

**Comment by kpfaulkner** [comment]
No, not missing any specific functionality. I was merely curious since the other parts of storage were extracted out to their own projects, I was wondering if table would also get that treatment. This SDK does everything I need.

**Comment by ArcturusZhang** [comment]
Hi @seym45 and @kpfaulkner , we have a repo for [azure-storage-blob-go](https://github.com/Azure/azure-storage-blob-go), if this could meet your expectation.

**Comment by kpfaulkner** [comment]
@ArcturusZhang For me it doesn't meet the criteria (need table storage access not blob). This SDK is good enough for what I need, was merely curious to see if Table was getting the same support as blob.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang For me it doesn't meet the criteria (need table storage access not blob). This SDK is good enough for what I need, was merely curious to see if Table was getting the same support as blob.

Sorry about that. There is no storage-table data plane SDK within Microsoft. But there is an open source sdk that seems to cover some storage table functionalities, which was made by a community contributor, you can check this one [here](https://github.com/tombuildsstuff/giovanni)
