### ISSUE TITLE
Acquiring a lease on a storage blob

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#406]
I can't find any methods in the storage package which provides the ability to gain a lease, is it missing?
 
A code sample in [this article](https://azure.microsoft.com/en-us/documentation/articles/storage-concurrency/#managing-concurrency-in-blob-storage) indicates that it is available as a method in the .NET SDK:

```
// Acquire lease for 15 seconds
string lease = blockBlob.AcquireLease(TimeSpan.FromSeconds(15), null);
Console.WriteLine("Blob lease acquired. Lease = {0}", lease);
```

**Comment by kpfaulkner** [comment]
Have forked the repo and have started to implement these at https://github.com/kpfaulkner/azure-sdk-for-go  if anyone is interested. 

Currently acquire, release, break, renew and change are working.
Once I add unit tests I'll submit for a PR, but if anyone wants a quick snoop/comment on the changes, please have a look. Although I'm a long time dev I'm fairly new to GO so would appreciate any feedback.

Thanks

Ken

**Comment by kpfaulkner** [comment]
Have submitted PR for this (have signed CLA but taking a while to register).

**Comment by mcardosos** [comment]
Awesome! Thanks @kpfaulkner ! :D
