### ISSUE TITLE
[question] where is azure file snapshot API

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-sdk-for-go#4093]
I could find azure file create API here:
https://github.com/Azure/azure-sdk-for-go/blob/master/storage/file.go#L136-L137

But where is the snapshot-share API?
https://docs.microsoft.com/en-us/rest/api/storageservices/snapshot-share

https://github.com/Azure/azure-sdk-for-go/blob/master/storage/ directory only contains blob snapshot API

I would like to implement azure file snapshot functionality on Kubernetes in [azure file CSI driver](https://github.com/csi-driver/azurefile-csi-driver), while I would like to know where is the go sdk first, thanks.

**Comment by jhendrixMSFT** [comment]
The `storage` package is currently in maintenance mode so we haven't added this new support.  For files, the functionality is being replaced by `azfile`.  You can find this specific API at https://github.com/Azure/azure-storage-file-go/blob/master/azfile/url_file.go#L53

**Comment by andyzhangx** [comment]
@jhendrixMSFT 
thanks for letting me know this. I have another question: kubernetes azure cloud provider is still depending on the old `storage` package(see below), are you suggesting we should upgrade to the new SDK? The simple question could be will the API of the old `storage` package will always work on Azure?

https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L56
```
			"ImportPath": "github.com/Azure/azure-sdk-for-go/storage",
			"Comment": "v21.3.0",
			"Rev": "da91af54816b4cf72949c225a2d0980f51fab01b"
```

**Comment by jhendrixMSFT** [comment]
It will work as long as API version 2016-05-31 is supported.  You should be able to mix both SDKs and slowly migrate old code to `azfile`.

**Comment by andyzhangx** [comment]
Thanks, it's clear to me now.
