### ISSUE TITLE
Support resources in cdn endpoint

### ISSUE THREAD

**Issue by imavroukakis** [Azure/azure-sdk-for-go#4111]
### Feature Request
In order to unblock https://github.com/terraform-providers/terraform-provider-azurerm/issues/398 and enable custom domains, please consider adding `resources` support to the `Endpoint` struct.

**Comment by jhendrixMSFT** [comment]
@hytao can you please comment, is this missing from the swagger?

**Comment by imavroukakis** [comment]
Hey there, would appreciate any updates on this :)

**Comment by jhendrixMSFT** [comment]
@hytao ping

**Comment by TheYorkshireDev** [comment]
I am interested in this feature for the same reason as @imavroukakis it would be great to get an update on progress.

**Comment by hytao** [comment]
Hi, we are currently updating the cdn swagger? What do we need to do to unblock this issue?

**Comment by imavroukakis** [comment]
Hi @hytao from what I can tell, the `Endpoint` struct is missing `resources` as per the API

**Comment by jhendrixMSFT** [comment]
The APIs for manipulating custom domains are in [customdomains.go](https://github.com/Azure/azure-sdk-for-go/blob/master/services/cdn/mgmt/2019-04-15/cdn/customdomains.go).

**Comment by jhendrixMSFT** [comment]
With the APIs available I believe this issue is resolved.  Please let me know if you have further questions.
