### ISSUE TITLE
Application Gateway WAF

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#412]
Hi,

The Swagger specs for network appear to support WAF SKU configuration for tge Application Gateway resource as of version [01-09-2016](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/network.json). However the corresponding code isn't there even thought the `arm/network` package claims to implement that version.

Is this due to the service being in preview?

Regards

**Comment by stack72** [comment]
@garimakhulbe / @ahmetalpbalkan any chance we could get the client regenerated for this? I believe that @pmcatominey wants to add support for this to Terraform :)

**Comment by garimakhulbe** [comment]
@mcardosos can you look into this?

**Comment by mcardosos** [comment]
Added in `v6.0.0-beta` :D

**Comment by pmcatominey** [comment]
@mcardosos @garimakhulbe cheers!
