### ISSUE TITLE
[question] how can i get the price for vmsize?

### ISSUE THREAD

**Issue by lsytj0413** [Azure/azure-sdk-for-go#4120]
I notice the compute.ResourceSku and skus.ResourceSku can help list the available vmsize in which location, and the return's type definition has such field:

```
	// Costs - Metadata for retrieving price info.
	Costs *[]ResourceSkuCosts `json:"costs,omitempty"`
``` 

but it always be nil in the response. so the question is, how can i get the price for which vmsize?

**Comment by jhendrixMSFT** [comment]
Hello @lsytj0413 can you please specify which API you're calling and in which region?

**Comment by lsytj0413** [comment]
I have tried the packages:

```
github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-06-01/compute
github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-09-01/skus
```
and construct the cilent as:

```
skuClient := compute.NewResourceSkusClientWithBaseURI(baseURI, subscriptionID)
r, err := skuClient.List(context.TODO())

skuClient := skus.NewResourceSkusClientWithBaseURI(
			baseURI,
			subscriptionID,
		)
r, err := skuClient.List(context.TODO())
```

the region we use is azure-china.

**Comment by jhendrixMSFT** [comment]
Can you please attach the HTTP request/response?  Easiest way is to set environment var `AZURE_GO_SDK_LOG_LEVEL` to `debug` then run your repro.  This way we will know if the value is being sent over the wire or not.

**Comment by lsytj0413** [comment]
[computesku.log](https://github.com/Azure/azure-sdk-for-go/files/2928837/computesku.log)
this is the log when compute.SkusClient.List is called.

**Comment by jhendrixMSFT** [comment]
Thanks, I don't see this info coming over the wire.
@hylee do you know why we don't receive the cost info here?

**Comment by stevedumais** [comment]
I've run in to the same thing - please let me know if any more log info would be of any assistance and I'll pass it along.

**Comment by stevedumais** [comment]
Hey all - just wanted to check in and see if there was any movement on this?

**Comment by jhendrixMSFT** [comment]
Waiting to hear back from the service team, sorry for the delay.

**Comment by hyonholee** [comment]
Does service return costs ?  Please get the response body of the REST call and see if the response body contains costs information.

**Comment by stevedumais** [comment]
I went on the REST try-it-now site to validate what I was seeing in the go-sdk, and didn't get any cost information back in the response.

**Comment by hyonholee** [comment]
Thanks, so it looks like the service (either CRP or ARM) does not send the information.  We will check if this is expected.

**Comment by alexeldeib** [comment]
SKUs client does not expose pricing information. You want Rate Card API (pay as you go, free trial) or Consumption/Billing API (enterprise customers).

SKUs client can be used to filter restricted resources in a given location/subscription.

**Comment by alexeldeib** [comment]
(not in PG but had this exact conversation a few days ago coincidentally, sharing the answer I got).
