### ISSUE TITLE
Bug in the Event Hubs SDK

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#413]
Thanks for adding the EventHub SDK recently.

I've been working on adding support for them into Terraform - and I believe I've found an SDK bug with one of the types is defined incorrectly. I'm getting the following error - (I've masked the Subscription ID for obvious reasons):

```
* azurerm_eventhub.test: eventhub.EventHubsClient#CreateOrUpdate: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type int32' JSON = '{"id":"/subscriptions/XXXXXXXXXXXXXXXXXXXX/resourceGroups/tomacctestrg/providers/Microsoft.EventHub/namespaces/th-eh-namespace/eventhubs/th-eh-test","name":"th-eh-test","type":"Microsoft.EventHub/EventHubs","location":"West US","tags":null,"properties":{"messageRetentionInDays":1,"status":"Active","createdAt":"2016-10-09T07:13:47.85","updatedAt":"2016-10-09T07:13:48.13","partitionCount":2,"partitionIds":["0","1"]}}'
```

I believe this error to be with the Partition ID's - which is returned as an array of strings and not Int's. For context the object is:

```
type Properties struct {
	CreatedAt              *date.Time   `json:"createdAt,omitempty"`
	MessageRetentionInDays *int64       `json:"messageRetentionInDays,omitempty"`
	PartitionCount         *int64       `json:"partitionCount,omitempty"`
	PartitionIds           *[]int32     `json:"partitionIds,omitempty"`
	Status                 EntityStatus `json:"status,omitempty"`
	UpdatedAt              *date.Time   `json:"updatedAt,omitempty"`
}
```

From what I can see - to route to fixing this is either:
 - Updating the SDK Definition to return an array of strings
 - Start returning integers from the API instead

As this SDK is auto-generated - I guess there'd be no point sending a PR to fix the type in this repo directly?

**Comment by mcardosos** [comment]
Hello! Thanks for reporting this :D
Yeah, as it is AutoRest generated, the best thing to do is update the swagger and then regen the SDK :(

**Comment by tombuildsstuff** [comment]
@amarzavery @mcardosos thanks for fixing the bug in the Swagger.. any idea when the SDK will be re-generated to account for this? Would it be possible to @ me in that PR? Many thanks :)
