### ISSUE TITLE
Pagination for UsageDetails List api requires parsing Response().NextLink to get the skiptoken

### ISSUE THREAD

**Issue by edesai** [Azure/azure-sdk-for-go#4142]

**Comment by jhendrixMSFT** [comment]
Related to https://github.com/Azure/azure-sdk-for-go/issues/2399

**Comment by RickWinter** [comment]
@ramaganesan-rg Please confirm the swagger was fixed for the missing skiptokenver and id query params in the swagger for manual paging.

Azure/azure-rest-api-specs#11351
