### ISSUE TITLE
The TumblingWindowTrigger struct is missing the `Annotations` field

### ISSUE THREAD

**Issue by kung-foo** [Azure/azure-sdk-for-go#4147]
### Bug Report

- `services/datafactory/mgmt/2018-06-01/datafactory/models.go`
- `23.0.0`
- `go version go1.11.4 linux/amd64`

- What happened?
The `TumblingWindowTrigger` struct is missing the `Annotations` field.
- What did you expect or want to happen?
To set the `Annotations` field.
- How can we reproduce it?
Try setting the `Annotations` field.
- Anything we should know about your environment.
The API accepts the field, and the DF UI sets and uses it. If I manually add it, it works just fine.

**Comment by jhendrixMSFT** [comment]
Ported to https://github.com/Azure/azure-rest-api-specs/issues/5274
