### ISSUE TITLE
Azure/azure-sdk-for-go/storage/table.go CreateTable failed

### ISSUE THREAD

**Issue by rjtsdl** [Azure/azure-sdk-for-go#415]
I am on v5.0.0 beta. 

I keep getting the failure for this CreateTable call. Here is the error message i got.

Error: _storage: status code from service response is 400 Bad Request; was expecting 201 Created_

Here is how i call this function
`tsc := i.client.GetTableService()`
`err := tsc.CreateTable((azureStorage.AzureTable)(table))`

Any idea ?

**Comment by colemickens** [comment]
What is `table` here?

**Comment by rjtsdl** [comment]
`table` here could be any string

**Comment by garimakhulbe** [comment]
@rjtsdl Can you send full request formed by sdk (using fiddler)?

@mcardosos @jhendrixMSFT Not sure. Might be date issue mentioned [here](http://stackoverflow.com/a/14866888).

**Comment by rjtsdl** [comment]
Reason found, the root cause is, the table name i used didn't conform with table name rules. 
![image](https://cloud.githubusercontent.com/assets/10858648/19445324/a75121bc-9448-11e6-84ea-138d3ba71139.png)
I will mark this as resolved
