### ISSUE TITLE
Authentication using SharedKeyCredential throws an error when correct username and  wrong secret key is given but getting stuck when wrong account name is given

### ISSUE THREAD

**Issue by PreethamTK** [Azure/azure-sdk-for-go#4167]
**credential, err := azblob.NewSharedKeyCredential(accountName, accountKey)**
Error is thrown when wrong account key is given but when the account Name is wrong there is no error thrown but the program eventually times out.

**Comment by jhendrixMSFT** [comment]
Moved to https://github.com/Azure/azure-storage-blob-go/issues/103
