### ISSUE TITLE
Unexpected CreateTable and DeleteTable result.

### ISSUE THREAD

**Issue by rjtsdl** [Azure/azure-sdk-for-go#417]
I encounter an issue that the multiple create and delete of a table result into unexpected results. 

Here is the scenario. I have 

```
    ClearStore(store)
    store.createRequiredTablesIfNotExist([]string{"subscription4b804c8ae8f6b435aa8051d467364d6bc"})
	fmt.Println("Create 1")
	ClearStore(store)
	store.createRequiredTablesIfNotExist([]string{"subscription4b804c8ae8f6b435aa8051d467364d6bc"})
	fmt.Println("Create 2")
	ClearStore(store)
	store.createRequiredTablesIfNotExist([]string{"subscription4b804c8ae8f6b435aa8051d467364d6bc"})
	fmt.Println("Create 3")
	ClearStore(store)
```
The expected result would be no error occur, since i always "create" after clearing all the tables in the account.
However, the results is, i either failed in creating the first table, or failed in creating the second table. They either return 409 conflict, which means recreating the existing table. 
Or return 404 not found even i just created the table.

Attached my file, you need to give it a accountName and accountKey of yours. **Note, ClearStore will clear every table in your accountName, be careful to use.**

[test_issue_demo.zip](https://github.com/Azure/azure-sdk-for-go/files/534741/test_issue_demo.zip)

**Comment by colemickens** [comment]
@garimakhulbe @mcardosos Are table deletes long running operations? And does the Storage client have any knowledge of polling on LROs? If not, that could be the cause of this issue.

**Comment by rjtsdl** [comment]
I tested out the potential LROs issue. Looks like it is not the case. I put enough sleep time between each of the operations above. Except taking longer to run my demo code, the output error doesn't change. So it would be better to get the sdk-for-go experts to take a look.

Meanwhile, i am trying to double test the same scenario by using C# sdk. I will get back with what i found.

**Comment by rjtsdl** [comment]
Take deletion take at least 40 seconds. So lesson learnt here is NOT do table deletion. From the sdk, no explicit way to verify the table is completely deleted or not.
