### ISSUE TITLE
Azure Automation Account

### ISSUE THREAD

**Issue by zlepper** [Azure/azure-sdk-for-go#418]
I don't see any way of interacting with the azure automation accounts right now. 

Currently I need it for simply adding another scheduler to my runbook, so it can run against multiple things. 

I have checked in both /arm and /management, neither seems to contain anything related to this.

**Comment by mcardosos** [comment]
Hello!
We cannot generate the Automation SDK until we get its [swagger](https://github.com/Azure/azure-rest-api-specs) spec.
It would be included in the `arm` folder.

**Comment by colemickens** [comment]
Related Issue: https://github.com/Azure/azure-rest-api-specs/issues/476

**Comment by marstr** [comment]
Howdy, it seems like this request is fully handled by Azure/azure-rest-api-specs#476. For that reason, I'm going to close this bug. If you feel this was in error, please feel free to re-open.
