### ISSUE TITLE
client Get return non-err but the object.property pointer is nil

### ISSUE THREAD

**Issue by lsytj0413** [Azure/azure-sdk-for-go#4182]
When I try to use the aks in azure, get the aks managed cluster use the code example:

```
		aks, err := aksClient.Get(
			context.TODO(),
			resourceGroupName,
			aksName,
		)
```

this works fine when the aksName isn't empty. but when the aksName is empty, there is no err returned and the aks.ManagedClusterProperties is nil. I also check the image.Get, it has the same behavior.

So, why not return the NotFound(or another err) in the scenario?

**Comment by jhendrixMSFT** [comment]
Hello @lsytj0413 can you please specify the API you're calling?

**Comment by lsytj0413** [comment]
I use the package **github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice** and contruct the client as:

```
	aksClient := containerservice.NewManagedClustersClientWithBaseURI(
		baseURI,
		subscriptionID,
	)
```

**Comment by jhendrixMSFT** [comment]
@yangl900 can you please comment on this?  For reference this maps the the following API in swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L334

**Comment by ArcturusZhang** [comment]
Do not get further respond from the custom, closing this one.
Feel free to reopen if there are any other questions, or raise new issues in this repo, thanks
