### ISSUE TITLE
bug in blobSASStringToSign

### ISSUE THREAD

**Issue by SeTriones** [Azure/azure-sdk-for-go#419]
stringToSign should contain SIGNED_IP and SIGNED_PROTOCOL, but currently not.
This causes GetBlobSASURI returns an invalid url.

**Comment by kpfaulkner** [comment]
@SeTriones  Are you referring to https://msdn.microsoft.com/en-us/library/azure/dn140255.aspx#Anchor_8 ?

**Comment by SeTriones** [comment]
@kpfaulkner yes.
You can see this in that page: 'Version 2015-04-05 adds support for the signed IP and signed protocol fields. These must be included in the string-to-sign. '  And I'm using version of 2015-04-05.

**Comment by kpfaulkner** [comment]
@mcardosos / @ahmetalpbalkan  I've written up a local solution to this, will submit a PR soon but have a question about preferred approach to this.

Currently I check if the API Version the user is >= "2015-04-05", if the user supplies the signedIP/protocols then I populate them.  

If the API version was < "2015-04-05" then I don't use the signedIP/protocols even if they're supplied. 

BUT I've noticed that the .NET client lib seems to generate a "2015-04-05" compatible URL regardless of the underlying API version being used. Which seems fair enough the more I think about it.

Any advice/suggestion on how we should approach this?

1) Stick with the version supplied and ignore signedIP/protocol even if provided (and not needed)
2) Always generated "2015-04-05" compatible URL regardless?

Thoughts?

**Comment by ahmetalpbalkan** [comment]
@kpfaulkner we already have date distinctions in SAS logic if I recall correctly. Any patch would be appreciated, as long as we don't break old clients or something.
