### ISSUE TITLE
Bug: InsertOrReplaceEnitity return nil in error when it should 400 bad request

### ISSUE THREAD

**Issue by rjtsdl** [Azure/azure-sdk-for-go#420]
I was confused when i successfully insert something in the table, but it is not shown in the explorer. Later i found out there is some partitionKey or rowKey limitation. It cannot be anything. In my case i have "/" in them, that is why it is not inserted sucessfully. However, it expose some **bug in the function "InsertOrReplaceEnitity"** of table storage. Developer like me do expect err message with 400 bad request, not nil.

**Comment by kpfaulkner** [comment]
Currently I'm getting back a 403 when trying to use / in a PK or RK.
Are you able to post a repro?

**Comment by rjtsdl** [comment]
Thanks, working now.
