### ISSUE TITLE
storage: Support for queue UpdateMessage operation in Go SDK

### ISSUE THREAD

**Issue by amanohar** [Azure/azure-sdk-for-go#421]
Does the current SDK for Go support UpdateMessage operation?:
https://msdn.microsoft.com/en-us/library/azure/hh452234.aspx 

Looking at the code looks like it doesn't. Can you confirm?

**Comment by colemickens** [comment]
cc: @ahmetalpbalkan any idea on this one?

**Comment by garimakhulbe** [comment]
We don't have this in SDK currently.

**Comment by ahmetalpbalkan** [comment]
True, it is not implemented. Shouldn't be hard to contribute given the examples.

**Comment by amanohar** [comment]
Thanks for confirming. I will add it and send a PR.

**Comment by amanohar** [comment]
UpdateMessage operation added to the Go SDK. Closing issue.
