### ISSUE TITLE
Bug Report: `Resource ID` is missing in API Management Logger response

### ISSUE THREAD

**Issue by JunyiYi** [Azure/azure-sdk-for-go#4211]
### Bug Report

[`Resource ID`](https://docs.microsoft.com/en-us/rest/api/apimanagement/logger/createorupdate#loggercontract) is missing in [API Management Logger response](https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2018-01-01/apimanagement/models.go#L5564).

**Comment by tombuildsstuff** [comment]
@JunyiYi it looks like it's available in the top level object: https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2018-01-01/apimanagement/models.go#L5485 :)

**Comment by jhendrixMSFT** [comment]
Tom is correct, please see here https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2018-01-01/apimanagement/models.go#L5485

**Comment by JunyiYi** [comment]
Hi @tombuildsstuff @jhendrixMSFT , it is my fault of not explaining it clearly. The Resource ID here represents `properties.resourceId`, not the `ID` of the logger.

For example, in the response body of [this example](https://docs.microsoft.com/en-us/rest/api/apimanagement/logger/createorupdate#apimanagementcreateehlogger), I mean the `resourceId` property is missing.

```json
{
  "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apimService1/loggers/loggerId",
  ...
  "properties": {
    ...
    "resourceId": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.EventHub/namespaces/hydraeventhub-ns"
  }
}
```

**Comment by jhendrixMSFT** [comment]
Thanks for clarifying.  Since this is an issue with the swagger I've ported this issue to https://github.com/Azure/azure-rest-api-specs/issues/5318
