### ISSUE TITLE
storage: Support a storage emulator

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#423]
It would be very useful to have a storage emulator for testing Go projects without needing to use a real storage server.

**Comment by mcardosos** [comment]
Hello Cole :D Actually I added this some weeks ago :D
You should be able to use [Azure Storage Emulator](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/) with some lines like this ones...
```go
client, err := storage.NewBasicClient(storage.StorageEmulatorAccountName, storage.StorageEmulatorAccountKey)
```
