### ISSUE TITLE
Define core Azure services resource Uri (audience) in SDK

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-sdk-for-go#4234]
### Feature Request
It would be convenient if we define common core Azure services resource Uri (audience) in SDK. This is related to issue #697, that the service endpoint may not exact match the resource Uri when acquiring access tokens. While #697 fixed the issue, it requires client to make one unauthenticated request first and parse the resource Uri from response header. This is additional overhead some times we want to avoid.

**Comment by jhendrixMSFT** [comment]
This has been resolved in v11.9.0 of go-autorest.
