### ISSUE TITLE
Abort Copy Blob operation.

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#424]
Currently the library supports the starting of a copy blob operation (CopyBlob function) which starts a single copy and then waits. 

I'd like to propose a new function for Aborting such a copy (see https://msdn.microsoft.com/en-us/library/azure/jj159098.aspx) as well as modifying the existing code a tiny bit.

Currently the exported function CopyBlob calls a non-exported (still trying to get my Go jargon right) startBlobCopy, then once the copying has started it loops checking the status.

I'd like to propose the following changes:
- make startBlobCopy exportable (ie name it StartBlobCopy) that way people can easily fire off a bunch of them without having to perform the wait.
- Add AbortBlobCopy which takes the copyID generated by startBlobCopy and can abort the operation if needed.

No functionality (CopyBlob function) is impacted but gives the users 2 methods (StartBlobCopy and AbortBlobCopy) which are closer (and for me personally more useful) to the REST API.

I've already coded up a PR with the above, but wanted to get opinions before I actually submit it.

Thoughts?

**Comment by ahmetalpbalkan** [comment]
@kpfaulkner sounds good. Folks can help you review if you submit a patch (with tests).

**Comment by kpfaulkner** [comment]
Closing. PR merged
