### ISSUE TITLE
Unable to create bot registration

### ISSUE THREAD

**Issue by avarabyeu** [Azure/azure-sdk-for-go#4248]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`

```go
import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/profiles/preview/preview/botservice/mgmt/botservice"
	"github.com/Azure/azure-sdk-for-go/services/keyvault/auth"
	"github.com/Azure/go-autorest/autorest"
	"github.com/pkg/errors"
	"io/ioutil"
	"os"
)
```

- SDK version e.g. `master`, `latest`, `18.1.0`
`latest`
- output of `go version`
`go version go1.12 darwin/amd64`

- What happened?
Unable to create bot channel registration 
- What did you expect or want to happen?
Registration is created
- How can we reproduce it?
```go
	rgClient := botservice.NewBotsClient(session.SubscriptionID)
	rgClient.Authorizer = session.Authorizer

	result, err := rgClient.Create(context.Background(), "bla-bla", "my-test-bot-bla-bla", botservice.Bot{
		Location: strPtr("global"),
		Name:     strPtr("my-test-bot-bla-bla"),
		Kind:     botservice.KindBot,
	})
	fmt.Println(err)
	fmt.Println(result)

```
Please note that:
1) Resource Group has been created manually and exists. 
2) Server returns the following error:
`Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Encountered internal server error. Please try again."`

![image](https://user-images.githubusercontent.com/1565439/54092698-40a69c80-43a0-11e9-8fea-4fb97baad3e7.png)

**Comment by jhendrixMSFT** [comment]
I can repro this too, I'm following up with the service team about it.

**Comment by Drewm3** [comment]
Fixing the team. This should go to the Bot Service, not compute.

**Comment by sgellock** [comment]
We don't ship Go support for the service.  Has this code path worked before?

**Comment by lirenhe** [comment]
@avarabyeu, close this item as it has been there for more than 1 year with no reply.
Please let us know if you have further comments.
