### ISSUE TITLE
Add support for managing Azure AD Directory roles (graphrbac)

### ISSUE THREAD

**Issue by tiwood** [Azure/azure-sdk-for-go#4280]
### Feature Request

Can you add support for managing Azure AD Directory Roles to the SDK? (graphrbac)

MS Graph links:

https://docs.microsoft.com/en-us/graph/api/resources/directoryrole?view=graph-rest-beta
https://docs.microsoft.com/en-us/graph/api/resources/directoryroletemplate?view=graph-rest-beta

And here are the links for Azure AD API: 

https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/directoryroles-operations

**Comment by tiwood** [comment]
This is currently blocked by https://github.com/Azure/azure-rest-api-specs/issues/5383

**Comment by sschu** [comment]
Isn't the Azure AD Graph API deprecated and the MS Graph API should be used instead anyways?

**Comment by landro** [comment]
Unfortunately, there is no golang binding yet for the MS Graph API yet. Vote for it on https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/37576909-graph-api-golang-sdk

**Comment by katbyte** [comment]
@ArcturusZhang, i can't seem to find support for directory roles in the SDK, am i just missing it? or should this not have been closed
