### ISSUE TITLE
Add compute.VirtualMachineScaleSetVMNetworkInterfaceClient

### ISSUE THREAD

**Issue by fchazel2** [Azure/azure-sdk-for-go#4301]
### Feature Request

Can you please add the required Client & structs to get Network Interfaces of Scale Set Virtual Machines? 

The network interfaces IDs can be retrieved using the 'compute.VirtualMachineScaleSetVMsClient' client, but there is currently no SDK client to retrieve network interfaces details for theses IDs

The use case is to retrieve the allocated IPs of all the VM instances in a scale set.

#### REST API for the same:

https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/getvirtualmachinescalesetnetworkinterface

```
GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines/{virtualmachineIndex}/networkInterfaces/{networkInterfaceName}?api-version=2017-03-30
```

**Comment by jhendrixMSFT** [comment]
I believe you can do this via the `InterfacesClient.GetVirtualMachineScaleSetNetworkInterface` in the `network` package.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2018-12-01/network/interfacesgroup.go#L452
Can you please take a look and let me know if it works?

**Comment by fchazel2** [comment]
Thanks a lot, this worked for me. 
I had missed this API.

Using `InterfacesClient.ListVirtualMachineScaleSetNetworkInterfaces` I can retrieve all allocated IPs for a scale set with a single call successfully.
