### ISSUE TITLE
Add vmss compute.ListInstancePublicIPs 

### ISSUE THREAD

**Issue by mjudeikis** [Azure/azure-sdk-for-go#4305]
### Feature Request

CLI has an option:
```
az vmss list-instance-public-ips -n ss-master -g rgName
```

Could we add SDK method to compute library:
```
ListInstancePublicIPs(ctx context.Context, resourceGroupName, VMScaleSetName string) ([]string, error) // somethind like this
```

**Comment by jhendrixMSFT** [comment]
That CLI command maps to API `PublicIPAddressesClient.ListVirtualMachineScaleSetPUblicIPAddresses`.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2018-12-01/network/publicipaddresses.go#L609
So you should be able to do something like this.
```go
	client := network.NewPublicIPAddressesClient("subscriptionID")
	for iter, err := client.ListVirtualMachineScaleSetPublicIPAddressesComplete(context.Background(), "resourceGroup", "scaleSet"); iter.NotDone(); err = iter.Next() {
		if err != nil {
			panic(err)
		}
		fmt.Println(*iter.Value().ID)
	}
```
Let me know if that works.

**Comment by mjudeikis** [comment]
@jhendrixMSFT awesome as always :100:
