### ISSUE TITLE
Go SDK fails to install with dependency error

### ISSUE THREAD

**Issue by seyadava** [Azure/azure-sdk-for-go#4316]
Install Go SDK fails with the following error:

> go get -u github.com/Azure/azure-sdk-for-go/...
package go.opencensus.io/exemplar: cannot find package "go.opencensus.io/exemplar" in any of:
        C:\Go\src\go.opencensus.io\exemplar (from $GOROOT)
        C:\Users\<user>\go\src\go.opencensus.io\exemplar (from $GOPATH)

**Comment by jhendrixMSFT** [comment]
This is a known upstream issue, please see https://github.com/census-instrumentation/opencensus-go/pull/1067#issuecomment-474279057.
Is there a reason you're not using `dep` for package management?

**Comment by seyadava** [comment]
Thanks for your quick response @jhendrixMSFT 

There is no technical reason. Go SDK document gives two options to install Go SDK and at the time we wrote our tests we chose to use Git instead of dep to install the SDK (mainly because we have Git installed on our environments and didn't want to install additional tools).
I can see the upstream fix is being merged 6 hours ago. But issue still repros on our end. Any ideas why?

**Comment by orlangure** [comment]
@seyadava, the PR with a fix was merged 20 minutes ago (or 6 minutes before you posted your comment).

**Comment by songy23** [comment]
https://github.com/census-instrumentation/opencensus-go/pull/1071 should temporarily fix this. Sorry for the inconvenience.

If you're using Go1.11+, maybe consider pinning a released version of `go.opencensus.io`, for example https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/ab5a58af316a529613aadf9f50eeed1b6f044b2f/go.mod#L11.

**Comment by jhendrixMSFT** [comment]
@songy23 thanks for the update.
@seyadava I highly recommend using `dep` to manage your dependencies to avoid such issues.  It's what we test with so everything should always just work.

**Comment by jhendrixMSFT** [comment]
Closing as the fix has been made upstream.
