### ISSUE TITLE
src/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:257:5: cannot use exmplr.Attachments (type metricdata.Attachments) as type map[string]string in field value

### ISSUE THREAD

**Issue by zed-rishabh** [Azure/azure-sdk-for-go#4336]
While doing **go get github.com/Azure/azure-sdk-for-go/storage**

contrib.go.opencensus.io/exporter/ocagent
My_GOPATH/src/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:257:5: cannot use exmplr.Attachments (type metricdata.Attachments) as type map[string]string in field value

**Comment by zed-rishabh** [comment]
https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/52

**Comment by songy23** [comment]
The fix in upstream (https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/53) is merged, feel free to close this issue. Moving forward, if Go modules is introduced to this project (I believe it's being discussed in https://github.com/Azure/azure-sdk-for-go/issues/2993), hopefully this kind of issues can be minimized.

**Comment by jhendrixMSFT** [comment]
In the meantime I'd suggest using `dep` to manage your dependencies until we've implemented support for modules.
