### ISSUE TITLE
disk resize 

### ISSUE THREAD

**Issue by rootfs** [Azure/azure-sdk-for-go#435]
Is there any plan to support a data disk resize?

From the [API doc](https://msdn.microsoft.com/en-us/library/azure/ee691966.aspx), updating blob size can be done by updating blob properties. Not sure if that's all it takes to change the vhd size though, since vhds also set sizes in their footers.

**Comment by mcardosos** [comment]
Hi @rootfs !
You can do something like this...
```go
	vm, err := vmClient.Get(resourceGroupName, vmName, compute.InstanceView)
	if err != nil {
		panic(err)
	}

	_, err = vmClient.PowerOff(resourceGroupName, vmName, nil)
	if err != nil {
		panic(err)
	}

	_, err = vmClient.Deallocate(resourceGroupName, vmName, nil)
	if err != nil {
		panic(err)
	}

	var index int
	for i, dd := range *vm.Properties.StorageProfile.DataDisks {
		if *dd.Name == "yourDataDisk" {
			index = i
		}
	}
	(*vm.Properties.StorageProfile.DataDisks)[index].DiskSizeGB = &newSize

	_, err = vmClient.CreateOrUpdate(resourceGroupName, vmName, vm, nil)
	if err != nil {
		panic(err)
	}
```
More on updating VMs [here](https://msdn.microsoft.com/en-us/library/azure/mt163591.aspx).
