### ISSUE TITLE
Add support for setting up SSO for Service Principal

### ISSUE THREAD

**Issue by AmudhaPalani** [Azure/azure-sdk-for-go#4381]
### Feature Request

Add support for setting up SSO for Service Principal.

Please add methods to configure azure AD SSO as mentioned in this document:
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/amazon-web-service-tutorial#configure-azure-ad-single-sign-on

**Comment by tiny-dancer** [comment]
@AmudhaPalani do you mean setting up SSO for an `enterprise application`?

**Comment by ArcturusZhang** [comment]
No further response from the customer, closing this one.
Feel free to reopen or raise new issues if any other questions occur.
