### ISSUE TITLE
v6 SDK: Usage Clarification for the Container Service

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#439]
Context: I'm trying to implement support for the Container Service into Terraform

Perhaps this isn't the right place to file this bug - but given I was trying to implement it using the Go SDK it seemed sensible - happy to open this elsewhere if needed :)

I've imported v6 of the Container Service SDK - and [built up a sample object](https://gist.github.com/tombuildsstuff/050d4f166c43ff477e27768017a9a257) - however I don't see how it's possible to specify the Operating System assigned to a particular Agent Pool?

Perhaps I'm overlooking something obvious - but I don't see how it's possible to specify the operating system for a particular agent pool? I encounter the same issue using the Azure Portal too - are Container Service Agents instances limited to Linux for the moment?

If that is the case - the [documentation](https://msdn.microsoft.com/en-gb/library/azure/mt711471.aspx) doesn't describe this limitation - but I'm assuming I could safely ignore the WindowsProfile for the moment?

Would it be possible for someone to point me in the right direction please? :)

Thanks!

**Comment by mcardosos** [comment]
Hi @tombuildsstuff  :D
Right now it is limited to Linux, so you can ignore the Windows Profile

**Comment by tombuildsstuff** [comment]
@mcardosos 👍🏼 ok cool - thanks!

Is there any plan to split the API into multiple calls btw? One giant call to manage the cluster makes life challenging to split this out into smaller resources like a resource per pool :)

**Comment by mcardosos** [comment]
Do you mean have a method to update only the `MasterProfile`, another method for `LinuxProfile` only, etc?

**Comment by colemickens** [comment]
cc: @Azure/acs

**Comment by tombuildsstuff** [comment]
@mcardosos @colemickens indeed - right now it's a lot of configuration to update in one API call. it'd be nice to be able to provision the Core with any default configurations, then say "add a linux pool with 5 agents" as a separate API call

e.g. I'd love to be able to have this as separate resources in Terraform:
```
resource "azurerm_container_service" "test" {
 type = "dcos"
}

resource "azurerm_container_agent_pool" "first_pool" {
  os = "linux"
  count = "3"
  admin_username = "foo"
  admin_password = "bar"
}

resource "azurerm_container_agent_pool" "second_pool" {
  os = "linux"
  count = "3"
  admin_username = "foo"
  admin_password = "bar"
}
```

**Comment by amanohar** [comment]
@tombuildsstuff, ACS does support specifying OS Type on AgentPool with a field called "osType". Allowed values are "Linux" and 'Windows'. Default is Linux

ACS currently does not support PATCH but you can send a partial object as part of your PUT (update) if you call the rest API. E.g. if you needed to scale up/down you could just provide agentpoolprofile in the request body. Note, however that ACS accepts only one agentpool in agentpoolprofile right now.

If you have Linux agents only then you should not specific the WindowsProfile in your request.

**Comment by tombuildsstuff** [comment]
@amanohar thanks for clarifying that - I'll look into just adding Linux support for the moment :)

Perhaps I'm looking in the wrong resource, but I don't believe that the [`osType` field is exposed via the SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/containerservice/models.go#L136) at this point?

**Comment by amanohar** [comment]
@tombuildsstuff thanks for the feedback.
