### ISSUE TITLE
arm/resources/locks: missing Get method, unclear param

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#440]
Hi, I've encountered a few issues when trying to user resource locks.

## Get misnamed

I believe the Get function should be called GetAtSubscriptionLevel, looking at the code it performs a Get for locks under the subscription scope.

## GetAtResourceLevel missing

This function doesn't exist, I can't see any other functions to use for this purpose instead.

## Unknown `parentResourcePath` param

The `parentResourcePath` path param is used in the [CreateOrUpdateAtResourceLevel](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/locks/managementlocks.go#L132) function, but I don't understand which part of a resource  ID this refers to.

`/subscriptions/abc-def/resourceGroups/res-group-1/providers/Microsoft.Storage/storageAccounts/storage-account`

resourceGroupName = res-group
resourceProviderNamespace = Microsoft.Storage
parentResourcePath = ???
resourceType = storageAccounts
resourceName = storage-account

**Comment by mcardosos** [comment]
Hello @pmcatominey !
Thanks for reporting the missing functions. I already sent a PR to the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repo, so the SDK can be regenerated later.
The `parentResourcePath` parameter is to be used when you need some extra stuff in the path... For example [SQL Databases](https://msdn.microsoft.com/en-us/library/azure/mt163685.aspx). For other resources you can just pass an empty string without problems.

**Comment by pmcatominey** [comment]
Hi @mcardosos 

Thanks for sending the PR to the specs repo!

Would it be possible to reopen this issue until the fix has landed in the SDK?

**Comment by marstr** [comment]
The above was released with version `v8.0.0-beta`.
