### ISSUE TITLE
Request for simplified & commented ARM examples/docs

### ISSUE THREAD

**Issue by robbyt** [Azure/azure-sdk-for-go#441]
I need to write a system to do some ARM automation- including creating, discovering, reading tags, deleting, etc.

However, this is a bit hard for me to get started because the examples are a bit complicated (and outdated), and the documentation about authenticating assumes a lot of prior knowledge.

Here's an example of what I consider good developer-friendly documentation: http://docs.pythonboto.org/en/latest/ec2_tut.html#an-introduction-to-boto-s-ec2-interface

Step 1: create a connection
Step 2: launch some instances
etc..

This library looks great, and I'd love to be able to start using it, but it's a bit too complicated (and under-documented) right now for me to get started without some additional help.

**Comment by mcardosos** [comment]
Hello!
For authenticating, you will need your `subscriptionID`, `tenantId`, `clientId` and `client secret`. You can get them following [this tutorial](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/) (there, the client secret is referred to as authentication key). I would recommend to set this IDs and keys as environment variables.
To use them with this SDK, your code will look similar to this...
```go
package main

import (
	"os"

	"github.com/Azure/azure-sdk-for-go/arm/resources/resources"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/autorest/to"
)

func main() {
	credentials, err := getCredentials()
	if err != nil {
		panic(err)
	}
	token, err := getToken(credentials)
	if err != nil {
		panic(err)
	}
     // Lets say you want to create a resource group...
	groupClient = resources.NewGroupsClient(credentials["AZURE_SUBSCRIPTION_ID"])
	groupClient.Authorizer = token

if _, err := groupClient.CreateOrUpdate("yourResourceGroup", resources.ResourceGroup{Location: to.StringPtr("westus"}); err != nil {
		panic(err)
	}

// getCredentials gets some credentials from your environment variables.
func getCredentials() (map[string]string, error) {
	credentials := map[string]string{
		"AZURE_CLIENT_ID":       os.Getenv("AZURE_CLIENT_ID"),
		"AZURE_CLIENT_SECRET":   os.Getenv("AZURE_CLIENT_SECRET"),
		"AZURE_SUBSCRIPTION_ID": os.Getenv("AZURE_SUBSCRIPTION_ID"),
		"AZURE_TENANT_ID":       os.Getenv("AZURE_TENANT_ID")}
	if err := checkEnvVar(&credentials); err != nil {
		return nil, err
	}
	return credentials, nil
}

// checkEnvVar checks if the environment variables are actually set.
func checkEnvVar(envVars *map[string]string) error {
	var missingVars []string
	for varName, value := range *envVars {
		if value == "" {
			missingVars = append(missingVars, varName)
		}
	}
	if len(missingVars) > 0 {
		return fmt.Errorf("Missing environment variables %s", missingVars)
	}
	return nil
}

// getToken gets a token using your credentials. The token will be used by clients.
func getToken(credentials map[string]string) (*azure.ServicePrincipalToken, error) {
	oauthConfig, err := azure.PublicCloud.OAuthConfigForTenant(credentials["AZURE_TENANT_ID"])
	if err != nil {
		return nil, err
	}
	token, err := azure.NewServicePrincipalToken(*oauthConfig, credentials["AZURE_CLIENT_ID"], credentials["AZURE_CLIENT_SECRET"], azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		return nil, err
	}
	return token, nil
}

**Comment by marstr** [comment]
@kirthik is spending some time strategizing on how to improve our samples, and many of us feel like the authentication story needs to be improved.

Given @mcardosos 's example above, I'm going to close out this issue.
