### ISSUE TITLE
Generate a function to get a resource ID without calling Azure

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#442]
Right now, some methods will [require a resource ID](https://github.com/Azure/azure-sdk-for-go/blob/bd73d950fa4440dae889bd9917bff7cef539f86e/arm/resources/resources/resources.go#L123), and the way to get it is with [Get](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/compute/virtualmachines.go#L423) methods that will return a struct containing the ID. Still, the resource ID can be built easily (and without sending a request to Azure) with `fmt.Sprintf`, similar to [this](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/compute/virtualmachines.go#L461).

It would be cool if [AutoRest](https://github.com/Azure/autorest/) generated functions like this one for resources...
```go
func (client VirtualMachinesClient) GetVirtualMachineID (resourceGroupName, vmName string) string {
   return fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/virtualMachines/%s", client.SubscriptionID, resourceGroupName, vmName)
}
```

cc @colemickens

**Comment by colemickens** [comment]
A fluent construction would be interesting as well.

`azure.Subscription(subId).ResourceGroup(rgId).Network.PublicIP(pipName)` might be interesting.

**Comment by marstr** [comment]
This is a great idea, but we'll need to figure out how this relates to the Swaggers to prevent adding too tight of a coupling between our generator and Azure Swaggers. Perhaps this is an example of a place where a Swagger extension could be helpful?

For now, this goes on the Backlog.

**Comment by joshgav** [comment]
duplicate of #322, closing
