### ISSUE TITLE
Storage Account CustomDomain has the wrong type

### ISSUE THREAD

**Issue by drosseau** [Azure/azure-sdk-for-go#4473]
### Bug Report

github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2018-11-01/storage

- What happened?

The JSON and Go type don't match up for [CustomDomains](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2018-11-01/storage#CustomDomain). The Go type is `*bool`, but the JSON contains a string.

- What did you expect or want to happen?

Types match.

- How can we reproduce it?

Create a storage account with a custom domain and use the AccountsClient to list storage accounts.

- Anything we should know about your environment.

Normal. Go version 1.12.1

**Comment by jhendrixMSFT** [comment]
Hello!  If you have an easy repro could you please provide the JSON response body of the failed request?  You can use the built in [logging](https://github.com/azure/azure-sdk-for-go#built-in-basic-requestresponse-logging) facility to log request/response bodies to get this info.  Thanks!

**Comment by jhendrixMSFT** [comment]
@drosseau according to the RP this should be resolved, now when you call the API the value for `useSubDomainName` is no longer sent across the wire.  Can you confirm it works for you now?

**Comment by drosseau** [comment]
Yep, I don't see `useSubDomain` anymore.

**Comment by jhendrixMSFT** [comment]
Closing as this is now resolved, thanks for helping.
