### ISSUE TITLE
Applications - parity with oauth2AllowIdTokenImplicitFlow as separate from oauth2AllowImplicitFlow

### ISSUE THREAD

**Issue by DavidR91** [Azure/azure-sdk-for-go#4478]
**Feature request**
Both in the portal and in the resulting manifest, AD applications can now separate implicit flow into allowing access tokens and/or ID tokens:

![image](https://user-images.githubusercontent.com/282737/55550459-24acc700-56d0-11e9-823f-e9e353519579.png)

![image](https://user-images.githubusercontent.com/282737/55550486-2f675c00-56d0-11e9-87c8-780d468d0ba0.png)

whereas this SDK only exposes Oauth2AllowImplicitFlow 

There is a use case for allowing implicit flow only for id_token, so having parity with this functionality in this SDK would be exceptionally useful

(Specific use case is upstream consumption of this SDK by Terraform)

**Comment by ArcturusZhang** [comment]
Staled issue, closing

**Comment by scivm** [comment]
This is not a stale issue and is relevant to those trying to deploy applications using the sdk for go (terraform)

**Comment by ArcturusZhang** [comment]
> This is not a stale issue and is relevant to those trying to deploy applications using the sdk for go (terraform)

Could you please open a new issue about this? It would be better if you can provide more context about the terraform usage in the new issue.
