### ISSUE TITLE
Create sample for Management - NetworkSecurityGroup

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#451]
Be sure to include the following operations.

get (withId)
updateRules

**Comment by salameer** [comment]
@marstr

**Comment by marstr** [comment]
This had gone on the backburner for a while, so progress was paused. However, I've resumed working on it as of this morning.

**Comment by marstr** [comment]
I believe I'm at code-complete for this sample. Last step will be writing the README.

**Comment by marstr** [comment]
I'm actively working on completing this task, so I'm taking it out of the Backlog.

**Comment by marstr** [comment]
Done. The sample can be found here:
[Azure-Samples/network-go-manage-network-security-group](https://github.com/Azure-Samples/network-go-manage-network-security-group)
