### ISSUE TITLE
Add support for Storage -  FileStorage

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#452]
Be sure to include support for the following operations.

getShare
createShare
deleteShare
getDir
createDir
deleteDir
downloadFile
uploadFile
deleteFile
setContentMD5
getContentMD5

**Comment by jhendrixMSFT** [comment]
Also be sure to create a matching sample.

**Comment by kpfaulkner** [comment]
Has this been started on already? Or can anyone pick it up and start working on it?

**Comment by kpfaulkner** [comment]
Just to clarify, looking at https://msdn.microsoft.com/en-us/library/azure/dn167006.aspx I don't see any immediate equivalent to "getShare" and "getDir". Am I right in assuming the "list" functionality is what's desired here?

**Comment by jhendrixMSFT** [comment]
You are correct.  I've started work on this yesterday, you can see my progress in my fork at https://github.com/jhendrixmsft/azure-sdk-for-go/tree/filestorage if you're interested.

**Comment by kpfaulkner** [comment]
Ah cool. I was going to start having a go at it, but if you're already on it I'll leave it be :)

**Comment by jhendrixMSFT** [comment]
The bulk of this was implemented in commit https://github.com/Azure/azure-sdk-for-go/commit/9a8a7d6ebdf934c3b5d3b82cbcd1c5a5b37eef05.  Only remaining item is support for content MD5.

**Comment by jhendrixMSFT** [comment]
The work was completed in the dev branch in commit https://github.com/Azure/azure-sdk-for-go/commit/3e97528bc3e487a719b8001f31e914ea02ca8fcf#diff-ddecebdea58b5f264d27f1f7909bab74.
