### ISSUE TITLE
Wrong Go type for field "documentdb.Usage.Limit"

### ISSUE THREAD

**Issue by lukasmalkmus** [Azure/azure-sdk-for-go#4521]
### Bug Report

- Import: `github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb`
- SDK version: `v27.0.0`
- Go version: `go version go1.12.3 darwin/amd64`

### What happened?

We saw errors in CI due to the `documentdb.DatabaseAccountsClient#ListUsages` returning an error:

```
documentdb.DatabaseAccountsClient#ListUsages: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number 107374182400 into Go struct field Usage.limit of type int32' JSON = '{"value":[{"unit":"Bytes","quotaPeriod":"P1D","limit":107374182400,"currentValue":184320,"name":{"value":"Storage","localizedValue":"Storage"}}]}'
exit status 1
```

The value `107374182400` does not fit an `int32`.

### What did you expect or want to happen?

To get a result and a `nil` error.

### How can we reproduce it?

`main.go`:

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb"
	"github.com/Azure/go-autorest/autorest/azure/auth"
	"github.com/Azure/go-autorest/autorest/to"
)

func main() {
	authorizer, err := auth.NewAuthorizerFromEnvironment()
	if err != nil {
		log.Fatal(err)
	}

	client := documentdb.NewDatabaseAccountsClient(os.Getenv("AZURE_SUBSCRIPTION_ID"))
	client.Authorizer = authorizer

	result, err := client.ListByResourceGroup(context.Background(), os.Getenv("AZURE_RESOURCE_GROUP"))
	if err != nil {
		log.Fatal(err)
	}

	if result.Value == nil {
		log.Fatal("result has no values")
	}

	for _, v := range *result.Value {
		_, err = client.ListUsages(context.Background(), os.Getenv("AZURE_RESOURCE_GROUP"), to.String(v.Name), "")
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

`go run main.go`

Expecting all env-vars to be set correctly.

### Anything we should know about your environment.

No.

**Comment by ronoc** [comment]
I have ran into similar issues come to think of it, any chance someone could take a look  ?

**Comment by jhendrixMSFT** [comment]
@shurd looks like the `limit` field is incorrectly defined as `integer` in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json#L1976), it should be `long` instead.  Can you confirm this is correct?

**Comment by ronoc** [comment]
Yep, that's correct.

**Comment by bahlo** [comment]
Same goes for `currentValue`, (see [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json#L4402)).

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v30.0.0
