### ISSUE TITLE
Add support for GraphRbac api

### ISSUE THREAD

**Issue by TamalSaha** [Azure/azure-sdk-for-go#455]
We would like to call GraphRbac api via GO. I noticed that it was commented out in the gen.go file. 
https://github.com/Azure/azure-sdk-for-go/blob/master/Gododir/gen.go#L118

Can we get this api added to GO SDK?

Thanks.

**Comment by jhendrixMSFT** [comment]
This is dependent on fixing support for composite swaggers in the Go generator, see https://github.com/Azure/autorest/issues/1746.

**Comment by mcardosos** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/pull/561
I should add that it is not using composite swaggers, so some operations might not be supported. Feel free to reopen the issue if you think it is not correctly solved.
