### ISSUE TITLE
Adding support for dnsZoneId and privacy properties for App Service Domain

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/azure-sdk-for-go#4573]
### Feature Request

The latest REST API can link an App Service Domain to an existing Azure DNS id through the dnsZoneId property

The privacy property is also missing.

https://docs.microsoft.com/en-us/rest/api/appservice/domains/createorupdate

Current implementation:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2018-02-01/web/domains.go

**Comment by jhendrixMSFT** [comment]
I see the properties here:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2018-02-01/web/models.go#L9686
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2018-02-01/web/models.go#L9665
Do these work or am I looking at the wrong thing?

**Comment by ArcturusZhang** [comment]
Hi @LaurentLesle , does the advice above work?
