### ISSUE TITLE
azure structs are missing Done method

### ISSUE THREAD

**Issue by ILoveGolang123** [Azure/azure-sdk-for-go#4579]
### Bug Report

go-autorest latest commit breaks azure sdk.
https://github.com/Azure/go-autorest/commit/fe1ebaab71ae2a2ab8a55f62ebe54cffd842acc2

### Breaking Changes
In preparation for modules the following deprecated content has been removed.

  - async.NewFuture()
  - async.Future.Done()

All instances of "future.Done()" need to be changed to DoneWithContext

**Comment by jhendrixMSFT** [comment]
Resolved in https://github.com/Azure/azure-sdk-for-go/releases/tag/v28.0.0
