### ISSUE TITLE
Cognitive Services API

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#458]
Just a general query. Do any FTEs/anyone know anything about a Go SDK/client-lib for the Azure Cognitive Services?

I've looked at the REST APIs (eg https://dev.projectoxford.ai/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fa ) and am thinking of writing up a Go lib.

I'm wondering if anyone knows if there are Swagger definitions of this (which might then auto generate a Go client lib)? If that's possible then I feel I'd be wasting my time working on a client lib.

Would any Go work on this be suitable as an add on to this repo? (it's Azure and Go related so seems fair) or should it be something separate?

Thoughts?

**Comment by colemickens** [comment]
The top right-hand corner of that page links to a Swagger spec. Presumably it would work with go-autorest.

From the looks of it, this isn't terribly Azure related, so it might make sense in a separate library, but again, I'll defer to @mcardosos and co.

**Comment by kpfaulkner** [comment]
hahaha cant believe I missed that link. Doh!
Was wondering about the applicability of Azure here.... but an example URL is https://azure.microsoft.com/en-us/services/cognitive-services/

It IS being offered by Azure itself.

But you're right, if the swagger is already there then not sure I'll bother coding anything.

**Comment by colemickens** [comment]
In that case, I would go look at [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) and see if they have the Swagger for it. If not, I'd start in that repo and ask them to add the relevant Swagger, and then it would make sense to auto-gen the client in this project.

**Comment by vishrutshah** [comment]
Regarding: https://github.com/Azure/azure-rest-api-specs/issues/731
cc:
@daniel-ms

**Comment by marstr** [comment]
Closing this issue, as it seems that this made its way into the arm packages:
[/azure-sdk-for-go/arm/cognitiveservices/
](https://github.com/Azure/azure-sdk-for-go/tree/master/arm/cognitiveservices)

If you fell that this is in error, feel free to reopen so that we can triage again.
