### ISSUE TITLE
Verify correctness and completeness of x-ms-odata extension for Go Generator

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-go#460]
https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-odata

**Comment by jhendrixMSFT** [comment]
There appears to be some support for this extension, e.g. if you look at the following.
https://github.com/Azure/azure-sdk-for-go/blob/master/arm/apimanagement/apis.go#L390
The last three parameters are for OData queries.  I don't know if this is complete though and the extension is a bit light on details.  @vishrutshah what do you think?

**Comment by vishrutshah** [comment]
@jhendrixMSFT That's a great question. I'd look into how .net handles it and then see whether we need all of those in Go generator or not.

**Comment by jhendrixMSFT** [comment]
We might need to call AutoRest.Extensions.Azure.ParseODataExtension() in the Go generator when transforming the code model.

**Comment by jhendrixMSFT** [comment]
In Go the OData parameters are treated like ordinary parameters, which is the right thing to do.
