### ISSUE TITLE
Application insights frustration

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#4601]
Hi

As much as I love this project, sometimes I really feel like I'm fighting the SDK as opposed to using it to develop my software.

I've recently needed to start coding against the app insights set of APIs. I've setup an AD app, set perms in IAM etc etc.... but I always end up with:

insights.MetricsClient#GetMetadata: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="InsufficientAccessError" Message="The provided credentials have insufficient access to perform the requested operation" InnerError={"code":"InvalidTokenError","message":"Could not validate the request. Challenge failed: SignatureVerificationFailed"}

(or similar).

And this was just to call the metrics metadata endpoint.

After a few hours of frustration, it took 2 minutes to code up something without the SDK.

request, err := http.NewRequest("GET", "https://api.applicationinsights.io/v1/apps/yyyyy/metrics/metadata", nil)
if err != nil {
	log.Fatalln(err)
}

request.Header.Set("x-api-key", "xxxxx")

resp, err := client.Do(request)
if err != nil {
	log.Fatalln(err)
}

Of course I'll have to do all the serialising/deserialising myself...   but I'm making progress so much more quickly than with the SDK.

(sorry if this just seems like a big whinge).

This is a long way of asking, is there any documentation/examples/ANYTHING for the app insights via this SDK? Since I'm at the point where I think I might roll my own and then come back and refactor once I figure the SDK out, but I feel I must be missing something obvious. I love this SDK for other aspects of Azure and am also a constant user of the storage SDK. But lately I seem to be fighting the SDK as opposed to using it.

Thoughts/comments?

Cheers

Ken

**Comment by jhendrixMSFT** [comment]
This is for package `github.com/Azure/azure-sdk-for-go/services/appinsights/v1/insights` yes?  Since this is data-plane I guess it doesn't use a bearer authorizer like most of the management-plane packages do.  I will work on getting the appropriate authorizer for this package implemented in `go-autorest`.
Looking at our [samples repo](https://github.com/azure-samples/azure-sdk-for-go-samples) I don't see any samples for this package.  Generally speaking samples is something we're aware of that's lacking however we haven't had the time to improve them.  :(

**Comment by kpfaulkner** [comment]
Hi Joel,

Yes, that's the package in question. Ideally I'd like to use the API that can be created specifically for App Insights, but I'll take anything on offer. Sorry if I came across grumpy in the original post, just that I'd been fighting for ages against it and the fact 10 lines of non SDK code does the job. I'm working on a PR for a 3rd party application that uses integrates with Azure. I suspect if I did it without using the SDK they'd have some complaints.

Again, sorry for the original tone and I completely understand about lack of time (something I specialise in ;) )

Cheers

Ken

**Comment by jhendrixMSFT** [comment]
I think this will get you a little closer.
```go
package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/services/appinsights/v1/insights"
	"github.com/Azure/go-autorest/autorest"
)

func main() {
	client := insights.NewMetricsClient()
	client.Authorizer = autorest.NewAPIKeyAuthorizerWithHeaders(map[string]interface{}{
		"x-api-key": "<key>",
	})
	results, err := client.GetMetadata(context.Background(), "appID")
	if err != nil {
		panic(err)
	}
	fmt.Println(results.Value)
}
```
Unfortunately the return object `results.Value` is of type `interface{}` which is not super-helpful (presumably it's a free-form JSON object of some kind).

**Comment by alexeldeib** [comment]
@jhendrixMSFT @kpfaulkner Stumbled on this issue, wish I'd seen it sooner. You're correct it doesn't use an ARM bearer token. That API accept tokens requested using resource = https://api.applicationinsights.io. Not sure how you are trying to authenticate but all the standard Go SDK authentication techniques should expose a resource parameter. And yes, we of course support API keys with that API. 

All of the above applies to the Log Analytics data plane too, but with https://api.loganalytics.io

I'm a heavy user of the Go SDK and wrote some of the data plane specs. Indeed, the results returned by our API are essentially free form json data (database rows from queries returning arbitrary schema). I'm no longer working specifically in this area but happy to help if we can improve the experience.

**Comment by ArcturusZhang** [comment]
Feel free to reopen or raise new issues if any other questions occur, thanks!
