### ISSUE TITLE
Generate container registry SDK

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#462]
[Swagger](https://github.com/Azure/azure-rest-api-specs/tree/master/arm-containerregistry) is available!
~~Note: it requires [x-ms-client-flatten](https://github.com/Azure/autorest/issues/1620)~~

**Comment by brendandburns** [comment]
Can I help with this?  What needs to be done (I'd love to get this in soon-ish as it's blocking some upstream work...)

Thanks!
--brendan

**Comment by jhendrixMSFT** [comment]
This was resolved in the latest beta.  https://github.com/Azure/azure-sdk-for-go/releases/tag/v7.0.0-beta
