### ISSUE TITLE
Storage unit test is failing when running tests under Linux against real storage account

### ISSUE THREAD

**Issue by alukyan** [Azure/azure-sdk-for-go#465]
I suspect this failure is related to using storage emulator for running unit tests vs using real storage account (local time vs UTC). I am not aware of storage emulator for Linux so I was running unit tests for my fork against real storage account. I have [a fix in my fork](https://github.com/alukyan/azure-sdk-for-go/commit/201b3fc48d395b5a810f8a79ce07fbca8303749a#diff-380f97775176bea8267283dcb409b023), but I am not sure if this is the right one if Azure team is using different test setup

**Comment by kpfaulkner** [comment]
Co-incidentally I've got that UTC() fix in. PR waiting review at the moment

**Comment by salameer** [comment]
hi Ken, can you please point us to the PR that  you're reffering to here?

**Comment by kpfaulkner** [comment]
Hi

In https://github.com/Azure/azure-sdk-for-go/pull/468 I added a UTC check to the blob test.

I believe it's related to what's discussed here.

Thanks

Ken

**Comment by marstr** [comment]
@alukyan Have we confirmed that this issue is fixed after the Pull Request above?

**Comment by alukyan** [comment]
I think this issue is fixed. Closing it
