### ISSUE TITLE
Storage tables - support for ETags as optimistic concurrency tokens and OData JSON format for explicit property types

### ISSUE THREAD

**Issue by alukyan** [Azure/azure-sdk-for-go#466]
Current implementation of TableServiceClient only provides one operation with "IfMatch" parameter that should contain entity ETag, but it is unclear how to get ETag for the entity in the first place.
Update operations do not support ETags. Is there plan to support this feature or I should just do something about it in my own fork?

Also, is there plan to support OData JSON format for inserting and updating entities in storage tables to be able to specify explicit types for properties?

**Comment by salameer** [comment]
Hi Andrey, we'll need sometime to investigate this and get back to you

**Comment by marstr** [comment]
For further conversation on this topic, please see the issue linked above.
