### ISSUE TITLE
Table ACLs not supported

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#467]
Cannot set or get Table ACLs as per https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/get-table-acl   and https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/set-table-acl

About to submit a PR

**Comment by salameer** [comment]
@marstr

**Comment by salameer** [comment]
THANKS for the PR Ken, assigning folks to take a look at it

**Comment by mcardosos** [comment]
Thanks for your contribution! @kpfaulkner
