### ISSUE TITLE
`go get` latest fails due to UUID usage

### ISSUE THREAD

**Issue by aviaoh** [Azure/azure-sdk-for-go#4690]
### Bug Report
PR https://github.com/Azure/azure-sdk-for-go/pull/4640 override some change made in https://github.com/Azure/azure-sdk-for-go/pull/948, and cause `go get` to fail with following error:
```
../../Azure/azure-sdk-for-go/storage/table_batch.go:135:61: multiple-value uuid.NewV1() in single-value context
../../Azure/azure-sdk-for-go/storage/table_batch.go:142:48: multiple-value uuid.NewV1() in single-value context
```

- import path of package in question, e.g. `storage/table_batch.go`
- SDK version: `latest`
- output of `go version`:  `go1.12.4 linux/amd64`

- What happened?
`go get` latest fails due to UUID usage

- What did you expect or want to happen? successful `go get`

**Comment by gourlaa** [comment]
We have the same problem

**Comment by jhendrixMSFT** [comment]
The problem here is that HEAD and tag v1.2.0 (the version we reference) have different signatures for uuid.NewV1(). If you're not using dep to manage dependencies can you please pin your module dependency to v1.2.0 to uuid?

**Comment by jhendrixMSFT** [comment]
Resolved in https://github.com/Azure/azure-sdk-for-go/releases/tag/v28.1.0
