### ISSUE TITLE
Clean up storage APIs

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#470]
In implementing the new file storage APIs we noticed there is a lot of room for improvement in the other APIs.  E.g. in blob.go GetBlobRange() we use an "extraHeaders" parameter to specify well-defined options (which then requires that the consumer goes to the docs and reads through the request headers section; every consumer has to do this over again).  We should use well-defined params (e.g. struct) with defined types to make the APIs easier to use.

**Comment by marstr** [comment]
For further conversation on this topic, please see the issue linked above.
