### ISSUE TITLE
Discuss splitting ARM and dataplane into separate repos

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#471]
Other SDKs have them split, we should discuss if it makes sense for Go.

**Comment by colemickens** [comment]
Is there a benefit to doing so?

Can you link me to some examples of this pattern in the other SDKs? I had
thought they were still in the same GitHub repo.

**Comment by jhendrixMSFT** [comment]
That's what we need to figure out.  It would allow the two stacks to version independently which could be useful in the context of breaking changes.
The Ruby SDK is split in this way, see https://github.com/azure/azure-sdk-for-ruby and https://github.com/Azure/azure-storage-ruby.  I will follow up with them on details.

**Comment by mcardosos** [comment]
Does glide allow to use a different tagged version for each subpackage?

**Comment by marstr** [comment]
We're going to open a new issue here shortly with a new proposal around package management. I'm going to close this issue for now.
