### ISSUE TITLE
Whole numbers that are `float64` are being interpreted as ints

### ISSUE THREAD

**Issue by jakebjorkekato** [Azure/azure-sdk-for-go#4733]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
   - github.com/Azure/azure-sdk-for-go/storage/entity.go
   - github.com/Azure/azure-sdk-for-go/storage/odata.go

- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
```
PROJECT                                                  CONSTRAINT          VERSION             REVISION  LATEST    PKGS USED
github.com/Azure/azure-sdk-for-go                        ^23.0.0             v23.0.0             07f918b   v23.2.0   10
```

- output of `go version`
    - go version go1.12 linux/amd64

- What happened?
    - We are writing `float64` values in a column to table storage.
    - All values with decimals are being written correctly
    - Whole numbers are being written as `Int32` see images 

No decimal

![image](https://user-images.githubusercontent.com/15744759/57089203-82313500-6cc9-11e9-9a56-14f1435d2701.png)

Decimal

![image](https://user-images.githubusercontent.com/15744759/57089718-b2c59e80-6cca-11e9-86e6-e58a4456d7c5.png)

- What did you expect or want to happen?
    - The `Value` property to be listed as a `Double` 

- How can we reproduce it?
    - Write to table storage with 2 columns both of which has the type in go as `float64`
    - Set one of them to `1.5` and one to `1`
    - Check the table object, when you look at the types one will be `Double` the other will be `Int32`
    - If you are reading these out as `float64` because that is what you wrote them as, the one with the `1` value will be read as `0`

- Anything we should know about your environment.

We are happy to send a PR but we believe the fix would be to make the below modifications

At [L30 of storage/odata.go](https://github.com/Azure/azure-sdk-for-go/blob/7971189ecf5a584b9211f2527737f94bb979644e/storage/odata.go#L30)

Add `OdataDouble = "Edm.Double"`

At `MarshalJSON` in [storage/entity.go](https://github.com/Azure/azure-sdk-for-go/blob/master/storage/entity.go#L241)

Add 

```
case float64:
    completeMap[typeKey] = OdataDouble
    completeMap[k] = fmt.Sprintf("%v", v)
```

Also in the check for the `OdataTypeSuffix` add a check for the `OdataDouble` suffix there

**Comment by jhendrixMSFT** [comment]
@jakebjorkekato could you give the change in https://github.com/Azure/azure-sdk-for-go/pull/4737 a try and verify it fixes your scenario?

**Comment by jakebjorkekato** [comment]
@jhendrixMSFT see the below test using the update.  Seems to have done the trick.  

FYI we tested `float32` as well just to see if the same behavior existed.

![image](https://user-images.githubusercontent.com/15744759/57156671-24255000-6da4-11e9-9c48-3f34abd2d97c.png)

**Comment by jhendrixMSFT** [comment]
Thanks for the info.  Seems like this should be expanded to cover float32 as well (I was thinking about this as I coded it up yesterday).  I'm not familiar with table storage and usage though so let me know if you disagree.

**Comment by jakebjorkekato** [comment]
If it is not a big deal to add it.  I know it is outside the requirements of the issue.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v29.0.0, thanks for reporting.
