### ISSUE TITLE
Official Release versions.

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#474]
Hi

Just wondering about how versioning, API stability/consistency etc are handled in this project?
I'm sort of under the impression that the GO SDK is still in adhoc development mode and once it gets to a certain "level" (what exactly that means, I'm not sure) then it would be stabilised and released.

Is this correct? Also is there any rough roadmap of where this SDK is headed? Knowing roughly the plans (if possible) would be great visibility. 

Merely curious and eager to contribute :)

Thanks

Ken

**Comment by marstr** [comment]
Howdy Ken, there's another thread about this same topic. Please see #432.

Note, we're working on a real answer to that thread too, and plan to respond next week.

I'm going to close this for now, but feel free to re-open if you think this is a distinct conversation.
