### ISSUE TITLE
Application Insights Continuous Export: How to get Export ID on create?

### ISSUE THREAD

**Issue by kmoe** [Azure/azure-sdk-for-go#4745]
## Environment

Import path: `.../services/appinsights/mgmt/2015-05-01/insights`
SDK version: 75f8b5f681677ab9f5d8c27c25b7169d46a37e7e
Go version: `go version go1.12.4 linux/amd64`

## What I am trying to do 

I want to use the Azure Go SDK to create a Continuous Export configuration for an existing Application Insights component. I need to save the Export ID on creation so I can use it later.

## What I expect

When I call `Create` from `exportconfigurations.go`, I expect to receive a response containing details of the export configuration I just created, including the Export ID.

## What happens

When I call `Create`, I get a response containing all export configurations (as if I had called `List`), not just the one I just created.

See the signature of the `Create` function: https://github.com/Azure/azure-sdk-for-go/blob/75f8b5f681677ab9f5d8c27c25b7169d46a37e7e/services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go#L50

It returns `ListApplicationInsightsComponentExportConfiguration`:
https://github.com/Azure/azure-sdk-for-go/blob/75f8b5f681677ab9f5d8c27c25b7169d46a37e7e/services/appinsights/mgmt/2015-05-01/insights/models.go#L1035,L1039

Since I do not know which member of the returned list is the export configuration I just created, I am unable to save the Export ID.

## Further details

Experimenting using the Azure Portal shows the REST API used in that webapp behaves in a similar way.

When I create an export configuration (and one already exists), the request payload for the API request is:
```
{"requests":[{"httpMethod":"GET","requestHeaderDetails":{"commandName":"AppInsightsExtension."},"url":"https://management.azure.com/subscriptions/.../resourcegroups/kmoe_test_rg/providers/microsoft.insights/components/kmoe_test_ai/ExportConfiguration?api-version=2015-05-01"}]}
```
and the response is:
```
{"responses":[{"httpStatusCode":200,"headers":{...},"content":[{"ExportId":"...",...},{"ExportId":"...",...}]}
```
The response contains both export configurations, not just the one I just created.

## Why I think this is a bug

It may be possible to guess which of the returned array of export configurations is the one I just created, based on the order of the array, or the `LastUserUpdate` field in the `ApplicationInsightsComponentExportConfiguration` (https://github.com/Azure/azure-sdk-for-go/blob/75f8b5f681677ab9f5d8c27c25b7169d46a37e7e/services/appinsights/mgmt/2015-05-01/insights/models.go#L531).

However, this is not robust, as it is possible that another `Create` request was made at roughly the same time as mine, so the export configuration whose ID I want is not the latest one in the returned list.

**Comment by jhendrixMSFT** [comment]
Hello!  I spoke with the service team about this, unfortunately there is no support for this right now and no real workaround :(.  Their suggestion is to open an issue on https://feedback.azure.com/forums/357324-application-insights to track this.  Please let me know if you have further questions.

**Comment by kmoe** [comment]
Thank you. I've created an issue: https://feedback.azure.com/forums/357324-application-insights/suggestions/37643014-return-export-id-on-application-insights-continuou
