### ISSUE TITLE
Add swagger-to-sdk for automatic PRs

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#476]
I guess we'll need to modify our `gen.go` file, but [this](https://github.com/lmazuel/swagger-to-sdk) would be really useful.

**Comment by marstr** [comment]
Once we have a resolution to #517, it'll be easier to make progress here. In general, the more granular the repositories that we can get, the more sense automatic PRs will make.

**Comment by joshgav** [comment]
we're tracking this elsewhere, so closing. thanks!
