### ISSUE TITLE
v7 of the SDK is Unusable

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#477]
Hello! 👋🏻

So I’ve just tried migrating to v7 of the SDK from v6, including the source changes required. I’ve then tried to Create Redis Instance through the API - which fails for validation reasons.

Digging into the SDK - it looks like the property has changed so you’re using the type name as the property name; but the validation still references the old name. I took a couple of minutes to go through the [v7 PR](https://github.com/Azure/azure-sdk-for-go/pull/472) and found a ton of these which all follow the same pattern:

This issue references the Create Redis SDK - but it’s also applicable to the other SDK’s listed at the bottom of this Issue, and more

The following Diff is from the Models class for Redis in the v7 PR (links below):

```
// CreateParameters is parameters supplied to the Create Redis operation.
  type CreateParameters struct {
 -	ID         *string             `json:"id,omitempty"`
 -	Name       *string             `json:"name,omitempty"`
 -	Type       *string             `json:"type,omitempty"`
 -	Location   *string             `json:"location,omitempty"`
 -	Tags       *map[string]*string `json:"tags,omitempty"`
 -	Properties *CreateProperties   `json:"properties,omitempty"`
 +	ID                *string             `json:"id,omitempty"`
 +	Name              *string             `json:"name,omitempty"`
 +	Type              *string             `json:"type,omitempty"`
 +	Location          *string             `json:"location,omitempty"`
 +	Tags              *map[string]*string `json:"tags,omitempty"`
 +	*CreateProperties `json:"properties,omitempty"`
  }
```

When you then dig into the Create operation - it includes the following validation:
```
 func (client Client) Create(resourceGroupName string, name string, parameters CreateParameters, cancel <-chan struct{}) (result autorest.Response, err error) {
  	if err := validation.Validate([]validation.Validation{
 		{TargetValue: parameters,
 			Constraints: []validation.Constraint{{Target: "parameters.Properties", Name: validation.Null, Rule: true,
 				Chain: []validation.Constraint{{Target: "parameters.Properties.Sku", Name: validation.Null, Rule: true,
 					Chain: []validation.Constraint{{Target: "parameters.Properties.Sku.Capacity", Name: validation.Null, Rule: true, Chain: nil}}},
 				}}}}}); err != nil {
 		return result, validation.NewErrorWithValidationError(err, "redis.Client", "Create")
 	}
```

In the diff above - the `Properties` property name has been removed from the source code. This means the name of the type is used as the property name instead - which ends up being either `CreateProperties`/`ResourceProperties`/`UpdateProperties` depending on the class that you’re referencing - which means it's impossible to match the validation.

Unfortunately this bug appears to in a ton of the Child SDK's within v7 of the main SDK - meaning that (IMO) v7 of the SDK is unusable in it's current form.

In my brief look through the PR - the following API’s are affected:

- Redis
  - [Model](https://github.com/Azure/azure-sdk-for-go/pull/472/files#diff-9c7ef0ef55f487cace5ff09b22e19460L105)
  - [Validation](https://github.com/Azure/azure-sdk-for-go/pull/472/files#diff-a81fe33250b82ce0c9c48ebaf5586b19L54)
- DocumentDB
  - [Model](https://github.com/jhendrixMSFT/azure-sdk-for-go/blob/efd3285ca0b0486beb00ad000fcb66499697aad1/arm/documentdb/models.go#L104)
  - [Validation](https://github.com/jhendrixMSFT/azure-sdk-for-go/blob/efd3285ca0b0486beb00ad000fcb66499697aad1/arm/documentdb/databaseaccounts.go#L132)
- Batch
  - [Model](https://github.com/Azure/azure-sdk-for-go/pull/472/files#diff-84bb661c9a1ca07626646ca138a4bfe0L76)
  - [Validation](https://github.com/jhendrixMSFT/azure-sdk-for-go/blob/efd3285ca0b0486beb00ad000fcb66499697aad1/arm/batch/accountoperations.go#L70)
- Policy
  - [Model](https://github.com/jhendrixMSFT/azure-sdk-for-go/blob/efd3285ca0b0486beb00ad000fcb66499697aad1/arm/documentdb/models.go#L104)
  - [Validation](https://github.com/jhendrixMSFT/azure-sdk-for-go/blob/efd3285ca0b0486beb00ad000fcb66499697aad1/arm/documentdb/databaseaccounts.go#L132)
- Locks

There’s probably more - but I stopped looking once I’d confirmed it wasn’t just a Redis thing.

Perhaps I’m holding it wrong or something - but given that v7 of the SDK has been released - would it be possible for someone to take a look into this please? :)

Thanks!

**Comment by mcardosos** [comment]
Hello @tombuildsstuff 
7.0.1 is merged with the fix. We are so sorry for the inconvinience

**Comment by tombuildsstuff** [comment]
Thanks a lot @mcardosos - I'll give it a whirl :)

**Comment by tombuildsstuff** [comment]
@mcardosos looks a lot better - thanks a bunch! :)
