### ISSUE TITLE
Databricks deployment to custom vnet

### ISSUE THREAD

**Issue by eCraftExtensions** [Azure/azure-sdk-for-go#4772]
### Feature Request

Databricks on Azure supports deployment to custom virtual network. This is not yet supported on Azure sdk for go. Details and ARM templates for this can be found on these links:

https://docs.azuredatabricks.net/administration-guide/cloud-configurations/azure/vnet-inject.html
https://github.com/Azure/azure-quickstart-templates/tree/master/101-databricks-workspace-with-vnet-injection/

**Comment by jhendrixMSFT** [comment]
@botang-databricks do you know if this is planned to be added to the swagger for databricks?

**Comment by ArcturusZhang** [comment]
Staled issue, closing
