### ISSUE TITLE
v7.0.1 still contains a number of surprising changes

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#479]
Even with 7.0.1, there are a lot of changes that cause a lot of churn.

@brendandburns updated Kubernetes to use commit 0984e0641ae43b89283223034574d6465be93bf4 (aka, )  of azure-sdk-for-go and had to make this many changes: https://github.com/kubernetes/kubernetes/pull/37783/commits/ea14bba4b2412c3403c4a1036348ae745bb93331

Is this expected? It looks like in a number of places, `Properties` was removed, or renamed. Maybe this is all due to flattening? 

Also, the CHANGELOG wasn't updated for 7.0.1.

**Comment by mcardosos** [comment]
All that is because of flattening, yes.

**Comment by tombuildsstuff** [comment]
@mcardosos @colemickens is this also going to become an issue when more API's are migrated towards Composite Swagger's out of interest?

There's a couple of really painful unannounced changes in v7.x - particularly with regards to CDN's - where the method signature has changed from `(name, profileName, resourceGroupName)` to `(resourceGroupName, profileName, name)`. Given they both have the same types for the method signature - this compiled and I initially assumed all was well - luckily our acceptance tests caught this.

Is there anything we can do about documenting that kind of painful breaking change a bit better next time around? Submitting 231 files in a single commit (in the case of 7.0.1) makes it pretty hard to review for breaking changes tbh :)

**Comment by mcardosos** [comment]
Reopening for further discussion

**Comment by marstr** [comment]
Hey @tombuildsstuff,

I think your point is really **really** valid. As a team, we're working on some proposals that should address this and some of the other broader related issues. Expect to see some news next week.

For now, I'm going to close this issue. If you feel there is further discussion that needs to happen specifically with the v7.0.1 changes, feel free to open it back up.
