### ISSUE TITLE
Reimplement parameter validation code

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#481]
Right now [validation](https://github.com/Azure/go-autorest/blob/master/autorest/validation/validation.go) code relies on strings and the `reflect` package to work. Because validation only works at runtime, it would be cool to change it so problems there can be found by Travis instead. It shouldn't introduce breaking changes to the SDK, but to [go-autorest](https://github.com/Azure/go-autorest); and rewrite some stuff in [AutoRest](https://github.com/Azure/autorest/tree/master/src/generator/AutoRest.Go).

**Comment by garimakhulbe** [comment]
what do you mean by 

> so problems there can be found by Travis instead

**Comment by mcardosos** [comment]
With `go build`

**Comment by tombuildsstuff** [comment]
@mcardosos great idea. Is there any reason why they couldn't be a split out into a separate re-usable 'validation' method so that validation errors could be picked up before trying to create an object?

**Comment by marstr** [comment]
I believe this issue should be in Azure/go-autorest, to compliment Azure/go-autorest#112. Alternatively, if we would like to solve it by change our codegen, then perhaps it would make more sense in [Azure/autorest](https://github.com/Azure/autorest).

**Comment by mcardosos** [comment]
If we fix this, the changes would be in AutoRest and in go-autorest, but the affected code would be in this repo.

**Comment by marstr** [comment]
Chatted offline with @mcardosos and moved to the autorest repository. Please see the conversation linked above for further discussion.
