### ISSUE TITLE
VirtualMachinesClient.ListAll does not return InstanceView object

### ISSUE THREAD

**Issue by dmitsh** [Azure/azure-sdk-for-go#4828]
### Bug Report

- import path of package in question:
`.../services/compute/mgmt/2018-10-01/compute`
- SDK version:
`master`

This is an issue that has been already discussed in #543

The problem is that `VirtualMachinesClient.ListAll()` does not populate `InstanceView` for the VMs.

The work-around is to call `VirtualMachinesClient.InstanceView()` for each VM in the list.
This is obviously not optimal and results with unnecessary overhead.

I'd like to inquiry whether there are plans to revisit this decision. Perhaps it would be possible to include an option to request InstanceView in `List` and `ListAll`, similar to `VirtualMachinesClient.Get( ... expand InstanceViewTypes)`.

**Comment by jhendrixMSFT** [comment]
@nitinbps are you the right person to answer this question?

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by jhendrixMSFT** [comment]
I spoke with the service team about this, there are plans to add a new "bulk list" API that will include the `InstanceView` data (sorry I can't be specific on the date).

**Comment by dmitsh** [comment]
Hello! Are there any updates for this issue?

**Comment by jhendrixMSFT** [comment]
The new API is in progress but unfortunately right now I can't be specific on the date when it will be available.

**Comment by Drewm3** [comment]
We are in the process of providing a way to get the status of a large number of VMs without needing to query the instance view for each one of them. Generally the status is the property which customers want to get in bulk most frequently. Will providing the status of these instances in bulk meet your needs or do you need to have more than the status property? 

There is a solution that will provide more properties through a slightly different mechanism, but please let me know which properties are needed in bulk first, and then I can provide the right details when they are available.

**Comment by dmitsh** [comment]
Hi Drew,
Thank you for replying.
We need to get the list of VMs with the following properties:
- VM ID
- VM name
- VM type
- location
- OS type
- tags
- scale set (if belongs to VMSS)
- power state
- private IP (if the VM is running)
- public IP (if exists)

Appreciate your response!

**Comment by dmitsh** [comment]
@Drewm3 any update on this? We are getting more and more requests for this feature, and it's unfortunate that people are walking away from Azure because of that.

**Comment by Drewm3** [comment]
The feature to expose the powerstate through the multi-VM APIs is being deployed now. This will be available to all customers in early June.

**Comment by Drewm3** [comment]
The ListAll API has been updated and deployed to all commercial cloud regions. Listing all VMs will now return the statuses in the instanceview for each VM to expose the PowerState and ProvisioningState for each VM. This is available using the version header of 2019-03-01 or later.

**Comment by dmitsh** [comment]
@Drewm3, I'm trying to use the new API, and I'm seeing the following issue.
If I set `statusOnly` to "true" in `ListAll`, then the returning compute.VirtualMachine object has `StorageProfile=nil`.
With `statusOnly` set to empty string, the returned `StorageProfile` point to a valid object.
I'm using `StorageProfile` to extract OS type: `osType := string(vm.StorageProfile.OsDisk.OsType)`

Is this a bug?

**Comment by Gadnief** [comment]
Issue seems to be still open... instanceview objecct is still nill

**Comment by jhendrixMSFT** [comment]
@tadelesh do we need to release an updated module?

**Comment by tadelesh** [comment]
> @tadelesh do we need to release an updated module?

@jhendrixMSFT It seems a service side behavior change. Our model has such property but service return nothing.

**Comment by Drewm3** [comment]
This is the expected behavior with statusOnly set to true. If you need to get both the storage profile and the status, then you will need to make two API calls. The general pattern for the VM GET API is that you can get either the "model view" or the "instance view", but not both in a single call. In the list all VMs API you can get the model view for all VMs or you can get the status for all VMs. We are unable to give the full instance view for all VMs because that is too much data for us to keep updated in the caching layer at all time (at least as implemented currently)

**Comment by dmitsh** [comment]
@Drewm3 , please reopen this issue.

Sending 2 API requests is not a solution. It causes throttling during Prometheus service discovery for clusters with multiple VMs.
Ideally we should be able to specify what information we want to get (we don't need ALL information, but a only certain fields)

**Comment by Drewm3** [comment]
Please open a feature request here: https://feedback.azure.com/d365community/forum/ec2f1827-be25-ec11-b6e6-000d3a4f0f1c
because this is a general feature request for the service as compared to a feature request that is specific to an individual SDK. Thanks.
