### ISSUE TITLE
InterfacesClient.Get() results with network.Interface containing nil for public IP 

### ISSUE THREAD

**Issue by dmitsh** [Azure/azure-sdk-for-go#4829]
### Bug Report

- import path of package in question:
.../services/compute/mgmt/2018-10-01/network

- What happened?
I'm trying to mitigate throttling of ARM requests.
I need to retrieve private and public IP for a NIC.
However, `InterfacesClient.Get()` returns `nil` for `ipConfigurations[].publicIpAddress.ipAddress`

The workaround is to make another API call `PublicIPAddressesClient.Get()`. However, given large number of VMs and periodicity of the checks (along with API calls for other resources), we are exceeding ARM limit of read API requests.

- What did you expect or want to happen?
I would expect that specifying "ipConfigurations" (or something similar) as the `expand` parameter in `InterfacesClient.Get()` would populate array of `InterfaceIPConfiguration` with `PublicIPAddress`

- How can we reproduce it?
Make a call to `azure-sdk-for-go/services/network/mgmt/2018-10-01/network/interfacesgroup.go:InterfacesClient.Get()` and examine the `Interface` structure.

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by dmitsh** [comment]
any updates on this issue?

**Comment by dmitsh** [comment]
Hello again, any updates on this issue?

**Comment by silencev** [comment]
I need this fix too

**Comment by ArcturusZhang** [comment]
Hi @dmitsh sorry for the delay. 
I tried with the [rest api](https://github.com/Azure/azure-rest-api-specs/blob/09aacbbf37cfe7d26cfe5b8c88c70dc4e59d7b98/specification/network/resource-manager/Microsoft.Network/stable/2019-07-01/networkInterface.json#L91).
Its response does not contains a field of `publicIpAddress`, therefore in SDK the value of `publicIpAddress` is `nil`.
This problem lies in the service side. I added a `Service Attention` tag to inform them. Please also feel free to submit an issue in the [rest api repo](https://github.com/Azure/azure-rest-api-specs).

**Comment by Drewm3** [comment]
I believe this is part of the networking APIs not the VM APIs. So I have routed to the appropriate networking team.

**Comment by ArcturusZhang** [comment]
> I believe this is part of the networking APIs not the VM APIs. So I have routed to the appropriate networking team.

Thanks!

**Comment by sfiguemsft** [comment]
@jhendrixMSFT can you look into this please?
seems to be related to this:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2018-10-01/network/publicipaddresses.go

**Comment by allegradomel** [comment]
@dmitsh, thanks for the feedback - I'm tracking the issue and we'll followup soon

**Comment by szymon3** [comment]
Hi, any progress on this?

**Comment by jaydrue** [comment]
Hi, do you have any progress on timeline on this?

**Comment by lirenhe** [comment]
@dmitsh, @szymon3 , @jaydrue,  this issue has been here for years and as this is a feature request for the virtual network service, could you post your question directly in https://docs.microsoft.com/en-us/answers/topics/azure-virtual-network.html

**Comment by xqi-aviatrix** [comment]
Any solution on this issue? Any fix would be helpful to me
