### ISSUE TITLE
Typo in Json Validation BlobServiceProperties

### ISSUE THREAD

**Issue by benjamin37** [Azure/azure-sdk-for-go#4842]
Hi,

in the client to set additional blob settings for an Azure Storage Account there is a Typo in the JSON validation which leads to the error that every request is invalid. See [blobservices.go](https://github.com/Azure/azure-sdk-for-go/blob/master/services/storage/mgmt/2019-04-01/storage/blobservices.go#L169-L173), it should be `parameters.BlobServicePropertiesProperties` instead of `parameters.BlobServiceProperties` in these 5 lines.

Kind regards
Benjamin

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v30.0.0
