### ISSUE TITLE
How to List all resources in a given resource group?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#491]
https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/resources#Client.List

So, I want to list all resources in a resource group. What do I pass for `filter` and `expand`? I don't care if anything is expanded and I don't want to filter? 

Also, this text: *"top is the number of results to return. If null is passed, returns all resource groups."* is **completely** confusing and misleading. I think it's safe to assume this still just returns a single page of results, not "*all*" resources. Additionally, why does the text say "returns all resource groups" ? Isn't this going to return all `resources` not all `resource groups`?

Also, why does it not take the `resourceGroup` name as a parameter?

Seems like this ought to be significantly easier?

**Comment by colemickens** [comment]
For `Client` type in the `resources/resources` package, I expected a method with signature:

    func (client Client) List(resourceGroupName string, filter *string, expand *string, top *int32) (result ResourceListResult, err error)

rather than:

    func (client Client) List(filter string, expand string, top *int32) (result ResourceListResult, err error)

Note that the two optional string args are now nullable, and the resourceGroupName is taken as an input. (Maybe it should be optional if there's really a way to list all resources in ALL resource groups in a subscription).

I have no doubt that these problems stem from the Swagger specs. If someone can confirm I'm willing to file the corresponding bug. Thanks.

**Comment by colemickens** [comment]
Aha! I wanted this: https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/groups.go#L505

I guess the other function I found really is a subscription wide List. Maybe these could cross-link each other for confused souls like myself. All other arm operations in this SDK are resourcegroup-based except these two `List`/`ListResources`.

**Comment by marstr** [comment]
Howdy @colemickens, I like the idea of adding hints to similar functions. I've opened [issue 862]( https://github.com/Azure/azure-rest-api-specs/issues/862) in the swagger repository to update the documentation to help folks in this situation.

**Comment by marstr** [comment]
@colemickens  If you think the issue that I opened up sufficiently captures your suggest, please close out this issue at your earliest convenience. Thanks for bringing this up!
