### ISSUE TITLE
arm/resources: can't create a tag

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#492]
Using the TagsClient.CreateOrUpdate method I get the following error:

```
resources.TagsClient#CreateOrUpdate: Failure responding to request: StatusCode=201 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go value of type string' JSON = '{"id":"/subscriptions/0000000/tagNames/peter-tag-test","tagName":"peter-tag-test","count":{"type":"Total","value":0},"values":[]}'
```

It appears the error is due to the value being returned by the API as an integer but it's expected to be a string:
```go
type TagCount struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}
```

The root cause appears to be an incorrect type in the Swagger spec.

**Comment by mcardosos** [comment]
Hello @pmcatominey ! Thanks for reporting this.
Already submitted a PR to the swaggers repo.

**Comment by marstr** [comment]
This issue appears to have been fixed by the issue and PR mentioned above. I'm going to close this issue for now, but if you feel it has not yet been resolved, please re-open.
