### ISSUE TITLE
large API surface from internal methods

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#493]
Each API call exposed usually calls 3 other methods:

* Preparer
* Sender
* Responder

Is it necessary for those methods to be exported by packages? It ends up creating a rather large API surface.

**Comment by marstr** [comment]
The short answer to your question is: yes, it is necessary. However, I know that's not really a satisfying answer. The whole story is that we're attempting to expose an easy way for folks to inject their own logic for each component of a request if desired. For instance, if you have custom Retry timing logic that you've implemented, you could use the stock Preparer and Responder, but swap in your own Sender.

Your point is not lost on us though, it certainly creates a large and slightly confusing API space while spinning up. We'll keep this in mind as we keep thinking of ways to improve the Azure SDK for Go.

I'm going to close this for now, but if you don't feel that I sufficiently answered your question, please open it back up.
