### ISSUE TITLE
Three ApplicationGatewayCipherSuite are missing.

### ISSUE THREAD

**Issue by kheiakiyama** [Azure/azure-sdk-for-go#4934]
### Bug Report

- import path of package in question, e.g. `.../services/network/mgmt/2018-12-01/network`
- SDK version e.g. `master`

- When I use [terraform-provider-azurerm](https://github.com/terraform-providers/terraform-provider-azurerm), I find it doesn't exists three ApplicationGatewayCipherSuite below.
  - `TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA` 
  - `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`
  - `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`   
- They are ["PosibleVaules"](https://raw.githubusercontent.com/Azure/azure-sdk-for-go/master/services/network/mgmt/2018-12-01/network/models.go), right?
- If we can use them, please add them.

**Comment by jhendrixMSFT** [comment]
Fix is coming, see https://github.com/Azure/azure-rest-api-specs/pull/6212/files

**Comment by kheiakiyama** [comment]
Appreciate it!

**Comment by lwilts** [comment]
Hi, that PR https://github.com/Azure/azure-rest-api-specs/pull/6212/files has been merged - looks like the cipher suites also need adding here?
https://github.com/Azure/azure-sdk-for-go/blob/784a56e5c68f892e337b82c8e1feb5fb6cd7a58a/services/network/mgmt/2018-04-01/network/models.go#L198

**Comment by jhendrixMSFT** [comment]
Should be released this week.

**Comment by SirWayne** [comment]
Any news?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay, this was released in v31.0.0 of the SDK.
