### ISSUE TITLE
Return the minimum TLS version with Redis Cache GET and LIST requests

### ISSUE THREAD

**Issue by drosseau** [Azure/azure-sdk-for-go#4968]
### Feature Request

It would be helpful for some automation if the `MinimumTLSVersion` field (seen [here](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/redis/mgmt/2018-03-01/redis#Properties)) was populated on GET and LIST requests.

I'm not sure where that change would need to be made since I don't see it mentioned in the documentation [here](https://docs.microsoft.com/en-us/rest/api/redis/redis/listbyresourcegroup#examples), but I do see it in the spec [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/redis/resource-manager/Microsoft.Cache/stable/2018-03-01/redis.json#L1413) although not in the [example](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/redis/resource-manager/Microsoft.Cache/stable/2018-03-01/examples/RedisCacheGet.json)

**Comment by jhendrixMSFT** [comment]
@TimLovellSmith is it possible to retrieve this info?

**Comment by TimLovellSmith** [comment]
@jhendrixMSFT It should be being included in the response, if you use api-version 2018-03-01 and *if* you configured the property on the cache. It is not included in the response when it is left unconfigured.

**Comment by drosseau** [comment]
Ah, so if it is the default value it will be left empty? I didn't think about that; I will check in a bit.

**Comment by jhendrixMSFT** [comment]
Hello @drosseau were you able to confirm this?

**Comment by MECHANDR** [comment]
@drosseau Planning to close this issue. Please let us know if you need any further clarifications.
