### ISSUE TITLE
[Challenge] Drop Issues Count < 10 by March 1st 2017

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#499]
Samer Will be buying lunch  (External Contributers Welcome). 

PLease note (Tickets to not Redmond will not be provided LOL)

**Comment by marstr** [comment]
^One addendum to this that we've agreed on at team meetings is that this doesn't include items that are on the Backlog. Only active issues.

**Comment by salameer** [comment]
5 days to Go

**Comment by mcardosos** [comment]
@salameer ! Today we dropped to 10 non backlog issues!
Of course we are not counting the ones we moved to https://github.com/Azure/azure-storage-go lolol!

**Comment by marstr** [comment]
We're well past this now. Closing!
