### ISSUE TITLE
Failed to delete App Insights API key

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/azure-sdk-for-go#4993]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`github.com/Azure/azure-sdk-for-go/services/appinsights/mgmt/2015-05-01/insights`

- SDK version e.g. `master`, `latest`, `18.1.0`
Tried either `25.1.0` or `30.0.0`.

- output of `go version`
`go version go1.9.2 linux/amd64`

**The App Insights client can create API Key but can't delete it.**

- What happened?

Got error: `insights.APIKeysClient#Delete: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: \"\" error: EOF"`

- What did you expect or want to happen?

Expect to delete the API Key.

- How can we reproduce it?

Example code:
```
        subID := <sub-id>
	resourceGroup := <rg-name>
	appInsightsName := <appinsights-name>
	apiKeyName := <api-key-name>
	appInsightsResourceID := fmt.Sprintf(
		"/subscriptions/%s/"+
			"resourceGroups/%s/"+
			"providers/Microsoft.Insights/components/%s",
		subID,
		resourceGroup,
		appInsightsName,
	)
	apiKeyProperties := appInsightsSDK.APIKeyRequest{
		Name: &apiKeyName,
		LinkedReadProperties: &[]string{
			appInsightsResourceID + "/api",
			appInsightsResourceID + "/agentconfig",
		},
		LinkedWriteProperties: &[]string{
			appInsightsResourceID + "/annotations",
		},
	}
	result, err := appInsightsAPIKeyClient.Create(
		context.Background(),
		resourceGroup,
		appInsightsName,
		apiKeyProperties,
	)
	if err != nil {
		return fmt.Errorf(
			"Error creating Application Insights API key %s: %+v",
			apiKeyName,
			err,
		)
	}
	if result.APIKey == nil {
		return fmt.Errorf(
			"Error creating Application Insights API key %s: got empty API key",
			apiKeyName,
		)
	}

        // I can reach here. And I can confirm in the Portal -- the API Key is right there. But the following deletion failed.

       if _, err := appInsightsAPIKeyClient.Delete(
		context.Background(),
		resourceGroup,
		appInsightsName,
		apiKeyName,
	); err != nil {
		return fmt.Errorf(
			"Error deleting Application Insights API key %s: %+v",
			apiKeyName,
			err,
		)
	}
```

- Anything we should know about your environment.

**Comment by jhendrixMSFT** [comment]
I looked into this, the value in `apiKeyName` is not the key ID which is why the API call fails.  The key ID is a GUID at the end of `result.ID`, so you have to do something like this.
```go
if _, err := appInsightsAPIKeyClient.Delete(
	context.Background(),
	resourceGroup,
	appInsightsName,
	(*result.ID)[strings.LastIndex(*result.ID, "/")+1:],
)
```
Not very intuitive from the docs unfortunately.  :(

**Comment by zhongyi-zhang** [comment]
Thanks a lot for the clarification! It works for me.
