### ISSUE TITLE
Support for Table/Queue service

### ISSUE THREAD

**Issue by dhanunjay** [Azure/azure-sdk-for-go#50]
Is there any plans for supporting table and queue services?

**Comment by ahmetalpbalkan** [comment]
@dhanunjay currently the storage part of the Go SDK is maintained on a per-need basis and we didn't really need it yet in any of our projects. If you're interested in implementing there must be plenty of common code/tests you can make use of. Any interest?

**Comment by dhanunjay** [comment]
I am interested. Please let me know some pointers on where i should look for common code.

**Comment by dstpierre** [comment]
I would also be interested in contributing since I also need the table and queue service. How can I help?

**Comment by ahmetalpbalkan** [comment]
You folks might want to look at the `storage/` package and start creating `table.go`, `table_test.go` and `queue.go`, `queue_test.go` by taking the blob storage implementation as a reference. Most of the authentication and HTTP request etc stuff is already there. All you need to do is creating the methods you need and preparing the request. If you can send small PRs, I would love to help our. Just send your pull requests to `dev` branch.

**Comment by dstpierre** [comment]
Great, I can start with the queue[_test].go since I need this first. Thanks

**Comment by ahmetalpbalkan** [comment]
@dstpierre Hey! Did you have any progress on that? If you created something we love to pick that up and add upon.

**Comment by dstpierre** [comment]
no did not have any time at all for this yet.

**Comment by igorgatis** [comment]
Interested.

**Comment by paulmey** [comment]
First set of queue API implementations in #164. Thanks @ahmetalpbalkan !

**Comment by gblmarquez** [comment]
+1

**Comment by gblmarquez** [comment]
Guys any plans for the Table Storage? I'm looking forwarding to migrating a REST API from .NET to Go.

**Comment by ahmetalpbalkan** [comment]
@gblmarquez there's a prototype of table storage in my fork (check branches) however I got stuck somewhere about request signing and gave up (just run go test storage). I'll revisit again to see if I can deliver.

**Comment by gblmarquez** [comment]
@ahmetalpbalkan that will be awesome. I check the branch it seems have many things ready.

**Comment by ahmetalpbalkan** [comment]
A proposal for Table Storage is at #217, please check out and leave comments if you are interested in using.

**Comment by vishrutshah** [comment]
Closing this one as basic support has been merged. Feel free to reopen if you find any issues. Thanks
