### ISSUE TITLE
New API method needed for Graph service

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-sdk-for-go#5041]
### Feature Request
Graph service is missing latest service principal endpoints.
Go sdk file: https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/serviceprincipals.go
API spec: https://github.com/Azure/azure-rest-api-specs/blob/e280b0a088439ed82a46e3b470d8da487de51037/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L1287

Didn't find the method that implements this API in the SDK.

**Comment by jhendrixMSFT** [comment]
Based on the linked swagger the API can be found here.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/applications.go#L363
Let me know if that works.

**Comment by feiyushi** [comment]
Thanks, @jhendrixMSFT ! I'll close the issue.
