### ISSUE TITLE
splitting application gateway into multiple modules

### ISSUE THREAD

**Issue by ranokarno** [Azure/azure-sdk-for-go#5051]
### Feature Request

Is it possible to separate `application gateway` SDK into multiple modules similar with loadbalancer.
```
applicationgatewaybackendpools.go
applicationgatewayfrontendipconfigurations.go
applicationgatewayroutingrules.go
applicationgatewayhttpsettings.go
applicationgatewaylistener.go
applicationgatewayhealthprobes.go
applicationgatewayrewrites.go
```

this will help us in updating or modifying existing `application gateway`

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by surajmb** [comment]
Can you post feature requests at https://feedback.azure.com/forums/217313-networking?category_id=134448 for tracking?

That's open to public voting and we usually update the status there.

**Comment by surajmb** [comment]
@ArcturusZhang , should we close this here?
