### ISSUE TITLE
devtestlabs: Using LabVirtualMachine.ComputeId requires knowledge of dynamic resource group

### ISSUE THREAD

**Issue by vosst** [Azure/azure-sdk-for-go#506]
I'm trying to dynamically create and destroy testing environments with `devtestlabs.LabOperationsClient`. The resulting `devtestlabs.LabVirtualMachine` contains the ComputeID of the `compute.VirtualMachine` instance. However, when trying to query properties (specifically, the public ip) of the vm assuming the resource group that the lab is contained within, the call fails due to an unknown resource in the resource group.

I could certainly split up the ComputeID string and extract the dynamic resource group myself. I think the SDK offering a convenience method doing that would be helpful and close the loop for this specific journey through the devtestlabs API.

**Comment by salameer** [comment]
Hey @vosst,  can you please provide some sample code on how your  using this API?

**Comment by vosst** [comment]
Hey @salameer, code looks like:
```
resourceGroup := "someGroup"

labsClient, _ := devtestlabs.NewLabOperationsClient(...)
labsClient.Authorizer = ...
vmClient, _ := compute.NewVirtualMachinesClient(...)
vmClient.Authorizer = ...
resClient, _ := resources.NewClient(...)
resClient.Authorizer = ...

labVm, _ := labsClient.CreateEnvironment(resourceGroup, ...)
res, _ := resClient.GetByID(*labVm.ComputeID)

vm, err := vmClient.Get(resourceGroup, *res.Name, ...)
if err != nil {
  // This code path is triggered as a VM with res.Name is
  // not known to resourceGroup. Instead the VM is associated
  // with a dynamic resource group created for the lab VM.
}
```
Hope that helps. Let me know if you want me to provide a distilled main that actually works.

**Comment by vosst** [comment]
Ping :)

**Comment by marstr** [comment]
Howdy @vosst, this is a really interesting point. I think you are absolutely correct that this should be included in the `labVm` environment that is returned from `labsClient.CreateEnvironment(...)`. I suspect that this means that the Swagger and maybe the service will need to be updated. If this does turn out to be the case, I'll create a corresponding issue in the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repository. Regardless, I don't think the change will be made here, so I'll close out this issue.

Thanks for bringing this to our attention!
