### ISSUE TITLE
devtestlabs: Resolving values in formulas

### ISSUE THREAD

**Issue by vosst** [Azure/azure-sdk-for-go#508]
When using formulas in devtestlabs to create environments, it is unclear how to resolve placeholder values (like LabVirtualNetworkID or Password) to actual values. For example, when passing in the `LabVirtualNetworkID` to `VirtualNetworkOperationsClient.GetResource(...)` an error is produced, as the ID is appended as is to the query.

**Comment by marstr** [comment]
Howdy @vosst, could you show me a snippet/gist of how you're instantiating the LabVirtualNetworkID?

**Comment by vosst** [comment]
Hey @marstr, thanks for getting back to my question. Please see https://github.com/snapcore/spread/pull/18/files, azureProvider.Allocate for the respective code. Right now, I pass in the network name via an env var as I fail to query it correctly.

**Comment by vosst** [comment]
Ping :)

**Comment by marstr** [comment]
Sorry for the delay, and thank you for providing that snippet. It definitely aided this conversation! I'm still confused about your question, so please forgive me if I miss the mark here.

In general, the pattern that our APIs will follow is fetching a Resource given a handful of names and its respective `Get` method. Like you mentioned, for virtual networks in devtestlabs, the method that one uses is to initially grab the resource is: `VirtualNetworkOperationsClient.GetResource(...)` The full header of which is:
```
func (client VirtualNetworkOperationsClient) GetResource(resourceGroupName string, labName string, name string) (result VirtualNetwork, err error) 
```
_Code from [arm/devtestlabs/virtualnetworkoperations.go](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/devtestlabs/virtualnetworkoperations.go)_

As you can see above, it takes a few names, but never IDs as `LabVirtualNetworkID` which you mentioned in your comment. (Perhaps this explains the error message you are encountering?) Once one has a devtestlabs.VirutalNetwork, you can mutate it and use it as the parameter in a `VirtualNetworkOperationsClient.CreateOrUpdateResource(...)` call.

Looking at your sample code, it looked like one of the particular pain points was rehydrating the name of the lab you are targeting. Unfortunately, there isn't really much of an answer there as we leave it to the consumer to create their own naming conventions and manage their own resources. However, if you're interested in a more programmatic approach, you could take a look at the `LabOperationsClient.ListByResourceGroup(...)` method to see if it could be of use.

As I said at the beginning, feel free to tell me I didn't answer your question.

**Comment by marstr** [comment]
I'm going to close this issue, if you feel this is unresolved, feel free to open it back up.
