### ISSUE TITLE
Storage package doesn't automatically retry.

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#509]
With all packages auto-generated from Swagger, the [go-autorest](https://github.com/Azure/go-autorest) library is used and automatically retries requests that fail in transient ways. However, being manually maintained for now, the storage package doesn't automatically pick up this value.

The Storage package should be refactored to use  [go-autorest](https://github.com/Azure/go-autorest)  where possible to encourage a consistent and easy to use API.

**Comment by marstr** [comment]
In order to fix this, this plan is to refactor the storage api to use the go-autorest library instead of having its own mechanisms for executing and handling requests. The main advantages of this rewrite would be consistency between planes, and adoption of functionality like that mentioned above and request timeout.

**Comment by kpfaulkner** [comment]
So does this mean that storage as we know it will be gone and completely replaced by a go-autorest generated version? 

Admittedly I'm not completely familiar with what exactly go-autorest generates (whether its 99% completely usable code or just provides a decent framework to begin with).

If it generates a fairly complete client library, should we be holding off on working on any storage related bugs? I was planning on picking up a couple but am unsure if it would be a wasted effort or not?

Advice?

**Comment by marstr** [comment]
Hey Ken, not to worry, we're not to the point of auto-generating the Storage package yet. Mostly, we'd just like it to be take advantage of some of the existing helper methods. Feel free to take on some bugs. :)

**Comment by marstr** [comment]
For further conversation around this topic, please see the issue linked above.
