### ISSUE TITLE
Change InterfaceIPConfiguration by name

### ISSUE THREAD

**Issue by dbaroncelli** [Azure/azure-sdk-for-go#5091]
### Feature Request

In case of multiple InterfaceIPConfigurations of a NIC, It would be very useful to amend a single InterfaceIPConfiguration, by name, without resubmitting the whole slice of InterfaceIPConfigurations:

Currently, it seems you need to resubmit the whole slice every time:
https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/network/nic.go

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by allegradomel** [comment]
@dbaroncelli, thanks for this feedback! We'll look into this as a possible option.

**Comment by lirenhe** [comment]
@dbaroncelli,  from the latest swagger, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2021-03-01/networkInterface.json, only the list operation is supported.  As the SDK is generated from Swagger, we are unable to provide 'amend' if this is not supported by service.   You could create an issue in https://github.com/Azure/azure-rest-api-specs/  for network
