### ISSUE TITLE
How to determine the price of Virtual Machine

### ISSUE THREAD

**Issue by apratina** [Azure/azure-sdk-for-go#5099]
1) I came across one of the [endpoint](https://azure.microsoft.com/api/v2/pricing/virtual-machines-software/calculator/) which provides the price of virtual machine. What is the equivalent approach in azure go sdk to determine the price of VMs?

2) In this [endpoint](https://azure.microsoft.com/api/v2/pricing/virtual-machines-software/calculator/), there is something called `baseOfferSlug` that will help me determine the exact price of the VM being used. How can I determine `baseOfferSlug` value for any running VM, through go azure sdk? (see attached screenshot)

<img width="647" alt="Screen Shot 2019-06-24 at 10 27 18 PM" src="https://user-images.githubusercontent.com/4571461/60071542-49ad4680-96cf-11e9-8c74-a3987a785bfe.png">

**Comment by loarabia** [comment]
Hey thanks for reporting the issue. I've reached out to the team to try to get it to the right engineers.

**Comment by apratina** [comment]
@loarabia : Any update on this ?

**Comment by loarabia** [comment]
Hi @apratina , I've reached out to folks and I had a brief chat with @mjconnection and think he might have the right next steps or know the next set of people to pull into the conversation here.

**Comment by mjconnection** [comment]
Hello @apratina, I am working to identify the correct resource to help answer your questions.

**Comment by Drewm3** [comment]
Hi @apratina, the following documentation provides details on the Azure Rate Card API (and other billing APIs) which can be used to get pricing details for many subscription types. If your subscription is using an "Enterprise Agreement", then I do not believe there is an existing API provided to get pricing details. 

Rate Card APIs: [https://docs.microsoft.com/en-us/azure/billing/billing-usage-rate-card-overview](url)
