### ISSUE TITLE
Entity Group Transactions with Table Storage

### ISSUE THREAD

**Issue by lienmeat** [Azure/azure-sdk-for-go#510]
I don't see how to do entity group transactions on table storage currently.  Is this missing functionality, or how would I go about this?

For instance, if I wanted to insert entities, and they all had the same partition key, instead of using func (*TableServiceClient) InsertEntity which inserts an entity at a time, it should be possible to create a batch of entity insert operations and transact them.  If that is currently supported, I'm missing how I might do that.

**Comment by marstr** [comment]
For further conversation around this issue, please see the issue linked above.
