### ISSUE TITLE
Investigate adding pre/post API call hooks in storage

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#513]
The management plane APIs (auto-generated stuff) have hooks for pre/post API calls which is lacking in the dataplane APIs.  Investigate adding such hooks.

**Comment by marstr** [comment]
For further conversation on this topic, please see the issue linked above.

**Comment by jhendrixMSFT** [comment]
This will be handled in the request policy pipeline, we won't be making this change to the existing storage package.
