### ISSUE TITLE
Cosmos DB CheckNameExists failing with 500

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#5157]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
"github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb"
- SDK version e.g. `master`, `latest`, `18.1.0`
github.com/Azure/azure-sdk-for-go v30.0.0+incompatible
- output of `go version`
go version go1.12.6 darwin/amd64

With no code changes all our cosmos DB tests started failing sometime in the last week with:
``
------- Stdout: -------
=== RUN   TestAccAzureRMCosmosDBAccount_strong
=== PAUSE TestAccAzureRMCosmosDBAccount_strong
=== CONT  TestAccAzureRMCosmosDBAccount_strong
--- FAIL: TestAccAzureRMCosmosDBAccount_strong (516.37s)
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Error checking if CosmosDB Account "acctest-190628022825260962" already exists (Resource Group "acctestRG-190628022825260962"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
        
          on /opt/teamcity-agent/temp/buildTmp/tf-test027250150/main.tf line 7:
          (source code not available)
    
```

<!--
Thanks!
-->

**Comment by jhendrixMSFT** [comment]
Thanks I can repro this, it also takes a really long time before the 500 is returned.

**Comment by jhendrixMSFT** [comment]
Known issue, RP is working on a fix.  Will update when I have more info.

**Comment by katbyte** [comment]
thanks for the update @jhendrixMSFT, we are going to release 1.31 today with an unideal fix (ignore 500s) but it'll unblock users

**Comment by jhendrixMSFT** [comment]
@katbyte RP has fixed this and I confirmed it's working now.  Please let me know if you still have issues.
