### ISSUE TITLE
Generation logic should dynamically pull Swagger specs (or they should be vendored into this repo)

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#516]
Example:

The KeyVault swagger was updated to include the data plane, but newest versions of the Go SDK don't have the new functionality.

Looking at this: https://github.com/Azure/azure-sdk-for-go/blob/master/Gododir/gen.go it seems that the Swaggers are downloaded manually.

 It seems that someone pulled the Swagger spec for KeyVault down, but missed the fact that it's since been updated. Since this is error prone, instead, the script should download the swagger specs ahead of calling Autorest.

**Comment by colemickens** [comment]
cc: @mbearup

**Comment by marstr** [comment]
Totally agreed. We're actively looking at ways to improve this story. Ideally, we wouldn't have a manual monthly release, but rather react to changes in swaggers with automatic releases. There is a similar thread that is open here: #476.

For now, I believe this is a duplicate suggestion to the issue above. If you agree, please close out the issue.

**Comment by colemickens** [comment]
makes sense. thanks!
