### ISSUE TITLE
Parameters cannot be set in blueprint properties

### ISSUE THREAD

**Issue by andysworkshop** [Azure/azure-sdk-for-go#5161]
### Bug Report

In the 2018-11-01-preview of the blueprint API there are a number of *Properties structures that contain a parameters map. [Here's one](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go#L2353). The `Parameters` are declared as:

```
Parameters map[string]*ParameterValueBase `json:"parameters"`
```

`ParameterValueBase` is declared as:

```
type ParameterValueBase struct {
	// Description - Optional property. Establishes ParameterValueBase as a BaseClass.
	Description *string `json:"description,omitempty"`
}
```
There is no way to set or receive the type that we actually need (`ParameterValue`):
```
type ParameterValue struct {
	// Value - Actual value.
	Value interface{} `json:"value,omitempty"`
	// Description - Optional property. Establishes ParameterValueBase as a BaseClass.
	Description *string `json:"description,omitempty"`
}
```
I have a feeling that the intention would have been to use interfaces to simulate polymorphism in the same way that it has been done with the [`BasicArtifact`](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go#L159) type.

**Comment by loarabia** [comment]
@andysworkshop thanks for reporting this. I've tagged what I think are the right teams so they can take a look.

**Comment by ArcturusZhang** [comment]
Hi @andysworkshop , according to the swagger [definition](https://github.com/Azure/azure-rest-api-specs/blob/ae48ce6edc05501e9b78d93d6e36862599cdedb5/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintAssignment.json#L431), the `ParameterValue` is a subclass of `ParameterValueBase`, and actually the map stores `ParameterValue`. You can try cast the value from this map to `ParameterValue` type, then you can get the actual values.
Feel free to let us know if this does not work.
