### ISSUE TITLE
Type error in compute models.go VirtualMachineScaleSetVMProperties

### ISSUE THREAD

**Issue by s27y** [Azure/azure-sdk-for-go#5179]
### Bug Report

When i make a List request using compute.VirtualMachineScaleSetVMsClient. i got the following error.

```
 compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field VirtualMachineScaleSetVMListResult.value of type string' JSON = '{
  "value": [
    {
      "instanceId": "0",
      "properties": {
        "latestModelApplied": false,
        "instanceView": {
          "statuses": [
            {
              "code": "PowerState/running",
              "level": "Info",
              "displayStatus": "VM running"
            }
          ]
        },
        "hardwareProfile": {},
        "provisioningState": 0
      },
      "id": "/subscriptions/6e00d5**3/resourceGroups/dev-msdn-***win-b/providers/Microsoft.Compute/virtualMachineScaleSets/d2****/virtualMachines/0"
    },
```

VirtualMachineScaleSetVMProperties.**ProvisioningState** is returned as an integer from Azure API, but it is declared as a string in models.go

Link to the line:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2018-10-01/compute/models.go#L10028

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by maggiepint** [comment]
Thanks for reporting this - we have routed to an appropriate team for follow up.

**Comment by ArcturusZhang** [comment]
> ### Bug Report
> When i make a List request using compute.VirtualMachineScaleSetVMsClient. i got the following error.
> 
> ```
>  compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field VirtualMachineScaleSetVMListResult.value of type string' JSON = '{
>   "value": [
>     {
>       "instanceId": "0",
>       "properties": {
>         "latestModelApplied": false,
>         "instanceView": {
>           "statuses": [
>             {
>               "code": "PowerState/running",
>               "level": "Info",
>               "displayStatus": "VM running"
>             }
>           ]
>         },
>         "hardwareProfile": {},
>         "provisioningState": 0
>       },
>       "id": "/subscriptions/6e00d5**3/resourceGroups/dev-msdn-***win-b/providers/Microsoft.Compute/virtualMachineScaleSets/d2****/virtualMachines/0"
>     },
> ```
> 
> VirtualMachineScaleSetVMProperties.**ProvisioningState** is returned as an integer from Azure API, but it is declared as a string in models.go
> 
> Link to the line:
> https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2018-10-01/compute/models.go#L10028
> 
> * import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
> * SDK version e.g. `master`, `latest`, `18.1.0`
>   
>   * Specify the exact commit if possible; one way to get this is the REVISION
>     column output by `dep status "github.com/Azure/azure-sdk-for-go`.
> * output of `go version`
> 
> * What happened?
> * What did you expect or want to happen?
> * How can we reproduce it?
> * Anything we should know about your environment.

This is very strange, I checked the corresponding [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json), all the ProvisioningState field has the type of string. This bug (if still exists) should be caused on the service side.

**Comment by Drewm3** [comment]
I am working to get the right dev owner engaged to this issue to provide a fix.

**Comment by ArcturusZhang** [comment]
> I am working to get the right dev owner engaged to this issue to provide a fix.

Thanks a lot!

**Comment by wangjun-jwa** [comment]
@s27y , does it always repro on your VMSS or it happened once. Can you provide the timestamp when you hit the issue?

**Comment by jakepearson** [comment]
I am also able to reproduce this issue consistently. Is there an ETA on a fix for the problem?

**Comment by wangjun-jwa** [comment]
@ArcturusZhang , please close the issue.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang , please close the issue.

Thanks a lot!
