### ISSUE TITLE
Operations on Account missing

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#518]
The ones in [here](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/operations-on-the-account--table-service-)

**Comment by mcardosos** [comment]
Also the ones in [file service](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/operations-on-the-account--file-service-)

**Comment by mcardosos** [comment]
Ok, all services are missing operations.

**Comment by marstr** [comment]
For further conversation around this topic, please see the issue linked above.

**Comment by jhendrixMSFT** [comment]
These will be added when we create all the swaggers for dataplane, we will not add it to the existing storage package.
