### ISSUE TITLE
Container registry network access profile VNET rule property is silently ignored on create/update

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#5181]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`"github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2018-09-01/containerregistry"`
- SDK version e.g. `master`, `latest`, `18.1.0`
```
	github.com/Azure/azure-sdk-for-go v30.0.0+incompatible
	github.com/Azure/go-autorest v11.7.0+incompatible
```
- output of `go version`
`go version go1.12.6 darwin/amd64`

- What happened?
When creating or updating a Container Register with a `NetworkRuleSet` with `VirtualNetworkRules` the property is silently ignored. Values in the `IPRules` property however are recognized and applied. I can see it being sent in the request, however its not returned.
Request captured by charles:
```
{
	"location": "westeurope",
	"properties": {
		"adminUserEnabled": false,
		"networkRuleSet": {
			"defaultAction": "Deny",
			"virtualNetworkRules": [{
				"action": "Allow",
				"id": "/subscriptions/1a6093a6-0000-0000-0000-ef71f76f2c02/resourceGroups/testAccRg-190702134607890682/providers/Microsoft.Network/virtualNetworks/testAccVnet-190702134607890682/subnets/testAccSubnet-190702134607890682"
			}],
			"ipRules": [{
				"action": "Allow",
				"value": "8.8.8.8/32"
			}]
		}
	},
	"sku": {
		"name": "Premium",
		"tier": "Premium"
	},
	"tags": {}
}
```
and the response:
```
{
	"sku": {
		"name": "Premium",
		"tier": "Premium"
	},
	"type": "Microsoft.ContainerRegistry/registries",
	"id": "/subscriptions/1a4032a6-0000-0000-0000-ef11f76f2c02/resourceGroups/testAccRg-190702134607890682/providers/Microsoft.ContainerRegistry/registries/testAccCr190702134607890682",
	"name": "testAccCr190702134607890682",
	"location": "westeurope",
	"tags": {},
	"properties": {
		"loginServer": "testacccr190702134607890682.azurecr.io",
		"creationDate": "2019-07-02T20:46:37.2989541Z",
		"provisioningState": "Succeeded",
		"adminUserEnabled": false,
		"networkRuleSet": {
			"defaultAction": "Deny",
			"virtualNetworkRules": [],
			"ipRules": [{
				"action": "Allow",
				"value": "8.8.8.8"
			}]
		}
	}
}
```

**Comment by maggiepint** [comment]
Thanks for letting us know about this issue. We have routed to the appropriate team for follow up.

**Comment by sajayantony** [comment]
Please assign this to @adewaleo

**Comment by adewaleo** [comment]
Can this be assigned to me here?

**Comment by adewaleo** [comment]
@katbyte, I’m looking into this issue. My guess is it’s a service side issue. But will confirm and provide updates and hopefully a work around. 

I do have a few questions to help with this investigation.

What method / operation did you call. Create or update? If you tried create, please try using update. 

create uses the POST method on the ACR REST API whilst update uses PATCH. It could be that the patch method has the correct validation / implementation for network rules whilst post doesn’t. I have to confirm. 

are the subject and registry in the same sub? This shouldn’t be the cause of the issue, but I’m curious.

Finally, did you follow the flow / prior steps in the network rules doc? I’m assuming you have but thought it won’t hurt to add this. 
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-vnet

**Comment by katbyte** [comment]
@adewaleo, I just fired up our tests and it seems to work now! looks like something was fixed on your side 🙂 Thank you so much for looking into it

**Comment by adewaleo** [comment]
Thanks @katbyte happy this was resolved! 😄 thanks for your patience!
