### ISSUE TITLE
UpdatePasswordCredentials no longer works

### ISSUE THREAD

**Issue by arbourd** [Azure/azure-sdk-for-go#5222]
### Bug Report

- Import path: `services/graphrbac/1.6/graphrbac`
- Function: `UpdatePasswordCredentials`
- SDK version: `v29.0.0`, `v31.1.0`

#### What happened?

`UpdatePasswordCredentials` successfully creates (or updates) a credential attached to a service principal and the API can retrieve it after creating it. This credential does not appear to work with AKS, nor does it appear in the UI after creating it.

#### What did you expect or want to happen?

The credential should appear in the UI or manifest of the service principal after creating the object.

#### How can we reproduce it?

Create a mutate a service principal's credentials with `UpdatePasswordCredentials`, and attempt to use the service principal (which will result in an error that the credential is not working) or check the Azure UI (which will exclude the new / updated credential).

#### Possible Cause.

I believe this might be caused by the migration from Azure AD Graph 1.6 to Microsoft Graph 1.0. Credentials created in the UI have a different schema than the ones created by `UpdatePasswordCredentials`.

#### Anything we should know about your environment.

This issue was first reported in the Azure AD Terraform Provider: https://github.com/terraform-providers/terraform-provider-azuread/issues/66

**Comment by kurtzeborn** [comment]
Thanks for reporting this issue!  We'll get this routed to the correct team for further investigation.

**Comment by ashemedai** [comment]
Hi @kurtzeborn, has there been any update on this front that you can share?

**Comment by gabrielmcf** [comment]
Any news about this issue? We are having the same problem trying to create a secret to use with HPA in AKS.

**Comment by cloudpea** [comment]
Is there any updates or workarounds for this? This is currently preventing us from using Terraform to automate our AKS cluster deployments as we can't create a client secret for the SPN.

**Comment by gvilarino** [comment]
Thanks please this is super important!

**Comment by lirenhe** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
azure-deprecation/dashboard#60
