### ISSUE TITLE
Create storage client using AAD token

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-sdk-for-go#5226]
### Feature Request

Azure storage now supports [authentication using AAD token](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad). I couldn't find a method that allows creating a client from an existing token - is this supported by the SDK?

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by mbrancato** [comment]
Any update on this @praries880 or there is work ongoing?

**Comment by gitirabassi** [comment]
Updates?

**Comment by Petermarcu** [comment]
@schaabs do you know the answer?

**Comment by zezha-msft** [comment]
Hi @omerlh, to confirm, are you using azblob?

**Comment by RickWinter** [comment]
Track2 supports this scenario.  This will NOT be backported to track1

**Comment by zezha-msft** [comment]
@RickWinter no track1 already supports AAD, I think @omerlh was asking about the legacy package here: https://github.com/Azure/azure-sdk-for-go/tree/main/storage. 

Track 1 is here: https://github.com/azure/azure-storage-blob-go
