### ISSUE TITLE
Add support for RateCard API for getting cost information from Azure

### ISSUE THREAD

**Issue by hopoffbaby** [Azure/azure-sdk-for-go#523]
Hi,

Would it be possible to add support for the following in order to be able to query rate information from Azure?

https://msdn.microsoft.com/en-us/library/azure/mt219004

Thanks,
hopoffbaby

**Comment by kirthik** [comment]
@hopoffbaby - Thank you for contacting us. We will work with Billing team to create swagger for their APIs. Once we have a swagger, we should be able to add support for the same in Go SDK. I will respond here once we have concrete plan and timeline.

**Comment by salameer** [comment]
Can you kindly open an issue on the API specs repo instead

**Comment by marstr** [comment]
This issue has been cloned and can be found here: Azure/azure-rest-api-specs#916

I'll close this copy of the issue. If folks feel there is additional Go specific conversation to be had, feel free to re-open this issue.

**Comment by marstr** [comment]
Many thanks to @hopoffbaby for creating the new issue in the azure-rest-api-specs repository.
