### ISSUE TITLE
Service Bus Namespace zone redundant parameter missing

### ISSUE THREAD

**Issue by steve-hawkins** [Azure/azure-sdk-for-go#5235]
### Feature Request

This appears to be part of the [2018-01-01-preview REST API specs](https://github.com/Azure/azure-rest-api-specs/blob/80bd59aa5166da3e4036765e0d88462a8027c24b/specification/servicebus/resource-manager/Microsoft.ServiceBus/preview/2018-01-01-preview/servicebus-preview.json#L997-L1000)

**Comment by kurtzeborn** [comment]
Thanks for opening this issue!  I've routed it to an appropriate team that I think will be able to investigate this further.

**Comment by jfggdl** [comment]
steve-hawkins, We have added this feature to our backlog and we will communicate later when this should be ready. Thanks for creating this issue.

**Comment by ArcturusZhang** [comment]
I submit a [PR](https://github.com/Azure/azure-rest-api-specs/pull/6931) that could resolve this issue
