### ISSUE TITLE
Not all storage clients are named in the same way

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#527]
Super nit

```
BlobStorageClient
```
vs 
```
QueueServiceClient
TableServiceClient
FileServiceClient
```

**Comment by marstr** [comment]
I'm not sure that this warrants a breaking change. It seems pretty mundane to me. What are your thoughts, @jhendrixMSFT?

**Comment by jhendrixMSFT** [comment]
I think there is some value in uniformity, however I wouldn't introduce such a breaking change just for that sake.  However since we'll be refactoring the blob storage APIs anyways (and introducing breaking changes) we can fix the client name at that time.

**Comment by marstr** [comment]
Sweet, what's the milestone we're going to be using there? Is that scheduled for 9.0?

**Comment by marstr** [comment]
(Tagging the PR associated with this conversation) #532

**Comment by marstr** [comment]
For further conversation on this topic, please see this issue linked above.

**Comment by marstr** [comment]
I don't think this is worth fixing. I'm going to close it out.
