### ISSUE TITLE
endpoint returns 500 instead of 400 with missing Content-Type header

### ISSUE THREAD

**Issue by atecce** [Azure/azure-sdk-for-go#5277]
### Service Package Request

hai! I'm trying to programmatically register devices in IoT Hub with [this http endpoint](https://docs.microsoft.com/en-us/rest/api/iothub/service/createorupdatedevice) and am getting `500`s (which I think should _probably_ be 400's?) for the following request body

```json
{
  "deviceId": "testing",
  "generationId": "",
  "etag": "",
  "connectionState": "Disconnected",
  "status": "enabled",
  "statusReason": "",
  "connectionStateUpdatedTime": "0001-01-01T00:00:00",
  "statusUpdatedTime": "0001-01-01T00:00:00",
  "lastActivityName": "0001-01-01T00:00:00-00:00",
  "cloudToDeviceMessageCount": 0,
  "Authentication": {
    "symmetricKey": {
      "primaryKey": "b/j8HZmwGSzf3a7EV+eSRW22PMiI5ZI3oqICwbfqB5c=",
      "secondaryKey": "IGDKnpmZJIAvQPE3961Sy7po+afyKYpECbsFq/H8R9w="
    },
    "x509Thumbprint": {
      "primaryThumbprint": null,
      "secondaryThumbprint": null
    },
    "type": "sas"
  }
}
```

which will return something like this:

```json
{
  "Message": "ErrorCode:ServerError;InternalServerError",
  "ExceptionMessage": "Tracking ID:2ee91d1a3d9b4671b6a29e48fa98f210-G:10-TimeStamp:07/17/2019 17:59:53"
}
```

is there already API somewhere in here which abstracts over this for me? is there something I'm missing in the request body?

**Comment by kurtzeborn** [comment]
Thanks for opening this issue!  I'm routing it to the correct team so they can take a deeper look.

**Comment by atecce** [comment]
tyvm! :D

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jlian** [comment]
Please label this as a question

**Comment by rezasherafat** [comment]
@atecce, can you make sure you have `Content-Type: application/json` in your request header.

**Comment by atecce** [comment]
@rezasherafat ohhhhhhhhhh. heh. I suppose I got a bit too minimal. tyvm! :D

I guess that changes the nature of this ticket to a much lower priority one about status codes?

**Comment by atecce** [comment]
closing since this is on a codebase of client libraries anyways
