### ISSUE TITLE
Documenting plans for 9.0

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#529]
This will invovle posting the upcoming changes in 9.0 Beta release in March

**Comment by marstr** [comment]
Howdy Folks, in order to both allow for high-level discussion and comment, and very granular detail I opened PR #569. Please navigate there for conversation of upcoming changes.

I'll leave this issue open until V9 is released to increase visibility.

**Comment by salameer** [comment]
Completed, Closing
