### ISSUE TITLE
File Storage CopyFile implementation

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#535]
Azure File storage doesn't currently implement CopyFile ( https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/copy-file )

I've implemented this and will be submitting a PR soon. I have a question about the preferred approach for timeout parameters.

The timeout parameter for most of the functionality in file.go is missing. I'm assuming this is by choice and will be implemented later once people are interested in it. I just wanted to check if that was a conscious decision or was just missed?

If I add it in for CopyFile (which uses the createResource function like many others)  then it will impact said others. Would it be preferable that I just skip timeout similar to the other functions, or go through and add this?  I merely bring this up since I'm aware of some discussion about stabilising the API and didn't want to go through making non-critical API signature changes.

Thoughts?

/cc @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
I wouldn't add it as a stand-alone parameter, instead I'd make it part of some type that is passed to the copy operation (take a look at the C# implementation).

**Comment by kpfaulkner** [comment]
Thanks, will check that out.

**Comment by mcardosos** [comment]
Hello @kpfaulkner :D
If you can do this in February we can include it in the next release.
Please make sure to submit the PR against the dev branch.
Thanks for your enthusiasm!

**Comment by kpfaulkner** [comment]
The copying side of things is already working. Just need to add in the FileRequestOptions idea from @jhendrixMSFT . Hopefully sort it out on the weekend.

**Comment by salameer** [comment]
Closing the PR is merged that Captain @kpfaulkner for the contribution!!!
