### ISSUE TITLE
MarshalJSON for EvenData return nil

### ISSUE THREAD

**Issue by mguglani** [Azure/azure-sdk-for-go#5379]
### Bug Report
- What happened?
I am using Rest API to get Activity Logs(github.com/Azure/azure-sdk-for-go/profiles/preview/preview/monitor/mgmt/insights) between two Timestamps for a given correlation Id. I successfully get the data. Here is the call sequence:

activityClient = insights.NewActivityLogsClient(subscriptionId)
activityClient.BaseClient.Authorizer = authorizer
// get all activitylogs for given correlation Id happened during ten minutes since the given event.
filter := fmt.Sprintf("eventTimestamp ge '%s' and eventTimestamp le '%s' and correlationid eq '%s'", timeStamp, endTime.Add(time.Duration(ActivityLogQueryDelta)).Format(time.RFC3339), unparsedEvent)
result, err := activityClient.List(ctx, filter, "")

I successfully get the activityLogs and we have a requirement to get eventData marshaled in to JSON.
call to json.Marshal(eventData) returns nil as all the fields in eventData are marked Read-Only and marshalJSON method defined in models.go returns nil in this case.

- What did you expect or want to happen?
I am looking for a way to be able to Marshal this data as JSON. Be it with updated marshalJSON method for eventData or if there is an alternate API to directly get the JSON output.

- How can we reproduce it?
Use the Rest API available for Azure SDK for Go (see path and code above) to get the Azure Activity Logs and use json.Marshal on EventData. 

- Anything we should know about your environment.

**Comment by kurtzeborn** [comment]
Thanks for opening this issue to ask the question.  I'm routing this to an appropriate team for further follow up and hopefully we'll get you an answer to this.

**Comment by mguglani** [comment]
I decided to use the auto rest API as I only needed the json output. I no longer need help on this issue.

**Comment by praveenvaltix** [comment]
reopened as https://github.com/Azure/azure-sdk-for-go/issues/8224
