### ISSUE TITLE
managed disk support

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-go#538]
Hi guys,

couldn't find any reference to `managed disks` in the code or any PRs.
Is this in your backlog already? 
This is really needed to get `packer` to work with managed disks.

If nobody's working on it, then I will just have to learn go well enough to do it myself or just whip something up in PowerShell :)

**Comment by colemickens** [comment]
I think we want this for Kubernetes as well. I think for now @khenidak wrote the calls manually.

**Comment by colemickens** [comment]
Relevant: new Disk swagger spec, and updated Compute swagger spec: https://github.com/Azure/azure-rest-api-specs/issues/924

**Comment by davidobrien1985** [comment]
Cool, however, I think that's a bit over my head... any takers? :)

**Comment by marstr** [comment]
Howdy folks, we actually already generated this for the v8.0.0-beta release. You can take a look at what we generated here:
https://github.com/Azure/azure-sdk-for-go/tree/master/arm/disk

**Comment by marstr** [comment]
I'm going to close this issue for now, but feel free to reopen this issue if your needs aren't addressed.
