### ISSUE TITLE
Latest release doesn't adhere to naming convention

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#539]
Current release:

`8.0.1-beta`

last release

`v8.0.0-beta`

Please can this be made consistent?

**Comment by marstr** [comment]
Shoot, this is sloppy stuff. I don't want to break anybody who added a reference to "8.0.1-beta" (even though tools like glide probably make this largely irrelevant.) I can add a second tag "v8.0.1-beta" which should help ease the situation.

**Comment by marstr** [comment]
Alright, even better, I was able to update the Release Name while keeping both tags.

**Comment by stack72** [comment]
Thanks so much :)
