### ISSUE TITLE
Support for client-side blob encryption

### ISSUE THREAD

**Issue by invidian** [Azure/azure-sdk-for-go#5391]
### Feature Request

It seems that Blob Encryption is currently only supported in [.Net](https://azure.microsoft.com/en-in/resources/samples/storage-dotnet-client-side-encryption/). It would be great if Go SDK could support is as well, so people can encrypt their data client-side.

(If I missed, that it IS supported, could one point me to some examples/source?)

**Comment by amishra-dev** [comment]
Thank you for this feature request. I have added it to our backlog and we will get to it in priority order.

**Comment by amishra-dev** [comment]
btw: here is the dataplane sdk repo for go https://github.com/Azure/azure-storage-blob-go
