### ISSUE TITLE
Release notes missing for v8.0.0-beta release

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#540]
The v7.0.0-beta had release notes that gave insight into what had actually [changed](https://github.com/Azure/azure-sdk-for-go/releases/tag/v7.0.0-beta)

The v8.0.0-beta didn't have anything [similar](https://github.com/Azure/azure-sdk-for-go/releases/tag/v8.0.0-beta) - where do we find what changed in this release?

**Comment by marstr** [comment]
Ah, sorry for this oversight.

You can find a table similar to that found in former releases in [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md). However, I'll investigate updating the Release tag to include those changes. Thanks for your input.

**Comment by stack72** [comment]
Thanks @marstr :)
