### ISSUE TITLE
Get App Service Plan 404 does not return an error

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#5407]
### Bug Report

- import path of package in question `github.com/Azure/azure-sdk-for-go/services/web/mgmt/2018-02-01/web
`
- SDK version e.g. `31.0.0`
- `go version go1.12.5 darwin/amd64`

### Issue

I ran into an issue where I used the Get method for an app service plan and received a nil object with a 404 response but no error. I expected an error to occur because that is how the majority of this provider handles 404 errors and it's causing issues in the [Terraform Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3584) . We're implementing a workaround for now but it'd be great to get this addressed! 

### Reproduce 
You should be able to reproduce this by doing a Get call on an app service plan that was deleted or doesn't exist

**Comment by loarabia** [comment]
Hi @mbfrahry  It looks like the team will merge the pull request you wrote up to help you work around this temporarily. I'm leaving this to track the real fix.
