### ISSUE TITLE
Authenticating with Azure using Certificate

### ISSUE THREAD

**Issue by udbhav-sharma** [Azure/azure-sdk-for-go#5412]
I am trying to authenticate with Azure Active Directory using Certificate. I get following error when I try authentication using SDK 
`Authorizer failed: failed to get oauth token from certificate auth: failed to decode pkcs12 certificate while creating spt: pkcs12: expected exactly two safe bags in the PFX PDU` 

Same certificate works if I use powershell commandlet to login to azure.

[Code Link](https://gist.github.com/udbhav-sharma/3aaff6c673af918e17cd18a82614958e)

There is one more concern I like to raise - Golang SDK forces to provide the certificate in pfx format where as `Login-AzureRmAccount` powershell commandlet not only works with certificate without private key but also only requires certificate thumbprint. Why is there a discrepancy in the API for different languages?

**Comment by loarabia** [comment]
Hi @udbhav-sharma  I've tagged this bug so that the right team member can take a look.

**Comment by udbhav-sharma** [comment]
Is there a update?

**Comment by ArcturusZhang** [comment]
@jhendrixMSFT Hi would you please check if this is related with auth in go-autorest?

**Comment by jhendrixMSFT** [comment]
Yes this is from the `adal` package in `go-autorest`.  Do you have a code sample how you're using the API?

**Comment by jhendrixMSFT** [comment]
Thanks.  We use `pkcs12.Decode()` to extract the cert/private key which expects there to be only one cert/private key pair in the data.  How are you creating the cert?

Regarding authentication with certificate thumbprint I've opened https://github.com/Azure/go-autorest/issues/468 to track it.

**Comment by gapariha** [comment]
Hi @jhendrixMSFT - I'm also seeing similar issue as above while trying to authN with certificate using Go auth SDK: "github.com/Azure/go-autorest/autorest/azure/auth"   NewAuthorizerFromEnvironment()

`"Error": "failed to get oauth token from certificate auth: failed to decode pkcs12 certificate while creating spt: pkcs12: expected exactly two safe bags in the PFX PDU"`

Wondering if there has been an update for this issue or any workaround to that matter? 
Regards.

**Comment by jhendrixMSFT** [comment]
No update here as we don't have a repro to investigate further.  How was your cert created?

**Comment by gapariha** [comment]
I see. I have generated the cert in the KeyVault with OneCert CA. 
In the PEM file, I can see one private key and but 3 certificate sections.

**Comment by tamilmani1989** [comment]
@jhendrixMSFT i'm also hitting the same issue..i created sslcert from azure keyvault. Can you please let us know how you tested it?

**Comment by jhendrixMSFT** [comment]
Presumably your certificate contains multiple sections too.  Are these intermediate authorities?  I don't have a repro but this is my current assumption.

The guts of this code was written before I joined the Go SDK team.  Presumably the original authors tested it with a cert that contained only the root authority (will try to find more info).

**Comment by tamilmani1989** [comment]
@jhendrixMSFT  Repro steps: create cert issued by ssladmin(choose integrated CA) from azure keyvault and download the pfx file. Then run the above sample code.

No issues with self signed certificate but certificates issued by integrated Authority CA are failing

we should have supporting api to decode pfx data issued by integrated authority CA

**Comment by tamilmani1989** [comment]
I figured out a way. Since it contains more than one cert, we have to use pkscs.ToPEM and then convert to x509 certs.

**Comment by jhendrixMSFT** [comment]
Thanks for the info, I will try to repro this.  Can you share the code changes you made that fixed it for you?

**Comment by tamilmani1989** [comment]
func decodePkcs12(pkcs []byte, password string) (*x509.Certificate, *rsa.PrivateKey, error) {
        blocks, err:= pkcs12.ToPEM(pkcs,password)
        if err != nil {
                return nil, nil, err
        }

        var (
           cert *x509.Certificate
           priv *rsa.PrivateKey
       )

       for _, block := range blocks {
          if block.Type == "CERTIFICATE" {
            if _, ok := block.Headers["localKeyId"]; ok {
              cert, err = x509.ParseCertificate(block.Bytes)
              if err !=  nil {
                  fmt.Printf("Error parsing certificate from pem block:%v\n", err)
                  continue
              }
            }
          } else if block.Type == "PRIVATE KEY" {
              priv, err = x509.ParsePKCS1PrivateKey(block.Bytes)
              if err != nil {
                fmt.Printf("Error parsing private key from pem block: %v\n",err)
              }
            }
        }

    return cert, priv, nil
}``

**Comment by jhendrixMSFT** [comment]
This has been fixed in autorest/azure/auth/v0.5.1.
