### ISSUE TITLE
Table query not extracting and following continuation token properly

### ISSUE THREAD

**Issue by djyou** [Azure/azure-sdk-for-go#5425]
### Bug Report

Azure Storage table query may return results with non-empty `x-ms-continuation-NextPartitionKey` but empty `x-ms-continuation-NextRowKey`, see https://docs.microsoft.com/en-us/rest/api/storageservices/query-timeout-and-pagination

The current Go SDK implementation couldn't extract and follow the continuation token for these cases due to the assumption that both have to exist https://github.com/Azure/azure-sdk-for-go/blob/7a9d2769e4a581b0b1bc609c71b59af043e05c98/storage/table.go#L374

The expectation is that (also how other SDKs handle continuation token), the pagination headers don't have dependencies on each other, and any non-empty ones should formulate a continuation token and be added to the URL of the next request.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v32.1.0
