### ISSUE TITLE
DatabaseVulnerabilityAssessmentRuleBaselinesClient always return "Default" as baseline

### ISSUE THREAD

**Issue by benjamin37** [Azure/azure-sdk-for-go#5435]
### Bug Report

- import path of package in question github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2017-03-01-preview/sql
- SDK version `v32.0.0` (Commit ` 7a9d276`)
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`:   `go version go1.12 linux/amd64`

- What happened?

When calling the method `CreateOrUpdate` with the parameter `baselineName=master` in `DatabaseVulnerabilityAssessmentRuleBaselinesClient` it returns `"Default"` as `baselines` in the `result.ID`.

- What did you expect or want to happen?
I would expect that the `result.ID` contains `master` as `baselines`.

- How can we reproduce it?
Create a mssql database with vulnerability scanning enabled. Set any baseline for the master database.

- Anything we should know about your environment.
No.

- Additional Information
I already contacted the Azure support on this case and it seems to be a bug on the Azure REST API. So I'm not sure if a quick fix in the SDK is wanted in this case or if we just wait until the Azure REST API is fixed.

**Comment by talhers** [comment]
Hi,
Could not reproduce. Can you check if the issue is still happening?
Thanks,
Tal

**Comment by benjamin37** [comment]
Hi,

no Microsoft fixed this bug meanwhile.

Kind regards
Benjamin
