### ISSUE TITLE
BootDiagnostics is missing for the ManagedCluster and AgentPool 

### ISSUE THREAD

**Issue by djsly** [Azure/azure-sdk-for-go#5443]
### Feature Request

We would like to be able to control the DiagnosticSettings of the AgentPool when creating an AKS cluster.

Right now: both https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2019-06-01/containerservice/models.go#L1747-L1784 and https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2019-06-01/containerservice/models.go#L1787-L1822 don't expose the settings, which makes it impossible to configure after the fact using terraform since we are not managing the underlying resources that AKS creates.

since both Compute(VM/VMSS) support the diagnosticSettings, I'm sure it should be straight forward to expose from the AKS object.

**Comment by djsly** [comment]
@ArcturusZhang  any update on this request ? Is this something we should be expecting to come available ?

**Comment by tombuildsstuff** [comment]
cc @jluk

**Comment by djsly** [comment]
@jluk what's you take here ?

**Comment by jluk** [comment]
Thanks for tagging and bumping - @djsly could you open this request on the azure/aks repo with the scenario and properties that require exposure of it? This would need to be a new feature for us to discover and investigate. There's a set of VMSS properties which we want to expose and some we do not in the hopes of being able to simplify the IaaS mgmt within AKS.

We're definitely open to discussing the validity of the ask, just need some more details and intake it with some more context.

**Comment by djsly** [comment]
Created: https://github.com/Azure/AKS/issues/1310

**Comment by jluk** [comment]
Thank you! @djsly do you mind if we close this issue on the sdk in favor of discussing merits of the feature within AKS first?

**Comment by djsly** [comment]
Sure no problem.  If you feel like it is worth tracking there only.

**Comment by ArcturusZhang** [comment]
Close this issue since it has been tracked at other place
