### ISSUE TITLE
Unable to acquire an infinite blob lease

### ISSUE THREAD

**Issue by pmcatominey** [Azure/azure-sdk-for-go#548]
There as a check added in #430 which only sets the lease duration header if the provided value is > 0, this prevents infinite leases from being acquired as the request is rejected for missing the header.

**Comment by marstr** [comment]
Nice catch.

Relevant documentation can be found here: [Microsoft Docs, storageservices/fileservices/lease-blob](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/lease-blob)

**Comment by marstr** [comment]
PR #550 solves this issue.
