### ISSUE TITLE
Documentation for Generating my own SDK

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#549]
Hi all.

There's a bug in the Compute Swagger. Someone has provided me with a one-off fixed copy of the Swagger. I need to test the whole thing end-to-end, so I need to generate this SDK myself.

Is this process documented? I'd be happy to contribute it if not... as long as someone can provide me with some help getting started...

**Comment by kirthik** [comment]
@colemickens - we are working on documenting the process. It is work in progress. I will share it with you offline. Any feedback would be great!

**Comment by salameer** [comment]
Hi Cole,

I'm guessing @kirthik shared the link with where the documentation is, one thing @kirthik I think we should make this page eventually public
