### ISSUE TITLE
Add User-Agent header

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#55]
We must add User-Agent header while making queries to management APIs. It should be configurable but should have a default. We can get the UA convention from other language sdks we have.

**Comment by paulmey** [comment]
Looks like in the .NET SDK, only HDI is setting useragent?

https://github.com/Azure/azure-sdk-for-net/search?utf8=%E2%9C%93&q=useragent

**Comment by paulmey** [comment]
How about something like this:
https://github.com/Azure/azure-sdk-for-node/blob/a06932a8b536318a49b65fa4d26f4aed0bc18c40/lib/common/lib/services/filters/useragentfilter.js#L42

**Comment by ahmetalpbalkan** [comment]
@paulmey hmm interesting. I thought they have it. this is good to have for tracking from our side e.g. how much docker-machine uses the API or how popular go sdk is.

e.g. python sdk has `pyazure`:
![](http://cl.ly/image/070x1I3E1U3X/Image%202015-03-26%20at%2011.12.59%20AM.png)

**Comment by ahmetalpbalkan** [comment]
@paulmey updating version on each release is a bit hard, other than that I'm down for `azure-sdk-for-go` string (we should also make it configurable through `Config` type so other software can pass their identity).
