### ISSUE TITLE
Unable to use `storagedatalake#PathClient.Create`

### ISSUE THREAD

**Issue by kahing** [Azure/azure-sdk-for-go#5502]
### Bug Report

package: `services/storage/datalake/2018-11-09/storagedatalake`
version: go-autorest/v12.4.2 Azure-SDK-For-Go/v32.1.0

`storagedatalake#PathClient.Create` takes many parameters, one of which is `xMsLeaseID`, which according to https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/create is optional. However the sdk validates that it follows some regex: https://github.com/Azure/azure-sdk-for-go/blob/master/services/storage/datalake/2018-11-09/storagedatalake/path.go#L116

as a result I cannot pass empty string for the parameter.

I could bypass validation by using `CreatePreparer`/`CreateSender`/`CreateResponder` manually but that's not ideal.

**Comment by kahing** [comment]
`X-Ms-Client-Request-Id`'s validation is similarly incorrect. Also, int64 pointers are not marshaled correctly and instead are marshaled like `Content-Length: 0xpointervalue`. Is this package actually used?

**Comment by ArcturusZhang** [comment]
This seems to be related with `go-autorest`, hi @jhendrixMSFT do you have any idea against this issue?

**Comment by jhendrixMSFT** [comment]
This looks to be a codegen bug, [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/storage/datalake/2018-11-09/storagedatalake/path.go#L1309) the code should dereference `contentLength`, I'll get this fixed.
As for the headers, they're marked as optional but the codegen isn't treating them as such; I'm still investigating that one.

**Comment by kahing** [comment]
I found a few other issues:

For `List()`, `isDirectory` is returned as a string (ie: `"true"`) and cannot be default json unmarshalled into a golang `bool`

similarly, `contentLength` is returned as a string (ie: `"123"`) and cannot be unmarshalled into golang `int64`

during rename, the source object needs to be url escaped (`url.PathEscape`)

**Comment by ArcturusZhang** [comment]
> I found a few other issues:
> 
> For `List()`, `isDirectory` is returned as a string (ie: `"true"`) and cannot be default json unmarshalled into a golang `bool`
> 
> similarly, `contentLength` is returned as a string (ie: `"123"`) and cannot be unmarshalled into golang `int64`
> 
> during rename, the source object needs to be url escaped (`url.PathEscape`)

Feel free to create new issues about these bad guys

**Comment by ArcturusZhang** [comment]
This bug has been fixed, closing
