### ISSUE TITLE
Storage Account Request Issues with Go 1.8

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#554]
Hi Team

Over in Terraform land, since we moved to Go 1.8, we are seeing the following issues in our code:

```
* azurerm_storage_account.test: 1 error(s) occurred:
        
        * azurerm_storage_account.test: Error creating Azure Storage Account 'testaccsa236v': storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: Put https://management.azure.com/subscriptions/*******/resourceGroups/testAccRg-5614354704730717118/providers/Microsoft.Storage/storageAccounts/testaccsa236v?api-version=2016-01-01: net/http: request canceled
```

Any thoughts would be great

thanks

Paul

**Comment by marstr** [comment]
Howdy @stack72, I'm experimenting with moving to Go 1.8 now and will update you if I find anything to help out.

**Comment by mcardosos** [comment]
Hello!
@stack72 , could you provide more info please? I haven't been able to repro, and I don't know the ins and outs of the net/http package.
As create storage account is a [long running operation](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-long-running-operation) which in the Go SDK has a cancel channel as parameter, could the issue have to do with that?

**Comment by salameer** [comment]
Hi @stack72,

We haven't heard back from you and we'll be closing this ticket if we having heard from you by next Wednesday (8th of March 2017)

**Comment by stack72** [comment]
Hi @salameer 

I am still trying to work out what the issue is here - so please keep this open - this is a real issue right now in the terraform repositiory

Paul

**Comment by mcardosos** [comment]
Hello @stack72 
From digging in the http package, it looks like the cancel channel is no being correctly replaced in the request. I will continue investigating.
Does this only happen in funcs that happen to be long running operations? Just to know if I'm in the right path.

**Comment by stack72** [comment]
Hi @mcardosos yes, this seem to only be long running operations - this is great that you are in the right area

Thanks

Paul

**Comment by mcardosos** [comment]
Hello @stack72 
Digging some more: this error, `net/http: request canceled` comes from the net/http package, but in fact, it can arrive from 2 different places in the package. As I mentioned above, one of them is when the cancel chan, if you happened to provide it as a parameter in the SDK func, is not replaced correctly in the request.
The other place this very same error could come from is when the cancel chan is closed. This is how I could repro this error. I know for sure that this from where I was able to repro. I could repro with both Go 1.8 and 1.7.5.
Where is your error coming from?

**Comment by mcardosos** [comment]
Hello again @stack72 
Is the issue solved in your side? If not, could you provide us some more context please? Maybe the stack trace or a link to the Terraform issue?

**Comment by stack72** [comment]
Hi @mcardosos 

Let's close out my issue for now and we will see what happens with the cancel chan

Paul
