### ISSUE TITLE
incorrect deserialization for `storagedatalake#PathClient.List`

### ISSUE THREAD

**Issue by kahing** [Azure/azure-sdk-for-go#5549]
From https://github.com/Azure/azure-sdk-for-go/issues/5502#issuecomment-521840401

For List(), isDirectory is returned as a string (ie: "true") and cannot be default json unmarshalled into a golang bool

similarly, contentLength is returned as a string (ie: "123") and cannot be unmarshalled into golang int64

**Comment by loarabia** [comment]
Triaging and assigning out given comments in the other bug.

**Comment by jhendrixMSFT** [comment]
This is has been ported to https://github.com/Azure/azure-rest-api-specs/issues/7003
