### ISSUE TITLE
Breaking changes in minor releases of the SDK

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#5557]
👋 

Taking a look through [the last few releases](https://github.com/Azure/azure-sdk-for-go/releases) it appears there's been a few breaking changes in minor releases of the SDK:

https://github.com/Azure/azure-sdk-for-go/commit/8c472686968f1d7b29df3d4bb9435a2db9eacbe7#diff-84e58a944451296f0308ed309e92e03fL410-R438

https://github.com/Azure/azure-sdk-for-go/commit/8c472686968f1d7b29df3d4bb9435a2db9eacbe7#diff-84e58a944451296f0308ed309e92e03fL235-R263

Whilst we can adapt [to these changes](https://github.com/Azure/azure-sdk-for-go/commit/8c472686968f1d7b29df3d4bb9435a2db9eacbe7#diff-e728ed263056eaa9d1ff20d3125706a8R438) they are breaking changes - and as such I'd assume they'd take effect in a major version of the SDK at the end of the month [as the breaking changes policy outlined here states](https://github.com/Azure/azure-sdk-for-go#package-updates) - out of interest has this policy changed, or was this just a bug? :)

Thanks!

**Comment by ArcturusZhang** [comment]
Hi @tombuildsstuff , in our release practice, preview packages will be considered as version 0 and always unstable, therefore breaking changes are allowed in minor version for preview packages.
See [wiki page](https://github.com/Azure/azure-sdk-for-go/wiki/SDK-Update-Practices)
