### ISSUE TITLE
Support for Kusto API version 2019-05-15

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-sdk-for-go#5558]
### Feature Request

Please integrate the Go Client Implementation for Kusto API v2019-05-15 to support the following features:

- virtualNetworkConfiguration
- optimizedAutoscale
- enableDiskEncryption
- enableStreamingIngest

Path: `/services/kusto/mgmt/2019-05-15/kusto`

**Comment by ArcturusZhang** [comment]
Hi @jrauschenbusch , as far as I know, there is not an api version 2019-05-15 for azure-kusto yet. All available version lists [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/azure-kusto/resource-manager/Microsoft.Kusto).

**Comment by jrauschenbusch** [comment]
@ArcturusZhang You can get all available API versions via executing the following shell script:

Precondition: Azure CLI installed an account logged in

```sh
#!/bin/bash

BEARER_TOKEN=`az account get-access-token | jq .accessToken | tr -d '"'`
SUBSCRIPTION=`az account list | jq .[0].tenantId | tr -d '"'`

GET https://management.azure.com/subscriptions/$SUBSCRIPTION/providers\?api-version=2019-08-01 -H "Authorization: Bearer $BEARER_TOKEN"
```

Extracted Kusto api versions from result:

```
[...]
"apiVersions": [
  "2019-05-15",
  "2019-01-21",
  "2018-09-07-preview",
  "2017-09-07-privatepreview"
],
"defaultApiVersion": "2019-05-15"
[...]
```

Hence the API is already live, but no spec yet.

Especially for Kusto you can show the resource properties via:

```sh
#!/bin/bash

BEARER_TOKEN=`az account get-access-token | jq .accessToken | tr -d '"'`
SUBSCRIPTION=`az account list | jq .[0].tenantId | tr -d '"'`

`GET https://management.azure.com/subscriptions/$SUBSCRIPTION/providers/Microsoft.Kusto/clusters\?api-version=2017-05-15  -H "Authorization: Bearer $BEARER_TOKEN"
```

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang You can get all available API versions via executing the following shell script:
> 
> Precondition: Azure CLI installed an account logged in
> 
> ```shell
> #!/bin/bash
> 
> BEARER_TOKEN=`az account get-access-token | jq .accessToken | tr -d '"'`
> SUBSCRIPTION=`az account list | jq .[0].tenantId | tr -d '"'`
> 
> GET https://management.azure.com/subscriptions/$SUBSCRIPTION/providers\?api-version=2019-08-01 -H "Authorization: Bearer $BEARER_TOKEN"
> ```
> 
> Extracted Kusto api versions from result:
> 
> ```
> [...]
> "apiVersions": [
>   "2019-05-15",
>   "2019-01-21",
>   "2018-09-07-preview",
>   "2017-09-07-privatepreview"
> ],
> "defaultApiVersion": "2019-05-15"
> [...]
> ```
> 
> Hence the API is already live, but no spec yet.
> 
> Especially for Kusto you can show the resource properties via:
> 
> ```shell
> #!/bin/bash
> 
> BEARER_TOKEN=`az account get-access-token | jq .accessToken | tr -d '"'`
> SUBSCRIPTION=`az account list | jq .[0].tenantId | tr -d '"'`
> 
> `GET https://management.azure.com/subscriptions/$SUBSCRIPTION/providers/Microsoft.Kusto/clusters\?api-version=2017-05-15  -H "Authorization: Bearer $BEARER_TOKEN"
> ```

Thanks for the clarification. But if the spec is not released, there will not be a SDK generated.
Closing this issue.
