### ISSUE TITLE
SDK equivalent for CLI "az aks install-connector" 

### ISSUE THREAD

**Issue by selvik** [Azure/azure-sdk-for-go#5559]
Hello,

Is there an equivalent for "az aks install-connector" in the Azure SDK for Go? I have looked under containerservices and containerinstance but can't seem to spot the relevant call. 

Thank you for any hints!

**Comment by seanmck** [comment]
No, this is a pure client side command in the CLI that wraps a helm deployment. It was an interim solution until 1st class support was added via virtual nodes. I'm afraid we don't have great docs on how to enable virtual nodes from the SDK but it should be fairly straightforward. It's just an add-on profile that looks like this (in JSON):

"addonProfiles": {
    "aciConnectorLinux": {
      "config": {
        "SubnetName": "virtual-node-aci"
      },
      "enabled": true
    },

Note that virtual nodes (the 1st class add-on) is only available for Linux today.
