### ISSUE TITLE
Please include serviceRequestId in error messages

### ISSUE THREAD

**Issue by ehashman** [Azure/azure-sdk-for-go#5563]
### Feature Request

We wrap the azure-sdk-for-go in [openshift-azure](https://github.com/openshift/openshift-azure/) (currently using v24.0.0). Occasionally, we hit internal Azure service errors like this one:

```
time="2019-08-13T23:24:40Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateWorkerAgentPoolDeleteVM: Code=\"NetworkingInternalOperationError\" Message=\"Unknown network allocation error.\"" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:24"
```

(from https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1853/pull-ci-azure-master-upgrade-v7.0/1/build-log.txt)

As you can see from the message above, we wrap the error returned by the SDK. In this case, the "Code" and "Message" were included in that error message when we bubble down `err.Error()`. https://github.com/openshift/openshift-azure/blob/ca7e2711cf39797889950a3f37754f548675a336/pkg/fakerp/util.go#L22-L26 https://github.com/openshift/openshift-azure/blob/master/pkg/fakerp/util.go#L36

Because the `serviceRequestId` is not included here, it is difficult for us to file support tickets to debug what went wrong on this particular request.

We do have other places in our code that is capable of dumping a `serviceRequestId`, but it's a bunch of extra work. See e.g.

```
time="2019-08-14T16:30:44Z" level=warning msg="deployment failed: autorest.DetailedError{Original:context.deadlineExceededError{}, PackageType:\"Future\", Method:\"WaitForCompletion\", StatusCode:200, Message:\"context has been cancelled\", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc000322360)}" func=github.com/openshift/openshift-azure/pkg/fakerp.GetDeployer.func1 file="/tmp/tmp.ifjA1woVPv/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:116"
time="2019-08-14T16:30:45Z" level=debug msg="{\n  \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1856-e2e-upgrade-yxnyjp/providers/Microsoft.Resources/deployments/azuredeploy/operations/9CD2E40928E6D3CA\",\n  \"operationId\": \"9CD2E40928E6D3CA\",\n  \"properties\": {\n    \"provisioningState\": \"Running\",\n    \"timestamp\": \"2019-08-14T16:30:31.7720173Z\",\n    \"serviceRequestId\": \"3af64e94-3216-460f-9595-2d890c9f0a5f\",\n    \"statusCode\": \"Created\",\n    \"targetResource\": {\n      \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1856-e2e-upgrade-yxnyjp/providers/Microsoft.Compute/virtualMachineScaleSets/ss-master\",\n      \"resourceName\": \"ss-master\",\n      \"resourceType\": \"Microsoft.Compute/virtualMachineScaleSets\"\n    }\n  }\n}" func=github.com/openshift/openshift-azure/pkg/fakerp.debugDeployerError file="/tmp/tmp.ifjA1woVPv/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:44"
```

(from https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1856/pull-ci-azure-master-upgrade-v5.2/449/build-log.txt)

https://github.com/openshift/openshift-azure/blob/ca7e2711cf39797889950a3f37754f548675a336/pkg/fakerp/fakerp.go#L43-L44

It would be great if this and any other pertinent debugging info was included in SDK errors by default.

**Comment by ArcturusZhang** [comment]
Hi @ehashman I added the `Service Attention` label so the service team will get informed about this.

**Comment by lirenhe** [comment]
@jhendrixMSFT, as the serviceRequestId  should be part of the response header based on ARM guideline, is it possible to update codeGen to expose that value?

**Comment by jhendrixMSFT** [comment]
Is this uniform across all ARM RPs?  Ideally this would be modeled in the swagger so that the code generator would include this field in the error type (we codegen the modeled error types in track 2 only).

CC @JeffreyRichter

**Comment by JeffreyRichter** [comment]
If they wrap our error and we return the entire response headers, then it is trivial for them to just grab the header value they desire.

**Comment by lirenhe** [comment]
@ehashman  to get the serviceRequestId, you could leverage RawResponse returned in API call get grab the header value if needed.
