### ISSUE TITLE
Support for setting blob properties

### ISSUE THREAD

**Issue by politician** [Azure/azure-sdk-for-go#56]
It doesn't look like the current library supports setting blob properties.  Ensuring that the Cache-Control and Content-Type properties are set correctly is an important use case when using Azure CDN to serve content from Blob Storage.

**Comment by ahmetalpbalkan** [comment]
@politician Interested in contributing the method yourself? The implementation should be rather simple if you're familiar with Go. We also have a full unit test suite for blob storage code which you can help you understand the code.

The current state of blob storage package is, we add methods based on our needs in other projects and we happily accept contributions from the community.

**Comment by ahmetalpbalkan** [comment]
@politician Do you still need this?

**Comment by politician** [comment]
Yes, we still need to ability to control the mimetype of files uploaded to
blob storage to be served over HTTP. AFAICT, setting blob properties is the
way to do that, but I haven't had time to jump on this myself.

**Comment by marstr** [comment]
@vishrutshah It seems to me that BlobProperties already has `Cache-Control` and and `Content-Type`. What else is required for us to be able to resolve this issue?

**Comment by vishrutshah** [comment]
@marstr  That's great then, we should just notify the customer then and close the issue then 👍

**Comment by politician** [comment]
That's good news.  Thanks @marstr.
