### ISSUE TITLE
Managed Disks for VMs

### ISSUE THREAD

**Issue by rrudduck** [Azure/azure-sdk-for-go#560]
Is creating VMs and Scale Sets with managed disks currently supported? 

Looking at the current sdk, it appears the compute provider has not been updated to api version 2016-04-30-preview yet, which would explain the Bad Request and validation errors I'm running into. Any timeline on that happening?

Thanks.

EDIT: Specifically I'm talking about the implicit create support. Not creating disks themselves.

More details: hashicorp/terraform#11874

**Comment by brandontosch** [comment]
FYI, looks like there is a pull request open for this: #561

**Comment by marstr** [comment]
Howdy folks. As @brandontosch mentioned, support for this is currently in review and should be approved and released in the next several days.

**Comment by colemickens** [comment]
>released in the next several days.

15 minutes later... 😉. Thanks for this!

**Comment by marstr** [comment]
under-promise over deliver! What can I say :)
