### ISSUE TITLE
Enable large block blob support

### ISSUE THREAD

**Issue by TeppeiIshii** [Azure/azure-sdk-for-go#562]
It seems this package assumes the block blob size == 4MB; however, with recent update, Azure Blob Storage now supports block size up to 100MB.

General Availability: Larger Block Blobs in Azure Storage
https://azure.microsoft.com/ja-jp/blog/general-availability-larger-block-blobs-in-azure-storage/
------------------
We have increased the maximum allowable block size from 4 MB to 100 MB, while maintaining support for up to 50,000 blocks committed to a single Blob.
------------------

Understanding Block Blobs, Append Blobs, and Page Blobs
https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/understanding-block-blobs--append-blobs--and-page-blobs
------------------
Each block can be a different size, up to a maximum of 100 MB (4 MB for requests using REST versions before 2016-05-31), and a block blob can include up to 50,000 blocks. 
------------------

For blob.go code, it defines the blob size to be 4 MB.  We need to have an option to use larger blocks.

https://github.com/Azure/azure-sdk-for-go/blob/ca43dde75b98dbf9ac4dc70df9c393a7fbe0ed46/storage/blob.go
===========================
// Maximum sizes (per REST API) for various concepts
const (
	MaxBlobBlockSize = 4 * 1024 * 1024
	MaxBlobPageSize  = 4 * 1024 * 1024
)
===========================

I'm not an expert in here, but you can just throw more data than 4 MB up to 100 MB into the same Put Blob REST API with REST version after 2016-05-31.

Azure Storage Services REST API Reference
https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/azure-storage-services-rest-api-reference
------------------
Block blobs larger than this must be uploaded as a set of blocks, each of which must be less than or equal to 100 MB (4 MB for requests using REST versions before 2016-05-31) in size.
------------------

Put Block List
https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/put-block-list
------------------
Each block can be a different size, up to a maximum of 100 MB for version 2016-05-31 and later, and 4 MB for older versions.
------------------

**Comment by marstr** [comment]
For further conversation on this topic, please see Azure/azure-storage-go#18

**Comment by mcardosos** [comment]
Fixed in https://github.com/Azure/azure-storage-go/pull/19
