### ISSUE TITLE
MERGE http verb used without const

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#564]
As mentioned in #563 review, there are a couple instances of hardcoded "MERGE " values being used as http verbs. Documentation for "MERGE" can be found [here](https://msdn.microsoft.com/en-us/library/dd541276.aspx).

It is not included in the stdlib's http library, so it didn't make sense to replace those instances until we decide on the best place to put `const MethodMerge = "MERGE"`.

**Comment by marstr** [comment]
@mcardosos & @jhendrixMSFT, thoughts on putting it in Azure/autorest?

**Comment by jhendrixMSFT** [comment]
There is a work item on my plate (I can't find it right now) to refactor constants into their own source file so they aren't duplicated; I think we can include it there yes?

**Comment by mcardosos** [comment]
https://github.com/Azure/azure-storage-go/issues/9 It is this one

**Comment by marstr** [comment]
^Nice. Yeah, lets go ahead and use that bug to track this item. I'll close this out.
