### ISSUE TITLE
Support ICMP in Network Security Group rules

### ISSUE THREAD

**Issue by nexxai** [Azure/azure-sdk-for-go#5642]
### Feature Request

The GUI currently allows for rules to be created with the ICMP traffic type.  models.go in the most recent version (network/mgmt/2019-06-01) does not currently support this.

**Comment by ArcturusZhang** [comment]
There is a type of enum `AzureFirewallNetworkRuleProtocol` in `services/network/mgmt/2019-06-01/module.go` line 423-434 with values `Any`, `ICMP`, `TCP` and `UDP`. Are you referring to this?

**Comment by anavinahar** [comment]
NSG's now support ICMP: https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#security-rules

**Comment by ArcturusZhang** [comment]
Closed due to no response from the issue author
