### ISSUE TITLE
There is no GetPolicyOperationResult API ?

### ISSUE THREAD

**Issue by metrue** [Azure/azure-sdk-for-go#5662]
### Service Package Request

The API document says there is an API `GetPolicyOperationResult` to check result of a backup policy modification or creation, But I search all the code, did not find any.
https://github.com/Azure/azure-sdk-for-go/blob/7a9d2769e4a581b0b1bc609c71b59af043e05c98/services/recoveryservices/mgmt/2016-06-01/backup/protectionpolicies.go#L44
````Go
// CreateOrUpdate creates or modifies a backup policy. This is an asynchronous operation. Use the
// GetPolicyOperationResult API to Get the operation status.
// Parameters:
// vaultName - the name of the Recovery Services vault.
// resourceGroupName - the name of the resource group associated with the Recovery Services vault.
// policyName - the backup policy to be created.
// resourceProtectionPolicy - the resource backup policy.
func (client ProtectionPoliciesClient) CreateOrUpdate(ctx context.Context, vaultName string, resourceGroupName string, policyName string, resourceProtectionPolicy ProtectionPolicyResource) (result ProtectionPolicyResource, err error) {
....
```

<!--
Please describe the service you seek support for, including a link to docs or
other libraries.

If you need this package for use in a downstream framework like Terraform or
Kubernetes please link any related issues from those projects.

Thanks and looking forward to serving you!
-->

**Comment by kaerm** [comment]
Thanks @metrue for checking in - I am routing it to the right team to take a look at this

**Comment by ArcturusZhang** [comment]
Hi @metrue there is no such method named `GetPolicyOperationResult` in go sdk. After a search in [swagger specs repo](https://github.com/Azure/azure-rest-api-specs), this method `GetPolicyOperationResult` only appears in description of the `CreateOrUpdate`, `Get` and `Delete` operation. 
Actually, despite the comments said that this method is an asynchronous operation, but it apparently is not. In go sdk, an asynchronous method will return a subtype of `azure.Future`. In the swagger specs, these operations are not be labelled as `"x-ms-long-running-operation": true`.
For now, you can regard these method as synchronous method, it will hold there until they return an actual result.

**Comment by metrue** [comment]
Thanks @ArcturusZhang,

Actually `Trigger` API also mentions using `GetProtectedItemOperationResult` to get result. 
https://github.com/Azure/azure-sdk-for-go/blob/7a9d2769e4a581b0b1bc609c71b59af043e05c98/services/recoveryservices/mgmt/2017-07-01/backup/backups.go#L52

And according to my test, normally these APIs like `CreateOrUpdate` and `Trigger`, they don't return an error when options of API are correct, but it does not mean everything is working well, it only means the Azure service receives the request, but what we want is what's the status of jobs like if backup enabled correct or backup job running well ?

**Comment by ArcturusZhang** [comment]
Hi @dheerendrarathor @dragonfly91 @sonathan do you guys have more information about this?

**Comment by pvrk** [comment]
Not sure if I am responding the right way. In the response for Async operations, you have 2 headers (Azure-AsyncOperation) or (Location). Tracking either of them should track the asynchronous operation.
