### ISSUE TITLE
Incorrect error may be returned in storage driver when response body couldn't be parsed for ServiceError

### ISSUE THREAD

**Issue by yuwaMSFT2** [Azure/azure-sdk-for-go#568]
In the following func in storage client: 
func (c Client) exec(verb, url string, headers map[string]string, body io.Reader, auth authentication) (*storageResponse, error) 

line 361, when the parsing the response to ServiceError fails, we will set a zero'ed AzureStorageServiceError with statuscode to be 0. This seems incorrect. Actually if the response body couldn't be deserialized correctly, we can treat it the same as case of no body, and return AzureStorageServiceError with correct status code, but with some message like "response body couldn't be parsed" . With that caller will be able to check the status code as usual.

https://github.com/Azure/azure-sdk-for-go/blob/4897648e310020dae650a89c31ff633284c13a24/storage/client.go#L361-L365

**Comment by yuwaMSFT2** [comment]
@marstr @DavidObando @SajayAntony

**Comment by SajayAntony** [comment]
@yuwaMSFT2 Do you already have a PR for this?

**Comment by yuwaMSFT2** [comment]
@SajayAntony @marstr It's a simple change...if you want I can prepare a PR...

**Comment by salameer** [comment]
Hi @yuwaMSFT2 

Thanks so much for brining this to our attention, @mcardosos will be looking into this, if you can do a PR it will certainly help with the investigation and speed up matters.

Btw for future refference we have now a seprate repo for GO Storage here:
https://github.com/Azure/azure-storage-go/tree/7c36d244fc8bf27bcf9785b0b37d6beef2949296

You can submit your pr there in the Dev branch :)

THANKS AGAIN!

**Comment by mcardosos** [comment]
Fixed in the dev branch in https://github.com/Azure/azure-storage-go
Thanks for catching this issue!
