### ISSUE TITLE
Import PublishSettings from File

### ISSUE THREAD

**Issue by waitingkuo** [Azure/azure-sdk-for-go#57]
It seems that there's a private function for importing the publishsetting file
[https://github.com/MSOpenTech/azure-sdk-for-go/blob/master/management/publishSettings.go#L31]

But I can't find another function that use the private function. Will it be public or have a NewClientFromPublishSettingsFile constructor?

**Comment by hopetobelievein** [comment]
It was removed here: https://github.com/MSOpenTech/azure-sdk-for-go/commit/63430b193b5e705cfe3e00054c4e6a3fcf5bd3b8
@anweiss can you please address this issue?

**Comment by anweiss** [comment]
so not sure on this yet. we left the private functions in there just in case. I'll let @ahmetalpbalkan chime in.

**Comment by waitingkuo** [comment]
It seems that we have to create a client then import the publishsettings later.
3c9cf2fecccf6bbbedbc117ac48c12f381536e02

**Comment by paulmey** [comment]
fixed in #65 /  ea0d561
