### ISSUE TITLE
Regenerate from latest CRP Spec

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#570]
They just merged (minutes ago) a fix to the Compute spec that I need in Kubernetes.

Is there any chance that this could be included in the pending V9? https://github.com/Azure/azure-rest-api-specs/pull/980

**Comment by mcardosos** [comment]
@marstr

**Comment by marstr** [comment]
Absolutely.

I created the PR so that folks could get a heads up about breaking changes. I'll wait at least two weeks before pulling it in. I'll keep re-generating until that happens.

-Martin

**Comment by colemickens** [comment]
Gentle ping, any chance I can convince you to regenerate and push sometime this week? Thanks!

**Comment by marstr** [comment]
I’ll regenerate and push to the marstr/v9 today. We’d like to keep it out of master for another week so that people have time to get a heads up about breaking changes.

-Martin

**Comment by marstr** [comment]
Done. (A little later than I mentioned yesterday, my apologies.)

**Comment by salameer** [comment]
Ping @colemickens can you verify if this is resolved on your side?

**Comment by colemickens** [comment]
I'm working on it, but KubeCon is interrupting me. I'll try to reply back in the next 48 hours.

**Comment by colemickens** [comment]
Let's close this out, the updated generated code has been pushed to master. If there's an issue with it, it's almost surely with the swagger spec...
