### ISSUE TITLE
reflect the restricted vm sizes in the sdk

### ISSUE THREAD

**Issue by lpuskas** [Azure/azure-sdk-for-go#5710]
### Bug Report

- import path:
github.com/!azure/azure-sdk-for-go@v24.1.0+incompatible/services/containerservice/mgmt/2018-03-31/containerservice/models.go

- SDK version 
 affects most versions

- What happened?
AKS cluster creation failed due to invalid machine type

- What did you expect or want to happen?
the SDK provides only machine types supported by the container service (the ones listed as restricted in the [documentation](https://aka.ms/aks/restricted-skus) are excluded)

The error message we got:
```
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The VM SKU chosen for this cluster `Standard_A1_v2` does not have enough CPU/memory to run as an AKS node. Please see https://aka.ms/aks/restricted-skus for more details."
```

**Comment by ArcturusZhang** [comment]
Hi @lpuskas sorry about the inconvenience, but this behaviour is defined by the [rest api](https://github.com/Azure/azure-rest-api-specs/blob/5c0a27ed2b2048cfcfea5f201bc3bb2d62dd75b7/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L1282), which does not separate the VMSize that is acceptable for different scenes of usage.

**Comment by stoader** [comment]
@ArcturusZhang we're using [containerservice.PossibleVMSizeTypesValues](https://github.com/Azure/azure-sdk-for-go/blob/v33.1.0/services/containerservice/mgmt/2018-03-31/containerservice/models.go#L468) to determine what VMSize is valid for AKS. 

Should we use the list stored in `containerservice.PossibleVMSizeTypesValues` for querying VMSizes for AKS or a different API? If the later what API should we use to query VMSizes that are accepted by AKS?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang we're using [containerservice.PossibleVMSizeTypesValues](https://github.com/Azure/azure-sdk-for-go/blob/v33.1.0/services/containerservice/mgmt/2018-03-31/containerservice/models.go#L468) to determine what VMSize is valid for AKS.
> 
> Should we use the list stored in `containerservice.PossibleVMSizeTypesValues` for querying VMSizes for AKS or a different API? If the later what API should we use to query VMSizes that are accepted by AKS?

Actually, this kind of method exists for every enum type, which just returns all possible values for that enum type. To acheive what you want, you may have to write a method that filters the valid enum by your self.

**Comment by stoader** [comment]
@ArcturusZhang where the values of this enum type are generated from? are these from https://github.com/Azure/azure-rest-api-specs/blob/5c0a27ed2b2048cfcfea5f201bc3bb2d62dd75b7/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L783 ?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang where the values of this enum type are generated from? are these generated from https://github.com/Azure/azure-rest-api-specs/blob/5c0a27ed2b2048cfcfea5f201bc3bb2d62dd75b7/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L783 ?

Yes, everything in the services folder is generated from the spec swagger json.

**Comment by stoader** [comment]
@ArcturusZhang than if I understand it correctly if this https://github.com/Azure/azure-rest-api-specs/issues/7153 is addressed then the enum in the services folder will reflect those changes.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang than if I understand it correctly if this [Azure/azure-rest-api-specs#7153](https://github.com/Azure/azure-rest-api-specs/issues/7153) is addressed then the enum in the services folder will reflect those changes.

Sure, thanks!
