### ISSUE TITLE
mssql 2018-06-01-preview is not included in Go SDK

### ISSUE THREAD

**Issue by mybayern1974** [Azure/azure-sdk-for-go#5719]
### Service Package Request

The desired service spec: [https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerVulnerabilityAssessments.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerVulnerabilityAssessments.json)

The downstream request: [https://github.com/terraform-providers/terraform-provider-azurerm/pull/3806#issuecomment-527856048](https://github.com/terraform-providers/terraform-provider-azurerm/pull/3806#issuecomment-527856048)

**Comment by ArcturusZhang** [comment]
This will be fixed by [this pr](https://github.com/Azure/azure-rest-api-specs/pull/7150)
