### ISSUE TITLE
LocalNetworkGatewaysClient.Get doesn't validate parameters

### ISSUE THREAD

**Issue by whiskeyjay** [Azure/azure-sdk-for-go#576]
In localnetworkgateways.go, the Get function doesn't validate parameters for special cases.

For example, if the value of localNetworkGatewayName is an empty string, the REST call won't fail, it actually becomes a different request:

expected request - .../providers/Microsoft.Network/localNetworkGateways/**&lt;name&gt;**?apiVersion=... This is to return the information of the specified LNG.

actual request - .../providers/Microsoft.Network/localNetworkGateways/?apiVersion= ... This is to list all LNGs from the resource group.

So the REST call won't fail, it returns 200 OK, with unexpected JSON body. Then autorest won't be able to unmarshall the JSON value into a proper LocalNetworkGateway object, and fails silently.

The result is that the Get function returns a LocalNetworkGateway object with all but the Response field set to nil.

I believe the correct behavior of the function is not to send the REST request if the  localNetworkGatewayName parameter is empty, and return an error instead.

**Comment by salameer** [comment]
Yup agreed

**Comment by marstr** [comment]
In order to fix this, we're going to need to put constraints in the Swagger that ensure that an empty localNetworkGatewaysID is not permissible. ([Here is the relevant swagger](https://github.com/Azure/azure-rest-api-specs/blob/c683f6510a689e1629adb5d8e9e21848c68f2ca3/arm-network/2016-09-01/swagger/virtualNetworkGateway.json#L818)).

Further more, it's pretty clear that this is a categorical problem. We should add a requirement that variables present in the path have a minimum length of 1. I'll file follow up bugs that will pop-up below.

**Comment by salameer** [comment]
That's correct Martin, 

this is actaully implemented in some swaggers such as this one:

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-12-01/swagger/storage.json#L69

We can create an issue in API Specs repo and tag it to networking as an improvement. but from what I'm seeing it's a common behavior across alot of swaggers to not include this, and maybe we should be adding this as a warning in the linter. @veronicagg and @ravbhatnagar might wanna take a look here :)

**Comment by marstr** [comment]
Beat you to it @salameer! I have already spun up a Linter issue and submitted a PR to add that min code. Next, we have to validate that the generator actually does anything with those criteria.

**Comment by marstr** [comment]
Chatting with @mcardosos offline, it sounds like our generator already supports parameter minLength validation.

**Comment by marstr** [comment]
My attention is still on this issue. We're currently working on chasing down the correct folks to approve Azure/azure-rest-api-specs#1088.

**Comment by marstr** [comment]
Specs repo updated. I'll mark this bug resolved, but keep it open until we can generate a new version of the API with the validation in it.
