### ISSUE TITLE
SQL Elastic Pool zone redundant parameter missing

### ISSUE THREAD

**Issue by steve-hawkins** [Azure/azure-sdk-for-go#5793]
### Feature Request

This appears to be part of the [2017-10-01-preview REST API specs](https://github.com/Azure/azure-rest-api-specs/blob/3b9c0d0747954e8c8e9e4fbe8de8e37de78c0e16/specification/sql/resource-manager/Microsoft.Sql/preview/2017-10-01-preview/elasticPools.json#L342-L345)

**Comment by ArcturusZhang** [comment]
Hi @steve-hawkins is [this](https://github.com/Azure/azure-sdk-for-go/blob/7577651eb4127da06c3cb42126e22d70ad974b12/services/preview/sql/mgmt/2017-10-01-preview/sql/models.go#L2615) what you want?

**Comment by steve-hawkins** [comment]
Hi @ArcturusZhang that's it, apologies I was looking in the wrong place
