### ISSUE TITLE
Official DocumentDB Go SDK?

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#580]
Hi All,

Just wondering if anyone has had some thoughts around an official Go SDK/client-lib for DocumentDB?
I know there are a few 3rd party ones, but was wondering if anything official will start?

This might not be the best place to ask the question, but I have to start somewhere ;)

Thoughts?

Ken

**Comment by salameer** [comment]
Hi Ken,

For now we don't have it  on our road-map, but we'll definitely be taking this request as feedback. we'll poke around on our side and see if there's something intermediate that you can go with

Thanks,

Samer

**Comment by tombuildsstuff** [comment]
Hey @salameer 

I hate to `+1` this, but this would be really useful for us - we've recently shipped support for CosmosDB Accounts, but it'd be great to add support for Databases and some of the other resources too :)

Thanks!

**Comment by mcardosos** [comment]
Hello @kpfaulkner @tombuildsstuff 
Here it is a [sample](https://github.com/Azure-Samples/azure-cosmos-db-mongodb-golang-getting-started) on how to use [mgo](http://gopkg.in/mgo.v2) with CosmosDB.

**Comment by kpfaulkner** [comment]
I'd been thinking about going down that route, but was wondering specifically around a DocumentDB compatible API (as opposed to using the MongoDB one).

Still, this is merely curiosity on my part atm.

**Comment by devigned** [comment]
@kpfaulkner are there specific features that pique your interest exposed in the DocumentDB wire format that aren't available in the MongoDB flavor of CosmosDB?

**Comment by kpfaulkner** [comment]
No.... wasn't thinking of any specific piece of functionality. I was thinking more along the lines of any features that MS adds that requires an API change the DocDB API would get (since they control that, but do NOT control the MongoDB API). 

Possibly a simplistic view but that's where my thoughts were going.

**Comment by mcardosos** [comment]
@tombuildsstuff quick question. Do you need a specific DocumentDB / CosmosDB SDK? Or does mgo provide all the functionality you need?

**Comment by tombuildsstuff** [comment]
@mcardosos sorry, missed this! We're away off from implementing this, but from a quick look I think `mgo` should be sufficient :)

Thanks!

**Comment by hiyelbaz** [comment]
Can we use triggers with MongoDB api?
