### ISSUE TITLE
AzureAD: Missing Group Parameters

### ISSUE THREAD

**Issue by midacts** [Azure/azure-sdk-for-go#5835]
### Feature Request

I'm new to this world (I am more of an ops guys).
I've been using Terraform's AzureAD provider and was noticing little things about the AzureAD groups that can be __set in the portal__, but __not__ via Terraform and the __go sdk__.

When I create a group, there is not an option to:
- Set a description
- Specify the membership type (assigned, dyn user, dyn device)
- License assignment

Are these things that are not available in the SDK or api spec? (I'm not sure how to check the api spec for this but I would be interested to know how).

Azure/azure-sdk-for-go: [group create](https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/groups.go#L216)
Azure/azure-sdk-for-go: [GroupCreateParameters](https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/models.go#L1972)

**Comment by ArcturusZhang** [comment]
Hi @midacts there is a `AdditionalProperties` in `GroupCreateParameters` struct, maybe you can use this map to store these additional properties.
