### ISSUE TITLE
AzureAD: Missing User Paramters

### ISSUE THREAD

**Issue by midacts** [Azure/azure-sdk-for-go#5836]
### Feature Request

I'm new to this world (I am more of an ops guys).
I've been using Terraform's AzureAD provider and was noticing little things about the AzureAD groups that can be set in the portal, but not via Terraform and the go sdk.

When I create a user, there is not an option to:

- License assignment

Job info
- Job title
- Department
- Manager

Contact Info
  - Street Address
  - State/Province
  - Country/Region
  - Office
  - City
  - Zip code
  - Office phone
  - Mobile phone

Are these things that are not available in the SDK or api spec? (I'm not sure how to check the api spec for this but I would be interested to know how).

Azure/azure-sdk-for-go: [user create](https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/users.go#L48)
Azure/azure-sdk-for-go: [UserCreateParameters](https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/models.go#L4090)

**Comment by ArcturusZhang** [comment]
Hi @midacts there is a `AdditionalProperties` field in `UserCreateParameters` struct, maybe this could satisfy your demand.
