### ISSUE TITLE
Verify client account name instead of panicing

### ISSUE THREAD

**Issue by mjibson** [Azure/azure-sdk-for-go#584]
The following program panics at `service.CreateBlockBlob` because of the newline in the client account name. NewBasicClient should perhaps verify the account name is a valid format and return an error if it is not, instead of ignoring it and causing a panic later on.

```
package main

import (
	"github.com/Azure/azure-sdk-for-go/storage"
)

func main() {
	client, err := storage.NewBasicClient("\n", "password")
	if err != nil {
		panic(err)
	}
	service := client.GetBlobService()
	if err := service.CreateBlockBlob("c", "n"); err != nil {
		panic(err)
	}
}
```

**Comment by mcardosos** [comment]
Fixed!
