### ISSUE TITLE
Support mysql server 8.0

### ISSUE THREAD

**Issue by Oicho** [Azure/azure-sdk-for-go#5841]
### Feature Request
Hello,

Currently  Azure Database for MySQL support version 5.7, 5.6 and 8.0. Sadly supports only the first two version.

I ll try to add the 8.0 version it should not take too long.

**Comment by ArcturusZhang** [comment]
There is no version 8.0 publish in the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/b73e672a41f4a2f0b7c8ed0d996f8dabd2e4c3d5/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json#L1302) yet. I will let you know if the service team release new versions about this.
