### ISSUE TITLE
Support updating customData on Azure RM VM Scaling Sets 

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#585]
👋 hey

An [issue's been opened on the Terraform repo](https://github.com/hashicorp/terraform/issues/13547) enquiring about updating customData for VM Scale Sets.

The current version of the Compute API used in the Go SDK (`2016-04-30-preview`) doesn't support updating customData - is it possible to update the SDK to use a newer version of the API which supports this functionality?

I've checked the Rest API Specs repository and I can't find an updated Swagger for the Compute API - so I'm guessing this might need an updated Swagger too? :)

Thanks!

**Comment by marstr** [comment]
Sorry this has been inactive for a while!

Does [2017-03-30 solve your issue](https://github.com/Azure/azure-rest-api-specs/blob/b86684441ae014cd58c924081488b6a71e92dba0/arm-compute/2017-03-30/swagger/compute.json#L5104)? If so, that should be [the one that we're using in the SDK](https://github.com/Azure/azure-sdk-for-go/blob/eb9eddfb7d680dca671221dba9e47626dd5fb464/arm/compute/models.go#L1164).

**Comment by salameer** [comment]
Hi @tombuildsstuff  any thoughts here? :)

**Comment by tombuildsstuff** [comment]
👋 hey @marstr @salameer 

Sorry - missed this!

From what I can see, [the SDK is currently running `2016-04-30-preview`](https://github.com/Azure/azure-sdk-for-go/blob/eb9eddfb7d680dca671221dba9e47626dd5fb464/arm/compute/virtualmachinescalesets.go#L80). Based on [this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/61#issuecomment-309854572) it appears this API version fixes the issue - as such would it be possible to upgrade the version of the Compute API to `2017-03-30` in the next release?

Thanks!

**Comment by marstr** [comment]
Howdy @tombuildsstuff, I'll make sure to apply extra scrutiny to compute the next time we generate. :) Given that this issue will be automatically fixed as part of generation, I'm going to close it out to reduce some noise in issues assigned to me.

**Comment by marstr** [comment]
Also, it looks like this is represented here as well: https://github.com/Azure/azure-rest-api-specs/issues/895
