### ISSUE TITLE
HTTP 412 / Preflight validation check timed out

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#586]
👋 hey folks

Our nightly acceptance tests have failed with a transient error from the Container Service API:

> containerservice.ContainerServicesClient#CreateOrUpdate: Failure responding to request: StatusCode=412 -- Original Error: autorest/azure: Service returned an error. Status=412 Code="PreconditionCheckTimeOut" Message="Preflight validation check timed out. Please try again later."

Currently the SDK handles both polling for completion and retrying - given this is a temporary error, would it make sense for the SDK to handle retrying automatically for this status code?

Thanks!

**Comment by jhendrixMSFT** [comment]
I'm looking into this and I believe it's a bug in the service, i.e. if the server times out or otherwise fails when evaluating a precondition it shouldn't be returning 412.

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff Have you seen this error lately and if so could you send me a request ID so I can follow up with the service team?
We can't treat 412 as a transient error as it really isn't (the service should return something like a 503 if the evaluation of a precondition times out), so if you are no longer seeing this issue I will close this issue.

**Comment by jhendrixMSFT** [comment]
Also it would be great to know in which region you saw this error.

**Comment by jhendrixMSFT** [comment]
I'm gonna close this, please reopen if you see this again.

**Comment by tombuildsstuff** [comment]
Hey @jhendrixMSFT

Apologies for the delay in getting back to you here, I’d missed this in the github notifications.

We were seeing this issue in West US and unfortunately I don’t have a request ID as we weren’t recording that level of output in our tests and we’ve not seen this since. However should this issue appear again I’ll update the log level and reopen this.

Thinking about it, I vaguely recall seeing this error code from the Template Deployment Validation API call too through the PowerShell CLI in a previous role - so I’m not sure if that helps to narrow this down in any form?

Thanks!
