### ISSUE TITLE
Pagination Support for Storage Account List (nextLink)

### ISSUE THREAD

**Issue by benjamin37** [Azure/azure-sdk-for-go#5899]
### Bug Report

- import path of package in question, e.g. `.../services/storage/mgmt/2019-04-01/storage/account.go`
- SDK version e.g. `master`
- output of `go version`: go version go1.12 linux/amd64

- What happened?

I used the List function for storage accounts to List all storage accounts of my subscription. I have about 20 storage accounts in my subscription. It returned a paginated response with only one storage account in the first page with a nextLink property in the json that refers to the others which is possible according to the documentation of the azure REST API https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/list

The current version of the azure sdk for go does not support a paginated response for this api so I just got the first with the List call in `.../services/storage/mgmt/2019-04-01/storage/account.go`.

Response of the API looked like this:

```
{
  'value': [
    {
      'identity': {
        'principalId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'tenantId': '***',
        'type': 'SystemAssigned'
      },
      'sku': {
        'name': 'Standard_RAGRS',
        'tier': 'Standard'
      },
      'kind': 'BlobStorage',
      'id': '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxxxxxxxx',
      'name': 'xxxxxxxxxxxxxxxxxxxxxxx',
      'type': 'Microsoft.Storage/storageAccounts',
      'location': 'northeurope',
      ...
    }
  ],
  'nextLink': 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Storage/storageAccounts?api-version=2019-04-01&%24skiptoken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
}
```

- What did you expect or want to happen?

I would expect to get all my 20 storage accounts with the List operation. Similar List methods like the one for virtual machines support these kind of paginated responses.

- How can we reproduce it?

For me it was hard to reproduce it cause it's not obvious to me when I get a paginated response and when I get a full List of storage accounts. The following worked out for me to reproduce it

* Make sure to have about 20+ storage accounts in your subscriptions (more is maybe better)
* Call the List storage account method 100 times, at some point you will get a paginated response and an incomplete list of your storage accounts.

Maybe it's easier to reproduce when there are a lot of storage accounts in your subscription but I didn't try that out.

**Comment by ArcturusZhang** [comment]
In go SDK, the `List` call often returns a `ResultPage` struct, it may contains only one page, or multiple pages. How the results are paginated is controlled on the service side. Since the api will not return all results all in one object, you may always need to iterate all pages of the ResultPages to collect all results. Therefore I thought on the SDK side, it makes no difference. Let us see if the service team will give this a fix.
To iterate the results, you can
* use the `Values()` method of it to check the values of the current page
* use `NotDone()` method of it to check if there are more content to go
* use `Next()` method of it to load the next page of results.
code snippet:
``` go
pages, err := client.List(ctx)
if err != nil {
    panic(err)
}
var accounts []storage.Account
for pages.NotDone() {
    accounts = append(accounts, pages.Values())
    pages.Next()
}
```
Another solution is to use the `ListComplete` method. This method returns an `ResultPageIterator` which follows the similar method to use.

**Comment by benjamin37** [comment]
Hi @zhusijia26,

any new from the appropriate team? This ticket has been open for a while now.

Kind regards
Benjamin

**Comment by zhusijia26** [comment]
@kartikshah9 to help take a look.

**Comment by zezha-msft** [comment]
Hi @benjamin37, pagination is a very common pattern, since if there are 10000 accounts, the service can't return all of them in a single call.

Does @ArcturusZhang's response answer your question?

**Comment by benjamin37** [comment]
Hi @zezha-msft,

just saw that the method `listNextResults` is now also available in storage account in the sdk, comitted by @ArcturusZhang on 30.09. This seems to be fine now. The issue can be closed.
