### ISSUE TITLE
There doesn't seem to be a way to get-blob and get content length.

### ISSUE THREAD

**Issue by jrwren** [Azure/azure-sdk-for-go#590]
There doesn't seem to be a way to get-blob and get content length without resorting to multiple calls.

storageResponse isn't exposed. GetBlobProperties is a separate call.

It would be nice if there were a call like GetBlob(...) exposed which included access to all of the Response Headers as listed at `https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/Get-Blob?redirectedfrom=MSDN`

The API as is requires 2 calls to obtain a blob & the blobs length, without resorting to reading the entire blob to caclulate the length. Regardless of length, it would be nice to have other headers such as ETag available.

**Comment by jhendrixMSFT** [comment]
This has been fixed and will be included with the v10 release of the SDK.

**Comment by jrwren** [comment]
I can't find the fix/feature in this repo or at https://github.com/Azure/azure-storage-go. Will you please link me to the commit with the feature?

**Comment by jhendrixMSFT** [comment]
It was fixed in this PR https://github.com/Azure/azure-storage-go/pull/46
