### ISSUE TITLE
Unable to provision a Data Catalog with the SDK and a service principal (plus unhelpful error message)

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#5900]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`github.com/Azure/azure-sdk-for-go/services/datacatalog/mgmt/2016-03-30/datacatalog`
- SDK version e.g. `master`, `latest`, `18.1.0`
`github.com/Azure/azure-sdk-for-go v33.2.0+incompatible`
- output of `go version`
`go version go1.12.6 darwin/amd64`

- What happened?

When attempting to provision a data catalog with the following API `https://management.azure.com/subscriptions/REDACTED/resourceGroups/acctestRG-190927000326307213/providers/Microsoft.DataCatalog/catalogs/acctest-DC-190927000326307213?api-version=2016-03-30`:
```
{
	"location": "westeurope",
	"properties": {
		"sku": "Free",
		"admins": [{
			"upn": "acctest-DCUser.190927000326307213@terraformhashicorp.onmicrosoft.com"
		}]
	},
	"tags": {}
}
```

I get the following error back:
```
Error: datacatalog.ADCCatalogsClient#CreateOrUpdate: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "Error while processing request. Please use ActivityId:'22344556-b783-4f27-ae45-a7845f3b2524' to contact user support group." error: invalid character 'E' looking for beginning of value
```

I have played around with the properties and nothing seems to work. Of note it does seem like some of the properties the SDK is sending are invalid:
```
Error: datacatalog.ADCCatalogsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedJsonProperty" Message="Unsupported property or properties 'units', 'enableAutomaticUnitAdjustment'"
```

- What did you expect or want to happen?
a data catalog to be provisioned
- How can we reproduce it?
i presume attempt to provision a catalog via the API
- Anything we should know about your environment.

Using a service principal

**Comment by katbyte** [comment]
I presume this is because i am using a service pricipal, logging in with the CLI and using that auth method seems to work. The error message should state as much rather then the unhelpful one returned.

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT do you have any clue about this?

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang I think you'll need to loop in somebody from the data catalog team to help investigate.

**Comment by ingave** [comment]
This is not a supported SDK, we never published SDK for Azure Data Catalog.

**Comment by ArcturusZhang** [comment]
> This is not a supported SDK, we never published SDK for Azure Data Catalog.

There is a [rest api spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datacatalog/resource-manager/Microsoft.DataCatalog/stable/2016-03-30/datacatalog.json) published for data catalog, which means there will be a corresponding SDK generated.
I suppose in this bug report, `Service returned an error` may means something is wrong on the service side. Please have a look.

**Comment by ingave** [comment]
ARM templates for creating Catalogs are not supported. There's no RST API SDK that is officially supported by MS.
