### ISSUE TITLE
DataCatalog SDK does not update admins/users & object has invalid & mis named properties

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#5915]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`github.com/Azure/azure-sdk-for-go/services/datacatalog/mgmt/2016-03-30/datacatalog`
- SDK version e.g. `master`, `latest`, `18.1.0`
`github.com/Azure/azure-sdk-for-go v33.2.0+incompatible ``
- output of `go version`
`go version go1.12.6 darwin/amd64`

- What happened?
When provisioning a data catalog some of the properties are invalid & misnamed:
```Error: datacatalog.ADCCatalogsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedJsonProperty" Message="Unsupported property or properties 'units', 'enableAutomaticUnitAdjustment'"```

This happens on creation or update when either of those properties are set. Looking at the json returned from the API it looks like units is missing and `enableAutomaticUnitAdjustment` is actually `enableAutomaticBillingUnitAdjustment`.

Additionally when trying to supply users or admins the API seems to ignore the properties entirely:

request:
```{
	"location": "westeurope",
	"properties": {
		"sku": "Free",
		"admins": [{
			"upn": "",
			"objectId": "534e0ea7-a6e7-4dc4-8436-79975fd6600b"
		}],
		"users": [{
			"upn": "",
			"objectId": "534e0ea7-a6e7-4dc4-8436-79975fd6600b"
		}]
	},
	"tags": {}
}
```

response:
```
{
	"id": "/subscriptions/NOPE/resourceGroups/acctestRG-kt20191028/providers/Microsoft.DataCatalog/catalogs/acctest-DC-kt20191028",
	"name": "acctest-DC-kt20191028",
	"type": "Microsoft.DataCatalog/catalogs",
	"location": "westeurope",
	"tags": {},
	"properties": {
		"sku": "Free",
		"admins": [],
		"provisioningState": "Succeeded",
		"enableAutomaticBillingUnitAdjustment": false,
		"users": []
	}
}
```

This happens with UPNs, one user, one admin, multiple, and on creation or update.

url:  `https://management.azure.com/subscriptions/REDACTED/resourceGroups/acctestRG-190927000326307213/providers/Microsoft.DataCatalog/catalogs/acctest-DC-190927000326307213?api-version=2016-03-30`

- What did you expect or want to happen?
the propeties not to be invalid / the users updated.

- How can we reproduce it?
see above

- Anything we should know about your environment.

**Comment by ingave** [comment]
This is not a supported SDK, we never published SDK for Azure Data Catalog.

**Comment by katbyte** [comment]
@ingave,

This is an official Azure SDK built from the published rest API specs. Nonetheless the error here i presume is from the specs used to generate this SDK not matching what the API actually expects.

**Comment by ingave** [comment]
This is not SDK we own
