### ISSUE TITLE
Tenant ID is nil for subscriptions

### ISSUE THREAD

**Issue by shhsu** [Azure/azure-sdk-for-go#592]
Hi

This is regarding subscriptions api. It seems that all the subscriptions has nil as its tenant ID, I.E

```
client := subscriptions.NewClient()
client.Authorizer = &azToken
subs, _ := client.List()
subsArray := *subs.Value
for _, sub := range subsArray {
    // *sub.TenantID == nil !?
}

```

**Comment by mcardosos** [comment]
Hello @shhsu !
I looked into how the response body looks like and yes, TenantID was not included.
@tfitzmac @vivsriaus Is there something we are mising here?

**Comment by shhsu** [comment]
Actually I think it is expected according to what the REST api returns.

Should we somehow fix this or communicate this in our documentation?

**Comment by mcardosos** [comment]
If this is the expected result in all calls, then the swagger should be updated. Creating issue in the swaggers repo...

**Comment by shhsu** [comment]
Not sure about the full context of why this filed is there and always null. Even on the Azure CLI side, it seem to expect that subscription objects not having the tenant id
This following code actually appends a tenant id to the subscription object that it returns.
https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/_profile.py#L453

**Comment by mcardosos** [comment]
Hello @shhsu :D
The subscriptions swagger has been modified so it does not include the tenantID in the subscription model. This value is never returned.
Will this be included in the next SDK version @marstr  ?

**Comment by marstr** [comment]
@mcardosos, it should be! I'll make sure to check for it when we generate.
