### ISSUE TITLE
Unmarshalling error when calling `Generatevpnclientpackage` method in virtual network gateway

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-go#5921]
### Bug Report

An error is raised when calling go SDK corresponding to [rest api](https://docs.microsoft.com/en-us/rest/api/network-gateway/virtualnetworkgateways/generatevpnclientpackage)
```
Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type network.String' JSON = '"https://nfvprodsuppdm.blob.core.windows.net/vpnprofileimmutable/subsID/amd64/22f9be10-50ad-417b-9abc-a584fb573706/ecbc0075-bf85-48a8-90a9-de14d9cff51f.exe?sv=2017-04-17&sr=b&sig=%2B4Nnj0DKEeLsyGnMKgvetHpT3vvbn%2BfUztafqcBvoOA%3D&st=2019-09-29T08%3A26%3A04Z&se=2019-09-29T09%3A26%3A04Z&sp=r&fileExtension=.exe"'
```
Note that the response of this api is string instead of json, but in [go SDK](https://github.com/Azure/azure-sdk-for-go/blob/088b4d484d58bba14d62f1de59a49272aecf7845/services/network/mgmt/2019-06-01/network/virtualnetworkgateways.go#L276), it is unmarshalling this response by calling autorest.ByUnmarshallingJSON.

**Comment by ArcturusZhang** [comment]
@jhendrixMSFT is this bug related with code gen? Thanks

**Comment by jhendrixMSFT** [comment]
Per internal discussion the REST endpoint should be returning the value as a JSON object.
```json
{
    "value": "<theValue>"
}
```
Long-term the REST endpoint should be updated to conform to this requirement.
I don't have a good short-term solution for this as autorest assumes request/response bodies are valid JSON objects.

**Comment by jhendrixMSFT** [comment]
One option for this broken operation is to set the `produces` section to `text/plain` for this specific operation ID.  I don't know if all generators support this though.

**Comment by sfiguemsft** [comment]
@anzaman can you look into this please?

**Comment by ArcturusZhang** [comment]
> One option for this broken operation is to set the `produces` section to `text/plain` for this specific operation ID. I don't know if all generators support this though.

There is a workaround we are using, that we take over the part of response handling.
@njuCZ could you please share something about your workaround on this issue?

**Comment by KarenHammons** [comment]
@ArcturusZhang is this still persistent?  Haven't seen an update on the workaround from @njuCZ

**Comment by njuCZ** [comment]
@KarenHammons the workaround is rewite the `future.Result` method
```
func getResult(client network.VirtualNetworkGatewaysClient, future network.VirtualNetworkGatewaysGeneratevpnclientpackageFuture) (str string, err error) {
	var done bool
	done, err = future.DoneWithContext(context.Background(), client)
	if err != nil {
		err = autorest.NewErrorWithError(err, "network.VirtualNetworkGatewaysGeneratevpnclientpackageFuture", "Result", future.Response(), "Polling failure")
		return
	}
	if !done {
		err = autorestAzure.NewAsyncOpIncompleteError("network.VirtualNetworkGatewaysGeneratevpnclientpackageFuture")
		return
	}
	sender := autorest.DecorateSender(client, autorest.DoRetryForStatusCodes(client.RetryAttempts, client.RetryDuration, autorest.StatusCodesForRetry...))
	var s network.String
	if s.Response.Response, err = future.GetResult(sender); err == nil && s.Response.Response.StatusCode != http.StatusNoContent {
		str, err = generatevpnclientpackageResponder(client, s.Response.Response)
		if err != nil {
			err = autorest.NewErrorWithError(err, "network.VirtualNetworkGatewaysGeneratevpnclientpackageFuture", "Result", s.Response.Response, "Failure responding to request")
		}
	}
	return
}

func generatevpnclientpackageResponder(client network.VirtualNetworkGatewaysClient, resp *http.Response) (result string, err error) {
	byteArr := make([]byte, 1024)
	err = autorest.Respond(
		resp,
		client.ByInspecting(),
		autorestAzure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusAccepted),
		autorest.ByUnmarshallingBytes(&byteArr),
		autorest.ByClosing())
	result = string(byteArr)
	return
}
```

**Comment by aristosvo** [comment]
What's the status here, when can we expect this to be fixed? 

This bug is open for more than half a year and affects both `Generatevpnclientpackage` and `GetvpnprofilepackageURL` operations.

**Comment by KarlRanseier** [comment]
Any news here?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

The code generator has been fixed, I'll defer to @ArcturusZhang about when the next release with this fix will happen.

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang I believe this has been resolved?
