### ISSUE TITLE
Regenerate the Service Bus SDK

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#593]
👋 hey Azure SDK for Go team!

I've been going through trying to upgrade us to v9 of the SDK - and noticed a blocker 😞

When previously dry-running the SDK upgrade - I'd commented out a breaking change in the Service Bus SDK, where the Location field has been removed from the Response models. Unfortunately this meant that I'd only reported 1 of the 2 issues with the Service Bus SDK, which means we're currently unable to upgrade to v9 of the Azure SDK for Go 😞 

I was hoping that we may be able to work around this by not posting the Location field at Creation/Update time - but unfortunately it's a required field. I've opened a PR to [the Rest API Specs Repository which fixes this](https://github.com/Azure/azure-rest-api-specs/pull/1138) - once this is merged, would it be possible to re-generate and re-release the SDK?

Could we also add this to [the list of breaking changes](https://github.com/Azure/azure-sdk-for-go/pull/569#issuecomment-285460597) in v9 too until this is resolved?

Thanks!

**Comment by marstr** [comment]
Thanks for taking care of submitting a PR the API Specs Repo! Given that this is strictly additive to what exists in v9, we may as well add it in as a v9.1.0. We're going to turn our sights to v10 shortly, but given how useful it would be to v9 to have this added back in, we'll try to include it in both.

**Comment by stack72** [comment]
Hi @marstr 

Is there any ETA on 9.1? We are currently waiting on it to support web_apps in terraform

Thanks

Paul

**Comment by tombuildsstuff** [comment]
@marstr I'm not sure if it's helpful or going to cause a ton of pain with the v10 release - but I had some spare time tonight and ended up attempting this in #601 :)

**Comment by mcardosos** [comment]
Fixed!
