### ISSUE TITLE
local error: tls: no renegotiation

### ISSUE THREAD

**Issue by yamaszone** [Azure/azure-sdk-for-go#5941]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-01-01/apimanagement`
- SDK version: `v34.0.0`
```
dep status "github.com/Azure/azure-sdk-for-go"
PROJECT                            CONSTRAINT  VERSION  REVISION  LATEST   PKGS USED
github.com/Azure/azure-sdk-for-go  ^34.0.0     v34.0.0  8c372e6   v34.0.0  3  
github.com/Azure/go-autorest       v13.0.1     v13.0.1  69b4126   v13.0.1  8  
github.com/dgrijalva/jwt-go        v3.2.0      v3.2.0   06ea103   v3.2.0   1  
github.com/satori/go.uuid          v1.2.0      v1.2.0   f58768c   v1.2.0   1 
```

- output of `go version` `go1.12.4 darwin/amd64`

- What happened?
I have the following env vars configured:
```
export AZURE_TENANT_ID="**********"
export AZURE_CLIENT_ID="**********"
export AZURE_CLIENT_SECRET="**********"
export AZURE_SUBSCRIPTION_ID="*********"
```
I have the following sample code to print the list of API Management Subscriptions for my instance:
```
package main

import (
	"context"
	"fmt"
	_ "github.com/Azure/azure-sdk-for-go"
	apim "github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-01-01/apimanagement"
	"log"
)

func main() {
	sc := apim.NewSubscriptionClientWithBaseURI("https://{foobar}.management.azure-api.net", "{Subscription ID}")
	top := int32(1)
	skip := int32(1)
	result, err := sc.List(
		context.Background(),
		"{resource group}",
		"{service name}",
		"name eq 'somename'",
		&top,
		&skip,
	)

	if err != nil {
		log.Println(err)
	}
	fmt.Println(result)
}
```
When I execute the above code, I am seeing the following error:
```
2019/10/02 16:36:37 apimanagement.SubscriptionClient#List: Failure sending request: StatusCode=0 -- Original Error: Get https://{foobar}.management.azure-api.net/subscriptions/{subscription ID}/resourceGroups/{resource group}/providers/Microsoft.ApiManagement/service/{service name}/subscriptions?%24filter=name+eq+%somename%27&%24skip=1&%24top=1&api-version=2019-01-01: local error: tls: no renegotiation
```
- What did you expect or want to happen?
It should print list of subscriptions for the API Management instance.
- How can we reproduce it?
Follow the steps as in "What happened?" section
- Anything we should know about your environment.
`cat Gopkg.toml`
```
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "34.0.0"

[prune]
  go-tests = true
  unused-packages = true
```

Initially I was trying to use `go mod` for dependency management without realizing that it's [not supported yet](https://github.com/Azure/azure-sdk-for-go#avoiding-breaking-changes).  Then I tried both `dep` and `go get` as per docs resulting in the same outcome. I have also reviewed the following places while looking for fix:
- https://github.com/Azure/go-autorest/issues/384
- https://github.com/golang/go/issues/5742
Both of these issues seem to be already addressed and latest version of the SDK should have those fixes. Unfortunately nothing seemed to work for me.

Thanks in advance for looking into this.

**Comment by maggiepint** [comment]
HI! Thanks for a well written bug report. I'm routing to the proper team for follow-up.

**Comment by solankisamir** [comment]
@jhendrixMSFT  do we have guidance on how to use the Go clients. This customer is trying to hit the wrong endpoint in this client.
He is hitting `https://{foobar}.management.azure-api.net` when he should be hitting `https://management.azure.com` as he is using AAD authentication.

**Comment by jhendrixMSFT** [comment]
@yamaszone you want [NewSubscriptionClient](https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2019-01-01/apimanagement/subscription.go#L35), it will specify the correct URL.

**Comment by yamaszone** [comment]
@jhendrixMSFT Thanks for your reply. With `NewSubscriptionClient`, I am seeing the following error:
```
apimanagement.SubscriptionClient#List: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing."
```
I am trying to use "Client credentials" auth method as documented [here](https://docs.microsoft.com/en-us/azure/go/azure-sdk-go-authorization#use-environment-based-authentication). [NewSubscriptionClient](https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2019-01-01/apimanagement/subscription.go#L35) doesn't seem to have a mechanism to set auth headers and as per docs it should read Client ID and Secrets from the environments. It'd be great if you could send a pointer to a complete sample for "Client credentials" method for API Management.

**Comment by solankisamir** [comment]
@yamaszone have you tried the Azure Samples repo for the pattern. This might help
`https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/network/ipaddress.go`

**Comment by jhendrixMSFT** [comment]
@yamaszone Please also see the Authorization section in the README https://github.com/azure/azure-sdk-for-go#authentication

**Comment by yamaszone** [comment]
@jhendrixMSFT Thanks for the pointer. I did try it previously but it didn't work because of hitting incorrect URL. I was switching between SAS auth (which needed FQDN) and Client credentials auth and overlooked the endpoint difference. I re-attempted it and it works! I wish the error message for bad URL was more informative instead of just saying `local error: tls: no renegotiation` to help me debugging. 

@jhendrixMSFT @solankisamir thanks both for helping out. I am going to close this issue.
