### ISSUE TITLE
Panic String in GoLang API (Azure)

### ISSUE THREAD

**Issue by JacksonSanders** [Azure/azure-sdk-for-go#5956]
This bug causes a panic in our code and is stopping us from listing out all the instances in a VMSS.  We need this ability in order to find and start deallocated machines.  
 
Here's a code snippet that causes the panic:
    client := compute.NewVirtualMachineScaleSetVMsClient(subscriptionID)

    res, err := client.List(ctx, group, vmss,
        "startswith(instanceView/statuses/code, 'PowerState') eq true",
        "instanceView/statuses",
        "")
    if err != nil {
        panic(err)
    }
 
Here's the panic string
 
panic: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field VirtualMachineScaleSetVMListResult.value of type string' JSON = '{
 
Can you help me figure out where to file this bug and or find someone who could help us confirm that it is a bug in the Azure Golang SDK and figure out a workaround or get it fixed ASAP?

**Comment by ArcturusZhang** [comment]
Hi @JacksonSanders 
usually the roor cause of these kind of unmarshalling error lies on the service side. But in this case, it is very peculiar that the struct VirtualMachineScaleSetVMListResult does not have a field of `value` (small v) as the error you posted, but it has a field of `Value` with type of an array (not string). 
And I notice the error message you posted is not complete, would please post the rest part of the error message?

**Comment by ArcturusZhang** [comment]
Closed due to no response from the author.
Please feel free to leave a comment to notice me if anything new you want to add, and I will reopen this issue then. Thanks
