### ISSUE TITLE
Service Principal Create for RBAC

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-go#596]
Creating a service principal and authentication are fraught with difficulty using the SDK. Service Principals and AAD applications are core pieces of functionality when using Azure for non-trivial automation scenarios. It would be helpful to provide higher level abstractions such as what is currently done in the Azure CLI with `az ad sp create-for-rbac`. See: https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py#L500-L632.

`az ad create-for-rbac` goes through multiple retry loops to ensure creation of the AAD application, service principal and Azure role based authorization resources. It is non-trivial for a developer to implement this logic and should not be left as an exercise to the reader.

See also: https://bugs.launchpad.net/juju/+bug/1680523

Please consider creating abstractions for common AAD / Azure identity scenarios.

**Comment by joshgav** [comment]
related: https://github.com/Azure/azure-rest-api-specs/issues/2135

That's probably why `az ad sp create-for-rbac` does retries when choosing a role definition.

@devigned would this be a good candidate for a sample?

**Comment by devigned** [comment]
@joshgav it would be a candidate for a sample, which would be moderately helpful. 

I think wrapping the API call in a retry handler or creating higher level methods, which combine these API calls and retries would be more helpful.

**Comment by joshgav** [comment]
Hi @devigned - We now offer the following samples on creating and assigning roles to a service principal:

* How to create a service principal programatically: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/graphrbac/graph.go
* How to assign roles to that principal: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/authorization/auth.go

If there are scenarios these samples don't meet could you open a specific issue? Thanks!

**Comment by jbw976** [comment]
Just a note for future users, the second link from the [previous comment](https://github.com/Azure/azure-sdk-for-go/issues/596#issuecomment-392813961) from @joshgav looks to have been moved to https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/authorization/authorization.go.
