### ISSUE TITLE
Support Custom CA Certificate Chain

### ISSUE THREAD

**Issue by danieladams456** [Azure/azure-sdk-for-go#5974]
### Feature Request
I am trying to use the Azure AD Terraform provider, but seemed like here would be a better place to file a request.

I am behind a corporate proxy that does SSL interception.  For AWS Terraform provider, I set `AWS_CA_BUNDLE` environment variable to override the certificate verification process.  I am not finding an analog for Azure go SDK.  The CLI works since I am setting `REQUESTS_CA_BUNDLE` for python.

Potentially related issues:
- #1435
- [golang mac certs](https://github.com/golang/go/issues/24652)

**Comment by maggiepint** [comment]
Thanks for the feedback! @mozehgir can you help get this routed?

**Comment by mybayern1974** [comment]
Hi @danieladams456 , could you please provide the full chain of your Az CLI calling, covering all involved CLI cmd and parameters?

**Comment by danieladams456** [comment]
I'm using the [azure ad terraform provider](https://github.com/terraform-providers/terraform-provider-azuread).  I figured the Go SDK would be the better place to file an issue for alternate CA support since it didn't seem to be currently supported at this level.

**Comment by lirenhe** [comment]
@jhendrixMSFT, do we already support this?

**Comment by danieladams456** [comment]
If I remember correctly, it turned out to be an issue in the keychain trust settings of one of the certs.  Sorry I forgot to close this.  Thanks!

**Comment by tullydwyer** [comment]
Do you remember which environment variable you used @danieladams456 ?

I am having issues setting a custom CA for Terraform Azure Provider. I have `REQUESTS_CA_BUNDLE` set for the Azure CLI and the CLI works. But Terraform gives SSL errors.
