### ISSUE TITLE
Redis Cache Premium: Backups

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#598]
👋 hey!

An issue's been opened on the Terraform repository to [add support for Backup Settings on a Premium Redis Cache](https://github.com/hashicorp/terraform/issues/14016) instance.

Taking a quick look at the Redis SDK - I can't see it in either v8 or v9 (which appear to be using the same API version `2016-04-01`) - would it be possible to add functionality for this in a future version?

Thanks :)

**Comment by marstr** [comment]
@TimLovellSmith,

Do you have any insights on whether or not the above is exposed via REST? We were looking at [the Swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json#L966) and suspect that this is covered, but want you to verify.

**Comment by marstr** [comment]
Alright, I'm going to go ahead and assume that the Swagger mentioned above is accurate, and that is the mechanism for configuring Redis instances is exposed via our [SDK here](https://github.com/Azure/azure-sdk-for-go/blob/eb9eddfb7d680dca671221dba9e47626dd5fb464/arm/redis/models.go#L114). Now that said, to my knowledge we've never tested this scenario where we have an object of type string in swagger.

**Comment by marstr** [comment]
To follow up, I'll try to create a Redis instances with some configuration passed through our SDK. If this fails for syntactic reasons, I'll have to reach out to other generators to see what they do. If it doesn't work anywhere, we can probably get away with changing the Swagger without it being a breaking change. (You can't break what never worked!)

**Comment by TimLovellSmith** [comment]
@marstr @tombuildsstuff 
It is intended to be possible via the 'redisConfiguration' property of the redis cache:

See the note on https://docs.microsoft.com/en-us/rest/api/redis/redis

"Few possible keys: **rdb-backup-enabled**,**rdb-storage-connection-string**,**rdb-backup-frequency**,maxmemory-delta,maxmemory-policy,notify-keyspace-events,maxmemory-samples,slowlog-log-slower-than,slowlog-max-len,list-max-ziplist-entries,list-max-ziplist-value,hash-max-ziplist-entries,hash-max-ziplist-value,set-max-intset-entries,zset-max-ziplist-entries,zset-max-ziplist-value etc."

Hope this helps!
Tim

**Comment by tombuildsstuff** [comment]
Hey @TimLovellSmith / @marstr

Thanks for confirming that - at this point we're explicitly defining the keys in the `redisConfiguration` object - so I'll update this to include the missing values. As such I'll close this issue for the moment - and re-open it if there's any issues :)

Thanks! :)
