### ISSUE TITLE
too many arguments to return have (string) want ()

### ISSUE THREAD

**Issue by manya0393** [Azure/azure-sdk-for-go#5985]
when try to run the terraform command to execute terraform code through GOLANG and want to return the id of the resource from the function and use it in other function. Kindly get through the code i am using.

func TestTerraformDataFactory(t *testing.T) {

terraformOptions := &terraform.Options{
	TerraformDir: *terraformDir ,
	VarFiles: []string{*varFiles},
}
terraform.InitAndApply(t, terraformOptions)
id := terraform.Output(t, terraformOptions, "id")
return id
}

func getDiagnosticSettings() insights.DiagnosticSettingsResource {
ctx := context.Background()
diagsettingsClient:= getDiagsettingsClient()
id := TestTerraformDataFactory()
diagnosticSettings, _ := diagsettingsClient.Get(ctx, id, *diagSettingsName)
return diagnosticSettings
}

**Comment by maggiepint** [comment]
@mozehgir

**Comment by ArcturusZhang** [comment]
Hi @manya0393 I do not quite get your point. But should this issue belong to terraform rather than go sdk? 
In addition, I suppose the code snippet you gave cannot compile. You have a function `func TestTerraformDataFactory(t *testing.T)` but called it as `id := TestTerraformDataFactory()`.
