### ISSUE TITLE
devspaces API `host_suffix` property is ignored in API version `2019-04-01`

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#5990]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
works in: `github.com/Azure/azure-sdk-for-go/services/preview/devspaces/mgmt/2018-06-01-preview/devspaces`
breaks in: `github.com/Azure/azure-sdk-for-go/services/devspaces/mgmt/2019-04-01/devspaces`

- SDK version e.g. `master`, `latest`, `18.1.0`
```
[17:09:43] kt@snowbook:~/hashi/tf/azure/azurerm▸feature/azure-bastion-host$ cat go.mod | egrep -i azure
module github.com/terraform-providers/terraform-provider-azurerm
	github.com/Azure/azure-sdk-for-go v33.2.0+incompatible
	github.com/Azure/go-autorest/autorest v0.9.0
	github.com/Azure/go-autorest/autorest/date v0.2.0
```

- output of `go version`
`go version go1.13.1 darwin/amd64`

- What happened?
in `github.com/Azure/azure-sdk-for-go/services/preview/devspaces/mgmt/2018-06-01-preview/devspaces` the `host_suffix` was user settable. We upgraded to `github.com/Azure/azure-sdk-for-go/services/devspaces/mgmt/2019-04-01/devspaces` and it doesn't appear to beable to be set anymore as a random FQDN is returned.

```
testing.go:568: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        DESTROY/CREATE: azurerm_devspace_controller.test
          data_plane_fqdn:                          "azds-d4a0111e-cb75-45e2-9b14-424a2874f154.weu.azds.io" => "<computed>"
          host_suffix:                              "rwxnnlkqxm.weu.azds.io" => "suffix" (forces new resource)
```

- What did you expect or want to happen?
the host suffix set?

- How can we reproduce it?
try and set the host suffix

- Anything we should know about your environment.

Please refer to https://github.com/terraform-providers/terraform-provider-azurerm/pull/4288 for more details

**Comment by maggiepint** [comment]
Thanks for the feedback - I have routed to the appropriate team for follow up.

**Comment by ArcturusZhang** [comment]
Hi @katbyte according to the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/b5c5da5888eb6ae81108161be58c88b583197d2a/specification/devspaces/resource-manager/Microsoft.DevSpaces/stable/2019-04-01/devspaces.json#L576) of devspaces, the hostSuffix is labeled of `readOnly: true` now, which indicates it is managed by azure now rather than user-provided.

**Comment by katbyte** [comment]
thanks @ArcturusZhang
