### ISSUE TITLE
Security API version 2019-08-01

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#6021]
### Service Package Request

👋 

We've been asked (offline) if we can migrate to a stable version of the Security API, rather than using the Preview API (2017-08-01-preview) that we're currently using. As a part of [this we've had a PR opened to update Terraform to use API version 2019-08-01](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4509)) - however it appears that most of the resources for this don't exist in this SDK (or the Swagger).

Taking a look at the Swagger it appears that different versions of the Security API offer different functionality - but the API versions aren't additive; thus it's not possible to easily migrate from the older -> newer API versions - which would be fine for a resource which has been removed, but in this instance it appears both are still current? In addition they appear to use a different versioning scheme to the rest of the Resource Provider SDK's for some reason?

Would it be possible for someone to confirm if the API's are additive, rather than outright replacing each other; so that we're able to determine a path forward onto the stable API version here? One example of this is the Advanced Protection Client [which appears to only be available in API version 2017-08-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/4129dd8c164fa325baf97d998673b3dd85b1d6d6/specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/advancedThreatProtectionSettings.json).

Downstream issue in Terraform: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4509

Thanks!

**Comment by tombuildsstuff** [comment]
@loarabia is there any update available here? :)

**Comment by loarabia** [comment]
@tombuildsstuff let me ping the team on email.

**Comment by chlahav** [comment]
hi @tombuildsstuff,
The API is indeed additive and the last API version of each type should be used.
we will keep this behavior in the future, but we're going to reduce the number of versions that we use (currently we are aligning towards "2019-01-01-preview" and "2019-01-01")

you can follow the latest composite to see the most current subset of types and versions (currently it is [package-composite-v3](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/readme.md#tag-package-composite-v3))

**Comment by ArcturusZhang** [comment]
Hi @tombuildsstuff does switching from `security/v1.0` to `security/v3.0` work? If so, I will close this issue.
