### ISSUE TITLE
Race Condition in File.WriteRange

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#605]
Original text here https://github.com/Azure/azure-storage-go/issues/39
@MarkSonghurst says:

> I call File.WriteRange within a Go routine for each 4MB chunk in a file I'm uploading.
I get a race condition warning reported by go test --race

>```
>==================
>WARNING: DATA RACE
>Write at 0x00c4200da738 by goroutine 27:
>  bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure-storage-go.(*File).updateEtagAndLastModified()
>      /home/msonghurst/go/src/bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure->storage-go/file.go:362 +0xf5
>  bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure-storage-go.(*File).WriteRange()
>      /home/msonghurst/go/src/bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure->storage-go/file.go:410 +0xdd
>  bitbucket.org/scanimal/caspianbhs/azure.(*Azure).PushImages.func1()
>      bitbucket.org/scanimal/caspianbhs/azure/_test/_obj_test/azure.go:119 +0x131
>Previous write at 0x00c4200da738 by goroutine 20:
>  bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure-storage-go.(*File).updateEtagAndLastModified()
>      /home/msonghurst/go/src/bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure->storage-go/file.go:362 +0xf5
>  bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure-storage-go.(*File).WriteRange()
>      /home/msonghurst/go/src/bitbucket.org/scanimal/caspianbhs/vendor/github.com/Azure/azure->storage-go/file.go:410 +0xdd
>  bitbucket.org/scanimal/caspianbhs/azure.(*Azure).PushImages.func1()
>      bitbucket.org/scanimal/caspianbhs/azure/_test/_obj_test/azure.go:119 +0x131
>```

>I think you need a mutex (or better still, use channels) in here:

>```
>// updates Etag and last modified date
>func (f *File) updateEtagAndLastModified(headers http.Header) {
>	f.Properties.Etag = headers.Get("Etag")
>	f.Properties.LastModified = headers.Get("Last-Modified")
>}
>```
>If the concept of using File.WriteRange concurrently is not acceptable, please update the documentation.
>Thank you.

**Comment by jhendrixMSFT** [comment]
Resolved in https://github.com/Azure/azure-sdk-for-go/pull/701.
