### ISSUE TITLE
InvalidApiVersionParameter - 2018-09-30

### ISSUE THREAD

**Issue by thanasisk** [Azure/azure-sdk-for-go#6082]
### Bug Report

Azure-SDK-via kubernetes

my team checked 4 kubernetes releases: 1.13.12, 1.14.7, 1.14.8, 1.15.5. All of them use incompatible azure api calls (vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute/disks.go):

> // CreateOrUpdatePreparer prepares the CreateOrUpdate request.
> func (client DisksClient) CreateOrUpdatePreparer(ctx context.Context, resourceGroupName        string, diskName string, disk Disk) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"diskName":          autorest.Encode("path", diskName),
		"resourceGroupName": autorest.Encode("path", resourceGroupName),
		"subscriptionId":    autorest.Encode("path", client.SubscriptionID),
	}
	const APIVersion = "2018-09-30"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}
	preparer := autorest.CreatePreparer(
		autorest.AsContentType("application/json; charset=utf-8"),
		autorest.AsPut(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/disks/{diskName}", pathParameters),
		autorest.WithJSON(disk),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}`

- What happened?
Failure to provision volume
`
2m         Warning   ProvisioningFailed          PersistentVolumeClaim   Failed to provision volume with StorageClass "azure-storage-class": compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidApiVersionParameter" Message="The api-version '2018-09-30' is invalid. The supported versions are '2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
`
- What did you expect or want to happen?
Volume to be provisioned normally - API version to be accepted
- How can we reproduce it?
create and describe a kubectl describe pvc (a PVC of your liking)
using the following Storage Class:
>
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: "" 
  resourceGroup: "" 
  fsType: ext4
>
- Anything we should know about your environment.
Self-hosted k8s on Azure (1.14.8 - 1.13.11)

**Comment by thanasisk** [comment]
https://github.com/kubernetes/kubernetes/commit/4fbdb08f98946be4a1277f59a32ab92b74670abe#diff-96b1e3f28bae5519329faeac2defcc8d

**Comment by thanasisk** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.14/vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute/disks.go#L87

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT do you have any insight about this? I suppose we may need more knowledge about how this [code](https://github.com/kubernetes/kubernetes/blob/release-1.14/vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute/disks.go#L87) is generated

**Comment by thanasisk** [comment]
Here is the root cause for this on our side. In azure.json we did NOT specify resourceGroup and location. So when the API request was formed, the resourceGroupName was not present. I assume this request got routed to a different API for which the version was not valid.

**Comment by jhendrixMSFT** [comment]
@thanasisk thanks for the info, does this mean the issue is resolved?

**Comment by thanasisk** [comment]
From our side yes, however, a bit more expressive error messages would have gone a long way to help us. In any case, please consider the issue resolved.

**Comment by ArcturusZhang** [comment]
Happy to see this get resolved!
