### ISSUE TITLE
Regenerate the Event Hubs SDK

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#610]
:wave: Happy Monday!

I've opened a PR to [Rest API Specs](https://github.com/Azure/azure-rest-api-specs/pull/1199) which adds the Location field back to the Event Hub SDK Response. Turns out this field's mandatory - so the Event Hubs functionality in v10 currently doesn't work for us :(

I felt adventurous, so I've regenerated the SDK in anticipation of that change being merged, and bumped everything but KeyVault and DataPlane to 10.0.1, which gave errors in AutoRest for me (¯\_(ツ)_/¯) but I'll open a PR shortly.. :)

Would it be possible to regenerate this once the change has been merged?

Thanks!

**Comment by marstr** [comment]
Thanks for doing this Tom! Joel is going to finish up getting the new tag on this release shortly.

**Comment by jhendrixMSFT** [comment]
v10.0.1-beta release has been created and tagged.

**Comment by tombuildsstuff** [comment]
Awesome! Thanks both :)

**Comment by tombuildsstuff** [comment]
@marstr @jhendrixMSFT just tried to upgrade to 10.0.1, but it appears that the release was done from the master branch, whereas I the PR was sent the `dev` branch :(

Sorry to be a pain here, but would it be possible to re-release with these changes included?
Thanks!

**Comment by jhendrixMSFT** [comment]
Epic fail on my part, will fix...

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff I've released v10.0.2 that contains the fix (for real this time :)).  Sorry for the hassle.
