### ISSUE TITLE
Accept a timeout parameter for Get calls

### ISSUE THREAD

**Issue by edevil** [Azure/azure-sdk-for-go#612]
It would be great if we could specify how long we are willing to wait for Get() calls on the *Clients. Specifically:

VirtualMachinesClient.Get()
RouteTablesClient.Get()
SecurityGroupsClient.Get()
LoadBalancerClient.Get()
PublicIPAddressesClient.Get()
SubnetsClient.Get()

These methods are used by the Kubernetes Azure Cloudprovider and it is important to be able to have a timeout since they are used on a status hook. Thanks.

**Comment by marstr** [comment]
This is a really awesome idea, and it's something that we're pondering for all of our operations, not just Get. For instance, at the moment long running operations take a `<-chan struct{}` for cancellation, but we could change that up and have a `context.Context` on all of our operations. Any solution that we come up with there will absolutely cover `Get` operations.

Thanks for bringing this up! It's important to hear people back up our concerns!
