### ISSUE TITLE
`resources` package(s) needs attention / how to use Subscriptions client?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#616]
RE:
https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/subscriptions in particular "TenantsClient"

* Huh? What is this trying to say here:  `TenantsClient is the all resource groups and resources exist within subscriptions. These operation enable you get information about your subscriptions and tenants` How is it meant to be used? Is this supposed to help me determine the list of available tenants for my authenticated user? How do I get it for a specific subscription using this client?

* Where is NewSubscriptionsClient in here? What is `NewGroupClient`? etc?

**Comment by colemickens** [comment]
The `NewGroupClient` has the exact same confusing description as `NewTenantClient`:

`GroupClient is the all resource groups and resources exist within subscriptions. These operation enable you get information about your subscriptions and tenants. A tenant is a dedicated instance of Azure Active Directory (Azure AD) for your organization.`

And I'm still unclear on what client (is there one?) I should be using to hit the subscriptions endpoint?

**Comment by marstr** [comment]
There's a lot of good feedback to unpack here! There are a few action-items that we can get started on:
- The descriptions in the Azure/azure-rest-api-specs repo (specifically in the resources/subscriptions directory) need another look.
- The generator needs to be evaluated to ensure that we're not confusing things further.
- We should add a sample on fetching resources.

**Comment by jhendrixMSFT** [comment]
Fixed by @mcardosos
