### ISSUE TITLE
fetching kubernetes api version and kubeconfig

### ISSUE THREAD

**Issue by jchauncey** [Azure/azure-sdk-for-go#617]
I need a way to get the kube api version and the kubeconfig of a running container service using the kubernetes orchestrator. Is that possible?

**Comment by marstr** [comment]
@colemickens do you happen to have any insights here?

**Comment by jchauncey** [comment]
Alright so @colemickens replied to my email and said this was not supported yet. Is this something that would be possible to add? (I'm assuming its possible to fetch this information because the az cli can already get this information)

**Comment by colemickens** [comment]
The information is simply not available in the API period...

**Comment by jchauncey** [comment]
dang well time for plan b =)
