### ISSUE TITLE
VirtualMachinesClient.ListAll statusOnly parameter behavior.

### ISSUE THREAD

**Issue by wojtii** [Azure/azure-sdk-for-go#6206]
### Bug Report

- import path of package `../services/compute/mgmt/2019-07-01/compute`
- SDK version `v35.0.0` (via go modules)
- output of `go version` `go version go1.13 darwin/amd64`

- What happened?
I have used the new parameter `statusOnly string` with value `"true"` in this function: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute#VirtualMachinesClient.ListAll and the program froze.

- What did you expect or want to happen?
I would like to list all my vms with their runtime statuses, similar to azure cli: `az vm list -d`.
Also I would be happy if the documentation would be more specific about what parameters can be passed in statusOnly string and call with wrong parameter should return error instead of freezing.

- How can we reproduce it?
```
vmClient := compute.NewVirtualMachinesClient(subscriptionID)
res, err := vmClient.ListAll(ctx, "true")
```
If 
```
ctx = context.Background()
```
then program is freezing.

If
```
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
defer cancel()
```
then err contains:
```
compute.VirtualMachinesClient#ListAll: Failure sending request: StatusCode=502 -- Original Error: context deadline exceeded
```
When i use empty string in `statusOnly` it works.
```
res, err := vmClient.ListAll(ctx, "")
```

- Anything we should know about your environment.
I think that I have shared enough information about my environment but I am happy to share more if it is going to help.
Thanks

**Comment by ArcturusZhang** [comment]
@wojtii Thanks for the issue!

This should be a service bug. I tried to use rest api `ListAll`, when there is not query parameter `statusOnly`, everything is fine. The request URI is 
```
https://management.azure.com/subscriptions/<subsID>/providers/Microsoft.Compute/virtualMachines?api-version=2019-07-01
```
When I add `statusOnly` query parameters, the service returns an error. The request URI is
```
https://management.azure.com/subscriptions/<subsID>/providers/Microsoft.Compute/virtualMachines?api-version=2019-07-01&statusOnly=true
```
The response is
```
{
    "error": {
        "code": "ProviderError",
        "message": "Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'."
    }
}
```

I have tagged this issue so the service team will have a look at this.

**Comment by Drewm3** [comment]
I believe the documentation for the statusOnly functionality was published before the service APIs were actually ready. Let me double check this and get back.

**Comment by Drewm3** [comment]
@wojtii, I was able to confirm that this flag is something that is coming soon, but not available publicly yet. I'll update this thread once the feature is enabled for public usage.

**Comment by wojtii** [comment]
Okay, thanks for help 👍

**Comment by dhimannext** [comment]
you should select **none** in Body tab.....if you are hitting through **postman**

**Comment by MinRam** [comment]
It is property because you added the body parameter to the "get" restful request.

The wrong invoke of powershell

```powershell
$body = @{}
Invoke-RestRequest -Method Get  -Uri $uri -Headers $headers -Body $body

```
