### ISSUE TITLE
When azure-sdk-for-go could turn from beta to stable

### ISSUE THREAD

**Issue by poohsleep** [Azure/azure-sdk-for-go#623]
Our project couldn't be compiled correctly due to azure-sdk-for-go's frequent change.
https://github.com/MindFlavor/ftpserver2

Currently we're about to change our code to meet with the latest azure-sdk-for-go/storage.
However it would to lovely to know when we could get a stable version so that we could avoid these kind of change in the future.

**Comment by marstr** [comment]
Howdy @poohsleep,

We don't have an exact timeline yet, but we're planning on removing the beta tag and being more stable this summer.

The main features that we'd like to finish before we remove the beta tag are:
 - Modifying the package structure that the generator produces to truly support all multiple API Versions of an operation group.
 - Generating tests for swaggers to help ensure consistent quality.

In the mean time, we recommend using [glide](https://github.com/Masterminds/glide) to lock yourself to a particular version of our SDK.

Thanks for using the Azure SDK for Go!

Martin
