### ISSUE TITLE
[Feature Request] Deployments Functionality

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#624]
:wave: howdy

I've been meaning to file this bug for _forever_ but never found the time until now..

When viewing a Resource Group in the AzureRM Portal - a Deployments section is visible - which contains the operations created through ARM Template Deployments and through the Portal:

<img width="717" alt="screen shot 2017-05-17 at 11 21 51" src="https://cloud.githubusercontent.com/assets/666005/26149783/7c60b268-3af3-11e7-8a52-110e52773902.png">

However operations performed through the SDK/API aren't visible in this tab :(

Is this functionality only available for ARM Template Deployments - or is there a way that we can integrate with it? I'd assumed that any kind of deployments through the API (by which I mean, calls to the API which modify resources) would appear here automatically?

Thanks!

**Comment by marstr** [comment]
I'm going to have to dig on this a little, but I'll update this thread as I learn more about how the Portal picks up activity and whether or not it is feasible for us to have our activity picked up.

**Comment by ravbhatnagar** [comment]
@tombuildsstuff - The deployment section will show logs from a template deployment only. So if you were to do a template deployment from the SDK, you will see it here. 
You can also go to the Azure Activity Log on the portal to see logs from all operations (deployment or non-deployment). It will show you all the write operations you performed in that Resource group.

**Comment by marstr** [comment]
I believe that @ravbhatnagar confirms that this is a by design thing. Sorry about that, @tombuildsstuff!
