### ISSUE TITLE
keyvault package should use go-uuid instead

### ISSUE THREAD

**Issue by weinong** [Azure/azure-sdk-for-go#625]
I believe https://github.com/satori/go.uuid is the proper package to be imported for keyvault package. Although https://github.com/satori/uuid seems equivalent to go.uuid, we don't want to import the same package in two different names.

**Comment by marstr** [comment]
Did this package get renamed? As far as I can tell, they are one and the same. Is GitHub just redirecting us?

**Comment by marstr** [comment]
It looks like this is going to have to be more of a global change, or else the build system in Go complains. For now, it seems to work to just target "github.com/satori/uuid", Github handles this correctly.

In the long term, I do agree, we should adjust to use the more up-to-date name.

**Comment by marstr** [comment]
I have a PR open to fix this issue in the generator which can be found here:
Azure/autorest#2329

**Comment by marstr** [comment]
Now that the PR above has been merged, I'm going to close this issue. The package name will be fixed the next time we generate an SDK.
