### ISSUE TITLE
containerservice.AgentPoolsClient#CreateOrUpdate force the ManagedClusterAgentPoolProfileProperties.Count  to be set

### ISSUE THREAD

**Issue by djsly** [Azure/azure-sdk-for-go#6271]
### Bug Report

- import path of package in question, e.g. `.../services/containerservice/mgmt/2019-08-01/containerservice`
- SDK version `github.com/Azure/azure-sdk-for-go v35.0.0+incompatible`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
```
Error creating/updating Managed Kubernetes Cluster Agent Pool "linux" (Resource Group "sly3-aks-rg"): containerservice.AgentPoolsClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterAgentPoolProfileProperties.Count constraint=Null value=(*int32)(nil) details: value can not be null; required parameter
```
- What did you expect or want to happen?
Since we have AutoScaler Enabled and min_count / max_count set, why is the ManagedClusterAgentPoolProfileProperties.Count mandatory, 
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by tombuildsstuff** [comment]
PR to fix this: https://github.com/Azure/azure-rest-api-specs/pull/7746

**Comment by djsly** [comment]
thanks @tombuildsstuff, I didn't know about this spec repo and was looking where this definitions was managed!
