### ISSUE TITLE
Create resource group

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#629]
Using the new version of the API, how would you create a resource group?

It appears that `resources.ResourceGroup` no longer exists...

**Comment by marstr** [comment]
Howdy @radu-matei,

A couple of versions ago, there were naming changes introduced by the [Autorest](https://github.com/Azure/autorest) Modeler in an attempt to reduce stuttering. You can work with Resource Groups by using [resources.Group](https://github.com/Azure/azure-sdk-for-go/blob/eb9eddfb7d680dca671221dba9e47626dd5fb464/arm/resources/resources/models.go#L226)

-Martin

**Comment by marstr** [comment]
I'm going to close this issue out for now. If I haven't sufficiently answered your question, feel free to open it up again.

**Comment by radu-matei** [comment]
And still use the `GroupClient`?
