### ISSUE TITLE
VirtualMachinesClient.CreateOrUpdate Failed with Could not find member 'resources' on object of type 'ResourceDefinition'

### ISSUE THREAD

**Issue by z4ce** [Azure/azure-sdk-for-go#630]
We are seeing the error  `The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'` when attempting to create a VM in the same likeness of another VM. See Azure case #117050515698595. 

basically the code looks like:
```
newInstance, err := s.VirtualMachinesClient.Get(s.resourceGroupName, sourceInstanceName, compute.InstanceView)
_, err = s.VirtualMachinesClient.CreateOrUpdate(s.resourceGroupName, *newInstance.Name, *newInstance, nil)
```

For more detail you can view the actual call in the tool at:
https://github.com/pivotal-cf/cliaas/blob/master/iaas/azure/client.go#L150

What we expect:
```
Given: `Azure/azure-sdk-for-go`   version: `088007b3b08cc02b27f2eadfdcd870958460ce7e` 
    and uses APIVersion: `2016-04-30-preview`
    and targeting `East US` location
When: making a call to `VirtualMachinesClient.CreateOrUpdate`
    (https://godoc.org//github.com/Azure/azure-sdk-for-go/arm/compute#VirtualMachinesClient.CreateOrUpdate)
Then: The call to the API completes successfully
```

What happens:
```
Given: `Azure/azure-sdk-for-go`   version: `088007b3b08cc02b27f2eadfdcd870958460ce7e` 
    and uses APIVersion: `2016-04-30-preview`
    and targeting `Canada East` location
When: making a call to `VirtualMachinesClient.CreateOrUpdate`
    (https://godoc.org//github.com/Azure/azure-sdk-for-go/arm/compute#VirtualMachinesClient.CreateOrUpdate)
Then: The call to the API completes unsuccessfully with the following error
`error: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 3603.'."````

**Comment by marstr** [comment]
This issue was discussed internally and the following context was provided:

Tim Basham says:
> We have a customer using Pivotal Cloud Foundry (Manulife) that opened a support request due to hitting an issue with the rest API calls from Go SDK.

He continues to say:
> They are running into an issue with CRP calls in Azure due to the fact that CRP does not support deep puts unless we're doing a template deployment.
Essentially when the Go SDK does a get it needs to prune the resources node/property prior to doing a subsequent put to avoid this issue. ...I have been informed this fix was implemented in Azure Cloud Provider Interface, and Azure Java SDK already, but appears to be missing from Azure Go SDK.

**Comment by z4ce** [comment]
@xchapter7x

**Comment by marstr** [comment]
Howdy folks, we've discussed this in triage and decided the first step is to validate that this is a scenario that is uniquely attributable to the Go SDK. As much as possible, we'd like to solve this in the same way that other languages have. @mcardosos is going to start the investigation off by reaching out to the Ruby SDK folks.

**Comment by mcardosos** [comment]
Hello @z4ce !
I have not been able to repro the very same error message. Quick question, the VM you are trying to copy, does it have extensions installed? I suspect this issue has to do with extensions, but I am still not that sure.

**Comment by z4ce** [comment]
Hi @mcardosos I don't have capability to reproduce, and I think the original microsoft customer lost interest or has workarounds. I'm going to close this issue. I do think it was due to extensions. Thanks for your help!

**Comment by pabowers** [comment]
I have run into this same error when trying to delete disk attachments. I see that the original poster either lost interest, or figured out a work around, but is there a known solution?

**Comment by marstr** [comment]
Hey @pabowers, sorry to hear you're running into trouble. This is an old enough issue that huge swaths of the potential problem have been changed.

I'm going to close this issue out, but please feel free to open a new issue with details specific to your repro.
