### ISSUE TITLE
Error in creating resources

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#632]
This is how I create the client for resource groups:
```
	oAuthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantID)
	if err != nil {
		fmt.Printf(err.Error())
		log.Fatalf("Cannot get oAuth configuration")
	}

	token, err := adal.NewServicePrincipalToken(*oAuthConfig, clientID, clientSecret, azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		fmt.Printf(err.Error())
		log.Fatalf("Cannot get service principal token")
	}

	groupsClient := resources.NewGroupsClient(subscriptionID)
	groupsClient.Authorizer = autorest.NewBearerAuthorizer(token)
```

Then, when I use it:
```
	 resourceGroupParameters := resources.Group{
	 	Location: &location,
	 }
	 _, err := groupsClient.CreateOrUpdate(name, resourceGroupParameters)
	 if err != nil {
	 	fmt.Println(err.Error())
	 }
```

resources.GroupsClient#CreateOrUpdate: Failure preparing request: StatusCode=0 -- Original Error: autorest: No scheme detected in URL

The same happens for the storage and network clients.

(Strangely, this doesn't happen for the VM client)

**Comment by marstr** [comment]
I see you closed this, @radu-matei. Has it been resolved?

**Comment by vsaroopchand** [comment]
I ran into this error recently, in my case I attempted to call an uninitialized client for Storage. Looking at your snippet, I see you initialize groupsClient but without specifying the base url. Try 
resourceGroupsClient := resources.NewGroupsClientWithBaseURI(env.ResourceManagerEndpoint, subscriptionId)  where endpoint is from

env, envErr := azure.EnvironmentFromName("AzurePublicCloud") // change environment name to suite your needs
