### ISSUE TITLE
Add Enrollment Group to Device Provisioning Service

### ISSUE THREAD

**Issue by brunhil** [Azure/azure-sdk-for-go#6336]
### Feature Request

Looking at the REST API for Device Provisioning Service, one can [Create or Update Enrollment Groups](https://docs.microsoft.com/en-us/rest/api/iot-dps/createorupdateenrollmentgroup/createorupdateenrollmentgroup). It would be great to have the latest version of the API supported so that functionality cold be used.

API Version is 2019-03-31

**Comment by jlian** [comment]
@nberdy ?

@brunhil sorry, I don't understand the question. It seems that you've already linked to the relevant REST API? Do you need something else?

**Comment by nberdy** [comment]
I'm not sure either. @brunhil would love to get details about what's missing.

**Comment by brunhil** [comment]
Hi @jlian , the current Go SDK doesn’t seem to support this functionality of the REST API that I’ve linked. Sorry if I wasn’t clear initially.

**Comment by brunhil** [comment]
Looks like there are no REST API Specs for API Version 2019-03-31 in [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable).

Would you like me to create an issue in that repository @nberdy / @jlian ? I can close this one and recreate in that repository if so.

**Comment by jlian** [comment]
I think the 2019-03-31 is the data plane version? @nberdy

**Comment by jlian** [comment]
Do we even have Go SDK for DPS data plane SDK?

**Comment by nberdy** [comment]
@jlian I didn't think we had one for DPS, but it seems this is about a missing REST API/swagger. @gregman-msft for FYI.

@brunhil Could you please file an issue about the lack of REST API spec in the repo you mentioned please?

**Comment by brunhil** [comment]
Created #[7870](https://github.com/Azure/azure-rest-api-specs/issues/7870) in [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs)

**Comment by jlian** [comment]
@nberdy The linked repo [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable) is meant for ARM APIs and therefore control plane only. 

If @brunhil is asking for Create or Update Enrollment Groups in Go, I imagine there are two options 

1. Add this API into control plane and have Go SDKs auto-generated
1. Created a whole Go SDK for DPS data plane APIs

**Comment by brunhil** [comment]
> If @brunhil is asking for Create or Update Enrollment Groups in Go, I imagine there are two options
> 
> 1. Add this API into control plane and have Go SDKs auto-generated
> 2. Created a whole Go SDK for DPS data plane APIs

I specifically need Create/Update/Get/Delete, but it may be easier to capture all possible interactions. I'm hoping to implement basic functionality with Terraform for Enrollment Groups, hence the need for exposure in Go SDK.

**Comment by ArcturusZhang** [comment]
> @nberdy The linked repo [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable) is meant for ARM APIs and therefore control plane only.
> 
> If @brunhil is asking for Create or Update Enrollment Groups in Go, I imagine there are two options
> 
> 1. Add this API into control plane and have Go SDKs auto-generated
> 2. Created a whole Go SDK for DPS data plane APIs

Is there a plan for adding your api into the spec repo? Actually there are plenty of data plane apis in the spec repo already, for instance [eventgrid](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventgrid/data-plane) and [graphrbac](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/graphrbac/data-plane)

**Comment by ArcturusZhang** [comment]
Close this issue since this is not a go specific issue. Please track status of this issue [here](https://github.com/Azure/azure-rest-api-specs/issues/7870) in the spec repo
