### ISSUE TITLE
dns.RecordSetsClient#CreateOrUpdate fails with "The location property is required for this definition."

### ISSUE THREAD

**Issue by ouziel-slama** [Azure/azure-sdk-for-go#635]
I try to create a DNS record following the example here https://github.com/Azure/azure-sdk-for-go/pull/600/files (@xtophs) and I get this error:

```
FATA[0003] dns.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationRequired" Message="The location property is required for this definition." 
```
(Here the code: https://github.com/symbiont-io/external-dns/blob/4f2c85e30da9edcdf73a9effac45943ae6d17a93/provider/azure.go#L175-L197)

**Comment by xtophs** [comment]
You may want to connect with @peterhuene, who's also working on an external DNS provider: https://github.com/peterhuene/external-dns

I haven't see this error when creating a RecordSet, only creating zones. What parameters are you passing to the CreateOrUpdateCall?

**Comment by peterhuene** [comment]
We're about to submit the work from the [azure branch](https://github.com/peterhuene/external-dns/tree/azure) as a PR once I finish up a few more unit tests.  Ideally the PR will go up this afternoon.

I also have not seen this error when creating records sets, only zones (which have a location property).

**Comment by peterhuene** [comment]
For reference, the PR is up at https://github.com/kubernetes-incubator/external-dns/pull/214

**Comment by ouziel-slama** [comment]
@peterhuene great !! Will try to test your branch today. Only me get the error so closing the issue for now. Will re-open if happen again with the @peterhuene branch.
