### ISSUE TITLE
Failed to delete resource NetApp Account when the delete API of NetApp Pool returns 404

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#6374]
### Bug Report

- Import path of package in question: https://github.com/Azure/azure-sdk-for-go/tree/master/services/netapp/mgmt/2019-06-01/netapp
- SDK version: v35.0.0
- Output of `go version`: go version go1.12.7 windows/amd64

- **What happened?**
The resource NetApp Pool depends on the resource NetApp Account. Although the delete API returns 404 which means the NetApp Pool resource has been deleted. Then it tries to immediately delete NetApp Account but it still throws error `Can not delete resource before nested resources are deleted.`, which means the resource NetApp Pool still hasn't been deleted. So it failed to delete top resource NetApp Account.

- **What did you expect or want to happen?**
It should delete both resources NetApp Pool and NetApp Account successfully.

- **How can we reproduce it?**
1. Create a resource group
2. Create NetApp Account
3. Create NetApp Pool
4. Delete NetApp Pool, which returns "202"
5. Immediately call "Get" rest api to get resource NetApp Pool, which returns "404"
6. Immediately delete NetApp Account, which returns error code "409"
7. Then it throws error `Can not delete resource before nested resources are deleted.`

- **My test result with rest api from above step 4 to 6:**
**1. Call NetApp Pool - Delete API:**
DELETE https://management.azure.com/subscriptions/xxxxx/resourceGroups/resources/providers/Microsoft.NetApp/netAppAccounts/netappaccount/capacityPools/netapppool?api-version=2019-06-01
Authorization: <token>

access-control-expose-headers: Azure-AsyncOperation,Request-Context,Access-Control-Expose-Headers,x-ms-ratelimit-remaining-subscription-deletes,Date,Location,Server,X-Powered-By,x-ms-request-id,x-ms-correlation-request-id,x-ms-routing-request-id,Content-Length
azure-asyncoperation: https://management.azure.com/subscriptions/xxxxxx/providers/Microsoft.NetApp/locations/eastus2/operationResults/xxxxxx?api-version=2019-06-01
cache-control: no-cache
content-length: 0
date: Mon, 18 Nov 2019 07:00:59 GMT
expires: -1
location: https://management.azure.com/subscriptions/xxxxx/providers/Microsoft.NetApp/locations/eastus2/operationResults/xxxxx?api-version=2019-06-01&operationResultResponseType=Location
pragma: no-cache
request-context: appId=cid-v1:xxxxx
server: Microsoft-IIS/10.0
x-ms-correlation-request-id: xxxx
x-ms-ratelimit-remaining-subscription-deletes: 14985
x-ms-request-id: xxxx
x-ms-routing-request-id: xxxxx
x-powered-by: ASP.NET

![image](https://user-images.githubusercontent.com/19754191/69035732-45d3e500-0a1f-11ea-9947-79e4725bdd42.png)
Response body: null

**2. Call NetApp Pool - Get API:**
GET https://management.azure.com/subscriptions/xxxx/resourceGroups/resources/providers/Microsoft.NetApp/netAppAccounts/netappaccount/capacityPools/netapppool?api-version=2019-06-01
Authorization: <token>

access-control-expose-headers: x-ms-request-id,Request-Context,Access-Control-Expose-Headers,x-ms-ratelimit-remaining-subscription-reads,Date,Server,X-Powered-By,x-ms-correlation-request-id,x-ms-routing-request-id,Content-Length
cache-control: no-cache
content-length: 285
content-type: application/json; charset=utf-8
date: Mon, 18 Nov 2019 07:01:02 GMT
expires: -1
pragma: no-cache
request-context: appId=cid-v1:xxxx
server: Microsoft-IIS/10.0
x-ms-correlation-request-id: xxx
x-ms-ratelimit-remaining-subscription-reads: 11983
x-ms-request-id: xxxx
x-ms-routing-request-id: SOUTHEASTASIA:20191118T070102Z:7887b82c-f318-427f-a504-15d135cf15f5
x-powered-by: ASP.NET

Response body
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The resource with identifier '/subscriptions/xxxx/resourceGroups/resources/providers/Microsoft.NetApp/netAppAccounts/netappaccount/capacityPools/netapppool' is not found."
  }
}
![image](https://user-images.githubusercontent.com/19754191/69035764-58e6b500-0a1f-11ea-9d35-4cb4099c71d8.png)

**3. Call NetApp Account - Delete API:**
DELETE https://management.azure.com/subscriptions/xxxx/resourceGroups/resources/providers/Microsoft.NetApp/netAppAccounts/netappaccount?api-version=2019-06-01
Authorization: <token>

cache-control: no-cache
content-length: 114
content-type: application/json; charset=utf-8
expires: -1
pragma: no-cache
x-ms-correlation-request-id: xxxx
x-ms-failure-cause: gateway
x-ms-request-id: xxx
x-ms-routing-request-id: SOUTHEASTASIA:20191118T070109Z:xxxx

Response body:
{
  "error": {
    "code": "CannotDeleteResource",
    "message": "Can not delete resource before nested resources are deleted."
  }
}
![image](https://user-images.githubusercontent.com/19754191/69035936-bed33c80-0a1f-11ea-9790-51d1b9d8cdd1.png)

**Comment by ArcturusZhang** [comment]
Hi @leonardbf could you please help on this NetApp issue?

**Comment by leonardbf** [comment]
Yes we will look into this. We have seen some issues previously due to lag in clearing the cache. Including a short delay after the get pool returns 404 would normally allow the account to be deleted.

**Comment by anlatsko** [comment]
I've been seeing this same error. Is there any movement on this issue and is there a workaround? We've had a volume that we've been unable to delete for multiple months with this exact same error. We've tried through the Python API and through the portal.

**Comment by Kumoservices** [comment]
same thing for me !!

i have open a case on Nov 25 2020 but it has been close for dark reason : https://github.com/terraform-providers/terraform-provider-azurerm/issues/9479

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
