### ISSUE TITLE
sloppy vendoring of unreleased "github.com/Azure/go-autorest"

### ISSUE THREAD

**Issue by onlyjob** [Azure/azure-sdk-for-go#6391]
`github.com/Azure/go-autorest/tracing` is not provided even by the latest [release](https://github.com/Azure/go-autorest/releases) v13.3.0 (released in October) yet _azure-sdk-for-go_ uses the import all over.

For the sake of best practice please only ever vendor tagged semantic releases instead of random commits.

**Comment by maggiepint** [comment]
@mozehgir are you able to route this?

**Comment by jhendrixMSFT** [comment]
@onlyjob can you please clarify what you're seeing.  Release v13.3.0 of go-autorest contains the tracing package.

**Comment by onlyjob** [comment]
Apologies for my mistake - I must have accidentally checked a prior release than v13.3.0.

All good.
