### ISSUE TITLE
How to use the parameter filter?

### ISSUE THREAD

**Issue by zxDiscovery** [Azure/azure-sdk-for-go#6393]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?
I saw the code `resourceskus.go` has been changed, and the list function adds a new parameter filter `func (client ResourceSkusClient) List(ctx context.Context, filter string)`. But the [doc](https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list) doesn't update yet. Now I don't know how to use the `List` function.

- What did you expect or want to happen?
I want to list the `vmSize` which available for My current Subscription. And also filter the `vmSize` available in the location which I specified. 
Is anyone can help me. Thanks!

- How can we reproduce it?
N/A

- Anything we should know about your environment.
N/A

**Comment by ArcturusZhang** [comment]
Yes, the doc is for old api-version. I did not find any new doc for 2019-03-01 either.
Let me find someone to help and then come back to you.

**Comment by ArcturusZhang** [comment]
Hi @zxDiscovery I did not get any feedback from the internal teams, but I found this [example](https://github.com/Azure/azure-rest-api-specs/blob/c649e5edeccb4152f44e4d32ffe12ae34bb2938f/specification/compute/resource-manager/Microsoft.Compute/stable/2019-04-01/examples/ListAvailableResourceSkusForARegion.json#L5) for filter, which you might find useful.

**Comment by zxDiscovery** [comment]
@ArcturusZhang Thank you for your replay. It's useful for me. Now I know the current API only can filter the location. The filter parameter just as you give the example.

**Comment by zxDiscovery** [comment]
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/custom.py#L774

Here is proof that the current AZ CLI only filter the location. The other data analysis will be done on the client-side when it gets the data from the server.
