### ISSUE TITLE
Batch update of the Recordset 

### ISSUE THREAD

**Issue by ideahitme** [Azure/azure-sdk-for-go#640]
Hello, 

From what I found RecordSet can be updated/deleted only individually using sdk. Is there a way to create a batch request for multiple RecordSets within a DNS zone, i.e. so that a batch request will succeed, only if change for each of the RecordSet succeeds. Otherwise no changes are applied. 

Thanks,

Yerken

**Comment by marstr** [comment]
Howdy @ideahitme,

I am unaware of batch functionality for DNS RecordSets. However, you may try posting this in the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repo to cast a wider net.

-Martin
