### ISSUE TITLE
Unified ErrorResponse Type and Unified Handling

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-go#643]
I could not find an existing bug on this, so apologies if there is.

Most models have their own definition of an ErrorResponse and ErrorDetails.  As near as I can tell the structure is mostly identical.  (Deployment errors include a status, but that's the only difference I have seen thus far.) 

The errors returned by Azure all appear to follow this style.

```json
{
    "error": {
        "code": "BadRequest",
        "message": "There was a bad request",
        "details": [{
          "code": "NestedBadRequest",
          "message": "{ \"error\": ... }"
       }]
    }
}
```

It would be great if there was a unified way to handle errors. My own needs are simply to display the error to the user, but I am sure there are others.  My example above showed a complex example, which I see quite often.  The error contains an embedded (serialized) ErrorDetails in the message of a detail's message.  One has to keep deserializing the JSON to get all of the errors that made up the change.

**Comment by mcardosos** [comment]
Hello @boumenot !
I think we can do better with the error unmarshaling, yes. If you happen to have a fix for this, PRs are always welcome. In all cases, @marstr will take a look at this.

**Comment by marstr** [comment]
We've done some work here https://github.com/Azure/go-autorest/pull/170 and here https://github.com/Azure/go-autorest/pull/140. Hopefully this helps makes errors a little easier to deal with. If there are further needs, feel free to open another issue either here or in https://github.com/Azure/go-autorest
