### ISSUE TITLE
Migrating Service Bus code for the latest SDK to the central repository

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk-for-go#6463]
Move code from https://github.com/Azure/azure-service-bus-go to https://github.com/Azure/azure-sdk-for-go/

**Comment by devigned** [comment]
What about Azure Storage? Will that be moved into this repo as well?

**Comment by mayurid** [comment]
@devigned : Answering the questions in order:-
1) Yes we will be looking into that
2) Yes we will look into that
3) Right now the only one's in our list are Storage, EH and Service Bus. Please let us know if there are more which we should look into
4) We are planning to move the Go repo to version with Go Modules. We are working on phased plan for that. To begin with the we will make sure newer to repo libraries like SB, EH etc will be using it
5) Yes they will be kept around for the near future but no new development will be done there. We will give appropriate heads up to make sure customer impact can be minimized
6) We have discussed keeping existing repos around but would prefer having them centralized. SB will be the first one where we will do this move. if we run into issues we will reassess the plan.

Really appreciate your questions. Keep them coming

//cc : @jhendrixMSFT 
6)

**Comment by devigned** [comment]
3. [Application Insights](https://github.com/microsoft/ApplicationInsights-Go) is one that comes to mind and would be super useful.
5 / 6. Perhaps, leaving the repos as archived would be a kinder approach than deleting.

It would be really helpful to publishing proposals for wide impacting work like this. I'd imagine it would be surprising if things like this happened abruptly.

**Comment by richardpark-msft** [comment]
Added in #15245 to deal with some of the mechanics of this transition.

We've pinned @devigned's issue discussing this in the azure-service-bus-go repo (https://github.com/Azure/azure-service-bus-go/issues/152). The repo's issue tracker is fairly low traffic, even for issues, so we're not expecting too much feedback via that channel at the moment.

Code for track 2 has 'started' (literally just copied over as of this moment) in https://github.com/azure/azure-sdk-for-go/tree/track2-servicebus

**Comment by serbrech** [comment]
About 6. I agree with @devigned.
deleting the repo means existing software relying on it will stop compiling. 
Comparing it to .NET, it would be the equivalent of deleting all nuget packages ever published for a project (not just deleting the repo)
Can we consider archiving the project instead?

**Comment by richardpark-msft** [comment]
@serbrech - Absolutely. Archiving is the _only_ path we're considering (and is what we've done in the past as we've transitioned repos into the monorepo).

**Comment by richardpark-msft** [comment]
Also, I've updated the title as it's less of a "move" and more of a "we're starting the new SDK development in the monorepo".

**Comment by RickWinter** [comment]
The code and module for latest azservicebus is available at: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus
