### ISSUE TITLE
Private Link Service returns success before values are persisted to Azure

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-sdk-for-go#6466]
### Bug Report
- Import Path: `.../services/network/mgmt/2019-09-01/network`
- SDK Version: `36.2`
- Go Version: `go1.12.5 linux/amd64`

#### What Happened:
While creating the `Private Link Service` resource for the Terraform Azure Provider I noticed that the API was returning success before the values were actually persisted to the Azure resource. In Terraform once a resource reports success we instantly do a `Get` on the Azure resource, out `Get` was/is returning empty values for the attributes we just `Set`.

#### What did I expect or want to happen:
The values that were 'Set' to be returned by the `Get`.

#### How can we reproduce it:
Create a `Private Link Service` and once it returns success do a `Get`.

#### Anything we should know about your environment:
No, standard Go development environment on `WSL`.

**Comment by allegradomel** [comment]
@WodansSon, thanks for bringing this to our attention. Looking into this - will update soon!

**Comment by markthebault** [comment]
Any update on this ?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
