### ISSUE TITLE
Unable to remove Tags from Private Link Endpoint

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-sdk-for-go#6467]
### Bug Report
Import Path: `.../services/network/mgmt/2019-09-01/network`
SDK Version: `36.2`
Go Version: `go1.12.5 linux/amd64`

#### What happened:
I set a tag on the private link endpoint resource, I then attempt to remove the tag by removing the tag block from my request message. The API returns success, but on a Get the tag is still there.

#### What did you expect or want to happen:
The tag to be removed from the resource.

#### How can we reproduce it:
Create a Private Link Endpoint and set the tag attributes, then update the same Private Link Endpoint by removing the tag attributes.

#### Anything we should know about your environment:
No, standard Go development environment on `WSL`.

**Comment by allegradomel** [comment]
Not sure if service side issue or SDK issue, @ivapplyr can you look into this?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
