### ISSUE TITLE
Request: support for Azure Marketplace Billing API

### ISSUE THREAD

**Issue by hepais-microsoft** [Azure/azure-sdk-for-go#6483]
### Service Package Request

Hello,

The Azure Marketplace Billing API is used by several ISV's to publish and maintain their offerings on Azure marketplace. It is a RESTful API but we don't have a go SDK for it.

Would it be possible to add it to your roadmap? Here is the link to the documentation:

https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/marketplace-metering-service-apis

**Comment by disrani-px** [comment]
We are working on integration with the Azure marketplace and adding these APIs would be really helpful for us. We are having to write our own wrappers for the REST APIs for now

**Comment by ramaganesan-rg** [comment]
This is not a Billing issue, can you please route this to the right team?
