### ISSUE TITLE
Failed to delete resource NetApp Pool when the delete API of NetApp Volume returns 404

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#6485]
### Bug Report

- Import path of package in question: https://github.com/Azure/azure-sdk-for-go/tree/master/services/netapp/mgmt/2019-06-01/netapp
- SDK version: v35.0.0
- Output of `go version`: go version go1.12.7 windows/amd64

- What happened?
The resource NetApp Volume depends on the resource NetApp Pool. Although the delete API returns 404 which means the NetApp Volume resource has been deleted. Then it tries to immediately delete NetApp Pool but it still throws error `Can not delete resource before nested resources are deleted.`, which means the resource NetApp Volume still hasn't been deleted. So it failed to delete top resource NetApp Pool.

- What did you expect or want to happen?
It should delete both resources NetApp Volume and NetApp Pool successfully.

- How can we reproduce it?
1. Create a resource group
2. Create NetApp Account
3. Create NetApp Pool
4. Create NetApp Volume
5. Delete NetApp Volume, which returns "202"
6. Immediately call "Get" rest api to get resource NetApp Volume, which returns "404"
7. Immediately delete NetApp Pool, which returns error code "409"
8. Then it throws error `Can not delete resource before nested resources are deleted.`

- Anything we should know about your environment.
The error message:
"Error: Error deleting NetApp Pool "acctest-NetAppPool" (Resource Group "acctestRG-netapp"): netapp.PoolsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."" when the delete API of NetApp Volume returns 404.

**Comment by ArcturusZhang** [comment]
Hi @leonardbf could please help on this issue?

**Comment by prasroy** [comment]
I am also receiving an error while deleting a ANF volume from Azure portal. The error message is as below.
Can not delete resource before nested resources are deleted.

**Comment by devtrf** [comment]
Did this ever get resolved? Having a similar issue.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
