### ISSUE TITLE
web/CertificatesClient should not force a value for the "password" property

### ISSUE THREAD

**Issue by tiwood** [Azure/azure-sdk-for-go#6498]
### Bug Report

- import path of package
`"github.com/Azure/azure-sdk-for-go/services/web/mgmt/2019-08-01/web"`
- SDK version `master`
- `go version go1.13.4 darwin/amd64`

You can now create `App Service Managed Certificates` by providing a `Certificate` struct with the following properties to the `CertificatesClient.CreateOrUpdate` function:

```go
certificate := web.Certificate{
		CertificateProperties: &web.CertificateProperties{
			CanonicalName: utils.String(name),
			ServerFarmID:  utils.String(appServicePlanID),
		},
		Location: utils.String(location),
		Tags:     tags.Expand(t),
	}
```

Note that `Password` is not required and should not be set. If a value for `Password` is set, the API will return `GatewayTimeout` errors.

Unfortunately, the SDK currently validates that `Password` is not nil. This has to be fixed to enable the creation of `App Service Managed Certificates`.

The validation happens here:
https://github.com/Azure/azure-sdk-for-go/blob/e56ec3f142bfbc83f619f7e7eaf72abf03a3ef17/services/web/mgmt/2019-08-01/web/certificates.go#L67

**Comment by ArcturusZhang** [comment]
Hi @tiwood thanks for opening this issue!
I just checked the corresponding swagger for this service. It turns out that the `password` field is marked as `required` in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/a6f20ec7547f17a355aafee2ec2ad7a4fa78412a/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/Certificates.json#L315).
I have tagged this issue, so the corresponding service team would have a look on this issue.

**Comment by tiwood** [comment]
Hi @ArcturusZhang, can you provide an update?

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang, can you provide an update?

I am afraid that I cannot provide a fix directly in go SDK. This is written in the swagger which is managed by the service team.
Would you please open an issue in the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repo about this and referring this issue then?

**Comment by tombuildsstuff** [comment]
@ArcturusZhang is there a timeframe for this Swagger getting fixed?

**Comment by drdamour** [comment]
Is this the upstream issue https://github.com/Azure/azure-rest-api-specs/issues/5029 ?

**Comment by ArcturusZhang** [comment]
> Is this the upstream issue [Azure/azure-rest-api-specs#5029](https://github.com/Azure/azure-rest-api-specs/issues/5029) ?

Indeed, thanks for reminding me this. I have tagged the upstream issue to inform the corresponding service team.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang is there a timeframe for this Swagger getting fixed?

Sorry that I do not have a timeframe for this issue...
I will try to make some internal email directly to the corresponding service team

**Comment by panchagnula** [comment]
@ArcturusZhang AFAIK password for a cert is always a required property if you are uploading a certificate - for a managed certificate we create the certificate & how are you trying to use this for managed certs? Can you refer to the CLI command here & check how are using the API terraform scripts to use this?  https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-create

**Comment by AdamCoulterOz** [comment]
> @ArcturusZhang AFAIK password for a cert is always a required property if you are uploading a certificate - for a managed certificate we create the certificate & how are you trying to use this for managed certs? Can you refer to the CLI command here & check how are using the API terraform scripts to use this? https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-create

I'm pretty sure its something like this .... but there is a problem with the bind ...

Step 1: Create Managed Certificate... which works perfectly
```bash
az webapp config ssl create --resource-group {rg} --name {webapp} --hostname {FQDN}
```

Step 2: get the {certificate_thumbprint} from the json object output from 1

Step 3: Bind the certificate to the website custom domain name

```bash
az webapp config ssl bind --certificate-thumbprint {certificate_thumbprint} --name MyWebapp --resource-group MyResourceGroup --ssl-type SNI
```

When running step 3 I get an error saying **`Certificate for thumbprint 'xxxx' not found`**. So I ran in debug mode and it clearly switches contexts from searching for the certificate under the webapp to the underlying server farm. Instead of running:

```http
GET /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/certificates
```
with {rg} of the webapp

it runs

```http
GET /subscriptions/{sub}/resourceGroups/{other-rg}/providers/Microsoft.Web/certificates
```
with {other-rg} of the webapp's serverfarm

important to note that the serverfarm is in a different rg than the webapp. This seems like a bug and would probably work if they were in the same rg.

When you do the same step 3 operation via the portal it does work, seems to get the context right. To perform the bind it does a HTTP request:

```http
PUT /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{webapp}?api-version=2018-11-01
```

with a JSON body (abbreviated):



```json
{
    "id": "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{webapp}",
    "kind": "app,linux,container",
    "location": "Australia East",
    "name": "{webapp}",
    "type": "Microsoft.Web/sites",
    "properties": {
        "hostNameSslStates": [
            {
                "name": "{FQDN}",
                "sslState": "SniEnabled",
                "ipBasedSslResult": null,
                "virtualIP": null,
                "thumbprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "toUpdate": true,
                "toUpdateIpBasedSsl": null,
                "iPBasedSslState": "NotConfigured",
                "hostType": "Standard"
            }
        ],
        "hostNames": [
            "{FQDN}"
        ]
    }
}
```

**Comment by AdamCoulterOz** [comment]
I was also able to get the bind to work with this newer api:

```http
PUT /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{webapp}/hostNameBindings/{custom_hostname}?api-version=2019-08-01
Authorization: Bearer {token}
Content-type: application/json
```

Body:
```json
{
    "kind": "app,linux,container",
    "properties": {
        "azureResoureName": "{webapp}",
        "azureResourceType": "Website",
        "customHostNameDnsRecordType": "CName",
        "domainId": null,
        "hostNameType": "Verified",
        "siteName": "{webapp}",
        "sslState": "SniEnabled",
        "thumbprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
}
```

**Comment by AdamCoulterOz** [comment]
as for the managed cert creation, the az cli does this (using Azure-SDK-For-Python), and I've tested it working:

```http
PUT /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/certificates/{custom-hostname}?api-version=2019-08-01
```

Body:
```json
{
    "location": "Australia East",
    "properties": {
        "password": "",
        "serverFarmId": "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/serverfarms/{serviceplan}",
        "canonicalName": "{custom-hostname}"
    }
}
```

@tiwood have you tried setting the password to empty string? `""`

**Comment by martinjt** [comment]
Is anyone actively pushing this? it's blocking some other things by the look of it.

**Comment by martinjt** [comment]
@tombuildsstuff Don't suppose you have someone at Azure you could nudge to sort the dependent issue?

**Comment by panchagnula** [comment]
@martinjt on the API end app service doesn't enforce the password option. A passoword is required when a cert (local) is being uploaded to a webapp. If its a managed certificate or certificate from a AKV - then you don't need the password info - the API has it optional. I am not aware of the GO SDK but I can ensure the API doesn't enforce - so please check the usage of the API. Thanks!

**Comment by AdamCoulterOz** [comment]
So I've just tested this out, and it looks like it works if you set the password to an empty string like this:

```go
certificate := web.Certificate{
	CertificateProperties: &web.CertificateProperties{
		CanonicalName: utils.String(name),
		ServerFarmID:  utils.String(appServicePlanID),
		Password:      new(string),
	},
	Location: utils.String(location),
	Tags:     tags.Expand(t),
}
```

This was my suspicion about three months ago when I posted earlier, but haven't had a chance till now to test my theory. I have created a PR to fix this for the new resource here:

https://github.com/terraform-providers/terraform-provider-azurerm/pull/9378
