### ISSUE TITLE
SDK refactor deleted appinsights/v1 data plane packages

### ISSUE THREAD

**Issue by alexeldeib** [Azure/azure-sdk-for-go#6499]
### Bug Report

- import path of package in question: services/appinsights/v1/insights
- SDK version: v34.4.0, this commit: https://github.com/Azure/azure-sdk-for-go/commit/8c372e6e1243e0427dffb2d750099ee3ed161a44#diff-616e7389a9af172905133b3d95de4379
- output of `go version`: irrelevant

- What happened? During an apparent refactor by the SDK team, the only data plane package available for querying App Insights was deleted in this commit: https://github.com/Azure/azure-sdk-for-go/commit/8c372e6e1243e0427dffb2d750099ee3ed161a44#diff-616e7389a9af172905133b3d95de4379
- What did you expect or want to happen? The package should have continued to exist, as it is current. For some reason only the management plane package exists now. Seems like someone tinkered with the autogen rules 
- How can we reproduce it? Look at master :) 
- Anything we should know about your environment. Nope.

Here's the package I was looking for: https://github.com/Azure/azure-sdk-for-go/tree/a6c1340e73c13630ef3f737617c2892847cab556/services/appinsights/v1

**Comment by ArcturusZhang** [comment]
Hi @alexeldeib  thanks for the issue.
Actually, there is also a package `appinsights` in 
```
github.com/Azure/azure-sdk-for-go/services/preview/appinsights/v1/insights
```
I am wondering if this package is the same as the one get deleted?

**Comment by alexeldeib** [comment]
That does seem to be the same one, sorry I didn’t see it under preview! Wonder why it was moved?

**Comment by ArcturusZhang** [comment]
> That does seem to be the same one, sorry I didn’t see it under preview! Wonder why it was moved?

The `services/appinsights/v1/insights` package is hand-written or generated by the early version of autorest, therefore it got deleted in v34.0.0. And the package under preview directory is generated by a newer version of autorest.
