### ISSUE TITLE
Define policy for supported versions of Go

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#650]
In our CI we verify changes against 1.7 and 1.8.  Investigate if we really need to support our SDK on N and N-1 versions of Go.

**Comment by jhendrixMSFT** [comment]
Latest versions of terraform and kubernetes require Go 1.8.*.

**Comment by marstr** [comment]
Now that we need to support profiles, we may need to require Go 1.9 when it comes out. [The new type aliasing that they are introducing](https://tip.golang.org/doc/go1.9#language) could save us months of work and headaches.

**Comment by jhendrixMSFT** [comment]
Go does not support previous releases, see https://golang.org/doc/devel/release.html.  I think it's safe to say we can drop N-1.

**Comment by marstr** [comment]
Alright, we've chatted about this internally. Officially, our policy will be that we only support the most recent version of Go. However, we will try to be cognizant of changes and when they break older versions of Go.
