### ISSUE TITLE
How to add existing VM into Backend Pool of Load balancer using Golang SDK?

### ISSUE THREAD

**Issue by renpengzhang** [Azure/azure-sdk-for-go#6504]
I want to use Golang SDK to **add existing VM into Backend Pool of Load balancer**. But I am not sure how to achieve this.

 I tried to use **LoadBalancersClient .CreateOrUpdate()** function, and specify the VM's private IP in the params, but it doesn't work.

**Comment by ArcturusZhang** [comment]
I found this [tutorial](https://docs.microsoft.com/en-us/azure/load-balancer/tutorial-load-balancer-standard-manage-portal) that you may find useful.

**Comment by renpengzhang** [comment]
Can you clarify how to do this using Azure Golang SDK?

**Comment by ArcturusZhang** [comment]
> Can you clarify how to do this using Azure Golang SDK?

You could try this [snippet](https://gist.github.com/ArcturusZhang/e371228283cd7e9438c03a8537330391)
My reference: https://docs.microsoft.com/en-us/azure/load-balancer/scripts/load-balancer-linux-cli-sample-zonal-frontend
