### ISSUE TITLE
Unable to build Go project that uses keyvalt SDK

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-sdk-for-go#6512]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`

```	
"github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault"
kvauth "github.com/Azure/azure-sdk-for-go/services/keyvault/auth"
```
Same happens with:
```	
"github.com/Azure/azure-sdk-for-go/profiles/latest/keyvault/keyvault"
```
- SDK version e.g. `master`, `latest`, `18.1.0`
```
latest
```
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`
```
# github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:112:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:199:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:279:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:359:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:455:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:544:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:638:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:719:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:794:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:874:8: undefined: autorest.GetSendDecorators
/Users/toddysm/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v37.0.0+incompatible/services/keyvault/v7.0/keyvault/client.go:874:8: too many errors
make: *** [server] Error 2
```

- What happened?
When building the project the above errors show up and the project is not build
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.
Running on MacOS

**Comment by ArcturusZhang** [comment]
That is weird, this method `autorest.GetSendDecorators` is used by every method that would send a rest request.
I did not reproduce your issue on my machine. Could you please clean your local cache in `$GOPATH/pkg` and try again?

**Comment by toddysm** [comment]
Nope, cleaning the cache didn't solve it. 

Just curious - what is the meaning of the `+incpmatible` in the package name (this immediately raises red flags to me)? Also, what is the correct import for the KeyVault packages because the samples are very conflicting?

**Comment by ArcturusZhang** [comment]
> Nope, cleaning the cache didn't solve it.
> 
> Just curious - what is the meaning of the `+incpmatible` in the package name (this immediately raises red flags to me)? Also, what is the correct import for the KeyVault packages because the samples are very conflicting?

Weird... SDK is using that function all over the place. Every function that sends rest api request will call that. Could you please give a more detailed snippet of code that could reproduce this problem? Have you ever tried other packages in the SDK, would them work?

BTW, the profile in keyvault dataplane `"github.com/Azure/azure-sdk-for-go/profiles/latest/keyvault/keyvault"` is actually equivalent to `"github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault"`

The `+incompatible` suffix is a backward compatibility mark to involve some library that does not implements go modules. The azure-sdk-for-go currently is not implemented as a module, therefore when you add the SDK as dependency to a module project, an `incompatible` suffix will be automatically added. You can find more detail [here](https://github.com/golang/go/wiki/Modules#how-are-versions-marked-as-incompatible).

As for the keyvault packages, which sample are you referring? I could have it a look at.
