### ISSUE TITLE
Allow to use an arbitrary credential provider endpoint 

### ISSUE THREAD

**Issue by hixichen** [Azure/azure-sdk-for-go#6520]
**What is expected:**
```
export AZURE_CREDENTIALS_URI=https://xyz:1234/path/to/creds
```

**Why:**
- In multi/hybrid cloud world, external creds provider is needed. 
- Let the SDK handle the creds rotation work instead of the services. 

**Refer:**
https://github.com/aws/aws-sdk-go-v2/issues/451

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT could you please help on this?

**Comment by RickWinter** [comment]
Track2 azidentity allows for providing a custom authority host via code.
