### ISSUE TITLE
Gremlin Database and GremlinGraph within Azure CosmosDB

### ISSUE THREAD

**Issue by petems** [Azure/azure-sdk-for-go#6533]
### Service Package Request

Terraform already ships with resources to access Azure CosmosDB's MongoDB, CassandraDB and Table API. However, analogous resources for GremlinDB are still missing. 

They don't seem to be available in the SDK as far as I can see. 

docs.microsoft.com/en-us/azure/cosmos-db/graph-introduction
docs.microsoft.com/en-us/azure/cosmos-db/create-graph-gremlin-console

### Terraform Issue	

https://github.com/terraform-providers/terraform-provider-azurerm/issues/4970

**Comment by ArcturusZhang** [comment]
Hi @petems thanks for this issue!
I am wondering if [this](https://github.com/Azure/azure-sdk-for-go/blob/ab2c50cd6e8d2d1552c9ba3c376e5eb405515ddd/services/cosmos-db/mgmt/2019-08-01/documentdb/gremlinresources.go#L30) or [this](https://github.com/Azure/azure-sdk-for-go/blob/ab2c50cd6e8d2d1552c9ba3c376e5eb405515ddd/services/preview/cosmos-db/mgmt/2019-08-01-preview/documentdb/gremlinresources.go#L30) could meet your requirement.
