### ISSUE TITLE
plans to support MySQL database service

### ISSUE THREAD

**Issue by sebastus** [Azure/azure-sdk-for-go#654]
Is anyone thinking about extending the sdk to cover the new MySQL database service?
What is the plan?

**Comment by mcardosos** [comment]
Hello @sebastus !
The first step would be to get a swagger spec for its API. I have already created an [issue](https://github.com/Azure/azure-rest-api-specs/issues/1309) in the azure-rest-api-specs repo.

**Comment by marstr** [comment]
Quick update, it looks like there are plans to move the swagger for MySQL management over into the [public specs repository](https://github.com/Azure/azure-rest-api-specs). Once that happens, a package will get dropped into our SDK.

**Comment by sebastus** [comment]
How long does that process take?

**Comment by marstr** [comment]
Good question. @kirthik or @salameer may be able to speak to the expectations about when this swagger will become public. Once it is, we should be able to generate/test it within a week or so.

**Comment by sebastus** [comment]
Any comment, @kirthik or @salameer ?

**Comment by kirthik** [comment]
@sebastus  - There is an open for PR for this - https://github.com/Azure/azure-rest-api-specs/pull/1338. I think this should be merged in next few days.

**Comment by salameer** [comment]
Hi @sebastus,

Would you mind taking a quick look at the spec that @kirthik mentioned and letting us know if it covers the functionalities that you're looking for?

If your having troubles finding or analyzing the spec we can also try to help with that :)

**Comment by sebastus** [comment]
will do.

**Comment by tombuildsstuff** [comment]
@salameer @marstr just a heads up that [the Swagger PR's been merged](https://github.com/Azure/azure-rest-api-specs/pull/1338) - as such would it be possible to add this the SDK? :) 

Thanks!

**Comment by tombuildsstuff** [comment]
@marstr / @mcardosos thanks for a bunch for adding this, since this has shipped in #681 / #709 I think this can be closed :)
