### ISSUE TITLE
Can't unmarshal AzureIaaSVMJob.actionsInfo of type backup.JobSupportedAction'

### ISSUE THREAD

**Issue by artii15** [Azure/azure-sdk-for-go#6543]
### Bug Report

- `../services/recoveryservices/mgmt/2019-05-13/backup`
- SDK version 37.1.0
- go version go1.12.5 linux/amd64

I was trying to get a virtual machine backup job status using `JobDetailsClient`. Calling the `Get` method resulted with an error. While debugging I've noticed that the API responded with 200 status, but the SDK is not able to parse the response body. 
The error suggests that there is a problem with parsing response.  Below I'm pasting the error message (I've replaced actual identifiers with "x"):

backup.JobDetailsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field AzureIaaSVMJob.actionsInfo of type backup.JobSupportedAction' JSON = '{\"id\":\"/Subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.RecoveryServices/vaults/xxxxxxx/backupJobs/xxxxxxxxx\",\"name\":\"xxxxxxxxx\",\"type\":\"Microsoft.RecoveryServices/vaults/backupJobs\",\"properties\":{\"jobType\":\"AzureIaaSVMJob\",\"containerName\":\"xxxxxx\",\"duration\":\"PT33.290293S\",\"actionsInfo\":[1],\"virtualMachineVersion\":\"Compute\",\"extendedInfo\":{\"tasksList\":[{\"taskId\":\"Take Snapshot\",\"duration\":\"PT0S\",\"status\":\"InProgress\"},{\"taskId\":\"Transfer data to Vault\",\"duration\":\"PT0S\",\"status\":\"NotStarted\"}],\"propertyBag\":{\"VM Name\":\"xxxxx\",\"Recovery Point Expiry Time in UTC\":\"12/31/2019 6:17:17 AM\"},\"internalPropertyBag\":{\"IsInstantRpJob\":\"True\"}},\"entityFriendlyName\":\"xxxxxx\",\"backupManagementType\":\"AzureIaasVM\",\"operation\":\"Backup\",\"status\":\"InProgress\",\"startTime\":\"2019-12-17T06:17:18.8407438Z\",\"activityId\":\"xxxxxxx\"}}'","time":"2019-12-17T07:41:18+01:00"}

It seems that ActionsInfo field can't be unmarshalled to a slice of strings, while the API returns a list of numbers. 
Could you please fix the response result parsing?

**Comment by ArcturusZhang** [comment]
Thanks for the issue!
But this issue is duplicated with [this](https://github.com/Azure/azure-sdk-for-go/issues/5339). This is a service or swagger bug, but the service team still did not provide a fix for this. I am very sorry for the inconvenience. I will push the service team to provide a fix for this. Thanks!
