### ISSUE TITLE
Kusto Database Principal - Unexpected issues

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#6547]
### Bug Report

- import path of package in question `github.com/Azure/azure-sdk-for-go/services/kusto/mgmt/2019-05-15/kusto`
- SDK version e.g. `36.2.0`
- `go version go1.13.4 darwin/amd64`

I'm attempting to use [AddPrincipal](https://github.com/Azure/azure-sdk-for-go/blob/master/services/kusto/mgmt/2019-05-15/kusto/databases.go#L52) for Kusto Database Principal but was hitting issue after issue as I tried to understand how to use it. I've made a list of each issue that I encountered as I tried to use this API.

I get an error message, "The request content was invalid and could not be deserialized." from: 
```
{
	"value": [{
		"role": "Viewer",
		"type": "App",
		"fqn": "aadapp=SomeUUID",
		"email": "",
		"appId": "SomeUUID"
	}]
}
```
More helpful error messages would help identify problem areas when building the request.

Values don't seem to matter like email, name, or appID as they just get overwritten by the FQN. For example:
```
{
	"value": [{
		"role": "Viewer",
		"name": "nameOfUser3",
		"type": "App",
		"fqn": "fqnOfUser1",
		"email": "emailOfUser2",
		"appId": ""
	}]
}
```
The above overwrites the requested name of user3 and email of user2 with that of user1 which makes the noted attributes have no bearing on what's actually happening. An error messages around requested values that don't match each other would be helpful.

When passing in the fqn of an email with the wrong prefix, the error returned  is `"The request is invalid."`. An error message on what is invalid would be preferred.
```
"fqn": "aadapp=someuuid // this should be prefixed with "aaduser=someuuid"
```

A principal can be created with just an `appID` and no `fqn` but if an `fqn` is specified, the `appID` is ignored and overwritten by the appID of the `fqn` with no message that that is happening.

A principal can't be created with just an `email`. It needs an `fqn` but if you specify the `fqn` with the wrong email than the email gets overwritten by the email of the `fqn`.

Apologies for the list of issues I encountered in a single issue. I'm happy to open a separate issue for each one if that is preferred.

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for opening this issue!
Sadly I am not familiar with `kusto`. Have you ever tried other tools to see if they are working well? Such as calling the `rest api` directly. Usually this kind of problem is caused by the service side.
Or if you can provide more information, I can do the investigation for you. Thanks!
