### ISSUE TITLE
go-autorest breaking things?

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#655]
Hi

Just did a merge from dev and I'm getting the build error:

.\client.go:78: undefined: autorest.NewRetriableRequest

I noticed that there was a recent upgrade to autorest 8.1.0, is that causing this?
I've repeated my go get on go-autorest, but no luck.

Suggestions?

**Comment by mcardosos** [comment]
Hello Ken!
Yes, it is because of 8.1.0 :) Try `go get -u github.com/Azure/go-autorest`
