### ISSUE TITLE
ListComplete is missing from the ResourceSkusClientAPI

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/azure-sdk-for-go#6559]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/computeapi`
- SDK version e.g. `master`, `latest`, `18.1.0`
`v34.2.0`

- What happened? 
`s.Client.ListComplete undefined (type "github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/computeapi".ResourceSkusClientAPI has no field or method ListComplete)`

Would like to be able to add the `ListComplete` ResourceSkusClient func https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2019-07-01/compute/resourceskus.go#L143 to the ResourceSkusClientAPI https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2019-07-01/compute/computeapi/interfaces.go#L261

I would love to contribute this if it's something that can be fixed but the interfaces.go file is autogenerated so I'm not sure if it's something that I can add and if so how.

**Comment by ArcturusZhang** [comment]
Hi @CecileRobertMichon thanks for opening this issue!
The `XXXAPI` interface is designed to correspond to every method defined in swagger (in your case, is this [swagger](https://github.com/Azure/azure-rest-api-specs/blob/49ca3623a8d853be17a604091a7df03c1f68307d/specification/compute/resource-manager/Microsoft.Compute/stable/2019-04-01/skus.json#L43)). In the swagger definition, `ResourceSkus` only possesses one method - `List`. The `ListComplete` is added by the code generator to make SDK more user friendly. Therefore the `ResourceSkusAPI` will not contain the `ListComplete` method.
Hi @jhendrixMSFT do you want to share a thought about this issue?

**Comment by devigned** [comment]
Hi @ArcturusZhang and @jhendrixMSFT, I think the omission of `ListComplete` was probably an oversight when enumeration / paging was implemented. The interface should probably included this to provide a more accurate representation of the struct.

**Comment by jhendrixMSFT** [comment]
@devigned is correct, it was an oversight when the mock interface was added to the code generator.  I'll get this fixed.

**Comment by ArcturusZhang** [comment]
Closed since this has been fixed in autorest.go v2.1.140
