### ISSUE TITLE
Unauthorized error then listing the repositories in ACR

### ISSUE THREAD

**Issue by vjtm** [Azure/azure-sdk-for-go#6562]
Hi,

I get an "unauthorized error" when trying to listing the repositories from ACR.

NOTE: I use the Azure CLI properly configured because the `az acr  repository list -n test-repo` shows the repositories.

imports:
```
	"github.com/Azure/azure-sdk-for-go/services/preview/containerregistry/runtime/2019-07/containerregistry"
	"github.com/Azure/go-autorest/autorest/azure/auth"
```
snippet code:
```
	authorizer, err := auth.NewAuthorizerFromCLI()
	if err != nil {
		log.Fatal(err)
	}

	client := containerregistry.New("https://test-repo.azurecr.io")
	client.Authorizer = authorizer

	repos, err := client.GetRepositories(context.Background(), "", nil)
	if err != nil {
		log.Fatal(err)
	}

	for _, name := range *repos.Names {
		fmt.Println(name)
	}
```

When I run it I get an Unauthorized message error. But from `az cli` it works fine.
```
FATA[0001] error getting repository images: containerregistry.BaseClient#GetRepositories: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unknown" Message="Unknown service error" Details=[{"errors":[{"code":"UNAUTHORIZED","detail":[{"Action":"*","Name":"catalog","Type":"registry"}],"message":"authentication required"}]}]
```

Thanks!

**Comment by ArcturusZhang** [comment]
Hi @vjtm  thanks for the issue.
Based on my observation on `azure-cli` acr command group, they will do a lot of credential working before actually call the rest api. You can find those procedure [here](https://github.com/Azure/azure-cli/blob/5d66e768c230e824b6329f2defdff6d43367a549/src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py#L283).
I am not familiar with how to authorize the ContainerResgistry. I may suggest you to find some docs about authorizing ACR. If you still have problem about it, you can come back, and I will see if I can fetch some one to provide more useful guide.
