### ISSUE TITLE
Cannot get tags after created NetApp Snapshot resource with tags successfully

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#6577]
### Bug Report

- Import path of package in question: https://github.com/Azure/azure-sdk-for-go/tree/master/services/netapp/mgmt/2019-08-01/netapp
- SDK version: v36.2.0
- Output of `go version`: go version go1.13 windows/amd64

- What happened?
I cannot get tags after created NetApp Snapshot resource with tags successfully.

- What did you expect or want to happen?
I should be able to get tags from the response of snapshot "GET" rest API.

- How can we reproduce it?
1. Create a resource group
2. Create NetApp Account
3. Create NetApp Pool
4. Create NetApp Volume
5. Create NetApp Snapshot with tags using snapshot "Create" rest API
6. Get snapshot resource by snapshot "GET" rest API and there is no tags in the response.

**The http request for snapshot "Create" rest API:**
Http request:
PUT https://management.azure.com/subscriptions/xxxxxx/resourceGroups/neiltestnetappvol-resources/providers/Microsoft.NetApp/netAppAccounts/neiltestnetappvol-netappaccount/capacityPools/neiltestnetappvol-netapppool/volumes/neiltestnetappvol-netappvolume/snapshots/neilsnapshottest?api-version=2019-08-01
Authorization: <your token>
Content-type: application/json

Headers:
access-control-expose-headers: x-ms-request-id,Azure-AsyncOperation,Request-Context,Access-Control-Expose-Headers,x-ms-ratelimit-remaining-subscription-writes,Date,Location,Server,X-Powered-By,x-ms-correlation-request-id,x-ms-routing-request-id,Content-Length
azure-asyncoperation: https://management.azure.com/subscriptions/xxxxxx/providers/Microsoft.NetApp/locations/eastus2/operationResults/eef1fe2e-41d1-442f-8f41-b27c05c534b1?api-version=2019-08-01
cache-control: no-cache
content-length: 646
content-type: application/json; charset=utf-8
date: Wed, 25 Dec 2019 05:11:18 GMT
expires: -1
location: https://management.azure.com/subscriptions/xxxxxx/providers/Microsoft.NetApp/locations/eastus2/operationResults/eef1fe2e-41d1-442f-8f41-b27c05c534b1?api-version=2019-08-01&operationResultResponseType=Location
pragma: no-cache
request-context: appId=cid-v1:xxxxxxx
server: Microsoft-IIS/10.0
x-ms-correlation-request-id: xxxxxxx
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-request-id: xxxxxxxxx
x-ms-routing-request-id: SOUTHEASTASIA:20191225T051119Z:xxxxxxx
x-powered-by: ASP.NET

response:
{
  "id": "/subscriptions/xxxxxx/resourceGroups/neiltestnetappvol-resources/providers/Microsoft.NetApp/netAppAccounts/neiltestnetappvol-netappaccount/capacityPools/neiltestnetappvol-netapppool/volumes/neiltestnetappvol-netappvolume/snapshots/neilsnapshottest",
  "name": "neiltestnetappvol-netappaccount/neiltestnetappvol-netapppool/neiltestnetappvol-netappvolume/neilsnapshottest",
  "type": "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots",
  "location": "eastus2",
  "tags": {
    "env": "test"
  },
  "properties": {
    "provisioningState": "Creating",
    "fileSystemId": "a28fba58-2835-7268-79d2-056e6755f0aa",
    "name": "neilsnapshottest"
  }
}

**The http request for snapshot "Get" rest API:**
http request:
GET https://management.azure.com/subscriptions/xxxxxx/resourceGroups/neiltestnetappvol-resources/providers/Microsoft.NetApp/netAppAccounts/neiltestnetappvol-netappaccount/capacityPools/neiltestnetappvol-netapppool/volumes/neiltestnetappvol-netappvolume/snapshots/neilsnapshottest?api-version=2019-08-01
Authorization: <your token>

headers:
access-control-expose-headers: x-ms-request-id,Request-Context,Access-Control-Expose-Headers,x-ms-ratelimit-remaining-subscription-reads,Date,Server,X-Powered-By,x-ms-correlation-request-id,x-ms-routing-request-id,Content-Length
cache-control: no-cache
content-type: application/json; charset=utf-8
date: Wed, 25 Dec 2019 05:03:03 GMT
expires: -1
pragma: no-cache
request-context: appId=cid-v1:xxxxxx
server: Microsoft-IIS/10.0
x-ms-correlation-request-id: xxxxxx
x-ms-ratelimit-remaining-subscription-reads: 11987
x-ms-request-id: 1xxxxxx
x-ms-routing-request-id: SOUTHEASTASIA:20191225T050304Z:xxxxxxxxx
x-powered-by: ASP.NET

response:
{
  "id": "/subscriptions/xxxxxx/resourceGroups/neiltestnetappvol-resources/providers/Microsoft.NetApp/netAppAccounts/neiltestnetappvol-netappaccount/capacityPools/neiltestnetappvol-netapppool/volumes/neiltestnetappvol-netappvolume/snapshots/neilsnapshottest",
  "name": "neiltestnetappvol-netappaccount/neiltestnetappvol-netapppool/neiltestnetappvol-netappvolume/neilsnapshottest",
  "type": "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots",
  "location": "eastus2",
  "properties": {
    "provisioningState": "Succeeded",
    "snapshotId": "c1976a24-0ee8-3398-598d-9bbf9726b774",
    "fileSystemId": "a28fba58-2835-7268-79d2-056e6755f0aa",
    "name": "neilsnapshottest",
    "created": "2019-12-25T04:59:44Z"
  }
}

**Comment by ArcturusZhang** [comment]
Hi @leonardbf would you please help on this?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
