### ISSUE TITLE
There is a bug with typecasting in Azure Cognitive part

### ISSUE THREAD

**Issue by thesunwave** [Azure/azure-sdk-for-go#6586]
### Bug Report

- import path `.../services/cognitiveservices/v1.0/face"`
- SDK version: `34.0.0`
- Go Version: `go1.13.1 darwin/amd64`

#### What happened?
When I try to call AddPhoto method of Cognitive through a picture that includes more than 1 face remote service returns me an error with description like "there is more 1 face", after that I call the Detect method to get coordinates of required face and then send it again, but AddFace answers me that coordinates are incorrect.

Instead of sending correct coordinates it sends value like this `<int32 Value> <int32 Value> <int32 Value> <int32 Value>`

#### What did you expect or want to happen?
I send coordinates and picture then receive a correct answer with persisted_face_id
#### How can we reproduce it?
Use `face.LargeFaceListClient` and call `AddFaceFromURL` set the valid targetFace with `[]int32{}` and send a request to a mock server to have an opportunity to see the result of that request.

#### Btw, I've found the reason. 

Here we are calling `autorest.Encode("query", targetFace, ",")` and this is the reason of that behavior.
https://github.com/Azure/azure-sdk-for-go/blob/781d9fb592a1818cb7fb8e0855ea9c00b095a9e9/services/cognitiveservices/v1.0/face/largefacelist.go#L288-L290

As we know, `targetFace` is a slice of `int32`, but `autorest.Encode` under the hood wants to get a slice of strings or some types derived from string.
Look: 

https://github.com/Azure/go-autorest/blob/b965d219bd9d10676384ef8f05da2e2441df9829/autorest/utility.go#L143-L157

So, now I don't really understand where we have to fix it. Either in `go-autorest` or here?

**Comment by ArcturusZhang** [comment]
Hi @thesunwave thanks for opening this issue!
I do not think this is a code gen problem, more of the probability is the service side bug. 
When I am checking the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/4dc4ff6b562d666782e11b66aaa5fefe3ebef399/specification/cognitiveservices/data-plane/Face/stable/v1.0/Face.json#L4112) for this service, the `targetFace` is defined as:
```
    "targetFace": {
      "name": "targetFace",
      "in": "query",
      "description": "A face rectangle to specify the target face to be added to a person in the format of \"targetFace=left,top,width,height\". E.g. \"targetFace=10,10,100,100\". If there is more than one face in the image, targetFace is required to specify which face to add. No targetFace means there is only one face detected in the entire image.",
      "type": "array",
      "x-ms-parameter-location": "method",
      "required": false,
      "collectionFormat": "csv",
      "items": {
        "type": "integer",
        "format": "int32",
        "x-nullable": false,
        "maxItems": 4,
        "minItems": 4
      }
    },
```
This means the targetFace in query indeed is an integer array. But the parameters in query is send as a URL, which will be converted to string anyway.
Hi @jhendrixMSFT what do you think about this issue?

**Comment by thesunwave** [comment]
Hi @ArcturusZhang, thanks for the answer. You are right, but `autorest.Encode` which using for convert int32 to string can't do it, there is a bug, or feature (I really don't know) and the function which has to converts types to string just use a reflection package and make this 
```
for i := 0; i < v.Len(); i++ {
    stringSlice =append(stringSlice, v.Index(i).String())
}
```

`v.Index(i).String()` is a reflection and the String() method can't return value from non-string types, instead of this, it returns the name of the type.

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang, thanks for the answer. You are right, but `autorest.Encode` which using for convert int32 to string can't do it, there is a bug, or feature (I don't know) and the function which has to converts types to string just use a reflection package and makes this
> 
> ```
> for i := 0; i < v.Len(); i++ {
>     stringSlice =append(stringSlice, v.Index(i).String())
> }
> ```
> 
> `v.Index(i).String()` is a reflection and the String() method can't return value from non-string types, instead of this, it returns the name of the type.

I see. I will see what I can do about this after the new year's vacation! Happy new year!

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v13.3.2
