### ISSUE TITLE
Failed to get resource Managed Application Definition after created this resource successfully

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#6589]
### Bug Report

- Import path of package in question: https://github.com/Azure/azure-sdk-for-go/tree/master/services/resources/mgmt/2018-06-01/managedapplications
- SDK version: v35.0.0
- Output of `go version`: go version go1.12.7 windows/amd64

- What happened?
It failed to get resource Managed Application Definition and threw below error message after created this resource successfully. After investigated, the property type of isEnabled in local package (https://github.com/Azure/azure-sdk-for-go/blob/781d9fb592a1818cb7fb8e0855ea9c00b095a9e9/services/resources/mgmt/2018-06-01/managedapplications/models.go#L589) is string, however, the property type of isEnabled in the response returned from azure side is boolean. As they are inconsistent, so it encountered property type conversion issue.

- What did you expect or want to happen?
It should get resource Managed Application Definition successfully.

- How can we reproduce it?
1. Create a resource group
2. Create Resource Managed Application Definition
3. Immediately call "Get" go rest api to get resource Managed Application Definition, which returns below error message

- Anything we should know about your environment.
The error message:
Error: Error retrieving Managed Application Definition (Managed Application Definition Name "neiltest2-managedapplicationdefinition" / Resource Group "neiltest2-resources"): managedapplications.ApplicationDefinitionsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal bool into Go struct field ApplicationDefinitionProperties.isEnabled of type string' JSON = '{"properties":{"authorizations":[{"principalId":"xxxx","roleDefinitionId":"xxxxx"}],"isEnabled":true,"lockLevel":"ReadOnly","displayName":"TestManagedApplicationDefinition","description":"Test Managed Application Definition","artifacts":[{"name":"ApplicationResourceTemplate","type":"Template","uri":"https://xxxx/applicationdefinitions/xxxxx/xxx/applicationResourceTemplate.json"},{"name":"CreateUiDefinition","type":"Custom","uri":"https://xxxx/subscriptions/xxx/resourceGroups/neiltest2-resources/providers/Microsoft.Solutions/applicationDefinitions/neiltest2-managedapplicationdefinition/applicationArtifacts/CreateUiDefinition?api-version=2017-09-01"},{"name":"MainTemplateParameters","type":"Custom","uri":"https://management.azure.com/subscriptions/xxxxx/resourceGroups/neiltest2-resources/providers/Microsoft.Solutions/applicationDefinitions/neiltest2-managedapplicationdefinition/applicationArtifacts/MainTemplateParameters?api-version=2017-09-01"}]},"id":"/subscriptions/xxxxxx/resourceGroups/neiltest2-resources/providers/Microsoft.Solutions/applicationDefinitions/neiltest2-managedapplicationdefinition","name":"neiltest2-managedapplicationdefinition","type":"Microsoft.Solutions/applicationDefinitions","location":"eastus","tags":{}}'

  on main.tf line 6, in resource "azurerm_managed_application_definition" "example":
   6: resource "azurerm_managed_application_definition" "example" {

**Comment by ArcturusZhang** [comment]
Hi @olsoro could you please check on this?

**Comment by MSEvanhi** [comment]
This has been fixed in later versions of the SDK: 
github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-07-01/managedapplications
in v39.0.0

**Comment by ArcturusZhang** [comment]
Closed since this get fixed in a higher api-version 2019-07-01
