### ISSUE TITLE
Blob.Properties.ContentLength is modified when GetRange is called.

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-sdk-for-go#659]
GetRange assigns the header values from the response back to the blob properties:

https://github.com/Azure/azure-sdk-for-go/blob/master/storage/blob.go#L215

As a result the Blob.Properties.ContentLength is set to the size of the range request and the size of the blob is lost.

**Comment by mcardosos** [comment]
Fixed :D

**Comment by giventocode** [comment]
Great! Thanks for the fast response and fix.
