### ISSUE TITLE
Azure.Identity Conceptual Docs (with language-specific code samples)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#6598]
This is a tracking item to finish writing Conceptual Documentation for Identity.

This is something @ellismg is driving, but it needs to be expanded with language-specific code samples as well.

Per offline discussion, this conceptual docs will be PR'd to all  azure-sdk language repos and each language-specific package owner will fill-in the language-specific portion in the markdown / docs

**Comment by catalinaperalta** [comment]
Recent push to match cross language docs in these PRs: #14520, #14749. Closing for now. Please reopen if there's something missing.
