### ISSUE TITLE
Several client creator functions have the same doc string.

### ISSUE THREAD

**Issue by cchildress** [Azure/azure-sdk-for-go#6605]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`services/resources/mgmt/2019-05-01/resources`
- SDK version e.g. `master`, `latest`, `18.1.0`
v31.0. Current master appears to be the same.
- output of `go version`
`go version go1.13.1 darwin/amd64`
- What happened?
There are several NewFooClient() functions that also have matching function to allow creation of a client with a specified base URI, but the pairs of functions have identical doc strings and do not document what the base URI is intended to be.
- What did you expect or want to happen?
The doc string should specify what the base URI variant of the functions do.
- How can we reproduce it?
Here are a few examples:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/tags.go#L33-L41
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/resources.go#L34-L42
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/providers.go#L33-L41
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/operations.go#L33-L41
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/groups.go#L34-L42
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/deployments.go#L34-L42
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/deploymentoperations.go#L34-L42
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2019-05-01/resources/client.go#L39-L51
- Anything we should know about your environment.
Don't think so.

**Comment by ArcturusZhang** [comment]
Close this issue, since this has been fixed in autorest.go v2.1.140
This change will take effect in next major version of go SDK
