### ISSUE TITLE
app configuration breaking change:  the api now returns the resource group name in the ID in lowercase now

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#6606]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`"github.com/Azure/azure-sdk-for-go/services/appconfiguration/mgmt/2019-10-01/appconfiguration"`
- SDK version e.g. `master`, `latest`, `18.1.0`
```
[13:07:52] kt@katbook:~/hashi/tf/azure/azurerm▸master$ cat go.mod | egrep "(autorest|Azure)"
	github.com/Azure/azure-sdk-for-go v36.2.0+incompatible
	github.com/Azure/go-autorest/autorest v0.9.3
	github.com/Azure/go-autorest/autorest/date v0.2.0
```
- output of `go version`
```
go version go1.13.1 darwin/amd64
```

- What happened?
Sometime in the last couple days the `appconfiguration` api behaviour changed how it handles resource group names. The resource group name now appears to be returned in lowercase:

put `https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200106130341948219/providers/Microsoft.AppConfiguration/configurationStores/testaccappconf200106130341948219?api-version=2019-10-01`
```
{
	"type": "Microsoft.AppConfiguration/configurationStores",
	"properties": {
		"provisioningState": "Creating",
		"creationDate": "2020-01-06T21:03:57.4444728+00:00",
		"endpoint": "https://testaccappconf200106130341948219.azconfig.io"
	},
	"sku": null,
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200106130341948219/providers/Microsoft.AppConfiguration/configurationStores/testaccappconf200106130341948219",
	"name": "testaccappconf200106130341948219",
	"location": "westeurope",
	"tags": {}
}
```

get `https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200106130341948219/providers/Microsoft.AppConfiguration/configurationStores/testaccappconf200106130341948219?api-version=2019-10-01`
```
{
	"type": "Microsoft.AppConfiguration/configurationStores",
	"properties": {
		"provisioningState": "Succeeded",
		"creationDate": "2020-01-06T21:03:58+00:00",
		"endpoint": "https://testaccappconf200106130341948219.azconfig.io"
	},
	"sku": {
		"name": "free"
	},
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestrg-200106130341948219/providers/Microsoft.AppConfiguration/configurationStores/testaccappconf200106130341948219",
	"name": "testaccappconf200106130341948219",
	"location": "westeurope",
	"tags": {
		"environment": "development"
	}
}
``

- What did you expect or want to happen?
the resource group to be returned in the correct casing as was the previous (and expected behaviour)

- How can we reproduce it?
run terraform app config tests or just do above api calls

<!--
Thanks!
-->

**Comment by ArcturusZhang** [comment]
Hi @jimmyca could you please have a look at this?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
