### ISSUE TITLE
azure-sdk-for-go comaptibility with auto-rest

### ISSUE THREAD

**Issue by goinggood** [Azure/azure-sdk-for-go#665]
# ******/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers
src\******\vendor\github.com\Azure\azure-sdk-for-go\arm\examples\helpers\helpers.go:23: undefined: azure.ServicePrincipalToken
src\******\vendor\github.com\Azure\azure-sdk-for-go\arm\examples\helpers\helpers.go:24: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
src\******\vendor\github.com\Azure\azure-sdk-for-go\arm\examples\helpers\helpers.go:28: undefined: azure.NewServicePrincipalToken

This problem is occurring if it downloads the auto-rest version 8.0.0, but when we manually go get auto-rest version 7.3.0 it is working fine.
Please fix this so that build should automatically pull dependency version.

**Comment by marstr** [comment]
This should be fixed now, as seen [here](https://github.com/Azure/azure-sdk-for-go/blob/738d332d2622d2206d81a83a26d34a40a1d6ab8f/arm/examples/helpers/helpers.go#L23).
