### ISSUE TITLE
Expose App Service inbound IP address properties

### ISSUE THREAD

**Issue by LukeCarrier** [Azure/azure-sdk-for-go#6682]
### Feature Request

The Rest API recently (I don't know what version -- hints on how to find out would be appreciated) started including two properties I need to implement terraform-providers/terraform-provider-azurerm#5333:

`GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Web/sites/my-site`:

```jsonc
{
    // snip
    "properties": {
        // snip
        "inboundIpAddress": "0.0.0.0",
        "possibleInboundIpAddresses": "0.0.0.0",
        "outboundIpAddresses": "0.0.0.0,1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4",
        "possibleOutboundIpAddresses": "0.0.0.0,1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,5.5.5.5,6.6.6.6,7.7.7.7,8.8.8.8,9.9.9.9"
        // snip
    }
    // snip
}
```

How do we go about getting these exposed via the Go SDK?

**Comment by ArcturusZhang** [comment]
Hi @LukeCarrier thanks for the issue!
What is the import path of the go SDK package you are now using? This could be a good start to investigate exactly what rest api spec you need.
By doing a thorough search for the request URL in the spec repo, I found several candidates:
1. https://github.com/Azure/azure-rest-api-specs/blob/8c16b5389045dbecce0a966d385e699330555370/specification/web/resource-manager/Microsoft.Web/stable/2015-08-01/service.json#L8222
1. https://github.com/Azure/azure-rest-api-specs/blob/8c16b5389045dbecce0a966d385e699330555370/specification/web/resource-manager/Microsoft.Web/stable/2016-08-01/WebApps.json#L85
1. https://github.com/Azure/azure-rest-api-specs/blob/8c16b5389045dbecce0a966d385e699330555370/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json#L97
1. https://github.com/Azure/azure-rest-api-specs/blob/8c16b5389045dbecce0a966d385e699330555370/specification/web/resource-manager/Microsoft.Web/stable/2018-11-01/WebApps.json#L97
1. https://github.com/Azure/azure-rest-api-specs/blob/8c16b5389045dbecce0a966d385e699330555370/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L97

**Comment by LukeCarrier** [comment]
@ArcturusZhang the path we're currently using is `github.com/Azure/azure-sdk-for-go/services/web/mgmt/2018-02-01/web`:

https://github.com/LukeCarrier/terraform-provider-azurerm/blob/2642118c55618ac3491179049af38f7f8f07916b/azurerm/internal/services/web/client/client.go#L4

This batch request made by the portal suggests that the field has been available since at least `2018-11-01`:

```json
{
    "requests": [
        {
            "httpMethod": "GET",
            "requestHeaderDetails": {
                "commandName": "WebsitesExtension.GetSite"
            },
            "url": "https://management.azure.com/subscriptions/2989d200-2815-4930-aa0d-e08fdc7215c8/resourceGroups/lp-docs/providers/Microsoft.Web/sites/avado-lp-docs?api-version=2018-11-01"
        }
    ]
}
```

**Comment by ArcturusZhang** [comment]
Well, I searched in 2018-02-01's swagger for inboundIPAddress, but got nothing, either do some newer api versions. 
You can find the corresponding swaggers [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/web/resource-manager/Microsoft.Web/stable)
If this field is not in the swagger, it cannot exposed by the SDK.

**Comment by ArcturusZhang** [comment]
I just did a search in the azure-rest-api-specs repo, there are no PRs for Microsoft.Web in progress now.

**Comment by LukeCarrier** [comment]
@ArcturusZhang yep, that was my result too. Wouldn't additional fields in responses that aren't documented in Swagger constitute API breakage in the `Microsoft.Web` service, or does this only apply to documented fields?

This seems like an oversight as, without that field, I can't automate configuring the A records I need to point the apex of a domain at a Website or Functions App.

I'm not sure where I'm supposed to report this -- can you direct me toward the maintainers?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang yep, that was my result too. Wouldn't additional fields in responses that aren't documented in Swagger constitute API breakage in the `Microsoft.Web` service, or does this only apply to documented fields?
> 
> This seems like an oversight as, without that field, I can't automate configuring the A records I need to point the apex of a domain at a Website or Functions App.
> 
> I'm not sure where I'm supposed to report this -- can you direct me toward the maintainers?

Well, I do not really catch your point. but if you are saying that there is a field called `inboundIPAddress` in the response, but the swagger definition of the response do not have this field, this should be a rest api bug, which goes to the [azure rest api spec](https://github.com/Azure/azure-rest-api-specs) repo. You can file your issue there with some context.

**Comment by LukeCarrier** [comment]
I'll chase this in the API spec repository then, thanks @ArcturusZhang.

FWIW I think a bit of signposting would go a long way in these SDK repositories -- the layers of abstraction are quite difficult to follow when you're outside of Microsoft and don't have access to the documentation that's kept behind closed doors.
