### ISSUE TITLE
Is "Create a standalone managed disk" supported now?

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-sdk-for-go#670]
I could find that create a VM with a managed disk is already supported. My question is "Create a standalone managed disk" already supported now? I could only find managed disk related code in arm/compute which is for VM, thanks.

**Comment by andyzhangx** [comment]
It looks like a silly question, create a disk in a VM with managed disk should create a managed disk

**Comment by marstr** [comment]
You are correct, you can find code on interacting just with disks here:
[github.com/Azure/azure-sdk-for-go/arm/disk](https://github.com/Azure/azure-sdk-for-go/blob/59c277f1b488b81b1a5f944212f25b69bea8ece3/arm/disk/)
