### ISSUE TITLE
Data Lake Store Filesystem Create converts stream to JSON string

### ISSUE THREAD

**Issue by arsenvlad** [Azure/azure-sdk-for-go#671]
It appears this line is a bug:

https://github.com/Azure/azure-sdk-for-go/blob/b558f7a651d50f9b2256b1f45abfef9e92efdfae/datalake-store/filesystem/filesystemgroup.go#L478

Shouldn't it be doing WithFile() instead of WithJson() here?

As is currently, it stores {Reader} in the file content.

**Comment by marstr** [comment]
Howdy, I've validated that you are correct that we should be encoding this as a file, as per the Swagger definition here:
[Azure/azure-rest-api-specs/arm-datalake-store/filesystem/2016-11-01/filesystem.json#721](https://github.com/Azure/azure-rest-api-specs/blob/156cd442edf6badb940149878cecfba2d3198776/arm-datalake-store/filesystem/2016-11-01/swagger/filesystem.json#L721)

I'll investigate how the [Go AutoRest Generator](https://github.com/Azure/autorest/tree/master/src/generator/AutoRest.Go) is supposed to handle this.

**Comment by jzampieron** [comment]
Can confirm that I'm seeing this issue as well: `{"Reader":{}}` are the data contents of all the files.

**Comment by jhendrixMSFT** [comment]
This is a bug in the generator, I will have a fix later today.
