### ISSUE TITLE
Data Lake Store Filesystem named "GroupClient"

### ISSUE THREAD

**Issue by arsenvlad** [Azure/azure-sdk-for-go#672]
Why is the client of Data Lake Store File system call "GroupClient" instead of something Azure Data Lake Store filesystem related?

https://github.com/Azure/azure-sdk-for-go/blob/b558f7a651d50f9b2256b1f45abfef9e92efdfae/datalake-store/filesystem/filesystemgroup.go#L37

**Comment by marstr** [comment]
Howdy @arsenvlad, it's a good question and naming has certainly been something we spend a lot of time wringing our hands about. In this case, the best answer I have for you is that there is the potential for their to be operations that don't pertain to FileSystemGroups, but still pertain to DataLake Store Files. For that reason, we try to name clients as locally to the functionality they represent as possible.
