### ISSUE TITLE
add DiskState in disk-model-Properties struct

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-sdk-for-go#675]
I could find "diskState" in get managed disk REST api, which is used to tell whether a disk is attached or not, it's useful in the disk attach/detach scenario. Would you add this field in arm/disk-model-Properties sturc, thanks.
Below is the api spec:
https://docs.microsoft.com/en-us/rest/api/manageddisks/disks/disks-get

**Comment by marstr** [comment]
Howdy @andyzhangx, thanks for filing this issue! I've filed a new issue in the Swagger repository to address this.

-Martin
