### ISSUE TITLE
[Service Package Request] azure front door 2019-10-01

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-go#6758]
### Service Package Request

I'm looking for the API version 2019-10-01 of front door included in this pull request 
https://github.com/Azure/azure-rest-api-specs/pull/7221

There's support in the .net and python SDKs but it appears to be missing here
https://github.com/Azure/azure-sdk-for-go/tree/master/services/frontdoor/mgmt

**Comment by ArcturusZhang** [comment]
Hi @timja thanks for the issue. I will release this package soon.

**Comment by ArcturusZhang** [comment]
Hi @timja the requested packages will be released in [this pr](https://github.com/Azure/azure-sdk-for-go/pull/6776)

**Comment by ArcturusZhang** [comment]
These packages has been released: https://github.com/Azure/azure-sdk-for-go/releases/tag/v38.1.0
