### ISSUE TITLE
Front Door: The casing of the HealthProbeSettings is not consistent

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-sdk-for-go#6762]
### Bug Report
- import path: `azure-sdk-for-go/services/frontdoor/mgmt/2019-04-01/frontdoor`
- SDK version: `v35.0.0`
- go version: `go1.12.5 linux/amd64`

### Description:
The casing of the HealthProbeSettings is not consistent:

In the backendPools block the casing of the HealthProbeSettings is (notice the lowercase 'h'):
portal-front-door/ -> healthProbeSettings/healthProbeSettings-1571100669337

but in the HealthProbeSettings block the casing of the HealthProbeSettings is (notice the uppercase `H`):
portal-front-door/ -> HealthProbeSettings/healthProbeSettings-1571100669337

**Expectation:**
The casing should be consistent.

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
