### ISSUE TITLE
Add support for writing data to Log Analytics

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-go#685]
Seems the current operational insights go is about managing workspaces, sources, etc. To enable custom resources to log data, it would be great if the SDK supported creating and hashing the signature and sending associative maps as log data.

**Comment by marstr** [comment]
Howdy @heaths,

If I'm reading this correctly, it sounds like you're looking to update the actual Azure Insights service, not just the way in which we communicate it. While this falls outside of the scope of our repository, I'll make sure that this feedback gets passed along to the appropriate people.

Thanks for your interest in our SDK!

-Martin
