### ISSUE TITLE
FrontDoorTlsProtocolType missing after 2019-04-01

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-go#6882]
### Bug Report

- import path of package in question, e.g. `.../services/frontdoor/mgmt/2019-11-01/frontdoor`
- 38.1.0
- output of `go version`
go version go1.13 darwin/amd64

Hi 👋 

I'm trying to upgrade terraform to the newest version of the SDK, it seems that FrontDoorTlsProtocolType is missing after 2019-04-01.
But it still appears to be in the rest api spec? 

Something wrong in the generation? https://github.com/Azure/azure-rest-api-specs/blob/master/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-05-01/frontdoor.json#L1395-L1405

(I can't see a frontdoor.json after 2019-05-01 so I assume that means the API spec hasn't changed since then, that's also the version that the constant disappeared in).

https://github.com/Azure/azure-sdk-for-go/blob/master/services/frontdoor/mgmt/2019-04-01/frontdoor/models.go#L775
https://github.com/Azure/azure-sdk-for-go/blob/master/services/frontdoor/mgmt/2019-11-01/frontdoor/models.go#L974

- What happened?
Missing field FrontDoorTlsProtocolType

- What did you expect or want to happen?
The field to be there
- How can we reproduce it?
Look at above links
- Anything we should know about your environment.

https://github.com/terraform-providers/terraform-provider-azurerm/pull/5385

**Comment by ArcturusZhang** [comment]
Hi @timja thanks for the issue.
You are correct, the spec for frontdoor is the same as 2019-05-01, you can find the corresponding spec definition in the [readme file](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/frontdoor/resource-manager/readme.md#tag-package-2019-11)
As for the `FrontDoorTlsProtocolType` type, as you see in the sdk repo, the `model.go` file has not been changed since `v34.0.0`. I will have some investigation on why that happens. In the mean time, that field is an enum, and it could only have one possible value: `ServerNameIndication`, you could just hard code that value as a workaround for now.

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT could you please have an explanation from the code gen side why it differs from [2019-04-01](https://github.com/Azure/azure-sdk-for-go/blob/a667766659ee442f09a8695ae8c675ebf0e1d188/services/frontdoor/mgmt/2019-04-01/frontdoor/models.go#L775) and [2019-05-01 (and higher)](https://github.com/Azure/azure-sdk-for-go/blob/a667766659ee442f09a8695ae8c675ebf0e1d188/services/frontdoor/mgmt/2019-05-01/frontdoor/models.go#L809)?

**Comment by timja** [comment]
(As you can see in the linked PR I’ve hard coded it with a link to this issue)

**Comment by jhendrixMSFT** [comment]
This enum has one value and is required.  In this case the codegen is supposed to treat it as a constant, i.e. you shouldn't be able to even set the field, the value is sent without user intervention.  This works for constant parameter values but is apparently broken for model properties.  Will work on a fix.

**Comment by chamons** [comment]
I just tested latest autorest.go and this is what it generated:

```go
// FrontDoorTLSProtocolType - Defines the TLS extension protocol that is used for secure delivery
type FrontDoorTLSProtocolType string

...
type CustomHTTPSConfiguration struct {
	// REQUIRED; Defines the source of the SSL certificate
	CertificateSource *FrontDoorCertificateSource `json:"certificateSource,omitempty"`

	// REQUIRED; The minimum TLS version required from the clients to establish an SSL handshake with Front Door.
	MinimumTLSVersion *MinimumTLSVersion `json:"minimumTlsVersion,omitempty"`

	// REQUIRED; Defines the TLS extension protocol that is used for secure delivery
	ProtocolType *FrontDoorTLSProtocolType `json:"protocolType,omitempty"`

	// Parameters required for enabling SSL with Front Door-managed certificates (if certificateSource=FrontDoor)
	FrontDoorCertificateSourceParameters *FrontDoorCertificateSourceParameters `json:"frontDoorCertificateSourceParameters,omitempty"`

	// KeyVault certificate source parameters (if certificateSource=AzureKeyVault)
	KeyVaultCertificateSourceParameters *KeyVaultCertificateSourceParameters `json:"keyVaultCertificateSourceParameters,omitempty"`
}

I am uncertain if that means this is fixed, or broken worse given your comment on constants @jhendrixMSFT 


```

**Comment by lirenhe** [comment]
@timja, could you help to confirm whether this problem is fixed in the latest version of the SDK?
https://github.com/Azure/azure-sdk-for-go/tree/main/services/frontdoor/mgmt/2020-11-01/frontdoor

**Comment by timja** [comment]
From @chamons comment it's not fixed.

Nothing appears to have changed:
https://github.com/Azure/azure-sdk-for-go/blob/da4167617ea762d2b4e17f8c0798073c679251a2/services/frontdoor/mgmt/2020-11-01/frontdoor/models.go#L277

According to @jhendrixMSFT this should just be a constant and not be settable.

(note I haven't tried to upgrade and I raised this nearly 2 years ago so just doing my best from checking the code)

**Comment by jhendrixMSFT** [comment]
Unfortunately, I misspoke earlier.  When the enum is marked as `modelAsString: true`, it means that this enum should be treated as extensible, i.e. more values might be added in the future.  In this case, it's not treated as a constant, so callers are expected to provide the value, even if there's only one to choose from.
