### ISSUE TITLE
Error occurred during fetching list of certificates using certificate client

### ISSUE THREAD

**Issue by shreyakanika15** [Azure/azure-sdk-for-go#695]
Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal array into Go value of type web.CertificateCollection. I have attached logs of error and go code file which is returning the error.
[mynewserver.pdf](https://github.com/Azure/azure-sdk-for-go/files/1174010/mynewserver.pdf)
.

[Log_error.pdf](https://github.com/Azure/azure-sdk-for-go/files/1173998/Log_error.pdf)

**Comment by marstr** [comment]
Howdy @shreyakanika15, mind including the release/commit of the Azure SDK for Go that you're using?

**Comment by marstr** [comment]
Thank you for providing a high-quality repro, it made debugging this a snap. I've opened up a bug in the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repository that addresses the underlying issue causing your failure. I'll close this issue for now, but will re-open it if there is further action that can be taken in this repository.
