### ISSUE TITLE
Update Container Registry SDK

### ISSUE THREAD

**Issue by juliusl** [Azure/azure-sdk-for-go#6971]
### Service Package Request

Hi I'm from ACR. I need to update our Container Registry SDK with the latest Swagger spec. 

Creating this issue for tracking and discussion.

Is there an automated pipeline to get the new generated files or do I need to do this manually and submit a PR?

**Comment by juliusl** [comment]
Spec:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerregistry/data-plane/Microsoft.ContainerRegistry/preview/2019-08-15/containerregistry.json

My fork with changes:
https://github.com/juliusl/azure-sdk-for-go/tree/pr/update-containerregistery

**Comment by ArcturusZhang** [comment]
Hi @juliusl thanks for this issue!
There is a automated pipeline for the SDK generation now.
For service package request from microsoft employees, please go to the [open api hub](aka.ms/openapihub) to submit a package request.
I notice that this api-version does not have a tag in the [readme.go.md](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerregistry/data-plane/readme.go.md), therefore i will first submit a PR to add that missing tag for the 2019-08-15 api-version, then you can fill the release request on open api hub and targeting to that PR.
Meanwhile, go SDK has a routine monthly major release, which will generate and release all valid swagger in the spec repo. Therefore wait for the major release (which will happen by the end of this month) is also an option for you.

**Comment by ArcturusZhang** [comment]
Hi @juliusl I have submitted a [PR](https://github.com/Azure/azure-rest-api-specs/pull/8171) for this.
Please submit the release request after this PR get merged.
Or wait for the end of month's major release also works.

**Comment by juliusl** [comment]
@ArcturusZhang Thanks!

**Comment by juliusl** [comment]
(@ArcturusZhang the open api hub link you have in your comment is broken)

**Comment by ArcturusZhang** [comment]
> (@ArcturusZhang the open api hub link you have in your comment is broken)

My bad. It should be https://aka.ms/openapihub
