### ISSUE TITLE
PermissionsClient doesn't retry on failed request (with no response received from server)

### ISSUE THREAD

**Issue by yuwaMSFT2** [Azure/azure-sdk-for-go#714]
We are using PermissionsClient to talk to ARM. However if the request fails due to:
1. connection timeout
2. connection being reset by remote
3. Other cases before client receive response status
The failed request is not retried.

The client is calling autorest Client.Do, which will only retry on a list of known status code. If no status code, no retry. Should we retry on these failures as well? It would be simply retry if err != nil in DoRetryForStatusCodes in autorest package or implement the logic in the PermissionClient.

This is authorization package v5.0.0-beta-14-g3b12823.

**Comment by yuwaMSFT2** [comment]
@marstr @DavidObando @SajayAntony @mcardosos @sivagms

**Comment by marstr** [comment]
In general, retooling Retry to be more flexible is something we've talked about but hasn't been high on our priority list. Honestly, I'd say that your best bet is to submit a PR to the go-autorest repository if you'd like it done anytime soon. I'm happy to chat about design ideas!

**Comment by jhendrixMSFT** [comment]
Fixed in go-autorest v9.3.1.
