### ISSUE TITLE
Create Azure website

### ISSUE THREAD

**Issue by aishukc** [Azure/azure-sdk-for-go#7141]
Hello all,
I am very new to azure-sdk-for-go and I am trying to create a static Azure website. However, I am not able to find right method/documentation for the job. 
I am trying to replicate following command : 
`az webapp up --sku F1 -n appname --html -l location`

It would of great help if you could point me to correct resources.

**Comment by ArcturusZhang** [comment]
Hi @aishukc thanks for this issue.
Based on the cli command you gave, the description of that command says:
```
Create a webapp and deploy code from a local workspace to the app. The command is required to run from the folder where the code is present. Current support includes Node, Python, .NET Core and ASP.NET. Node, Python apps are created as Linux apps. .Net Core, ASP.NET, and static HTML apps are created as Windows apps. Append the html flag to deploy as a static HTML app.
```
This seems to be a composite command designed in azure-cli to bring more convenient experience.
Go SDK currently does not support such method, all of the methods in the SDK is auto-generated from the rest api specs. Therefore if you are intending to use go SDK to achieve the same purpose, you must do everything on your own. The methods you need should be [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2019-08-01/web/apps.go) (you may want to open this file on your local machine, it is too big).
Purely based on the description, this command `create`s a webapp (corresponding to the `CreateOrUpdate` method) and `deploy`s code (I do not find which method is corresponding to this operation).
To find out, you can run your cli command with a `--debug` flag. In this way, cli will print every rest api request to stdout. With the rest api call, you can find the corresponding go SDK method.
If you are not sure how to find the go SDK method by rest api call, you can paste your debug log in this issue.
