### ISSUE TITLE
x509: failed to load system roots and no roots provided on Dockers

### ISSUE THREAD

**Issue by salmanbukhari** [Azure/azure-sdk-for-go#715]
I am trying to use Azure-sdk-for-go on Dockers but I am getting error 

> ERROR: 2017/08/02 08:34:18 azure_sdk_services.go:435: azure.ServicePrincipalToken#Refresh: Failure sending request for Service Principal {subscription_id}: StatusCode=0 -- Original Error: Post https://login.microsoftonline.com/{subscription_id}/oauth2/token?api-version=1.0: x509: failed to load system roots and no roots provided

I am using Ubuntu 14.04.5 LTS on docker version 17.05.0-ce
Can anyone guide me what should I do? I read somewhere that it is related to certificates.

**Comment by marstr** [comment]
Howdy @salmanbukhari, Sorry for the delay in getting back to you here.

This isn't an issue that I've run into before, but doing a little poking around, it looks like a quasi-common issue with using HTTPS from inside of a container. For what it's worth, I found a help thread here for you: http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/

I'm going to close this out for now, as it doesn't seem like there is an actionable request for our team. If you do run into a case where [our Auth library](https://github.com/Azure/go-autorest/tree/0545944f0d7822e1c75b036402f6ca4a1ce7e570/autorest/adal) is getting in the way, definitely let us know!
