### ISSUE TITLE
Update EventHubs SDK to `2017-04-01`

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#721]
👋🏻 hey all

We've had [a request come in to add support for Auto Inflate within EventHubs](https://github.com/terraform-providers/terraform-provider-azurerm/issues/168).

Taking a quick look into this I can see they've been [added to the Swagger in API Version `2017-04-01`](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/eventhub/resource-manager/Microsoft.EventHub/2017-04-01/EventHub.json#L1428), however the SDK currently uses `2015-08-01`.

Would it be possible to update to this version of the EventHubs Swagger at some point? :)

Thanks!

**Comment by marstr** [comment]
Howdy @tombuildsstuff,

I dug into this a bit today and confirmed that the next time we generate we'll include EventHub's 2015-08-01.

We'll start thinking seriously about whether or not we can wait for my experimental branch to merge into master or not, or if we need another intermediate refreshed SDK.

Either way, the action of ensuring that we use the updated version the next time we gen is done, so I'm going to close this out. :)

-Martin
