### ISSUE TITLE
Add modules to manage network.ApplicationGateway resources as done with network.LoadBalancer

### ISSUE THREAD

**Issue by boillodmanuel** [Azure/azure-sdk-for-go#7234]
### Feature Request

Hello,

network.ApplicationGateway provides only 1 module :
- applicationgateways.go [MAIN]

network.LoadBalancer provides 7 modules : 
- loadbalancers.go [MAIN]
- loadbalancerbackendaddresspools.go
- loadbalancerfrontendipconfigurations.go
- loadbalancerloadbalancingrules.go
- loadbalancernetworkinterfaces.go
- loadbalanceroutboundrules.go
- loadbalancerprobes.go

The Azure cli for ApplicationGateway provides 20 modules, see  here: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest

Could you add the missing modules in the SDK?

**Comment by ArcturusZhang** [comment]
Hi @boillodmanuel thanks for this issue.
But unfortunately this feature request cannot be addressed.
The go SDK is auto-generated from the [rest api specs](https://github.com/Azure/azure-rest-api-specs) by [autorest](https://github.com/Azure/autorest), and it is designed to be a library corresponding to the rest-api. If the rest api does not support those methods you listed, the go SDK cannot contain them. In fact, the rest api allows you use the `CreateOrUpdate` method directly modify the loadbalancer instance to achieve those purpose.
In the meantime, azure-cli is carefully designed manually and written by humans.
Therefore I will close this issue, sorry about this.

**Comment by boillodmanuel** [comment]
I understand @ArcturusZhang, but in this case, this could worth to move the issue to correct github repository or ask me to create the issue in the correct repo.
Otherwise, feedbacks will be lost... 
And it could be great to mention it in `README.md`

**Comment by ArcturusZhang** [comment]
> I understand @ArcturusZhang, but in this case, this could be worth to move the issue to correct github repository or ask me to create the issue in the correct repo.
> Otherwise, feedbacks will be lost...
> And it could be great to mention it in `README.md`

Well, you could raise an issue ask for the api to create those resources independently in the [azure-rest-api-specs repo](https://github.com/Azure/azure-rest-api-specs/issues). I could tag your issue there so the service team will have a look at that issue.

**Comment by boillodmanuel** [comment]
Here is the azure-rest-api-specs issue: https://github.com/Azure/azure-rest-api-specs/issues/8252
