### ISSUE TITLE
Clarification over branches

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#726]
Hi

I see it's a while since anything was committed to the dev branch, but master has some recent changes. Have all the changes been merged into master? 

Merely curious since I've started updating the https://github.com/Azure-Samples/storage-blob-go-getting-started  to give blob/table/queue examples but it wasn't clear (to me) if master had all the new changes or if things were still happening in dev.

Cheers

Ken

**Comment by marstr** [comment]
Howdy @kpfaulkner, sorry for the delay in responding to this!

We may have developed some bad habits, but in principal your former understanding is still correct. 

The idea is that we make improvements and do feature work in either a dedicated feature branch or the `dev` branch. While in isolated branches, we test them, break them, then eventually feel good about it and merge them into the `master`. We make an exception for bug fixes that we want to include as hot patches, those go directly in `master`.

However, as you've noticed, we've developed some bad habits and should really get back to being diligent about having PRs target `dev` by default.
