### ISSUE TITLE
Azure SQL Database SDK succeeds creating database of name "azure" which is prevented from portal as it is a reserved word

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-sdk-for-go#7265]
### Bug Report

- import path of package in question : "github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2015-05-01-preview/sql"
- SDK version : master
- output of `go version`: go version go1.13.7 darwin/amd64

- What happened?
I am using the Azure SQL database client in the above package to create a SQL database given the resource group and SQL server. I expect the behavior I see when using the SDK to mirror what I see from the portal. From the portal, when I try to create a database of name "azure", the name validation fails as it is a reserved word. However, I am able to successfully create a database of name "azure" using the SDK. 

- What did you expect or want to happen?
I expected the SDK to fail to create the Database as the name I provided is  a reserved word

- How can we reproduce it?
* Try creating a SQL database of name "azure" in the portal. Check that it doesnt allow you to create this.
* Now use the following function to create a database from code and use the name "azure" as the database name. Note that this will succeed.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/2015-05-01-preview/sql/databases.go#L145

**Comment by ArcturusZhang** [comment]
Hi @jananivMS thanks for the issue.
I believe this is either swagger side or service side problem. Therefore I tagged this issue so the corresponding service team will have a look at this issue.

**Comment by jaredmoo** [comment]
Thank you for the feedback. Let me ask around to find out what the correct behaviour should be here.

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
CSEF365118
</details>

**Comment by lirenhe** [comment]
@jaredmoo and @scgbear, do you have any conclusion about what the correct behavior is for SQL database of name "azure"?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
