### ISSUE TITLE
KeyVault: CheckNameAvailability for KeyVault returns a value different from the enum defined for KeyVault

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-sdk-for-go#7266]
### Bug Report

- import path of package in question: "github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2018-02-14/keyvault"
- SDK version: master
- output of `go version`: go version go1.13.7 darwin/amd64

- What happened?
I am using the above SDK to check the validity for a KeyVault name using the below snippet. KeyVault SDK has an enum defined as "keyvault.AccountNameInvalid" that is one of the possible values. However, the API actually returns "Invalid" and so I cannot just compare to the keyvault enum.

```// Check if keyvault name is valid
	vaultNameCheck := keyvault.VaultCheckNameAvailabilityParameters{
		Name: to.StringPtr(vaultName),
		Type: to.StringPtr("Microsoft.KeyVault/vaults"),
	}
	result, err := vaultsClient.CheckNameAvailability(ctx, vaultNameCheck)
	if err != nil {
		return keyvault.Vault{}, err
	}
	if result.Reason == keyvault.Reason("Invalid") || result.Reason == keyvault.AccountNameInvalid {
		return keyvault.Vault{}, fmt.Errorf("AccountNameInvalid")
	} else if result.Reason == keyvault.AlreadyExists {
		return keyvault.Vault{}, fmt.Errorf("AlreadyExists")
	}```

- What did you expect or want to happen?

We should either change the enum or change what we return to the string that the enum defines. I expect that return values to be one of the defined enums.

- How can we reproduce it?
Use the above code snippet with an invalid vault name

**Comment by ArcturusZhang** [comment]
Hi @jananivMS thanks for the issue.
I suspect this is caused because the keyvault service has changed their return value. A new major version of go SDK is on its way. After the new version is released, please update your SDK and have another try to see if this is resolved.

**Comment by jananivMS** [comment]
I can use the new one when it is released. But does that mean the current SDK will not be fixed? Any ETAs on when the next version will be released?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArcturusZhang** [comment]
> I can use the new one when it is released. But does that mean the current SDK will not be fixed? Any ETAs on when the next version will be released? Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: Arcturus <notifications@github.com> Sent: Wednesday, January 29, 2020 10:08:35 PM To: Azure/azure-sdk-for-go <azure-sdk-for-go@noreply.github.com> Cc: Janani Vasudevan <jananiv@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [Azure/azure-sdk-for-go] KeyVault: CheckNameAvailability for KeyVault returns a value different from the enum defined for KeyVault (#7266) Hi @jananivMS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FjananivMS&data=02%7C01%7Cjananiv%40microsoft.com%7C02c88322a5f64e1caa4508d7a542766c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637159577217282476&sdata=8UFPFFunTV6i3VUWuV9L88MaNchaS%2BVK7DDETauPvD0%3D&reserved=0> thanks for the issue. I suspect this is caused because the keyvault service has changed their return value. A new major version of go SDK is on its way. After the new version is released, please update your SDK and have another try to see if this is resolved. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-go%2Fissues%2F7266%3Femail_source%3Dnotifications%26email_token%3DAL2HWUK2EOUOF46HDFA6RKDRAJOFHA5CNFSM4KNLXT32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKJWPMI%23issuecomment-580085681&data=02%7C01%7Cjananiv%40microsoft.com%7C02c88322a5f64e1caa4508d7a542766c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637159577217282476&sdata=qntVAnylg3AMTevOGQFF23Uwf47oiNscI8now0r9rac%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL2HWUPCYOAUBZMF2LMPLKLRAJOFHANCNFSM4KNLXT3Q&data=02%7C01%7Cjananiv%40microsoft.com%7C02c88322a5f64e1caa4508d7a542766c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637159577217292435&sdata=4KcNFU59F5HvNo7YPbQA1Qzrh5mM91lOz%2BFxL6YAzMw%3D&reserved=0>.

`v39.0.0` has been released. You can have a try with the same package using this new version of SDK.
To clarify, by "new SDK version", I mean the version of SDK itself, not the api-version you are using now (2018-02-14).

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
CSEF365120
</details>
