### ISSUE TITLE
Azure Container Instance support

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#727]
Hi!
There is a new compute service called [Azure Container Instance](https://docs.microsoft.com/en-us/azure/container-instances/)

Are there any plans for introducing this into the SDK?

Thanks!

**Comment by tombuildsstuff** [comment]
+1 - I'd been meaning to file a bug about this on the Rest API Specs Repository - although from what I could see there's no API documentation for this yet either?

**Comment by mcardosos** [comment]
Hello!

There's a preview version for this service [here](https://github.com/Azure/azure-rest-api-specs/tree/current/specification/containerinstance/resource-manager), so I can update and release the SDK to include this. I'll let you know when it is ready.

Little note, this API is still on preview, so there could be breaking changes in the future.

**Comment by radu-matei** [comment]
Great, thanks for the reply :)

**Comment by mcardosos** [comment]
@radu-matei @tombuildsstuff 
[Container Instance SDK](https://github.com/Azure/azure-sdk-for-go/tree/master/arm/containerinstance) is ready!

**Comment by radu-matei** [comment]
@mcardosos That was fast, awesome!
Thanks!

**Comment by tombuildsstuff** [comment]
@mcardosos awesome, thanks! :)
