### ISSUE TITLE
Table Service SDK Deprecated

### ISSUE THREAD

**Issue by thinkdavid** [Azure/azure-sdk-for-go#7278]
### Question about Deprecation

Is there a plan for continuing the SDK for the Table Service? The README says the storage sdk for Go is being deprecated but contains links to new SDK's for files/blobs/queues but not for tables. If one wants to programmatically insert to tables -- what service should they use going forward?

Thanks,
David

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT do you have any comment about this?

**Comment by takekazuomi** [comment]
In my opinion, in .NET, the Table SDK has moved to the cosmos DB SDK and has been removed from the Azure SDK.
Azure golang SDK also removed table SDK, but golang cosmos DB SDK does not support Table API. This is a big problem.

**Comment by jhendrixMSFT** [comment]
There is still functionality for interacting with table storage in the `./storage` package, however this package isn't under active development.  The POR is to generate a new swagger-based package for table storage however this hasn't happened yet.  While I can't commit to any timeline I will follow up to see what happened to the swagger for table storage.  In the meantime are you able to use what's available?

**Comment by thinkdavid** [comment]
In the meantime, yes the current one works. I just wanted to avoid running into issues down the road if I begin coding the service now using it.

**Comment by jhendrixMSFT** [comment]
Understood.  And to clarify my earlier statement, even though we're not actively adding features to this package we will continue to support it until we have a replacement ready.

**Comment by vijayrajah** [comment]
@jhendrixMSFT Any updates on this ?

**Comment by jhendrixMSFT** [comment]
We've started work on a track 2 implementation of table storage, please see https://github.com/Azure/azure-sdk-for-go/pull/14441.  Sorry I don't yet have an ETA on when this would be tagged and consumable.

**Comment by jhendrixMSFT** [comment]
We've released a beta of our new tables package, [`aztables`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables).  This is the package you want to use going forward.
