### ISSUE TITLE
apimanagement 2019-12-01-preview

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-go#7281]
### Service Package Request

https://github.com/Azure/azure-rest-api-specs/pull/8225

Terraform issue:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3203

**Comment by ArcturusZhang** [comment]
Hi @timja thanks for this issue.
I am working on this [now](https://github.com/Azure/azure-rest-api-specs/pull/8291) and it will be released soon.

**Comment by ArcturusZhang** [comment]
This package has been released in v39.1.0
