### ISSUE TITLE
Update Existing Track 2 Build - Cross-Plat/Linting

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-go#7296]
Currently, CI is triggered from a single [here](https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/ci.yml)

However, notice that the triggers explicitly exclude the track 2 packages. We need to get one up and running that _does_ trigger off the track 2 packages. Not only this, but we'd also prefer that the builds scoped to just the relevant packages as well.

I'm going to take the opportunity here to get the ymls working like they do in the other repos. Ex:
- Release template pulled in from `azure-sdk-build-tools`
- `ci.yml` per service directory, calling a standardized build template

@jhendrixMSFT @catalinaperalta Anything I'm missing? Do we want to make updates to the build-matrix while I'm here?

**Comment by scbedd** [comment]
Current Steps. Checkmarks where I intend to transfer.

- [x] Vet
- [x] Build
- [x] Run Tests
- [ ] Display Breaking Changes
- [ ] Verify Package Directory
- [x] Copyright Header Check
- [x] Format Check
- [x] Linter Check

**Comment by jhendrixMSFT** [comment]
The linter check will fail on `azcore` which is why I omitted it in the track 2 CI.  I want to look into using something like https://github.com/golangci/golangci-lint which is much more powerful, just haven't had the time yet.

**Comment by scbedd** [comment]
I'll take a look at this Joel. The release furior should be ended now. When I add the linting stuff, I'll check this out.
