### ISSUE TITLE
PostrgeSQL servers CreateOrUpdate function does not marshal Server struct in response

### ISSUE THREAD

**Issue by dave-read** [Azure/azure-sdk-for-go#732]
The [CreateOrUpdate](https://github.com/Azure/azure-sdk-for-go/blob/v10.2.1-beta/arm/postgresql/servers.go#L43) function for PostgreSQL servers defines a Server channel as one of the return values.

```
CreateOrUpdate(
    resourceGroupName string,
    serverName string, 
    parameters ServerForCreate, 
    cancel <-chan struct{}
) (<-chan Server, <-chan error)
```
The Sender includes a `azure.DoPollForAsynchronous` decorator.  So the function blocks until the operation completes.   The polling logic uses the URL from the **Azure-AsyncOperation** HTTP Response header, so the format of each poll operation returns a structure like this:

```
{
  "name":"ebddb3a6-c75c-40fe-ab87-77ea7a5c9d70",
  "status":"InProgress",
  "startTime":"2017-08-21T04:45:14.243Z"
}
```

When the status changes to "Succeeded", it looks like that response is what's unmarshalled into the Server struct defined for the result channel.
```
{
  "name":"ebddb3a6-c75c-40fe-ab87-77ea7a5c9d70",
  "status":"Succeeded",
  "startTime":"2017-08-21T04:45:14.243Z"
}
```
So you end up with a Server struct with only the ```name``` property populated with the async operation id value.

In looking at the async polling code, it's using the URI from the **Azure-AsyncOperation** header in the original request as the polling endpoint.  That's one of the possible [approaches](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations), but I think requires an additional GET against the original resource endpoint or the value from the **Location** header to get the state of the created resource.

**Comment by jhendrixMSFT** [comment]
The refactoring work for long-running operations will have a fix for this; it should be released in the v12 SDK later this month.

**Comment by jhendrixMSFT** [comment]
This should be resolved in the v12 release.
https://github.com/Azure/azure-sdk-for-go/releases/tag/v12.0.0-beta
