### ISSUE TITLE
Deploy ARM template using the Go SDK

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#733]
Hello!

Can you deploy an ARM template using the Go SDK?

Here is the scenario: I recently contributed to a project where the requirement was to create a simple VM based on VHD file you created locally.
You had to upload the VHD in a storage account, then create all necessary infrastructure for the VM - virtual network, subnet, public IP address, network interface, network security group and so on.

[Here is the actual project for that.](https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/azure.go)

It would be much simpler (and easier for versioning and so on) if I could write an ARM template and then from my Go application (maybe) set some parameters and deploy it.
While I'm not an expert on this SDK, I haven't seen in possible to actually take an ARM template and deploy it.

Is this something possible? If not, is it a scenario that is worth exploring?

Also, what is currently the recommended way of achieving what I was talking about earlier?

Thanks!

**Comment by marstr** [comment]
Howdy @radu-matei, always good to hear from you!

Yes, using the Azure SDK for Go, you are able to do use ARM templates using "Deployments".

The package that one looking to utilize ARM templates will find most useful can be found here:

**Comment by radu-matei** [comment]
Hi, @marstr!
Thanks a lot for the fast reply, helpful information.
