### ISSUE TITLE
Cosmos gremlin api support

### ISSUE THREAD

**Issue by kwontae** [Azure/azure-sdk-for-go#7345]

**Comment by ArcturusZhang** [comment]
Hi @kwontae what kind of feature are you requesting? Please feel free to complete your content, and then I will reopen this issue for you.

**Comment by kwontae** [comment]
Hi @ArcturusZhang I see I didn't know it had to be supported by the azure rest api specs. I just wanted a feature(like an sdk for other packages such as eventhub) that will allow me to do aad authentication to my gremlin database using cosmos db and make queries. I know they have sdk for other languages such as java, .net, python and etc but not for Golang yet and it would be lovely if that is supported

**Comment by ArcturusZhang** [comment]
I am quite sorry that this kind of SDKs are manually written by the service team, while this repo stores mostly management plane which is auto-generated from the rest api specs. Therefore as far as I know, this kind of SDK will not be supported here. If the service team write a go SDK manually, usually it will not be placed in this repo. You can find some links of other data-plane SDKs in the README file.
Could you please give me an link of the existing Java SDK you have mentioned? Maybe I could find a way to contact those teams directly, but I am not promising anything here.

**Comment by kwontae** [comment]
@ArcturusZhang https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-java this is the link that talks about how to use the java sdk

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-java this is the link that talks about how to use the java sdk

Thanks. And hope you not mind that I am going to close this issue since this is irrelevant with go SDK.

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT are you aware of any plans of GO data plane SDK for this service?

**Comment by jhendrixMSFT** [comment]
There are plans to add a module supporting CosmosDB but we don't have a firm timeline for when that will happen.

**Comment by kwontae** [comment]
@jhendrixMSFT  any updates?
