### ISSUE TITLE
Azure-Core: Add OpenTelemetry Tracing Plugin Support for Track2 Go SDKs

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#7358]
Tracking issue for adding OpenTelemetry tracing support for azure-core, azure-identity, and Storage Go SDKs

- See https://opentelemetry.io/docs/golang/tracing/
- See https://github.com/Azure/azure-sdk/issues/501
- See https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92

/cc @lmolkova @pakrym

**Comment by jhendrixMSFT** [comment]
Codegen changes https://github.com/Azure/autorest.go/issues/501
