### ISSUE TITLE
Support MSI Feature

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#739]
Please Sync up with @marstr on his findings and follow-up with the latest changes in MSI support

**Comment by jhendrixMSFT** [comment]
The work has been completed, all that remains is to write a sample.

**Comment by joshgav** [comment]
move https://github.com/Azure-Samples/compute-go-msi-vm to https://github.com/Azure-Samples/azure-sdk-for-go-samples. thanks!

**Comment by joshgav** [comment]
tracking in https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/2

**Comment by mcardosos** [comment]
Fixed on https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/89
