### ISSUE TITLE
Upgrade to version `2017-08-01` of the Networking API's

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#744]
👋 

We've had [a request come in](https://github.com/terraform-providers/terraform-provider-azurerm/issues/272) to add support for [accelerated networking on network interfaces](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-vm-accelerated-networking). Taking a look at the Swagger [it appears this exists in version `2017-08-01`](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/networkInterface.json#L643) - but the version included in the SDK is `2017-03-01`.

Would it be possible to upgrade to the new version of the API? :)

Thanks!

**Comment by salameer** [comment]
Hi Tom,

From our side I still see the networking team updating the swagger for that API version, that's why we haven't released this yet to minimize our impact on service teams.

**Comment by salameer** [comment]
We're planning to do a new release around mid September and hopefully this swagger will stabilize by then. Even if it doesn't we will still try to release this in that release, does that timeline work?

**Comment by tombuildsstuff** [comment]
@salameer sure, that works great - thanks for letting us know :)

**Comment by mcardosos** [comment]
Fixed
