### ISSUE TITLE
AKS Subnet is not available in output

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-sdk-for-go#7498]
### Bug Report

- path: /services/containerservice/mgmt/2019-10-01/containerservice
- SDK version: `v39.2.0`

- What happened?
Subnet ID is not exposed
- What did you expect or want to happen?
I expected to have a Subnet ID exposed if I request my AKS cluster state
- How can we reproduce it?
`az aks list` or terraform:
```
data "azurerm_kubernetes_cluster" "aks" {
  name                = "aks"
  resource_group_name = aks-rg
}

output "subnet" {
    value = data.azurerm_kubernetes_cluster.aks.agent_pool_profile.0.vnet_subnet_id
}
```
- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Hi @aristosvo thanks for this issue.
I assume you are talking about the `Get` method of `ManagedClustersClient`?
It would help a lot if you can paste the log of terraform, or just append a `--debug` parameter to your azure cli command, to check whether the actual rest api response contains the field you want.
The management plane of go SDK is auto-generated from the [rest api specs](https://github.com/Azure/azure-rest-api-specs), if the rest api will not return the value you wanted, I could not help you from the SDK side.

**Comment by ArcturusZhang** [comment]
After a brief search, would these two meet your requirement?
1. https://github.com/Azure/azure-sdk-for-go/blob/ee7c54530df34dd03f392562bcb869613fd7efdc/services/containerservice/mgmt/2019-10-01/containerservice/models.go#L1757
2. https://github.com/Azure/azure-sdk-for-go/blob/ee7c54530df34dd03f392562bcb869613fd7efdc/services/containerservice/mgmt/2019-10-01/containerservice/models.go#L1795

**Comment by aristosvo** [comment]
Yes, it meets my requirements, if these were always filled. I've opened an issue [here](https://github.com/Azure/azure-rest-api-specs/issues/8494) to check why these fields are not filled in the latest AKS clusters I created
