### ISSUE TITLE
Update Logic App Workflow to support `FlowEndpoints`

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#7499]
### Feature Request

Current available version of logic app workflow is **2016-06-01**, which lacks of `FlowEndpointsConfiguration` in `WorkflowProperties`, this has already been supported in the latest version **2019-05-01**.

So please bump the version (if feasible) so that user could refer to info like: `outgoingIpAddresses` or `accessEndpointIpAddresses`.

**Comment by ArcturusZhang** [comment]
This package will be released in the next minor version v39.4.0

**Comment by ArcturusZhang** [comment]
Well, this has been released here:
github.com/Azure/azure-sdk-for-go/services/preview/logic/mgmt/2019-05-01/logic
in v39.0.0 of the SDK, but it is located in the preview directory by mistake.
I will move this package out of the preview directory in the next major version release.

**Comment by ArcturusZhang** [comment]
PR: https://github.com/Azure/azure-rest-api-specs/pull/8491
