### ISSUE TITLE
Key Vault - Sovereign Clouds 

### ISSUE THREAD

**Issue by khenidak** [Azure/azure-sdk-for-go#756]
Key vault funcs expects a key vault uri in the form of https://myvault.vault.azure.net (like [here](https://github.com/Azure/azure-sdk-for-go/blob/master/dataplane/keyvault/client.go#L802)) Does this mean it will not work as is in sovereign clouds (German, China, gov etc..?) or is the user expected to pass the correct vault Uri?

**Comment by mcardosos** [comment]
Hello @khenidak !
Yes, it is expected to pass the vault URI. Example `https://myvault.vault.microsoftazure.de`
You can find the suffixes for each cloud [here](https://github.com/Azure/go-autorest/blob/5432abe734f8d95c78340cd56712f912906e6514/autorest/azure/environments.go) and [here](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-access-behind-firewall).
