### ISSUE TITLE
Add Content-MD5 header for AppendBlock or add Option to AppendBlockOptions

### ISSUE THREAD

**Issue by someone1** [Azure/azure-sdk-for-go#757]
It's trivial to calculate the md5 sum for the chunk provided:

```
        md5sum := md5.Sum(chunk)
	headers["Content-MD5"] = base64.StdEncoding.EncodeToString(md5sum[:])
```

Or allow the user to pass the option to include the header upon upload by adding a property to `AppendBlockOptions`

**Comment by mcardosos** [comment]
@someone1 Fixed!
