### ISSUE TITLE
Associated subnet in routing table is deleted during "Configuring subnet"

### ISSUE THREAD

**Issue by kleinsasserm** [Azure/azure-sdk-for-go#760]
I have opened up an issue at docker/machine#4244 because it seems like, that during the call to the API interface [createorupdate](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/subnets/createorupdate), an already (precreated) associated subnet routing table entry gets deleted.

I know, that this is probably not a sdk issue, but maybe someone can take a look at the referenced issue and have a look at the API implementation from Azure. The described behavior is reproducible. Thx.

**Comment by marstr** [comment]
Thanks for bringing this to our attention. While I believe you are correct that there is not an SDK level fix for this, it does seem like something that should get some attention. I'll find someone to reach out to you to get this issue filed in the appropriate place.

**Comment by kleinsasserm** [comment]
You are welcome! I'm happy to read that this gets some attention. Just contact me, if you need any further information.
