### ISSUE TITLE
equivalent of CloudBlockBlob

### ISSUE THREAD

**Issue by sentient** [Azure/azure-sdk-for-go#761]
Background: converting some old C# code.
```
 CloudBlockBlob blob = new CloudBlockBlob(new Uri(url), client.Credentials);
 await blob.DownloadToStreamAsync(target);
```

So giving a url, how I can download the blob. Does this SDK have an equivalent for the CloudBlockBlob functionality? 
I'm poking at examples and documentations, but they seem to be all accessed from the blob container. 

I'm sure I'm missing something obvious

**Comment by mcardosos** [comment]
Hello @sentient !
This SDK does not have an equivalent to getting a blob reference from URL. What you can do today is this:

```go
cli, err := NewBasicClient(name, key)
blobCli := cli.GetBlobService()
cnt := blobCli.GetContainerReference(containerName)
b := cnt.GetBlobReference(blobName)
resp, err := b.Get(nil)
data, err := ioutil.ReadAll(resp)
```
