### ISSUE TITLE
Which resource group do I belong to?

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#762]
@kirankumarbv says on https://github.com/Azure/azure-sdk-for-go/pull/729
> I had a question about the sdk. I am not sure if it is suitable to ask here. If I have a virtualmachineClient object and required authentication, how do I query through which resource group do I belong to?

**Comment by mcardosos** [comment]
@kirankumarbv I am not sure what are you referring exactly to. Do you want to know to which resource group a VM belongs to?

**Comment by kirankumarbv** [comment]
Yes. Can I know from some function call where the input is VM, it returns the VM's resource group. Or a similar method?
Right now, I am trying to build a path like this 
/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName} in my application and I have to find a way to get resourcegroup name within the application?

**Comment by mcardosos** [comment]
To perform operations on a VM you will always need the resource group it belongs to. In this case, [operations on resource groups](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/groups.go) are a better idea. Listing resource groups and them listing resources inside the groups might be what you are looking for.

**Comment by kirankumarbv** [comment]
Alright thanks for your input.

**Comment by akskap** [comment]
@mcardosos Can you please point to the correct link ? Looks like the original page has moved
