### ISSUE TITLE
cosmos-db apis

### ISSUE THREAD

**Issue by kirankumarbv** [Azure/azure-sdk-for-go#763]
Hi,

I was going through cosmos-db and document db package under arm. I can only find creation, updation and deletion of database accounts apis. How do I create, list, update and delete collections inside those database accounts? Are these apis still being developed for go?

For reference, Below is the python program that makes use of python azure sdk.
https://github.com/Azure/azure-documentdb-python/blob/master/samples/CollectionManagement/Program.py
In that program they do all the manipulations with collections that I talked about above.

**Comment by marstr** [comment]
Howdy @kirankumarbv,

The short answer is that we don't have our own library for querying these No-SQL databases, and that our team's recommendation is to use an existing open-source library. @devigned has previously researched a few, he may be able to chime in here with his findings.

-Martin

**Comment by kirankumarbv** [comment]
That is a bummer. Anyway we will try to use cosmos REST APIS using some rest client within our go application. I believe that is possible and we can make use of full functionalities?

**Comment by devigned** [comment]
@kirankumarbv I really enjoyed using CosmosDB through the Mongo APIs. The only hurdle is setting up the SSL dialer. If you check out the code here, it'll help you get started: https://github.com/team-tissue/labelizer-app/blob/261713fcc6d553a6309d82e6158018bd325885c7/server.go#L96-L110.

Let me know if you have any questions. I'm happy to help.

**Comment by kirankumarbv** [comment]
Thanks. Will take a look!
