### ISSUE TITLE
KeyVault - Dataplan - Encrypt/Decrypt/Wrap/Unwrap

### ISSUE THREAD

**Issue by khenidak** [Azure/azure-sdk-for-go#764]
Ref Docs https://docs.microsoft.com/en-us/rest/api/keyvault/decrypt states that request+response for all key operations (Encrypt/Decrypt/Wrap/Unwrap) is Base64Url encoded string. However golang fails to decode the response, consistently 

Can you help identifying what exactly is wrong? Possible de/serialization issue (though not sure)  

Here is a quick sample:
The same sample below is tried with 
- (assuming that docs are wrong) Golang's StdEncoding for upstream/downstream encoding (both failed) 
- This failed for simple "Hello, World!" string and binary blobs (consistently)
- This goes for any KeyOperation fun (Encrypt/Decrypt/Wrap & Unwrap)

```golang
   value := base64.URLEncoding.EncodeToString(data) // <- Data is a string
   parameters := keyvault.KeyOperationsParameters{
     Algorithm: keyvault.RSA15,
     Value:     &value,
   }

   result, err := KeyVaultClient.Encrypt([vaultUri], [KeyName], [KeyVersion] /* empty string*/, parameters)
   if err != nil {
     return "", err
   }

   bytes, err := base64.URLEncoding.DecodeString(*result.Result)
   if err != nil {
     glog.V(2).Infof("Encrypt - Decode Failed!!!!") // <- alway fails here with decoding failure.
    return "", err
 }  

```

**Comment by khenidak** [comment]
@marstr ping

**Comment by marstr** [comment]
Howdy @khenidak, I'll look into this for you. Unfortunately, I don't have any answers off the top of my head.

-Martin

**Comment by khenidak** [comment]
no dice?

**Comment by marstr** [comment]
Sorry @khenidak, :/ I'm all tied up right now. I still want to get at this for you, but it may have to wait a week or so. If you're actively blocked, and need more immediate attention, I can try to delegate this to someone else on the team.

**Comment by khenidak** [comment]
I had time to look more into this. The docs are incorrect on KV side. the response value is a string is **unpadded** Base64Url Encoded. You can safely close this issue.

**Comment by marstr** [comment]
Thanks for following up, @khenidak.
