### ISSUE TITLE
Microsoft.Network: `securityRule` resource group name not respecting case sensitivity 

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#7738]
opening as a copy of https://github.com/Azure/azure-rest-api-specs/issues/8309 as it was closed due to not being a rest API spec issue (its a service issue)
When creating a securityRule, the case of resource group name is inherited from the networkSecurityGroup ignoring case passed as a parameter.

Repro steps:

Create resource group with resourceGroupName = "test-rg"
Create network security group with resourceGroupName = "TEST-RG"
Create security rule associated to network security group created in step 2 with resourceGroupName = "test-rg"
Subsequent GET of security rule created in step 3 has resourceGroupName with value of "TEST-RG"
For example, when creating a virtualNetwork associating a subnet if created with virtualNetwork.resourceGroupName = "test-rg" and subnet.resourceGroupName = "TEST-RG", performing a GET subnet respects case sensitivity of resource group name passed at create time, i.e. GET returns subnet.resourceGroupName = "TEST-RG".

**Comment by ArcturusZhang** [comment]
Hi @katbyte I have tagged this issue therefore the corresponding service team could have a look at this.

**Comment by rushabh268** [comment]
@ArcturusZhang I am seeing this issue as well. Any chance when this can be fixed?

**Comment by ArcturusZhang** [comment]
Hi @rushabh268 sorry for the inconvenience but this has to be fixed on the service side rather than in this SDK. Therefore I have tagged this issue again with the `Service Attention` label which would send notifications to the corresponding service team and they may have a look at this issue

**Comment by allegradomel** [comment]
@anharazi, can you please take a look? This a service side issue

**Comment by anharazi** [comment]
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md
The resource group names and resource names should be matched case insensitively. That means, for example, if a user creates a resource in resource group "rG1", and then calls a read operation on "RG1", the same resource should be returned even though the casing differs.
Additionally, the REST API MUST preserve the casing provided by the user. That means the API should return back the most recently specified casing to the client (and API MUST not normalize / return back a toupper/tolower form of the resource group or resource name, for example).

**Comment by allegradomel** [comment]
#please-close

**Comment by tombuildsstuff** [comment]
@allegradomel why is this closed? Has this issue been fixed?

**Comment by tombuildsstuff** [comment]
ping @allegradomel

**Comment by tombuildsstuff** [comment]
@ArcturusZhang can we re-open this until we can confirm if this has been fixed?

**Comment by katbyte** [comment]
Hey @allegradomel @jhendrixMSFT @JeffreyRichter - This was closed without a fix or adequate response: Can we please reopen this until it has been resolved?

**Comment by ArcturusZhang** [comment]
Reopen this issue per request

**Comment by rushabh268** [comment]
Any update on when this will be resolved?
