### ISSUE TITLE
[FEATURE REQ] Azure.Identity - Support KnownAuthorities like Python SDK

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-go#7745]
Azure.Identity

It would be great if we provided a "KnownAuthorities" concept, like we have in the Python SDK.
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/azure/identity/_constants.py

Right now, in Go, devs have to provide the url for the environment they are targeting `https://login.microsoftonline.us` for Gov, for example.

With Python
```python
credential = DefaultAzureCredential(authority=KnownAuthorities.AZURE_GOVERNMENT)
```

It's unclear what the implementation would be for Go, since it is still not in preview, but would be great to have this be consistent across SDKs.

**Comment by jongio** [comment]
@catalinaperalta - Can we try to get this in the first release?  We'll have with all the other SDKs at that point, would be good to ship go with it from day 1.  Thanks

**Comment by jongio** [comment]
While Python uses the name KnownAuthorities, KnownAuthorityHosts looks like the better name for the other languages.

**Comment by catalinaperalta** [comment]
I will need to analyze how many changes this will require, but it might be possible to get it in the first release. Will get back to you about this.

**Comment by catalinaperalta** [comment]
KnownAuthorities have been added in #8309.
