### ISSUE TITLE
Azure Functions SDK

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#776]
Hello there!
I was wondering why there isn't an Azure Functions SDK (or maybe I missed it?).

I know I can [deploy the ARM templates that create an Azure Function](https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code) but compared to how you would [do it using the CLI](https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code) it is much more tedious.

Thanks!

**Comment by radu-matei** [comment]
Adding this [issue from the Azure REST API Specs](https://github.com/Azure/azure-rest-api-specs/issues/1348) - so this issue is not related to the Go SDK, will close.
Thanks!

**Comment by marstr** [comment]
Cheers! Thanks for looking into this, @radu-matei.
