### ISSUE TITLE
Creating VMs in Azure using the GoSDK

### ISSUE THREAD

**Issue by pitthu** [Azure/azure-sdk-for-go#780]
We have a question on creating VM in Azure. 

We are trying to create a VM using the go sdk where we want to use our private linux image. 

The Image parameters that Azure needs are Publisher, sku, offer  and version and uses them to get the image from the marketplace.

What values will we need for our private image to be passed in the vmClient.CreateOrUpdate function? 

 type ImageReference struct {
  ID          *string `json:"id,omitempty"`
  Publisher *string `json:"publisher,omitempty"`
  Offer       *string `json:"offer,omitempty"`
  Sku         *string `json:"sku,omitempty"`
  Version   *string `json:"version,omitempty"`
  }

Is there a way to pass just the vmName?

`

**Comment by marstr** [comment]
Howdy @pitthu, sorry this has gone without a response for a few weeks!

My colleague @devigned actually just finished updating the sample for managing virtual machines to include dealing with private images. You can find that code here:
https://github.com/devigned/virtual-machines-go-manage/blob/image-ref-update/example.go

It hasn't made it's way into the main [Azure-Sample repository](https://github.com/Azure-Samples?utf8=%E2%9C%93&q=&type=&language=go) yet, but rest assured that it will.

I hope that helps!

-Martin

**Comment by pitthu** [comment]
Hi Martin,

Thanks for replying. We have been in contact with David, he has helped a
lot with the create instance :)

Best,
Sunanda
