### ISSUE TITLE
Time Series Insights Environment - Error occurred unmarshalling JSON - Error = 'parsing time'

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#7824]
### Bug Report

- github.com/Azure/azure-sdk-for-go/services/preview/timeseriesinsights/mgmt/2018-08-15-preview/timeseriesinsights
- github.com/Azure/azure-sdk-for-go/services/timeseriesinsights/mgmt/2017-11-15/timeseriesinsights
- Version - 38.1.0
- go version go1.13.4 darwin/amd64

I'm getting an error when trying to get a Get a Time Series Insights Environment that happens in both the preview and stable branch

```
        Error: retrieving Time Series Insights Environment "test" (Resource Group "test-rg"): timeseriesinsights.EnvironmentsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'parsing time ""TUE, 10 MAR 2020 22:21:46 GMT"" as ""2006-01-02T15:04:05.999999999"": cannot parse "TUE, 10 MAR 2020 22:21:46 GMT"" as "2006"' JSON = '{"sku":{"name":"S1","capacity":1},"kind":"Standard","location":"eastus2","tags":{},"properties":{"dataRetentionTime":"P30D","storageLimitExceededBehavior":"PurgeOldData","creationTime":"Tue, 10 Mar 2020 22:21:46 GMT","provisioningState":"Succeeded","requestApiVersion":"2018-08-15-preview","dataAccessId":"dataID","dataAccessFqdn":"dataFQDN","partitionKeyProperties":null},"id":"resourceId","name":"resourceName","type":"Microsoft.TimeSeriesInsights/Environments"}'
```

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry  thanks for the issue.
It seems that the SDK is trying to parse the returned time "Tue, 10 Mar 2020 22:21:46 GMT" into `date.time` but failed. I am not quite familiar with the format of a string of time, but I suppose "Tue 10 Mar 2020 22:21:46 GMT" just looks better to me.

Hi @jhendrixMSFT any thoughts? Is the time in right format?

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang this is a bug in the swagger.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/preview/2018-08-15-preview/timeseriesinsights.json#L1199

The default format of `date-time` is RFC3339Nano however the value being sent over-the-wire is RFC1123.  Can you please work with the swagger owner to change the `format` to `date-time-rfc1123`.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang this is a bug in the swagger.
> 
> https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/preview/2018-08-15-preview/timeseriesinsights.json#L1199
> 
> The default format of `date-time` is RFC3339Nano however the value being sent over-the-wire is RFC1123. Can you please work with the swagger owner to change the `format` to `date-time-rfc1123`.

No problem, I will take care of this.

**Comment by ArcturusZhang** [comment]
I have opened a new issue in the rest api specs repo, therefore I will close this issue for more clear track on this. Thanks!

**Comment by mbfrahry** [comment]
Thank you!
