### ISSUE TITLE
Feature Request: Expose a method of obtaining all Enum values

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#783]
:wave:

As [mentioned in this issue](https://github.com/Azure/azure-rest-api-specs/issues/1739#issuecomment-332167675) - we make use of the Enum's provided by the Azure SDK for Go for validation purposes - by listing each value in the Enum into our validation function:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/766261fa228fca0e2b3e1928346c95d86cd85946/azurerm/resource_arm_app_service.go#L213-L224

Whilst this works great - it means we're listing these constants out, and with the SDK being auto-generated - we're having to review each Model every time we upgrade to determine if any new Constants have been added. As such - I'm wondering if it'd make sense to expose a method of obtaining all of these values, pseudo code below:

```
types := web.AvailableConnectionStringTypes() # which returns [ web.APIHub, web.Custom ] (etc)
```

That would allow consumers to iterate over these as needed - in our case as a Validation function - but other consumers could use it for picking options dynamically from a CLI (for example). What do you think? :)

Thanks!

**Comment by jhendrixMSFT** [comment]
The updated generator with support for this is 2.1.88.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.0.0
