### ISSUE TITLE
graphrbac: `GroupMembershipClaimTypes` missing `DirectoryRole` constant

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#7857]
### Bug Report

- import path of package in question
`"github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac"`
- SDK version 
`v40.3.0`

- What happened?
the enum type GroupMembershipClaimTypes is missing the constant `DirectoryRole` which is supported by the API.

- What did you expect or want to happen?
the enum to be present, as you can see [from here](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims) this appears to be a valid value
![image](https://user-images.githubusercontent.com/1638467/76442820-b744f400-637e-11ea-8063-1293d2b5976a.png)

**Comment by ArcturusZhang** [comment]
Hi @katbyte thanks for the issue.
I just checked the rest api specs, the spec is also missing this value. Therefore I will close this issue and open a new issue in the spec repo for this.
