### ISSUE TITLE
Feature Request: Support for device api in Iothub service

### ISSUE THREAD

**Issue by girishramnani** [Azure/azure-sdk-for-go#789]
Hello,
The current IotHub client does not have support for the [Device api](https://docs.microsoft.com/en-us/rest/api/iothub/deviceapi).
One use case of this api will be that it will provide the user the functionality to integrate addition and removal IOT devices in their CI/ CD pipeline ( maybe using terraform ). What do you think?

**Comment by marstr** [comment]
Howdy @girishramnani, anything that improves CI/CD using Terraform sounds good to us!

I went and dug into the Azure OpenAPI Specs repository which can be found [here](https://github.com/Azure/azure-rest-api-specs), but didn't find the operations you pointed to. The closest thing I found is here: [github.com/Azure/azure-rest-api-specs/specification/iothub/resource-manager](https://github.com/Azure/azure-rest-api-specs/tree/765c5a6807e3a093868bff793ec3e8ea0cdabe75/specification/iothub/resource-manager). However, it doesn't document API Version 2016-11-14 like you pointed to. The first step of getting support would be to add an OpenAPI spec for it in the repository I keep linking to. If you file an issue over there, somebody should pick up your request.

I hope that helps!

-Martin
