### ISSUE TITLE
There is no function named "Send" but the codes use it [Code Bug in Master Branch]

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-go#7890]
### Bug Report

- import path of package in question, e.g. `.../services/preview/customproviders/mgmt/2018-09-01-preview/customproviders`
- SDK version `master`

In the sdk of cusomproviders of master branch, there are two files named "associations.go" and "customresourceprovider.go". The two files have a bug.

Here, we just have a look at associations.go because customresourceprovider.go has the same issue.

In associations.go, there are many places using `client.Send`  and the client is a AssociationsClient. However, we cannot find where the sdk defines the method `Send`.

Also, I find some other sdk of other services also have this issue.

**Comment by ArcturusZhang** [comment]
Duplicate with #7757
