### ISSUE TITLE
Add the expand flag for api calls in UsersClientAPI in graphrbac

### ISSUE THREAD

**Issue by UdiRaitblat** [Azure/azure-sdk-for-go#7893]
The expand flag allows the caller to expand the fetched data in the same call, not having to add a call per returned user.

These are the original calls in UsersClientAPI (https://github.com/Azure/azure-sdk-for-go/tree/master/services/graphrbac/1.6/graphrbac) :
List(ctx context.Context, filter) (result graphrbac.UserListResultPage, err error)
ListComplete(ctx context.Context, filter) (result graphrbac.UserListResultIterator, err error)

This is how it should look:
List(ctx context.Context, filter, expand string) (result graphrbac.UserListResultPage, err error)
ListComplete(ctx context.Context, filter, expand string) (result graphrbac.UserListResultIterator, err error)
when expand is added to the query as $expand just like filter is added (as $filter).

**Comment by ArcturusZhang** [comment]
Hi @UdiRaitblat thanks for this issue. I have tagged this issue so the corresponding service team could have a look at this.
But in the meantime, have you tried the expand using the REST API call? If it works, maybe they just need to update their swagger. But if not, this may be a new feature request for them, which may take longer time.

**Comment by UdiRaitblat** [comment]
Hey,

Thanks for the reply, it would be really nice if this was added.
I have tried to submit this fix: https://github.com/Azure/azure-sdk-for-go/pull/7886
But was told this code is generated.
Right now we are working on a forked version but this is very simple and will be better if fixed on master/latest.

Thanks,
Udi
________________________________

**Comment by ArcturusZhang** [comment]
Hi @UdiRaitblat sorry about that. Because go SDK is generated from the swaggers, we cannot directly change the generated code in go SDK. We have to push the service team to modify their swagger if there are some features missing in the swagger.

**Comment by AdallomRoy** [comment]
Where do these swaggers reside? Maybe we can publish a PR there to speed things up.

**Comment by ArcturusZhang** [comment]
> Where do these swaggers reside? Maybe we can publish a PR there to speed things up.

You could find those swaggers [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json)
