### ISSUE TITLE
ListBlobsSegmentedAsync implementation

### ISSUE THREAD

**Issue by jdelobel** [Azure/azure-sdk-for-go#791]
Hi,

Is it possible to implement [ListBlobsSegmentedAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobclient.listblobssegmentedasync?redirectedfrom=MSDN&view=azurestorage-8.1.3#Microsoft_WindowsAzure_Storage_Blob_CloudBlobClient_ListBlobsSegmentedAsync_System_String_System_Boolean_Microsoft_WindowsAzure_Storage_Blob_BlobListingDetails_System_Nullable_System_Int32__Microsoft_WindowsAzure_Storage_Blob_BlobContinuationToken_Microsoft_WindowsAzure_Storage_Blob_BlobRequestOptions_Microsoft_WindowsAzure_Storage_OperationContext_)?

You have a method **ListBlobs** but this method is limited to list a maximum of **5000 items** (according to the [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs), masResults parameter, and poor performance because this method is synchronous and block the current thread).

**ListBlobsSegmentedAsync** is asynchronous and you can paginate blobs and so **have an unlimited number of results :)**

Thanks!

**Comment by jhendrixMSFT** [comment]
Hello!  To clarify on the docs, the limit of 5000 items is per page.  So if you have a total of 20K blobs and specify 5K for maxResults you'll receive 4 pages of blob listings.  To retrieve the next page you must pass in the "marker" that's returned as part of the current page.  While we don't have a great sample that details this you can find an example in the container_test.go file, please see [here](https://github.com/Azure/azure-sdk-for-go/blob/master/storage/container_test.go#L278).

**Comment by jhendrixMSFT** [comment]
Please re-open if you have any further questions.  :)
