### ISSUE TITLE
Kusto Data Support

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#7916]
I see sdks for Kusto Data across many languages but not for Go. https://docs.microsoft.com/en-us/azure/kusto/api/netfx/about-kusto-data

Right now, the lack of support is hindering Terraform's ability to support [data connections](https://github.com/terraform-providers/terraform-provider-azurerm/pull/5607) in Terraform as a Kusto Table needs to be setup/managed prior to creating a data connection.

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for this issue. 
The features you are requesting should be some data-plane functionalities. Generally this go SDK repo only contains those are from management plane and a some amount of data-plane whose swagger is published in [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs).

**Comment by jhendrixMSFT** [comment]
CC @mayurid 

Kusto is on our radar but we don't have a firm release date at present.

**Comment by yogilad** [comment]
Kusto Go is available:

- https://github.com/Azure/azure-kusto-go
- https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/golang/kusto-golang-client-library

**Comment by vladikbr** [comment]
Kusto data plane SDK for Go is published here: https://github.com/Azure/azure-kusto-go
