### ISSUE TITLE
Issue when creating a file using file service

### ISSUE THREAD

**Issue by scriptonist** [Azure/azure-sdk-for-go#792]
How can we create a file in an azure file share using the SDK ?.

Trying it out with the following code.
 ```
newFile := rootDir.GetFileReference("filename")
f := strings.NewReader("test")
err := newFile.WriteRange(f, storage.FileRange{}, &storage.WriteRangeOptions{})
panic(err)
```

When using this implementation the following error is thrown

`panic: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

Their is no error being thrown when creating the client using the following code.
`client, err := storage.NewBasicClient(accountName, accountKey)`

Had no problems when communicating with the azure blob and table service with the same `client`.

@salameer

**Comment by mcardosos** [comment]
Hello @scriptonist !
I assume this would be a completely new file? If that is the case, you only need an extra line and modify other a little bit:
``` go
newFile := rootDir.GetFileReference("filename")
err := newFile.Create(fileSize, &storage.FileRequestOptions{})
f := strings.NewReader("test")
err = newFile.WriteRange(f, storage.FileRange{End: fileSize -1}, &storage.WriteRangeOptions{})
```
