### ISSUE TITLE
Container Registry API Version in SDK isn't available

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#795]
👋 

As mentioned in #794 - I've been trying to migrate us over to using v11 of the Azure SDK for Go. Unfortunately it appears the API Version used for Container Registry also isn't configured correctly:

```
containerregistry.RegistriesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'westeurope' and API version '2017-10-01' for type 'registries'. The supported api-versions are '2016-06-27-preview, 2017-03-01, 2017-10-01, 2017-06-01-preview'. The supported locations are 'westus, eastus, southcentralus, westeurope, northeurope, uksouth, ukwest, australiaeast, australiasoutheast, centralindia, eastasia, japaneast, japanwest, southeastasia, southindia, brazilsouth, canadaeast, canadacentral, centralus, eastus2, northcentralus, westcentralus, westus2'."
```

Checking the Provider Registration status in the Portal ([output](https://gist.github.com/tombuildsstuff/cce55e70dd2ec16bfc8bdcbaa0866170)) - it appears whilst this this API version is valid for the Resource Provider itself (as it's shown in the error message above) and some of the sub-types of the Resource Provider - isn't available for the `registry` type.

As such - would it be possible to downgrade to the previous version of the Container Registry API until this is fixed? I'm unsure if this needs a Swagger fix or a Generator fix - but at this point in time we're unable to upgrade to v11

Thanks!

**Comment by marstr** [comment]
Howdy @tombuildsstuff!

Looks like there were some timing issues for the v11 release. @djyou drew our attention to this PR this morning: https://github.com/Azure/azure-rest-api-specs/pull/1771 which seems to have been merged in after our release. We'll be regening and releasing a patch to fix the Container Registry issues that you're seeing.

Sorry for the hassle!

-Martin

**Comment by marstr** [comment]
This should be taken care of in #801

**Comment by mcardosos** [comment]
Fixed
