### ISSUE TITLE
Support Context.context

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#797]

**Comment by CAFxX** [comment]
I need this especially for blob storage

**Comment by salameer** [comment]
THanks for the Feedback @CAFxX

**Comment by salameer** [comment]
@mcardosos  add more info here and handoff to @vladbarosan

**Comment by vladbarosan** [comment]
The PR Azure/autorest.go#43 adds support for the Context pattern.

**Comment by salameer** [comment]
Vlad told me to :)
