### ISSUE TITLE
Cleaning up the repo folder structure and Docs (including Multi API and Profiles Docs)

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#798]

**Comment by marstr** [comment]
Adding context:

Newcomers to the repository are presented with a pretty confusing set of packages, often with either truly or perceived redundant functionality.

As part of this work item, we should mark deprecated/eventually delete truly redundant packages. For packages that remain, documentation MUST be improved.

**Comment by joshgav** [comment]
this is tracked in issues for each item to be cleaned up. closing.
