### ISSUE TITLE
EventHub Dedicated Cluster support 

### ISSUE THREAD

**Issue by djsly** [Azure/azure-sdk-for-go#8014]
### Feature Request

https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dedicated-overview

**Comment by ArcturusZhang** [comment]
Hi @djsly thanks for this issue.
Is [this](https://github.com/Azure/azure-sdk-for-go/blob/797e8ede3a89e35d4a847127b5f1b7426bd42cd0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go#L586) related with the doc you posted here?

**Comment by djsly** [comment]
Looks like it indeed! thanks, I'm looking with Terraform folks to see if they are OK using a `-preview` API version.

**Comment by ArcturusZhang** [comment]
> Looks like it indeed! thanks, I'm looking with Terraform folks to see if they are OK using a `-preview` API version.

Glad to help. If you do not mind, I will close this issue then.
