### ISSUE TITLE
EventHub Namespace should allow a EventHub Cluster ID to be set

### ISSUE THREAD

**Issue by djsly** [Azure/azure-sdk-for-go#8015]
### Feature Request

We want to create EventHub namespaces in a EventHub Cluster using the SDK, right now the EventHub Namespace don't allow to be added to a EventHub cluster ID.

**Comment by ArcturusZhang** [comment]
Hi @djsly thanks for this issue!
Would [this](https://github.com/Azure/azure-sdk-for-go/blob/797e8ede3a89e35d4a847127b5f1b7426bd42cd0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go#L808) meet your requirement?

**Comment by djsly** [comment]
indeed! I didn't look at the -Preview since Terraform was not using this version of the API, I guess we should have all we need. 

Do we know when this API will leave the Preview state ?

**Comment by ArcturusZhang** [comment]
> indeed! I didn't look at the -Preview since Terraform was not using this version of the API, I guess we should have all we need.
> 
> Do we know when this API will leave the Preview state ? I"m looking with the terraform folks to see if the `-preview` API will be accepted

I suppose if a preview api-version have something other api-version do not, they will still have to take it.

It is hard to say when it will leave preview... sometimes they just release a newer api-version directly replace the preview one.

And if you do not mind, I will close this issue. Please feel free to reopen or comment if you have other concerns, thanks!
