### ISSUE TITLE
copy image to another region support is needed 

### ISSUE THREAD

**Issue by himanshurraj** [Azure/azure-sdk-for-go#8021]
### Feature Request

I have an image in south central us and i want to copy the image in eastus.
I am not getting the proper method in the sdk.

**Comment by ArcturusZhang** [comment]
Hi @himanshurraj thanks for this issue.
I am not quite sure whether there is direct support for this in REST API of azure. If there is not such a way, there will not be such a method in the go SDK. Sorry about this.

But you can try some work around of this. For instance, take a snapshot of that image, and recreate a new image in the new location: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/snapshot-copy-managed-disk
