### ISSUE TITLE
API Version Incompatibility with securitygroups.go (network.SecurityGroup)

### ISSUE THREAD

**Issue by IyerVishSJSU** [Azure/azure-sdk-for-go#803]
Calling the Get method in securitygroups.go and the version mentioned in GetPreparer function is "const APIVersion = "2017-09-01"" which is providing me the following error:

network.SecurityGroupsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2017-09-01' is invalid. The supported versions are '2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

**Comment by marstr** [comment]
Howdy @IyerVishSJSU, sorry to hear you're running into trouble. Which environment are you targeting when you experience this?

-Martin

**Comment by IyerVishSJSU** [comment]
Hi Martin,

I am using Linux Ubuntu as my environment and following are the details

Linux Version : Ubuntu 16.04.3 LTS
Linux ubuntu 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marstr** [comment]
Thanks for responding so quickly. Sorry, I should have been more specific.

Which Azure Cloud are you target, and which region? These are the environments I'm talking about:
[Go-AutoRest - Environments](https://github.com/Azure/go-autorest/blob/faeb847c8586092daaa111b17cc4e6c792fd3a87/autorest/azure/environments.go#L38)
Azure Region list is here: https://azure.microsoft.com/en-us/regions/


-Martin

**Comment by IyerVishSJSU** [comment]
Thanks Martin for the clarification. We are using "AzurePublicCloud" and the region would be "West US". 

-Vish

**Comment by kirankumarbv** [comment]
Hitting the same issue with compute.VirtualMachinesClient.
I am trying to create a VM in the "westus" region.

Failed to create the VM: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2017-03-30' is invalid. The supported versions are '2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

**Comment by marstr** [comment]
Howdy @kirankumarbv, could you checkout #803? Another user just complained about `compute` API Version availability, but found it was available after all.

**Comment by kirankumarbv** [comment]
Hey @marstr My bad. Yes it was an issue with the resource group name. I was passing null value in that case. I verified it and fixed it. It is working now.

**Comment by marstr** [comment]
Howdy @IyerVishSJSU,

I just updated the Network Security Group to target v11, you can see that code here: https://github.com/marstr/network-go-manage-network-security-group
and the PR to make it the official sample:
https://github.com/Azure-Samples/network-go-manage-network-security-group/pull/3

Though to test this, I ran this sample against WESTUS as well as WESTUS2.

I was unable to repro this issue, are you still experiencing it?

**Comment by IyerVishSJSU** [comment]
Hey Martin,
It was my bad. The problem was not due to API but null values were being passed to Get method which was raising the version mismatch issue. I got the desired output after passing the proper values.

Thanks for your help.

-Vish
