### ISSUE TITLE
Pointers for slices and maps

### ISSUE THREAD

**Issue by jkawamoto** [Azure/azure-sdk-for-go#807]
In `arm` package, some structures have pointers for slices and maps, for example, `Tags` of [`arm.batch.Account`](https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/batch#Account) and `Value` of [`arm.batch.AccountListResult`](https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/batch#AccountListResult). Is there a particular reason for using pointers instead of having slices and maps directly?

Slice and map variables are nullable. I think it seems okay to not use pointers.

Currently, since those structures have pointers, we have to check whether they are nil or not, and it might be a cause of bugs.

For example, batch.AccountListResult.Value is a pointer as follows

```go
type AccountListResult struct {
    autorest.Response `json:"-"`
    Value             *[]Account `json:"value,omitempty"`
    NextLink          *string    `json:"nextLink,omitempty"`
}
```

We then have to check whether Value is nil or not before enumerating it:

```go 
var res AccountListResult

res, err = cli.List() // cli is an instance of batch.AccountClient
if err !=nil {
  // error handling
}
if res == nil {
  // another error handling
}
for _, account := range *res.Value {
  fmt.Println(account)
}
```

If the type of `Value` is []Account, we don't need to check `res == nil` in the above code.

**Comment by marstr** [comment]
Thanks for reaching out, @jkawamoto. This is a known issue, and something that @jhendrixMSFT is changing in https://github.com/Azure/autorest.go/pull/27
