### ISSUE TITLE
Archive Blob Storage and Blob-Level Tiering

### ISSUE THREAD

**Issue by cswarth** [Azure/azure-sdk-for-go#808]
Is there a timeline for adding support for Archive Blob Storage and Blob-Level Tiering to this SDK?
(or are those expected to come in through public contributions?)

[Announcing the public preview of Azure Archive Blob Storage and Blob-Level Tiering](https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-azure-archive-blob-storage-and-blob-level-tiering/)

**Comment by seguler** [comment]
We are actually working on a major overhaul of this library at the moment, and the Archive feature is also in our list. Although cannot share an exact timeline, we should have the archive feature available in the upcoming few months.

**Comment by jhendrixMSFT** [comment]
I've moved this issue to the new blob storage repo https://github.com/Azure/azure-storage-blob-go.

**Comment by ncw** [comment]
There still doesn't seem to be a way to set blob level tiering in either this library or [Azure/azure-storage-blob-go](https://github.com/Azure/azure-storage-blob-go) (see https://github.com/Azure/azure-storage-blob-go/issues/1)

Will it be added to this library?

Shall I send a PR?

**Comment by ncw** [comment]
@jhendrixMSFT maybe I should swap to using the azblob package... Is it ready for production?

**Comment by seguler** [comment]
We are working on this feature and will publish as part of the azblob package. We could normally accept PR, but in this case we generate the APIs from the Swagger spec... So we'll update the swagger spec first, generate the protocol layer and then add the support which makes it hard for us to accept PRs on service features.
