### ISSUE TITLE
Custom Provider Association - 301 Location Header is missing

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#8083]
### Bug Report

- `services/preview/customproviders/mgmt/2018-09-01-preview/customproviders`
- SDK version `v40.3.0`
- output of `go version go1.13.4 darwin/amd64`

I'm trying to provision a custom provider association and I'm running into an issue where I'm getting 
```
{"error":{"code":"DownstreamEndpointError","message":"The resource provider 'example' received a non-success response 'MovedPermanently' from the downstream endpoint for the request 'PUT' on 'associations/example'. Please refer to additional info for details."}}
```

with the additional details of 
```
301 response missing Location header
```

I don't see where to set the Location header in the sdk or if that's even the issue. I'm not sure if I'm doing something wrong here or if it's an sdk issue. I'd love a little guidance here

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for this issue.
I am tagging this issue therefore the service team would see this.

**Comment by ArcturusZhang** [comment]
> Hi @mbfrahry thanks for this issue.
> I am tagging this issue therefore the service team would see this.

@ramacasturi could you please have a look at this?

**Comment by lirenhe** [comment]
@mbfrahry, we didn't get service team's reply on this, to solve the problem, could you create a support ticket in Azure directly?
https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
I don't think there is any change needed on the SDK side. So please let me know if you have other questions. Thanks
