### ISSUE TITLE
Support Managed Disk incremental snapshot

### ISSUE THREAD

**Issue by rocketraman** [Azure/azure-sdk-for-go#8086]
### Feature Request

Incremental snapshots of managed disks are now in GA. Please support making these snapshots.

https://azure.microsoft.com/en-ca/blog/announcing-general-availability-of-incremental-snapshots-of-managed-disks/

**Comment by ArcturusZhang** [comment]
Hi @rocketraman thanks for this issue.
The feature you are requesting should be shipped in with this [PR](https://github.com/Azure/azure-rest-api-specs/pull/8195) and will be included in the next major release of go SDK (should be release very soon)

**Comment by ArcturusZhang** [comment]
The new major version v41.0.0 has released. Therefore I suppose this should be resolved and I will then close this issue.
If this issue remains, please feel free to comment and I will reopen this issue.
Thanks!
