### ISSUE TITLE
Ensure that convenience layers reject unsupported credential types

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#8090]
All credential types implement the `azcore.Credential` interface which means any credential type (shared key, bearer token, etc) can be passed to a client constructor.  However, since not all services will support all credential types, the client constructor should fail when passed an unsupported credential type.

One possible pattern is something like this: https://play.golang.org/p/N4JpENDzbrK

We should investigate other patterns.

It would be ideal if this can be implemented in such a way that the convenience layers do _not_ need to take a dependency on `azidentity`.

**Comment by JeffreyRichter** [comment]
https://play.golang.org/p/RU0_deaPAbN

package main

import (
	"fmt"
	"net/http"	// You can remove this import
	"reflect"
)

func main() {
        fmt.Println(IsSupportedCredentialType(http.Client{}, "http.Request", "http.response"))	// If you remove the import, pass something else here
	fmt.Println(IsSupportedCredentialType(http.Request{}, "http.Request", "http.response")) // And here but both tests will return false
}

type Credential interface {}

func IsSupportedCredentialType(credential Credential, supportedCredentialTypes ...string) (bool, error) {
	credType := reflect.ValueOf(credential).Type().String()
	for _, t := range supportedCredentialTypes {
		if t == credType {
			return true, nil
		}
	}
	return false, &UnsupportedCredentialError{}
}

type UnsupportedCredentialError struct{}

func (e *UnsupportedCredentialError) Error() string { return "" }

**Comment by jhendrixMSFT** [comment]
Callers have to go out of their way to accidentally fall into this pit.  Will revisit if it becomes a problem.
