### ISSUE TITLE
Updating the Managed Data Disks on a VM

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#816]
👋 

In the Azure Portal it's possible to update the disks of existing VM's at will - and through the API this is also possible for Unmanaged Disks (from what I recall). However, I'm having issues replicating this for Managed Disks, where upon re-ordering the attached disks (either by updating the Managed Disk ID or the `LUN`) we see an error stating that it's not possible to modify the Managed Disk ID (even when shutting down the VM, then attempting to modify the disks).

I have a feeling this is possible and that I'm missing something obvious - as such would it be possible to point me in the direction of an example of how to update the Managed Data Disks on a VM?

Thanks!

**Comment by marstr** [comment]
This is a great question, @tombuildsstuff. @mcardosos or I will play with this tomorrow (Pacific Time, October 18th) and either we'll figure out how this works or reach out to the service team to understand why there is a limitation.

**Comment by marstr** [comment]
Derp, looks like we slipped on the 18th. Sorry about that, @tombuildsstuff. I'll take a look today or tomorrow.

**Comment by mcardosos** [comment]
Okok :D I know how to reorder.
First detach all data disks. This is so you avoid an error like this...
```
Status=409 Code="ConflictingUserInput" Message="Disk '/subscriptions/subID/resourceGroups/terraform/providers/Microsoft.Compute/disks/hello' cannot be attached as the disk is already owned by VM '/subscriptions/subID/resourceGroups/terraform/providers/Microsoft.Compute/virtualMachines/terraform'."
```

```go
vm.VirtualMachineProperties.StorageProfile.DataDisks = &[]compute.DataDisk{}
_, errChan := vmsClient.CreateOrUpdate(resourceGroup, vmName, vm, nil)
```
And then reattach them...

```go
vm.VirtualMachineProperties.StorageProfile.DataDisks = &[]compute.DataDisk{
	{
		Lun: to.Int32Ptr(0),
		Name: (*list.Value)[2].Name,
		CreateOption: compute.DiskCreateOptionTypesAttach,
		ManagedDisk: &compute.ManagedDiskParameters{
			ID: (*list.Value)[2].ID,
		},
	},
	{
		Lun: to.Int32Ptr(1),
		Name: (*list.Value)[0].Name,
		CreateOption: compute.DiskCreateOptionTypesAttach,
		ManagedDisk: &compute.ManagedDiskParameters{
			ID: (*list.Value)[0].ID,
		},
	},
}
_, errChan = vmsClient.CreateOrUpdate(resourceGroup, vmName, vm, nil)
```
The magic in on the `CreateOption`. You dont need to shut down the VM.

**Comment by tombuildsstuff** [comment]
@mcardosos @marstr awesome - thanks! :)
