### ISSUE TITLE
Add support for OS Disk resize in VMSS

### ISSUE THREAD

**Issue by bpoland** [Azure/azure-sdk-for-go#818]
Hi there,

Wondering if it would be possible to add support for resizing an OS disk when deploying a Virtual Machine Scale Set.

The standalone Virtual machine supports an OsDiskSizeInMB property:
https://github.com/Azure/azure-sdk-for-go/blob/c1ff18326387fa67ccc6e1b17c76e65773684227/arm/compute/models.go#L2267

However, the Scale Set is missing that property:
https://github.com/Azure/azure-sdk-for-go/blob/c1ff18326387fa67ccc6e1b17c76e65773684227/arm/compute/models.go#L1994

I have been able to deploy a scale set with an ARM template specifying a disk size property like this (using API version 2017-03-30) so I know it's possible:
```
                    "storageProfile": {
                        "osDisk": {
                            "caching": "ReadWrite",
                            "createOption": "FromImage",
                            "diskSizeGB": "10",
                            "name": "[concat(variables('vmssName'), '-osp')]",
                            "osType": "Linux",
                            "image": {
                                "uri": "[variables('vmssImageUri')]"
                            }
                        }
                    },
```

Hope that makes sense -- thanks!

**Comment by marstr** [comment]
Howdy @bpoland, thanks for your submission! This sort of issue must be fixed upstream of us a bit, and I've added an issue to the Open API Specs repository which quotes this one.  (You can see a link directly above this comment.)

I'm going to close this issue in favor of the specs repository one, but please feel free to continue commenting and following along there!

**Comment by bpoland** [comment]
Okay, thanks for your help :)
