### ISSUE TITLE
Unable to Generate Network API Version 2015-06-15

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#820]
When running Autorest.Go against this tag: 

https://github.com/Azure/azure-rest-api-specs/tree/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/network/resource-manager#tag-package-2015-06split-and-go

You end up with the following errors in the package:

```
services\network\mgmt\2015-06-15\network\models.go:1546:11: client.NextLink undefined (type UsagesListResult has no field or method NextLink)
services\network\mgmt\2015-06-15\network\models.go:1552:40: client.NextLink undefined (type UsagesListResult has no field or method NextLink)
services\network\mgmt\2015-06-15\network\usages.go:160:11: list.NextLink undefined (type UsagesListResult has no field or method NextLink)
```

This is impacting the ability to generate the Azure Stack profile.

**Comment by marstr** [comment]
The same problem is reproducible with the following packages as well:
- github.com/Azure/azure-sdk-for-go/services/network/mgmt/2015-05-01-preview/network [[Tag](https://github.com/Azure/azure-rest-api-specs/tree/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/network/resource-manager#tag-package-2015-05-preview-and-go)]
- github.com/Azure/azure-sdk-for-go/services/network/mgmt/2015-06-15/network [[Tag](https://github.com/Azure/azure-rest-api-specs/tree/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/network/resource-manager#tag-package-2015-06split-and-go)]
- github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2015-11-01/resources [[Tag](https://github.com/Azure/azure-rest-api-specs/tree/54ffab48d25a576c1a676be9b0b3db6dbba2064b/specification/resources/resource-manager#tag-package-resources-2015-11-and-go)]

**Comment by mcardosos** [comment]
Network 2015-06-15 - This [definition](https://github.com/Azure/azure-rest-api-specs/blob/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/network/resource-manager/Microsoft.Network/2015-06-15/usage.json#L126) is missing the NextLink property.
Network 2015-05-01-preview - Same [here](https://github.com/Azure/azure-rest-api-specs/blob/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/network/resource-manager/Microsoft.Network/2015-05-01-preview/network.json#L6192)
Resources - And [here](https://github.com/Azure/azure-rest-api-specs/blob/54ffab48d25a576c1a676be9b0b3db6dbba2064b/specification/resources/resource-manager/Microsoft.Resources/2015-11-01/resources.json#L2794). In this particular case, if after fixing this issue on resources, autorest is still not generating the SDK, there is a bug in the generator.

**Comment by marstr** [comment]
Fixed.
