### ISSUE TITLE
PutBlockWithLength fails for many io.Reader implementations

### ISSUE THREAD

**Issue by majedev** [Azure/azure-sdk-for-go#822]
`blob.PutBlockWithLength()` returns AuthenticationFailed error when passed any implementations of `io.Reader` other than `bytes.Reader`, `bytes.Buffer`, `strings.Reader` and `io.LimitedReader`. This is caused by the `Content-Length` header not being set correctly for the outgoing request, causing a 403 response from the server.

This is a generalization for issue #683 (which was resolved in #704 but only for io.LimitedReader type). The following example demonstrates this behavior for `os.File` reader type (assuming test.txt file exists):

```
f, err := os.Open("test.txt")
if err != nil {
    panic(err)
}
defer f.Close()

stat, err := f.Stat()
if err != nil {
    panic(err)
}

size := stat.Size()

cli, err := storage.NewBasicClient("testAccount", "topSecretAwesomeSauce")
if err != nil {
    panic(err)
}

blobSvc := cli.GetBlobService()
container := blobSvc.GetContainerReference("azure-test")

blob := container.GetBlobReference("test.txt")
err = blob.PutBlockWithLength("0000", uint64(size), f, nil)
if err != nil {
    panic(err)
}
```

**Comment by jhendrixMSFT** [comment]
Fix has been merged and will be included in the next release.
