### ISSUE TITLE
Unable to marshal insights.EventData

### ISSUE THREAD

**Issue by praveenvaltix** [Azure/azure-sdk-for-go#8224]
### Bug Report

- import path of package in question: services/preview/monitor/mgmt/2019-06-01/insights/models.go
- SDK version: v40.0.0
- output of `go version`: go1.13.4

- What happened?
This issue is same as https://github.com/Azure/azure-sdk-for-go/issues/5379 but I cannot reopen.

- What did you expect or want to happen?
In json marshal, I want to see the full object. I am seeing a null string. It is because of this method:
// MarshalJSON is the custom marshaler for EventData.
func (ed EventData) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	return json.Marshal(objectMap)
}

- How can we reproduce it? 
Straightforward.

- Anything we should know about your environment.
None

**Comment by ArcturusZhang** [comment]
Hi @praveenvaltix thanks for this issue.
The reason of this marshal function returns nothing of this object is that all of its properties are marked as `read only` in its corresponding swagger.
What I am expecting here should be an `UnmarshalJSON` function which de-serialized the JSON in REST API response to a Go struct, since this is the return value of a `List` call here...

Hi @jhendrixMSFT would you please provide some insight about this?

**Comment by jhendrixMSFT** [comment]
MarshalJSON is when we send a payload over-the-wire and per Azure rules R/O properties are required to be omitted from the payload.
What is the scenario here?  I'm guessing it's different then making an API call.

**Comment by praveenvaltix** [comment]
@jhendrixMSFT we at Valtix are building a cloud network security product. Our software has deep integrations with cloud providers including Azure and we use the Go SDKs for the integration. For the resources we manage on Azure, we would like to display the activity log back to the user. Because of the marshal issue, we are unable to do so. Infact, I made a deep copy of the EventData struct to our own struct field by field but ofcourse this is ugly.

**Comment by jhendrixMSFT** [comment]
Thanks for the explanation.  Agreed making a deep copy isn't a great solution.  Something a bit easier would be to create your own type definition of `EventData` without a custom marshaller then cast `insights.EventData` to your type.

```go
type MyEventData insights.EventData

eventData := insights.EventData{}
// other code that populates eventData with content ...

// cast to my type to avoid EventData.MarshalJSON()
b, err := json.Marshal(MyEventData(eventData))
```
We're redesigning our Go SDK, maybe we can do something better here (will look into it).

**Comment by praveenvaltix** [comment]
@jhendrixMSFT thanks for your suggestion. Let me try this out.

**Comment by praveenvaltix** [comment]
Thanks @jhendrixMSFT for your suggestion. That worked. I am closing the issue.
