### ISSUE TITLE
graphrbac: "GroupMembershipClaimTypes" missing "ApplicationGroup" constant 

### ISSUE THREAD

**Issue by MarkDordoy** [Azure/azure-sdk-for-go#8244]
### Bug Report

- import path of package in question 
   `"github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac"`

- SDK version
   `v40.3.0`

- What happened?
The enum type GroupMembershipClaimTypes is missing the constant ApplicationGroup which is supported by the API.

- What did you expect or want to happen?
The enum to be present, as you can see from [here](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#configure-the-azure-ad-application-registration-for-group-attributes) this appears to be a valid value

![image](https://user-images.githubusercontent.com/7372737/78878309-18c5b480-7a4a-11ea-98b5-e684ce18f273.png)

Same issue with different value can be seen here: https://github.com/Azure/azure-sdk-for-go/issues/7857

**Comment by ArcturusZhang** [comment]
This should be duplicate with https://github.com/Azure/azure-sdk-for-go/issues/7857, and you can track this issue [here](https://github.com/Azure/azure-rest-api-specs/issues/8692) in the specs repo which is the upstream of the go SDK

**Comment by katbyte** [comment]
@ArcturusZhang - this is not a duplicate, it is a different enum that is not included in that other issue. cuold you add it to the rest api issue to ensure its fxed at the same time? thanks!

**Comment by ArcturusZhang** [comment]
Hi @katbyte I have updated the REST API specs issue accordingly
