### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-sdk-for-go#827]
https://github.com/Azure/azure-sdk-for-go/blob/2592daf71ab6b95dcfc7f7437ecc1afb9ddb7360/storage/pageblob.go#L93

This should say something like "End modulus 512 should be 511".

**Comment by marstr** [comment]
Seems reasonable! Mind putting together a PR?

**Comment by paulmey** [comment]
Sure. Coming up...

**Comment by marstr** [comment]
Fixed.
