### ISSUE TITLE
Running Sample on Canary and Production

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#829]

**Comment by marstr** [comment]
Adding Context:
At the moment we have a pretty robust set of tests to ensure that the generator produces something functional/reasonable given an accurate Swagger definition. Separately, the folks who own the Swagger Rpeository have been working on building out more robust tests to ensure that Swaggers are accurate. Conspicuously absent from those existing assets is support for end-to-end scenario testing where we make sure that the Go SDK that was tested works against production bits.
Note: this is not a problem for the existing `storage` package, it already has some live testing capabilities, but it is also not generated from Swagger.

**Comment by mcardosos** [comment]
Samples need to be updated to v12

**Comment by mcardosos** [comment]
Samples in the samples repo are running against canary and prod. However there are a couple resource providers for which we need additional whitelisting in canary.

**Comment by mcardosos** [comment]
Samples have been running on Jenkins for a while
