### ISSUE TITLE
Failed to delete resource Shared Image when the delete API of Shared Image Gallery returns 404

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#8314]
### Bug Report

- Import path of package in question: https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2019-07-01/compute/galleryimages.go
- SDK version: v41.2.0
- Output of `go version`: go version go1.12.9 windows/amd64

- **What happened?**
The resource Shared Image depends on the resource Shared Image Gallery. Although the delete API returns 404 which means the Shared Image resource has been deleted. Then it tries to immediately delete Shared Image Gallery but it still throws error `Can not delete resource before nested resources are deleted.`, which means the resource Shared Image still hasn't been deleted. So it failed to delete top resource Shared Image Gallery.

- **What did you expect or want to happen?**
It should delete both resources Shared Image and Shared Image Gallery successfully.

- **How can we reproduce it?**
1. Create a resource group
2. Create Shared Image Gallery
3. Create Shared Image
4. Delete Shared Image, which returns "202"
5. Immediately call "Get" rest api to get resource Shared Image, which returns "404"
6. Immediately delete Shared Image Gallery, which returns error code "409"
7. Then it throws error `Can not delete resource before nested resources are deleted.`

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei thanks for this issue. I have tagged this issue so the corresponding service team will have a look

**Comment by Drewm3** [comment]
@axayjo, could you please take a look at this issue?

**Comment by axayjo** [comment]
@neil-yechenwei, do you have Image Versions under the Shared Image Definition?

**Comment by axayjo** [comment]
@neil-yechenwei Checking in again. Was this issue resolved? Do you have any updates for us?

**Comment by axayjo** [comment]
@neil-yechenwei Closing this since there's been no update. Feel free to reopen the issue if it resurfaces.
