### ISSUE TITLE
Enum has incorrect values in cost-management

### ISSUE THREAD

**Issue by jinxue-w** [Azure/azure-sdk-for-go#8318]
### Bug Report
A follow up for issue #8132 

Instead of `Tag` , it should have the value of `TagKey` [here](https://github.com/Azure/azure-sdk-for-go/blob/68d483faf640e457e33779443ebc5108b900d3ff/services/costmanagement/mgmt/2019-10-01/costmanagement/models.go#L108)

**Comment by ArcturusZhang** [comment]
Hi @jinxue-w could you please also provide the error message when you are assigning `Tag` to `QueryGrouping`?

**Comment by jinxue-w** [comment]
> 嗨@ jinxue-w分配`Tag`给您时，您还可以提供请求和错误消息`QueryGrouping`吗？

我已经修改了，问题已经解决，你们可以测试一下

**Comment by prem9in** [comment]
Thanks for the feedback, we will be updating swagger by end of this month.

**Comment by ms-premp** [comment]
Thanks for the feedback, we will be updating the swagger by end of this month.

**Comment by ms-premp** [comment]
Thanks for the feedback. We will update the swagger in coming month.

**Comment by jochav** [comment]
@jinxue-w the values should be "tags" instead of "tag" and "dimensions" instead of "dimension". We will be updating our documentation to reflect these changes. Thanks!

**Comment by ramaganesan-rg** [comment]
@jinxue-w - thank you for the feedback. May i go ahead to archive the request, if there are no further questions? please let us know.

**Comment by jinxue-w** [comment]
ok
