### ISSUE TITLE
Make Azure environments pluggable

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#8328]
It would get ideal to be able to seamlessly switch clouds, i.e. public cloud -> sovereign cloud.  In track 1 there is the [Environment](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L52) settings but it requires the caller to wire up all the endpoints themselves.
One idea is to add an Environment arg to client constructors that will contain all the endpoints and scope.  It would need to include the authority host to be passed to the `GetToken()` call.

**Comment by RickWinter** [comment]
Need to review our EndPoint usage.  The SDK needs to follow design guidelines for talking to many clouds

**Comment by JeffreyRichter** [comment]
@jhendrixMSFT This is a very old issue. I believe that our clients support multiple clouds simply by requiring the customer to pass an endpoint when creating each client and also by allowing them to override the authentication scope. Do you think there is anything else we need to do?

**Comment by jhendrixMSFT** [comment]
@JeffreyRichter while we do support this today via custom endpoints, you have to match them when authenticating and creating a client.  What I was conceptually envisioning was that you could indicate "use USGov cloud" and the correct endpoints would be wired up.

**Comment by RickWinter** [comment]
We need to ensure we can add this in the future without making a breaking change

**Comment by chlowell** [comment]
Yes, this was closed by #16942
