### ISSUE TITLE
Better Support For "Discriminator" Types

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#8367]
### Problem

THE current SDK is able to handle `discriminator` defined in swagger and generate the corresponding interface and concrete structures together with implementation. Additionally, it will generate a "base" struct which contains only the common attributes shared among other concrete structs. I assume this "base" struct is serving the purpose that the user can always get those common attributes from it, no matter which concrete struct current object actually belongs to. However, this mechanism actually not work currently.

### Example

Take [`BasicAlertRule`](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go#L1014) as example:

```go
type BasicAlertRule interface {
	AsFusionAlertRule() (*FusionAlertRule, bool)
	AsMicrosoftSecurityIncidentCreationAlertRule() (*MicrosoftSecurityIncidentCreationAlertRule, bool)
	AsScheduledAlertRule() (*ScheduledAlertRule, bool)
	AsAlertRule() (*AlertRule, bool)
}

// three concrete strucutrs

type FusionAlertRule struct {
	// FusionAlertRuleProperties - Fusion alert rule properties
	*FusionAlertRuleProperties `json:"properties,omitempty"`
	// ID - READ-ONLY; Azure resource Id
	ID *string `json:"id,omitempty"`
	// Name - READ-ONLY; Azure resource name
	Name *string `json:"name,omitempty"`
	// Type - READ-ONLY; Azure resource type
	Type *string `json:"type,omitempty"`
	// Etag - Etag of the azure resource
	Etag *string `json:"etag,omitempty"`
	// Kind - Possible values include: 'KindAlertRule', 'KindFusion', 'KindMicrosoftSecurityIncidentCreation', 'KindScheduled'
	Kind Kind `json:"kind,omitempty"`
}

type MicrosoftSecurityIncidentCreationAlertRule struct {
    // similar
}

type MicrosoftSecurityIncidentCreationAlertRule struct {
    // similar
}

// one base strucut
type AlertRule struct {
	autorest.Response `json:"-"`
	// ID - READ-ONLY; Azure resource Id
	ID *string `json:"id,omitempty"`
	// Name - READ-ONLY; Azure resource name
	Name *string `json:"name,omitempty"`
	// Type - READ-ONLY; Azure resource type
	Type *string `json:"type,omitempty"`
	// Etag - Etag of the azure resource
	Etag *string `json:"etag,omitempty"`
	// Kind - Possible values include: 'KindAlertRule', 'KindFusion', 'KindMicrosoftSecurityIncidentCreation', 'KindScheduled'
	Kind Kind `json:"kind,omitempty"`
}

// AsAlertRule is the BasicAlertRule implementation for FusionAlertRule.
func (far FusionAlertRule) AsAlertRule() (*AlertRule, bool) {
	return nil, false
}

```

Say if we have an `object` which has type `BasicAlertRule`, with underlying type of one of the concrete structs. Then if user simply wants to get the `ID` of the alert rule, one have to use `switch` type assertion to cast the `object` to the correct underlying type and reference the `ID` attribute. That would be a non-trivial experience.

### Proposal

A better solution might be that user could always call `object.AsAlertRule()` to get the `AlertRule` and reference the `ID` from it.

The required change is as below:

```go
type FusionAlertRule struct {
	// FusionAlertRuleProperties - Fusion alert rule properties
	*FusionAlertRuleProperties `json:"properties,omitempty"`
        AlertRule
}

// AsAlertRule is the BasicAlertRule implementation for FusionAlertRule.
func (far FusionAlertRule) AsAlertRule() (*AlertRule, bool) {
	return &far.AlertRule, false
}
```

There should also be no change needed for the marshal/unmarshal code.

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT would you please have a look at this?

**Comment by jhendrixMSFT** [comment]
We have redesigned how discriminated types will work for the track 2 SDK to be more idiomatic to the language.  Here's a very brief example.

```go
package main

import "fmt"

type FishType interface {
	fishType()
}

type Fish struct {
	ID       int
	FishType string // discriminator
}

func (f *Fish) fishType() {}

type Salmon struct {
	ID       int
	FishType string // discriminator
	Breed    string
}

func (f *Salmon) fishType() {}

type Tuna struct {
	ID       int
	FishType string // discriminator
	Color    string
}

func (f *Tuna) fishType() {}

func GetFish() FishType {
	return &Salmon{
		ID:       42,
		FishType: "salmon",
		Breed:    "king",
	}
}

func main() {
	switch x := GetFish().(type) {
	case *Salmon:
		fmt.Printf("caught a %s salmon\n", x.Breed)
	case *Tuna:
		fmt.Printf("the tuna has color %s\n", x.Color)
	}
}
```

Note that we won't be back-porting this to track 1 as it's a significant breaking change.

**Comment by magodo** [comment]
@jhendrixMSFT Thank you for providing the illustration above. While I feel that still doesn't fix the case that once user got a whatever fish. He/she should be able to access the comment field like `ID` without type assertion. Shouldn't we just embed the `Fish` struct as an anonymous field inside `Salmon` or `Tuna`?

**Comment by jhendrixMSFT** [comment]
I will discuss with the team about including the common fields as methods in the interface.  This came up before while working on this design however we decided against it (I forget why).

While using anonymous embedding of related types seems nice conceptually, the user experience is frustrating.  E.g. creating a `Salmon` literal becomes more verbose.

**Comment by magodo** [comment]
Yes, in that case could we have some `NewSalmon()` function?

**Comment by jhendrixMSFT** [comment]
We cannot have the common fields as methods in the interface as you cannot have a type with matching field (`ID`) and method (`ID()`) names.

Having a `NewSalmon()` is not really idiomatic to the language, considering that all the fields on `Salmon` are exported.

**Comment by magodo** [comment]
How about combining these ideas together? Make the field (`ID`) to be private (`id`) and provide the method `ID()` as a getter. Meanwhile, have a function called `NewSalmon()` to allow user to instantiate.

**Comment by jhendrixMSFT** [comment]
We discussed this as well, it's just not really idiomatic Go.

Is there a customer scenario here that's we've overlooked?

**Comment by magodo** [comment]
Yes, the abstract use case is the one a mentioned at the very beginning. The actual use case is in context of terraform azurerm provider, we will invokes several `GET` call for example, each one will return a `BasicAlertRule`, sometimes what I want to do is to simply retrieve the `ID` of the it, but I have to write a long `type switch` to convert it to the correct type and retrieve the `ID`. It would be super handy if I can directly access those "basic" fields from the interface, or if I can simply convert it to the "base" struct and access the fields via it (the "base" struct seems have no chance to be used for now).

**Comment by jhendrixMSFT** [comment]
After more discussion and prototyping we'll be going with the following.
```go
// FishType provides polymorphic access to various types of fish.
type FishType interface {
	GetFish() *Fish
}

// Fish is the "base" discriminated type.
type Fish struct {
	ID       int
	FishType string // discriminator
}

// GetFish implements the FishType interface.
func (f *Fish) GetFish() *Fish {
	return f
}

// Tuna inherits Fish.
type Tuna struct {
	Fish
	Color string
}

// SalmonType provides polymorphic access to various types of salmon.
type SalmonType interface {
	FishType
	GetSalmon() *Salmon
}

// Salmon inherits Fish.
type Salmon struct {
	Fish
	Breed string
}

// GetSalmon implements the SalmonType interface.
func (f *Salmon) GetSalmon() *Salmon {
	return f
}

// SmartSalmon inherits Salmon.
type SmartSalmon struct {
	Salmon
	IQ int
}

// GetFish returns some type of fish.
func GetFish() FishType {
	return &Tuna{
		Color: "white",
		Fish: Fish{
			ID:       42,
			FishType: "salmon",
		},
	}
}

// GetSalmon returns some type of salmon.
func GetSalmon() SalmonType {
	return &SmartSalmon{
		Salmon: Salmon{
			Breed: "king",
			Fish: Fish{
				ID:       98,
				FishType: "smart_salmon",
			},
		},
		IQ: 151,
	}
}
```

**Comment by magodo** [comment]
@jhendrixMSFT  thanks for the update!

The code looks pretty good and should solve my problem now! One little suggestion is that instead of defining a **Getter** (which is not so Go) for (e.g.) `Fish`/`Salmon`, we can just ensure that `Salmon` composes `Fish`. In this case, to allow `GetFish()` still returning a valid interface, we can define and implement the interface like:

```
type FishType interface {
	IsFishType()
}

func (f *Fish) IsFishType() {}
func (f *Salmon) IsFishType()  {}
func (f *Tuna) IsFishType() {}

type SalmonType interface {
    FishType
    IsSalmonType()
}

func (f *Salmon) IsSalmonType() {}
func (f *SmartSalmon) IsSalmonType() {}
```

So after the user calls `GetFish()`, he will get a `Salmon` or `Tuna` object. Then he can directly access the `Fish` field or fields inside `Fish`. Or he can type assert/switch to the type on his wish. Similarly, after the user calls `GetSalmon()`, he will get whatever `Salmon` and can directly access the `Salmon` field.

**Comment by jhendrixMSFT** [comment]
I renamed the "client APIs" to CatchA* as the names were ambiguous with the Get* methods on the interfaces.

Sorry I don't quite follow your example.  In my current draft, all derived types already are composed of `Fish`.  Also, which `GetFish()` and `GetSalmon()` are you referring to?  I think an end-to-end example would help.

The "Get" prefix is to avoid having a method with the same name as a field, i.e. on `Salmon` there is a field `Fish` so you cannot have a method named `Fish()`.  We could rename it to something else, perhaps `AsFish()`, open to suggestions.

**Comment by magodo** [comment]
The modified example based on yours is as below:

```go
// FishType provides polymorphic access to various types of fish.
type FishType interface {
	IsFish()
}

// Fish is the "base" discriminated type.
type Fish struct {
	ID       int
	FishType string // discriminator
}

// GetFish implements the FishType interface.
func (f *Fish) IsFish()  {}

// Tuna inherits Fish.
type Tuna struct {
	Fish
	Color string
}

// SalmonType provides polymorphic access to various types of salmon.
type SalmonType interface {
	FishType
	IsSalmon()
}

// Salmon inherits Fish.
type Salmon struct {
	Fish
	Breed string
}

// GetSalmon implements the SalmonType interface.
func (f *Salmon) IsSalmon()  {}

// SmartSalmon inherits Salmon.
type SmartSalmon struct {
	Salmon
	IQ int
}

// CatchAFish returns some type of fish.
func CatchAFish() FishType {
	return &Tuna{
		Color: "white",
		Fish: Fish{
			ID:       42,
			FishType: "salmon",
		},
	}
}

// CatchASalmon returns some type of salmon.
func CatchASalmon() SalmonType {
	return &SmartSalmon{
		Salmon: Salmon{
			Breed: "king",
			Fish: Fish{
				ID:       98,
				FishType: "smart_salmon",
			},
		},
		IQ: 151,
	}
}
```

The main change is to modify the interface definition of `FishType` and `SalmonType`. Since I think there should be no case that users really needs to call the method of those interfaces. Instead, they only serve for the purpose to make some types to be as some interface.

**Comment by jhendrixMSFT** [comment]
So when iterating over a slice of `FishType` how do you get the `ID` of each fish without performing a type assertion (I thought you wanted to avoid that)?

**Comment by magodo** [comment]
@jhendrixMSFT Oh yes, you're right. The getter for the parent structure(s) are necessary for this use case.

**Comment by magodo** [comment]
@jhendrixMSFT FYI if we are using embedded fields, maybe need to look out the (un)marshal implementation, for cases like [this](https://github.com/golang/go/issues/39175)

**Comment by jhendrixMSFT** [comment]
I have this working end-to-end for the autorest test server, see https://github.com/Azure/autorest.go/tree/track2/test/autorest/generated/lrogroup for what the complete codegen looks like.

**Comment by chamons** [comment]
Given that there is a checked [in test](https://github.com/Azure/autorest.go/blob/track2/.scripts/regeneration.js#L34) for this, is this issue resolved @jhendrixMSFT @magodo?

**Comment by chamons** [comment]
Also, the linked swagger is broken (as it was linking against master and not a hash).

https://github.com/Azure/azure-sdk-for-go/blob/3d1380634d6029820c1fc504da346e512fb36c87/services/securityinsight/mgmt/v1.0/securityinsight/models.go

I believe is what was referenced.
