### ISSUE TITLE
Generic version of the To package which will replace the To package someday

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-sdk-for-go#8400]
I was teaching myself Go generics and so the entire To package can be rewritten with this 1 function:

func Ptr(type T contracts.Ordered) (l T) *T {
   return &l
}

Someday, we can replace the to package with this.

**Comment by RickWinter** [comment]
to package was moved to internal and will be replaced when Go formally supports Generics.

**Comment by jhendrixMSFT** [comment]
It was moved to `azcore/to`.
