### ISSUE TITLE
anonymous and "Management" OperationGroup would trick generator

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#846]
See https://github.com/Azure/autorest.go/pull/42 for more details.

**Comment by vladbarosan** [comment]
This should be solved in the https://github.com/Azure/autorest.go/pull/52 . Opened issue #941 for other golint issues

**Comment by vladbarosan** [comment]
the generator build fails when this happens. still another related issue came from recovery services which fail because stuttering handling is not together with the others and also not part of the assuring uniqueness. #962
