### ISSUE TITLE
[FEATURE REQ] Add support for AZURE_CLIENT_ID environment variable to ManagedIdentityCredential

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-go#8465]
**Library or service name.**
Azure Identity
 
**Is your feature request related to a problem? Please describe.**
Developers need to be able to specify which AZURE_CLIENT_ID Managed Identity Credential with an environment variable. 

#6602

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT seems this should be added to go-autorest, could you please have a look?

**Comment by jongio** [comment]
Please follow up with @schaabs before implementing.

**Comment by catalinaperalta** [comment]
Closing this. Issue was resolved in #10841.
