### ISSUE TITLE
Go-Client for AKS(Azure Kubernetes Service)

### ISSUE THREAD

**Issue by StrongMonkey** [Azure/azure-sdk-for-go#847]
Is there a roadmap to generate go-client for AKS?

**Comment by tombuildsstuff** [comment]
+1 - I'd also been meaning to open an issue about this - I'm guessing it's blocked on the Swagger not existing?

**Comment by StrongMonkey** [comment]
@tombuildsstuff yeah, i think swagger pr is in [here](https://github.com/Azure/azure-rest-api-specs/pull/1956)

**Comment by marstr** [comment]
Once the PR is in, we will be able to publish as an additive change at will. If there's lag, feel free to ping us on it.

**Comment by marstr** [comment]
(Closing for now, as there isn't a unique action item)

Feel free to have us open this up again if you don't see the new AKS package once the swagger is available.
