### ISSUE TITLE
services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/ missing resources

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#8532]
The preview package for eventhub is missing many of the resources found in `services/eventhub/mgmt/2017-04-01/eventhub/` including Consumer Groups, Disaster Recover Configs and Event Hubs.  Are there are plans for those resources to be included in the preview package?

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry the config of `2018-01-01-preview/eventhub` was just updated 4 days ago in [this commit of specs](https://github.com/Azure/azure-rest-api-specs/commit/59d2942cfd8bc5c4a7256dadaf18bd06b124b033#diff-1533b1772133e88bb3048c3c7108d5ee), and it will be released in go SDK in the next major version (working on it right now)

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry v42.0.0 has been released, and the resources have be added into the `eventhub/2018-01-01-preview` package (for instance the [consumer groups](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/consumergroups.go)).
Therefore I will close this issue, please feel free to reopen if there are any other concerns. Thanks!
