### ISSUE TITLE
EventHub Cluster Put Failure

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#8533]
### Bug Report

- `services/preview/eventhub/mgmt/2018-01-01-preview/eventhub`
- `41.2.0`
- go version go1.14 darwin/amd64

I'm looking to create an eventhub cluster using [PUT](https://github.com/Azure/azure-sdk-for-go/blob/v41.3.0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go#L586). And the response comes back with 
```
{
	"error": {
		"code": "InvalidResource",
		"message": "The resource definition is invalid."
	}
}
```

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for this issue!
On my first glance, this error message does not give me much information about how this problem was raised... How about trying again after the new version of event hub SDK got out in the next major version of go SDK? It will be released in a day or two. The swagger of event hub changed quite a lot. Sorry for the inconvenience.

**Comment by katbyte** [comment]
@ArcturusZhang - that's kinda the point, that error message should probably be fixes by the service team :/ 

we can try the newer SDK and see if its changed thou.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang - that's kinda the point, that error message should probably be fixes by the service team :/
> 
> we can try the newer SDK and see if its changed thou.

Sure, I have tagged this issue so that the service team could take a look

**Comment by mbfrahry** [comment]
Hey @ArcturusZhang, I'm still seeing this issue with the latest version of the sdk. The reason there isn't much to go on is because there isn't much there. The only way to create a cluster in the sdk is by calling
```
Put(ctx context.Context, resourceGroupName string, clusterName string)
```
which is from [here](https://github.com/Azure/azure-sdk-for-go/blob/v42.1.0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go#L585)

**Comment by ArcturusZhang** [comment]
> Hey @ArcturusZhang, I'm still seeing this issue with the latest version of the sdk. The reason there isn't much to go on is because there isn't much there. The only way to create a cluster in the sdk is by calling
> 
> ```
> Put(ctx context.Context, resourceGroupName string, clusterName string)
> ```
> 
> which is from [here](https://github.com/Azure/azure-sdk-for-go/blob/v42.1.0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go#L585)

It is quite curious that a PUT request does not have a body, which does not look good to me.

**Comment by ArcturusZhang** [comment]
After checking the swagger of eventhub cluster, I can confirm that this should be a bug in swagger in which the service team forget to add the body parameter in the definition [here](https://github.com/Azure/azure-rest-api-specs/blob/b25cd297c7cb5f6b5991127c2b96a9c56dff50c7/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/Clusters-preview.json#L131)

The proof I found should be [this example](https://github.com/Azure/azure-rest-api-specs/blob/b25cd297c7cb5f6b5991127c2b96a9c56dff50c7/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/examples/Clusters/ClusterPut.json#L7) for Clusters_Put, as you can see, the request in this example do have a body:
```
    "parameters": {
      "sku": {
        "tier": "Dedicated",
        "capacity": 1
      },
      "location": "South Central US",
      "tags": {
        "tag1": "value1",
        "tag2": "value2"
      }
    }
  },
```
and it aligns with this [definition](https://github.com/Azure/azure-rest-api-specs/blob/b25cd297c7cb5f6b5991127c2b96a9c56dff50c7/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/Clusters-preview.json#L318) in the response

**Comment by ArcturusZhang** [comment]
@jfggdl @v-Ajnava @sazeesha @dsouzaarun could you please have a look at this issue?

**Comment by mbfrahry** [comment]
Thanks for finding that @ArcturusZhang!

**Comment by favoretti** [comment]
Anxiously following this as we're waiting for EH Clusters support in TF provider! :)

**Comment by ArcturusZhang** [comment]
Should be resolved by [this PR](https://github.com/Azure/azure-sdk-for-go/pull/9756)
