### ISSUE TITLE
Stuttering in the services\...\management package fails golint

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#856]
Repro by checking out v11.2 or later locally and running the following command:

 `golint github.com/Azure/azure-sdk-for-go/services/...`

It will fail with the following complaints:
```
services\resources\mgmt\2017-08-31-preview\management\client.go:37:6: type name will be used as management.ManagementClient by other packages, and that stutters; consider calling this Client
services\resources\mgmt\2017-08-31-preview\management\models.go:57:6: type name will be used as management.ManagementGroupType by other packages, and that stutters; consider calling this GroupType
```
Depending on how we fix #846, the package impacted by this issue may change, or this issue may be solved simultaneously.

edit: grammar

**Comment by vladbarosan** [comment]
This is solved here Azure/autorest.go#52 . Opened issue #941 for other golint issues
