### ISSUE TITLE
Add AKS Client

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#860]

**Comment by moritzheiber** [comment]
What's the status on this? Would love to get this moving along so that terraform-provider-azurerm#471 can be implemented. People are eager to try the new service :smiley:

**Comment by StrongMonkey** [comment]
@vladbarosan Kindly reminder that https://github.com/Azure/azure-rest-api-specs/pull/1956 has been merged today. 😄

**Comment by vladbarosan** [comment]
@StrongMonkey thanks for the reminder 😄 . I worked with the author to get it in. We delayed the v0.12 release a little to fix an issue with Stream Analytics but he should be ready to release tomorrow if no other major issue appears.

**Comment by vladbarosan** [comment]
@StrongMonkey  @moritzheiber  we just release v0.12 https://github.com/Azure/azure-sdk-for-go/releases/tag/v12.0.0-beta . Thanks for patience!
