### ISSUE TITLE
Register providers for subscriptions

### ISSUE THREAD

**Issue by cdelacruzpinto** [Azure/azure-sdk-for-go#8608]
### Feature Request

At this moment, if one has a freshly created subscription, it is not possible to create certain resources. I.e: a KeyVault without registering the appropriate provider Microsoft.KeyVault. One needs to use the az resource register command from the CLI. There is an endpoint in the azure API for this, but there is no support for it in the SDK.

**Comment by ArcturusZhang** [comment]
Hi @cdelacruzpinto thanks for this issue.

I believe [this](https://github.com/Azure/azure-sdk-for-go/blob/3f64637acf66a92ee46a1987273ad740291d3c99/services/resources/mgmt/2019-05-01/resources/providers.go#L129)  may meet your requirement, could you please have a try?

**Comment by cdelacruzpinto** [comment]
Yes, this function was exactly what I needed. I looked at the documentation for some time and was unable to find something like this. We can close this issue. Thanks.
