### ISSUE TITLE
Write sample for new mongodb client

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#863]
Support for mongodb via mango package was added in https://github.com/Azure/azure-sdk-for-go/pull/844, now we need a sample for it.

**Comment by jhendrixMSFT** [comment]
If possible also include mongodb in user-agent so we can track usage.

**Comment by joshgav** [comment]
tracked here: https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/20
