### ISSUE TITLE
Add support for Cassandra in CosmosDB

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#864]
1. Choose a client library for Cassandra API in CosmosDB (see https://docs.microsoft.com/en-us/azure/cosmos-db/cassandra-introduction).
1. Vendor the lib into SDK project.
1. Symlink into services/cosmosdb directory, with helpers or monkey patches needed for seamless Azure support.

**Comment by RickWinter** [comment]
Closing old issue, new Cosmos work can open a new issue if applicable
