### ISSUE TITLE
Improve List/ListAll experience

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#865]
The List and ListAll APIs are clunky and hard to use, plus the latter one returns a channel which is an anti-pattern.  Will probably implement an iterator pattern.

**Comment by blndev** [comment]
When you rewrite the function, please think about supporting the "expand InstanceViewType" in the Call as it is in the Get call https://github.com/Azure/azure-sdk-for-go/blob/master/arm/compute/virtualmachines.go#L568.

Currently i'm using ListAll, then filtering by Tags and then use vmClient.Get to see the status of the machine like running or stopped.
Maybe you have some better suggestions.

By the way the Resource Group is not a Part of the Response from ListAll. That makes it very difficult to handle the VM or executing a vmClient.Get call.

**Comment by joshgav** [comment]
can we add a sample for this in https://github.com/Azure-Samples/azure-sdk-for-go-samples

**Comment by jhendrixMSFT** [comment]
We have addressed this in the v12 SDK by having pageable operations return a Page abstraction to simplify iterating over the result set.
