### ISSUE TITLE
SQL Server API seems to ignore `minimalTlsVersion` sdk property

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#8663]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
  `"github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/v3.0/sql"`

- SDK version e.g. `master`, `latest`, `18.1.0`
  `github.com/Azure/azure-sdk-for-go v41.2.0+incompatible`

- output of `go version`
1.14

- What happened?
i tried to set the `minimalTlsVersion` version but it seems to be ignores:

put@https://management.azure.com/subscriptions/x/resourceGroups/acctestRG-mssql-200428201737595165/providers/Microsoft.Sql/servers/acctestsqlserver200428201737595165?api-version=2019-06-01-preview
```
{
	"identity": {
		"type": "SystemAssigned"
	},
	"location": "westus2",
	"properties": {
		"administratorLogin": "mradministrator",
		"administratorLoginPassword": "thisIsCat11",
		"version": "12.0",
		"minimalTlsVersion": "1.0",
		"publicNetworkAccess": "Enabled"
	},
	"tags": {
		"ENV": "Staging",
		"database": "NotProd"
	}
}
```

get@https://management.azure.com/subscriptions/1a6092a6-137e-4025-9a7c-ef77f76f2c02/resourceGroups/acctestRG-mssql-200428201737595165/providers/Microsoft.Sql/servers/acctestsqlserver200428201737595165?api-version=2019-06-01-preview
```
{
	"kind": "v12.0",
	"properties": {
		"administratorLogin": "mradministrator",
		"version": "12.0",
		"state": "Ready",
		"fullyQualifiedDomainName": "acctestsqlserver200428201737595165.database.windows.net",
		"privateEndpointConnections": [],
		"publicNetworkAccess": "Enabled"
	},
	"location": "westus2",
	"tags": {
		"ENV": "Staging",
		"database": "NotProd"
	},
	"name": "acctestsqlserver200428201737595165",
	"type": "Microsoft.Sql/servers"
}

```

- What did you expect or want to happen?
the property to be set 

- How can we reproduce it?
above api paylog

- Anything we should know about your environment.
no

**Comment by ArcturusZhang** [comment]
Hi @katbyte thanks for this issue!
This should be a service side issue, and I have tagged this issue so that the corresponding service team will receive message and have a look at this.

**Comment by azureSQLGitHub** [comment]
@Mike Wang<mailto:ziwa@microsoft.com> would you be able to own this one?

**Comment by adeal** [comment]
@ziwa-msft

**Comment by ziwa-msft** [comment]
@katbyte Thanks for reaching out to us. This is due to the fact that TLS Version Choice feature rollout got unexpectedly delayed due to Covid-19. The APis are released but we had to disable the feature in the backend. As of now, the plan is to roll out this feature by next month. Please stay tuned to our official feature announcement before trying it out. Thanks for your patience.

**Comment by azureSQLGitHub** [comment]
Replied.

Thanks Austin.

From: Austin Deal <adeal@microsoft.com>
Sent: Wednesday, April 29, 2020 11:08 PM
To: Azure/azure-sdk-for-go <reply@reply.github.com>; Azure/azure-sdk-for-go <azure-sdk-for-go@noreply.github.com>; Mike Wang <ziwa@microsoft.com>
Cc: Azure SQL GitHub issues notifications <sqldbghissues@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-sdk-for-go] SQL Server API seems to ignore `minimalTlsVersion` sdk property (#8663)

@Mike Wang<mailto:ziwa@microsoft.com> would you be able to own this one?

**Comment by lirenhe** [comment]
The latest release of Sql already contains this feature. Close this item and @katbyte please let us know if you still face the problem.
