### ISSUE TITLE
Need a listing of Azure API endpoints

### ISSUE THREAD

**Issue by kawsark** [Azure/azure-sdk-for-go#8667]
### Feature Request

Hello,
To setup network access in order to use the Go SDK, would it be possible to provide what Azure endpoints need to be whitelisted? More specifically, we are using the following parts of the SDK:
```
github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac
github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization
github.com/Azure/go-autorest/autorest
github.com/Azure/go-autorest/autorest/azure/auth
```
Thank you.

**Comment by ArcturusZhang** [comment]
Hi @kawsark thanks for this issue.

Unfortunately I do not have much knowledge about this... @jhendrixMSFT could you please have a look? Is it possible?

**Comment by jhendrixMSFT** [comment]
Assuming you're using the public cloud (i.e. not one of the sovereign clouds) you should be able to search through the source code you include to find all the endpoints; there is no programmatic way to get this information.

**Comment by kawsark** [comment]
Thanks @jhendrixMSFT . Would you be able to provide an example endpoint? I can then try to write a script find these URLs.

**Comment by jhendrixMSFT** [comment]
Here are a few based on the packages you provided.

https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go#L29

https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L85

**Comment by kawsark** [comment]
Thank you @jhendrixMSFT! Thats super valuable!
