### ISSUE TITLE
short import paths (instead of github.com/...)

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#867]
Today, code written targeting the Azure SDK for Go must be imported using the path:

``` Go
import (
    "github.com/Azure/azure-sdk-for-go/services/[name of service]/[path to dataplane or management package]"
)
```

Not only is this cumbersome, the casing choice of the "Azure" organization can cause problems for folks. Especially if they accidentally `go get github.com/azure/azure-sdk-for-go`.

If we were to use a vanity import path, we could conceivably reduce the number of characters used to import our code, and do away with annoying casing choices.

Off of the top of our heads, these are a couple of our ideas:
  1. "azure.microsoft.com/[services]/[versions]
  1. "az.msft.com/go/services"
  1. "go.microsoft.com/azure"

**Comment by vladbarosan** [comment]
@joshgav @marstr  is this something we are still chasing or  close ?

**Comment by marstr** [comment]
This is still something we're chasing.

Truthfully, it probably makes sense to do this at the same time that we move to support `vgo` modules, which are supposed to land in February. I wouldn't mind setting up some time next sprint to experiment with `vgo` and make sure we're still on the right track.

**Comment by vladbarosan** [comment]
@marstr  February 2019 ? that seems pretty far away and anything could change. I would just close this if that is the case.

**Comment by marstr** [comment]
Works for me. It doesn't seem like we've been gathering any feedback by having this issue open, which is the only reason I would leave it open.

**Comment by marstr** [comment]
I do want to qualify my statement above a little. Just because we didn't get feedback here, doesn't mean that there isn't good feedback to hear about this. We don't want to pull a "beware of the leopard"

**Comment by vladbarosan** [comment]
everyone agrees closing and when vgo comes up we will start tracking issues related to that then.
