### ISSUE TITLE
client.Get on missing network mapping returns StatusCode 400 instead of 404

### ISSUE THREAD

**Issue by martenbohlin** [Azure/azure-sdk-for-go#8705]
### Bug Report

- import path of package in question `azure-sdk-for-go/services/recoveryservices/mgmt/2018-01-10/siterecovery`
- SDK version v41.2.0
- output of `go version` `go version go1.13.7 darwin/amd64`

- What happened?
Invoking client.Get(ctx, fabricName, networkName, networkMappingName) where for a valid fabric and network but where no mapping has yet been created will return a response where the StatusCode is **400**

- What did you expect or want to happen?
Expected respinse code is **404**. The other APIs return 404 if a resource is missing

- Anything we should know about your environment.
This used to work before, not sure when it stopped working, but it is causing issues for terraform users. 

See bug reported on terraform: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6026

**Comment by allenjzhang** [comment]
Thank you for reporting this issue to us. Marking issues for service team to respond. Here is the link to the operation in [REST API spec.](https://github.com/Azure/azure-rest-api-specs/blob/698dd56aed277461ad3975deb78b3b78b5354ebf/specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2018-01-10/service.json#L1041)

**Comment by sideeksh** [comment]
This is a bug. We are issuing a fix in the next release (ETA 1st week of June 2020). Bug: https://msazure.visualstudio.com/One/_workitems/edit/6244666/

**Comment by sideeksh** [comment]
We are still reviewing and will respond with an update shortly.

**Comment by Sharmistha-Rai** [comment]
We are planning to release a fix for this in our future updates.

**Comment by Sharmistha-Rai** [comment]
Please feel free to reopen for any additional queries.

**Comment by Sharmistha-Rai** [comment]
This bug has been fixed an released. Please feel free to reopen in case you still face any issues.
#please-close

**Comment by Sharmistha-Rai** [comment]
#please-close

**Comment by Rajeswari-Mamilla** [comment]
#please-close

**Comment by Sharmistha-Rai** [comment]
@allenjzhang - could you please close this issue? I'm unable to close it.

**Comment by allenjzhang** [comment]
Sure. Thank you for fixing the issue.
