### ISSUE TITLE
Delete `arm`, `dataplane`, and `datalake-store` directories

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#875]
In v12, these are being marked as deprecated, in v13 these should be deleted.

**Comment by marstr** [comment]
To elaborate further, this is part of a broader effort to clean up the repository and make it easier to navigate when people first arrive at our repository. The broader effort is being tracked by #798.

**Comment by joshgav** [comment]
have we marked all of these as deprecated?

**Comment by jhendrixMSFT** [comment]
When these are deleted we should be sure they get deleted from https://godoc.org/github.com/Azure/azure-sdk-for-go

**Comment by marstr** [comment]
Done in Dev.
