### ISSUE TITLE
web.Site json round-trip serialisation is broken

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-sdk-for-go#8767]
### Bug Report

- import path of package `"github.com/Azure/azure-sdk-for-go/services/web/mgmt/2019-08-01/web"`

- SDK version `v42.0.0`

- `go version go1.14.2 darwin/amd64`

- What happened?

Getting the list of web apps, serialise response into JSON, and then back. 
Some properties are `nil` after this, namely `Name`.

- What did you expect or want to happen?

All properties in the original `[]web.Site` survive round-trip JSON serialisation.

Looking at the SDK code, it does not add `ID` and `Name` to the serialisation map. Clearly an oversight? https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2019-08-01/web/models.go#L17659

**Comment by ppanyukov** [comment]
The workaround here is to bypass custom mashaller implemented by `web.Site` type (why is it needed anyway?) like so:

```go
// declare an alias to web.Site to bypass custom marshaller
type siteC web.Site

// get the list of web apps
// the actual call is different as it goes via the iterator
// here just for illustration
var apps []web.Site = appsClient.List(ctx)

// use unsafe hackery to cast slice to alias
appsC := *(*[]siteC)(unsafe.Pointer(&apps))

// marshal
j, err := json.MarshalIndent(appsC, "", "  ")

// unmarshal back
var appsC []siteC
json.Unmarshal(cacheBytes, &appsC)

// use unsafe hackery again to cast back to []web.Site
apps := *(*[]web.Site)(unsafe.Pointer(&appsC))
```

Very ugly but seems to resovle this particular issue. Not sure if anything else would be broken by this though.

**Comment by ArcturusZhang** [comment]
Hi @ppanyukov thanks for the issue!
Sorry for the inconvenience that this issue has caused, but the behavior is kind of by designed...
First thing is that the whole track 1 go SDK (almost everything in `services` directory) is auto-generated from [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs). For a particular REST API, you will have to marshal the a go struct to JSON payload. The rest api specs may mark some of the properties in the payload as `read-only` (and in your case, `name` and `id` are read-only, you can find it [here](https://github.com/Azure/azure-rest-api-specs/blob/42df7cfde61ff57f0234c99462a8d51cd0514e02/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/CommonDefinitions.json#L1582). Note that the object `Site` inherent the object `Resource`), and the read-only properties should not be in the request payload, therefore go SDK will not include those field into the marshaler.

**Comment by ppanyukov** [comment]
Thanks. I can see your point. But. Consider that serialisation to JSON just drops the fields. This prevents caching (roundtrip is broken), and even printing things out in JSON format. Every time I need JSON output I must not forget to use alias. This does not feel quite right to me.

Now looking at this, *all* types are broken, not just `web.Site`, if they all follow the same design. For example `resources.GenericResource` is broken too -- same problem `ID` and `Name` are missing from JSON output because they are marked as "read-only".

If all types are broken, do I need to alias everything?

**Comment by ppanyukov** [comment]
Oh and it just occurred to me -- what about the field in the top-level types? For example, `web.Site` has field `*SiteProperties`, and it has tons of read-only properties all of which I suspect will be missing in JSON output? Aliasing doesn't solve that.

**Comment by ppanyukov** [comment]
So, I found a sort of workaround for JSON printing at least. 

The idea is to use response inspector to capture raw JSON response from API and use that :) As per docs: https://github.com/Azure/azure-sdk-for-go#writing-custom-requestresponse-inspectors

I assume that deserialising types from it should work too (but haven't tested that yet).

While this works, it's not pretty.

```go
// Will capture raw JSON from API HTTP response and pretty-format it here.
var jsonBytes []byte

// This will plug into the API call
responseTrapFn := func(p autorest.Responder) autorest.Responder {
    return autorest.ResponderFunc(func(r *http.Response) error {
        err := p.Respond(r)
        cmdutil.CheckErr(err)

        bodyBytes, err := ioutil.ReadAll(r.Body)
        cmdutil.CheckErr(err)

        // Need to pretend we haven't read the body
        saveBody := ioutil.NopCloser(bytes.NewBuffer(bodyBytes))
        r.Body = saveBody

        jsonMap := make(map[string]interface{})
        err = json.Unmarshal(bodyBytes, &jsonMap)
        cmdutil.CheckErr(err)

        jsonFormatted, err := json.MarshalIndent(jsonMap, "", "  ")
        cmdutil.CheckErr(err)

        jsonBytes = jsonFormatted
        return nil
    })
}

// Do things normally.
resClient := resources.NewClient(azClient.SubscriptionId())
resClient.ResponseInspector = responseTrapFn
resClient.Authorizer = azClient.Authoriser()
result, err := resClient.GetByID(ctx, to.String(f.ID), to.String(f.ApiVersion))
cmdutil.CheckErr(err)

// Print JSON or do whatever with it.
_, err = os.Stdout.Write(jsonBytes)
cmdutil.CheckErr(err)
```

**Comment by jhendrixMSFT** [comment]
The omission of read-only properties when making a request to the REST endpoint is a hard requirement from ARM (Azure Resource Manager).  Unfortunately, at present I don't have a good solution other than aliasing types to remove the custom marshaller (which doesn't work for nested types as you pointed out).

We're working on an updated version of our Go SDK, I'll be sure to enable this scenario.  Depending on the solution we might be able to back-port it but I can't commit to that at present.

**Comment by lirenhe** [comment]
@ppanyukov，do you still face this issue?

**Comment by ppanyukov** [comment]
I will need to check @lirenhe , I assume there were changes to the SDK which should help resolve this?

**Comment by lirenhe** [comment]
We are working on the preview of the next version of Go SDK. And we started to preview a couple of packages. you could have a try of https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/web/armweb to check whether it solves your problem.
