### ISSUE TITLE
Investigate services/resources package

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#877]
As noted in #873, there was one hand written file in the `arm` directory that I ported over into the `services` directory. We need to go make sure that it is in the right place, and that it makes sense to continue to have it.

**Comment by mcardosos** [comment]
They are helper methods I added for template deployment.
I might have added them so we could use them on a sample

**Comment by joshgav** [comment]
we should consider if this should be migrated to the samples repo

**Comment by mcardosos** [comment]
There is already similar code [here](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/820e6fb1ed79e7c39820feeed897e4a22092272e/_quickstarts/deployments.go#L93)
