### ISSUE TITLE
Can't list/read publicly accessible blobs

### ISSUE THREAD

**Issue by aviaoh** [Azure/azure-sdk-for-go#878]
Seems like sdk forces to create storage client with valid key. 
Is there any way to bypass it and list all blobs/read a specific blob from a container with a container access policy?

I'm using current version of sdk. Thanks :)

**Comment by jhendrixMSFT** [comment]
Hello!  Unfortunately the current design doesn't allow a way around this.  However, we have just released a preview of our new package, azblob, that will replace the blob storage functionality in the storage package.  You can find it here https://github.com/Azure/azure-storage-blob-go, and I believe it will do exactly what you're asking about here.

**Comment by aviaoh** [comment]
great! thanks for the update :)
