### ISSUE TITLE
Improve and simplify authentication

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#881]
The current implementation requires callers to write some boiler-plate code, plus it's not very intuitive in some cases.  We should retool how authentication works so it's easier to use.

**Comment by mxork** [comment]
+1 for this. Some docs or `examples/` would go a long way, but a client constructor which handles auth would certainly be the least-surprise way to address this issue.

**Comment by vladbarosan** [comment]
@mxork thanks for the suggestions. We already have some work done on this here https://github.com/Azure/go-autorest/pull/221

One of the options we are considering is to integrate this with the constructor for the clients. We are targeting this for GA so stay tuned!

**Comment by vladbarosan** [comment]
The previous mentioned PR was merged and will be available in the next SDK release. Also we decided not to follow up on including a parameter in the constructor ( See #943 )
