### ISSUE TITLE
App Service Client should poll for HTTP the status code 429

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#884]
👋🏻

[We've had an issue come in](https://github.com/terraform-providers/terraform-provider-azurerm/issues/600) where the following retry-able error is being retuned from the Azure API but isn't automatically retried by the SDK. Here's the error:

> web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Put https://management.azure.com/subscriptions/eXXXXXX-cXXX-4XXX-bXXX-dXXXXXX/resourceGroups/agid-rg-test/providers/Microsoft.Web/serverfarms/agid-app-test?api-version=2016-09-01: http: ContentLength=131 with Body length 0

and the associated message from the logs:

> Cannot acquire exclusive lock to create or update this server farm. Retry the request later.`

After asking the requestor for more information, it appears that a HTTP 429 is being returned from the Azure API but not exposed/polled for in the SDK: https://gist.github.com/gunzip/46e32eedaaedf57902195e8a4ec634c9

Whilst I'm aware the Web API's are a little different to the rest of the Azure API's (insofar as they don't necessarily match the Status Codes usages returned by the other API's) - would it be possible to look into polling for this Status Code?

Thanks!

**Comment by jhendrixMSFT** [comment]
This looks related to https://github.com/Azure/go-autorest/issues/214

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff this should be fixed in v9.5.1 of go-autorest.  Please re-open if you can still repro this issue with that version all I'll investigate further.
