### ISSUE TITLE
Support Context.context in /storage

### ISSUE THREAD

**Issue by mappu** [Azure/azure-sdk-for-go#885]
Hi,

The `/storage` package does not support context.Context. This is important to allow request cancellation and management from user code.

#797 began the work of adding context support, but, it doesn't yet seem to be possible in the `/storage` package.

Thanks,

**Comment by jhendrixMSFT** [comment]
Hello!  Which features in storage are you using?  I ask because we are slowing deprecating the functionality in this package, replacing it with new packages.  If you're using blob storage you should take a look at our new azblob package which does use context.Context.
https://github.com/Azure/azure-storage-blob-go
We don't yet have replacements for files/tables/queues though.

**Comment by mappu** [comment]
I am only using blob storage.

Honestly I am a little bit hesitant to move to that new package. It doesn't seem mature yet, and it has a very different-looking API.

Is it based-on `/storage` in this repository? And if not,
- Does that new package cover all uses of blob storage that were covered by `/storage` ?
- Can users expect the same reliability/performance/behaviour?
- Is there a porting guide?

What is the reason for this change?
- What will happen to this `azure-sdk-for-go` repository?
- Are the other APIs going to be split out into separate repositories, as well?
- Is the new `azblob` package autogenerated (e.g. from autorest)?
- If it is not autogenerated, what are the expectations about maintenance and updates?

**Comment by jhendrixMSFT** [comment]
This is a completely rewritten API for blob storage however it's based on the same REST API version.  Some of your questions might be answered in the [docs](https://godoc.org/github.com/Azure/azure-storage-blob-go/2016-05-31/azblob), and I will try to answer the rest here.
The azblob package is a superset of functionality of blobs in the storage package and while we have not performed any comparison of perf between the two I would expect azblob to have parity or better perf compared to storage as we were very mindful of this during the rewrite (e.g. there is no double-buffering of streams when retrying a request).
The current plan is to pull the azblob package into the azure-sdk-for-go repo so you can continue to just reference the one repo however this work has not happened yet.  Note that we plan on doing this for other packages in the repo however it will happen in a way that's completely transparent to consumers so no calling code will have to change.
All of the content in the storage package is hand-written, whereas for azblob the "protocol" layer is generated from swagger via AutoRest (see the files with the prefix zz_generated*) with hand-written "convenience" and "fitness" layers on top; this way we can easily add high-level abstractions on top of the protocol, e.g. the ability to upload files of arbitrary size with one function call.
CC @jeffreyrichter

**Comment by joshgav** [comment]
cc @seguler

**Comment by joshgav** [comment]
ref #903

**Comment by joshgav** [comment]
@vladbarosan will https://github.com/Azure/autorest.go/pull/43 apply to `storage/` here too?

**Comment by jhendrixMSFT** [comment]
@joshgav No, everything in storage/ is hand-written.

**Comment by jhendrixMSFT** [comment]
I'm going to close this as we are phasing out this package.  That said we are happy to accept PRs if you'd like to add this functionality.
