### ISSUE TITLE
[EventHub] Add properties to capture messages to data lake

### ISSUE THREAD

**Issue by thsutton** [Azure/azure-sdk-for-go#887]
I've opened https://github.com/Azure/azure-rest-api-specs/issues/2120 to add the additional fields needed to support capturing EventHub messages to a Data Lake Store account as well as a Storage account. If I understand correctly, the above change to the specs will, at some point, filter through to this project?

I've tested manual changes to the Go SDK code (see diff below) vendored in my project and it seems to work fine.

```
diff --git a/vendor/github.com/Azure/azure-sdk-for-go/arm/eventhub/models.go b/vendor/github.com/Azure/azure-sdk-for-go/arm/eventhub/models.go
index afef330..0ff6e8b 100755
--- a/vendor/github.com/Azure/azure-sdk-for-go/arm/eventhub/models.go
+++ b/vendor/github.com/Azure/azure-sdk-for-go/arm/eventhub/models.go
@@ -231,6 +232,9 @@ type DestinationProperties struct {
 	StorageAccountResourceID *string `json:"storageAccountResourceId,omitempty"`
 	BlobContainer            *string `json:"blobContainer,omitempty"`
 	ArchiveNameFormat        *string `json:"archiveNameFormat,omitempty"`
+	DataLakeSubscriptionID   *string `json:"dataLakeSubscriptionId,omitempty"`
+	DataLakeAccountName      *string `json:"dataLakeAccountName,omitempty"`
+	DataLakeFolderPath       *string `json:"dataLakeFolderPath,omitempty"`
 }
 
 // EHNamespace is single Namespace item in List or Get Operation
```

**Comment by vladbarosan** [comment]
Hi @thsutton  thanks for opening the issue. Yes once the change is made in the specs it will make its way here in the immediate release after those get updated.

**Comment by thsutton** [comment]
Thanks

**Comment by vladbarosan** [comment]
v0.12 has been released with the code updated according to the specs. Please reopen the issue if you still see any issue. Also please note that we deprecated `arm` folder. Please use `profiles` and `services` folder instead.

**Comment by thsutton** [comment]
The change hasn't been done upstream yet but I'm happy to close this now and reopen later if necessary. Thanks.

**Comment by vladbarosan** [comment]
@thsutton  I checked that the issue you opened on the specs was not addressed. once that gets updated it will be included in our next release, but first the event hub team needs to decide if they want to make the change.
