### ISSUE TITLE
[key vault] Use of Key Vault Secrets

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#888]
:wave: heyo!

We've had [an issue opened on the Terraform Repository about the use of Key Vault Secrets within Resources](https://github.com/terraform-providers/terraform-provider-azurerm/issues/606).

Picking [this ARM Template at random](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter#reference-a-secret-with-static-id) - it's possible to specify a Reference to a Key Vault ID as an alternative to specifying the password directly:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "adminLogin": {
            "value": "exampleadmin"
        },
        "adminPassword": {
            "reference": {
              "keyVault": {
                "id": "/subscriptions/<subscription-id>/resourceGroups/examplegroup/providers/Microsoft.KeyVault/vaults/<vault-name>"
              },
              "secretName": "examplesecret"
            }
        },
        "sqlServerName": {
            "value": "<your-server-name>"
        }
    }
}
```

However the SDK only exposes the AdminPassword field as a String (and the other fields don't seem to be applicable here):

```
// OSProfile is specifies the operating system settings for the virtual machine.
type OSProfile struct {
	ComputerName         *string               `json:"computerName,omitempty"`
	AdminUsername        *string               `json:"adminUsername,omitempty"`
	AdminPassword        *string               `json:"adminPassword,omitempty"`
	CustomData           *string               `json:"customData,omitempty"`
	WindowsConfiguration *WindowsConfiguration `json:"windowsConfiguration,omitempty"`
	LinuxConfiguration   *LinuxConfiguration   `json:"linuxConfiguration,omitempty"`
	Secrets              *[]VaultSecretGroup   `json:"secrets,omitempty"`
}

// VaultSecretGroup is describes a set of certificates which are all in the same Key Vault.
type VaultSecretGroup struct {
	SourceVault       *SubResource        `json:"sourceVault,omitempty"`
	VaultCertificates *[]VaultCertificate `json:"vaultCertificates,omitempty"`
}

// VaultCertificate is describes a single certificate reference in a Key Vault, and where the certificate should reside
// on the VM.
type VaultCertificate struct {
	CertificateURL   *string `json:"certificateUrl,omitempty"`
	CertificateStore *string `json:"certificateStore,omitempty"`
}
```

Is this functionality still supported? If so - I'm assuming that this is missing from the Swagger and I can raise an issue over there - however I wanted to check first that it wasn't intentionally missing/absent from the SDK?

Thanks!

**Comment by vladbarosan** [comment]
Hi @tombuildsstuff ! 

I took a look and a couple of points:
1. The article you are referencing refers to *ARM deployment templates*. So that is not using any compute client, it is a feature of the ARM template deployment to be able to refer the password parameter from the Key Vault.
2. To note that you can achieve this also using the SDK by retrieving the secret from Key Vault and then passing it as a parameter to this client.

Let me know if this clarifies the issue.

**Comment by tevert** [comment]
I'll jump in, since I logged terraform-providers/terraform-provider-azurerm#606.

We're looking to have an option to emulate the ARM template behavior so that we don't need to directly handle secrets client-side. Specifically, Terraform will serialize everything it plans to do to a file, and doesn't have a great way to protect secrets in that file.

So we're looking for a way to leverage that feature of ARM templates via the Go SDK. 

Does that help? Thanks!

**Comment by tombuildsstuff** [comment]
hey @vladbarosan

Thanks for looking into this :)

To clarify I was referencing the ARM Template an example of how the Virtual Machine API works (since, from my understanding each resource in the ARM Template is sent as the HTTP body to the respective API from the ARM Template Deployment endpoint)? (although I may be misunderstanding this heh 😄)

> The article you are referencing refers to ARM deployment templates. So that is not using any compute client, it is a feature of the ARM template deployment to be able to refer the password parameter from the Key Vault.
> To note that you can achieve this also using the SDK by retrieving the secret from Key Vault and then passing it as a parameter to this client.

Whilst it's possible to obtain the value of the secret from Key Vault (and submit this as the value of the `adminPassword` field) like so:

```
adminPassword: "foo"
```

it also appears to be valid to submit a reference to the Key Vault Secret to use in it's place, like so:

```
"adminPassword": {
  "reference": {
    "keyVault": {
      "id": "/subscriptions/<subscription-id>/resourceGroups/examplegroup/providers/Microsoft.KeyVault/vaults/<vault-name>"
    },
    "secretName": "examplesecret"
  }
}
```

This is the first time I've seen an API designed in this fashion, so I'm unsure if it's possible to represent this setup in the Swagger? Whilst we _could_ retrieve the password I don't believe that's ideal if it's possible to submit the Key Vault Reference directly to Azure?

What do you think? :)

Thanks!

**Comment by vladbarosan** [comment]
@tombuildsstuff  checking the [compute swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L4146)  service itself uses the key vault secret for getting certificates on the VM, but again for the admin password they don't seem to support this. 

My guess is that ARM deployment service takes care of getting the secret from the key vault (to note that even there deploy permission needs to be given on the key vault).  Given this, I think this is not even about incomplete swagger, but the service itself does not support it.

Adding @joshgav to follow up with the service team as a feature request.  

Let me know if you have any other questions.

**Comment by tombuildsstuff** [comment]
@vladbarosan 👍 awesome, thanks

**Comment by glenjamin** [comment]
Is there a tracking issue for this feature in whatever other repository it's being tracked in now?
