### ISSUE TITLE
[storage] Client does not authenticate properly with an SAS generated from a container's access policy

### ISSUE THREAD

**Issue by StrikerX3** [Azure/azure-sdk-for-go#889]
I've been trying to use this library to write blobs and messages to a queue on an Azure account using a Shared Access Signature token generated with one of my container's access policies. The issue I'm facing is that it does not seem to support Shared Access Signatures based on a container's access policy at all.

If I try to use a client created with `storage.NewClientFromConnectionString`, following [these instructions](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1#authenticating-from-a-client-application-with-a-sas) to build the connection string, any attempt to communicate with Azure services fail because they expect an account name which is actually embedded in the service endpoints. It seems that this method always uses the regular, non-SAS authentication scheme.

Using `storage.NewAccountSASClient` with the SAS token converted into `url.Values` and the appropriate storage account name also doesn't work. This time, every operation on the container returns 404 and ResourceNotFound. Doing `httputil.DumpRequest` on the request generated by the library I can see that the SAS token is never appended to the resource URL and there is no `Authorization` header.

I am currently using https://github.com/Azure/azure-storage-blob-go and it works fine for blobs, but doesn't support queues.

**Comment by joshgav** [comment]
cc @seguler

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v12.2.0-beta.  Thanks for reporting this issue.
