### ISSUE TITLE
services/ and profiles/ not showing up in godoc

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#899]
see e.g. https://godoc.org/github.com/Azure/azure-sdk-for-go/services

expected: services/ and profiles/ show up there.

**Comment by jhendrixMSFT** [comment]
This is apparently a known issue with godoc not recursively scanning for all packages, see https://github.com/golang/gddo/issues/494 for more details.

**Comment by jhendrixMSFT** [comment]
For now the only option we have is to manually visit each package so it will get indexed (I did this for the advisor package, it's now indexed).

**Comment by jhendrixMSFT** [comment]
I should be able to write a tool to automate this.

**Comment by jhendrixMSFT** [comment]
Indexer tool added in v14.3.0.
