### ISSUE TITLE
Eliminate stdlib forks living at core/

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#90]
`core/` currently has `net/http` and `crypto/tls` vendored (with some changes we don't entirely know). We must watch out if we can make feature requests to golang about these and eventually get rid of those (nobody will vendor our entire repo like this) :smile:

**Comment by paulmey** [comment]
:+1:

**Comment by ahmetalpbalkan** [comment]
@paulmey can you dump here what you know about those (i.e. why we have them) it'd be nice to know where exactly we modified if we can.

**Comment by hopetobelievein** [comment]
t

**Comment by ahmetalpbalkan** [comment]
@hopetobelievein sure it will, thanks! Was that the only patch for vendoring `crypto/tls` package here?

Any ideas about `net/http`?

**Comment by hopetobelievein** [comment]
Yes, that is the only thing that changed, plus references to changed packages.
I've added <code>net/http</code> because it has references to <code>crypto/tls</code> in some places:
https://github.com/MSOpenTech/azure-sdk-for-go/blob/master/core/http/response.go
https://github.com/MSOpenTech/azure-sdk-for-go/blob/master/core/http/transport.go
So final code in <code>./management/http.go</code> uses changed <code>net/http</code> which uses patched <code>crypto/tls</code>

**Comment by ahmetalpbalkan** [comment]
@hopetobelievein thanks for clarifications. it took us some time in the past to dig deep and understand what's the diff'ed part.

**Comment by mvanotti** [comment]
Hi!

Is it possible to add the patch as a separate commit? That way the differences are more visible, and also it adds more context.

It would be: One commit with the changes of the original repo (to revert everything), and one commit adding the patch and some context.

**Comment by paulmey** [comment]
Well, that history is sorta gone. This project was passed around a bit before ending up here. From my own archeology, the tls package looks like go1.2: ([full diff](https://gist.github.com/paulmey/8fc5722f1bb825ddeac8))
```ShellSession
paulmey@paulmey-z800:~/src/tmp-golang$ git co go1.2
HEAD is now at 402d359... go1.2
paulmey@paulmey-z800:~/src/tmp-golang$ diff -rw ~/src/go/src/github.com/Azure/azure-sdk-for-go/core/tls/ src/pkg/crypto/tls/|diffstat
 common.go             |    1 -
 conn.go               |   31 +------------------------------
 handshake_messages.go |   11 -----------
 3 files changed, 1 insertion(+), 42 deletions(-)
```
The http package looks like go1.3:
```ShellSession
paulmey@paulmey-z800:~/src/tmp-golang$ git co go1.3
Previous HEAD position was 402d359... go1.2
HEAD is now at 1cdd48c... go1.3
paulmey@paulmey-z800:~/src/tmp-golang$ diff -rw ~/src/go/src/github.com/Azure/azure-sdk-for-go/core/http/ src/pkg/net/http/|diffstat 
 response.go       |    2 +-
 transport.go      |    2 +-
 transport_test.go |    2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)
```

Note that the only changes to the http package are to reference the modified tls package.

**Comment by ahmetalpbalkan** [comment]
Heads up go1.7 probably will ship with TLS renegotation support https://github.com/golang/go/issues/5742#issuecomment-214900065 and we confirmed that fix works with Azure Service Management REST APIs. So we'll finally have a way to fix forks of `crypto/tls` and `net/http`. 🎉

**Comment by colemickens** [comment]
Are we comfortable saying azure-sdk-for-go is only compatible with the very latest Go compiler/stdlib? (Not that I'm against removing unneeded code...)

**Comment by ahmetalpbalkan** [comment]
@colemickens well first of all we expect all users to use vendoring, they always can go back. second is, this is `management/**` packages only. so ARM users won't get broken with this.

**Comment by paulmey** [comment]
:+1:  very much in favor of dropping /core/

**Comment by ahmetalpbalkan** [comment]
🔜  go1.7 will come out.
