### ISSUE TITLE
[storage] integrate new storage lib into SDK

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#903]
https://github.com/Azure/azure-storage-blob-go is the first of several new libs for Storage. We proposed vendoring in that lib and exposing it under `services/storage` for consistency with other libs.

We also will need to gradually deprecate the existing `storage/` package.

**Comment by joshgav** [comment]
cc @JeffreyRichter @seguler

**Comment by jhendrixMSFT** [comment]
Closing as we're not going to do this.
