### ISSUE TITLE
[Stream Analytics] Async polling for CreateOrReplace returns struct full of nils

### ISSUE THREAD

**Issue by thsutton** [Azure/azure-sdk-for-go#912]
Using `CreateOrReplace` to create a new Stream Analytics Job works fine and returns a `StreamingJob` struct full of the appropriate information.

Using `CreateOrReplace` to update a running Stream Analytics Job that requires asynchronous polling returns a `StreamingJob` struct full of `nil`s.

I don't entirely understand the way the autorest.go code is working but it seems  as though the async polling code might discard the `StreamingJob` JSON in the original request and return the JSON of the final polling request which cannot unmarshalled into a `StreamingJob` struct:

```
{"status":"Succeeded","error":null}
```

As a result I have to call `CreateOrReplace` and then, if it succeeds but leaves `res.ID == nil`, call `Get`. This works, but is quite unsatisfactory as APIs go.

**Comment by vladbarosan** [comment]
Hi @thsutton ,We changed the way we handle this situation in the next release so it might not be an issue.  @marstr  will have a look.

**Comment by marstr** [comment]
I can verify what @vladbarosan said. [Here](https://github.com/Azure/azure-rest-api-specs/blob/de2b9ea0a57423477d86a0ebfd78f88de109a00a/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/2016-03-01/streamingjobs.json#L140) you can see that StreamAnalytics/StreamingJob/CreateOrReplace is annotated as a Long Running Operation (LRO). @jhendrixMSFT has been leading the charge on updating the way that we generate code to call Azure LROs. Once #916 is merged, you'll be able to see the new pattern, which should fix this issue.

**Comment by joshgav** [comment]
hi @thsutton we've addressed this in version 12, can you check if that works for you? thank you!

**Comment by thsutton** [comment]
The new approach works great for me. Thanks!
