### ISSUE TITLE
App Service information

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-sdk-for-go#914]
Hi

I'm wondering if the SDK covers REST endpoints like https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/get   (ie just get information about running services as opposed to create/delete  services etc).

I had a quick look around but couldn't see where it was covered.

Cheers

Ken

**Comment by jhendrixMSFT** [comment]
Hello Ken!  The app service plans APIs are part of the web package, please take a look here.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2016-09-01/web/appserviceplans.go

**Comment by jhendrixMSFT** [comment]
I'm going to close this as this has been answered, please re-open if you have further questions.
