### ISSUE TITLE
Implement missing service principal operations in graphrbac

### ISSUE THREAD

**Issue by twendt** [Azure/azure-sdk-for-go#9216]
### Feature Request

Currently there is only a method to list the owners of a service principal in graphrbac, but no methods to add or remove owners.

It would be great if the same methods would be available as they are for applications.

I would also be great to have a possibility to configure the "User and Groups" assignments of the service principal.

**Comment by xinyi-joffre** [comment]
I can take a look at adding these to the specs for graphrbac here: https://github.com/Azure/azure-rest-api-specs as a first step.

Our team is also blocked on terraform-providers/terraform-provider-azuread#199

**Comment by xinyi-joffre** [comment]
I made a PR here: Azure/azure-rest-api-specs#12081

**Comment by xinyi-joffre** [comment]
The PR was merged to the azure-rest-api-specs repo 10 days ago. Is there anything I need to do to trigger generating the sdk update for graphrbac?

**Comment by twendt** [comment]
There was a new major release today, but the change is not included.

**Comment by ArcturusZhang** [comment]
Hi @xinyi-joffre could you please open a release request on this RP so that we could carry your changes in the next release of the SDK?

**Comment by FernandoMiguel** [comment]
is there any update on this new release with the new code ?

**Comment by lirenhe** [comment]
Data plane package, @RickWinter could you help to check?

**Comment by lirenhe** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
