### ISSUE TITLE
DNS 2017-09-01 API with CAA support

### ISSUE THREAD

**Issue by elyscape** [Azure/azure-sdk-for-go#922]
The Azure DNS API now supports CAA records with version 2017-09-01 (see Swagger PR at Azure/azure-rest-api-specs#1835). As mentioned [in a comment], that has not been brought over to the Go SDK, which currently [only supports up to 2016-04-01][current].

[in a comment]: https://github.com/Azure/azure-rest-api-specs/pull/1835#issuecomment-353475083
[current]: https://github.com/Azure/azure-sdk-for-go/tree/v12.0.0-beta/services/dns/mgmt

**Comment by vladbarosan** [comment]
@elyscape  we are targeting to release v12.1 . We will try to include the new DNS API version in this release.

**Comment by vladbarosan** [comment]
Candidate PR for  12.1 #923

**Comment by vladbarosan** [comment]
@elyscape  we just released [v12.1-beta](https://github.com/Azure/azure-sdk-for-go/releases/tag/v12.1.0-beta)  which contains the new DNS API version.

**Comment by elyscape** [comment]
Fantastic. Thanks for your help!
