### ISSUE TITLE
Duplicate calls to ResponseInspector

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-sdk-for-go#9221]
### Bug Report

I'm following the example "Writing Custom Request/Response Inspectors" here: https://github.com/Azure/azure-sdk-for-go#writing-custom-requestresponse-inspectors

Want: inspector is called once.
Got: inspector is called twice with the same response.

------

Looks like autorest already calls the inspectors, but then SDK calls then again.

~Full repro go project is here: https://github.com/ppanyukov/AzureDuplicateResponder~
Full repro go project is here: https://github.com/ppanyukov/azure-sdk-for-go-issues/tree/master/issues/duplicate-response-inspector-call

-----

EDIT: I moved the repro project to new location

**Comment by ArcturusZhang** [comment]
Hi @ppanyukov thanks for this issue!

Hi @jhendrixMSFT could you have a look at this?

**Comment by feiyushi** [comment]
> Hi @ppanyukov thanks for this issue!
> 
> Hi @jhendrixMSFT could you have a look at this?

Any updates? thx

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT could you please have a look at this issue?

**Comment by jhendrixMSFT** [comment]
The response inspector is called from `client.Do` and the responder method in the generated code.  Will need to update the code generator to remove the extra call to `c.ByInspecting()`.

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang can you please make this fix?  Should be somewhere in MethodGo.cs.

**Comment by ArcturusZhang** [comment]
PR opened [here] https://github.com/Azure/autorest.go/pull/413, please have a look @jhendrixMSFT thanks!

**Comment by ArcturusZhang** [comment]
This should have been resolved and go SDK will fetch that change in the next major version.
