### ISSUE TITLE
[v12.0.0] Idiomatic way of using futures

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#927]
Hello!
I'm currently looking at working with futures and I want to know the idiomatic way to get the value from one once the long-running operation completed.

So I'm doing some sort of `CreateOrUpdate` (this can be any long-running operation that returns a future):

```go
future, err := someClient.CreateOrUpdate(
		ctx,
		properties...
		})

// how do I properly use result?
```

Now there's a `.WaitForCompletion` function on `future`, so I assume I can do something like:

```go
	err = future.WaitForCompletion(ctx, someClient.Client)
	if err != nil {
		log.Fatalf("error in getting the result: %v", err)
	}

	actualObject, err := future.Result(someClient)
	if err != nil {
		log.Fatalf("cannot create object: %v", err)
	}
```

Is this the correct way to do it?

Thanks,
Radu M

**Comment by sptramer** [comment]
@marstr Very interested in this as well since I need to write the documentation on idiomatic `Future` use. If anyone on the team (or the CDAs) are interested in helping by giving some deeper API detail or common patterns for Go, I'd appreciate it. Outside of that I'm assuming that standard usage models for futures/promises apply.

**Comment by radu-matei** [comment]
I actually tried the above way a couple of times and it seems to work - waiting to make sure this is the intended way of use.

Thanks,
Radu M

**Comment by jhendrixMSFT** [comment]
@radu-matei your understanding is correct, we just haven't yet updated our samples with this new functionality.  For completeness I would also like to point out that ```WaitForCompletion()``` is just a default implementation we provide; everything it uses is publicly exported so people can roll their own polling loop if this one doesn't meet their requirements.

**Comment by jhendrixMSFT** [comment]
Closing as this has been answered, please re-open if you have further questions.
