### ISSUE TITLE
DeploymentsClient.Validate builds invalid HTTP request

### ISSUE THREAD

**Issue by StiviiK** [Azure/azure-sdk-for-go#9283]
### Bug Report
- import path of the package in question,
`github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/resources`
- SDK version 
`2a3fd68`
- output of `go version`
`go version go1.14.2 darwin/amd64`

- What happened?
Trying to validate an ARM template with `DeploymentsClient.Validate` method fails with the code Bad Request, after fiddling around with an HTTP Proxy it turns out the request is slightly wrong.
The error which I receive is the following:
```
{
   "error":{
      "code":"InvalidRequestContent",
      "message":"The request content was invalid and could not be deserialized: 'Error converting value \"https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#\" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 1313.'."
   }
}
```
- What did you expect or want to happen?
The deployment to return a code 200 OK, which it does if you fix the JSON body (see attached files below)
- How can we reproduce it?
[Template.json](https://hastebin.com/cimorubacu.json)(hastebin)
[Parameters.json](https://hastebin.com/jiwinafiqu.json)(hastebin)
[Working HTTP request](https://hastebin.com/esazoqepih.http)(hastebin)   
[Not working HTTP request](https://hastebin.com/iqapicutob.http)(hastebin) which the method 
call produces.
The difference between the two request bodies is that I removed on the non-working body the Lines `95,96,97` and `134`

- The files also have been uploaded to GitHub:
[parameters.json.txt](https://github.com/Azure/azure-sdk-for-go/files/4626915/parameters.json.txt)
[template.json.txt](https://github.com/Azure/azure-sdk-for-go/files/4626916/template.json.txt)
[working.request.txt](https://github.com/Azure/azure-sdk-for-go/files/4626928/working.request.txt)
[not_working.request.txt](https://github.com/Azure/azure-sdk-for-go/files/4626929/not_working.request.txt)

- Anything we should know about your environment.
Whole Project: https://github.com/whiteducksoftware/azure-arm-action
The method call in question can be found here: https://github.com/whiteducksoftware/azure-arm-action/blob/master/pkg/azure/azure.go#L124
I am parsing the JSON the following way: https://github.com/whiteducksoftware/azure-arm-action/blob/master/pkg/util/util.go#L17

**Comment by ArcturusZhang** [comment]
Hi @StiviiK thanks for this issue.
Is it too elementary to ask that how to check the request in hastebin? When I open it, i just see an empty web page.

**Comment by StiviiK** [comment]
>When I open it, i just see an empty web page.    

Oh that a weird issue, I have attached you the required files as an TXT to this comment:
[parameters.json.txt](https://github.com/Azure/azure-sdk-for-go/files/4626915/parameters.json.txt)
[template.json.txt](https://github.com/Azure/azure-sdk-for-go/files/4626916/template.json.txt)
[working.request.txt](https://github.com/Azure/azure-sdk-for-go/files/4626928/working.request.txt)
[not_working.request.txt](https://github.com/Azure/azure-sdk-for-go/files/4626929/not_working.request.txt)

**Comment by ArcturusZhang** [comment]
I believe the problem should be your `parameters.json` file.
[Here](https://github.com/whiteducksoftware/azure-arm-action/blob/4db3f32c273ef2cb3a52ab23ae334ba56113e919/pkg/github/options.go#L70) you parsed the parameters using the function `util.ReadJSON`, therefore using the input you provided here:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "containerName": {
            "value": "github-action"
        },
        "location": {
            "value": "westeurope"
        },
        "imageType": {
            "value": "Public"
        },
        "imageName": {
            "value": "whiteduck/sample-mvc"
        },
        "osType": {
            "value": "Linux"
        },
        "numberCpuCores": {
            "value": "1"
        },
        "memory": {
            "value": "0.5"
        },
        "restartPolicy": {
            "value": "OnFailure"
        },
        "ipAddressType": {
            "value": "Public"
        },
        "ports": {
            "value": [
                {
                    "port": "8080",
                    "protocol": "TCP"
                }
            ]
        }
    }
}
```
There will be a JSON object with three entries `$schema`, `currentVersion` and `parameters` assigned to the `parameters` attribute in the deployment. 
Actually, if you change the `paramter.json` to something like this:
```
{
    "containerName": {
        "value": "github-action"
    },
    "location": {
        "value": "westeurope"
    },
    "imageType": {
        "value": "Public"
    },
    "imageName": {
        "value": "whiteduck/sample-mvc"
    },
    "osType": {
        "value": "Linux"
    },
    "numberCpuCores": {
        "value": "1"
    },
    "memory": {
        "value": "0.5"
    },
    "restartPolicy": {
        "value": "OnFailure"
    },
    "ipAddressType": {
        "value": "Public"
    },
    "ports": {
        "value": [
            {
                "port": "8080",
                "protocol": "TCP"
            }
        ]
    }
}
```
This issue should be resolved. Could you please have a try?

**Comment by StiviiK** [comment]
Ah I see, that makes sense. Thanks for pointing that out!
I have fixed the Issue now by checking if its wrapped, [here's](https://github.com/whiteducksoftware/azure-arm-action/commit/41247cc58f2c474db59563e5595d2e535b39faa7) the commit if anyone is interested.
