### ISSUE TITLE
Organization of profile versions in service paths

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-sdk-for-go#932]
Open question for discussion about the location of profile versions in service paths. Currently they are organized as `service/SERVICE_NAME/[mgmt|client]/PROFILE/SERVICE_NAME` but this has a couple of failings:

1. It repeats `SERVICE_NAME`, which is a poor naming convention
2. It disconnects the toplevel `service` directory from the `PROFILE`, when profiles exist specifically to denote compatibility _between services_ - this obscures the purpose of profiles from the user
3. It makes it easy to typo, misimport, etc. by including the profile later in the inclusion path

For the next version, I'd like to suggest rethinking this - maybe reorganizing the path to instead be `service/PROFILE/SERVICE_NAME/[mgmt|client]`?

**Comment by joshgav** [comment]
@sptramer what you've named `PROFILE` in `services/SERVICE_NAME/[mgmt|client]/PROFILE/SERVICE_NAME` is in fact an API version not related to profiles; profiles are instead accessed via the [`profiles/`](https://github.com/Azure/azure-sdk-for-go/tree/master/profiles) path. For example, in `profiles/PROFILE/SERVICE_NAME/...` PROFILE *does* refer to a *profile* version.

This pattern is more correct (though still not exact):
`services/SERVICE_NAME/[SERVICE_SUBNAME/]SERVICE_VERSION/[SERVICE_NAME|SERVICE_SUBNAME]`

For example:
* services/cognitiveservices/luis/v2.0/runtime
* services/cognitiveservices/mgmt/2017-04-18/cognitiveservices
* services/cognitiveservices/v1.0/face
* services/cognitiveservices/v2.0/textanalytics

@sptramer:

> It repeats SERVICE_NAME, which is a poor naming convention

This is to provide a more intuitive package name when users directly import via e.g. `import github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute`.

Please keep sharing feedback on API versions and profiles! Let's make the experience better.

cc @marstr @devigned

**Comment by sptramer** [comment]
I was under the impression that profile versions and service versions were roughly identical - if a service had a specific version `V`, then it would be guaranteed to work with profile `V` and no others. Are profiles taken as snapshots at specific timeframes of guaranteed-interoperable versions, and a new version release for a service generates a new profile?

**Comment by joshgav** [comment]
Hi @sptramer - you've likely figured this out by now :), but the version numbers (dates) for profiles don't correlate or correspond with version numbers (dates) for APIs. They both just happen to use YYYY-MM-DD strings for versions; any overlap is coincidental. If you still have questions feel free to reopen this or reach out directly. Thanks!
