### ISSUE TITLE
kusto.DatabasesClient#Get unmarshal error: ReadWriteDatabaseProperties.isFollowed

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-sdk-for-go#9339]
### Bug Report

- import path: `.../services/kusto/mgmt/2020-02-15/kusto/databases`
- go dep: github.com/Azure/azure-sdk-for-go v41.2.0+incompatible
- output of `go version`: go version go1.13.8 darwin/amd64

Following error occured while using the Kusto DatabasesClient:
`
kusto.DatabasesClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal bool into Go struct field ReadWriteDatabaseProperties.isFollowed of type string' JSON = '{"id":"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.Kusto/Clusters/xxxxxx/Databases/xxxxxxx","name":"xxxxxxx/xxxxxxx","type":"Microsoft.Kusto/Clusters/Databases","etag":"\"\"","location":"West Europe","kind":"ReadWrite","tags":{"Environment":"testing"},"properties":{"isFollowed":false,"softDeletePeriodInDays":30,"softDeletePeriod":"P30D","hotCachePeriodInDays":10,"hotCachePeriod":"P10D","statistics":{"size":0.0},"provisioningState":"Succeeded"}}'
`
- What happened?
JSON unmarshall error
- What did you expect or want to happen?
No unmarshalling error
- How can we reproduce it?
Reading DB options using  DatabasesClient#Get having a database of type ReadWrite

**Comment by ArcturusZhang** [comment]
Closing this issue in favor of the [spec issue](https://github.com/Azure/azure-rest-api-specs/issues/9450)
