### ISSUE TITLE
Does SQL server support VirtualNetworkRulesClient?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-go#9340]
### Service Package Request

MySQL has VirtualNetworkRulesClient in https://github.com/Azure/azure-sdk-for-go/blob/master/services/mysql/mgmt/2020-01-01/mysql/virtualnetworkrules.go.
Does SQL server have similar client to create/update virtual network rules for SQL server?

**Comment by ArcturusZhang** [comment]
Hi @bingosummer thanks for this issue!

This should be what you are finding: https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/v3.0/sql/virtualnetworkrules.go
v3.0 of `sql` is a super set of all other api-versions

**Comment by alan-marcinkowski** [comment]
The mentioned version has been removed from the 67 line. Sadly, the portal itself is still using a preview version of the virtual network management for SQL Server from 5 ... yes, that's right ... 5 years ago. Why can't this be rolled in somewhere?
