### ISSUE TITLE
dns.RecordSetsClient has unsupported 2016-04-01 api-version

### ISSUE THREAD

**Issue by kopiczko** [Azure/azure-sdk-for-go#935]
I encounter following error:

```
dns.RecordSetsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2016-04-01' is invalid. The supported versions are '2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

It was working a few weeks ago. I run it in west europe region.

**Comment by kopiczko** [comment]
I also tried "github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2017-09-01/dns", but version `2017-09-01` is also unsupported.

```
dns.RecordSetsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2017-09-01' is invalid. The supported versions are '2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

What happened? Why versions can be dropped like that? Why `2017-*` version was dropped when `2013-*` versions exist?

**Comment by kopiczko** [comment]
It started to work out of the sudden. Was it some API outage?

**Comment by vladbarosan** [comment]
Hi @kopiczko most likely there was an issue on the service/ARM side since the returned api versions in your error are not even valid DNS API versions.  

We will follow up with the service team to see what might has caused this, but please reopen this issue if you encounter this issue again.

**Comment by TheoBrigitte** [comment]
Just came across this issue again today
`dns.RecordSetsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2017-09-01' is invalid. The supported versions are '2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."`

**Comment by vladbarosan** [comment]
@kopiczko can you provide the following details : 
1. Have you noticed this only in west europe ?
2. Did you see the issue only for the 2016-04-01 api version of DNS ?
3. Also just for reference, what SDK version are you using ?

**Comment by TheoBrigitte** [comment]
1. I do no have a way to easily test this in a different region
2. api version `2017-09-01` gave the exact same error
3. currently using SDK version `v12.1.0-beta`
4. This keeps happening, I saw the error today again at `18-03-29 13:13:43`, `18-03-29 13:34:24`, `18-03-29 14:58:41` and `18-03-29 15:03:56` (UTC time)

During the same time, a similar request succeed from a different environment. Something must be wrong on my side regarding `dns.RecordSetsClient.Get` arguments but also the API response seems does not seems right here.

**Comment by TheoBrigitte** [comment]
Ok this was due to passing an empty `resourceGroupName` argument when calling `RecordSetsClient.Get()`

**Comment by TheoBrigitte** [comment]
Here is how I reproduced it https://gist.github.com/TheoBrigitte/37bb318d0b6ad40f476ec33e6c755356

**Comment by vladbarosan** [comment]
the extra checks are present in `v18`
