### ISSUE TITLE
Connection String not returned 

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-go#9382]
### Bug Report

The Go SDK seems to be doing different things when it comes to listing connection strings depending on whether it's a SQL or mongoDB account.

`ListConnectionStrings` is called for mongoDB:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/cosmos-db/mongodb/client.go#L71

`DocumentDB` client.go does not have this implemented:

https://github.com/Azure/azure-sdk-for-go/blob/master/services/cosmos-db/mgmt/2020-03-01/documentdb/client.go

Why is that?
The portal shows the connection strings for all account types. This feels like a bug or oversight.

**Comment by ArcturusZhang** [comment]
Hi @davidobrien1985 thanks for this issue!
Actually it is defined here: https://github.com/Azure/azure-sdk-for-go/blob/ac906323d9febf3349e9fd1e1e0adc75229237fa/services/cosmos-db/mgmt/2020-03-01/documentdb/databaseaccounts.go#L748

And the `ListConectionStrings` function in https://github.com/Azure/azure-sdk-for-go/blob/master/services/cosmos-db/mongodb/client.go#L71 is also defined in a file with same name but different api-version: https://github.com/Azure/azure-sdk-for-go/blob/ac906323d9febf3349e9fd1e1e0adc75229237fa/services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go#L4281

**Comment by davidobrien1985** [comment]
@ArcturusZhang okay, what do you make of the comment here from terraform? https://github.com/terraform-providers/terraform-provider-azurerm/issues/6939

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang okay, what do you make of the comment here from terraform? [terraform-providers/terraform-provider-azurerm#6939](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6939)

Well I do not have much context about the service itself. But the newer api-version does support listing of connection strings (based on the code).

I assume you should encounter this issue in terraform, could you please provide some more information for us to reproduce this? Based on my understanding, in your use case, the list api returns nothing. And we need more information to find the root cause.

**Comment by davidobrien1985** [comment]
@ArcturusZhang turns out, it works now. Not sure why it wasn't working before. I asked Terraform to update their documentation.
