### ISSUE TITLE
Azure blob storage equivalent to S3 website redirect

### ISSUE THREAD

**Issue by meirf** [Azure/azure-sdk-for-go#939]
S3 has its own defined metadata for redirects: `x-amz-website-redirect-location` ([WebsiteRedirectLocation][1]).
But I don't see anything equivalent for [Azure blob storage][2]. Is there any first class support for this or should I should use a custom key in blob metadata?

  [1]: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#PutObjectInput.SetWebsiteRedirectLocation
  [2]: https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Blob

**Comment by joshgav** [comment]
@seguler @JeffreyRichter can you help?

@meirf note that there's a new Storage lib available at https://github.com/Azure/azure-storage-blob-go, but I don't know if that would help you.
