### ISSUE TITLE
uuid.NewV1() new Satori implementation

### ISSUE THREAD

**Issue by SoufienMIMS** [Azure/azure-sdk-for-go#940]
Hi guys!

I have this error when I'm generating a docker image using your azure-sdk-for-go : 

![image](https://user-images.githubusercontent.com/29100476/34539436-74b925ca-f09e-11e7-83bc-b002bade858c.png)

It is probably because the sdk used (github.com/satori/go.uuid) got an API updates.

**Comment by SoufienMIMS** [comment]
Here a screenshot of it last commit diff showing it : 
![image](https://user-images.githubusercontent.com/29100476/34539515-c7d7079a-f09e-11e7-8f8a-5fd928ec6a61.png)

Here the link I found for this : https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c

**Comment by joshgav** [comment]
Hi @SoufienMIMS, would you be able to try dep or another dependency manager? Then you can specify a specific version of satori/uuid, as we do here: https://github.com/Azure/azure-sdk-for-go/blob/934e2462aeb6e0c14186dcfeedd73a026d1b8eeb/Gopkg.toml#L46

**Comment by SoufienMIMS** [comment]
Hey @joshgav,

I finally used godep and used a vendoring system to avoid this issue for the moment to get able to build my project with the tag v1.0.0 of satori's uuid.

You'll find an opened issue here discussing about this last update here : https://github.com/satori/go.uuid/issues/66

Thanks for your help !

**Comment by joshgav** [comment]
Great, glad you were able to get unblocked, and thanks for the tip!
