### ISSUE TITLE
How to set `Accept-Language` header in the SDKs 

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-sdk-for-go#9409]
### Feature Request
We'd like to get localized response from RPs by setting `Accept-Language` header.
Is there a way to do that now in azure-sdk-for-go?
Thanks!

**Comment by feiyushi** [comment]
I guess it can be done in the same way as logging:
https://github.com/Azure/azure-sdk-for-go/blob/32160a3836db46d7b3b6751f2c5566570e348516/README.md#writing-custom-requestresponse-inspectors

**Comment by feiyushi** [comment]
`RequestInspector` is on the client level for all requests. Is there a way to set the header on the request level?

**Comment by ArcturusZhang** [comment]
Hi @feiyushi thanks for this issue!

> `RequestInspector` is on the client level for all requests. Is there a way to set the header on the request level within a client?

In my understanding, this should have the swagger supported beforehand. I happened to know one of them: the [migrate](https://github.com/Azure/azure-rest-api-specs/blob/087557f23f941df95cf10e188754b78b995cb1fd/specification/migrate/resource-manager/Microsoft.Migrate/stable/2019-10-01/migrate.json#L112). But most of the swagger do  not support this...

**Comment by lirenhe** [comment]
@feiyushi, does the workaround provided by @ArcturusZhang work for you?

**Comment by feiyushi** [comment]
Currently I just set it on the client level with `RequestInspector`.

**Comment by ArcturusZhang** [comment]
Since `RequestInspector` works, I would close this PR.
