### ISSUE TITLE
go get not working correctly

### ISSUE THREAD

**Issue by ritazh** [Azure/azure-sdk-for-go#945]
using `go get -u ` gives me this error:

```bash
github.com/Azure/azure-sdk-for-go/storage
azure-sdk-for-go/storage/table_batch.go:134:61: multiple-value uuid.NewV1() in single-value context
azure-sdk-for-go/storage/table_batch.go:141:48: multiple-value uuid.NewV1() in single-value context
```
Fixed it by running `dep ensure` inside of `github.com/Azure/azure-sdk-for-go` in `GOPATH`

**Comment by joshgav** [comment]
Thanks for reporting @ritazh! We're working on addressing this in #947 so will close this now.
