### ISSUE TITLE
address breaking change in satori/go.uuid

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#947]
Several issues have been opened: https://github.com/Azure/azure-sdk-for-go/issues/945, https://github.com/Azure/azure-sdk-for-go/issues/940, https://github.com/Azure/azure-sdk-for-go/pull/946.

Also: https://github.com/satori/go.uuid/issues/66

Let's get a fix in perhaps starting with #946 and release a new minor. Thanks!

@carolynvs do you have suggestions on how we can best shield users of our library from changes in [transitive dependencies](https://github.com/golang/dep/blob/master/docs/FAQ.md#what-is-a-direct-or-transitive-dependency)? Is dep's recommended practice for users to explicitly declare the dependency and version in their own Gopkg.toml file? Thank you!

**Comment by joshgav** [comment]
If you're looking for a workaround, see https://github.com/satori/go.uuid/issues/66#issuecomment-355382630.

**Comment by carolynvs** [comment]
@joshgav I thought go.uuid was a _direct_ dependency of the sdk, so a constraint should have worked. Testing now!

**Comment by carolynvs** [comment]
@joshgav It appears to me that anyone who is using dep to manage their dependencies should already be shielded from the breaking change in go.uuid. The sdk's Gopkg.toml specifies `1.1.0` for go.uuid. When someone uses dep on their project, and pulls in the sdk as a dependency, dep will enforce that constraint.

I looked at some of the other bugs and they appear to all be from non-dep consumers of the sdk.

Let me know if you've seen reports of anyone using dep to vendor the sdk who is having trouble!

**Comment by carolynvs** [comment]
To be clear, dep isn't built into the go toolchain yet. So even if a library has dep configuration files, when the consuming project doesn't use dep, running things like `go get` or `go build` won't pick up and use dep's configuration. The end-user needs to use dep as well.

**Comment by joshgav** [comment]
awesome, thanks @carolynvs!

**Comment by ritazh** [comment]
> running things like go get or go build won't pick up and use dep's configuration

yea completely agree with @carolynvs we just need to update the readme

**Comment by carolynvs** [comment]
Let me know if I can help clear up any other confusion about how dep works. I see #948 is doing some work that sounds like its to avoid certain behaviors in dep, but I'm not clear on what?

**Comment by vladbarosan** [comment]
@carolynvs that change you are mentioning is to help people using go get. The change was the only place where we were actually using the function with the breaking change so we switchted to another package for getting the UUID there so pretty much anyone using go get won't have problems with satori's breaking change with the go sdk.

**Comment by carolynvs** [comment]
Gotcha, thanks! 👍
