### ISSUE TITLE
Private Link: Cannot approve the private endpoint connection programatically

### ISSUE THREAD

**Issue by sidheshdivekar29** [Azure/azure-sdk-for-go#9484]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`.../services/network/mgmt/2019-06-01/network
- SDK version e.g. `master`, `latest`, `18.1.0`
master
  - Specify the exact commit if possible; one way to get this is the REVISION
github.com/Azure/azure-sdk-for-go v39.3.0+incompatible h1:xGwpf9r9uVRjcfLYlyB7WIcgOAHX6izsTrQApAH9ewo=
github.com/Azure/azure-sdk-for-go v39.3.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

I have created a private link service in one vnet and private end point in another under same resource group. When service is created I dont pass visibility & autoapproval parameters.
After end point is created I try to call UpdatePrivateEndpointConnection with created private endpoint in order to approve the private endpoint connection.

- What happened?

network.PrivateLinkServicesClient#UpdatePrivateEndpointConnection: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrivateEndpointConnectionCannotBeCreatedByServiceProvider" Message="Private endpoint connection /subscriptions/2de14016-6ebc-426e-848e-62a10837ce40/resourceGroups/TestPvtLnkRG15-6-sidhesh/providers/Microsoft.Network/privateLinkServices/TestPvtLnkService-6-sidhesh/privateEndpointConnections/TestPvtEndpt-6-sidhesh-pec on private link service /subscriptions/2de14016-6ebc-426e-848e-62a10837ce40/resourceGroups/TestPvtLnkRG15-6-sidhesh/providers/Microsoft.Network/privateLinkServices/TestPvtLnkService-6-sidhesh cannot be created by service provider. The consumer of your service must initiate the connection." Details=[]

- What did you expect or want to happen?
Should ideally approve the connection.
- How can we reproduce it?
Create 2 vnets across in same resource group, private link service and private endpoint.
Use private endpoint to as form private endpoint connection object and call UpdatePrivateEndpointConnection. Above error will be seen.
- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Hi @sidheshdivekar29 thanks for this issue!

But this is more of a question rather than a bug in SDK? I have tagged this issue therefore someone from the service could answer you this question.

**Comment by sidheshdivekar29** [comment]
I think its a bug where in its not working as expected. Lets wait for someone to take a look and confirm.

**Comment by lilyjma** [comment]
Hi @aznetsuppgithub, please take a look. Thanks!

**Comment by ivapplyr** [comment]
#Acknowledging Apologies for the delay on this. Is the customer still experiencing this issue ?

**Comment by sidheshdivekar29** [comment]
Yes, it will be good to get this fixed sooner. Is it a quick fix ?

**Comment by Zeev17** [comment]
Have you find a solution ?

**Comment by tadelesh** [comment]
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.
