### ISSUE TITLE
Clean up GUIDs

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#949]
As covered in #947, the Satori UUID library broke underneath us.

Depending on how that is resolved (e.g. he adds a v2.0 label,) we can remove the code commited in #948.

Be careful though, as removing this code too early, or in response to an inadequate resolution by Satori could cause trouble for people installing directly, or targeting a version of `github.com/satori/go.uuid` from before the breaking changes.

**Comment by jhendrixMSFT** [comment]
Long-term we need to remove our dependency on this package.
