### ISSUE TITLE
Using the azure-sdk-for-go to create a service principal without client id/secret

### ISSUE THREAD

**Issue by genevieve** [Azure/azure-sdk-for-go#950]
Is there a supported way of using the azure-sdk-for-go to create a service principal without already having a client id and secret? It is possible to login with the azure cli (and going to the browser with single sign-on), but it doesn't seem this is possible with the sdk.

**Comment by genevievelesperance** [comment]
It looks like it might be possible with this config: https://github.com/Azure/go-autorest/blob/cab8279ba5cd5e165c58201f798712f2ec0f49d6/autorest/adal/config.go#L47-L81

**Comment by joshgav** [comment]
related: https://github.com/Azure/azure-sdk-for-go/issues/596

@genevievelesperance you can use [Device Flow](https://tools.ietf.org/html/draft-ietf-oauth-device-flow-07) like the CLI as follows. You'll still need a client ID AFAIK but not a secret.

```go
var tenantID string
var clientID string
var subscriptionID string

oauthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantID)

func getDeviceToken() (adal.OAuthTokenProvider, error) {
	sender := &http.Client{}

	code, err := adal.InitiateDeviceAuth(
		sender,
		*oauthConfig,
		clientID,
		azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		log.Fatalf("%s: %v\n", "failed to initiate device auth", err)
	}

	fmt.Println(*code.Message)
	return adal.WaitForUserCompletion(sender, code)
}

token, _ := getDeviceToken()
groupsClient := resources.NewGroupsClient(subscriptionID)
groupsClient.Authorizer = autorest.NewBearerAuthorizer(token)
// use groupsClient
```

**Comment by genevievelesperance** [comment]
That's interesting. So in order to get a client id, we would have to configure an applications client and create a new application. To configure that applications client with a token, we would still require a client id. It doesn't seem possible to use the sdk without plenty of intervention in the azure console or cli.

**Comment by vladbarosan** [comment]
@genevievelesperance  you can try using the Azure CLI client id" `04b07795-8ddb-461a-bbee-02f9e1bf7b46` . 

I presume you have 2FA enabled. In that case, right now  you need a client id.

**Comment by genevievelesperance** [comment]
Okay, sounds good. Will give that a try.

**Comment by joshgav** [comment]
@genevievelesperance you can also use  `github.com/Azure/go-autorest/autorest/azure/auth.ClientSetup` ([docs](https://godoc.org/github.com/Azure/go-autorest/autorest/azure/auth)) wherever a BearerAuthorizer would work. That code is meant to handle resolving the location of the cached token from the CLI - it does rely on the user having logged on with the CLI at some point.

@mcardosos opened https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/84 to show how to use it.

For others reviewing this, we don't recommend re-using the client ID from the CLI directly.

---

It's also possible to create new service principals with the [graphrbac](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac) service and assign these principals permissions with the [ARM authorization](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization) service. We'll create some samples for that too, see https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/83 and https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/82.

**Comment by genevievelesperance** [comment]
The `GetClientSetup` expects a json file be created with all of the credentials that we would hope to get after having created the first service principal for a user: https://github.com/Azure/azure-sdk-for-go/blob/c1ff18326387fa67ccc6e1b17c76e65773684227/arm/README.md#use-an-authentication-file

**Comment by genevievelesperance** [comment]
Is it possible to skip the client id/client secret and still resolve the token after a user has logged in?

**Comment by genevievelesperance** [comment]
Having the cli and being logged in is an acceptable requirement, our blocker is that we require the user to have a service principal in order to create a service principal with the sdk entirely.

We were looking for `az login` by the user to be all we need in order to have a go library that can create the service principal without the cli.

**Comment by sepiroth887** [comment]
bump. Interested to use az login context as well but the example above isn't working :(

**Comment by vladbarosan** [comment]
@genevieve @sepiroth887 you can have a look at :
1. https://github.com/Azure/go-autorest/blob/master/autorest/azure/cli/token.go  and at
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/authentication/config.

Note that the access token will expire in 1 hour. To refresh the go app ( or something ) will need to call 
"az account get-access-token" in a sub process to refresh the access token.

I have to mention this is not recommended and the proper way right now to authenticate is to create a service principal and authenticate with it for non interactive access.

**Comment by vladbarosan** [comment]
@sepiroth887 , @genevieve will be closing this please reopen if there is anything else
