### ISSUE TITLE
the struct `ListResultIterator` does not work properly

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-sdk-for-go#9510]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources`
- SDK version:  `latest`

generally, when we want to list all results, we would use `listcomplete` function, which returns a `ListResultIterator` response. We would use following codes to iterate all results.

```
 for ite.NotDone() {
       v := ite.Value()
       ...
       ite.NextWithContext()
 }
```

But the implementation of `NotDone()` is not right. It checks the `value` is empty or nil. 

some service might returned following response: value is empty and nextLink is not empty
```
{"value":[],"nextLink":"https://management.azure.com/subscriptions/........"}
```

above is a real case in `microsoft.Resources` RP. And I have confirmed with the service team, they says 
```
It’s a little bit weird but this is by design, There could be a couple of reasons:
1) results might be filtered were for some reasons, e.g. permission.
2) there is no data in current partition, but still need to search the rest of partitions
```

we should take consider of this senario. Even then `value` is empty, if the nextlink is not empty, we still need to iterate the results.

**Comment by wsupernor** [comment]
We have created a script to reproduce this problem on demand - please see comments in https://github.com/Azure/autorest.go/pull/401

**Comment by andyzhangx** [comment]
anyone know how common is `Azure API returns empty values with non-empty nextLink`, it's corner case or common case?

**Comment by ArcturusZhang** [comment]
Hi @andyzhangx it might be quite common especially in the cases that there are quite a lot results and a filter, either a filter by the user or the cases that service relies on a filter to get the values.
At least in the tests I have done with the compute RP, they implement the LIST API using filters - here is only my guessings - they have a full paginated list of all kinds of resources, when they receive a request of list one of the type of resources, they would just return the full list after applying a filter on the current page. For example, the user is listing the images, and the current page contains all of the VMs, after applying the filter, the service just returns an empty list with a non-empty next link. I am not sure how it is implemented, but this is the hypophysis I made after I have done the test of listing a lot of images in a resource group that contains several VMs and a lot of images.
