### ISSUE TITLE
Stuttering for Container ServiceFuture in ContainerService package

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#953]
@jhendrixMSFT  after #941  I left one issue which happens in the container service . 

Because there is a type `ContainerService` in the `containerservice` package it triggers stuttering on the LRU's types `ContainerServiceCreateOrUpdateFuture` and `ContainerServiceDeleteFuture` . 

Was hesitant in removing it here since then on the imported package without an alias the types will be just `CreateOrUpdateFuture` and `DeleteFuture` which might be a little confusing. 

Thoughts if we should go that route ?

**Comment by jhendrixMSFT** [comment]
The type names would still be ```containerservice.CreateOrUpdateFuture``` yes?  Given that I think it would be ok to fix the stuttering.
