### ISSUE TITLE
General Availability of the Azure Go SDK Revisited

### ISSUE THREAD

**Issue by carlsoane** [Azure/azure-sdk-for-go#955]
Sorry to revisit a closed issue, but I still have a question about the planned GA of the Azure Go SDK. 

I went to https://github.com/Azure/azure-sdk-for-go/wiki/Road-Map link as recommended in https://github.com/Azure/azure-sdk-for-go/issues/804 but wasn't able to find any more information on the GA status of the SDK. Is there an update on when the SDK will be GA? Would it be correct to say that it is currently in Beta and a GA data has not been set?

**Comment by joshgav** [comment]
Hi @carlsoane - we're tracking our GA release in [the v14.0.0 milestone](https://github.com/Azure/azure-sdk-for-go/milestone/11) and currently aiming for Feb 12. We'll get the wiki updated, thank you for your patience!

**Comment by joshgav** [comment]
We're still on track with https://github.com/Azure/azure-sdk-for-go/milestone/11, so closing this now. Thanks!
