### ISSUE TITLE
Does function GetContainerReferenceFromSASURI really work?

### ISSUE THREAD

**Issue by rjtsdl** [Azure/azure-sdk-for-go#959]
I tried the way using SA name and key, it worked. I am trying to create a `containerRef` by using `GetContainerReferenceFromSASURI`. 

So far i have seen unexpected behavior. 
I generate a sasuri in the format like this
`https://<storageaccountname>.blob.core.windows.net/<containername>?se=2018-12-31&sp=rwdl&sv=2017-04-17&sr=c&sig=<theSignature>`

Unexpected:
1. I tried to call `containerRef.Exists`, it shows me the container doesn't exist. 
2. I tried to call 
```
        blob := containerRef.GetBlobReference(key)
	putBlobOpts := storage.PutBlobOptions{}
	err = blob.CreateBlockBlob(&putBlobOpts)
```
The error message is looks like 
`Put http://.blob./myabscontainer/example-etcd-regular2.backup_0000000000000001: dial tcp: lookup .blob.: no such host`
I don't expect my host is like **.blob.** !

**Comment by jhendrixMSFT** [comment]
Hello!  Are you sure your SAS query params are correct?  I tried this and it works for me using a SAS token generated via the Azure portal.

**Comment by jhendrixMSFT** [comment]
Also note that we're working on a new package for blob storage, see https://github.com/azure/azure-storage-blob-go.

**Comment by rjtsdl** [comment]
@jhendrixMSFT can you share the git-hash of azure-sdk-for-go you used?

**Comment by jhendrixMSFT** [comment]
This was v12.2.0-beta, the hash is eae258195456be76b2ec9ad2ee2ab63cdda365d9.

**Comment by jhendrixMSFT** [comment]
@rjtsdl Did you get this working?

**Comment by rjtsdl** [comment]
@jhendrixMSFT 

Didn't get time to try this yet. :(

How is the plan of having two storage repo? I guess https://github.com/azure/azure-storage-blob-go is one going forward, right?

Do you think it is time to move dependency from azure-sdk-for-go to the new repo? If the dependency only in storage.

**Comment by jhendrixMSFT** [comment]
You are correct  azure-storage-blob-go is the future for the blob storage SDK (it has much better SAS support too).  If you can migrate to this new package that would be best future-proofing.

**Comment by jhendrixMSFT** [comment]
Given that this is working plus moving to the new storage is the way to go I'm going to close this.
