### ISSUE TITLE
SignalR SDK: default value doesn’t exist in the SDK

### ISSUE THREAD

**Issue by tracypholmes** [Azure/azure-sdk-for-go#9619]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`"github.com/Azure/azure-sdk-for-go/services/signalr/mgmt/2018-10-01/signalr"`

- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.

```
~/Projects/workstuff/terraform-providers/terraform-provider-azurerm(master) » cat go.mod | egrep azure
module github.com/terraform-providers/terraform-provider-azurerm
	github.com/Azure/azure-sdk-for-go v42.1.0+incompatible
	github.com/hashicorp/go-azure-helpers v0.10.0
	github.com/terraform-providers/terraform-provider-azuread v0.9.0
```

- output of `go version`
`go version go1.14.3 linux/amd64`

- What happened?
Azure appears to have a default value for SignalR feature `EnableMessagingLogs`. However, this is not one of the currently available features (`EnableConnectivityLogs`, and `ServiceMode` are the only current choices). Without the feature block added and when using `terraform apply` followed by `terraform plan`, the following is received: 
```
resource "azurerm_signalr_service" "signalr" {
      ~ hostname                    = "tracy-signalr-sbox.service.signalr.net" -> (known after apply)
      ~ id                          = "/subscriptions/*****/resourceGroups/tracy-test/providers/Microsoft.SignalRService/SignalR/tracy-signalr-sbox" -> (known after apply)
      ~ ip_address                  = "*****" -> (known after apply)
        location                    = "eastus"
        name                        = "tracy-signalr-sbox"
      ~ primary_access_key          = (sensitive value)
      ~ primary_connection_string   = (sensitive value)
      ~ public_port                 = 443 -> (known after apply)
      ~ resource_group_name         = "tracy-test-2"
      ~ secondary_access_key        = (sensitive value)
      ~ secondary_connection_string = (sensitive value)
      ~ server_port                 = 443 -> (known after apply)
      - tags                        = {} -> null

        cors {
            allowed_origins = [
                "*",
            ]
        }

        features {
            flag  = "ServiceMode"
            value = "Serverless"
        }
        features {
            flag  = "EnableConnectivityLogs"
            value = "False"
        }
      - features {
          - flag  = "EnableMessagingLogs" -> null
          - value = "False" -> null
        }

        sku {
            capacity = 1
            name     = "Free_F1"
        }
    }
```

When adding in the feature block, we get the following:
```
Error: expected features.2.flag to be one of [EnableConnectivityLogs ServiceMode], got EnableMessagingLogs

  on example.tf line 12, in resource "azurerm_signalr_service" "signalr":
  12: resource "azurerm_signalr_service" "signalr" {
```

- What did you expect or want to happen?
The `EnableMessagingLogs` value to exist in the SDK constants.

- How can we reproduce it?
Please see the above.

- Anything we should know about your environment. 
Relevant issue on our side - https://github.com/terraform-providers/terraform-provider-azurerm/issues/7025

**Comment by ArcturusZhang** [comment]
Hi @tracypholmes thanks for this issue!

Unfortunately `signalr/2018-06-01` does not support this `EnableMessagingLogs` feature. 
But in the next major version v43.0.0, a new api-version 2020-05-01 is introduced for `signalr` and `EnableMessagingLogs` is supported in the new api-version. I am working on that in [this PR](https://github.com/Azure/azure-sdk-for-go/pull/9756)
