### ISSUE TITLE
Client names are not checked for uniqueness

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#962]
Currently we cannot generate a client for `RecoveryServicesBackup` since a couple of errors show up.

**Comment by vladbarosan** [comment]
The issue comes because client stuttering is handled separatley from enum and model types and uniqueness is handled.

**Comment by vladbarosan** [comment]
@jhendrixMSFT  it seems that https://github.com/Azure/azure-rest-api-specs/pull/2208 changed the names of the client so we might not encounter the issue in the specific case of Recovery Services.

**Comment by jhendrixMSFT** [comment]
This was introduced in https://github.com/Azure/autorest.go/pull/42.  We don't want to completely reinstate that behavior though as it introduces some poor client names.
