### ISSUE TITLE
Changing Azure VM Size

### ISSUE THREAD

**Issue by salmanbukhari** [Azure/azure-sdk-for-go#967]
I want to resize the VM. Is it possible using SDK? I tried deallocating the VM and calling CreateOrUpdate with a different size but I am getting exception 

> compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedResourceOperation" Message="The resource type 'virtualMachines' does not support this operation."

I am unable to find this anywhere in API/SDK documentation.

**Comment by vladbarosan** [comment]
@salmanbukhari can you please paste in a gist the code you are trying ? Also can you check if the new VM size is available in the region ?

**Comment by salmanbukhari** [comment]
I deallocated the machine tried to update the node using following code

> instanceType="Standard_F2"
> updatedObj := compute.VirtualMachine{
> 		VirtualMachineProperties: &compute.VirtualMachineProperties{
> 			HardwareProfile: &compute.HardwareProfile{
> 				VMSize: compute.VirtualMachineSizeTypes(instanceType),
> 			},
> 		},
> 	}
> 
> 	vmC , errC := vmClient.CreateOrUpdate(resourceGroup,vmName,updatedObj,nil)
> 	err = <-errC
> 	if(err != nil){
> 		fmt.Println(err)
> 		return 1, nil
> 	}

Current VM type is Standard_F1 and it is available in that US_EAST.

**Comment by vladbarosan** [comment]
@salmanbukhari instead of defining a new vm can you do a get on the one that already exists modify that object and then call CreateOrUpdate with that one  ?

I noticed you are using an older version of the sdk. We will be be releasing our GA with the target of February. You might want to look to upgrade. if you plan to do it before GA to current release ( v12 preview) beware of the issue #1000

**Comment by jhendrixMSFT** [comment]
Hello @salmanbukhari were you able to get this working?

**Comment by salmanbukhari** [comment]
@jhendrixMSFT Yes, I just checked it now. It worked. @vladbarosan thanks for the help.

**Comment by jhendrixMSFT** [comment]
Fantastic thanks for letting us know.  :)
