### ISSUE TITLE
Time Series Insights Access Policy - 401 Unauthorized

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#9696]
### Bug Report

- `github.com/Azure/azure-sdk-for-go/services/preview/timeseriesinsights/mgmt/2018-08-15-preview/timeseriesinsights`
- `v42.1.0`
- `go version go1.14 darwin/amd64`

I was looking at adding Terraform support for Time Series Insights Access Policy but any api call to that service just results in:

```
Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing."
```

**Comment by ArcturusZhang** [comment]
Hi @mbfrahry thanks for this issue!

By checking the code, I spotted nothing suspicious... Could you please provide some logs during sending the request?

**Comment by mbfrahry** [comment]
I've answered on the other issue. We can just consolidate on the other issue for now since it looks like they're both caused by the same thing
