### ISSUE TITLE
graphrbac: property 'samlToken' does not exist on type 'Microsoft.DirectoryServices.OptionalClaims'

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#9714]
### Bug Report

- `github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac`
- `v42.1.0`
- `go version go1.14.2 darwin/amd64`

I'm trying to include `OptionalClaims` when creating an Application. I can submit claims for `AccessToken` and `IDToken`, but attempting to set claims for `SamlToken` I get a 400 error:

```
The property 'samlToken' does not exist on type 'Microsoft.DirectoryServices.OptionalClaims'. Make sure to only use property names that are defined by the type.
```

SDK is using the object key `samlToken` but I believe this is supposed to be `saml2Token` as described at https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#optionalclaims-type

**Comment by ArcturusZhang** [comment]
Hi @manicminer thanks for this issue!

This should be another bug in `graphrbac`'s swagger... I have tagged this issue so that the service team would have a look and probably update their swagger and then the SDK would pick up that update accordingly.

**Comment by MarkDordoy** [comment]
Any idea when this bug will be fixed?

**Comment by MarkDordoy** [comment]
Any idea when this will be done?

**Comment by drem-darios** [comment]
Is there any update on this issue?
