### ISSUE TITLE
Azure Web Apps support for Go

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#972]
Work has begun here: https://github.com/Azure-App-Service/go/pull/1. We're coordinating with Web Apps team on putting in production.

**Comment by vladbarosan** [comment]
Related PR's
- Kudu script : https://github.com/projectkudu/KuduScript/pull/90
- Kudu container: https://github.com/Azure-App-Service/kudu/pull/43
- Go container: https://github.com/Azure-App-Service/go/pull/1

**Comment by vladbarosan** [comment]
To mention that:
1. After Kudu script is checked in -> we need to update the reference in the Kudu service
2. After kudu service is updated -> we need to update the version in the kudu service

**Comment by jhendrixMSFT** [comment]
Work is done, waiting to release.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT out of interest is this being exposed in ARM or via a Kudu SDK?

**Comment by vladbarosan** [comment]
@tombuildsstuff can you detail what you mean by this ? 
Creating them will be exposed through ARM and available in the SDK's .
For Kudu SDK I presume you are referring to the kudu rest api ? ( https://github.com/projectkudu/kudu/wiki/REST-API )

**Comment by tombuildsstuff** [comment]
@vladbarosan sorry, ignore that comment (I was thinking this was to do with a Kudu SDK rather than integration with Kudu) - looks like I mis-read this issue when replying the first time around :(

**Comment by vladbarosan** [comment]
this effort has went a different direction. will be closing this issue as stale
