### ISSUE TITLE
Suggestion: Move `management` to `services/asm`

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#976]
to drive consistency of package naming, and removing noise from the top level, we could move the `management` package into `services/asm`.

**Comment by jhendrixMSFT** [comment]
This is (obviously) a breaking change and would change the package name too.  While it's nice for us (the repo maintainers) I'm not convinced the annoyance to the few customers that use this is worth it.

**Comment by joshgav** [comment]
@jhendrixMSFT I think the top-level "management" and "storage" packages are misleading and they'd be more discoverable and consistent in the "services" directory.

We should also deprecate this library now (I'll open another issue) and I think it would make sense to deprecate and move at the same time.
