### ISSUE TITLE
add support for VM Instance Metadata

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#982]
Add types and methods for querying [Instance Metadata](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service).

**Comment by joshgav** [comment]
Hi @jhendrixMSFT - assigning this to you to help figure out considerations such as only running on Azure instances. I believe we're still blocked on a proper spec though.

**Comment by fiunchinho** [comment]
No news in nearly two years?

**Comment by deepanreddy87** [comment]
Is this Fixed yet ?

**Comment by lirenhe** [comment]
@joshgav, as there is still a gap for swagger, please follow up on https://github.com/Azure/azure-rest-api-specs/issues/4408
