### ISSUE TITLE
Support `passwordPolicies` for `User` entity of AAD Graph API

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#9851]
### Feature Request

Support listing, getting and setting the `passwordPolicies` attribute of the [User entity in the Azure AD Graph API](https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#user-entity).

Per the API documentation:

> Specifies password policies for the user. This value is an enumeration with one possible value being "DisableStrongPassword", which allows weaker passwords than the default policy to be specified. "DisablePasswordExpiration" can also be specified. The two may be specified together; for example: "DisablePasswordExpiration, DisableStrongPassword".

**Comment by lirenhe** [comment]
@manicminer, we don't release the SDK for msgraph API, for any feature ask, please create new issue in https://github.com/microsoftgraph/msgraph-metadata. thanks

**Comment by manicminer** [comment]
This feature request was for AAD Graph as per the issue title
