### ISSUE TITLE
Run CI with and without dep

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#990]
As discussed offline with @marstr , `go get` might cause problems with dependencies. So CI should run with and without `dep`. A cronjob would be healthy.

**Comment by jhendrixMSFT** [comment]
Can you please elaborate on the details from the offline discussion?

**Comment by mcardosos** [comment]
OK, so what we said...
Right now, some users are not using `dep`, and instead are relying on `go get`. What `go get` does is, it pulls the specified package/repo to the `src` folder in the GOPATH. It also pulls the package dependencies. This are also downloaded in the `src` folder, not in a `vendor` folder right next to the package we gogetted.
All this dependencies are pulled from their master branches, and `go get` does not really care about package manager like glide or dep. So when a user go gets the SDK, they will get the SDK master branch, and all dependencies on their master branches. This is not guaranteed to compile. If we `go get` the SDK today, we will get satori/uuid package, which has breaking changes and is not compatible with the current SDK.
To at least know where users that use `go get` could have problems, I propose we run CI just with `go get`, without the awesomeness that comes from dep.

**Comment by jhendrixMSFT** [comment]
I see your point, thanks for the explanation.  Can we start by adding this as a non-blocking task in CI?

**Comment by marstr** [comment]
Chatting during triage, we agree that this is adding alerting for a problem we've never had trouble getting visibility into.
