### ISSUE TITLE
KeyVault service is missing in 2017-03-09 profile

### ISSUE THREAD

**Issue by seyadava** [Azure/azure-sdk-for-go#991]
2017-03-09 profile does not have KeyVault service

**Comment by bganapa** [comment]
Azure stack supports the keyvault api version 2016-10-01. We need to include this SDK version part of the 2017-03-09 profile

**Comment by marstr** [comment]
@bganapa, ARM or data-plane?

**Comment by bganapa** [comment]
Thanks Martin for looking in to this . We need both, we support the version  2016-10-01 for both.
