### ISSUE TITLE
Ability to update AAD groups

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-sdk-for-go#9911]
### Feature Request

Currently the graphrbac package only enables creating and deleting groups. It would be great to also be able to update existing groups.

The API supports PATCH requests for groups, see https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/groups-operations#update-a-group--

**Comment by ArcturusZhang** [comment]
Hi @manicminer thanks for this issue!

This should be another issue that requires the graph rbac team to update their swagger....

**Comment by baywet** [comment]
@manicminer alternatively you could use the [Microsoft Graph Go SDK](https://github.com/microsoftgraph/msgraph-sdk-go) to do that.
