### ISSUE TITLE
Cannot unmarshal string into Go struct field ManagedServiceIdentity.type of type map[string]interface {}

### ISSUE THREAD

**Issue by gunzip** [Azure/azure-sdk-for-go#992]
I'm getting the following error using Terraform to create an App Service:

`Error making Read request on AzureRM App Service "agid-portal-test": web.AppsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field ManagedServiceIdentity.type of type map[string]interface {}' JSON 
`

It looks like the problem lies here:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2016-09-01/web/models.go#L8650

The SDK expects a map but the output of the identity field is a plain string:

```
{
     .....
    "kind": "app",
  },
  "identity": {
    "type": "SystemAssigned",
    "tenantId": "....",
    "principalId": "......"
  }
}

```

**Comment by jhendrixMSFT** [comment]
This is due to a bug in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2016-03-01/CommonDefinitions.json#L1038).  The type field is missing ```"type": "string"``` so the modeler incorrectly models this field as an object.

**Comment by gunzip** [comment]
Thank you, I've filed an issue there https://github.com/Azure/azure-rest-api-specs/issues/2344

**Comment by gunzip** [comment]
is there any way to monkey patch the specs in this repo ? it looks like the issue won't be fixed son in the specs and this prevents deploying app services that uses managed service identity

**Comment by jhendrixMSFT** [comment]
How are you consuming the SDK?  If you're checking in a vendored copy it might be easiest to change the type from map to string.  Also, if you are able to move to v14 this has been somewhat fixed in that version as the definition of this field has changed to the empty interface which shouldn't cause any unmarshaling failures.

**Comment by gunzip** [comment]
Thank you, I'm running it though Terraform -> [azurerm provider](https://www.terraform.io/docs/providers/azurerm/). Maybe they should update as well.

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff FYI

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.0.0
