### ISSUE TITLE
Feature request: Signalr client

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-sdk-for-go#9956]
### Feature Request

It would be great to have an official signalr client

**Comment by ArcturusZhang** [comment]
Hi @akshaybabloo thanks for this issue!

Are [these packages](https://github.com/Azure/azure-sdk-for-go/tree/master/services/signalr/mgmt) the ones you are looking for?

**Comment by akshaybabloo** [comment]
Isn't that used for management? I was thinking about using it on the web. For example to have a chat room like what you have with ASP.Net.

**Comment by ArcturusZhang** [comment]
> Isn't that used for management? I was thinking about using it on the web. For example to have a chat room like what you have with ASP.Net.

Indeed those are mgmt plane SDK. But I am afraid we do not have signalr data plane SDK right now...

Hi @jhendrixMSFT do you have any information about this?

**Comment by jhendrixMSFT** [comment]
@mayurid do you know if there are plans for signalr data-plane swagger?

**Comment by akshaybabloo** [comment]
Any update on this?
